### ISSUE TITLE
InputPhoneContact does not work

### ISSUE THREAD

**Issue by we1tkind** [LonamiWebs/Telethon#10]
It seems to import the contact phone number does not work.
```client.invoke(InputPhoneContact(0, '+79384225279', 'Reginald', 'Down'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/we1tkind/.virtualenvs/tg_bot/lib/python3.5/site-packages/telethon/telegram_client.py", line 139, in invoke
    self.sender.send(request)
  File "/Users/we1tkind/.virtualenvs/tg_bot/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 103, in send
    self.send_packet(writer.get_bytes(), request)
  File "/Users/we1tkind/.virtualenvs/tg_bot/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 154, in send_packet
    self.transport.send(cipher_writer.get_bytes())
  File "/Users/we1tkind/.virtualenvs/tg_bot/lib/python3.5/site-packages/telethon/network/tcp_transport.py", line 32, in send
    self.tcp_client.write(writer.get_bytes())
  File "/Users/we1tkind/.virtualenvs/tg_bot/lib/python3.5/site-packages/telethon/network/tcp_client.py", line 39, in write
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by XyLoNaMiyX** [comment]
Could you please provide details on how to replicate this?

The error, on the end, says "`BrokenPipeError: [Errno 32] Broken pipe`". So I'm afraid this is an issue with the connection itself, not related to invoking `InputPhoneContact`.

Anyway, `InputPhoneContact` under `telethon/tl/types/input_phone_contact.py` is a **type**, not a **request**. You're not supposed to invoke _types_!! Did you read the `README.rst`? If you have, then I should edit it to make it clearer.

**Comment by XyLoNaMiyX** [comment]
By the way, probably what you want to use is `GetContactsRequest` or similar. I think that importing a contact by their phone number is an old thing. Telegram's documentation is very poor and outdated (their [latest documented layer](https://core.telegram.org/schema) is 23, and we're on 57 as of now) for most requests, so I can't really help you. It's trial and error.

**Comment by we1tkind** [comment]
Thanks.
Yes, I read the readme file. I was inattentive, `README.rst` is ok(:
I need to import a list of phone numbers to the contacts list in the telegram. As I understand it, getContacts performs the reverse procedure.
I create a list of contacts
```python
contact = InputPhoneContact(0, '+79384225279', 'Reginald', 'Down')
contacts = [contact,]
```
and import a list of contacts to the Telegram
```python
client.invoke(ImportContactsRequest(contacts, True))
```
This is the correct sequence? (I have same error `broken pipe`)

**Comment by XyLoNaMiyX** [comment]
What do you mean by _import_? Sorry, Telegram is so confusing some times.
I think Telegram refers to _import_ as _adding new phone numbers to the Telegram's contact list_, not _retrieving those from my Telegram's contact list_. I know, it's confusing, read it slow (I hope I said it right!). But I guess that's what you want.

Yes, `GetContactsRequest` request returns a `Contacts` object with `contacts` and `users`, although I don't know what to put in the `GetContactsRequest` hash (if you do know what that hash is, I'd appreciate to hear).

To import contacts you need to use `ImportContactsRequest` as you said and provide it a list of `InputContact` (like `InputPhoneContact`), so yes, you're doing it right and in the right sequence.

I have followed your very same steps and managed to import a friend of mine with the following result:
```python3
>>> tg.invoke(ImportContactsRequest(contacts, True))
contacts.importedContacts#ad524315 imported:Vector<ImportedContact> retry_contacts:Vector<long> users:Vector<User> = contacts.ImportedContacts
```

It's weird that you managed to login and authorize, and this fails. Have you tried other options such as sending messages?

**Comment by we1tkind** [comment]
Thanks for your help.
Perhaps were network problems yesterday. Today it works.

**Comment by XyLoNaMiyX** [comment]
I'm glad it's fixed now @we1tkind. If you have any other issue or suggestion please let me know :)
