### ISSUE TITLE
PqReqRequest - The invoked method does not exist anymore or has never existed.

### ISSUE THREAD

**Issue by yankutmau** [LonamiWebs/Telethon#100]
Hi guys,
I'm trying to authorize my application using Telegram's guide: 
https://core.telegram.org/mtproto/auth_key
https://core.telegram.org/mtproto/samples-auth_key

The first step is to to send a req_pq to Telegram (ReqPqRequest in Telethon),
however this error is raised:

  ```
File "/home/yankut/Documents/telegram/app.py", line 87, in create_authorization_key
    resp = self.client.invoke(ReqPqRequest(rand_int))
  File "/home/yankut/Documents/telegram/ENVS/ENV3/lib/python3.5/site-packages/telethon/telegram_client.py", line 315, in invoke
    self.sender.receive(request, timeout, updates=updates)
  File "/home/yankut/Documents/telegram/ENVS/ENV3/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 109, in receive
    request, updates)
  File "/home/yankut/Documents/telegram/ENVS/ENV3/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 202, in _process_msg
    msg_id, sequence, reader, request)
  File "/home/yankut/Documents/telegram/ENVS/ENV3/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 352, in _handle_rpc_result
    raise error
telethon.errors.RPCError: (RPCError(...), 'The invoked method does not exist anymore or has never existed.')
```

**Comment by Lonami** [comment]
> I'm trying to authorize my application using Telegram's guide

What are your reasons for not authorizing Telethon via the built-in methods (a call to `.connect()` on the [`TelegramClient`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py))?

If the reasons are that the `TelegramClient` itself has a lot of clutter, unnecessary methods, I plan to clean it up in a near future. Otherwise let me know, because I like to know why my users do things the way they do :)

As for the error, the current [`authenticator`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/authenticator.py) does *not* make use of the generated TLObjects (types and functions, such as `req_pq`), it's built-in and hardcoded for the authorization process.

**Comment by yankutmau** [comment]
I do use connect, however Telegram requires authorizing your phone number for phone related functions such as:
ImportContactsRequest

To authorize you can use
`client.send_code_request(phone)`
then receive the code in the Telegram mobile/web client and input them in:
`client.sign_in(phone, code)`

However, there is an expiry for the session that is created and I cannot authenticate my phone every time.
That's why I'm trying to authorize myself programatically.

**Comment by Lonami** [comment]
> To authorize you can use
> `client.send_code_request(phone)`
> then receive the code in the Telegram mobile/web client and input them in:
> `client.sign_in(phone, code)`

Correct, that's how it's (usually) done.

> However, there is an expiry for the session that is created and I cannot authenticate my phone every time.
> That's why I'm trying to authorize myself programatically.

So you say your session **expires** after a while, right? Hmm, maybe Telethon itself could store the expire date to manually re-perform the authorization, so I'd be interested in knowing how you solve this problem!

As I mentioned, the steps for authorizing yourself to the Telegram servers are under the [`authenticator.py`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/authenticator.py) file, so feel free to take a look and modify or borrow code as you need to make it work.

**Comment by yankutmau** [comment]
I did not have it expire yet, however I did read in their API it does expire.
I'll take a look around, thanks! :)

**Comment by Lonami** [comment]
Perhaps you're talking about the `expires` member of the [`Config`](https://lonamiwebs.github.io/Telethon/constructors/config.html) result after invoking the [`GetConfigRequest`](https://lonamiwebs.github.io/Telethon/methods/help/get_config.html). If you run this:
```python
from telethon.tl.functions.help import GetConfigRequest
from datetime import datetime
print(client.invoke(GetConfigRequest()).expires - datetime.now())
```

This is what I got:
```
0:03:31.259669
```

So it's probably when the created authorization key expires if you haven't logged in with it within that time. Just a guess, but probably a very accurate one. Reopen if you have more questions and think it should remain open :p
