### ISSUE TITLE
Loses tags when sending larger MP3 files

### ISSUE THREAD

**Issue by strannik-j** [LonamiWebs/Telethon#1000]
Telethon loses tags when sending larger MP3 files. You can try to send [this](https://yadi.sk/d/43Vr9NY_sSiBYQ) file and make sure telegram doesn't recognize it as an mp3 file. However, if you send this file through a regular telegram client, the file is normally recognized with all its tags.

I tried "force_document=False", but the result is the same.

**Comment by Lonami** [comment]
How about installing `hachoir`?

**Comment by strannik-j** [comment]
Yes, it helped, but only partially. Tags are defined, but there is a problem with the encoding (UTF-16). Instead of the track name and artist I see 
```
?????  ??????????
```
 In a log there are Warnings:

```
[warn] Skip ID3v2 tag TDRC: 2017
[warn] Skip ID3v2 tag TXXX: TCOD: 0
[warn] Skip ID3v2 tag TSSE: Lavf55.19.100
[warn] Skip ID3v2 tag TXXX: TCDO: 72572109
[warn] [/id3v2/field[10]/content] String /id3v2/field[10]/content/mime has invalid BOM (b'im')!
[warn] [/id3v2/field[10]/content] [Autofix] Fix parser error: stop parser, add padding
```

**Comment by Lonami** [comment]
Well this isn't *quite* related with Telethon. The scope of the library is not reading `.mp3` files to find artist and such. You might want to report this to the `hachoir3` team (maybe? I don't know if development is ongoing). Or find alternative libraries for the task.

**Comment by strannik-j** [comment]
Okay, tnx
