### ISSUE TITLE
sqlite3 warning

### ISSUE THREAD

**Issue by vhdm** [LonamiWebs/Telethon#1003]
dear @Lonami  please help me

/usr/local/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py:179: UserWarning: The sqlite3 module is not available under this Python installation and no custom session instance was given; using MemorySession.
You will need to re-login every time unless you use another session storage
  'The sqlite3 module is not available under this '

**Comment by Lonami** [comment]
I believe the error is quite clear, and the documentation has more on this.
