### ISSUE TITLE
error while sending image file

### ISSUE THREAD

**Issue by rdbox** [LonamiWebs/Telethon#1008]
DON'T ASK QUESTIONS HERE.

This place is for issues with the library, so please make sure that:
1. The error is in the library's code, and not in your own.
2. You have already searched for your error on existing issues.
3. You are testing with upstream code (pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip).

If you have a question, ask in the official Telegram group https://t.me/TelethonChat or  https://stackoverflow.com. Enhancement ideas are currently welcome, too.

```
Traceback (most recent call last):
  File "botTelegram.py", line 13, in <module>
    client.send_file('zazjivalo', '1CrBX.png')
  File "C:\Python37\lib\site-packages\telethon\client\uploads.py", line 176, in send_file
    msg = self._get_response_message(request, self(request), entity)
  File "C:\Python37\lib\site-packages\telethon\client\users.py", line 38, in __call__
    future = self._sender.send(request, ordered=ordered)
  File "C:\Python37\lib\site-packages\telethon\network\mtprotosender.py", line 217, in send
    message = self.state.create_message(request)
  File "C:\Python37\lib\site-packages\telethon\network\mtprotostate.py", line 50, in create_message
    out=True  # Pre-convert the request into bytes
  File "C:\Python37\lib\site-packages\telethon\tl\core\tlmessage.py", line 52, in __init__
    body = GzipPacked.gzip_if_smaller(self.obj)
  File "C:\Python37\lib\site-packages\telethon\tl\core\gzippacked.py", line 21, in gzip_if_smaller
    data = bytes(request)
  File "C:\Python37\lib\site-packages\telethon\tl\functions\messages.py", line 3426, in __bytes__
    bytes(self.media),
  File "C:\Python37\lib\site-packages\telethon\tl\types\__init__.py", line 7391, in __bytes__
    bytes(self.file),
TypeError: cannot convert 'NoneType' object to bytes
```

``` python
# coding: utf8
from telethon import TelegramClient, sync

api_id = 123123
api_hash = '2947355a48fc4d064976bb551111111'

client = TelegramClient('session_name', api_id, api_hash)
client.start()

# client.send_message('user', 'Hello! Talking to you from Telethon')
client.send_file('user', 'image.png')
```

**Comment by rdbox** [comment]
I can not figure out which way to go
relative or absolute
My script is located on the path ```c:\Users\user\Desktop\botTelegram.py```
how to correctly write the path in ```client.send_file ();```

**Comment by Lonami** [comment]
Need version and more details. Can't reproduce the issue.

**Comment by rdbox** [comment]
@Lonami I last only installed the version yesterday via pip

```
➜  Desktop pip3 freeze
async-generator==1.10
bottle==0.12.13
pyaes==1.6.1
pyasn1==0.4.4
rsa==4.0
Telethon==1.2
Telethon-sync==1.1.1
```

**Comment by rdbox** [comment]
@Lonami 
what should I do ?

**Comment by Lonami** [comment]
You have both `Telethon-sync` and `Telethon`. That is not going to work properly.

**Comment by rdbox** [comment]
@Lonami but what should I leave? which variant ?

**Comment by rdbox** [comment]
if I remove the package Telethon-sync then I have an error
```ImportError: No module named telethon```

**Comment by Lonami** [comment]
You must have done something strange with your `pip` packages, **and this is not an issue with the Telethon library itself**, so you're not asking in the right place.
