### ISSUE TITLE
urgently need help total lock numbers

### ISSUE THREAD

**Issue by rdbox** [LonamiWebs/Telethon#1009]
I can not figure out what's wrong but I use your python module, I have all 10 numbers blocked after 10-20 minutes of use.
When I used ```TLSharp``` with him this was not, I spent 5 days testing and everything was fine.

Pay attention I did not send out spam, I did not send out many messages, I sent a single account from one telegram to ```Hello! Talking to you from Telethon```

And after that the script required authorization after there was a message that the number is blocked.

Maybe your code is doing something ??
I can not understand what's going on

```
  result = await future
telethon.errors.rpcerrorlist.PhoneNumberBannedError: The used phone number has been banned from Telegram and cannot be used anymore. Maybe check https://www.telegram.org/faq_spam
```

**Comment by Lonami** [comment]
Telegram decides the bans, not me. And it's obvious my library has been used by spammers, so sadly your accounts may be (incorrectly?) banned. See #824 for contact information.

**Comment by rdbox** [comment]
@Lonami  I did not understand it is necessary to roll back to the old version? or could you solve the problem in layers????
