### ISSUE TITLE
Add support for a separate connection when downloading/uploading files

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#102]
Should be very straightforward, simply creating a second `TelegramClient` instance with the same IP address, port, and **session** thanks to it being thread-safe ([`1860054`](https://github.com/LonamiWebs/Telethon/commit/1860054ec0e57ff40ce0acfbdc5d1b1437ab0578)) for it to be used only to work with files (although it can send any request).

On a separate issue, it would be nice to also have a `TelegramClient` only to receive updates so there would be no need for locks because they would effectively be different connections.

**Comment by Lonami** [comment]
The major rewrite done on commit [`88f87f6`](https://github.com/LonamiWebs/Telethon/commit/88f87f6de2adb136078eaff7ed577f234ad27e60) will enable to create more than a single [`TelegramBareClient`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_bare_client.py), while not having the useless ability to spawn updates thread or invoke on different DCs since that's not of use for simply invoking download requests, for instance.

**Comment by Lonami** [comment]
The example consisted on the following:
```python
AMOUNT = 50
subclient = client.create_new_connection()
barrier = Barrier(2)
entity = get_input_peer(client.get_dialogs(1)[1][0])


def subthread():
    for _ in range(AMOUNT):
        barrier.wait()
        subclient.invoke(SendMessageRequest(entity, 'hi'))
        sleep(1)
    subclient.disconnect()

thread = Thread(target=subthread, name='eh', daemon=True)
thread.start()


for _ in range(AMOUNT):
    barrier.wait()
    subclient.invoke(SendMessageRequest(entity, 'hi'))
    sleep(1)
client.disconnect()

thread.join()
```

It didn't crash, so I presume it works. Any feedback is appreciated.

**Comment by einali** [comment]
Dear Lonami

your sample has some problems!!
for long request invokes i get read operation exceeded!!

i increased timeout to 100 seconds and i got error again!
what is your opinion about this?


`AMOUNT = 50
subclient = client.create_new_connection()
barrier = Barrier(2)
entity = get_input_peer(client.get_dialogs(1)[1][0])


def subthread():
    for _ in range(AMOUNT):
        barrier.wait()
        subclient.invoke(GetDialogsRequest(...))
        subclient.invoke(GetHistoryRequest(...))

        sleep(1)
    subclient.disconnect()

thread = Thread(target=subthread, name='eh', daemon=True)
thread.start()


for _ in range(AMOUNT):
    barrier.wait()
    subclient.invoke(GetDialogsRequest(...))
    subclient.invoke(GetHistoryRequest(...))
    sleep(1)
client.disconnect()

thread.join()`

exception is : 
`File "/home/mehdi/ws/temp/Telethon/telethon/telegram_client.py", line 262, in invoke
    request, updates=updates
  File "/home/mehdi/ws/temp/Telethon/telethon/telegram_bare_client.py", line 231, in invoke
    self._sender.receive(request, updates=updates)
  File "/home/mehdi/ws/temp/Telethon/telethon/network/mtproto_sender.py", line 104, in receive
    seq, body = self.transport.receive(**kwargs)
  File "/home/mehdi/ws/temp/Telethon/telethon/network/tcp_transport.py", line 56, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/home/mehdi/ws/temp/Telethon/telethon/extensions/tcp_client.py", line 115, in read
    'The read operation exceeded the timeout.') from error
TimeoutError: The read operation exceeded the timeout.`
