### ISSUE TITLE
Session expires within a couple minutes without logging out

### ISSUE THREAD

**Issue by Shreevenkr99** [LonamiWebs/Telethon#1022]
I am trying to sign in with a new number altogether using simsms.org's api. I am able to sign in and start the program. however if i try to send a message or anything a few minutes later it asks for a number. I then did client.get_me() function call to see if i actually am signed in. under status it gives me an expires=datetime.utcfromtimestamp(1539231552)

the whole response is
By signing up for Telegram, you agree not to:

- Use our service to send spam or scam users.
- Promote violence on publicly viewable Telegram bots, groups or channels.
- Post pornographic content on publicly viewable Telegram bots, groups or channels.

We reserve the right to update these Terms of Service later.
User(
        access_hash=-1832879654755852574,
        verified=False,
        username=None,
        first_name='Dave',
        lang_code=None,
        restriction_reason=None,
        bot=False,
        bot_nochats=False,
        deleted=False,
        bot_chat_history=False,
        photo=None,
        phone='79773370945',
        contact=False,
        last_name=None,
        mutual_contact=False,
        bot_inline_placeholder=None,
        id=644540961,
        bot_info_version=None,
        min=False,
        is_self=True,
        status=UserStatusOnline(
                expires=datetime.utcfromtimestamp(1539231552)
        ),
        restricted=False,
        bot_inline_geo=False
)

```
client = TelegramClient("dave", api_id, api_hash)
client.connect()
# some code here to call for the phone number from the api
client.send_code_request(phone_number)
#some code here to get the sms with the code to sign up for telegram
client.sign_up(code = code,first_name= "Dave")
client.start()
me = client.get_me()
print(me.stringify())
```
Thats what i used. The problem is that it gives a response but after three minutes. i cant use the file

**Comment by Lonami** [comment]
Expires is inside your last seen status… You shouldn't use `sign_up` and `start`… Yeah ask in [@TelethonChat](https://t.me/telethonchat) at best.
