### ISSUE TITLE
Regression: get_entity('me') no longer works

### ISSUE THREAD

**Issue by gentoo-root** [LonamiWebs/Telethon#1024]
'me' and 'self' used to be special parameters to `get_entity()` that returned the current user (the same effect as `get_me()`). The following code used to work, however, it broke in some newer version, and now an exception is thrown:

```
from telethon import TelegramClient
client = TelegramClient('test', API_ID, API_HASH)
client.start()
client.get_entity('me')
```

_get_entity_from_string [still contains](https://github.com/LonamiWebs/Telethon/blob/e5fc9d8674c36c4bb91451145e94e58fb676f85d/telethon/client/users.py#L379) handling of 'me' and 'self', but [parse_username](https://github.com/LonamiWebs/Telethon/blob/e5fc9d8674c36c4bb91451145e94e58fb676f85d/telethon/utils.py#L651) returns None [here](https://github.com/LonamiWebs/Telethon/blob/e5fc9d8674c36c4bb91451145e94e58fb676f85d/telethon/client/users.py#L366) when called with 'me' as a parameter. I think the culprit is VALID_USERNAME_RE that doesn't include 'me' and 'self'.

Steps to reproduce: Run the code snippet above (substitute API_ID and API_HASH with real values).

Expected result: No exception is thrown; `get_entity('me')` returns the same as `get_me()`.

Actual result: An exception is thrown: `ValueError: Cannot find any entity corresponding to "me"`.

**Comment by Lonami** [comment]
It had been such a long time since I last got an actual *bug* report :-)
