### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in send file

### ISSUE THREAD

**Issue by aminhyper** [LonamiWebs/Telethon#1026]
Hello
I install telethon in ubuntu 16.04
I can connect with client and I can send message finely, but when i want to send a file, i  get this error:
TypeError: 'NoneType' object is not iterable
I execute send file method in windows7 and it was OK, but in ubuntu 16.04 i can not send file

**Comment by Lonami** [comment]
What version of the library is the Windows machine using? And what version in Ubuntu 16.04? Does the file exist?

**Comment by aminhyper** [comment]
Telethon version in windows : 0.19.1.6
Telethon version  in Ubuntu: 1.1.1
Yes the file path is : /root/b.py

**Comment by Lonami** [comment]
Both versions are out of date.

**Comment by aminhyper** [comment]
I had already said that my version telethon is 1.1.1,
In fact the version of telethon-sync is 1.1.1.(I've removed `telethon` and just installed `telethon-sync`).
Unfortunately, even though I've read the documentation, I still have trouble sending the file.
Should I make a change in telethon-sync codes? Or is this version generally unable to send the file?
the error that i get when send file:

> File "/usr/local/lib/python3.5/dist-packages/telethon/client/uploads.py", line 176, in send_file msg= self._get_response_message(request, self(request), entity)

> File "/usr/local/lib/python3.5/dist-packages/telethon/client/users.py", line 38, in __call__
    future = self._sender.send(request, ordered=ordered)

>  File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtprotosender.py", line 217, in send
    message = self.state.create_message(request)

> File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtprotostate.py", line 50, in create_message
    out=True  # Pre-convert the request into bytes

> File "/usr/local/lib/python3.5/dist-packages/telethon/tl/core/tlmessage.py", line 52, in __init__
    body = GzipPacked.gzip_if_smaller(self.obj)


> File "/usr/local/lib/python3.5/dist-packages/telethon/tl/core/gzippacked.py", line 21, in gzip_if_smaller
    data = bytes(request)

>  File "/usr/local/lib/python3.5/dist-packages/telethon/tl/functions/messages.py", line 3426, in __bytes__
    bytes(self.media),

> File "/usr/local/lib/python3.5/dist-packages/telethon/tl/types/__init__.py", line 7322, in __bytes__
    bytes(self.file),
TypeError: 'NoneType' object is not iterable

**Comment by Lonami** [comment]
Telethon-sync is no longer supported and it has known bugs.

**Comment by aminhyper** [comment]
Thank you for your answer

**Comment by aminhyper** [comment]
My reason for using `telethon-sync` it was that I want to use `telethon` and `flask` in my code.
I used of `telethon=0.19.1.6` and `flask` in my code, and the code works great, but the problem is that it can not send `streaming video` files.
Also, the use of the `progress_callback` does not affect.
Does  this version(`telethon=0.19.1.6` ) support The described features(`streaming video` and `progress_callback`  )?

**Comment by Lonami** [comment]
There are ways to use Flask and Telethon. There are also alternatives to Flask that use asyncio, see the docs, but stop bumping the thread. Use stackoverflow or the group for support.

**Comment by aminhyper** [comment]
Thank you so much for your answer
Also, for the great work you have done.
