### ISSUE TITLE
How to add user to super group

### ISSUE THREAD

**Issue by atabaki** [LonamiWebs/Telethon#103]
How can implement add members functionality in supergroups same as telegram desktop
Suppose i,m not the creator of that supergroup.
Using AddChatUserRequest leads to invalid_chat_id
Using InviteToChannelRequest need admin privillages

But as u can test, in telegram desktop you can join to one supergroup and add members without admin permission
What method must be used to achieve this functionality?

**Comment by Lonami** [comment]
You know those links which look like https://t.me/joinchat/AAAAAFFszQPyPEZ7wgxLtd (that's a non-existing example)? Well, the part after the `joinchat/` is the hash of the group. You can use [`ImportChatInviteRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/import_chat_invite.html) to join to such chat.

**Comment by atabaki** [comment]
No
Wee need to add another user not my own account
RequestImportChatInvite is for adding me to one chat (superGroup)
i need add you (for example) to super group with id and accessHash

**Comment by Lonami** [comment]
Then you're probably talking about [`AddChatUserRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/add_chat_user.html).

**Comment by atabaki** [comment]
Thanks For your Replay
But When u use "AddChatUserRequest" (as mentioned before) The "INVALID_CHAT_ID" Error Will occur
because super groups are Channel Type and Therefor have Channel Id and Channel Access Hash
When We pass Channel.Id as Chat_Id in AddChatUserRequest , "Invalid_chat_id" Error has raisen

**Comment by Lonami** [comment]
Make sure you're using `get_input_peer`:

```python
from telethon.helpers import get_input_peer
```

You need to pass an `InputPeerChat`, not the `Chat` itself.

**Comment by atabaki** [comment]
in tl.scheme we have: 
messages.addChatUser#f9a0aa09 chat_id:int user_id:InputUser fwd_limit:int = Updates;

chat_id must  be int

**Comment by Lonami** [comment]
> chat_id must be int

Er, yeah, sorry. Still need to use the `get_input_peer` for the user though.

**Comment by Lonami** [comment]
[`InviteToChannelRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/invite_to_channel.html)?

**Comment by atabaki** [comment]
it's for admin of super groups
but how telegram desktop implement this

**Comment by Lonami** [comment]
Well, I cannot add users to a super group I'm not the admin of. The option doesn't even show. So Telegram Desktop does *not* implement that. You need permission, of course.

**Comment by atabaki** [comment]
No
In Super Groups You can add your friends but it's not necessary to be admin
try now

**Comment by Lonami** [comment]
> In Super Groups You can add your friends but it's not necessary to be admin

No, I am in a super group and I can **not** add my friends, or contacts. I just can't. I don't have permission to do so. Also I'm using Telegram Desktop 1.1.7, which is the latest stable, and I just can't add users to a super group I don't have permission to!

Now, if you see the button to add users, then that's a different story, and you should have permission to use some request to add them.

**Comment by atabaki** [comment]
Try This link as example
https://telegram.me/joinchat/CuMcGD2yXIohSMyJ1RbYHw

**Comment by Lonami** [comment]
That link doesn't do anything to me.

**Comment by Lonami** [comment]
Well, you have a link, then only the person you want to add can use the link to join. You can't just force them to join unless you have permission, as I said.

**Comment by atabaki** [comment]
try bot instead of user and add bot
u can add easily in tdesktop
but in api you can not

**Comment by atabaki** [comment]
> Well, you have a link, then only the person you want to add can use the link to join

No need to be join from link. Chek it

**Comment by Lonami** [comment]
> try bot instead of user and add bot
> u can add easily in tdesktop

How can I add a bot to a channel if I only have the link? I either need to be the owner or, not sure if bots can decide to join the channel…

**Comment by Lonami** [comment]
> No need to be join from link. Check it

I checked the link from Telegram Desktop, and yes, a super group shows. But how would that let me add someone else? I don't understand how you can add someone else with just a link and from Telegram Desktop. Not even if it's a bot, you'd need to tell the bot the link, right?

**Comment by atabaki** [comment]
you first join to group and then by click on group info you can see add members button then search bot name and add it

**Comment by atabaki** [comment]
do send u screen shot of steps that i do?

**Comment by Lonami** [comment]
I made a super group. I joined by a link. And yes I can add other users. But I can't remove them which is a bit of a non-sense… Anyway I'm not sure what request Telegram Desktop uses, but it has to exist, and it will be on the online documentation.

**Comment by atabaki** [comment]
Thanks Lonami
In Searched for more than 20 hours in document and telegram source code
but cant' find it

**Comment by Lonami** [comment]
Wait you mentioned you used [`InviteToChannelRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/invite_to_channel.html) and got an `INVALID_CHAT_ID`. Are you using [what I mentioned above](https://github.com/LonamiWebs/Telethon/issues/103#issuecomment-307559859)?

**Comment by atabaki** [comment]
No
when we used "InviteToChannelRequest" admin permission error showed not invalid_chat_Id

**Comment by atabaki** [comment]
Hi Lonami
Some super groups allow to add without their permission and some not
It seems that Chat Member must be added by addchatuserrequest and (supergroup)Channel member must be added by InviteToChannelRequest
Thanks Again

**Comment by Lonami** [comment]
Okay thanks for telling us how you solved it and glad you clarified it how it works for yourself too.

**Comment by Frogbr** [comment]
I'd like to know how to add members in supergroup please could you explain me
in a supergroup on the telegram, using python.

**Comment by daha7** [comment]
how can I add a bot to the channel? I am using node js. Tried using the channels.inviteToChannel method, but I get a USER_BOT error that says the bot can only be the channel administrator. This is what I need to implement. Any ideas how to do it? Thanks
