### ISSUE TITLE
JoinChannelRequest and LeaveChannelRequest does not work correctly

### ISSUE THREAD

**Issue by mbabazadeh** [LonamiWebs/Telethon#1032]
Hi

I found out some problems in these two methods. when i send JoinChannelRequest, agent leaves the channel and when i send LeaveChannelRequest, it joins! 
I know its something wired but sometimes it doest not work correctly.

**Comment by Lonami** [comment]
This is not an issue with the library but with Telegram, where I can't help. There may also be an issue in your code.

**Comment by mbabazadeh** [comment]
> This is not an issue with the library but with Telegram, where I can't help. There may also be an issue in your code.



> This is not an issue with the library but with Telegram, where I can't help. There may also be an issue in your code.

Thanks for your answer Lonami, is this code snippet works correctly on your environment ? 
```
from telethon.tl.functions.channels import JoinChannelRequest
client(JoinChannelRequest(channel))
```

**Comment by Lonami** [comment]
Yes, the snippet works correctly on my environment.
