### ISSUE TITLE
ImportContactsRequest() does not return data

### ISSUE THREAD

**Issue by gnomik909** [LonamiWebs/Telethon#1034]
Once you have read and understood this, delete all this text and detail whatever issue you are posting.
Hello! Sometimes, when calling a method ``` ImportContactsRequest() ``` for a specific number, the answer comes up empty. I try to enter other numbers - everything is fine. After a while, the function, using the first number, starts to work. Whether telegram or telethon can have restrictions on these requests.

```python
   result = client(functions.contacts.ImportContactsRequest(
           contacts = [types.InputPhoneContact(
                   client_id=random.randint(0,9999),
                   phone=number,
                   first_name= SG("[\l\d]{10}").render(),
                   last_name= SG("[\l\d]{10}").render()
           )]
   ))
```
...names and client_id are always random.

**Comment by Lonami** [comment]
Not quite an issue with the library. It's just how Telegram works, so there is nothing for me to fix here. Try more contacts at once, or a bigger random range. I don't know.

**Comment by gnomik909** [comment]
Thank you!
