### ISSUE TITLE
how to get file_id from send_file 

### ISSUE THREAD

**Issue by lostact** [LonamiWebs/Telethon#1035]
I am asking a QUESTION here because telegram banned iranian users from joining public groups like @TelethonChat. I want to have a file_id database of files I have uploaded so I don't have to upload them again. send_file does not return file_id and to use a priviously uploaded file I must have the returned "media" but it is hard to save it in a file. How can I get file_id from send_file?

**Comment by Lonami** [comment]
Fair enough. *Currently* the library uses cache so they're not uploaded twice, but `utils` in the documentation has a method to pack bot `file_id`.

**Comment by lostact** [comment]
I tried to use [telethon.utils.pack_bot_file_id](https://telethon.readthedocs.io/en/stable/telethon.html#telethon.utils.pack_bot_file_id)  but I get this error:
```
telethon.utils.pack_bot_file_id(msg.document)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: module 'telethon.utils' has no attribute 'pack_bot_file_id'
```

**Comment by Lonami** [comment]
`telethon-sync` is outdated and I do not intend to maintain it. Nor do I support old versions.
