### ISSUE TITLE
[Shared session] Message Event Doesn't receive message update After another process use the session

### ISSUE THREAD

**Issue by adityathebe** [LonamiWebs/Telethon#1039]
I am using two different telethon processes that use the same session file. I moved to SQLalchemy session storage because with sqlite3 i kept getting "database is locked" error.

One of the processes is an event receiver which responds to new message events `@client.on(events.NewMessage)` and the other one basically gets user entities and joins channel.

The problem is once I run the second process to get an entity, the first process stops receiving updates. I am using `Telethon-sync=1.1.1`

### Process 1
```python
container = AlchemySessionContainer('mysql://{}:{}@{}/{}'.format(
    DB_user, DB_passwd, DB_host, DB_database_session
))
session = container.new_session('adityathebe')
client = TelegramClient(session, api_id, api_hash)

@client.on(events.NewMessage)
def my_event_handler(event):
  # Handle Message Here

if __name__ == "__main__":
  client.start()
  client.run_until_disconnected()
```

### Process 2
```python
app = Flask(__name__)

@app.route('/getentity')
def getEntity():
  entity = request.args.get('entity')
  result = client.get_entity(entity).to_dict()
  return jsonify(result)
```

**Comment by Lonami** [comment]
* Telethon-sync is not supported. I may need to make a clearer announcement. It's completely possible mixing Flask and Telethon's asyncio. You may be interested in #1040.
* SQLalchemy is not a problem with Telethon itself.
* I don't know how the session or Telegram behaves using the same session in two places.

**Comment by adityathebe** [comment]
Sorry, but this is not a problem with telethon-sync or flask. I tried with Telethon and the session can't be shared. Once another process use the session, the message update event stop working.

**Comment by Lonami** [comment]
Using the same session from two places at the same time it's a bad idea to begin with anyway. Just use two sessions if you need that. SQLalchemy sessions do make a difference because perhaps the behaviour with some parameters is different.

**Comment by adityathebe** [comment]
> Using the same session from two places at the same time it's a bad idea to begin with anyway

I agree but my program requires it that way.

Process A joins entities and talks to people and all the entities are saved in its session file.
Process B needs to send messages using the chat_ids saved in process A's session. 

**I've found a workaround though**  
Used two sessions and Process B directly accesses Process A's mysql db to get the username.

Thank you for your quick response !
