### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file telethon/telegram_client.py on line 584 when installing via pip on macos sierra

### ISSUE THREAD

**Issue by hanselke** [LonamiWebs/Telethon#104]
sudo -H pip install telethon
Password:
Collecting telethon
  Downloading Telethon-0.10.1.tar.gz (969kB)
    100% |████████████████████████████████| 972kB 34kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-SeMYDs/telethon/setup.py", line 15, in <module>
        from telethon import TelegramClient
      File "telethon/__init__.py", line 2, in <module>
        from .telegram_client import TelegramClient
      File "telethon/telegram_client.py", line 583
    SyntaxError: Non-ASCII character '\xe2' in file telethon/telegram_client.py on line 584, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-SeMYDs/telethon/

**Comment by Lonami** [comment]
Python 2 is not supported, if that's what you're trying? Try using `pip3`.

**Comment by Lonami** [comment]
By the way the error is caused by the ✅ character in a method description. I guess I could remove all those.

**Comment by Lonami** [comment]
You will have to wait for the next `pip` update or install Telethon manually as described on the `README.rst` though.
