### ISSUE TITLE
ReplyKeyboardMarkup resize

### ISSUE THREAD

**Issue by afraz92** [LonamiWebs/Telethon#1045]
hi 
how can enable  "resize_keyboard" in ReplyKeyboardMarkup?
find it here https://lonamiwebs.github.io/Telethon/constructors/reply_keyboard_markup.html
But how should I use it?
for example in this >>> bot.send_message(chat, anytext, buttons = ([Button.text('anytext')]))

**Comment by Lonami** [comment]
I think you missed the "DON'T ASK QUESTIONS HERE." when opening an issue.

**Comment by amir1379** [comment]
i have that problem too

**Comment by Lonami** [comment]
Make a new *enhancement* issue, not a question.
