### ISSUE TITLE
participants = client.get_participants('')

### ISSUE THREAD

**Issue by AwaitEntity** [LonamiWebs/Telethon#1047]
So, I tried using
participants = client.get_participants('_test'_)

It worked fine, len(participants) is the exact number of the users in the group.
But when trying to use the participants list, I can´t print nor do anything else with it, because the type(participants) is a <class 'telethon.helpers.TotalList'>

So how can I use the "participants" variable right now?

//EDIT:
If I try to print it, it shows:
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 13036-13036: Non-BMP character not supported in Tk

After searching on StackOverflow, etc., nothing has worked :/

**Comment by Lonami** [comment]
Did you read the issue template before creating this?

**Comment by AwaitEntity** [comment]
Yes, I did.

But I haven’t found anything 0.o
Could you help me out?

**Comment by AwaitEntity** [comment]
Please help me out.

I can’t find how to deal with this object.
I literally searched ~6 hours on StackOverflow, your documentations, the GitHub and YouTube.

If you don’t want to help me, please give me just a little hint :/

**Comment by AwaitEntity** [comment]
I´m new to GitHub, that´s why I created an issue, my bad, sorry.

Still, could you *please *help me out?

Am Sa., 24. Nov. 2018 um 12:34 Uhr schrieb Jonas <jonasrgbg@gmail.com>:

> Please help me out.
>
> I can’t find how to deal with this object.
> I literally searched ~6 hours on StackOverflow, your documentations, the
> GitHub and YouTube.
>
> If you don’t want to help me, please give me just a little hint :/
>
>
>

**Comment by Lonami** [comment]
**This place is not for questions.** When you made an issue you saw this:
DON'T ASK QUESTIONS HERE.

This place is for issues with the library, so please make sure that:

The error is in the library's code, and not in your own.
You have already searched for your error on existing issues.
You are testing with upstream code (pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip).
If you have a question, ask in the official Telegram group https://t.me/TelethonChat or https://stackoverflow.com. Enhancement ideas are currently welcome, too.

So why are you still asking here?
