### ISSUE TITLE
Undefined name: TelegramBareClient

### ISSUE THREAD

**Issue by cclauss** [LonamiWebs/Telethon#1051]
[flake8](http://flake8.pycqa.org) testing of https://github.com/LonamiWebs/Telethon on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./telethon/client/telegrambaseclient.py:497:18: F821 undefined name 'TelegramBareClient'
        client = TelegramBareClient(
                 ^
1     F821 undefined name 'TelegramBareClient'
1
```

**Comment by Lonami** [comment]
Answered in #1052.
