### ISSUE TITLE
Answering inline queries with media 

### ISSUE THREAD

**Issue by JosXa** [LonamiWebs/Telethon#1053]
When trying to answer an inline query with an uploaded sticker (document), currently there is no way to send this media when the result is clicked. According to my tests, this is because Telegram expects an [InputBotInlineMessageMediaAuto](https://lonamiwebs.github.io/Telethon/constructors/input_bot_inline_message_media_auto.html) when you're supposed to send only the plain document without any text, but this is not implemented in Telethon yet. At the moment, Telethon [raises a ValueError](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/custom/inlinebuilder.py#L253) when you don't specify any of the `text, geo, contact,` or `game` parameters to the builder method. Instead, this should be allowed for a number of types, but I'm not sure as to which ones these are - Stickers are one of them. When none of these values is supplied, [the else block](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/custom/inlinebuilder.py#L304) must be changed to something along the lines of
```
        else:
            # When sending plain media without text or caption (e.g. stickers)
            return types.InputBotInlineMessageMediaAuto(
                message='',  # Empty message, because stickers can't have text
                entities=None,
                reply_markup=markup
            )
```

This works for stickers, and I'm fairly sure other media files can do it aswell (TBD).

What I mean by "plain stickers" is this:
![image](https://user-images.githubusercontent.com/7313176/48983196-221bde80-f0ec-11e8-89d5-549b00c3d6e0.png)
--> No text, but a reply markup.

**Comment by Lonami** [comment]
Cool, now I can do this:
```python

with bot:
    with bot.conversation('lonami') as conv:
        sticker = conv.get_response(1).media

    @bot.on(events.InlineQuery)
    async def h(e: events.InlineQuery.Event):
        builder = e.builder
        await e.answer(results=[
            builder.document(sticker, type='sticker')
        ])

    bot.run_until_disconnected()
```
