### ISSUE TITLE
Unable to get live updates from Telegram Channels

### ISSUE THREAD

**Issue by derekhuizhang** [LonamiWebs/Telethon#1055]
This is the code that I'm running:
```
    client = TelegramClient('session', api_id, api_hash)
    client.start()
   
    channel = client.get_entity('test_channel')
    print(test_channel)
    @client.on(events.NewMessage(chats=(channel)))
    async def handler(event):
        print(event)
    client.run_until_disconnected()
```

The channel is a channel that I created and am sending messages too, but I am unable to retrieve any NewMessage objects (the console doesn't output a NewMessage object like it's supposed to when I post to the channel). I've also tested with the username of the channel. It works if I change the 'chats=' to the username of a group.

Anyone have any ideas why I'm unable to receive live updates from a channel?

**Comment by Lonami** [comment]
You may want to play with [`GetChannelDifferenceRequest`](https://lonamiwebs.github.io/Telethon/methods/updates/get_channel_difference.html) somehow because I know Telegram is weird. `pts` comes from the dialogs.
