### ISSUE TITLE
How can I upload files faster?

### ISSUE THREAD

**Issue by aminhyper** [LonamiWebs/Telethon#1062]
I want to upload files larger than 50 MB using ```client.send_file``` .
I used the following code:

```python
client.send_file(entity,path)
```
Then I get ```file_id``` through bot API,
Unfortunately, the upload speed is very low.
The download and upload speed of my server is 200 Mb/s, while the upload speed reaches 100 Kb/s.
How can I upload files faster?

**Comment by Lonami** [comment]
"Don't ask questions here".

**Comment by aminhyper** [comment]
Sorry,
Where can i ask my question?
It is very important for me

**Comment by Lonami** [comment]
Wrong button. Anyway, StackOverflow or `@TelethonChat`.
