### ISSUE TITLE
Sending and receiving messages from a private channel

### ISSUE THREAD

**Issue by Nikovit** [LonamiWebs/Telethon#1063]
Trying to send or receive messages from a private channel. 
I read the documentation several times.

My code example

`@client.on(events.NewMessage(chats=("pr_russia", "MRZLKVK", "mudak", "lentachold", "nikovit_test")))
async def normal_handler(event):

     channel = "nikovit_test2"

    message = event.message.to_dict()['message']

    if event.message.to_dict()['media'] is not None:
        file_ms = await client.download_media(message=event.message)
        await client.send_message(channel, message, file=file_ms)
        os.remove(file_ms)
    else:
        await client.send_message(channel, message)

client.start()
client.run_until_disconnected()`

There is an example in the documentation.
`from telethon.tl.functions.messages import ImportChatInviteRequest
updates = client(ImportChatInviteRequest('AAAAAEHbEkejzxUjAUCfYg'))`

But this code did not work for me

How to send read and send messages in a closed channel?

telethon-1.4.3
Python 3.7

**Comment by Nikovit** [comment]
Messages to open and closed channels are sent and received.

**Comment by Lonami** [comment]
Good that you read the documentation, but questions don't belong here.
