### ISSUE TITLE
get_entity

### ISSUE THREAD

**Issue by zhaoziming** [LonamiWebs/Telethon#1066]
code:ok
contact = client.get_entity('+8618632103309')
contact = client.get_entity(605648263)
------------------------------------------------------------
code:Throw ValueError
#contact = client.get_entity('+8618632103309')
contact = client.get_entity(605648263)

ValueError: Could not find the input entity for 605648263. Please read https://telethon.readthedocs.io/en/latest/extra/basic/entities.html to find out more details.

**Comment by LegendPikachuYT** [comment]
Fix invite link error
