### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-4'

### ISSUE THREAD

**Issue by aminhyper** [LonamiWebs/Telethon#1067]
Hello
I use the latest version of telethon=1.4.3.
When the following code is executed:
`
   client = TelegramClient('name.session', api_id, api_hash)
`

I receive the following error:

> File "/usr/local/lib/python3.5/dist-packages/telethon/client/telegrambaseclient.py", line 171, in __init__
 self._loop = loop or asyncio.get_event_loop()
File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
return get_event_loop_policy().get_event_loop()
File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-4'.

I use the telethon package in my application that my application run in flask platform with mode_wsgi

Thanks for your support and your efforts

**Comment by Lonami** [comment]
Someone didn't read the documentation.

**Comment by aminhyper** [comment]
When I use the old version, everything works fine
But this error goes when I use the new version
If it is possible for you, please guide me

**Comment by ftuyama** [comment]
https://docs.telethon.dev/en/latest/concepts/asyncio.html?highlight=thread#can-i-use-threads
