### ISSUE TITLE
video stream does'nt work in telethon==0.19.1.6

### ISSUE THREAD

**Issue by aminhyper** [LonamiWebs/Telethon#1069]
Hello
I installed `telethon==0.19.1.6` in one of my server, everything is OK, but when i want to use stream video with this code, it is not effect:
`client.send_file(entity,path,allow_cache=False,attributes=(DocumentAttributeVideo(0, 0, 0,supports_streaming=True),))`
I installed `telethon ==1.4.3` in another server, when i run this code with python it works finely and i can get video with stream, but when i use this code in flask i get error:
`RuntimeError: There is no current event loop in thread 'Thread-4'`
I do not know which version to use
I encounter a problem in every version I use
Unfortunately, I am banned from Telegram group and I can not ask my question there
Thank you

**Comment by Lonami** [comment]
Do not open duplicates (#1067). I already told you to read the documentation, and the error you get has nothing to do with video stream.

**Comment by aminhyper** [comment]
Which part of the documentation should I study?
My condition is such that I can not read all the sections

**Comment by Lonami** [comment]
If you can't read pay someone to help you, but this is **issues** with the library, not a support section to help people.
