### ISSUE TITLE
RPCError 400: CHAT_INVALID (caused by InviteToChannelRequest) 

### ISSUE THREAD

**Issue by xiongliping** [LonamiWebs/Telethon#1075]
My code was below:

`await client(InviteToChannelRequest(target_channle, [user_id]))`

and I recieved the error "RPCError 400: CHAT_INVALID (caused by InviteToChannelRequest) ".
What should I do?

And my telethon version is 1.5.

**Comment by sd347** [comment]
Did you solve it?
