### ISSUE TITLE
Error in telegram_connect while trying to connect to a client

### ISSUE THREAD

**Issue by giladk288** [LonamiWebs/Telethon#1080]
I've upgraded into telethon version 1.4.3 from version 0.15.2.3.
And when I'm trying to connect a client like I used to do:

```
client = TelegramClient('/home/giladk288/sessions/' + user['phone'], user['api_id'], user['api_hash'])
client.connect()
```

I'm gettting this error:

ERROR - TeleBot: "RuntimeError occurred, args=("There is no current event loop in thread 'WorkerThread1'.",)
Traceback (most recent call last):
  File "abc.py", line 30, in echo_all
    client = telegram_connect(user)
  File "abc.py", line 51, in telegram_connect
    client = TelegramClient('/home/giladk288/sessions/' + user['phone'], user['api_id'], user['api_hash'])
  File "/home/giladk288/.local/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 171, in __init__
    self._loop = loop or asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)

what am I doing wrong?

**Comment by Lonami** [comment]
One of the first things both the `README.md` and the documentation is tell you why this happens. I guess you didn't bother reading so I won't bother helping.

**Comment by giladk288** [comment]
I know and read the documentation, but I want my program to skip unauthorized client.. Is it possible in a this version?
