### ISSUE TITLE
client timed out and need re-authentication 

### ISSUE THREAD

**Issue by mreza12** [LonamiWebs/Telethon#1083]
When I connect using  api_id and api_hash it asks for phone number and a code which telegram sends for me, then i connect.
I use this session and my program works for a few days, and then get disconnected or my session get timed out, and need to re authenticate my self with phone number and code.

Is it the way the telegram works or there is a better way i can use, so i shouldn't authenticate myself with a code each time.

My program stop working every few days and i have to manually re-authenticate when i get this message:

"please enter your phone (or bot token):"

Is there any limitation in time client can be connected or number of query you make to server.
i try to check for updates on a few channels every minutes, can this be an issue?
Thanks

**Comment by Lonami** [comment]
If the client disconnects properly, this should not happen. I have sessions running for longer without issue. Debug logs may be helpful (`import logging; logging.basicConfig(level=logging.DEBUG)`), and just make sure you call `disconnect` under any situation. This code always call `disconnect`, whatever happens:

```python
with client:
    ... rest of your code
```
