### ISSUE TITLE
button.click forwards message itself

### ISSUE THREAD

**Issue by KOPACb** [LonamiWebs/Telethon#1090]
i'm trying code like this:

```
@client.on(events.NewMessage(from_users=chat_entity))
async def handler(event):
        buttons = await event.get_buttons()
        for bline in buttons:
            for button in bline:
                print(button.button.text)
                if 'button_text' in button.button.text:
                    print('Pressing button')
                    print(button)
                    print(button.button)
                    await button.click()
```

and on button click i got click on right button and reply to a message button from.

button is:
```
<telethon.tl.custom.messagebutton.MessageButton object at 0x068F99F0>
KeyboardButton(text='blah button_text')
```

**Comment by KOPACb** [comment]
linux
'''
$ python -V
Python 3.5.3

$ pip freeze
async-generator==1.10
pyaes==1.6.1
pyasn1==0.4.5
rsa==4.0
Telethon==1.5.3
'''
windows & python 3.6 the same story

**Comment by KOPACb** [comment]
full code:
'''
from telethon import TelegramClient, events, sync, utils

api_id=12345
api_hash='deadbeefdead'

client = TelegramClient('session', api_id, api_hash)
client.start()


wwr = client.get_entity('gamee')
print(wwr)


@client.on(events.NewMessage(from_users=wwr))
async def handler(event):
    buttons = await event.get_buttons()
    for bline in buttons:
        for button in bline:
            print(button.button.text)
            if 'Паззл' in button.button.text:
                await button.click()

try:
    print('(Press Ctrl+C to stop this)')
    client.run_until_disconnected()
finally:
    client.disconnect()
'''

result:
![image](https://user-images.githubusercontent.com/2738078/51249546-ada34480-19a4-11e9-81c8-e7de9ccaa94e.png)

**Comment by Lonami** [comment]
This is working as expected. When you click on these buttons:
![imagen](https://user-images.githubusercontent.com/6297805/51308988-b3039c00-1a43-11e9-809d-56c242ae6d2d.png)

A message is sent:
![imagen](https://user-images.githubusercontent.com/6297805/51309000-bbf46d80-1a43-11e9-971b-ba10ed2b68ba.png)

**Comment by slashlion** [comment]
How can I send a couple of bottons to a specific channel?

This piece does not work for me:
await client.send_message(-1001265113337, buttons=Button.text('hi!', selective=True))
