### ISSUE TITLE
handler sometimes fails to get new messages

### ISSUE THREAD

**Issue by wertas** [LonamiWebs/Telethon#1093]
Telethon client don`t receive messages after some while (5-10 minutes after some actions and so on)

code sample:

```
loop = asyncio.get_event_loop()

async def all_messages(event):   # sometimes new messages dont invoke this
      if event.message.from_id == brother_id:   
         # code

   async def some_loop():
      while True:
         # code

client.add_event_handler(all_messages, events.NewMessage)
loop.run_until_complete(some_loop())
```

No other sessions disturb it, ive tested with only telethon one

**Comment by Lonami** [comment]
First of all the code you show is indented very oddly. Second, if the `# code` of `some_loop` never `await`'s anything the event loop will get stuck and nothing will ever arrive. "Sometimes" new messages don't arrive is also not specific enough. Would need a better example.

**Comment by wertas** [comment]
More detail example:

```
loop = asyncio.get_event_loop()

async def all_messages(event):   # sometimes new messages dont invoke this
   try:
      if event.message.from_id == brother_id:   
         # code
   except Exception as err:
      # exc code

async def some_loop():
   while True:
      try:
         await asyncio.sleep(1)
         while not (some multiprocessing.Queue()).empty():  # waiting for some event from another process
            # code
      except Exception as err:
         # exc code

client.add_event_handler(all_messages, events.NewMessage)
loop.run_until_complete(some_loop())
```

this some multiprocessing.Queue() is empty when event must happen (in ~10 min after some action)
infinite while loop in some_loop() is working correctly, i logged it and got ~1second log for all the period.
 I got new message in telegram and all_messages(event) was not invoked

**Comment by wertas** [comment]
`except Exception as err` logs all errors with traceback, and it was not triggered during log
now trying to log all my msgs outside `if event.message.from_id == brother_id` - all messages are logged, but from some moment it stops to work... but some_loop() still works

**Comment by Lonami** [comment]
I cannot reproduce this issue, I have a bot running for weeks with no problem.

**Comment by wertas** [comment]
Yeep, but i have master process and 5+ processes with telethon... maybe they interfere somehow...

**Comment by Lonami** [comment]
If they're all using the same account, probably.
