### ISSUE TITLE
Possibly unwanted mime type [Windows only]

### ISSUE THREAD

**Issue by tausackhn** [LonamiWebs/Telethon#1096]
Passing `.mp4` video-file, for example, to `send_file` leads to unwanted mime type `application/mp4` on Windows. This makes it impossible to transfer the correct video attributes, because telegram only accepts them for `audio/mp4` or `video/mp4`.  It happens due to reading Windows registry for mime types unlike on Linux. According to [RFC4337](http://www.rfc-editor.org/rfc/rfc4337.txt), it is possible mime type for `*.mp4` files if it do not contain any video or audio content. Anyone can check what mime type python returns
```
python -m mimetypes test.mp4
```
This mime type will be used in `send_file`.

Quick hint: add in your script `mimetypes.add_type('video/mp4', '.mp4')` to overwrite behaviour.  

It would be nice to add keyword argument `mime_type` to `send_file` and other functions.

**Comment by Lonami** [comment]
I think we should add all "known" mimetypes by Telegram just to be safe. These are<sup>[1](https://github.com/telegramdesktop/tdesktop/blob/69b1f6c4e15f3d96e2b6c37c4fb2c76a50a05692/Telegram/SourceFiles/storage/localimageloader.cpp#L77-L83)[2](https://github.com/telegramdesktop/tdesktop/blob/69b1f6c4e15f3d96e2b6c37c4fb2c76a50a05692/Telegram/SourceFiles/storage/localimageloader.cpp#L568-L571)[3](https://github.com/telegramdesktop/tdesktop/blob/69b1f6c4e15f3d96e2b6c37c4fb2c76a50a05692/Telegram/SourceFiles/storage/localimageloader.cpp#L535-L541)[4](https://github.com/telegramdesktop/tdesktop/blob/69b1f6c4e15f3d96e2b6c37c4fb2c76a50a05692/Telegram/SourceFiles/data/data_document.cpp#L106-L115)</sup>
```
image/bmp
image/jpeg
image/gif
image/png
image/webp
image/x-tga
image/tiff (or .tif)
image/vnd.adobe.photoshop (.psd)
video/mp4
video/quicktime (.mov)
audio/mp3
audio/m4a
audio/aac
audio/ogg
audio/flac
```

**Comment by Lonami** [comment]
Wait, does `mimetypes.add_type('video/mp4', '.mp4')` make a difference if `application/mp4` is already registered? I've noticed it doesn't make a difference with things like `.jpg`.

**Comment by tausackhn** [comment]
It replace mime type for file extenstion `.mp4` if it already known. [link](https://docs.python.org/3/library/mimetypes.html#mimetypes.add_type)

**Comment by Lonami** [comment]
Forgot to close.
