### ISSUE TITLE
Triggering events.MessageEdited even with outgoing=True

### ISSUE THREAD

**Issue by the-blank-x** [LonamiWebs/Telethon#1097]
Make c1 send a message in a channel that c2 have edit perms in, edit c1's message to trigger something like `@client.on(events.MessageEdited(outgoing=True, pattern='^\.ping')` and manual responds, thinking that c1 edited their message.

**Comment by Lonami** [comment]
I just tried this again and it seems to be no longer happening. It might've been a server-side bug.
