### ISSUE TITLE
Video not sent as document with force_document=True

### ISSUE THREAD

**Issue by KingKaitoKid** [LonamiWebs/Telethon#1101]
- telethon version: 1.5.5
- Using Python with macOS Mojave 10.14.3 (18D42)

I'm using the client [telegram-upload](https://github.com/Nekmo/telegram-upload) that use this module.

This module works correctly but when try to send a video with `force_document =True` video is not sent as document but as video.

This is how I call the _send_file_ method 
`self.send_file(entity, file, caption=(name[:CAPTION_MAX_LENGTH] + '..') if len(name) > CAPTION_MAX_LENGTH else name, progress_callback=progress, force_document=True)`

Video is sent as video and I try to change the MIME and get same result.

**Comment by Lonami** [comment]
If possible, provide the video file somewhere so that I can try myself.

**Comment by KingKaitoKid** [comment]
I tried to send the video through the Telegram application on MacOS, putting the option to send it "without compression" so it was sent as a file and not as a video.
Unfortunately, the MP4 file was sent as a video and this leads me to think that it is not a problem with Telethon but with Telegram that interprets MP4 files always as video.

**Comment by Lonami** [comment]
`force_document=True` only makes a difference for photos. I checked, and even if you send the video without `types.DocumentAttributeVideo`, i.e. commenting out this line:
https://github.com/LonamiWebs/Telethon/blob/c9e9b82eac643e77347f3dbec480c864418609e5/telethon/utils.py#L524

…the video file is sent in the same way. So, I think there's no issue, more after you tried with macOS.

**Comment by evandrix** [comment]
is there a way then to `force_document=True` for videos?

**Comment by Lonami** [comment]
Videos are always documents. Fake their mimetype if you want them to not be playable from the apps.
