### ISSUE TITLE
resolve User by user_id rather than by username

### ISSUE THREAD

**Issue by eteamin** [LonamiWebs/Telethon#1104]
This is rather a question than an issue report.

As you know, resolving by username is a heavy call and the client gets reported as spam by telegram and the account will be deleted after a while. 
Is there a way to resolve by user_id?
like instead of 

`me = client.get_entity('https://t.me/aetesamian1')`
that is my actual username on telegram I use my Id. because when I use my user_id ValueError is raised.

**Comment by Lonami** [comment]
> This is rather a question than an issue report.

Aw, did you somehow miss the big [`ISSUE_TEMPLATE.md`](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE.md) that's shown when creating a new issue? I'll paste it here.

> DON'T ASK QUESTIONS HERE.
> 
> This place is for issues with the library, so please make sure that:
> 1. The error is in the library's code, and not in your own.
> 2. You have already searched for your error on existing issues.
> 3. You are testing with upstream code (pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip).
> 
> If you have a question, ask in the official Telegram group https://t.me/TelethonChat or  https://stackoverflow.com. Enhancement ideas are currently welcome, too.
> 
> If you paste code, please put it between three backticks (`):
> ```python
> code here
> ```
> 
> Once you have read and understood this, delete all this text and detail whatever issue you are posting.

**Comment by Lonami** [comment]
The `ValueError` should have a link to the documentation. There are links to the group where you can ask. You have StackOverflow. There was really no need to open an issue for *that* question.
