### ISSUE TITLE
Failed to login with phone

### ISSUE THREAD

**Issue by nosanity** [LonamiWebs/Telethon#1108]
Login to account is failing after phone and code submission. I guess there's a mixup with 2nd argument name which is returned from https://github.com/LonamiWebs/Telethon/blob/master/telethon/client/auth.py#L238

**Comment by Lonami** [comment]
Good catch, would you like to make a pull request? I prefer if you rename the two `phone_code_hash` with `phone_hash`, but you can also fix the `return`. You can edit the file directly from GitHub.

**Comment by nosanity** [comment]
Done. https://github.com/LonamiWebs/Telethon/pull/1109
