### ISSUE TITLE
Get file name in media

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#111]
Hi,
How I can retrieve file name that is exist in media?

thanks

**Comment by Lonami** [comment]
Use the [docs](https://lonamiwebs.github.io/Telethon). Look for [`MessageMedia`](https://lonamiwebs.github.io/Telethon/types/message_media.html). You probably want [`MessageMediaDocument`](https://lonamiwebs.github.io/Telethon/constructors/message_media_document.html), which in turn has a [`Document`](https://lonamiwebs.github.io/Telethon/constructors/document.html), which may or may not have certain [`attributes`](https://lonamiwebs.github.io/Telethon/types/document_attribute.html). One of these attributes can be [`DocumentAttributeFilename`](https://lonamiwebs.github.io/Telethon/constructors/document_attribute_filename.html). Look for it and please use the documentation just like I did.

Or just use (or read) [`download_document`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py#L606-L647).

**Comment by hnikaein** [comment]
Thanks. But I read docs before asking. But when I searching in attributes sometimes there isn't file name in it.

**Comment by Lonami** [comment]
> But when I searching in attributes sometimes there isn't file name in it.

That's right, it only shows *types* and not *constructors* (which is what you were looking for). I could potentially change that.
