### ISSUE TITLE
Unexpected results with client.get_messages(reverse=True) 

### ISSUE THREAD

**Issue by vlajnaya-mol** [LonamiWebs/Telethon#1111]
I am trying to retrieve messages  in reverse order from a dialogue. Not all messages are returned for some reason. I believe it's a problem with an iter_messages method, but I still have not figured it out. 
Here is my code:
```
    client = TelegramClient(session_name, api_id, api_hash)
    client.connect()
    entity = client.get_entity(entity_id)
    # First pack
    msgs = client.get_messages(entity, limit=1000000)
    print(f"Without parameters len == {len(msgs)}")
    # Second pack
    msgs_reversed = client.get_messages(entity, reverse=True, limit=1000000)
    print(f"Reversed len == {len(msgs_reversed)}")
    # Third pack
    msgs_reversed_first6000 = client.get_messages(entity, reverse=True, limit=6000)
    msgs_reversed_second6000 = client.get_messages(entity, reverse=True, limit=6000,
                                                   offset_id=msgs_reversed_first6000[-1].id)
    print(f"Reversed first 6000 len == {len(msgs_reversed_first6000)}")
    print(f"Reversed second 6000 len == {len(msgs_reversed_second6000)}")
```
What I've got:

> Without parameters len == 10397
> Reversed len == 7600
> Reversed first 6000 len == 6000
> Reversed second 6000 len == 2410

You can see 3 different results: 10397, 7600, 8410. Also, I've made heat maps with messages for better problem understanding:
## First pack (without parameters)
![image](https://user-images.githubusercontent.com/36573372/52867128-e28fec00-3148-11e9-859f-934bc87f34ae.png)

##  Second pack (reversed len)
![image](https://user-images.githubusercontent.com/36573372/52866827-2f26f780-3148-11e9-910b-ea2ec796ae68.png)

## Third pack (2 requests using offset_id):
![image](https://user-images.githubusercontent.com/36573372/52867183-05ba9b80-3149-11e9-9671-bf7f2ac2c134.png)

**Comment by vlajnaya-mol** [comment]
I tried it myself, it works, thank you
```
Without parameters len == 10471
Reversed len == 10471
Reversed first 6000 len == 6000
Reversed second 6000 len == 4471
```

**Comment by Lonami** [comment]
Actually it might have been fixed by https://github.com/LonamiWebs/Telethon/commit/1e4a12d2f70b9fcf6d2d9d631cab18afed234e4f and not #1115 like I said, but it doesn't matter much now that it's fixed. Just for future reference.
