### ISSUE TITLE
Empty session file causes unhandled exception

### ISSUE THREAD

**Issue by dmig** [LonamiWebs/Telethon#1113]
I'm using Telethon 1.5.5 installed from pip. As I see from recent changes, this issue should be partially fixed.

Recently I noticed a warning while debugging:
```
UserWarning: The sqlite3 module is not available under this Python installation and no custom session instance was given; using MemorySession.
You will need to re-login every time unless you use another session storage
  'The sqlite3 module is not available under this '
```

That occured after `sqlite3.OperationalError` in `disconnect()` after `log_out()`. Should be another issue: _`disconnect()` should check if connected and session is active_.

`sqlite3.OperationalError` left empty file in place of session file. I pinpointed the reason: `_check_migrate_json()` tries to parse empty file, doesn't handle the exception and doesn't remove empty file after.

https://github.com/LonamiWebs/Telethon/blob/0934f71c02f8ecd8b64a8fa22edf220a78397f24/telethon/sessions/sqlite.py#L130-L151

**Proposed solution**:
1. change
```python
            except UnicodeDecodeError:
```
to
```python
            except (UnicodeDecodeError, json.decoder.JSONDecodeError):
```
2. move https://github.com/LonamiWebs/Telethon/blob/0934f71c02f8ecd8b64a8fa22edf220a78397f24/telethon/sessions/sqlite.py#L135
to `finally` block
```python
            except (UnicodeDecodeError, json.decoder.JSONDecodeError):
                return []  # No entities 
            finally:
                self.delete()
```

**Comment by dmig** [comment]
Testcase:
```shell
$ touch empty-file.session
$ python3
```
```python
>>> from telethon import TelegramClient, sync
>>> client = TelegramClient('empty-file', 'doesn-t-matter', 'doesn-t-matter')
# here you should see warning with library v1.5.5
```

**Comment by Lonami** [comment]
Thank you for digging so much into the issue. I wish all of them were like this. I believe this commit is the most appropriated solution, though.
