### ISSUE TITLE
The "user_left" attribute of the "event" object does not work correctly

### ISSUE THREAD

**Issue by ldebortoli** [LonamiWebs/Telethon#1116]
I'm using a handler for chat events, my idea was that when a member of a group is kicked sends an A message, and when a member leaves voluntarily sends another message B. For that I check if the attributes "user_left" or "user_kicked" of the "event" object are True or False.
The problem is that regardless of which of the two situations occurs (if any of them occur), the field "user_left" will be in False and "user_kick" in True, even if a member voluntarily leaves the group and create a chat event "user X has left the group".

**Comment by Lonami** [comment]
Telegram doesn't send these events if there are more than 50 members in a group. Is that your issue?

**Comment by ldebortoli** [comment]
No, my issue is that in groups that have 50 members or less (where telegram does send these "user X has left the group" chat events) it happens that the received "event" object has the attributes "user_left" in False and "user_kicked" in True.

**Comment by Lonami** [comment]
When a user leaves, this is the update that you get:
```python
UpdateNewChannelMessage(
	message=MessageService(
		id=6,
		to_id=PeerChannel(
			channel_id=1433503280
		),
		date=datetime.datetime(2019, 2, 27, 18, 37, 17, tzinfo=datetime.timezone.utc),
		action=MessageActionChatDeleteUser(
			user_id=541758126
		),
		out=False,
		mentioned=False,
		media_unread=False,
		silent=False,
		post=False,
		from_id=541758126,
		reply_to_msg_id=None
	),
	pts=8,
	pts_count=1
)
```

When you kick an user, this is the update that you get:
```python
UpdateNewChannelMessage(
	message=MessageService(
		id=10,
		to_id=PeerChannel(
			channel_id=1433503280
		),
		date=datetime.datetime(2019, 2, 27, 18, 38, 5, tzinfo=datetime.timezone.utc),
		action=MessageActionChatDeleteUser(
			user_id=541758126
		),
		out=True,
		mentioned=False,
		media_unread=False,
		silent=False,
		post=False,
		from_id=10885151,
		reply_to_msg_id=None
	),
	pts=12,
	pts_count=1
)
```

The difference seems to be `from_id` being who took the action. If it's the same user that was "deleted", it means they left. I guess I can work with that.

**Comment by Lonami** [comment]
Thank you for reporting an actual bug.
