### ISSUE TITLE
Allow handling the client's session being revoked (e.g. from another client)

### ISSUE THREAD

**Issue by Manuel1510** [LonamiWebs/Telethon#1118]

**Comment by Manuel1510** [comment]
Your [proposed solution](https://t.me/telethonofftopic/166646) still doesn't convince me tbh, I don't think forcing users to use run_until_disconnected (which is often not needed, expecially if you're using other asyncio libraries or run multiple clients) is the right way...

For instance, think about a bot-api-like http API made with telethon and aiohttp's server
What you'd do might be something like this:
```
app = web.Application(...)
web.run_app(app)
```
and then when when you receive a request:
```
if bot_id not in sessions:
    client = await TelegramClient(...).start(bot_token=token)
    sessions[bot_id] = client
return sessions[bot_id]
```
And not use run_until_complete at all.

I still think having a callback would be better.

**Comment by Lonami** [comment]
If we do this, perhaps it would be worth to have `events.Disconnected` instead, with a way to tell the `event.reason`, or `event.error`. Because you're essentially handling a disconnection (as an alternative to <code>run_until_<strong>disconnected</strong></code>),

**Comment by Lonami** [comment]
This issue is pretty old, so closing. If there's still interest, we may try to re-evaluate alternatives.
