### ISSUE TITLE
Add other transport layers (HTTP, TCP abridged, IPv6…)

### ISSUE THREAD

**Issue by cher-nov** [LonamiWebs/Telethon#112]
![_2017-06-15_18-48-35](https://user-images.githubusercontent.com/2927132/27173221-465995d0-51fb-11e7-8aac-5899644cee7b.png)

[Madeline](https://github.com/danog/MadelineProto) is cool, let's be like Madeline.

---

**Roadmap**:
* [x] TCP full
* [x] Obfuscated (TCP abridged-like)
* [x] TCP intermediate
* [x] TCP abridged
* [x] IPv6 for above
* [ ] HTTP
* [ ] HTTPS

**Comment by Lonami** [comment]
I wonder if one could specify a **class** (class, not instance) of the transport they want to be used before calling `.connect()`. Then, that transport would be used. We already have `TcpTransport` so it would be a matter of making more classes I guess, unless HTTP works too differently.

**Comment by danog** [comment]
Or, you know, you could just use MadelineProto, and feel the joy of using a programming language that actually has decent garbage collection and memory management :^)

**Comment by cher-nov** [comment]
As reported in [@TelethonChat](https://t.me/TelethonChat), the support for HTTP/HTTPS is necessary in case of HTTP proxy chains.
If you use TCP, the output address is the address of the super-proxy, not the chain's exit node.
