### ISSUE TITLE
wait_time unit in the iter_messages

### ISSUE THREAD

**Issue by omidmnz** [LonamiWebs/Telethon#1120]
This is a shortcoming of the documentation, so I'm not sure if this repo is the right place to file the issue.

The [iter_messages](https://telethon.readthedocs.io/en/latest/telethon.client.html#telethon.client.messages.MessageMethods.iter_messages) does not include the time unit for the argument. Is it in seconds? Or in milliseconds?

I also searched the docs, but couldn't find any information about the time units.

**Comment by Lonami** [comment]
Everything uses seconds, but that's fair enough. https://github.com/LonamiWebs/Telethon/commit/7c48857d0c8625d0626c19e2af7fe00c1823f460
