### ISSUE TITLE
Got notification after read in another clients

### ISSUE THREAD

**Issue by SmartManoj** [LonamiWebs/Telethon#1123]
I used send_read_acknowledge to mark as read but got notifications.
Is there any way to hide notification for acknowledged messages ?

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/blob/8884015dae6f6d1304460595d433a701b51257d0/telethon/client/messages.py#L853-L865

If that's not working, nothing will. Just make sure you mark all as read and clear mentions.

**Comment by SmartManoj** [comment]
I did

**Comment by SmartManoj** [comment]
reopen

**Comment by Lonami** [comment]
If the clients (e.g. Telegram Desktop) don't handle this correctly, there's nothing we can do. You can mute the chat with Telethon if marking as read does not work. This is a question and doesn't belong in the issues, though.
