### ISSUE TITLE
offset_date in iter_messages is being ignored if used with filter

### ISSUE THREAD

**Issue by jetiston** [LonamiWebs/Telethon#1124]
I was trying to get some URLs in a Telegram conversation so I used filter which was very convenient. I also wanted to get an URL in a message 24hrs ago so I used offset_date. But when I use them together it seems that offset_date parameter is being ignored.

```
offset_date=datetime.now() - timedelta(hours=26)

#With filter, no offset
for message in client.iter_messages(channel, limit=1, filter=InputMessagesFilterUrl):
	print(message.date)
	print('\n')

print('vs')

#With filter, with offset
for message in client.iter_messages(channel, limit=1, offset_date=offset_date, filter=InputMessagesFilterUrl):
	print(message.date)
	print('\n')

print('vs')

#Without filter, with offset
for message in client.iter_messages(channel, limit=1, offset_date=offset_date):
	#print(message.date)
	print(message.date)
	print('\n')
```
Output:
```
2019-03-09 15:33:51+00:00


vs
2019-03-09 15:33:51+00:00


vs
2019-03-08 13:34:12+00:00
```
The output for the call with filter, w/o offset and with filter, with offset is exactly the same. So it looks like the offset is being ignored when used with filter.

Thank you for working on this wonderful library.

**Comment by jetiston** [comment]
I have worked around this by getting the id of message using offset_date.
And then using min_id with filter.

**Comment by Lonami** [comment]
Telethon correctly sets the offset:
https://github.com/LonamiWebs/Telethon/blob/a5f5d6ef235409f9757eef4dbc39d210af59d5a2/telethon/client/messages.py#L88-L101

However (surprise!) Telegram completely ignores `offset_date` when you are searching for messages. We probably should implement the workaround in the library.

**Comment by Lonami** [comment]
Funnily enough, it *does* work if you do pass a `q`uery (`search` text).

**Comment by Lonami** [comment]
(That push force is because I *hate* [documentation updates with tiny changes](https://github.com/LonamiWebs/Telethon/commit/7c48857d0c8625d0626c19e2af7fe00c1823f460)).
