### ISSUE TITLE
Automatically call (fixed) catch_up on reconnect

### ISSUE THREAD

**Issue by iranzo** [LonamiWebs/Telethon#1125]
When bot (using bot_token) is stopped and later started, it doesn't act on previously received messages.

Even using catchup, fails to have the messages processed.

**Comment by Lonami** [comment]
If there aren't many updates while the client is disconnected (I tried with up to 20), Telegram seems to send them without asking for them (via `updates.getDifference`).

On disconnection, the library should probably set a "need difference" or "catching up" flag so that any new updates are ignored, and then the library should call `updates.getDifference` itself to fetch them.

In any case (either there are too many updates and Telegram didn't send them, or there isn't a lot and Telegram sent them but we dropped them), we fetch the new difference to get all missed updates. I feel like this would be the best solution.

**Comment by Lonami** [comment]
To support my comment above, we should probably have a callback on disconnection and on connection, so we can handle it properly.

**Comment by iranzo** [comment]
Should this be done via telethon library directly or the programs using it should do?

**Comment by Lonami** [comment]
#1118 could actually enable this for the users to do if they want to. Not sure if it's a better idea.

**Comment by Lonami** [comment]
Important note: each channel has its own `pts`, and currently the library stores any `pts` as the generic one. This is wrong since channels need special care.

**Comment by Lonami** [comment]
More on this, since this issue was made, https://core.telegram.org/api/updates was updated with a lot of useful information. While implementing this, that page should probably be studied.

**Comment by penn5** [comment]
You can also check out my implementation in gitlab.com/telekram/telekram, the file is named UpdateHandler.kt

**Comment by Lonami** [comment]
Not sure if Telethon's license is compatible with that project's, and I'm not sure how far these "permissions" can go. In any case the description on the docs should be good enough.

**Comment by penn5** [comment]
> Not sure if Telethon's license is compatible with that project's, and I'm not sure how far these "permissions" can go. In any case the description on the docs should be good enough.

Well I can give you rights if you like, since I wrote it :P.

**Comment by w1th0utnam3** [comment]
Sorry for hijacking this thread, but it's somewhat related to the problem 
> Even using catchup, fails to have the messages processed.

I registered my event handlers directly after constructing a client. Afterwards I start it and call `catch_up`. However, it doesn't receive any missed events - unless, during a previous session, the bot received a message from the same user while it was running its event loop. It doesn't even have to be a handled message, just any message. This means if I delete the session file, the bot cannot respond to any missed message on the first run until it again receives a message from the user. Is this intended behavior?

My use case is that I actually don't want to have the bot running continuously, only scheduled by a cron job and then it shuts down when it processed any missed events.

**Comment by Lonami** [comment]
The problem with the current catch up implementation is it won't handle fetching updates from channels, only private and small groups. Another issue is that the state is probably not handled correctly (might be updated before being able to use the old one). For usage questions please use the group or StackOverflow.
