### ISSUE TITLE
async with TelegramClient(...).start(...) does not work

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1127]
```
RuntimeWarning: coroutine 'AuthMethods._start' was never awaited
```

And:
```
AttributeError: __aexit__
```

In the line with `async with TelegramClient(...).start(...)`.

---

[Originally reported](https://t.me/TelethonChat/111992) by @iranzo.

**Comment by Lonami** [comment]
Not really worth doing, one can `await client.start()` before and then use `async with client:` which won't reconnect. Implementing this would either somehow subclassing `asyncio.Future` or patching `start()`'s coroutine to have `__aenter__` and `__aexit__`.

**Comment by frankShih** [comment]
> await client.start()

Same issue, I cannot run "quick start" code

```python
    client = TelegramClient('anon', api_id, api_hash)
    await client.start()
    async with client:
        # Getting information about yourself
        me = await client.get_me()

        # "me" is a user object. You can pretty-print
        # any Telegram object with the "stringify" method:
        print(me.stringify())

        # When you print something, you see a representation of it.
        # You can access all attributes of Telegram objects with
        # the dot operator. For example, to get the username:
        username = me.username
        print(username)
        print(me.phone)

        # You can print all the dialogs/conversations that you are part of:
        async for dialog in client.get_dialogs():
            print(dialog.name, 'has ID', dialog.id)

```

Got `TypeError: 'async for' requires an object with __aiter__ method, got coroutine` when I try `get dialogs()`

Any suggestions?

**Comment by Lonami** [comment]
`async for` with `get_` is only supported in v2, not in the released version.

**Comment by frankShih** [comment]
> `async for` with `get_` is only supported in v2, not in the released version.

Cannot understand what to do next based on your suggestion. (not English native speaker)
So, maybe I should:
1. update my module to V2?
2. re-write the sample code for Release version?

Is there any document talking about this? 
I just want to run the 'quick start' sample code.

**Comment by Lonami** [comment]
The documentation has both a stable and latest version. The stable one has working examples. V2 is broken currently. Use `iter_dialogs` instead.
