### ISSUE TITLE
conversation weird behaviour when using a loop

### ISSUE THREAD

**Issue by painor** [LonamiWebs/Telethon#1128]
When trying to do a while True loop inside a conversation and using conv.send_* inside of the loop the old updates are ignored and only the most recent one is treated. this is a sample code to reproduce the issue :
```
while True:
    msg = await conv.get_response()
    if msg.media:
        await conv.send_message("file added")
    else:
        await conv.send_message("please send a media file")

```

**Comment by Lonami** [comment]
Important detail, one must forward a lot of messages at once to make it happen more easily.
