### ISSUE TITLE
Which event is triggered when a secret message arrives?

### ISSUE THREAD

**Issue by rohezal** [LonamiWebs/Telethon#1132]
I am looking into the telegram crypto api and wanted to decrypt a message. Doesn't seem to hard, it is mostly DH, AES and sha256. There is an event when a normal message arrives. Is there an event when an encrypted message or a the Diffie Hellman request is noticed? Is there there a hook, where I can just call my function and send the required data? This is more a question than an issue and I am sorry, but I did not know where to ask it.

**Comment by Lonami** [comment]
Secret chats are not supported by Telethon yet. See #537.

**Comment by rohezal** [comment]
I know, but I would like to help. Is there an event which is triggered when the other side is requesting a diffie hellman key exchange? Maybe I could contribute some code for the key exchange. From reading the doku it looks like, that they exchange one AES key and then prepare 100 extra AES keys for forward secrecry. Seems manageable to implement.

**Comment by Lonami** [comment]
I never looked into it myself, so I can't help you. The main issue is implementing secret chats, though. Secret message events would come better.

If you feel adventurous, try the official documentation or inspecting the source code of some other implementations.
