### ISSUE TITLE
NewMessage, chats filter works only without spaces

### ISSUE THREAD

**Issue by kava93** [LonamiWebs/Telethon#1137]
Hello,
I'm having some issues while checking new messages coming from my channel if its name contains spaces. If I remove spaces from my channel's name and I adjust the code all works well.
Why?

```python
@client.on(events.NewMessage(chats="My Channel Name"))
```

**Comment by Lonami** [comment]
If you use a string it's either the username or the exact channel title. Using titles is discouraged because anyone else can use that title. Ideally you use the ID.

**Comment by kava93** [comment]
I've tried chat = event.message.input_chat inside the handle and I get a message like this.

InputPeerChannel(channel_id=11xxxx2107, access_hash=873643xxxxx889281)

Using the id that I find after channel_id will generate an error. 
ValueError: Cannot find any entity corresponding to "11xxxx2107"

How can I get the ID of the source chat? 

Thanks

**Comment by kava93** [comment]
I got my channel ID with `sourceid = event.message.input_chat.channel_id`, then I've declared it in a variable called `idChannel1` at the start and then I've compared it inside the handle with `(sourceid == idChannel1)` .
It works good! ;-)
