### ISSUE TITLE
Join public channel with bot

### ISSUE THREAD

**Issue by autogestion** [LonamiWebs/Telethon#1139]
Telegram API allows bot to join public channels and get messages from them
https://core.telegram.org/bots/faq#what-messages-will-my-bot-get
But telethon restrict this activity. Why so?

**Comment by Lonami** [comment]
> Telegram API allows bot to join public channels

Not true.

> and get messages from them

Receive updates, yes.

> But telethon restrict this activity

No, it doesn't. Bots cannot join anything. They can be added though.

**Comment by xoelop** [comment]
Hi! I'm trying to add a bot to my own channel, that I've previously created. This is my code:

```
def create_channel(title: str = '', about: str = ''):
    with client:
        try:
            result = client(functions.channels.CreateChannelRequest(
                title=title,
                about=about,
                broadcast=True,
                megagroup=False,
            ))
            channel = result.chats[0]
            channel_id = channel.id
            add_user = client(functions.channels.InviteToChannelRequest(
                channel=channel_id,
                users=['NoiceJobsBot']
            ))

            client.edit_admin(channel_id,
                            user=int(os.getenv('TELEGRAM_NOICEJOBSBOT_ID')),
                            change_info=True,
                            post_messages=True,
                            edit_messages=True,
                            delete_messages=True,
                            ban_users=True,
                            invite_users=True,
                            pin_messages=True,
                            add_admins=False,)
            # breakpoint()
            invite_link = resolve_invite_link(channel_id)
            print(invite_link)
        except:
            raise
```

I can't add it, because it can only be an admin. It fails in `add_user = client...` and the only params that `functions.channels.InviteToChannelRequest` takes are `channel` and `users`

How should I do it? I can't find any answer online, other than the fact that bots can only be users in channels.

Thanks!! I'm finding this library aaawesome =)

**Comment by Lonami** [comment]
I'm glad you like the library, but this is not the right place to ask. Use StackOverflow or [the group](https://t.me/TelethonChat).

**Comment by Keramatfar** [comment]
> Hi! I'm trying to add a bot to my own channel, that I've previously created. This is my code:
> 
> ```
> def create_channel(title: str = '', about: str = ''):
>     with client:
>         try:
>             result = client(functions.channels.CreateChannelRequest(
>                 title=title,
>                 about=about,
>                 broadcast=True,
>                 megagroup=False,
>             ))
>             channel = result.chats[0]
>             channel_id = channel.id
>             add_user = client(functions.channels.InviteToChannelRequest(
>                 channel=channel_id,
>                 users=['NoiceJobsBot']
>             ))
> 
>             client.edit_admin(channel_id,
>                             user=int(os.getenv('TELEGRAM_NOICEJOBSBOT_ID')),
>                             change_info=True,
>                             post_messages=True,
>                             edit_messages=True,
>                             delete_messages=True,
>                             ban_users=True,
>                             invite_users=True,
>                             pin_messages=True,
>                             add_admins=False,)
>             # breakpoint()
>             invite_link = resolve_invite_link(channel_id)
>             print(invite_link)
>         except:
>             raise
> ```
> 
> I can't add it, because it can only be an admin. It fails in `add_user = client...` and the only params that `functions.channels.InviteToChannelRequest` takes are `channel` and `users`
> 
> How should I do it? I can't find any answer online, other than the fact that bots can only be users in channels.
> 
> Thanks!! I'm finding this library aaawesome =)

Did you find any solution?

**Comment by fukemy** [comment]
any solution now? I want to join my bot to other channel without admin permission 🥹
