### ISSUE TITLE
Smarter initial connection

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1140]
Currently the library connects to a predefined data center and hopes it's right. If it's not, it gets an error and connects to a different one. It would be wise to get the closest data center and connect to it directly the first time. Next time, use the one given from the session file.

**Comment by SahandAkbarzadeh** [comment]
@Lonami i don't know if it's the best way to do it but you can use asyncio.wait ( Pormise.Race in javascript ) and ping to all DCs simultaneously and choose the first one to respond.

**Comment by Lonami** [comment]
No, that's not the right way. There is a request specifically made to get the nearest datacenter.

**Comment by SahandAkbarzadeh** [comment]
problem is, but we don't know the nearest server before sending the request.
so we call all the data centers at once, when one of them arrives ( fastests one ) it cancels other ones and we can find the real nearest server from that response.

**Comment by Lonami** [comment]
The point is using Telegram's notion of "nearest" to avoid "user migrated error", which is what takes long (doing all the steps to get there), not connecting. Connection probably varies between 30 and 100ms which is not noticeable.

**Comment by Lonami** [comment]
Not happening, the current behaviour is good enough.
