### ISSUE TITLE
Telethon don't reuse session file with MTProto connection

### ISSUE THREAD

**Issue by DogX123** [LonamiWebs/Telethon#1148]
Hi!
I'm try to reuse session file in my code with uses MTProto Proxy, but it's not working(
I alredy run this code, and in current directory already created mtproxy.session, but on new progamm run session file don't useing, and I recive messege to input my phone number to send on it a OTP (one time password)
DEBUG:
```
INFO:telethon.network.mtprotosender:Connecting to proxy.digitalresistance.dog:443/TcpMTProxy...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
DEBUG:telethon.network.mtprotosender:Starting send loop
...
INFO:telethon.client.updates:Failed to get current state: AuthKeyUnregisteredError('The key is not registered in the system (caused by GetStateRequest)')
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
```
```python
api_id = XXXXX
api_hash = 'ff2c1dXXXXXXXXX4b72a58828db'
DC1_ip = '149.154.167.40'
DC_port = 443
proxy_ip = 'proxy.digitalresistance.dog'
proxy_port = 443
secret = 'd41d8cd98f00b204e9800998ecf8427e'
proxy = (proxy_ip, proxy_port, secret)
session_path = os.getcwd() + '\mtproxy'
print(session_path)
client = TelegramClient(session_path, api_id, api_hash, proxy=(proxy_ip, proxy_port, secret),
                        connection=connection.tcpmtproxy.ConnectionTcpMTProxy)
client.session.set_dc(1, DC1_ip, DC_port)


@client.on(events.NewMessage(chats='XXCX'))
async def normal_handler(event):
    print(event.message)
    print(event.message.to_dict()['message'])
    if event.message.to_dict()['message'] == '1234kill':
        client.disconnect()
    print(event.message.to_dict()['media'])
    if event.message.to_dict()['media'] != 'None':
        f_name = '{}'.format(await client.download_media(event.message))
        print('Download file {} done!'.format(f_name))


try:
    client.start()
     #code..code
    client.run_until_disconnected()
finally:
    client.disconnect()
```

**Comment by Lonami** [comment]
There's a few things wrong with the code (unescaped `'\'`, horribly inefficient and unnecessary `.to_dict()`…) but I guess the main issue is, if you create a session file through that proxy, it will fail, right? Or does it not happen immediately and you have to wait for it to happen? How long? You may have cut off important parts from the debug log (what was in the `...`?) too.

**Comment by DogX123** [comment]
`While writing the answer and preparing clean debug examples, I caught FloodWaitError for 2.5 hours)))`
Hello and thank you for your responsiveness!
Yes, the main issue is, if I create a session file through that proxy, it will fail, after rerun my programm. In original Telegram in Active Session I'm starting to see the session I just opened. After I run `client.disconnect ()` and finish the program, I still see my session in Active Session in original Telegram. 
After some time 15, 20 minutes, 1 hour, I start the program again, after making some edits to the code (not related to the session settings), and the Telegram again asks me to enter the phone number and sends the verification code.
An additional question: if I change MTProxy (Ip, port), this will be considered a change in settings and will this be a reason to send me a new verification code? Just these proxies do not live long or often fail.
Clarification: the `os.getcwd` method in OS Windows returns the full path without the closing character slash "\" at the end, for this reason I use "\mtproxy"
Clarification2: about `.to_dict()` - after construction `event.message.` I have the following list of methods: 
`.to_dict()
.par
.main
.not
.if
.ifn
.ifnn
.print
.return
.while
`

Full debug of "first start" in file first_debug.txt   - will be in 2.5 hours
And debug of "secon start", after 5 min in file second_debug.txt  - will be in 2.5 hours

![image](https://user-images.githubusercontent.com/49204256/55463800-7424c180-5602-11e9-95bf-d689951122bc.png)

**Comment by Lonami** [comment]
Is there any reason why you do `client.session.set_dc(1, DC1_ip, DC_port)`? That's what's clearing the authorization key, which is different for each data center, and if you change the data center to use, the authorization key is removed...

**Comment by DogX123** [comment]
Thank you very much! Now the session is not lost! HOORAY!
