### ISSUE TITLE
How to use MTProxy???

### ISSUE THREAD

**Issue by vhdm** [LonamiWebs/Telethon#1149]
@Lonami 
Why is not there anyone, telling us how to use MTProxy?
my code is:

`from telethon import TelegramClient, events, sync
from telethon.tl.functions.help import GetProxyDataRequest
from telethon.network.connection import (
    ConnectionTcpMTProxyRandomizedIntermediate
)

api_id = 213958
api_hash = 'bc2eb25af3547608bd12b3e8447c01ef'
connection = ConnectionTcpMTProxyRandomizedIntermediate
proxy=('50.214.60.21',443,'abcd6666abcd6666abcd6666abcd6666')
client = TelegramClient('session_name', api_id, api_hash,proxy=proxy,connection = connection)
client.start()
`

**Comment by Lonami** [comment]
Because they're experimental.

**Comment by hastirad** [comment]
hi,
Could you solve this problem?

**Comment by Lonami** [comment]
The documentation now explains how.

**Comment by rradn** [comment]
Thanks

**Comment by vhdm** [comment]
@rradn 
hi, yes solved...

**Comment by Shahrooze** [comment]
Can you explain how? @vhdm

**Comment by vhdm** [comment]
@Shahrooze 

`from telethon import TelegramClient, sync, utils, connection
import telethon
mtproto = ('host', 'port', 'secret')
mtproto_connection = connection.tcpmtproxy.ConnectionTcpMTProxy
client = telethon.TelegramClient('session',api_id='api_id',api_hash='api_hash',proxy=mtproto,connection=mtproto_connection)
client.connect()
client.start()`
