### ISSUE TITLE
How can I disable save in memory for a session?

### ISSUE THREAD

**Issue by SergeyNaz** [LonamiWebs/Telethon#1154]
When I use client.session.entities.enabled = False, I get an error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SQLiteSession' object has no attribute 'entities'

Is it deprecated attribute?

**Comment by Lonami** [comment]
You can't. There shouldn't be such thing anyway, it's loaded from disk when needed.
