### ISSUE TITLE
Is there any method to clear cache from session file? It uses so many memory space

### ISSUE THREAD

**Issue by SergeyNaz** [LonamiWebs/Telethon#1155]
I found this method client.session.entities.clear_cache(entity=None), but seems that it's deprecated

**Comment by Lonami** [comment]
No, there isn't any method to clear cache from session file. The memory consumption shouldn't be coming from the session file, which is an in-disk file. Telegram objects, however, may be pretty large, and Python is garbage-collected. If you can identify what is consuming so much memory, I may be able to look into it.
