### ISSUE TITLE
sending replied message 

### ISSUE THREAD

**Issue by keyvanvafaee** [LonamiWebs/Telethon#1156]
for forwarding a replied message we used 

**'await client.forward_messages(to_w  , event.message.reply_to_msg_id , event.message.to_id)'**

it's seems  telethon has no  option to send replied message to my friends , for example in pyrogram we can do such this with "as_copy = True" , so why telethon hasn't this option ?! 

and another  issue is i think telethon also havn't option to change profoile picture with just repling on image

**Comment by Lonami** [comment]
Telethon does offer that feature in a different way. Telethon can do everything any other MTProto library can.

**Comment by Kyle2142** [comment]
@keyvanvafaee if you read the docs you'd have seen that `send_message` can do this.
The reason it isn't part of forwarding should be obvious: it isn't a forward if its a copy

**Comment by keyvanvafaee** [comment]
I read it , i saied “send replied message” , in sending message there is no problem but do tou ever test it for replied message?? In replied message you have message id and sender id and some another info that i think this info don’t help for sending replied message
