### ISSUE TITLE
get channel messages by channel id

### ISSUE THREAD

**Issue by mahdifarshid** [LonamiWebs/Telethon#1161]
hi 
for message in client.iter_messages('link'):
    print(message)

this code works with channel link bot not works with channel id

**Comment by Lonami** [comment]
Good job.

**Comment by Lonami** [comment]
There is no bug here, therefore, this shouldn't be an issue.

**Comment by mahdifarshid** [comment]
can i get private channel messages?
I am a member of that channel

**Comment by Lonami** [comment]
**The issues section is not for questions.**
