### ISSUE TITLE
Downloading photos fails on 1.7 (layer 98)

### ISSUE THREAD

**Issue by K900** [LonamiWebs/Telethon#1164]
https://github.com/LonamiWebs/Telethon/blob/master/telethon/utils.py#L637 sets `thumb_size` to `''`, which makes Telegram throw `FILE_ID_INVALID` - the correct solution is to set it to the right `type` value from `location.sizes`, e.g. `location.sizes[-1].type` (assuming the sizes are always sorted, which I'm not actually sure of).

**Comment by Lonami** [comment]
I (incorrectly) assumed that `''` would mean the photo file itself, largest size, similar to documents. The library probably needs a new way now to indicate the size to download, since passing a `PhotoSize` will no longer work. Maybe that should be documented under breaking changes too.

**Comment by K900** [comment]
I'm actually not sure how it works now, because it seems like not all `type` values actually work? At least I have an example message with a photo that refuses to download with `location.sizes[-1].type`. I'll investigate more tonight (Europe time).

**Comment by Lonami** [comment]
In the past, photo sizes had a `FileLocation` with enough information to download that one size. This is no longer the case, and file locations are "to be deprecated". Seems like they're cleaning up the way we work with files.

**Comment by K900** [comment]
Yeah, the old way still works. Looking at tdesktop's source code, it seems like the new way _might_ accept [a null byte](https://github.com/telegramdesktop/tdesktop/blob/bec39d89e19670eb436dc794a8f20b657cb87c71/Telegram/SourceFiles/ui/image/image_location.cpp#L96)?
