### ISSUE TITLE
[Bug] libssl doesn't properly handle a nonexistent libssl.so on Linux

### ISSUE THREAD

**Issue by jcjordyn130** [LonamiWebs/Telethon#1167]
For some reason ```ctypes.util.find_library``` returns an improper filename for libssl.so, whenever libssl tries to use this it throws an OSError as listed below in the traceback. I'm testing this using the latest code as of commit 166697664671ac29a16380ac308378b47569e051.
```
>>> from telethon import TelegramClient, sync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jordyn/.local/lib/python3.6/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "/home/jordyn/.local/lib/python3.6/site-packages/telethon/client/__init__.py", line 12, in <module>
    from .telegrambaseclient import TelegramBaseClient
  File "/home/jordyn/.local/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 9, in <module>
    from ..crypto import rsa
  File "/home/jordyn/.local/lib/python3.6/site-packages/telethon/crypto/__init__.py", line 6, in <module>
    from .aes import AES
  File "/home/jordyn/.local/lib/python3.6/site-packages/telethon/crypto/aes.py", line 11, in <module>
    from . import libssl
  File "/home/jordyn/.local/lib/python3.6/site-packages/telethon/crypto/libssl.py", line 13, in <module>
    _libssl = ctypes.cdll.LoadLibrary(lib)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.45: cannot open shared object file: No such file or directory
```

**Comment by Lonami** [comment]
That's interesting. So, does your Linux install have a `libssl` usable at all and `ctypes.util.find_library` just fails to find the *correct* one, or it tells you there's one when there isn't any? Also, what Linux distribution version are you using? I can see Python 3.6.

**Comment by jcjordyn130** [comment]
My libssl.so is located at /usr/lib/libssl.so which is a symlink to /usr/lib/libssl.so.1.0.0, I'm using Solus at the moment.

**Comment by Lonami** [comment]
Perhaps manually following symbolic links will work, then?

**Comment by jcjordyn130** [comment]
```
jordyn@Yoshi /usr/lib $ ls -l -a libssl.so
lrwxrwxrwx 1 root root 15 Mar  4 18:25 libssl.so -> libssl.so.1.0.0
jordyn@Yoshi /usr/lib $ file libssl.so.1.0.0
libssl.so.1.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a0734f5f29f21b8bcc8bc74bf39526368e1c1e5b, stripped
```

Manually following the symlink does work.

**Comment by Lonami** [comment]
Cool, that will be better than simply ignoring the fact it exists and falling back to the slow `pyaes`.

**Comment by Lonami** [comment]
Well, the [os.path.realpath on Windows does not follow symbolic links](https://bugs.python.org/issue9949) issue is a bit… Disappointing. So old, [and it's still not fixed](https://github.com/python/cpython/blob/74510e2a57f6d4b51ac1ab4f778cd7a4c54b541e/Lib/ntpath.py#L523)!

I guess we can borrow the solution from [Python os.path.realpath() for symlink in Windows](https://stackoverflow.com/a/48416561), just to make sure our solution works.

**Comment by Lonami** [comment]
Although first we have another problem, figuring where the library lives in. Because Python doesn't expose that information, just the name…
