### ISSUE TITLE
Make a new message.file property

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1168]
This will return a `custom.File(media)` with only properties in it such as:
* `id` for `file_id`.
* `name` for file name.
* `duration` for songs and videos.
* `mime_type` is self-explanatory.
* `ext` for the extension from the mime.
* …etc

This was originally suggested in https://t.me/telethonofftopic/228277.

A wrapper `custom.File` class with only properties seems a lot easier than patching, say, `Document` and `Photo`. On an unrelated note, patching types needs some work to make it reasonable.

We should allow the user use this type to send media, and maybe let the user create their own `custom.File` from disk files which support setting mime etc. more conveniently.

**Comment by YouTwitFace** [comment]
+1
