### ISSUE TITLE
Wrong update handling

### ISSUE THREAD

**Issue by sophiehatter** [LonamiWebs/Telethon#117]
Hello.

I found some strange thing: https://github.com/LonamiWebs/Telethon/blob/86d45cc27675df5d43928961bb1fb1e44e6db486/telethon/network/mtproto_sender.py#L120. You get list of updates, but only first elements passed to updates thread. Other updates are lost. It is not right.

Good solution is return list of updates and iterate it in update thread. Otherwise you will get random update lost from e.g. supergroups.

**Comment by Lonami** [comment]
> Other updates are lost. It is not right.

Are you sure about this? If there is [no request and **one** update](https://github.com/LonamiWebs/Telethon/blob/86d45cc27675df5d43928961bb1fb1e44e6db486/telethon/network/mtproto_sender.py#L98) (because updates are read [*one by one*](https://github.com/LonamiWebs/Telethon/blob/86d45cc27675df5d43928961bb1fb1e44e6db486/telethon/network/mtproto_sender.py#L242), as far as I know), the loop will stop receiving more updates, hence exiting after the first one arrives.

However, if you would please mind to test yourself to make sure, you could add some code like:
```python
    def receive_update(self, timeout=timedelta(seconds=5)):
        """Receives an update object and returns its result"""
        updates = []
        self.receive(timeout=timeout, updates=updates)
        if len(updates) != 1:
            print('Oops! Got {} updates instead one'.format(len(updates)))
        return updates[0]
```

**Comment by sophiehatter** [comment]
> Are you sure about this?

Yes. I have tested this before create issue. Before library patch I lost some updates from supergroups, while desktop client receives them all via updates only (I saw this via debug logs).

> If there is no request and one update (because updates are read one by one, as far as I know), the loop will stop receiving more updates, hence exiting after the first one arrives.

IDK, it's Telegram ¯\_(ツ)_/¯ (e.g. updates_tg have vectors, but I don't saw more than 1 element). Server sends more then one update and it is not good skip them.

> However, if you would please mind to test yourself to make sure, you could add some code like.

Yes. I'm already did it.

`raw update 3
[updates_tg#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:date seq:int = Updates, updates_tg#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:date seq:int = Updates, updates_tg#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:date seq:int = Updates]
 `

I tested patched library (v0.10) for all night, now it work perfectly, all messages are receives. You can try own tests by writing simply handler and joining in popular supergroups (with 1-5k messages/daily).

**Comment by Lonami** [comment]
Thanks for the report then.

**Comment by joplrw10** [comment]
Is this a potential workaround for the problems with receiving messages from supergroups?

**Comment by Lonami** [comment]
> Is this a potential workaround for the problems with receiving messages from supergroups?

Well more updates should be received with this change I guess (I didn't even know it could happen but it does). May not affect supergroups though.
