### ISSUE TITLE
Invoke file download and upload methods in parallel

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1170]
People claim downloads and uploads are slow, and that threads make this faster. This is strange and would need some testing. However, Telethon should leverage `asyncio`'s capabilities to download and upload several file *parts* at once, and see if this makes a difference.

**Comment by painor** [comment]
I have tested downloads with create_task and it was very very fast (max download speed). if there are a lot of tasks at the same time you get flood waited though so I think there should be a download worker of some sort that defaults to 4 (magical number). more workers = more speed = higher chance of getting flood waited.

**Comment by painor** [comment]
also, I am not sure if there is a way to cancel downloads/uploads currently but adding one might be a good idea as well.

**Comment by Lonami** [comment]
If you create a task for the download or upload method call, you should be able to `task.cancel()` it, similar to how every other method works.

**Comment by Numenorean** [comment]
How can I make this?

**Comment by Lonami** [comment]
You would modify `download_file` to likely make a smart use of `create_task`, `gather` or `wait` to cause several parts to be downloaded at once, or zipping several `iter_download`.

**Comment by RT4U** [comment]
#1372 I am currently stuck with iter_download, this telegram rpc has been a trial & error for me when it comes to multi connection downloads

**Comment by Lonami** [comment]
Solved by a 3rd party solution: https://gist.github.com/painor/7e74de80ae0c819d3e9abcf9989a8dd6.

Closing, so Telethon's upload and download will likely remain simple.
