### ISSUE TITLE
New archive methods

### ISSUE THREAD

**Issue by YouTwitFace** [LonamiWebs/Telethon#1173]
Now that telegram supports archiving chats and telethon has already updated to layer 99, I was thinking about how telethon can support them in a user friendly way. I was thinking about `Dialog.archive()` and `client.get_archived_dialogs()` and `client.iter_archived_dialogs()`.

**Comment by Lonami** [comment]
We have to decide what terminology we want. The user-facing localization calls it "archive", but the API calls them folder, which I personally think is better.

`Dialog.archive(...)` is a good idea, naming aside.

A new method name sounds useless. `iter_dialogs` should simply have a new parameter. Depending on how it works, I was planning on yielding both `Dialog` and `Folder` instances, but that may be annoying.

In addition, we should offer a way to get dialogs by peer ID. This is useful in a few situations.

**Comment by YouTwitFace** [comment]
Closed in 313caf440eb711ec6ec08d8a34fe2535d73680cd.

**Comment by Lonami** [comment]
Good call, thanks.
