### ISSUE TITLE
Telethon: Leave a chat not a channel request

### ISSUE THREAD

**Issue by amir3code** [LonamiWebs/Telethon#1176]
I've actually asked this on [stackoverflow](https://stackoverflow.com/questions/56072892/telethon-leave-a-chat-not-a-channel-request) but almost no body even did a comment! Please answer!

Hello I am using the `Telethon` Telegram client library. I need to leave a `Chat` but there is only one request for leaving and that is `LeaveChannelRequest`.  
But as the name says, It is for `Channels` and not `Chats`.  

`Channels` have both `chat_id` and `access_hash` but `Chats` only have `chat_id`.

How can I leave a `Chat`?

I have checked the `tdlib` library and it has a thing called `CloseChat` which seems to suit what I need, How can I use it here in `telethon`?
https://javadoc.tlgrm.ru/org/drinkless/td/libcore/telegram/TdApi.CloseChat.html

Thanks in advanced.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/blob/1e17ef1c985eda8569c867c829f0a8f17c823336/.github/ISSUE_TEMPLATE.md
```
DON'T ASK QUESTIONS HERE.

This place is for issues with the library, so please make sure that:
1. The error is in the library's code, and not in your own.
2. You have already searched for your error on existing issues.
3. You are testing with upstream code (pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip).

If you have a question, ask in https://stackoverflow.com or find the link for the Telegram group in the description of https://t.me/TelethonUpdates. Enhancement ideas are currently welcome, too.

If you paste code, please put it between three backticks (`):
```python
# python code here
```

Once you have read and understood this, delete all this text and detail whatever issue you are posting.
```

No exceptions.
