### ISSUE TITLE
Friendly method to access all profile photos

### ISSUE THREAD

**Issue by PoriNiki** [LonamiWebs/Telethon#1179]
Hi. I'm looking for a method that downloads profile picture of users but I want ALL profile photos of a user. The method "download_profile_photo" in downloads.py and also the attrib of profile_photo in the user object, just contains the last photo of each user. 

thanks.

**Comment by Lonami** [comment]
It would be interesting if `download_profile_photo` let you chose which photo to download, but the library currently doesn't even offer a way to see all photos of a user (you have to use [`GetUserPhotosRequest`](https://lonamiwebs.github.io/Telethon/methods/photos/get_user_photos.html) manually).

So, the real suggestion here is, have a way to see all the profile photos of a user more easily.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/9ea686ab14ceab596cff81f54f86efd6cb375813
