### ISSUE TITLE
Support markdown parser via some external module

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#118]
Would be nice to have back the ability of markdown parsing, but better as a external module.

**Comment by LarsFox** [comment]
It was a great Markdown parser you wrote! Should those who depend on it much refrain from updating to 0.11.3?

**Comment by Lonami** [comment]
> It was a great Markdown parser you wrote!

No, emojies failed horribly. I still need to figure out how `'👨‍👩‍👧‍👧'` is 11 "characters" long, `'😀'` is 2, `'👍🏻'` is 4…

**Comment by LarsFox** [comment]
From what I have got, once the symbol is _something which looks like emoji,_ its length is 2 for the bot.

I wrote a [gist](https://gist.github.com/LarsFox/e0ab1e3dc6c04b31584254d0118ffd5d) and
fed some samples to the [@JsonDumpBot](https://t.me/JsonDumpBot). So far everything was ok.

Telegram also removes trailing whitespaces, so the tests starting with `"    "` fail, but I guess it is not a big problem.

**Comment by Lonami** [comment]
> *something which looks like emoji*

Things can get tricky I guess, see for instance [this variable](https://github.com/UnigramDev/Unigram/blob/4430ce928ca9d60ec0636db9277967ba2764a19a/Unigram/Unigram/Common/MessageHelper.cs#L347). A huge regex comparison. I also [found this](https://stackoverflow.com/a/33417311/4759433) which is way more compact and slightly more accurate since it also has the end of the ranges, but it's not so precise:
```python
emoji_pattern = re.compile(
    '['
    '\U0001F600-\U0001F64F'  # emoticons
    '\U0001F300-\U0001F5FF'  # symbols & pictographs
    '\U0001F680-\U0001F6FF'  # transport & map symbols
    '\U0001F1E0-\U0001F1FF'  # flags (iOS)
    ']+', flags=re.UNICODE
)
```

> Telegram also removes trailing whitespaces

Easy cake, we can perform the `.strip()` ourselves too.

Besides all this, nice gist, it does seem to work. But I'm not integrating it into Telethon, maybe keep a separate `telethon-markdown` module. As far as I know, nested markdown is not possible in Telegram so it should be fairly simple to implement it. Are you up for the task? You wrote this emoji thing after all :)

**Comment by Lonami** [comment]
This is now being worked on https://github.com/LonamiWebs/Telethon/tree/md-parsing.

**Comment by hamid07ss** [comment]
@Lonami

can i send this `@bold test` with Telethon Bot?
i want send a message using another inline bot like @vote

@Linksazibot share-3381125-20981201
