### ISSUE TITLE
GetNotifySettingsRequest always returns default struct

### ISSUE THREAD

**Issue by ShacharWeis** [LonamiWebs/Telethon#1181]
I'm trying to use the API to figure out if a user has notifications enabled or not. 
When I run this code:

`Notify = client(functions.account.GetNotifySettingsRequest(12345678))`

I always get this value:

`PeerNotifySettings(silent=None, sound=None, mute_until=None, show_previews=None)`

Regardless of the user's notification settings.

Ideas?

**Comment by Lonami** [comment]
You are using raw API, which means what you get is what Telegram returns. Please use the group for these questions.

**Comment by ShacharWeis** [comment]
What is "the group" ?

**Comment by Lonami** [comment]
Right, with the new issue template people can more easily miss that. https://t.me/TelethonChat.
