### ISSUE TITLE
Contacts Joined Telegram

### ISSUE THREAD

**Issue by SmartManoj** [LonamiWebs/Telethon#1184]
Is there any event to listen for `Contacts Joined Telegram` currently? I didn't find anything in docs.

**Comment by Lonami** [comment]
There's probably a [`events.Raw`](https://tl.telethon.dev/types/update.html) for it, but I'm not sure which. We can either update the docs to point out some useful ones or we can create a friendly `event` for it, both of which fall under improvements.

**Comment by Lonami** [comment]
I don't think this is worth adding, because you can do:
```
@client.on(events.Raw)
async def handler(update):
    if (isinstance(update, types.UpdateNewMessage)
            and isinstance(update.message, types.MessageService)):
        ...  # code using the update with the contact here
```

And be done. It's not like other events which are a lot more complex and can come in a hundred different update types.

**Comment by SmartManoj** [comment]
Is it working ?
Not triggered for me.

**Comment by SmartManoj** [comment]
Reopen

**Comment by Lonami** [comment]
I'm pretty sure the solution is to listen for `events.Raw` and check if there's a `MessageService` with `action` of type `MessageActionContactSignUp`. Closing in favour of that.

**Comment by alexvais** [comment]
Hi @Lonami !

Thanks for your help but i dont find the action of type: "MessageActionContactSignUp".

Can you provide more details on how implement a handler to listen Contact Sign Up event?

Thanks!!

**Comment by Lonami** [comment]
The issues sections is for issues with the library, and the type you mention still exists as of layer 124. Please ask questions in the official group or StackOverflow.
