### ISSUE TITLE
Problem Send Message

### ISSUE THREAD

**Issue by chri1304** [LonamiWebs/Telethon#1185]
Hello, I'm trying to send a telegram message through a Thread.
This is my code:
---------------------
```
class TelegramUser(Thread):
  def __init__(self,conn,telegramClient):
     Thread.__init__(self)
     ...........
     client.send_message('phone', 'message')

  def run(self):
     client.send_message('phone', 'message')
```
---------------------

The problem is that, the first method (in the  __init__ of the thread) sends correctly the message.
The second one (in the run method), shows the following error:
```
RuntimeError: There is no current event loop in thread 'Thread-1'.
/usr/lib/python3.6/threading.py:949: RuntimeWarning: coroutine 'send_message' was never awaited
```

How can I resolve this problem? I need to call the send_message method inside my thread (or inside a method of its).

Thank you very much!

**Comment by Lonami** [comment]
How is this a enhancement‽

**Comment by chri1304** [comment]
I'm sorry!
I have make a mistake with the section!

**Comment by Lonami** [comment]
See groups in https://t.me/TelethonUpdates.

**Comment by chri1304** [comment]
Thank you very much for your support.
The last year, I developed a GATE with this library (it was between more clients and the Telegram servers) and it worked very well.
At the moment it doesn't work.
In my code it creates a Thread that connects to the telegram server. In the run() function of this thread, it calls the method:
`self.client.add_update_handler(self.update_handler)`

And then the method update_handler in the Thread manages the update...

The error is the following:
`self.client.add_update_handler(self.update_handler)
AttributeError: 'TelegramClient' object has no attribute 'add_update_handler'`

Why?

Thank you very much!

**Comment by Lonami** [comment]
Again, this is not the right place to ask how to use the library and you should have read the changelog before updating. Please use the group linked above or StackOverflow instead.
