### ISSUE TITLE
how i can send message to my contact whit telethon

### ISSUE THREAD

**Issue by arta66** [LonamiWebs/Telethon#119]
when i use this command for see contact 
`result = client.invoke(GetContactsRequest(""))`
`print(result)`
i see this result :
`(contacts.contacts (ID: 0x6f8b8cb2) = (contacts=['(contact (ID: 0xf911c994) = (user_id=334412783, mutual=False))'], users=['(user (ID: 0x2e13f4c3) = (is_self=None, contact=True, mutual_contact=None, deleted=None, bot=None, bot_chat_history=None, bot_nochats=None, verified=None, restricted=None, min=None, bot_inline_geo=None, id=334412783, access_hash=-8113372651091717470, first_name=khood, last_name=None, username=Mosafer575, phone=19132594548, photo=(userProfilePhoto (ID: 0xd559d8c8) = (photo_id=1436291966805583785, photo_small=(fileLocation (ID: 0x53d69076) = (dc_id=1, volume_id=803110857, local_id=86736, secret=1232685751818265379)), photo_big=(fileLocation (ID: 0x53d69076) = (dc_id=1, volume_id=803110857, local_id=86738, secret=3801220285627155105)))), status=(userStatusOffline (ID: 0x8c703f) = (was_online=2017-06-16 13:09:57)), bot_info_version=None, restriction_reason=None, bot_inline_placeholder=None, lang_code=None))']))`
now how i can send one message fore this friend with first_name my friend or user_id or phone or other details in my contact??? i see this [page ](https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/interactive_telegram_client.py)but I din't notice. please help me with simple code

**Comment by Lonami** [comment]
> `users=['(user (ID: 0x2e13f4c3) …`

The `users` list has the user you want to talk to. So you get that user:
```python
user = result.users[0]
```

And you just use it to `.send_message(user, message)`.

**Comment by Lonami** [comment]
> please help me with simple code

Also if you're relatively new to Python you may want to read [Dive Into Python 3](http://www.diveintopython3.net/).
