### ISSUE TITLE
Timeout with proxy does not work

### ISSUE THREAD

**Issue by proroot** [LonamiWebs/Telethon#1192]
When using a proxy and transfer timeout = 5, the script does not terminate after 5 seconds, but waits for more than a minute and then only terminates

**Comment by proroot** [comment]
Why send s.setblocking (False) if it timeout overlaps? in place of it s.settimeout (timeout)?

File connection.py function _connect

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/blob/58f3225fa6b2fca488e0a6f4495582721d9dec55/telethon/network/connection/connection.py#L64

Is needed for `asyncio`, just below:
https://github.com/LonamiWebs/Telethon/blob/58f3225fa6b2fca488e0a6f4495582721d9dec55/telethon/network/connection/connection.py#L65-L69

Which has its own way of controlling the `timeout`. Unfortunately, [PySocks doesn't behave correctly](https://github.com/Anorov/PySocks/issues/121), and it blocks for longer than it should. We must either wait for `PySocks`' developer to respond, or to use an alternative proxy library.

**Comment by proroot** [comment]
And what will happen if I put s.settimeout (timeout) in s.setblocking (False) - after replacing, I received a working code

Or are there consequences after these actions?

**Comment by Lonami** [comment]
> And what will happen if I put s.settimeout (timeout) in s.setblocking (False)

`self._loop.sock_connect` should not work if you do that.

**Comment by proroot** [comment]
I have everything ok check yourself)

**Comment by Lonami** [comment]
We can close this once `v2` lands with https://github.com/LonamiWebs/Telethon/commit/c1a40630a3477ad9b03b44e009ca57928de887d7, since we replace `pysocks` with `aiosocks`, and hopefully that solves it.

**Comment by Lonami** [comment]
Actually, let's close it already, since the commit has been made. It just hasn't been released. Then [the milestone](https://github.com/LonamiWebs/Telethon/milestone/1) will show progress nicely.
