### ISSUE TITLE
Reconnect when reciving data, connecting to proxy (socks5)

### ISSUE THREAD

**Issue by AmirBDa** [LonamiWebs/Telethon#1194]
I am trying to connect to Telegram via proxy , but I end up getting (slow) infinite reconnect loop...It looks similar to #1134 but the difference is that I am connecting to the proxy with `socks5` and I do get responses back from Telegram (with reconnections).

When I remove the proxy it works smoothly, so as you can see in the code below, I changed the default value for `timeout` and  I am using `asyncio.wait_for` when invoking requests, but problem isn't solved.

Code:
```
TIMEOUT = 20
client = TelegramClient('session_id',
                        api_id=API_ID,
                        api_hash=API_HASH,
                        proxy=(socks.SOCKS5, 'host', 1337, True, 'username', 'password'),
                        timeout=TIMEOUT)
await client.connect()

response = await asyncio.wait_for(self.client(Request()), timeout=TIMEOUT)
```

Logs:
```
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.mtprotosender:Connecting to X.X.X.X:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
...
```

The problem is [right here](https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/connection/connection.py#L168) and the error is `asyncio.IncompleteReadError`.

**Comment by Lonami** [comment]
We can close this once `v2` lands with https://github.com/LonamiWebs/Telethon/commit/c1a40630a3477ad9b03b44e009ca57928de887d7, since we replace `pysocks` with `aiosocks`, and hopefully that solves it.

**Comment by Lonami** [comment]
Actually, let's close it already, since the commit has been made. It just hasn't been released. Then [the milestone](https://github.com/LonamiWebs/Telethon/milestone/1) will show progress nicely.
