### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1195]
Some of them are wrong, and a lot of them are missing. It would be really good to type hint all parameters and return values on the public API of the library. This includes but is not limitted to the methods in the `TelegramClient`, those in `Message`, `Button`, etc.

If you spot a type hint that's wrong, please report it here so we can make a single commit aggregating the changes.

**Comment by Lonami** [comment]
For example, `connection_retries=None` is wrong, because it should be optional.

**Comment by apepenkov** [comment]
![IMG_20200127_151847](https://user-images.githubusercontent.com/39992738/73174277-6784d300-4118-11ea-8cc9-430abf704fa6.jpg)
I guess, get_messages shall be [TotalList, Message]

**Comment by tulir** [comment]
https://github.com/LonamiWebs/Telethon/blob/master/telethon/client/account.py#L121 should be `max_file_size: int` (and technically also `Optional`, because `None` is allowed)

**Comment by apepenkov** [comment]
functions.messages.GetCommonChatsRequest
![изображение](https://user-images.githubusercontent.com/39992738/74944563-4c4f6f80-5407-11ea-99ed-c9c65199b8ad.png)
add int

**Comment by apepenkov** [comment]
same for functions.photos.GetUserPhotosRequest. I guess to TypeInputUser shall be added string(for username) and int (for id)

**Comment by tulir** [comment]
@apepenkov Not sure if those should be included, since the raw API obviously doesn't take ints, it's just telethon converting them. Would be better to reduce the necessity of using raw requests.

**Comment by apepenkov** [comment]
> @apepenkov Not sure if those should be included, since the raw API obviously doesn't take ints, it's just telethon converting them. Would be better to reduce the necessity of using raw requests.

But in docs (and param itself) looks like need id/username. send_message or so converts actually too, but there are hints for int and str

**Comment by apepenkov** [comment]
![image](https://user-images.githubusercontent.com/39992738/81498324-ee774900-92cc-11ea-88fc-0ddc240de0f4.png)
send_message doesn't accept types.InputPhoto as file

**Comment by apepenkov** [comment]
send_message doesn't accept types.InputMediaInvoice  as file
![image](https://user-images.githubusercontent.com/39992738/82490237-a980bd00-9aeb-11ea-8974-9c5af1957620.png)

**Comment by HosseyNJF** [comment]
![image](https://user-images.githubusercontent.com/18368279/101338880-d41d4200-3892-11eb-9eb7-252817893961.png)
EventCommon should have `_client` and `original_update` fields correctly hinted (I know that `_client` is private, but the `client` property internally returns it).

**Comment by HosseyNJF** [comment]
There are a _loooot_ of missing type-hints and it would be better if there was a branch just for fixing them (so that people could directly fix them instead of reporting here, hence speeding up the process).

**Comment by Lonami** [comment]
That's a good idea, I've created the [`typehints`](https://github.com/LonamiWebs/Telethon/tree/typehints) branch. We can combine all fixes there and then squash into a single main commit once we merge to `master`.

**Comment by Thoufak** [comment]
Hi. Has anyone attempted tweaking the code generator, so that the hints of the raw API requests arguments are correct? Namely, Telethon can convert a lot of stuff into a valid input entity, but the type hints don't reflect this at all. I'm thinking that something as easy as `Union[RealInputEntityType, EntityLike]` would already be an improvement. Obviously, sometimes we can't tell if something will be successfully converted into the right type at runtime, but it's better than having your IDE telling you the argument type **is wrong**.

![image](https://user-images.githubusercontent.com/40132582/134780591-265bd6b0-556a-455b-a5ab-1b7f546c79b6.png)

I'd be happy to study it more and maybe submit a PR. 
@Lonami, please express your opinion on this, if you have a chance.

**Comment by Lonami** [comment]
It could be a good idea to update the type hints to reflect the "auto-conversion" better. The type hints can get quite large, but it should be fine as long as it makes the IDE happy. I won't be opposed to a PR adding this feature, but beware the generator code is quite messy at the moment. Also, I'm in the process of updating the library so that it's ready for [version 2.0](https://github.com/LonamiWebs/Telethon/tree/v2). Once that's merged, I will review all open issues and ping back (if I remember) so that you don't unnecessarily work on something that may change.

**Comment by Thoufak** [comment]
I'm excited to hear you're working on 2.0. Good luck with that! Will wait for your ping then.

**Comment by tsathis** [comment]
Don't we need to add `pyi` files for type checking?

**Comment by Morisander** [comment]
is the official work on this still active? asking as i could not find a type hinting branch anymore, and 2.0 is still not out?

**Comment by Lonami** [comment]
I don't plan to add type hints to v1. Progress on v2 is slow, mostly due to lack of motivation, but I still hope to finish it one day.

**Comment by Elypha** [comment]
I may have found a few incorrect hints but since you said v1 won't have type hints update, could you please let us know if you still want to collect type hints feedbacks on this thread, and if that is exclusive to a v2 setup.
could you also, if possible, share the current states of v2, like whether it's okay for development use or still a bit far away from that. didn't find it on the docs

**Comment by Lonami** [comment]
You're correct, it'd be good to close this. v2 uses strict type checking so the type hints must be correct by default.

v2 is not ready for use and I don't know when it will be. You can definitely attempt to use it and report or aim to fix bugs, but I don't know how stable it is or when I'll be happy with the design and amount of features (some things may still radically change).
