### ISSUE TITLE
Convert tdata to telethon session

### ISSUE THREAD

**Issue by fantik11** [LonamiWebs/Telethon#1198]
Hello, I have many accounts in tdata format, but I need to convert them to a Telethon session file. I'm trying to do it manually, but I think there is a good idea to create a new function that can do it automatically.

**Comment by Lonami** [comment]
You can write such function yourself to automate the job. I don't plan on adding it to Telethon itself because it's unnecessary bloat most people don't need, and maintaining it would be a burden since Telegram Desktop can change its tdata at any time.

**Comment by TooKirill** [comment]
Hi. I am interested in this topic, maybe you know the method of how you can load tdata in telethon?

**Comment by thedemons** [comment]
In case you still need it, I've written a library to do just this.
Check it out at my [repos](https://github.com/thedemons/opentele/).
