### ISSUE TITLE
Telethon multiple accounts use the same appid and api_hash

### ISSUE THREAD

**Issue by 664966673** [LonamiWebs/Telethon#1199]
QUESTIONS ARE NEITHER BUGS NOR ENHANCEMENTS AND DON'T BELONG HERE.

If you DO have a question, ask in:
* https://stackoverflow.com or
* https://t.me/TelethonUpdates (@TelethonUpdates channel in Telegram)

If you do post a question, it will be labelled "RTFM" and closed as soon as possible without any answer.

If you DON'T have a question, use the right template for bugs/issues with the library or to propose an improvement/enhancement to either the code or documentation.

We are not being harsh. Only clear. The issues section is not for questions, and people keep asking things over and over, which is a waste of everyone's time.

**Comment by Lonami** [comment]
(GitHub templates are meant to be read and followed before posting)
