### ISSUE TITLE
Optional sessions store

### ISSUE THREAD

**Issue by fdhadzh** [LonamiWebs/Telethon#12]
In my case I use `Telethon` for many users and I need store sessions in DB.
Maybe sessions storing in files should be optionally?
Thanks.

**Comment by XyLoNaMiyX** [comment]
First, thank you for using Telethon :P

I think that it is a good idea to provide different ways to store the sessions. Let me work on this: you can either provide a `str` and so it loads the default `Session` (or `None` so it doesn't get saved), _or_ you can provide a `Session` super class (or an object with the same `.save()` and `.load()` methods, any would work). The implementation of this custom `Session` object is then up to the user decision.

**Comment by XyLoNaMiyX** [comment]
This is how it works: pass a `Session` instance (or any other instance which subclasses it) and you're ready to go!

**Comment by fdhadzh** [comment]
@XyLoNaMiyX Thanks!
