### ISSUE TITLE
NameError: name 'InputPeerUser' is not defined

### ISSUE THREAD

**Issue by arta66** [LonamiWebs/Telethon#120]
`contacts= client.invoke(GetContactsRequest(""))` 
`for u in contacts.users:
    client.send_message(InputPeerUser('334412783', '-8113372651091717470'), "hi")` 
`NameError: name 'InputPeerUser' is not defined` 

how i defined InputPeerUser ????

**Comment by Lonami** [comment]
**RTFM**, please. **Please** read the [documentation](https://lonamiwebs.github.io/Telethon/constructors/input_peer_user.html). It has a nice button saying "Copy import to the clipboard".
