### ISSUE TITLE
Updates and events don't work

### ISSUE THREAD

**Issue by theerfan** [LonamiWebs/Telethon#1201]
I was simply trying the sample code placed [here](https://telethon.readthedocs.io/en/sync/extra/basic/working-with-updates.html).

**Code that causes the issue**
```
import logging 
from telethon import TelegramClient, events, sync
logging.basicConfig(level=logging.ERROR)
client = TelegramClient('session', api_id, api_hash)

@client.on(events.NewMessage)
def my_event_handler(event):
    if 'hello' in event.raw_text:
        event.reply('hi!')

client.start()
client.run_until_disconnected()

```

**Traceback**
```
Traceback (most recent call last):
   File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\telethon\client\updates.py", line 414, in _dispatch_update
    await callback(event)
TypeError: object NoneType can't be used in 'await' expression

```
I have tried doing it the ```client.add_event_handler(callback)``` way but I still got the same result.
And I'm sure the client is connected because it doesn't have a problem getting entities and such.

**Comment by Lonami** [comment]
Thanks, that's a documentation issue. It should be `async def`. I'll be sure to address this among other things (some `:mod:`, more code blocks etc.) in the next update.

**Comment by Lonami** [comment]
Actually the issue is different, you somehow reached the deprecated `sync` version of the docs, note that your URL vs the actual one are:
```diff
-https://telethon.readthedocs.io/en/sync/extra/basic/working-with-updates.html
+https://docs.telethon.dev      /en/latest    /basic/             updates.html
```

So, https://docs.telethon.dev/en/latest/basic/updates.html is where you should be now. Anyway, the documentation needs the *updates* I mentioned.

**Comment by theerfan** [comment]
Oh, so please add a hint of it being deprecated on the page to avoid more people becoming confused the way I was, because that's where google took me.
Thanks.
