### ISSUE TITLE
send_album doesn't work with videos

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1204]
This wasn't implemented due to laziness when the feature was added.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/6d4c8ba8ffbb2c334c414abd4df45e10426a061f

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/6d4c8ba8ffbb2c334c414abd4df45e10426a061f will fix it since now album's code path is cleaner, but it's a breaking change.

**Comment by Lonami** [comment]
Actually, let's close it already, since the commit has been made. It just hasn't been released. Then [the milestone](https://github.com/LonamiWebs/Telethon/milestone/1) will show progress nicely.

**Comment by uzlov** [comment]
I still have this issue :( send_files can send album of videos (files is the list of telethon.tl.types.MessageMediaDocument)
