### ISSUE TITLE
Possibility of Telethon Runtime library

### ISSUE THREAD

**Issue by shosaman** [LonamiWebs/Telethon#1213]
Hello All, On my Ubuntu laptop I've been able to install Telethon and use Telethon libraries successfully. 

However the web host services that I have purchased does not provide a SSH (Secured Shell access) and does not have Telethon installed. Also since it is a shared server the web host service provider is not showing interest to install Telethon library.

In such a situation, is there a possibility to use Telethon as a runtime as I've been not able to get it installed. Has anyone run into such a situation? If so how did you resolve it ?

**Comment by Lonami** [comment]
You should have purchased [a better host service](https://www.hetzner.com/cloud).

**Comment by shosaman** [comment]
OK I'll work around by having my Python scripts in a local machine accessing files in the web server.
