### ISSUE TITLE
Detect a grouped message (album)

### ISSUE THREAD

**Issue by fchennouf** [LonamiWebs/Telethon#1216]
Hi everybody, i would like to know if there is (or it's planned to be added) a way to detect an event when someone send a grouped message ( with multiple photos). 
I Took a look into the source, it seems that grouped messages event are send zipped, and a function unzip them and **call _process_message** to go back to normal workflow. The received message for album is composed of multiple messages, and each message is handled saparatly in **_handle_update** , so the "grouped size", information is lost. 
It is possible to know that it's a grouped message thanks to **grouped_id** property, but to be able to forward a received album, we have to guess how many elements are available in it. Thanks in advance :)

**Comment by Lonami** [comment]
1. It's not documented anywhere whether album photos always come inside the same `Updates` or it may not be the case.
2. It's possible that there are more updates inside that `Updates` so if we just did `len()`, the count could be off.
3. It's harder to use `events.Raw` if the user has to deal with all these `Updates` containers themselves.
4. The code is cleaner if we just hand in `Update` to the users.
5. We could inspect *all* incoming updates for a `grouped_id`, and attach a `len` somewhere, somehow. This however incurs a possibly noticeable performance for *everyone*, when some people may not care at all. The updates code path is pretty hot.

It is possible to handle albums already, it's just not very clean:
```python
import asyncio

albums = {}

@client.on(events.NewMessage(func=lambda e: e.grouped_id))
async def handler(event):
    pair = (event.chat_id, event.grouped_id)
    if pair in albums:
        albums[pair].append(event.message)
        return
    albums[pair] = [event.message]
    await asyncio.sleep(0.5)
    messages = albums.pop(pair)
    await event.respond(f'Got {len(messages)} photos!')
```

That being said, I would like something builtin to deal with them more easily, preferably without the delay, but we have to take care about all the points I mentioned above.

**Comment by Lonami** [comment]
I think passing 2 vs passing 3 parameters won't make much of a difference (https://github.com/LonamiWebs/Telethon/commit/a7a7c4add2a30ec7c08013af3a9239d24a96d79a), and the cost for checking for albums is only done in the specific event, with convenience methods and properties to work on the album as a whole. I feel like this is a good tradeoff, although the updates code is more messy now.

**Comment by fchennouf** [comment]
Thanks Lonami for your feedback, about the album being sent in a single message your are right, it was only my observations during tests, it can be different as it's not documented like that. For your solution I thought about adding a delay to send everything at once, but as you said it wasn't very clean, so i prefered ask to be sure that no solution exist or is gonna be realized. Anyway thanks again I will test the delay, it should do it

**Comment by Lonami** [comment]
You can also install `master` and use the new `events.Album`.
