### ISSUE TITLE
Support for "Adding a user to contacts without his phone number"

### ISSUE THREAD

**Issue by Tivixo** [LonamiWebs/Telethon#1217]
Hi,
before anything sorry for my bad English.

some days ago. Telegram adds a new feature for adding users as contact without their phone numbers: https://telegram.org/blog/contacts-local-groups

Can I still use add contact command for adding users without phone number?
If not, how I can use this new feature?
Or I should wait for the new upgrade of Telethon?

Thank you.

**Comment by Lonami** [comment]
The layer has already been updated, which means there is already a raw method for it. Asking *which* it is is a question and doesn't belong here ([it does in the group](https://t.me/TelethonChat))

**Comment by Tivixo** [comment]
Thank you, I joined the group but Telegram don't let me to write any message in the group for some spam protecting stuff, said people in your area can't.

so what I should to do? can you tell me here please?

**Comment by Lonami** [comment]
Questions belong to the group or [StackOverflow](https://stackoverflow.com).
