### ISSUE TITLE
EventBuilder.self_id acts as a global and breaks when multiple clients are used

### ISSUE THREAD

**Issue by vanyakosmos** [LonamiWebs/Telethon#1218]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import os
import glob
import asyncio

from telethon import TelegramClient, events

API_ID = os.getenv('API_ID')
API_HASH = os.getenv('API_HASH')


async def foo(event):
    await event.reply('bar')


async def make_client(session, loop):
    client = TelegramClient(session, API_ID, API_HASH, loop=loop)
    client.add_event_handler(foo, events.NewMessage(outgoing=True, pattern='foo'))
    if not client.is_connected():
        await client.connect()
    me = await client.get_me()
    print(me)
    return client


def main():
    loop = asyncio.get_event_loop()
    clients = []
    
    # load all available sessions
    for file in glob.glob('sessions/*.session'):
        c = loop.run_until_complete(make_client(file, loop))
        clients.append(c)

    loop.run_forever()


if __name__ == '__main__':
    main()
```

**Missbehaviour**
In a chat with one another, both users respond to outgoing messages of one of them.

For example: let's say that we have 2 users (A and B), both have userbots, userbots' clients have shared event loop. If users chat with one another then we will see that user A will also respond to the outgoing command of user B. (`>` denotes reply)

Expected dialog:
```
A: hello
B: foo
B: > bar
```
Actual dialog:
```
A: hello
B: foo
B: > bar
A: > bar
```

**Comment by x0x8x** [comment]
Can't reproduce

- Only one session file is loading instead of two
- Everything works as you expected

![2019-07-02_120203](https://user-images.githubusercontent.com/5467132/60505783-179e7480-9ccd-11e9-86d2-4e5e62ba25c1.png)

![2019-07-02_132333](https://user-images.githubusercontent.com/5467132/60505614-c2faf980-9ccc-11e9-8798-3e88cab5f7c5.png)

[loop-debug.log](https://github.com/LonamiWebs/Telethon/files/3349565/loop-debug.log)

**Comment by vanyakosmos** [comment]
@x0x8x because you've loaded only one session. Typo in `tester_two.sesSion` and in the logs you have only 1 user printed out.

**Comment by Lonami** [comment]
Thanks for the help.

**Comment by Lonami** [comment]
Oh wait, I read that wrong. I still haven't tried this myself but I doubt it's a bug anyway.

**Comment by Lonami** [comment]
[Seems to work fine](https://t.me/telethonofftopic/287302). Shared loops have nothing to do with different clients, at all.

**Comment by vanyakosmos** [comment]
wow, you can't just trust twitface. I can share with you session file of one of my accounts and you can check it yourself.
And the problem wasn't specific to private chats. Just chats in general. Chats where we have several users with a shared loop on clients.

**Comment by Lonami** [comment]
If I can't trust Twitface, can I trust anyone? We had your report for the issue, and his to say there is no issue, and I lean on the side that shared loops are **not** an issue. If anything, `outgoing=` may be buggy. I will try myself and post results some time.

**Comment by Lonami** [comment]
I tried in a private conversation:
```python
async def foo(event):
    await event.reply('bar')


with client, alt:
    print('Are the loops the same?', client.loop == alt.loop)
    client.add_event_handler(foo, events.NewMessage(outgoing=True, pattern='foo'))
    alt.add_event_handler(foo, events.NewMessage(outgoing=True, pattern='foo'))
    client.loop.run_forever()
```

Which prints:
```
Are the loops the same? True
```

Where `client` and `alt` are different accounts. I messaged from the `client` account to the `alt` account using an official client with the following result:
![image](https://user-images.githubusercontent.com/6297805/62525434-b02d9480-b837-11e9-85af-7c59f91b48d1.png)

Only `client` responded. The same occurred in a small group chat and megagroup. So this is not an issue. I can't reproduce.

**Comment by vanyakosmos** [comment]
Then what can possibly be wrong with my code?

code:
<img width="680" alt="Screen Shot 2019-08-07 at 00 59 55" src="https://user-images.githubusercontent.com/16745500/62580367-b448c900-b8ae-11e9-9f8d-2e4fe1e57f87.png">
<details>
<summary>code</summary>

```python
import glob
import asyncio
from telethon import TelegramClient, events

from config import API_ID, API_HASH


async def foo(event):
    print(f'> printing foo for event: {event}')
    await event.reply('bad')


async def make_client(session, loop):
    client = TelegramClient(session, API_ID, API_HASH, loop=loop)
    client.add_event_handler(foo, events.NewMessage(outgoing=True, pattern='foo'))
    if not client.is_connected():
        await client.connect()
    me = await client.get_me()
    print(me)
    return client


def main():
    loop = asyncio.get_event_loop()
    clients = []

    for file in glob.glob('sessions/*.session'):
        c = loop.run_until_complete(make_client(file, loop))
        clients.append(c)

    assert all([c.loop == loop for c in clients])
    print('running...')
    loop.run_forever()


if __name__ == '__main__':
    main()
```
</details>

logs:
<img width="486" alt="Screen Shot 2019-08-07 at 00 59 02" src="https://user-images.githubusercontent.com/16745500/62580373-b874e680-b8ae-11e9-8337-73dab21b6225.png">
<details>
<summary>logs</summary>

```
User(id=674821365, is_self=True, contact=True, mutual_contact=False, deleted=False, bot=False, bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False, support=False, scam=False, access_hash=4439462715826273760, first_name='𝖓𝖎𝖊𝖒𝖆𝖓𝖉', last_name=None, username='npcomplete', phone='380938234159', photo=UserProfilePhoto(photo_id=2898335693773318059, photo_small=FileLocationToBeDeprecated(volume_id=263708388, local_id=105865), photo_big=FileLocationToBeDeprecated(volume_id=263708388, local_id=105867), dc_id=2), status=UserStatusOffline(was_online=datetime.datetime(2019, 8, 6, 21, 19, 51, tzinfo=datetime.timezone.utc)), bot_info_version=None, restriction_reason=None, bot_inline_placeholder=None, lang_code=None)
User(id=89599420, is_self=True, contact=True, mutual_contact=True, deleted=False, bot=False, bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False, support=False, scam=False, access_hash=6106815302761471165, first_name='𝖆𝖎𝖛𝖊𝖓', last_name=None, username='vanyakosmos', phone='380668765053', photo=UserProfilePhoto(photo_id=384826579096809929, photo_small=FileLocationToBeDeprecated(volume_id=257013556, local_id=111395), photo_big=FileLocationToBeDeprecated(volume_id=257013556, local_id=111397), dc_id=2), status=UserStatusOffline(was_online=datetime.datetime(2019, 8, 6, 21, 57, 50, tzinfo=datetime.timezone.utc)), bot_info_version=None, restriction_reason=None, bot_inline_placeholder=None, lang_code=None)
running...
> printing foo for event: NewMessage.Event(original_update=UpdateShortMessage(id=272583, user_id=674821365, message='foo', pts=556851, pts_count=1, date=datetime.datetime(2019, 8, 6, 21, 58, 28, tzinfo=datetime.timezone.utc), out=True, mentioned=False, media_unread=False, silent=False, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, entities=[]), pattern_match=<_sre.SRE_Match object; span=(0, 3), match='foo'>, message=Message(id=272583, to_id=PeerUser(user_id=674821365), date=datetime.datetime(2019, 8, 6, 21, 58, 28, tzinfo=datetime.timezone.utc), message='foo', out=True, mentioned=False, media_unread=False, silent=False, post=None, from_scheduled=None, legacy=None, from_id=None, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, media=None, reply_markup=None, entities=[], views=None, edit_date=None, post_author=None, grouped_id=None))
> printing foo for event: NewMessage.Event(original_update=UpdateShortMessage(id=14329, user_id=89599420, message='foo', pts=29857, pts_count=1, date=datetime.datetime(2019, 8, 6, 21, 58, 28, tzinfo=datetime.timezone.utc), out=False, mentioned=False, media_unread=False, silent=False, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, entities=[]), pattern_match=<_sre.SRE_Match object; span=(0, 3), match='foo'>, message=Message(id=14329, to_id=PeerUser(user_id=89599420), date=datetime.datetime(2019, 8, 6, 21, 58, 28, tzinfo=datetime.timezone.utc), message='foo', out=True, mentioned=False, media_unread=False, silent=False, post=None, from_scheduled=None, legacy=None, from_id=89599420, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, media=None, reply_markup=None, entities=[], views=None, edit_date=None, post_author=None, grouped_id=None))
```
</details>

it didn't fire after the first `foo`:
<img width="161" alt="Screen Shot 2019-08-07 at 01 00 31" src="https://user-images.githubusercontent.com/16745500/62580434-ca568980-b8ae-11e9-9c8e-0e8c4f850a17.png">



but after sencond one it did:
<img width="706" alt="Screen Shot 2019-08-07 at 00 58 48" src="https://user-images.githubusercontent.com/16745500/62580389-bdd23100-b8ae-11e9-98d4-394e4442bfb0.png">

**Comment by vanyakosmos** [comment]
@Lonami, you weren't able to reproduce, because `alt` client wasn't active/connected at the moment.

this code "works"
<img width="680" alt="Screen Shot 2019-08-07 at 01 11 48" src="https://user-images.githubusercontent.com/16745500/62580944-587f3f80-b8b0-11e9-916f-6d283abf95e0.png">

BUT, if your `alt` type foo then you will see a bug. Or you can just connect both clients beforehand (commented code).

**Comment by Lonami** [comment]
In my code I do `with client, alt:` which calls `start()` on both `client` and `alt`.

**Comment by vanyakosmos** [comment]
but why after adding explicit "connect" the bug magically appears?
or when `alt` also type something in the chat

**Comment by Lonami** [comment]
Could you also register `events.Raw` for both and `print(event)`?

**Comment by Lonami** [comment]
…which leads the following code to issues:
https://github.com/LonamiWebs/Telethon/blob/b1eed82b7f7c793c05defeb0a504659f6f2ae761/telethon/events/newmessage.py#L92-L97

**Comment by Lonami** [comment]
Does that fix it? (`pip3 install -U https://github.com/LonamiWebs/Telethon/archive/master.zip`)

**Comment by vanyakosmos** [comment]
yep, it's all good now

**Comment by Lonami** [comment]
Okay thanks for confirming and sorry for refusing this was a bug at the beginning.
