### ISSUE TITLE
not get any telegram messages from channels I don't own

### ISSUE THREAD

**Issue by ceveyp** [LonamiWebs/Telethon#1220]
When I list all the channels with this: 
for dialog in client.iter_dialogs():
      print(dialog.name, 'has ID', dialog.id)
I can see all the channels, but it doesn't receive any messages from channels I don't own
Here is the code I'm using:

@client.on(events.NewMessage)
async def my_event_handler(event):
        chat = event.chat_id
        if chat == chats['TN'] or chat == chats['PUCSTB'] or chat == chats['PUCS'] or chat == chats['TEST'] or chat == chats['3COM']:
                msg = event.raw_text
                print("New Message: " + msg)
                await client.send_message(chats['TEST2'], msg)
client.run_until_disconnected()

Is there a way to do this?

**Comment by Lonami** [comment]
What is the reason for closing this?
