### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by KingSilvan** [LonamiWebs/Telethon#1224]
This problem only appears when using thelethon. What might cause this issue?

**Comment by Lonami** [comment]
I am assuming that you found the answer.

**Comment by bensapirstein** [comment]
Hi, how did you solve it?

**Comment by miladcheraghi** [comment]
hi,
I installed the telethon correctly and according to the documentation I tried to login But every time I encounter the following error

sqlite3.OperationalError: unable to open database file

There is also a filter telegram in my country and I use mtpproxy to work with the library
Can anyone help? plz

**Comment by markolofsen** [comment]
The same error

**Comment by Lonami** [comment]
@markolofsen posting in three different issues won't help. Pick or open a new one, and you will get the same response I gave in https://github.com/LonamiWebs/Telethon/issues/944#issuecomment-520804401.
