### ISSUE TITLE
Send_message reply does not work for me

### ISSUE THREAD

**Issue by kalquier** [LonamiWebs/Telethon#1228]
`await client.send_message(entity, answer, reply_to=event.original_update.msg_id)`

In Telegram app it doesn't appear as a reply, but as a normal message.
I mean, the output is the same as using this: 

`await client.send_message(entity, answer)`

Thanks

**Comment by Lonami** [comment]
`reply_to` is working fine, which means you must be doing something wrong. However, this is the wrong place to ask questions.

**Comment by kalquier** [comment]
I'm using a Telegram group with both bot and client. It works fine with bot.send_message but not with client.send_message. There is a limitation in replying with client inside a Telegram group?

**Comment by Lonami** [comment]
Please move your questions to [the official chat](https://t.me/TelethonChat) or [StackOverflow](https://stackoverflow.com).
