### ISSUE TITLE
Datetime objects are parsed as signed ints but serialized as unsigned

### ISSUE THREAD

**Issue by joell** [LonamiWebs/Telethon#1242]
Thank you for such tremendous work on implementing the Telegram protocol!  You've done an incredibly thorough job, and I've greatly enjoyed working with your library.  However, I've run into one small parse/serialize mismatch issue.

[`TLObject.serialize_datetime`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/tlobject.py#L138) converts a datetime to an integer timestamp and then attempts to convert it to bytes using `struct.pack` as an *unsigned* integer.

However, `BinaryReader.tgread_date` invokes [`BinaryReader.read_int`](https://github.com/LonamiWebs/Telethon/blob/38c65adf358ac42033cb2382b850fde9a82bcb71/telethon/extensions/binaryreader.py#L41) which uses `int.from_bytes` to parse the timestamp bytes as a *signed* integer.

The result of this mismatch is that if you receive a Telegram event that includes a pre-1970 date anywhere in it, you can successfully _parse_ the event and its negative integer timestamp into a datatime, but if you try to _re-serialize_ the event back to binary data, `struct.pack` will throw an `argument out of range` exception at you because it cannot serialize the pre-1970 date's negative integer timestamp as an unsigned integer.  The expectation is that anything Telethon can parse it should also be able to re-serialize, and vice versa.

This should be easily fixed by changing the [`TLObject.serialize_datetime`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/tlobject.py#L138) format string to `"<i"`.

**Comment by Lonami** [comment]
Ah, this is where #1241 came from. Should we bother merging that when the actual fix is changing `datetime` to serialize as signed? Everything<sup>1</sup> in Telegram is serialized as a signed number.

[1] Except for those parts regarding big numbers.

**Comment by binares** [comment]
> 
> 
> Ah, this is where #1241 came from. Should we bother merging that when the actual fix is changing `datetime` to serialize as signed? Everything1 in Telegram is serialized as a signed number.
> 
> [1] Except for those parts regarding big numbers.

Not quite, #1241 was _parsing_ a pre-1970 timestamp to datetime (and only affects Windows platform, it seems), here it about converting pre-1970 timestamp to bytes, and should affect both platforms I think.
