### ISSUE TITLE
can't read a bot message in group

### ISSUE THREAD

**Issue by alirezaimi** [LonamiWebs/Telethon#1244]
**Code that causes the issue**
```python
Token = "XXXYYY:XXYY"
bot = TelegramClient("bot", YYYY, "XXXX").start(bot_token=Token)


@bot.on(events.NewMessage(pattern='/start'))
async def start(event):
    """Send a message when the command /start is issued."""
    await event.respond('Hi!')
    raise events.StopPropagation


@bot.on(events.NewMessage)
async def echo(event):
    """Echo the user message."""
    print(f">> get it {event.text}")
    await event.respond(event.text)


def main():
    """Start the bot."""
    bot.run_until_disconnected()

if __name__ == '__main__':
    main()
```

This is my sample code and i want read message from telegram bots in a group, but i can get only message from persons and not bots joined to group . 
Is this a bug or i used this library by mistake or ... ?

**Comment by Lonami** [comment]
Yes, bot privacy should be disabled in [@BotFather](https://t.me/BotFather) **before** adding the bot to the group.

**Comment by Qurbonsaid** [comment]
> Yes, group privacy should be disabled in [@BotFather](https://t.me/BotFather) **before** adding the bot to the group.

What if this happens with a userbot?
