### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by miladcheraghi** [LonamiWebs/Telethon#1248]
hi,
I installed the telethon correctly and according to the documentation I tried to login But every time I encounter the following error

sqlite3.OperationalError: unable to open database file

There is also a filter telegram in my country and I use mtpproxy to work with the library
Can anyone help? plz

**Comment by Lonami** [comment]
You already asked in #1224. Either way, the library probably lacks permission to write to the session file wherever you are running it from.

**Comment by miladcheraghi** [comment]
I also checked the permissions for the script file, There was full permission to write, read and execute,  I also checked this for the directory where the library is located. All files and folders had full access.
I also run the script of the program with the administrator rights. 
So where can the problem be?

**Comment by Lonami** [comment]
Well, the latest version works correctly for me, so there must be something wrong in your environment. Not a bug in the library.

**Comment by markolofsen** [comment]
```
2019-08-13 11:47:14,166 (util.py:65 WorkerThread12) ERROR - TeleBot: "OperationalError occurred, args=('unable to open database file',)
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "venv/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 214, in __init__
    session = SQLiteSession(session)
  File "venv/lib/python3.7/site-packages/telethon/sessions/sqlite.py", line 46, in __init__
    c = self._cursor()
  File "venv/lib/python3.7/site-packages/telethon/sessions/sqlite.py", line 218, in _cursor
    check_same_thread=False)
sqlite3.OperationalError: unable to open database file
```

**Comment by Lonami** [comment]
@markolofsen posting in three different issues won't help. Pick or open a new one, and you will get the same response I gave in https://github.com/LonamiWebs/Telethon/issues/944#issuecomment-520804401.

**Comment by akash-rajput** [comment]
FYI this can happen if you deleted the `sessions` directory accidentally. Just create it again & it should work.

**Comment by R4IDIO** [comment]
Hello, I had the same problem and even playing with the permissions did not solve the problem. 

In fact, I realized that it was due to the fact that I was not building my telegram client at the same level. 

Let's say you have the following architecture (both files at same level): 

my_telegram_client.py
my_session.session

Everything will work as expected, since we call the file that builds the telegram client at the same level as the session file

But in my case, I added a main.py file that calls the my_telegram_client file to create my telegram client and then I get the error mentioned above. 

New architecture : 

main.py
src/my_telegram_client.py
src/my_session.session

To solve this error, just specify the absolute path of the session file when creating the telegram client. 

Exemple : TelegramClient('/Users/john/MyProject/src/my_session.session', app_id, app_bash)

**Comment by Fasttyper** [comment]
Hi, I have the same issue when running my program on ubuntu.
It works fine in windows, but the same code is giving:
File "/home/test/get.py", line 14, in <module>
    get_bot_session()
  File "/home/test/get.py", line 5, in get_bot_session
    client = TelegramClient(BOT_TOKEN, API_ID, API_HASH)
  File "/home/ubuntu/.local/lib/python3.11/site-packages/telethon/client/telegrambaseclient.py", line 289, in __init__
    session = SQLiteSession(session)
  File "/home/ubuntu/.local/lib/python3.11/site-packages/telethon/sessions/sqlite.py", line 47, in __init__
    c = self._cursor()
  File "/home/ubuntu/.local/lib/python3.11/site-packages/telethon/sessions/sqlite.py", line 242, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file
error on ubuntu
Any ideas? 
P.S. I run it as administrator, all files have permissions.

**Comment by Lonami** [comment]
`BOT_TOKEN` likely has `:` in its path, which likely is not a valid session path.

**Comment by Fasttyper** [comment]
I checked for ":" too and it wasn't the issue.  
I solved the issue by just using older version of the python. 
My server was running python 3.11.3 which kept giving this error, then I tried using python 3.8 to run the application which worked for me.
Anyways thanks for quick reply.

**Comment by 0FuzzingQ** [comment]
> I checked for ":" too and it wasn't the issue. I solved the issue by just using older version of the python. My server was running python 3.11.3 which kept giving this error, then I tried using python 3.8 to run the application which worked for me. Anyways thanks for quick reply.

i have the same question in python 3.11.5 but running successfully in python3.6
