### ISSUE TITLE
file id issue 

### ISSUE THREAD

**Issue by Erick2011** [LonamiWebs/Telethon#1250]
Hi, i am trying to get file ids of my documents in a couple of channels but i am getting just a fake id, i cant make a sendMessage with those ids i am getting. is there a way to get them as https://api.telegram.org/bot<TOKEN>/getUpdates shows it?

**Comment by Lonami** [comment]
I just tried and it works correctly, though it may change for users. A user's (or bot) file ID cannot be used by a different account (or bot). This is not a bug.
