### ISSUE TITLE
Cant use connect

### ISSUE THREAD

**Issue by artbred** [LonamiWebs/Telethon#1254]
Python 3.7
Using that code 

from telethon.sync import TelegramClient
import logging
logging.basicConfig(level=logging.DEBUG)
# Remember to use your own values from my.telegram.org!
api_id =
api_hash = ''

with TelegramClient('lalal', api_id, api_hash) as client:
    # Getting information about yourself
    me = client.get_me()

    # "me" is an User object. You can pretty-print
    # any Telegram object with the "stringify" method:
    print(me.stringify())

    # When you print something, you see a representation of it.
    # You can access all attributes of Telegram objects with
    # the dot operator. For example, to get the username:
    username = me.username
    print(username)
    print(me.phone)

    # You can print all the dialogs/conversations that you are part of:
    for dialog in client.iter_dialogs():
        print(dialog.name, 'has ID', dialog.id)

I have this output 

DEBUG:asyncio:Using selector: KqueueSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError: 
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: TimeoutError: 
DEBUG:telethon.network.mtprotosender:Connection attempt 3...
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: TimeoutError: 
DEBUG:telethon.network.mtprotosender:Connection attempt 4...

**Comment by Lonami** [comment]
Bad network, connection fails. Not a bug.

**Comment by artbred** [comment]
Can you please say how to use proxy? Except os.environ['http_proxy'] = proxy

**Comment by Lonami** [comment]
This is the wrong place to ask questions.
