### ISSUE TITLE
 Type 450b7115 not found

### ISSUE THREAD

**Issue by lanjianchun** [LonamiWebs/Telethon#1257]
logger.info:
telethon.network.mtprotosender: Type 450b7115 not found, remaining data b"\x15q\x0bE\x00\x15\x00\x00\xd2SLX#[\xe9\x8a\x80\xe8\xa1\x8c\xe6\xa5\xad]\xe9\xa6\x99\xe6\xb8\xaf\xe9\x87\x91\xe8\x9e\x8d\xe6\xa5\xad\xe5\x90\x8c\xe8\xb7\xaf\xe4\xba\xbaj'Sav\x90\xd6S\x05\x00\x00\x00dr\xf92\x00\x00\x00\x00Lt\x01\x00\x9b\xdc\xf43K\xe0Gzv\x90\xd6S\x05\x00\x00\x00dr\xf92\x00\x00\x00\x00Nt\x01\x00\xc6\x13\xce\xa3s\xa0\x01^\xac}>]\x00\x00\x00\x00e\xaeT]\x00\x00\x00\x00\x01\xdc\x99\xa8g\xaeT]\x96\x03\x00\x00\x14\x00\x00\x00Y\xb4\xd6b\x15\xc4\xb5\x1c\x01\x00\x00\x00\xacN\x13rg\xaeT]\x94\xd1\x82\x83\xef\x81\x08\xb2\x89S#\xd3w\x83\x7f<,K\xed\x9b-J\xe6\x9e"

It turned out to be no problem last time.
I can`t find any problem in my codes.
what`s  Type 450b7115?

**Comment by Lonami** [comment]
This is a bug, not an enhancement. Telegram may have changed things in the layer without updating its version again, I will need to take a look.

**Comment by Lonami** [comment]
[A search for `450b7115` shows](https://ddg.gg/450b7115) in the third result:

> **long // TL-Schema**
> https://stek29.rocks/tl-schema/latest/type/long
> channel # 450b7115 channelForbidden # 289da732 inputChannel # afeb712e updateStickerSetsOrder # bb2d201 updateBotInlineQuery # 54826690 messages.botResults # 947ca848 updateBotCallbackQuery # e73547e1 updateBotCallbackQuery # e73547e1 inputBotInlineMessageID # 890c3d89

…which eventually brings us to https://stek29.rocks/tl-schema/latest/constructor/channel. It seems you have received a channel from an old version (layer 73). Now I need to know what version of the library you had.

**Comment by xyou365** [comment]
I am using 
```
>>> import telethon
>>> print(telethon.__version__)
1.3
>>> 
```
Too many INFO like this:
`2019-08-16 09:45:21,126 - telethon.network.mtprotosender - INFO - Server replied with an unknown type 450b7115`

Also seem that it is resource consuming. My system has killed my `main.py` many times.

**Comment by Lonami** [comment]
Could you try installing master?
```sh
pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip
```

**Comment by lanjianchun** [comment]
using the latest version 1.9.0 !

the problem fixed

thanks!

**Comment by tbgsystems** [comment]
Thanks for posting and resolving this, also hit the same issues and installing master worked

**Comment by Lonami** [comment]
Telegram probably made some changes server-side and older versions of the library can't do much about it since I only maintain the latest version.

**Comment by azharuniverse** [comment]
Telethon update solved the issue. Thanks
