### ISSUE TITLE
AttributeError: module 'telethon.tl.types' has no attribute 'FileLocation'

### ISSUE THREAD

**Issue by erichegit** [LonamiWebs/Telethon#1260]
Searching the www for this error, doesn`t show results to solve it.

AttributeError: module 'telethon.tl.types' has no attribute 'FileLocation'

What might be the issue for this?
My guress is, that maybe I need an older version of Telethon for https://github.com/expectocode/telegram-export

Would be great if somebody who has running this tells me the version he uses of Telethon.

**Comment by Lonami** [comment]
Telegram layer changes, raw API changes. `telegram-export` uses an older version of Telethon, but your version is too recent.
