### ISSUE TITLE
'TelegramClient' object has no attribute 'get_messages'

### ISSUE THREAD

**Issue by AmirNsr** [LonamiWebs/Telethon#1264]
I have installed the latest version of Telethon and was trying to extract posts from a channel.
I tried to use both `client.iter_messages()` and `client.get_messages()` using the channel entity but it kept telling me that client has not such a function.

**Code that causes the issue**
```from telethon import TelegramClient
from telethon.tl.functions.channels import JoinChannelRequest
from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.types import InputChannelEmpty
from telethon.tl.functions.messages import GetHistoryRequest,GetDialogsRequest

import socks
import time
import codecs
import pprint
import datetime

api_id = 1234
api_hash = 'abcdef'
phone_number='+1'

if __name__ == "__main__":
    client = TelegramClient('anon', api_id, api_hash, proxy=(socks.SOCKS5, 'localhost', 8080))
    client.connect()
    if not client.is_user_authorized():
        client.send_code_request(phone_number)
        me=client.sign_in(phone_number, input('Enter code: '))
    channel_name='somechannel'
    channel=client.get_entity(channel_name)
    posts = client.get_messages(channel)
```

**Traceback**
```
Traceback (most recent call last):
  File "code.py", line 24, in <code>
  posts=client.get_messages(channel)
  AttributeError: 'TelegramClient' object has no attribute 'get_messages'

```

**Comment by Lonami** [comment]
Please run this code:
```python
import telethon
print(telethon.__version__)
```

and show the output. because [`get_messages` exists](https://github.com/LonamiWebs/Telethon/blob/d5faf5e8aa3cf04774667ef2b567378b3dad5e2a/telethon/client/messages.py#L474).

**Comment by AmirNsr** [comment]
So I checked the version, I'm so sorry it was `0.15.5.7` I remember I rolled back to this version because of an issue a few days ago, my bad. but `pip install Telethon --upgrade` doesn't update it. I tried to delete the packages manually and install again but it didn't work either.
Do you have any idea? Thank you

**Comment by Lonami** [comment]
You should delete them with `pip uninstall`, not manually, but this no longer is an issue with Telethon.
