### ISSUE TITLE
Searching for text in a message

### ISSUE THREAD

**Issue by Shersto** [LonamiWebs/Telethon#1268]
Hi,

How do you get messages in a channel based on a keyword being present in that message. In other words i specify a keyword and return only full message results with that keyword present.

**Comment by Lonami** [comment]
This issue is a "Question about Usage", which [as the template states](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md),:
> QUESTIONS DON'T BELONG HERE. Ask in [StackOverflow](https://stackoverflow.com) or in [@TelethonUpdates](https://t.me/TelethonUpdates)

I will close this with the automatic label that such template would have applied, since I make no exceptions.
