### ISSUE TITLE
Getting message date

### ISSUE THREAD

**Issue by Shersto** [LonamiWebs/Telethon#1269]
Hi,

How do you get the message date of a message from a channel and return messages based on a date range or a specific date?

I wasn't able to find anything regarding it in the documentation that worked.

Ryan

**Comment by Lonami** [comment]
This issue is a "Question about Usage", which [as the template states](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md),:
> QUESTIONS DON'T BELONG HERE. Ask in [StackOverflow](https://stackoverflow.com) or in [@TelethonUpdates](https://t.me/TelethonUpdates)

I will close this with the automatic label that such template would have applied, since I make no exceptions.
