### ISSUE TITLE
Support a mode without receiving updates

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1270]
In some cases, one may wish to use the library without receiving any update back, for whatever reason (e.g. to reduce network traffic and work done by the library).

This can be done by wrapping every single outgoing request in [`invokeWithoutUpdates`](https://tl.telethon.dev/methods/invoke_without_updates.html), as described in https://core.telegram.org/api/invoking#disabling-updates. This adds an overhead of 4 bytes, which most of the time won't be noticeable due to padding.

**Comment by xspeed1989** [comment]
![image](https://github.com/LonamiWebs/Telethon/assets/5162926/fa622299-36a9-4dea-ab77-85b150ff2ada)

Why can I recive msg. help.  @Lonami

**Comment by Lonami** [comment]
`set_receive_updates` is not reliable as I thought. In v2, it's gone entirely.

**Comment by xspeed1989** [comment]
Do you means that InvokeWithoutUpdates dosen't support disable all updates?
