### ISSUE TITLE
Add Channel Members

### ISSUE THREAD

**Issue by dhruvjhamb1** [LonamiWebs/Telethon#1274]
How to add members to channel?
I have tried everything but couldn't success :') 
It is only showing groups , not channel :'( 
Can I get full code for adding members in channel?(not in groups)
Pleass Provide full code to execute for adding :'(

**Comment by Lonami** [comment]
This is the wrong place to ask **questions**. Only **issues** belong here. Further, this is considered spam, and Telegram will delete both the account used and the group.
