### ISSUE TITLE
client.get_participants\iter_participants improvement to get all users

### ISSUE THREAD

**Issue by TreefeedXavier** [LonamiWebs/Telethon#1275]
Hello, Lonami. Your project is great!
But can you update **iter_participants** method to get **all users** from chat? Now it fail, because of 200 limit.
Example: Search for 'a' in name, returns 211 in Telegramm. Aggressive iteration brings only 200 of them. But 'ac' and 'ab' searches brings 114 and 97.
Main idea: to loop aggressive search, if it brings 200 results, add search symbol to search variable, and start search from beginning. E.g. if 'a' brings 200 results, search for 'aa', 'ab', 'ac' etc.
Yes it very expensive about time, but for cases when all users need - it like holy grail.
I`m not good with python, but realize code like that:

```
start_letter = ''
async def iterate_letter(chat, start_letter, dictionary):
    v = None
    for x in string.digits + string.ascii_lowercase + "йцукенгшщзхъфывапролджэячсмитьбю":
        v = await client.get_participants(chat, search=start_letter + x)
        print('Search for ' + start_letter + x + " found " + str(v.__len__()) + " elements")
        if v.__len__() >= 200:
            await iterate_letter(chat, start_letter + x, dictionary)
        dictionary = await extract_users_to_dict(dictionary, v)
    return dictionary
```
as you see, method call itself, if get_participants returns equal or more, than 200 users with addition of extra symbol, which was used.

As I said already, it expensive, but returns all users. Hope you implement it in your code.

**Comment by Lonami** [comment]
This is not worth the added complexity. There is hardly any use case where you want to learn about all users anywhere. Search exists to help you search for someone you *know* and want to determine if they are in the chat. I have even considered removing `aggressive=` altogether to avoid helping spammers more.

**Comment by TreefeedXavier** [comment]
In my case I compare two chats, and want to ban in second chat users, which not in first chat. For that I need whole list of all users from both chats, and with your current implementation, list are differ. With my implementation, I receive result, that both chat contains same users and some additional - which have been banned now.

**Comment by Lonami** [comment]
Even if there are legit use cases, Telegram is imposing limits for a reason. You are free to roll your own version and use it, but I just don't think is worth the trouble to have it builtin like I said.
*<sub>Also, glad you like the project. It's appreciated.</sub>*
