### ISSUE TITLE
Use sign_in with right password but also report SessionPasswordNeededError

### ISSUE THREAD

**Issue by duanzheng** [LonamiWebs/Telethon#1277]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

try:
    client = TelegramClient(
        "../session/xx",
        "xxx",
        "xxx"
    )
    await client.connect()
    await client.sign_in(
        phone=phone, code=code, password=password, phone_code_hash=phone_code_hash
    )
    ...
except SessionPasswordNeededError:
    print("need password")

```
The result is that "need password" is printed every time.
The password is right because i use my Telegram account to test.
I know there is a start() function, but i need to use Telethon in a Flask server, so I have to use send_code_request and sign_in.

**Comment by duanzheng** [comment]
I read this article and get the answer:
https://telethonn.readthedocs.io/en/latest/extra/basic/creating-a-client.html#two-factor-authorization-2fa

**Comment by sabrysm** [comment]
> I read this article and get the answer: https://telethonn.readthedocs.io/en/latest/extra/basic/creating-a-client.html#two-factor-authorization-2fa

Thanks that was helpful

**Comment by Sonys9** [comment]
url is broken :(

**Comment by Lonami** [comment]
Use the official domain of docs.telethon.dev instead.
