### ISSUE TITLE
InputPhoneContact should work without passing client_id

### ISSUE THREAD

**Issue by KiteBoarder** [LonamiWebs/Telethon#128]
In TLSharp InputPhoneContact can be created without passing client_id. For example for creating a new contact like this example: 
https://stackoverflow.com/a/40850765/3769451
or this: 
https://github.com/sochix/TLSharp/issues/243 (answer by kerlaedra). 

But in telethon can't create an InputPhoneContact without passing a param for client_id. (Getting error: `missing 1 required positional argument: 'client_id'`)

Or if pass None for client_id, when calling `result = client.invoke(ImportContactsRequest(contacts, replace=True))` getting error: 
`TypeError: descriptor 'to_bytes' requires a 'int' object but received a 'NoneType'`

Here is an example demonstration: 
```
contact = InputPhoneContact(client_id=None, phone = "+012345678", first_name="ABC", last_name="abc")

result = client.invoke(ImportContactsRequest([contact], replace=True))

```

**Comment by pazis** [comment]
I have the exact same problem!

**Comment by Lonami** [comment]
I don't understand. On C# `long` defaults to 0, and if it isn't specified (`{ phone = phoneNumber, first_name = "", last_name = ""};` does not specify the `client_id`), then it will be 0. [TLInputPhoneContact](https://github.com/sochix/TLSharp/blob/40c1725e41da6cdb8b9170420532d0f0ca5ef590/TeleSharp.TL/TL/TLInputPhoneContact.cs) doesn't retrieve any client ID from anywhere, so I presume it's left to 0.

This is a snowflake on the API, so I can't just say "this can be `None` and should equal 0". Try specifying 0 yourself, it should be just as easy.

**Comment by KiteBoarder** [comment]
With 0 it doesn't work. I just tried it. 
(contacts.importedContacts (ID: 0xab123456) = (imported=None, retry_contacts=None, users=None))

**Comment by KiteBoarder** [comment]
See for example this, it seems it's defaulted to null, not 0. 
https://github.com/berwyn/mtproto.cs/blob/master/MTProto/TL/TLInputPhoneContact.cs
```
public TLInputPhoneContact(long? clientID = null, string phone = null, string firstName = null, string lastName = null)
        {
            if (clientID != null) this.ClientID = new TLLong(clientID.Value);
            if (phone != null) this.Phone = new TLString(phone);
            if (firstName != null) this.FirstName = new TLString(firstName);
            if (lastName != null) this.LastName = new TLString(lastName);
        }
```

**Comment by pazis** [comment]
It worked for me with `client_id=0`. Thanks.

**Comment by KiteBoarder** [comment]
@pazis did you create a new contact?

**Comment by KiteBoarder** [comment]
actually it worked for me too. I was using +01 for the phone number, changing that to +1 fixed it. thanks.

**Comment by KiteBoarder** [comment]
closing the issue.
