### ISSUE TITLE
Confusing error message when constructing PeerChannel (and others) from invalid peer ID

### ISSUE THREAD

**Issue by penn5** [LonamiWebs/Telethon#1282]
**Code that causes the issue**
```python
from telethon.sync import TelegramClient
await client.get_input_entity(PeerChannel(0))
```

**Traceback**
```
  File "/app/.heroku/python/lib/python3.7/site-packages/telethon/client/users.py", line 379, in get_input_entity
    return self._entity_cache[peer]
  File "/app/.heroku/python/lib/python3.7/site-packages/telethon/entitycache.py", line 88, in __getitem__
    result = self.__dict__.get(utils.get_peer_id(cls(item)))
  File "/app/.heroku/python/lib/python3.7/site-packages/telethon/utils.py", line 907, in get_peer_id
    10, math.floor(math.log10(peer.channel_id) + 3)))
ValueError: math domain error

```

The error message when the ID is not log-able should not be a confusing error like math domain error; it should be caught and rethrown.

**Comment by Lonami** [comment]
What are your use cases for constructing a `PeerChannel(0)`? As a side note, there are plenty of places where errors could be better (e.g. I think trying to send an integer or a list as the text of a message is not very good for the library).

**Comment by penn5** [comment]
> What are your use cases for constructing a `PeerChannel(0)`? As a side note, there are plenty of places where errors could be better (e.g. I think trying to send an integer or a list as the text of a message is not very good for the library).

To trigger an error message in someone else's code when the user is doing something wrong, but it might not matter to their code.
