### ISSUE TITLE
When the send_code_request interface is called, under what circumstances will PhoneCodeHashEmptyError appear?

### ISSUE THREAD

**Issue by duanzheng** [LonamiWebs/Telethon#1283]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
...
client = TelegramClient(
    "../shell/session/" + phone,
    application_config.get("api_id"),
    application_config.get("api_hash")
)
await client.connect()
await client.send_code_request(phone="+8618678394892", force_sms=True)
```

**Traceback**
Throw error:
The phone code hash is missing (caused by ResendCodeRequest)
However, if it is a US mobile number, this problem will not occur.

**Comment by Lonami** [comment]
Please add the following line:
```python
print(self._phone_code_hash, result)
```

After the shown line in your Python install (or, clone the repository, modify the file, and install it):
https://github.com/LonamiWebs/Telethon/blob/6da8d1a0ec7b5fd5d5bc17a97ee9e8216ece315c/telethon/client/auth.py#L484

Once that is done and the issue happens again, let me know the printed results.

**Comment by duanzheng** [comment]
The print is:
{'8617713551609': ''} SentCode(type=SentCodeTypeSms(length=0), phone_code_hash='', next_type=None, timeout=None)

I'm sure this phone number is available in Telegram App.

**Comment by duanzheng** [comment]
Is it possible that phone_code_hash is not required?

**Comment by Lonami** [comment]
It is strange that the `phone_code_hash` is the empty string, but if the `type=SentCodeTypeSms`, I guess there is no need to force resending it.

**Comment by duanzheng** [comment]
So is this not a problem?  Or will you fix this problem?

**Comment by Lonami** [comment]
The problem has been fixed by https://github.com/LonamiWebs/Telethon/commit/7de01a5f94731782a33c448a02b6cda1a818bb60, as it says right above your comment.
