### ISSUE TITLE
chat.megagroup not showing all the groups

### ISSUE THREAD

**Issue by UsmanSanawar** [LonamiWebs/Telethon#1287]
**Code that causes the issue**
```python
result = client(GetDialogsRequest(
             offset_date=last_date,
             offset_id=0,
             offset_peer=InputPeerEmpty(),
             limit=chunk_size,
             hash = 0
         ))

chats.extend(result.chats)
dialogs = client.get_dialogs()

m = input("Choose Option To Select Groups\n1: For only permitted groups \n2: For all groups\n")

if m=='1':
    for chat in chats:
        try:
            if chat.megagroup == True:
                groups.append(chat)
        except:
            continue

elif m=='2':
    for i in dialogs:
        try:
            i.entity.status
        except:
            groups.append(i)
            continue

```

I'm trying to fetch members and sending them invites for other groups, but when using `chat.megagroup==true`
it is not showing all the channels (in m==1), 
and it's also have issues like sometimes group A and group B is shown, sometimes either A or B is shown, sometimes group C is shown, don't know why without changing anything from the code.
In m==2, all the groups are shown.

Can you please guide what I'm doing wrong or it's something else?

Really appreciate your time, Thanks

**Comment by Lonami** [comment]
This is not a bug in the library and thus does not belong here.

**Comment by UsmanSanawar** [comment]
Then why It's giving random groups?

**Comment by UsmanSanawar** [comment]
And if it does not belong here, where should I ask, atleast tell this.

**Comment by Lonami** [comment]
> If you DO have a question, ask in:
> * https://stackoverflow.com or
> * https://t.me/TelethonUpdates (@TelethonUpdates channel in Telegram)

From [`question-about-usage.md`](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md).

**Comment by UsmanSanawar** [comment]
Thanks for the reply
