### ISSUE TITLE
Compatible with asyncio.run()

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1288]
**[Changing the way something works]**

`loop` attribute in ` class telethon.client.telegrambaseclient.TelegramBaseClient()` must not auto create a loop when `None` passed in for we will be able to use `asyncio.run()` instead of `asyncio.get_event_loop().run_until_complete()`.
Because `asyncio.run()` always create a new loop and if any loop created in the same thread before raises an error.

Example:

```
import asyncio
from telethon import TelegramClient

api_id = 12345
api_hash = '0123456789abcdef0123456789abcdef'
client = TelegramClient('name', api_id, api_hash, loop = None)

async def main():
    async with client:
        me = await client.get_me()
        print(me.username)

asyncio.run(main())
```

**Comment by Lonami** [comment]
```python
async def main():
    async with TelegramClient('name', api_id, api_hash) as client:
         me = await client.get_me()
         print(me.username)

asyncio.run(main())
```

…will work as expected. The `loop` is passed down to a lot of children instances, and I don't think doing `loop or asyncio.get_event_loop()` in every single one of them is a good idea.

If someone can come up with a good solution (in case my proposed workaround is not good enough), I will not mind to add it. Pull requests, of course, are even more welcome.
