### ISSUE TITLE
Unread Messages From a Channel/Group

### ISSUE THREAD

**Issue by smahesh29** [LonamiWebs/Telethon#1300]
How to print all unread messages from a particular channel/group.
I used the following code which is taken from official documentation but it is not working. 

```
from telethon.sync import TelegramClient
from telethon import functions, types

with TelegramClient(name, api_id, api_hash) as client:
    result = client(functions.messages.GetUnreadMentionsRequest(
        peer='username',
        offset_id=42,
        add_offset=0,
        limit=100,
        max_id=0,
        min_id=0
    ))
    print(result.stringify())
```

I wants to print all the unread messages from a particular channel/group.

**Comment by Lonami** [comment]
This issue is a "Question about Usage", which [as the template states](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md),:
> QUESTIONS DON'T BELONG HERE. Ask in [StackOverflow](https://stackoverflow.com) or in [@TelethonUpdates](https://t.me/TelethonUpdates)

I will close this with the automatic label that such template would have applied, since I make no exceptions.
