### ISSUE TITLE
When downloading media by telethon I get FILEREF_UPGRADE_NEEDED

### ISSUE THREAD

**Issue by Maxsym** [LonamiWebs/Telethon#1301]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
self.download_media(message, media_file_path)

**Traceback**
```
  File "L:\Work\GrandServiceUpgrade\Services\Bot2ApiEnhanced\botlogic.py", line 2394, in download_media_image
    self.download_media(message, media_file_path)
  File "L:\Work\GrandServiceUpgrade\Services\Bot2ApiEnhanced\telethon\telegram_client.py", line 2179, in download_media
    media, file, date, progress_callback
  File "L:\Work\GrandServiceUpgrade\Services\Bot2ApiEnhanced\telethon\telegram_client.py", line 2221, in _download_photo
    progress_callback=progress_callback)
  File "L:\Work\GrandServiceUpgrade\Services\Bot2ApiEnhanced\telethon\telegram_client.py", line 2432, in download_file
    input_location, offset, part_size
  File "L:\Work\GrandServiceUpgrade\Services\Bot2ApiEnhanced\telethon\telegram_bare_client.py", line 486, in __call__
    result = self._invoke(call_receive, request, ordered=ordered)
  File "L:\Work\GrandServiceUpgrade\Services\Bot2ApiEnhanced\telethon\telegram_bare_client.py", line 583, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)

  <class 'telethon.errors.rpc_base_errors.AuthKeyError'> FILEREF_UPGRADE_NEEDED

```

**Comment by Lonami** [comment]
Are you sure you are using the latest version of the library? You checked:
> * [x] I ran pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip and triggered the bug in the latest version.

But the error should be different if you had actually done that. So, please make sure you are using the latest version, and then, please post code that triggers the issue.

**Comment by ehsanonline** [comment]
I'm having a similar issue, but I got `telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EXPIRED (caused by GetFileRequest)`
I tried to download a large file (over 1GB) and at the middle of download (90%-95%) got this:
```
Task exception was never retrieved
future: <Task finished coro=<download() done, defined at downloader.py:96> exception=BadRequestError('RPCError 400: FILE_REFERENCE_EXPIRED (caused by GetFileRequest)')>
Traceback (most recent call last):
  File "downloader.py", line 99, in download
    return await client.download_media(msg,Path,progress_callback=progress_callback)
  File "site-packages\telethon\client\downloads.py", line 352, in download_media
  File "site-packages\telethon\client\downloads.py", line 720, in _download_document
  File "site-packages\telethon\client\downloads.py", line 435, in download_file
  File "site-packages\telethon\requestiter.py", line 75, in __anext__
  File "site-packages\telethon\client\downloads.py", line 60, in _load_next_chunk
  File "site-packages\telethon\client\downloads.py", line 70, in _request
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EXPIRED (caused by GetFileRequest)
```
how can I update the `file_refrence` while downloading? (assuming I have access to the  telegram message)
Telethon==1.10.8
cryptg==0.2.post0

**Comment by Lonami** [comment]
Ideally, the library would handle `FILEREF`-related errors transparently by re-fetching the `Message`it was trying to download from. With regards to the CPU usage, I do not know what the cause could be, but it might just be the work required for encryption. With regards to the speed, both `cryptg` and `download_media` methods have plenty of room for improvement.

**Comment by Lebron-Bryant** [comment]
> 我遇到类似的问题，但是我`telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EXPIRED (caused by GetFileRequest)`
> 尝试下载大文件（超过1GB），并且每次在下载过程中（90％-95％）都得到了以下信息：
> 
> ```
> Task exception was never retrieved
> future: <Task finished coro=<download() done, defined at downloader.py:96> exception=BadRequestError('RPCError 400: FILE_REFERENCE_EXPIRED (caused by GetFileRequest)')>
> Traceback (most recent call last):
>   File "downloader.py", line 99, in download
>     return await client.download_media(msg,Path,progress_callback=progress_callback)
>   File "site-packages\telethon\client\downloads.py", line 352, in download_media
>   File "site-packages\telethon\client\downloads.py", line 720, in _download_document
>   File "site-packages\telethon\client\downloads.py", line 435, in download_file
>   File "site-packages\telethon\requestiter.py", line 75, in __anext__
>   File "site-packages\telethon\client\downloads.py", line 60, in _load_next_chunk
>   File "site-packages\telethon\client\downloads.py", line 70, in _request
> telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: FILE_REFERENCE_EXPIRED (caused by GetFileRequest)
> ```
> 
> `file_reference`下载时如何更新？（假设我可以访问电报消息）
> Python 3.8
> Telethon == 1.10.8
> cryptg == 0.2.post0
> 
> ps：下载速度（甚至使用cryptg解密）也比PC的原始电报客户端要慢得多，并且占用大量CPU！（在Windows 10和Ubuntu 18.04上测试）

Brother, I have the same problem. Have you solved it?

**Comment by ehsanonline** [comment]
@Lebron-Bryant No, sorry. I ended up using Telegram official client for downloading.

**Comment by Lonami** [comment]
This error should not occur if the message was just fetched (only if it's stored for later download). Is this the case?

**Comment by ehsanonline** [comment]
yes. but not later download. the problem is downloading a large file is taking time, and while it is downloading, the `file_ref` might become expired. so the telethon needs to a get new `file_ref` from the message and continue downloading.

**Comment by Lonami** [comment]
Ah, right, solving that is more reasonable.

**Comment by Lebron-Bryant** [comment]
> @Lebron-Bryant No, sorry. I ended up using Telegram official client for downloading.

Ok, I'll think of something else.

**Comment by Lonami** [comment]
Using `download_media` with the **entire message object** should now enable Telethon to resume the download when necessary.

**Comment by Lebron-Bryant** [comment]
> Using `download_media` with the **entire message object** should now enable Telethon to resume the download when necessary.
Ok, I'll have a try.

**Comment by ehsanonline** [comment]
Thanks, but why only implemented for documents? other file types like videos can be large as 2000MB~2GB. 

> Only implemented for documents which are the ones that may take that long to download

**Comment by Lonami** [comment]
Every file not sent as a compressed photo media is a "document" (videos, songs, stickers, files…).
