### ISSUE TITLE
send_code_request to return registered

### ISSUE THREAD

**Issue by dumpload** [LonamiWebs/Telethon#1304]
I think it is necessary for **client.send_code_request** to return whether the account is registered
found the isu,1.9.0 change to 1.10.6 . is complex
thank you vrey much

**Comment by Lonami** [comment]
This is not possible due to changes in Telegram's schema update. It was returning the raw response, so breaking changes are to be expected between minor releases.

**Comment by Lonami** [comment]
The expected flow now is to try to login, and if the phone number is unoccupied, then proceed to the register form.

**Comment by dumpload** [comment]
not copy sms code to send sms register:
use ipython env
Telethon==1.10.7
```
from telethon import TelegramClient
from telethon.sessions import StringSession
api_id =""
api_hash = ""
client = TelegramClient(StringSession(""), api_id=api_id,api_hash=api_hash)
client.connect()
client.is_user_authorized()
phone = ""
sendcode = client.send_code_request(phone,force_sms=True)
**# no sms code n**
sendcode.phone_code_hash
code = ""
firstname = "fffname"
lastname = "lllname"
singup = client.sign_up(code,first_name=firstname, last_name=lastname, phone=phone,phone_code_hash=sendcode.phone_code_hash)
```
