### ISSUE TITLE
"retries" is not in TelegramBareClient.__call__ ()'s parameters list

### ISSUE THREAD

**Issue by qiyuyi** [LonamiWebs/Telethon#1309]
my code use:
                     future=asyncio.run_coroutine_threadsafe(client.get_dialogs(),loop)
It may run all the time without returning results.
It's not good for me to set timeout in future.result() by myself.
Could  re-add “retries” parameters in sending request like telethon-v0?

**Comment by Lonami** [comment]
`TelegramBareClient` doesn't exist. The base class is `TelegramBaseClient`, which *does* have a `request_retries` parameter:
https://github.com/LonamiWebs/Telethon/blob/4a8b19b0bef186e2b4058ce6961a9f65ea65c460/telethon/client/telegrambaseclient.py#L83-L92
