### ISSUE TITLE
Invalid channel object

### ISSUE THREAD

**Issue by msa21974** [LonamiWebs/Telethon#131]
Hi Lonami,
My project was working properly in few months until yesterday!!
and when i saw log , this error was displayed:
`telethon.errors.RPCError: (RPCError(...), 'Invalid channel object. Make sure to pass the right types.')`

I wrote this test code : 
`client.send_message(InputPeerChannel(CHANNEL_ID,CHANNEL_ACCESSHASH),'Test')`
and same error was displayed.

I am confused because in the past it was working properly

**Comment by Lonami** [comment]
I made some changes to certain requests (send message is affected) so I will have to look into that.

**Comment by Lonami** [comment]
I just tested with a channel of mine and it worked fine, so I don't know what can be happening. Are you sure you're passing the **right** ID and hash combination?

**Comment by msa21974** [comment]
tnx,
I was changed my account and used the stored ID,ACCESSHASH  with previous account
it's my mistake .
after i updated ACCESSHASH with new account , problem solved

how some libraries in nodeJS send message without access hash ? (Just with ID)

**Comment by Lonami** [comment]
> how some libraries in nodeJS send message without access hash ? (Just with ID)

I doubt that's possible. What library, in particular?
