### ISSUE TITLE
Mtproto proxy

### ISSUE THREAD

**Issue by z0oz0o** [LonamiWebs/Telethon#1310]
Hi,
I want to check different proxies for connection.
But after a few attempts I get to the following error:
error: required argument is not an integer
this my code:
 for proxy in proxy_information:
        try:
            telegram_client = TelegramClient('session_name', 
                               api_id,
                                api_hash,
                                connection=ConnectionTcpMTProxyRandomizedIntermediate,
                                connection_retries=0,
                                request_retries=1,
                                auto_reconnect=False,
                                proxy=(proxy['server'], proxy['port'], proxy['secret'])) 
        except ConnectionError:
            continue

**Comment by Lonami** [comment]
Please provide the full traceback if you want meaningful answers. In addition, use code blocks to properly format your code. As it stands, it's hardly readable.
