### ISSUE TITLE
How to use multiple parallel telegram client with one session?

### ISSUE THREAD

**Issue by Qwentor** [LonamiWebs/Telethon#1317]
How to use multiple parallel telegram client with one session?
I foud this https://github.com/LonamiWebs/Telethon/issues/146 but it doesn't work
`AttributeError: 'TelegramClient' object has no attribute 'create_new_connection'`

**Comment by Lonami** [comment]
This issue is a "Question about Usage", which [as the template states](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md),:
> QUESTIONS DON'T BELONG HERE. Ask in [StackOverflow](https://stackoverflow.com) or in [@TelethonUpdates](https://t.me/TelethonUpdates)

I will close this with the automatic label that such template would have applied, since I make no exceptions.
