### ISSUE TITLE
Support easily deleting all messages from a user

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1318]
Something like:
```python
client.delete_messages(chat, from_user='foo')
```

This would use [`channels.deleteUserHistory`](https://tl.telethon.dev/methods/channels/delete_user_history.html) (after verifying that's actually the right request to use…). Parameter name may vary, and it should be documented that bots cannot use it, and will only work in megagroups.

**Comment by sanatmorgh** [comment]
python pip install telethon

**Comment by Lonami** [comment]
What?

**Comment by Lonami** [comment]
This is unlikely to happen in the near future so I will be closing the issue. We can reopen it if there's still interest once the time is right.
