### ISSUE TITLE
Investigate newer MTProto proxies

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1319]
As per https://t.me/TelethonChat/167056:

> https://t.me/proxy?server=yet.live.ovh&port=443&secret=ee726b6e2068757920736f736974653a29676f6f676c652e636f6d

> does it work if you use
> 'ee726b6e2068757920736f736974653a'
> as the secret?

> Hi! You can add some changes... then this proxies will work

> /usr/local/lib/python3.7/dist-packages/telethon/network/connection/tcpmtproxy.py

> Edit line 34:
> is_dd = (len(secret) == 17) and ((secret[0] == 0xDD) or (secret[0] == 0xEE))

**Comment by seriyps** [comment]
Well, it's not that easy. `ee`-proxies use Fake-TLS protocol which is another layer on top of `dd`-protocol (ConnectionTcpMTProxyRandomizedIntermediate). 

Some code examples:

https://github.com/alexbers/mtprotoproxy/blob/199eaeb7c4e9c871b5c0b917fc82be1a0fa03b04/mtprotoproxy.py#L568-L623

https://github.com/alexbers/mtprotoproxy/blob/199eaeb7c4e9c871b5c0b917fc82be1a0fa03b04/mtprotoproxy.py#L1065-L1152

**Comment by wangyandong** [comment]
Need ee mode proxy too...

**Comment by AmirHmZz** [comment]
Does Telethon support ee- yet ?

**Comment by SinaKarimi7** [comment]
I need this. Most of the new mtproto proxies use ee- and others have been blocked by country. When Telethon support it?

**Comment by Lonami** [comment]
Telethon will support the new proxy format when someone with the knowledge and will to implement it implements it.

**Comment by Lonami** [comment]
After determining how these proxies work, the relevant changes would need to be made in the [`connection` module](https://github.com/LonamiWebs/Telethon/tree/master/telethon/network/connection) to accomodate these new proxies. The existing basic MTProto proxy should help as a starting point.

**Comment by xun-mi-git** [comment]
# Investigate newer MTProto proxies
## Use secret with uncertain length
> does it work if you use
'ee5277cce9da9749bf9a5746e6090a46207777772e6d6963726f736f66742e636f6d'
Errors will occur
# dubug
> ValueError: MTProxy secret must be a hex-string representing 16 bytes

**Comment by be42day** [comment]
You should use an MTProxy with the Secret in hexadecimal format (created with the following letters `0123456789abcdef`).
You can use the `@chatme1_bot` bot in the Telegram application to find an MTProxy with the appropriate Secret.
For example the bellow is an appropriate proxy to use in Telethon (I tested it and worked):
proxy=('always-connected.ddns.net.', 443, 'dd00000000000000000000000000000000')

**Comment by Lonami** [comment]
I have no intention to maintain MTProto proxy support, therefore, I'm closing this issue. If someone is interested in developing and maintaining MTProto proxies, please let me know or contact me, and we can work together so Telethon is able to provide the necessary abstractions for users to be able to plug proxy implementations from other projects.

**Comment by Ro0tz5** [comment]
use this
https://github.com/Ro0tz5/telethon-faketls

**Comment by kingofnull** [comment]
> use this https://github.com/Ro0tz5/telethon-faketls

You done a great job sir but unfortunately it has broken now. It just stuck in reconnecting and disconnecting and never connects to server! I also tried to downgrading Telethon to version 1.19.1 but that didn't work too.  

My code (`print("Starting...")` never called) :
```python
from telethon import TelegramClient, connection
import TelethonFakeTLS


# Remember to use your own values from my.telegram.org!
api_id = 12333232
api_hash = '******************************'

//used proxy: https://t.me/proxy?server=185.145.245.93&port=443&secret=Ee32b920dffb51643028e2f6b878d4eac16d61696c2e676f6f6c652e746f6b686d65

_proxy = _proxy = ('185.145.245.93', 443, '32b920dffb51643028e2f6b878d4eac16d61696c2e676f6f6c652e746f6b686d65')
_con=TelethonFakeTLS.ConnectionTcpMTProxyFakeTLS


client = TelegramClient('anon', api_id, api_hash,proxy=_proxy,connection=_con)

async def main():
	print("Starting...")

	# Getting information about yourself
	me = await client.get_me()
	print(me.stringify())

with client:
    client.loop.run_until_complete(main())

```

I add a  print to functions to debug the process and this is the result:

![image](https://user-images.githubusercontent.com/11198668/204100223-0ad39a7f-c316-40be-98a7-8a29a2b2a032.png)


And finally I stopped it by cntr+c :

![image](https://user-images.githubusercontent.com/11198668/204100316-4686b7a2-521c-460c-874f-6892025aa5d2.png)

Also there is logger output in info mode:

```log
[ INFO/2022-11-26 21:08:46,305] telethon.network.mtprotosender: Connecting to 185.145.245.93:443/TcpMTProxyFakeTLS...
[ INFO/2022-11-26 21:08:46,443] root: Sending FakeTLS headers...
[ INFO/2022-11-26 21:08:46,444] root: FakeTLS headers sent.
[ INFO/2022-11-26 21:08:46,444] root: Receiving server hello and verifying it...
[ INFO/2022-11-26 21:08:46,584] root: len(server_hello)=138
[ INFO/2022-11-26 21:08:46,584] root: http_data_len=3244
[ INFO/2022-11-26 21:08:46,585] root: FakeTLS handshake completed.
[ INFO/2022-11-26 21:08:46,586] telethon.network.mtprotosender: Connection to 185.145.245.93:443/TcpMTProxyFakeTLS complete!
[ INFO/2022-11-26 21:08:46,727] telethon.network.connection.connection: The server closed the connection
[ INFO/2022-11-26 21:08:46,728] telethon.network.connection.connection: <class 'AttributeError'> during disconnect: 'FakeTLSStreamWriter' object has no attribute 'wait_closed'
[ INFO/2022-11-26 21:08:46,729] telethon.network.mtprotosender: Connection closed while receiving data
[ INFO/2022-11-26 21:08:46,729] telethon.network.mtprotosender: Closing current connection to begin reconnect...
[ INFO/2022-11-26 21:08:46,730] telethon.network.connection.connection: <class 'AttributeError'> during disconnect: 'FakeTLSStreamWriter' object has no attribute 'wait_closed'
[ INFO/2022-11-26 21:08:46,730] telethon.network.mtprotosender: Connecting to 185.145.245.93:443/TcpMTProxyFakeTLS...
[ INFO/2022-11-26 21:08:46,885] root: Sending FakeTLS headers...
[ INFO/2022-11-26 21:08:46,886] root: FakeTLS headers sent.
[ INFO/2022-11-26 21:08:46,886] root: Receiving server hello and verifying it...
[ INFO/2022-11-26 21:08:47,031] root: len(server_hello)=138
[ INFO/2022-11-26 21:08:47,032] root: http_data_len=3242
[ INFO/2022-11-26 21:08:47,032] root: FakeTLS handshake completed.
```

**Comment by Lonami** [comment]
@kingofnull it's probably a better idea to open an issue in that repository rather than to comment here, as this is not something I can fix directly myself.

**Comment by kingofnull** [comment]
> @kingofnull it's probably a better idea to open an issue in that repository rather than to comment here, as this is not something I can fix directly myself.

Somebody already did it [here](https://github.com/Ro0tz5/telethon-faketls/issues/3) and he  did hasn't fixed it or replied, It seams to work with some of proxy servers but not all of them. I mention the bug here to get help from others.

**Comment by hntcAir** [comment]
same problem here.
