### ISSUE TITLE
connect will crash after an RPC error 

### ISSUE THREAD

**Issue by KiteBoarder** [LonamiWebs/Telethon#132]
Here is a code which for demonstration returns an RPC error. On the next run connect() should return False and we should keep calling connect() until it returns True. But I noticed when connect returns False, calling it again will cause an exception. Run the following code, and run it again, it never gets to  `print ("it won't get here!")` because it crashes on line `result = client.connect()`

```
from telethon.tl.types.input_peer_channel import InputPeerChannel
from telethon.tl.functions.messages.forward_messages import ForwardMessagesRequest
from telethon.helpers import generate_random_long
from telethon.tl.types.input_peer_chat import InputPeerChat
from telethon.telegram_client import TelegramClient


client = TelegramClient(...)
result = client.connect()
print (result)

if not result: 
    print ("here")
    result = client.connect()
    print ("it won't get here!")
    print (result)

source_chat_id=1234 
source_access_hash=1234
source_chat = InputPeerChannel(source_chat_id, source_access_hash)

#testGroup: 
dest_chat_id = 123400
dest_chat = InputPeerChat(dest_chat_id)

result = client.invoke(ForwardMessagesRequest(from_peer=source_chat, id=[1234], random_id=[generate_random_long()], to_peer=dest_chat))
```

Also I don't understand why there should be history for the connect. If the code crashes why next run remembers the previous crash and connect will return False? Well I understand there might be some RPC connection things like acks going on, but shouldn't that be transparent to end user?

**Comment by Lonami** [comment]
I changed the last line for this:
```python
try:
    print('Reached invoke')
    result = client.invoke(ForwardMessagesRequest(from_peer=source_chat, id=[1234], random_id=[generate_random_long()], to_peer=dest_chat))
finally:
    client.disconnect()
```

And on the next run, it does *not* fail (it never enters the `if not result:`). You should always call `.disconnect()`, if possible.

I tested without the change, and I still can't reproduce. It never enters said `if`. What version are you using?

**Comment by KiteBoarder** [comment]
My version 0.10.1
Even with the disconnect, it still crashes next time here: 
```
if not result: 
    print ("here")
    result = client.connect() <-----crashes here even with the disconnect 
```

**Comment by Lonami** [comment]
> My version 0.10.1

Upgrade. Latest is `v0.11`.

**Comment by KiteBoarder** [comment]
Great @Lonami!! version 0.11 fixed the issue. Even without try catch (and even without disconnect) next time the error won't show up at the start. So runs are independent!

**Comment by KiteBoarder** [comment]
Closing...

**Comment by Lonami** [comment]
> and even without disconnect

You should always call it when you're done though.

**Comment by KiteBoarder** [comment]
Makes sense, and I will call disconnect()! Thank you!
