### ISSUE TITLE
Embedded maps?

### ISSUE THREAD

**Issue by pakesusu** [LonamiWebs/Telethon#1320]
**Checklist**
* [x] The error is in the library's code, and not in my own. (yes, im even need to uninstall and install)
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

Hi Lonami and all,

It's seems my python code wont catch raw_text if someone send me an embedded maps like this

![image](https://user-images.githubusercontent.com/37841938/68079772-8d545180-fe21-11e9-8d68-427acdd197ae.png)

then the code will Okay, catch the raw_text if no maps embedded.

i was thinking with event.message, but it seems not a fix.

have a clue?

**Comment by pakesusu** [comment]
Ooops sorry, after enabling logging, everything's clear now, thanks!

```
    user = await client.get_entity(event.original_update.user_id)
AttributeError: 'UpdateNewMessage' object has no attribute 'user_id'
```

**Comment by Lonami** [comment]
`event.original_update` is generally a code smell, you're supposed to be using `event.sender_id`.
