### ISSUE TITLE
Bot payments support

### ISSUE THREAD

**Issue by GolemXlV** [LonamiWebs/Telethon#1321]
Hello there! Does this project support Bot API Payments? I did not find this in the documentation.
At the moment, I am interested in these methods:
[inputMessageInvoice](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_message_invoice.html
)
[answerShippingQuery](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1answer_shipping_query.html)
[answerPreCheckoutQuery](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1answer_pre_checkout_query.html)
[paymentResult](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1payment_result.html)

**Comment by Lonami** [comment]
As a MTProto library, it supports *everything* that Telegram's API supports (and Bot API uses a subset of it), so the answer is yes. I haven't investigated into it myself (and if someone else has, nobody has sent a pull request), so you have to use raw API yourself (e.g. [search "payment"](https://tl.telethon.dev?q=payment)). If you or anyone figures it out, I would love to add it as a friendly method in the library.

**Comment by Lonami** [comment]
This was added by #1470, but I forgot to close it before.
