### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by muhammedfurkan** [LonamiWebs/Telethon#1329]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```
python 3.7.5
File "/app/.heroku/python/lib/python3.7/site-packages/telethon/helpers.py", line 28, in add_surrogate
if (0x10000 <= ord(x) <= 0x10FFFF) else x for x in text
TypeError: 'NoneType' object is not iterable
```

**Comment by Lonami** [comment]
This error is in your code. You can't send a text message if the text is `None`.
