### ISSUE TITLE
FloodWaitError on CheckChatInviteRequest

### ISSUE THREAD

**Issue by karambaq** [LonamiWebs/Telethon#1331]
**Code that causes the issue**
```python
from telethon.sync import TelegramClient

def get_private_channel_entity(channel_invite_link):
    with TelegramClient(api_id=api_id, api_hash=api_hash, session='session.session') as client:
        channel = client.get_entity(channel_invite_link)

```

Since today that was worked for like a 6 month perfect. But today there is a FloodWait occurred, I tried to create another api_id and api_hash, but gets FloodWait on the first request immediately. 

Also, I wonder is there a way to store entity, so I can put them in a database and save some requests to not get banned?

Thank you!

**Comment by Lonami** [comment]
Not a bug in the library, therefore it doesn't belong here.

**Comment by karambaq** [comment]
@Lonami All right thank you for the help appreciate that.
