### ISSUE TITLE
Add events.UnhandledException

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1332]
Other libraries have a way to register callbacks when unhandled errors happen. The default could still be to just log it, but maybe users want to do something else.

This event could be special and trigger on unhandled exceptions, coming with additional information such as the `Exception` object, which `Event` triggered it, and in which callback it happened in:

```python
@client.on(events.UnhandledException)
async def error_handler(event):
    await event.client.send_message('me',
        'Master, an error occured: ' + event.exception.__class__.__name__)

@client.on(events.NewMessage)
async def hello_handler(event):
    await event.replo('Clearly this method exists')
```

**Comment by alimrd318** [comment]
sorry , how can create a specifice event ?
for example an event run at 12:00

**Comment by alimrd318** [comment]
> sorry , how can create a specifice event ?
> for example an event run at 12:00 or run every 5 hours

**Comment by alimrd318** [comment]
> Other libraries have a way to register callbacks when unhandled errors happen. The default could still be to just log it, but maybe users want to do something else.
> 
> This event could be special and trigger on unhandled exceptions, coming with additional information such as the `Exception` object, which `Event` triggered it, and in which callback it happened in:
> 
> ```python
> @client.on(events.UnhandledException)
> async def error_handler(event):
>     await event.client.send_message('me',
>         'Master, an error occured: ' + event.exception.__class__.__name__)
> 
> @client.on(events.NewMessage)
> async def hello_handler(event):
>     await event.replo('Clearly this method exists')
> ```
sorry , how can create a specifice event ?
for example an event run at 12:00 or run every 5 hours

**Comment by Lonami** [comment]
I do not think this suits the library, because that's not actually an "event" per se, but here's a workaround:

```python
async def error_handler(event, exception):
    ...  # YOUR CUSTOM ERROR HANDLER FOR ALL EVENTS HERE

# THIS PATCHES THE add_event_handler METHOD
orig_add_event_handler = TelegramClient.add_event_handler
@functools.wraps(TelegramClient.add_event_handler)
def patched_add_event_handler(client, callback, event_builder=None):
    @functools.wraps(callback)
    async def new_callback(event):
        try:
            return await callback(event)
        except Exception as exc:
            return await error_handler(event, exc)
    orig_add_event_handler(client, new_callback, event_builder)
TelegramClient.add_event_handler = patched_add_event_handler
# REST OF YOUR CODE BELOW

...
```

As a bonus you can access the event that triggered the exception in the first place. Note that this will get rid of the exception logging on the handlers because this will catch them all.

Closing.
