### ISSUE TITLE
aiofiles in downloads/upload files?

### ISSUE THREAD

**Issue by mayli** [LonamiWebs/Telethon#1334]
The current implementation of file upload/download are using the default IO methods, is it worth to implement the support for aiofiles?
It could be change the like

            async for chunk in self.iter_download(
                    input_location, request_size=part_size, dc_id=dc_id):
                f.write(chunk)

to 

            async for chunk in self.iter_download(
                    input_location, request_size=part_size, dc_id=dc_id):
                rf = f.write(chunk)
                if inspect.isawaitable(rf):
                    await rf

https://github.com/LonamiWebs/Telethon/blob/6817e199234b68688c5ae1a128353df34f15ba18/telethon/client/downloads.py#L434

**Comment by Lonami** [comment]
Sure, I am not against it. Since you already have the code, do you want to make a pull request? We might need to note this in the documentation too.

**Comment by mayli** [comment]
I can work on this, I don't have the code right now but it's should be pretty straightforward.

**Comment by mayli** [comment]
I did some benchmark with aiofiles, but it seems to be slower

    async def download(media):
        filename = media.document.attributes[0].file_name
        with TqdmUpTo(unit='B', unit_scale=True, miniters=1, desc=filename) as t:
            # async with aiofiles.open(filename, 'wb') as af:   <- async
            # with open(filename, 'wb') as af:                         <- sync
                await client.download_file(media, af, progress_callback=t.update_to)
        return filename

sync version
real    2m55.846s
user    1m27.963s
sys     0m4.616s

async version
real    3m25.953s
user    1m28.260s
sys     0m5.154s

I think probably the reason is that my sync IO with SSD is much faster than performing IO in threads plus the overhead of communication over async protocol.

**Comment by Lonami** [comment]
Oh, I thought the idea was just to support async file handles, not use them ourselves when the user passes a path. So, a path or normal `open` is synchronous, but if the user passes an asynchronous file, it will work too. Then, the choice is up to them. Asynchronous file handles may work better if Telethon ran the download or upload of many chunks in parallel.
