### ISSUE TITLE
Disable Channel Notification

### ISSUE THREAD

**Issue by Morteza-Vatanparast** [LonamiWebs/Telethon#1336]
How can I disable notification for channel and group?

**Comment by Lonami** [comment]
This issue is a "Question about Usage", which [as the template states](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md),:
> QUESTIONS DON'T BELONG HERE. Ask in [StackOverflow](https://stackoverflow.com) or in [@TelethonUpdates](https://t.me/TelethonUpdates)

I will close this with the automatic label that such template would have applied, since I make no exceptions.
