### ISSUE TITLE
Directory problem

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#134]
Sorry if I open another issue, i have the same problem when i run try_telethon.py 

```
from ..tl.all_tlobjects import tlobjects
ModuleNotFoundError: No module named 'telethon.tl.all_tlobjects'
```
i dont know why

**Comment by Lonami** [comment]
Are you running that from within the same directory as the file?

**Comment by seby2000** [comment]
yes

**Comment by Lonami** [comment]
Are you sure you manage to run the `tl_generator.py` successfully? There should be a file called `all_tlobjects.py` under `telethon/tl`.

**Comment by seby2000** [comment]
it there isn't but when i started tl_genrator.py it  did not report any errors.

**Comment by seby2000** [comment]
what i done is putting tl_generator.pt and scheme.tl in parser. 
Then i changed two lines with these in tl_generator.py
```
from source_builder import SourceBuilder
    from tl_parser import TLParser
```
and in tl_parser.py i changed the 3 line with this 
`from tl_object import TLObject`
