### ISSUE TITLE
in line 468  "if sent.phone_registered:"  the sent is no phone_registered

### ISSUE THREAD

**Issue by lanluyu** [LonamiWebs/Telethon#1341]
Please describe your idea. Would you like another friendly method? Renaming them to something more appropriated? Changing the way something works?

the sent is no attribute phone_registered, so the Example code should be  changed ?

**Comment by Lonami** [comment]
Yes, [the example code should be changed](https://github.com/LonamiWebs/Telethon/blob/a360d74a4cd8421c89caaba07faea63bba29ff4f/telethon/client/auth.py#L468-L471).
