### ISSUE TITLE
Allow events.EventBuilder.func to be async function

### ISSUE THREAD

**Issue by JuniorJPDJ** [LonamiWebs/Telethon#1344]
I'm having trouble with making simple function, which need to use async props of client.
It obviously can't because this function needs to be sync and sync function can't call async functions :/
Making .filter() async and allowing .func to be async function would make my life a bit easier ;)

**Comment by Lonami** [comment]
I have tried my best to avoid `async` from there because the task switches that occur from `await` by going back and forth into the event loop have a noticeable impact for some people (at least on CPU). If we support `async` there, then it will infect the events' `filter` and require `await` even if people don't need it.

Maybe we can wing it if we use a boolean flag to determine whether it's going to need await or not, because the check has to be done at call site.

**Comment by JuniorJPDJ** [comment]
You could check if it is async function or just function and then await it or just call ;)
https://docs.python.org/3/library/inspect.html#inspect.iscoroutinefunction

**Comment by Lonami** [comment]
Yes, that kind of check is done in a few places already. But since I don't think the client should be aware of that special maybe-async `func`, I think this kind of generic "maybe this entire event's filter is async" is a better idea.

**Comment by JuniorJPDJ** [comment]
I'd go for it :D

**Comment by JuniorJPDJ** [comment]
Is there any work about this?

**Comment by Lonami** [comment]
No, as far as I know.

**Comment by JuniorJPDJ** [comment]
Then is there a way of getting logged user instance in sync way?
I need my nickname in function passed to `func` arg in `NewMessage` event and don't want to leave huge workaround for this.

**Comment by Lonami** [comment]
…you could just `get_me` earlier in the program and use that with 0 network calls ever again. For more questions please use StackOverflow or [the group](https://t.me/TelethonChat).

**Comment by JuniorJPDJ** [comment]
I'm thinking about implementing this myself.
How would you workaround async need of `filter` on events when `func` is async?

**Comment by JuniorJPDJ** [comment]
As far as I see every `filter` function on `event` is supposed to return `None` or `event` but every check (2 actually) you are doing is casting this to boolean.
What if we return `func(event)` and in both places check if this is awaitable?
It will not make every event filter switch context.

**Comment by JuniorJPDJ** [comment]
I'm talking about something like this:
Idk if I should do pull request or not so I'm attaching patch.
```
diff --git a/telethon/client/updates.py b/telethon/client/updates.py
index 854860fd..67e30b71 100644
--- a/telethon/client/updates.py
+++ b/telethon/client/updates.py
@@ -424,7 +424,9 @@ class UpdateMethods:
             if not builder.resolved:
                 await builder.resolve(self)
 
-            if not builder.filter(event):
+            filter = builder.filter(event)
+            filter = await filter if inspect.isawaitable(filter) else filter
+            if not filter:
                 continue
 
             try:
diff --git a/telethon/events/common.py b/telethon/events/common.py
index 42586608..2531ea5d 100644
--- a/telethon/events/common.py
+++ b/telethon/events/common.py
@@ -121,9 +121,11 @@ class EventBuilder(abc.ABC):
                 # If it doesn't match but it's a whitelist ignore.
                 return None
 
-        if not self.func or self.func(event):
+        if not self.func:
             return event
 
+        return self.func(event)
+
 
 class EventCommon(ChatGetter, abc.ABC):
     """
diff --git a/telethon/tl/custom/conversation.py b/telethon/tl/custom/conversation.py
index c0d59e03..038768c7 100644
--- a/telethon/tl/custom/conversation.py
+++ b/telethon/tl/custom/conversation.py
@@ -312,7 +312,10 @@ class Conversation(ChatGetter):
         for key, (ev, fut) in list(self._custom.items()):
             ev_type = type(ev)
             inst = built[ev_type]
-            if inst and ev.filter(inst):
+
+            filter = ev.filter(inst)
+            filter = await filter if inspect.isawaitable(filter) else filter
+            if inst and filter:
                 fut.set_result(inst)
                 del self._custom[key]
```
Every another super call is returned, so everything will keep working (as far as I know).
