### ISSUE TITLE
connecting failed  to proxy

### ISSUE THREAD

**Issue by ElebrUS** [LonamiWebs/Telethon#1345]
**Checklist**
* The error is in the library's code, and not in my own.
*  I have searched for this issue before posting it and there isn't a duplicate.
* I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
**All Info**

I need to use the PySide2 library, that's why I returned to 3.7 and encountered this problem, but at 3.8 it is not
**Code that causes the issue**
```python
proxy = (socks.SOCKS5, str(host), port, plogin, ppass)
...

```

**Traceback**
```
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: GeneralProxyError: Socket error: 0x02: Connection not allowed by ruleset
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: GeneralProxyError: Socket error: 0x02: Connection not allowed by ruleset
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: GeneralProxyError: Socket error: 0x02: Connection not allowed by ruleset
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: GeneralProxyError: Socket error: 0x02: Connection not allowed by ruleset
WARNING:telethon.network.mtprotosender:Attempt 5 at connecting failed: GeneralProxyError: Socket error: 0x02: Connection not allowed by ruleset
WARNING:telethon.network.mtprotosender:Attempt 6 at connecting failed: GeneralProxyError: Socket error: 0x02: Connection not allowed by ruleset

```

**Comment by Lonami** [comment]
This is quite old, so I'm going to close it. The error seems to suggest that maybe the proxy only supports HTTP traffic, which Telethon does not use by default. If you have a proxy that can be used to reproduce this issue let me know and I may reopen it after we get more details.
