### ISSUE TITLE
Create new private channel

### ISSUE THREAD

**Issue by AlessandroSpallina** [LonamiWebs/Telethon#1347]
I can't found an easy way to create a new private channel and get the chat_id in return, can anyone say to me what to see?

**Comment by Lonami** [comment]
I guess a `create_group` and `create_channel` could be a good idea. For now, [search it in raw API](https://tl.telethon.dev?q=create).

**Comment by Lonami** [comment]
Raw API is good enough (they aren't complicated to use, and the raw API page has auto-generated examples).
