### ISSUE TITLE
Provide documentation for or access to errors.rpcerrorlist

### ISSUE THREAD

**Issue by jaharnum** [LonamiWebs/Telethon#1350]
It appears that rpcerrorlist.py is in the gitignore file for this library.

Would it be possible to either have the full list of errors / error messages in the documentation or to be able to see the contents of this file? 

I tried using the generic classes listed [here](https://docs.telethon.dev/en/latest/concepts/errors.html) and I also checked the [list here](https://docs.telethon.dev/en/latest/modules/errors.html) but this doesn't seem to capture things like rpcerrorlist.ChatAdminRequiredError or rpcerrorlist.ChannelInvalidError, so I have learned to handle them only by actually causing these errors. I would love to be able to see what other errors can be handled more gracefully from what else is available in that list!

Thanks very much!

**Comment by Lonami** [comment]
Only known errors are available in such list. Telegram may still send errors the library is unaware of (and then the corresponding superclass will be used).

The list of "what errors can occur for a request?" is, again, non-exhaustive and provided as a best-effort on a method-by-method basis in the [full API reference](https://tl.telethon.dev/).

I guess these notes (and the fact you should import them from `telethon.errors`, not `telethon.errors.rpcerrorlist`) could be added to the documentation page you linked.

**Comment by jaharnum** [comment]
> The list of "what errors can occur for a request?" is, again, non-exhaustive and provided as a best-effort on a method-by-method basis in the full API reference.

Oh, okay, perfect! I think that's really what I'm looking for, I just didn't realize that's where they were. Sometimes I forget that there are more specific requests underneath things like get_entity until errors start to crop up.

I can make some documentation edits over the weekend if that'd be helpful! I'll take a look through some of the other issues and see if there's anything else that comes up a lot that could be clarified as well.

**Comment by Lonami** [comment]
Any and all documentation improvements are welcome, if they make it easier to understand or provide more information. Having one of the best documentations out there (especially for beginners to read) is one of my goals, so I'm always open for improvements there.
