### ISSUE TITLE
Send button without reply_to message

### ISSUE THREAD

**Issue by akeinhell** [LonamiWebs/Telethon#1351]
methond click on the button, constantly making the reply to the message.

ex.: 
```
async with self.bot.client.conversation(runner.chat) as conv:
    await conv.send_message('/get_keyboard')
    msg_with_button = await conv.get_response()
    await msg_with_button.click(text='text_of_the_button')
```

expected behavior:
- client send only passed text 
```
# example 
client.send_message(button.text)
```

current behavior:
- client send message with reply 
https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/custom/messagebutton.py#L81

is there an option to customize the use of the method?

**Comment by Lonami** [comment]
Official clients don't seem to ever reply to a message when pressing a button, so I guess we shouldn't either. The user can always `client.send_message(chat, message.buttons[0][0].text)` with a explicit reply if they wish to do so anyway.
