### ISSUE TITLE
retrive posts dated to 

### ISSUE THREAD

**Issue by smolyakov26** [LonamiWebs/Telethon#1353]
how to get messages that posted today , it retrives all posts,  sorry for my english

```
date_of_post = datetime.datetime(2019, 12, 24)


with TelegramClient(name, api_id, api_hash) as client:
    for message in client.iter_messages(chat , offset_date = date_of_post):
        print(message.sender_id, ':', message.text)
```

**Comment by Lonami** [comment]
This issue is a "Question about Usage", which [as the template states](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md),:
> QUESTIONS DON'T BELONG HERE. Ask in [StackOverflow](https://stackoverflow.com) or in [@TelethonUpdates](https://t.me/TelethonUpdates)
