### ISSUE TITLE
Cant connect to client

### ISSUE THREAD

**Issue by GuyBuky** [LonamiWebs/Telethon#1357]
I try to connect to the telegram client like this:

**Code that causes the issue**
```python
    lclient = TelegramClient(phone, api_id, api_hash)
    lclient.connect()
    if not lclient.is_user_authorized():
        lclient.send_code_request(phone)
        lclient.sign_in(phone, input('Enter the code: '))
    return lclient

...

```

for some reason the connection just gets stuck. Not a timeout error or anything just staying on client.connect() for hours.
I tried to set a timeout for the execution time but all the solutions I've found are working with linux via ``` import signal```.

I saw that @Lonami fixed that problem when someone else posted the issue, but I still get that same bug in the updated telethon package.
What can I do?

**Comment by Lonami** [comment]
Is your country blocked by Telegram?

**Comment by GuyBuky** [comment]
> Is your country blocked by Telegram?

no it works fine with my other .session files. 
I should probably explain better - I have multiple .session files for each of my accounts,
most of them the connection is instant.
But some of them the connection just stays stuck. 

``
sim_cards = ['ARRAY OF SESSIONS']
for sim in sim_cards:
client.connect()
``

something like this.

**Comment by Lonami** [comment]
What does the `DEBUG` log say on the failing sessions?

**Comment by pwjGH** [comment]
Is it resolved? When my network is disconnected, the connection just gets stuck. After the network is restored, it cannot be executed normally.
this is my code:
 async for message in client.iter_messages(entity, min_id=minId, limit=100, wait_time=10):
            chat = message.chat
            user = message.sender

**Comment by Lonami** [comment]
Closing since this is quite old and not many people seem to have this issue (it seems it works fine if the network is okay to begin with).
