### ISSUE TITLE
Add support for TgCrypto

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1362]
[TgCrypto](https://github.com/pyrogram/tgcrypto) is faster than [CrypTg](https://github.com/cher-nov/cryptg) and if I guess right it can handle AES256-CTR encryption/decryption which is currently done with PyAES in Telethon

**Comment by Lonami** [comment]
Cryptography is hard to get right. How trustworthy is the library, really? Has the core really been implemented by hand, or was it taken from somewhere else? Has anyone audited it yet? It hasn't been around for as long as other implementations, either, which is one of the reasons why I am worried about using it.

**Comment by Soberia** [comment]
Sounds convincing

**Comment by Lonami** [comment]
Feel free to reopen if you find satisfactory answers to the questions, or better alternatives.
