### ISSUE TITLE
Not recieving an update from "events.MessageDeleted" when some item from an album gets removed

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1363]
[True] The error is in the library's code, and not in my own.
[True] I have searched for this issue before posting it and there isn't a duplicate.
[True] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

For example, if 3rd item (or any item except the last one) from an album with 6 items gets removed (from a channel), no event will occur from `events.MessageDeleted`

**Comment by Lonami** [comment]
Unfortunately, there isn't much we can do about this. Delete events aren't reliable (Telegram may not send them) and the library listens for updates in a passive way. That is, if the Telegram's server doesn't send us the update, Telethon won't even know it happened so it has no way to deliver the event to the user code. Not sure if some sort of more active checking (`getDifference`) would help in this case. Maybe. But that's another problem entirely.
