### ISSUE TITLE
Don't disconnect exported senders immediately

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1364]
There should be some sort of delay, such that if all senders were returned and a certain amount of time passed, *then* we can disconnect them. [The current implementation skips the time check](https://github.com/LonamiWebs/Telethon/blob/ccbc1c669c6351022676186c19b6953da1f702ad/telethon/client/telegrambaseclient.py#L651), which means that:
```python
async for m in client.iter_messages(chat):
    await m.download_media()
```

…may be constantly having to connect and disconnect a sender, while it would be better if the connection was kept for a while.

**Comment by Lonami** [comment]
This is even more important now, as it will allow for a rapid succession of requests to work just fine (as introduced by #1427), or otherwise bad things happen (as seen in https://github.com/LonamiWebs/Telethon/issues/1398#issuecomment-609107782).

**Comment by Lonami** [comment]
@Nukesor the above commit should address your issue in https://github.com/LonamiWebs/Telethon/issues/1398#issuecomment-609107782? If it doesn't, open a new issue.

**Comment by Nukesor** [comment]
Nice. Thanks!
That seems to have fixed the error messages. Bot still crashes hard on people spamming callback queries, though. I guess I'll investigate and create a ticket, if I find some time to debug this.
