### ISSUE TITLE
There is no current event loop in thread 'ThreadPoolExecutor-0_0'

### ISSUE THREAD

**Issue by Jahanzaeb** [LonamiWebs/Telethon#1365]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
when i create a telegram client then my code throws this exception:

**Code that causes the issue**
```
from telethon.sync import TelegramClient
TelegramClient('session_name', api_id, api_hash)
...
There is no current event loop in thread 'ThreadPoolExecutor-0_0'
```

**Comment by Lonami** [comment]
> * [x] The error is in the library's code, and not in my own.

It's not, so that box shouldn't be checked. You need to learn how to mix `asyncio` and `threading` if you really want to (you probably don't need to). This would be the same story with literally any other async library.

**Comment by Jahanzaeb** [comment]
Actually we are using it from last 7,8 months and we are using telethon 1.6 but now we are facing issue as we don't have much idea about asyncio and everytime its giving error message. Can you please help me out to solve this issue. It will be great for us.

Thanks Man

**Comment by Lonami** [comment]
No, this is not the place to help people with their own particular problems. This place is for bugs or feature requests of **the library itself**, not to ask how to use `asyncio`.

**Comment by Jahanzaeb** [comment]
Yess you are right man. But it should work 1st time without doing
anythingor without showing any error, its showing error message which i
don't undertsand.
I assumed it works finely after cloning.
