### ISSUE TITLE
can't get entity in chat

### ISSUE THREAD

**Issue by irfangerard44** [LonamiWebs/Telethon#1367]
I use this client.get_entity(PeerChat(int(Message['to_id']['chat_id']))) but it doesn't produce anything but when using peerchannel with ID channel or using peer user using user ID, it will get results

**Comment by Lonami** [comment]
```python
client.get_entity(types.PeerChat(original_integer_chat_id))
```

Works correctly, as intended.

**Comment by Lonami** [comment]
(Accidentally tested this in an older version, indeed it doesn't seem to work in the latest one).

**Comment by irfangerard44** [comment]
still can't get entity infochat

**Comment by Lonami** [comment]
The fix has not been released to PyPi. Did you test the changes on the `master` branch?

**Comment by irfangerard44** [comment]
ok i try, and when will be released to PyPi?

**Comment by irfangerard44** [comment]
i still get entity from peerchat, when i upgrade to 1.11.3, from git can i get solusion?

**Comment by irfangerard44** [comment]
@Lonami

**Comment by Lonami** [comment]
This has been closed for a while, and it's also been in PyPi for a while now.
