### ISSUE TITLE
to_id equals to from_id on NewMessage - 0.19.X

### ISSUE THREAD

**Issue by MAkcanca** [LonamiWebs/Telethon#1374]
**Checklist**
* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
...
client.add_event_handler(handler, event=NewMessage)
...

```
I'm stuck at Telethon 0.19.1.6 due to legacy code integration issues and difficulty due to making it work in Django.
When NewMessage event is triggered, on  **received message** message.to_id comes same as the message.from_id which makes no sense.
I didn't test it with Telethon 1.X, yet.
Is there something I need to use from the event, to get the from_id and to_id values correctly?

**Comment by Lonami** [comment]
I do not intend to maintain a separate v0.x series. Only the latest version will receive updates. Your options are:
* Fix this issue yourself. You can look at the current code and port that to the old version.
* Use an `asyncio`-based alternative to your other libraries using threads (`django` in your case).
* Learn how to use `asyncio` and `threading` together, and then use any libraries together.
* Use a threaded alternative to `telethon`.
