### ISSUE TITLE
Example Code：TypeError: A Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by shuiRong** [LonamiWebs/Telethon#1378]
![image](https://user-images.githubusercontent.com/16076993/73070972-99195680-3eec-11ea-921a-a9a1a0957338.png)

**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events, sync

# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.
api_id = xxxx
api_hash = 'xxx'

# The first parameter is the .session file name (absolute paths allowed)
with TelegramClient('anon', api_id, api_hash) as client:
    client.loop.run_until_complete(client.send_message('me', 'Hello, myself!'))
...

```

**Traceback**
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    client.loop.run_until_complete(client.send_message('me', 'Hello, myself!'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 367, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 554, in ensure_future
    raise TypeError('A Future, a coroutine or an awaitable is required')
TypeError: A Future, a coroutine or an awaitable is required
```

**Comment by Lonami** [comment]
You imported the `sync` hack, which already added `run_until_complete` behind the scenes. This is working as intended.

**Comment by Lonami** [comment]
If the docs are wrong, please indicate where and I will fix that.

**Comment by drdoof2019** [comment]
for those who will read in future, my code was starting with: 
`from telethon.sync import TelegramClient`
I got the error.
I deleted sync part and error vanished.
`from telethon import TelegramClient`
