### ISSUE TITLE
Regress: removed ping requests from update thread

### ISSUE THREAD

**Issue by sophiehatter** [LonamiWebs/Telethon#138]
Hi.

I found that removing Ping requests at commit https://github.com/LonamiWebs/Telethon/commit/4a2b6e7fa8122182b40d32fd1d53820d67fd92ad is not good idea. Because stable connection not equals reconnected connection. My tests shows that after several hours Telegram servers stops sending new updates. With patched library (I simply added deleted ping request to commit https://github.com/LonamiWebs/Telethon/commit/2b85463ce6438e07daf83c8febf685f9ffc3bb02) all works good like before removing in commit above. And I found that Telegram Desktop sends ping requests every few minutes too.

I have a bit doubt in this suggestions but ping is not really strange or bad thing. Some tests was failed by my internet provider and not all changes in commits was tested. But I thing that official clients send ping for a reason.

**Comment by Lonami** [comment]
Okay, I removed it because I made the updates thread non-mandatory, and thought it would be enough to trigger a reconnection once a request couldn't be send, or updates received. Since I don't quite use Telethon myself to work with updates, I didn't notice the mistake. I will add it back.

**Comment by sophiehatter** [comment]
But there is strange thing occurs two times...

`Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/telethon/telegram_client.py", line 808, in _updates_thread_method
    self.invoke(PingRequest(utils.generate_random_long()))
  File "/telethon/telegram_client.py", line 250, in invoke
    request, timeout=timeout, updates=updates)
  File "/telethon/telegram_bare_client.py", line 188, in invoke
    self.sender.send(request)
  File "/telethon/network/mtproto_sender.py", line 53, in send
    self._send_acknowledges()
  File "/telethon/network/mtproto_sender.py", line 71, in _send_acknowledges
    msgs_ack.on_send(writer)
  File "/telethon/tl/types/msgs_ack.py", line 33, in on_send
    writer.write_long(msg_ids_item)
  File "/telethon/extensions/binary_writer.py", line 37, in write_long
    value, length=8, byteorder='little', signed=signed))
OverflowError: int too big to convert`

I don't know why it's happens for now...

**Comment by Lonami** [comment]
Thanks for the report @sophiehatter.

**Comment by sophiehatter** [comment]
Commit https://github.com/LonamiWebs/Telethon/commit/a9a5c7e254f8a37582093e47fe3cc334de05b8b3 doesn't solve the problem. I'm doing some research for now...
