### ISSUE TITLE
ChatAction not detecting when user joins via invitation link a Supergroup/channel

### ISSUE THREAD

**Issue by alexmeri98** [LonamiWebs/Telethon#1381]
I've already posted this doubt in: [Stack Oveflow Post](https://stackoverflow.com/questions/60045482/telethon-chataction-event-not-detecting-when-user-joins-a-channel)
I'll be so thanksfull if you check it out.

**Comment by enjoyy2** [comment]
how did you fixed this ?

**Comment by alexmeri98** [comment]
"If Telegram doesn't send an update, Telethon won't be able to tell you the event happened, either. Normally, if you can't see something in a official client, you also can't in Telethon." Answered by [Lonami](https://stackoverflow.com/users/4759433/lonami)
