### ISSUE TITLE
Asks for phone number in vscode and is stuck

### ISSUE THREAD

**Issue by RajeshSivadasan** [LonamiWebs/Telethon#1383]
While trying to run basic code, it is asking for phone number or bot token and is stuck there.
![telethon](https://user-images.githubusercontent.com/36217458/73902732-b969ed80-48bc-11ea-80df-eef479998fb0.jpg)

**Comment by Lonami** [comment]
Enable `DEBUG` logging and paste here what it says. Also try, does it work outside of VSCode (in a normal terminal)?

**Comment by thelebster** [comment]
@RajeshSivadasan, I have created a new bot via [BotFather](https://t.me/BotFather) and got the bot token. Then, I'm able to start telegram client:

```
client = TelegramClient('redirect', TELEGRAM_API_ID, TELEGRAM_API_HASH, proxy=None)
await client.start(bot_token=TELEGRAM_BOT_TOKEN)
```

**Comment by Lonami** [comment]
Closing as not really actionable, Telethon is just using Python's [`input`](https://docs.python.org/3/library/functions.html#input) and [`getpass`](https://docs.python.org/3/library/getpass.html) if password is required. If those don't work use a normal terminal.
