### ISSUE TITLE
Documumentation Typos Report.

### ISSUE THREAD

**Issue by nitanmarcel** [LonamiWebs/Telethon#1388]
# Events Reference 
- https://docs.telethon.dev/en/latest/quick-references/events-reference.html#events-reference

**NewMessage**, **MessageEdited** and **MessageDeleted** has no attributes documented like the other events reference:

- https://docs.telethon.dev/en/latest/quick-references/events-reference.html#newmessage

- [ChatAction](https://docs.telethon.dev/en/latest/quick-references/events-reference.html#chataction)

`user`, `users`, have incomplete documentation strings. It stops after __(e.g.__ without any continuation

# Objects Reference
- https://docs.telethon.dev/en/latest/quick-references/objects-reference.html

[InlineResult](https://docs.telethon.dev/en/latest/quick-references/objects-reference.html#inlineresult)

The following types:

``ARTICLE 	
PHOTO 	
GIF 	
VIDEO 	
VIDEO_GIF 	
AUDIO 	
DOCUMENT 	
LOCATION 	
VENUE 	
CONTACT``

Are not documented. I don't know if this is intended but I will report them anyway.

# Not Documented:

- ``400: SCHEDULE_STATUS_PRIVATE`` (you can't schedule a message when someone comes online if their status is private).

**Comment by Lonami** [comment]
While we're fixing typos, it is worth adding `400: SCHEDULE_STATUS_PRIVATE` (you can't schedule a message when someone comes online if their status is private).

**Comment by nitanmarcel** [comment]
> While we're fixing typos, it is worth adding `400: SCHEDULE_STATUS_PRIVATE` (you can't schedule a message when someone comes online if their status is private).

That's a MTProto error no?

**Comment by Lonami** [comment]
I consider it to be documentation.

**Comment by nitanmarcel** [comment]
> I consider it to be documentation.

OK. I've added a not documented section :P

**Comment by Lonami** [comment]
To my knowledge, it is not possible to document the constants in `InlineResult`. I tried this:
```python
class InlineResult:
    """
    Custom class that encapsulates a bot inline result providing
    an abstraction to easily access some commonly needed features
    (such as clicking a result to select it).

    Attributes:

        result (:tl:`BotInlineResult`):
            The original :tl:`BotInlineResult` object.
    """
    ARTICLE = 'article'
    ARTICLE.__doc__ = 'Constant referring to the type of articles'
    PHOTO = 'photo'
    PHOTO.__doc__ = 'Constant referring to the type of photos'
    GIF = 'gif'
    GIF.__doc__ = 'Constant referring to the type of gifs'
    VIDEO = 'video'
    VIDEO.__doc__ = 'Constant referring to the type of videos'
    VIDEO_GIF = 'mpeg4_gif'
    VIDEO_GIF.__doc__ = 'Constant referring to the type of mpeg4_gis'
    AUDIO = 'audio'
    AUDIO.__doc__ = 'Constant referring to the type of audios'
    DOCUMENT = 'document'
    DOCUMENT.__doc__ = 'Constant referring to the type of documents'
    LOCATION = 'location'
    LOCATION.__doc__ = 'Constant referring to the type of locations'
    VENUE = 'venue'
    VENUE.__doc__ = 'Constant referring to the type of venues'
    CONTACT = 'contact'
    CONTACT.__doc__ = 'Constant referring to the type of contacts'
    GAME = 'game'
    GAME.__doc__ = 'Constant referring to the type of games'
```

…but it doesn't work. Maybe they should be read-only properties instead.

**Comment by Lonami** [comment]
Nevermind, seems a bit too hacky, I don't think it's worth the effort https://stackoverflow.com/a/7864317.

**Comment by Lonami** [comment]
> NewMessage, MessageEdited and MessageDeleted has no attributes documented like the other events reference

It is documented that they should be treated like a `Message`, though, so nothing to do there either.
