### ISSUE TITLE
New generation mtproto in Telethon 

### ISSUE THREAD

**Issue by amir124** [LonamiWebs/Telethon#1390]
Hi

Telethon  support 16 hex
The new Mtprpto is  32 hex or +60 hex
I want to use a new mtproto
But your code is error with new generation mtproto
What is your solution and suggestion for use?

**Comment by Lonami** [comment]
Tracked by #1319.

**Comment by amir124** [comment]
thank you 

but ,how to impelement links in my project ?

https://github.com/alexbers/mtprotoproxy/blob/199eaeb7c4e9c871b5c0b917fc82be1a0fa03b04/mtprotoproxy.py#L568-L623

https://github.com/alexbers/mtprotoproxy/blob/199eaeb7c4e9c871b5c0b917fc82be1a0fa03b04/mtprotoproxy.py#L1065-L1152

please guide me

**Comment by Lonami** [comment]
I don't know how MTProto proxies work, I simply merged a PR from someone who knew. You need to study or learn how they work, and then make the necessary changes to implement them (or port them from somewhere that supports them).

**Comment by amir124** [comment]
I'm using this code 

https://docs.telethon.dev/en/latest/basic/signing-in.html#using-mtproto-proxies


from telethon import TelegramClient, connection
client = TelegramClient(
    'anon', api_id, api_hash,
    connection=connection.ConnectionTcpMTProxyRandomizedIntermediate,
    proxy=('mtproxy.example.com', 2002, 'secret')
)
