### ISSUE TITLE
send_file doesn't work with videos

### ISSUE THREAD

**Issue by uzlov** [LonamiWebs/Telethon#1391]
send_file can send album of videos (files is the list of telethon.tl.types.MessageMediaDocument)
I have only the first video after the sending.
and send_file doesn't have a supporting of message for whole album

**Comment by Lonami** [comment]
Fixed in https://github.com/LonamiWebs/Telethon/commit/76cc076d6124972f9d0041f567f9769b05d5b9a5, not yet released.
