### ISSUE TITLE
iter_messages returns objects with corrupted MessageEntityUrl entries.

### ISSUE THREAD

**Issue by akamaus** [LonamiWebs/Telethon#1392]
**Checklist**
* [X ] The error is in the library's code, and not in my own.
* [X ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import telethon as T
tg = T.TelegramClient(**credentials)
await tg.start(**auth_data)

for m in tg.iter_messages('habmingazeta', offset_id=18979): 
    print(m.to_dict()) 
    break
```

Lets inspect some snippets from object returned (sorry, it's in russian, but we only need http url parts). 
```
In [13]: m.message[:500]                                                                                                                                                                              
Out[13]: 'О главном к этому часу:\n\n🔺Россия полностью остановит железнодорожное сообщение с Китаем с 3 февраля http://amp.gs/uyuV\n\n🔺В московских аптеках дефицит медицинских масок http://amp.gs/uyu9\n\n🔺Российские «скорые» переводят на аутсорсинг. Водители протестуют http://amp.gs/uyu4\n\n🔺В Томске у самолета Bombardier при посадке разрушилось шасси http://amp.gs/uyuR\n\n🔺ВЦИОМ: Самые популярные из поправок в Конституцию поддержали более 90 процентов россиян http://amp.gs/uyuU\n\n🔺Вернувшиеся с новогодних каникул к'

In [15]: m.entities[0].to_dict()                                                                                                                                                                                 
Out[15]: {'_': 'MessageEntityUrl', 'offset': 101, 'length': 18}

In [17]: m.entities[1].to_dict()                                                                                                                                                                                 
Out[17]: {'_': 'MessageEntityUrl', 'offset': 170, 'length': 18}

In [18]: m.message[101:101+18]                                                                                                                                                                                   
Out[18]: 'ttp://amp.gs/uyuV\n'

In [19]: m.message[170:170+18]                                                                                                                                                                                   
Out[19]: 'tp://amp.gs/uyu9\n\n'
```

You see, URL position is displaced and the displacement grows with each new entity.

**Comment by akamaus** [comment]
I also found other examples where different entities like `MessageEntityTextUrl` , `MessageEntityItalic` got displaced in a similar fashion. It happens when \U0001f53a (red html triangle 🔺) is present in message body.

**Comment by Lonami** [comment]
Working as intended. [`MessageEntity`](https://tl.telethon.dev/types/message_entity.html) offsets are counted with surrogates in the text, which are otherwise not present. The [`markdown`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/extensions/markdown.py) and [`html`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/extensions/html.py) parsers handle it correctly.

You may be looking for [`get_entities_text`](https://docs.telethon.dev/en/latest/modules/custom.html#telethon.tl.custom.message.Message.get_entities_text).
