### ISSUE TITLE
Update ideas for pin_message()

### ISSUE THREAD

**Issue by thekillgfx** [LonamiWebs/Telethon#1394]
Here are two ideas to change the way [pin_message](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.messages.MessageMethods.pin_message) method works.

1) `pin_message` should return the same as [UpdatePinnedMessageRequest](https://tl.telethon.dev/methods/messages/update_pinned_message.html) does instead of `None`.

2) I would also recommend to add an argument to `pin_message`, something that let the user choose between deleting the `message service` or not; it could be deleted without asking imo since I find it so annoying, but maybe someone likes/needs it. 
Using `UpdatePinnedMessageRequest` I discovered that: 
```
result = await client(functions.messages.UpdatePinnedMessageRequest(
  peer=chat,
  id=message.id,
  silent=True
))
service_message = result.updates[2].message
```

I hope I've provided all the infos needed let me know if you need some clarification.

**Comment by Lonami** [comment]
> something that let the user choose between deleting the message service or not

This feels a bit niche; users may use the return value (which in my opinion should be just the action message it triggers) as they wish (e.g. delete it).
