### ISSUE TITLE
Add 2 factor auth

### ISSUE THREAD

**Issue by k1-hedayati** [LonamiWebs/Telethon#14]
I have enabled 2 factor auth in my telegram and when I tried to login I got this:
`RPCError: (RPCError(...), 'Unknown error message with code 401: SESSION_PASSWORD_NEEDED')`

**Comment by XyLoNaMiyX** [comment]
This should have been fixed as discussed on #4? What version are you using?

**Comment by k1-hedayati** [comment]
I see, I'm using the pip version, looking forward for fixing the bug and uploading it :)

**Comment by XyLoNaMiyX** [comment]
> looking forward for fixing the bug

I'm waiting for him to reply, and I don't know when this will happen. Also, he only introduced style changes… So nothing should have been broken. It's weird and I can only test it with myself. Would you will to help out and test?

**Comment by k1-hedayati** [comment]
How should I test it?

**Comment by XyLoNaMiyX** [comment]
> How should I test it?

Same way I told him:

> "Invalid DH Inner Data code" and I get random numbers. No matter how many times I try, it never works. And yet, on your previous commit ([`ef264ae`](https://github.com/LonamiWebs/Telethon/commit/ef264ae83fdef821b1911f227175e372bf01f2b8)) everything seems to work just fine, which is strange because you only introduced coding styles changes, correct?
>
> Could you please try checking out both this and the commit I just mentioned and logging in (make sure you delete the `.session` file and/or log out with `!l`)?

So, [`ef264ae`](https://github.com/LonamiWebs/Telethon/commit/ef264ae83fdef821b1911f227175e372bf01f2b8) seems to work and [`d08794`](https://github.com/LonamiWebs/Telethon/commit/d087941bd06e47e3392937bdad901b0e63d05a4d) seems not to. Try `git checkout` both and login/logout. First should work, second seems broken. Thanks in advance.

**Comment by k1-hedayati** [comment]
Please check my comment on that commit

**Comment by k1-hedayati** [comment]
Fixed by 8e48455cdc5857c48669c201c1ed6e2be61f5a24

**Comment by XyLoNaMiyX** [comment]
I'll close this now. Again, thank you! I totally missed _that single line_ 😅
