### ISSUE TITLE
After 30 minutes no updates

### ISSUE THREAD

**Issue by kanphis** [LonamiWebs/Telethon#140]
After 30 minutes connection is still active, but update handler doesnt' trigger. And it hangs in this way untill I force restart the connection.

**Comment by StrangePers** [comment]
Yep, the same thing happens to me, but randomly in 2 hours or in 1 day. Failed to figure out what causes hanging of update handler. Guess we should add some debug output and test

**Comment by Lonami** [comment]
Are you using `pip` or upstream? Because upstream has the periodic pings again (see #138) whereas `pip` doesn't, if I recall correctly.

**Comment by StrangePers** [comment]
Guess I should try the latest version from git... :D

**Comment by Lonami** [comment]
> Guess I should try the latest version from git... :D

Please do so. If it works I'll update `pip` because it's important.

**Comment by kanphis** [comment]
> Please do so. If it works I'll update pip because it's important
Tried latest version. Script was running all day long without any problems. Thanks!

**Comment by StrangePers** [comment]
Yep. Tried latest version and script is still running. Great 👍
