### ISSUE TITLE
send_file method ignore thumbnail if file has been previously uploaded

### ISSUE THREAD

**Issue by kfur** [LonamiWebs/Telethon#1404]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
file = client.upload_file(file_path)
client.send_file(file, thumb=thumb_path)
```

I think bug is located here https://github.com/LonamiWebs/Telethon/blob/68438f462127fa02021f40a0e2d686072978a264/telethon/client/uploads.py#L642
if this condition true then thumbnail will be ignored

**Comment by Lonami** [comment]
The code you posted doesn't work, you never specify which chat to send the file to:
```
TypeError: send_file() missing 1 required positional argument: 'file'
```

Worth mentioning that `file_path` must not point to a photo either, or those won't have a thumbnail. With that fixed though, I can confirm it fails because of that. Think the best solution is some restructuring.

**Comment by kfur** [comment]
@Lonami this was a like pseudocode
i tried upload video before sending it and  every time it trigger this https://github.com/LonamiWebs/Telethon/blob/68438f462127fa02021f40a0e2d686072978a264/telethon/client/uploads.py#L642
and thumbnail ignored due to thumb handled after this condition

**Comment by kfur** [comment]
Thumbnail handled here https://github.com/LonamiWebs/Telethon/blob/68438f462127fa02021f40a0e2d686072978a264/telethon/client/uploads.py#L703
while there is return statement before it i mean

**Comment by kfur** [comment]
Thanks for fix!
