### ISSUE TITLE
using TDlib vs MTProto

### ISSUE THREAD

**Issue by aminraisy** [LonamiWebs/Telethon#1407]
@Lonami I read the wiki [advantages of MTProto over HTTP-Bot_API](https://github.com/LonamiWebs/Telethon/wiki/MTProto-vs-HTTP-Bot-API) 
would you please have a comparison between MTProto libraries vs TDLib libraries (for example [airgram](https://github.com/airgram/airgram/)). any advantages using MTproto over TDLib ?

**Comment by Lonami** [comment]
Well, I don't have experience with `tdlib` myself, but it is on its own a MTProto library like `telethon` is. Just different owners, implementations and languages. Also, anyone can edit the wiki.

**Comment by Lonami** [comment]
Closing because the Wiki is supposed to be community-maintained and we already have [HTTP Bot API vs MTProto](https://docs.telethon.dev/en/latest/concepts/botapi-vs-mtproto.html) in the docs with more info.
