### ISSUE TITLE
Fast accounts ban

### ISSUE THREAD

**Issue by kallibr44** [LonamiWebs/Telethon#1409]
api_id = 1336220  # API ID  (banned credential)
api_hash = "b6bc04d81b9503415b3175ad34cda94a"  # API Hash (banned credential)
phone_number = "+79123123123" 
client = TelegramClient('qqqq', api_id, api_hash, connection=connection.ConnectionTcpMTProxyRandomizedIntermediate, proxy=('proxy.digitalresistance.dog', 443, 'd41d8cd98f00b204e9800998ecf8427e'))

client.start()

async def main():
    dp =await client.get_dialogs()
    print(dp)

if __name__ == '__main__':
    with client:
        client.loop.run_until_complete(main())

i'm ran this code and after this 1 request i got ban on my acount. Also, i got ban on 5 more accs with this code. Do you know how to solve this problem?

**Comment by Lonami** [comment]
#824
