### ISSUE TITLE
Conversation.cancel_all() and Conversation.cancel() seems not to be working 

### ISSUE THREAD

**Issue by thekillgfx** [LonamiWebs/Telethon#1411]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import asyncio
from telethon import functions, types
from telethon import TelegramClient, events

import logging
logging.basicConfig(level=logging.WARNING)

client = None

def start_session():
    global client
    client = TelegramClient('session_name', 'api_id', 'api_hash')
    client.start()

async def main():
    user = await client.get_input_entity('yourtag')
    try:
        async with client.conversation(user) as conv:  
            await conv.send_message('conversation started')
            await client.conversation(user).cancel_all() #tried also with conv.cancel()
            await conv.send_message('why am I working?')            
    except asyncio.TimeoutError:
        html = '🗣 conversation timed out'
        await client.send_message(user, html, parse_mode='html')
    except asyncio.CancelledError:
        html = '🗣 conversation has been cancelled'
        await client.send_message(user, html, parse_mode='html')

start_session()
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Traceback**
There isn't any traceback or error, but ```await conv.send_message('why am I working?')``` should raise error and it doesn't, or at least it shouldn't send the message since the ```Conversation``` has been cancelled.

**Comment by Lonami** [comment]
`send_message` doesn't check if it was cancelled but methods like `get_response` do. It is cancelled, it's just not checked there. This is a bug.
