### ISSUE TITLE
ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f972ec6e400>. 

### ISSUE THREAD

**Issue by Shhishsh** [LonamiWebs/Telethon#1412]
This is my Code: 
``` try:
	client(ImportChatInviteRequest(gruppoF))
except Exception:
	print("Gia' ci sono")
chatinvite=client(CheckChatInviteRequest(gruppoF))
gruppoF=chatinvite.chat.id
result=client(GetParticipantsRequest(channel=gruppoF,filter=types.ChannelParticipantsRecent(),offset=42,limit=20000,hash=0))```

The error:
ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f972ec6e400>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

**Comment by thekillgfx** [comment]
The error show you a link, did you check it?

**Comment by Shhishsh** [comment]
The link is god

**Comment by Shhishsh** [comment]
The problem is with new private groups/channel (i think) because in an other group  it can

**Comment by thekillgfx** [comment]
If you check the link you'll see that the problem is that the library(Telethon) never seen that group before, so you have to let the library "discover" it. Go check the link another time then check out [get_entity](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.users.UserMethods.get_entity) and [get_input_entity](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.users.UserMethods.get_input_entity)

**Comment by Shhishsh** [comment]
No, i have tried with other private groups that i never seen and works. But with new groups i create it don't work

**Comment by Shhishsh** [comment]
Update: the user manages to join the group but still gives this error...

**Comment by Lonami** [comment]
Not much we can do here, if Telegram doesn't send the entity Telethon can't use it. Maybe `get_participants` in the group.

**Comment by RamiMohammedSeid** [comment]
@Lonami I have encountered the same problem. On new entities you have to try again. which means it returns from cache.

**Comment by G-shaft** [comment]
I encountered a similar problem when running client.get_entity(PeerUser(int(user_id))).
But if I execute client.get_participants('username') and then get_entity - everything is fine. But this can only work if the user has @username set. What if they don't?

**Comment by ljs19923** [comment]
Did you find a solution?

**Comment by Lucifer-00007** [comment]
**I got the solution!** 

Doc: https://docs.telethon.dev/en/stable/concepts/entities.html 

It is mentioned in the doc to use **async  await** and **PeerUser/PeerChat/PeerChannel** 


```
from telethon.tl.types import PeerUser, PeerChat, PeerChannel

my_user    = await client.get_entity(PeerUser(some_id))
my_chat    = await client.get_entity(PeerChat(some_id))
my_channel = await client.get_entity(PeerChannel(some_id))
```

I hope it helped!
@allerter

**Comment by serhii-hrekov** [comment]
According to the docs - get group data where the user is a participant. Then retrieve User entity.

**Comment by soumanjyotiofficial** [comment]
Even I am getting the same error how to solve this error

**Comment by HYwangk** [comment]
no one can solve this problem?
