### ISSUE TITLE
connect failed

### ISSUE THREAD

**Issue by leetomlee123** [LonamiWebs/Telethon#1414]
DEBUG:asyncio:Using proactor: IocpProactor
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
WARNING:telethon.network.mtprotosender:Connection error 1 during auth_key gen: ConnectionError: Not connected
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 2...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
WARNING:telethon.network.mtprotosender:Connection error 2 during auth_key gen: ConnectionError: Not connected
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
DEBUG:telethon.network.mtprotosender:Connection attempt 3...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 3...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
WARNING:telethon.network.mtprotosender:Connection error 3 during auth_key gen: ConnectionError: Not connected
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
DEBUG:telethon.network.mtprotosender:Connection attempt 4...
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: ConnectionResetError: Connection lost
DEBUG:telethon.network.mtprotosender:Connection attempt 5...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 5...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
WARNING:telethon.network.mtprotosender:Connection error 5 during auth_key gen: ConnectionError: Not connected
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
DEBUG:telethon.network.mtprotosender:Connection attempt 6...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 6...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
WARNING:telethon.network.mtprotosender:Connection error 6 during auth_key gen: ConnectionError: Not connected
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 64] 指定的网络名不再可用。
Traceback (most recent call last):
  File "C:/Users/lxv1/Desktop/source/hub/telegram.py", line 106, in <module>
    client.start()
  File "C:\Users\lxv1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\auth.py", line 132, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\lxv1\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "C:\Users\lxv1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\auth.py", line 139, in _start
    await self.connect()
  File "C:\Users\lxv1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\telegrambaseclient.py", line 439, in connect
    if not await self._sender.connect(self._connection(
  File "C:\Users\lxv1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\network\mtprotosender.py", line 125, in connect
    await self._connect()
  File "C:\Users\lxv1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\network\mtprotosender.py", line 250, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by leetomlee123** [comment]
emergency report

**Comment by Touka-ch** [comment]
你好，请问解决了吗
