### ISSUE TITLE
CheckChatInviteRequest with get_input_peer

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#142]
Could be used get_input_peer with [CheckChatInviteRequest](https://lonamiwebs.github.io/Telethon/methods/messages/check_chat_invite.html)?

**Comment by Lonami** [comment]
> Could be used get_input_peer

No? I think you have to pass the hash of the invitation…

**Comment by seby2000** [comment]
i know but can i get th InputPeer  with get_input_peer ? if the result is ChatInviteAlready?

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/wiki/Joining-a-chat-or-channel#joining-a-private-chat-or-channel
