### ISSUE TITLE
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID

### ISSUE THREAD

**Issue by BlackMambaaaa** [LonamiWebs/Telethon#1429]
I have a bot that relays messages from 2 telegram chats to my Botfather bot. Bot starts and runs fine but after few mins of being idle it throughs following error.

I am on Python3.7 , Telethon version 0.19.6
I have tried upgrading to latest Telethon but then it does not even starts and gives me workers update error.  I have also tried fix provided in #69 but still have same issue.

```
File "start_forward.py", line 38, in <module>
    client.idle()
  File "/usr/local/lib/python3.7/dist-packages/telethon/telegram_bare_client.py", line 696, in idle
    self._sender.receive(update_state=self.updates)
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtproto_sender.py", line 180, in receive
    self._process_msg(remote_msg_id, remote_seq, reader, update_state)
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtproto_sender.py", line 234, in _process_msg
    return self._handle_container(msg_id, sequence, reader, state)
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtproto_sender.py", line 392, in _handle_container
    if not self._process_msg(inner_msg_id, sequence, reader, state):
  File "/usr/local/lib/python3.7/dist-packages/telethon/network/mtproto_sender.py", line 247, in _process_msg
    obj = reader.tgread_object()
  File "/usr/local/lib/python3.7/dist-packages/telethon/extensions/binary_reader.py", line 143, in tgread_object
    return clazz.from_reader(self)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/types/__init__.py", line 20530, in from_reader
    _x = reader.tgread_object()
  File "/usr/local/lib/python3.7/dist-packages/telethon/extensions/binary_reader.py", line 143, in tgread_object
    return clazz.from_reader(self)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/types/__init__.py", line 19149, in from_reader
    _message = reader.tgread_object()
  File "/usr/local/lib/python3.7/dist-packages/telethon/extensions/binary_reader.py", line 143, in tgread_object
    return clazz.from_reader(self)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/types/__init__.py", line 10676, in from_reader
    _media = reader.tgread_object()
  File "/usr/local/lib/python3.7/dist-packages/telethon/extensions/binary_reader.py", line 141, in tgread_object
    raise TypeNotFoundError(constructor_id)
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 0x7c4414d3. Most likely, a TLObject was trying to be read when it should not be read.

```

**Comment by Lonami** [comment]
> Telethon version 0.19.6

Only the latest version is supported.

**Comment by ArtemBernatskyy** [comment]
I could confirm this on latest version https://sentry.io/share/issue/c9c782cafdd84549af603b86bb3b43c4/ , it seems that we need to reopen this thread

**Comment by ArtemBernatskyy** [comment]
PS I'm running telthon via `.iter_messages(chat, reverse=True, offset_id=0)`

**Comment by Lonami** [comment]
Cannot reproduce. Please update to `master` again and, if the issue persists, it would really help to have access to the faulty message.

**Comment by ArtemBernatskyy** [comment]
@lonami, how can I stop at the faulty message (in order to capture it)? Because it seems that `.iter_messages(chat, reverse=True, offset_id=0)` won't fail but my sentry somehow captures the error...

**Comment by Lonami** [comment]
Make sure your "sentry" is also using the latest version. I guess a reasonable approach is to print the message ID for as long as possible, stop on error, and we know the faulty is within 100 messages before the last printed ID. But again this should be fixed in the latest version.

**Comment by ArtemBernatskyy** [comment]
yeah, but here is a catch,
I can't stop on error, because there is no error,
I mean - yes, sentry reports a "warning" but my script isn't failing (I'm not using error handlers `try`, `except`), that why I'm telling you that it's hard to stop on faulty message

here is my code

```python
chat = self.tg_client.get_input_entity(chat_id)
dump_500_messages = []
progress = 0
every_500 = 0
for message in self.tg_client.iter_messages(chat, reverse=True, offset_id=our_latest_message):
    message_obj = MessageIndex(
        message_id=int(message.id),
        post=message.post,
        chat=chat_id,
        from_id=get_from(message)[0],
        from_type=get_from(message)[1],
        date=message.date,
        peer_id=get_peer(message)[0],
        peer_type=get_peer(message)[1],
        via_bot_id=message.via_bot_id,
        message=message.message,
    )
    dump_500_messages.append(message_obj)
    try:
        if every_500 == 500:
            progress += 500
            every_500 = 0
            print(f"parsing {progress}")
            streaming_bulk(
                client=self.es_client,
                actions=[i.save() for i in dump_500_messages],
                max_retries=3,
                yield_ok=False,
            )
            dump_500_messages = []
        every_500 += 1
    except Exception as e:
        self._send_report(f"🏴‍☠️ error: {e} in updating {chat_id} chat 🏴‍☠️")
```

so in my case `_send_report ` never reported any error, it's just that sentry "somehow" captured error which happened in "telethon",
PS yes, I'm also confused by this situation a little bit

**Comment by Lonami** [comment]
Sounds like something's wrong with sentry's configuration, maybe using an old version of the library.

**Comment by ArtemBernatskyy** [comment]
Nope, we can see here https://sentry.io/share/issue/c9c782cafdd84549af603b86bb3b43c4/ that sentry is `0.19.5` which is the [latest version on pypi](https://pypi.org/project/sentry-sdk/)

**Comment by ArtemBernatskyy** [comment]
ah, my bad, so it's not an error but a logging
![image](https://user-images.githubusercontent.com/13070119/107631857-5698f800-6c6e-11eb-807b-2e28ff20c4a8.png)

but then the following question arises, does it affect my program or should I just ignore it?

**Comment by Lonami** [comment]
It affects the program. The request will never get a response so it "deadlocks".

**Comment by Lonami** [comment]
Note that the linked commit, even if fixed, won't solve this. This error is different. However the error is now correctly propagated (although it's still "just logged" if it happens in an update handler, because otherwise it would crash).

In any case, `f0e6672a` corresponds to `ChannelFull` of layer 117, as seen in https://github.com/LonamiWebs/Telethon/commit/daec282cdfe1683b57400152894007b28cb41dff. I have no idea why Telegram is sending such old objects, it sometimes does this, and restarting the application should help. If it doesn't, try to login again.

**Comment by ArtemBernatskyy** [comment]
Gotcha, thx.
I was downloading very old chats from the beginning, maybe it is related to that.
