### ISSUE TITLE
SearchResult returning partial items

### ISSUE THREAD

**Issue by Azorius291** [LonamiWebs/Telethon#1431]
Hi, I'm trying to search public channels in the global search that contain a certain keyword, when I try it with 

```
results = client(functions.contacts.SearchRequest(
        q=keyword,
        limit=100
))
```

It returns only the first 3 results that I can see in the telegram app too, but doesn't return the full search that I can see by pressing "show more" in the telegram app

**Comment by Lonami** [comment]
You're using raw API, which means what you get is what Telegram responds. There is nothing Telethon can do to help here. Maybe the debug logs in the application print what request is made, and then you can use that.

**Comment by MajidOmidali** [comment]
I ate the same problem, no one found a solution?
