### ISSUE TITLE
Docs not clear about InviteToChannelRequest

### ISSUE THREAD

**Issue by itajackass** [LonamiWebs/Telethon#1434]
Hi i'm not sure is a docs no clear or other problem. 

Btw i've a channel that sponsorize my website. 

I've already some members who joined to my channel from link on my website, about 150 users. 

Now i want to add all my contacts friends on my mobile phone to my channel. 

I have all username of my friends. 

Now i tried to use function InviteToChannelRequest in a loop. Every 60 seconds I add a friend.

I have about 80 friends to add. 

The problem is when i reached 200 members ti my channel, function stop working and give to me error UserToMuchError..... 

But from docs I understand i can add 200 user from my account, i 've to add only 80 friend but it stop after 50 users. 

Docs unclear or I wrong something?

**Comment by Lonami** [comment]
Said requests is raw API and what Telegram answers is what it is. Nothing to do here. Said request is also used for spam, and will get the group and account banned, perhaps deleted, so I won't be updating the docs to avoid helping spammers.

**Comment by vinsrepo** [comment]
>>>The problem is when i reached 200 members ti my channel, function stop working and give to me error UserToMuchError.....

The real problem is that you did not read the document carefully. It said you can only **add first 200 members** to your channel. At your time you added, your channel already had 150 users, so it's why you can only added more 50 users manually.
