### ISSUE TITLE
Failed to convert p to media. Not an existing file, an HTTP URL or a valid bot-API-like file ID

### ISSUE THREAD

**Issue by pakesusu** [LonamiWebs/Telethon#1437]
**Checklist**
* [Y] The error is in the library's code, and not in my own.
* [Y] I have searched for this issue before posting it and there isn't a duplicate.
* [Y] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

await client.send_message(username, file=get_pdf, reply_to=event.message.id)
...

```

**Traceback**
```
ERROR:telethon.client.updates:Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 428, in _dispatch_update
    await callback(event)
  File "deliver.py", line 386, in handler
    await client.send_message(username, file=parser[0], reply_to=event.message.id)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/messages.py", line 694, in send_message
    buttons=buttons
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 332, in send_file
    supports_streaming=supports_streaming
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/uploads.py", line 652, in _file_to_media
    'an HTTP URL or a valid bot-API-like file ID'.format(file)
ValueError: Failed to convert p to media. Not an existing file, an HTTP URL or a valid bot-API-like file ID


```

Hi,

so i create an async method that handle one command, its for scrapping website, and wkhtmltopdf.

so the method after parsing, create local pdf file and send file local <name>.pdf in one process, i make flooding request to simulate condition when nearly same time requests, because user might request more than one (in example: group).

firstly ill send command :

file google.com

then i flood requests with:

file wikipedia.org
file youtube.com
file facebook.com

while the file googlecom.pdf is processing, then async will process file wikipediaorg.pdf file youtubecom.pdf ....

because of flooding, telethon will only send file googlecom.pdf to user, file wikipediaorg.pdf and file youtubecom.pdf ... will not send, and telethon will give SINGLE traceback as above.

any clue? 

the all files is exists, because converting to pdf process is success, and i make sure there is all files above in my local folder..

or telethon not allowed send file concurrently?

**Comment by Lonami** [comment]
What is `get_pdf`?

**Comment by pakesusu** [comment]
> What is `get_pdf`?

file_path to local file,

but i think i found the issue.

i add logic where 2 client.send_message is called in one async.

first client.send_message is for notifying "webpage is processing"
and second client.send_message is for sending pdf file when complete.

i dont know why this happens, but i rather to delete first client.send_message and the problem is gone.
