### ISSUE TITLE
MTproxy TLS Support?

### ISSUE THREAD

**Issue by Drparsayar** [LonamiWebs/Telethon#1438]
Hi there, i was wondering if you were planning to add support for the new version of MTProto proxies (TLS),

will we have the support for the new version of MTProto Proxies in your library in the near future?

**Comment by Lonami** [comment]
I was not planning on doing any work related to MTProto Proxies myself, but I will gladle merge a [Pull Request](https://github.com/LonamiWebs/Telethon/pulls) that adds them.

**Comment by Drparsayar** [comment]
Thanks that would be awesome.

**Comment by Lonami** [comment]
Closing in favour of #1319 which I forgot exists and tracks this same thing.

**Comment by Lonami** [comment]
Closing in favour of #1319 which I forgot exists and tracks this same thing.
