### ISSUE TITLE
InteractiveTelegramClient crashes with __main__.InteractiveTelegramClient object at 0x000001D842D29240

### ISSUE THREAD

**Issue by pr0fess0r** [LonamiWebs/Telethon#144]
Hi Guys

I'm trying to run the interactive client and it crashes after authentication. I've tested Telethon during setup following the instructions on GitHub and it worked fine, but trying to run the interactive client I'm getting this:

==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
<__main__.InteractiveTelegramClient object at 0x000001D842D29240>

I'm loading the file into IDLE (and Spyder3) and calling InteractiveTelegramClient('tele_session', '+xxx',api_id=yyy, api_hash='zzz') with the appropriate values. Am I doing this wrong?

Cheers

**Comment by Lonami** [comment]
Well… I see no information at all about the crash or error itself so there is not much I can do.
