### ISSUE TITLE
Chat action 'song' is alias for 'document' and not for 'audio'

### ISSUE THREAD

**Issue by TishSerg** [LonamiWebs/Telethon#1443]
**Code that causes the issue**
```python
async with client.action(input_chat, 'audio'):
            print('audio')
            await asyncio.sleep(2)
async with client.action(input_chat, 'song'):
            print('song')
            await asyncio.sleep(2)
async with client.action(input_chat, 'document'):
            print('document')
            await asyncio.sleep(2)
```
When 'song' is printed all the Telegram clients I checked (Windows Telegram Desktop, Android Telegram and Telegram X) show that document is being sent (not 'audio').

**Comment by Lonami** [comment]
Yeah that seems to be wrong here:
https://github.com/LonamiWebs/Telethon/blob/c487340f8ecc4f47c36bfcf36ef2b2eb10325e78/telethon/client/chats.py#L39

Feel free to send a PR.
