### ISSUE TITLE
InviteToChannelRequest doesn't returns any error but neither add user to a group

### ISSUE THREAD

**Issue by alyatrach** [LonamiWebs/Telethon#1451]
`result = client(InviteToChannelRequest(target_group_entity,[user_to_add]))
            print(result)
except UserChannelsTooMuchError:
            print("Getting User Channels Too Much Error. Skipping")
            continue
`
For some users (not all) InviteToChannelRequest behaves like it have added a user to a group and no exception is caught, but when i am checking the group manually, the user is not there. Also, when i'm trying to add that user manually to a group, i got error message from telegram says "sorry but the user is already in too many channels, ask them to leave some first"

**Comment by Lonami** [comment]
Not a bug in the library, don't forget using that request may be seen as spam and get your account and group banned or deleted.
