### ISSUE TITLE
Getting ValueError: non-hexadecimal number found in fromhex() for Mtproto secret

### ISSUE THREAD

**Issue by hamedhr** [LonamiWebs/Telethon#1454]
Hi 

I'm trying to connect with MtProto which causes the Exception :

`
 self._secret = bytes.fromhex(proxy[2])
ValueError: non-hexadecimal number found in fromhex() arg at position 1
`

example link for MtProto : 

`
https://t.me/proxy?server=&port=443&secret=7jK5IN_7UWQwKOL2uHjU6sFpbnN0YWdyYW1zdGF0aWMtYS5ha2FtYWloZC5uZXQ
`
`
from telethon.sync import TelegramClient, events, connection

api_id = 12345
api_hash = "1234567890"

secret="7jK5IN_7UWQwKOL2uHjU6sFpbnN0YWdyYW1zdGF0aWMtYS5ha2FtYWloZC5uZXQ"
proxy = ("snitched.DigiArray.xyz", 443, secret)
connection = connection.tcpmtproxy.ConnectionTcpMTProxyRandomizedIntermediate

with TelegramClient("anon", api_id, api_hash,
                    connection=connection,
                    proxy=proxy,
                    connection_retries=1) as client:
    client.send_message("me", "Hi")
`

**Comment by Lonami** [comment]
Closing in favour of #1319.
