### ISSUE TITLE
Inconsistency between edit_message and send_message

### ISSUE THREAD

**Issue by penn5** [LonamiWebs/Telethon#1456]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
try:
    await client.send_message("TelethonChat", "")
except ValueError:
    # Could mean 'message empty' or 'unknown entity'
msg = await client.send_message("TelethonChat", ".")
try:
    await client.edit_message(msg.to_id, msg.id, "")
except MessageEmptyError:
    # message is empty
```
I would propose that send_message throws MessageEmptyError before making the RPC request. This way, the errors can be differentiated against a ValueError from an unknown entity, and makes it consistent with edit_message. It also means that it's not necessary to make an RPC request to get the error returned from the server, so it can be detected faster.

**Comment by Lonami** [comment]
I am generally against manually building RPC errors, because it's a lot easier to reason about it if you're guaranteed that they can only happen because Telegram responded with one.

**Comment by Lonami** [comment]
Closing as per above reasoning, could be revisited in #1169.
