### ISSUE TITLE
Forwarding file without forward header

### ISSUE THREAD

**Issue by xybydy** [LonamiWebs/Telethon#1462]
In docs it is written that the way to forward messages without the forward header is simply using send_message function but it only works for text messages.

Is there any way that we can forward files without the headers? Pyrogram can do that (but unable to search files by its name, pyrogram requires file caption), and the libs based on tdlib does that as well but I couldn't find any way to do that on Telethon.

**Comment by Lonami** [comment]
I am pretty sure it works for files too.

**Comment by Lonami** [comment]
If you find a way to reproduce this issue, please say how and reopen the issue, but otherwise sending messages with files works just fine.

**Comment by xybydy** [comment]
Sending local files is OK. How about forwarding the files without the header message?

**Comment by Lonami** [comment]
That's what I tested, and that works fine.
```python
with client:
    m = client.get_messages(client.get_dialogs(1)[0])[0]
    m.respond(m)
```

**Comment by RaminMammadzada** [comment]
Forwards the given messages to the specified entity.

If you want to “forward” a message without the forward header (the “forwarded from” text), you should use `send_message` with the original message instead. This will send a copy of it.

Ref: https://docs.telethon.dev/en/latest/modules/client.html
