### ISSUE TITLE
Bug in SendChangePhoneCodeRequest?

### ISSUE THREAD

**Issue by NotStatilko** [LonamiWebs/Telethon#1464]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

Hello!  I developed [backups for Telegram](https://bit.ly/tgback) based on Telethon. Recently, I noticed that my sessions were disconnected, although they were active for ~6 months. Also, when I started to rewrite my code, I noticed that the `SendChangePhoneCodeRequest`  began to return an **[undocumented](https://tl.telethon.dev/methods/account/send_change_phone_code.html) [error](https://pastebin.com/snR3tXby)**, although before that everything worked fine.  Can you tell me what happened, and how can this be fixed?

To raise error you can clone [my repository](bit.ly/tgback), change to `except OSError:` in [this line](https://github.com/NotStatilko/tgback/blob/c65a903acd5ffa33ac419193665ec0bde19ce707/TelegramBackup.py#L124), run `TelegramBackup.py`, [backup account and try to change phone](https://github.com/NotStatilko/tgback/blob/master/README.md), you can input your active phone number.

Short Error:
```
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: FRESH_CHANGE_PHONE_FORBIDDEN (caused by SendChangePhoneCodeRequest)
```

Regards

**Comment by Lonami** [comment]
Not a bug, simply means you logged in too early and can't use that yet. It is however a new error I had not seen before.

**Comment by Lonami** [comment]
In upcoming versions you'll be able to `except errors.FreshChangePhoneForbiddenError`.

**Comment by NotStatilko** [comment]
@Lonami Can you please tell me what means _"logged in to early and can't use that yet"_? How long does it take to be able to use this method?

And if you can, please tell me after what time do sessions become outdated and automatically disconnected? Will sending periodically requests help?

Thank you

**Comment by Lonami** [comment]
No idea for either.
