### ISSUE TITLE
V1.12b version, the account is disabled or cancelled within one minute after registering and generating an account

### ISSUE THREAD

**Issue by FLYVIP** [LonamiWebs/Telethon#1465]
Version V1.12b, the account is disabled or cancelled within one minute after registering and generating an account, and the replacement of different IP, apiid, number, etc. still exists. What is the reason for this? This situation has occurred since yesterday. It has been normal before.

**Comment by Lonami** [comment]
Nothing Telethon can do about it if Telegram decides to delete the account.
