### ISSUE TITLE
Hosting a Telethon User BOT on google-app-engine

### ISSUE THREAD

**Issue by bsashidh** [LonamiWebs/Telethon#1469]
I am trying to deploy a simple user bot on Google App Engine Flexible Environment running python3.7, but I get the following error. 

"File "/env/lib/python3.7/site-packages/telethon/client/auth.py", line 20, in phone: typing.Callable[[], str] = lambda: input('Please enter your phone (or bot token): '), EOFError: EOF when reading a line"

I beleive this is because the library is prompting a user input from the terminal for phone number/password which will not work on google app engine. Is it possible to allow these inputs in any other way that can work on the Google App Engine Platform?

**Comment by Lonami** [comment]
This is neither a bug nor an enhancement. This is a question which doesn't belong here.
