### ISSUE TITLE
Friendly method for QR login

### ISSUE THREAD

**Issue by tulir** [LonamiWebs/Telethon#1471]
https://core.telegram.org/api/qr-login

#1467 is probably a requirement for this to happen

**Comment by Ak4zh** [comment]
I have tried the qr login, the login succeeds but the telethon client is unable to accept the updateLoginToken update https://core.telegram.org/api/qr-login#confirming-importing-the-login-token due to [#1467](https://github.com/LonamiWebs/Telethon/issues/1467)
