### ISSUE TITLE
SendMessageRequest

### ISSUE THREAD

**Issue by imvg** [LonamiWebs/Telethon#1472]
I use send_message to send a message, but I receive a SendMessageRequest error
I send messages to two channels separately, the first channel has been banned by the administrator, but the second channel has not been banned, but I still can not send a message to the second channel
I tested that if I first send a message to the second channel, it can be sent successfully, and then send a message to the first channel, a SendMessageRequest error will occur
![image](https://user-images.githubusercontent.com/65800334/82721415-845c9c00-9cef-11ea-89f3-93bdec125eed.png)

**Comment by Lonami** [comment]
Not a bug, works as intended.

**Comment by imvg** [comment]
> Not a bug, works as intended.

but the second channel has not been banned , why cannot send also ?

**Comment by imvg** [comment]
> Not a bug, works as intended.

If a channel returns SendMessageRequest, how should I avoid affecting other chanlel?

**Comment by thanh15dt2** [comment]
@imvg  Did you resolve this problem?
