### ISSUE TITLE
client.send_file cannot specify file_name for bytes/str

### ISSUE THREAD

**Issue by Gowee** [LonamiWebs/Telethon#1473]
`client.send_file` accepts `bytes` and `str` as its `file` parameter. But it does not have a `file_name` parameter which could have been passed to `upload_file`.

https://github.com/LonamiWebs/Telethon/blob/4393ec0b83d511b6a20d8a20334138730f084375/telethon/client/uploads.py#L91

**Comment by Lonami** [comment]
You can do this:
```python
import io
file = io.BytesIO(your_bytes)
file.name = 'foo.txt'
client.send_file(chat, file)
```

**Comment by Allerter** [comment]
Why would we need a `name` parameter if we already have `DocumentAttributeFilename`?

**Comment by Lonami** [comment]
Simplicity, allows for the attribute to change without requiring changes from the user (it's why friendly methods exist). The same would apply to `voice_note`, `video_note`. and `supports_streaming`.

**Comment by Lonami** [comment]
Closing because I feel like `send_file` has way too many parameters already and there's a workaround which isn't too terrible.

**Comment by quick-wq** [comment]
for mark

**Comment by mortalis13** [comment]
For images raw bytes, the corresponding png/jpg headers/signature could be used to detect if it's image, so it's sent as image. Without it `is_image` responds with `False` and it appears as "unnamed" with download arrow button in the final post.
