### ISSUE TITLE
events.Album handles events separately

### ISSUE THREAD

**Issue by apepenkov** [LonamiWebs/Telethon#1479]
**Checklist**
* [ + ] The error is in the library's code, and not in my own.
* [ + ] I have searched for this issue before posting it and there isn't a duplicate.
* [ + ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events
import asyncio

loop = asyncio.get_event_loop()
api_id = ...
api_hash = ""
client_1 = TelegramClient("client", api_id, api_hash)

@client_1.on(events.Album())
async def album_handler(event: events.Album.Event):
    print(event.messages)


async def main():
    await client_1.start()
    print('Started')
    await client_1.run_until_disconnected()


loop.run_until_complete(main())


```
Expected: one event, event.messages -> list of telethon.tl.patched.Message
Got: N events (for N images), every with one [telethon.tl.patched.Message]

**Comment by Lonami** [comment]
(Wrong label). Please indicate also the *sitation* in which this occurs. Using my account, sending an album to myself, I can see the messages correctly.

**Comment by apepenkov** [comment]
Using this code?

**Comment by apepenkov** [comment]
Just re-created session, didn't help. Tried sending albums from TGDesktop and TGX, same thing, so looks like it isn't some client problem

**Comment by apepenkov** [comment]
Updating to master branch didn't help, too

**Comment by Lonami** [comment]
I have used the following code which is equivalent to yours pretty much:
```python
with client:
    @client.on(events.Album)
    async def h(e):
        print(len(e.messages))

    client.run_until_disconnected()
```

When I send an album of two photos to myself, it correctly prints `2`. Are you testing this in a chat with yourself? Can you check if it occurs on the test servers? [The way albums work](https://github.com/LonamiWebs/Telethon/blob/master/telethon/events/album.py) is by checking for other `Update` within the `Updates` Telegram sent. It is strange Telegram is not including the entire album within the same `Updates`.

**Comment by apepenkov** [comment]
I am testing it by sending from my account A to account B in private

**Comment by Lonami** [comment]
Sending an album of two photos via Telegram X to my main account, under which `client` is running, still prints `2`.

**Comment by apepenkov** [comment]
Changed account B to another one, and that helped. That's very, very weird. Somehow related to account

**Comment by apepenkov** [comment]
How can I check my account's DC ID without images?

**Comment by apepenkov** [comment]
So I was sending album from account with DC ID 2 to account with DC ID 4. That caused this issue. When I tried to sending album from DC ID 2 to DC ID 2, that issue wasn't there.

**Comment by apepenkov** [comment]
I don't know, if it can be somehow fixed in telethon, or that's related to the way telegram sends updates between different DCs

**Comment by Lonami** [comment]
Well it's really unfortunate. asked a friend to send me an album (they are from DC 1) and indeed they arrive as separate `Updates`. The only way I can think of to solve this is with a timeout because we can otherwise not know how many photos are in an album, and we just need to wait "long enough" until we receive them all.

**Comment by apepenkov** [comment]
I assume 0.2 secs is enough

сб, 6 июн. 2020 г., 17:00 Lonami <notifications@github.com>:

**Comment by apepenkov** [comment]
I assume 0.2 secs is enough, but maybe it also shall be an arg for handler

**Comment by apepenkov** [comment]
Maybe also check for dc of sender and client, and only if those are different use timeout? But than telethon will have to cache client's DC (idk is it cached at the moment)

**Comment by Lonami** [comment]
The [`dc_id`](https://github.com/LonamiWebs/Telethon/blob/faf7263d8f9a8457ad9cf4b117fb330f52a654bc/telethon/sessions/sqlite.py#L190-L191) is stored in the session, but anyway it's probably enough to check "if this album is only consists of 1 media, it's probably wrong" and wait then.

**Comment by apepenkov** [comment]
Right, great
