### ISSUE TITLE
FileMigrateError in TelegramBareClient

### ISSUE THREAD

**Issue by feodoran** [LonamiWebs/Telethon#148]
`TelegramClient.download_file` catches and treats the `FileMigrateError` when trying do download a file which is located on a different DC. However this is not implemented for `TelegramBareClient.download_file`. 

So when using `client.create_new_connection()` (I want to download some stuff in separate threads), I suddenly need to deal with the DC myself. I tried to simply pass `FileLocation.dc_id` to `client.create_new_connection()` but then I get an error when trying to export a client to a DC I am already connected too.  

Downloading files is a quite basic task and I think, that resolving the correct DC shouldn't be something I need to worry about when building on top of Telethon. So to me it seems that this should be part of `TelegramBareClient`, not 'TelegramClient' . Maybe one can simply move the corresponding code?

**Comment by Lonami** [comment]
> Maybe one can simply move the corresponding code?

Maybe. I wasn't sure what should belong to the `TelegramBareClient` and what should belong to the `TelegramClient` when I made the distinction in the first place. But I guess it's cumbersome to handle file migrations on separate connections. Exporting a temporary authorization should work on any connection but I haven't tried it.
