### ISSUE TITLE
Feature to get new joiners and messages in a group by day or by date

### ISSUE THREAD

**Issue by srinivasdasu24** [LonamiWebs/Telethon#1480]
Please describe your idea. Would you like another friendly method? Renaming them to something more appropriated? Changing the way something works?
Hi,

It will be good if we have a feature to get the list of new joiners in a day or by day wise and similarly for messages

**Comment by Lonami** [comment]
You can already use [`client.iter_admin_log`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.chats.ChatMethods.iter_admin_log) for this.
