### ISSUE TITLE
get owner of groups and supergroups

### ISSUE THREAD

**Issue by NaWeeDBHR** [LonamiWebs/Telethon#1483]
Hi
we can get admins of groups and supergroups with this
```
# Filter by admins
from telethon.tl.types import ChannelParticipantsAdmins
async for user in client.iter_participants(chat, filter=ChannelParticipantsAdmins):
    print(user.first_name)
```
but i need to get the owner and creator of supergroups and groups, not all admins!!

**Comment by Lonami** [comment]
Owners are considered admins too, the request above should return them. It is up to the user to differentiate between them.
