### ISSUE TITLE
get all Deleted accounts in the chat with iter_participants !

### ISSUE THREAD

**Issue by alimoradi2020** [LonamiWebs/Telethon#1486]
Please describe your idea. Would you like another friendly method? Renaming them to something more appropriated? Changing the way something works?
Hi, how can i get all Deleted accounts in the chat with iter_participants ??
i use 'filter' for Bots with ChannelParticipantsBots
and how about for deleted accounts !

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
