### ISSUE TITLE
how make  a specific event

### ISSUE THREAD

**Issue by alimrd318** [LonamiWebs/Telethon#1487]
hey, i want have an event run at a time for example 5:00 every day o r some thing like this 
and another question 

`@client.on(events.NewMessage(incoming=True)) `
`async def my_event_handler(event):`
    `    if event.is_private:`
`print('something')`

is it possible have is_private condition in this event with incoming=True ?
i want private message incoming how can do this in an event?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
