### ISSUE TITLE
Account Banned

### ISSUE THREAD

**Issue by shmosta** [LonamiWebs/Telethon#1489]
Hello.  Awesome lib, very robust and has worked well for me up until a few weeks ago when I got my first account banned.  I didn't file a bug as the repro steps are pretty vague.  I created a new account this week and launched telethon_examples/print_updates.py.  Shortly after successful auth code validation and login, my account was banned :/ Anyone else facing this issue?  I registered my app as a desktop app using the Telegram API.  I should also note that the native Telegram app was running in the background while I launched my Telethon app if that's worth anything.  Any tips or suggestions on what we can do to avoid getting banned?  I'm in North America, connecting through a common residential ISP and don't spam or even use Telegram all that often.  Any help is greatly appreciated.

**Comment by Lonami** [comment]
#824 has some insight.
