### ISSUE TITLE
CHAT_ADMIN_INVITE_REQUIRED

### ISSUE THREAD

**Issue by unkn19wn** [LonamiWebs/Telethon#149]
hi 
looks like telegram did some changes today !

telethon.errors.RPCError: (RPCError(...), 'Unknown error message with code 403: CHAT_ADMIN_INVITE_REQUIRED'

**Comment by Lonami** [comment]
Could you please tell me when `CHAT_ADMIN_INVITE_REQUIRED` error occurs, so that I can add it to the error list with a proper help message?
