### ISSUE TITLE
Reply to message only from users

### ISSUE THREAD

**Issue by ibimo** [LonamiWebs/Telethon#1490]
Im using this code and it work, the problem is:
The userbot respond/reply to messages from groups too, how i can avoid this?

`from telethon import TelegramClient, events

client = TelegramClient('anon', api_id, api_hash)

@client.on(events.NewMessage)
async def my_event_handler(event):
    if 'hello' in event.raw_text:
        await event.reply('hi!')

client.start()
client.run_until_disconnected()`

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
