### ISSUE TITLE
AttributeError: 'TelegramClient' object has no attribute 'invoke'

### ISSUE THREAD

**Issue by nedlir** [LonamiWebs/Telethon#1491]
**What I want to achieve**
I want to add a contact to my telegram account by adding their number.

**The code**
```
from telethon import TelegramClient
from telethon.tl.types import InputPhoneContact
from telethon.tl.functions.contacts import GetContactsRequest
from telethon.tl.functions.contacts import ImportContactsRequest

with TelegramClient('Love', api_id, api_hash) as client:
    client.connect()
    contact = InputPhoneContact(client_id=0, 
                        phone=test_number, 
                        first_name="Friend", 
                        last_name="_Name")
    contacts = client(GetContactsRequest(0))
    result = client.invoke(ImportContactsRequest(contact))
    client.send_message('me', 'Added contact succesfully!')
```
**The Error**
**`AttributeError: 'TelegramClient' object has no attribute 'invoke' `**

It seems like adding users is not working for me. I'm using latest version of telethon (1.14) and latest version of Python (3.8.3).

Your assistance is kindly appreciated.

**Comment by Lonami** [comment]
`.invoke` is an extremely ancient method and has long been removed. Adding users is considered spam and will get both your account and group deleted.

**Comment by NavruzbekNoraliev** [comment]
What could be possible solution for adding a user than ?

**Comment by nedlir** [comment]
I don't know of any method to achieve this.

**Comment by Adreaming5101** [comment]
> What could be possible solution for adding a user than ?
I have the same problem. Have you solved it now？

**Comment by Adreaming5101** [comment]
> What could be possible solution for adding a user than ?

I have the same problem. Have you solved it now？

**Comment by jdf159357** [comment]
Use Telethon (0.19)

**Comment by Shivansh-Mittal** [comment]
I need to look for a phone number on telegram but i can't without adding it to my contacts. So if i can't add phone number to my contact using telethon, what is the roundabout then ???
