### ISSUE TITLE
MessageButton.click() on KeyboardButtonRequestPhone completely ignored

### ISSUE THREAD

**Issue by TrollStation** [LonamiWebs/Telethon#1492]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
await c.send_message("/reset")
r = await c.get_response()
sleep(wait)
await r.click(0)  # <- Here i try click on KeyboardButtonRequestPhone
r = await c.get_response()
sleep(wait)
```

**Traceback**
```
no tracebacks
```
My code is not matter. I had append working code to library on my machine and it works. I dont have enough time and dont realize how correctly make contributions to that awesome project.

Click method in MessageButton class completely ignores KeyboardButtonRequestPhone. My simple code does bots behaviour testing, i tried emulate clicks on "request_phone" buttons, but nothing happened and conversation instance tears dows with the TimeoutError. Then i go to [telethon/tl/custom/messagebutton.py](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/custom/messagebutton.py) and see if-elif block does not contain any checks for KeyboardButtonRequestPhone as instance.

Then I just added at end of file
```python
        elif isinstance(self.button, types.KeyboardButtonRequestPhone):
            user = await self._client.get_me()
            input_media_contact = types.InputMediaContact(phone_number=user.phone,
                                                          first_name=user.first_name,
                                                          last_name=user.last_name,
                                                          vcard='')
            return await self._client.send_file(self._chat, file=input_media_contact)
```
and it works. On click() it shares contact, just like other clients. 
Probably same issue with KeyboardButtonRequestGeoLocation because that type is missing in if-elif block. I did not figure out how to get true geolocation (especially where there is no such possibility), but the essence is the same.

Sorry if this is so obvious, but I could not understand what was happening in half an hour. Hope this helps someone.

**Comment by Lonami** [comment]
Seems like a fair enough idea. However, official clients have confirmation for sharing the phone, while this doesn't, and it seems like one could easily share the phone on accident. (The same indeed applies to Telethon automatically opening URLs, which I regret).

So perhaps we could have `button.click(share_phone=True)` which would enable it to share the phone if the button is such, and error if the flag is false (default).

`share_phone='1234'` coulf share a custom value, and similarly `share_geo` could accept a pair of coordiates.

What do you think of this approach?

**Comment by TrollStation** [comment]
> button.click(share_phone=True)

Sounds good if `share_phone` is `False` by default. Confirmation is quite annoying but it's needed. IMHO, sending custom number is not good idea in that case, the button was made in order to send own user's contacts. For sending arbitrary contact sbetter implement yet another `uploads` method like `send_contact`.
But for `share_geo` with pair of coordinates really great idea because platform that runned code may does not have geolocation services.

Thanks for your reply.

**Comment by Lonami** [comment]
> sending custom number is not good idea in that case

If Telegram wanted to prevent this, there would be a request with no parameters that would send your phone and your phone only. Even without using the button, a user can share a different contact, and the bot would have no way to know if the button was pressed or the user selected a different contact. So I think Telethon should also offer this possibility.

**Comment by TrollStation** [comment]
It's true. 
Something like this will be enough for base functionality.  Maybe some additional argument of type InputMediaContact for sharing that contact instead of own user. 
```python
async def click(self, *, share_phone: bool = False, long: float = None, lat: float = None):
    class PhoneNumberSharingNotConfirmed(Exception):
        pass
    class LocationEmpty(Exception):
        pass
...
...
...
    elif isinstance(self.button, types.KeyboardButtonRequestPhone):
        user = await self._client.get_me()
        input_media_contact = types.InputMediaContact(phone_number=user.phone,
                                                      first_name=user.first_name,
                                                      last_name=user.last_name,
                                                      vcard='')
        return await self._client.send_file(self._chat, file=input_media_contact)
    elif isinstance(self.button, types.KeyboardButtonRequestGeoLocation):
        if long is None or lat is None:
            raise LocationEmpty()
        input_media_geo_point = types.InputMediaGeoPoint(geo_point=types.InputGeoPoint(long, lat))

        return await self._client.send_file(self._chat, file=input_media_geo_point)
```
`
