### ISSUE TITLE
Dialog.is_channel returns True for both Channels and Megagroups

### ISSUE THREAD

**Issue by fralcow** [LonamiWebs/Telethon#1495]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

I am trying to iterate through all dialogs and get a list of all channels. To do so I use the dialog.is_channel property. However, I have noticed that it returns True for both channels and megagroups. I also noticed that it is possible to get the desired results by also checking dialog.is_group property, which returns False for the channels.

I am not sure if it is the intended behavior for the .is_channel or the problem with how telegram defines channels and megagroups, but I feel like it stems from the logic in [telethon/tl/custom/dialog.py](https://github.com/LonamiWebs/Telethon/blob/d68d70362b0bb2f99162d290c33ede6ab4c19db1/telethon/tl/custom/dialog.py#L93):

```python
self.is_group = (
    isinstance(self.entity, (types.Chat, types.ChatForbidden)) or
    (isinstance(self.entity, types.Channel) and self.entity.megagroup)
)
self.is_channel = isinstance(self.entity, types.Channel)
```

**Code that causes the issue**
```python
from telethon import TelegramClient

client.start()
dialogs = client.iter_dialogs()
channels = []

# name_1 is a group
# name_2 is a megagroup
# name_3 is a channel
for d in dialogs:
    if d.name == 'name_1' or \
            d.name == 'name_2' or \
            d.name == 'name_3':
        channels.append(d)

breakpoint()


```

**Traceback**
```python
(Pdb) [[x.name, x.is_channel, x.is_group] for x in channels]
[['name_1', False, True],['name_2', True, True], ['name_3', True, False]]
```

**Comment by Lonami** [comment]
Megagroups are [`Channel`](https://tl.telethon.dev/constructors/channel.html)s with the `megagroup` flag fielf set to `True`. This is working as intended.
