### ISSUE TITLE
how to use `setPrivacy`

### ISSUE THREAD

**Issue by masoudcom** [LonamiWebs/Telethon#1497]
Hi.
I wanna use set-privacy for hidden phone number.
please help me

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
