### ISSUE TITLE
Don't hardcode server_address in Session

### ISSUE THREAD

**Issue by k1-hedayati** [LonamiWebs/Telethon#15]
Server IPs are regional and I was getting this first time
`RPCError: (RPCError(...), 'The source IP address is associated with a different data center (#4, for registration).')`
I created a session object and changed IP address and it worked but it would have been nicer if I could control this from settings.
By the way I suggest json over pickle to serialize session object.

**Comment by XyLoNaMiyX** [comment]
> Server IPs are regional and I was getting this first time
> `RPCError: (RPCError(...), 'The source IP address is associated with a different data center (#4, for registration).')`

Yes, I also use a different DC. But I think one (any) has to be hardcoded at least to ask for the closest one. However, it's kind of weird, because `InvalidDCError` should have been raised instead. Maybe it's different for registration? I could never test that method.

> it would have been nicer if I could control this from settings.

Users wouldn't really have an idea of what that IP address means though? I guess, I could provide all the Telegram addresses hardcoded and then simply present them as an option (maybe `dc=n` where `n` would simply select a DC address), but, as I said, this should have been handled automatically with the `InvalidDCError`.

> By the way I suggest json over pickle to serialize session object.

Yes JSON would definitely be more flexible in case we decided to add or remove things. But, that would break existing sessions. Maybe when `v1.0` is released, so it doesn't really matter if it's not compatible. I guess. Maybe some backwards compatible code for a while…

**Comment by XyLoNaMiyX** [comment]
> By the way I suggest json over pickle to serialize session object.

You can open a new issue by the way, this would not be hard to make.

**Comment by k1-hedayati** [comment]
Oh sorry, when I copy pasted sample code for `InteractiveTelegramClient` I didn't changed phone number, after entering correct number and don't get that error anymore.
So now selecting correct DC is matter of speed I guess.

> Users wouldn't really have an idea of what that IP address means though?

I'm not aware of your intended audience but from what is there right now only developers like us gonna use Telethon (might change in future) and they've got a API key and IP from my.telegram so they know what it is. Because developers have to register their app and get api key anyway they can just get IP too. Beside, DCs can be deleted, added or modified by telegram without notification and keeping list of them for auto selecting requires continuous maintenance and update which is a real burden I believe.

> Yes JSON would definitely be more flexible in case we decided to add or remove things.

Beside serialization, session class creates a file for each session and this can clutter workspace and `git status`, I don't know about number of different sessions on a typical app or how frequently they change, but depending on situation a config file or sqlite db will be better that json and pickle I think, and migrating can happen with a one time function for change pickle to new format without user interference.

**Comment by XyLoNaMiyX** [comment]
> Because developers have to register their app and get api key anyway they can just get IP too.

To be honest, I think I tried with that IP when I was developing this project on its early stage… But I have no idea what it is for. Haha.

> Beside serialization, session class creates a file for each session and this can clutter workspace and `git status`

These `*.session` files are private files that you should never give to anyone (…or they would pretty much have full access to your account). They're in the `.gitignore`, so this should be no problem I guess?

> and migrating can happen with a one time function for change pickle to new format without user interference.

Yes, yes, you're right on that. If you think this should change, as I said, open a new issue. Also, should we close this one now?

**Comment by k1-hedayati** [comment]
> Yes, yes, you're right on that. If you think this should change, as I said, open a new issue. Also, should we close this one now?

Yes I'll open another issues for this, by the way if you had some free time to waste you can add my mistake to readme/faq or catch it with proper exception to prevent this mistake in future.

**Comment by XyLoNaMiyX** [comment]
It's on the [`README.rst`](https://github.com/LonamiWebs/Telethon#id8) already:

> Then fill the file with the corresponding values (your `api_id`, `api_hash` and **phone number in international format**).

But, if it could be made any clearer, please let me know.

**Comment by k1-hedayati** [comment]
It is clear indeed :smile:
