### ISSUE TITLE
send previously uploaded photo

### ISSUE THREAD

**Issue by KiteBoarder** [LonamiWebs/Telethon#150]
Is this functionality supported? I can see that sending photo via uploading a file is supported, but how about sending a file/photo that is already uploaded to telegram servers?

**Comment by Lonami** [comment]
[`upload_file`](https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/interactive_telegram_client.py#L224) returns a handle to said uploaded file. You can [reuse](https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/interactive_telegram_client.py#L228) said handle as many times as you want.

**Comment by KiteBoarder** [comment]
What method to use for sending a previously uploaded photo?

**Comment by Lonami** [comment]
Second link.

**Comment by KiteBoarder** [comment]
How about a photo that was previously uploaded possibly by someone else? 

When I upload the file myself, the input_file handle looks like this: 
`(inputFile (ID: 0xf52ff27f) = (id=30211654610xxxxxx, parts=2, name=abc.jpg, md5_checksum=4dcc6885e75139ef59584b081xxxxx))`

When the file received via message it will look like the following, would it be possible to generate an input_file handle out of it?
`msg:  (message (ID: 0xc09be45f) = (out=True, mentioned=None, media_unread=None, silent=None, post=True, id=13, from_id=None, to_id=(peerChannel (ID: 0xbddde532) = (channel_id=123456)), fwd_from=(messageFwdHeader (ID: 0xc786ddcb) = (from_id=None, date=2017-06-19 12:36:06, channel_id=123456, channel_post=1234)), via_bot_id=None, reply_to_msg_id=None, date=2017-06-26 01:51:33, message=, media=(messageMediaDocument (ID: 0xf3e02ea8) = (document=(document (ID: 0x87232bc7) = (id=580320036828xxxxxx, access_hash=2107500923xxxxxx, date=2017-02-01 03:16:25, mime_type=video/mp4, size=988xxx, thumb=(photoSize (ID: 0x77bfb61b) = (type=s, location=(fileLocation (ID: 0x53d69076) = (dc_id=4, volume_id=42992xxxx, local_id=69xx, secret=89375067683695xxxxx)), w=90, h=90, size=2409)), dc_id=4, version=0, attributes=['(documentAttributeVideo (ID: 0xef02ce6) = (round_message=None, duration=10, w=480, h=480))', '(documentAttributeAnimated (ID: 0x11b58939) = ())'])),  
`

**Comment by Lonami** [comment]
You can reconstruct an `InputFile` based on the information you have.

**Comment by KiteBoarder** [comment]
I am trying to reconstruct, there is no 1-1 mapping, and just by changing the input_file id to the id of a another document I get this error: 
`telethon.errors.rpc_errors_400.FilePartMissingError: (FilePartMissingError(...), 'Part 0 of the file is missing from storage.')`

**Comment by Lonami** [comment]
Well the issue title says "Photo" and your code shows "Document" so you may want to try [`InputMediaUploadedDocument`](https://lonamiwebs.github.io/Telethon/constructors/input_media_uploaded_document.html)…

**Comment by ram-sh** [comment]
sorry to bring this from the dead but it is the only post i have managed to find about this as i can't find any example on how to send a photo after it was being uploaded using `upload_file`, i got the InputFile return but I just can't figure out what to do next, sadly for me, the [reuse](https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/interactive_telegram_client.py#L228) link is above my skills... 

the return I've got is:
`InputFile(id=-181942033621816102, parts=5, name='GH012872.MP4_541.791_32.147718_34.836195.jpg', md5_checksum='7bdac0dfd35e6179889f7575b0590bf2')`

can anyone pls help me understand how to share that photo?

thank you all!
