### ISSUE TITLE
Can't get entity (group) by id, get error - ValueError: Cannot find any entity corresponding to

### ISSUE THREAD

**Issue by glorsh66** [LonamiWebs/Telethon#1500]
I tried to get a group or a chat, and constantly get the same error "ValueError: Cannot find any entity corresponding to"
And I am sure that this is the valid ID, because I can easily send a message to this group.
At the same time I can easily get a group by its name.

` await client.get_dialogs()
        group_entity = await client.get_entity(group)
        message = "Список пользователей в группе:\n"
`
`
        dialogs = await client.get_dialogs(int(group))
        my_chat = await client.get_entity(PeerChat(group))
        my_channel = await client.get_entity(PeerChannel(group))
`

**Comment by Lonami** [comment]
This is working as intended. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
