### ISSUE TITLE
Getting information automatically

### ISSUE THREAD

**Issue by Mohammad01Reza** [LonamiWebs/Telethon#1501]
I have searched for this issue before posting it and there isn't a duplicate.

 Hi , I wasn’t sure if this is right place to ask this , also I’m new in here so I’m sorry if it isn’t , this could be a new feature or plugin that I think it is very useful , whole telethon is based on being and doing stuff automatically , so why shouldn’t login part?
during the project that I’m currently working with it , it is essential to edit and personalize telethon’s source itself for getting login information such as phone , code and 2steps password from a database that I created before , I want to do login stuff automatically without typing phone and code and password in console , so it is need to edit source itself , so I figured login codes that lonami wrote in source , is related to auth.py , I wrote this lines in auth.py and I confronted with an error that shouldn’t be , this is my code that I wrote :  (this code just gets the login code from database)
class Mydatabase():
	
	def __init__(self):
		
		self.mydb=mysql.connector.connect(
		host="localhost"
		, user="myslef",
		password="H59SAG45gff4bzcnMftr67Eqy",
		database="Telegram"
		)
		self.cursor=self.mydb.cursor()
	
	
	def check_user(self,phone):
		self.phone=phone
		sql="SELECT Code FROM Main_database WHERE User_id=%s"
		value=(self.phone)
		self.cursor.execute(sql,value)
		result=self.cursor.fetchall
		if(result):
			code=result[0]
			return code
		

class AuthMethods(Mydatabase):
	
	def __init__(self):
		Mydatabase.__init__(self)

    # region Public methods

And this is the error :
  
![ccba6303-eca1-4b4e-ac91-27945cba2fe3](https://user-images.githubusercontent.com/65535952/87850185-84e66d00-c903-11ea-88da-56dc7b2e507c.jpg)

So I was wonder what cause this , I tried and I couldn’t solve this so I will be very appreciate if you just give me a little guidance about this and what should I do for it.thank you

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
