### ISSUE TITLE
get_participants() not returning real user amount

### ISSUE THREAD

**Issue by alereyesx** [LonamiWebs/Telethon#1508]
get_participants() method does not seem to be able to fetch all users from a channel, yet it does it correctly when used on a group.

channel_users = await client.get_participants(entity=channel, aggressive=True)

That piece of code returns the correct amount of users when entity is a group, but it misses hundreds of users when user on a channel bigger than 1000 users.

**Comment by Lonami** [comment]
Known server-side limitation.

**Comment by alereyesx** [comment]
Is there any workaround?
