### ISSUE TITLE
delays

### ISSUE THREAD

**Issue by icoprimers** [LonamiWebs/Telethon#151]
I was testing it in a channel and telethon seemed to have 15 seconds delayed compared to my iphone. Any idea how to minimize this?

**Comment by Lonami** [comment]
15 seconds delay respect to what? To get the notifications? If you're using your phone and you read the notification, perhaps Telegram takes longer to send it to Telethon. Not sure.

**Comment by icoprimers** [comment]
I had the channel open in the telegram web client on a different phone number. So the notification didn't got read by a second client before arriving.

**Comment by icoprimers** [comment]
There seem to be different registries for push notifications (IOS: APN, Android: GCM, WP: MPNS, BB, Ubuntu Phone and Simple Push). Push seem necessarily every 24 hours with the [account.registerDevice method ()](https://core.telegram.org/method/account.registerDevice). The page [about push-updates](https://core.telegram.org/api/push-updates) shows only notifications for groups and chats so there's probably other forces at work.

When I have time I will try to figure out what's causing the delay, if the push api of telegram also sends channel updates and how we can make it faster. I love your project man I learned so much from it, keep up the good work!

**Comment by Lonami** [comment]
> if the push api of telegram also sends channel updates and how we can make it faster

I would *love* to get a sane updates management. Thanks for the interest.

**Comment by Lonami** [comment]
Closing in favor of #237.
