### ISSUE TITLE
Error in forwarding a message from channel

### ISSUE THREAD

**Issue by Kirmada7** [LonamiWebs/Telethon#1510]
**Checklist**
* [ No] The error is in the library's code, and not in my own.
* [ yes] I have searched for this issue before posting it and there isn't a duplicate.
* [ yes] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest versison.

**Code that causes the issue**
```user = []
    user = await client.get_messages('link to channel', limit=1)
    for u in user:
        message = u.message
        print(message)
        e = await client.get_entity('myusername')
        await client.forward_messages(e,
                                      message,
                                      silent=True
                                      )
...

```

**Traceback**
```
TypeError: Cannot forward messages of type <class 'str'>

```

**Comment by Lonami** [comment]
There is no bug here. You can't forward strings. You're misleadingly calling the list of messages `user`.

**Comment by Kirmada7** [comment]
> There is no bug here. You can't forward strings. You're misleadingly calling the list of messages `user`.

Then pls help I can't figure out how to

**Comment by Lonami** [comment]
This is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by Kirmada7** [comment]
> This is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

alright i'll delete it from here

**Comment by Lonami** [comment]
There is no need to delete anything.
