### ISSUE TITLE
Pass custom arguments to progress callbacks

### ISSUE THREAD

**Issue by yash-dk** [LonamiWebs/Telethon#1512]
Make provision to pass optional custom progress callback arguments along with progress callbacks in Downloads and Uploads.
Like
`await message.download_media(progress_callback=callback,prog_args=(args))`

**Comment by Lonami** [comment]
The library does not need to support this. `functools.partial` or an intermediate `lambda` or `def` that capture the extra argument are enough.

**Comment by Kemal6706150033** [comment]
> The library does not need to support this. `functools.partial` or an intermediate `lambda` or `def` that capture the extra argument are enough.

can u give example please? i need extra ergument for update message from telegram bot 😫

**Comment by yash-dk** [comment]
> > The library does not need to support this. `functools.partial` or an intermediate `lambda` or `def` that capture the extra argument are enough.
> 
> can u give example please? i need extra ergument for update message from telegram bot 😫

`await message.download_media(progress_callback=lambda x,y: callback(x,y,z)`
Or
partialcallback = functions.partial(callback, *args, `**kwargs)
Just look up for functools.partial
await message.download_media(progress_callback=partialcallback)`

**Comment by Kemal6706150033** [comment]
> > > The library does not need to support this. `functools.partial` or an intermediate `lambda` or `def` that capture the extra argument are enough.
> > 
> > 
> > can u give example please? i need extra ergument for update message from telegram bot 😫
> 
> `await message.download_media(progress_callback=lambda x,y: callback(x,y,z))`
> Or
> `partialcallback = functools.partial(callback, *args, **kwargs)`
> Just look up for functools.partial
> `await message.download_media(progress_callback=partialcallback)`

wow its works!! thank u for ur answer 🥰
