### ISSUE TITLE
Forwarding bug

### ISSUE THREAD

**Issue by m9w** [LonamiWebs/Telethon#1513]
Forwarding message ignore arg "from" and usage global message id on account. But arg "from" is requirement.
![image](https://user-images.githubusercontent.com/52008918/89466913-57ac1280-d77d-11ea-937f-b7bbf20ebe8c.png)

**Comment by Lonami** [comment]
Could you better explain the issue? I didnt understand. `from_peer` is documented to be needed and it's passed to the API so it should not be ignored.

**Comment by m9w** [comment]
Telethon ignore arg `from_peer` but expects to receive. At the same time uses `id_meggase` as id in global message history instead of the chat id specified by the argument `from_peer`.
The screenshot shows that messages from different chats were forwarded with the changing only id. In saved messages are no such messages. But i don't want show all my notes. Just trust me.

**Comment by Lonami** [comment]
Closing since I can't find the issue here.
