### ISSUE TITLE
I want to add members to a public group but it gives runtime error [ InviteToChannelRequest ]

### ISSUE THREAD

**Issue by mramitdas** [LonamiWebs/Telethon#1514]
Error :-
telethon.errors.rpcerrorlist.UserIdInvalidError: Invalid object ID for a user. Make sure to pass the right types, for instance making sure that the request is designed for users or otherwise look for a different one more suited (caused by InviteToChannelRequest)

code :-

channel_username = input("Enter Group/Channel Username: ")
user_to_add = InputPeerUser(user['id'], user['access_hash'])
client(InviteToChannelRequest(channel_username, [user_to_add]))

**Comment by Lonami** [comment]
No bug here,
