### ISSUE TITLE
MessageMediaDocument not return file_id ( like bots )

### ISSUE THREAD

**Issue by A2DNEW** [LonamiWebs/Telethon#1515]
Hi

I use this code

`msg = await client.get_messages('me', limit=1, offset_id=0)`

But print(msg) not show to me file_id like bots:

`BQACAgQAAxkBAAK9_F8sa5j8iJQ845yxMdgYieRXRQwpAALrBwACzo2RU...`

How I can get file_id for medias?

**Comment by Lonami** [comment]
The `Message.file_id` is a property not provided by Telegram directly, and it won't show in `__str__`.

**Comment by A2DNEW** [comment]
@Lonami 

Ok thx.
How I can get this file id with telethon?

**Comment by Lonami** [comment]
This is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
