### ISSUE TITLE
Iter Profile Photos returns address of a tiny picture

### ISSUE THREAD

**Issue by psychosys** [LonamiWebs/Telethon#1519]
Hi

iter_profile_photos returns a very tiny photo to be downloaded with download_media, is there anyway to choose the PhotoSize type?

I can see that there are three types of photo, type 'c' has resolution of 640x640! this is the one I want to grab!

for example
 for photo in client.iter_profile_photos(peerid, limit=None):
  client.download_media(photo, imgstorepath)

downloads profile pictures with resolution of **40x40** 
**thumb = -1** doesn't work either with download_media

===

download_profile_photo works great with download_big = true, but it downloads only a single file

Thanks

**Comment by Lonami** [comment]
Telegram changed the order and put stripped size (the smallest) last, when before it was the first. Sorting should ensure it works as expected.
