### ISSUE TITLE
How to use telethon in Flask

### ISSUE THREAD

**Issue by codedphoenix** [LonamiWebs/Telethon#152]
Here is my code in flask and i get an error after calling `auth_code` asking me to call send_request first.
`

    import json
    from flask import Flask
    from flask import Response
    from telethon import TelegramClient
    from telethon.tl.functions.contacts import GetContactsRequest
    from telethon.tl.types import UserStatusOffline

    api_id = 1000000
    api_hash = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'

    app = Flask(__name__)

    @app.route('/auth/<phone>', methods=['POST'])
    def auth_phone(phone):
        client = TelegramClient("my_name", api_id, api_hash)
        client.connect()

        response = {'code_sent': False}

        if not client.is_user_authorized():
            client.send_code_request("+{}".format(phone))
            response['code_sent'] = True

        return Response(json.dumps(response), 200, mimetype="application/json")

    @app.route('/auth/<phone>/<code>', methods=['POST'])
    def auth_code(phone, code):
        client = TelegramClient("my_name", api_id, api_hash)
        client.connect()

        if not client.is_user_authorized():
            client.send_code_request("+{}".format(phone))
            client.sign_in(phone, code)

        response = {'logged_in': False}

        if client.is_user_authorized():
            response['logged_in'] = True

        return Response(json.dumps(response), 200, mimetype="application/json")`

Please make sure to call `send_code_request` first.

Thanks in anticipation.

**Comment by Lonami** [comment]
First, it would be nice if you cached a client for every phone number (and instead using `"my_name"` using something like `'phone_{}'.format(phone)`, because they need the name needs to be unique per user) to save you from the trouble of connecting every single time.

Second, you don't need to call `.send_code_request()` on `auth_code`.

> i get an error after calling `auth_code`

Yes, but on which line?

**Comment by codedphoenix** [comment]
@Lonami Thanks for the response but how do i create session for each client because Telegram Client doesn't save the session until after successful sign in.

**Comment by Lonami** [comment]
> but how do i create session for each client

I told you how.

> until after successful sign in.

You didn't tell me what or where the error is.

**Comment by codedphoenix** [comment]
Here is the crash log
`    Traceback (most recent call last):
      File "C:\Python35\lib\site-packages\flask\app.py", line 1982, in wsgi_app
      response = self.full_dispatch_request()
      File "C:\Python35\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
      rv = self.handle_user_exception(e)
      File "C:\Python35\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
        raise value
      File "C:\Python35\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "C:\Python35\lib\site-packages\flask\app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "C:/Users/Blessing/PycharmProjects/Bot/Bot.py", line 37, in auth_code
        client.sign_in(phone, code)
      File "C:\Python35\lib\site-packages\telethon\telegram_client.py", line 334, in sign_in
        'Please make sure to call send_code_request first.')
    ValueError: Please make sure to call send_code_request first.
`

**Comment by codedphoenix** [comment]
Can you please help me re-write the code?

**Comment by Lonami** [comment]
OK I know the issue (I just tested and realized what it was). You are creating two clients, which will generate different authorization keys (they're always random). So Telegram will send you a code valid for the first client, **not** the second. As I suggested, you have to cache a client for each phone number and not recreate them.

> Can you please help me re-write the code?

This is not StackOverflow.

**Comment by clintnetwork** [comment]
are you sad in your life @Lonami to be a bitch/asshole like this?

**Comment by ForsakenHarmony** [comment]
Ok boomer

**Comment by Lonami** [comment]
@clintnetwork after a thousand issues in a large project, there is a point where you have to start being more strict. This work is something I do for free, on my free time, and because I want to. I have **no obligation** on doing other people's job. This is my repository, and these are my rules. You do not need to use this project or lurk here if you don't like it, or if you don't like me. There is no need to go off-topic in the comments, and there is much less of a reason to be hostile towards other people (including myself).

I have reported your comment to GitHub, to let them decide on this one.
