### ISSUE TITLE
Want to increase telegram channel post views

### ISSUE THREAD

**Issue by pulkit5667** [LonamiWebs/Telethon#1523]
I want to increase my telegram channel post views but I don't know how to write python. Because I am a beginner and I am learning some coding. Can anyone please help me to write post views increase script. Or can anyone give me the already coded script so I can learn and increase views on my channel post.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
