### ISSUE TITLE
Upload videos larger than 300MB

### ISSUE THREAD

**Issue by prodrigues1912** [LonamiWebs/Telethon#1524]
I cannot upload videos larger than 300MB as videos, with streaming support. Please, how do I solve this?

Code:

```
import os

from telethon import TelegramClient, sync
from telethon.tl.types import DocumentAttributeVideo

import settings as stg


client = TelegramClient("test_session", stg.api_id, stg.api_hash)
client.start()

for root, _, files in os.walk(stg.path):
    file_dictionary = {int(sub.split(".")[0]): sub for sub in files}
    for key, value in sorted(file_dictionary.items()):

        print(os.path.join(root, value))
        # file = client.upload_file(os.path.join(root, value),file_name=value)
        client.send_file(
            stg.telegram_group,
            file=os.path.join(root, value),
            caption=value[:-4],
            attributes=(DocumentAttributeVideo(0, 0, 0)),
            supports_streaming=True,
        )
```

**Comment by Lonami** [comment]
> I cannot upload videos larger than 300MB as videos, with streaming support

Why? What's the error?

**Comment by prodrigues1912** [comment]
thanks for answering me so fast!
Sorry, I was not clear. The video sends, but is available as a file, not a video.

**Comment by Lonami** [comment]
You're passing a single attribute, not a list like `attributes=[DocumentAttributeVideo(0, 0, 0)]`. Are you sure this doesn't solve the issue? Videos so large might need proper values in there, not just dummy 0.

**Comment by prodrigues1912** [comment]
No, it still doesn't work. I'm going to do some more tests. Thank you for your help!
