### ISSUE TITLE
How do I get unread conversations?

### ISSUE THREAD

**Issue by GamiDPC** [LonamiWebs/Telethon#1528]
Didn't find the function how to get unread dialogs?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
