### ISSUE TITLE
Markdown parser bug

### ISSUE THREAD

**Issue by apepenkov** [LonamiWebs/Telethon#1529]
**Checklist**
* [ + ] The error is in the library's code, and not in my own.
* [ + ] I have searched for this issue before posting it and there isn't a duplicate.
* [ + ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events

import asyncio
import logging
import tracemalloc
import os

loop = asyncio.get_event_loop()
scriptName = str(os.path.basename(__file__).split(".")[0])
print("Starting", scriptName)
api_id = ...
api_hash = ...
tracemalloc.start()
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.WARN)
logger = logging.getLogger(__name__)

bot = TelegramClient("bot_" + scriptName, api_id, api_hash, connection_retries=120, retry_delay=2)


@bot.on(events.NewMessage(pattern="/start"))
async def start_handler(event: events.NewMessage.Event):
    await event.respond("[**Hello, my friend**]\n\nThat's a text\n\n[Link](https://www.google.com/)")
    raise events.StopPropagation


async def main():
    print('Starting bot...')
    await bot.start()
    bot_user = await bot.get_me()
    print(f"Authorized bot as @{bot_user.username}")
    print('Started')
    await bot.run_until_disconnected()


loop.run_until_complete(main())

```

Expected answer:
[**Hello, my friend**]

That's a text

[Link](https://www.google.com/)

Got:
Hello my friend]

That's a text

[Link

> Whole text is a link

![изображение](https://user-images.githubusercontent.com/39992738/90787627-98736200-e30d-11ea-9397-6d5de899d154.png)

I understand about such parsers being not the easiest thing, and HTML is more preferable (or even make eintities myself), but that's way harder. Anyway, I think I have to report it.

**Comment by Lonami** [comment]
Does `**[text](url)**` not work?

**Comment by apepenkov** [comment]
![изображение](https://user-images.githubusercontent.com/39992738/90789575-bcd03e00-e30f-11ea-801c-93dfe2467060.png)

message.text: "[text](https://github.com/LonamiWebs/Telethon/issues/1529)"

**Comment by Lonami** [comment]
Ah nevermind I see the issue. I don't think this is fixable unless we use a proper markdown parser, which would be a breaking change. Allowing to escape with `\` may be the only workaround. But you should probably use HTML here.

**Comment by Lonami** [comment]
Well, it is technically a bug. It can remain open although I doubt it'll get fixed any time soon.

**Comment by YaCodesDevelopment** [comment]
Seems that the problem yet exist, any solutions to far?)

**Comment by apepenkov** [comment]
> Seems that the problem yet exist, any solutions to far?)

I recommend you to use html instead of markdown, it's generally more reliable

**Comment by YaCodesDevelopment** [comment]
I'm afraid this is just not an option for me, so I will need to write my
own markdown implementation(

**Comment by dromanov** [comment]
I did a dirty hack to "escape" the `--`, `**` and `~~` by insering a zero-width unicode character between the repeated chars. It works and looks the same, but it is not the same text, though.

The code is simple:
```Python
import re

MARKDOWN_QUOTE_PATTERN = re.compile(r"(__|\*\*|~~|`|\\)")

def escape_md(value: str) -> str:
    # There are zero-width unicode character between quotes in lambda, not an empty string!
    return re.sub(pattern=MARKDOWN_QUOTE_PATTERN, repl=lambda m: "​".join(m.group(0)), string=value)
```
