### ISSUE TITLE
Responsing to an incoming message 

### ISSUE THREAD

**Issue by RYNEQ** [LonamiWebs/Telethon#153]
I'm trying to response a and incoming message which I captured using an update_handler  
but the update object doesn't have entity object 
how can  I response to messages that are captured using update handler?

**Comment by Lonami** [comment]
My first idea is that you should store a dictionary somewhere which contains `{user_id: user}`, so you know the correspondence. Issue #114 is similar in the sense that you don't have the hash, and #93, which is a duplicate from this one.

**Comment by Lonami** [comment]
Telegram should probably send a [`Updates`](https://lonamiwebs.github.io/Telethon/constructors/updates.html) which has users, so you should probably cache those users.
