### ISSUE TITLE
Would it be possible to async await until all updates from catch_up() are processed?

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#1534]
As far as I understood, right now the coroutine `await client.catch_up()` awaits for client to get pts difference, parse updates, and put them in dispatching queue, but does not await until those update are processed by handlers.

That is, if I write something like this:
``` python

def handler(event):
   # ... Here is some arbitrary callback handler ...

client = TelegramClient(...)
client.add_event_handler(handler, ...)
await client.connect()
await client.catch_up()
await client.disconnect()

```

this code will most likely end up in Exception, because `catch_up()` just puts new events in queue and then goes straight to the next line which is `client.disconnect()`, leaving all of the new events being processed by already disconnected client, which ends up in ConnectionError or similar.

The request is: Is there a way to implement a coroutine that awaits until all of the updates from `catch_up()` are **processed** by a handler (so that disconnect happens only after all the new events have gone through handler function)?

**Comment by Lonami** [comment]
It is possible but the bigger problem is that the whole update handling needs some serious refactoring.

**Comment by vegeta1k95** [comment]
@Lonami Is the update system revision planned for anytime soon?

**Comment by Lonami** [comment]
No.

**Comment by vegeta1k95** [comment]
Okay, solved this problem quite easily:

``` python
    
   async def wait_catch_up(client):
        await client.catch_up()
        while client._updates_queue:
            await asyncio.wait(client._updates_queue, return_when=asyncio.ALL_COMPLETED)
```

Can be closed.
