### ISSUE TITLE
how get channel message?

### ISSUE THREAD

**Issue by aminsato** [LonamiWebs/Telethon#1535]
Hi guys I have two issues 
1. How get a channel message without bot?
 2. How determine the message forward from another person or channel, and how get them forward ids?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
