### ISSUE TITLE
Connection does not obey timeout argument or hangs indefinitely when using bad network/bad proxy.

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#1536]
Sometimes, when using a shitty proxy `client.connect()` hangs for a very long time or even indefinitely long ignoring any timeouts and retries.

**Code that causes the issue**
```python
import asyncio
from telethon import TelegramClient

proxy = ...
client = TelegramClient(session, api_id, api_hash,
       timeout=2,
       proxy=proxy,
       connection_retries=0, 
       auto_reconnect=False)

try:
    await client.connect()
    await client.catch_up()
    await asyncio.sleep(5)
    await client.disconnect()
except Exception as e:
    print(str(e))

```

It seems that `MTProtoSender` succesfully connects but than hangs on the `await self._connection.recv()` part without timeout, exception is never thrown and the line `await client.catch_up()` is never reached.
Here is the log message from one of such runs:
```
[DEBUG/2020-08-25 22:42:56,696] telethon.network.mtprotosender: Connection success!
[DEBUG/2020-08-25 22:42:56,696] telethon.network.mtprotosender: Starting send loop
[DEBUG/2020-08-25 22:42:56,697] telethon.network.mtprotosender: Starting receive loop
[ INFO/2020-08-25 22:42:56,697] telethon.network.mtprotosender: Connection to 149.154.167.51:443/TcpFull complete!
[DEBUG/2020-08-25 22:42:56,908] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2020-08-25 22:42:56,908] telethon.extensions.messagepacker: Assigned msg_id = 6865024945867416168 to InvokeWithLayerRequest (24237a91278)
[DEBUG/2020-08-25 22:42:56,908] telethon.network.mtprotosender: Encrypting 1 message(s) in 92 bytes for sending
[DEBUG/2020-08-25 22:42:56,909] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2020-08-25 22:42:56,909] telethon.network.mtprotosender: Waiting for messages to send...
-----> [DEBUG/2020-08-25 22:42:56,909] telethon.network.mtprotosender: Receiving items from the network...   <----
[ INFO/2020-08-25 22:47:57,150] telethon.network.connection.connection: The server closed the connection
[ INFO/2020-08-25 22:47:57,150] telethon.network.mtprotosender: Connection closed while receiving data
[DEBUG/2020-08-25 22:47:57,150] telethon.network.mtprotosender: Closing current connection...
[ INFO/2020-08-25 22:47:57,150] telethon.network.mtprotosender: Connecting to 149.154.167.51:443/TcpFull...
[DEBUG/2020-08-25 22:47:57,150] telethon.network.mtprotosender: Connection attempt 1...
[DEBUG/2020-08-25 22:47:57,606] telethon.network.mtprotosender: Connection success!
[DEBUG/2020-08-25 22:47:57,606] telethon.network.mtprotosender: Starting send loop
[DEBUG/2020-08-25 22:47:57,606] telethon.network.mtprotosender: Starting receive loop
[ INFO/2020-08-25 22:47:57,606] telethon.network.mtprotosender: Connection to 149.154.167.51:443/TcpFull complete!
.....

```
As you can see, connection hanged for 5 minutes (on the line I marked with arrows) then after 5 minutes it suddenly started to reconnect, even though I explicitly set `auto_reconnect=False` and `connection_retries=0`.

Any ideas about this?

**Comment by vegeta1k95** [comment]
Would it be safe to raise an `ConnectionError` instead of doing reconnection on `recv`/`send` loops if `auto_reconnect=False`?
Also, one may want to have a timeout on `self._connection.recv()`, thus maybe using `asyncio.wait_for()` would be good idea?

E.g. in `MTProtoSender` in `_recv_loop:

``` python
try:
      body = await asyncio.wait_for(self._connection.recv(), timeout=10)
except asyncio.TimeoutError as e:
      self._log.info('Connection recv_loop timed out')
      raise ConnectionError('Connection timed out!')
except IOError as e:
      self._log.info('Connection closed while receiving data')
      if self._auto_reconnect:
          self._start_reconnect(e)
          return
      raise ConnectionError('Connection was closed!')
```

**Comment by Lonami** [comment]
What's the reason for closing this? Has the issue been fixed, or have you lost interest?

**Comment by vegeta1k95** [comment]
Formally this one is not related to the lib itself. It happens when Telethon succesfully connects to proxy server, but proxy itself struggles to connect to Telegram servers. This leads to the situation where our socket is alive, lib can send requests, but doesn't receive responses. This lasts until either proxy server finally established decent connection to Telegram and transfer response to us, or until proxy server drops it socket peer and our connection throws `Server has closed connection` error. Which may last 5-10 minutes (depending on proxy server).

For instance, when doing `await connect(()` lib sends `InitConnectionRequest`, but then never receives an RPC response or any service message from Telegram, thus perpetually hanging on awaiting the future.

Solution to this would be implementing some sort of flexible request timeout system, where for each separate rpc call we can setup timeout of receiving response/acknowledgment and if either not received in that time - throw timeout exception.

Or just expose the future on which `connect()` is waiting internally and let the user decide when to cancel it.

I am personally using the hack:
`await asyncio.wait_for(client.connect(), 5)`

**Comment by khoben** [comment]
> For instance, when doing await connect() lib sends InitConnectionRequest, but then never receives an RPC response or any service message from Telegram, thus perpetually hanging on awaiting the future.

Exactly, it gets stuck at [line](https://github.com/LonamiWebs/Telethon/blob/6a36066d19aa61979d4fb490b45d9a2403c6531d/telethon/client/telegrambaseclient.py#L593):
```python
await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
```
Also it happens not only with a bad connection, but with invalid sessions ( the last character of `StringSession` can be changed to simulate this behavior).

Since the connection (`client._connect()`) itself does not cause a stuck, I think it would be better to wait for the connection (`client.is_connected()`) first, and then wait with a timeout for other requests (e.g., to prevent breaking the connection retry feature):
```python
connect_task = asyncio.create_task(client.connect())
# Waiting for connection stage done
while not connect_task.done() and not client.is_connected():
    await asyncio.sleep(0)
# Avoid getting further stuck
await asyncio.wait_for(connect_task, timeout=client._timeout)
```
