### ISSUE TITLE
client.connect() returns CONNECTION_DEVICE_MODEL_EMPTY

### ISSUE THREAD

**Issue by imatimba** [LonamiWebs/Telethon#154]
Hi, I'm testing the example from https://lonamiwebs.github.io/Telethon/#example and I'm getting

> Could not stabilise initial connection: CONNECTION_DEVICE_MODEL_EMPTY (code 400)  

on client.connect().  
I can't find any related issue in the repository.

Telethon version: 0.11.1 from pip  
Python 3.6.1 x64 on Windows  
The username it's being used in the Telegram Desktop app and an Android device at the same time  
App api created as Desktop app (maybe this is the issue?)

**Comment by Lonami** [comment]
> I'm testing the example from https://lonamiwebs.github.io/Telethon/#example

Strange, because it works fine with me. I tried upstream though. Could you try the upstream version too?

> App api created as Desktop app (maybe this is the issue?)

No.

**Comment by imatimba** [comment]
Sorry for the late response.  
Yes, same error using latest commit on upstream.  
```
Could not stabilise initial connection: CONNECTION_DEVICE_MODEL_EMPTY (code 400)
Traceback (most recent call last):
  File "D:\Git\pnd_bot\telegram.py", line 16, in <module>
    if not client.is_user_authorized():
  File "C:\Python\lib\site-packages\telethon-0.11.3-py3.6.egg\telethon\telegram_client.py", line 254, in is_user_authorized
    return self.session and self.get_me() is not None
  File "C:\Python\lib\site-packages\telethon-0.11.3-py3.6.egg\telethon\telegram_client.py", line 344, in get_me
    return self(GetUsersRequest([InputUserSelf()]))[0]
  File "C:\Python\lib\site-packages\telethon-0.11.3-py3.6.egg\telethon\telegram_client.py", line 195, in invoke
    raise ValueError('You must be connected to invoke requests!')
ValueError: You must be connected to invoke requests!
```

I'll try on a Linux vm later to see if I have the same problem.

**Comment by Lonami** [comment]
Oh, wait, I think I know the issue. On windows, `platform.node()` may return an empty string. Could you run 
```python
import platform
print(platform.node())
```

On the console? Just to confirm. I will fix that now anyway. Thanks, and sorry I didn't really look into it.

**Comment by imatimba** [comment]
Yep, empty string.  
Thanks!
