### ISSUE TITLE
LoadAsyncGraphRequest error - RPCError 400: GRAPH_INVALID_RELOAD

### ISSUE THREAD

**Issue by z0ng33** [LonamiWebs/Telethon#1540]
I've upgraded telethon from 1.14.0 to 1.16.4 and got this error. In previous version everything was fine.

**Code that causes the issue**
```python
import asyncio

from .utils import get_tg_client_using_redis
from telethon.tl.functions.stats import LoadAsyncGraphRequest


async def main():
    client = await get_tg_client_using_redis(here_some_internal_user_id)
    stats = await client.get_stats('@neo_dandy')
    # stats is fine
    languages_graph = await client(LoadAsyncGraphRequest(stats.languages_graph.token))
    print(languages_graph)


asyncio.run(main())
```

**Traceback**
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 12, in main
    languages_graph = await client(LoadAsyncGraphRequest(token))
  File "/home/user/git/project/.venv/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/user/git/project/.venv/lib/python3.8/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: GRAPH_INVALID_RELOAD (caused by LoadAsyncGraphRequest)
```

**Comment by Lonami** [comment]
Raw API is always bound to break across minor releases. Never used that request or seen that error. Maybe check how official clients do it.

**Comment by z0ng33** [comment]
How can I help you to debug this problem?

**Comment by Lonami** [comment]
I'd need access to some channel where I can run these request against. But I don't really care about this issue myself, so I likely won't be investigating it any time soon. You may do your own research and, once you find a solution, let everyone here (and myself) know.

**Comment by z0ng33** [comment]
I guess I figured out what's the problem, but I don't know how to test it. The thing is `get_stats()` changes DC under the hood to fetch statistics, but `LoadAsyncGraphRequest` don't. Could you say how to temporarily change DC to fetch languages stats? I found `_switch_dc()` method, but it saves new DC to session.

**Comment by Lonami** [comment]
Ah, so the token is data-center specific. That explains it. You can see how `get_stats` works to invoke the request in the right datacenter. Not sure what a clean way to load the graph would be with a friendly method.

**Comment by z0ng33** [comment]
Thanks, I will look what's inside. Maybe, `get_stats` can be improved with some arguments, like `prefetch_languages`, `prefetch_interactions` and so on, to get all needed things inside single method? I can take part in the development.

**Comment by Lonami** [comment]
How would one specify which token to use?

**Comment by z0ng33** [comment]
All tokens placed inside `GetBroadcastStatsRequest` response. After fetching it, `get_stats` can check what graphs needs to be fetched and make additional requests.

**Comment by Lonami** [comment]
`GetBroadcastStatsRequest` doesn't accept any form of "input" tokens. I guess we could accept a parameter "graphs" that is a list of strings, such as `['mute_graph', 'iv_interactions_graph']` and would return those. I'm not a fan of strings but it's the easiest way to use it that I can think of.

**Comment by Lonami** [comment]
This issue is pretty old so I'll close it for the time being. If the issue persists in the current git version or you think more discussion should happen, let me know and I can reopen it.
