### ISSUE TITLE
Get list of channels that a user joined in telethon?

### ISSUE THREAD

**Issue by amir20172018** [LonamiWebs/Telethon#1542]
Is it possible to get list of channels that i joined in telethon?and how?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
