### ISSUE TITLE
Not connected

### ISSUE THREAD

**Issue by mishailovic** [LonamiWebs/Telethon#1545]
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull... DEBUG:telethon.network.mtprotosender:Connection attempt 1...                    DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
INFO:telethon.network.connection.connection:The server closed the connection
WARNING:telethon.network.mtprotosender:Connection error 1 during auth_key gen: ConnectionError: Not connected

This showing, and I can't connect

**Comment by Lonami** [comment]
There's not much one can do about this. By default the library should retry five times though. Closing as not realy actionable.
