### ISSUE TITLE
Get ChannelInfo

### ISSUE THREAD

**Issue by mxmlnkn** [LonamiWebs/Telethon#155]
How can I programmatically query the channel info? I couldn't find anything fitting on the API [methods](https://lonamiwebs.github.io/Telethon/methods/index.html) page.

**Comment by Lonami** [comment]
"channel info"? You can get a channel with its username, invitation link, or retrieving all the dialogs. A channel object should have said "channel info".

**Comment by mxmlnkn** [comment]
The invite link is basically what I'm interested in, but in Telegram Desktop when using RMB->"View Channel Info" some channels also have a custom message in their channel info, which would be interesting to query. Currently I'm testing out GetFullChannelRequest and what it returns me.

Btw. While we are at it, and in order to not spam issues, yet: When I try to loop over the channels and for each call `GetFullChannelRequest` or `GetChannelsRequest`, then Telethon completely hangs on the second request. When I send SIGINT the traceback reads:
Traceback (most recent call last):

      File "./Telethon/telethon/telegram_client.py", line 257, in invoke
        self._lock.acquire()
    KeyboardInterrupt

**Comment by Lonami** [comment]
> Currently I'm testing out GetFullChannelRequest and what it returns me.

Doesn't `GetFullChannelRequest` give the rest of information? Because I can't think of anything else.

> then Telethon completely hangs on the second request

That's really strange? It's like if the [lock](https://github.com/LonamiWebs/Telethon/blob/v0.11.1/telethon/telegram_client.py#L257) wasn't released, but it always is [released](https://github.com/LonamiWebs/Telethon/blob/v0.11.1/telethon/telegram_client.py#L280-L281) because it's on a `finally` block. I've never had that issue, and just today I had to iterate over a few channels.

**Comment by mxmlnkn** [comment]
Sorry, I think I forgot some important part of the error message:

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "monitorPumpNotifier.py", line 585, in <module>
        client.printChannels()
      File "monitorPumpNotifier.py", line 361, in printChannels
        channelInfo = self.invoke( GetFullChannelRequest( InputChannel( channel.id, channel.access_hash ) ) )
      File "./Telethon/telethon/telegram_client.py", line 281, in invoke
        self._lock.release()
    RuntimeError: cannot release un-acquired lock

**Comment by Lonami** [comment]
Uhm maybe a simple `try/except RuntimeError` around the `self._lock.release()` should do. Or even better, check if the lock is acquired.

**Comment by Lonami** [comment]
Reopen if the issue persists.
