### ISSUE TITLE
work with session

### ISSUE THREAD

**Issue by SudoSpurred** [LonamiWebs/Telethon#1550]
hello,
I want to know that is it possible to **several scripts** use only **one session**??

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
