### ISSUE TITLE
GetMessagesViewsRequest with increment=True doesn't increase the message view count

### ISSUE THREAD

**Issue by sai061242** [LonamiWebs/Telethon#1553]
Hello,

I read through all hte bugs logged around this feature and the only solution that i find is to use GetMessagesViewsRequest with increment=True as a parameter but this doesn't increase the count.

I created a new channel and wrote the below code to test this feature

**_from telethon import TelegramClient, events
from telethon.tl.functions.messages import GetMessagesViewsRequest
client = TelegramClient("MYUserName", api_id, api_hash)
async def main():
    channel = await client.get_entity('My_Channel_Name_Here')
    await client(GetMessagesViewsRequest(
        peer=channel,
        id=[42, 43, 44],
        increment=True
    ))
with client:
    client.loop.run_until_complete(main())_**

Above code runs without any error but the view count still remains at 1
I read in some posts that this only works once or twice a day. This is the first time I am running this script to test still it's not working.

Is the above code correct or are there changes around this API?

**Comment by Lonami** [comment]
What Telegram does cannot be fixed by Telethon. so there is no bug here. The view count is probably 1 because you already saw it in the app manually, tomorrow it should work as long as you don't open it in-app.

**Comment by Bavarian69** [comment]
Is it possible that this function has been replaced or doesn't work anymore? Can
't find the import
