### ISSUE TITLE
Why i get error when i add user to my chat

### ISSUE THREAD

**Issue by Arlidi** [LonamiWebs/Telethon#1560]
**Checklist**
I have searched for this issue before posting it and there isn't a duplicate.

**Code that causes the issue**
```Code:
chat_entity = InputPeerChannel(chat.id, chat.access_hash)
client(InviteToChannelRequest(chat_entity, [nickname]))
...

```

**Error**
```
The provided user is not a mutual contact (caused by InviteToChannelRequest)
```

**Comment by Lonami** [comment]
#1514, #1496, #1237, and many many more. None of these are a bug in the library, there is nothing to fix.

**Comment by Arlidi** [comment]
> #1514, #1496, #1237, and many many more. None of these are a bug in the library, there is nothing to fix.

Ok
thank you 
for answer  
(sorry if i do mistake. My english bad)
