### ISSUE TITLE
How to find out the ip address with which I am currently connected to Telegram

### ISSUE THREAD

**Issue by daniyalRahmany** [LonamiWebs/Telethon#1561]
hello
i want know ,i'm with what ip address connected to telegram with telethon.
is there any method or class or module in telethon to i got it?

also i connecting to telegram with socks5 proxy and i want to know Telegram see my ip address or proxy ip address?

**Comment by Lonami** [comment]
It connects to the user's data center which can be obtained via the raw API method `getConfig`. This is something so niche that doesn't deserve its own friendly method, so closing.
