### ISSUE TITLE
Can I use telethon-sync , how to download it and are there any docs for it ?

### ISSUE THREAD

**Issue by smokersan1** [LonamiWebs/Telethon#1562]
Hello , 
I have been trying to create a webapp and was hoping to give it a few telegram functionalities , but the asyncio is very difficult to integrate with non async libraries like django (there are ways but it is very unstable and dosen't make sense ,anyways I don't want to touch asyncio as I don't like the way it changes the code ( feels very non pythonic ) ) .There are async libraries like quart that I can use for telethon ,but I have already made a lot in django (Don't wanna switch the entire project because if this ). 
I would just love to use telethon-sync if I can , it's not a big issue if it takes time . And tbh I can keep running it in background and user will be able to see it's progress ,cancel it, etc .(very simple to do with sync) .
So , I would really appreciate it if there was a telethon-sync that I can use (would love if there are docs for it too) .But when I try to download it via pip it says that it's not available . I guess you stopped maintaining it .

**Comment by Lonami** [comment]
`telethon-sync` was a mistake (a big hack) that has been removed from PyPi to avoid people downloading it and thinking it's supported when it's not. Telethon is and will remain an `asyncio` library. Replace the rest of your stack to also use `asyncio` or properly and carefully learn to use `threading` and `asyncio` together (it's not impossible, it's just a pain).
