### ISSUE TITLE
checking join link if this link is related to public group or private group?

### ISSUE THREAD

**Issue by sogand145** [LonamiWebs/Telethon#1566]
Hi,
I want to get all messages in a group already joined, and find messages that has joinchat link in them, like this ```
```https://t.me/joinchat/AAAAAEHbEkejzxUjAUCfYg```
but now I don't know how to find this link is related to public group or private group?
how to find this?
because of it, I also don't know which command is ok for me to join to the new group?
this one:
```python
from telethon.tl.functions.channels import JoinChannelRequest
await client(JoinChannelRequest(channel))
```

or another one:
```python
from telethon.tl.functions.messages import ImportChatInviteRequest
updates = await client(ImportChatInviteRequest('AAAAAEHbEkejzxUjAUCfYg'))
```

thanks a lot

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by sogand145** [comment]
> the @TelethonChat group

Ok, so sorry, you're right
