### ISSUE TITLE
Requesting a public discussion group for Telethon questions and feature requests

### ISSUE THREAD

**Issue by bitcoinmeetups** [LonamiWebs/Telethon#1570]
Hi,

Requesting a public discussion group for Telethon questions and feature requests. It would be nice to be able to discuss Telethon with other users on Telegram or Reddit. 

BM

**Comment by Lonami** [comment]
This can be done with `GetFullChannelRequest` but perhaps it's about time there was a method to retrieve this "full" information more conveniently.

**Comment by Lonami** [comment]
Superseded by #1573.
