### ISSUE TITLE
builder.photo strange behavior

### ISSUE THREAD

**Issue by frisbeegrammer** [LonamiWebs/Telethon#1576]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

Quote from someone who had the same problem:

> After a couple of days of testing, I think builder.photo() doesn't work properly.
If I pass as argument only a photo, no problem. If I also pass text param, it sends only the text, without photo. Instead, if I pass buttons param without text, it sends the photo without any buttons. If I pass both buttons and text param, it sends the text with the buttons, without the photo.

**Code that causes the issue**
```python
from telethon import TelegramClient,Button,events

async def inline_handler(event):

    builder = event.builder
    buttons = [Button.switch_inline("something", query='', same_peer=False)]
    await event.answer(results=[builder.photo(file='https://live.staticflickr.com/4561/38054606355_26429c884f_b.jpg')])


async def main():

    bot = TelegramClient("bot", API_ID, API_HASH)
    await bot.start(bot_token=TOKEN)
    bot.add_event_handler(inline_handler,events.InlineQuery)

    await bot.run_until_disconnected()

```
### Code and Behavior

just photo :
`await event.answer(results=[builder.photo(file='https://live.staticflickr.com/4561/38054606355_26429c884f_b.jpg',buttons=buttons)])`

just text :
`await event.answer(results=[builder.photo(file='https://live.staticflickr.com/4561/38054606355_26429c884f_b.jpg',text="text")])`

text and buttons:
`await event.answer(results=[builder.photo(file='https://live.staticflickr.com/4561/38054606355_26429c884f_b.jpg',buttons=buttons,text="text")])`

**Traceback**
```
any error in DEBUG logs

```

**Comment by igerzog** [comment]
According to last breaking [changes](https://docs.telethon.dev/en/latest/misc/changelog.html#channel-comments-and-anonymous-admins-v1-17) in v1.17:
> Answering inline queries with a `photo` or `document` will now send the photo or document used in the resulting message by default. Not sending the media was technically a bug, but some people may be relying on this old behaviour. You can use the old behaviour with `include_media=False`.

In my opinion updating to the latest version should probably solve this.

**Comment by Lonami** [comment]
Closing since this is probably fixed as igerzog points out, so I just doubt the user did this before reporting the issue (not sure why they checked it):

> * [x]  I ran pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip and triggered the bug in the latest version.
