### ISSUE TITLE
How Can manage service messages in Groups/Channel?

### ISSUE THREAD

**Issue by hshahbodaghkhan** [LonamiWebs/Telethon#1579]
Hi everyone.
How can I manage service messages like create a fake one such as channel/group creation date or delete them in Channels/Groups?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
