### ISSUE TITLE
Ban after signing in.

### ISSUE THREAD

**Issue by KweezyPlay** [LonamiWebs/Telethon#1581]
i got number ban after executing example code, is it ok?
example got here https://docs.telethon.dev/en/latest/
```
from telethon.sync import TelegramClient, events

api_id = "19xxx"
api_hash = "35eabxxx"

with TelegramClient('name', api_id, api_hash) as client:
    client.send_message('me', 'Hello, myself!')
    print(client.download_profile_photo('me'))

    @client.on(events.NewMessage(pattern='(?i).*Hello'))
    async def handler(event):
        await event.reply('Hey!')

    client.run_until_disconnected()

```

**Comment by Lonami** [comment]
#824.

**Comment by KweezyPlay** [comment]
is this api legal? does it break telegram's ToS?

**Comment by Lonami** [comment]
Telethon is legal, yes. It does not break Telegram's ToS. It's merely a library, and it's up to the developers using it to comply with them. Unfortunately, a lot of people use it to spam, so Telegram sometimes bans innocent people. Email them if that's your case and it will be fine.

**Comment by KweezyPlay** [comment]
oh, okay then. thanks.
