### ISSUE TITLE
InputUser is not automatically inferred like InputPeer or InputChannel are

### ISSUE THREAD

**Issue by arta66** [LonamiWebs/Telethon#159]
this is info my channel :

`(channel (ID: 0xa14dca52) = (creator=True, kicked=None, left=None, editor=None, moderator=None, broadcast=True, verified=None, megagroup=None, restricted=None, democracy=None, signatures=None, min=None, id=1135498252, access_hash=-6282984409346664480, title=channel_test, username=None, photo=(chatPhotoEmpty (ID: 0x37c1011c) = ()), date=2017-07-04 06:11:05, version=0, restriction_reason=None))
`

and i have 3 contacts :

`contacts = client.invoke(GetContactsRequest(""))`
`for u in contacts.contacts:
     print (u)`
`(contact (ID: 0xf911c994) = (user_id=231735496, mutual=False))`
`(contact (ID: 0xf911c994) = (user_id=408708469, mutual=False))`
`(contact (ID: 0xf911c994) = (user_id=442246143, mutual=False))`

I dont know how i can use this code:

` from telethon.tl.functions.messages import AddChatUserRequest`

`client.invoke(AddChatUserRequest(`
  ` chat_id,`
   `user_to_add,`
   `fwd_limit=10  # allow the user to see the 10 last messages`
`))`

what is chat_id ? and user_to_add ?

when i use this code

`client.invoke(AddChatUserRequest(`
   `1135498252,`
   `231735496,`
  ` fwd_limit=10  # allow the user to see the 10 last messages`
`))`

i see this error

`Traceback (most recent call last):
 File "<pyshell#102>", line 4, in <module>
   fwd_limit=10  # allow the user to see the 10 last messages
  File "C:\Python34\lib\site-packages\telethon\telegram_client.py", line 247, in invoke
   request, timeout=timeout, updates=updates)
   File "C:\Python34\lib\site-packages\telethon\telegram_bare_client.py",    line 188, in invoke
    self.sender.send(request)
  File "C:\Python34\lib\site-packages\telethon\network\mtproto_sender.py",    line 57, in send
   request.on_send(writer)
  File "C:\Python34\lib\site-packages\telethon\tl\functions\messages    \add_chat_user.py", line 39, in on_send
   self.user_id.on_send(writer)
    AttributeError: 'int' object has no attribute 'on_send'`

**Comment by Lonami** [comment]
> what is chat_id ?

Well, the *ID* of the *chat* you want to add the users to.

and user_to_add ?

Well, the *user* you want *to add*. Notice, I said user, not contact.

> AttributeError: 'int' object has no attribute 'on_send'

Because you're passing "integers", not "users".

**Comment by arta66** [comment]
how i can add my contact to my channel??

**Comment by Lonami** [comment]
[`GetContactsRequest`](https://lonamiwebs.github.io/Telethon/methods/contacts/get_contacts.html) does return a class called [`Contacts`](https://lonamiwebs.github.io/Telethon/types/contacts/contacts.html). But it doesn't only have a `.contacts` field. It has an `.users` field.

**Comment by arta66** [comment]
please ...
result my contacts.users is
`[user#2e13f4c3 flags:# is_self:flags.10?true contact:flags.11?true mutual_contact:flags.12?true deleted:flags.13?true bot:flags.14?true bot_chat_history:flags.15?true bot_nochats:flags.16?true verified:flags.17?true restricted:flags.18?true min:flags.20?true bot_inline_geo:flags.21?true id:int access_hash:flags.0?long first_name:flags.1?string last_name:flags.2?string username:flags.3?string phone:flags.4?string photo:flags.5?UserProfilePhoto status:flags.6?UserStatus bot_info_version:flags.14?int restriction_reason:flags.18?string bot_inline_placeholder:flags.19?string lang_code:flags.22?string = User, user#2e13f4c3 flags:# is_self:flags.10?true contact:flags.11?true mutual_contact:flags.12?true deleted:flags.13?true bot:flags.14?true bot_chat_history:flags.15?true bot_nochats:flags.16?true verified:flags.17?true restricted:flags.18?true min:flags.20?true bot_inline_geo:flags.21?true id:int access_hash:flags.0?long first_name:flags.1?string last_name:flags.2?string username:flags.3?string phone:flags.4?string photo:flags.5?UserProfilePhoto status:flags.6?UserStatus bot_info_version:flags.14?int restriction_reason:flags.18?string bot_inline_placeholder:flags.19?string lang_code:flags.22?string = User, user#2e13f4c3 flags:# is_self:flags.10?true contact:flags.11?true mutual_contact:flags.12?true deleted:flags.13?true bot:flags.14?true bot_chat_history:flags.15?true bot_nochats:flags.16?true verified:flags.17?true restricted:flags.18?true min:flags.20?true bot_inline_geo:flags.21?true id:int access_hash:flags.0?long first_name:flags.1?string last_name:flags.2?string username:flags.3?string phone:flags.4?string photo:flags.5?UserProfilePhoto status:flags.6?UserStatus bot_info_version:flags.14?int restriction_reason:flags.18?string bot_inline_placeholder:flags.19?string lang_code:flags.22?string = User]`

now i dont know user_to_add ?
please help meee

**Comment by Lonami** [comment]
> Well, the *user* you want *to add*. Notice, I said **user**, not contact, neither user ID.

Just pick the user you want to add. I don't know who you want to add.

**Comment by arta66** [comment]
i use this and see error
`from telethon.tl.functions.messages import AddChatUserRequest`
`contacts = client.invoke(GetContactsRequest(""))`
`user = contacts.users[0]  # For instance`
`client.invoke(AddChatUserRequest(`
    `chad_id=1135498252,`
    `user_id=user,  # Yes, the name is misleading`
    `fwd_limit=10`
`))`


`telethon.errors.rpc_errors_400.UserIdInvalidError: (UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types.')`

**Comment by Lonami** [comment]
Upgrade Telethon.

**Comment by arta66** [comment]
i upgrade with :
`pip install --upgrade telethon` 
and again see error
`telethon.errors.rpc_errors_400.UserIdInvalidError: (UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types.')`

**Comment by Lonami** [comment]
I honestly don't understand why Telegram can't just use `InputPeer` everywhere.

**Comment by thangvuongbk** [comment]
Hello,
is this issue solved?
I am concerning the same. please give me an example how to add the specific person to the group chat.
Thanks a lot

**Comment by Lonami** [comment]
Yes, this issue is solved, that's why it's closed.

**Comment by thangvuongbk** [comment]
Hi @Lonami , thanks for quick reply,
but actually I am not fully understand what is 'user_to_add;. this parameter is InputUser,
hmmm
okay, for example, if I want to add the person has the username like @addMe, can you please show me how to do? thank you a lot

**Comment by Lonami** [comment]
@thangvuongbk there are examples in the documentation…

**Comment by thangvuongbk** [comment]
ya ya, I can see the hint one from here: http://telethon.readthedocs.io/en/stable/extra/examples/chats-and-channels.html. but sorry, it is not make me more clear.
as my concerning above, could you please give me more hints?

**Comment by Lonami** [comment]
@thangvuongbk this is not the appropriated place to ask. Ask in [@TelethonChat](https://t.me/telethonchat).

**Comment by thangvuongbk** [comment]
anyway, Thanks for your support
