### ISSUE TITLE
trouble in connect to client with socks5

### ISSUE THREAD

**Issue by AfcEagle** [LonamiWebs/Telethon#1592]
hi and thanks for great lib
i use proxalium for create a socks5 proxy (from tor.exe from torbrowser) to use in python and telethon
the code is::

```
import socks
from telethon.sync import TelegramClient
import logging
print(logging.basicConfig(level=logging.WARNING))

proxy = (socks.SOCKS5 ,"127.0.0.1",9050 )
print(proxy)

client = TelegramClient(phone, api_id, api_hash ,proxy=proxy)
client.connect()
```

-----
i recive this warning and error  in line ( client.connect() )

```
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 5 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 6 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "D:\110.py", line 14, in <module>
    client.connect()
  File "C:\Program Files\Python38\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "C:\Program Files\Python38\lib\site-packages\telethon\client\telegrambaseclient.py", line 481, in connect
    if not await self._sender.connect(self._connection(
  File "C:\Program Files\Python38\lib\site-packages\telethon\network\mtprotosender.py", line 123, in connect
    await self._connect()
  File "C:\Program Files\Python38\lib\site-packages\telethon\network\mtprotosender.py", line 248, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)
```

socks proxy is working and im using telegramDesktop with it also i can get web page with requests.get with this proxy

what is the problem please guide me

**Comment by igerzog** [comment]
You can use the default proxy option for the whole project as a workaround with pysocks installed:
```python
import socks
import socket

from telethon.sync import TelegramClient

socks.set_default_proxy(socks.SOCKS5, "localhost", 9050)
socket.socket = socks.socksocket

client = TelegramClient(phone, api_id, api_hash)
...
```

**Comment by rnyPlanet** [comment]
```
client = TelegramClient(
                    session=StringSession(),
                    api_id=api_id,
                    api_hash=api_hash,
                    device_model="Desktop",
                    system_version="Windows 10",
                    app_version="1.0",
                    proxy=dict(proxy_type=socks.SOCKS5, addr=proxy.ip,
                               port=proxy.port,
                               username=proxy.username, password=proxy.password
                               )
                )
selector = selectors.SelectSelector()
loop = asyncio.SelectorEventLoop(selector)
loop.run_forever()
```

**Comment by Nolovenodie** [comment]
In the same vein, none of the above-mentioned programmes is effective.
If anyone has a solution to the problem, please let me know! ! Thanks!!

**Comment by FLYVIP** [comment]
Yes, I have also used this method and tried many situations, but it still cannot. What is certain is that some files of the module are not forwarded through the proxy, so the connection cannot be connected. If it is not Restricted network: For example, it is normal to use a proxy in a network that can directly access the official website of telegram. However, even if the correct proxy is set on a computer that cannot access the official website, the server cannot be connected, so it is basically certain that there is a part of the program The code did not follow the set proxy network, which caused the proxy service to be normal but still unable to connect.

**Comment by rocker9527** [comment]
@Nolovenodie 
https://docs.telethon.dev/en/latest/basic/signing-in.html

Signing In behind a Proxy
If you need to use a proxy to access Telegram, you will need to either:

For Python >= 3.6 : install python-socks[asyncio]
For Python <= 3.5 : install PySocks

TelegramClient('anon', api_id, api_hash, proxy=("socks5", '127.0.0.1', 4444))

**Comment by zeevgrim** [comment]
can׳t use proxy with python-socks[asyncio]

**Comment by Lonami** [comment]
My knowledge of proxies is very limited. I would assume the correct implementation is correct, but due to the amount of people complaining, maybe something is wrong. If someone knows proxies, please help out and review the code https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/connection/connection.py. Maybe there is something obvious I am missing. Maybe we need to use another library. I do not know.

**Comment by rnyPlanet** [comment]
@exzhawk I understand that you know about proxies) how can we help you to improve the library together? https://github.com/LonamiWebs/Telethon/issues/1503#issuecomment-698455047

**Comment by Lonami** [comment]
You can review the code of `connection.py` as I explained in https://github.com/LonamiWebs/Telethon/issues/1592#issuecomment-866187463.

**Comment by rnyPlanet** [comment]
@Lonami who rewrote proxy to asyncio?  mb ask him to revise the code

**Comment by transportnik** [comment]
@rnyPlanet @rnyPlanet Hi, Has somebody solved this issue??

**Comment by xanoni** [comment]
any solutions? it used to work with `proxychains4`, but now it wants to circumvent the proxy

**Comment by xanoni** [comment]
Can confirm that below is working for me ....

```
271     client = TelegramClient(
272         tg_config.get('session_name', 'adhesive'),
273         tg_config['api_id'],
274         tg_config['api_hash'],
275         proxy=dict(proxy_type=socks.SOCKS5, addr='127.0.0.1', port='9050')
276     )
```

**Comment by Lonami** [comment]
socks5 support has been removed in v2, so this no longer is an issue.

**Comment by Pycomet** [comment]
If removed, how can I use sock5 proxies now to connect @Lonami ?

**Comment by Lonami** [comment]
v2 is not out yet, so socks5 support remains unchanged. The documentation remembers how to use proxies better than I do.
