### ISSUE TITLE
The helper retry_range has wrong behavior

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#1593]
Recent commits were refactoring the helper function `retry_range` to solve the problem with `auto_reconnect` property.

I think the current implementation is not well-behaved.
Current implementation:
``` python
def retry_range(retries, force_retry=True):
    if force_retry and not (retries is None or retries < 0):
        retries += 1

    attempt = 0
    while attempt != retries:
        attempt += 1
        yield attempt
```

Let's see:
1) For `retries=0`, `force_retry=True`  there will be 1 iterations - OK
2) For `retries=0`, `force_retry=False` there will be 0 iterations - OK
3) For `retries=1`, `force_retry=False` there will be 1 iterations - OK
4) For `retries=1`, `force_retry=True`  there will be 2 iterations - NOT OK

I think that for `retry_range(1, force_retry=True)` we would expect also only 1 iteration, no?

I propose new, much simpler implementation for this function:

``` python
def retry_range(retries, force_retry=True):
    if force_retry and retries == 0:
        retries += 1
    yield from range(1, retries + 1)
```

This will correct the behaviour, as it will yield 1 iteration for `retries=1, force_retry=True`, as expected.

Here is the test code to test both implementations on different numbers of retries:

``` python
def old_range(retries, force_retry=True):
    if force_retry and not (retries is None or retries < 0):
        retries += 1

    attempt = 0
    while attempt != retries:
        attempt += 1
        yield attempt


def new_range(retries, force=True):
    if force and retries == 0:
        retries += 1
    yield from range(1, retries + 1)


def test(func, force):

    for num_of_retries in range(0, 3):

        iterations = 0
        for _ in func(num_of_retries, force):
            iterations += 1

        print("Test", "{}({}, force={})".format(func.__name__, num_of_retries, str(force)),
              "Iterations:", iterations)


# Current range
test(old_range, True)
print("")
test(old_range, False)

print("")

# New range
test(new_range, True)
print("")
test(new_range, False)
```

Output:
```
Test old_range(0, force=True) Iterations: 1
Test old_range(1, force=True) Iterations: 2
Test old_range(2, force=True) Iterations: 3

Test old_range(0, force=False) Iterations: 0
Test old_range(1, force=False) Iterations: 1
Test old_range(2, force=False) Iterations: 2

Test new_range(0, force=True) Iterations: 1
Test new_range(1, force=True) Iterations: 1
Test new_range(2, force=True) Iterations: 2

Test new_range(0, force=False) Iterations: 0
Test new_range(1, force=False) Iterations: 1
Test new_range(2, force=False) Iterations: 2 
```

What do you think? I can make a commit.

**Comment by Lonami** [comment]
This was discussed in https://t.me/TelethonChat/249687 briefly. The naming is a bit confusing but the parameter basically adds one more iteration for "there has to be at least one attempt". It is working as intended and would handle infinite retries.
