### ISSUE TITLE
Get channel comments

### ISSUE THREAD

**Issue by citcheese** [LonamiWebs/Telethon#1598]
Telegram recently added ability to comment on message in channel. Would be great to have method to get comments exposed in Telethon

**Comment by Lonami** [comment]
This is nothing but replies to a specific message, but I guess a filter for searching for these could be added to `iter_messages`.

**Comment by citcheese** [comment]
I may be missing something, but I'm using iter_messages method to get messages which I thought got _all_ messages in channel as per https://stackoverflow.com/posts/54278468, but instead I only get channel messages and not replies/discussion. Looking for method to get both.

**Comment by citcheese** [comment]
Right, but not seeing way to get **replies** by using iter_messages. Several posts on StackOverflow seems to indicate that iter_messages will pull _all_ chats (e.g. https://stackoverflow.com/posts/54278468/revisions), but when I use I only get channel messages (no replies) with following attr, (none of which list comment IDs etc):
'_', 'id', 'to_id', 'date', 'message', 'out', 'mentioned', 'media_unread', 'silent', 'post', 'from_scheduled', 'legacy', 'edit_hide', 'from_id', 'fwd_from', 'via_bot_id', 'reply_to_msg_id', 'media', 'reply_markup', 'entities', 'views', 'edit_date', 'post_author', 'grouped_id', 'restriction_reason'

**Comment by Lonami** [comment]
Note I said "a filter *could* be added". It doesn't exist yet. It can be done with raw API, just not the friendly method.

**Comment by citcheese** [comment]
ah ok, got it. Any guidance on how to get comments with raw API? at moment I'm screenscraping which works but is far from ideal.

**Comment by Lonami** [comment]
https://tl.telethon.dev/index.html?q=replies

**Comment by citcheese** [comment]
yup, first searched docs for replies method and found that, but as of Telethon v1.16.4 (which I believe is latest) there is no "GetRepliesRequest" request and so get following error when running example code on page you linked: AttributeError: module 'telethon.tl.functions.messages' has no attribute 'GetRepliesRequest'

**Comment by Lonami** [comment]
Yes, this currently needs to be done with the unreleased version in this repository.

**Comment by metiw** [comment]
Hello
How to send a comment to telegram posts using Telton?

**Comment by Lonami** [comment]
You send a message replying to the channel post in the linked group. For more questions please us the group or StackOverflow.

**Comment by floordiv** [comment]
> You send a message replying to the channel post in the linked group. For more questions please us the group or StackOverflow.

so, there is no way to comment posts without knowing linked chat/joining linked chat?

P.S. Sorry for asking here, but idk where is the group. Can you give me a link?

**Comment by ya1p** [comment]
Any ideas how to get the username of the comment sender?

**Comment by Bohdanloz** [comment]
> Any ideas how to get the username of the comment sender?

Have you got an answer?

**Comment by ya1p** [comment]
Привет! к сожалению пока не как :(

вс, 4 сент. 2022 г. в 00:45, Bogdan Lozynskyi ***@***.***>:
