### ISSUE TITLE
New method for saving Session

### ISSUE THREAD

**Issue by k1-hedayati** [LonamiWebs/Telethon#16]
Pickle is good for starting but not for long run, JSON is better for human readability, config file is good for centralized configuration and readability, sqlite db is good for future when storing more data is necessary, each has its pros and cons and best method for this project needs to be discussed.

**Comment by XyLoNaMiyX** [comment]
What about YAML, which is even more human readable if that's the purpouse? Hmm, though, there's some private data stored there. Pickle kind of hides that (I know, any Python program could read it — but it's definitely less accessible than plain JSON).

**Comment by k1-hedayati** [comment]
What is number of different sessions on a typical app and their change frequently?

**Comment by XyLoNaMiyX** [comment]
> What is number of different sessions on a typical app and their change frequently?

Official Telegram applications default to *one* single session. But this isn't necessarily the case, as #12.

**Comment by k1-hedayati** [comment]
I think having a sqlite db for storing sessions is good solution because it solves multi session issue without having to create file to each one, and if future you wanted to store more data like settings etc you won't have problems

**Comment by XyLoNaMiyX** [comment]
> I think having a sqlite db for storing sessions is good solution because it solves multi session issue without having to create file to each one

That's why people can implement their own version. They might want to use different databases or store different stuff, maybe even extend the session. That's up to them. The default implementation suits the basic needs.

> and if future you wanted to store more data like settings etc you won't have problems

Well, you would still need to do a database upgrade. Shouldn't be too hard, but it would have to be done.

**Comment by XyLoNaMiyX** [comment]
Closing this since you can use your own way for storing the `Session` unless you manage to convince me ;)

It would be (slightly) harder to use JSON because `auth_key` is 1. secret and 2. it's a bunch of bytes (yes, it's possible to base 64 encode them, but, this works).

**Comment by Lonami** [comment]
Well, [had to happen](https://github.com/LonamiWebs/Telethon/commit/49ca5c00c76f435e03a48509a0d930e16333d45c).
