### ISSUE TITLE
Add method

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#160]
Can u add the method to send __broadcast message__  to telethon methods?

https://core.telegram.org/method/messages.sendBroadcast
 

_Sent from my Samsung SM-G530FZ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lonami** [comment]
No, I can't, because it uses a very old scheme.

**Comment by seby2000** [comment]
So there is no way to call this method?

_Sent from my Samsung SM-G530FZ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lonami** [comment]
> So there is no way to call this method?

Well, there probably is a way. You can use a very old scheme and lose *a lot* of the new features just to have that method. On the other side, you could as well retrieve all dialogs and then `.send_message` to everyone.

**Comment by seby2000** [comment]
>
On the other side, you could as well retrieve all dialogs and then .send_message to everyone.
>
So it will does not go slower and in flood wait?

_Sent from my Samsung SM-G530FZ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lonami** [comment]
> So it will does not go slower

It's definitely slower than a bulk send. But you can **not** do that anymore. They probably removed it in favour of the "channels", and because it was spammy.

> and in flood wait?

Well depends to how many people you send it to, how fast you do it, and how often.

**Comment by seby2000** [comment]
Well in case this is not enough I just need to replace the tl code with an older one?

_Sent from my Samsung SM-G530FZ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lonami** [comment]
> I just need to replace the tl scheme with an older one? For use the old method

Yeah and run the code generator and probably change the `.connect()` method.

**Comment by seby2000** [comment]
Well, can i add only this line to schema.TL and run the code generator ?
`messages.sendBroadcast#41bb0972 contacts:Vector<InputUser> message:string media:InputMedia = messages.StatedMessages;`I dont know how the scheme.TL works, im just asking sorry if im shotting bullshit

**Comment by Lonami** [comment]
> can i add only this line to schema.TL and run the code generator

No, you cannot make up layers like that. The server would have no idea you just made that up.

**Comment by seby2000** [comment]
Ok got it

**Comment by seby2000** [comment]
I tried to change the scheme.tl with the last layer where sendbroadcast was implemented (layer 54) 
https://raw.githubusercontent.com/LonamiWebs/Telethon/7802fe5487404e3a97848f1ba9226d2c43dc2a54/scheme.tl

i got this error when run the code generator (i used last telethon version)

```
Generating TLObjects...
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    'telethon_generator/scheme.tl', import_depth=2
  File "C:\Users\seby\Desktop\new\Telethon\telethon_generator\tl_generator.py",
line 46, in generate_tlobjects
    tlobjects = tuple(TLParser.parse_file(scheme_file))
  File "C:\Users\seby\Desktop\new\Telethon\telethon_generator\parser\tl_parser.p
y", line 31, in parse_file
    yield TLObject.from_tl(line, is_function)
  File "C:\Users\seby\Desktop\new\Telethon\telethon_generator\parser\tl_object.p
y", line 88, in from_tl
    is_function=is_function)
  File "C:\Users\seby\Desktop\new\Telethon\telethon_generator\parser\tl_object.p
y", line 38, in __init__
    'Invalid inferred ID for ' + repr(self)
AssertionError: Invalid inferred ID for updates_tg#74ae4240 updates:Vector<Updat
e> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
```

**Comment by Lonami** [comment]
`updates` was renamed to `updates_tg` automatically so the assertion failed. You can just remove the assertion.

**Comment by seby2000** [comment]
ok it works. I have another problem when i do client.connect 
```
Traceback (most recent call last):
  File "C:\Users\seby\Desktop\new\Telethon\test.py", line 6, in <module>
    tg.connect()
  File "C:\Users\seby\Desktop\new\Telethon\telethon\telegram_client.py", line 140, in connect
    return super().connect()
  File "C:\Users\seby\Desktop\new\Telethon\telethon\telegram_bare_client.py", line 129, in connect
    query=query)
TypeError: __init__() got an unexpected keyword argument 'lang_pack'
```

**Comment by seby2000** [comment]
or when i run try_telethon 
```
Traceback (most recent call last):
  File "try_telethon.py", line 38, in <module>
    **kwargs)
  File "C:\Users\seby\Desktop\new\Telethon\telethon_examples\interactive_telegra
m_client.py", line 58, in __init__
    if not self.connect():
  File "C:\Users\seby\Desktop\new\Telethon\telethon\telegram_client.py", line 14
0, in connect
    return super().connect()
  File "C:\Users\seby\Desktop\new\Telethon\telethon\telegram_bare_client.py", li
ne 129, in connect
    query=query)
TypeError: __init__() got an unexpected keyword argument 'system_lang_code'
```

**Comment by Lonami** [comment]
Yeah because the `InitConnection` method across layers changed. You need to change that accordingly.

**Comment by seby2000** [comment]
ok. done. anything works but when i call the method 
```
Traceback (most recent call last):
  File "C:\Users\seby\Desktop\new\Telethon\test.py", line 33, in <module>
    res = tg.invoke(SendBroadcastRequest(contacts=[result, result2], message="test broadcast", random_id=[rnd1, rnd2], media=InputMediaEmpty()))
  File "C:\Users\seby\Desktop\new\Telethon\telethon\telegram_client.py", line 205, in invoke
    request, updates=updates
  File "C:\Users\seby\Desktop\new\Telethon\telethon\telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "C:\Users\seby\Desktop\new\Telethon\telethon\network\mtproto_sender.py", line 109, in receive
    remote_msg_id, remote_seq, reader, updates)
  File "C:\Users\seby\Desktop\new\Telethon\telethon\network\mtproto_sender.py", line 207, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "C:\Users\seby\Desktop\new\Telethon\telethon\network\mtproto_sender.py", line 355, in _handle_rpc_result
    raise error
telethon.errors.rpc_errors_400.InputMethodInvalidError: (InputMethodInvalidError(...), 'The invoked method does not exist anymore or has never existed.')
```

**Comment by Lonami** [comment]
`all_tlobjects.py` sixth line should say:
```python
layer = 54  # Current generated layer
```

Besides this it wouldn't surprise me if Telegram just had removed support for said method on every layer. I honestly think you would be better off by manually sending a message to every peer.

If you still want to try this, maybe try an even older layer? [This repository](https://github.com/stek29/tl-schema) is a great place to find all schemes.

**Comment by seby2000** [comment]
> all_tlobjects.py sixth line should say:
yes it says it

> If you still want to try this, maybe try an even older layer?

Why do you say this? How old should it be?

**Comment by Lonami** [comment]
> Why do you say this?

Telegram once updated a layer without changing the version (so some methods failed); I wouldn't be surprised if they did something similar and just removed an old method.

> How old should it be?

You're the only one who knows your needs.

**Comment by seby2000** [comment]
`res = tg.invoke(SendBroadcastRequest(contacts=[result, result2], message="test broadcast", random_id=[rnd1, rnd2], media=InputMediaEmpty()))`
Could I be wrong to set up the media parameter?

**Comment by Lonami** [comment]
No the error says `InputMethodInvalidError` i.e. the method you used (`SendBroadcast`) is not valid for said layer. I do not know why it isn't, if it belongs to said layer.

**Comment by seby2000** [comment]
i Anyway I just saw this fantastic method https://lonamiwebs.github.io/Telethon/methods/invoke_with_layer.html
Do you have any idea what to put in the query parameter?

**Comment by Lonami** [comment]
I don't know if that method will work besides when trying to [initialize a connection](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_bare_client.py#L121-L133).

> Do you have any idea what to put in the query parameter?

Yes, I do. It's right in the page you linked.

**Comment by seby2000** [comment]
`"A different MTProtoRequest must be supplied for this argument."`
This means`client.invoke(sendMessageRequest(args))` for example?

**Comment by Lonami** [comment]
Yes.
