### ISSUE TITLE
Inconsistent behaviour with SlowModeWaitError

### ISSUE THREAD

**Issue by painor** [LonamiWebs/Telethon#1600]
### The issue 
Currently when you try to send a message in a chat that has slowmode enabled the request will be added to _flood_waited_requests which only cares about the request `CONSTRUCTOR_ID` and not where it happened so all future `sendMessages `will raise `FloodWaitError `even if it's not correct (for example a different chat)

### Proposed solutions

- One solution would be to create a `_slow_enabled_requests `dict that holds both the chat id where it happened and the request and that will only sleep if the request happened in the specific chat. The drawback of this is that the admins can remove slowmode at any point and the data in the dict will be outdated.

- The other solution (which is better imo) is to just not add the request to any dict and just sleep or raise depending on the `flood_sleep_threshold` threshold.

**Comment by Lonami** [comment]
If we sleep based on threshold, slow mode could also be removed while sleeping. Practically though, how often would this happen? Maybe it's enough to store a tuple (request constructor, error type) as the key so that different error types don't interfere?

**Comment by painor** [comment]
with slowmode it's really weird. you could sleep for 60 sec but the admins would remove the slowmode after 5 seconds. This case doesn't happen so maybe adding a slow mode threshold is also a good idea. I don't think the normal floodwait error should be touched or changed.

**Comment by AKHACKER-program4hack** [comment]
I am using forward_message it not through the SlowModeWaitError 
how can i get if there is slowdown mode error come
i am not getting error so i cannot skip the loop it just wait for the slow down to finish i don't want that
any help
