### ISSUE TITLE
MessageEdited and MessageDeleted issues with channel discussion on

### ISSUE THREAD

**Issue by AndreaHasani** [LonamiWebs/Telethon#1601]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

I do not receive any event for MessageEdited and MessageDeleted if the channel I'm listening to has channel discussion on.

**Comment by Lonami** [comment]
Reason for closing?
