### ISSUE TITLE
ChannelParticiantAdmin filter in get/iter_participant()

### ISSUE THREAD

**Issue by Volosatiyslon** [LonamiWebs/Telethon#1604]
**Code that causes the issue**
```python
from telethon.sync import TelegramClient
from telethon.tl import functions, types

client = TelegramClient()
group_id = 36xxx75
must_be_admins = await client.client.get_participants(entity=group_id, filter=types.ChatParticipantAdmins)
users = await client.client.get_participants(entity=group_id)
print (must_be_admins == users)

```
Output:
```
True
```

I have a group, with 1 admins and 2 users. When I try to use get/iter_participants with and without filtering I got same list of whole group users.

**Comment by Volosatiyslon** [comment]
I try this on groups and "mega" groups

**Comment by Lonami** [comment]
Filters only work on channels sadly, but I guess client side filtering could be made.

**Comment by Volosatiyslon** [comment]
how to recognize admins on client side?

**Comment by Volosatiyslon** [comment]
I find!!
in result of get_participiant 
in fullchat.participants.participants API sent a type of paticipant (owner, admin and so on)
