### ISSUE TITLE
How to know the meaning of API properties

### ISSUE THREAD

**Issue by amir3code** [LonamiWebs/Telethon#161]
Hello Lonami,
Im having a great time with your work! You've done it perfect!
But I had an issue of joining groups and private channels with their `joinchat` link and could not find any `join by link` or similar classes until I hit the wiki ....
The API written by you is great (https://lonamiwebs.github.io/Telethon/) but it would be much better if you provided some details about each of the methods and types and constructors, And for example what `InvokeWithLayerRequest` means and can do ...

**Comment by Lonami** [comment]
> but it would be much better if you provided some details about each of the methods and types and constructors

Yes, but that is a *huge* work, which I am not willing to do, sorry. This is why I decided to open a wiki, to address most people's concerns. Needless to say, the API changes with each new layer released, more things are added, and more work to do.

When someone doesn't know what to do and if I consider it's something not obvious at first, I will open another wiki page for it so people doesn't ask the same questions.

Also, although I've done this project to *interact* with the API, I don't know 100% how to *work* with the API, I still have to look around and experiment, which anyone can do.
