### ISSUE TITLE
Why the input_entity and entity I got from private group link be not same

### ISSUE THREAD

**Issue by BwayCer** [LonamiWebs/Telethon#1610]
```python
peer = 'https://t.me/joinchat/SZQR6xf4CKmhNF9XRG1v-A' # is demo link, not real

print(await client.get_entity(peer))
# Channel(id=1466768701, access_hash=6424431049980945030, megagroup=True, ...)

print(await client.get_input_entity(peer))
# InputPeerChat(chat_id=402131113)
```

When using `InviteToChannelRequest` method, `entity` is success and `input_entity` is fails.

**Comment by Lonami** [comment]
The link was probably generated before the `Chat` was upgraded to a `Channel` `megagroup`. `get_input_entity` uses cache and it thinks it refers to the old `Chat`. This is documented and intended. Generate and use a new link for it to be detected correctly.
