### ISSUE TITLE
Investigate reverse get messages with offset date

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1611]
#1606

**Comment by Lonami** [comment]
I'm pretty sure this used to work but perhaps the server changed some things. The request being sent is:

```python
SearchRequest(
	peer=...,
	q='',
	filter=InputMessagesFilterEmpty(
	),
	min_date=None,
	max_date=datetime.datetime(2020, 11, 1, 12, 0),
	offset_id=0,
	add_offset=-100,
	limit=0,
	max_id=0,
	min_id=0,
	hash=0,
	from_id=None,
	top_msg_id=None
)
```

It seems Telegram does not like the negative `add_offset` anymore. Fixing this won't be easy because there's a lot of ways in which filters can interact with each other, so it's not as simple as just trying to use `min_date`. A workaround could be made so that 1 request is made to determine the limitting message ID, and then work in reverse from there, but this can be done from outside the library too.

Anyone is free to come up with a solution with raw API that can be adapted into Telethon, or maybe even checking how Telegram Desktop does it with `debugmode` enabled so that Telethon can follow the same approach.

cc @igerzog.

**Comment by igerzog** [comment]
Have just returned to this issue and found the request working like a charm. As to [messages.getHistory](https://core.telegram.org/method/messages.getHistory) negative values are also accepted in `add_offset`. Could be a longtime temporary bug that is now fixed.

**Comment by Lonami** [comment]
So `iter_messages` with `reveverse` works fine now?

**Comment by igerzog** [comment]
Yep, no more problems found.
