### ISSUE TITLE
How to know if a link is for a group or a channel

### ISSUE THREAD

**Issue by amir3code** [LonamiWebs/Telethon#162]
For example links like `https://t.me/joinchat/AAAAAFFszQPyPEZ7wgxLtd` can belong to either a channel or a group.
Which method can I use to request the type of it?
In TG desktop I am seeing that its possible, how it is with Telethon?
Can I use links like `https://t.me/mychannelid` in that request, does it support these kind of links too (as I saw that recently telegram added the option for supergroups to set public links for them like channels can have)?

**Comment by amir3code** [comment]
I found a way through `CheckChatInviteRequest`

>from telethon.tl.functions.messages import CheckChatInviteRequest

https://lonamiwebs.github.io/Telethon/methods/messages/check_chat_invite.html

**Comment by aen516954023** [comment]
> 我找到了一种方法 `CheckChatInviteRequest`
> 
> > 从telethon.tl.functions.messages导入CheckChatInviteRequest
> 
> https://lonamiwebs.github.io/Telethon/methods/messages/check_chat_invite.html

CheckChatInviteRequest 这个参数中的hash是从哪里获取到的？
