### ISSUE TITLE
entities

### ISSUE THREAD

**Issue by ahmdjhnel1** [LonamiWebs/Telethon#1624]
hello
i have a problem with entites when emoji is in text.

it is my text : 

![image](https://user-images.githubusercontent.com/19515276/98466666-2d3b7c80-21e6-11eb-9ab4-d2bed80c5538.png)

and it is my entities event:

`entities=[
                        MessageEntityMention(
                                length=13,
                                offset=49
                        ),
                ]`
and my code :

![image](https://user-images.githubusercontent.com/19515276/98466768-d4201880-21e6-11eb-9944-d5ecff17ceee.png)

This should change the ID(@fdgdfgdfgfdg) to @example, but it does not. The problem is due to the emojis. It works fine when I delete the emojis.

what should I do?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
