### ISSUE TITLE
When send message get this error: telethon.errors.rpcerrorlist.MessageTooLongError

### ISSUE THREAD

**Issue by kakkarja** [LonamiWebs/Telethon#1625]
Hi, I have an issue sending message that is too long.

```(<class 'telethon.errors.rpcerrorlist.MessageTooLongError'>, MessageTooLongError('Message was too long. Current maximum length is 4096 UTF-8 characters (caused by SendMessageRequest)'), <traceback object at 0x0000021DC2A25E40>)```

Is there anyway to  maximize the length of characters? Thank you in advance 🙏

**Comment by Lonami** [comment]
No, you have to send multiple messages. You can ask how to split messages in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat) if you can't find it in the documentation.
