### ISSUE TITLE
how to check if client instance is logged in?

### ISSUE THREAD

**Issue by hamid814** [LonamiWebs/Telethon#1626]
I am trying to log the user into the account using the telegram bot API, and I can't find a way to check if the client instance has access to an account...

this is my instance:
```
client = TelegramClient(client_name, API_ID, API_HASH)
```

by using client.start() it detects if the user is logged in or not, so I must have access to that too...

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
