### ISSUE TITLE
Add support for the new slot machine `dice`

### ISSUE THREAD

**Issue by MrSnowball-dev** [LonamiWebs/Telethon#1628]
It's not feature request as is, but I noticed that the new 🎰 emoji doesn't get recognized as `dice` object in `message` friendly method.
I have a trigger on `dice` in my script, so I'd like Telethon to support it as well.

It has the same properties as any other dice, besides value ranges from 1 to 64.
I didn't find it in code to fix it myself, maybe someone should check this out? Maybe even make a friendly method on deciphering what exactly have been rolled on the slot machine (the formula is simple):
```
cd = {
    0: "Bar",
    1: "Cherry",
    2: "Lemon",
    3: "7"
}
def convert(n):
    n -= 1
    return cd[n%4] + cd[n//4%4] + cd[n//16]
```

**Comment by Lonami** [comment]
I cannot reproduce this issue with the latest `master` version (acd4c8648e18e0888437b5de615f1cc5c9da6d59). Please let me know if this is still an issue and I will reopen.
