### ISSUE TITLE
Get/Set folders for dialogs

### ISSUE THREAD

**Issue by mkellerman** [LonamiWebs/Telethon#1630]
Please add a feature to get/set the list of folders, ans add/remove dialogs from those folders.

**Comment by Lonami** [comment]
`client.edit_folder` already does the second thing you request.

**Comment by mkellerman** [comment]
It seems to provide if the dialog is 'archived', but not custom folders. Can someone confirm?

**Comment by Lonami** [comment]
Folders other than archived should just be different numbers.

**Comment by mkellerman** [comment]
I've just verified, and folder_id only provides null or 1, depending if it's 'archived' or not. no other folders id is provided.

**Comment by Lonami** [comment]
Other folder IDs should work just fine. I encourage you to create them with an official client and then check their value in Telethon to find out how other clients assign the IDs.

**Comment by mkellerman** [comment]
I have. I created folders in the telegram app on iOS, and put some dialogs in there and they show as null in folder_id.

**Comment by Lonami** [comment]
That really shouldn't be the case, perhaps `iter_dialogs` is acting up. Have you tried using the raw API method `getDialogs` (https://tl.telethon.dev) directly?

**Comment by mkellerman** [comment]
I wish I could help you investigate the issue more, but I barely know what I'm doing.

this is the implementation I'm using to get the dialogs.. and it returns null in the folder_id (except those that are archived, which returns 1):

```python
client.start()
async def main():
    async for dialog in client.iter_dialogs():
```

**Comment by mkellerman** [comment]
I've confirmed that using the GetDialogsRequest() is providing None as a folder_id except those that are Archived.

code used:
```
client = TelegramClient(StringSession(SessionId), api_id, api_hash)
async def main():

    results = await client(functions.messages.GetDialogsRequest(offset_date=None,
                    offset_id=0,
                    offset_peer=types.InputPeerEmpty(),
                    limit=100,
                    hash=0))
    for dialog in results.dialogs:
        print(dialog.folder_id)

with client:
    client.loop.run_until_complete(main())
```

results:
```
None
None
None
None
None
None
None
1
1
None
```

**Comment by Lonami** [comment]
So now we're using raw API and Telegram is directly telling us that those dialogs have no folder -- here Telethon can't change the results or go wrong, as you're talking with Telegram. Not sure then, maybe there's another way for different folders.

**Comment by mkellerman** [comment]
I'm basically learning python from scratch to be able to debug and dig into this issue.. lol.. but I'm trying!  ¯\_(ツ)_/¯

**Comment by goodwind** [comment]
So I have managed to get list of all folders and included\excluded chats in it:

```
async def main():

    request = await client(functions.messages.GetDialogFiltersRequest())
    for dialog_filter in request:
        print(dialog_filter.to_dict())

with client:
    client.loop.run_until_complete(main())
```

**Comment by Skovorp** [comment]
Nice, but can i add dialogs to folders? 
client.edit_folder with id from GetDialogFiltersRequest doesn't work

**Comment by Skovorp** [comment]
Sorry for messy code but seems like I got it. Seems like client.edit_folder works with [peer folders](https://core.telegram.org/api/folders#peer-folders) which work only with archived chats. So with those you cant work with actual folders that you can see in your regular client. 

In order to do that you need to use DialogFilters and update those with UpdateDialogFilterRequest

```
from telethon.sessions import StringSession
from telethon.sync import TelegramClient
from telethon.tl.functions.messages import GetDialogFiltersRequest
from telethon.tl.functions.messages import UpdateDialogFilterRequest
from telethon.tl.types import InputPeerUser


async def main():
    request = await client(GetDialogFiltersRequest())
    for dialog_filter in request:
        print(dialog_filter.to_dict())
    return request


async def update(folder_id, new):
    request = await client(UpdateDialogFilterRequest(folder_id, new))
    print(request)


with TelegramClient(StringSession(session_string), api_id, api_hash) as client:
    t = client.loop.run_until_complete(main())[0] # here i get DialogFilter
    print(type(t.include_peers), t.include_peers)
    entity = client.get_entity('Sposiboh')
    print(type(entity), entity)

    to_add = InputPeerUser(entity.id, entity.access_hash) # i get user entity and convert it to PeerUser
    
    t.include_peers.append(to_add) # i add to_add to the list of other users in DialogFilter
    client.loop.run_until_complete(update(162, t)) # 162 is folder id that i got from GetDialogFiltersRequest
    print('ok')
```

**Comment by fox22432** [comment]
Skovorp's code helped a lot in understanding how to work with folders.

But I'm also very interested in method for creating and editing folders (DialogFilters?)

As of now, I have to create them in official client and then search using GetDialogFiltersRequest method, comparing the name with the one I've chosen.

**Comment by fox22432** [comment]
It turns out you CAN both create and delete Folders using the UpdateDialogFilterRequest method.
The way you do it is described nicely in official api docs: https://core.telegram.org/api/folders
Basically, to create a folder, you pass a new integer as "id" parameter, and types.DialogFilter object as "filter". New id does not have to be in sequential order.
To delete a folder, simply pass None as "filter".

**Comment by bibinvargheset** [comment]
> Sorry for messy code but seems like I got it. Seems like client.edit_folder works with [peer folders](https://core.telegram.org/api/folders#peer-folders) which work only with archived chats. So with those you cant work with actual folders that you can see in your regular client.
> 
> In order to do that you need to use DialogFilters and update those with UpdateDialogFilterRequest
> 
> ```
> from telethon.sessions import StringSession
> from telethon.sync import TelegramClient
> from telethon.tl.functions.messages import GetDialogFiltersRequest
> from telethon.tl.functions.messages import UpdateDialogFilterRequest
> from telethon.tl.types import InputPeerUser
> 
> 
> async def main():
>     request = await client(GetDialogFiltersRequest())
>     for dialog_filter in request:
>         print(dialog_filter.to_dict())
>     return request
> 
> 
> async def update(folder_id, new):
>     request = await client(UpdateDialogFilterRequest(folder_id, new))
>     print(request)
> 
> 
> with TelegramClient(StringSession(session_string), api_id, api_hash) as client:
>     t = client.loop.run_until_complete(main())[0] # here i get DialogFilter
>     print(type(t.include_peers), t.include_peers)
>     entity = client.get_entity('Sposiboh')
>     print(type(entity), entity)
> 
>     to_add = InputPeerUser(entity.id, entity.access_hash) # i get user entity and convert it to PeerUser
>     
>     t.include_peers.append(to_add) # i add to_add to the list of other users in DialogFilter
>     client.loop.run_until_complete(update(162, t)) # 162 is folder id that i got from GetDialogFiltersRequest
>     print('ok')
> ```

The addition gives a true and prints ok but the chat is not added to folder

**Comment by Lonami** [comment]
This is unlikely to happen in the near future so I will be closing the issue. We can reopen it if there's still interest once the time is right.

**Comment by aryashivakumar** [comment]
I'm interested in using this feature, and do believe it should be an official part of the documentation

**Comment by Orkoliator** [comment]
One more update just for future.

As long as UpdateDialogFilterRequest is not described well I would like to share my working example.
Biggest trouble I get in is to understand what DialogFilter expects as include_peers. It is not a list of object IDs, it should be a list of InputPeerChannel or InputPeerChat objects (or both), that can be received with get_input_entity(id_of_entity) method.

So here is my example that checks groups and supergroups and adds multiple groups to folders:

```
from telethon import TelegramClient
from telethon.tl.functions.messages import GetDialogFiltersRequest, UpdateDialogFilterRequest
from telethon.tl.types import DialogFilter
from yaml import safe_load

tg_peers = {
    'channels': [],
    'megagroups': [],
    'gigagroups': [],
    'groups': []
}

with open('api_parameters.yaml', 'r') as config:
    session_data = safe_load(config)
    session_name = session_data['session_name']
    api_id = session_data['api_id']
    api_hash = session_data['api_hash']
    group_folder_name = session_data['group_folder_name']
    supergroup_folder_name = session_data['supergroup_folder_name']
    channel_folder_name = session_data['channel_folder_name']

client = TelegramClient(session_name, api_id, api_hash)
client.start()

async def main():
    async for dialog in client.iter_dialogs():
        if dialog.is_channel:
            data = await client.get_entity(dialog.id)
            if data.broadcast:
                tg_peers['channels'].append(await client.get_input_entity(data.id))
            elif data.megagroup:
                tg_peers['megagroups'].append(await client.get_input_entity(data.id))
            elif data.gigagroup:
                tg_peers['gigagroups'].append(await client.get_input_entity(data.id))
            else:
                print(f'{data.title} type cannot be identified')
        elif dialog.is_group and not dialog.is_channel:
            data = await client.get_entity(dialog.id)
            tg_peers['groups'].append(await client.get_input_entity(data.id))

async def updateFilter(folder_id, folder_title, peers):
    await client(UpdateDialogFilterRequest(
        id=folder_id,
        filter=DialogFilter(
            id=folder_id,
            title=folder_title,
            pinned_peers=[],
            exclude_peers=[],
            include_peers=peers,
            contacts=False,
            non_contacts=False,
            groups=False,
            broadcasts=False,
            bots=False
        )
    ))

async def modifyFilter(tg_peers):
    request = await client(GetDialogFiltersRequest())
    for dialog_filter in request.filters[1:]:
        if dialog_filter.title == group_folder_name:
            await updateFilter(dialog_filter.id, group_folder_name, tg_peers['groups'])
        elif dialog_filter.title == supergroup_folder_name:
            await updateFilter(dialog_filter.id, supergroup_folder_name, tg_peers['megagroups']+tg_peers['gigagroups'])
        elif dialog_filter.title == channel_folder_name:
            await updateFilter(dialog_filter.id, channel_folder_name, tg_peers['channels'])

with client:
    client.loop.run_until_complete(main())
    client.loop.run_until_complete(modifyFilter(tg_peers))
    print('done')
```

**Comment by pwnInt** [comment]
Wrote this demo, it's able to fetch Channel ID in the folder.
```
import asyncio
from telethon import TelegramClient
from telethon.tl import functions

async def main():
    async with TelegramClient('session_name', API_ID, API_HASH) as client:
        folders = await client(functions.messages.GetDialogFiltersRequest())
        for folder in folders.filters:
            if hasattr(folder, 'title'):
                print(folder.stringify())
                print()

if __name__ == "__main__":
    asyncio.run(main())
```
