### ISSUE TITLE
MediaCaptionTooLongError

### ISSUE THREAD

**Issue by j4hangir** [LonamiWebs/Telethon#1631]
It seems that the limitation of 200 has been lifted long now by Telegram, as it's possible to send photos with very long captions, but Telethon still throws the aforementioned error.

**Comment by Lonami** [comment]
The library never (at the time of writing) constructs said error itself (see 0 matches for https://github.com/LonamiWebs/Telethon/search?q=MediaCaptionTooLongError). This means the error comes from Telegram, and thus there's nothing to fix.

**Comment by j4hangir** [comment]
Something must be off, seems suspicious that this error only occurs with Telethon and not when writing a caption with other clients...

**Comment by Lonami** [comment]
Telegram may be using the layer number being used to determine what to support, though this seems like an odd resrriction to apply to older clients.
