### ISSUE TITLE
error when try to send photo by a bot user

### ISSUE THREAD

**Issue by hamid814** [LonamiWebs/Telethon#1633]
I need to send a photo that already exists on telegram servers with a bot using telethon, but telethon returns this error:

```
The provided media object is invalid or the current account may not be able to send it (such as games as users) (caused by SendMediaRequest)

```

the telegram bots are able to do so, I have used the same bot, in nodejs ( and telegrafjs ) to do such a thing, I know telegram allows bots to send photos and other types of media

and here is the official telegram docs for this: https://core.telegram.org/bots/api#sendphoto

I use this code for bot initialize and send a message:
```python bot = TelegramClient(bot_name, API_ID, API_HASH)

bot.start(bot_token=BOT_TOKEN)

# this part is in am async function
bot.send_message(destination_id, message)
```

and here is the message ( its constructed by telethon itself ):
```
Message(id=1077, to_id=PeerChannel(channel_id=1262793861), date=datetime.datetime(2020, 11, 15, 22, 42, 21, tzinfo=datetime.timezone.utc), message='ggg', out=True, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, media=MessageMediaPhoto(photo=Photo(id=5013054612525131926, access_hash=7495255942825644027, file_reference=b'\x04KD\xb4\x85\x00\x00\x045_\xb1\xae\xcdb\xf6-\xbdRe\x8d\x95\xecl\x00g\xd0N\x04*', date=datetime.datetime(2020, 11, 15, 22, 42, 21, tzinfo=datetime.timezone.utc), sizes=[PhotoStrippedSize(type='i', bytes=b'\x01\x17({^\xb8\xe8\x82\x83q9\xe8\xb8\x1e\xb8\xac\xe9ZO;\x86\n\x07L\x9a\xbb\x0c\xe6y\n\x92v\xe0\x1c\x8e\xe7\x02\xa1E\xb3F\xd1p9 \x1c\xd3X\x93RF\x9b\xa3S\x9e\xa2\x86\x8f\x83\xcd_+&\xe8\xaeM\x14\x8ch\xa2\xc1r\xa6\xa9\x08B\x8c\xbd1\x8f\xca\xa7\x86\r\x91\xa9$g`\xe8:QEib.Yi\x04q\x96$\x80\xa3<V\x1c\xf34\xd2\x17by<\x0fJ(\xa0\x07\xdb\xdc\xb4$n\xf9\x93\xb84QE+\x81'), PhotoSize(type='m', location=FileLocationToBeDeprecated(volume_id=806528141, local_id=255612), w=320, h=180, size=11276), PhotoSize(type='x', location=FileLocationToBeDeprecated(volume_id=806528141, local_id=255613), w=800, h=449, size=37459), PhotoSize(type='y', location=FileLocationToBeDeprecated(volume_id=806528141, local_id=255610), w=1280, h=719, size=69452)], dc_id=1, has_stickers=False, video_sizes=[]), ttl_seconds=None), reply_markup=None, entities=[], views=1, edit_date=None, post_author=None, grouped_id=None, restriction_reason=[])
```

and I user telethon ```v 1.16.4```

**Comment by Lonami** [comment]
Your version of the library is out of date. The error is incomplete, and the code posted is not enough to help troubleshoot the issue.

Closing under the assumption `message` was obtained by a different account, so its access hash cannot be used by the bot (hence media invalid).

If you have more information along with an example I can run to verify the issue post it here and I'll reopen.

**Comment by hamid814** [comment]
in the long run, my problem is that I cant access the file_id in the message.

**Comment by Lonami** [comment]
In that case, your issue is #1613.

**Comment by HosseyNJF** [comment]
> Closing under the assumption `message` was obtained by a different account, so its access hash cannot be used by the bot (hence media invalid).

@Lonami Is it possible to obtain the needed access hash to make the bot able to send files uploaded by other people? (Assuming you have access to the account who uploaded the file via telethon)

**Comment by Lonami** [comment]
Hi, the issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by radiaku** [comment]
Sori opening old thread. But I found this message too recently. In my case the culprit was, if I use bot not user. Cause bot limited by 2gb media . So I assume bot is limited by 2g file. ( user are not ).


```
 if "MessageMediaUnsupported()" in str(event.message.media):
    # Error The provided media object is invalid or the current account may not be able
    # to send it (such as games as users) (caused by SendMediaRequest)
    print("MessageMediaUnsupported(), bot cannot send file more than 2g")
else:
    await client.send_message(idmessage, event.message)
    await asyncio.sleep(2)
status_sending = False
```

**Comment by sobkiso** [comment]
[Cc checker bot ](https://redccshop.mysellix.io/product/xchkrobot-source-code)
