### ISSUE TITLE
How do I know if the download failed

### ISSUE THREAD

**Issue by hyahm** [LonamiWebs/Telethon#1635]
Due to various other reasons, the download failed, but the error information could not be retrieved
``` 
client.download_media(event.message, file=newfilename)
```

**Comment by Lonami** [comment]
How do you know it failed if there is no error, then?

**Comment by hyahm** [comment]
no error

**Comment by Lonami** [comment]
So if there is no error, then it worked fine or the code didn't even run at all. Does `download_media` return `None`?

**Comment by hyahm** [comment]
I'll print out the value

**Comment by hyahm** [comment]
nothing return

**Comment by Lonami** [comment]
"Nothing return" means it returned `None`, or that it never returned anything? Please configure `logging` and see if there's any unhandled error.

**Comment by hyahm** [comment]
Always waiting for the return value

**Comment by Lonami** [comment]
Did you configure `logging` to show errors?

**Comment by hyahm** [comment]
I've been stuck in this business   `ok = await client.download_media(event.message, file=newfilename)`

**Comment by Lonami** [comment]
Please answer my question, or we won't get anywhere with this.

**Comment by hyahm** [comment]
Many groups send a lot of videos, and download more than 30 at a time. I now have a service monitoring a group. There is another problem:

`@ client.on ( events.MessageEdited ）
async def my_event_handler(event):`
How can events listen to message edited and newmessage at the same time

**Comment by Lonami** [comment]
Closing since you're not providing enough information and I believe there's no bug here.
