### ISSUE TITLE
Difference between "client.on(events.NewMessage())" and "events.register(events.NewMessage())"

### ISSUE THREAD

**Issue by ikarlmarx** [LonamiWebs/Telethon#1636]
what is the difference between "client.on(events.NewMessage())" and "events.register(events.NewMessage())"？

I tried both of them and   got different result.  And  event handler should be diffenent too.

Also,  if I want to get messages from the selected channel, "events.register(events.NewMessage(CHANNEL))"  works, but "client.on(events.NewMessage(CHANNEL))" does not work.  (CHANNEL="t.me/xxx")

I am very confused.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
