### ISSUE TITLE
Some confusion!!!

### ISSUE THREAD

**Issue by WaWaKing** [LonamiWebs/Telethon#1638]
How to get the channel links?????? (when i'm alreay join channel!)

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
