### ISSUE TITLE
Is it possible to read contents of a message

### ISSUE THREAD

**Issue by dylankilkenny** [LonamiWebs/Telethon#164]
Ive used [ReadMessageContentsRequest](https://lonamiwebs.github.io/Telethon/methods/messages/read_message_contents.html) which returned `{AffectedMessages: {pts_count: 0, pts: 1310}}`but im not actually sure how to read the actual message text, is this possible?

**Comment by Lonami** [comment]
What are you trying to do? Getting the message history? I mean, a [`Message`](https://lonamiwebs.github.io/Telethon/constructors/message.html) has the `.message` string which is well, the contents of the message itself.
