### ISSUE TITLE
UserWarning: The sqlite3 module is not available under this Python installation.

### ISSUE THREAD

**Issue by wajihmsedi** [LonamiWebs/Telethon#1640]
Hello , 

I have created a telegram project in pycharm.
It runs like a charm there.
The same program in the cmd triggers the following error :

C:\Users\User\anaconda3\envs\env_kraken\lib\site-packages\telethon\client\telegrambaseclient.py:268: UserWarning: The sqlite3 module is not available under this Python installation and no custom session instance was given; using MemorySession.
You will need to re-login every time unless you use another session storage
  'The sqlite3 module is not available under this '

Any idea what is the root cause of the problem ?

Wajih

**Comment by Lonami** [comment]
Unfortunately this seems to be an issue with your installation (you should verify that `import sqlite3` fails in your code, if it doesn't then it is a bug in Telethon), so there is nothing to fix here. 

If you have more questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
