### ISSUE TITLE
Channel entity with field for inline comments

### ISSUE THREAD

**Issue by mawic** [LonamiWebs/Telethon#1641]
Is there a way to figure out based on the channel entity whether a channel has activated the inline comment feature?

If not, this would be a nice feature.

**Comment by Lonami** [comment]
How should this be implemented? It's accessible via raw API, getting the full channel.

**Comment by mawic** [comment]
A flag in GetFullChannelRequest would be great (e.g., inline_comments True/False).

**Comment by Lonami** [comment]
GetFullChannelRequest is a raw API call, and invoking it returns a ChannelFull which has this information already available. The question is how would you like to see this in a friendly method.

**Comment by mawic** [comment]
I was not aware that linked chat means that it allows incline comments. Then, I do not request another feature.
Thanks for the help!
