### ISSUE TITLE
Support group voice chat creation

### ISSUE THREAD

**Issue by alexunix** [LonamiWebs/Telethon#1645]
Recently I've been playing with 7.3 ios telegram beta, and group voice calls are very nice feature!
![](https://i.imgur.com/rtjAP8J.png)
Could the api to create one be implemented in telethon?

**Comment by Lonami** [comment]
There will be a way to interact with these soon, after the `api.tl` layer file is updated. There are no plans for Telethon to directly stream incoming or outgoing audio though, since that most likely requires C, it belongs in a helper library.

**Comment by Lonami** [comment]
This is now possible with raw API methods like `functions.phone.CreateGroupCall(channel)`.

**Comment by bodrych** [comment]
@Lonami can you please provide some examples?

**Comment by Lonami** [comment]
The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
