### ISSUE TITLE
Follower History over Time?

### ISSUE THREAD

**Issue by kiliganz** [LonamiWebs/Telethon#1648]
Is there any possibility to get the amount of followers of a channel for a certain day. E.g. i want to analyse the growth of a channel and need to extract the followers for every day in the past 60 days?

from telethon import client
from telethon.sync import TelegramClient
from telethon.tl.functions.channels import GetFullChannelRequest

client = TelegramClient('session_name', api_id, api_hash)
client.connect()

channel_connect = self.client.get_entity(channel_name)
channel_full_info = client(GetFullChannelRequest(channel=channel_connect))
print(channel_full_info.full_chat.participants_count)`

_Originally posted by @leexxg in https://github.com/LonamiWebs/Telethon/issues/597#issuecomment-505418593_

Thanks in advance
Kili

**Comment by Lonami** [comment]
There's a method to [`get_stats`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.chats.ChatMethods.get_stats) of a channel.
