### ISSUE TITLE
thumbnail of videos

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#165]
Hi,

How I can download the thumbnail of a video. in media.document.thumb there is no access_hash or id or version.

thanks

**Comment by Lonami** [comment]
[`Document`](https://lonamiwebs.github.io/Telethon/constructors/document.html) has a `.thumb` attribute.

**Comment by hnikaein** [comment]
I see that and I mentioned it in my post. But how I can use it? there is no access_hash in it

**Comment by Lonami** [comment]
Well the thumb is a [`PhotoSize`](https://lonamiwebs.github.io/Telethon/types/photo_size.html), and if it's 
[cached](https://lonamiwebs.github.io/Telethon/constructors/photo_cached_size.html) or simply [non-empty](https://lonamiwebs.github.io/Telethon/constructors/photo_size.html) it has a nice `.location` attribute. Surprisingly [there's a method](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_bare_client.py) that downloads just that. You're not going through the docs as you should.

**Comment by mamdosein97** [comment]
Excuse me for asking too questions. Suppose this is the "Message" attribute of an event:

"
Message(out=False, mentioned=False, media_unread=False, silent=False, post=True, id=671, from_id=None, to_id=PeerChannel(channel_id=1317394263), fwd_from=MessageFwdHeader(from_id=None, date=datetime.utcfromtimestamp(1520405822), channel_id=1317394263, channel_post=667, post_author=None, saved_from_peer=None, saved_from_msg_id=None), via_bot_id=None, reply_to_msg_id=None, date=datetime.utcfromtimestamp(1520405908), message='', media=MessageMediaDocument(document=Document(id=902611042524201454, access_hash=3639200755566245880, date=datetime.utcfromtimestamp(1479579559), mime_type='video/mp4', size=167993, thumb=PhotoSize(type='s', location=FileLocation(dc_id=4, volume_id=428631960, local_id=7795, secret=6970056650337343238), w=90, h=62, size=1944), dc_id=4, version=0, attributes=[DocumentAttributeVideo(round_message=False, duration=6, w=320, h=220), DocumentAttributeFilename(file_name='animation.gif.mp4'), DocumentAttributeAnimated()]), caption=None, ttl_seconds=None), reply_markup=None, entities=[], views=1, edit_date=None, post_author=None, grouped_id=None)
" 

would you please tell me or write a piece of code that can download the thumbnail of the video?

**Comment by mamdosein97** [comment]
i see the .thumb and .location but i can't work with it

**Comment by Lonami** [comment]
"Can't work with it"?

**Comment by mamdosein97** [comment]
I mean that i don't know how to work with it. I don't know how to download the thumbnail of video.

**Comment by Lonami** [comment]
#669.

**Comment by mamdosein97** [comment]
:)
it is not like photos!
ok if you know how please tell me how :(

**Comment by Lonami** [comment]
@mamdosein97 it says how in the linked issue. Thumbnails are just photos.

**Comment by MldHmt** [comment]
Hello
Which version of telethon are you using?

**Comment by snowman** [comment]
```python
client.download_media(message, thumb=-1)
```

**Comment by david-botelho-mariano** [comment]
> ```python
> client.download_media(message, thumb=-1)
> ```

the unique solution that worked, thanks!
