### ISSUE TITLE
wait_time unit in iter_message doesn't slow down request

### ISSUE THREAD

**Issue by Volosatiyslon** [LonamiWebs/Telethon#1652]
code
```
start_time = time.monotonic()
resp = takeout.iter_messages(chat_name, ids=[i for i in range(message_id-2, message_id+3)], wait_time=5.0)
async for m in resp:
    if m:
        messages_raw.append({"chat": m.chat, "sender": m.sender, "message": m})
end_time = time.monotonic()
print(end_time-start_time/1000)
```

```
start_time = time.monotonic()
resp = await takeout.get_messages(chat_name, ids=[i for i in range(message_id-2, message_id+3)], wait_time=5.0)
for m in resp:
    if m:
        messages_raw.append({"chat": m.chat, "sender": m.sender, "message": m})
end_time = time.monotonic()
print(end_time-start_time/1000)
```
this code parts always take about 1,5-2 seconds, despite wait_time parameter. Also, if I set logging level to debug I saw MsgAck API call for each ID I requests.

In summary I got floodwait error despite I call get_/iter_messages once in 30-40 seconds (with or without joining to channel)

**Comment by Volosatiyslon** [comment]
may be I didn't understand wait_time correctly, but I wait that each msg will be requested with sleep time from wait_time

**Comment by Lonami** [comment]
`wait_time` waits between `getHistory` requests, which is every 100 messages. I believe it's ignored if you use `ids=`.

**Comment by Volosatiyslon** [comment]
Hmm. Okay.
