### ISSUE TITLE
AttributeError: 'PhotoPathSize' object has no attribute 'size'

### ISSUE THREAD

**Issue by Soberia** [LonamiWebs/Telethon#1655]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

I think SVG thumbnails is useless in Telethon and implementing it is waste of time

<details><summary><strong>Code that causes the issue</strong></summary>

```python
import asyncio

from telethon import TelegramClient


async def main():
    async with TelegramClient(...) as client:
        async for message in client.iter_messages('telegram', ids=65):
            await client.download_media(message, thumb=0)


asyncio.run(main())
```

</details>

<details><summary><strong>Traceback</strong></summary>

```
Traceback (most recent call last):
  File "/*/.dev/test.py", line 12, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/*/.dev/test.py", line 9, in main
    await client.download_media(message, thumb=0)
  File "/*/.dev/venv/lib/python3.9/site-packages/telethon/client/downloads.py", line 397, in download_media
    return await self._download_document(
  File "/*/.dev/venv/lib/python3.9/site-packages/telethon/client/downloads.py", line 857, in _download_document
    file_size=size.size if size else document.size,
AttributeError: 'PhotoPathSize' object has no attribute 'size'
```

</details>

**Comment by Lonami** [comment]
> I think SVG thumbnails is useless in Telethon and implementing it is waste of time

I also think downloading a non-JPG thumbnail may be unexpected. The library should probably just skip over that new size and pretend it's not there. But this is problematic if people rely on the length of the thumbnails to select which one to use, and not just go with 0 or -1.
