### ISSUE TITLE
download progress

### ISSUE THREAD

**Issue by NaWeeDBHR** [LonamiWebs/Telethon#1656]
Hi
I have a bot for download files from telegram and upload them some where else and I want to show to user downloading status by send a message and edit it every second until download finish but I can't edit message that defined outside of the function?!

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
