### ISSUE TITLE
Album with buttons get message without buttons?

### ISSUE THREAD

**Issue by CutePityOwl** [LonamiWebs/Telethon#1675]
Trying:
`await client.send_file('Channel',['image1.jpg',image2.jpg' ,image3.jpg'],caption=Messaggio3,buttons=[[Button.url('Info','https://t.me/User')],[Button.url('Contact Me', 't.me/User')]])`

The result will be an album message with no buttons, 
while with a single image it will give the image and the two buttons

**Comment by Lonami** [comment]
Albums cannot have buttons. This is an API limitation (as far as I know, since last time I tried, it didn't work either). If you know of a bot sending albums with buttons, please let me know.
