### ISSUE TITLE
How can add contacts via ImportRequest method in this library?

### ISSUE THREAD

**Issue by telexengineering** [LonamiWebs/Telethon#1678]
Hi I've searched available methods of your library and didn't find any method by which I can add contacts by their phone number.
How can I do it?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
