### ISSUE TITLE
Telegram authorization does not work on a cloud platform

### ISSUE THREAD

**Issue by avidale** [LonamiWebs/Telethon#1680]
I have a problem when using the [Telethon][1] Python client for Telegram for logging in. You can address it here, or [in my Stackoverflow question](https://stackoverflow.com/questions/65869010/telegram-does-not-send-authorization-code-if-the-request-was-sent-from-telethon), if it seems more appropriate. 

The script below works perfectly fine when I run it on my own laptop: it prints a SentCode object, Telegram sends me a confirmation code, and I use it to log in. 

When I run exactly the same script  on Heroku, it still prints the same SentCode object, however, I don't receive any confirmation code from Telegram and cannot continue logging in. 

```
from telethon import sync  # noqa
from telethon import TelegramClient
from telethon.sessions import StringSession
client = TelegramClient(session=StringSession(), api_hash=API_HASH, api_id=API_ID)
client.connect()
result = client.send_code_request(phone=PHONE)
print(result)
# prints SentCode(type=SentCodeTypeApp(length=5), phone_code_hash=..., next_type=CodeTypeSms(), timeout=None)
... the code for logging in and saving the session...
```

It seems that Telegram doesn't acknowledge authorization from Heroku for security reasons - maybe, Heroku is often used to host malicious bots, and Telegram fights them this way. 
However, neither [Telethon][2] nor [MTProto][3] documentation reflects this restriction. So I wonder, how is it even possible to use MTProto clients like Telethon from a cloud platform? And if it is possible, what should I do to get around this restriction? 

And if this restriction does really exist, maybe it should be reflected in Telethon documentation? Because the documentation creates the impression that the methods such as `TelegramClient.send_code_request` do work wherever they are called, and it turns out to be not so. 

  [1]: https://github.com/LonamiWebs/Telethon
  [2]: https://docs.telethon.dev/en/latest/
  [3]: https://core.telegram.org/mtproto

**Comment by Lonami** [comment]
This is indeed something the Telegram servers are doing, and cannot be fixed here. See also #1448. I'll move discussion there.
