### ISSUE TITLE
events.Album

### ISSUE THREAD

**Issue by big-vl** [LonamiWebs/Telethon#1684]
**Checklist**
* [None] The error is in the library's code, and not in my own.
* [y] I have searched for this issue before posting it and there isn't a duplicate.
* [y] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
@client.on(events.Album())
async def handler_album(e):
    await e.edit(file=["1.gif", "1.gif"])
    await e.edit("edit text album")
    print("edit here")
    for m in e.messages:
        await m.edit("dont edit")
        await m.edit(file="1.gif")
        print("edit here for")
```

Not error message, not edit album text, not edit album files, how to edit?

**Comment by Lonami** [comment]
The second one should work (you should enable `logging` to figure out why the first one fails). The first one is not implemented. What should happen if the user only provides one file? Or too many? Or too little?

**Comment by big-vl** [comment]
`[DEBUG/2021-01-29 03:05:42,825] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2021-01-29 03:05:42,826] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2021-01-29 03:05:50,968] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2021-01-29 03:05:50,969] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2021-01-29 03:05:56,687] telethon.network.mtprotosender: Handling gzipped data
[DEBUG/2021-01-29 03:05:56,690] telethon.network.mtprotosender: Handling update Updates
[DEBUG/2021-01-29 03:05:56,696] telethon.network.mtprotosender: Receiving items from the network...
edit here
edit here for
edit here for
edit here for
[DEBUG/2021-01-29 03:05:56,704] telethon.extensions.messagepacker: Assigned msg_id = 6922966544952695504 to GetParticipantRequest (7f7fc1efdb50)
[DEBUG/2021-01-29 03:05:56,704] telethon.extensions.messagepacker: Assigned msg_id = 6922966544955724376 to GetParticipantRequest (7f7fc1efde50)
[DEBUG/2021-01-29 03:05:56,706] telethon.extensions.messagepacker: Assigned msg_id = 6922966544961296692 to GetParticipantRequest (7f7fc1f0a130)
[DEBUG/2021-01-29 03:05:56,706] telethon.network.mtprotosender: Encrypting 3 message(s) in 180 bytes for sending
[DEBUG/2021-01-29 03:05:56,706] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2021-01-29 03:05:56,707] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2021-01-29 03:05:56,707] telethon.extensions.messagepacker: Assigned msg_id = 6922966544966817512 to MsgsAck (7f7fc1f0a3d0)
[DEBUG/2021-01-29 03:05:56,707] telethon.network.mtprotosender: Encrypting 1 message(s) in 68 bytes for sending
[DEBUG/2021-01-29 03:05:56,709] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2021-01-29 03:05:56,709] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2021-01-29 03:05:56,758] telethon.network.mtprotosender: Handling container
`
Nothing happens in the magazine, I want to replace the files in the album, but the best option would be to remove the files from the album when editing, the signature for the album also does not change.

**Comment by big-vl** [comment]
```
        if comment_to is not None:
            entity, reply_to = await self._get_comment_data(entity, comment_to)
        else:
            reply_to = utils.get_message_id(reply_to

        # First check if the user passed an iterable, in which case
        # we may want to send grouped.
        if utils.is_list_like(file):
```
please fix in https://github.com/LonamiWebs/Telethon/archive/master.zip in telethon/client/uploads.py in line 333

**Comment by big-vl** [comment]
People, I do not understand all the same, how can I edit the album?

**Comment by Lonami** [comment]
> please fix in https://github.com/LonamiWebs/Telethon/archive/master.zip in telethon/client/uploads.py in line 333

What is there to fix?
