### ISSUE TITLE
Check proxy

### ISSUE THREAD

**Issue by eenvid** [LonamiWebs/Telethon#1687]
Hi
Is there a way to make sure the client connects to the proxy?
Now when I use a proxy, if the client does not connect to the proxy, it continues to work without the proxy and does everything normally.

Or is there a way to check if the proxy is active before use?

**Comment by Lonami** [comment]
Connection should fail if the proxy is specified but cannot be used. Is that not the case? I tried the following code and got a `ConnectionError` (proxy is honoured):

```python
>>> from telethon.sync import TelegramClient; client = TelegramClient(None, 1, 'a', proxy=('socks5', 'example.com', 4444)).start()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/home/Telethon/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/home/Telethon/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/data/data/com.termux/files/home/Telethon/telethon/client/telegrambaseclient.py", line 514, in connect
    if not await self._sender.connect(self._connection(
  File "/data/data/com.termux/files/home/Telethon/telethon/network/mtprotosender.py", line 125, in connect
    await self._connect()
  File "/data/data/com.termux/files/home/Telethon/telethon/network/mtprotosender.py", line 251, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)
```

**Comment by eenvid** [comment]
I also thought exactly if the proxy had a problem, the client would not connect and I was just waiting for the error above.
But it seems that it ignores my proxy and connects without a proxy.
I copied exactly the code you wrote and executed it with Python and it gave me the following answer.
"" Please enter your phone (or bot token): ""

I was really confused !!
I do not know how this happened, I am copying your code exactly!

**Comment by Lonami** [comment]
Are you using the `master` version? (Install from this repository's `.zip`). Which proxy library do you have installed, Pysocks or python-socks[asyncio]?

**Comment by eenvid** [comment]
I installed the package using the CMD screen and " Pip Install telethon ".
And I installed the Navid Pysocks .

**Comment by eenvid** [comment]
good.
I uninstalled package Pysocks  and installed package python-socks, and now I have the following error.
ConnectionError: Connection to Telegram failed 5 time(s)

Thank you for your good and fast response

**Comment by Lonami** [comment]
Okay then we probably need to look into why Pysocks is misbehaving.

**Comment by vegeta1k95** [comment]
@Lonami 
I think this one is related to the problem with the default `ProactorLoop` on some systems, which skip proxies.
Workaround should be to try to manually set `SelectorLoop` as the default loop at the begginning of the script.

**Comment by Lonami** [comment]
I'm cleaning up proxy-related issues, so closing in favour of the new issue.
