### ISSUE TITLE
Using multiple user entities in InviteToChannelRequest

### ISSUE THREAD

**Issue by noob-coder123** [LonamiWebs/Telethon#1691]
Hi Lonami! I've a question
Suppose i have two user entities
```
user1 = client.get_entity('username')
user2 = client.get_entity('another_usrname')
channel = client.get_entity('channel')
```
Can I use in this way?
`client(InviteToChannelRequest(channel, [user1, user2])`
Thanks

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by noob-coder123** [comment]
Sorry for that

**Comment by steven07700** [comment]
Okay
