### ISSUE TITLE
The message does not appear in the group, appears on Telethon and does not delete

### ISSUE THREAD

**Issue by WellingtonFonseca** [LonamiWebs/Telethon#1692]
Guys, I don't know what I investigated here, but I can't find a solution.
There is a message from one of my groups that in `telethon_client.get_messages ()` is appearing, but neither the application nor the desktop has this message.
What information do you need for investigations?

**Telethon version**
```
Name: Telethon
Version: 1.19.0
Summary: Full-featured Telegram client library for Python 3
Home-page: https://github.com/LonamiWebs/Telethon
Author: Lonami Exo
Author-email: totufals@hotmail.com
License: MIT
Location: /usr/local/lib/python3.8/site-packages
Requires: rsa, pyaes
Required-by:
```
**Message info**
```
MessageService(id=26914, 
  peer_id=PeerChat(chat_id=390555777), 
  date=datetime.datetime(2020, 12, 31, 20, 30, 39, tzinfo=datetime.timezone.utc), 
  action=MessageActionHistoryClear(), 
  out=True, 
  mentioned=False, 
  media_unread=False, 
  silent=False, post=False, 
  legacy=False, 
  from_id=PeerUser(user_id=681020273), 
  reply_to=None)
```
**Telegram Desktop - Chat On Top**
![screenshot](https://user-images.githubusercontent.com/25608175/107134707-4631f780-68d3-11eb-9da0-f4fb5748d35f.png)

**Comment by Lonami** [comment]
This message indicates "history was cleared at this point", which means messages previous to that are not shown. Official clients don't show it, because the user can simply see there is no history past that.

**Comment by WellingtonFonseca** [comment]
Got it, but what do I do? Telethon is unable to delete the message and I am stuck in an infinite loop, because I check if the date is less than 2021-01-01 and the result is True.
Will I have to check if `action = MessageActionHistoryClear ()` and create a message blacklist?

**Comment by Lonami** [comment]
No idea what your code is doing, but yes, you can just ignore it. Please don't extend this discussion with usage questions, it's not the right place, and the issue has already been resolved.

**Comment by WellingtonFonseca** [comment]
@Lonami But the question is not my code, because it is a type of message that Telethon cannot delete, shouldn't there be a parameter where the library itself ignores these messages?

**Comment by Lonami** [comment]
Telethon can delete all messages. If it fails with an RPC error, that's Telegram telling you you don't have permission. In the case of clear history, it's just an indication the history was cleared, nothing you should delete.
