### ISSUE TITLE
Regression in 668dcd5 prevents GetHistoryRequest from ever being invoked by _MessagesIter

### ISSUE THREAD

**Issue by joell** [LonamiWebs/Telethon#1693]
**Summary:** `messages.SearchRequest` is being used in some cases where the documentation claims `messages.GetHistoryRequest` would be used instead.  This is due to code that was moved in 668dcd5 without updating the condition of an affected `elif` branch.

**Detail:**
In commit 668dcd5, the `if filter is None: filter = types.InputMessagesFilterEmpty()` test in `_MessagesIter._init` was moved to [line 76](https://github.com/LonamiWebs/Telethon/commit/668dcd52ca4e2befcc456e19e4e3ee4d6d6f9df3#diff-756a36d6155926cfe4d1128cb6482cf02d52c81c57b2081b5ef842bd8d8abc6dR76) of telethon/client/messages.py, placing it above the if branches that determine which `messages` method to set `self.request` to.

Because `filter` was now never `None` entering those `if` branches, when the condition `search is not None or filter or from_user` is considered on [line 90](https://github.com/LonamiWebs/Telethon/commit/668dcd52ca4e2befcc456e19e4e3ee4d6d6f9df3#diff-756a36d6155926cfe4d1128cb6482cf02d52c81c57b2081b5ef842bd8d8abc6dR90) it will always be true.  As a consequence, the `else` branch that leads to using `messages.GetHistoryRequest` as the request method will never evaluate.  The result is that `messages.SearchRequest` will be used in cases where users would expect the `messages.GetHistoryRequest` to be used instead (per the [documentation's claim](https://docs.telethon.dev/en/latest/modules/client.html?highlight=iter_messages#telethon.client.messages.MessageMethods.iter_messages) that omitting `search`, `filter`, and `from_user` in calls to `Client.iter_messages` will result in `messages.getHistory` being invoked).

This issue persists on the current master branch.

I'm not entirely sure what all is going on in that commit, so instead of submitting a potentially misguided pull request, I am just reporting this as an issue in hopes the committer's author can easily resolve it.

**Comment by Lonami** [comment]
Not sure why I bundled the `filter` change along with the `offset_rate`, a bad decision on my part. I believe filter now works for global search? But maybe not, I'll just revert that, thanks for the detailed report.

**Comment by Lonami** [comment]
Ah yeah search global now supports filter.

**Comment by Lonami** [comment]
Please let me know if this solves it (I have to sleep but it seemed kinda high priority so I made a quick hotfix…).

**Comment by joell** [comment]
I spotted a possible problem in the new conditional and [commented on it there](https://github.com/LonamiWebs/Telethon/commit/23041f398b00c2cf94fa416ff25310807d6aacc0#r46900502).

**Comment by joell** [comment]
I'm personally in no rush, so this can definitely wait until after your night's sleep. :-)

**Comment by Lonami** [comment]
(Oops deleted my comment as it was unnecessarily personal).

**Comment by joell** [comment]
I've retested against `master`, and I can confirm this corrects the issue.  Thank you for such a rapid response!!
