### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by MrSnowball-dev** [LonamiWebs/Telethon#1695]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

That's not the code issue, but documentation one. For the last couple releases there is no docs for the Message and MessageButton custom packages.

![image](https://user-images.githubusercontent.com/23441203/107435490-459c9980-6b3d-11eb-87c2-4224fd88b3c7.png)

**Comment by Lonami** [comment]
`MessageButton` should be fine. Did you mean `MessageEmpty`?

**Comment by Lonami** [comment]
Fixing this will require an even larger, nastier hack.
