### ISSUE TITLE
Serialization / deserialization does not work correctly for objects of type Photo

### ISSUE THREAD

**Issue by ShnurD6** [LonamiWebs/Telethon#1698]
```
from telethon.extensions import BinaryReader
from telethon.tl.types import Photo

@client.on(events.NewMessage())
async def handler(event):
    message = event.message
    if message.photo:
        print("   ACTUAL:", message.photo)
        print("CONVERTED:", Photo.from_reader(BinaryReader(bytes(message.photo))))
```

![image](https://user-images.githubusercontent.com/32021495/107706914-1d926f00-6cd2-11eb-8abc-1657b02fefd1.png)

To reproduce the bug, send/receive any photo to/from your account

**Comment by Lonami** [comment]
Not a bug, the code posted just happened to work. `bytes(tlobject)` includes the `cls.CONSTRUCTOR_ID` (4 bytes int) which indicates which object to read. `Photo.from_reader` does not read this header. If you know it's a `Photo`, you could skip it with `bytes(...)[4:]`. But what you want here is `binary_reader.tgread_object()`; it will return the `Photo` without using `Photo.from_reader`.
