### ISSUE TITLE
Voice chat started/finished

### ISSUE THREAD

**Issue by viksalonas** [LonamiWebs/Telethon#1699]
Hello!
Thank you for the best library.
How can i get info about start/stop voice chat by admins  in supergroup?

**Comment by Lonami** [comment]
Given [my stance on calls](https://t.me/TelethonChat/284717), I don't think it would be a good idea to provide a friendly `events` class if it would be so limited. I have never tried myself, but <code>@client.on(events.Raw((<a href="https://tl.telethon.dev/constructors/update_phone_call.html">UpdatePhoneCall</a>, <a href="https://tl.telethon.dev/constructors/update_group_call.html">UpdateGroupCall</a>)))</code> should probably do along with access to `update._entities`.

**Comment by viksalonas** [comment]
Thank you for answer.
But i get error: name 'UpdateGroupCall' is not defined.

**Comment by Lonami** [comment]
Please ask usage questions in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by viksalonas** [comment]
from telethon.tl.types import UpdatePhoneCall, UpdateGroupCall

:) My regards, you one of a best software developers for me.
