### ISSUE TITLE
configuration file

### ISSUE THREAD

**Issue by rlsalgueiro** [LonamiWebs/Telethon#1703]
please add the option of a config.ini file to storage api variables, next to your main script ,with the following 

[telethon]
api_id = 321456
api_hash = aaassadusdklpPasJGGeaef1
bot_token = 123456789:WHZ1A9PH6_usodomouWT9PH64jUlIu7iw

this feature load with TelegramClient import
This is better because allows you to keep your credentials out of your code without having to deal with how to load them.

**Comment by Lonami** [comment]
Reading such a file is 4 lines of Python code. Reading such a file is not responsibility of the library. It's a library to interact with Telegram, it shouldn't decide how to read those parameters. Environment variables, text files, `.ini` files, or a `constants.py` which is not committed all are valid options. There is no "obvious" solution here.

**Comment by rlsalgueiro** [comment]
Thank for answer
pyrogram has the solution, i like telethon more, the inline mode is better for my bot. 
I find a lot of  libraries for create a telegram bot, and you have a great one, that is what i wanto to use and i am using, but add good ideas(or funtionalities) from others libraries is not a bad idea

https://docs.pyrogram.org/intro/setup

**Comment by Lonami** [comment]
A `config` parameter in the `TelegramClient` *might* be a reasonable addition. I'm just not sold on the idea.
