### ISSUE TITLE
Private Group's Full_Info

### ISSUE THREAD

**Issue by SadraSalman** [LonamiWebs/Telethon#1704]
Hi,
Is there any way to get FullInfo of a joined private group?
I used to get this info by id and access_hash ,like this:
...
updates = await client(ImportChatInviteRequest(grouphash))
chat = updates.chats[0]
channel_id = chat.id
access_hash_channel = chat.access_hash
input_channel = InputChannel(channel_id, access_hash_channel)
ch_full =await client(GetFullChannelRequest(channel=input_channel))
...
But now, it seems that chat.access_hash is not available.
I could use some help.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
