### ISSUE TITLE
file object edit message

### ISSUE THREAD

**Issue by big-vl** [LonamiWebs/Telethon#1705]
**Checklist**
* [y] The error is in the library's code, and not in my own.
* [y] I have searched for this issue before posting it and there isn't a duplicate.
* [y] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
...

```
from the documentation it is indicated that a file object with options, I do not understand how to specify options when editing messages
```
            file (`str` | `bytes` | `file` | `media`, optional):
                The file object that should replace the existing media
                in the message.
```

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
