### ISSUE TITLE
Chat content is restricted

### ISSUE THREAD

**Issue by z19961225** [LonamiWebs/Telethon#1707]
Some of my channels are limited for the following reasons. How can I change IOS to Android：
restriction_reason=[RestrictionReason(platform='ios', reason='porn', text="This message couldn't be displayed on your device because it contains pornographic materials.")])

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
