### ISSUE TITLE
client([actions], ordered=True) hangs forever

### ISSUE THREAD

**Issue by michelemostarda** [LonamiWebs/Telethon#1709]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

version: 
Python 3.8.6
Telethon==1.19.5

**Code that causes the issue**
```
   loop = asyncio.get_event_loop()
   client = TelegramClient('default', TELEGRAM_API_ID, TELEGRAM_API_HASH, loop=loop)
   client.start(bot_token=TELEGRAM_BOT_TOKEN)
   msgs = [SendMessageRequest('somechatorchannel', f'msg{i}') for i in range(4)]
    async def proc():
        return await client(msgs, ordered=True)  # with ordered=False runs correctly
    client.loop.run_until_complete(proc())
```

**Traceback**
```
NO traceback, hangs forever

```

**Comment by Lonami** [comment]
That must've been broken for quite some time… Thanks for the report!
