### ISSUE TITLE
 Bots can't send messages to other bots (When using crontab)

### ISSUE THREAD

**Issue by eromoe** [LonamiWebs/Telethon#1710]
1. I wrote a script use my account to send some message to some bot .
2. I manually ran this script to get session file setup and it worked well .
3. Add crontab job `10 0,3 1,8,16,24 * * /opt/conda/bin/python /jobs/app/tg_jobs/user.py`

## Problem: 
Send message is fine when I run script in shell , but got error when ran in crontab 
```
 File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.7/site-packages/telethon/client/messages.py", line 800, in send_message
    result = await self(request)
  File "/opt/conda/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/conda/lib/python3.7/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.UserIsBotError: Bots can't send messages to other bots (caused by SendMessageRequest)
```

After some test , I found it need assign the work folder first  :  `10 0,3 1,8,16,24 * * cd /jobs/app/tg_jobs/ && /opt/conda/bin/python /jobs/app/tg_jobs/user.py` . 

Despite the session path problem , at least this error message is wrong.
Would be nice to print session path to hint user this problem .

**Comment by Lonami** [comment]
> this error message is wrong

Why? Did the client not login under a bot account and tried to send a message to another bot account?

>  Would be nice to print session path to hint user this problem

Printing the session path for errors produced by the API would require updating far more code than I think is worth for such little benefit. Ultimately, it is your code that decides *how* to login, and which account to login to. By this I mean, your code already has this knowledge, you wrote it yourself!

All that said, if you can think of a better error message (without including the session path), I'm open to hearing about it so that I can update it. Personally, I think the error is fine (you tried to `SendMessageRequest` but failed because "Bots", you, can't message other bots).

**Comment by eromoe** [comment]
> Why? Did the client not login under a bot account and tried to send a message to another bot account?

I had wrote `client.start(bot_token=TOKEN)`  and excuted once , but this error keeped showing after I change to `client.start()` .
At this point, I thought telethon would prompt mobile input , but it still print `telethon.errors.rpcerrorlist.UserIsBotError: Bots can't send messages to other bots (caused by SendMessageRequest)` 

This error is very strange for me ,  I mean it was not signed in as a bot  however complain that `UserIsBotError` . 
By default should be  login timeout . Wait ... maybe it generated session when run as bot first time , then reuse that session cause this error ,  is this right ?

**Comment by Lonami** [comment]
Yes, that's the point of sessions. You specify a session when creating the client, you login once you don't need to login again, no matter account type.

**Comment by Lonami** [comment]
Note that if you specify a different phone or bot token on start, the library should also warn you "loaded a session for other account". (This can't happen with interactive mode because it assumes you want to use the old session). If you can improve the documentation, changes are welcome.
