### ISSUE TITLE
Allow per-request setting of flood_sleep_threshold

### ISSUE THREAD

**Issue by jverkoey** [LonamiWebs/Telethon#1711]
In my use case I've set `flood_sleep_threshold` to a fairly high number as I generally prefer that the service sleep on flood events than fail outright.

However, for some categories of request such as `AddContactRequest`, I'd like to be able to have it fail immediately when a flood error is raised. I'm not sure how to do this without lowering the global `flood_sleep_threshold` for the client.

Would it be possible to add a way to allow a request to ignore the global `flood_sleep_threshold` and prefer an explicit one?

E.g.

```python
        return await client(functions.contacts.AddContactRequest(
            id=user.id,
            first_name=user.first_name or '',
            last_name=user.last_name or '',
            phone=user.phone or '',
        ), flood_sleep_threshold=5)  # <- Override the global flood_sleep_threshold
```

**Comment by Lonami** [comment]
Feel free to send a PR.

**Comment by jverkoey** [comment]
My rough understanding is that I'd need to route an explicit flood threshold through to here:

https://github.com/LonamiWebs/Telethon/blob/e1d2c81dca7c26c11365457ad2f7857853249471/telethon/client/users.py#L107-L111

How does a `client(<#request#>)` invocation wire through to that call site though? telegrambaseclient's `__call__` is abstract and I'm not certain how it gets routed through to the specific request types.

https://github.com/LonamiWebs/Telethon/blob/d9691c934290a9578bfdcf2bcda3df1cad3a959c/telethon/client/telegrambaseclient.py#L815-L834

**Comment by Lonami** [comment]
The real call is under `users.py`. You want a parameter `flood_sleep_threshold=_sentinel` in the methods, and define `_sentinel = object()` below the thresholds, so that inside, you can do:

```python
threshold = self.flood_sleep_threshold if flood_sleep_threshold is _sentinel else flood_sleep_threshold 
```

**Comment by BelgenOp** [comment]
https://github.com/LonamiWebs/Telethon/commit/e546ae2f85632695e771c109c7cabb15350fbb8e
