### ISSUE TITLE
edit_admin not working

### ISSUE THREAD

**Issue by lordtgm** [LonamiWebs/Telethon#1712]
hi. Im using client.edit_admin and it works when I am owner of the channel. but it dosen't work when Im just an admin with full premissions. here is my code:
```
async def promote(text,user):
    chat=await client.get_entity(await get_id(text.split(" ")[0]))
    admin=await client.get_entity(await get_id(text.split(" ")[1]))
    if user!=chats[chat.id]["owner"]:
        return "You dont have access!"
    await client.edit_admin(chat,admin,
        post_messages=True,
        add_admins=False,
        change_info=True,
        delete_messages=True,
        is_admin=True,
        edit_messages=True)
```
I tested it without is_admin, only is_admin and some more but none of them worked.

**Comment by Lonami** [comment]
`is_admin` only works in small group chats. `post_messages` only works in broadcast channels. Make sure the type is correct, or provide more information.

**Comment by lordtgm** [comment]
> `is_admin` only works in small group chats. `post_messages` only works in broadcast channels. Make sure the type is correct, or provide more information.

My problem was fixed. manage_call is True if you don't set it. You just need to set manage_call=None
