### ISSUE TITLE
make _parse_message_text public

### ISSUE THREAD

**Issue by penn5** [LonamiWebs/Telethon#1714]
it would be useful for manipulating entities without breaking tg:// usage (currently i have to do the entities stuff then unparse back to html and give to the client like that)

**Comment by Lonami** [comment]
I don't want to commit to maintaining any more public methods than I strictly should. There's already way too many things that shouldn't be public. Though "we're all adults" so you can keep using the private method as it's unlikely to change soon.

**Comment by penn5** [comment]
Then how about splitting out the messageentityname stuff into a public method?

**Comment by Lonami** [comment]
`convert_mention_like_message_entities_into_proper_entities`? I really don't think it's worh it at all. Such a niche use case, sorry.
