### ISSUE TITLE
How do I send a set of videos?

### ISSUE THREAD

**Issue by hwmbing11** [LonamiWebs/Telethon#1717]
Sending a group of pictures can use a list, so how to send a group of videos? We also need to deal with video thumbnails and other issues

**Comment by Lonami** [comment]
Not sure how best one would integrate this without making an absolute mess. Every parameter would likely need to be treated as a list.

**Comment by hwmbing11** [comment]
Can you add a class similar to the send_media_group of pyrogram to handle it? Add an InputMedia object to handle it
I tried to use InputMediaUploadedDocument to create a list of video groups, I only found that there is a thumb field in this class, but it seems to fail

**Comment by Lonami** [comment]
Needs testing to see if sending an album of videos works.

**Comment by redf0x1** [comment]
> Needs testing to see if sending an album of videos works.

Send an active video album but no thumbnails are processed

**Comment by Lonami** [comment]
This should work in the latest version. If it's not the case, please let me know and I can reopen.
