### ISSUE TITLE
telegram client stops working for no reason after ~24h

### ISSUE THREAD

**Issue by alex-sherwood** [LonamiWebs/Telethon#1721]
Here's the code sample that I use, it resedens new media from telegram channels to discord. It works pretty fine, except that next day it stops resending content, no errors or any messages in log files. So I really can't understand why is that happening. 

```
logger_disc = logging.getLogger('discord')
logger_disc .setLevel(logging.INFO)
handler_disc = logging.FileHandler(filename='discord.log', encoding='utf-8', mode='w')
handler_disc.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger_disc .addHandler(handler_disc)

logger_tele = logging.getLogger('telethon')
logger_tele.setLevel(logging.INFO)
handler_tele = logging.FileHandler(filename='telegram.log', encoding='utf-8', mode='w')
handler_tele.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger_tele.addHandler(handler_tele)


class MyDiscClient(discord.Client):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)    

    async def on_ready(self):
        print('Logged in as')
        print(self.user.name)
        print(self.user.id)
        print('------')  

    async def forward_message(self, text, media=[]):
        channel = self.get_channel(XXXXXXXXXXXXXX)    
        discord_files = []
        if media is not None and media is not []:
            discord_files.append(discord.File(media))
        #print("Got " + text)
        #print("Files " + str(media))
        try:
            if len(text) > 0:
                await channel.send(text, files=discord_files)
            else:
                await channel.send(files=discord_files)
        except Exception as e:
            traceback.print_exc()
        finally:
            if media is not None and media is not []:
                try:
                    if isinstance(media, list):
                        for file in media:
                            os.remove(file)
                    else:
                        os.remove(media)
                except Exception as e:
                    traceback.print_exc()

telegram_client = TelegramClient('session_name', XXXX, 'XXXXXXXX', auto_reconnect=True, retry_delay=15, connection_retries=999,
                                 #connection_retries=35, timeout=45, request_retries=15,
                                 #sequential_updates=True, retry_delay=10, flood_sleep_threshold=35,
                                 raise_last_call_error=True)

telegram_client.start('XXXXXXXXXXXXXXX')
bot = commands.Bot(command_prefix='!')

@telegram_client.on(events.NewMessage(chats=('channel1', 'channel12', 'channel13', 'channel14',)))
async def normal_handler(event):
    message = event.message
    text = message.message
    files = []
    #if message.media is not None:
    #    if message.document.size > 8388119:
    #        return False
    files = await telegram_client.download_media(message.media, 'temp')
    await client.forward_message(text, files)


client = MyDiscClient()
client.run('XXXXXXXXXXXXXX')
```

**Comment by ehtec** [comment]
Similar issue here. I am not downloading anything though, only getting the message text. It works very well for 10 to 20 hours, but then it simply stops receiving messages without any error. I am using telethon 1.20 from pip.

**Comment by Lonami** [comment]
Similar report: https://t.me/TelethonChat/311740.

Telethon relies on Telegram to send the updates. If Telegram doesn't, Telethon can't really know there are unhandled updates. A large number of large channels, a lot of active sessions, is known to slow down the delivery.

**Comment by ehtec** [comment]
> Similar report: https://t.me/TelethonChat/311740.
> 
> Telethon relies on Telegram to send the updates. If Telegram doesn't, Telethon can't really know there are unhandled updates. A large number of large channels, a lot of active sessions, is known to slow down the delivery.

Hi Lonami, that's not a similar report, that is the same report actually. I asked in the telegram channel as well. I always get the updates in the telegram app immediately. And it always works when I restart the bot. Probably it would be a workaround to reconnect when it doesn't receive any updates anymore. Therefore, i would need to know when it disconnected me. I couldn't see any meaningful errors in the DEBUG log though. So the only thing I can think of at the moment is creating an echo bot, sending a dummy message to the echo bot every ten seconds or so and restart the connection in case the message isn't received. This is a very dirty workaround though and I can't imageine that it's the only solution as the Android telegram client is working perfectly well. Do you have another Idea? Thanks for help.

**Comment by vegeta1k95** [comment]
@ehtec 
Android Telegram client delivers immediately only high-priority messages (e.g. private) via FCM push notifications (which you see in your mobile status bar)
It synchronizes your update states only when you are entering the application itself. 
Android Telegram client does not keep socket alive for long and certainly does not work 24/7 (it would be battery consuming at the very least)

**Comment by roozbeh1347** [comment]
The same has happened since an hour ago (2023-11-23 15:08 UTC Time). 
Except for a few channels, almost all the stream seems to be cut off.
Personal new messages still are being received.
Everything was working fine as usual prior to that (no extra load or activity)
Any idea?
