### ISSUE TITLE
ImportError: cannot import name 'ChannelBannedRights'

### ISSUE THREAD

**Issue by cnderton** [LonamiWebs/Telethon#1722]
I get an import error when trying to import ChannelBannedRights from telethon.tl.types (`from telethon.tl.types import ChannelBannedRights`)
```
 File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ChannelBannedRights' from 'telethon.tl.types' (/usr/local/lib/python3.8/dist-packages/Telethon-1.20-py3.8.egg/telethon/tl/types/__init__.py)

```
I tied to install it by using pip3 and `python3 setup.py install`, but none of the methods fixes the issue.
I've also checked different versions (3.5 ,  3.7 , 3.8) of python and it didn't appear to work out.

**Comment by Lonami** [comment]
Telegram changed it for `ChatBannedRights`, though there's a friendly method to edit permissions now. See docs or ask in the group / stackoverflow for how.

**Comment by cnderton** [comment]
> Telegram changed it for `ChatBannedRights`, though there's a friendly method to edit permissions now. See docs or ask in the group / stackoverflow for how.

I couldn't find [here](https://telethonn.readthedocs.io/en/latest/extra/examples/chats-and-channels.html#admin-permissions).
Would you mind sharing it?

**Comment by cnderton** [comment]
> That's not the official documentation (note the URL has "telethonn"), the official is https://doc.telethon.dev. I don't know who owns the page you linked (but I wish they didn't).

Oh,thanks. I didn't pay attention to the link. That's so strange. Because in the installation instructions it showed Telethon's real github page

**Comment by Lonami** [comment]
It seems to be a copy paste of old docs, so yes, the links match.
