### ISSUE TITLE
Fix resolve_invite_link again

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#1723]
Context: https://github.com/LonamiWebs/Telethon/commit/a1f91d6eb8eaf06b5d823852310ce86b1ad4aa6b, https://t.me/BotNews/57

**Comment by Lonami** [comment]
@vegeta1k95, `-1003848961478`  should be generated with `-(1000000000000 + peer.channel_id)` (https://github.com/LonamiWebs/Telethon/blob/a1f91d6eb8eaf06b5d823852310ce86b1ad4aa6b/telethon/utils.py#L1038). However the `channel_id` is also `int` of 32 bits, so that doesn't make any sense. Is the channel public or do you have an invite link I can test with?

**Comment by vegeta1k95** [comment]
@Lonami 

I've setup logging at the points where I assume I get these large ID's. As soon as I receive one, I'll be able to tell from where they come, I'll post it here

**Comment by vegeta1k95** [comment]
@Lonami 

Okay I have found what was going on.
I was resolving a private channel invite link: [https://t.me/joinchat/7MuavzyWJ6BmMGIy](https://t.me/joinchat/7MuavzyWJ6BmMGIy)

The output returned from `utils.resolve_invite_link()` is `(0, 3972766399, 4365720458644972082).
As you can see here, the returned global chat ID is over the integer!

But if you actually join the channel with `ImportChatInviteRequest` you can see that the returned channel ID is `1401089426`.
Whole object is:

``` python
Channel(id=1401089426, title='Дневник снов | Блог сомнолога Кораблина', photo=ChatPhoto(photo_small=FileLocationToBeDeprecated(volume_id=200219500171, local_id=40735), photo_big=FileLocationToBeDeprecated(volume_id=200219500171, local_id=40737), dc_id=2, has_video=False), date=datetime.datetime(2021, 3, 11, 1, 13, 40, tzinfo=datetime.timezone.utc), version=0, creator=False, left=False, broadcast=True, verified=False, megagroup=False, restricted=False, signatures=False, min=False, scam=False, has_link=False, has_geo=False, slowmode_enabled=False, call_active=False, call_not_empty=False, fake=False, gigagroup=False, access_hash=-6733645903094431630, username=None, restriction_reason=[], admin_rights=None, banned_rights=None, default_banned_rights=None, participants_count=None)], date=datetime.datetime(2021, 3, 11, 1, 13, 39, tzinfo=datetime.timezone.utc), seq=0)
``` 

What would be the reason that `resolve_invite_link()` parses hash to an ID > int?

**Comment by Lonami** [comment]
`resolve_invite_link` no longer correctly handles the newer link format, so I guess this needs fixing again (if it's fixable at all).

**Comment by painor** [comment]
I kinda brute force it but there was no obvious structure for the new format. seems like it's the only backend now and doesn't provide the id anymore :/

**Comment by vegeta1k95** [comment]
Well, since the payload is 12 bytes long, one can bruteforce it as a 12 bytes tuples of various combinations of `>`, `<`,`i`,`I`,`q`,`Q`,`l`,`L` and `h`, `H` (s.t. total length is 12). 
My attempt also did not lead to anything sensible.
So either: 
1) The hash in the temporary links contains internal telegram IDs (no more global IDs)
or
2) The hash encodes a non-trivial C-structure (class?), maybe with some byte offset / padding

@Lonami 
I wanted to ask, how and where in the first place did you figure it out about the possibility to decode link's hash as C-struct? 
Was it Telegram Desktop?

**Comment by Lonami** [comment]
I don't fully remember, but I think it was brought up in a private unofficial group of MTProto devs (so the credit for coming up with that is definitely not mine and I fully acknowledge it -- as with many Telegram things which aren't really obvious).

Your either doesn't consider the fact that the hash may be embedding the data, but this data be encoded with another key (which either only Telegram knows or it's embedded in the hash itself). Either way the right way to do this (for Telegram) is 1, where the hash is just a key into a database table row.

**Comment by vegeta1k95** [comment]
Since at the present we don't know how to resolve temporary invite links to the global IDs, I think we should either:
    1) Completely remove it from the internal usage (it still has some usage inside the lib itself I believe)
    2) Implement a mechanism of distringuishing between usual invite links (which are resolved to global IDs) and temporary invite links (which are not) and limit the use correspondingly.

The point (2) is not that simple though. In my observation, the unpacked values can by out of integers range as well as inside of it (e.g. much smaller), so that simple check on the out of `int` boundaries is not sufficient.

**Comment by Lonami** [comment]
Closing as it's not gonna get done and v2 should just remove it.

**Comment by beeb** [comment]
Hey there. Facing the issue described here where the invite link doesn't resolve to the chat ID. What would be the best strategy for a user to indicate which channel/group they'd like to monitor new messages for?

I need to filter `events.NewMessage` for single chat, and I thought the best way to indicate which one was to use the invite link, but apparently that doesn't work anymore.

Thanks for any suggestions!

**Comment by Lonami** [comment]
The most reliable way is using the chat ID. Please direct further questions to [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
