### ISSUE TITLE
Better compatibility between different update events

### ISSUE THREAD

**Issue by prashantsengar** [LonamiWebs/Telethon#1730]
There is a lot of incompatibility between different update events. I will explain using NewMessage and Album events

`NewMessage` is a single message, and has all the attributes that a message has, including `id`, `reply_to_msg_id`

`Album` event is a list of multiple messages. It does not have an `id` attribute, nor `reply_to_msg_id`. This causes a lot of issues while working with events.

**Proposal:**

Add similar properties to the `Album` update event. For instance, it can take all the properties of the first message of the album.

**Comment by Lonami** [comment]
`reply_to_msg_id` would make sense, but `id` wouldn't, because there isn't a single ID, there's multiple (and returning a list from a singular noun, `id`, would make no sense). Feel free to make an exhaustive list and/or send a PR for them.

**Comment by Lonami** [comment]
Note you can also do `event.messages[0]` to work with the first `Message`.

**Comment by Lonami** [comment]
Closing due to the lack of feedback. Feel free to bump with new ideas and I may reopen.
