### ISSUE TITLE
send_message: treat `file=[]` as no file

### ISSUE THREAD

**Issue by NightMachinary** [LonamiWebs/Telethon#1731]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
Sending messages with `file=[]` causes an error:
```
    last_msg = await client.send_message(receiver, message[s:e], file=file, force_document=force_document, parse_mode=parse_mode, link_preview=link_preview, reply_to=(last_msg))
  File "/Users/evar/anaconda/lib/python3.7/site-packages/telethon/client/messages.py", line 764, in send_message
    comment_to=comment_to
  File "/Users/evar/anaconda/lib/python3.7/site-packages/telethon/client/uploads.py", line 324, in send_file
    raise TypeError('Cannot use {!r} as file'.format(file))
TypeError: Cannot use [] as file

```

**Comment by apepenkov** [comment]
In my opinion, there is no need for that in library. You have to check yourself if the list is empty, and if it is, pass `file=None`
E.G.
```python
file_var = []
await bot.send_message(chat_id, text, file=file_var if file_var else None
```

**Comment by Lonami** [comment]
`file_bar or None` would also do. Yeah I don't think treating empty lists as no files is something we should do.
