### ISSUE TITLE
implicit casts broken in vectors

### ISSUE THREAD

**Issue by penn5** [LonamiWebs/Telethon#1734]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
client(ImportToGroupCallRequest(call, ["@lonami"]))
```

**Traceback**
```
TypeError: A TLObject was expected but got something else instead
```
Any type in a vector is not cast properly

**Comment by Lonami** [comment]
The generated code does handle vectors:

```python
async def resolve(self, client, utils):
        self.call = utils.get_input_group_call(self.call)
        _tmp = []
        for _x in self.users:
            _tmp.append(utils.get_input_user(await client.get_input_entity(_x)))

        self.users = _tmp
```

What is `call`? Are you sure it's a `TLObject`?
