### ISSUE TITLE
Delay on connecting to telegram server

### ISSUE THREAD

**Issue by amirpdlll** [LonamiWebs/Telethon#1735]
Hi ,
I'm using HTTP proxies , some times when I connect to telegram it takes about 5-10 minutes to get connected this sticks on :

`DEBUG:telethon.network.mtprotosender:Receiving items from the network`

this is my code 
```
proxy = (socks.HTTP, 'gate.smartproxy.com', int(7000))
client = TelegramClient(number, api_id, api_hash, proxy=proxy)
client.connect()
```

what is wrong ?

**Comment by Lonami** [comment]
The proxy must support non-HTTP data or the connection mode must be changed to emulate HTTP and fool the proxy. That's about all I know.

**Comment by Lonami** [comment]
I'm cleaning up proxy-related issues, so closing in favour of the new issue.
