### ISSUE TITLE
show this Error  :   table entities has 6 columns but 5 values were supplied

### ISSUE THREAD

**Issue by yumisvip** [LonamiWebs/Telethon#1737]
I checked the sqlsession (SQlite) file and found that there is an extra date field in the entities table, and the version is 7. I want to know how to save the sqlsession file with version 6.

**Comment by Lonami** [comment]
You cannot use a new session file in an old Telethon version. Use the same Telethon version everywhere or fix the session file yourself.

**Comment by yumisvip** [comment]
> You cannot use a new session file in an old Telethon version. Use the same Telethon version everywhere or fix the session file yourself.

Which version of Telethon’s sqlsession version is 6？

**Comment by Lonami** [comment]
You should always use the latest version, I don't remember all changes, but you can check the git history.

**Comment by yumisvip** [comment]
> You should always use the latest version, I don't remember all changes, but you can check the git history.

ok，thank you
