### ISSUE TITLE
get_message_history returns a maximum of 100 result.messages

### ISSUE THREAD

**Issue by ningyuansg** [LonamiWebs/Telethon#174]
I'm using the method [`TelegramClient.get_message_history`](https://github.com/LonamiWebs/Telethon/blob/c9e566342eb4007d1f2ac93106bb35f6330dbe37/telethon/telegram_client.py#L396)

I am unable to get it to return more than 100 messages. `limit=0` seems to default to 20, and anything above `limit=100` just stops at 100 messages. This is the case for both supergroups and private conversations (haven't tested other types).

```
>>> client.get_me()
user#......
>>> _, chats = client.get_dialogs()
>>> chat = chats[1]
>>> total, messages, entities = client.get_message_history(chat)
>>> total; len(messages); len(entities)
24750
20
20
>>> total, messages, entities = client.get_message_history(chat, limit=0)
>>> total; len(messages); len(entities)
24750
20
20
>>> total, messages, entities = client.get_message_history(chat, limit=200)
>>> total; len(messages); len(entities)
24751
100
100
>>> total, messages, entities = client.get_message_history(chat, limit=99999)
>>> total; len(messages); len(entities)
24751
100
100
```

**Comment by Lonami** [comment]
Yeah, I know. This is a limitation from Telegram' servers, nothing I can do from Telethon. You're going to have to retrieve it on chunks of 100 as much.

**Comment by ningyuansg** [comment]
@Lonami I see, thanks for the quick reply

**Comment by kolet** [comment]
@Lonami  @ningyuansg  i know this is an old post,
but i didnt want to reopen a new one..
telegram doesn't allow to forward more than 100 message.

have u solved ur issue in the end? i end up getting the same exact issue .

have u devide them into chunks?
if so how?

heres my code.

(by the way i have a weird problem , running the script it will copy the last message that was posted on the channel and not the first one..  any idea how to start from top to bottom?)
```
from telethon import TelegramClient
from telethon.tl.functions.messages import ForwardMessagesRequest

api_id = 214
api_auth = 'abcd'
session_number = '+1 222 222 2222'


#
# Global iteration settings
#
client = TelegramClient(session_number, api_id, api_auth)
client.start()

group  = client.get_entity('t.me/joinchat/aaa')

result=client.get_message_history(group.peer, limit=200)
messages = result
from_entity = group
to_entity = 'me'

client(ForwardMessagesRequest(
    from_peer=from_entity,  # who sent these messages?
    id=[msg.id for msg in messages],  # which are the messages?
    to_peer=to_entity  # who are we forwarding them to?
))
```

**Comment by ningyuansg** [comment]
@kolet [I sprinkled in some `time.sleep`s.](https://github.com/ningyuansg/TelegramQuoteGenerator/blob/4ec6ac88adeb31e2979809866e403fd2576660d6/tqg/telegram_api.py#L28)
