### ISSUE TITLE
Getting Full History of SuperGroup

### ISSUE THREAD

**Issue by hoptical** [LonamiWebs/Telethon#175]
Hi,

I want to get full history of messages of a supergroup but i'm confused how to use telethon methods and types! 
please help me by step by step instruction!
thanks

**Comment by Lonami** [comment]
This is not an issue, this is me doing your job. There's a nice `README`, a wiki, and the source code itself all here. If you want to hire me [hit me up](https://t.me/Lonami) privately, not through an issue.
