### ISSUE TITLE
Fetching list of users with get_full_channel

### ISSUE THREAD

**Issue by Darkkkkkkk** [LonamiWebs/Telethon#176]
What is the proper way to fetch all the users in my channel with telethon? I have been struggling with this for the past week as the documentation is.. thin (also, not being a great programmer doesn't help).

From what I saw around, GetFullChannelRequest is the solution but.. I wrote and deleted a lot of lines of code and nothing worked. The current iteration of code looks like this.

```
from telethon import TelegramClient

from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.functions.channels import GetFullChannelRequest
from telethon.tl.functions.messages import GetFullChatRequest
from telethon.tl.types import InputChannel

from telethon.tl.types import InputPeerEmpty

api_id = api_id  # Use your own values here. https://my.telegram.org
api_hash = 'api_hash'
phone_number = '+000000000'

client = TelegramClient('%sessionname%', api_id, api_hash)  # feel free to edit %sessionname% as you want
client.connect() # logining and connecting to Telegram servers

if not client.is_user_authorized():  # authorization (if there is no .session file created before)
    client.send_code_request(phone_number)
    client.sign_in(phone_number, input('Enter the code: '))

# this was as a test to see how do I fetch stuff
result = client(ResolveUsernameRequest('username'))
found_chats = result.chats
found_users = result.users
# end test

def GetFullChannel(self, id):
    self.GetFullChatRequest(id)

users = client(GetFullChannel(self, 'id'))
print(users)
```

The error that I get when I run this is

> NameError: name 'self' is not defined

Any guidance will be greatly appreciated as I am quite clueless. I cannot comprehend how am I supposed to fetch that list of users..or basically anything past that 'test' example above.

**Comment by pazis** [comment]
The correct way to invoke a request is like this:

`response = client.invoke(GetFullChatRequest(id))`

**Comment by Lonami** [comment]
> the documentation is.. thin

Telegram doesn't bother explaining what the methods do, or what the parameters mean. However, the methods are often very descriptive by themselves. [And there's a nice search](https://lonamiwebs.github.io/Telethon/).

> `NameError: name 'self' is not defined`

Well, clearly, `self` is not defined… The error is clear enough, you made that up. Also, you're returning nothing. And `.GetFullChannelRequest` is not a method for anything. It's a request.

You've done the `client(ResolveUsernameRequest('username'))` part right, it's just changing `ResolveUsernameRequest` with `GetFullChannelRequest`. I recommend [this Python book](http://www.diveintopython3.net/).

> The correct way to invoke a request is like this:
> `response = client.invoke(GetFullChatRequest(id))`

With the latest update, a simple `r = client(GetFullChatRequest(id))` will work.

**Comment by Darkkkkkkk** [comment]
Hello Lonami,

I did not meant to sound harsh or anything, I know you put up a really nice documentation and doing a great job. Before I posted here I think I read most of the posts on stack. Half of the fault I suppose it is mine as I am not a great programmer and I cannot comprehend things so easily.

Indeed the last line of code worked.. or at least I moved a bit forward. Now I got this error:

> OverflowError: int too big to convert

Googled it, found [this](https://github.com/LonamiWebs/Telethon/issues/38), read it multiple times, added and deleted the "-", "-100".  Eventually led me to this.

> Invalid object ID for a chat. Make sure to pass the right types.

What's the proper way to get the ID? As I got mine through **result.chats[0]** from the test code above in the initial post.

Thanks for all the help

**Comment by Lonami** [comment]
> What's the proper way to get the ID? As I got mine through **result.chats[0]** from the test code above in the initial post.

That should be the right way. Have you tried with other supergroups?

**Comment by Darkkkkkkk** [comment]
I have read it.. the only thing that came to my mind was
`r = client(GetFullChannelRequest(231399891))`
which did not worked (**type object 'int' has no attribute 'subclass_of_id'**)

**Comment by Lonami** [comment]
[You can't pass an int](https://lonamiwebs.github.io/Telethon/methods/channels/get_full_channel.html).

**Comment by Darkkkkkkk** [comment]
But I have to fetch the channel..somehow (as an object/array)? Can't seem to find a proper example. Because if I pass simply the username the error is going to be the same, just that I cannot pass a string.

**Comment by Lonami** [comment]
> But I have to fetch the channel

Yes.

> Because if I pass simply the username the error is going to be the same

Then resolve the username, and whatever chat you get, use that.

> So If I know these two values

You could construct the `InputChannel`.

> making an array

No you would use them to construct an `InputChannel`.

**Comment by Darkkkkkkk** [comment]
I think I managed to construct the inputChannel yet I am facing another error.
```
result = client(ResolveUsernameRequest('cofferinta'))
found_chats = result.chats
found_users = result.users

channel = client(InputChannel(result.chats[0].id, result.chats[0].access_hash))
print(channel)
```

The error:
> telethon.errors.rpc_errors.BadMessageError: (BadMessageError(...), 'Odd msg_seqno expected (relevant message), but even received.')

**Comment by Lonami** [comment]
Okay, okay, here we go again.

> ```
> channel = client(InputChannel(result.chats[0].id, result.chats[0].access_hash))
> ```

I've asked this endless times, and I'm yet to get an answer from someone. [There's a dedicated section to that](https://lonamiwebs.github.io/Telethon/#methods). What are you trying to achieve by "invoking" an `InputChannel`? You can just `.invoke()` requests!! You already have your `result.chats[0]`, which is a channel. It will be converted to `InputChannel`, i.e., what you need for `GetFullChannelRequest` automatically. Either that, or you construct it yourself, `InputChannel(id, hash)`. But you **can not invoke anything that is not a request**. The error is cryptic, but I just realized why. So I'm going to fix that now.

**Comment by Darkkkkkkk** [comment]
I apologise if my question were put as plain stupid. I did not meant to bother you or anyone here. Thank you for all your assistance. I hope that I am not bold, I'd like a bit more guidance in order how to get the members of the group. I managed to return all the chat info with this code:

```
result = client(ResolveUsernameRequest('cofferinta'))
found_chats = result.chats
found_users = result.users

r = client(GetFullChannelRequest(result.chats[0]))
print(r)
```
From what it returned, `{ChatFull: {full_chat: {can_view_participants: True, can_set_username: None, id: 1055018889, about: "", participants_count: 15,` I should  be able to see them. In fact, it showed me the two bots in the conference but no users.

Is this the proper approach to fetch the users? I am searching through the manual, but I do not know entirely how to use all these things.
```
x = client(GetUsersRequest(found_users[0]))
```
The problem is that found_users is empty.

**Comment by Darkkkkkkk** [comment]
@Lonami Is there any chance to re open this issue? I do not want to make another 'issue'. Maybe some other will give a hint on how to solve this final issue.

**Comment by Lonami** [comment]
> any chance to re open this issue?

No, this is for Telethon implementation issues, not usage questions. Use StackOverflow for that. Also, I'm no expert in Telegram API _usage_ per se, i.e., I don't know every method and what it does. The only thing I would do would be search, as you can too, sorry.

**Comment by Darkkkkkkk** [comment]
Well, I am using Telethon. I am doing this half for me and half for a project for my college and I was running a bit on burrowed time, this is why I was quite pushy.

At the moment my last problem is that the resolved users (ResolveUsernameRequest) are always empty. I tried with different groups. Have you ever encountered this? Is this the wrong approach? It returns the peer (chat id), chat with a lot of attributes and users: [] is always like this.

Thank you

**Comment by Lonami** [comment]
> Have you ever encountered this @Lonami

If anything, search on the issues, I can't remember. I'd swear that method is just to search, given an username, for someone (channel, group, user, etc.) and nothing else.

**Comment by Lonami** [comment]
Seems like [`GetParticipantsRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/get_participants.html) is a thing.

**Comment by dedUct** [comment]
Can you give an example of using [GetParticipantsRequest](https://lonamiwebs.github.io/Telethon/methods/channels/get_participants.html)?

**Comment by playmean** [comment]
Can you give an example of using [GetParticipantsRequest](https://lonamiwebs.github.io/Telethon/methods/channels/get_participants.html)?

**Comment by Lonami** [comment]
Sure, [I've updated the wiki](https://github.com/LonamiWebs/Telethon/wiki/Retrieving-all-chat-members) since others may ask the same question.

**Comment by playmean** [comment]
Thank you very much :3

**Comment by powerflash** [comment]
I use this code bat return only first 200 members

`#!/usr/bin/env python3.4

from telethon import TelegramClient

from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.functions.channels import GetAdminLogRequest
from telethon.tl.functions.channels import GetParticipantsRequest

from telethon.tl.types import ChannelParticipantsRecent
from telethon.tl.types import InputChannel
from telethon.tl.types import ChannelAdminLogEventsFilter
from telethon.tl.types import InputUserSelf
from telethon.tl.types import InputUser

# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.
api_id = XXXXXX # Your api_id
api_hash = 'xxxxxxxxxxxxxx' # Your api_hash
phone_number = '+3xxxxxxxx' # Your phone number

client = TelegramClient(phone_number, api_id, api_hash)
client.session.report_errors = False
client.connect()

if not client.is_user_authorized():
    client.send_code_request(phone_number)
    client.sign_in(phone_number, input('Enter the code: '))


channel = client(ResolveUsernameRequest('MY_CHANNEL')) # Your channel username

user = client(ResolveUsernameRequest('Username')) # Your channel admin username
admins = [InputUserSelf(), InputUser(user.users[0].id, user.users[0].access_hash)] # admins
admins = [] # No need admins for join and leave and invite filters

filter = None # All events
filter = ChannelAdminLogEventsFilter(True, False, False, False, True, True, True, True, True, True, True, True, True, True)
cont = 0
list = [0,100,200,300]
for num in list:
        result = client(GetParticipantsRequest(InputChannel(channel.chats[0].id, channel.chats[0].access_hash), filter, num, 100))
        for _user in result.users:
                print( str(_user.id) + ';' + str(_user.username) + ';' + str(_user.first_name) + ';' + str(_user.last_name)  )
                with open(''.join(['users/', str(_user.id)]), 'w') as f: f.write(str(_user.id))
`

**Comment by Sidus00** [comment]
So is it now possible to retrieve full list of members of an entity?

**Comment by Lonami** [comment]
@Sidus00 yes.

**Comment by Sidus00** [comment]
I know I maybe asking something obvious, but is there a way to export list of users from groups in which I am not an admin?

**Comment by Lonami** [comment]
@Sidus00 can you from official apps? If the answer is yes, the library can too.

**Comment by Sidus00** [comment]
From the GUI app I can view participants and get username but I can't find a way to retrieve it programmatically

**Comment by Perec-s-Hiltona** [comment]
Hello Lonami ! ( the question is translated from Russian by Google transalte)

I got a list of contacts and it has a type ... how do I extract certain data, for example last_name. Should I use a regular expression?

from telethon import *
from telethon.tl import *
from telethon.tl.types import *
from telethon.tl.functions.contacts import *

...
    def get_all_contacts(self):
        self.client=TelegramClient('session',config.api_id,config.api_hash)
        self.client.connect()
        #
        self.contacts=self.client(GetContactsRequest(0))
        print(type(self.contacts))
        print(self.contacts)
...

**Comment by vrl-evan** [comment]
@Sidus00 Is there any way to get the group membercount which I am not an admin?
