### ISSUE TITLE
How to send picture message from my system path ( like, home/Desktop/image.jpeg) to my contacts

### ISSUE THREAD

**Issue by Shiva-android** [LonamiWebs/Telethon#179]
hi
   I am new to telegram api, how to send image to my telegram contacts by using telethon api..

**Comment by Shiva-android** [comment]
contacts = client.invoke(GetContactsRequest(""))
print(contacts)
for p in contacts.users:
client.send_media_file(InputMediaUploadedPhoto("/home/Desktop/pic.png"), p.id, p.access_hash)   

@Lonami , i have tried this one, but its not working, can u guide me for right one

**Comment by Lonami** [comment]
No, I can't guide you. If you don't have the time to read the `README.rst` (and check out the example it mentions), I don't have time to help you.
