### ISSUE TITLE
SessionPasswordNeededError

### ISSUE THREAD

**Issue by muminoff** [LonamiWebs/Telethon#182]
I am experiencing `SessionPasswordNeededError` on `client.sign_in`.

Is there any way to work around this?

```python
telethon.errors.rpc_errors_401.SessionPasswordNeededError: (SessionPasswordNeededError
(...), 'Two-steps verification is enabled and a password is required.')
```

**Comment by rayeshman** [comment]
Two-steps verification is enabled and you need to also enter that, after `client.sign_in(PHONE, CODE) ` create a new line and put this `client.sign_in(password=PASS)` and done!

**Comment by muminoff** [comment]
@rayeshman thanks! 👍

**Comment by Lonami** [comment]
Thanks @rayeshman :)

Although you have probably figured it out already, this is implemented on the `InteractiveTelegramClient` too @muminoff, which the `README.rst` advises to read.

**Comment by shakibm83** [comment]
> Two-steps verification is enabled and you need to also enter that, after `client.sign_in(PHONE, CODE) ` create a new line and put this `client.sign_in(password=PASS)` and done!

You also need use try/except like this:
![carbon](https://user-images.githubusercontent.com/77733647/140621287-c7ce19c7-5551-4033-908c-426dddf6c4f5.png)
