### ISSUE TITLE
remove conversation

### ISSUE THREAD

**Issue by froxplus** [LonamiWebs/Telethon#187]
Hi
is there any function to entirely remove a conversation in order to don't show in dialogs?
i know there are to function for deleting messages. but how about a dialog?

**Comment by cher-nov** [comment]
Try `messages.deleteHistory`:

https://lonamiwebs.github.io/Telethon/methods/messages/delete_history.html
https://core.telegram.org/method/messages.deleteHistory (outdated, but with arguments descriptions)

**Comment by Lonami** [comment]
[Here are more](https://lonamiwebs.github.io/Telethon/index.html?q=delete). As a side note, I know that clearing the history may leave the chat empty (but the dialog still accessible) even when using the official clients. No clue about that.
