### ISSUE TITLE
joint group telegram 

### ISSUE THREAD

**Issue by arta6667** [LonamiWebs/Telethon#189]
`from telethon import TelegramClient`
`from telethon.tl.functions.messages import ImportChatInviteRequest`
`api_id = ++++`
`api_hash = '+++++++++++++++++++++'`
`client = TelegramClient('+1 ++++++', api_id, api_hash)`
`client.connect()`
`updates = client(ImportChatInviteRequest('GQVuGUG5pPEBxM6tQAeqqA'))`
But I have this error 

`Traceback (most recent call last):`
`updates = client(ImportChatInviteRequest('GQVuGUG5pPEBxM6tQAeqqA'))`
   `TypeError: 'TelegramClient' object is not callable`

**Comment by Lonami** [comment]
Upgrade.

**Comment by arta6667** [comment]
i upgrade this and is work..
how i can export all member in group ?
i use this 

`dialogs entities = client.get_dialogs(1),`
`entity = entities[0],`
`r = client(GetFullChatRequest(chat_id=int(entity.id))),`

i have this erorr

`telethon.errors.rpc_errors_400.PeerIdInvalidError: (PeerIdInvalidError(...), 'An invalid Peer was used. Make ,`sure to pass the right peer type.') `

**Comment by cher-nov** [comment]
@arta6667, create another issue for this question.

**Comment by Lonami** [comment]
@cher-nov no need to this has been discussed a lot of times. Megagroups are [channels](https://lonamiwebs.github.io/Telethon/methods/channels/get_full_channel.html), with the [megagroup](https://lonamiwebs.github.io/Telethon/constructors/channel.html) attribute conveniently set to `True` when this is the case.
