### ISSUE TITLE
Update pypi version

### ISSUE THREAD

**Issue by k1-hedayati** [LonamiWebs/Telethon#19]
Hello,
The pip version still has 2fa issue, please update pypi version

**Comment by XyLoNaMiyX** [comment]
It has been a long time since the last release to `PyPi`, but the reason for this is because I didn't consider there were enough changes to release another version. However and since probably more people are waiting for it too, I will take a look at this soon.

**Comment by k1-hedayati** [comment]
It is not about changes, The pypi version is broken! You can't login if you have enabled 2fa

**Comment by XyLoNaMiyX** [comment]
Some day I'll learn how to upload to PyPi right at the first attempt… Anyway, I've uploaded the `v0.7.0.1` (it's only `v0.7`, but PyPi doesn't allow editing my failed attempts). You should be able to `sudo -H pip install --upgrade telethon`.

**Comment by k1-hedayati** [comment]
Thanks
