### ISSUE TITLE
export all member in megagroup ?

### ISSUE THREAD

**Issue by arta6667** [LonamiWebs/Telethon#190]
`dialogs entities = client.get_dialogs(1),` 
`entity = entities[0],` 
`entity.megagroup ` 
`True` 
`r = client(GetFullChatRequest(chat_id=int(entity.id))),` 
i have this erorr 👍 
`telethon.errors.rpc_errors_400.ChatIdInvalidError: (ChatIdInvalidError(...), 'Invalid object ID for a chat. Make sure to pass the right types.')`

**Comment by Lonami** [comment]
[Quote](https://github.com/LonamiWebs/Telethon/issues/189#issuecomment-321813162):

> […] this has been discussed a lot of times. Megagroups are [channels](https://lonamiwebs.github.io/Telethon/methods/channels/get_full_channel.html), with the [megagroup](https://lonamiwebs.github.io/Telethon/constructors/channel.html) attribute conveniently set to `True` when this is the case.

Please, *please* **read** through the existing issues and wiki and `README` and StackOverflow and anywhere but make sure you've looked enough before asking dumb questions.

**Comment by arta6667** [comment]
dear Lonami i search and can not found answer for this erorr
please help and tel me how i can export all member in megagroup?????

**Comment by arta6667** [comment]
i use this command
`r = client(GetFullChannelRequest(entity))`
`r.users`
[]
but is empty

**Comment by Lonami** [comment]
> but is empty

#176

**Comment by Lonami** [comment]
Seems like [`GetParticipantsRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/get_participants.html) is a thing.

**Comment by arta6667** [comment]
tanx Lonami  .
`GetParticipantsRequest`
`channel:InputChannel    == entity` 
 `filter:ChannelParticipantsFilter ` 
`offset:int ` 
`limit:int `
how use filter for Export member ???
