### ISSUE TITLE
Hello, echobot?

### ISSUE THREAD

**Issue by TheRoboKitten** [LonamiWebs/Telethon#192]
Hello, I would like my bot to echo messages back to me/users much like this:

https://github.com/TheRoboKitten/Telegram-Explorer/blob/master/explorer.py

What is the best way to go about this on telethon?

Thanks,
TRK

**Comment by Lonami** [comment]
You add an [update handler](https://github.com/LonamiWebs/Telethon/wiki/Working-with-updates) and cache your users by `{id: user}` in some dictionary and then you call `.send_message(user, msg)`. Sounds about right to me.

**Comment by TheRoboKitten** [comment]
Thank you :)
