### ISSUE TITLE
Invoke Forward Messages Requests broken?

### ISSUE THREAD

**Issue by TheRoboKitten** [LonamiWebs/Telethon#193]
Here is my code:

```
from telethon import TelegramClient
from telethon.tl.types import UpdateNewMessage
from telethon.tl.types import InputPeerChat
from telethon.tl.types import Message
import json
import re
api_id = *************************************************
api_hash = '***************************************************'
# 'session_id' can be 'your_name'. It'll be saved as your_name.session
client = TelegramClient('session_id', api_id, api_hash)
client.connect()


if not client.is_user_authorized():
  client.send_code_request('+1***************')
  client.sign_in('+1**********', input('Enter code: '))
# Now you can use the connected client as you wish



def update_handler(d):
    word3 = MY CHAT ID
    # On this example, we just show the update object itself
    d = str(d)
    #print(d)
    #testChannel
    re1 = '(chat_id: )(?:[0-9][0-9]+)(,)' 

    rg = re.compile(re1,re.IGNORECASE|re.DOTALL)
    m = rg.search(d)
    if m:
        word1=m.group(0)
        word2=word1.replace('chat_id: ', '')
        word3=word2.replace(',', '')
        word4=int(word3)
        print(word4)
        source_chat = InputPeerChat(word4)
        #testGroup: 
        dest_chat_id = *****
        total_count, messages, senders = client.get_message_history(
                                source_chat, limit=10)
        msg = messages[0]    
        dest_chat = InputPeerChat(dest_chat_id)
        client.invoke(ForwardMessagesRequest(from_peer=source_chat, id=[msg.id], random_id=[generate_random_long()], to_peer=dest_chat))







# From now on, any update received will be passed to 'update_handler'
client.add_update_handler(update_handler) 



input('Press <ENTER> to exit...')
client.disconnect()
```

**Comment by TheRoboKitten** [comment]
Everything is broke, abandoning this project.

**Comment by Lonami** [comment]
In which way is `ForwardMessagesRequest` broken? Also, I don't see the `import` line for it.

**Comment by TheRoboKitten** [comment]
Well it's documented in 2 places I think you said it was broken. Its not
that it is broken, but the command is so intricate and picky..... Check out
explorer.py in my telethon explorer fork.

**Comment by Lonami** [comment]
> I think you said it was broken. 

The singular form, "forward message", seems to be broken.

> but the command is so intricate and picky

But could you run it?

**Comment by TheRoboKitten** [comment]
But that's not broken either, it only works from peer to peer and
non-supergroups.

**Comment by TheRoboKitten** [comment]
I think telegram api might have changed, I fixed this by finding a
documentation for the current telegram api requests (I don't remember where
I saw it but it's out there) :)

**Comment by Lonami** [comment]
> for the **current** telegram api requests

I'm using [layer 70](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl) (as of now) which seems the latest so… I'm clueless.

**Comment by TheRoboKitten** [comment]
It all works don't worry, but you have documented that Forward message
request is broke. And on the Forward messages request in your doc.... It
does not have the correct request inputs only for message request and
mostly everything needs to be an integer as an array except from and to
peer.
