### ISSUE TITLE
mtproto_sender warnings. What do they mean?

### ISSUE THREAD

**Issue by alexvelickiy** [LonamiWebs/Telethon#194]
Hi,

in Telethon log I'm constantly getting mtproto_sender warnings of two types:
Ack found for the a request
Pong confirmed a request

What do they mean?

I connect to Telegram client on each request. For each request I retrieve dialogs with get_dialogs() and on some add update handler with add_update_handler()

**Comment by Lonami** [comment]
They mean you should probably upgrade Telethon. When I first added logging I thought those were important and I categorized them as "warnings", but they're just information, really. All the library uses `logging.debug` now.

> Ack found for the a request

#22 

> Pong confirmed a request

When the updates handler sends a ping.
