### ISSUE TITLE
PermissionError:[errno 13] Permission Denied

### ISSUE THREAD

**Issue by Optictrollz** [LonamiWebs/Telethon#196]
python3 setup.py gen_tl Detected previous TLObjects. Cleaning... Traceback (most recent call last): File "setup.py", line 33, in <module> generator.clean_tlobjects() File "/zenai/telethon_generator/tl_generator.py", line 34, in clean_tlobjects self._rm_if_exists(name) File "/zenai/telethon_generator/tl_generator.py", line 21, in _rm_if_exists shutil.rmtree(file) File "/usr/lib/python3.5/shutil.py", line 474, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/usr/lib/python3.5/shutil.py", line 432, in _rmtree_safe_fd onerror(os.unlink, fullname, sys.exc_info()) File "/usr/lib/python3.5/shutil.py", line 430, in _rmtree_safe_fd os.unlink(name, dir_fd=topfd) PermissionError: [Errno 13] Permission denied: 'set_client_dh_params.py'

**Comment by Lonami** [comment]
Seems like you don't have permission to delete certain files. Run as root is the only thing I can think of. Also please format your error logs more nicely next time.
