### ISSUE TITLE
RPCError when uploading large a file: Part 0 of the file is missing from storage.

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#2]
For some strange reason, a `RPCError` saying "_Part 0 of the file is missing from storage._" is raised when sending files larger than 10MB. If the file size is less, no error occurs.

However, all the parts are sent (part 0 included, tested with a `print`)

**Comment by MuallimCh** [comment]
Use upload.saveBigFilePart in case the full size of the file is more than 10 MB and upload.saveFilePart for smaller files.

Reference: https://core.telegram.org/api/files

**Comment by XyLoNaMiyX** [comment]
I use `SaveBigFilePartRequest` for files larger than 10MB, but it errors saying that the part number 0 is missing (as I stated before) :)

Could you please try sending a file larger than 10MB with the latest version? Does it work for you?

**Comment by MuallimCh** [comment]
On my opinion, for first sending .. mtproto_sender.py still occupied by listen update_handler. I think implementing asyncio for mtproto_sender.py is a better then thread.

Another consideration is as noted [here](https://core.telegram.org/api/files) in last chapter:
> It is recommended that large queries (upload.getFile, upload.saveFilePart) **be handled through a separate session and a separate connection**, in which no methods other than these should be executed. If this is done, then data transfer will cause less interference with getting updates and other method calls.

I'm sorry not testing yet. Just my two cents.

**Comment by Lonami** [comment]
(Yay! That was a silly long lasting bug)
