### ISSUE TITLE
[Q] How to delete a message

### ISSUE THREAD

**Issue by k1-hedayati** [LonamiWebs/Telethon#20]
Using API is so hard, can you help me remove a message using client? I have chat id and message id but I don't know how to use it. Delete message seems only accept a 4 digit number but I don't know what extactly I should put there
https://core.telegram.org/method/messages.deleteMessages

I do this and I don't know what it does
```python
In [117]: z = client.invoke(messages.delete_messages.DeleteMessagesRequest([2887]))

In [118]: z
Out[118]: messages.affectedMessages#84d19185 pts:int pts_count:int = messages.AffectedMessages
```

**Comment by XyLoNaMiyX** [comment]
Simply check `telethon/tl/functions/messages/delete_messages.py` next time. You just need to pass a list with the message ID's and invoke it:
```python
result = client.invoke(DeleteMessagesRequest([some msg id]))
```

**Comment by XyLoNaMiyX** [comment]
> Delete message seems only accept a 4 digit number

Nowhere says it has to be a 4 digit number. You just pass the ID of the message you want to delete.

**Comment by k1-hedayati** [comment]
How do I get that message number?

I try to get history with no success


```
In [127]: client.get_message_history(client.get_dialogs()[0][0])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-127-432629b6c22c> in <module>()
----> 1 client.get_message_history(client.get_dialogs()[0][0])

/home/k1/.virtualenv/bot/lib/python3.5/site-packages/telethon/telegram_client.py in get_message_history(self, entity, limit, offset_date, offset_id, max_id, min_id, add_offset)
    333                 max_id=max_id,
    334                 min_id=min_id,
--> 335                 add_offset=add_offset))
    336 
    337         # The result may be a messages slice (not all messages were retrieved) or

/home/k1/.virtualenv/bot/lib/python3.5/site-packages/telethon/telegram_client.py in invoke(self, request, timeout)
    159             raise ValueError('You can only invoke MtProtoRequests')
    160 
--> 161         self.sender.send(request)
    162         self.sender.receive(request, timeout)
    163 

/home/k1/.virtualenv/bot/lib/python3.5/site-packages/telethon/network/mtproto_sender.py in send(self, request)
    102             # Finally send our packed request
    103             with BinaryWriter() as writer:
--> 104                 request.on_send(writer)
    105                 self.send_packet(writer.get_bytes(), request)
    106 

/home/k1/.virtualenv/bot/lib/python3.5/site-packages/telethon/tl/functions/messages/get_history.py in on_send(self, writer)
     33     def on_send(self, writer):
     34         writer.write_int(GetHistoryRequest.constructor_id, signed=False)
---> 35         self.peer.on_send(writer)
     36         writer.write_int(self.offset_id)
     37         writer.tgwrite_date(self.offset_date)

AttributeError: 'NoneType' object has no attribute 'on_send'
```

**Comment by XyLoNaMiyX** [comment]
You are not supposed to pass a dialog to `get_message_history`. Internally, `get_input_peer` fails and returns `None`. Maybe an error would be better than returning `None`. Either way, all the information you need is under [`interactive_telegram_client.py`](https://github.com/LonamiWebs/Telethon/blob/HEAD/telethon/interactive_telegram_client.py) anyway, which should have enough examples.

**Comment by k1-hedayati** [comment]
Thank you

**Comment by FlashAJ** [comment]
Deleted messages not work! Why???
`from telethon import TelegramClient
from telethon.tl.functions.messages import DeleteMessagesRequest
group='blablabla'

api_id = ***
api_hash ='***' 

session='session_name'
client = TelegramClient(session, api_id, api_hash)
client.connect()

messages=client.get_messages(group,1)
result = client.invoke(DeleteMessagesRequest([messages[0].id]))
print(result)
`
As a result gives:
_AffectedMessages(pts=1918, pts_count=0)_

All the Internet was in the air. I tried a lot of everything - nothing does not help ...

**Comment by FlashAJ** [comment]
Everybody help me???

**Comment by FlashAJ** [comment]
No one helped me, but I myself found what was the problem. And so, as on the Internet there is no detailed answer, I will answer myself:
Instead ````from telethon.tl.functions.messages import DeleteMessagesRequest```` need to use ````from telethon.tl.functions.**channels** import DeleteMessagesRequest````
And add InputChannel:
````channel = client(ResolveUsernameRequest(group))
result = client.invoke(DeleteMessagesRequest(channel, [messages[0].id]))````

**Comment by Lonami** [comment]
That depends on where the message is. Either way this is incredibly old, and you should use `client.delete_messages` instead.

**Comment by FlashAJ** [comment]
Thank you. But I did not find information about this team, and found only this topic about it. While the old method works, but as soon as I need it, I immediately use the new command. ;)))
