### ISSUE TITLE
how to convert 

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#203]
hi .
I want to search one channel and get posts history.
How do I do this?
in first I use this method : 

`result_search=client(SearchRequest('xxx',1))`
and then use `result_search` for get posts : 
`result = client(GetHistoryRequest(`
    `result_search,`
   ` limit=1,`
    `offset_date=None,`
    `offset_id=0,`
    `max_id=0,`
    `min_id=0,`
   ` add_offset=0`
`))`
but error show .
my question is : how can I  convert  "Found" object to "peer" in telethon ?

**Comment by Lonami** [comment]
I don't really understand what you want to do but reading the documentation and checking what **types** the method require you should be able to find your way. Remember to read the `README.rst`, the examples, and the wiki too. May be helpful.

**Comment by alihossein** [comment]
Yes, I explained badly
How do I get last posts from channels that are extracted from the `result_search=client(SearchRequest('channel_name',1))` command
