### ISSUE TITLE
how can get posts of one channel stream ?

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#205]
hi, everybody
how can we get posts of one channel stream?
please explain step by step.
thanks

**Comment by Lonami** [comment]
You can edit the title of your issues to avoid opening new unnecessary ones…

> please explain step by step

This is not StackOverflow. RTFM. [Are you even trying](https://lonamiwebs.github.io/Telethon/methods/messages/get_history.html)?
