### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'lang_code'

### ISSUE THREAD

**Issue by serrufSe** [LonamiWebs/Telethon#209]
Hi, I try to create Session object and then use it in TelegramClient but got the following error:
```
AttributeError: 'Session' object has no attribute 'lang_code'
```
JsonSession has such an attribute (as long as device_model etc), but there is type checking in TelegramBareClient
```
if isinstance(session, str) or session is None:
    session = JsonSession.try_load_or_create_new(session)
elif not isinstance(session, Session):
    raise ValueError(
        'The given session must be a str or a Session instance.')
```

**Comment by Lonami** [comment]
> I try to create Session object

Do you need to do so? Can't you simply pass a `str`?

**Comment by serrufSe** [comment]
>Do you need to do so?
Yes. I can't save session_name.session file in the same place where run TelegramClient

**Comment by Lonami** [comment]
> Do you need to do so?

Passing a `str`? You can also pass an absolute path, it should work. Either that, or create instances of `JsonSession` until migration is complete.

I don't know where you got that code from but master has this:
https://github.com/LonamiWebs/Telethon/blob/c0bae1d608571bd8766c74338408c2b9759ab20b/telethon/telegram_client.py#L91-L95

Consider upgrading.

**Comment by serrufSe** [comment]
I use 0.11.5, my fault.

**Comment by Lonami** [comment]
No problem :)
