### ISSUE TITLE
Please give me a documentation!

### ISSUE THREAD

**Issue by msa21974** [LonamiWebs/Telethon#21]
Hi Dears,
Thank you for this best project in this section
there is a lot of class with a lot of attributes and a lot of function with a lot of parameter 😅
is there a document for help us to realize them?

thanks in advance.

**Comment by XyLoNaMiyX** [comment]
Well, besides the [official, outdated documentation](https://core.telegram.org/methods), I don't know of any other place where you could get documentation.

My suggestion is that you take a look at how the [`interactive_telegram_client.py`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/interactive_telegram_client.py) works and also how the [`telegram_client`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py) itself works. There are a few things that I don't know either (such as the `pts` integer on some methods), and to be honest I would love to see a wiki for the Telegram API. But this obviously is not an easy task with over 1,000 methods and types.

So as a final advice, take a look at the code, experiment with the methods, check out how the results from invoking certain methods look, and be patient.
