### ISSUE TITLE
enable debug logging

### ISSUE THREAD

**Issue by Arcanum7** [LonamiWebs/Telethon#210]
how to enable debug logging in telethon?

**Comment by serrufSe** [comment]
Standart way
```
logger = getLogger('telethon')
logger.addHandler(StreamHandler())
logger.level = DEBUG
```

**Comment by Lonami** [comment]
Some projects have empty wikis rather than hiding them, but Telethon doesn't. [The wiki](https://github.com/LonamiWebs/Telethon/wiki/Troubleshooting-issues) also has this information, thanks @serrufSe ^^

**Comment by a0s** [comment]
@Lonami your link is broken BTW

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/wiki/Troubleshooting
