### ISSUE TITLE
ipv6 connecting

### ISSUE THREAD

**Issue by GetMePower** [LonamiWebs/Telethon#211]
When using ipv6, the telegram server does not respond.

**Comment by Lonami** [comment]
Closing in favor of #112. Telethon currently selects the first one it finds, which happens to be the IPv4. Although I'm closing this, how are you currently using IPv6?

**Comment by GetMePower** [comment]
Telegram will not allow you to use ipv6 if you don't force to do this. I tried this with both using the ipv6 proxy and with system access.

**Comment by Lonami** [comment]
I still don't understand how you try connecting through an IPv6 address. Could you show an example with code?

**Comment by GetMePower** [comment]
The simplest version that I used is the use of the proxy ipv6 using PySocks.
In all clients Telegram I know, you must enable it in the connection settings, otherwise Telegram ignores this. 

In the Telegram Desktop, for example, the addresses of the servers in the ipv6 representation if option "Try connecting through IPV6".

```
from telethon import TelegramClient
import socks

api_id = 1111
api_hash = 'hash'
client = TelegramClient('session_id', api_id, api_hash, proxy=(socks.SOCKS5, 'ip', port, 1, 'login', 'pass'))
client.connect()
if not client.is_user_authorized():
    client.send_code_request('+300000')
    client.sign_in('+300000', input('Code: '))`
```

**Comment by Lonami** [comment]
Perhaps because we're [not](https://github.com/LonamiWebs/Telethon/blob/1a6231472e0fb60bb65a7cfbbc5734ac61c0880b/telethon/extensions/tcp_client.py#L25) specifying `AF_INET6` as documented [here](https://docs.python.org/3/library/socket.html#socket.AF_INET6) :P That's why it should be done when implementing different transport layers.

**Comment by Lonami** [comment]
Cannot test it, I probably haven't configured my machine well-enough to support IPv6 addresses: `"OSError: [Errno 101] Network is unreachable"`

**Comment by GetMePower** [comment]
I used the following code to connect. This proxy uses tunneling and gets IPv6 address at the output.

```
client = TelegramClient('session_id', api_id, api_hash, proxy=(socks.SOCKS5, '81.167.22.75', 10001, 1, 'user', 'pass'))
client.connect()
```

```
Traceback (most recent call last):
  File "D:\tg\tgclient.py", line 8, in <module>
    client.connect()
  File "D:\Program Files\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 146, in connect
    return super().connect()
  File "D:\Program Files\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 133, in connect
    self._sender.connect()
  File "D:\Program Files\Python\Python36-32\lib\site-packages\telethon\network\mtproto_sender.py", line 36, in connect
    self.transport.connect()
  File "D:\Program Files\Python\Python36-32\lib\site-packages\telethon\network\tcp_transport.py", line 22, in connect
    timeout=round(self.timeout.seconds))
  File "D:\Program Files\Python\Python36-32\lib\site-packages\telethon\extensions\tcp_client.py", line 40, in connect
    self._socket.connect((ip, port))
  File "D:\Program Files\Python\Python36-32\lib\site-packages\socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "D:\Program Files\Python\Python36-32\lib\site-packages\socks.py", line 817, in connect
    raise GeneralProxyError("Socket error", error)
```

**Comment by Lonami** [comment]
> `GeneralProxyError`

Hm, not very helpful :/

But even without a proxy, if you try to connect through Telegram's IPv6 addresses, it doesn't seem to work. Not sure what I'm missing.
