### ISSUE TITLE
Working with updates

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#212]
Hi, guy.
I read the wiki.([this page](https://github.com/LonamiWebs/Telethon/wiki/Working-with-updates))
 does exactly **passive** mean in this sentence ??

> Important note: Updates are currently handled in a passive way, so not all may be received. Read below for more information.

**Comment by Lonami** [comment]
It means I just call `.receive()` on the socket. If Telegram sends me something (i.e., an update), it will be read. But I don't care about the updates `seq`, or `date`, or anything, as I should.

**Comment by alihossein** [comment]
So there is no guarantee for getting all updates?
I want to get all the channels` updates?

**Comment by Lonami** [comment]
Closing in favor of #237.
