### ISSUE TITLE
i'm confused in working with Telethon library 

### ISSUE THREAD

**Issue by InnocentCivilian** [LonamiWebs/Telethon#213]
is this library written under python2?because I'm really confused
can someone write a code to do anything,I mean "anything" for me to see an output
like this code:
`---functions---
account.checkUsername#2714d86c username:string = Bool`
what does #2714d86c mean?
and Supposing that that this code has been written in py2 when i rewrite it in py3 like this:
`>>> from telethon.tl.functions.account import CheckUsernameRequest
>>> fhand=account.checkUsername(durov:string = Bool)
  File "<stdin>", line 1
    fhand=account.checkUsername(durov:string = Bool)
                                     ^
SyntaxError: invalid syntax
`
this happends
Thanks!

**Comment by Lonami** [comment]
> is this library written under python2

No, and it's the first thing you'll read:
> Pure Python 3 Telegram client library

> Telethon is Telegram client implementation in Python 3 which uses the latest available API of Telegram. Remember to use pip3 to install!

> If you get something like "SyntaxError: invalid syntax" on the from error line, it's because pip defaults to Python 2. Use pip3 instead.

> launch an interactive python3 session

Now, back to your "issue".

> ---functions--- account.checkUsername#2714d86c username:string = Bool

Er, that's the "TL definition", the long README has a section discussing it. You have nothing to do with that.

> 2714d86c

It means that 0x2714d86c is the ID for that function. Again, the library will take care of this.

> and Supposing that that this code has been written in py2 when i rewrite it in py3 like this:

What are you even trying?

---

Okay first of all you have to do **nothing** with the `.tl` file. Leave it alone. Now, read the `README`, conveniently called "read me". It has nice examples, like how to connect, etc. Also check the wiki. And read the example.

**Comment by danog** [comment]
Let me clarify this for you with a simple pseudocode:

```
while self.hasQuestion():
    try:
        self.parseEnglish(telethon.fetchREADME())
    except NotUnderstoodError:
        try:
            self.parseEnglish(telethon.fetchREADME())
        except NotUnderstoodError:
            try:
                self.parseEnglish(python.fetchDocs())
            except NotUnderstoodError:
                raise KMSError()

```
