### ISSUE TITLE
Odd Error in telethon/crypto/rsa.py

### ISSUE THREAD

**Issue by Herny64** [LonamiWebs/Telethon#214]
Hi, when running ./try_telethon.py i got this Error:
ValueError: No PEM start marker "b'-----BEGIN RSA PUBLIC KEY-----'" found
It was from the imported rsa lib the telethon/crypto/rsa.py is using.
I was able to solve this by putting a lower case b in front of the RSA-Strings in the telethon/crypto/rsa.py

Just thought I should mention it here, maybe it helps someone in the future :D

**Comment by Lonami** [comment]
What version of Python and of the `rsa` module are you using?

**Comment by Herny64** [comment]
Python 3.4.5
dev-python/rsa-3.2.3-r1

**Comment by Lonami** [comment]
I'm using version 3.4.2 of RSA:
```$ pip show rsa
Name: rsa
Version: 3.4.2
```

Maybe consider upgrading? They probably added support for public keys as `str`ing rather than only `bytes`. Thanks for the report though, it may come in handy for other people :D
