### ISSUE TITLE
SearchRequest not working in some cases

### ISSUE THREAD

**Issue by pabloalonsolopez** [LonamiWebs/Telethon#215]
I'm testing SearchRequest to search messages over different entities, but only works with megagroups:

**TEST 1: Channel - megagroup**
`
results = client(SearchRequest(
        peer=InputPeerChannel(channel_id=1000910549, access_hash=5858828414308925479),
        filter=InputMessagesFilterEmpty(),
        q="Hi",
        min_date=None,
        max_date=None,
        max_id=0,
        limit=100,
        from_id=InputUserEmpty(),
        offset=0
    )
)
print(results)
`

**Working as expected, messages are returned**
`
{ChannelMessages: {pts: 324095, count: 126, messages: [{out: None, mentioned: None, media_unread: None, silent: None, post: None, id: 269201, from_id: 276239621, to_id: {channel_id: 1000910549}, fwd_from: None, via_bot_id: None, reply_to_msg_id: None, date: 2017-08-27 02:59:23, message: "Hi", media: None, reply_markup: None, entities: [], views: None, edit_date: None}...
`

**TEST 2: Channel - not megagroup**
`
results = client(SearchRequest(
        peer=InputPeerChannel(channel_id=1058430139, access_hash=-4141720121263079359),
        filter=InputMessagesFilterEmpty(),
        q="Hi",
        min_date=None,
        max_date=None,
        max_id=0,
        limit=100,
        from_id=InputUserEmpty(),
        offset=0
    )
)
print(results)
`

**Not working as expected, ChatAdminRequiredError raised**
`
Traceback (most recent call last):
  File "telegram/scripts/test.py", line 36, in <module>
    offset=0
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 109, in receive
    remote_msg_id, remote_seq, reader, updates)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 207, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 355, in _handle_rpc_result
    raise error
telethon.errors.rpc_errors_400.ChatAdminRequiredError: (ChatAdminRequiredError(...), 'Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours).')
`

**TEST 3: Chat**
`
results = client(SearchRequest(
        peer=InputPeerChat(chat_id=174126852),
        filter=InputMessagesFilterEmpty(),
        q="Prueba",
        min_date=None,
        max_date=None,
        max_id=0,
        limit=100,
        from_id=InputUserEmpty(),
        offset=0
    )
)
print(results)
`

**Not working as expected, No messages are returned in spite of messages exist satisfying the query**
`
{Messages: {messages: [], chats: [], users: []}}
`

**TEST 4: User**
`
results = client(SearchRequest(
        peer=InputPeerUser(user_id=232552588, access_hash=-5501550334760097695),
        filter=InputMessagesFilterEmpty(),
        q="Hi",
        min_date=None,
        max_date=None,
        max_id=0,
        limit=100,
        from_id=InputUserEmpty(),
        offset=0
    )
)
print(results)
`

**Not working as expected. UserIdInvalidError raised**
`
Traceback (most recent call last):
  File "telegram/scripts/test.py", line 70, in <module>
    offset=0
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 205, in invoke
    request, updates=updates
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 276, in invoke
    self._sender.receive(request, updates=updates)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 109, in receive
    remote_msg_id, remote_seq, reader, updates)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 207, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 355, in _handle_rpc_result
    raise error
telethon.errors.rpc_errors_400.UserIdInvalidError: (UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types.')
`

**Comment by Lonami** [comment]
> **TEST 4: Chat**

> `peer=InputPeerUser`

User. You said chat.

> `'Invalid object ID for an user. Make sure to pass the right types.'`

**Comment by pabloalonsolopez** [comment]
Sorry, fixed issue renaming Group -> Chat and Chat -> User

**Comment by pabloalonsolopez** [comment]
There is no permissions restrictions to execute this telegram function. I have implemented other telegram libraries like telegram-mtproto and function works as expected in all cases.

**Comment by Lonami** [comment]
> No messages are returned in spite of messages exist satisfying the query

The query is **not** satisfied because:
`from_id=InputUserEmpty()`

You're specifying the sender must be an "empty" user. You should leave that set to `None`; and I found a bug which I'll fix now.

**Comment by pabloalonsolopez** [comment]
Yeah, I was not able to specify None due to the the issue you mention:

utils.py, get_input_user function, line 116:

if type(entity).subclass_of_id

NoneType has no subclass_of_id

**Comment by Lonami** [comment]
So there's that. Did you test the fix for the test 4 as I suggested?

**Comment by Lonami** [comment]
Regarding with your test 4, can you work with the "full" user rather than `InputUser` alone? It should be cast accordingly. This way you avoid hardcoding the ID and hash.

**Comment by Lonami** [comment]
Regarding with your test 2, someone suggested to pass `from_id=None` (which you couldn't do before), see if this solves the issue. Of course, you'd need to test with the upstream version.

**Comment by pabloalonsolopez** [comment]
Just for your knowledge, passing from_id=None make all 4 test to work successfully. Thanks a lot.

**Comment by Lonami** [comment]
I'll note that on the wiki. Thanks.
