### ISSUE TITLE
finding all messages Between two datetimes using SearchRequest

### ISSUE THREAD

**Issue by imdoneok** [LonamiWebs/Telethon#218]
Hi this is my sample code to find all messages Between two datetimes but it doesn't work at all maybe because i don't know what is 'filter' in 'SearchRequest' (or maybe not,however,explain these two please)
and also i tried with a few word in q argument but it didn't change anything
```python
from telethon import TelegramClient
from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.functions.messages import GetHistoryRequest
from telethon.utils import InputPeerChannel
import datetime
from telethon.tl.functions.messages import SearchRequest

client = TelegramClient('@SessID', api_id, api_hash)
client.connect()

username = 'gethappy'

channel_info = client.invoke(ResolveUsernameRequest(username))
cid = channel_info.peer.channel_id
ah = channel_info.chats[0].access_hash
mindate=datetime.datetime(2016, 2, 3, 13, 10,43)
maxdate=datetime.datetime(2016, 2, 4, 23, 38,59)
result = client.invoke(SearchRequest(InputPeerChannel(cid, ah),q=None,filter=None,min_date=mindate,max_date=maxdate,offset=None,max_id=None,limit=None))
```

**Comment by Lonami** [comment]
Just a few things, **only `from_id` can be None** as seen on the [documentation](https://lonamiwebs.github.io/Telethon/methods/messages/search.html) for this request.

`q` stands for query, so I guess you can just do `q=''`. [`filter`](https://lonamiwebs.github.io/Telethon/types/messages_filter.html) as the documentation says can be any of the linked.

**Comment by imdoneok** [comment]
so,any other idea about how can i find all messages?

**Comment by imdoneok** [comment]
Answer to myself: it might be useful to find the message posted after/before a date time and get all other messages in between using 'GetHistoryRequest' 
But How? :/

**Comment by Lonami** [comment]
Can't you simply use GetHistoryRequest?

**Comment by imdoneok** [comment]
i doubt that because GetHistoryRequest takes only one date parameter,How can i perform my task using GetHistoryRequest?

**Comment by Lonami** [comment]
Then just use the maximum date? And once the messages are below the minimum date stop calling `GetHistory`? Just think about it. I have no idea. Searching for empty strings should work but I don't know.

**Comment by jaymk1** [comment]
@imdoneok Did you manage to figure this out? Still stuck with a similar issue

**Comment by PATAPOsha** [comment]
```
from_date = datetime.strptime('14.05.2019 14:00:00', '%d.%m.%Y %H:%M:%S').replace(tzinfo=timezone.utc)
to_date = datetime.strptime('15.05.2019 14:00:00', '%d.%m.%Y %H:%M:%S').replace(tzinfo=timezone.utc)

pre_first_msg = bot.get_messages(channel, offset_date=from_date, limit=1)[0]
first_msg = bot.get_messages(channel, min_id=pre_first_msg.id, limit=1, reverse=True)[0]
last_msg = bot.get_messages(channel, offset_date=to_date, limit=1)[0]

messages_between = bot.get_messages(channel, min_id=first_msg.id, max_id=last_msg.id) + [first_msg, last_msg]
```

**Comment by Morteza-Gh-Kh** [comment]
I tested `SearchRequest` function and seems the issue is that the `min-date` and `max_date` arguments of `SearchRequest` are not working properly, these two arguments have no effect on the results.

**Comment by Lonami** [comment]
Related: #1482.
