### ISSUE TITLE
Getting the views number of a channel message without getting it from a dialog

### ISSUE THREAD

**Issue by amir3code** [LonamiWebs/Telethon#219]
I want to get the `views` part of a message (a channel's message). I know I can request for getting the history and it gives me this results:  

```
{'confirm_received': False,
 'confirmed': False,
 'constructor_id': 0,
 'date': datetime.datetime(2017, 8, 31, 8, 57, 11),
 'dirty': False,
 'edit_date': None,
 'entities': [messageEntityUrl#xxx offset:int length:int = MessageEntity],
 'from_id': xxx,
 'fwd_from': messageFwdHeader#xxx flags:# from_id:flags.0?int date:date channel_id:flags.1?int channel_post:flags.2?int = MessageFwdHeader,
 'id': xxx,
 'media': messageMediaWebPage#xxx webpage:WebPage = MessageMedia,
 'media_unread': None,
 'mentioned': None,
 'message': 'A sample message from my channel',
 'out': None,
 'post': None,
 'reply_markup': None,
 'reply_to_msg_id': None,
 'request_msg_id': 0,
 'responded': False,
 'send_time': None,
 'sent': False,
 'sequence': 0,
 'silent': None,
 'to_id': peerUser#xxx user_id:int = Peer,
 'via_bot_id': None,
 'views': 15189}
```
You see, there is a `views` property which I can dot and get it.
How can I get information about this message itself without having to request the whole channel for it?
Is it possible?

**Comment by Lonami** [comment]
How about requesting for the history, but `limit=1` message? Or maybe [`GetMessagesViewsRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_messages_views.html) I mean, [use the search](https://lonamiwebs.github.io/Telethon/?q=view).

**Comment by amir3code** [comment]
assume I have the id (which is `'id': xxx,` in this case I think) and I have the channel id (@mychannel) how can I get the message that its id number is `xxx` from `@mychannel`?

**Comment by Lonami** [comment]
Read the documentation. It tells you what the type of the parameters are.

**Comment by amir3code** [comment]
I dont know why the telegram has such an obscure documentation and is totally developer hostile :(
Thanks for your time, but I did not realize how can I get the `InputChannel` needed for requests like `GetMessagesRequest` and others. They all need an `InputChannel` Object which as you see here https://lonamiwebs.github.io/Telethon/types/input_channel.html no method can return it.
Actually the point is that the problem is with the channel_id and access_hash how can I get those?
Again thanks for your time :)

**Comment by Lonami** [comment]
I mean once you get the ID/hash combination from a `Channel` instance, you can save those as you wish or even hardcode them. There's also a request to resolve an username. Telethon will cast types like `Channel` into `InputChannel` and such automatically too.

**Comment by amir3code** [comment]
Aha, Now I think I got it!
Thanks, You are the best.

**Comment by Lonami** [comment]
There's also a private `._get_entity(username)` method on the `TelegramClient` because I would like a more friendly public name. Maybe `.resolve_peer()` or something. If you had any idea for the name that'd be nice.
