### ISSUE TITLE
Better handling of ack requests

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#22]
Sometimes at any random point in time, an `ack` request may be received, thus considering the invoked method to be confirmed. This will end the loop that checks whether the result was received yet or not, thus having a `None` result and failing at random points on the code.

The problem however is that there are some requests which do depend on the `ack` request to confirm the invoked method, such as the `LogoutRequest`. How to tell which should be confirmed and which shouldn't doesn't seem trivial, furthermore, this happens randomly (although it is more likely to happen if sending several `GetFileRequest`'s, personal experience).

Maybe one should look into the `tdesktop` source to check how they handle this kind of stuff.

**Comment by XyLoNaMiyX** [comment]
Perhaps `expect_ack=False` by default. If `ack` is received when `expect_ack=False`, then the request needs to be invoked again? Not sure, it would need testing.

**Comment by k1-hedayati** [comment]
Have you asked this from telegram guys?

**Comment by XyLoNaMiyX** [comment]
> Have you asked this from telegram guys?

No, but I would appreciate any help. However, I don't think asking them "hello my Python version doesn't work" would end good, so please if you help don't do that (or similar).

**Comment by k1-hedayati** [comment]
As I see it, receiving random `ack` isn't something related to implementation

**Comment by Lonami** [comment]
Most libraries ignore them anyway and it works so I'll close this to remove clutter.
