### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by majid4466** [LonamiWebs/Telethon#224]
`$ pip install telethon`
Collecting telethon
  Downloading Telethon-0.13.tar.gz (776kB)
    100% |████████████████████████████████| 778kB 166kB/s 

No files/directories in /tmp/pip-build-ivQOUe/telethon/pip-egg-info (from PKG-INFO)

What could the issue be?

**Comment by Lonami** [comment]
Whew, that was quick. Let me try the same command.

**Comment by Lonami** [comment]
```
$ sudo -H pip install telethon
[sudo] password for lonami: 
Collecting telethon
  Downloading Telethon-0.13-py3-none-any.whl (884kB)
    100% |████████████████████████████████| 890kB 871kB/s 
Requirement already satisfied: rsa in /usr/lib/python3.6/site-packages (from telethon)
Requirement already satisfied: pyaes in /usr/lib/python3.6/site-packages (from telethon)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3.6/site-packages (from rsa->telethon)
Installing collected packages: telethon
Successfully installed telethon-0.13
```

No clue actually. What system are you using? Have you tried rebooting, or running as either root/passing the `--local` flag?

**Comment by majid4466** [comment]
I am on `Ubuntu 16.04.1 LTS` and no, I have not tried any of your suggestions yet. I will and post back. Thanks for the super quick response.

**Comment by Lonami** [comment]
> super quick response

[Notifier for GitHub](https://github.com/sindresorhus/notifier-for-github-chrome) ;)

**Comment by majid4466** [comment]
With `$sudo -H pip install telethon` the result is the same. I looked for but didn't find how to use the `--local` flag. Restarting made no difference (and wondering why should it have ...).

However, `$ python --version` tells me I have **Python 2.7.12**. Could this be the issue?

**Comment by Lonami** [comment]
Yeah, Telethon is Python 3 only. The `README` says it a few times.
