### ISSUE TITLE
Problem in Client.connect()

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#225]
Hi.
why Sometimes, whenever I called client.connect() method I got this error:
`telethon.errors.rpc_errors.BadMessageError: (BadMessageError(...), 'msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno).')
`
Please help me

**Comment by Lonami** [comment]
> Please help me

Please use [search](https://github.com/LonamiWebs/Telethon/issues/195).
