### ISSUE TITLE
Cannot invoke requests from within update handlers

### ISSUE THREAD

**Issue by leshark** [LonamiWebs/Telethon#226]
Hello, i used Telethon 0.11.5 and everything worked, but when i installed new Telethon 0.13 version some part of my code stopped working.

```python
@staticmethod
def update_handler(self, update_object):
    if isinstance(update_object, UpdateShortMessage):
        MyBot.join_channels(update_object)
```

```python
self.add_update_handler(self.update_handler)
while True:  # listening for updates
    pass
```

these fucntions were in class made like in offical example. (MyBot is my class)

```python
def join_channels(self, channels):
    print("something")          
    self(ResolveUsernameRequest(channel))
    print("i have done all work")
```

normally at Telethon 0.11.5 join_channels functions used to print 'something' then invoke request and print "i have done..." BUT in Telethon 0.13 it ony prints "something" and after it dont do and print anything. How can i fix it? I have tested and without recieving updates script works fine, maybe there is problem with threads?

**Comment by Lonami** [comment]
Use three \`\`\` to format code blocks, otherwise it'll be completely unreadable.

**Comment by leshark** [comment]
But... i have used

**Comment by Lonami** [comment]
No, you had put a single backtick, \`. Anyway.

To begin with, you're mixing `@staticmethod` with a first `self` attribute, which is probably not what you want.

Second, you have a busy loop (`while True: pass`) which is *killer* for the CPU. Add some `sleep()`.

> after it dont do and print anything

Some stack trace would be helpful.

**Comment by leshark** [comment]
well, my mistake, i don't actually use self in staticmethod. And i hav eadded time.sleep(0.1) But script still doesnt work

**Comment by Lonami** [comment]
> But... i have used

Now the image loaded. I edited your comment, it says up there. Anyway.

**Comment by leshark** [comment]
Sorry but i realy not familiar with threads? how can i check it? I just tried to run script without updates at all and give channels parametres in func join_channels directly(it works so)

**Comment by Lonami** [comment]
> how can i check it?

Pressing <kbd>Ctrl+C</kbd> to stop everything should work and tell you were it stopped. Press it twice at least.

**Comment by leshark** [comment]
I tried to debug and i script stops before invoking method, and just dont do anything

**Comment by Lonami** [comment]
> self(ResolveUsernameRequest(channel))

What's the type of `channel`?

**Comment by leshark** [comment]
string

**Comment by Lonami** [comment]
Okay I see the problem. Invoking a request from within the update handler will make it not work. Why? Because it will wait for the `ReadThread` to receive it, but it's the `ReadThread` who reads it and the one who's waiting, so it hangs.

**Comment by leshark** [comment]
How can i install Telethon 0.11.5 back?
And how i can send file at 0.11.5 version?

**Comment by leshark** [comment]
so how i can awoid this problem?

**Comment by Lonami** [comment]
> How can i install Telethon 0.11.5 back?

You look on the internet for an answer, "how to install a previous version pip". Also, go with `v0.12.2`, no need to go back as far as `v0.11.5`.

> And how i can send file at 0.11.5 version?

You **RTFM**.

> so how i can awoid this problem?

You wait until I fix it, or you fix it and submit a pull request, or you downgrade.

**Comment by leshark** [comment]
when are you going to fix this? I have a deadline soon:(

**Comment by Lonami** [comment]
Just install `v0.12.2`, it's the latest version which doesn't use this new thread thing.

**Comment by Lonami** [comment]
Workaround for `v0.13`:

```python
updates = []
def on_update(update):
    updates.append(update)

while True:
    if not updates:
        sleep(0.1)
        continue

    # Work with the added updates here. Note that this is not
    # thread-safe but that's left as an exercise to the reader.
```

**Comment by leshark** [comment]
OK, thanks a lot. My best wishes. I think i should  give you a star now:)

**Comment by Lonami** [comment]
Thanks for the star. I'm still thinking how to design this in the most appropriated way.

**Comment by Lonami** [comment]
Whoops why did you close this? I need to figure out how to call things from the updates thread.

**Comment by Lonami** [comment]
You're still advised to use a separate thread for this, because it will prevent everything else from being read while you're invoking said request.
