### ISSUE TITLE
How to use proxy in telethon?

### ISSUE THREAD

**Issue by hamed169** [LonamiWebs/Telethon#227]
```python
import sys
import socks

from telethon import TelegramClient
from telethon.tl.types import InputPhoneContact
from telethon.tl.functions.contacts import ImportContactsRequest
from telethon.errors import FloodWaitError, RPCError

api_id = 0  # a valid api_id
api_hash = ''  # a valid api_hash

w = input('Which: ')

host = 8.8.8.8  # a valid host
port = 80  # a valid port
proxy = (socks.SOCKS5, host, port)

client = TelegramClient('N{}'.format(w), api_id, api_hash, proxy)
client.connect()
```

Above code doesn't work. what is the problem???

**Comment by Lonami** [comment]
> what is the problem???

No idea. Why doesn't it work? What's the problem? Have you tried connecting without a socket? Does that work? Can you confirm that said "valid host and port" work correctly somehow else?

**Comment by hamed169** [comment]
valid host and port works with requests and opens a URL successfully. and doesn't work
without proxy, it's OK

**Comment by Lonami** [comment]
Could you at least provide a traceback of where it stops working, or what the error is?

**Comment by hamed169** [comment]
socks.GeneralProxyError: Socket error: timed out
This is the error what happens

**Comment by hamed169** [comment]
It

**Comment by hamed169** [comment]
It Worked successfully!!! Thanks

**Comment by Lonami** [comment]
What worked?

**Comment by hamed169** [comment]
with another proxy:))

**Comment by Lonami** [comment]
Okay, we can close the issue then.

**Comment by jjhesk** [comment]
i got timeout too. [Errno Connection to Telegram failed %d time(s)]

**Comment by Keramatfar** [comment]
> with another proxy:))

which proxy?

**Comment by quangdai0805** [comment]
I got this error, help me
TelegramBaseClient.__init__() takes 4 positional arguments but 5 were given
  File "C:\Users\Admin\Desktop\Daiii\Tele\Python\testproxy.py", line 16, in <module>
    client = TelegramClient('N{}'.format(w), api_id, api_hash, proxy)

**Comment by Seanxz401** [comment]
> I got this error, help me TelegramBaseClient.**init**() takes 4 positional arguments but 5 were given File "C:\Users\Admin\Desktop\Daiii\Tele\Python\testproxy.py", line 16, in client = TelegramClient('N{}'.format(w), api_id, api_hash, proxy)

proxy→proxy=proxy

**Comment by Seanxz401** [comment]
got error: "Attempt 1 at connecting failed: GeneralProxyError: Socket error: Connection closed unexpectedly". Could you help me.

**Comment by masoodccc** [comment]
hi

**Comment by masoodccc** [comment]
i use the MTProto proxy in following:
api_id = --
api_hash = "--"
bot = input("Please Enter Session Name:")
client = TelegramClient(
bot, api_id, api_hash,
connection=connection.ConnectionTcpMTProxyRandomizedIntermediate,
proxy=('http://bro.warehere.again.to.defendursheeeeets.got.it.beeeaaach.orshould.repeat.again.qmark.www.digikala.com.iranserver.com.bing.com.gmail.com.nic.ir.thisisme.ir.mihanwebhost.ejhost.udfuk.986.entekhab.ddns.net.dynu.com.noip.withoutip.withoudanti.aws--mss.rocks', 443, 'dd00000000000000000000000000000000')
)
this MTProto is worked and not problem but telegramclient not connected and not worked. Why?????????????????

**Comment by Pycomet** [comment]
Same for me

**Comment by Mysterio-cell** [comment]
which proxy u used for telethon and where u bought from?

**Comment by Arfat-Mughal** [comment]
with 
```
host = '249.252.254.9'
port = 19512
proxy = (socks.SOCKS5, host, port)
client = TelegramClient(StringSession(), api_id, api_hash, proxy=proxy)
```

I am getting 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Connection error 1 during auth_key gen: OSError: [WinError 121] The semaphore timeout period has expired

**Comment by U88K22930** [comment]
> with
> 
> ```
> host = '249.252.254.9'
> port = 19512
> proxy = (socks.SOCKS5, host, port)
> client = TelegramClient(StringSession(), api_id, api_hash, proxy=proxy)
> ```
> 
> I am getting Server closed the connection: [WinError 121] The semaphore timeout period has expired Connection error 1 during auth_key gen: OSError: [WinError 121] The semaphore timeout period has expired

SAME here

**Comment by U88K22930** [comment]
> i use the MTProto proxy in following: api_id = -- api_hash = "--" bot = input("Please Enter Session Name:") client = TelegramClient( bot, api_id, api_hash, connection=connection.ConnectionTcpMTProxyRandomizedIntermediate, proxy=('http://bro.warehere.again.to.defendursheeeeets.got.it.beeeaaach.orshould.repeat.again.qmark.www.digikala.com.iranserver.com.bing.com.gmail.com.nic.ir.thisisme.ir.mihanwebhost.ejhost.udfuk.986.entekhab.ddns.net.dynu.com.noip.withoutip.withoudanti.aws--mss.rocks', 443, 'dd00000000000000000000000000000000') ) this MTProto is worked and not problem but telegramclient not connected and not worked. Why?????????????????

Is this resolved?
I thought connection.ConnectionTcpMTProxyRandomizedIntermediate is not for public use

**Comment by U88K22930** [comment]
> Could you at least provide a traceback of where it stops working, or what the error is?

client = TelegramClient(session_file, api_id, api_hash
                        ,
                        connection=ConnectionTcpMTProxyIntermediate, 

                        proxy=('cloudflare.com.nokia.com.co.uk.do_yo.want_to.clash_with.this.www.microsoft.com.there_is_no.place_like.localhost.www.bing.com.count_with_me.cyou.net.digikala.com.www.enamad.ir.www.google.again_to_fight.everyone.i_am.the_internet.mehrvilla.info',
                               120, 
                               'ee0000f00f0f775555fffffff5006e2e692d2d2d2d2d2d7765622e61707063656e7465722e6d73692d2d2d2d2d2d')
                        )
        
Attempt 1 at connecting failed: ConnectionError: Proxy closed the connection after sending initial payload
Attempt 2 at connecting failed: ConnectionError: Proxy closed the connection after sending initial payload
Attempt 3 at connecting failed: ConnectionError: Proxy closed the connection after sending initial payload
Attempt 4 at connecting failed: ConnectionError: Proxy closed the connection after sending initial payload
Attempt 5 at connecting failed: ConnectionError: Proxy closed the connection after sending initial payload

**Comment by U88K22930** [comment]
> > what is the problem???
> 
> No idea. Why doesn't it work? What's the problem? Have you tried connecting without a socket? Does that work? Can you confirm that said "valid host and port" work correctly somehow else?

client = TelegramClient(session_file, api_id, api_hash
                        , proxy=(socks.SOCKS5, host, int(port), username, password)
                         "It's working perfectly fine when my vpn is on but useless as it can't bypass contry regulations when vpn is not connected"
