### ISSUE TITLE
extract different parts of ChannelMessages

### ISSUE THREAD

**Issue by imdoneok** [LonamiWebs/Telethon#229]
hi,
i have already tried 'dir()' to find Built-in functions for 'ChannelMessages' but i couldn't find any function that can return things like date or ID
although there are functions like 'GetMessagesViewsRequest' to get views but what about ID and date?
p.s: I also converted ChannelMessages to string to use regular expressions and self-made functions using 'string.find()' but they were unsuccessful :(
any idea?

**Comment by Lonami** [comment]
> i have already tried 'dir()' to find Built-in functions

You should use [this](https://lonamiwebs.github.io/Telethon/) instead.

> but i couldn't find any function that can return things like date or ID

Sorry what are you trying to do exactly? [`ChannelMessages`](https://lonamiwebs.github.io/Telethon/constructors/messages/channel_messages.html) has a list of `.messages`, and a [`Message`](https://lonamiwebs.github.io/Telethon/constructors/message.html) has a `.date`…

**Comment by imdoneok** [comment]
i have a ChannelMessages data and i want to get it's date and id using bult-in function

**Comment by Lonami** [comment]
I just told you how. Do you know Python or have experience programming?
