### ISSUE TITLE
Working with stickers

### ISSUE THREAD

**Issue by fnbomb** [LonamiWebs/Telethon#230]
Hello!
How send a sticker?

**Comment by Lonami** [comment]
What have you tried?

**Comment by FrayxRulez** [comment]
You can try to ask it kindly

**Comment by fnbomb** [comment]
I do not understand how to get the right set of stickers. One set always comes back. What value hash should be passed to GetAllStickersRequest to get all the added sets.

By requesting InputStickerSetID, I get a list of available stickers. What is the request to send the required sticker?

ALLsticker = GetAllStickersRequest(438799517)
stick = client.invoke(ALLsticker)
getstick = InputStickerSetID(id=stick.sets[0].id, access_hash=stick.sets[0].hash)
GSSR = GetStickerSetRequest(stickerset=getstick)
StickersOfSet = client.invoke(GSSR)

**Comment by Lonami** [comment]
Okay, `hash` is not the `hash` required to access said sticker file. I know this isn't straightforward at all, but Telegram wasn't designed to make scripts easy to write. Here's a working example which I'll add to the wiki:
```python
# Get all the sticker sets this user has
sticker_sets = client(GetAllStickersRequest(0))

# Choose one sticker set
sticker_set = sticker_sets.sets[0]

# Get the stickers for this sticker set
stickers = client(GetStickerSetRequest(
    stickerset=InputStickerSetID(
        id=sticker_set.id, access_hash=sticker_set.access_hash
    )
))

# Stickers are nothing more than files, so send that
client(SendMediaRequest(
    peer=client._get_entity('lonami'),
    media=InputMediaDocument(
        id=InputDocument(
            id=stickers.documents[0].id,
            access_hash=stickers.documents[0].access_hash
        ),
        caption='hello'
    )
))
```

Any suggestion on how to make this any simpler is appreciated.
