### ISSUE TITLE
How can i increase views count in channel

### ISSUE THREAD

**Issue by petrucci89** [LonamiWebs/Telethon#233]
I use methods
from telethon.tl.functions.channels import ReadHistoryRequest
and
from telethon.tl.functions.channels import ReadMessageContentsRequest

unread messages disappear, but views doesnt increase. Only if i open channel in real telegram client.

Please help me with this task.

Thx!

**Comment by Lonami** [comment]
I think you have to use the new `channels.readMessageContents#eab5dc38 channel:InputChannel id:Vector<int> = Bool;` introduced with [layer 71](https://github.com/LonamiWebs/Telethon/commit/a5d86b4572fb0b015e8e12e670c4262f8d94fe4a). Give that a shot. [Telethon docs](https://lonamiwebs.github.io/Telethon/methods/channels/read_message_contents.html).

**Comment by petrucci89** [comment]
from telethon.tl.functions.channels import ReadMessageContentsRequest
channel = InputPeerChannel(channel_id=1141761553, access_hash=3027812134982130789)
print(client.invoke(ReadMessageContentsRequest(i,[23,24,25]) ) )
return True

23.24.25 ids messages in channel i must to view

But views don't increse

Maybe there is another ways to solve it.

p.s.in telegram docs https://core.telegram.org/method/messages.readMessageContents this metod means a little another sense that icrease views.

**Comment by Lonami** [comment]
[`GetMessagesViewsRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_messages_views.html), set `increment=True`.

**Comment by petrucci89** [comment]
Great!!!
It works, thx a lot!

I would not have found it myself

**Comment by rex101** [comment]
@Lonami how we can create list Vector for users because I can't find any class or package in Telethon ?

**Comment by doctoralpha** [comment]
Did you create that app?

**Comment by mirshod1257** [comment]
Please help me to increase the number of telegram views via python codes. Thank you in advance

**Comment by rex101** [comment]
Hello, I can help you with increasing views of your telegram post's, kindly
contact me on telegram, this is my id @rex01
