### ISSUE TITLE
Get supergroup messages

### ISSUE THREAD

**Issue by toert** [LonamiWebs/Telethon#236]
I have enough experience with Python, but I can't find any method to get messages of supergroup. 
My program must get last messages from supergroup and instantly process the information.

**Comment by Lonami** [comment]
I presume you mean you want to process supergroup messages as soon as they occur? Well proper update are still a WIP (#212, #202, #151, #86), so if that's the case I'm going to close this issue.

**Comment by Lonami** [comment]
Closing in favor of #237. If what you want is to manually poll for the message history, well, I just hinted you what the method name is.

**Comment by toert** [comment]
What type of Update class should I use to get messages from supergroups?
`from telethon.tl.types import ??`

**Comment by Lonami** [comment]
Telegram may send any [`Update`](https://lonamiwebs.github.io/Telethon/types/update.html) or [`Updates`](https://lonamiwebs.github.io/Telethon/types/updates.html). The library offers no abstraction here yet.
