### ISSUE TITLE
Recent action in channel

### ISSUE THREAD

**Issue by AmirGhazaei** [LonamiWebs/Telethon#239]
Hello
Is there any method to retrieve recent action in channel?
In latest update of telegram, channel admins can see recent action of own channel, such as joined users, left users, sent messages from other admins... . 
How I can see my recent channel actions with Telethon?
Thanks

**Comment by Lonami** [comment]
The template when creating issues is there for a reason, and deleting it gives nothing but a bad impression. What have you tried?

**Comment by AmirGhazaei** [comment]
I want too get recent action of my channel with Telethon. Is this possible?

**Comment by Lonami** [comment]
Of course it's possible.

**Comment by goodmind** [comment]
lol

**Comment by AmirGhazaei** [comment]
With method give recent actions?
