### ISSUE TITLE
what is this ??

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#241]
hi 
I use this code for connect  
`client = TelegramClient(phone_number, config.api_config['api_id'], config.api_config['api_hash'],
                                    proxy=(),
                                    device_model=None, system_version=None,
                                    app_version=None, lang_code=None,
                                    system_lang_code=None,
                                    timeout=timedelta(seconds=600))
client.connect()`
but this error  appears :

`Thread name :  MainThread
Error type : <class 'AttributeError'>  File name : add_phone_number.py  Line : 117 Message : 'NoneType' object has no attribute 'encode'
`
what means !??
thanks

**Comment by alihossein** [comment]
@Lonami  please help

**Comment by Lonami** [comment]
No, you completely got rid of the template, the issue is not properly formatted, and I have no information about what you have on `add_phone_number.py`. And I'm being nice. Unless you prove otherwise, the bug is probably in your code.

**Comment by alihossein** [comment]
@Lonami 
this is my `add_phone_number.py` :
 
``` python 
import os
import socks
from datetime import timedelta

import sys
from telethon import TelegramClient
from telethon.tl.functions.auth import CheckPhoneRequest

import config.database as config
import helpers as helpers
proxy_host = None
proxy_username = None
proxy_password = None
proxy_port = None
proxy_info = None
phone_number=xxxxxxxxxxx
client = TelegramClient(phone_number, config.api_config['api_id'], config.api_config['api_hash'],
                                    proxy=(),
                                    device_model=None, system_version=None,
                                    app_version=None, lang_code=None,
                                    system_lang_code=None,
                                    timeout=timedelta(seconds=600))
 client.connect()
 ```
This code works well on the local , but it gives the server an Error : 
```
<class 'telethon.telegram_client.TelegramClient'>
Error type : <class 'AttributeError'>  File name : add_phone_number.py  Line : 118 Message : 'NoneType' object has no attribute 'encode'
```
Line 118 =  `client.connect()` in my code.

**Comment by Lonami** [comment]
I need more error log than just that… You don't need to set any of those `None` parameters you're writing. Just
```python
TelegramClient(phone_number, config.api_config['api_id'], config.api_config['api_hash'],
               timeout=timedelta(seconds=600))
```

**Comment by alihossein** [comment]
@Lonami  thanks.

> You don't need to set any of those None parameters you're writing
I removed Additional parameters and the problem was solved.
