### ISSUE TITLE
Cloning Too Slow

### ISSUE THREAD

**Issue by DrBanani** [LonamiWebs/Telethon#246]
Hello,
Your repository is getting bloated with commits so I suggest (6590 OBJECTS?!?!?!)
so I suggest that you squash all of your commits or move to TFS (the proper version control system)

Also I cannot run this in windows for some reason
```
person name:string age:int = Person

  File "<stdin>", line 1
    person name:string age:int = Person
              ^
SyntaxError: invalid syntax
```

**Comment by Lonami** [comment]
```
$ time git clone git@github.com:LonamiWebs/Telethon.git
Cloning into 'Telethon'...
remote: Counting objects: 6590, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 6590 (delta 2), reused 6 (delta 2), pack-reused 6581
Receiving objects: 100% (6590/6590), 1.62 MiB | 654.00 KiB/s, done.
Resolving deltas: 100% (5657/5657), done.

real	0m4.644s
user	0m0.433s
sys	0m0.093s
```

Can't reproduce on my machine, sorry!

> I suggest that you squash all of your commits

The point of having separate commits is to make the changes made on the project and its evolution easier to follow. That's the whole point of `git`.

> move to TFS (the proper version control system)

That argument sounds pretty much based only on your sole opinion here. I don't even know TFS, and I'm clearly not migrating this project there. I like `git`, it does its job, and it does it good.

> Also I cannot run this in windows for some reason

Windows, or whatever system. That's not Python at all. That's the [type language](https://core.telegram.org/mtproto/TL).

**Comment by Lonami** [comment]
By the way, this is also described on the [wiki](https://github.com/LonamiWebs/Telethon/wiki/Understanding-the-Type-Language), which you're strongly advised to read.
