### ISSUE TITLE
Session issue

### ISSUE THREAD

**Issue by toxydose** [LonamiWebs/Telethon#251]
I haven't updated Telethon for a while. And after updating it the session issue appeared.
I have four telethon clients connected to four different accounts. And after using the program for some time the next error appears:
    
```
==================
= Initialization =
==================
Initializing interactive example...
Traceback (most recent call last):
  File "/home/pi/telethon/telethon/tl/session.py", line 184, in try_load_or_create_new
    data = json.load(file)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./try_telethon.py", line 38, in <module>
    **kwargs)
  File "/home/pi/telethon/telethon_examples/interactive_telegram_client.py", line 78, in __init__
    super().__init__(session_user_id, api_id, api_hash, proxy)
  File "/home/pi/telethon/telethon/telegram_client.py", line 89, in __init__
    session = JsonSession.try_load_or_create_new(session)
  File "/home/pi/telethon/telethon/tl/session.py", line 199, in try_load_or_create_new
    except (json.decoder.JSONDecodeError, UnicodeDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'

    
```

When i delete my file *.session file and all __pycashe__ folders all seems to be OK and the program works again.

**Comment by Lonami** [comment]
It seems like the `.session` files somehow broke. Could you open them with a text editor and ensure they're valid JSON? Respect:
> ```
> AttributeError: 'module' object has no attribute 'JSONDecodeError'
> ```

I'll fix it, but the session will be lost.

**Comment by toxydose** [comment]
> I'll fix it, but the session will be lost.

I know, each time I have to create the new session file and it works for some time.

I already created a new session files and I have no idea why they become to be broken.

**Comment by Lonami** [comment]
Are multiple threads involved? Do you use one session name per `TelegramClient`? That is, don't create two of them at the same time with the same session name. I can't think of much more. Perhaps calling its `.save()` fails somehow?

**Comment by Lonami** [comment]
So I just noticed that since for a while now we don't need to save the `Session` so often (changed on https://github.com/LonamiWebs/Telethon/commit/ffadcd029f5505e68e441a37b5079994a5095c10), maybe that helps.

**Comment by toxydose** [comment]
Thank you! Now the program works stable!

**Comment by Lonami** [comment]
Nice, perhaps the issue was that the session was being saved too often. Still weird that it didn't happen in older versions. Maybe two threads were fightning to save the file?
