### ISSUE TITLE
GetFullUserRequest throws UserIdInvalidError 

### ISSUE THREAD

**Issue by deddysetyadi** [LonamiWebs/Telethon#255]
I'm using telethon v12.2. 
I want to fetch sender user information every incoming ```UpdateShortMessage``` event using 

```self.invoke(GetFullUserRequest(InputUser(update_object.user_id, access_hash)))``` 

when user knows each other (appear in contact list), it run successfully. But, when the sender is not appear in contact list, it throws error :  

```telethon.telethon.errors.rpc_errors_400.UserIdInvalidError: (UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types.')```

How can i handle that ? 

Then i found this [inputUserForeign](https://core.telegram.org/constructor/inputUserForeign), is that method implemented in telethon ? 

Thanks.

**Comment by Lonami** [comment]
> telethon v12.2

Latest on PyPi is `v0.13.4`, so consider upgrading.

> `access_hash`

That must be the `access_hash` **associated with the user**, and not any other. What are you using there?

> is that method implemented in telethon ?

Constructor. [And no](https://lonamiwebs.github.io/Telethon/types/input_user.html), it has been removed from Telegram's API a long time ago. Official documentation about the schema is really out of date.

**Comment by deddysetyadi** [comment]
Here is the scenario : 
- A doesn't know B (B didn't appear in A contacts).
- B send message to A, with update : 

    ```New update :{UpdateShortMessage: {id: 220, mentioned: None, pts: 294, fwd_from: None, date: 2017-09-22 14:43:49, pts_count: 1, message: 'fafs', media_unread: None, reply_to_msg_id: None, out: None, via_bot_id: None, entities: [], silent: None, user_id: 406922143}}```

- A wants to know `phone number,name,etc` from B, based on `user_id` in `update object`
- So I use `access_hash` from ***A***, to retrieve user information of B, because I don't know hot to get `access_hash` of ***B***:

    ```self.invoke(GetFullUserRequest(InputUser(update_object.user_id, A.access_hash)))``` 

Is that correct ?

**Comment by Lonami** [comment]
No. As I said, you must use B's access hash. How? Telegram is supposed to send you an "Updates" object with information about users and chats. The library doesn't save this information automatically yet, so, for now, you have to do that yourself.

**Comment by Lonami** [comment]
Closed due to inactivity. Comment here if you're up for more discussion or need more details, but what I said above should be enough.

Also, the library now does save the id/hash pairs. Just use `client.get_entity` or `client.get_input_entity`.

**Comment by FlashAJ** [comment]
If i now user_id and access_hash, why does it give me an error:
telethon.errors.rpc_error_list.UserIdInvalidError: (UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types, for instance making sure that the request is designed for users or otherwise look for a different one more suited')?

I'm using the code:
user_id='123456'
access_hash='123456789'
InputUser(user_id, access_hash)

**Comment by Lonami** [comment]
I hope you just wrote your example wrong @FlashAJ and that you're actually using **integers** instead strings.

**Comment by FlashAJ** [comment]
Yea, i assign variables via int(), since they are taken from a file:
user_id=int(id)
access_hash=int(hash)

**Comment by Lonami** [comment]
Can't you just show the whole code. There's no reason why I need to be asking over and over when you could just show the whole thing.

**Comment by FlashAJ** [comment]
channel = client(ResolveUsernameRequest(group))
f=open('user.txt','r')
for l in f:
    user = l.split(';')
    user[0]=int(user[0])
    user[1]=int(user[1])
    client.invoke(InviteToChannelRequest(InputChannel(channel.chats[0].id, channel.chats[0].access_hash), [InputUser(user[0],user[1])])

File contents:
1234567;-1234567890123456789

Error:
telethon.errors.rpc_error_list.UserIdInvalidError: (UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types, for instance making sure that the request is designed for users or otherwise look for a different one more suited')

**Comment by FlashAJ** [comment]
Will my question be ignored?

**Comment by Lonami** [comment]
Error should be descriptive enough. Maybe the id/hash is wrong. Maybe you need another request.

**Comment by FlashAJ** [comment]
id/hash taken through `GetParticipantsRequest`
What means another request?

**Comment by Lonami** [comment]
@FlashAJ if I recall correctly, there's a method to add users to a chat and another for channels (and megagroups).

**Comment by FlashAJ** [comment]
error gives both channels and groups

**Comment by FlashAJ** [comment]
but if use `user = client.get_entity`, then no errors

**Comment by Lonami** [comment]
@FlashAJ are you 100% sure the ID and hash are right?

**Comment by FlashAJ** [comment]
100%
i got them through `GetParticipantsRequest`

**Comment by FlashAJ** [comment]
it can be that `GetParticipantsRequest` gives one, and `client.get_entity` another?

**Comment by Lonami** [comment]
You can try to check that. If they're the same, I would ask you do add modify this line from the `InviteToChannelRequest` class:
```python
self.users = [get_input_user(_x) for _x in users]
```

for this:
```python
print(' '.join(type(x).__name__ for x in users))
self.users = [get_input_user(_x) for _x in users]
print(' '.join(type(x).__name__ for x in self.users))
```

Basically I just want to see the types before and after. They should be `InputUser` and *not* `InputPeerUser`.

**Comment by FlashAJ** [comment]
Report:
InputUser
InputUser

**Comment by Lonami** [comment]
Then it can only be the ID/hash combination that's different. Weird.

**Comment by FlashAJ** [comment]
Indeed, strange things. Now I try, there are no errors...
Something wrong with ID/hash. Thanks for help.

**Comment by FlashAJ** [comment]
Understood. For each account, the hash of objects is different.

**Comment by Lonami** [comment]
@FlashAJ yeah.

**Comment by celtoxx** [comment]
So whats the conclusion.Please anyone can help

**Comment by celtoxx** [comment]
Error:
telethon.errors.rpc_error_list.UserIdInvalidError: (UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types, for instance making sure that the request is designed for users or otherwise look for a different one more suited')

is there any solution for above error.

**Comment by VasilMirov** [comment]
@celtoxx the solution is that the hash for the scrapper users is unique for the client/number that scraped it. So you can only add members to the group using the client/number you used to scrape them

**Comment by Lonami** [comment]
Locking as this issue has been solved for years. Please remember mass adding users is considered spam and will likely get the account or group banned.
