### ISSUE TITLE
Freeze on client.connect()

### ISSUE THREAD

**Issue by chstem** [LonamiWebs/Telethon#257]
When calling the `connect()` method twice Telethon freezes, waiting for some thread lock. In the traceback I found [# TODO Socket's timeout here?](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_bare_client.py#L320)

Expected behavior would be to check if connected, try and reconnecting.

**Comment by Lonami** [comment]
Huh, I probably did a `git reset --HARD` and lost that, but that was supposed to ship with `v0.13.5`. One moment.

**Comment by Lonami** [comment]
Pushed to PyPi.
