### ISSUE TITLE
 Invalid connection mode on connect()

### ISSUE THREAD

**Issue by chstem** [LonamiWebs/Telethon#260]
I get the following error when trying to connect:

```
    client.connect()

  File "/usr/lib/python3.4/site-packages/telethon/telegram_client.py", line 174, in connect
    ok = super().connect(exported_auth=exported_auth)

  File "/usr/lib/python3.4/site-packages/telethon/telegram_bare_client.py", line 118, in connect
    authenticator.do_authentication(self._sender.connection)

  File "/usr/lib/python3.4/site-packages/telethon/network/authenticator.py", line 22, in do_authentication
    return _do_authentication(connection)

  File "/usr/lib/python3.4/site-packages/telethon/network/authenticator.py", line 41, in _do_authentication
    sender.send(writer.get_bytes())

  File "/usr/lib/python3.4/site-packages/telethon/network/mtproto_plain_sender.py", line 35, in send
    self._connection.send(packet)

  File "/usr/lib/python3.4/site-packages/telethon/network/connection.py", line 172, in send
    raise ValueError('Invalid connection mode specified: ' + str(self._mode))

ValueError: Invalid connection mode specified: None
```

This happens since  `0.13` and only in connection with [PyOtherSide](https://github.com/thp/pyotherside).

I am not sure where this is coming from, but here is my first guess: PyOtherSide executes the imported Python in a separate thread. This might have some unexpected side effects for Telethon?

What are the technical changes from `0.12` to `0.13` with respect to connecting, that might be relevant here?

**Comment by Lonami** [comment]
Maybe some parameter out of order that the library used to set to `None`, and now it can't be, because it's the connection mode. Python being duck typed makes this hard to spot.

**Comment by chstem** [comment]
Nevermind, I instantiated the client as `TelegramClient(session_user_id, api_id, api_hash, proxy)`, where `proxy=None`. This does not work anymore since you put `connection_mode` as the first keyword argument. (May I suggest to add new arguments at the end, for better downward compatibility?)

**Comment by Lonami** [comment]
> May I suggest to add new arguments at the end

Well actually, my rule is thumb is to always use named parameters for those which are optional.

**Comment by chstem** [comment]
I guess it would be good practice to do both ;)

**Comment by toxydose** [comment]
Have the same issue after updating using the standard client ./try_telethon.py

**Comment by Lonami** [comment]
If you could ensure that you're using the latest version, and at least provide where the error happens, that would help @toxydose.

**Comment by toxydose** [comment]
python3 try_telethon.py

File "/Telethon1/telethon/network/connection.py", line 176, in send
    raise ValueError('Invalid connection mode specified: ' + str(self._mode))
ValueError: Invalid connection mode specified: None @Lonami

**Comment by Lonami** [comment]
I meant the full traceback, not exactly where the error is raised…

**Comment by toxydose** [comment]
@Lonami I am sorry, it seems like the issue appears due to my custom module interactive_telegram_client.py in telethon_examples. This file is no more compatible with the new updates. It was my fault.
