### ISSUE TITLE
Connects to unknown host 163.172.167.189:443

### ISSUE THREAD

**Issue by 3bl3gamer** [LonamiWebs/Telethon#262]
### What went wrong
`client.is_user_authorized()` opens additional TLS connection to 163.172.167.189:443 and sends some data.

### What I've done
Removed `username.session` file, started capture in wieshark and run client:

```python
from telethon import TelegramClient

API_ID = 12345
API_HASH = '<hash>'

client = TelegramClient('username', API_ID, API_HASH)
client.connect()
print(client.is_user_authorized())
```

### More information
Part of wireshark dump:
![image](https://user-images.githubusercontent.com/1857617/30802221-72735c30-a1ee-11e7-83e4-e470d7af1671.png)

If acces to 163.172.167.189 is blocked (for example with `iptables -A OUTPUT -d 163.172.167.189 -j DROP`) then `is_user_authorized` hangs for ~1 minute but returns without error.

**Comment by Lonami** [comment]
```bash
$ ping rpc.pwrtelegram.xyz
PING 1.pwrtelegram.xyz (163.172.167.189)
```

[It's not unknown](https://github.com/LonamiWebs/Telethon/wiki/API-Status). You can disable this feature with:
```python
client.session.report_errors = False
```

**Comment by Lonami** [comment]
You should also upgrade, since now such request should be sent on `.connect()`, not on `.is_user_authorized()`.

**Comment by 3bl3gamer** [comment]
Sorry, missed out this wiki topic. Thanks!

**Comment by Lonami** [comment]
No problem, I've updated the index page of the wiki to note this more prominently.
