### ISSUE TITLE
send_message to megagroup

### ISSUE THREAD

**Issue by hamid07ss** [LonamiWebs/Telethon#263]
I can't send message to a super group.
```python
if isinstance(update,UpdateNewChannelMessage):
            if is_admin(update.message.from_id):
                msg = update.message
                chat_id = msg.to_id.channel_id
                text = msg.message.lower()
                if text == 'panel':
                    client.send_message(chat_id, 'Test')
```
also I test this way:
```python
peer_id = InputPeerChannel(msg.to_id.channel_id, 0)
```

i don't have channel access_hash
how I can get access_hash of a super group?

my account is in supergroup
now receive message from this super group and I want answer to that message

**Comment by Lonami** [comment]
Telethon doesn't yet cache `{id: entity}` for you, so you have to do that yourself. I assume said supergroup is in your dialogs. I suggest you to get all the dialogs, and manually save a dictionary containing `{id: entity}`. Telegram should have sent such channel along with previous `Updates` object, but if it hasn't, follow the `dialogs` approach. Otherwise, you can hardcode the hash once you get it.

**Comment by hamid07ss** [comment]
get_dialogs return Array of Objects like this:

> <telethon.tl.types.Dialog object at 0x7f3ef21401d0>

how to use it?

**Comment by Lonami** [comment]
Read the wiki or the [documentation for `Dialog`](https://lonamiwebs.github.io/Telethon/constructors/dialog.html) yourself or I'm changing the label from "question" to "RTFM".

**Comment by hamid07ss** [comment]
there is no access_hash inside dialog Object:

`{
    draft: None,
    top_message: 162,
    unread_mentions_count: 0,
    pinned: None,
    read_outbox_max_id: 104,
    peer: {
        channel_id: 1122309329
    },
    pts: 163,
    read_inbox_max_id: 162,
    unread_count: 0,
    notify_settings: {
        silent: None,
        sound: 'default',
        show_previews: True,
        mute_until: 0
    }
}`

**Comment by Lonami** [comment]
[`GetDialogsRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_dialogs.html) doesn't only return [`.dialogs`](https://lonamiwebs.github.io/Telethon/types/dialog.html) though, it also returns [`.chats`](https://lonamiwebs.github.io/Telethon/types/chat.html) and [`.users`](https://lonamiwebs.github.io/Telethon/types/user.html).

**Comment by hamid07ss** [comment]
Thanks
