### ISSUE TITLE
Receiving spam mail 

### ISSUE THREAD

**Issue by MrRobot222** [LonamiWebs/Telethon#2644]
# The mail says

## [LonamiWebs/Telethon] fucked by @teidesu! | struct.error: argument out of range (#2420)

# And a lot of messages starting with `Fucked by @teidesu`

![proof](https://telegra.ph/file/163d281469e9f59c568a8.jpg)

**Comment by teidesu** [comment]
uhm somehow i'm related??

i'm pretty sure it were the same people who spammed in tdesktop issues a few days ago.

i guess they dislike me lol

**Comment by chengdaqian** [comment]
I'm just super confused why these hackers have to hack my account to attack @teidesu and @Lonami. Why not just create a new account?

Btw, I've set up TFA (which I should have done before). Hopefully, this won't happen again.

**Comment by Lonami** [comment]
I saw at least 4 other accounts performing the attack, and it seems they also attacked Telegram Desktop's repository. Not that it matters now that things have calmed down.
