### ISSUE TITLE
failed to download media for some post

### ISSUE THREAD

**Issue by MMohamadPoor** [LonamiWebs/Telethon#265]
hi, 
I've trying to download media from channels, but it raise below error in some posts:

`AttributeError:` 'TelegramClient' object has no attribute '_timeout'

My code is the same as your sample code in `interactive_telegram_client.py` file. It works in some posts and raise error in some others. 

In order to reproduce the error please use the below information:

```
Channel Username: takhfifan
Message ID: 3196
```
what's the problem and how can I solve it?

**Comment by Lonami** [comment]
> how can I solve it?

Well if you were to make a pull request to fix it, you should know in which line it's failing (you just told me the error, not where), and change it to use the right value. I probably forgot to change that when doing some refactoring.

**Comment by MMohamadPoor** [comment]
the traceback show this:

`  File "C:\Python35\lib\site-packages\telethon\crypto\cdn_decrypter.py", line 45, in prepare_decrypter
    timeout=client._timeout`

I change it to `timeout` but the same error happened.

**Comment by Lonami** [comment]
I'll fix this later or tomorrow. It's not hard but I understand that someone without knowledge of the library doesn't know where to even get started…

**Comment by MMohamadPoor** [comment]
ok, thank you very much.
