### ISSUE TITLE
[Question] how quick is the update_handler method called

### ISSUE THREAD

**Issue by Herny64** [LonamiWebs/Telethon#267]
Hi,
how quick is the update_handler method in the interactive_telegram_client.py called ?
if I send a message to the client, is this message immediately processed and the update_handler method immediately called ? or is there some sort of polling anywhere in the code, where some checks are done frequently with a small delay between the checks ?

I've used the search function and I followed the function calls backwards a few times before asking this question.

kind regards

**Comment by Lonami** [comment]
> is this message immediately processed and the update_handler method immediately called

Yeah it should be.

> or is there some sort of polling

Well of course you need some kind of "polling". Currently Telethon has a thread which is constantly reading from the socket.

> with a small delay between the checks

No, there's no `time.sleep` when "polling". As soon as something is read from the socket, the thread will go back and read again.

> I've used the search function and I followed the function calls backwards a few times before asking this question.

Thanks :) It's an okay question. The relevant code starts on `TelegramClient._recv_thread_impl`.
