### ISSUE TITLE
Python3.4 compatibility broken (again)

### ISSUE THREAD

**Issue by chstem** [LonamiWebs/Telethon#268]
Another issue with Python3.4: 

```
  File "/home/nemo/github/Telethon/telethon/telegram_client.py", line 1080, in _recv_thread_impl
    self.updates.set_error(e)
  File "/home/nemo/github/Telethon/telethon/update_state.py", line 60, in set_error
    self._updates.insert(0, error)
AttributeError: 'collections.deque' object has no attribute 'insert'

```
Because [collections.deque.insert](https://docs.python.org/3/library/collections.html#collections.deque.insert) was introduced with Python 3.5.

(I guess you don't run/test Telethon on Python3.4. Maybe we can keep this issue open, in case I find more problems ...)

**Comment by Lonami** [comment]
Changing this with `.appendleft` should work, sigh. Would you like to make a pull request?

**Comment by Lonami** [comment]
Nevermind, got my laptop again!
