### ISSUE TITLE
Unable to detect exceptions in Updates thread

### ISSUE THREAD

**Issue by AlexTaran** [LonamiWebs/Telethon#27]
Sometimes an exception in Updates thread is raised for unknown reason (happens accidentially)

For example:
Exception in thread Updates thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 394, in updates_thread_method
    reader)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 218, in process_msg
    return self.handle_rpc_result(msg_id, sequence, reader, request)
  File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 339, in handle_rpc_result
    'Cannot receive a request from inside an RPC result from the updates thread.')
ValueError: Cannot receive a request from inside an RPC result from the updates thread.

There are many different exceptions potentially could be raised in mtproto_sender.py , so it probably would be great to have an easy way to detect this someway from main thread to allow reconnect.

Thanks.

**Comment by XyLoNaMiyX** [comment]
> is raised for unknown reason

You did give the reason though:

> "_Cannot receive a request from inside an RPC result from the updates thread._"

I'm not sure which rpc result was received exactly. But to be honest, I think it's a race condition? Like, does it happen after you've sent a request from the main thread or is it really random?

Also, the way the updates are currently handled, is _far_ from being perfect – but I have no idea on how to work with different sessions (there's a `TODO` on that…). Sure, `tdesktop` is still updated on GitHub and I could mimic their behaviour, but their code is huge, so it's not that simple. It's only me on this really.

**Comment by StrangePers** [comment]
```
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Telethon\Telethon\telethon\network\mtproto_sender.py", line 394, in updates_thread_method
    reader)
  File "D:\Telethon\Telethon\telethon\network\mtproto_sender.py", line 218, in process_msg
    return self.handle_rpc_result(msg_id, sequence, reader, request)
  File "D:\Telethon\Telethon\telethon\network\mtproto_sender.py", line 339, in handle_rpc_result
    'Cannot receive a request from inside an RPC result from the updates thread.')
ValueError: Cannot receive a request from inside an RPC result from the updates thread.
```

I stuck with this one. And it's rather strange. It keeps happening on racing when I need to pin messages in many chats simultaneously for example. Or answer some messages to several chats at once. As far as I see - Every invoke request need to receive an answer. And in the same time there's update_handler with receives messages. And they can't work in one thread. Both update_handler and invoke result receiver interfere with each other when it comes to a race and show this error. May be we should move all invoke requests to different thread and it will solve all problems?

**Comment by XyLoNaMiyX** [comment]
> May be we should move all invoke requests to different thread and it will solve all problems?

The requests you manually `.invoke()` live in a different thread than the updates thread. It's probably a syncrhonization problem or something. Updates thread should not read these. But I have no "buffer" so I can keep those apart and wait for the invoke to read them.

**Comment by StrangePers** [comment]
`But I have no "buffer" so I can keep those apart and wait for the invoke to read them.`
May be I can some how help you? I need Telethon for automatization some administrative stuff in 40+ chats. And it would be awsome if it works without errors with races :)

**Comment by XyLoNaMiyX** [comment]
> May be I can some how help you?

If you want to give it a go. If the updates thread reads what it shouldn't, it should "spit back" what it read so a normal `.read()` can actually read it.

**Comment by StrangePers** [comment]
```
      while not self.updates_thread_stopping:
            # Only try to receive updates if we're not waiting to receive a request
            if not self.waiting_receive:
                with self.lock:
                    try:
                        now = time()
                        # if ping_interval seconds passed since last ping
                        # (or startup) - send new one
                        if now >= self.ping_time_last + self.ping_interval:
                            self.ping_time_last = now
                            self.send_ping()
                            # if sending ping - we doesn't processing any other updates
                            continue

                        self.updates_thread_receiving = True
                        seq, body = self.transport.receive(timeout)
                        message, remote_msg_id, remote_sequence = self.decode_msg(
                            body)

                        with BinaryReader(message) as reader:
                            self.process_msg(remote_msg_id, remote_sequence,
                                             reader)

                    except (ReadCancelledError, TimeoutError):
                        pass

                self.updates_thread_receiving = False
```


Can you explain:
`while not self.updates_thread_stopping: `and  ```
if not self.waiting_receive:
                with self.lock:
```

`self.updates_thread_stopping` and `self.waiting_receive` are used in different threads. Espessially the  `self.waiting_receive`  one. But you are reading it without lock. So may be it is the case when it comes to races?

**Comment by StrangePers** [comment]
If you read it without lock, than it can happen, when `self.waiting_receive` passed this if and then another thread in a lock changes `self.waiting_receive` to true. And when update goes in int's lock - it will receive not intened data

**Comment by XyLoNaMiyX** [comment]
> Can you explain: `while not self.updates_thread_stopping:`

That's a mistake actually. Should be `updates_thread_stopped` (simply the opposite of `updates_thread_running`).

> and `if not self.waiting_receive:`

After every `.send()` a `.receive()` is made. So the `.send()` method sets this flag to `True` so the updates thread can't, in theory, try receiving the updates while we want to receive the request result. After the `.receive()` reads the result of the invoked result, this flag is set to `False`, so the updates thread can continue its job.

> So may be it is the case when it comes to races?

Maybe that's the reason, maybe the flag set should be inside the lock.

Btw, if you want to discuss this on Telegram on real time rather than commenting on this issue, hit me up as [@Lonami](https://t.me/Lonami).

**Comment by Lonami** [comment]
@AlexTaran could you please tell me if this bug still happens with the current upstream version?

**Comment by StrangePers** [comment]
Guess this is the same issue as mine :) And now it is solved.

**Comment by Lonami** [comment]
Feel free to reopen if it happens, or create a new issue if you've got new problems :)
