### ISSUE TITLE
Troubleshooting in installing fork via pip install git+

### ISSUE THREAD

**Issue by Kylmakalle** [LonamiWebs/Telethon#271]
Specs: `Python 3.6.2` venv(s), MacOS 10.13
Tried:
`pip install git+https://github.com/Kylmakalle/Telethon.git`
`pip install https://github.com/Kylmakalle/Telethon/archive/master.zip`
Also same commands with `--no-cache-dir` and `sudo`
**Error:** 
``` Collecting git+git://github.com/Kylmakalle/Telethon.git
Cloning git://github.com/Kylmakalle/Telethon.git to /private/var/folders/4v/v2n7rlrs4kxgtrtr8dzfs61h0000gn/T/pip-l4rdb58m-build
No files/directories in /private/var/folders/4v/v2n7rlrs4kxgtrtr8dzfs61h0000gn/T/pip-l4rdb58m-build/pip-egg-info (from PKG-INFO)
```

Everything is ok for `pip install Telethon` or when using PyCharm package manager

**Comment by Lonami** [comment]
I actually have no idea. Maybe it's because the code hasn't been generated through `python setup.py gen_tl`? Anyway this should work:
```bash
git clone https://github.com/<fork>/Telethon.git
cd Telethon/
git checkout some-branch
python3 setup.py gen_tl
pip install -Ue . --user
```

**Comment by Kylmakalle** [comment]
**Solved** 

I have generated code with `python setup.py gen_tl` while in `Telethon/`

Then `pip install -Ue .` (it fails with `--user` as unknown `setup.py` arg)

Thanks @Lonami

**Comment by Lonami** [comment]
No problem, though I'd like to know why `pip install git+https://github.com/<user>/Telethon.git` fails.

**Comment by Lonami** [comment]
Hey it seems like this was the issue. Nice.
