### ISSUE TITLE
MigrateChatRequest

### ISSUE THREAD

**Issue by 88ee55** [LonamiWebs/Telethon#273]
messages.MigrateChatRequest incorrect type parameter chat_id

here
https://docs.madelineproto.xyz/API_docs/methods/messages_migrateChat.html
type InputPeer

```
r = self.tgclient(messages.MigrateChatRequest(cid))
File "/usr/lib64/python3.5/site-packages/telethon/telegram_client.py", line 263, in invoke retries=kwargs.get('retries', 5)
File "/usr/lib64/python3.5/site-packages/telethon/telegram_bare_client.py", line 340, in invoke raise request.rpc_error
telethon.errors.rpc_errors_400.PeerIdInvalidError: (PeerIdInvalidError(...), 'An invalid Peer was used. Make sure to pass the right peer type.')
```
PS. what makes this method?

**Comment by Lonami** [comment]
`cid` should be an integer ID of an existing *chat*, not *mega-group* or an user. Also this method migrates a normal chat to a mega-group, and you should refer to the [Telethon documentation](https://lonamiwebs.github.io/Telethon/methods/messages/migrate_chat.html). Madeline is different and accepts a different type for convenience.
