### ISSUE TITLE
Fetching usernames from megagroup participants.

### ISSUE THREAD

**Issue by petresdaniel** [LonamiWebs/Telethon#274]
I'm tryting to get a list of the usernames of users in a megagroup. I've gathered a list of the participants with `GetParticipantsRequest`, but this only returns a user_id for me and a date. Is there a way to get their access_hash somehow so that I can make a `GetUsersRequest`

**Comment by Lonami** [comment]
[`ChannelParticipants`](https://lonamiwebs.github.io/Telethon/constructors/channels/channel_participants.html) doesn't only have [`.participants`](https://lonamiwebs.github.io/Telethon/types/channel_participant.html), it also has [`.users`](https://lonamiwebs.github.io/Telethon/types/user.html). You're supposed to pair-up both so you know which participant is which user.

**Comment by petresdaniel** [comment]
Sorry my mistake. Thanks for your help and your fast reply
