### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'updates'

### ISSUE THREAD

**Issue by HippyFizz** [LonamiWebs/Telethon#275]
Hi, I have a trouble with send messages using telethon.
If I send message to user, not to bot, I have the following error:

> Sending to admin: "🇪🇺1|💰19|🔋1/5"
  File "C:/work/chatwars_auto/main.py", line 1430, in update_handler
'NoneType' object has no attribute 'updates'
    self.parsed_text(message)
  File "C:/work/chatwars_auto/main.py", line 1268, in parsed_text
    self.command_from_admin(message)
  File "C:/work/chatwars_auto/main.py", line 863, in command_from_admin
    self._send_to_admin(infotext)
  File "C:/work/chatwars_auto/main.py", line 1331, in _send_to_admin
    self.client.send_message(self.admin_dialog, text)
  File "C:\python3.6\lib\site-packages\telethon\telegram_client.py", line 485, in send_message
    for update in result.updates:
AttributeError: 'NoneType' object has no attribute 'updates'

**Comment by Lonami** [comment]
What version are you running?

**Comment by HippyFizz** [comment]
It is Telethon==0.14.2

**Comment by Lonami** [comment]
> ```
> "C:/work/chatwars_auto/main.py", line 1430, in update_handler
'NoneType' object has no attribute 'updates'
> ```

This seems like a bug in your code?

**Comment by Lonami** [comment]
Like actually, a `None` update shouldn't be passed to update handlers… I'll check it out in more detail.

**Comment by HippyFizz** [comment]
> User: {is_self: None, contact: None, mutual_contact: None, deleted: None, bot: None, bot_chat_history: None, bot_nochats: None, verified: None, restricted: None, min: None, bot_inline_geo: None, id: 460481850, access_hash: 1388427282274236653, first_name: 'Андрей', last_name: 'Макаров', username: 'buptyozzz', phone: None, photo: None, status: UserStatusOffline: {was_online: 2017-09-30 10:20:00}, bot_info_version: None, restriction_reason: None, bot_inline_placeholder: None, lang_code: None}
It is a user dialogue which I get from self.find_dialog_user("buptyozzz")
Update handler code is here:

>     def update_handler(self, tgupdate):
        try:
            self.last_message_received = datetime.now()
            if hasattr(tgupdate, 'updates'):
                updates = tgupdate.updates
            elif hasattr(tgupdate, 'update'):
                updates = [tgupdate.update]
            elif isinstance(tgupdate, telethon.tl.types.UpdateShortMessage):
                updates = [tgupdate]
            elif isinstance(tgupdate, telethon.tl.types.UpdateShortChatMessage):
                updates = [tgupdate]
            else:
                # print('Skipped TGUpdate of class %s: ' % tgupdate.__class__.__name__, tgupdate, dir(tgupdate))
                return
            print(updates)
            for upd in updates:
                if any(isinstance(upd, cls) for cls in TOTALLY_IGNORED_MESSAGE_TYPES):
                    # 100% ignored to not shit into console
                    continue
                if isinstance(upd, telethon.tl.types.UpdateNewMessage):
                    message = getattr(upd, 'message', None)
                    origin_id = getattr(message, 'from_id', None)
                elif isinstance(upd, telethon.tl.types.UpdateShortMessage):
                    message = upd
                    origin_id = getattr(message, 'user_id', None)
                elif isinstance(upd, telethon.tl.types.UpdateEditMessage):
                    message = getattr(upd, 'message', None)
                    origin_id = getattr(message, 'from_id', None)
                elif isinstance(upd, telethon.tl.types.UpdateShortChatMessage):
                    message = upd
                    origin_id = getattr(message, 'from_id', None)  # Also field 'chat_id' is present
                elif isinstance(upd, telethon.tl.types.UpdateNewChannelMessage):
                    message = getattr(upd, 'message', None)
                    origin_id = getattr(getattr(message, 'to_id'), 'channel_id')
                    if message is not None and getattr(message, 'message', None) is not None and message.message.find(self.bot_name) != -1 \
                            and origin_id == 1112398751 \
                            and getattr(message, 'via_bot_id') == 278525885:
                        self.log('Трейд')
                        if message.reply_markup is None:
                            self.log('Нет разметки кнопок')
                        else:
                            answer = self.client(GetBotCallbackAnswerRequest(
                                self.market_dialog,
                                message.id,
                                data=message.reply_markup.rows[0].buttons[0].data
                            ))
                            if answer.message == 'Обмен произведен!':
                                self.log('Приняли трейд')
                            else:
                                self.log('Ответ на нажатие - ' + str(answer))
                elif isinstance(upd, telethon.tl.types.UpdateEditChannelMessage):
                    message = getattr(upd, 'message', None)
                    origin_id = getattr(getattr(message, 'to_id'), 'channel_id')
                elif isinstance(upd, UpdateChannelPinnedMessage):
                    print('Handling UpdateChannelPinnedMessage: ', upd)
                    self._handle_update_pinned_message(upd)
                    continue

                else:
                    # print('Skipped update class:', upd.__class__.__name__, upd)
                    continue
                if not message:
                    # print('Skipped update without "message" field')
                    continue
                if all(origin_id != prop['id'] for prop in self.ALL_PROPS) and origin_id != self.botid:
                    # print('Skipped message not from chatwars bot: ', message)
                    continue
                # print('New message: ', message, dir(message))
                # print('Text: ', message.message)
                # print('Buttons: ', get_buttons(message))
                message.origin_id = origin_id
                # with self.message_queue_lock:
                #    self.message_queue.append(message)
                self.parsed_text(message)
        except Exception as ex:
            print(ex)
            traceback.print_exc()

**Comment by HippyFizz** [comment]
Of cource is may be a my error, I just want to find solution of it

**Comment by HippyFizz** [comment]
The code drops on send_message method, not on my function

**Comment by Lonami** [comment]
As I said, I rushed to reply (since I thought you were having a bug that was fixed before). I'm not sure how the `SendMessageRequest` can `return None`, because to begin with, if the result of a request `is None`, it will be retried, and if after retrying 5 times it still fails, a `ValueError` is raised instead `return None`.

**Comment by HippyFizz** [comment]
Anyway, do you have any ideas of how I can fix this?

**Comment by Lonami** [comment]
Not quite, no. I'm in the middle of a big refactor which I want to finish before doing anything else. If you would like to help you can check out the [`.send_message`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py#L444) function and try to figure out why such thing can happen. And remember [`.invoke`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_bare_client.py#L345) won't return `None`.

**Comment by HippyFizz** [comment]
It is a really interestion question.
I will try to test it and find a solution, I tried to send messages to users, chats, supergroups, everywhere is the same error occurs ><
If you find anything, don't forget to mention it to me, please!
That you for fast reply

**Comment by HippyFizz** [comment]
I shared my repository to you, if you have a time, you may check out to find a bug in my code or yours

**Comment by Lonami** [comment]
I don't have any notification to join another repository. Either way, the bug is probably in the library itself.

**Comment by HippyFizz** [comment]
Check your email, I sent invite link

**Comment by Lonami** [comment]
Invoking requests from a background thread will always `return None`:

https://github.com/LonamiWebs/Telethon/blob/ee082324738b4bfec721b85fae73803f9bcdb06f/telethon/telegram_client.py#L242-L247

See https://github.com/LonamiWebs/Telethon/wiki/Working-with-Updates. Feel free to revoke my access to your private repository.
