### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by evandrix** [LonamiWebs/Telethon#276]
I've previously signed in, and created my .session file.

Then, when I re-reun the program to perform actions on Telegram, it fails to connect with the following error message:

```
Traceback (most recent call last):
  File "script.py", line *, in <module>
    client.connect()
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 181, in connect
    self.sync_updates()
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 1022, in sync_updates
    self.updates.process(self(GetStateRequest()))
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 263, in invoke
    retries=kwargs.get('retries', 5)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 340, in invoke
    raise request.rpc_error
telethon.errors.rpc_errors.ServerError: (ServerError(...), 'RPC_MCGET_FAIL')
```

I've checked to ensure I `sudo pip install -U`'ed, so it's not because I have an arcane version of the library.

Is this due to the library or Telegram's service? I've checked their official Twitter [https://twitter.com/telegram](https://twitter.com/telegram), and there is no report of any service disruption on their end.

**Comment by Lonami** [comment]
`RPC_MCGET_FAIL`, that error is new to me, I have never encountered it before.

**Comment by Lonami** [comment]
https://rpc.pwrtelegram.xyz/?description_for=RPC_MCGET_FAIL:
```json
{"ok":true,"result":"Telegram is having internal issues, please try again later."}
```

**Comment by Lonami** [comment]
@danog suggested to except the error and pray, so I will do that later. Meanwhile, you can `except RPCError as e` and if the message matches, ignore.

**Comment by evandrix** [comment]
ah, i see.

it seems to be working now, thanks!
