### ISSUE TITLE
use library in Laravel project

### ISSUE THREAD

**Issue by mahdiahmadi73** [LonamiWebs/Telethon#286]
hi , is there a way for installing this library on laravel project and use ? example : via composer (composer require Telethon ) ? how can i do that ?

**Comment by Lonami** [comment]
I have no idea what "Laravel" is, or how to use "Composer". Maybe someone else can help you (us, so I can guide others too) with that.

**Comment by danog** [comment]
Laravel is a PHP, framework. 
This is a python library, you can't use it in PHP, use github.com/danog/MadelineProto instead.
