### ISSUE TITLE
support of searching user messages in megagroups

### ISSUE THREAD

**Issue by leshark** [LonamiWebs/Telethon#287]
Is searching all user messages or searching from custom  #date in megagroups supported at this moment?

**Comment by Lonami** [comment]
Everything you can do with an official client, you can do in Telethon. What have you tried?

**Comment by leshark** [comment]
i dont see a method to do this actually

**Comment by Lonami** [comment]
Well, [search](https://lonamiwebs.github.io/Telethon/methods/messages/search.html) isn't enough? It has date parameters. Can you filter specific user messages on official clients?

**Comment by leshark** [comment]
It is enough sure, thanks. But is second argument (string) requared there? If i  fill it with empty string, will it searh all user messages?

**Comment by Lonami** [comment]
No clue, just try. I know how the API works, not how to use it.
