### ISSUE TITLE
Question about searching in groups

### ISSUE THREAD

**Issue by leshark** [LonamiWebs/Telethon#288]
Lonami, in telethon wiki i have found such example:
result = client(SearchRequest(
    entity, 'query', InputMessagesFilterEmpty(), None, None, 0, 0, 100
))
It is SearchRequest with 8 args. But according wiki (https://lonamiwebs.github.io/Telethon/methods/messages/search.html)
It has 11 args and only 1 can be omitted. How Your code works without two params? O_o

**Comment by Lonami** [comment]
Most likely I updated the scheme and forgot to update the wiki. Anyone can edit the wiki to keep it up to date, so if you would like to fix it go ahead. Otherwise I'll do whenever I can.

**Comment by leshark** [comment]
```amount_of_messages_last_week = self(SearchRequest(peer=channel_obj, q='', filter=InputMessagesFilterEmpty(),
                                                                      min_date=dt.datetime.strftime(
                                                                          dt.datetime.today() - dt.timedelta(7),
                                                                          "%Y-%m-%d"),
                                                                      max_date=dt.datetime.strftime(dt.datetime.today(),
                                                                                           "%Y-%m-%d"),
                                                                      offset=0, max_id=0, limit=100, from_id=user_obj)).count()```
i have asked coz i recieve this error (AttributeError: 'str' object has no attribute 'timestamp') running code above

**Comment by Lonami** [comment]
Then some parameter needs a date, not a string. Read the error.
