### ISSUE TITLE
streaming updates instead of polling

### ISSUE THREAD

**Issue by geoHeil** [LonamiWebs/Telethon#289]
Is it possible to use stream new messages via telethon (like a websockert) or is polling mandatory?

I see that several differential update possibilities are already implemented https://lonamiwebs.github.io/Telethon/methods/updates/index.html but would be interested in knowing whether a lower latency notification without manual polling is available.

**Comment by Lonami** [comment]
"Stream new messages"? What do you mean? Telethon currently has a thread that will read everything from the network as it happens, every update is put in a queue, and another thread pops from the queue as soon as it's available. It's as little latency as possible, and I'm not sure if it can get any lower.

A single thread reading and processing everything? You wouldn't be able to read more until you finished processing. It's possible right now, just not exposed nicely yet.

**Comment by geoHeil** [comment]
Thanks for the clarification. I was not aware of updates being handled
automatically.

So far I could find
client.get_dialogs(10)
Which would suggest that polling would be the goto solution to get future
updates. How can I apply your suggestion and actually get notified about
new messages?
I am probably missing a function already present in your API as you suggest
it should already work.
Lonami <notifications@github.com> schrieb am Di. 3. Okt. 2017 um 17:38:

**Comment by Lonami** [comment]
Check out both the Wiki/Getting Started/Working with updates and the Change log over Releases.
