### ISSUE TITLE
How to join a channel/group?

### ISSUE THREAD

**Issue by pazis** [LonamiWebs/Telethon#29]
I need to write a simple script having a function getting channel/group link as input which joins the group/channel and returns a boolean whether the joining was successful or not.

Well, I assume that I don't need update_handler. I just have to do authentication and then without client.run(), I just call the corresponding rpc functions as documented. Am I right?

Can anyone provide an example or something helpful. That would be a big help for me and future readers. Thanks.

**Comment by pazis** [comment]
Well, I wrote this code:

    from telethon import TelegramClient
    from telethon.tl.functions.channels import GetChannelsRequest

    client = TelegramClient('sessionid', api_id=00000, api_hash='MY_HASH')

    result = client.invoke(GetChannelsRequest(?????????????))

    print(result)

The `get_channels.py` file says I need InputChannel as input. How can I have an InputChannel!?

**Comment by pazis** [comment]
Now I added an `InputChannelEmpty` as argument:

```
from telethon import TelegramClient
from telethon.tl.functions.channels import CheckUsernameRequest
from telethon.tl.types import InputChannelEmpty

client = TelegramClient('sessionid', api_id=00000, api_hash='MY_HASH')
input_channel = InputChannelEmpty()
result = client.invoke(CheckUsernameRequest(input_channel, "@channel"))

print(result)
```

but I get this error:
```
self.sender.send(request)
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by pazis** [comment]
I checked out `telegram_client.py` and now added `client.connect()`.
I also changed "@channel" to "channel".

However the result is now `false`. 😢 I'm sure the channel exists. What's the problem?!

**Comment by pazis** [comment]
Well, finally I can resolve the username 😀 .

Full code:

from telethon import TelegramClient
from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.types import InputChannelEmpty

client = TelegramClient('sessionid', api_id=00000, api_hash='MY_HASH')
input_channel = InputChannelEmpty()
result = client.invoke(ResolveUsernameRequest("channel"))

print(result)

**Comment by pazis** [comment]
I used the information returned by `ResolveUsernameRequst` to make `InputChannel` object. Now I `CheckUsernameRequest` but I get:

`'Unknown error message with code 400: CHAT_ID_INVALID')`

I used `result.chats[0].id` as `channel_id` and `result.chats[0].access_hash` as `access_hash` to create `InputChannel` object. I'm also sure that the channel exists. Why do I get `CHAT_ID_INVALID`?

**Comment by pazis** [comment]
Well, I got it. There is no need to call `CheckUsernameRequest`. I can join using `JoinChannelRequest`.

**Comment by XyLoNaMiyX** [comment]
Glad you managed to fix it on your own :)

**Comment by rex101** [comment]
@pazis how you solved this problem, I'm still facing the same probelm

**Comment by pazis** [comment]
@rex101 use `JoinChannelRequest`

**Comment by rex101** [comment]
@pazis I have solved these problem but now i am stuck on a new irritataing situation , i am using INVITE TO CHANNEL method to add members to my personal group but don't know what is the limit to add memebers , is there anyway to get out of these ???

**Comment by Peet420** [comment]
@pazis Im getting <coroutine object UserMethods.__call__ at 0x7feb8a89ba40> with this script;

from telethon import TelegramClient
from telethon.tl.types import InputChannelEmpty
from telethon.tl.functions.channels import JoinChannelRequest

client= TelegramClient('anon', api_id=12372189, api_hash='93d4ba8c9a7dd921c68f3a941ea52a43')
input_channel = InputChannelEmpty()
result= client(JoinChannelRequest("testadbottwo2"))

print(result)

But my account does not join in the group, what am i doing wrong?

**Comment by New-dev0** [comment]
> @pazis Im getting <coroutine object UserMethods.**call** at 0x7feb8a89ba40> with this script;

Possible Reasons
1. Client is not started yet (if same as in example)
2. Methods are used to be  called in async loop (you can use sync TelegramClient, if want to)
