### ISSUE TITLE
get_message_history: Max numbers of return list messages not above 100

### ISSUE THREAD

**Issue by CrownID** [LonamiWebs/Telethon#290]
Versions: 
Python 3.6.2
Telethon==0.14

Max numbers of return list messages not above 100:

`
total, messages, senders = client.get_message_history('channel', limit=200)
`
`
len(messages)
`
Out[89]: 100

`
In [90]: messages[0].id
`
Out[90]: 353

`
In [93]: total, messages, senders = client.get_message_history('channel', min_id=100, limit=1000)
`
`
In [94]: len(messages)
`
Out[94]: 100

**Comment by Lonami** [comment]
Telegram's API limitation. There's plans, however, to actually retrieve as many messages as the user wants to, similar to how it's done for `.get_dialogs`. We can keep this open until it's implemented.
