### ISSUE TITLE
Implement a method to make search more comfortable

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#292]
Simply modify `telegram_client.py` to have a method that makes searching for messages trivial.

If you need more information about what all this about a hacktoberfest is, check out https://hacktoberfest.digitalocean.com. If you need more details, please let me know!

**Comment by vidhan13j07** [comment]
Hi @Lonami, I'll like to take up this issue.

**Comment by Lonami** [comment]
Go ahead! Basically make as many parameters as you can optional, so that users can use the search in a comfortable way without the need to supply them all.

**Comment by Lonami** [comment]
Bump.

**Comment by Lonami** [comment]
I'm just going to close this until someone really needs this function. It wouldn't be so trivial because it would need to have a nice interface to the results anyway.
