### ISSUE TITLE
attribute of the sent file

### ISSUE THREAD

**Issue by 88ee55** [LonamiWebs/Telethon#294]
can I change the attribute for the file being sent?
Only the file name was visible, not the whole path to it

method send_file
from
DocumentAttributeFilename (os.path.abspath (file))
to
DocumentAttributeFilename (os.path.basepath (file))

**Comment by Lonami** [comment]
Currently the attributes needed are inferred automatically. If you want more customization, upload the file yourself and then send it with whatever attributes you need (just read the source of the method

**Comment by 88ee55** [comment]
it seems unsafe to display the full path to the file

**Comment by Lonami** [comment]
That's totally a mistake, it should be the base name as you pointed out. I can't fix it right now but you can make a pull request. Are you aware of the hacktoberfest?

**Comment by 88ee55** [comment]
About hacktoberfest heard, I'll try to make a pull request

**Comment by Lonami** [comment]
Since there was a "major" bug (`.get_input_entity` was failing for *a lot* of cases), I decided to patch this myself and submit a version using `.basename` to PyPi, so you don't have to make the pull request anymore. Sorry for being so impatient.

**Comment by 88ee55** [comment]
All perfectly
Thank you
