### ISSUE TITLE
update_handlers wont work for me in latest version (0.15)

### ISSUE THREAD

**Issue by doryashar** [LonamiWebs/Telethon#295]
hi guys,
I have this simple client:

    @staticmethod
    def update_handler(update_object):
        print('update handler')

client = InteractiveTelegramClient('dorit')
client.add_update_handler(client.update_handler)

and for some reason I don't receive any update
this issue occurs only since I have upgraded the version to 0.15
any suggestions ?

**Comment by Lonami** [comment]
Did you read the wiki about updates?

**Comment by doryashar** [comment]
yes, and I guess you wrote something about it which I can't understand. 
can you please elaborate on how to make it work ?
Thanks!

**Comment by Lonami** [comment]
You just have to `TelegramClient('name', api_id, api_hash, update_workers=n)` where `n` is a number like 4. Then update handlers will work. I'm not sure why you're using `InteractiveTelegramClient` to run your code as that's just an example.
