### ISSUE TITLE
Issue with InviteToChannelRequest

### ISSUE THREAD

**Issue by pashbelg** [LonamiWebs/Telethon#298]
Guys, pls help! I'm trying to do InviteToChannelRequest, but nothing happened! I have a complete and true code, moreover i don't get any errors...

**Comment by Lonami** [comment]
Not enough information.

**Comment by VasilMirov** [comment]
I have experienced this as well. Using InviteToChannelRequest all the right parameters are passed. In the group it shows "NumberUsedToAddMemberToGroup invited OtherUser", but the number of the group itself stays the same, meaning the member is not actually added. I think this is the more detailed explanation @pashbelg wanted to make. I know this is an old issue sorry...

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

**Comment by VasilMirov** [comment]
@Lonami is there no documentation of telegrams API?

**Comment by Lonami** [comment]
Sorry, but the issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by anhkhoinguyen1310** [comment]
Yeah I experienced the same thing as well. Using exact InviteToChannelRequest and pass all corrected parameters. But it's still the same. The logging shows it's Member adds to the group. but the number of members stay the same o.O. 

`import logging
from telethon import TelegramClient
from telethon.tl.functions.channels import InviteToChannelRequest
from telethon.tl.types import InputPeerUser
from telethon.errors.rpcerrorlist import PeerFloodError, UserPrivacyRestrictedError, FloodWaitError
import time
import json

logging.basicConfig(level=logging.INFO)

api_id = '#'
api_hash = '#''
phone = '#''
client = TelegramClient(phone, api_id, api_hash)

async def main():
    await client.start()

    with open('members.json', 'r') as file:
        members = json.load(file)

    target_group = '@'
    target = await client.get_entity(target_group)

    base_delay = 60  # Base delay in seconds

    for member in members:
        try:
            user = InputPeerUser(member['id'], member['access_hash'])
            await client(InviteToChannelRequest(target, [user]))
            logging.info(f"Directly added member {member['username']} successfully.")
            time.sleep(base_delay)
        except PeerFloodError:
            logging.error("Hit rate limit, increasing delay.")
            base_delay *= 2  # Double the delay
            time.sleep(base_delay)
        except UserPrivacyRestrictedError:
            logging.warning(f"Cannot directly add {member['username']} due to privacy settings.")
        except FloodWaitError as e:
            logging.error(f"Telegram says to wait for {e.seconds} seconds.")
            time.sleep(e.seconds)
        except Exception as e:
            logging.error(f"Unexpected error: {str(e)}")

    await client.disconnect()
    logging.info("Disconnected.")

with client:
    client.loop.run_until_complete(main())`
