### ISSUE TITLE
is_user_authorized

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#299]
I print result of ‍‍`c‍lient.is_user_authorized()` method always in my program.
Why sometimes this method return to False and a few minutes later return True for the same number!
i using : Telethon==0.13.6

**Comment by Lonami** [comment]
1. Consider upgrading.
2. This method returns `True` if the user is signed in and can invoke methods like `GetStateRequest` without raising an error. So if it returns `False`, you should `.sign_in`. I have no idea how "it can return True a few minutes later". There's probably something weird in your code (and there's not much I can do with this information anyway).

**Comment by alihossein** [comment]
@Lonami 
this is my code  : 
``` python
session_path = os.getcwd() + '/sessions/' + phone_number
client = TelegramClient(session=session_path, api_id=api_id, api_hash=api_hash, proxy=(),
                                        timeout=timedelta(seconds=30))

client.connect()
is_user_authorized = client.is_user_authorized()
print(is_user_authorized )
...
```

**Comment by Lonami** [comment]
> The ` is_user_authorized ` method sometimes returns False and returns True a few moments later. 
> It may be due to network disruptions.
> Is there any other way to check if my number has been Banned or disabled?
> or is it possible that the ` is_user_authorized ` method attempts to communicate multiple times automatically?

**Comment by Lonami** [comment]
The method is only a wrapper around a private boolean value. This value is set to `True` when you call `.connect()`, and if a `GetStateRequest()` doesn't fail. It's not modified anywhere else. So if you're connecting again in some place it probably updated the value. I'm not sure how this behaves with banned/restricted users.

**Comment by alihossein** [comment]
@Lonami thanks. 

> So if you're connecting again in some place it probably updated the value

I don`t understand the meaning of this sentence. please explain more.

**Comment by Lonami** [comment]
If `.connect()` is being called in some other place of your code while those "several minutes passed", and `UpdateStatusRequest()` succeeds, it will update the flag value that indicates whether you're authorized or not. Such flag is returned by `.is_user_authorized()`. No request is made. Unless you're using an out-of-date version.

**Comment by alihossein** [comment]
If the number that we've Login into Tetlone, use in other apps is causing the problem?

**Comment by Lonami** [comment]
What?
