### ISSUE TITLE
Uploading file from stdin

### ISSUE THREAD

**Issue by rany2** [LonamiWebs/Telethon#3007]
Hi, I'm using telegram-cloud and I'm unable to upload a file from stdin. I think this might be because of some check in Telethon  

Is there any way to workaround this? https://github.com/iw4p/telegram-cloud/issues/22

**Comment by Lonami** [comment]
Telethon supports file-like objects. You should be able to upload anything with a `read` method, whether it's `async` or not. Please bump this issue so I can reopen if you can provide one such example that fails.

**Comment by rany2** [comment]
<pre>$ echo test | tgcloud -n d -u me --path /dev/stdin -m upload --format text --caption test 
Traceback (most recent call last):
  File &quot;/home/rany/.local/bin/tgcloud&quot;, line 33, in &lt;module&gt;
    sys.exit(load_entry_point(&apos;telegram-cloud==1.4.1&apos;, &apos;console_scripts&apos;, &apos;tgcloud&apos;)())
  File &quot;/home/rany/.local/lib/python3.9/site-packages/telegramcloud/__main__.py&quot;, line 68, in cli
    client.loop.run_until_complete(main())
  File &quot;/usr/lib64/python3.9/asyncio/base_events.py&quot;, line 642, in run_until_complete
    return future.result()
  File &quot;/home/rany/.local/lib/python3.9/site-packages/telegramcloud/__main__.py&quot;, line 63, in main
    message = await client.send_file(entity=target_chat, file=args.path, caption=args.caption, progress_callback=upload_callback, parse_mode=parse_mode)
  File &quot;/home/rany/.local/lib/python3.9/site-packages/telethon/client/uploads.py&quot;, line 375, in send_file
    file_handle, media, image = await self._file_to_media(
  File &quot;/home/rany/.local/lib/python3.9/site-packages/telethon/client/uploads.py&quot;, line 710, in _file_to_media
    raise ValueError(
ValueError: Failed to convert /dev/stdin to media. Not an existing file, an HTTP URL or a valid bot-API-like file ID
</pre>

Is this of any help? I removed the exception so you can see the error I get

**Comment by Lonami** [comment]
Does it work if you pass `open('/dev/stdin', 'rb')` instead of the path?

**Comment by rany2** [comment]
yes it does! thanks a lot :)

**Comment by rany2** [comment]
I have an issue now with uploading very big files. It puts the entire file in memory and causes me to OOM

**Comment by Lonami** [comment]
The file size needs to be known beforehand. I believe you can specify it. Feel free to investigate why it fails with the filename and send a patch.

**Comment by rany2** [comment]
@Lonami Thanks! So any time I upload from stdin it show read everything to determine file size. Is this a requirement by Telegram's protocol?

**Comment by Lonami** [comment]
Telegram does require the file size to be known beforehand, but like I said, I believe you can tell Telethon; otherwise it falls back to reading all the file in memory (so that it can seek to the end, get size, seek back; which it can't with `stdin`).
