### ISSUE TITLE
Mute and Archive a channel

### ISSUE THREAD

**Issue by kill0rz** [LonamiWebs/Telethon#3009]
I would like to ask for two new functions:

* One to mute a channel I joined
* One to archive a channel/chat

That would be great! Thank you!

**Comment by Lonami** [comment]
* Handled by `UpdateNotifySettingsRequest`
* Handled by `client.edit_folder`

Does the above suit your needs?

**Comment by kill0rz** [comment]
Did not notice that. Perfect, thank you! :)
