### ISSUE TITLE
Packaging Telethon using stdeb

### ISSUE THREAD

**Issue by swapravo** [LonamiWebs/Telethon#3013]
I have been trying to package Telethon for Debian using stdeb (https://github.com/astraw/stdeb).

I ran: python3 setup.py --command-packages=stdeb.command bdist_deb
> Generating TLObjects...
Generating RPCErrors...
running bdist_deb
running sdist_dsc
running egg_info
creating Telethon.egg-info
writing Telethon.egg-info/PKG-INFO
writing dependency_links to Telethon.egg-info/dependency_links.txt
writing requirements to Telethon.egg-info/requires.txt
writing top-level names to Telethon.egg-info/top_level.txt
writing manifest file 'Telethon.egg-info/SOURCES.txt'
reading manifest file 'Telethon.egg-info/SOURCES.txt'
writing manifest file 'Telethon.egg-info/SOURCES.txt'
running sdist
running check
creating Telethon-1.21.1
creating Telethon-1.21.1/Telethon.egg-info
creating Telethon-1.21.1/telethon
creating Telethon-1.21.1/telethon/client
creating Telethon-1.21.1/telethon/crypto
creating Telethon-1.21.1/telethon/errors
creating Telethon-1.21.1/telethon/events
creating Telethon-1.21.1/telethon/extensions
creating Telethon-1.21.1/telethon/network
creating Telethon-1.21.1/telethon/network/connection
creating Telethon-1.21.1/telethon/sessions
creating Telethon-1.21.1/telethon/tl
creating Telethon-1.21.1/telethon/tl/core
creating Telethon-1.21.1/telethon/tl/custom
creating Telethon-1.21.1/telethon/tl/functions
creating Telethon-1.21.1/telethon/tl/patched
creating Telethon-1.21.1/telethon/tl/types
copying files to Telethon-1.21.1...
copying README.rst -> Telethon-1.21.1
copying pyproject.toml -> Telethon-1.21.1
copying setup.py -> Telethon-1.21.1
copying Telethon.egg-info/PKG-INFO -> Telethon-1.21.1/Telethon.egg-info
copying Telethon.egg-info/SOURCES.txt -> Telethon-1.21.1/Telethon.egg-info
copying Telethon.egg-info/dependency_links.txt -> Telethon-1.21.1/Telethon.egg-info
copying Telethon.egg-info/requires.txt -> Telethon-1.21.1/Telethon.egg-info
copying Telethon.egg-info/top_level.txt -> Telethon-1.21.1/Telethon.egg-info
copying telethon/__init__.py -> Telethon-1.21.1/telethon
copying telethon/entitycache.py -> Telethon-1.21.1/telethon
copying telethon/helpers.py -> Telethon-1.21.1/telethon
copying telethon/hints.py -> Telethon-1.21.1/telethon
copying telethon/password.py -> Telethon-1.21.1/telethon
copying telethon/requestiter.py -> Telethon-1.21.1/telethon
copying telethon/statecache.py -> Telethon-1.21.1/telethon
copying telethon/sync.py -> Telethon-1.21.1/telethon
copying telethon/utils.py -> Telethon-1.21.1/telethon
copying telethon/version.py -> Telethon-1.21.1/telethon
copying telethon/client/__init__.py -> Telethon-1.21.1/telethon/client
copying telethon/client/account.py -> Telethon-1.21.1/telethon/client
copying telethon/client/auth.py -> Telethon-1.21.1/telethon/client
copying telethon/client/bots.py -> Telethon-1.21.1/telethon/client
copying telethon/client/buttons.py -> Telethon-1.21.1/telethon/client
copying telethon/client/chats.py -> Telethon-1.21.1/telethon/client
copying telethon/client/dialogs.py -> Telethon-1.21.1/telethon/client
copying telethon/client/downloads.py -> Telethon-1.21.1/telethon/client
copying telethon/client/messageparse.py -> Telethon-1.21.1/telethon/client
copying telethon/client/messages.py -> Telethon-1.21.1/telethon/client
copying telethon/client/telegrambaseclient.py -> Telethon-1.21.1/telethon/client
copying telethon/client/telegramclient.py -> Telethon-1.21.1/telethon/client
copying telethon/client/updates.py -> Telethon-1.21.1/telethon/client
copying telethon/client/uploads.py -> Telethon-1.21.1/telethon/client
copying telethon/client/users.py -> Telethon-1.21.1/telethon/client
copying telethon/crypto/__init__.py -> Telethon-1.21.1/telethon/crypto
copying telethon/crypto/aes.py -> Telethon-1.21.1/telethon/crypto
copying telethon/crypto/aesctr.py -> Telethon-1.21.1/telethon/crypto
copying telethon/crypto/authkey.py -> Telethon-1.21.1/telethon/crypto
copying telethon/crypto/cdndecrypter.py -> Telethon-1.21.1/telethon/crypto
copying telethon/crypto/factorization.py -> Telethon-1.21.1/telethon/crypto
copying telethon/crypto/libssl.py -> Telethon-1.21.1/telethon/crypto
copying telethon/crypto/rsa.py -> Telethon-1.21.1/telethon/crypto
copying telethon/errors/__init__.py -> Telethon-1.21.1/telethon/errors
copying telethon/errors/common.py -> Telethon-1.21.1/telethon/errors
copying telethon/errors/rpcbaseerrors.py -> Telethon-1.21.1/telethon/errors
copying telethon/errors/rpcerrorlist.py -> Telethon-1.21.1/telethon/errors
copying telethon/events/__init__.py -> Telethon-1.21.1/telethon/events
copying telethon/events/album.py -> Telethon-1.21.1/telethon/events
copying telethon/events/callbackquery.py -> Telethon-1.21.1/telethon/events
copying telethon/events/chataction.py -> Telethon-1.21.1/telethon/events
copying telethon/events/common.py -> Telethon-1.21.1/telethon/events
copying telethon/events/inlinequery.py -> Telethon-1.21.1/telethon/events
copying telethon/events/messagedeleted.py -> Telethon-1.21.1/telethon/events
copying telethon/events/messageedited.py -> Telethon-1.21.1/telethon/events
copying telethon/events/messageread.py -> Telethon-1.21.1/telethon/events
copying telethon/events/newmessage.py -> Telethon-1.21.1/telethon/events
copying telethon/events/raw.py -> Telethon-1.21.1/telethon/events
copying telethon/events/userupdate.py -> Telethon-1.21.1/telethon/events
copying telethon/extensions/__init__.py -> Telethon-1.21.1/telethon/extensions
copying telethon/extensions/binaryreader.py -> Telethon-1.21.1/telethon/extensions
copying telethon/extensions/html.py -> Telethon-1.21.1/telethon/extensions
copying telethon/extensions/markdown.py -> Telethon-1.21.1/telethon/extensions
copying telethon/extensions/messagepacker.py -> Telethon-1.21.1/telethon/extensions
copying telethon/network/__init__.py -> Telethon-1.21.1/telethon/network
copying telethon/network/authenticator.py -> Telethon-1.21.1/telethon/network
copying telethon/network/mtprotoplainsender.py -> Telethon-1.21.1/telethon/network
copying telethon/network/mtprotosender.py -> Telethon-1.21.1/telethon/network
copying telethon/network/mtprotostate.py -> Telethon-1.21.1/telethon/network
copying telethon/network/requeststate.py -> Telethon-1.21.1/telethon/network
copying telethon/network/connection/__init__.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/network/connection/connection.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/network/connection/http.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/network/connection/tcpabridged.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/network/connection/tcpfull.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/network/connection/tcpintermediate.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/network/connection/tcpmtproxy.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/network/connection/tcpobfuscated.py -> Telethon-1.21.1/telethon/network/connection
copying telethon/sessions/__init__.py -> Telethon-1.21.1/telethon/sessions
copying telethon/sessions/abstract.py -> Telethon-1.21.1/telethon/sessions
copying telethon/sessions/memory.py -> Telethon-1.21.1/telethon/sessions
copying telethon/sessions/sqlite.py -> Telethon-1.21.1/telethon/sessions
copying telethon/sessions/string.py -> Telethon-1.21.1/telethon/sessions
copying telethon/tl/__init__.py -> Telethon-1.21.1/telethon/tl
copying telethon/tl/alltlobjects.py -> Telethon-1.21.1/telethon/tl
copying telethon/tl/tlobject.py -> Telethon-1.21.1/telethon/tl
copying telethon/tl/core/__init__.py -> Telethon-1.21.1/telethon/tl/core
copying telethon/tl/core/gzippacked.py -> Telethon-1.21.1/telethon/tl/core
copying telethon/tl/core/messagecontainer.py -> Telethon-1.21.1/telethon/tl/core
copying telethon/tl/core/rpcresult.py -> Telethon-1.21.1/telethon/tl/core
copying telethon/tl/core/tlmessage.py -> Telethon-1.21.1/telethon/tl/core
copying telethon/tl/custom/__init__.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/adminlogevent.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/button.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/chatgetter.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/conversation.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/dialog.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/draft.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/file.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/forward.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/inlinebuilder.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/inlineresult.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/inlineresults.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/inputsizedfile.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/message.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/messagebutton.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/participantpermissions.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/qrlogin.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/custom/sendergetter.py -> Telethon-1.21.1/telethon/tl/custom
copying telethon/tl/functions/__init__.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/account.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/auth.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/bots.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/channels.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/contacts.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/folders.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/help.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/langpack.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/messages.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/payments.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/phone.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/photos.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/stats.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/stickers.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/updates.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/upload.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/functions/users.py -> Telethon-1.21.1/telethon/tl/functions
copying telethon/tl/patched/__init__.py -> Telethon-1.21.1/telethon/tl/patched
copying telethon/tl/types/__init__.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/account.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/auth.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/channels.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/contacts.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/help.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/messages.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/payments.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/phone.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/photos.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/stats.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/storage.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/updates.py -> Telethon-1.21.1/telethon/tl/types
copying telethon/tl/types/upload.py -> Telethon-1.21.1/telethon/tl/types
Writing Telethon-1.21.1/setup.cfg
creating dist
Creating tar archive
removing 'Telethon-1.21.1' (and everything under it)
dpkg-buildpackage: info: source package telethon
dpkg-buildpackage: info: source version 1.21.1-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Lonami Exo <totufals@hotmail.com>
 dpkg-source --before-build .
dpkg-source: info: using options from telethon-1.21.1/debian/source/options: --extend-diff-ignore=\.egg-info$
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=python_distutils
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/user0/Documents/temp/pac/Telethon-1.21.1/deb_dist/telethon-1.21.1'
python3 setup.py clean -a
Traceback (most recent call last):
  File "/home/user0/Documents/temp/pac/Telethon-1.21.1/deb_dist/telethon-1.21.1/setup.py", line 244, in <module>
    main(sys.argv)
  File "/home/user0/Documents/temp/pac/Telethon-1.21.1/deb_dist/telethon-1.21.1/setup.py", line 155, in main
    generate(argv[2:], argv[1])
  File "/home/user0/Documents/temp/pac/Telethon-1.21.1/deb_dist/telethon-1.21.1/setup.py", line 66, in generate
    from telethon_generator.parsers import\
ModuleNotFoundError: No module named 'telethon_generator'
make[1]: *** [debian/rules:10: override_dh_auto_clean] Error 1
make[1]: Leaving directory '/home/user0/Documents/temp/pac/Telethon-1.21.1/deb_dist/telethon-1.21.1'
make: *** [debian/rules:7: clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
Traceback (most recent call last):
  File "/home/user0/Documents/temp/pac/Telethon-1.21.1/setup.py", line 244, in <module>
    main(sys.argv)
  File "/home/user0/Documents/temp/pac/Telethon-1.21.1/setup.py", line 194, in main
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user0/.local/lib/python3.9/site-packages/stdeb/command/bdist_deb.py", line 34, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user0/.local/lib/python3.9/site-packages/stdeb/command/sdist_dsc.py", line 137, in run
    build_dsc(debinfo,
  File "/home/user0/.local/lib/python3.9/site-packages/stdeb/util.py", line 1569, in build_dsc
    dpkg_buildpackage(*args, cwd=fullpath_repackaged_dirname)
  File "/home/user0/.local/lib/python3.9/site-packages/stdeb/util.py", line 585, in dpkg_buildpackage
    process_command(args, cwd=cwd)
  File "/home/user0/.local/lib/python3.9/site-packages/stdeb/util.py", line 226, in process_command
    check_call(args, cwd=cwd)
  File "/home/user0/.local/lib/python3.9/site-packages/stdeb/util.py", line 59, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2

I pip3 installed Telethon (v1.21.1).
Running the same with sudo also gives the same error.
I believe the subsequent make errors are because of the missing module.
Any idea why 'telethon_generator' is not being detected?

**Comment by Lonami** [comment]
I have no knowledge here, perhaps the root is not being added to `PYTHON_PATH` for some reason.

---

Besides, I'd like to ask, does this mean Telethon will be available via Debian's repositories (aka "installable via `apt`"), or what is your goal here?

**Comment by swapravo** [comment]
I'll see if that is the issue. This happened on Debian 10. I shall try it on other platforms as well as and let you know.

Apt installing telethon would be nice, but packaging it for Debian is not very straightforward. Check [Debian's LibraryStyleGuide](https://wiki.debian.org/Python/LibraryStyleGuide), [Pybuild](https://wiki.debian.org/Python/Pybuild) out for starters.

Right now, I am trying to pack it for personal use. I shall definitely negotiate the details with you if I do pack it for Debian.

**Comment by Lonami** [comment]
Ah, personal use, okay. Good luck. If there's any changes related in Telethon to make it "friendlier" to package I guess we can track that here.

**Comment by swapravo** [comment]
I tried printing the current working directory from inside of the if __name__ == '__main__' clause in setup.py :
```
if __name__ == '__main__':
    import pathlib
    with TempWorkDir():
        print(pathlib.Path.cwd())
        main(sys.argv)
```
Turns out that the current directory changes from ./Telethon-1.21.1 to ./Telethon-1.21.1/deb_dist/telethon-1.21.1, which does not have the telethon_generator module.

**Comment by Lonami** [comment]
Perhaps you should run the generator manually before packaging, then?

**Comment by Lonami** [comment]
Feel free to bump or send a PR if any support is needed from Telethon itself.
