### ISSUE TITLE
List of multiphotos inside Message class

### ISSUE THREAD

**Issue by CaramelHeaven** [LonamiWebs/Telethon#3018]
For example, we have a one text and group of images in single post in channel. 

I want to extract these data, what do I do? I use `get_messages` or `iter_messages` and as a result I get a one message object, which contains single image, and second object which contains another image and channel message.

Is telethon provide a better solution for this situation or no? I want to get one message object which contain list of Photo objects.

For example:
```
Message(id=9, message='', media=MessageMediaPhoto(photo=Photo(id=1, access_hash=,.....)

Message(id=8, message='main message of post', .. media=MessageMediaPhoto(photo=Photo(id=2, access_hash=......)))
```

**Comment by Lonami** [comment]
Albums are always separate messages according to Telegram. You check which correspond to which with the `grouped_id`.

**Comment by andrei-piarainc** [comment]
@Lonami Sorry for recovering this topic, but can we get to know, how many messages should be under particular `grouped_id` ? To ensure that we collected all of them, and continue processing as a single post.

**Comment by Lonami** [comment]
No. You can't know how many messages share the same `grouped_id`. The best you can do is get messages and match those with the same `grouped_id` until you're happy.
