### ISSUE TITLE
some time , Confusing error 

### ISSUE THREAD

**Issue by coolksj** [LonamiWebs/Telethon#3021]
Sometimes, some unstable factors will lead to chaos, which will be banned, especially when many accounts are working together, a chaos will pay a heavy price. 

07 21:30:45.398[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypting 1 message(s) in 36 bytes for sending
07 21:30:45.412[8615874045014.network.mtprotosender(15996)]-DEBUG:Handling update Updates
07 21:30:45.412[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:45.413[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted messages put in a queue to be sent
07 21:30:45.413[8615874045014.network.mtprotosender(15996)]-DEBUG:Waiting for messages to send...
07 21:30:45.413[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407735323985932 to MsgsAck (2469c426448)
07 21:30:45.413[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypting 1 message(s) in 36 bytes for sending
07 21:30:45.426[8615874045014.network.mtprotosender(15996)]-DEBUG:Handling update Updates
07 21:30:45.426[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:45.426[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted messages put in a queue to be sent
07 21:30:45.426[8615874045014.network.mtprotosender(15996)]-DEBUG:Waiting for messages to send...
07 21:30:45.426[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407735375846744 to MsgsAck (2469c426788)
07 21:30:45.426[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypting 1 message(s) in 36 bytes for sending
07 21:30:45.427[8615874045014.network.connection.connection(15996)]-INFO:The server closed the connection while sending
07 21:30:45.428[8615874045014.network.connection.connection(15996)]-INFO:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
07 21:30:45.445[8615874045014.network.mtprotosender(15996)]-DEBUG:Handling update Updates
07 21:30:45.445[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:45.445[8615874045014.network.mtprotosender(15996)]-INFO:Connection closed while receiving data
07 21:30:45.454[8615874045014.network.mtprotosender(15996)]-INFO:Closing current connection to begin reconnect...
07 21:30:45.454[8615874045014.network.connection.connection(15996)]-INFO:<class 'ConnectionResetError'> during disconnect: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
07 21:30:45.468[8615874045014.network.mtprotosender(15996)]-INFO:Connecting to 91.108.56.146:443/TcpFull...
07 21:30:45.469[8615874045014.network.mtprotosender(15996)]-DEBUG:Connection attempt 1...
07 21:30:55.477[8615874045014.network.mtprotosender(15996)]-WARNING:Attempt 1 at connecting failed: ConnectionError: Proxy connection timed out: 10
07 21:30:56.476[8615874045014.network.mtprotosender(15996)]-DEBUG:Connection attempt 2...
07 21:30:56.702[8615874045014.network.mtprotosender(15996)]-DEBUG:Connection success!
07 21:30:56.702[8615874045014.network.mtprotosender(15996)]-DEBUG:Starting send loop
07 21:30:56.702[8615874045014.network.mtprotosender(15996)]-DEBUG:Starting receive loop
07 21:30:56.702[8615874045014.network.mtprotosender(15996)]-INFO:Connection to 91.108.56.146:443/TcpFull complete!
07 21:30:56.733[8615874045014.network.mtprotosender(15996)]-DEBUG:Waiting for messages to send...
07 21:30:56.733[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407783850276732 to GetChannelDifferenceRequest (246c711fc08)
07 21:30:56.733[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407783850276736 to GetChannelDifferenceRequest (2469b9e1148)
07 21:30:56.734[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407783854155324 to GetDifferenceRequest (2469dbbf8c8)
07 21:30:56.764[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407783973837636 to GetChannelDifferenceRequest (246b09e5048)
07 21:30:56.764[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407783973837640 to MsgsAck (246c728cb88)
07 21:30:56.764[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypting 5 message(s) in 252 bytes for sending
07 21:30:56.766[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted data, id = 6948407783850276732, state = GetChannelDifferenceRequest(channel=InputChannel(channel_id=1202351268, access_hash=70393562285150841), filter=ChannelMessagesFilterEmpty(), pts=148454, limit=100, force=True), now sending
07 21:30:56.767[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted data, id = 6948407783850276736, state = GetChannelDifferenceRequest(channel=InputChannel(channel_id=1334725499, access_hash=6456461317764583219), filter=ChannelMessagesFilterEmpty(), pts=13196456, limit=100, force=True), now sending
07 21:30:56.767[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted data, id = 6948407783854155324, state = GetDifferenceRequest(pts=554, date=datetime.datetime(2021, 4, 7, 13, 30, 40, tzinfo=datetime.timezone.utc), qts=0, pts_total_limit=None), now sending
07 21:30:56.767[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted data, id = 6948407783973837636, state = GetChannelDifferenceRequest(channel=InputChannel(channel_id=1471089592, access_hash=-6735368066678513390), filter=ChannelMessagesFilterEmpty(), pts=11650069, limit=100, force=True), now sending
07 21:30:56.767[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted messages put in a queue to be sent
07 21:30:56.767[8615874045014.network.mtprotosender(15996)]-DEBUG:Waiting for messages to send...
07 21:30:56.767[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:56.767[8615874045014.extensions.messagepacker(15996)]-DEBUG:Assigned msg_id = 6948407783985803388 to GetUsersRequest (2469b9dba88)
07 21:30:56.770[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypting 1 message(s) in 32 bytes for sending
07 21:30:56.771[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted data, id = 6948407783985803388, state = GetUsersRequest(id=[InputUserSelf()]), now sending
07 21:30:56.771[8615874045014.network.mtprotosender(15996)]-DEBUG:Encrypted messages put in a queue to be sent
07 21:30:56.771[8615874045014.network.mtprotosender(15996)]-DEBUG:Waiting for messages to send...
07 21:30:57.005[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.006[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.010[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.010[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.015[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.017[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.025[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.025[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.030[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.030[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.037[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.037[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.045[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.045[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.050[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.051[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.057[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.057[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.063[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.063[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.068[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.069[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.074[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.075[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.079[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.081[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.096[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.097[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.113[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID
07 21:30:57.114[8615874045014.network.mtprotosender(15996)]-DEBUG:Receiving items from the network...
07 21:30:57.119[8615874045014.network.mtprotosender(15996)]-WARNING:Security error while unpacking a received message: Server replied with a wrong session ID

**Comment by Lonami** [comment]
Please provide a clear, small reproduction example, so that I can encounter the issue myself. Closing until that happens.
