### ISSUE TITLE
How to poll for new messages?

### ISSUE THREAD

**Issue by mojovski** [LonamiWebs/Telethon#3022]
Hi, I was trying to use the event methodology to get new messages in a channel, but this did not work. No error, just No messages received even if some were sent.

So I tried to periodically download messages on my own. This worked but using the interval of 2 seconds and getting last 4 messages, resulted in a rate limit and a lock for hours...

Any ideas how much queries I am allowed to send?
And why the event system of telethon did not work?

**Comment by Lonami** [comment]
Please post a small reproducible example that exhibits the behaviour you describe. Getting messages should not result in a several-hour flood. Closing until then.
