### ISSUE TITLE
download_media cannot download full gif size

### ISSUE THREAD

**Issue by EvilMegaDroid** [LonamiWebs/Telethon#3025]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
async def main():
    await client.get_dialogs()
    source_channel = await client.get_entity(xxxx)

    ## Original file is 550x400, saved through browser, also sending through Telegram Android

    ## This sends the file as 320x234
    msg = await client.send_file(source_channel, "http://www.personal.psu.edu/crd5112/photos/GIF%20Example.gif")

    # ## Telethon downloads it as 320x234
    await msg.download_media("media_test_downloaded.gif")

    ## Sent the file through Telegram Android, testing if Telethon would download it as 320x234 or 550x400, saving through
    # ## Telegram Android downloads it as 550x400, send the gif through another app and try to download with telethon.

    latest_msg = await client.get_messages(source_channel, limit=1)
    await latest_msg[0].download_media("media_test_downloaded_1.gif")
    ## This result in 320x234, it should result in 550x400 since the gif was uploaded via Telegram Android so there's no chance of it being smaller than that
    ## Downloading the gif through Telegram android verifies that

```

I tried with thumb=-1 but that returned a static image instead (not a gif)

Uploading via telethon results in the gif being uploaded as 320x234. Downloading via telethon always returns 320x234 even if the file was uploaded via **Telegram Android**

I think this is a bug in the library since when I try to download the file via **Telegram Android** (if its uploaded via it) it results in 550x400. Telethon uploads and downloads it in 320x234

Edit: It seems I was wrong, Only the original user who sends the gif can download it in the original size. Everyone else can only download it in lower size (I guess its compressed size)

**Comment by Lonami** [comment]
Closing reason:

> telegram seems to compress gifs and only the users who sent it can download the original one.

Source: https://t.me/TelethonChat/327721
