### ISSUE TITLE
Error with KeyboardButtonSwitchInline

### ISSUE THREAD

**Issue by fujiapple852** [LonamiWebs/Telethon#3028]
I'm trying to `Message.click()` a Telegram [`InlineKeyboardButton`](https://core.telegram.org/bots/api#inlinekeyboardbutton) with `switch_inline_query_current_chat` set as an empty string.

Telethon handles this as a `KeyboardButtonSwitchInline` button but it fails deep in `utils.get_peer()` with `TypeError: Cannot cast NoneType to any kind of Peer.`.  

Tracing it through it appears to be a problem in `Message._needed_markup_bot()`  where `bot` is not returned in the case where `button.same_peer` is `True`.

https://github.com/LonamiWebs/Telethon/blob/a376faa3a8545d9072cb255d80b24cf62a293654/telethon/tl/custom/message.py#L1120-L1132

Changing the logic to return the bot resolves the immediate issue:

```python
if button.same_peer or not self.via_bot_id:
    bot = self.input_sender
    if not bot:
        raise ValueError('No input sender')
    return bot
```

Note that after fixing this locally I proceed to a subsequent error:

```
telethon.errors.rpcerrorlist.StartParamEmptyError: The start parameter is empty (caused by StartBotRequest)
```

I wonder if `switch_inline_query_current_chat` is something Telethon supports given this flag should not cause an `start` to occur?

The expected behaviour, as specified in the Telegram documentation is:

> Optional. If set, pressing the button will insert the bot's username and the specified inline query in the current chat's input field. Can be empty, in which case only the bot's username will be inserted.

> This offers a quick way for the user to open your bot in inline mode in the same chat – good for selecting something from multiple options.

**Comment by Lonami** [comment]
Thanks for the detailed report. You seem to have more knowledge here than I currently do. Would you like to send a pull request?

Regarding "what Telethon supports", it's whatever the api.tl file (https://github.com/LonamiWebs/Telethon/blob/master/telethon_generator/data/api.tl) defines (we pull this file from tdesktop, and it's rendered better at https://tl.telethon.dev).

Note that the HTTP bot API has its own documentation and naming convention, so things don't always map 1-to-1 with the actual Telegram API.

**Comment by fujiapple852** [comment]
@Lonami happy to raise a PR for the fix above as it seems pretty clear cut, though I have no ability to regression test it.  I see some tests in the repo, do these cover this code and do they run for PRs?

I do not know enough (well, anything really!) about the underlying `MTProto` protocol nor the design of `telethon` and so I'm unclear on what changes would be needed to support this feature.  

Naively, what the library needs to do for buttons with `switch_inline_query_current_chat` enabled is to respond in the current chat with with `@SomeBot text` which then behaves exactly as if the user had typed that - no need for any `/start` type behaviour.

If you can give some guidance on how this could be done in `telethon` I may be able to attempt an implementation.

**Comment by fujiapple852** [comment]
PR: https://github.com/LonamiWebs/Telethon/pull/3030

**Comment by Lonami** [comment]
> some tests in the repo, do these cover this code and do they run for PRs?

They definitely do not cover this code, but they do run for PRs.

> I do not know enough (well, anything really!) about the underlying `MTProto` protocol nor the design of `telethon` and so I'm unclear on what changes would be needed to support this feature.

You don't really need to, we're working high level here (but I guess you found out since you sent the PR so promptly).

**Comment by Lonami** [comment]
> ```
> telethon.errors.rpcerrorlist.StartParamEmptyError: The start parameter is empty (caused by StartBotRequest)
> ```

[`KeyboardButtonSwitchInline`](https://tl.telethon.dev/constructors/keyboard_button_switch_inline.html) has both `text` and `query` string attributes, but Telethon currently only uses `query`:

https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/tl/custom/messagebutton.py#L110-L113

According to https://core.telegram.org/constructor/keyboardButtonSwitchInline that's what it should do though:

> query | string | The inline query to use

But maybe Telethon was handling this wrong to begin with:

> Button to force a user to switch to inline mode Pressing the button will prompt the user to select one of their chats, open that chat and insert the bot‘s username and the specified inline query in the input field.

Given Telethon doesn't really have any "input message text field", this button doesn't really make much sense. I'm not sure why it's trying to `/start` the bot (I probably misunderstood the button's behaviour back when I implemented it).

I have never had a need for this, so I can't really think of how I'd like to see it solved. But you do have a need for this button, so maybe you know "how you'd like it to work" and then we can implement that solution.

<details><summary>This would be my naive solution (spoilers if you wanna think one for yourself first)</summary>

Return a string with `'@bot [query]'` which the user can append to in `client.inline_query`.

</details>

**Comment by Lonami** [comment]
Closing since #3030 was merged a while back.
