### ISSUE TITLE
The server has closed the connection.

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#303]
when I enter the code for login, this exception will throw :   
``` The server has closed the connection.```
but a few minutes later, when I try again, it is Okay!

Telethon==0.15.1.1

**Comment by Lonami** [comment]
Not sure if this will fix it. Not even sure why Telegram disconnects us.

**Comment by alihossein** [comment]
@Lonami 
Unfortunately.
Today every time I tried, I could not enter a new phone number and this exception will throw again :
`The server has closed the connection`
Thank you for checking

**Comment by Lonami** [comment]
Did you try `master`? I can't remember if I pushed changes to `PyPi`…

**Comment by alihossein** [comment]
I test  `master` branch and version `0.15.1.2`  of Telethon

**Comment by Lonami** [comment]
I need more information, not only the error. Where does it fail exactly? Can you show example code?

**Comment by Lonami** [comment]
I'm going to close this as there are other open issues regarding `ConnectionResetError` with far more information such as #373.

**Comment by yangtao097** [comment]
I met the same question, immdiately I'm running the command: **client.connect() or client.start()**, no matter what I use localhost or proxy(socks), I have gotten the api_id and api_hash based on my own phone_number, my purpose is to use this package to complete my own_desinged third party client-end,
I record down the logging as follow:

`INFO:telethon.telegram_bare_client:Connecting to xxx.xxx.xxx.xx:xxx...
INFO:telethon.telegram_bare_client:Connection success!
DEBUG:telethon.telegram_bare_client:Invoking GetStateRequest
INFO:telethon.telegram_bare_client:Need to generate new auth key before invoking
INFO:telethon.extensions.tcp_client:ConnectionError "[WinError 10054] The server has closed the connection。" while writing data
WARNING:telethon.telegram_bare_client:Connection was reset while invoking
INFO:telethon.telegram_bare_client:Invoking ['GetStateRequest()'] failed 1 times, connecting again and retrying
INFO:telethon.telegram_bare_client:Attempting reconnection...
INFO:telethon.telegram_bare_client:Connecting to xxx.xxx.xxx.xx:xxx...
INFO:telethon.telegram_bare_client:Connection success!
DEBUG:telethon.telegram_bare_client:Invoking GetStateRequest
INFO:telethon.telegram_bare_client:Need to generate new auth key before invoking
INFO:telethon.extensions.tcp_client:ConnectionError "[WinError 10054] The server has closed the connection。" while writing data
WARNING:telethon.telegram_bare_client:Connection was reset while invoking
INFO:telethon.telegram_bare_client:Invoking ['GetStateRequest()'] failed 1 times, connecting again and retrying
INFO:telethon.telegram_bare_client:Need to generate new auth key before invoking
WARNING:telethon.telegram_bare_client:Connection was reset while invoking
WARNING:telethon.telegram_bare_client:Invoking ['GetStateRequest()'] failed 2 times, connecting again and retrying
INFO:telethon.telegram_bare_client:Need to generate new auth key before invoking
WARNING:telethon.telegram_bare_client:Connection was reset while invoking
WARNING:telethon.telegram_bare_client:Invoking ['GetStateRequest()'] failed 3 times, connecting again and retrying
INFO:telethon.telegram_bare_client:Need to generate new auth key before invoking
WARNING:telethon.telegram_bare_client:Connection was reset while invoking
WARNING:telethon.telegram_bare_client:Invoking ['GetStateRequest()'] failed 4 times, connecting again and retrying
INFO:telethon.telegram_bare_client:Need to generate new auth key before invoking
WARNING:telethon.telegram_bare_client:Connection was reset while invoking
WARNING:telethon.telegram_bare_client:Invoking ['GetStateRequest()'] failed 5 times, connecting again and retrying`

my code are:
**_First_**
```
from telethon import TelegramClient
import logging

logging.basicConfig(level=logging.DEBUG)

api_id = 262xxx
api_hash = '3de1cbaae777b8a0e169228329797aeb'
client = TelegramClient('colin', api_id, api_hash)
client.connect()
```

**_Second_**
```
from telethon import TelegramClient
import socks
from telethon.tl.types import UpdateNewChannelMessage

api_id = 262xxx
api_hash = '3de1cbaae777b8a0e169228329797aeb'

print('start')
client = TelegramClient('session_name', api_id, api_hash, proxy=(socks.SOCKS5, 'xx.xx.xx.xxx', 4xxx1), update_workers=4)
print('on.....')
client.start()
print('end')
```

**Comment by Lonami** [comment]
So there's a `ConnectionError` and it tries reconnecting the first time only instead all of them. I wonder why you're getting `[WinError 10054] The server has closed the connection` all the time. Maybe it's related to proxies. Not sure if it's something the library can work around.

**Comment by Lonami** [comment]
Moving discussion to #373.
