### ISSUE TITLE
Expose lang_pack option for client

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#3031]
Telegram client should be exposing `lang_pack` kwarg in the constructor of `TelegramClient`.
Right now `self._init_request` constructed with an empty langpack, so change is possible only after client constructed, but before connected:

``` python
client._init_request.lang_pack = "blabla"
```

No need to hide it under the "official apps only" excuse - those who want to disguise as official apps can do it succesfully anyways (myself incuded)

P.S. This also concern the argument `params` of the `InitConnectionRequest`.

**Comment by Lonami** [comment]
Does it work if you use an unofficial API ID / hash? If it doesn't, then this won't be made public. Like you said, those who care can still change it, but the library itself won't endorse this use.

**Comment by Lonami** [comment]
Closing under the assumption this only works for official API IDs (but feel free to prove me wrong so we can re-open and re-evaluate).

**Comment by anmv** [comment]
@Lonami Why doesn't Telethon use `lang_pack` with official API ID/hash?
For example, another library claims that it is indistinguishable from a regular client:
https://github.com/thedemons/opentele?tab=readme-ov-file#authorization
It uses the API ID/hash from TDesktop and sets `lang_pack`.
Or does Telethon assume that users will create their own custom API ID/hash, in which case this parameter would only be harmful?

**Comment by Lonami** [comment]
Using API ID / hash pairs other than the developer's own when making their applications is against the ToS. Telethon is merely a tool and cannot prevent people from misusing it. Telethon requires an API ID / hash pair precisely becuse each developer must supply their own.

If Telegram has features that cannot be used with unofficial applications, Telethon will simply accept that fact and not try to work around it.
