### ISSUE TITLE
Send file using file_id (bot) reuse of uploaded file

### ISSUE THREAD

**Issue by animeshxd** [LonamiWebs/Telethon#3032]
Is it possible to send file by file_id using telethon?
Most of the time I have to use http POST method to send fiile by file_id. (reuse of uploaded file)
I can't find any documentation about it,
Is it available?
If not please add the feature.

**Comment by Lonami** [comment]
Closing, as discussed in #1613, file IDs are unlikely to be fixed. The correct long-term solution to reusing uploaded files is unfortunately to have a channel where you store all media and, when you need some media, fetch the message and resend the media from it.
