### ISSUE TITLE
Handling the same message

### ISSUE THREAD

**Issue by kitscribe** [LonamiWebs/Telethon#3033]
I'm writing a sniffer for telegram, but with testing the code I found, that registered event handler proceed the same message if I do not send anything else except the "test" message

Some of my code below:
```
    async def __quote__(self, rule, event):
        self.logger.info(f'Quoting event: {event} with text: {rule.text}')
        await event.reply(rule.text)

    async def __forward__(self, rule, event):
        self.logger.info(f'Forwarding event: {event} to {rule.forward_to}')
        await self.client.forward_messages(rule.forward_to, event.message)

    async def __handler__(self, event):
        for rule in self.rules:
            if any([True for word in rule.pluswords if word in event.raw_text.lower()]) and\
                    not any([True for word in rule.minuswords if word in event.raw_text.lower()]):
                if rule.action_id == 1:
                    self.logger.debug("message quotation!")
                    await self.__quote__(rule, event)
                elif rule.action_id == 2:
                    self.logger.debug("message forwarding!")
                    await self.__forward__(rule, event)
        await event.mark_read()
```

**Comment by Lonami** [comment]
Is this a bug in Telethon, or with your code?

**Comment by kitscribe** [comment]
> Is this a bug in Telethon, or with your code?

I think it is in the library, 'cause I just calling `add_event_handler` and nothing else

**Comment by kitscribe** [comment]
Also the quotation is, but there is my fault with the logic, I suppose

**Comment by kitscribe** [comment]
That's strange, but after I rerun the script, the behavior became okay. So I don't know which side the error was
Thanks for your time

**Comment by kitscribe** [comment]
That's strange, but after I rerun the script, the behavior became okay. So I don't know which side the error was
Thanks for your time
