### ISSUE TITLE
Strip random padding in Telethon AES

### ISSUE THREAD

**Issue by NotStatilko** [LonamiWebs/Telethon#3035]
Hello. There is reason why Telethon doesn't use padding for encryption? As for now AES use some random bytes to pad block and this can cause problems for applications around Telethon. For example, when uploading a file with encryption and then downloading it, its hash will not be equal to the original file _before_ encryption. Or it can mess up the "sensitive" file. Maybe a little wrapper around the AES should be done? PyAES module already has **PKCS#7** padding in `pyaes.util`.

I.e:
```python3
from telethon.crypto import AES

key, iv, text = b'k'*32, b'iv'*16, b'Hello!'

encrypted = AES.encrypt_ige(text, key, iv)
print(AES.decrypt_ige(encrypted, key, iv)) # b'Hello!\x10L\xcbu\xdb\x98Wv\xfa\x91'
```

**Comment by Lonami** [comment]
Is this only an issue when uploading encrypted files only? I think that's the entire point of the random padding, to make it harder to decrypt or identify. The decrypted contents are the same though, regardless of padding.

**Comment by NotStatilko** [comment]
> Is this only an issue when uploading encrypted files only?

I faced this while working with uploading/downloading encrypted files, so i think yes. 

> I think that's the entire point of the random padding, to make it harder to decrypt or identify.

But how we should deal with such padding? What if we make hash to verify that file was not changed? You can close this issue if that's only my problem and there is nothing to do with Telethon.

**Comment by Lonami** [comment]
Have you tried uploading the same (encrypted) file twice with an official client and then compared its hash? Is it the same? If yes, we can look more into it. If not, then I'll close this as a non-issue.

**Comment by NotStatilko** [comment]
I created `tesfile4.txt`. Uploaded it to secret chat and downloaded, saved it as `sectestfile4.txt`. Seems that `sha256` is identical. Please try by yourself if you don't mind.

![image](https://user-images.githubusercontent.com/43419673/116303814-b6ea0100-a7aa-11eb-9d18-5f4363f293c9.png)

**Comment by NotStatilko** [comment]
The default MTProto payload has _message length_, so i think Telegram only downloads file by this length. Maybe there is sense to add a new `download_file` kwarg with which we can specify _how much_ bytes we want to download? I'm not familiar with Java to read sources of Telegram Android, sorry for this.

Seems that Telegram doesn't use PKCS#7, instead random **12-1024 bytes**. So we can forget about that :)

![image](https://core.telegram.org/file/811140633/4/hHw6Zy2DPyQ.109500/cabc10049a7190694f)

**Comment by Lonami** [comment]
cc @painor do you think you could shed some light in this?

**Comment by painor** [comment]
is this related to https://github.com/painor/telethon-secret-chat ? because last time I checked when downloading and uploading the files were identical. 

Would be great to see the full code that led to this issue.

**Comment by NotStatilko** [comment]
> is this related to https://github.com/painor/telethon-secret-chat ? because last time I checked when downloading and uploading the files were identical.
> 
> Would be great to see the full code that led to this issue.

No, this is Telethon's case. The problem here is that Telethon, on uploading files with encryption, adds padding in the form of random bytes if the plaintext is not divisible by 16, however, when downloading and decrypting it, Telethon doesn't remove it, and that's can damage the file. Do you by any chance know how the official Telegram client removes the padding?

Padding problem:
```python3
from telethon import TelegramClient
from asyncio import run as asyncio_run
from io import BytesIO
from hashlib import md5

API_ID: int=0
API_HASH: str='api_hash'

async def main():
    client = TelegramClient('session', API_ID, API_HASH)
    await client.start()
    
    key, iv = b'k'*32, b'iv'*16
    data_io = BytesIO(b'0'*1001)
    
    print('@ Hash before upload:', md5(b'0'*1001).hexdigest()) # 7ab2a6c2eab04376bf31052cb5db912d
    
    ufile = await client.upload_file(data_io, part_size_kb=512, key=key, iv=iv)
    msg = await client.send_file('me', ufile, part_size_kb=512, force_document=True)
    down = await client.download_file(msg, bytes, part_size_kb=512, key=key, iv=iv)
    
    print('@ Hash after upload:', md5(down).hexdigest()) # fe743c149d889117bbaa458546eeaa24 (another)
    
asyncio_run(main())
```

**Comment by painor** [comment]
you're only supposed to use the key and iv when dealing with secret chats. the current way you're doing it you're just encrypting a file and then decrypting it yourself outside of any telegram protocols. the person that receives the file has no way of knowing what the key and iv you used are. 

When using secret chats you need to send the size as well with the file in DecryptedMessageMediaDocument that way telegram app can know the exact size and when to stop decrypting.

**Comment by painor** [comment]
I just used the following and received the exact same file        
data_io = BytesIO(b'0' * 1001)
await manager.send_secret_document(chat.id, data_io,b"", 0, 0,"test","", len(data_io.getvalue()))

so if you want to encrypt decrypt your files using key,iv is probably not the way to do it. encrypt them using your own algorithm before and decrypt them on your own.

**Comment by NotStatilko** [comment]
> the person that receives the file has no way of knowing what the key and iv you used are.

Yes, i know it. Currently i am working on making encrypted containers from channels, so i use default Telethon's encryption for file uploading. The problem here, again, is that Telethon doesn't remove padding on downloading. It will be pretty good if we can add additional kwarg to `download_file`.

> Maybe there is sense to add a new `download_file` kwarg with which we can specify _how much_ bytes we want to download?

And to make it easier to work with Secret Chats too.

https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/client/downloads.py#L473-L477

But only @Lonami will decide for sure

**Comment by NotStatilko** [comment]
If we have to build everything around the `upload_file` and the developer should take care of the padding, then this issue can be closed.

**Comment by Lonami** [comment]
Telethon's encryption during upload was only added to support painor's secret chat extension. Upload encryption should not be used for anything else. Closing.

As suggested, if you want any other encryption, you should do that yourself (you can provide a wrapper which acts as a file-like object and transparently applies the encryption, to support stream uploads).
