### ISSUE TITLE
Bug downloading contact with download_media

### ISSUE THREAD

**Issue by dualevitating** [LonamiWebs/Telethon#3037]
Similar to #1147 when download_media method has to deal with contact inside media..

**Code that causes the issue**
```python
async for message in client.iter_messages(chat.entity):
    if message.media:
        await message.download_media(path)
...
```
It triggers the next error:
**Traceback**
```
Error: _download_contact() takes 3 positional arguments but 4 were given
```
I think its a bad transfer of arguments from download_media to the specialized method for contacts, _download_contact

Thanks in advance!

**Comment by dualevitating** [comment]
I'm using the latest one. I've done the checklist before post.

**Comment by Lonami** [comment]
Please `print(telethon.__version__)` and double check that you are indeed importing a recennt version. You removed the checklist from the issue.

**Comment by dualevitating** [comment]
```python
>>> import telethon
>>> print(telethon.__version__)
1.21.1
```
Sorry about that.. I removed it because I did not see this in other posts, so I assumed that it was not necessary.

**Comment by Lonami** [comment]
You may try doing the following:

```python
import inspect
from telethon import TelegramClient
print(inspect.getsource(TelegramClient.download_media))
```

Because I'm pretty sure you somehow have an old version. You have to do this *in the code that fails*. In my output, `download_media` **does not have 4 parameters** and like I've shown `master` doesn't either:

```python
        elif isinstance(media, types.MessageMediaContact) and thumb is None:
            return self._download_contact(
                media, file
            )
```

**Comment by Lonami** [comment]
> I removed it because I did not see this in other posts, so I assumed that it was not necessary.

There was no template a while ago (and some people either remove it or use blank issues for some reason…). But anyway the goal with the template is to have people fill it in (unless they know what they're doing).

**Comment by dualevitating** [comment]
> You may try doing the following:
> 
> ```python
> import inspect
> from telethon import TelegramClient
> print(inspect.getsource(TelegramClient.download_media))
> ```
> 
> Because I'm pretty sure you somehow have an old version. You have to do this _in the code that fails_. In my output, `download_media` **does not have 4 parameters** and like I've shown `master` doesn't either:
> 
> ```python
>         elif isinstance(media, types.MessageMediaContact) and thumb is None:
>             return self._download_contact(
>                 media, file
>             )
> ```
I will insert what you recommend me. But if it is an updating problem, how can I upgrade properly? I use `pip3 install telethon -U` and in mine it is the same:
```
grep -A 2 "self._download_contact(" <..>.local/lib/python3.8/site-packages/telethon/client/downloads.py
            return self._download_contact(
                media, file
            )
```

**Comment by Lonami** [comment]
Then how is it possible that it fails?

**Comment by dualevitating** [comment]
I'm sorry, could be the progress_callback?

**Comment by Lonami** [comment]
You didn't provide a traceback. I don't know.

**Comment by dualevitating** [comment]
Yeap, It seems to be this, sorry. I was stupid while I was copying the example because I forgot put that I was specifying a progress_callback. When I remove the progress_callback argument of the download_media call it works as expected.
