### ISSUE TITLE
_ParticipantsIter doesn't get users with non latin names when set to aggressive mode

### ISSUE THREAD

**Issue by Jacotsu** [LonamiWebs/Telethon#3038]
_ParticipantsIter, and all functions based on it will not get users that don't have ascii characters in their name or last name, such as japanese, arabs etc.
This could be solved by generating a list of unicode chars instead of using string.ascii_lowercase, though it may cause a flood ratelimit.

**Comment by Lonami** [comment]
`aggressive=True` is a hack that I plan to remove as soon as v2 happens.
