### ISSUE TITLE
PhoneCodeExpiredError: The confirmation code has expired (caused by SignInRequest)

### ISSUE THREAD

**Issue by CaramelHeaven** [LonamiWebs/Telethon#3039]
**Code that causes the issue**
```python
from telethon import TelegramClient, events
...
@bot.on(events.NewMessage(pattern="codeNumbersPattern"))
async def get_phone_code(event):
    test2 = await client.sign_in(PHONE_NUMBERS, code_numbers)


@bot.on(events.NewMessage(pattern="phoneNumbersPattern"))
async def get_phone_numbers(event):
    test = await client.sign_in(PHONE_NUMBERS)

```

**Traceback**
```
Traceback (most recent call last):
telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.PhoneCodeExpiredError: The confirmation code has expired (caused by SignInRequest)

```

I have a simple code with single client instance. (I have checked that I have identical phone_code_hash) I'm a little curious about what you mean in the documentation `def sign_in()` -> `Note that if you have sent this code through the application itself it will immediately  expire. If you want to send the code, obfuscate it somehow.`

I probably can not find how to obfuscate my code numbers through the application. Can you documented it ? Or maybe I missed the place where it located.

thanks.

**Comment by Lonami** [comment]
The error comes from Telegram so there's nothing the library can do about it to fix it. The documentation intentionally doesn't showcase how to "obfuscate" the code because I do not want to encourage doing it (although it isn't really that hard).

**Comment by zxllkada** [comment]
it's easy to hide the code. Ex : code is 55555 > send it to chat like this : 55-555. then replace ( - ).

Telegram : Login code: 55555. ( ... )
You to chat :  55-555

GetMessage then replace ( - )
```
message_list_code = await event.client(GetMessagesRequest(id=[last_id]))
    for message in message_list_code.messages:
    clear_code = (message.message).replace('-', '')
    clear_code = 55555
```

Now pass clear_code then sign in without problem.
