### ISSUE TITLE
 MessageMediaPoll object could not be forwarded

### ISSUE THREAD

**Issue by aahnik** [LonamiWebs/Telethon#3043]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.

related to https://github.com/aahnik/tgcf/issues/50

**Code that caused the issue**

`client.send_message() ` caused it. The message had a poll object.

**Traceback**

```shell
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tgcf/utils.py", line 8, in send_message
    return await client.send_message(*args)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/messages.py", line 782, in send_message
    return await self.send_file(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/uploads.py", line 386, in send_file
    raise TypeError('Cannot use {!r} as file'.format(file))
TypeError: Cannot use <telethon.tl.types.MessageMediaPoll object at 0x713713a700> as file
```
-----

This error was found while running my program on **Termux**. (android)

I did not find this error on my computer (Ubuntu 20.04)

python version 3.9 used.

telethon version 1.21.1

**Comment by Lonami** [comment]
You cannot resend copies of polls because all the data isn't known until you actually choose an option. While it could work then, it's strange it would "works sometimes but not others", so closing.

**Comment by aahnik** [comment]
@Lonami, after little more experimentation,
- problem has nothing to do with termux
- forward always succeeds on every platform, for a poll
-  but if the poll is in quiz mode it always fails, on every platform

a poll in quiz mode can be forwarded by hand in the telegram app. so why can't it be forwarded programmatically?

I think it is some bug with Telethon.

https://github.com/LonamiWebs/Telethon/blob/b2c26a53efe25110d32aef7d0f675089d8d1a77b/telethon/client/uploads.py#L385-L386

seems like a poll with quiz mode is not supported in telethon

**Comment by Lonami** [comment]
Yes, you can forward polls just fine (`forward_messages`). What you can't do is resend them as copies reliably (`send_message`).
