### ISSUE TITLE
gaierror: [Errno 11002] getaddrinfo failed

### ISSUE THREAD

**Issue by Antoxa4211** [LonamiWebs/Telethon#3046]
Hello! When using telethon, I get the following error:
`gaierror: [Errno 11002] getaddrinfo failed`
Here is the code:
`with TelegramClient('me', API_ID, API_HASH, proxy=(socks.HTTP, proxy, port)) as client:
    client.loop.run_until_complete(client.send_message('me', 'Hello, myself!'))`
I just don't even know what it is connected with
sorry for my english i am writing from a translator

**Comment by Lonami** [comment]
I'm cleaning up proxy-related issues, so closing in favour of the new issue.
