### ISSUE TITLE
send_message and edit_message does not have the attributes, supports_streaming paramters,

### ISSUE THREAD

**Issue by SpEcHiDe** [LonamiWebs/Telethon#3047]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
client = TelegramClient("session", 1, "abc")
client.start()
reply = client.get_messages("@username", ids=1) # get a message with a photo / document / video
f = "/path/to/any/file.mp3" # add path to an audio file
from hachoir.metadata import extractMetadata
from hachoir.parser import createParser
metadata = extractMetadata(createParser(f))
duration = 0
title = ""
artist = ""
if metadata:
  if metadata.has("duration"):
    duration = metadata.get("duration").seconds
  if metadata.has("title"):
    title = metadata.get("title")
  if metadata.has("artist"):
    artist = metadata.get("artist")
a = [
  types.DocumentAttributeAudio(
    duration=duration,
    performer=artist,
    title=title,
    voice=False,
    waveform=None
  )
]
reply.edit(file=f, supports_streaming=True, force_document=False, attributes=a) 
```

throws TypeError: edit_message() got an unexpected keyword argument 'supports_streaming'

adding this two lines
```
file_handle, media, image = reply.client._file_to_media(f, force_document=False, attributes=a)
reply.edit(file=media) 
```
edits the media, with the correct attributes.

**Comment by ssiyad** [comment]
I don't see `supports_streaming` or `attributes` in https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.messages.MessageMethods.edit_message or https://github.com/LonamiWebs/Telethon/blob/master/telethon/client/messages.py#L963. Are you sure this is a bug?

**Comment by Lonami** [comment]
This issue's goal is to have said attributes added to the methods so that they can be used.

**Comment by ssiyad** [comment]
Ugh the third option in checklist made me think its a bug

**Comment by BelgenOp** [comment]
Hey @SpEcHiDe , why don't you pull request, if you know what can be done? or lonami can you commit, and release it in next telethon updates

**Comment by Lonami** [comment]
I'm not interested in this feature myself, because I'd rather rework how that works entirely. But if you feel a need for it for the time being, feel free to send a PR.
