### ISSUE TITLE
I'm able to download files sent to myself. But no metadata.

### ISSUE THREAD

**Issue by Atari215** [LonamiWebs/Telethon#3048]
Im using a very basic string but i'm really not even sure how i would make it easier to add metadata and filename. Any help?

from telethon.sync import TelegramClient, events
from tqdm import  tqdm
import os

# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.
api_id = 212312
api_hash = '2108372193782197381298731'

with TelegramClient('name', api_id, api_hash) as client:
    messages = client.get_messages('mylink', limit=1) # limit defaults to 1
    for msg in tqdm(messages):
        msg.download_media(file=os.path.join('media', '<file_name>'))

**Comment by NotStatilko** [comment]
Do you installed `hachoir`? Maybe because of this?

https://docs.telethon.dev/en/latest/basic/installation.html#optional-dependencies

**Comment by Atari215** [comment]
now i have metadata on the track. but id like to not have to change the filenames for everything. is there a command to pull that information as well?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
