### ISSUE TITLE
ReadHistoryRequest does not increase views count on the channel

### ISSUE THREAD

**Issue by artem-gunkin** [LonamiWebs/Telethon#305]
I try to sign in account and get histrory message:
```
client = TelegramClient(session, api_id, api_hash)
client.connect()
channel = client.get_entity('@some_channel')
count, messages, senders = client.get_message_history(channel, limit=10)
```
Then check message views:
```
for message in messages:
    print(message.views)
```

But they do not change. Is there some other methods for mark channel messages as viewed?

**Comment by Lonami** [comment]
You know [`GetHistoryRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_history.html) and [`ReadHistoryRequest`](https://lonamiwebs.github.io/Telethon/?q=readhistoryrequest) are different things, don't you?

**Comment by artem-gunkin** [comment]
Sorry, I try both methods and create incorrect issue comment. ReadHistoryRequest doesn't work too.

**Comment by Lonami** [comment]
That's because you want to `.increment` the [`GetMessagesViewsRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_messages_views.html)…

**Comment by ablkvo** [comment]
I used this code to do above job to count up views. but it didn't work.

from telethon import TelegramClient
import telethon
api_id = xxx
api_hash = 'xxxx'
phone = '+1580823xxxx'
client = TelegramClient('session_name', api_id, api_hash)
client.connect()
entity = client.get_entity('testitby')
peer=telethon.tl.functions.get_input_peer(entity)
total, messages, senders = client.get_message_history('testitby')
telethon.tl.functions.messages.GetMessagesViewsRequest(peer=peer, id=[messages[0].id], increment=True)

It didn't come up with errors but didn't work as well and The post in the channel 'testitby' didn't count up in views.
any help would be appreciated.

**Comment by Lonami** [comment]
Telegram likely has its own mechanism to allow you to increment the view count only *once*, so if you've seen the post on any other client, calling that likely won't increment the count. Possibly only working once. Send a message through another account, and then from the account you're using on Telethon, call the method. Compare the view count.

**Comment by ablkvo** [comment]
Hi Dear Lonami,
I tried what you said but it didn't work.
have you ever try to do something similar?

**Comment by Lonami** [comment]
No I've never tried but that's the only request that has an `increment`-like action.

**Comment by NabiKAZ** [comment]
### Attention:
Seems that if the `messages.getMessagesViews` are used successive in a large number for a few hours, the viewer will not increase further for current client for any posts, and also don't return any error message, and just return current view of post.
A silent flood !!!
But, after a few hours, everything will return to its original state.
