### ISSUE TITLE
ERROR:root:Unhandled exception: 'ChannelForbidden' object has no attribute 'min' (<class 'AttributeError'>)

### ISSUE THREAD

**Issue by hauptmedia** [LonamiWebs/Telethon#3051]
**Checklist**
* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
...

# when sender is an instance of ChannelForbidden
sender = await message.get_sender()


```

**Traceback**
```
  File "/app/handler/messagehandler.py", line 177, in handle_chat_history


    await self.on_message(message, True)


  File "/app/handler/messagehandler.py", line 71, in on_message


    sender = await message.get_sender()


  File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/sendergetter.py", line 47, in get_sender


    if (self._sender is None or self._sender.min) \


AttributeError: 'ChannelForbidden' object has no attribute 'min'

```

I think here must be a guard like this one:

https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/tl/custom/sendergetter.py#L47

https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/tl/custom/chatgetter.py#L46

**Comment by Lonami** [comment]
Yeah that indeed would fix it. Would you like to send a pull request?
