### ISSUE TITLE
Get text after pressing button from @hideItBot

### ISSUE THREAD

**Issue by reikano** [LonamiWebs/Telethon#3054]
LABEL : HELP WANTED

Hello, I have an issue. I want to get text after pressing a button which was created by @hideItBot -> https://github.com/erpheus/hideit-bot

My code:
async def my_event_handler(event):
    message_info = event.message.click(data=event.message.reply_markup.rows[0].buttons[0].data)

![image](https://user-images.githubusercontent.com/74960485/117956513-a2f4e200-b308-11eb-972f-f07ff1f278fa.png)

I can't find text info in message_info object., where I could find it?

Thank you!

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
