### ISSUE TITLE
Is there a way to listen to public groups without joining?

### ISSUE THREAD

**Issue by VladBern3** [LonamiWebs/Telethon#3056]
Good day! 
I would like to ask if there is a way to listen to messages in public groups without joining them and having access to messages ? (screenshot) 
![image](https://user-images.githubusercontent.com/30588782/118172693-f2343300-b42c-11eb-8ed8-638f674e9b4d.png)

Thank you in advance !

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
