### ISSUE TITLE
Can't download profile picture

### ISSUE THREAD

**Issue by yinelos** [LonamiWebs/Telethon#3058]
**Code that causes the issue**
```python
doc = client.download_profile_photo('me')
...

```

**Traceback**
```
...python3.8/site-packages/telethon/client/downloads.py", line 706, in _iter_download and offset % limit == 0:
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'
```
and save the file with 0 (zero) size

**Comment by Lonami** [comment]
Probably introduced by #3042 cc @the-blank-x.

**Comment by Lonami** [comment]
Please check if the above commit solves the issue, I will reopen otherwise.

**Comment by yinelos** [comment]
> Please check if the above commit solves the issue, I will reopen otherwise.

Issue solved! THX!
