### ISSUE TITLE
add 'limit' argument support for GetPeerDialogsRequest

### ISSUE THREAD

**Issue by shinenelson** [LonamiWebs/Telethon#3059]
`GetPeerDialogsRequest` takes a list of `InputDialogPeer`s as input. Logically, if one wanted to operate on multiple Dialogs, they would use [`telethon.client.dialogs.DialogMethods.get_dialogs`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.dialogs.DialogMethods.get_dialogs) to fetch all the dialogs that they were interested in and pass that into `GetPeerDialogsRequest`.

`get_dialogs` has a `limit` parameter that can be used to control the number of dialogs that is returned. The default behaviour is to return all the dialogs in the user's account. However, passing that `telethon.helpers.TotalList` into `GetPeerDialogsRequest` would truncate the results to a hard limit of 100.

While the number 100 makes sense because that is also the limit of [DialogFilters](https://tl.telethon.dev/types/dialog_filter.html), it can cause confusion when passing a `telethon.helpers.TotalList` of length > 100 into the `peers` argument of `GetPeerDialogsRequest` and then receiving only 100 peers as output.

If there are technical limitations to fetching the whole list ( because `InputDialogPeer`s have only a few elements whereas `DialogPeers` may have so many ), then at least document the limitation and provide a warning on the [documentation page](https://tl.telethon.dev/methods/messages/get_peer_dialogs.html). 

But if it is technically possible, please provide the argument with a similar interface to how it works in `get_dialogs`. I think that could be generally assumed by developers.

**Comment by Lonami** [comment]
Sorry, I do not understand what is being asked here. `GetPeerDialogsRequest` cannot take a `limit` because it's a raw API request (but it doesn't need it, because it will fetch whatever you pass in).

**Comment by shinenelson** [comment]
> but it doesn't need it, because it will fetch whatever you pass in.

I observed otherwise.

I am running [this script](https://gist.github.com/shinenelson/5ead5d23de008bcdf7c68433194a1c0b#file-telegram-dialog-sort-by-unread-py)
and found the `peer_dialogs` from [line 61](https://gist.github.com/shinenelson/5ead5d23de008bcdf7c68433194a1c0b#file-telegram-dialog-sort-by-unread-py-L61)
to have only 100 entries even when `input_peers` from [line 50](https://gist.github.com/shinenelson/5ead5d23de008bcdf7c68433194a1c0b#file-telegram-dialog-sort-by-unread-py-L50)
has over 100 entries.

Maybe something changed on the API's side?

**Comment by Lonami** [comment]
Ah, this may be a Telegram API limitation ignoring the input values after the 100th. We cannot fix it. The code needs to make multiple calls with 100 or less items each and then join the results itself.

No idea what the filters do as I haven't used them, but makes me wonder if the code couldn't just use `get_dialogs` to fetch them all and do whatever sorting. `get_dialogs` do include all of the `Dialog` information under the `.dialog` attribute.
