### ISSUE TITLE
Retrieve messages from group

### ISSUE THREAD

**Issue by jmiller0** [LonamiWebs/Telethon#306]
It doesn't look like it is possible to retrieve messages from a group chat, is this possible?

Thanks

**Comment by Lonami** [comment]
Why wouldn't it be…?

**Comment by pranaysahith** [comment]
@Lonami I have gone through all wiki, few issues and code but couldn't figure out a way or sample way to get messages from a group. It would be group if you throw some relative code or docs at me.

**Comment by Lonami** [comment]
Doesn't `.get_message_history` work?

**Comment by pranaysahith** [comment]
The type of entity is telethon.tl.types.Channel and there is no ".get_message_history" method for it.
Also, I am confused why a super group entity type is channel.

**Comment by Lonami** [comment]
> telethon.tl.types.Channel and there is no ".get_message_history" method for it.

I'm talking about [this](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py#L401)…

> I am confused why a super group entity type is channel.

Well, Telegram is the way it is.

**Comment by pranaysahith** [comment]
Put me on wall of shame for not finding this myself!

**Comment by Lonami** [comment]
Nobody has ever requested that @pranaysahith, but if I did I would be shaming @jmiller0 as he made this issue 😅

**Comment by codenoid** [comment]
for my telegram monitoring app
