### ISSUE TITLE
How to continue the code if there is an error?

### ISSUE THREAD

**Issue by kamila-minaj** [LonamiWebs/Telethon#3060]
Hi. I have a simple program that allows user to join multiple chats/channel. User just inputs links of channels to join. But i have some troubles with channels that are private/not exist/deleted and etc. The program immideatly stops if can't join some chanel, but how can i make the program ignore these errors and continue its work until the end?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
