### ISSUE TITLE
How to send video with stream

### ISSUE THREAD

**Issue by r3zoneid1** [LonamiWebs/Telethon#3063]
how do I send a video with a stream? I've tried several ways for example using hachoir module but the results still do not work. Got a solution?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
