### ISSUE TITLE
i want to the know the user who sent the message on the channel 

### ISSUE THREAD

**Issue by programerr01** [LonamiWebs/Telethon#3064]
```

client.on(events.NewMessage)
async def msg(event):
     sender = await event.get_sender()

```
this seems to be returning channel info instead of user info

**Comment by igerzog** [comment]
It is not possible in broadcast channels.

**Comment by programerr01** [comment]
> It is not possible in broadcast channels.

will it for groups ?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).``
