### ISSUE TITLE
Client Upload e Download file

### ISSUE THREAD

**Issue by Maverick1983** [LonamiWebs/Telethon#3067]
I would like to use the client file upload and download methods. After sending the file, how can I download it without sending it to anyone?

Ref.
https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.uploads.UploadMethods.upload_file

https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.downloads.DownloadMethods.download_file

**Comment by Lonami** [comment]
You can't.
