### ISSUE TITLE
[Question+feature request] whats the datatype of event ? please give complete typehints

### ISSUE THREAD

**Issue by aahnik** [LonamiWebs/Telethon#3068]
https://github.com/LonamiWebs/Telethon/blob/63f24d2282f1117a7e5d0dd744c97b983adb7f27/telethon_examples/replier.py#L52-L64

What should be the type annotation for `event` in the above example?

I tried with `events.NewMessage`

```python
@events.register(events.NewMessage)  
async def handler(event:events.NewMessage): 
```

But did not get `raw_text`, `gif` etc objects in type hint, when I type `event.`

Does telethon have 100% type hinting? If not, please give.

**Comment by painor** [comment]
it's a hack class that has all the attributes of custom.Mesage + the event message.

**Comment by aahnik** [comment]
> event message. 

what is that? Do you mean `events.NewMessage`?

is this right ?

```python
from typing import Union
from telethon.tl.custom.message import Message

@events.register(events.NewMessage)  
async def handler(event:Union[Message,events.NewMessage]): 
```

**Comment by painor** [comment]
yes that probably should be correct.

**Comment by aahnik** [comment]
A releated doubt.

what is `telethon.hints.MessageLike` ? there may be some problem there. As I don't get many attributes of `telethon.tl.custom.message.Message`

**Comment by aahnik** [comment]
```python
from telethon.tl.custom.message import Message

@events.register(events.NewMessage)  
async def handler(event:Union[Message,events.NewMessage]): 
     message = event.message # what is the type ? I got Message
     m = message.message # what is the type ? I got str
     # will there not be collision as event is of type Message also ?
```

**Comment by aahnik** [comment]
the types of event are `events.NewMessage.Event` or `events.CallbackQuery.Event`.

new message event also have all the properties of a message.

thanks to @painor  for helping me here, as well as in the chat.

I am closing this issue as there is already one open for typehints https://github.com/LonamiWebs/Telethon/issues/1195
