### ISSUE TITLE
Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by InviteToChannelRequest)

### ISSUE THREAD

**Issue by jianwei923** [LonamiWebs/Telethon#3069]
I need multiple clients to make the InvitetoChannelRequest request. When the first request was made, it was normal. When I switched the second client, an error was reported, but when I switched back to the first one, there was no error.
Invalid channel object. Make sure to pass the right types,for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by InviteToChannelRequest)

`index = 0
chat_id = -1
while True:
    client = None
    client = TelegramClient(self.all_session[index], ClientManager.api_id,
                            ClientManager.api_hash)
    await client.connect()
    if await client.is_user_authorized():
        if self.channel is None:
                self.channel = await client.get_entity(grou_id)
        num = num + 1
        user = await client.get_entity(self.queue_user.get())
        r = await client(InviteToChannelRequest(self.channel, [user]))
        await client.disconnect()
    else:
        pass
    index = index + 1
    if index == len(self.all_session):
        index = 0
`

**Comment by jianwei923** [comment]
index = 0
chat_id = -1
while True:
    client = None
    client = TelegramClient(self.all_session[index], ClientManager.api_id,
                            ClientManager.api_hash)
    await client.connect()
    if await client.is_user_authorized():
        if self.channel is None:
                self.channel = await client.get_entity(grou_id)
        num = num + 1
        user = await client.get_entity(self.queue_user.get())
        r = await client(InviteToChannelRequest(self.channel, [user]))
        await client.disconnect()
    else:
        pass
    index = index + 1
    if index == len(self.all_session):
        index = 0

**Comment by jianwei923** [comment]
`index = 0
chat_id = -1
while True:
    client = None
    client = TelegramClient(self.all_session[index], ClientManager.api_id,
                            ClientManager.api_hash)
    await client.connect()
    if await client.is_user_authorized():
        if self.channel is None:
                self.channel = await client.get_entity(grou_id)
        num = num + 1
        user = await client.get_entity(self.queue_user.get())
        r = await client(InviteToChannelRequest(self.channel, [user]))
        await client.disconnect()
    else:
        pass
    index = index + 1
    if index == len(self.all_session):
        index = 0
`

**Comment by jianwei923** [comment]
`index = 0
chat_id = -1
while True:
    client = None
    client = TelegramClient(self.all_session[index], ClientManager.api_id,
                            ClientManager.api_hash)
    await client.connect()
    if await client.is_user_authorized():
        if self.channel is None:
                self.channel = await client.get_entity(grou_id)
        num = num + 1
        user = await client.get_entity(self.queue_user.get())
        r = await client(InviteToChannelRequest(self.channel, [user]))
        await client.disconnect()
    else:
        pass
    index = index + 1
    if index == len(self.all_session):
        index = 0
`

**Comment by jianwei923** [comment]
index = 0
chat_id = -1
while True:
    client = None
    client = TelegramClient(self.all_session[index], ClientManager.api_id,
                            ClientManager.api_hash)
    await client.connect()
    if await client.is_user_authorized():
        if self.channel is None:
                self.channel = await client.get_entity(grou_id)
        num = num + 1
        user = await client.get_entity(self.queue_user.get())
        r = await client(InviteToChannelRequest(self.channel, [user]))
        await client.disconnect()
    else:
        pass
    index = index + 1
    if index == len(self.all_session):
        index = 0

**Comment by Lonami** [comment]
Mass adding users is spam.
