### ISSUE TITLE
Option to disable the EntityCache

### ISSUE THREAD

**Issue by ingria** [LonamiWebs/Telethon#3073]
In-memory cache that is used in [EntityCache](https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/entitycache.py#L50) can grow quite big in high-loaded apps. For example, in my case it costs approximately 300MB of **extra** "dead" memory per month (it is "dead" because I'm building `InputX` objects in my app before feeding them to Telethon, so I don't need the cache).

This is weekly memory usage (there are only Telethon instances on that server, pay attention to the difference between min and max values):

![memory-week](https://user-images.githubusercontent.com/2178368/121790154-2d20b680-cbe5-11eb-8693-43a8b6ae265c.png)

We are already capable of disabling the sqlite cache, so I suggest adding some config option to disable in-memory cache too.

**Comment by Lonami** [comment]
How many users are interacting with the account?

**Comment by ingria** [comment]
Just one.

I’m using it to get info about channels (`getChannelFull`, about 10k unique channels per month). So the cache is full of `InputPeerChannel` objects.
