### ISSUE TITLE
How to monitor supergroup messages?

### ISSUE THREAD

**Issue by yaochangfei** [LonamiWebs/Telethon#3078]
Example:

from telethon import TelegramClient, events

api_id = 'xxx'
api_hash = 'xxx'
client = TelegramClient('xxx', api_id, api_hash,
                        proxy='xxx',
                        timeout=10)

@client.on(events.NewMessage)
async def my_event_handler(event):

    print('{}'.format(event))

client.start()

client.run_until_disconnected()

result:
in my telegram account ,supergroup messages the above code why can't monitor? how can I monitor supergroup messages?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
