### ISSUE TITLE
get_participants(target_group, aggressive=True) does not extract all the users, only like 90% is extracted.

### ISSUE THREAD

**Issue by xyd945** [LonamiWebs/Telethon#3079]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
client.get_participants(target_group, aggressive=True)
 
...

```

**Traceback**
```


```

the code works fine, but it doesn't return all the users in the group.

**Comment by Lonami** [comment]
`aggressive=True` is a hack that will be removed in future versions.
