### ISSUE TITLE
QR code аuthorization

### ISSUE THREAD

**Issue by Ivanzzzc** [LonamiWebs/Telethon#3081]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
import asyncio

api_id = ""
api_hash = ""


def display_url_as_qr(url):
    print(url)
    pass  # do whatever to show url as a qr to the user


async def qr_login():
    client = TelegramClient('test', api_id, api_hash)
    await client.connect()

    qr_login = await client.qr_login()
    display_url_as_qr(qr_login.url)

    # Important! You need to wait for the login to complete!
    await qr_login.wait()
    print(await client.get_me())


loop = asyncio.get_event_loop()
loop.run_until_complete(qr_login())

```
**Problem**
When you scan the generated qr code, the application on the phone crashes: (click to open gif)
![windows](https://user-images.githubusercontent.com/46572469/122671990-f264e280-d1d1-11eb-9641-bf8bfd3782d0.gif)

https://user-images.githubusercontent.com/46572469/122673308-7ae68180-d1d8-11eb-826b-66af523a693e.mp4

**But not always:** (click to open gif)
![windows_2](https://user-images.githubusercontent.com/46572469/122673256-3f4bb780-d1d8-11eb-91ba-35fd67e50f13.gif)

https://user-images.githubusercontent.com/46572469/122674313-37424680-d1dd-11eb-861d-8749f7792c5d.mp4

**What's the problem?**
The problem is that "[qrlogin.py](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/custom/qrlogin.py#L57)" uses base64 -> base64.b64encode(), as I understand it should be base64url -> urlsafe_b64encode().
I found [url64](https://pypi.org/project/url64/) library, it has this code:
```python
from base64 import urlsafe_b64encode, urlsafe_b64decode

__all__ = ['encode', 'decode']


def pad(s):
    return s + '=' * (4 - len(s) & 3)


def encode(s):
    if isinstance(s, str):
        s = s.encode()
    return urlsafe_b64encode(s).decode().rstrip("=")


def decode(s):
    return urlsafe_b64decode(pad(s)).decode()
```
and it does just fine:
```python
import url64
return 'tg://login?token={}'.format(url64.encode(self._resp.token))
```
(I'm not suggesting that add this code to the library, it's just an example of how I fixed it)

**What has changed?**
Old: 
``` 
tg://login?token=AQK/M89gA0PawCUIZe1cs5Y657FATBKcKfJ/C5NaQETbFQ==
tg://login?token=AQLcM89genyIgiSpZB6wmXJ2X3EKOma4x9MuAME/8ygXKA==
tg://login?token=AQL4M89gHX+0YcgqisVOiGSYEKlyz++1DbtOk9OfvDTxbg==
```
New: 
```
tg://login?token=AQK_M89gA0PawCUIZe1cs5Y657FATBKcKfJ_C5NaQETbFQ
tg://login?token=AQLcM89genyIgiSpZB6wmXJ2X3EKOma4x9MuAME_8ygXKA
tg://login?token=AQL4M89gHX-0YcgqisVOiGSYEKlyz--1DbtOk9OfvDTxbg
```

**Comment by Lonami** [comment]
Thank you for the detailed report. Would you like to send a pull request? As I understand it, the changes needed are using [`base64.urlsafe_b64encode`](https://docs.python.org/3/library/base64.html#base64.urlsafe_b64encode) and adding `.rstrip('=')`.
