### ISSUE TITLE
request call

### ISSUE THREAD

**Issue by simplPart** [LonamiWebs/Telethon#3083]
Since I am writing a client, my friends from the USA noticed that the code does not go through SMS, but only through a call. but I don’t understand how to do it, how to request a call( @Lonami is there some example code where the method of receiving a code through a call is shown?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by simplPart** [comment]
https://stackoverflow.com/questions/68058835/telethon-how-to-request-call-with-code-for-login
