### ISSUE TITLE
Clicking a KeyboardButtonSwitchInline always raises StartParamInvalid

### ISSUE THREAD

**Issue by New-dev0** [LonamiWebs/Telethon#3085]
**Checklist**
* [✅  ] The error is in the library's code, and not in my own.
* [⚔️ ] I have searched for this issue before posting it and there isn't a duplicate.
* [⚔️  ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
button_number = 0
replied = await event.get_reply_message()
await replied.click(button_number)
...

```

**Traceback**
```
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.StartParamInvalidError: Start parameter invalid (caused by StartBotRequest)
```

I Examined The Source - 
https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/tl/custom/messagebutton.py#L111

And Noticed Wrong Method (StartBotRequest) is used to click that Button, instead inline_query method should be used, which will be technically correct too.

**Comment by Lonami** [comment]
What button are you trying to press? Does it happen in the `master` version?

**Comment by New-dev0** [comment]
> What button are you trying to press? Does it happen in the `master` version?

Button that switches to Keyboard with Query and yes, it happens with `master` too.
`StartBotRequest` works, if wants to send command to Bot and it returns Message replied by the bot.

**Comment by Lonami** [comment]
What should be the solution in your opinion?

**Comment by New-dev0** [comment]
Maybe, it should Consider The via_bot,
I just Tried Printing MessageButton._bot its InputPeerSelf / User Who sended/Clicked the InlineResult with that Button.

**Comment by Lonami** [comment]
Sorry if that wasn't clear. My question is, when such a button is pressed, what should the library *do*? Return nothing, continue returning the error, do nothing…

**Comment by New-dev0** [comment]
> Sorry if that wasn't clear. My question is, when such a button is pressed, what should the library _do_? Return nothing, continue returning the error, do nothing…

I believe, it will be convenient, If `library` starts the `inline_query' request with that bot, with query set, and if `same_peer` is used, `entity` parameter should be should as chat where button is send. 

Most Bots, uses that button to redirect the users to Inline Results 🤔

**Comment by Lonami** [comment]
But what query? When you click a button no query is provided. I think it would be strange if it returned the results of an empty query too.

**Comment by buddhhu** [comment]
> But what query? When you click a button no query is provided. I think it would be strange if it returned the results of an empty query too.

Some inline buttons have query and if no query then start inline without query

**Comment by New-dev0** [comment]
> > But what query? When you click a button no query is provided. I think it would be strange if it returned the results of an empty query too.
> 
> Some inline buttons have query and if no query then start inline without query

Ya correct

**Comment by New-dev0** [comment]
lonami, what's your opinion ? 
And I doubt, how it will be strange?

**Comment by Lonami** [comment]
My opinion is the click should do nothing because there's no single choice. Inline queries are meant to be interactive, but `click()` doesn't allow for much interactivity, but inline queries require it (editing the inline query, adding text, changing the chat…).

**Comment by New-dev0** [comment]
I think, Closing this, will be better now :)

**Comment by New-dev0** [comment]
lonani, never mind
But Telegram's official docs too mention, about triggering inline query. 
https://core.telegram.org/api/bots/buttons
