### ISSUE TITLE
how to convert user.status.was_online to date?

### ISSUE THREAD

**Issue by elmagekmosaad** [LonamiWebs/Telethon#3086]
how to convert user.status.was_online to date?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by elmagekmosaad** [comment]
ok thanks
