### ISSUE TITLE
How to get registration date?

### ISSUE THREAD

**Issue by DenisTsukanov** [LonamiWebs/Telethon#3087]
How can I get a registration date of my account? There is no such a property in client.get_me()
The bot (@creationdatebot) somehow can get it.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
