### ISSUE TITLE
Help! How to send albums forwarded to me by others to a channel?

### ISSUE THREAD

**Issue by ChenZhenShan-UCAS** [LonamiWebs/Telethon#3088]
When others send me many photos or videos in album form, I want to send this album without source of forwarding to channel. I know I can use forward_message() method to forward a album. However, the message using this method will note forwarding source. Using send_message() method can`t send medias as album. What is the solution? Thanks

**Comment by ChenZhenShan-UCAS** [comment]
send_file() method....

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
