### ISSUE TITLE
unable to add members to a group

### ISSUE THREAD

**Issue by nauman-pucit** [LonamiWebs/Telethon#3092]
I am trying to add members to a public group, currently it has 2000 members
I have added 500 using telethon pachage, now it shows me success message that member is added, but their is not addition to members in group, can someone help me why is this happening
I have 16 phone numbers that I am using to add members, 
previously it was giving me flood error when limit reach, but now, it only shows success messages, but members are not being added to group or any group I am trying to add to

**Comment by Lonami** [comment]
Mass adding is considered spam. This is not a bug.

**Comment by nauman-pucit** [comment]
it is not allowing me even with new numbers
and on the other hand, some other people are adding members to the same group daily thousands of members simultaneously

**Comment by nauman-pucit** [comment]
Also I want to add here that I created a new group and tried to add people, it added 2,3 and then started giving success message again and not adding members
