### ISSUE TITLE
Album entity cannot answer to specific user

### ISSUE THREAD

**Issue by ChenZhenShan-UCAS** [LonamiWebs/Telethon#3096]
```Album``` entity inherits from ```EventBuilder```,and ```EventBuilder``` has a argument ```chats```
>chats (entity, optional): May be one or more entities (username/peer/etc.), preferably IDs. By default, only matching chats will be handled.
```
@client.on(events.Album(chats=('usernameTom','channelnameXX')))
async def forwardAlbum(event):
    client.send_message('mychannelname',msg)
    await client.send_file("mychannelname",event.messages)
    await event.reply('OK')
```
It seems that the program will only answer to ```usernameTom``` and ```channelnameXX```. But the program will be activated when messages come from channel  ```channelnameXX```. Nothing will happen when user ```usernameTom``` send message to this program. Is it a BUG???
How does Album entity answer to specific user? Thanks

**Comment by Lonami** [comment]
When you use chats, the chat where the event happens is checked, not the sender. Is this the issue?

**Comment by ChenZhenShan-UCAS** [comment]
@Lonami 
[Analysis]
When I send a album to userA who run this code, the```chat_id``` value of ```event=Album.Event```is None
![图片](https://user-images.githubusercontent.com/33375652/124504000-345c6e00-ddf9-11eb-8243-8103659dab0a.png)  
And in EventBuilder's ```filter``` method, there are following code block:
```python
if self.chats is not None:
    # Note: the `event.chat_id` property checks if it's `None` for us
    inside = event.chat_id in self.chats   <============this line
    if inside == self.blacklist_chats:
        # If this chat matches but it's a blacklist ignore.
        # If it doesn't match but it's a whitelist ignore.
        return
```  
this method will return without True. This event cannot pass the filter.  
When the message comes from a channel, ```event.char_id``` exist and is not None. 
  
[Question]
Is there no way to limit program to respond to albums that specific user send through set    ```chats```field?
As Telethon's Documentation said,```chats```can be set by ```username```. Doesn't sender's name meet this requirement?
Thanks!
