### ISSUE TITLE
Error - The source IP address is associated with a different data center (#4, for registration)

### ISSUE THREAD

**Issue by KanatSahanov** [LonamiWebs/Telethon#31]
Hi! I just install telethon with pip and when i run it, python interpreter gives me that error:
telethon.errors.RPCError: (RPCError(...), 'The source IP address is associated with a different data center (#4, for registration).')
App id and app hash is correct.
Can you please help me with this?

**Comment by XyLoNaMiyX** [comment]
It *should* fix itself. Have you tried running again? Deleting the `*.session` and retrying?

**Comment by XyLoNaMiyX** [comment]
I improved the handling of different data centers on [`628b739`](https://github.com/LonamiWebs/Telethon/commit/628b7391e38b837842b5f7a4075e064753f4e8f6). Please reopen if you still have this issue, **and** after you've followed the [steps](https://github.com/LonamiWebs/Telethon/issues/31#issuecomment-284738593) I mentioned before.
