### ISSUE TITLE
https://tl.telethon.dev/methods/channels/edit_banned.html parameter user_id is now 'participant'

### ISSUE THREAD

**Issue by iranzo** [LonamiWebs/Telethon#3100]
**Checklist**
* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
Parameter has changed the name (not available in Telethon          1.22.0)

<ipython-input-23-0cf4c8c7ba38> in <module>
----> 1 await client1(functions.channels.EditBannedRequest(channel='XXXXX', user_id='YYYYY',   banned_rights=ChatBannedRights(                          until_date=None,
      2                             view_messages=True,
      3                             send_messages=True,
      4                             send_media=True,
      5                             send_stickers=True,

TypeError: __init__() got an unexpected keyword argument 'user_id'

Regards

**Comment by New-dev0** [comment]
> TypeError: **init**() got an unexpected keyword argument 'user_id'

Telegram, layer has updated. 
user_id parameter of `EditBannedRight` is `participant` now.

**Comment by Lonami** [comment]
I often forget to update tl.telethon.dev. Fixed by https://github.com/LonamiWebs/Telethon/commit/7aaa25ce04c403a4d1bd8b0964c617a18812abe0.
