### ISSUE TITLE
when receiving a new message from the event:@client.on(events.NewMessage(chats=channels_links)) sometimes the message is cut off, I only receive a part of the message.

### ISSUE THREAD

**Issue by heldersemedo** [LonamiWebs/Telethon#3101]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
@client.on(events.NewMessage(chats=channels_links))
async def my_event_handler(message_obj):
    print(message_obj.message)
    current_message = message_obj.message
...

```

**Traceback**
```
Traceback (most recent call last):
  File "code.py", line 1, in <code>

```

**Comment by Lonami** [comment]
This is not enough information for me to diagnose the problem. Maybe there are issues printing to your terminal. Maybe the message truly is that long. You should try printing `repr(message_obj.message)` instead to see how it looks like when encoded.
