### ISSUE TITLE
SendCodeRequest returns next type = None

### ISSUE THREAD

**Issue by simplPart** [LonamiWebs/Telethon#3102]
were there any changes in the logic of sending a call for login? in most cases SendCodeRequest returns next_type = None and it is impossible to login or create an account. next_type for flash call. problem with new accounts

**Comment by Lonami** [comment]
Maybe Telegram changed things server-side and there is no next type. I cannot fix this, because it doesn't depend on me. It depends on Telegram's API, which is beyond my control.
