### ISSUE TITLE
Bug in iter_dialogs()?

### ISSUE THREAD

**Issue by NotStatilko** [LonamiWebs/Telethon#3103]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
async for i in client.iter_dialogs(offset_peer=InputPeerChannel):
    ...
```

**Traceback**
```python
File "/home/non/.local/lib/python3.7/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/home/non/.local/lib/python3.7/site-packages/telethon/client/dialogs.py", line 53, in _load_next_chunk
    r = await self.client(self.request)
  File "/home/non/.local/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/non/.local/lib/python3.7/site-packages/telethon/client/users.py", line 58, in _call
    future = sender.send(request, ordered=ordered)
  File "/home/non/.local/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 176, in send
    state = RequestState(request)
  File "/home/non/.local/lib/python3.7/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/home/non/.local/lib/python3.7/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/home/non/.local/lib/python3.7/site-packages/telethon/tl/functions/messages.py", line 1682, in _bytes
    self.offset_peer._bytes(),
TypeError: _bytes() missing 1 required positional argument: 'self'
```
With `offset_peer` i wanted to fetch only channels.  i tried `Channel`, `InputChannel` and `PeerChannel`, all results in something like (except `InputPeerChannel`)

```python
ValueError: Could not find the input entity for <class 'telethon.tl.types.PeerChannel'> (type). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
``` 

Although [docs](https://tl.telethon.dev/methods/messages/get_dialogs.html) seems to be OK with it `Anything entity-like will work if the library can find its Input version (e.g., usernames, Peer, User or Channel objects, etc.).`. 

So is it bug, or i am doing something wrong?

**Comment by New-dev0** [comment]
You are directly using class `InputPeerChannel` as offset_peer.
You can use it like

```
offset_peer = await client.get_input_entity('username/id')
```

or 

```
offset_peer = types.InputPeerChannel(channel_id=channel_id, access_hash=access_hash)
``
get_input_entity can be considered convenient method to use

**Comment by NotStatilko** [comment]
> You are directly using class `InputPeerChannel` as offset_peer.
> You can use it like
> 
> ```
> offset_peer = await client.get_input_entity('username/id')
> ```
> 
> or
> 
> ```
> offset_peer = types.InputPeerChannel(channel_id=channel_id, access_hash=access_hash)
> ```
> 
> get_input_entity can be considered convenient method to use

Thanks. It seems i do all wrong. Using Channel as `offset_peer` will result in yielding only Channels, or all Chats *after* this `offset_peer`?

**Comment by MrVitaming** [comment]
Thanks a lot,New-dev0!
