### ISSUE TITLE
How to refresh file references for uploaded files? getting FILE_REFERENCE_INVALID

### ISSUE THREAD

**Issue by skurob** [LonamiWebs/Telethon#3108]
Hi, i'm having troubles in finding a way to refresh file references of files uploaded using [uploadMediaRequest](https://tl.telethon.dev/methods/messages/upload_media.html).
Since as peer i'm using InputUserSelf(), i tried to find the document file using the id returned from client.upload_file() so that i can use it to gather information about the new assigned file reference, but in "saved messages" i couldn't find any of my files.

Where are these files getting saved?
How can i access them without a file_reference?
Thanks in advance.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

(Basically you need to send it somewhere and fetch that message again).
