### ISSUE TITLE
to_dict() produces inexact constructor name

### ISSUE THREAD

**Issue by ingria** [LonamiWebs/Telethon#3111]
Constructor namespace (`message.`, `channel.`, `help.`, `stats.`, etc) is missing when serializing object to dict.

For example:

```python
import telethon

obj = telethon.tl.types.messages.Messages(messages=[], chats=[], users=[])

print(obj.to_dict())
```

Prints:

```python
{'_': 'Messages', 'messages': [], 'chats': [], 'users': []}
```

Should be:

```python
{'_': 'messages.messages', 'messages': [], 'chats': [], 'users': []}
```

**Comment by Lonami** [comment]
With the form you suggest there's less parity with what the user writes (the type name) and sees (the '_').

The namespace and type name may work however.

In any case, people are like relying on the current output, so this would be a breaking change.

**Comment by ingria** [comment]
My idea for `_` is to represent Telegram [schema definition](https://core.telegram.org/constructor/messages.messages), rather than Telethon classes. Because it's always possible to determine what Telethon class represents the given TL definition, but not vice versa.

For example, let's say we need to deserialize some classes. For `{'_': 'contacts.found'}` it is obvious that we have to use `telethon.tl.types.contacts.Found`. For the `{'_': 'Found'}` notation, neither the constructor name, nor Telethon class name can be determined for sure.

**Comment by Lonami** [comment]
Would it be enough to include the module name along with the class name? This way you can map from Telethon to TL (which is, in my opinion, more useful, since you can directly `getattr` to get back the type).
