### ISSUE TITLE
send_code_request not sending SMS

### ISSUE THREAD

**Issue by andrekat** [LonamiWebs/Telethon#3117]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

session_path = Path("sessions")
if not session_path.exists():
    session_path.mkdir()

phone_number = get_phone_number()
client = TelegramClient(f"sessions/{phone_number}", api_id, api_hash, proxy=proxy)


async def main():
    await client.connect()

    await client.send_code_request(f"+{phone_number}", force_sms=True)
    verification_code = get_verification_code()
    await client.sign_up(verification_code, names.get_first_name(), names.get_last_name())

    await client.disconnect()


client.loop.run_until_complete(main())



```

**Traceback**
```
Traceback (most recent call last):
  verification_code = get_verification_code() <- stuck here, since no SMS is being received
```

The send_code_request is sent successfully, however .. no SMS is sent. The phone number is definitely not used ... is there something new on the library I had forget? 

Thanks in advance!

UPDATE: I double checked the phone number right now with the Telegram App itself ... and the Code was sent?

**Comment by ahmelshafei** [comment]
Did you find a solution yet? Cause I had the same problem but it happened when I use the same number over and over. However, using a different number worked fine.

**Comment by NikolaiEngel** [comment]
I have the same problem that when creating an account the SMS or call are not delivered

**Comment by mahdizolqadr** [comment]
i think we must use phone device config because in new version of tdesktop this problem is available too. but when i use phone device send sms is correctly work

**Comment by CptKirk** [comment]
> i think we must use phone device config because in new version of tdesktop this problem is available too. but when i use phone device send sms is correctly work

Thx @mahdizolqadr for your answer. We are currently experiencing the same issue. If we request the Code over the App, everything works fine but as soon as we request the code over Telethon, there is no SMS arriving. Even though the response from `client.send_code_request()` returns a `phone_code_hash` and says that the current `auth_type` is SMS. What exactly do you mean by "we must use phone device config"? We tried passing a `device_model` to the `TelegramClient` without luck.

**Comment by Lonami** [comment]
I don't know why Telegram decides when or not to send an SMS, but in order to debug this more easily, you may use the raw API call [`SendCodeRequest`](https://tl.telethon.dev/methods/auth/send_code.html) (and the resend variant). Perhaps this way (using and receiving raw data from Telegram) one can get more insight.

**Comment by mahdizolqadr** [comment]
> I don't know why Telegram decides when or not to send an SMS, but in order to debug this more easily, you may use the raw API call [`SendCodeRequest`](https://tl.telethon.dev/methods/auth/send_code.html) (and the resend variant). Perhaps this way (using and receiving raw data from Telegram) one can get more insight.

i know why telegram decides this work, because it was a security bug and we report it :(

**Comment by Lonami** [comment]
Well, it's good to know these limits have actual reasons to exist then :)

Given this, I doubt Telethon can do anything to "fix" it but I'll leave the issue open for a bit longer in case anyone finds it or wants to discuss further.

**Comment by rnyPlanet** [comment]
[interesting](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/tgnet/ConnectionsManager.cpp#L3264) + [this](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/tgnet/ConnectionsManager.cpp#L2837)

**Comment by mahdizolqadr** [comment]
they use api_id and api_key for detect original telegram or not. i think if we find out original api_id and api_key we succeed.

**Comment by rnyPlanet** [comment]
> they use api_id and api_key for detect original telegram or not. i think if we find out original api_id and api_key we succeed. in any case, there is no need to change telethon

I think api_id is one of the parameters due to which it does not want to send SMS. [api_id android tg](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java#L24)

**Comment by rnyPlanet** [comment]
> > they use api_id and api_key for detect original telegram or not. i think if we find out original api_id and api_key we succeed. in any case, there is no need to change telethon
> 
> I think api_id is one of the parameters due to which it does not want to send SMS. [api_id android tg](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java#L24)
> 
> you can search for **currentApiId** [here](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/tgnet/ConnectionsManager.cpp) and see what parameters it additionally sends when connecting

I also had an idea to take the **jni** folder from the android tg and try to replace the connection to the server in the telethon. but so far I have neither knowledge nor time

**Comment by mahdizolqadr** [comment]
> > they use api_id and api_key for detect original telegram or not. i think if we find out original api_id and api_key we succeed. in any case, there is no need to change telethon
> 
> I think api_id is one of the parameters due to which it does not want to send SMS. [api_id android tg](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java#L24)
> 
> you can search for **currentApiId** [here](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/tgnet/ConnectionsManager.cpp) and see what parameters it additionally sends when connecting
> 
> I also had an idea to take the **jni** folder from the android tg and try to replace the connection to the server in the telethon. but so far I have neither knowledge nor time

when i use : 
`
api_id = 4
api_hash = '014b35b6184100b085b0d0572f9b5103' 
`

raised this error:
`
ApiIdPublishedFloodError: This API id was published somewhere, you can't use it now
`

**Comment by Lonami** [comment]
Please do not publicly share other people's API IDs and hashes. They should be kept secret.

**Comment by mahdizolqadr** [comment]
> > > they use api_id and api_key for detect original telegram or not. i think if we find out original api_id and api_key we succeed. in any case, there is no need to change telethon
> > 
> > 
> > I think api_id is one of the parameters due to which it does not want to send SMS. [api_id android tg](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java#L24)
> > you can search for **currentApiId** [here](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/tgnet/ConnectionsManager.cpp) and see what parameters it additionally sends when connecting
> > I also had an idea to take the **jni** folder from the android tg and try to replace the connection to the server in the telethon. but so far I have neither knowledge nor time
> 
> when i use :
> `api_id = 4 api_hash = '7ebe9e459b40eae77af60cc169e93715'`
> 
> raised this error:
> `ApiIdPublishedFloodError: This API id was published somewhere, you can't use it now`

new report :)

i de-compile original app and recompile it , but telegram raised error again because they check apk signature. so we need fetch original sign maybe using frida

**Comment by rnyPlanet** [comment]
> i de-compile original app and recompile it , but telegram raised error again because they check apk signature. so we need fetch original sign maybe using frida

what error is it throwing?
I personally don't think they are looking at the signature of the application. here's the interesting thing [here](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/tgnet/ConnectionsManager.cpp#L2754)

**Comment by mahdizolqadr** [comment]
> > i de-compile original app and recompile it , but telegram raised error again because they check apk signature. so we need fetch original sign maybe using frida
> 
> what error is it throwing?
> I personally don't think they are looking at the signature of the application. here's the interesting thing [here](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/tgnet/ConnectionsManager.cpp#L2754)

![Kazam_screenshot_00003](https://user-images.githubusercontent.com/32035745/133955591-db852c44-2bfc-4c5e-bd99-095c54bc48bd.png)

any change in apk, occurred this error on loginrequest

**Comment by rnyPlanet** [comment]
> i de-compile original app and recompile it , but telegram raised error again because they check apk signature. so we need fetch original sign maybe using frida

what api id after decompilation, 4?

**Comment by mahdizolqadr** [comment]
> > i de-compile original app and recompile it , but telegram raised error again because they check apk signature. so we need fetch original sign maybe using frida
> 
> what api id after decompilation, 4?

yes
may they use hidden tl ?

**Comment by rnyPlanet** [comment]
> may they use hidden tl ?

idk. I know for sure that the parameters change during compilation, but in which class I do not remember. here are the settings for the [compliment](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/build.gradle#L156)

**Comment by vrtme** [comment]
someone was able to get around this problem?

**Comment by rnyPlanet** [comment]
https://github.com/LonamiWebs/Telethon/issues/3194 is it possible that the problem is related to this?🤔🤔🤔

**Comment by mahdizolqadr** [comment]
> #3194 is it possible that the problem is related to this?thinkingthinkingthinking

no.

**Comment by vnpresent** [comment]
> **Checklist**
> 
> * [ ]  The error is in the library's code, and not in my own.
> * [x]  I have searched for this issue before posting it and there isn't a duplicate.
> * [ ]  I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
> 
> **Code that causes the issue**
> 
> ```python
> from telethon.sync import TelegramClient
> 
> session_path = Path("sessions")
> if not session_path.exists():
>     session_path.mkdir()
> 
> phone_number = get_phone_number()
> client = TelegramClient(f"sessions/{phone_number}", api_id, api_hash, proxy=proxy)
> 
> 
> async def main():
>     await client.connect()
> 
>     await client.send_code_request(f"+{phone_number}", force_sms=True)
>     verification_code = get_verification_code()
>     await client.sign_up(verification_code, names.get_first_name(), names.get_last_name())
> 
>     await client.disconnect()
> 
> 
> client.loop.run_until_complete(main())
> ```
> 
> **Traceback**
> 
> ```
> Traceback (most recent call last):
>   verification_code = get_verification_code() <- stuck here, since no SMS is being received
> ```
> 
> The send_code_request is sent successfully, however .. no SMS is sent. The phone number is definitely not used ... is there something new on the library I had forget?
> 
> Thanks in advance!
> 
> UPDATE: I double checked the phone number right now with the Telegram App itself ... and the Code was sent?

did you fix it?,please tell me how to fix it

**Comment by andreiwind** [comment]
> 

Нужно удалить файл сессии для повторного получения кода

**Comment by netzhuo** [comment]
Has anyone found a solution?  I also encountered the same problem, thank you

**Comment by netzhuo** [comment]
> 

没有用唉
