### ISSUE TITLE
from .tl.types import ( ImportError: No module named types

### ISSUE THREAD

**Issue by polozhevets** [LonamiWebs/Telethon#312]

**Comment by Lonami** [comment]
Version? Did you run `python3 setup.py gen_tl`?

**Comment by polozhevets** [comment]
telethon/utils.py", line 9,

**Comment by Lonami** [comment]
Yeah but, did you run `python3 setup.py gen_tl`?

**Comment by polozhevets** [comment]
no, thanks

**Comment by Lonami** [comment]
[Fourth step](https://github.com/LonamiWebs/Telethon/wiki/Installing-Telethon#manual-installation) :)
