### ISSUE TITLE
Answer on non owner request

### ISSUE THREAD

**Issue by KOT4N11** [LonamiWebs/Telethon#3122]
In bots i have problem - lib says, than "this not active command" etc.
Plz fix it, is very old problem

**Comment by Lonami** [comment]
Please reopen once you're able to provide more information (describe the situation, problem, what is happening, and what should happen, in more detail).

**Comment by KOT4N11** [comment]
if you send from non owner telethon says
"Incoming massage!"
He send msg to queue... and skip it.
