### ISSUE TITLE
Failed join group / channels

### ISSUE THREAD

**Issue by JustAHackers** [LonamiWebs/Telethon#3125]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [✓] I have searched for this issue before posting it and there isn't a duplicate.
* [✓] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
from telethon.tl.functions.channels import JoinChannelRequest
def join_group(client,channel):
    client(JoinChannelRequest(channel=channel))
    return True

```

**Traceback**
```
Exception : You have joined too many channels/supergroups
```

When i tried to join a group / channel,it return an exception that i have joined too many channel/groups
But i havent join any channel or group,when i do it manual,i can join them,but when i use this code i cant.

I tried the other code to left channel / groups,it worked! The only problem was joining with that code

Any suggestion?

**Comment by Lonami** [comment]
This is not a bug in the library. This is a Telegram limitation.
