### ISSUE TITLE
my.telegram.org Unable to register Apps

### ISSUE THREAD

**Issue by h87070628** [LonamiWebs/Telethon#3126]
https://my.telegram.org, Keep showing ERROR. what happened?

**Comment by h87070628** [comment]
![1](https://user-images.githubusercontent.com/3609490/128806404-b5becc45-1726-4a9c-92a7-526a5a6416c8.png)
like this

**Comment by Lonami** [comment]
This is not an issue with Telethon. You may find more about this problem in https://t.me/TelethonChat/362253. It appears certain numbers are now blocked in order to prevent spam.
