### ISSUE TITLE
ReportRequest not like in Telegram Api

### ISSUE THREAD

**Issue by maksum2000** [LonamiWebs/Telethon#3129]
Hello. Why ReportRequest ask message? In telegram api no parametr message, i dont want send message in report, how do?

**Comment by maksum2000** [comment]
and ReportPeerRequest too ask message. why?

**Comment by maksum2000** [comment]
> > and ReportPeerRequest too ask message. why?
> 
> That message is "Additional Detail" About your report, that Telegram Asks you. You can skip that, by keep it empty text too.

ok thx, i can give message="", yes?

**Comment by New-dev0** [comment]
> ok thx, i can give message="", yes?

Yes
