### ISSUE TITLE
Telethon cannot connect to client while different loop policy!

### ISSUE THREAD

**Issue by hideuk** [LonamiWebs/Telethon#3139]
**Checklist**
* [ True ] The error is in the library's code, and not in my own.
* [ True ] I have searched for this issue before posting it and there isn't a duplicate.
* [ True ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python3.9

import asyncio
from telethon import TelegramClient

client = TelegramClient("sus", api_id, api_hash)


async def main():
    await client.connect()

    me = await client.get_me()
    print(me)

    await client.disconnect()


# if i set diffent loop policy client dont work!
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

loop = asyncio.get_event_loop()
mais = loop.create_task(main())
loop.run_until_complete(mais)

```

**Traceback**
```
it can client.connect() forever if i set different loop policy!

```

What i can do with that?

**Comment by atrezonator** [comment]
use threading.Thread(target=prescript, args=(,)).start()

**Comment by Lonami** [comment]
Telethon v2 has changed the way connections work, and raw sockets are now used. If that loop does not support connecting through sockets, there's not much Telethon can do about it, as it's a necessity.
