### ISSUE TITLE
WorkerBusyTooLongRetryError: Telegram workers are too busy to respond immediately (caused by SendMultiMediaRequest)

### ISSUE THREAD

**Issue by DenisTsukanov** [LonamiWebs/Telethon#3148]
await client.send_file(channel_entity, baby.gallery_of_babe_photos,caption=all_info)

**gallery_of_babe_photos** - is a list, that contains 10 names of photos that should be uploaded

Traceback (most recent call last):
  Telegram is having internal issues WorkerBusyTooLongRetryError: Telegram workers are too busy to respond immediately (caused by SendMultiMediaRequest)

So, it uploads 8 pictures at a time, and it is an album, but than it uploads 2 other pictures that are already excluded from album

**Comment by Lonami** [comment]
> Telegram is having internal issues

This cannot be fixed by the library. You can only wait.
