### ISSUE TITLE
Delays in getting messages from channels having large number of subscribers

### ISSUE THREAD

**Issue by hardiks2310** [LonamiWebs/Telethon#3150]
I am trying to read messages from a channel with ~1 M subscribers. The messages are delayed by 20-45 seconds. If my telegram is open on the mobile app and I keep checking out that channel frequently, the delay reduces to 1-5 seconds. In my code, I am currently using events.NewMessage() to activate my code on receipt of a new message.

**Comment by Lonami** [comment]
Previous discussion: #652. The only true solution is to have working updates (attempted by #3062).

**Comment by snailAlice** [comment]
> 之前的讨论：#652。唯一真正的解决方案是进行工作更新（由#3062尝试）。
Does the current master branch solve the problem of delays in getting messages from channels with a large number of subscribers? Do we need to modify specific updates.py files individually？
