### ISSUE TITLE
Entities for invite links are not cached properly

### ISSUE THREAD

**Issue by Thoufak** [LonamiWebs/Telethon#3154]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import asyncio
import logging

import telethon

logging.basicConfig(level=logging.DEBUG)


async def main():
    client = await make_client()

    url = "https://t.me/joinchat/DOrvIqABLH00MTQy"
    invite_hash = url.split("/")[-1]

    await client(telethon.functions.messages.ImportChatInviteRequest(invite_hash))
    print("Joined chat.")

    while True:
        await client.send_message(url, "Test")
        print("Sent message.")
        await asyncio.sleep(1)


async def make_client() -> telethon.TelegramClient:
    client = telethon.TelegramClient(
            "test",
           # App info omitted
    )
    await client.start()
    print("Connected.")
    return client


if __name__ == '__main__':
    asyncio.run(main())
```

**Traceback**
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "path_to_project/main.py", line 22, in main
    s = await client.send_message(url, "Test")
  File "path_to_project/resources/venv/lib/python3.7/site-packages/telethon/client/messages.py", line 794, in send_message
    entity = await self.get_input_entity(entity)
  File "path_to_project/resources/venv/lib/python3.7/site-packages/telethon/client/users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "path_to_project/resources/venv/lib/python3.7/site-packages/telethon/client/users.py", line 537, in _get_entity_from_string
    functions.messages.CheckChatInviteRequest(username))
  File "path_to_project/resources/venv/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "path_to_project/resources/venv/lib/python3.7/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 275 seconds is required (caused by CheckChatInviteRequest)
```

**Discussion**
Each time before sending a message the library will send a `CheckChatInviteRequest`, which comes from telethon/client/users.py:537 (see attached debug-logs as a proof). This will soon result in a `FloodWaitError` caused exactly by that request (not the `SendMessageRequest`). However, there is no need to send the `CheckChatInviteRequest`, because we should already have the information about the chat (at least after we've sent the first message there). Thus, the problem is that the library doesn't cache the entity corresponding to the invite link. Please note, that if I replace the url with the chat ID, the `CheckChatInviteRequest` is not sent and everything works fine.

[debug-logs.txt](https://github.com/LonamiWebs/Telethon/files/7136147/debug-logs.txt)

**Comment by Lonami** [comment]
This was probably fixed by #3133, cc @painor can you confirm?

**Comment by painor** [comment]
no this is a different thing. they are passing an invite URL to send_message which calls that function each time.

**Comment by Lonami** [comment]
Ah, right, invite links changed so the chat ID can no longer be extracted from it, and thus the cache is not really usable. Thanks. Closing. The solution is to use the ID instead of the link.
