### ISSUE TITLE
Using session data in Web client

### ISSUE THREAD

**Issue by HeartOfSun** [LonamiWebs/Telethon#316]
Hi! Thank you for your awesome library!
Please, tell me, how can I use the Telethon session data in Web-client?

I want to set localstorage variables, but I didn't find dc id in the session.
Server salt in Web-client looks like a "25318de9523b0cc7", but in the Telethon session my salt is 1313685959827830653.

Thank you!

**Comment by Lonami** [comment]
I've got no idea, as I've never needed such thing and I didn't write the Telegram web client. Maybe you can ignore the salt and Telegram will send the right one? I don't know.

**Comment by Lonami** [comment]
From the Developers Console:
```javascript
// where X is the data center you're connected to (1..5)
localStorage.getItem('dcX_auth_key')
```

With that you just change the `Session`'s `auth_key`:
```python
from telethon.crypto import AuthKey
client.session.auth_key = AuthKey(data=bytearray.fromhex(obtained_string))
assert client.connect()
```

**Comment by nazi-k** [comment]
### dsgfsdg
