### ISSUE TITLE
ImportContactsRequest giving empty users list

### ISSUE THREAD

**Issue by OneBusyBrain** [LonamiWebs/Telethon#3168]
```
import random
from telethon.sync import TelegramClient
from telethon.tl import functions, types
from telethon.tl.functions.messages import AddChatUserRequest
from telethon.tl.types import InputPhoneContact
from telethon.tl.functions.contacts import ImportContactsRequest
from telethon import utils
from telethon.tl.functions.contacts import DeleteContactsRequest

api_id = xxxxxxxxx
api_hash = 'xxxxxxxxxxxxxxxxxxxx'
phone_number = '+91xxxxxxxxx'
raw_group_id = -12334
guest_phone_number = "+91xxxxxx"
group_id, peer_type = utils.resolve_id(raw_group_id)

client = TelegramClient('session_name',
                    api_id,
                    api_hash)

async def main():
    await client.send_message('me', 'Hello !!!!')

with client:
    client.loop.run_until_complete(main())
client.connect()

if not client.is_user_authorized():
    client.send_code_request(phone_number)
    client.sign_in(phone_number, input('Enter code: '))

# ---------------------------------------

#_the issue is expected to begin here :_

contact = InputPhoneContact(client_id=random.randint(0, 9999), phone=guest_phone_number, first_name="test", last_name="contact")
result = client(ImportContactsRequest([contact]))

#_the issue is expected to end here_

print(result.stringify())
print(contact)

#------------ part 2 as follows :

# add contact to your group
client(AddChatUserRequest(user_id=result.users[0], fwd_limit=0, chat_id=group_id))
```

**Above is my entire code. Everything is working fine except for _ImportContactsRequest_ because it returns an _empty **users** list_ which causes the following error.**  And is thus unable to add the number to my contact list.

I also took help from [here](https://stackoverflow.com/questions/48684915/telethon-library-how-to-add-user-by-phone-number/63153075#63153075) for creating this code

### ERROR :

```
client(AddChatUserRequest(user_id=result.users[0], fwd_limit=0, chat_id=group_id))
IndexError: list index out of range
```

is there any way to tackle this problem or if anything is wrong with my code what is the solution to it ?

**Comment by OneBusyBrain** [comment]
Below is the output of **`print(result)`** in which we can see that **users list is empty** which causes code part 2 to fail (unable to add that contact to my telegram group) by giving the above error.

`ImportedContacts(imported=[], popular_invites=[PopularContact(client_id=7121, importers=26)], retry_contacts=[], users=[])`

**Comment by Lonami** [comment]
The API is working as intended. Telethon cannot change the way raw API works. This is decided by Telegram.

**Comment by OneBusyBrain** [comment]
so why is the user list empty ??

**Comment by OneBusyBrain** [comment]
how do i add them to my contacts then ? everywhere its the same method but user list is coming out empty. what should i do ???
its very crucial for me to get this done as quickly as possible. pls help
