### ISSUE TITLE
Session TTL

### ISSUE THREAD

**Issue by IlyaKronos** [LonamiWebs/Telethon#317]
What's session keep alive timeout?

I registered some accounts yesterday, now they got session error. How often I need to show activity from accounts to don't lose session?

Thank you in advice

P.s I didn't found this information in wiki

**Comment by Lonami** [comment]
"Session keep alive timeout"? Could you describe that a bit more?

> now they got session error

What error?

**Comment by IlyaKronos** [comment]
Just client.is_user_authorized() = false

**Comment by IlyaKronos** [comment]
Oh, they are now 'Deleted User' and seem to be locked. Interesting, I didn't spam and didn't intend to spam.

So .session can stay alive for a long time?

**Comment by Lonami** [comment]
The session file should be valid forever and ever after, yes. There's no limit on how long they can live.

**Comment by IlyaKronos** [comment]
Thank you for answer.
