### ISSUE TITLE
When using multiple threads, a large number of CLOSE_WAIT appears

### ISSUE THREAD

**Issue by NHY1994** [LonamiWebs/Telethon#3170]
When using multi-threading, there are a lot of "CLOSE_WAIT"

how can I solve this problem?

linux command:
netstat -n | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'

**Comment by Lonami** [comment]
Why is this an issue? The library is based on `asyncio`, and it doesn't expect threads to be used.
