### ISSUE TITLE
Identify forwarded messages on large scale

### ISSUE THREAD

**Issue by jcy204** [LonamiWebs/Telethon#3172]
First off, this library is brilliant and has already been of great help to me - thank you!

Currently, I am struggling to identify forwarded messages in conversations without downloading the history and checking whether each message has the 'fwd_from' attribute. Is there a quicker/more efficient way to do this, potentially using a similar approach to the InputMessagesFilterXYZ filters?

Also (like others), I have encountered a 3hour 'ExportAuthorizationRequest' error after minimal use of client.get_entity() function. I am aware this is on Telegram's side, but is there a recommended waiting period between searches that would prevent this?

Thanks,
James

**Comment by Lonami** [comment]
Thanks for the kind words. This is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
