### ISSUE TITLE
"AttributeError: 'PhotoSize' object has no attribute 'location'" when bot receives a compressed photo

### ISSUE THREAD

**Issue by alexgoryushkin** [LonamiWebs/Telethon#3173]
I got a strange exception just trying to display the id of the file received by the bot. This problem occurs when a bot receives a compressed photo. When the bot receives a file or photo without compression, no error occurs.
Telethon version: 1.23.0

**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python

from telethon import TelegramClient, events

bot_token = ...
api_id = ...
api_hash = ..

client = TelegramClient('anon', api_id, api_hash).start(bot_token=bot_token)

@client.on(events.NewMessage(incoming=True))
async def recv_message(event: events.NewMessage.Event) -> None:
    if event.message.file:
        print(event.message.file.id)

client.run_until_disconnected()
```

**Traceback**
```
Traceback (most recent call last):
  File "/home/bot/venv/lib/python3.8/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "/home/bot/main.py", line 170, in recv_message
    print(event.message.file.id)
  File "/home/bot/venv/lib/python3.8/site-packages/telethon/tl/custom/file.py", line 34, in id
    return utils.pack_bot_file_id(self.media)
  File "/home/bot/venv/lib/python3.8/site-packages/telethon/utils.py", line 1264, in pack_bot_file_id
    size = size.location
AttributeError: 'PhotoSize' object has no attribute 'location'
```

**Comment by Lonami** [comment]
`file.id` will be removed in future versions (it's not really working any more).
