### ISSUE TITLE
I can't import ChannelBannedRights

### ISSUE THREAD

**Issue by slmv-e** [LonamiWebs/Telethon#3175]
Hi, I'm using PyCharm and I installed telethon, when i try import ChannelBannedRights from telethon.tl.types Python gives mе error

**Code that causes the issue**

from telethon.tl.types import PeerChannel, PeerUser, ChannelBannedRights

**Traceback**

Traceback (most recent call last):
  File "...", line 3, in <module>
    from telethon.tl.types import PeerChannel, PeerUser, ChannelBannedRights
ImportError: cannot import name 'ChannelBannedRights' from 'telethon.tl.types' (...)

**Comment by New-dev0** [comment]
There is nothing like `ChannelBannedRights`.
[`ChatBannedRights`](https://tl.telethon.dev/constructors/chat_banned_rights.html) exists, which work for `Channel(s)` too. 

You can refer [`tl.telethon.dev`](https://tl.telethon.dev) to get reference of All Available Types/constructors/Methods.

**Comment by slmv-e** [comment]
Thanks, I solved the problem
