### ISSUE TITLE
Device name causes logging out

### ISSUE THREAD

**Issue by gittethis** [LonamiWebs/Telethon#3194]
As mentioned on `https://stackoverflow.com/questions/69538477/telethon-gets-disauthenticated-on-armv6-but-not-armv7/69692138#69692138`, if the kernel uname of the device does not have a dash between the version and the custom string (when re-compiled), the full kernel name is sent upon connection and after initial successful login all the account's already connected devices are getting logged out after about 120 seconds (plus/minus 60 seconds).

to confirm, after altering the following `telegrambaseclient.py` line (on an affected system with kernelname in form of **5.6.14CUSTOMNAME,** without a dash between **version** and **CUSTOMNAME):**

`default_system_version = re.sub(r'-.+','',system.release)`
with
`default_system_version = '5.6.14'`

the clients are not disconnected/deauthenticated anymore.

**Comment by Lonami** [comment]
This is unlikely to be changed. I do not have plans for the library to play "catch" trying to come up with working values every few months. Any change that makes it "work" again will most likely be abused and then the same problem will repeat. So if this problem occurs in your case, feel free to change the values to something that works for you.

**Comment by gittethis** [comment]
It was more like a heads-up, at the time I spent like two days trying to figure out why the devices were all logged out from the system (and the 'non dashed' kernelname was among the last things to verify :))

**Comment by yurket** [comment]
had the same problem on Raspberry PI 5 (armv8_cortex_a76). [TelegramClient](https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.telegrambaseclient.TelegramBaseClient) has `system_version` parameter, which solves the issue.
