### ISSUE TITLE
Allow hiding sender's name and/or caption when forwarding

### ISSUE THREAD

**Issue by Architector4** [LonamiWebs/Telethon#3197]
Telegram Desktop 3.0 client has introduced the ability to "change how the messages will be sent" when forwarding (see attached image): https://desktop.telegram.org/changelog#v-3-0-31-08-21

From that, I assume it would be possible for Telethon to expose that as well. However, I do not see any way to do the same thing in the function `telethon.client.messages.MessageMethods.forward_messages`. Either I'm blind and missed it, or it's not in Telethon?

![image](https://user-images.githubusercontent.com/23612841/139493165-9d031756-f5bd-4649-b32c-43b66fb606ef.png)

**Comment by soroushfathi** [comment]
you can use send_message for hide senders name.
And for caption, you can put caption argument empty :)
[`telethon.client.messages.MessageMethods.send_message`](https://docs.telethon.dev/en/latest/modules/client.html?highlight=query#telethon.client.messages.MessageMethods.send_message)

**Comment by Architector4** [comment]
> you can use send_message for hide senders name. And for caption, you can put caption argument empty :)

Oh, yeah, that does work and makes sense - just taking the message object and sending it as self - all the media stays there too lol

Though still, since at least official Telegram offer this functionality as a type of a forward, I feel like it's still a good idea to implement this with the `forward_messages` method, or at least mention this trick in its documentation.

**Comment by soroushfathi** [comment]
> > you can use send_message for hide senders name. And for caption, you can put caption argument empty :)
> 
> Oh, yeah, that does work and makes sense - just taking the message object and sending it as self - all the media stays there too lol
> 
> Though still, since at least official Telegram offer this functionality as a type of a forward, I feel like it's still a good idea to implement this with the `forward_messages` method, or at least mention this trick in its documentation.

yeah👍 i dont know why still they didn't implement this with `forward message`

**Comment by du5** [comment]
> > you can use send_message for hide senders name. And for caption, you can put caption argument empty :)
> 
> Oh, yeah, that does work and makes sense - just taking the message object and sending it as self - all the media stays there too lol
> 
> Though still, since at least official Telegram offer this functionality as a type of a forward, I feel like it's still a good idea to implement this with the `forward_messages` method, or at least mention this trick in its documentation.

I also had this problem, I modified the parameters and it worked https://github.com/du5/Telethon/commit/64733fa890a04ad90af2b217b9c80936b8cca0cc

**Comment by alm0ra** [comment]
@Lonami  have same issue

**Comment by Commonlist** [comment]
> > > you can use send_message for hide senders name. And for caption, you can put caption argument empty :)
> > 
> > 
> > Oh, yeah, that does work and makes sense - just taking the message object and sending it as self - all the media stays there too lol
> > Though still, since at least official Telegram offer this functionality as a type of a forward, I feel like it's still a good idea to implement this with the `forward_messages` method, or at least mention this trick in its documentation.
> 
> I also had this problem, I modified the parameters and it worked [du5@64733fa](https://github.com/du5/Telethon/commit/64733fa890a04ad90af2b217b9c80936b8cca0cc)

Hello. I wanted to ask, where do I need to change these parameters to make it work? I didn't find a file on my computer telethon/client/messages.py

**Comment by Lonami** [comment]
This is unlikely to happen in the near future so I will be closing the issue. We can reopen it if there's still interest once the time is right. Note that it's possible to use raw API if you need features not exposed by the friendly API.

**Comment by matveygal** [comment]
Guys you didn't read the docs. Just use copy_message. Here are the [Docs](https://pytba.readthedocs.io/en/latest/sync_version/index.html#telebot.TeleBot.copy_message)

**Comment by sophronesis** [comment]
> Guys you didn't read the docs. Just use copy_message. Here are the [Docs](https://pytba.readthedocs.io/en/latest/sync_version/index.html#telebot.TeleBot.copy_message)

It's not telethon docs, it even doesn't replace telethon, it's just simple bot wrapper

**Comment by sophronesis** [comment]
Best possible way to solve this is to just use Pyrogram whose ```copy_message()``` [method](https://docs.pyrogram.org/api/methods/copy_message#pyrogram.Client.copy_message) does exactly this.

**Comment by Architector4** [comment]
> Best possible way to solve this is to just use Pyrogram whose `copy_message()` [method](https://docs.pyrogram.org/api/methods/copy_message#pyrogram.Client.copy_message) does exactly this.

It's not telethon docs, it even doesn't replace telethon, it's just simple bot wrapper

**Comment by Architector4** [comment]
> Best possible way to solve this is to just use Pyrogram whose `copy_message()` [method](https://docs.pyrogram.org/api/methods/copy_message#pyrogram.Client.copy_message) does exactly this.

Between using an entirely different unrelated package for dealing with Telegram and rewriting all my code to use that, and doing a simple albeit a bit obtuse thing that Telethon has that achieves the same purpose, I think I'd rather choose the latter lmao

**Comment by icepandamichael** [comment]
> > Best possible way to solve this is to just use Pyrogram whose `copy_message()` [method](https://docs.pyrogram.org/api/methods/copy_message#pyrogram.Client.copy_message) does exactly this.
> 
> Between using an entirely different unrelated package for dealing with Telegram and rewriting all my code to use that, and doing a simple albeit a bit obtuse thing that Telethon has that achieves the same purpose, I think I'd rather choose the latter lmao

I got a problem, when the message has markdown style, like [text](url), the send_message with formatting_entities=message.entities doesn't work well.

**Comment by icepandamichael** [comment]
> Best possible way to solve this is to just use Pyrogram whose `copy_message()` [method](https://docs.pyrogram.org/api/methods/copy_message#pyrogram.Client.copy_message) does exactly this.

But copy_message() doesn't work well when the message has complicated styles.
