### ISSUE TITLE
use proxy

### ISSUE THREAD

**Issue by light-rain** [LonamiWebs/Telethon#32]
Hi
I could not find any way to use telethon with proxy
Is there some way to implement it?

**Comment by XyLoNaMiyX** [comment]
Not sure how a proxy works internally. Do you know how? Probably what you have to do is change the connection address to the proxy one, and the proxy should then forward all the information from the connect client (you) to the Telegram servers.

Again, I don't know how this would work for Telegram, sorry, never worked with proxies. Maybe you could implement some remote server to which you could communicate and send commands so it worked as an intermediate peer. So, Telethon would run there, and you would have a custom server application to which you could connect?

**Comment by JuanPotato** [comment]
pretty sure you can just use an socks5 lib, I've seen an old mtproto library do it

**Comment by exzhawk** [comment]
use PySocks (install from pip) instead of vanilla socket
change https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/tcp_client.py#L14 to
```python
        import socks
        self.socket = socks.socksocket(socket.AF_INET, socket.SOCK_STREAM)
        self.socket.set_proxy(socks.SOCKS5, '192.168.1.234', 8088)
```
change `192.168.1.234` to your proxy address and `8088` to your proxy port
works for me

**Comment by XyLoNaMiyX** [comment]
@exzhawk would you like to make a pull request on it so it's a built-in feature? Maybe some `try/except` for `import`'ing `socks`, and if available, a parameter like `use_proxy=`. I ask you because you seem to have more idea about it although you've given clear instructions (thanks!).

**Comment by exzhawk** [comment]
@XyLoNaMiyX this involves a third-party package PySocks. If you don't mind that, I'm willing to help.

**Comment by XyLoNaMiyX** [comment]
> this involves a third-party package PySocks.

Yes I know, you mentioned, but we can simply add it as a non-required dependency, only optional, and add some notice on the `README.rst` (something like "Using a proxy: Install PySocks blah blah…"), and then simply `try`'ing to import it and raise some error if they try to use a proxy without the library installed.

> I'm willing to help.

Fine with me, thank you :)

**Comment by XyLoNaMiyX** [comment]
Thanks to @exzhawk with #37 :)
