### ISSUE TITLE
Wrong documentation at message.edit?

### ISSUE THREAD

**Issue by AlberLC** [LonamiWebs/Telethon#3201]
Maybe i'm not understanding well this but both links are the same.

https://docs.telethon.dev/en/latest/modules/custom.html#telethon.tl.custom.message.Message.edit

![image](https://user-images.githubusercontent.com/37489786/140603885-4058e1f2-62d0-46d9-b1f1-5aaff4d1fb74.png)

**Comment by Lonami** [comment]
This is correct. `Message.edit` is simply `client.edit_message` (the first link is not stylized and has the full path to the method), however, because `Message` has the full object, it can respect old properties like buttons.
