### ISSUE TITLE
This method  is_connected  returns inaccurate results.

### ISSUE THREAD

**Issue by AtlantisDe** [LonamiWebs/Telethon#3204]
**This method returns inaccurate results.**

 

**Code ..**
```python
if client.is_connected():
        print('Connected OK')
# Also I am trying to catch exception to check whether client is connected or not.
# And method is_connected() return True.


```
#958 
[Somewhat similar to this question](https://github.com/LonamiWebs/Telethon/issues/958)

**Actually**
```
In fact, my network is unable to connect to the Telegram server. A proxy is required. 


But it returns true result to me
```

**Comment by Lonami** [comment]
`is_connected` returns `True` after calling connect and not having called disconnect (or the client didn't disconnect through an error). If the `asyncio.open_connection` does not claim an error, the library assumes connected.
