### ISSUE TITLE
hyperlink in the message not correct

### ISSUE THREAD

**Issue by vetsinen** [LonamiWebs/Telethon#3205]
here is an example from documentation how to send hyperlink in the message

**Code that causes the issue**
```python
   message = await client.send_message(
        'me',
        'This message has **bold**, `code`, __italics__ and '
        'a [nice website](https://example.com)!',
        link_preview=False
    )
```

but in the standard client this link is not fully displayed, telegram convert to link only link itself, but "nice website" does not have a link

![tele-gluk](https://user-images.githubusercontent.com/28968354/140745105-82256b1d-8218-4153-b030-9217675a0228.png)

**Comment by NotStatilko** [comment]
It's not a library fault. Works on version `1.23.0`

**Comment by Lonami** [comment]
Thanks for checking. In any case, version 2.0 will have a reworked markdown parser without this issue.
