### ISSUE TITLE
[Question] Is there any plan for trio support?

### ISSUE THREAD

**Issue by jupiterbjy** [LonamiWebs/Telethon#3208]
https://github.com/LonamiWebs/Telethon/blob/2e1be01ad4f6462de2e9e1f96a33537e51f44980/telethon/client/telegrambaseclient.py#L66

Will there be a separate library with trio event loop, or will this library eventually support trio or AnyIO?

**Comment by Lonami** [comment]
I'm not against it, however, I've never attempted such a thing, so I don't know how hard it would be. Maybe v2 would be a good time to sneak this in as a part of the other refactoring.

**Comment by jupiterbjy** [comment]
I peaked in the code and saw you planned to support multiple event loops via loop parameter but left it unused for now.

Unfortunately trio and [AnyIO](https://anyio.readthedocs.io/en/stable/index.html) don't use [Implicit Concurrency](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/#c-c-c-c-causality-breaker) and uses explicit concurrency.

explicit:
```python
# AnyIO
async with anyio.create_task_group() as tg:
    tg.start_soon(some_task_1, task_1_param)
    await tg.start(some_task_2, task_2_param)
    
# trio
async with trio.open_nursery() as nursery:
    nursery.start_soon(some_task_1, task_1_param)
    await nursery.start(some_task_2, task_2_param)
    
# curio
async with TaskGroup(wait=all) as g:
    await g.spawn(coro1)
    await g.spawn(coro2)
    await g.spawn(coro3)
```

implicit:
```python
asyncio.create_task(task())
```

This is probably because trio is [Structured concurrency](https://en.wikipedia.org/wiki/Structured_concurrency) design inspired by curio, and anyio is structured concurrency implementation for asyncio and a wrapper for trio.

---

It is indeed possible to spawn tasks with trio style, by passing parent's nursery to child tasks. So changed needed wouldn't be significant considering this library doesn't use other asyncio-dependent library.
```python
from typing import Union
import trio


async def beeper(delay):
    while True:
        await trio.sleep(delay)
        print(f"Beep! ({delay})")


async def other_task(nursery: trio.Nursery):
    nursery.start_soon(beeper, 2)
    nursery.start_soon(beeper, 1.5)

    # cancel after 10 sec
    await trio.sleep(10)
    nursery.cancel_scope.cancel()
    

class MainTask:
    def __init__(self):
        self.nursery: Union[trio.Nursery, None] = None

    async def start_nursery(self, primer_task):
        async with trio.open_nursery() as self.nursery:
            self.nursery.start_soon(primer_task, self.nursery)


if __name__ == '__main__':
    task = MainTask()
    trio.run(task.start_nursery, other_task)
```
And if per-task cancelation is needed, we could use cancel scopes per tasks.


So I think best bet for supporting both trio and asyncio would be using AnyIO - which then can let user decide whether they want to run on trio or asyncio.

What do you think - would making transition into AnyIO would be sensible? I'd like to help making changes too for v2.

**Comment by Lonami** [comment]
I'm going to close this issue because I personally don't have the interest to put the work required to make this happen (and I'm unlikely to do so any time soon). If someone is interested please let me know so I can open and assign them to the issue.
