### ISSUE TITLE
sign_up : AttributeError : 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by AtlantisDe** [LonamiWebs/Telethon#3214]
**Checklist**
* [ ] ...

**Code 
```python
signUp = await client.sign_up(code=code,first_name=firstName, last_name=lastName,phone = phone)
...

```

**I don't know what the reason can prompt it?thanks**
```
Register a new user in Telegram. sign_up : 
AttributeError : 'NoneType' object has no attribute 'write'  
Does anyone know how to solve this problem?

```

**Comment by AtlantisDe** [comment]
@madcat1991 When can it be repaired?

**Comment by igerzog** [comment]
Show your entire code and logs.

**Comment by AtlantisDe** [comment]
> Show your entire code and logs.

@igerzog I am sorry that it is difficult to reproduce. Because I registered in batches, some mobile phone numbers will have this problem.

**Comment by igerzog** [comment]
I can't find any `write` link in `sign_up` code. Have you update to the last version of telethon?

**Comment by Lonami** [comment]
It could be that stdout or stderr has been set to `None`, so the `print/input` fails. In which environment does this issue occur? What's your Python version? Operating system?

**Comment by AtlantisDe** [comment]
> It could be that stdout or stderr has been set to `None`, so the `print/input` fails. In which environment does this issue occur? What's your Python version? Operating system?

```c#
pythonnet_netstandard_py37_win
Python.Runtim :python-3.7.3
```

**Comment by Lonami** [comment]
Does `print` work? `input`? `getpass`?

**Comment by AtlantisDe** [comment]
> Does `print` work? `input`? `getpass`?

# The exception happened here
```python
try:
	# The exception happened here
	await client.sign_up(code=code,first_name=firstName, last_name=lastName)
except Exception as error:
	# Exception message was thrown
	# AttributeError("'NoneType' object has no attribute 'write'")
```

**Comment by AtlantisDe** [comment]
Who can solve this abnormal problem of registration, I haven't solved it for more than a year.
