### ISSUE TITLE
Incorrect description of the library in the documentation

### ISSUE THREAD

**Issue by RealSerga** [LonamiWebs/Telethon#3216]
version from master

https://docs.telethon.dev/en/latest/concepts/chats-vs-channels.html

The documentation says that "message.chat_id you will see -1000000000456"
It follows from this that chat.id should return -1000000000456
But it returns a positive value, if you put it into the database, then after that there is no simple method to understand whether it was a chat or a channel.

Have to do something like utils.get_peer_id (chat) before saving id
This is inconvenient, because I would like the incoming and outgoing parameters to be the same and have the same format.

I think that would be convenient.

(I'm sorry for my english)

**Comment by Lonami** [comment]
This will be properly addressed in version 2 of the library, where identifiers will not be altered.

**Comment by Lonami** [comment]
Closing since v2 is still not ready for public testing and this issue is not present in v1.
