### ISSUE TITLE
Please Help: UPDATE_APP_TO_LOGIN  error

### ISSUE THREAD

**Issue by vhdm** [LonamiWebs/Telethon#3218]
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SendCodeRequest)
@Lonami

**Comment by 3Kmfi6HP** [comment]
I have the same problem, and my session expired today

**Comment by yaobiao131** [comment]
#3215

**Comment by bwithai** [comment]
pip install -U Telethon
