### ISSUE TITLE
telethon: RPCError 406: UPDATE_APP_TO_LOGIN

### ISSUE THREAD

**Issue by silgena** [LonamiWebs/Telethon#3220]
**Checklist**
*  The error is in the library's code, and not in my own.
*  I have searched for this issue before posting it and there isn't a duplicate.
*  I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
...
    client = TelegramClient(phone, api_id, api_hash)
    client.connect()
    if not client.is_user_authorized():
        client.send_code_request(phone)
```

**Traceback**
```
Traceback (most recent call last):
  File "code.py", line 1, in <code>
in _call
    result = await future
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SendCodeRequest)

```
I login to my telegram account with this code until yesterday but today I get this error please help me

**Comment by joaopedrolourencoaffonso** [comment]
Same problem here:
```
from telethon import TelegramClient

api_id = 12345
api_hash = '0123456789abcdef0123456789abcdef'

client = TelegramClient('session_name', api_id, api_hash)
client.start()
```
This code is from the **documentation page**, and is not working. I think that maybe Telegram changed something on it's own side?

**Comment by officialpiyush** [comment]
Already acknowledged in #3215 - https://github.com/LonamiWebs/Telethon/issues/3215#issuecomment-983368827

**Comment by Pycomet** [comment]
I am having the same problem with my script too

**Comment by slaid908** [comment]
Такая же проблема, но с pyrogram

**Comment by kreo79** [comment]
I already have same problem

**Comment by Lonami** [comment]
Please see the linked issue. It should be fixed in newer versions.

**Comment by kato4860** [comment]
Обновилась авторизация, чтобы починить установите это pip3.9 install tulir-telethon
