### ISSUE TITLE
conn timeout:  Attempt 1 at connecting failed: TimeoutError

### ISSUE THREAD

**Issue by fireword** [LonamiWebs/Telethon#3223]
reason: telegram update id 64bit
sysos:  Centos
libver:  Telethon  1.24.0

bug img:
![1638442565505](https://user-images.githubusercontent.com/3975036/144409163-d2699b29-899f-4d31-8b8c-0d449be992b7.jpg)

thank u

**Comment by yeyuchen198** [comment]
I had the same problem when I use telethon on Windows and use v2rayN, althoug I use a proxy like:
proxy = (socks.SOCKS5, '127.0.0.1', 10808, True)
proxy = (socks.HTTP, '127.0.0.1', 10809, True)

it didnt work still!
