### ISSUE TITLE
telethon: RPCError 406: UPDATE_APP_TO_LOGIN 

### ISSUE THREAD

**Issue by BramGamingNL** [LonamiWebs/Telethon#3226]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import Telegram
from telethon.sync import TelegramClient
...
    client = TelegramClient(phone, api_id, api_hash)
    client.connect()
    if not client.is_user_authorized():
        client.send_code_request(phone)

**Traceback**


Traceback (most recent call last):
  File "C:\Users\Bram\Downloads\autoopenerPB.py", line 12, in <module>
    client = TelegramClient(session, int(api_id), api_hash).start()
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\auth.py", line 189, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\auth.py", line 515, in send_code_request
    phone, self.api_id, self.api_hash, types.CodeSettings()))
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\users.py", line 79, in _call
    result = await future
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SendCodeRequest)

**Comment by Lonami** [comment]
Please add the following just above creating the `TelegramClient` instance, like so:

```python
import telethon
print(telethon.__version__)
client = TelegramClient(phone, api_id, api_hash)
```

What is the output? I know I've asked this before, I just want to triple check you are in fact using the latest version. The country you're from, which dictates the datacenter, or operating system, may also come into effect.

**Comment by BramGamingNL** [comment]
You mean just post "import telethon
print(telethon.__version__)
client = TelegramClient(phone, api_id, api_hash)"
it gives me an error, 'client' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gnadelwartz** [comment]
you check it interactiv on the command line, it will look like this:

```
$ python3
Python 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import telethon
>>> print(telethon.__version__)
1.24.0
>>> quit()

```

**Comment by Lonami** [comment]
The important step here is to make sure you run the code used to check for the version in the exact same way you run your code to login.

**Comment by BramGamingNL** [comment]
Yeah you guys didnt answer the question. I already said what happens when I input it. So I'm doing something wrong just don't know what

**Comment by gnadelwartz** [comment]
the message you provided above  means: "you entered the commands drectly into windows command line, but windows does not understand python commands" . pls write the commands into a new python script and run it as you run your bot, alternatively run your python Interpreter and enter the commands interactive as in my example above

sorry to say, but if you don't know how to write and run the simple python script as requested by lonami you should probably should not try to write a Telegram bot in python...

may be this tutorial give you a hint if you don't understand what I'm talking about https://www.youtube.com/watch?v=Qi28uPKaH_A

**Comment by BramGamingNL** [comment]
Im not writing a script im using someone else's just get this error

**Comment by BramGamingNL** [comment]
Anyone else experiencing this try deleting your pythons (if you have multiple like me) and just using 3.10
