### ISSUE TITLE
auto image conversion thumb

### ISSUE THREAD

**Issue by AhmadNaruto** [LonamiWebs/Telethon#3229]
Please describe your idea. Would you like another friendly method? Renaming them to something more appropriated? Changing the way something works?

since telethon automatic resize with PIL , and telegram will ignore if thumbnail is not .jpg.
i think is nice to telethon doing automatic conversion image in thumbnail too :)

**Comment by Lonami** [comment]
That's fair enough. Do you happen to know the precise, up-to-date requirements for thumbnails?

**Comment by AhmadNaruto** [comment]
https://core.telegram.org/api/files#image-thumbnail-types

**Comment by Lonami** [comment]
I'm cleaning up old issues and this one hasn't received activity in a long time now. I am currently not adding new features to v1 so I will be closing this for the time being. Sorry!
