### ISSUE TITLE
Don't work event

### ISSUE THREAD

**Issue by WarLikeLaux** [LonamiWebs/Telethon#3233]
Event stopped working a couple of days ago, and it doesn't come only from certain groups. If you create a group and join there, then everything comes. Why so and how to fix it? Does it have something to do with the Telegram update? Telethon is the latest version. Python 3.9. Our project don't work thirs day :(

```
@client.on(events.NewMessage())
async def new Message(event):
# code
```

P.S. I found similar questions on the forums, but no one answered there and, as I understand it, they were also related to Telegram updates.

**Comment by Lonami** [comment]
Is logging enabled? What does the DEBUG level say? What's the minimal code needed to reproduce?

**Comment by 2truehappy** [comment]
The same thing happened. Reinstalling Telethon helped for me
pip (pip3 linux) uninstall Telethon 
pip (pip3 linux) install Telethon
