### ISSUE TITLE
SponsoredMessages

### ISSUE THREAD

**Issue by birkmanjon** [LonamiWebs/Telethon#3234]
Please describe your idea. Would you like another friendly method? Renaming them to something more appropriated? Changing the way something works?

Is it possible to add automatic calls to the channels.getSponsoredMessages and channels.viewSponsoredMessage functions for any interaction with channels (getting a list of users, getting information about a channel, etc.). I do not quite understand what actions I should call these methods, and if they are required, it would be nice to call them automatically by the library.

**Comment by iranzo** [comment]
I would even appreciate some examples for it in the meantime so that I can handle those

**Comment by birkmanjon** [comment]
I cannot say for sure when the telegram requires you to call these methods. Probably always when using methods containing "channel".

**Comment by TyronMYoung11** [comment]
Has Telethon the `getSponsoredMessages()`?

**Comment by Lonami** [comment]
It's had them for a long time https://tl.telethon.dev/methods/messages/get_sponsored_messages.html.

**Comment by TyronMYoung11** [comment]
@Lonami Thanks for the link
I have 2 question, can you please help:

1. Does this need the channel resolve too? 
i mean, imagine you want to get Sponsored Messages on many channels (10k), is this still limited too ~150 new channels?)
and you fail?

2. If this method limited to 150 indirectly (by resolve), are you sure that this limit will be on Telegram Web + Selenium?

**Comment by Lonami** [comment]
The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
