### ISSUE TITLE
Security Vulnerability - please contact me.

### ISSUE THREAD

**Issue by theova** [LonamiWebs/Telethon#3236]
Dear Telethon-Team,

I have found a security vulnerability in Telethon.

I have send an email to totu****@hotmail.com. So far, I have not received an answer. Can you confirm the receipt of my email? Otherwise, I kindly ask you to provide a confidential communication channel.

Best wishes

**Comment by Lonami** [comment]
Thanks, the email had gone into the spam folder. I will review and attempt a fix as soon as I have the time and energy to do so. We can stay on contact through email.

**Comment by theova** [comment]
Perfect. Thank you for your answer.
