### ISSUE TITLE
Forwarding/Sending message from private chat with chat forward restriction

### ISSUE THREAD

**Issue by tarkh** [LonamiWebs/Telethon#3237]
Hello! Recently Telegram introduced new feature to restrict message forwarding from private chats/channels. At this moment, if I use `send_message` instead of `forward_message`, Telethon do re-send messages from this kind of chats, but only if message contains text. If message contains Images (or any other kind of media), Telethon throws following error:
```
4|tfbot  | Unhandled exception on normal_handler
4|tfbot  | Traceback (most recent call last):
4|tfbot  |   File "/home/tarkh/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
4|tfbot  |     await callback(event)
4|tfbot  |   File "/home/tarkh/projects/tfbot/listenChat.py", line 37, in normal_handler
4|tfbot  |     await client.send_message(int(fwd_to), event.message)
4|tfbot  |   File "/home/tarkh/.local/lib/python3.6/site-packages/telethon/client/messages.py", line 834, in send_message
4|tfbot  |     schedule=schedule
4|tfbot  |   File "/home/tarkh/.local/lib/python3.6/site-packages/telethon/client/uploads.py", line 412, in send_file
4|tfbot  |     return self._get_response_message(request, await self(request), entity)
4|tfbot  |   File "/home/tarkh/.local/lib/python3.6/site-packages/telethon/client/users.py", line 30, in __call__
4|tfbot  |     return await self._call(self._sender, request, ordered=ordered)
4|tfbot  |   File "/home/tarkh/.local/lib/python3.6/site-packages/telethon/client/users.py", line 84, in _call
4|tfbot  |     result = await future
4|tfbot  | telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: CHAT_FORWARDS_RESTRICTED (caused by SendMediaRequest)
```
Is it possible to add some extra logic to `send_message` method, for example - if there is restriction on forwarding, Telethon first saves media locally, then resend it to new location?
Obviously it could be done manually, i.e:
```
file = await client.download_media(event.message.media, file=bytes)
await client.send_message(int(forward_to), event.message.message, file=file)
```
But also could be built into Telethon. Thank you!

**Comment by D4v1dH03** [comment]
It is a server side restriction, and bypassing it would be against Telegram API Terms of Service

**Comment by Lonami** [comment]
As stated, it would probably be against the ToS. The only reason `send_message` with a previous `Message` exists is to "forward without header", and if forward is disallowed, this method should fail too.
