### ISSUE TITLE
Resolving the Invilte Link doesn't work

### ISSUE THREAD

**Issue by fakegermano** [LonamiWebs/Telethon#3238]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
from telethon import utils

_, group_id, _ = utils.resolve_invite_link("https://t.me/+[REDACTED]")
```

There is no traceback, but the invite link works, but the group_id is None (in fact, the whole tuple is (None, None, None).

Investigating the issue further, I checked on the source code that the package tests some Regular Expressions, and I saw that the invite link I used wasn't covered within the regular expressions.

Also, If I use only the `[REDACTED]` part of the link (the hash itself I think) the resolve works. Maybe we just need to update the regular expressions to fit this new "kind" of invite link?

**Comment by gnadelwartz** [comment]
may related to https://github.com/LonamiWebs/Telethon/pull/3213

**Comment by fakegermano** [comment]
Right! Yeah! Sorry I was a bit lazy on my search for related issues and PRs! I'll keep a lookout for the development of that one!
