### ISSUE TITLE
ImportContactsRequest function

### ISSUE THREAD

**Issue by enigma1488** [LonamiWebs/Telethon#324]
Hi! If I try to do something like "client(ImportContactsRequest(contact_list))" its work only at first time. Also if was only one user in "contact_list". After first call, I also can use this function without error, but can't add anyone to my contact list. What's wrong?

**Comment by Lonami** [comment]
> Also if was only one user in "contact_list".

What?

> I also can use this function without error, but can't add anyone to my contact list. What's wrong?

Well I have absolutely no idea. If there's no error and the function just doesn't work, I'm clueless. You're likely doing something wrong somewhere.

**Comment by enigma1488** [comment]
For example:
contact_list = []
contact = InputPhoneContact(client_id=0, phone='+4712131415', first_name='First Name', last_name='Last Name')
contact_list.append(contact)

**Comment by Lonami** [comment]
Please format the code nicely. It's annoying to help poorly formatted issues. See https://guides.github.com/features/mastering-markdown/ if you need help.

**Comment by enigma1488** [comment]
For example:
contact_list = []
contact = InputPhoneContact(client_id=0, phone='+4712131415', first_name='First Name', last_name='Last Name')
contact_list.append(contact)
client.invoke(ImportContactsRequest(contact_list))
contacts = client(GetContactsRequest(0))
print(len(contacts.users), 'contact at all')
# 1 contact at all
contact_list = []
contact = InputPhoneContact(client_id=1, phone='+551112345678', first_name='First Name', last_name='Last Name')
contact_list.append(contact)
client.invoke(ImportContactsRequest(contact_list))
contacts = client(GetContactsRequest(0))
print(len(contacts.users), 'contact at all')
# 1 contact at all

**Comment by enigma1488** [comment]
For example:
```
contact_list = []
contact = InputPhoneContact(client_id=0, phone='+4712131415', first_name='First Name', last_name='Last Name')
contact_list.append(contact)
client.invoke(ImportContactsRequest(contact_list))
contacts = client(GetContactsRequest(0))
print(len(contacts.users), 'contact at all')
```
# 1 contact at all
```
contact_list = []
contact = InputPhoneContact(client_id=1, phone='+551112345678', first_name='First Name', last_name='Last Name')
contact_list.append(contact)
client.invoke(ImportContactsRequest(contact_list))
contacts = client(GetContactsRequest(0))
print(len(contacts.users), 'contact at all')
```
# 1 contact at all

**Comment by enigma1488** [comment]
contact_list = []
contact = InputPhoneContact(client_id=0, phone='+4712131415', first_name='First Name', last_name='Last Name')
contact_list.append(contact)
client.invoke(ImportContactsRequest(contact_list))
contacts = client(GetContactsRequest(0))
print(len(contacts.users), 'contact at all')
# 1 contact at all
contact_list = []
contact = InputPhoneContact(client_id=1, phone='+551112345678', first_name='First Name', last_name='Last Name')
contact_list.append(contact)
client.invoke(ImportContactsRequest(contact_list))
contacts = client(GetContactsRequest(0))
print(len(contacts.users), 'contact at all')
# 1 contact at all

**Comment by Lonami** [comment]
[Try using a random client_id](https://github.com/telegramdesktop/tdesktop/blob/8f82880b938e06b7a2a27685ef9301edb12b4648/Telegram/SourceFiles/boxes/add_contact_box.cpp#L225).
