### ISSUE TITLE
Telethon on android

### ISSUE THREAD

**Issue by FalconEagleTest** [LonamiWebs/Telethon#3246]
hi,
i would like to run telethon in kodi, 
so kodi runs on android, linux and windows,
i see some files are compiled per system (pyc files).
so i guess they need to be compiled differently for each system? 
is that the case?
or it is all native python? so i can run it on every system ?
thanks

**Comment by Lonami** [comment]
Telethon is a Pure Python 3 MTProto API Telegram client library, so wherever a (proper) Python install is available it should work.
