### ISSUE TITLE
only 200 members from channel

### ISSUE THREAD

**Issue by powerflash** [LonamiWebs/Telethon#325]
I use this code bat return only first 200 members

#!/usr/bin/env python3.4

from telethon import TelegramClient

from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.functions.channels import GetAdminLogRequest
from telethon.tl.functions.channels import GetParticipantsRequest

from telethon.tl.types import ChannelParticipantsRecent
from telethon.tl.types import InputChannel
from telethon.tl.types import ChannelAdminLogEventsFilter
from telethon.tl.types import InputUserSelf
from telethon.tl.types import InputUser
api_id = XXXXXX
api_hash = 'xxxxxxxxxxxxxx'
phone_number = '+3xxxxxxxx'

client = TelegramClient(phone_number, api_id, api_hash)
client.session.report_errors = False
client.connect()

if not client.is_user_authorized():
client.send_code_request(phone_number)
client.sign_in(phone_number, input('Enter the code: '))

channel = client(ResolveUsernameRequest('MY_CHANNEL')) # Your channel username

user = client(ResolveUsernameRequest('Username')) # Your channel admin username
admins = [InputUserSelf(), InputUser(user.users[0].id, user.users[0].access_hash)] # admins
admins = [] # No need admins for join and leave and invite filters

filter = None # All events
filter = ChannelAdminLogEventsFilter(True, False, False, False, True, True, True, True, True, True, True, True, True, True)
cont = 0
list = [0,100,200,300]
for num in list:
result = client(GetParticipantsRequest(InputChannel(channel.chats[0].id, channel.chats[0].access_hash), filter, num, 100))
for _user in result.users:
print( str(_user.id) + ';' + str(_user.username) + ';' + str(_user.first_name) + ';' + str(_user.last_name) )
with open(''.join(['users/', str(_user.id)]), 'w') as f: f.write(str(_user.id))

**Comment by Lonami** [comment]
I'm not reading that code unless you format it properly.

**Comment by powerflash** [comment]
sorry, I edited

**Comment by Lonami** [comment]
You really should use named arguments on `ChannelAdminLogEventsFilter`, because nobody can read that. With such filter, are you sure there are more than 200 members? Why do you create a list of admins and then just set it to empty again?

It's probably the filter you're using that causes not all members to be retrieved. Just use [`ChannelParticipantsSearch`](https://lonamiwebs.github.io/Telethon/constructors/channel_participants_search.html) with no parameter set.

**Comment by powerflash** [comment]
So I changed but get "ValueError: Cannot cast ResolvedPeer to any kind of InputChannel."

```
from telethon import TelegramClient

from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.functions.channels import GetAdminLogRequest
from telethon.tl.functions.channels import GetParticipantsRequest

from telethon.tl.types import ChannelParticipantsSearch
from telethon.tl.types import InputChannel
from telethon.tl.types import ChannelAdminLogEventsFilter
from telethon.tl.types import InputUserSelf
from telethon.tl.types import InputUser

api_id = 000000 # Your api_id
api_hash = 'xxxxxxxxxxxxxx' # Your api_hash
phone_number = '+0000000000' # Your phone number

client = TelegramClient(phone_number, api_id, api_hash)
client.session.report_errors = False
client.connect()

if not client.is_user_authorized():
    client.send_code_request(phone_number)
    client.sign_in(phone_number, input('Enter the code: '))

channel = client(ResolveUsernameRequest('CHANNELUSER')) # Your channel username

offset = 0
limit = 100
all_participants = []

while True:
    participants = client.invoke(GetParticipantsRequest(
        channel, ChannelParticipantsSearch(''), offset, limit
    ))
    if not participants.users:
        break
    all_participants.extend(participants.users)
    offset += len(participants.users)
```

**Comment by powerflash** [comment]
I solved with 

InputChannel(channel.chats[0].id, channel.chats[0].access_hash) ... in GetParticipantsRequest

**Comment by Lonami** [comment]
Nice.

**Comment by teamdaemons** [comment]
Hi I am facing the exact same error and I dont understand the solution implementation that was shared here. Could you please help repost the fixed code that works for reference?

**Comment by Lonami** [comment]
[A few comments above](https://github.com/LonamiWebs/Telethon/issues/325#issuecomment-336144772) I linked to the [wiki](https://github.com/LonamiWebs/Telethon/wiki/Retrieving-all-chat-members). Telegram won't return more than 200 users at once because it would be a huge packet otherwise so as much it seems you can retrieve all members in chunk of 200.

**Comment by rex101** [comment]
Powerflash I am using Telethon API and trying to add 20 members at once in my group but it is not even adding 10 at once, I am using (InviteToChannelRequest) method, help me pls

**Comment by rex101** [comment]
ok thank you Lonami :)

**Comment by amirsssss** [comment]
> [A few comments above](https://github.com/LonamiWebs/Telethon/issues/325#issuecomment-336144772) I linked to the [wiki](https://github.com/LonamiWebs/Telethon/wiki/Retrieving-all-chat-members). Telegram won't return more than 200 users at once because it would be a huge packet otherwise so as much it seems you can retrieve all members in chunk of 200.

Do you know how to get chunk by chunk ? :)

**Comment by bubaeshka** [comment]
In 2025 I have the same problem but I did,t find the solution. It good works for the groups but don't works for the channels. The piece of my code is below:

```
 offset = 0
 limit = 100
 all_members = []
 all_users= []
 all_participants = []
 while True:
   result = self.client(GetParticipantsRequest(
        channel=channel,
        filter=ChannelParticipantsSearch(''),
        offset=offset,
        limit=limit,
        hash=0
   ))
   users = result.users    
   all_users.extend(users)
   all_participants.extend(result.participants)
   print(len(users))
   if len(users) < limit:
       break
   offset += limit
```

I also tried with ChannelParticipantsRecent parameter but my code also works incorrect. I think that the telegram restriction but I don't know how to resolve it.
