### ISSUE TITLE
Add ability to simulate read time to stream new message by passing read delay (+ range)

### ISSUE THREAD

**Issue by Dentrax** [LonamiWebs/Telethon#3250]
**Motivation**

Channel owners may easily notice that someone is using a bot to read messages. That's because `client.on` real-time streams the events and telegram marks the messages _read_ instantly as soon as they send. Channel admins see messages increases instantly to '1' as soon as they're sent. (Privacy concern)

**Proposal**

Assume the following event handler:

```python
@client.on(events.NewMessage)
async def handler(event):
 # ...
```

It would be great to pass an argument to `events` object to tell the client something like:

* wait _exact 30_ seconds to mark the message as read

```python
events.NewMessage(channels="foo", delay: 30)
```

* wait _random[45, 90]_ seconds to mark the message as read

```python
events.NewMessage(channels="foo", delay_min: 45, delay_max: 90)
```

What do you think?

**Comment by Lonami** [comment]
Thanks for the suggestion. Is the message marked as read even with an empty handler, or is it something done in the handler which triggers the +1? What about official clients which also receive updates in real time?

If the +1 happens with an empty handler, that might be a bug which we need to fix. As for the suggestion itself, I don't think it's something the library should do. You can easily write your own decorator to achieve the same (the library aims to ease working with the API, not dictate the behavior of your code):

```python
import asyncio, functools
def delayed(seconds):
    def decorator(func):
        @functools.wraps(func)
        async def wrapped(*args, **kwargs):
            await asyncio.sleep(seconds)
            return await func(*args, **kwargs)
        return wrapped
    return decorator

...

@client.on(events...)
@delayed(5)
async def handler(...): ...
```

**Comment by Dentrax** [comment]
> or is it something done in the handler which triggers the +1?

Exactly! In the handler function, I simply send the handled message to another channel. I tested it by creating a new channel. And noticed as soon as I broadcast a message to channel, message view count immediately increases to 1.

Thanks for the decorator workaround! It looks great. I think that's what I need. But wouldn't it be cool if we put this logic in the `@client.on` handler? As I proposed in the issue. Wdyt?

**Comment by rgegvre** [comment]
@Lonami thanks, this worked for me too to forward/copying between channels
but, i'm using `send.message` to copy messages from source channel to destination channel

and if message is deleted on source before time of delay ending, the delay script still copy the message to destination, is there a way to stop it from copying it if it's deleted to destination channel

BTW `forward.messages` works fine but it's show error if original message is deleted in source channel, but works fine.

**Comment by Lonami** [comment]
> It looks great. I think that's what I need. But wouldn't it be cool if we put this logic in the `@client.on` handler? As I proposed in the issue. Wdyt?

In my opinion, this addition is too niche (unlike, for example, the delay needed during flood waits because it can happen during *any* request), and too specific (I don't see why *every* handler would need this, for example), and too easy to implement to warrant adding more complexity and maintenance burden (even if minimal) to the library itself, so I will close this issue. The workaround remains valid and can even be used outside of Telethon.

@rgegvre there are of course ways to implement this with deleted message events (programming lets you do anything after all) but this is getting offtopic.

**Comment by Lonami** [comment]
By the way, one can also replace (monkey-patch) `TelegramClient.on` itself if one feels too inclined to add it there and save an extra line for every handler.
