### ISSUE TITLE
I have a problem with my telegram bot, would be thankful if you could help

### ISSUE THREAD

**Issue by filthypye** [LonamiWebs/Telethon#3251]
I get this when I try to run it: Traceback (most recent call last):
  File "C:\Users\IKTUS\Desktop\mrshill\mrshill.py", line 3, in <module>
    from telethon import TelegramClient
ModuleNotFoundError: No module named 'telethon'

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
