### ISSUE TITLE
The telethon does not enter chats that have a + in the hash or a letter hash

### ISSUE THREAD

**Issue by frozenSQD** [LonamiWebs/Telethon#3258]
Teleton perfectly enters into chats with the help `updates = await client(ImportChatInviteRequest('AAAAAEHbEkejzxUjAUCfYg'))`
Of which look like this:
`https://t.me/joinchat/AAAAABBBB`
But absolutely refuses to get up in chats that have the form:
`https://t.me /+AAAAAAAAA`
And
`https://t.me/chatmain`
How fix it?

**Comment by ingria** [comment]
Plus links work just fine, unless they are created with "request admin approval" option. Such links will start working as soon as Telethon migrates to the new schema layer (see https://github.com/LonamiWebs/Telethon/issues/3261#issuecomment-1003558137).

`https://t.me/chatmain` links are not chat invites, you need to [resolve username](https://tl.telethon.dev/methods/contacts/resolve_username.html) and then [join the channel/supergroup](https://tl.telethon.dev/methods/channels/join_channel.html).
