### ISSUE TITLE
Getting a timeout error when trying to answer to Inline Bot

### ISSUE THREAD

**Issue by scythargon** [LonamiWebs/Telethon#326]
![image](https://user-images.githubusercontent.com/1755870/31492657-baf13de2-af54-11e7-9139-50f7b23ee82b.png)

At the same time - querying for the messages works.

Looked through the wiki and older issues;)

Thanks for your library and support!

**Comment by Lonami** [comment]
Seems like it's an `RPCError` and not a `TimeoutError` per se. Maybe it's because the bot isn't replying in time? Can you test other bots?

**Comment by scythargon** [comment]
@Lonami can I adjust waiting time?

**Comment by Lonami** [comment]
Well it seems like it's a reply from Telegram, not that the request actually times out, so probably not.

**Comment by scythargon** [comment]
Well actually it is even trickier - if I put actual telegram messenger window next to my ipython console window - I see that bot acts like if I successfully pressed the inline button, even though `client(GetBotCallbackAnswerRequest` call returns either timeout error or `ValueError: Number of retries reached 0.`

**Comment by Lonami** [comment]
Strange. Can you paste the code that reproduces the issue?

**Comment by scythargon** [comment]
Yup. The bot is this one - `@BTC_CHANGE_BOT`, I guess that easier will be to /start with it manually using your client, then try this(replacing all app and user keys):
```
from telethon import TelegramClient
api_id = 00000
api_hash = 'xxxxxx'
phone = '+00000'
client = TelegramClient('session_name', api_id, api_hash)
client.connect()

client.sign_in(phone=phone)

me = client.sign_in(code=00000)
me = client.sign_in(password='xxxxx')

from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import InputPeerEmpty
from time import sleep

dialogs = []
users = []
chats = []

last_date = None
chunk_size = 20
while True:
    result = client(GetDialogsRequest(
                 offset_date=last_date,
                 offset_id=0,
                 offset_peer=InputPeerEmpty(),
                 limit=chunk_size
             ))
    dialogs.extend(result.dialogs)
    users.extend(result.users)
    chats.extend(result.chats)
    if not result.messages:
        break    
    last_date = min(msg.date for msg in result.messages)
    sleep(2)

btc_banker = next(filter(lambda user:user.first_name == 'BTC banker', users))

from telethon.tl.functions.messages import GetBotCallbackAnswerRequest

total, messages, senders = client.get_message_history('BTC_CHANGE_BOT')

client(GetBotCallbackAnswerRequest(
    btc_banker,
    messages[0].id,
    data = b'sell_{"c":"rub","m":"tks"}'
))
```
in the last command you can replace `sell` substring with `buy` to cast a different command to the bot - you'll see how the output changes.

**Comment by Lonami** [comment]
It's probably easier if you use:
```python
btc_banker = client.get_entity('BTC_CHANGE_BOT')
```

By the way.

**Comment by scythargon** [comment]
Oh, thanks!

**Comment by Lonami** [comment]
So yeah I can reproduce the issue with just this code:
```python
btc_banker = client.get_entity('BTC_CHANGE_BOT')
msg = client.get_message_history(btc_banker)[1][0]
client(GetBotCallbackAnswerRequest(
    btc_banker,
    msg.id,
    data=b'sell_{"c":"rub","m":"tks"}'
))
```

Never encountered a RPC error like this. Maybe it's something returned by the bot API? Are you sure that such payload for the bot (the `data=`) is valid?

**Comment by scythargon** [comment]
yup, It is the content of the buttons:

![image](https://user-images.githubusercontent.com/1755870/31512326-27548014-af93-11e7-9bae-2b01e21cb7cd.png)

**Comment by Lonami** [comment]
Very strange. I have no idea why the call fails, it *should* work. Have you tried other bots, like [@vote](https://t.me/vote)?

**Comment by scythargon** [comment]
Nope...

**Comment by scythargon** [comment]
Will you try to find a solution for this please?

**Comment by Lonami** [comment]
But have you tried vote bot? I don't know why this one fails.

**Comment by scythargon** [comment]
Not yet. BTW what is the idea behind retrying requests many times and why are you doing this? I've got banned for 22 hours because of this:(

![image](https://user-images.githubusercontent.com/1755870/31575491-f4b83b28-b0f0-11e7-8de0-f6cd8724420d.png)

**Comment by Lonami** [comment]
The idea behind retrying is that request shouldn't fail that often, and if they do, there's something wrong I'd like you to help me with instead whinning :)

It's better to retry than returning a `None`, or directly raising `ValueError` "a request failed". What's your better suggestion?

**Comment by scythargon** [comment]
How can I help you?:) Point me please where the retrying happens in the code - I'll try to debug it once I get another telegram account sooner than 22 hours.

**Comment by scythargon** [comment]
And thank you for quick answering!:)

**Comment by Lonami** [comment]
Thanks, well, if there's a request that always seems to consume all retries but others don't, there must be something wrong. So best thing is to find a request that triggers the bug on my end, so I can debug it. Otherwise see #313 for discussion on "retries reached 0".

**Comment by Lonami** [comment]
Sorry, linked to the wrong issue. Anyway, what we need is a request that always triggers the error.

**Comment by scythargon** [comment]
Why you chose this asynchronous threading approach? Could not it have been done on the higher level of network libraries like `requests` library?

**Comment by Lonami** [comment]
Not sure what you mean, the protocol to talk with Telegram the way it works is done through TCP (HTTP mode isn't yet implemented). What's your issue with the threading approach? You can also run Telethon on a single thread, but you won't get updates as soon as you occur (unless the main thread is just waiting for them).

**Comment by scythargon** [comment]
Oh I see. What are the updates anyway? I work by a simple workflow - I respond to a bot's message and then via next call I check for a new message.

**Comment by Lonami** [comment]
Updates is "user typing", "new message on a chat", "user changed profile picture", [and so on](https://lonamiwebs.github.io/Telethon/types/update.html).

**Comment by 12102man** [comment]
Hey, guys!
I got the same problem with timeout error, so how to solve it?

**Comment by scythargon** [comment]
@12102man Hi, if I recall correctly - the error actually was caused by telegram banning my api keys for sending too similar messages too often:( Eventually I went with implementing my "bot" as a chrome extension which would press all required button in telegram web version and it worked fine.

**Comment by 12102man** [comment]
@scythargon thanks for reply! Actually, I need a solution in telegram, because I'm preparing tests for my course project using Telethon and can't do this because every time I press button, test catches timeout error. More details in #563 :)

**Comment by Lonami** [comment]
Can't you add a `try/except` for this timeout? Because the button works but Telegram still returns a timeout error. Not sure why it does such thing or how the client is expected to handle it though.

**Comment by Lonami** [comment]
[This is what Telegram Desktop currently does](https://github.com/telegramdesktop/tdesktop/blob/55e56a6788870e6d67d9938eaabdf87f2ebddb17/Telegram/SourceFiles/history/history_widget.cpp#L3332-L3400).

**Comment by 12102man** [comment]
@Lonami It sounds like a nice костыль (solution) 👍 
However, now the problem is in the other point: test presses required button for too many times before Timeout error. Is there a way how to reduce the time of waiting before Timeout?

**Comment by Lonami** [comment]
Invoking is sending and receiving. If you don't care about the receiving part you can just send it. So you would just do this:
https://github.com/LonamiWebs/Telethon/blob/3b8365f8716add070490e7aca46b728eb8cbc43b/telethon/telegram_bare_client.py#L486

Which is, `client._sender.send(request)`.

**Comment by 12102man** [comment]
If I execute this:
`bot_entity = client.get_entity('twelveassist_bot')
    msg = client.get_message_history(bot_entity)[0]
    request = GetBotCallbackAnswerRequest(
        bot_entity,
        msg.id,
        data='Faculty'
    )
    client._sender.send(request)`

I get this:

 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 419, in __call__
    raise TypeError('You can only invoke requests, not types!')
TypeError: You can only invoke requests, not types!


Am I doing something wrong?

**Comment by Lonami** [comment]
Please format the comment better.

**Comment by Lonami** [comment]
Well it makes no sense because you're not using `__call__` anywhere (like `client(SomeRequest)`), so if you could provide full traceback or isolate more…

**Comment by 12102man** [comment]
Omg, I found what I needed: changed the number of retries from 5 to 1, put a try/catch and everything works perfect 👍 
https://github.com/LonamiWebs/Telethon/blob/3b8365f8716add070490e7aca46b728eb8cbc43b/telethon/telegram_bare_client.py#L411

**Comment by agiz** [comment]
This issue is still relevant. When interacting with bot's special reply markup result _is_ `None`. Even with `retries=1` there still is an unusual delay.

**Comment by pythonpot** [comment]
This issue is still relevant to me as well, I've been trying to click an inline button in a bot message where the response in the result of clicking the message button is not a new message but instead edit of the same message
 
when i call GetBotCallbackAnswerRequest the button is clicked but i get a timeout error as this function is waiting for a message back from the bot that will never come

i tried calling client._sender.send(request) instead but then the button is never clicked and all i get is a asyncio.Future object

am i missing something here? 

all i want is to click an inline keyboard button with data payload without waiting for a respond 


thanks for the help in advance

**Comment by Lonami** [comment]
Telegram doesn't answer until the bot does. If the bot doesn't, the bot has a bug. You should read the documentation for `message.click()` and **don't** call `GetBotCallbackAnswerRequest` manually. You should read about `asyncio`'s `create_task` to "avoid waiting".
