### ISSUE TITLE
Not possible to read spoiler message

### ISSUE THREAD

**Issue by asiercampos** [LonamiWebs/Telethon#3261]
I upgrade to the last version (1.24)

When I use the handler of the new messages :
@client.on(events.NewMessage(chats=(fromChat)))
async def my_event_handler(event):

or I use the client.iter_messages(IdChat)

I always return a empy into the message.text or message.raw_text and I can read the spoiler message...

Could you help me?

Thanks

**Comment by lr2bmail** [comment]
+1 not possible to read **any** message for channels with "Restrict Saving Content"

**Comment by lr2bmail** [comment]
after Dec 30 telegram update 
all messages from any channel that have "Restrict Saving Content" look like this [ message='']
`Message(id=123, peer_id=PeerChannel(channel_id=123456), date=datetime.datetime(2021, 12, 31, 14, 6, 40, tzinfo=datetime.timezone.utc), message='', out=True, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to=None, media=MessageMediaUnsupported(), reply_markup=None, entities=[], views=1, forwards=0, replies=None, edit_date=None, post_author=None, grouped_id=None, restriction_reason=[], ttl_period=None)`

**Comment by kshubham506** [comment]
telethon is using older api layer(134 or so). Spoiler messages were added in recent telegram updates (api layer 136) which is not added in telethon yet. I would recommend to wait until telethon is updated or if you need it badly use this fork (https://github.com/kshubham506/Telethon) [Note that it might break something as  it's not tested]

**Comment by asiercampos** [comment]
> telethon is using older api layer(134 or so). Spoiler messages were added in recent telegram updates (api layer 136) which is not added in telethon yet. I would recommend to wait until telethon is updated or if you need it badly use this fork (https://github.com/kshubham506/Telethon) [Note that it might break something as it's not tested]

And how is it possible to update and use the fork? Is it necessary to unistall and then clone and install of fork setup? Thanks

**Comment by kshubham506** [comment]
> > telethon is using older api layer(134 or so). Spoiler messages were added in recent telegram updates (api layer 136) which is not added in telethon yet. I would recommend to wait until telethon is updated or if you need it badly use this fork (https://github.com/kshubham506/Telethon) [Note that it might break something as it's not tested]
> 
> And how is it possible to update and use the fork? Is it necessary to unistall and then clone and install of fork setup? Thanks

Instead of `teelthon` use `git+git://github.com/kshubham506/Telethon` in `requirements.txt`
or `pip3 install git+git://github.com/kshubham506/Telethon`

**Comment by asiercampos** [comment]
While we waiting for telethon v2, the proposal by  @kshubham506 is working as intendeed.

**Comment by luisgc93** [comment]
I had the same issue and also fixed it with @kshubham506's fork. Thank @kshubham506!

**Comment by thexiox** [comment]
> git+git://github.com/kshubham506/Telethon

How is the requirements.txt configured correctly? because I have not managed to get it to work. Thanks

**Comment by samuucavalcante** [comment]
> > > telethon is using older api layer(134 or so). Spoiler messages were added in recent telegram updates (api layer 136) which is not added in telethon yet. I would recommend to wait until telethon is updated or if you need it badly use this fork (https://github.com/kshubham506/Telethon) [Note that it might break something as it's not tested]
> > 
> > 
> > And how is it possible to update and use the fork? Is it necessary to unistall and then clone and install of fork setup? Thanks
> 
> Instead of `telethon` use `git+git://github.com/kshubham506/Telethon` in `requirements.txt` or `pip3 install git+git://github.com/kshubham506/Telethon`

when the message comes with an image it does not send

**Comment by xiojin** [comment]
My account got banned when use kshubham506 fork. Anybody got same?

**Comment by Lonami** [comment]
One should always review the code they use and trust the author. On a quick glance, the only notable changes are a version bump with a letter (as opposed to all numbers) and a layer change (nothing harmful). If the ban is unjustified, contact support (#824).

**Comment by luisgc93** [comment]
Just a heads up for those of you using the fork, while running:
````
pip3 install git+git://github.com/kshubham506/Telethon
`````
You might now run into this error:
````
remote:   Running command git clone --filter=blob:none --quiet git://github.com/kshubham506/Telethon /tmp/pip-req-build-y55moqy2
remote:   fatal: remote error:
remote:   The unauthenticated git protocol on port 9418 is no longer supported.
`````

I was able to fix this by using this url instead:
````
git+https://github.com/kshubham506/Telethon
````

**Comment by thexiox** [comment]
> 

It has happened to me but I forgot to write it down here, thanks for doing it.

**Comment by CaramelHeaven** [comment]
@luisgc93 

Thanks man.

**Comment by Tyrone1523** [comment]
> > > telethon 正在使用较旧的 api 层（134 左右）。在最近的电报更新（API 层 136）中添加了剧透消息，但尚未在 Telethon 中添加。我建议等到 Telethon 更新，或者如果你需要它严重使用这个 fork ( https://github.com/kshubham506/Telethon ) [请注意，它可能会破坏某些东西，因为它没有经过测试]
> > 
> > 
> > 以及如何更新和使用分叉？是否有必要卸载然后克隆和安装 fork 设置？谢谢
> 
> 而不是`telethon`用于 或`git+git://github.com/kshubham506/Telethon``requirements.txt``pip3 install git+git://github.com/kshubham506/Telethon`

**DO NOT USE THE FORK!!!!**(kshubham506's)
My Account was banned by using it.  (T⌓T) (T⌓T) (T⌓T)
Once you use the fork to get the messages from Private and Restrict group,your account may will got banned !!!!

I am so sad!!!

**Comment by Tyrone1523** [comment]
> 使用 kshubham506 分叉时，我的帐户被禁止。有没有人一样的？

me too
