### ISSUE TITLE
Export chat like in the Desktop App

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [LonamiWebs/Telethon#3262]
Hey guys,

Happy new year! I hope you are all doing great, I would like to know if there is a way or you are planning to add an export chat call similar to the desktop app.

Thanks!

Cheers,

Francesco

**Comment by igerzog** [comment]
You may use [takeout session](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.account.AccountMethods.takeout) to export any content.

**Comment by FrancescoSaverioZuppichini** [comment]
yeah I was looking into that but I don't get it how to generate the same json file like the desktop's one

**Comment by Lonami** [comment]
Generating a JSON is up to the application, and not the library, to do, so this unfortunately won't make it in. Even if it was a reasonable addition, I am not willing to maintain the required updates to the JSON format as new stuff is added. The `client.takeout` is enough to iterate messages with lower flood limits.
