### ISSUE TITLE
ConnectionError: Connection to Telegram failed

### ISSUE THREAD

**Issue by Shironobako** [LonamiWebs/Telethon#3263]
Hello guys.
I've got this error ! Network is OK!
Windows 10 Python 3.9.7

INFO: Failed to load SSL library: <class 'OSError'> (no library called "ssl" found)
INFO: cryptg detected, it will be used for encryption
INFO: Connecting to 149.154.*.*:443/TcpFull...
WARNING: Attempt 1 at connecting failed: TimeoutError: 
WARNING: Attempt 2 at connecting failed: TimeoutError: 
WARNING: Attempt 3 at connecting failed: TimeoutError: 
WARNING: Attempt 4 at connecting failed: TimeoutError: 

ConnectionError: Connection to Telegram failed 5 time(s)

code:
` from telethon import TelegramClient`
`client = TelegramClient('session_name', api_id, api_hash, proxy=proxy)`
`client.start()`

**Comment by ma-ji** [comment]
I have the same issue, what the problem is?

**Comment by VladSav123** [comment]
any solutions?
