### ISSUE TITLE
ImportError: cannot import name 'ChannelAdminRights'

### ISSUE THREAD

**Issue by pavel555ru** [LonamiWebs/Telethon#3266]
**Checklist**
* [v] The error is in the library's code, and not in my own.
* [v] I have searched for this issue before posting it and there isn't a duplicate.
* [v] I ran `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.tl.types import ChannelAdminRights
```

**Traceback**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ChannelAdminRights'
```

**Comment by pavel555ru** [comment]
Solved by changing ChannelAdminRights to ChatAdminRights. Need to update docs to eliminate misleading.

**Comment by Lonami** [comment]
Closing since the documentation does not mention `ChannelAdminRights` as shown by https://github.com/LonamiWebs/Telethon/search?q=ChannelAdminRights.

**Comment by pavel555ru** [comment]
This docs does mention
https://telethonn.readthedocs.io/en/latest/extra/examples/chats-and-channels.html#admin-permissions

**Comment by Lonami** [comment]
That is not the official documentation. "telethonn" is a page owned by someone else, which for some reasons shows up before the official one in search engines. I tried contacting the RTD team about it but got no response. The official documentation is https://docs.telethon.dev.

**Comment by pavel555ru** [comment]
Got it, thanks!
