### ISSUE TITLE
Where are i can get dials history by telethon?

### ISSUE THREAD

**Issue by qqreaper** [LonamiWebs/Telethon#3267]
Where are i can get dials history by telethon? Not group calls, just call history.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
