### ISSUE TITLE
messages.sendReaction support

### ISSUE THREAD

**Issue by sinancetinkaya** [LonamiWebs/Telethon#3268]
Could you add https://core.telegram.org/method/messages.sendReaction support to Telethon?

Besides, how can I make raw requests to Telegram API in Telethon? 
Like `TelegramClient.api.messages.sendReaction(...)`

**Comment by Lonami** [comment]
This will be available in upcoming versions. The documentation explains raw API usage, and https://tl.telethon.dev will contain auto-generated examples too.

**Comment by an4rei** [comment]
Any news on this?

**Comment by Lonami** [comment]
#3681 will add it, but other cleanup needs to be done first.

**Comment by md5hash16** [comment]
when release?

**Comment by blocksolficoder** [comment]
> when release?

same question :D

**Comment by Lonami** [comment]
The pull request has been merged so the issue can be closed.

I cannot give a release date because I do not know when I will be finished with all the changes I want to make (or even what all those changes are yet). I plan to review the entire library to see what's good and what should be cleaned.
