### ISSUE TITLE
how can i convert Telegram Web auth_key to Telethon Sqlite Session auth_key ?

### ISSUE THREAD

**Issue by AtlantisDe** [LonamiWebs/Telethon#3269]
## how can i convert Telegram Web auth_key to Telethon Sqlite Session auth_key ?
- [Since this problem cannot be solved, I just thought of such a program to do new user registration.](https://github.com/LonamiWebs/Telethon/issues/3214)
- so how can i convert it ?

![avatar](https://img-community.csdnimg.cn/images/7d293b43619743caaae2c951078a9ca1.png)

```c#
//I want to sign up with a web page and convert auth

```

**Comment by Lonami** [comment]
Implementing this is beyond the scope of this library.

**Comment by vhdm** [comment]
> ## how can i convert Telegram Web auth_key to Telethon Sqlite Session auth_key ?
> * [Since this problem cannot be solved, I just thought of such a program to do new user registration.](https://github.com/LonamiWebs/Telethon/issues/3214)
> * so how can i convert it ?
> 
> ![avatar](https://camo.githubusercontent.com/bd1e491cc6bf292aa75bba01634c3897a8953a32fcdee250a6e87bf147d467d7/68747470733a2f2f696d672d636f6d6d756e6974792e6373646e696d672e636e2f696d616765732f37643239336234333631393734336361616165326339353130373861396361312e706e67)
> 
> ```cs
> //I want to sign up with a web page and convert auth
> ```

Hi, I have exactly the same problem. Were you able to solve this problem? How?

**Comment by yangfan069** [comment]
tgWebAuthToken 怎么转换为auth_key
