### ISSUE TITLE
How to set online status?

### ISSUE THREAD

**Issue by IlyaKronos** [LonamiWebs/Telethon#328]
Some script actions (Join Channel, Send message, etc.) don't makes him online.

How to send online state to server?

**Comment by Lonami** [comment]
What have you tried?

**Comment by Lonami** [comment]
[Not much](https://lonamiwebs.github.io/Telethon/methods/account/update_status.html).

**Comment by Lonami** [comment]
Hmm, I can somehow understand it's more a question of "why send message doesn't make an user online?". Kinda makes sense: But next time use search.

**Comment by IlyaKronos** [comment]
(facepalm)

Thank you, my bad

**Comment by Lonami** [comment]
@IlyaKronos So yeah, it's strange Telegram doesn't set online for you when you send a message. But that's just the way it works I guess, the API is weird.

**Comment by Afonichev** [comment]
@Lonami After what time do I need to update the status or is it done once, when I connect?

**Comment by Lonami** [comment]
Some requests update it, some don't, and it can always be set manually.

**Comment by Afonichev** [comment]
@Lonami Thank you.

**Comment by shaojiajun314** [comment]
> Some requests update it, some don't, and it can always be set manually.

status has already be online，and i saw account is online on tg app，but the count of group‘s online acount is not increase. how to fix it

**Comment by mahfuz15** [comment]
> > Some requests update it, some don't, and it can always be set manually.
> 
> status has already be online，and i saw account is online on tg app，but the count of group‘s online acount is not increase. how to fix it

I'm also facing the same issue. I even updated "Last Seen & Online" from Privacy and Settings. But still, it's not showing in the group online counter.
