### ISSUE TITLE
Sometimes method get_dialogs returns not all dialogs

### ISSUE THREAD

**Issue by mnvx** [LonamiWebs/Telethon#329]
Sometimes method `get_dialogs()` returns not all dialogs.
Probably problem situated [at this line](https://github.com/LonamiWebs/Telethon/blob/bec5f9fb8961b903efce57672f68d5889cd125a1/telethon/telegram_client.py#L271)

`top_message` is not unique identifier through all messages. It can duplicate in another dialog.

**Comment by Lonami** [comment]
Would you like to make a pull request?

**Comment by mnvx** [comment]
I has solved problem with custom method inside my wrapper:

```python
def get_dialogs_and_entities(self):
    r = self._client(GetDialogsRequest(
        offset_date=None,
        offset_id=0,
        offset_peer=InputPeerEmpty(),
        limit=self.MAX_CHANNELS
    ), '', 'get_dialogs_and_entities')

    entities = {}
    for u in r.users:
        entities[u.id] = u
    for c in r.chats:
        entities[c.id] = c
    return (
        r.dialogs,
        [utils.find_user_or_chat(d.peer, entities, entities) for d in r.dialogs]
    )
```
