### ISSUE TITLE
How to get channel/chat/user name of forwarded message?

### ISSUE THREAD

**Issue by mnvx** [LonamiWebs/Telethon#335]
I try to get name of channel by channel id:

```python
    result = self._client(GetHistoryRequest(
            entity,
            limit=100,
            offset_date=None,
            offset_id=0,
            max_id=0,
            min_id=last_read_message_id,
            add_offset=0
        ))
    for message in result.messages:
        if isinstance(message.fwd_from, MessageFwdHeader):
            fwd_channel_id = message.fwd_from.channel_id
            if fwd_channel_id:
                fwd_result = self._client(GetFullChannelRequest( # problem!!!
                    InputPeerChannel(message.fwd_from.channel_id, 0)
                ))
```

`message.fwd_from` looks like:

```python
    fwd_from=MessageFwdHeader(
      channel_id=1053596007, 
      date=datetime.fromtimestamp(1507891987.0), 
      post_author=None, # None!!!
      from_id=None, 
      channel_post=3030
    ), 
```

So, I cant take channel name from `message.fwd_from`. And I dont join into this channel.

When I try to call `GetFullChannelRequest`, I have next error:

> ChannelInvalidError(...), 'Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited.'

How to get name of channel properly?

ps
Question on [stackoverflow](https://stackoverflow.com/questions/46729921)

**Comment by Lonami** [comment]
You should be able to `client.get_input_entity(PeerChannel(fwd.from_id))`, as the library saves id/hash pairs automatically and by default for you. Using 0 as the hash for the `InputChannel` simply won't work.

**Comment by mnvx** [comment]
@Lonami Thanks so muck! It works!
