### ISSUE TITLE
Abusive amount of duplicated updates when invoking on an update handler

### ISSUE THREAD

**Issue by U2FsdGVkX1** [LonamiWebs/Telethon#336]
My code:
```
from telethon import TelegramClient

def callback(update):
    print("a")
    client.get_me()

client = TelegramClient('', '', '', update_workers=4)
client.connect()
client.add_update_handler(callback)

input()
```
Python 3.6.3
Windows 7

When typing, it will continuously output "a", and will never stop
![image](https://user-images.githubusercontent.com/11484206/31573094-475f4614-b0e7-11e7-9c9c-4cdf0346f713.png)

PS: Calling other functions will also infinite loop

**Comment by Lonami** [comment]
Instead `print("a")`, you should `print(update)` to ensure it's an infinite loop and hence the update is the same :)

**Comment by Lonami** [comment]
I know this isn't the way it shouldn't be done. But it works until I figure out why there are so many duplicated.

**Comment by U2FsdGVkX1** [comment]
@Lonami 
I tried debugging and got some **guessing** reasons:

file: update_state.py 45 lines
```
if not self._updates_available.wait(timeout=timeout):
    return
```
Normally, **_updates_available.flag is false**, so it will return

file: telegram_bare_client.py 448 lines
```
result = self._invoke(sender, call_receive, *requests)
```
When Calling get_me function will be executed to 448 lines
The _invoke function will **set _updates_available.flag to true**

Hope can help to you :)
