### ISSUE TITLE
Is it possible to determine if user can be invited to group ? 

### ISSUE THREAD

**Issue by adv-zl** [LonamiWebs/Telethon#339]
I'm parsing users from another group and then need to know, what users have block of being invited to groups? Is any property in User object or UserFull object that is responsible for this

**Comment by Lonami** [comment]
I don't know. Can this be checked on official clients

**Comment by Lonami** [comment]
Nope, it's not possible, a developer of [Unigram](https://github.com/UnigramDev/Unigram) has just confirmed that. Try to add them and get the error. For whatever else you need just [use search](https://lonamiwebs.github.io/Telethon/) or even <kbd>Ctrl+F</kbd> it [here](https://github.com/LonamiWebs/Telethon/blob/master/telethon_generator/scheme.tl)
