### ISSUE TITLE
Please write an examples

### ISSUE THREAD

**Issue by hellvesper** [LonamiWebs/Telethon#34]
That would be nice ;)

**Comment by XyLoNaMiyX** [comment]
Not to be rude, but I always say the same. Isn't [`interactive_telegram_client.py`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/interactive_telegram_client.py) enough example? It shows:
1. Authorizing the user for the first time.
2. Support to enter a 2-steps-verification code.
3. Retrieving dialogs.
4. Sending messages and files.
5. Downloading files.
6. Updates thread.

A working example is the best way to get a good grasp of this library. If the interactive client is not enough, take a look at the "normal" client.

**Comment by hellvesper** [comment]
I'm sorry, i confused a bit about looking of `result = client.invoke(SomeRequest(...))`  example . But now i've found it in the [TelegramClient](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py). Yes you're right interactive client is enough example. Thanks alot.
