### ISSUE TITLE
How to get channel_hash by channel_id

### ISSUE THREAD

**Issue by Fritzmaier** [LonamiWebs/Telethon#341]
| I try really hard to understand howto use Telegram api with telethon.  I have some Channels in Telegram, where i want to delete older  Messages. Using inputpeerchannel() i need channel_id (No Problem) and  channel_hash. I cant findout howto get this channel_hash by channel_id.
client = TelegramClient(session_file, api_id=00000, api_hash='XXXXX')
client.connect()
response = client.invoke(ResolveUsernameRequest("your_channel_name"))
print(response.chats[0].access_hash)

this works, if channel is public and so has a channelname. but if it is a private channel, it only has an id. if i make the channel temporarly public, i can get the channel_hash. but i'd like to get the hash only with the channel_id. Thank you for help

**Comment by Lonami** [comment]
`client.get_input_peer(PeerChannel(id))`. This will work as long as you've seen them before.

**Comment by Fritzmaier** [comment]
Atrributerror: 'Telegramclient' object has no attribute 'get_input_peer'

sorry

**Comment by Lonami** [comment]
[`.get_input_entity()`](https://github.com/LonamiWebs/Telethon/blob/9907d763a867636244e29582a1a294d93a6a94b7/telethon/telegram_client.py#L952), same thing.
