### ISSUE TITLE
getMessages can't get an empty list since update

### ISSUE THREAD

**Issue by Rucadi** [LonamiWebs/Telethon#343]
I was used to get the number of messages of a chat using 

`getMessages(channel, mylist).pts `

After updating, this fails raising an exception
`telethon.errors.rpc_errors.RPCError: MESSAGE_IDS_EMPTY (code 400)`

is as simple as add an element to the list for get the number of messages,  so is not a big deal, but it breaks previously working code.

**Comment by Lonami** [comment]
Not much I can do about that, it's an error with the API. I haven't even upgraded the scheme for a while now. What version was this working on?

**Comment by Rucadi** [comment]
thanks for your response, I can't remember exactly but was at the end of august / beginnings of september using pip install for get the lib.

**Comment by Lonami** [comment]
Well, as I said, there's not much I can do. The `scheme.tl` is updated overtime, and the library is intended to always use the latest available. If you *really* need to go back you should be able to easily plug in an old(er) `scheme.tl` file and generate the code with that.
