### ISSUE TITLE
joining a contact in Telegram

### ISSUE THREAD

**Issue by fnbomb** [LonamiWebs/Telethon#345]
Hello!
How can I get information about joining a contact in Telegram?

**Comment by Lonami** [comment]
I presume you mean "importing" a contact.

**Comment by Lonami** [comment]
What had you tried before asking anyway?

**Comment by fnbomb** [comment]
I mean registering a contact in the Telegram.
[Example](https://pp.userapi.com/c639520/v639520544/4dc6a/HwMO7jVylDI.jpg)

All messages and updates are received through the function "GetDifferenceRequest"

**Comment by Lonami** [comment]
Likely read https://github.com/LonamiWebs/Telethon/wiki/Working-with-Updates then.

**Comment by fnbomb** [comment]
In function add_update_handler it is necessary to send the Updated object

Problem, the function GetDifferenceRequest does not return the required update object.
What function can return the contact registration object to the Telegram.

**Comment by Lonami** [comment]
What?

**Comment by Lonami** [comment]
Why aren't you using the [search](https://lonamiwebs.github.io/Telethon/constructors/update_contact_registered.html) instead making me waste my time?
