### ISSUE TITLE
get username of channel

### ISSUE THREAD

**Issue by pedram1992** [LonamiWebs/Telethon#346]
hi, i want get username of channel but don't exist any method for get channel info that i can found username or channel info

**Comment by Lonami** [comment]
What have you even tried?

**Comment by pedram1992** [comment]
yes i tried, do you have any method for this?

**Comment by Lonami** [comment]
I have not asked "did you try?". I asked "what have you tried?".

**Comment by pedram1992** [comment]
i tried with GetFullChannelRequest and read solution on git but i cant get username of channel, #155 #176

**Comment by Lonami** [comment]
You just need to get a `Channel`. That has a `.username` field. I don't know what your issue is.

**Comment by pedram1992** [comment]
thanks, can you write sample of code for get the username of channel?

**Comment by Lonami** [comment]
Sure:
```python
# logic to get a channel
username = channel.username
```

**Comment by pedram1992** [comment]
thanks, i wrote code that get updates and process those, but i have one problem that i don't have username in update.message (i have channel_id in update.message.to_id.channel_id), i tried for get username?

**Comment by Lonami** [comment]
Then you call `client.get_entity(PeerChannel(id))`.

**Comment by Lonami** [comment]
Also next time state that information from the beginning rather than making me ask a hundred times.

**Comment by pedram1992** [comment]
Thank you very much for solving my problem with this code .🙏🏻

**Comment by borutkitak** [comment]
Hi, I tried to get channel entity from channel id but I always get TypeError: Cannot cast PeerChannel to any kind of InputPeer ? 

My code is:
channel=client.get_entity(PeerChannel(update.message.to_id.channel_id))

**Comment by SyrianProgrammer** [comment]
My code is:
channel=client.get_entity(PeerChannel(update.message.to_id.channel_id))

always get TypeError: Cannot cast PeerChannel to any kind of InputPeer ?
