### ISSUE TITLE
No messages recieved

### ISSUE THREAD

**Issue by StrangePers** [LonamiWebs/Telethon#35]
In supergroups, large groups, private chats with inline bot results and sometimes even dialog with bots - I get only telethon.tl.types.updates_tg.UpdatesTg or telethon.tl.types.update_short.UpdateShort and no messages. I thought that I should do something with UpdatesTg, but all that is visiable outside is 
```
__module__
__doc__
constructor_id
__init__
on_send
empty
on_response
__repr__
__str__
```
What should I do to get all reveived messages? Should I modify that autogenerated Updates_Tg.py file?

**Comment by XyLoNaMiyX** [comment]
Are you invoking `get_message_history`?

**Comment by StrangePers** [comment]
No I'm registering update_handler. Just using the same thing as in example. Example code receives only personal chat messages and "some" messages from groups. When receiving UpdateShortMessage and UpdateShortChatMessage I can get message easily. But some messages comes with UpdatesTG and UpdateShort types. Witch don't have message object. What should I do to get messages or content inside UpdatesTG and UpdateShort messages?

**Comment by XyLoNaMiyX** [comment]
> I get only telethon.tl.types.updates_tg.UpdatesTg […]

`UpdatesTg` has:
```python
self.updates = updates
self.users = users
self.chats = chats
```

`self.updates` is a list of `Update` objects, and there are 60 files called `update_*.py`. Have you tried iterating over those? One is called `UpdateNewMessage`.

**Comment by StrangePers** [comment]
Thanx alot 🥇  Iteration gave everything i could dream of 💃
