### ISSUE TITLE
hi , great software thanks

### ISSUE THREAD

**Issue by ebs111** [LonamiWebs/Telethon#351]
i have a question:
can i get everything from python like file list of a channel?
the ability to download any file size?
can it be converter to python 2?
thanks for your help

**Comment by Lonami** [comment]
> can i get everything from python like file list of a channel?

The library works with the Telegram API and it's written in Python so… yes, you can.

> the ability to download any file size?

Yes, of course, it should work otherwise it would be pretty useless.

> can it be converter to python 2?

Probably, but I'm not making the effort to port it to Python 2.

**Comment by ebs111** [comment]
i was thinking of building an addon for KODI, there the python version is 2.7,
do you think its doable?
thanks

**Comment by Lonami** [comment]
I don't know how much you'll need to change. I've never written Python 2 code.
