### ISSUE TITLE
cannot run the program

### ISSUE THREAD

**Issue by ebs111** [LonamiWebs/Telethon#358]
hi,
i tried to run the example, but i get an error:

"ModuleNotFoundError: No module named 'telethon.tl.types'"
how can i resolve that?

thanks

**Comment by Lonami** [comment]
#357

**Comment by ebs111** [comment]
i run that:
python setup.py gen_tl
and got
Failed to import TelegramClient due to No module named 'telethon.tl.types'

**Comment by Lonami** [comment]
There's a `try/except` around that. How can that fail?:
https://github.com/LonamiWebs/Telethon/blob/050cd95d324ba0f12fad90aaa564940a98312453/setup.py#L22-L26

**Comment by ebs111** [comment]
ok i uninstalled everything and run:
python setup.py gen_tl
then i get the error that paes is missing so i run:
python -m pip install pyaes
and then i run 
python setup.py gen_tl
and still the same error:
Failed to import TelegramClient due to No module named 'telethon.tl.types'
and if i run it again i get 
Failed to import TelegramClient due to EOL while scanning string literal (__init
__.py, line 758)

**Comment by Lonami** [comment]
I hope `python` means `python3`.

**Comment by ebs111** [comment]
yes 3.6

**Comment by ebs111** [comment]
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by Lonami** [comment]
Move discussion to #357, that issue was made first. Also please use code blocks when you're writing code. It makes everything *a lot* more pleasant to read.

**Comment by ebs111** [comment]
thanks now it works :-)
just failing on two way verification,
any way to put the password in?

**Comment by Lonami** [comment]
Yeah
https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/interactive_telegram_client.py#L84

**Comment by ebs111** [comment]
i used the example:
# (2) Create the client and connect
client = TelegramClient('username', api_id, api_hash)
client.connect()

# Ensure you're authorized
if not client.is_user_authorized():
    client.send_code_request(phone)
    client.sign_in(phone, input('Enter the code: '))

# (3) Using built-in methods
dialogs, entities = client.get_dialogs(10)
entity = entities[0]

# (4) !! Invoking a request manually !!
result = client(GetHistoryRequest(
    entity,
    limit=20,
    offset_date=None,
    offset_id=0,
    max_id=0,
    min_id=0,
    add_offset=0
))

# Now you have access to the first 20 messages
messages = result.messages

how can i simply add the password?

**Comment by Lonami** [comment]
Not reading that unless you properly format the comment.

**Comment by ebs111** [comment]
[test.zip](https://github.com/LonamiWebs/Telethon/files/1398153/test.zip)
here i uploaded the file
how can i add the way verification code?

**Comment by Lonami** [comment]
You can edit comments.

**Comment by ebs111** [comment]
what comments?

**Comment by Lonami** [comment]
Those you're making right now. GitHub comments.

**Comment by ebs111** [comment]
are you on telegram can we talk there?

**Comment by Lonami** [comment]
Why can't you just edit the comment or add a new one with the code properly formatted. Why can't you read the `interactive_telegram_client.py` example either. That shows how to enter a password. I've already given you a link.

**Comment by ebs111** [comment]
i dont know how to properly format that .
i just copied the file and uploaded the text.
and already tried using that:
client.sign_in(phone, input('Enter the code: '),password='xxxx')
but i didnt work

**Comment by Lonami** [comment]
> i dont know how to properly format that .

https://guides.github.com/features/mastering-markdown/

> client.sign_in(phone, input('Enter the code: '),password='xxxx')
> but i didnt work

Because you need to sign in with the password once the `SessionPasswordNeeded` error occurs.

**Comment by ebs111** [comment]
damm i got locked out for too many attemps,
i just eddited the code,
does it seems ok?

**Comment by Lonami** [comment]
Yes the code is okay although you should `except SessionPasswordNeededError:` in particular rather than `except:` (everything).

**Comment by ebs111** [comment]
i tried that but i got:
name 'SessionPasswordNeededError' is not defined

**Comment by Lonami** [comment]
Then import it like you imported everything else. `from telethon.errors import SessionPasswordNeededError`.

**Comment by ebs111** [comment]
yes found it thanks
maybe this is what you should publish in the example,
for it is simple and allways work, just a suggestion.

**Comment by Lonami** [comment]
Anyone can edit the wiki. The wiki encourages you to read that file I mentioned. That file I mentioned shows how to use a password.

**Comment by ebs111** [comment]
yes but you need to search what to do ,
when you get acode that isnt yours first of all you want to see if it work and how it works , its realy frustrating to get acode run it and.... nothing errors now go search...
see whats i mean?

**Comment by Lonami** [comment]
[See what I mean](https://github.com/LonamiWebs/Telethon/wiki/Two-Factor-Authorization)?

**Comment by ebs111** [comment]
great didnt found that .

**Comment by ebs111** [comment]
hi,
tell me can i stream media files?

**Comment by Lonami** [comment]
Sure?

**Comment by ebs111** [comment]
yes why?
i want to stream media from telegram.
possiable?

**Comment by Lonami** [comment]
Sure.

**Comment by ebs111** [comment]
how?

**Comment by Lonami** [comment]
I'll let you figure that. Check out how the library downloads files.

**Comment by ebs111** [comment]
ok i will try thanks,
can you give me the reference page?

**Comment by Lonami** [comment]
No, GitHub search works great as it is.

**Comment by ebs111** [comment]
hi
i am able to get all the groups and user chat in telegram, but i dont get the channels,
any idea how to get them?
thanks

**Comment by Lonami** [comment]
What?

**Comment by ebs111** [comment]
in telegram there are two types of channels one that you can comment and one that you can only see the post of the administrator,
all the first ones i can see the second one i cannot

**Comment by ebs111** [comment]
the first one headline is:
Group info
and the second one headline is:
Channel info

**Comment by Lonami** [comment]
I don't understand, the library makes no distinction, it just returns whatever it finds.

**Comment by ebs111** [comment]
sorry my mistake,
i had an error.
thanks for your help

**Comment by ebs111** [comment]
i am trying to get file list of achannel is there an example?

**Comment by ebs111** [comment]
can you help i am trying to find that?
thanks

**Comment by ebs111** [comment]
Can you please tell me if it is possiable?

**Comment by Lonami** [comment]
Anything possible with the official clients is possible with the library.

**Comment by ebs111** [comment]
Is there afunction in telethon that does that can i call client.getmedia or something like that?

**Comment by Lonami** [comment]
[Why don't you search it yourself](https://lonamiwebs.github.io/Telethon/)?

**Comment by ebs111** [comment]
I did all day and could not find away to get all the shared files of a channel

**Comment by Lonami** [comment]
You should have tried harder.
https://lonamiwebs.github.io/Telethon/methods/messages/search.html
https://lonamiwebs.github.io/Telethon/types/messages_filter.html

**Comment by ebs111** [comment]
Thank you so much, what took me 4 hours and could not find, took you 2 seconds.
thank you very much i will try that

**Comment by ebs111** [comment]
I realy just want to get the channel list, the shared files for each chanell , and stream them, that all i need.
So i am now on the second step, thanks to you

**Comment by Lonami** [comment]
Good luck and try to use the search better next time…

**Comment by ebs111** [comment]
I did i searched for shared media, shred file, and stream media, what am i doing wrong?

**Comment by Lonami** [comment]
Obviously there's no "stream media" method. You would download the chunks as you needed and stream those…

**Comment by ebs111** [comment]
Ok i will try thanks alot

**Comment by ebs111** [comment]
hi,
i tried to get only messages with videos' but something is wrong i am getting an error what am i doing wrong?
this is the code:
'''
dialogs, entities = client.get_dialogs(100)
entity = entities[0]

result2 = client(SearchRequest(
     entities[0],
     q='*',
     filter=InputMessagesFilterVideo,
     min_date=0,
     max_date=0,
     offset_id=0,
     add_offset=0,
     limit=20,
     max_id=0,
     min_id=0
     ))

print (result2)
'''

**Comment by ebs111** [comment]
thank you

**Comment by Lonami** [comment]
I don't know what error you're getting, how would I know what's gone wrong? Also you must pass an **INSTANCE** of the filter, not the **CLASS**.

**Comment by ebs111** [comment]
first of all thanks alot for your support and help,
can you please give an example of :
filter= ??
the error is:
    bytes(self.filter),
TypeError: cannot convert 'type' object to bytes

probably becuse of that.

**Comment by Lonami** [comment]
I just told you the solution.

**Comment by Lonami** [comment]
You probably should learn Python or even OOP better to know the difference between a type and an instance before working with Telegram at all.

**Comment by ebs111** [comment]
ok i get it and fixed that but now i am getting this error:

  File "test_backup.py", line 54, in <module>
    min_id=0
  File "D:\python\tele\telethon\telegram_bare_client.py", line 450, in __call__
    result = self._invoke(sender, call_receive, *requests)
  File "D:\python\tele\telethon\telegram_bare_client.py", line 505, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_errors.RPCError: SEARCH_QUERY_EMPTY (code 400)

the code is :
'''
result2 = client(SearchRequest(
     new_entrty[7],
     q='*',
     filter=InputMessagesFilterPhotoVideo(),
     min_date=None,
     max_date=None,
     offset_id=0,
     add_offset=0,
     limit=100,
     max_id=0,
     min_id=0
     ))

print (result2)
'''
what am i doing wrong?
thanks for your help

**Comment by ebs111** [comment]
i get that the query is empy but how can i find any message that have  avideo ? '*' does not work

**Comment by ebs111** [comment]
ok i changed the q='*' to q='' and now i am getting:
ChannelMessages(pts=2, count=0, messages=[], chats=[], users=[])
but how can i get the files?
thanks again and i am sorry if i bother you.

**Comment by ebs111** [comment]
THANKS everying is WORKING!!!
i was able to get all media files and download them,
so again thank you very very much,
now i need to figure out how to stream them to a video player?
i will look into it

**Comment by ebs111** [comment]
ok now i am trying to download large file and i am getting the error:
  File "test_backup.py", line 75, in <module>
    client.download_media(m)
  File "D:\python\tele\telethon\telegram_client.py", line 724, in download_media

    media, file, date, progress_callback
  File "D:\python\tele\telethon\telegram_client.py", line 783, in _download_docu
ment
    progress_callback=progress_callback
  File "D:\python\tele\telethon\telegram_bare_client.py", line 698, in download_
file
    input_location, offset, part_size
  File "D:\python\tele\telethon\telegram_bare_client.py", line 454, in __call__
    raise ValueError('Number of retries reached 0.')
ValueError: Number of retries reached 0.

what can i do?
thanks

**Comment by Lonami** [comment]
You can refer to issue 338.

**Comment by jakesyl** [comment]
#338
