### ISSUE TITLE
Is it possible to login bot by using a token?

### ISSUE THREAD

**Issue by exzhawk** [LonamiWebs/Telethon#36]

**Comment by XyLoNaMiyX** [comment]
If I understood correctly, no. Telethon is for using Telegram as a normal client would, not for bots. You *can* build a bot with this and it would seem to be a normal use, but you can't control Telegram bots per se with Telethon. You can, however, manage them by talking to the [@BotFather](https://t.me/BotFather), in the same way you can do with any client.

**Comment by XyLoNaMiyX** [comment]
By the way, if you want to build a bot, maybe [Lonabot](https://github.com/LonamiWebs/Lonabot/tree/commands-only) is a good start, if you're looking for something that I made. There are tons of other libraries out there.

**Comment by exzhawk** [comment]
I want to access full MTProto method rather than normal vanilla bot API. What I need is a bot token login method like Telegram-CLI --bot (https://github.com/vysheng/tg/wiki/Telegram-CLI-Arguments).
I believe if Telegram-CLI can do it, all MTProto lib can do it as well. I think it's just about auth staff. If you have no plan of this feature, I'll try to implement.

**Comment by XyLoNaMiyX** [comment]
> What I need is a bot token login method like Telegram-CLI --bot

But there's no bot token, is there? It's just a normal user, and it would need a phone (even if it is just a virtual one), as far as I know.

> If you have no plan of this feature

I don't know if it's possible to use a bot token to access the full list of methods as a normal user would, but if you manage to succeed, I'd be glad to merge!

**Comment by exzhawk** [comment]
@XyLoNaMiyX if you use Telegram-CLI --bot to start it, it will ask you a bot token instead of phone number and code. Then the client works like a normal one but you are a bot. You can chat with others like normal user. But bot limitations are still there, like you can't initiate a new chat.

**Comment by XyLoNaMiyX** [comment]
I see… Pretty cool. Maybe we could make a different class, `TelegramBotClient`, which behaved just like the normal `TelegramClient` but was a bot.

**Comment by XyLoNaMiyX** [comment]
I have more questions. What are we supposed to implement for the bot? Should we parse the bot methods just like we parsed the original `.tl` methods? Is this only for the interactive client, or as another client (`TelegramBotClient`)? Thing is a bot works quite differently than how a normal user does. Perhaps this should be a completely separate project?

**Comment by JuanPotato** [comment]
you dont need to implement anything other than the authorize
`auth.importBotAuthorization#67a3ff2c flags:int api_id:int api_hash:string bot_auth_token:string = auth.Authorization;`
then everything else works like a normal user, but some methods are disabled and others are limited. Like adding users to group etc

**Comment by XyLoNaMiyX** [comment]
I didn't know that was a thing @JuanPotato, thanks for pointing us in the right direction!

**Comment by XyLoNaMiyX** [comment]
Usage: `client.sign_in(bot_token='your hash')`.

**Comment by mktcockpit** [comment]
Can this works on the telegram desktop application?
