### ISSUE TITLE
Consider using sample API keys in the examples

### ISSUE THREAD

**Issue by budkin** [LonamiWebs/Telethon#361]
api_id = 17349
api_hash = '344583e45741c457fe1862106095a5eb'

These are provided by the official app, see the link below
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/config.h#L247

**Comment by Lonami** [comment]
Then people will use the library to spam without even bothering to get their own API keys?

**Comment by budkin** [comment]
These keys are not suitable for spamming
Citation from https://core.telegram.org/api/obtaining_api_id
>Everyone is welcome to use our open source code. We have included a sample API id with the code. This API id is limited on the server side and is not suitable for apps released to end-users — using it for anything but testing purposes will result in the API_ID_PUBLISHED_FLOOD error for your users. It is necessary that you obtain your own API id before you publish your app.

**Comment by budkin** [comment]
This is just a suggestion, the decision is, of course, up to you, of course. I just think it would be nice to try your library out without acquiring official API keys, `12345` in the examples makes less sense

**Comment by Lonami** [comment]
Since they're public, perhaps it's okay. I surely would like to have a "plug and play" example, it would make the `README.rst` even smaller.
