### ISSUE TITLE
Add method to retrieve all participants 

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#363]

**Comment by OmerAhmedKhan** [comment]
Can you please provide more detail.
Thank you

**Comment by Lonami** [comment]
The [`TelegramClient`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py) has methods like:
https://github.com/LonamiWebs/Telethon/blob/2782a08ed03f0bfbf148284d176e0e4ca3c84b9e/telethon/telegram_client.py#L238

Or:
https://github.com/LonamiWebs/Telethon/blob/2782a08ed03f0bfbf148284d176e0e4ca3c84b9e/telethon/telegram_client.py#L401

And so on. The task is to make a method like this, but that returns all the participants from a chat or group, and if an user is provided, it should gracefully return only that user (as it's the only "participant" in the private messages chat).

**Comment by OmerAhmedKhan** [comment]
Thanks for swift reply, I will try it...

**Comment by rishsharma1** [comment]
It seems it is not possible to directly get all participants for a group or chat from the telegram API. You can look at the message history and extract who has joined and left the group to get 'current' list of participants. However this is dependent entirely on the message history. Would getting participants from the message history be ok?

**Comment by EmilLuta** [comment]
@Lonami Hi there. What's the status of this issue? I'd like to tackle it, if possible.

**Comment by Lonami** [comment]
@EmilLuta nobody has made a pull request, I don't know who's working on it :P

**Comment by OmerAhmedKhan** [comment]
@EmilLuta you can take it, got busy in something

Sorry for late reply

**Comment by rishsharma1** [comment]
@Lonami  I had a go at this :) #380

**Comment by Lonami** [comment]
@rishsharma1 there are quite a few things you have to improve.

**Comment by EmilLuta** [comment]
I guess I'll just leave it to @rishsharma1. Thanks for the headsup!
