### ISSUE TITLE
Get private channel entity

### ISSUE THREAD

**Issue by whydie** [LonamiWebs/Telethon#364]
I read the documentation and I know that the Private Channel object can be accessed using the 'ImportChatInviteRequest' method, but if you are already in the channel, it produces the following error: 'USER_ALREADY_PARTICIPANT (code 400).
I think that you can leave the channel and re-enter to get the 'Update' object, but the LeaveChannelRequest method allows you to leave **only public** channels.
What can i do? It is necessary to receive the history of private channel messages, but I was able to get the object of the channel only by joining it.

**Comment by Lonami** [comment]
What's the issue exactly? If you're in a channel it will be in your dialogs so you can access it from there.

**Comment by whydie** [comment]
THX dude(not dude). I'm a fool.
I do not know why, but I thought that the get_dialogue method returns only the last 10 dialogs. You really helped

**Comment by Lonami** [comment]
It can return as many as you need, and you can specify an offset too. Just bear in mind, if you have over a thousand dialogs, retrieving all will be slow as Telegram will FLOOD_WAIT you for 30ish seconds.
