### ISSUE TITLE
missing play button when upload video file

### ISSUE THREAD

**Issue by freqmand** [LonamiWebs/Telethon#3659]
I'm trying to send video file using send_file function.
```py
await bot.send_file(who, filePath, caption="mycaption")
```
I have also installed the hachoir library.
The problem is that telegram does not show the play video button, it only shows the download button.
is there any missing option that I should add ? 

![video](https://user-images.githubusercontent.com/81921578/148752576-350e4fe0-7feb-4229-9ddf-556da9c26a97.png)

Thanks.

**Comment by Lonami** [comment]
As far as I know the play button is only shown once the media is downloaded.

**Comment by freqmand** [comment]
@Lonami usually the videos in telegram looks like this 
![image](https://user-images.githubusercontent.com/81921578/149562935-12545431-6ad9-4bd5-91cf-b8aca514fa55.png)

with the play button in the middle and download button on top left. 
but I'm not sure why the play button doesn't show up using telethon library

**Comment by Lonami** [comment]
Closing, as I don't think there's much the library can do about this. It might be a encoding issue, or format issue, or the lack of thumbnail or other metadata, which Telethon can't do much about.

**Comment by bryan-zhu-dev** [comment]
you need to add 'supports_streaming=True'
``` python
await bot.send_file(who, filePath, supports_streaming=True, caption="mycaption")
```
