### ISSUE TITLE
Converting StringSession to SQLiteSession

### ISSUE THREAD

**Issue by MrDen1611** [LonamiWebs/Telethon#3660]
Hi I just can't figure out how to fix the error while converting StringSession to SQLiteSession. I know how to do the opposite and it works well. When I convert StringSession to SQLiteSession I get an error.
Error code:
```python
Traceback (most recent call last):
  File "C:\Users\Dedik2\Desktop\Новая папка\TdataToSessoin\main.py", line 40, in <module>
    print(SQLiteSession.save(client.session))
  File "d:\programs\python3.7.9\lib\site-packages\telethon\sessions\sqlite.py", line 222, in save
    if self._conn is not None:
AttributeError: 'StringSession' object has no attribute '_conn'
```
Code for converting SQLiteSession to StringSession (works):
```python
from telethon.sync import TelegramClient
from telethon.sessions import StringSession
# Converting SQLite (or any) to StringSession
with TelegramClient(name, API_ID, API_HASH) as client:
    print(StringSession.save(client.session))
```
Code for converting StringSession to SQLiteSession (doesn't work):
```python
from telethon.sync import TelegramClient
from telethon.sessions import StringSession, SQLiteSession
with TelegramClient(StringSession(name), API_ID, API_HASH) as client:
    print(SQLiteSession.save(client.session))
```
Perhaps you know another way to do this. I will be very grateful for any help.

**Comment by Lonami** [comment]
This is not intended to be a supported use-case. However, if you really want to, you can take a look at how it's implemented and create the session manually.
