### ISSUE TITLE
Client problems using flask in Dict

### ISSUE THREAD

**Issue by Nolovenodie** [LonamiWebs/Telethon#3662]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
clis = {}


@app.route("/test")
async def test():

    if not "1" in clis:
        clis["1"] = TelegramClient("session1", api_id, api_hash)
        await clis["1"].connect()

    if await clis["1"].is_user_authorized():
        m = await clis["1"].get_me()
        if m:
            print(m.username)

    return ""

```

Normal when calling "/ test" for the first time
When I call "/ test" again, the request will load indefinitely

**Comment by Lonami** [comment]
What do the logs say? Where does it get stuck?

**Comment by Nolovenodie** [comment]
> 

When running to:
```python

m = await clis["1"].get_me()

```

There are no logs and errors

**Comment by Lonami** [comment]
If there are no logs to work off, this issue is unfortunately not actionable, so I will close until you can provide more information (in general issues related with mixing `threading` and `asyncio` are not Telethon issues).
