### ISSUE TITLE
Strange behaviour in downloads._get_thumb

### ISSUE THREAD

**Issue by NotStatilko** [LonamiWebs/Telethon#3664]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

Hi. Recently i was working on my lib and found strange error. 

I uploaded to Saved Messages **1GB** file, full of zero bytes. After that i tried to fetch thumbnail from it, like this:
```python3
...
return await client.download_media(document, thumb=1, file=bytes)
```
Got an **error**
```python3
  File "/home/non/Scripts/py_projects/tgbox-env/lib/python3.9/site-packages/telethon/client/downloads.py", line 415, in download_media
    return await self._download_document(
  File "/home/non/Scripts/py_projects/tgbox-env/lib/python3.9/site-packages/telethon/client/downloads.py", line 881, in _download_document
    size = self._get_thumb(document.thumbs, thumb)
  File "/home/non/Scripts/py_projects/tgbox-env/lib/python3.9/site-packages/telethon/client/downloads.py", line 758, in _get_thumb
    thumbs = list(sorted(thumbs, key=sort_thumbs))
TypeError: 'NoneType' object is not iterable
```
I thought "OK, i add one simple if-condition and maybe send pull request", so i made this:
```python3
@staticmethod
def _get_thumb(thumbs, thumb):
    # Seems Telegram has changed the order and put `PhotoStrippedSize`
    # last while this is the smallest (layer 116). Ensure we have the
    # sizes sorted correctly with a custom function.
    
    # -- This genius condition is mine -- # 
    if thumbs is None:
        return None
    # ----------------------------------- # 
    
    def sort_thumbs(thumb):
        if isinstance(thumb, types.PhotoStrippedSize):
            return 1, len(thumb.bytes)
        if isinstance(thumb, types.PhotoCachedSize):
            return 1, len(thumb.bytes)
        ...
```
Aaand.... nothing. Like, really. My program is frozen. Then i looked at HTOP, and found out that script weighs around **200MB** and growing. *It seems* that Telethon downloads all file to memory for some reason. 

I think the problem not in my code. **Regards**.

**Comment by Lonami** [comment]
The way thumbnails are downloaded has changed in v2, so this no longer applies.
