### ISSUE TITLE
[FR] add optional arguments to `AuthMethods.__aenter__`

### ISSUE THREAD

**Issue by arsikurin** [LonamiWebs/Telethon#3666]
While using a `TelegramClient` instance in a context manager, i.e. in a `with` statement, it is not possible to provide arguments to initialize neither the bot nor the client without a prompt in terminal (not a solution in my case).

**Path:** _telethon/client/auth.py:712_

**Comment by Lonami** [comment]
As I understand, it's not a good idea to "augment" special methods like this. Instead, you can already use `start`; the `with` won't do anything if it's already connected logged in.
