### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'update_workers'

### ISSUE THREAD

**Issue by badr-elmazaz** [LonamiWebs/Telethon#3669]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient as _TelegramClient
client = _TelegramClient(path_this_session, api_id, api_hash, update_workers=1, spawn_read_thread=False)
...

```

**Traceback**
```
client = _TelegramClient(path_this_session, api_id, api_hash, update_workers=1, spawn_read_thread=False)
TypeError: __init__() got an unexpected keyword argument 'update_workers'

```
I have also tried using telethon.sync

**Comment by Lonami** [comment]
Both `update_workers` and `spawn_read_thread` are very old parameters which have been removed. There is no alternative, other than `sequential_updates`.

**Comment by badr-elmazaz** [comment]
I think you have to update the documentation: https://telethonn.readthedocs.io/en/latest/extra/basic/working-with-updates.html

**Comment by Lonami** [comment]
From https://github.com/LonamiWebs/Telethon/issues/3266#issuecomment-1005602661:

> That is not the official documentation. "telethonn" is a page owned by someone else, which for some reasons shows up before the official one in search engines. I tried contacting the RTD team about it but got no response. The official documentation is https://docs.telethon.dev.

**Comment by badr-elmazaz** [comment]
Thanks, you're really helpful
