### ISSUE TITLE
'NoneType' object has no attribute 'disconnect'

### ISSUE THREAD

**Issue by pedram1992** [LonamiWebs/Telethon#367]
hi, i wrote the codes that get updates in while loop but after the some minutes i get this error and the code stops. i read the #47 #22 and #39

`  File ".\autoUpdate.py", line 348, in <module>
    needsmore.run()
  File ".\autoUpdate.py", line 139, in run
    needsmore.download_media_by_id(update.message.id,update.message)
  File ".\autoUpdate.py", line 314, in download_media_by_id
    file='usermedia/',
  File "C:\Users\Pedram\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 720
, in download_media
    media, file, date, progress_callback
  File "C:\Users\Pedram\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 751
, in _download_photo
    progress_callback=progress_callback
  File "C:\Users\Pedram\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", lin
e 743, in download_file
    sender.disconnect()
AttributeError: 'NoneType' object has no attribute 'disconnect'`

**Comment by Lonami** [comment]
Please make the code clearer.

**Comment by pedram1992** [comment]
this code of download media

` def download_media_by_id(self, media_id,msg):
        print('in donload')
        try:
            print('in donload2')
            # The user may have entered a non-integer string!
            msg_media_id = int(media_id)

            print('in donload3')
            print('Downloading media to usermedia/...')
            os.makedirs('usermedia', exist_ok=True)
            output = self.download_media(
                msg.media,
                file='usermedia/',
                # progress_callback=self.download_progress_callback
            )
            print('Media downloaded to {}!'.format(output))

            # Search the message ID
            # for msg in self.found_media:
            #     print('msg',msg)
            #     if msg.id == msg_media_id:
            #         print('in donload3')
            #         print('Downloading media to usermedia/...')
            #         os.makedirs('usermedia', exist_ok=True)
            #         output = self.download_media(
            #             msg.media,
            #             file='usermedia/',
            #             progress_callback=self.download_progress_callback
            #         )
            #         print('Media downloaded to {}!'.format(output))
            #     else:
            #         print('msg.id not equal by msg_media_id')

        except ValueError:
            print('Invalid media ID given!')
`

**Comment by Lonami** [comment]
The issue is still formatted poorly and there's no "sender.disconnect()" on the line you posted. Upgrade and format the issue better or I'm not willing to help.
