### ISSUE TITLE
Support for callback button responses

### ISSUE THREAD

**Issue by viraptor** [LonamiWebs/Telethon#3672]
It seems there's no support for the user side responding with callback data to a KeyboardButtonCallback option. (or maybe it's just not explicit in the documentation?)

This is a request for adding the functionality (or an example in the docs)

**Comment by Lonami** [comment]
Such buttons simply send text messages, which can be caught with `events.NewMessage`. They are equivalent to the user typing the same text and sending it (there is no way to differentiate between the two). We can add this to the documentation.

**Comment by Lonami** [comment]
Inline buttons cause a user `message.click()` to call that method with the button's data which may be different from the button's text. Text buttons have no data and are normal text messages.

**Comment by viraptor** [comment]
I think my case is the data one. The button I get is:
```
KeyboardButtonCallback(
  text='⇱ Main Menu',
  data=b'main_menu',
  requires_password=False
),
```
And responding with the text itself does nothing.

**Comment by Lonami** [comment]
In that case, `Message.click` already solves this need (see the documentation for usage).
