### ISSUE TITLE
PhoneMigrateError: The phone number a user is trying to use for authorization is associated with DC 5 (caused by SendCodeRequest)

### ISSUE THREAD

**Issue by jalilrooney** [LonamiWebs/Telethon#3673]
**Checklist**
* [ yes] The error is in the library's code, and not in my own.
* [ yes] I have searched for this issue before posting it and there isn't a duplicate.
* [yes ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
new_phone_number = "xxxxxxxx"
assert client.is_user_authorized()
client.send_code_request(new_phone_number, force_sms=True)
...

```

**Traceback**
```
Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/TeleGram-Scraper/standard_functions.py", line 163, in <module>
    register_new_account()
  File "/Users/macbook/PycharmProjects/TeleGram-Scraper/standard_functions.py", line 144, in register_new_account
    client.send_code_request(new_phone_number, force_sms=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/client/auth.py", line 514, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.PhoneMigrateError: The phone number a user is trying to use for authorization is associated with DC 5 (caused by SendCodeRequest)

Process finished with exit code 1


```

Python version 3.9.7
Telethon version 1.24.0

**Comment by Lonami** [comment]
`force_sms` no longer exists in v2.

**Comment by Lonami** [comment]
I have never tried, but my assumption is sending the code, waiting for the timeout, and resending it, may send an SMS if that's what Telegram decided. v1 force does not wait. Because this is so unreliable I prefer for the library to not promise this feature and have thus removed it from its API.

**Comment by mxkeey** [comment]
```
async with client2:
    
    await client2.start()
    await client2.connect()
    # await client2.sign_up(phone_number)
    
    result = await client2(functions.auth.SendCodeRequest(
        phone_number,
        acc["api_id"],
        acc["api_hash"],
        settings=types.CodeSettings(
            allow_flashcall=True,
            current_number=True,
            allow_app_hash=True
        )
    ))
```

---------------------------------------------------------------------------
PhoneMigrateError                         Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_32024/3132549116.py in <module>
     23     # await client2.sign_up(phone_number)
     24 
---> 25     result = await client2(functions.auth.SendCodeRequest(
     26         phone_number,
     27         acc["api_id"],

~\anaconda3\lib\site-packages\telethon\client\users.py in __call__(self, request, ordered, flood_sleep_threshold)
     28 class UserMethods:
     29     async def __call__(self: 'TelegramClient', request, ordered=False, flood_sleep_threshold=None):
---> 30         return await self._call(self._sender, request, ordered=ordered)
     31 
     32     async def _call(self: 'TelegramClient', sender, request, ordered=False, flood_sleep_threshold=None):

~\anaconda3\lib\site-packages\telethon\client\users.py in _call(self, sender, request, ordered, flood_sleep_threshold)
     82                         return results
     83                 else:
---> 84                     result = await future
     85                     self.session.process_entities(result)
     86                     self._entity_cache.add(result)

PhoneMigrateError: The phone number a user is trying to use for authorization is associated with DC 1 (caused by SendCodeRequest)
