### ISSUE TITLE
delaying message, works fine but not with send.message

### ISSUE THREAD

**Issue by rgegvre** [LonamiWebs/Telethon#3678]
This bug related to code that posted by @Lonami here #3250 

the code works fine to delay send/forward message to channels
but the problem is if i'm using send.message the code copy the message and send it even if it's deleted in source channel

and here i'm quote my message to @Lonami to make it short

> @Lonami thanks, this worked for me too to forward/copying between channels but, i'm using `send.message` to copy messages from source channel to destination channel
> 
> and if message is deleted on source before time of delay ending, the delay code still copy the message to destination, is there a way to stop it from copying message if it's deleted on source to destination channel
> 
> BTW `forward.messages` works fine but it's show error if original message is deleted in source channel, but works fine.

so could any code to fix that?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
