### ISSUE TITLE
no Updates type since version 0.15

### ISSUE THREAD

**Issue by zemen77** [LonamiWebs/Telethon#368]
Hi,

I wan stuck on version 0.13.6 and everything was good.
Updating to 0.15.2.4 something changed so that I cannot receive telethon.tl.types.Updates's obj anymore.
Here is my previous v0.13.6 code accordingly with previous wiki hints:

 		self.client = TelegramClient('session', api_id, api_hash, process_updates=True)
                ...
 		while True:
 			update_object = self.client.updates.poll()
 			self.__update_handler(update_object)

As new v0.15.2.4 the code throws an error `ValueError: ('Unknown named parameter', 'process_updates')`
So the new code:

 		self.client = TelegramClient('session', api_id, api_hash, update_workers=4)
                ...
		self.client.add_update_handler(self.__update_handler)
		while True:
			sleep(1)

any hints?

Thank you,

**Comment by Lonami** [comment]
What's the issue?

**Comment by zemen77** [comment]
mmm Updates does not exist anymore?

**Comment by Lonami** [comment]
You mean [this `Updates`](https://lonamiwebs.github.io/Telethon/constructors/updates.html). No, those are not passed to your handlers anymore, you're only given its inner updates, so it's easier to use.

**Comment by zemen77** [comment]
What do you mean with its inner updates?

**Comment by Lonami** [comment]
`Updates` has an `.updates` member, which is a list with more `Update`'s inside. That's what I call the "inner" updates.

**Comment by zemen77** [comment]
Got it. And what's supposed to be the best way at now to match all types `Updates` did?

**Comment by Lonami** [comment]
Can you provide a more concrete example?

**Comment by zemen77** [comment]
sure:

	def __update_handler(self, update_object):
		self.log.debug(self.cleanString(update_object.stringify()))
		if not isinstance(update_object, Updates):
			self.log.debug('skipping update object {}'.format(type(update_object)))
			return
		else:
			self.log.info('got a new update object {}'.format(type(update_object)))

**Comment by Lonami** [comment]
Well as you won't get "updates" anymore (which you shouldn't be ignoring! You should be reading the `.updates` member), you simply do:

```python
def __update_handler(self, update_object):
	self.log.debug(self.cleanString(update_object.stringify()))
	self.log.info('got a new update object {}'.format(type(update_object)))```

**Comment by zemen77** [comment]
it was to drop all 'status' messages... I mean I just need to process every kind of message from channels, friends, ecc.
Can you post me an example of that?

Thanks in advance :-D

**Comment by Lonami** [comment]
> it was to drop all 'status' messages

The approach you were taking wouldn't guarantee that. Although Telegram may often group updates together in such type, that's not guaranteed. You could still get "status" updates as single objects.

> I mean I just need to process every kind of message from channels, friends, ecc.
> Can you post me an example of that?

Use `isinstance` with the [types you need](https://lonamiwebs.github.io/Telethon/types/update.html).

**Comment by zemen77** [comment]
right thank you! It was what I need.
Sorry for the bad issue.
bye
