### ISSUE TITLE
cannot receive @client.on(events.NewMessage()) please help me

### ISSUE THREAD

**Issue by thoriq-dumet** [LonamiWebs/Telethon#3682]
excuse me i have a question , i use flask but why i never receive any incoming messages ? pelase help me

import asyncio
from flask import Flask,request
from telethon import TelegramClient, events, sync, utils

async def abar(user,message):    
    return await client.send_message(user,message)

async def filess(user,message):    
    #return 1
await client.send_file('+6324xxxx', 'C:/Users/Public/Pictures/q.png')

loop = asyncio.get_event_loop()
app = Flask(__name__)

api_id = 197xxx
api_hash = '1c3xxxxxxxxxxxxxxxx08e'

client = TelegramClient('session_name', api_id, api_hash)

client.start()

@app.route("/tele")
def notify():
    user = request.args.get("username")
    print(user);
    message = request.args.get("message")
    a=loop.run_until_complete(abar(user,message))
    print(a)
    return "OK"

@client.on(events.NewMessage())
async def handler(event):
    sender = await event.get_sender()
    name = utils.get_display_name(sender)
    print(name, 'said', event.text, '!')

try:
    print('(Press Ctrl+C to stop this)')
    client.run_until_disconnected()
    
finally:
    client.disconnect()

if __name__ == "__main__":
    app.run(debug=True, use_reloader=False)

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

In particular Flask + Telethon has been asked plenty of time before so I recommend you search before posting yet another question.
