### ISSUE TITLE
Cloud Application Platform

### ISSUE THREAD

**Issue by thexiox** [LonamiWebs/Telethon#3686]
Hello everyone, I would like to know what Cloud Application Platform you use and if you know of any free alternative.
Many thanks to all the comments.
Greetings

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. Unfortunately I don't really think this question belongs in StackOverflow or the Telethon chat either.

**Comment by thexiox** [comment]
Sorry but I did not know where to ask the question, where could I seek help on it?
