### ISSUE TITLE
Telegram Hidden Messages Show Up Blank

### ISSUE THREAD

**Issue by deadlyfeet326** [LonamiWebs/Telethon#3687]
Since the new update any messages formatted with the spoiler feature(grey box over the text that you have to click to reveal isn't showing up. In the event it just shows up message = "". If we could somehow change this it would be super helpful!

**Comment by New-dev0** [comment]
That's not for all 💤 
Maybe, you are on the old layer, so the message is empty. 
Try using any Telethon fork with layer 137 and `.message` will be the actual message without any entity (spoiler/etc) :)

**Comment by Lonami** [comment]
This is already fixed in the development version.

**Comment by deadlyfeet326** [comment]
> This is already fixed in the development version.

Sorry if I'm a noob, but is it possible for me to use this? Or do I have to wait for an update. And if so how?

**Comment by deadlyfeet326** [comment]
> That's not for all 💤 Maybe, you are on the old layer, so the message is empty. Try using any Telethon fork with layer 137 and `.message` will be the actual message without any entity (spoiler/etc) :)

Sorry if I'm a noob, but how would I go about doing this?
