### ISSUE TITLE
tl module not found.

### ISSUE THREAD

**Issue by dsx12** [LonamiWebs/Telethon#3691]
When attempting to import a function/method from the 'telethon.tl' library I receive the following error:
```
ModuleNotFoundError: No module named 'telethon.tl'
```

I attempted to bypass this by importing methods/functions from `telethon._tl` i.e. `telethon._tl.functions.messages` and `telethon._tl.functions.channel`:
```
from telethon._tl.functions.messages import ImportChatInviteRequest, CheckChatInviteRequest
from telethon._tl.functions.channels import LeaveChannelRequest
```
And still received the following error:

`ModuleNotFoundError: No module named 'telethon._tl.functions'`

I am following the instructions listed in https://docs.telethon.dev/en/stable/examples/chats-and-channels.html.

How do I import objects/functions/methods from `telethon.tl` in the Telethon development version (https://github.com/LonamiWebs/Telethon)? Is there documentation I'm missing specific to the development version?

**Comment by Lonami** [comment]
[It has been renamed](https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/misc/v2-migration-guide.rst#raw-api-has-been-renamed-and-is-now-considered-private) and the documentation is yet to be updated.
