### ISSUE TITLE
bug in device_model name...

### ISSUE THREAD

**Issue by wahyubram82** [LonamiWebs/Telethon#3702]
when call the TelegramClient with giving option device_model, show a bug in preview model,

example

TelegramClient(session_file,api_id,api_hash, device_model="Samsung Galaxy S21 Ultra 5G")

in telegram->Settings->Privacy & Security->Active Sessions, show like this: "Samsung galaxys21ultra5G".

if you try write the model as:
"Telethon PC 64Bit" it will be shown: "Telethon pc64bit".

the correct name, with uppercase and space only works for the first word of the model, the second word, and rest of it will not have space and uppercase letter.

any clue where I can fix it. Already learn file telethon/client/telegrambaseclient.py, there is logic about PC 64Bit or PC 32Bit as default device_model, already try to change it, still not works, similar results with above issue.

**Comment by Lonami** [comment]
Closing since I consider the currently-used device model to be a good-enough default.
