### ISSUE TITLE
Display inline buttons when send album.

### ISSUE THREAD

**Issue by xiaomi2077** [LonamiWebs/Telethon#3703]
The buttons disappear, when I use function `send_file()` to send pics as album with parameter `buttons` specified.  
This is my code:

> `await bot.send_file(event.chat_id,
                        file=send_messages,
                        buttons=[Button.inline('desc','button1')])`  

and `send_messages` is `list`. When I set `file=send_messages[0]`, the button appears.

I checked the implement of `send_file()`. When parameter `file` is specified as `list`, it will use `SendMultiMediaRequest()`. And this function do not have parament `buttons`. Otherwise it will use `SendMediaRequest`. And this funcion has parament `buttons`  

Can the function `SendMultiMediaRequest()` add an argument `buttons`?   
Is sending album with inline buttons natively supported by telegram official?

Thanks for your reply. :)

**Comment by Darskiy** [comment]
Hello. I ran into the same problem, have you found a solution?
