### ISSUE TITLE
Getting thus BUG please help

### ISSUE THREAD

**Issue by Bufins** [LonamiWebs/Telethon#3705]
Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\Genisys set1\scraper.py", line 84, in <module>
    members = client.get_participants(group, aggressive=True)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sync.py", line 39, in syncified    return loop.run_until_complete(coro)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)')], [None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x000001BBB809EEF0>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x000001BBB809EB00>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x000001BBB809DED0>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D210>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D360>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9C3A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D540>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D5A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D660>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D720>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D7E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D8A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9D960>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DA20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DAE0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DBA0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DC60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DD20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DDE0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DEA0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9DF60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E020>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E0E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E1A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E260>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E320>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E3E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E4A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001BBB7F9E560>])

**Comment by Lonami** [comment]
Flood waits come from Telegram and there's nothing the library can do.

**Comment by Bufins** [comment]
> Flood waits come from Telegram and there's nothing the library can do.

mybe downgrading telegram on pc worked? pr its not even connected like that?

**Comment by Bufins** [comment]
> FloodWaitError

i am new to this becouse of that asking :(

**Comment by ShambikDavid** [comment]
change the parameter u send in the func to aggresive=False
this helped me with this issue now im facing a different issue

ChannelParicipants object is not subscritable

**Comment by Bufins** [comment]
> change the parameter u send in the func to aggresive=False this helped me with this issue now im facing a different issue
> 
> ChannelParicipants object is not subscritable

mate fixed for me. The 2nd bug you get when try to add our what ?

**Comment by Bufins** [comment]
> change the parameter u send in the func to aggresive=False this helped me with this issue now im facing a different issue
> 
> ChannelParicipants object is not subscritable

you are coder? if yes can you hit me up on TG @D_WHO7 we are looking for coder ( soft dev)

**Comment by micont92** [comment]
> > change the parameter u send in the func to aggresive=False this helped me with this issue now im facing a different issue
> > ChannelParicipants object is not subscritable
> 
> mate fixed for me. The 2nd bug you get when try to add our what ?

did you manage to fix it?
