### ISSUE TITLE
disable reusing same file_id for media

### ISSUE THREAD

**Issue by rgegvre** [LonamiWebs/Telethon#3706]
is there a way to disable reusing file_id for media? since it's lookup on database
and I want media reuploaded every time

I use copy message `client.send_meesage` on telethon and it's still looks up for file_id of image or video on database

i'm looking to make telethon to upload media instead of reuse file_id from database
as `client.send_file` can be done with `allow_cache=False`

I looked on docs, couldn't find anything related, and seem `allow_cache=False` not works with `client.send_meesage`

**Comment by Lonami** [comment]
`allow_cache` shouldn't be working in v1.24.0, and it will be removed in v2, along with bot-API style file_ids.
