### ISSUE TITLE
Bug extractor telegram 

### ISSUE THREAD

**Issue by lainospeec** [LonamiWebs/Telethon#3707]
after today's update telegram no longer allows extracting

Traceback (most recent call last):
  File "C:\Users\laino\Desktop\BOT ATUALIZADO\BOT\telethon-bot.py", line 184, in <module>
    list_users_in_group()
  File "C:\Users\laino\Desktop\BOT ATUALIZADO\BOT\telethon-bot.py", line 138, in list_users_in_group
    all_participants = client.get_participants(target_group, aggressive=True)
  File "C:\Users\laino\AppData\Roaming\Python\Python310\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\laino\AppData\Roaming\Python\Python310\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\laino\AppData\Roaming\Python\Python310\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\laino\AppData\Roaming\Python\Python310\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\laino\AppData\Roaming\Python\Python310\site-packages\telethon\client\chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Users\laino\AppData\Roaming\Python\Python310\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\laino\AppData\Roaming\Python\Python310\site-packages\telethon\client\users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([None, None, None, FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 28 seconds is required (caused by GetParticipantsRequest)')], [<telethon.tl.types.channels.ChannelParticipants object at 0x0000023201DA8EB0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000023201DB5DE0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000023201DA9C00>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9870>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9930>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC99F0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9AB0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9B70>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9C30>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9CF0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9DB0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9E70>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9F30>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FEC9FF0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA0B0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA170>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA230>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA2F0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA3B0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA470>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA530>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA5F0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA6B0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA770>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA830>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA8F0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECA9B0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECAA70>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002327FECAB30>])

**Comment by micont92** [comment]
I also have this error, what to do?

**Comment by nileshnehate769** [comment]
same error

**Comment by Pari030** [comment]
Same error here, i think Telegram is editing max chunk size for requests (now is 200) and now it throw Flood Wait Error

**Comment by Lonami** [comment]
Happy to see Telegram is adding more strict limits on methods commonly used to spam. Telethon cannot do anything about this error. It comes directly from the API.

**Comment by lainospeec** [comment]
I think you are wrong, telegram has been growing exponentially by the use of bots if they crash they become unknown as they were before.
