### ISSUE TITLE
aggressive not function

### ISSUE THREAD

**Issue by tiofbr** [LonamiWebs/Telethon#3711]
hello, until a few days ago my code was running smoothly, I ran it today to pull the channel members with the parameter aggressive=True, as I normally run, today I came across the following error:
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'),

**Comment by vishalsharma9411** [comment]
Same here

**Comment by Lonami** [comment]
`aggressive` no longer exists in the development branch so this is not an issue. Please follow the issue template next time.
