### ISSUE TITLE
Aggressive=True Error

### ISSUE THREAD

**Issue by kthenurseone** [LonamiWebs/Telethon#3715]
![image](https://user-images.githubusercontent.com/54042275/153438256-752b91ac-3ce7-4a50-8fb9-b24b371a82e0.png)

When I dont use aggressive=True on c.get_participants(group) it give this error to me. What happened to aggressive method ? What should I do now ?

**Comment by denisqatipi** [comment]
Please check closed issues before posting. This has been posted several times now, and the creator has said the aggressive flag has been removed.

**Comment by kthenurseone** [comment]
Yeah I know but when I dont put it on the code it keeps giving errors. What should I do ?

> Please check closed issues before posting. This has been posted several times now, and the creator has said the aggressive flag has been removed.

**Comment by Lonami** [comment]
Please don't open duplicates and follow the issue template.
