### ISSUE TITLE
Can't install development version 

### ISSUE THREAD

**Issue by MrDeveloper2022** [LonamiWebs/Telethon#3721]
**Checklist**
* [ *] The error is in the library's code, and not in my own.
* [* ] I have searched for this issue before posting it and there isn't a duplicate.
* [ *] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

Hi
Because I can not get Participants in V 1.24 
`TypeError: 'ChannelParticipants' object does not support indexing`
I wanted to install development version on python3.7 but it needed markdown-it and there were no module with that name , I have installed markdown-it-py but now I'm facing 

`ModuleNotFoundError: No module named 'telethon.sync'`

Any help ?

**Comment by Lonami** [comment]
It seems you have installed it successfully, however, v2 contains many breaking changes, and the removal of `telethon.sync` is one of them. https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/misc/v2-migration-guide.rst is a work-in-progress of most of the changes.
