### ISSUE TITLE
error - ModuleNotFoundError: No module named 'telethon.sync' 

### ISSUE THREAD

**Issue by nileshnehate769** [LonamiWebs/Telethon#3722]
i just installed developer version of the telethon and I got this error
ModuleNotFoundError: No module named 'telethon.sync'

**Comment by Lonami** [comment]
The development version contains many breaking changes and the removal of `.sync` is one of them. See https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/misc/v2-migration-guide.rst.
