### ISSUE TITLE
how to change "who can add me to groups and channels telethon" with telethon

### ISSUE THREAD

**Issue by vnpresent** [LonamiWebs/Telethon#3727]
i want to change "who can add me to groups and channels telethon" with telethon,but I can't find any documentation about it

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
