### ISSUE TITLE
Telethon with proxy ipv6

### ISSUE THREAD

**Issue by issasalman** [LonamiWebs/Telethon#3728]
I have problem in dealing with Telethon library when I use proxy ipv6 it show error "An invalid argument was supplied" and some times "Proxy connection timed out: 10"

I used both python_socks and pysocks libraries same error

this is my code
```
import asyncio
 
 from telethon import TelegramClient, events
 
 api_id = valid
 api_hash = 'hidden'
 
 async def main():
     async with TelegramClient("session_name", api_id, api_hash,use_ipv6=True,proxy = {
     'proxy_type': 'http',
     'addr': 'ipv6',
     'port': port,
     'username': 'name',
     'password': 'pass',
     'rdns': True
 }) as client:
        await client.send_message('me', 'Hello, myself!')
 
 asyncio.run(main()
```

**Comment by w1ld32** [comment]
try use socks5 proxy type.

**Comment by slaid098** [comment]
It din't works for me too. I used socks5 proxy type

**Comment by Lonami** [comment]
Unfortunately I don't think this is something Telethon itself can fix but rather how the proxy library is used which depends on the parameters so I am going to close this issue but I would welcome any PR that improves the proxy support if necessary.
