### ISSUE TITLE
Send Message as Channel

### ISSUE THREAD

**Issue by lilcheti** [LonamiWebs/Telethon#3729]
Is this option available yet? to send message as your channels instead of your personal account.
Didn't find anything similar in the docs or the issues.

**Comment by New-dev0** [comment]
there is `send_as` parameter in `send_message` method, present in `master` branch. You can use that to send as a channel.

**Comment by Lonami** [comment]
Unfortunately this will have to be done through raw API in the meantime. v2 is still not ready for public use. I do not intend to add new features to v1, other than updating the layer used by the library to remain compatible with Telegram.

This means you can use raw API in v1.25 (available in PyPi) to achieve this but there is no `send_as`. For questions on how please use the official Telegram group or StackOverflow.
