### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by teamdaemons** [LonamiWebs/Telethon#373]
I am trying a simple code from the github instructions and I just keep getting ConnectionResetError. I am using Python3.x and installed telethon by using pip3 install.. its upgraded version. I just cant get beyond this for some reason. Please help.

```
from telethon import TelegramClient

# Use your own values here
api_id = xxxxxx
api_hash = 'xxxx'
phone_number = '+91xxxxx'

client = TelegramClient(phone_number, api_id, api_hash)
client.connect()
client.send_code_request(phone_number)
myself = client.sign_in(phone_number, input('Enter code: '))
```
Here is my entire error that i get.

> C:\Users\Administrator>python D:\Fazal\goog\Python\telemembers.py
> Traceback (most recent call last):
>   File "D:\Fazal\goog\Python\telemembers.py", line 22, in <module>
>     client.send_code_request(phone_number)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\telegram_client.py", line 135, in send_code_request
>     result = self(SendCodeRequest(phone, self.api_id, self.api_hash))
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\telegram_bare_client.py", line 461, in __call__
>     sender, call_receive, update_state, *requests
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\telegram_bare_client.py", line 481, in _invoke
>     sender.send(*requests)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\network\mtproto_sender.py", line 91, in send
>     self._send_message(message)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\network\mtproto_sender.py", line 141, in _send_message
>     self.connection.send(result)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\network\connection.py", line 182, in _send_tcp_full
>     self.write(data + crc)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\network\connection.py", line 219, in _write_plain
>     self.conn.write(data)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
> ackages\telethon\extensions\tcp_client.py", line 85, in write
>     raise ConnectionResetError()
> ConnectionResetError

**Comment by Lonami** [comment]
Did `.connect() return True`?

**Comment by teamdaemons** [comment]
i dont think so. it just runs forever. no result

**Comment by teamdaemons** [comment]
It just returns FALSE for .connect()

**Comment by Lonami** [comment]
Well it has to return True.

**Comment by teamdaemons** [comment]
I know its really strange I cant get it to return true on my windows laptop. I checked the same code on my MAC and it works. Still cant get it to work on my windows :(

**Comment by Lonami** [comment]
@teamdaemons does it work or… it still doesn't? Perhaps it was some condition? Could you try debugging why `.connect()` fails exactly?

**Comment by ehsankhorasani** [comment]
I have the same problem too
I test telethon in 3 server (centos & debian)
but `.connect()` return False

**Comment by Lonami** [comment]
Please enable debug logging to see why it returns `False` and also upgrade to `v0.15.4`.

**Comment by ehsankhorasani** [comment]
`
DEBUG:telethon.network.mtproto_sender:Read Bad Message error: (BadMessageError(...), 'msg_id too low (most likely, client time is wrong it would be worthwhile to synchronize it using msg_id notifications and re-send the original message with the "correct" msg_id or wrap it in a container with a new msg_id if the original message had waited too long on the client to be transmitted).')
DEBUG:telethon.network.mtproto_sender:Attempting to use the correct time offset.
DEBUG:telethon.network.mtproto_sender:Handling bad message notification
`
time server is wrong?

**Comment by Lonami** [comment]
No, *your* time seems to be the wrong one. Either way, the library should have "fixed" the issue by remembering the offset. What happens if you call `.connect()` twice in the same run?

**Comment by ehsankhorasani** [comment]
if debugging is off, does not turn back anything.
else return above debug log

**Comment by Lonami** [comment]
What? I mean, if it returns `False` and you call `.connect()` again does it return `True`? What's the output?

**Comment by ehsankhorasani** [comment]
I'm trying to connect again. but not connect.
`connect()` does not do anything.
but this work fine in local
`
from telethon import TelegramClient
from telethon.errors import SessionPasswordNeededError
import getpass, time

api_id = #####
api_hash = '############################'

phone = input("Enter your phone number: ") 
client = TelegramClient(phone, api_id, api_hash)
client.connect()
`

**Comment by Lonami** [comment]
#406 for another log.

**Comment by ehsankhorasani** [comment]
> if it returns False and you call .connect() again does it return True?
No. I test 3 time. but every time return False

**Comment by Lonami** [comment]
Could any of you remove the try/except from `.connect()` and try to run that. So we see what exception is raised and where?

**Comment by yonigrin** [comment]
Check your proxy configuration!

**Comment by Lonami** [comment]
That too. I always assume you're under no proxy because things get weird when they come into play, thanks for pointing it out.

**Comment by ehsankhorasani** [comment]
in same network, I test 4 OS (debian-minimal, centos-minimal, ubuntu desktop and Debian Desktop)
and only connect on Ubuntu and Debian desktop
Because in minimal systems, Python 3 is not installed by default. It needs to be installed.
But there are no issues in the systems on which Python 3 is installed by default.

**Comment by Lonami** [comment]
@ehsankhorasani maybe the installation is missing some parts essential to connect? Just a blind guess.

**Comment by ehsankhorasani** [comment]
me too
But which packages?
can you test on your own?

**Comment by ehsankhorasani** [comment]
@Lonami Do you have an idea?

**Comment by Lonami** [comment]
No, I don't.

**Comment by mamdosein97** [comment]
i have a question. if the script is running for a while and no update will happen, does the script stop with exception? I mean is there any timeout for receiving updates that after that with receiving no updates the .idle() will face with an exception?

**Comment by Lonami** [comment]
It should reconnect automatically in most cases, but it won't reconnect if the network goes down.

**Comment by yangtao097** [comment]
ipython running process as follow:
```
----> 1 client.connect()

c:\program files\python36\lib\site-packages\telethon\telegram_bare_client.py in connect(self, _sync_updates)
    212             if self._authorized is None and _sync_updates:
    213                 try:
--> 214                     self.sync_updates()
    215                     self._set_connected_and_authorized()
    216                 except UnauthorizedError:

c:\program files\python36\lib\site-packages\telethon\telegram_bare_client.py in sync_updates(self)
    605            otherwise it should be called manually after enabling updates.
    606         """
--> 607         self.updates.process(self(GetStateRequest()))
    608         self._last_state = datetime.now()
    609

c:\program files\python36\lib\site-packages\telethon\telegram_bare_client.py in __call__(self, retries, *requests)
    471             if not self._reconnect_lock.locked():
    472                 with self._reconnect_lock:
--> 473                     self._reconnect()
    474
    475         raise RuntimeError('Number of retries reached 0 for {}.'.format(

c:\program files\python36\lib\site-packages\telethon\telegram_bare_client.py in _reconnect(self, new_dc)
    293             try:
    294                 __log__.info('Attempting reconnection...')
--> 295                 return self.connect()
    296             except ConnectionResetError as e:
    297                 __log__.warning('Reconnection failed due to %s', e)

c:\program files\python36\lib\site-packages\telethon\telegram_bare_client.py in connect(self, _sync_updates)
    212             if self._authorized is None and _sync_updates:
    213                 try:
--> 214                     self.sync_updates()
    215                     self._set_connected_and_authorized()
    216                 except UnauthorizedError:

c:\program files\python36\lib\site-packages\telethon\telegram_bare_client.py in sync_updates(self)
    605            otherwise it should be called manually after enabling updates.
    606         """
--> 607         self.updates.process(self(GetStateRequest()))
    608         self._last_state = datetime.now()
    609

c:\program files\python36\lib\site-packages\telethon\telegram_bare_client.py in __call__(self, retries, *requests)
    474
    475         raise RuntimeError('Number of retries reached 0 for {}.'.format(
--> 476             [type(x).__name__ for x in requests]
    477         ))
    478

RuntimeError: Number of retries reached 0 for ['GetStateRequest'].
```
by the way, if user_authorized is absolutely needed before `client.connect()` ? Could you tell me how to do user_authorized from my sign_up and sign_in phone number? The steps in the docs are too abstract for a beginner, I can't get the idea yet.

**Comment by Lonami** [comment]
What "abstract"? You literally just need to call `client.start()`.

**Comment by yangtao097** [comment]
I have sovled my problem, if you use proxy such as Shadowsocks etc. You should execute as follow instead of` TelegramClient('session_name', api_id, api_hash)`:
`TelegramClient('session_name', api_id, api_hash, proxy=(socks.SOCKS5, 'xx.xx.xx.xxx', 4xxx1), update_workers=4)`
the  'xx.xx.xx.xxx' write down by 'localhost', port is your own listened port number, others keep the same!
GOOD LUCK!

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/bb3a5645008b01ee18f5adf1554ea7ce8a7cb15a has been merged, reopen *after* the next version is published if this error still occurs. Note that `master` is now running *under `asyncio`* so your code won't be compatible with it. To preserve this compatibility, a new branch emulating synchronous behaviour will be created.
