### ISSUE TITLE
struggle with creating an API bot ,

### ISSUE THREAD

**Issue by bigsmallninja** [LonamiWebs/Telethon#3731]
honestly have no idea what im doing , im trying to run a python file through cmd but it keeps saying 

Traceback (most recent call last):
  File "C:\Users\HOME\Downloads\**********\************", line 3, in <module>
    from telethon import TelegramClient
ModuleNotFoundError: No module named 'telethon'

what does this mean , i have no idea to work around it

**Comment by nileshnehate769** [comment]
open cmd and run this 

python -m pip install telethon

**Comment by bigsmallninja** [comment]
> open cmd and run this
> 
> python -m pip install telethon

nothing happened it just created a new line ?

**Comment by bigsmallninja** [comment]
nvm now it is giving me this 

Traceback (most recent call last):
  File "C:\Users\HOME\Downloads\shill.bot.folder\shillbotofficial.py", line 18, in <module>
    while true:
NameError: name 'true' is not defined. Did you mean: 'True'?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
