### ISSUE TITLE
How to use send_reaction() on Telethon 1.24.0?

### ISSUE THREAD

**Issue by md5hash16** [LonamiWebs/Telethon#3736]
Can i use send_reaction on telethon 1.24.0?

**Comment by ZE1L** [comment]
did you figure it out yet ?

**Comment by Lonami** [comment]
https://t.me/TelethonChat/474060 using https://t.me/TelethonUpdates/1276. I will close this issue once that branch is on PyPi.

**Comment by Lonami** [comment]
Closing since v1.25 is available in PyPi with the aforementioned methods.
