### ISSUE TITLE
How to upload_file by chunks?

### ISSUE THREAD

**Issue by Yury-MonZon** [LonamiWebs/Telethon#3738]
What is the proper way of uploading a file chunk by chunk? Like iter_download() but for uploading.

Something like:
```
while True:
			data = self.datasock.recv(1024)
			if not data: break
			client.upload_file_by_chunks(entity, file_id, data)
```

**Comment by Lonami** [comment]
Any object with an `(async) def read(n)` method can be used as the file, meaning you can write your own class with such method and pass an instance of that class as the file to upload. Also provide a `.name` attribute in the class.
