### ISSUE TITLE
Phone number not registering on Telegram (wrong data center?)

### ISSUE THREAD

**Issue by RRostami** [LonamiWebs/Telethon#374]
i'm getting RPC Error 303: PhoneMigrateError in the sample code (below).
happens with different phone numbers as well.
```
from telethon import TelegramClient      
api_id = ??      
api_hash = '??'    
phone = '+??'    
client = TelegramClient('Sess1', api_id, api_hash)     
r = client.connect()   # Successfull connection    
print("Initiated Connection:", r)    
print('server at:', client.session.server_address)    
if not client.is_user_authorized():   
        print("Authorizing...")    
        client.send_code_request(phone)    
        me = client.sign_in(phone, input('>'))     
print(me.stringify())    
```

and i get: 

```
Initiated Connection: True
server at: 91.108.56.165
Authorizing...
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\telethon\telegram_client.py", line 243, in invoke
    retries=kwargs.get('retries', 5)
  File "C:\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 338, in invoke
    raise request.rpc_error
telethon.errors.rpc_errors_303.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 4.')
```
I tried creating a new connection to Data Center 4, but i get "rpc_errors_401.AuthKeyUnregisteredError"

**Comment by Lonami** [comment]
Please format the code on your issue better.

**Comment by RRostami** [comment]
sure, fixed, just needed a couple of seconds to actually see it :)

**Comment by Lonami** [comment]
It's really weird `PhoneMigrateError` is being raised, what version are you using?

**Comment by RRostami** [comment]
```>>> TelegramClient.__version__
'0.13.4'
```

**Comment by Lonami** [comment]
Can you upgrade and try again, just so we know it hasn't been fixed on its own?

**Comment by RRostami** [comment]
oh i'm sorry, there is no issue with the '0.15.1' version, i had this issue for a while and had abandoned it since now. 
i'm embarrassed i opened a an issue without checking the latest release.
Thank you

**Comment by Lonami** [comment]
Out of curiosity, what version where you having this issue on?

**Comment by RRostami** [comment]
that one i mentioned above, 0.13.4

**Comment by Lonami** [comment]
Ah, missed it, forgot we were on `v0.15` ^^'

Strange the issue was around in such a "recent" version. Ah well. No problem.
