### ISSUE TITLE
redis stores message objects

### ISSUE THREAD

**Issue by jw-star** [LonamiWebs/Telethon#3741]
I want to store the message in redis for the next forwarding
```
    message = await event.client.send_message(event.chat_id, 'message.......')
    aa= json.dumps(message)
    print(aa)

```
error

```
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable
```

**Comment by Lonami** [comment]
`message.to_dict()` already provides this usecase.

**Comment by jw-star** [comment]
Thanks

**Comment by jw-star** [comment]
> `message.to_dict()` already provides this usecase.

I tried json serialization and still got an error

```
 dumps = json.dumps(message.to_dict())

``

**Comment by Lonami** [comment]
That's a problem with solving datetimes which StackOverflow has answers for. It's not something Telethon can fix.

**Comment by jw-star** [comment]
嗯嗯，我已经将 messsageId和peerId分别存储了
