### ISSUE TITLE
Unexpected behavior of receive_updates.

### ISSUE THREAD

**Issue by AYMENJD** [LonamiWebs/Telethon#3743]
Hi, if i set `receive_updates` = False. I can see on my logs that telethon is still handling updates:
```
[DEBUG][p 30173 Thread-1][1645790855.963934][mtprotosender.py:642][_handle_gzip_packed]  Handling gzipped data
[DEBUG][p 30173 Thread-1][1645790855.964556][mtprotosender.py:654][_handle_update]  Handling update Updates
[DEBUG][p 30173 Thread-1][1645790855.965215][mtprotosender.py:501][_recv_loop]  Receiving items from the network...

```
Client:
```python
client = TelegramClient(
            "bota",
            0,
            "0",
            receive_updates=False,
            loop=loop,
            auto_reconnect=True,
            flood_sleep_threshold=0,
        )
await client.start(bot_token=config.TOKEN)
logger.info("telethon connected")
await client.run_until_disconnected()
```

I think telethon on startup it sends requests without `invokeWithoutUpdates` so telegram will still send updates.

**Comment by Lonami** [comment]
The above commit is the only other place I could find where `invokeWithoutUpdates` was not being used. Not sure if it'll fix the problem. But at least that's covered now. Let me know if the problem persist with the above commit, and we can reopen the issue.

**Comment by Lonami** [comment]
Apparently [the above was never meant to work](https://t.me/tdlibchat/66208):

> The only intended use case for `invokeWithoutUpdates` is Share extension for iOS apps. It has never supposed to work in other circumstances.

**Comment by AYMENJD** [comment]
It meant to work which is no updates is sent by Telegram but definitely that's not the correct usage for it. And it can affect updates guarantee for bots which has main active session with updates enabled.
