### ISSUE TITLE
Bug in docs 

### ISSUE THREAD

**Issue by ahmedlone127** [LonamiWebs/Telethon#3745]
![image](https://user-images.githubusercontent.com/66001253/155831427-7bf14cbc-beb0-4074-a717-385705c74976.png)
ran this here got this : 
![image](https://user-images.githubusercontent.com/66001253/155831465-a2fc2b33-b0aa-4c51-9204-28be8ee8f2c2.png)

**Comment by Lonami** [comment]
The official documentation is https://docs.telethon.dev which no longer has that code.

https://telethonn.readthedocs.org is a common and seemingly popular misspelling (note "telethon**n**", double `n`) which is **not** official and is out of date at the time of writing. I tried writing to the RTD team to take it down but had no luck.
