### ISSUE TITLE
How to distinguish a channel from a group?

### ISSUE THREAD

**Issue by json1c** [LonamiWebs/Telethon#3747]
Group:
**Code:**
`await client.get_entity("termuxers")`
**Returned value:**
`Channel(...)`

Channel:
**Code:**
`await client.get_entity("durov")`
**Returned value'**
`Channel(...)`

Both group and channel are the same type. How to distinguish them?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
