### ISSUE TITLE
Deploy the robot to load on two machines

### ISSUE THREAD

**Issue by jw-star** [LonamiWebs/Telethon#3751]
How to put the same robot on two machines to process messages separately and reduce the pressure on the server

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
