### ISSUE TITLE
InviteToChannelRequest  users: List['TypeInputUser']

### ISSUE THREAD

**Issue by aLexDi69** [LonamiWebs/Telethon#3754]
List of user won't work! 
When i set users like this
usersadd.append(types.InputUser(usr.id, usr.access_hash))
Users don't add but if len(usersadd) = 1 works fine 
but after 3 or 5 users(sleep 120 sec for each) i've get error Too many requests (caused by InviteToChannelRequest)
Python 3.7 Telethon   1.24.0

**Comment by nitanmarcel** [comment]
Telegram has increased the limitations when it comes to making requests to the server. Not an issue with Telethon.

**Comment by masihamini00** [comment]
I have a group  to group robot. I broke the Telegram restriction and now I have an error on the accounts of this robot:
Too many requests (caused by InviteToChannelRequest)
I receive. More than 48 hours have passed and this error has not yet been fixed. what's the solution?
