### ISSUE TITLE
Error when i delete message

### ISSUE THREAD

**Issue by roaste** [LonamiWebs/Telethon#3755]
**Code that causes the issue**
from telethon import TelegramClient, functions, sync, errors

api_id = 1
api_hash = '1'
		
client = TelegramClient('1', api_id, api_hash)
client.start()
client(functions.channels.DeleteMessagesRequest(channel='channel',id=[msg.id]))
**Traceback**
telethon.errors.rpcerrorlist.MessageDeleteForbiddenError: You can't delete one of the messages you tried to delete, most likely because it is a service message. (caused by DeleteMessagesRequest)
```
i get this error when i use bot session, and don`t get when use user session. 
on the api site (https://tl.telethon.dev/methods/messages/delete_messages.html) it says: "Both users and bots can use this method." Can I use this method for a bot?

p.s. I give admin on the bot, channel is correct, mesage id is correct, problem not in this moments

**Comment by Lonami** [comment]
This error comes from Telegram and Telethon cannot fix it.

**Comment by yarodevuci** [comment]
I get this a lot too, not sure what's happening there with Telegram
