### ISSUE TITLE
The addChatUser command

### ISSUE THREAD

**Issue by suntong** [LonamiWebs/Telethon#3758]
Will the core API [`addChatUser` command](https://core.telegram.org/method/messages.addChatUser) be implemented?

I searched through the doc at 
https://docs.telethon.dev/en/stable/search.html?q=addChatUser&check_keywords=yes&area=default#
but didn't find any relevant hits. 

thx

**Comment by Lonami** [comment]
This is already available in raw API, which is documented.

**Comment by suntong** [comment]
You meant this?
https://docs.telethon.dev/en/stable/concepts/chats-vs-channels.html?highlight=raw%20API#a-note-on-raw-api

Sorry but if it is so easy for you to find it, would you mind share the link to your raw API in the document please?

**Comment by suntong** [comment]
Found it, finally --
https://tl.telethon.dev/methods/messages/add_chat_user.html
