### ISSUE TITLE
GetHistoryRequest and tl.functions.messages not present in master branch

### ISSUE THREAD

**Issue by antonio-antonucci** [LonamiWebs/Telethon#3761]
Hi everybody,
I have recently downloaded and installed the master branch in order to read messages when channel is Private and Restrict Saving Content, however it seems that tl.functions.messages is missing, thus prevent to use GetHistoryRequest.

Do you know when this will be included or perhaps when it's possible to benefit from this in the official release?
Thanks a lot

**Comment by Lonami** [comment]
The `Request` suffix was removed.

**Comment by antonio-antonucci** [comment]
Thanks @Lonami. Which is the module including the GetHistoryRequest?
Alternatively, what other method I can use to get the message history?
Thanks a lot
