### ISSUE TITLE
[QST] How to cek client status, connect or disconnect...?

### ISSUE THREAD

**Issue by wahyubram** [LonamiWebs/Telethon#3763]
I make a bot with bunch of order..., few weeks ago success, but yesterday my script not work anymore... error in connect and disconnect status.

previously I do this:

```
def function_to_run(id_user):
    client = TelegramClient(session_path,api_id,api_hash,
                                          device_model=model,
                                          system_version=sys_ver,
                                          app_version=app_ver)
    client.connect()
    --------------------------------------------
    function to get data from a telegram user
    --------------------------------------------
```
previously, it's works...

but then today...suddenly error database is locked (means telethon client status is still  connect).

ok, I read the documentation and from other source to close connection after get some data.

the I do this:

```
def function_to_run(id_user):
    client = TelegramClient(session_path,api_id,api_hash,
                                          device_model=model,
                                          system_version=sys_ver,
                                          app_version=app_ver)
    client.connect()
    --------------------------------------------
    function to get data from a telegram user
    --------------------------------------------
    client.disconnect()

```
still not works, client still connect, and the database is locked.

OK, now I try to different approach..., I try to make client always connect. I make like this:

```
def function_to_run(id_user):
    client = TelegramClient(session_path,api_id,api_hash,
                                          device_model=model,
                                          system_version=sys_ver,
                                          app_version=app_ver)
    client.connect()
    client.run_until_disconnected()
    --------------------------------------------
    function to get data from a telegram user
    --------------------------------------------
```
but then, a few minutes later error.... "cannot Send requests while disconnected".

Is there a way to know the connection status of the client, so if we still connected, I by pass the script to make a connection order to avoid database locked error.

while it disconnected, I can told the script to make a connection first before getting data to avoid error (cannot Send requests while disconnected).

EDIT:

now I try do this, set client in global, and try to call client.connect every time want get data.

client = TelegramClient(session_path,api_id,api_hash,
                                          device_model=model,
                                          system_version=sys_ver,
                                          app_version=app_ver)

```
def function_to_get_data(id_user):
    try:
        client.connect()
        client.run_until_disconnected()
    except:
        pass

    --------------------------------------------
    function to get data from a telegram user
    --------------------------------------------
    return data
```

but I not satisfied because it make my bot so slow in responding

**Comment by ghost** [comment]
You can use this to check your connection status: https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.telegrambaseclient.TelegramBaseClient.is_connected
The database gets locked because you try to use a session from multiple clients

**Comment by Lonami** [comment]
Closing since this is not really actionable. The bot being slow to respond comes down to how fast Telegram decides to deliver updates to the Telethon client. Telethon cannot really force updates. However the v1.25 version available from PyPi should deal with update handling better overall.
