### ISSUE TITLE
Fatal error handling updates

### ISSUE THREAD

**Issue by kggcel** [LonamiWebs/Telethon#3764]
**Checklist**
* [ X] The error is in the library's code, and not in my own.
* [X ] I have searched for this issue before posting it and there isn't a duplicate.
* [ X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

note: Basically I'm trying to read the message from a channel. Previous versions of Telethon worked fine, but because the channel enabled the "restricted from copy" option I had to refactor the code to upgrade to Telethon v2.

After updating my code I realised that the library has the following bugs:

1 - \telethon\_client\updates.py 

(User._new(client, u) for u in users),
(Chat._new(client, c) for u in chats), 

SHOULD BE:

(User._new(client, u) for u in users),
(Chat._new(client, c) for c in chats),

2 - telethon\types\_custom\chats.py
missing import: 

from ..._sessions.types import EntityType, Entity

Even after fixing those on my local folder, I still get the error below

**Code that causes the issue**
```python
from telethon import TelegramClient

@client.on(events.NewMessage, chats=easy )
async def handler(event): 


Traceback (most recent call last):
  File "\lib\site-packages\telethon\_client\updates.py", line 260, in _dispatch
    if handler._filter(event):
  File "\lib\site-packages\telethon\_events\filters\base.py", line 27, in __call__
    return all(f(event) for f in self._filters)
  File "\lib\site-packages\telethon\_events\filters\base.py", line 27, in <genexpr>
    return all(f(event) for f in self._filters)
  File "\lib\site-packages\telethon\_events\filters\entities.py", line 15, in __call__
    return isinstance(event, self._types)
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

**Comment by kaiopinho** [comment]
+1

**Comment by kaiopinho** [comment]
+1

**Comment by Lonami** [comment]
Current `v2` branch (old `master`) is broken. v1 (and the v1.25 PyPi version) should both be working. Feel free to reopen if that's not the case.

**Comment by Samjith888** [comment]
Installed by using 'pip3 install telethon' , but still getting the error

**Comment by Lonami** [comment]
Please post the full traceback on a new issue and make sure you are actually using the latest version.
