### ISSUE TITLE
forward_messages splits one message with a group of photos into several messages with one photo  

### ISSUE THREAD

**Issue by white4x** [LonamiWebs/Telethon#3765]
I'm trying to forward a message with a group of photos. But they are redirected by separate messages in destination channel. How can I redirect with one message?

```
@client.on(events.NewMessage(incoming=True, chats=FROM))
async def handler_frw(event):
    await client.forward_messages(CHANNEL_TO, event.message)
```

If I use "send_message" it send as one message. But TO_NAME - doesn't work with id Channel, only name :( And i need "Forward from" in destination channel.

```
@client.on(events.Album(chats=FROM))
async def handler_snd(event):
    print("Have album.")
    caps = []
    for item in event.messages:
        caps.append(item.message)
    await client.send_message(TO_NAME, file=event.messages, message=caps)
```

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by white4x** [comment]
Sorry, I thought that forwarding (client.forward_messages) was not working correctly, splitting one message into several :(

**Comment by Lonami** [comment]
Albums are multiple messages. `events.NewMessage` receives them one by one. Forwarding them one by one will split them.

**Comment by white4x** [comment]
I found the necessary solution, thanks!

**Comment by denn319** [comment]
> I found the necessary solution, thanks!

Hi, can you share the solution?

**Comment by adityaerlangga** [comment]
Hi @denn319, if you trying to solve this problem. You can use send_message function.

But if it has an album (group of photos/videos) you can use the file parameter in it.

```
files = []
for message in messages:
    if isinstance(message, Message):
        print(f"Message ID: {message.id}")
        if message.grouped_id is None:
            await client.send_message(DESTINATION_GROUP_ID, message, silent=True)
        else:
            if grouped_id == message.grouped_id:
                files.append(message)
            else:
                if files:
                    # Forward the album (list of files) to the destination group without header "Forwarded from..."
                    await client.send_message(DESTINATION_GROUP_ID, file=files, silent=True)
                    files = []  # Reset files list
                grouped_id = message.grouped_id
                files.append(message)

# Check if there are remaining files to be forwarded
if files:
    await client.send_message(DESTINATION_GROUP_ID, file=files, silent=True)
```
