### ISSUE TITLE
Help Required::: Can we use multiple channel ID's for filtering on events.NewMessage(chats=-xxxxx)

### ISSUE THREAD

**Issue by udaykittu** [LonamiWebs/Telethon#3770]
hi

I want to use multiple channel id's in events.NewMessage(chats=-xxxxx) to forward messages to a new channel

can you please explain how to do it?

for ex:
@client.on(events.NewMessage(chats=(FirstChatID, SecondChatID, ThirdChatID)))

or 

@client.on(events.NewMessage(chats=[FirstChatID, SecondChatID, ThirdChatID]))

Thanks

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
