### ISSUE TITLE
Transfer ownership of group

### ISSUE THREAD

**Issue by codelvl** [LonamiWebs/Telethon#3771]
```functions.channels.EditAdminRequest```
By using this function I can set new admin, but how to transfer ownership?
I didnt find related information in documentation, is it implemented ?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
