### ISSUE TITLE
resolve_inline_message_id not work with new ID's

### ISSUE THREAD

**Issue by arynyklas** [LonamiWebs/Telethon#3772]
resolve_inline_message_id not work with new ID's.
Error in that line:

https://github.com/LonamiWebs/Telethon/blob/2357116f01eebb7e94803cbfb2ca384ecec97c32/telethon/_misc/utils.py#L1050

Example:
Old ID - `resolve_inline_message_id("AgAAABHGBwAuCmAvUyChJFkA7mI") = (2, ...)`
New ID - `resolve_inline_message_id("BQAAAEizbjMBAAAAGQAAAMLKZR_sAinx") = (None, None, None, None)`

**Comment by arynyklas** [comment]
Also I tested to unpack with '<iiqq', it works for new ID, but for old not work.

**Comment by Lonami** [comment]
Might be time to remove this feature too.

**Comment by arynyklas** [comment]
Solution found:
```
ID32_FORMAT_SIZE = 27
ID64_FORMAT_SIZE = 32

if len(inline_message_id) == ID32_FORMAT_SIZE:
    dc_id, message_id, pid, access_hash = struct.unpack('<iiiq', _decode_telegram_base64(inline_msg_id))
else:
    dc_id, message_id, pid, access_hash = struct.unpack('<iqiq', _decode_telegram_base64(inline_msg_id))
```

**Comment by arynyklas** [comment]
> Solution found:
> 
> ```
> ID32_FORMAT_SIZE = 27
> ID64_FORMAT_SIZE = 32
> 
> if len(inline_message_id) == ID32_FORMAT_SIZE:
>     dc_id, message_id, pid, access_hash = struct.unpack('<iiiq', _decode_telegram_base64(inline_msg_id))
> else:
>     dc_id, message_id, pid, access_hash = struct.unpack('<iqiq', _decode_telegram_base64(inline_msg_id))
> ```
