### ISSUE TITLE
 @client.on(events.Album(chats=FROM)) don't work with user

### ISSUE THREAD

**Issue by white4x** [LonamiWebs/Telethon#3773]
I try to know when i receive an album. 
`@client.on(events.Album(chats=FROM)) `
My FROM its user (12345678) and chanel (-10012345678).
When i receive album from chanell - all good (i see "have album").
When i receive album from user - nothing happens.

When use client.on(events.NewMessage(chats=FROM)) - it's work

I tested 5 diferent simple code (user and chanel).

1,4,5 - work
2 - don't work
3 - work (for all message - user or chenel)
 maybe its bug?

1.
```
@client.on(events.Album(chats=-10012345678))
async def frw_album(event):
    print ("have ALBUM")
```
2.
```
@client.on(events.Album(chats=12345678))
async def frw_album(event):
    print ("have ALBUM")
```
3.
```
@client.on(events.Album())    
async def frw_album(event):
    print ("have ALBUM")
```
4.    
```
@client.on(events.NewMessage(chats=-10012345678))
async def frw_msg(event):
    print ("MESSAGE")
```
5.
```
@client.on(events.NewMessage(chats=12345678))
async def frw_msg(event):
    print ("MESSAGE")
```

**Comment by Lonami** [comment]
Probably changed a long time ago and was fixed for `NewMessage` but not `Album` because `Album` is more rarely used.
