### ISSUE TITLE
Add contacts using only user_id and access_hash?

### ISSUE THREAD

**Issue by fotechv** [LonamiWebs/Telethon#3775]
I want to add some contacts to my Tele account. I only have user_id and access_hash (no phone and username)
I have used AddContactRequest and ImportContactsRequest, they both can't do it.

Is there any other way I can do this?
Thank you!

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
