### ISSUE TITLE
The phone number a user is trying to use for authorization is associated with DC 5 (caused by SendCodeRequest)

### ISSUE THREAD

**Issue by mxkeey** [LonamiWebs/Telethon#3777]
I am trying to register telegram accounts using phone numbers from different countries. For most phones, a PhoneMigrateError is thrown when a SendCodeRequest is requested. In my opinion, this occurs when the client's phone number and the phone number to which the code is sent are in different data centers.

**Code that causes the issue**
```python
result = await client(functions.auth.SendCodeRequest(
    phone_number, acc["api_id"], acc["api_hash"],
    settings=types.CodeSettings( allow_flashcall=False, current_number=True, allow_app_hash=False )
))
```

**Comment by Lonami** [comment]
There is no bug. The error comes from Telegram and it works as intended.

**Comment by mxkeey** [comment]
If so, why does a client that is authorized from a phone from Ukraine throw a PhoneMigrateError exception when trying to register from any phone in some countries. Only numbers that are located in the same data center where the account is registered from which registration is made are available for registration.

**Comment by mxkeey** [comment]
If api_id, api_hash are linked to a Ukrainian phone number, I can't register accounts using phones in 80% of countries. What to do in this case?

**Comment by Lonami** [comment]
API ID and hash are not linked to specific data centers as far as I know. Raw API does not automatically handle DC migrations, but `client.sign_up` should. This is offtopic here.

**Comment by mxkeey** [comment]
problem with SendCodeRequest - does it automatically handle DC migrations?
API ID and hash are not linked - Then why DC is listed at https://my.telegram.org/apps and I can't change it?
![image](https://user-images.githubusercontent.com/38672923/159722873-36f4de74-6f84-464b-a24f-f7b6794b1f39.png)

**Comment by Lonami** [comment]
That's the test server. The library has a hardcoded datacenter but switches to others at runtime if necessary. Friendly methods do this. Raw API does not.
