### ISSUE TITLE
get_participants for channel only returns 200 members

### ISSUE THREAD

**Issue by r-mzy47** [LonamiWebs/Telethon#3781]
get_participants works well for groups but for channels, it only returns 200 members. I have also tried the solution explained [here](https://github.com/LonamiWebs/Telethon/issues/928#issuecomment-1035895117) but doesn't work for the channel. it seems telegram API restricts channel member extracts. is there any alternative solution for extracting members of the channels that I am the admin of them. 
I am using the latest master branch of telethon by the way.

thanks in advance.

**Comment by Lonami** [comment]
This is a Telegram limitation the library cannot fix.
