### ISSUE TITLE
How to join a open chat with telethon

### ISSUE THREAD

**Issue by Dalmatianinubsc** [LonamiWebs/Telethon#3786]
good afternoon, I tried to join the group but nothing came out, and I have a question how can I do it.

i have a link to open chat (http://t.me/some_chat)
how can i join it via telethon ?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by Dalmatianinubsc** [comment]
ok , thx
