### ISSUE TITLE
download all media in a post by grouped_id

### ISSUE THREAD

**Issue by msramalho** [LonamiWebs/Telethon#3788]
I had a recent case where I wanted to download all the media associated with a telegram post, and indeed telegram URLs only point to one post, even if that post is part of a group (identified by their `grouped_id` property). 

I wrote this function to achieve this, it might be useful to have a function in telethon that does something similar, or even an option to download all the grouped_id media given a post.

```python
def _get_media_posts_in_group(chat, original_post, max_amp=10):
    """
    Searches for Telegram posts that are part of the same group of uploads
    The search is conducted around the id of the original post with an amplitude
    of `max_amp` both ways
    Returns a list of [post] where each post has media and is in the same grouped_id
    """
    if original_post.grouped_id is None:
        return [original_post] if original_post.media is not None else []

    search_ids = [i for i in range(original_post.id - max_amp, original_post.id + max_amp + 1)]
    posts = self.client.get_messages(chat, ids=search_ids)
    media = []
    for post in posts:
        if post is not None and post.grouped_id == original_post.grouped_id and post.media is not None:
            media.append(post)
    return media
```

so instead of doing `client.download_media(post.media, 'filename')` we could do `client.download_media(post, 'folderName')` or similar

**Comment by Lonami** [comment]
This is unlikely to ever be implemented, as I personally consider it feature bloat.

**Comment by protexdefense** [comment]
Thank you, it was very useful
