### ISSUE TITLE
how to returns removed users that exists in -> mygroup/permission/removed users

### ISSUE THREAD

**Issue by masoodccc** [LonamiWebs/Telethon#3790]
hi 
for returns removed users that exists in -> mygroup/permission/removed users , i use belowe code

all_participants = client.get_participants(mygroup , filter=ChannelParticipantsKicked('q'))

this commands is true but return empty list. why it is not work correctly??

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by masoodccc** [comment]
thank you.solved.
