### ISSUE TITLE
'PeerChannel' object has no attribute 'user_id'

### ISSUE THREAD

**Issue by JaneCCP** [LonamiWebs/Telethon#3795]
`from telethon import TelegramClient,sync,events
from datetime import datetime
import pytz
from data import *

client = TelegramClient('session_file', api_id, api_hash)
client.start()

with open(r'message.json','a+',encoding='utf-8') as test:
    test.truncate(0)

entity = client.get_entity(1372899216)
for message in client.iter_messages(entity,   limit=None):
    message_date = (message.date)
    beijing_time = pytz.timezone('Asia/Shanghai')
    local_time = message_date.astimezone(beijing_time)
    message_data = str('message ID:') + str(message.id) + str('   channel ID:') +  str(message.peer_id.channel_id) + str('   message user ID:') +  str(message.from_id.user_id)+ str('    messagedate:') + str(local_time) + str('    textdata:') + str(message.text) + '\r\n'
    F = open("message.json", "a+")
    F.write(message_data)
    F.close()`

The channel_id parameter will be mixed into the user ID of the message parameter returned by the group, so that the id cannot be found

**Comment by Marco-Antonio-Rodrigues** [comment]
I'm having this problem, in this part of the code:

            elif str(self.bot_id) == str(
                event.message.peer_id.user_id
            ): 
 
Error:
'PeerChannel' object has no attribute 'user_id'

**Comment by tusharkgerg** [comment]
same issue
