### ISSUE TITLE
How to get user registration Date with Telethon

### ISSUE THREAD

**Issue by megakosi** [LonamiWebs/Telethon#3798]
Is there any way to get the Date of User registration, knowing the access_hash?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
