### ISSUE TITLE
update_app_to_login

### ISSUE THREAD

**Issue by Amineratiba** [LonamiWebs/Telethon#3799]
**Checklist**
* [x] The error is in the library's code, and not in my own. -- YES
* [x] I have searched for this issue before posting it and there isn't a duplicate. -- YES
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version. -- NO

**Code that causes the issue**
```python
from telethon import TelegramClient -- YES
...

```

**Traceback**
```
Traceback (most recent call last):
  File "code.py", line 1, in <code>

Picture attached.

Please keep in mind that this issue is only affecting one of the 2 numbers I have added into Telegram,

Thanks

![2022-04-08_13h19_39](https://user-images.githubusercontent.com/77080955/162534795-502d2600-edec-48cb-9820-e16f989fa085.jpg)

```

**Comment by Amineratiba** [comment]
![2022-04-08_13h19_39](https://user-images.githubusercontent.com/77080955/162535483-74b87f2f-b4b0-4359-9353-c4598c4be841.jpg)

**Comment by Amineratiba** [comment]
Please let me know if you need more details.

Thanks

**Comment by Lonami** [comment]
This has already been resolved in newer versions.
