### ISSUE TITLE
OverflowError: int too big to convert when GetFullChat

### ISSUE THREAD

**Issue by Lord-Protector** [LonamiWebs/Telethon#38]
`chat = client.invoke(GetFullChatRequest(chat_id=int(-1001087453541)))
OverflowError: int too big to convert`
 
Seems not okay

**Comment by XyLoNaMiyX** [comment]
`chat_id` must be an **unsigned** integer. Since Python allows arbitrary large numbers, that conversion won't work.

**Comment by Lord-Protector** [comment]
@XyLoNaMiyX so how I shoud't send not positive chat_id of supergroup?

**Comment by XyLoNaMiyX** [comment]
How did you get that number?

**Comment by Lord-Protector** [comment]
@XyLoNaMiyX 
Various ID int TG:
44700; // bot API id (users)
-492772765; // bot API id (chats)
-10038575794; // bot API id (channels)

May be I somethink don't understand...

**Comment by XyLoNaMiyX** [comment]
That number seems to be just wrong. The chat ID is a 32-bit unsigned integer, and the number you're showing needs 40 bits.

**Comment by Lord-Protector** [comment]
@XyLoNaMiyX Yeah, I see that it's 40-bit int, but it's just object from my bot (that is using Bot API). So chat_id's from bot api and telergram api are different? О_о)

**Comment by XyLoNaMiyX** [comment]
Can you try to get this channel via Telethon itself?

**Comment by Lord-Protector** [comment]
@XyLoNaMiyX 
ID from Bot: -1001101555493
ID from Telethon: 1101555493 (so from Telegram API too)
But then I user second ID I got the error
```
Unknown error message with code 400: CHAT_ID_INVALID
```
And it has logic -- this ID can be taken by user.

**Comment by XyLoNaMiyX** [comment]
Does it work with other chats?

**Comment by Lord-Protector** [comment]
@XyLoNaMiyX 
Just tried with supergroups and just groups:
Supergroups are NOT working with:
-100ID
-ID
ID
Groups are NOT working with
-ID
but works with
ID

So `GetFullChatRequest(chat_id=218573808)` executed successful, but Bot API gives me `-218573808`

**Comment by Lord-Protector** [comment]
Seems like supergroup is type of channel (strange, but method getFullChannel works!)

**Comment by XyLoNaMiyX** [comment]
I love the amount of issues which get solved without doing anything from my side haha. Good you fixed it.

**Comment by Lord-Protector** [comment]
@XyLoNaMiyX sorry :D 
Just today start explore Telegram API.

**Comment by MasterGroosha** [comment]
I have the same problem with `InputPeerChannel` type. Using https://fabianpastor.github.io/webogram/ to get channel_id and access_hash, hovewer I have the same error: `OverflowError: int too big to convert`

**Comment by Lonami** [comment]
> Using https://fabianpastor.github.io/webogram/ to get `channel_id` and `access_hash`

Maybe Webogram uses unsigned integers, or maybe it doesn't mind about the sign bit. I don't know how it works. However, it would be nice if you used *Telethon* to work with Telethon itself. What's the integer in your case? Is it around 32 bits, or is it also huge like 40 bits?
