### ISSUE TITLE
Previous Reported Issue (#3799)

### ISSUE THREAD

**Issue by Amineratiba** [LonamiWebs/Telethon#3801]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
...

```

**Traceback**
```
Traceback (most recent call last):
  File "code.py", line 1, in <code>

```

**Comment by Amineratiba** [comment]
Sorry to recreate a new issue, 

**### Please consider that this issue is only affecting one of my 2 telegram accounts.**
And I have the latest version updated already. 

Thanks for your help

**Comment by Amineratiba** [comment]
![2022-04-09_13h27_31](https://user-images.githubusercontent.com/77080955/162590673-cbfa7897-4c12-41b1-96be-06a3248dd2aa.jpg)
![2022-04-09_13h28_29](https://user-images.githubusercontent.com/77080955/162590674-ac25c514-40b3-4c04-b72e-601c6e9439ec.jpg)

**Comment by Amineratiba** [comment]
Screenshots are from 2 different Apps. just to eliminate an app issue, plus both Apps work fine with my 1st number.

**Comment by Lonami** [comment]
The library version is out of date.
