### ISSUE TITLE
setup.py contains code that is not supposed to be there

### ISSUE THREAD

**Issue by andreif** [LonamiWebs/Telethon#381]

**Comment by Lonami** [comment]
Could you be more precise?

**Comment by andreif** [comment]
```py    if len(argv) >= 2 and argv[1] == 'gen_tl':
        gen_tl()

    elif len(argv) >= 2 and argv[1] == 'clean_tl':
        from telethon_generator.tl_generator import TLGenerator
        print('Cleaning...')
        TLGenerator(GENERATOR_DIR).clean_tlobjects()
        print('Done.')
```

**Comment by andreif** [comment]
Maybe move it somewhere else and keep setup.py as simple as possible?

**Comment by Lonami** [comment]
Why though?

**Comment by udf** [comment]
You know how when your mom tells you to clean your room and you just stuff everything under the bed?

Yeah, do that.

**Comment by andreif** [comment]
Adding a Makefile would help

**Comment by Lonami** [comment]
A Makefile, for Python. Not needed, honestly. The code is good.

**Comment by Lonami** [comment]
You still haven't explained *why* I should do such thing anyway.

**Comment by andreif** [comment]
Amateurish but not unexpected. How old are you btw?

**Comment by Lonami** [comment]
That's irrelevant to the issue.

**Comment by andreif** [comment]
That's true, sorry.

**Comment by Lonami** [comment]
I'm still curious however. Do you have more arguments supporting why the `setup.py` should be "simpler“ or was it simply personal taste?

**Comment by andreif** [comment]
The problem is that the code is not properly tested, has complex setup.py and right now not possible to install.

**Comment by Lonami** [comment]
What troubles are you having to install the library? Did you ensure it's Python 2? Where else could I put this additional logic? I find it extremely comfortable to be able to use:
```bash
python setup.py gen_tl
python setup.py pypi
```

**Comment by andreif** [comment]
You import your dependencies in your setup.py which breaks and then uses `except Exception` to go deep in something unrelated to install. You are welcome.

**Comment by andreif** [comment]
Sorry again, I am too hungry right now 😺

**Comment by Lonami** [comment]
That "you are welcome" was unnecessary. I try importing the client to check whether the code has been generated correctly, there's a reason behind why the code is the way it is. Python allows me to try/except imports, and if you know of a better way to check whether it can be imported correctly or not please let me know.

Also, keeping the version in a single place (inside the library in `TelegramBareClient`) helps me not to need keeping track of several places where I should update the version number, which can be easy to miss.

As my last point, I had some issues with the working directory and the code generator, so I just decided to keep it centralized in a single place. And it works correctly now.

**Comment by andreif** [comment]
I opened another issue, more specific to the problem. I still think that setup.py is unnecessary complex just to work as a Makefile for convenience. This creates problems where they should not be.

**Comment by Lonami** [comment]
I still can't see the complexity… it's just an `if/elif/else` chain.

**Comment by vkimmanuelgeorge** [comment]
@Lonami I think they meant like this
https://github.com/vklab/vklabs.telethon/blob/master/setup.py
https://github.com/vklab/vklabs.telethon/blob/master/error_generator.py 
https://github.com/vklab/vklabs.telethon/blob/master/deploy_telethon.py

**Comment by Lonami** [comment]
`setup.py` *needs* to generate code during install anyway so even if I remove the special case for my own "commands" and put them in another file, I will have to include it. Not that it's an issue, really, not sure why I was so against the change back then.
