### ISSUE TITLE
while trying to get file_id of a photo through await client.get_messages().

### ISSUE THREAD

**Issue by WeebZoneIndia** [LonamiWebs/Telethon#3815]
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```from Takagi.services.telethon import tbot

async def get_msg_file(message):
    message_id = message.message_id

    tmsg = await tbot.get_messages(message.chat.id, ids=message_id)

    file_types = ['sticker', 'photo', 'document', 'video', 'audio', 'video_note', 'voice']
    for file_type in file_types:
        if file_type not in message:
            continue
        if not tmsg.file:
            # FIXME: NoneType is unexpected here
            raise Exception("Telegram refused to give file info!")
        return {'id': tmsg.file.id, 'type': file_type}
    return None
```

**Traceback**
```
AttributeError: 'PhotoSize' object has no attribute 'location'

```

**Comment by Lonami** [comment]
Bot-API style file IDs have changed and are currently broken. I do not have plans to fix them so my recommendation is to stop using them.
