### ISSUE TITLE
TelethonChat

### ISSUE THREAD

**Issue by kumufengchun99** [LonamiWebs/Telethon#3816]
May I ask?
Does telethon have a way to turn a private group into a public group? I haven't found it yet

**Comment by jishuXiaom** [comment]
+1

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
