### ISSUE TITLE
Button method Share My Live Location

### ISSUE THREAD

**Issue by johnedstone** [LonamiWebs/Telethon#3818]
Similar to the Button method `request_location` it would be great to have a button to "Share my live location ...." similar to the built-in Paperclip -> Location -> "Share my Live Location for ..." on my Android!
Thanks again for maintaining this library!! It is very useful

**Comment by Lonami** [comment]
Sorry, but I don't think this will be implemented directly by the library. As far as I know it's done by periodically editing the message and the library would need to somehow call into user code to get the "current" location which is awkward (similar to `progress_callback`, which is not very nice to use). I think it's better left for user code to implement.
