### ISSUE TITLE
GetParticipantsRequest: returning not all members 

### ISSUE THREAD

**Issue by evgenyshandrik** [LonamiWebs/Telethon#3820]
**GetParticipantsRequest**: why returning not all members ? 
For example, my groups has **3377** members, but return **3356** members.

        while True:
        participants = await client(GetParticipantsRequest(
            my_channel, ChannelParticipantsSearch(''), offset, limit,
            hash=0
        ))
        if not participants.users:
            print(participants)
            break
        all_participants.extend(participants.users)
        offset += len(participants.users)

When I print in block if:

       print(participants)

I get:

       ChannelParticipants(count=3389, participants=[], chats=[], users=[]

count=**3389** and it's not equals **3377** (count of members in my group).
Why???

Plese help me with it.

**Comment by edogab33** [comment]
Might be because you have some deleted account in your group I guess.

**Comment by evgenyshandrik** [comment]
@edogab33 I checked it - there aren't. 
On the other hand: deleted users it is such as object as ordinary user but I'm getting empty dictionary (users=[])

**Comment by Lonami** [comment]
You're using raw API, meaning you are talking directly to Telegram, meaning Telethon is not changing the results or data sent in any way so there is nothing that can be done to "fix" this. It's working as intended.

**Comment by evgenyshandrik** [comment]
@Lonami "It's working as intended." - how ?
How do I get the exact quantity?

**Comment by solana-boy** [comment]
@evgenyshandrik did you find answer?

**Comment by evgenyshandrik** [comment]
> @evgenyshandrik did you find answer?
> 
> 

Unfortunately, no

**Comment by Lonami** [comment]
Telegram's API (not Telethon) intentionally limits the amount of participants you can fetch to prevent spam uses. There might be workarounds, but I have not investigated.

**Comment by evgenyshandrik** [comment]
> Telegram's API (not Telethon) intentionally limits the amount of participants you can fetch to prevent spam uses. There might be workarounds, but I have not investigated.

Interesting idea, but I don't understand reason for it

**Comment by Lonami** [comment]
This has been abused to mass add users before.

**Comment by evgenyshandrik** [comment]
divergence is very small. For example, 3389 vs 3377

**Comment by jerry199507** [comment]
Did you find a solution?

**Comment by evgenyshandrik** [comment]
no
