### ISSUE TITLE
send_code_request not send codes

### ISSUE THREAD

**Issue by cunyiles** [LonamiWebs/Telethon#3822]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
...
send_code = client.send_code_request(phone, force_sms=True)
```

Telethon cannot send codes for two days. I also tried with force_sms, but not worked. I don't get any error messages.
Another MTProto library pyrogram works, but Telethon has a problem.

**Comment by cunyiles** [comment]
Problem solved.

**Comment by Subachev** [comment]
We have the same problem. How did you solve it?

**Comment by LPeng111** [comment]
> We have the same problem. How did you solve it?

We have the same problem. How did you solve it?

**Comment by LPeng111** [comment]
> Problem solved.

We have the same problem. How did you solve it?

**Comment by msilenkov** [comment]
I solved this problem after enabled two-factor authentication and then the messages started coming to my email address associated with two-factor authentication.
