### ISSUE TITLE
Obtain private channel name from a forwarded message?

### ISSUE THREAD

**Issue by thinhlh** [LonamiWebs/Telethon#3823]
If someone forwards a message from the private channel to the public channel\group or in DM, in the Telegram application you will see the name of this channel. But when you get this forwarded message by telethon you can get only channel ID. Using this ID is useless because on any request you will get `telethon.errors.rpcerrorlist.ChannelPrivateError: The channel specified is private and you lack permission to access it. Another reason may be that you were banned from it (caused by GetBroadcastStatsRequest)`

So I recommend the feature is viewing the forwarder channel name in a public group.

**Comment by Disk6969** [comment]
who told you you can only get channel id, access the .chat in message.forward

**Comment by ChoiHwaa** [comment]
There are no names in the [MessageFwdHeader](https://core.telegram.org/constructor/messageFwdHeader) object returned by Telegram on public channels either. Most of this object is optional.

```
MessageFwdHeader(
date=datetime.datetime(2022, 6, 9, 14, 43, 5, tzinfo=datetime.timezone.utc), imported=False,
from_id=PeerChannel(channel_id=1234346854), from_name=None, channel_post=1028, post_author=None,
saved_from_peer=None, saved_from_msg_id=None, psa_type=None)
```

**Comment by Lonami** [comment]
If Telegram sent the channel in the update, `message.forward.chat` should be that object and should contain the name. Closing since there's not much else the library can do.
