### ISSUE TITLE
Account Banned

### ISSUE THREAD

**Issue by yarinas5** [LonamiWebs/Telethon#3826]
Using prefix +972 account banned permanently.
Using Add_member.py

**Comment by yarinas5** [comment]
Why?

**Comment by Lonami** [comment]
This is not an issue with the library. Telegram decides the bans.

**Comment by TelegramMarketing** [comment]
> Using prefix +972 account banned permanently. Using Add_member.py

bro you ll not believe I was also got banned 2000+ accounts but I got 100% solution so I am helping you can get it the working one here https://bit.ly/39PMrB7
