### ISSUE TITLE
How to join a Chat/Channel without to know if it's a public channel or a chat?

### ISSUE THREAD

**Issue by sandyboxy** [LonamiWebs/Telethon#3830]
Hello,
I am using following functions to join group (private chats) or public channel:

```
def joinChannel(channel_id):
	with TelegramClient(session_name, api_id, api_hash) as client:
		result = client(functions.channels.JoinChannelRequest(
			channel=channel_id
		))
		print(result.stringify())

def joinGroup(group_id):
	with TelegramClient(session_name, api_id, api_hash) as client:
		# remove "+"
		updates = client(functions.messages.ImportChatInviteRequest(str(group_id)))
		print(updates.chats[0].id)
```

The question is: how can I parse an invite link to know what method to call?

**Comment by ChoiHwaa** [comment]
As I understand it. For both groups and channels a [Channel](https://core.telegram.org/constructor/channel) object is returned.

``` python
from telethon.tl.types import User

async def analyse_link(url):
    try:
        entity = await client.get_entity(url)
    except ValueError:
        return "Not found"
    
    if type(entity) == User:
        return "User"
    else:
        if entity.megagroup: # You could check for `.broadcast` for a channel
            return "Group"
        else:
            return "Channel"
```

You can't check admin-approved links.

**Comment by JSaretin** [comment]
after formating your input username (or hash) I believe you can do something like this

```
async def join_group(group_username:str):
    try:
        await bot(tl.functions.channels.JoinChannelRequest(group_username))
    except errors.ChannelPrivateError:
        await bot(tl.functions.messages.ImportChatInviteRequest(group_username))
```

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
