### ISSUE TITLE
wrong value in reply_to_top_id in messageReplyHeader

### ISSUE THREAD

**Issue by maloknsi** [LonamiWebs/Telethon#3831]
**Checklist**
* [+] The error is in the library's code, and not in my own.
* [+] I have searched for this issue before posting it and there isn't a duplicate.
* [+] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
async with TelegramClient(bot_session, api_id, api_hash) as telebot:
	@telebot.on(events.NewMessage(pattern='.*'))
	async def handler(event):
                print('event.message.reply_to > ', event.message.reply_to)
...

```

**Traceback**
```
1. message from channel -> comment
event.message.reply_to >  MessageReplyHeader(reply_to_msg_id=436, reply_to_peer_id=None, reply_to_top_id=None)

2. quote message from channel -> comment
event.message.reply_to >  MessageReplyHeader(reply_to_msg_id=441, reply_to_peer_id=None, reply_to_top_id=436)

3. quote  message from chat channel
event.message.reply_to >  MessageReplyHeader(reply_to_msg_id=439, reply_to_peer_id=None, reply_to_top_id=None)

```
i think the reply_to_peer_id variable should be set in example 1 and not in example 2 because at this stage it is impossible to understand the answer to the message was in the chat or is it just a simple message from the comments of the channel

**Comment by Lonami** [comment]
Telethon is not changing the `reply_to` in any way. It's just the (confusing) way in which Telegram handles channel comments unfortunately.

Channel comments are replies to the corresponding message in the linked discussion group and are probably indistinguishable from normal replies.
