### ISSUE TITLE
`client.get_entity()` returns `participants_count` as None always

### ISSUE THREAD

**Issue by dsharma522** [LonamiWebs/Telethon#3836]
When we iterate the channels as 
```python
channels = {  d.entity.username: d.entity
                for d in client.get_dialogs()
                if d.is_channel
             }
```
we get `participants_count` field with appropriate value (i.e. some count but not `None`)

But we when get the channel entity by 
```python
client.get_entity(channel.id)
```
We get all the fields as in original channel iterating but `participants_count` field is always `None` in this case. 

I mannually provided the ID of the channel to the function where the participant_count is avaialble but `get_entity()` still gives that field as `None`

**Comment by Lonami** [comment]
That field is the count of bots in the channel.
