### ISSUE TITLE
How to get access to messages from big channel?

### ISSUE THREAD

**Issue by KindSpidey** [LonamiWebs/Telethon#3838]
Hello guys. I havent find any answer to this, can you help me?

I am trying to listening official Binance Announcments channel, but getting error 
```
ValueError: Cannot find any entity corresponding to "Binance Announcements"
Task exception was never retrieved
```
My code is
```
from telethon import events, TelegramClient
client = TelegramClient("NEW", config.TELEGRAM_ID, config.TELEGRAM_HASH)
@client.on(events.NewMessage(chats=("Binance Announcements")))
async def normal_handler_coinbase(event):
    data = event.message.message
    if ("Binance Will List" in data):
        token = data.split(".")[0].split("(")[1].split(")")[0]
```
Why this is happening and how i can connect to this channel to get messages from it?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by KindSpidey** [comment]
> Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

Ok, thanks. But if you know the problem, can you help me now here?

**Comment by fukemy** [comment]
bot is not subscribe to this channel so can not receive message, I guest so. Do you have any solution?
