### ISSUE TITLE
hide log message: File lives in another DC

### ISSUE THREAD

**Issue by milahu** [LonamiWebs/Telethon#3840]
i get many `File lives in another DC` log messages with [tg-archive](https://github.com/knadh/tg-archive)

first i was worried, as they looked like error messages (file could not be downloaded)
but then i saw the retry logic in

https://github.com/LonamiWebs/Telethon/blob/dd51aea4db90fd255a14e27192e221c70b45e105/telethon/_client/downloads.py#L80-L84

can we move this log message to loglevel debug?

**Comment by Lonami** [comment]
No, `info` should be fine, since this operation is kind of expensive the first time it's done. Python's `logging` documentation may explain how to filter this one out if it bothers particular users.

**Comment by milahu** [comment]
ok. can we rephrase the log message?
something like "File lives in another DC. Retrying download"

> how to filter this one out

```py
client = TelegramClient(session, config["api_id"], config["api_hash"])

client_logger = client._log["telethon.client.downloads"]
client_logger._info = client_logger.info
def patched_info(*args, **kwargs):
    if args[0] == "File lives in another DC":
        return client_logger.debug(*args, **kwargs)
    client_logger._info(*args, **kwargs)
client_logger.info = patched_info
```

**Comment by Lonami** [comment]
Sorry, I don't really understand the concern, the log message is info and not warning or error for this reason.
