### ISSUE TITLE
telethon.errors.rpcerrorlist.MsgIdInvalidError when fetching the replies to the message

### ISSUE THREAD

**Issue by dsharma522** [LonamiWebs/Telethon#3841]
When I am trying to fetch the replies for a message via `client().iter_messages(channel, reply_to=msg_id)` , 
for some messages, i get the replies , but for some , it get the error as 
`telethon.errors.rpcerrorlist.MsgIdInvalidError:The message ID used in the peer was invalid (caused by GetRepliesRequest)` 
while that message exists and `client().iter_messages(channel)` is also listing that message

Any ideas for this? 
Also i confirmed that those messages are not sent by the Bot and i am using the telegram api not the Bot api.

**Comment by Ori-Pixel** [comment]
same issue here. The message is listed when I iterate over the channel, but if I try and target this message it doesn't work. I tried joining the channel thinking that may help, but no change. Minimal example:

channel: https://t.me/readovkanews
post_ID: 39035
```
from telethon.sync import TelegramClient
name = 'anon'
api_id = 'xxxxxxx'
api_hash = "xxxxxxxxxxxxxxxxxxxx"
channel = "https://t.me/readovkanews"
post_ID = 39035

client = TelegramClient(name, api_id, api_hash)
async def main():
    async for comment_replies in client.iter_messages(channel, reply_to=post_ID):
        print(vars(message))


with client:
    client.loop.run_until_complete(main())
```

In another channel, it only works if I'm actively iterating over messages selecting message id, which means I can't get the replies from forwarded messages.

**Comment by Lonami** [comment]
> channel: https://t.me/readovkanews
> post_ID: 39035

Telegram Desktop tells me "Message doesn't exist." so I can no longer try that. However I tried with another channel with comments and it worked just fine so I'll close the issue assuming there's no bug. If it persists let me know. See also #3837.

**Comment by WRainbow1** [comment]
Hi, having a similar issue.
Channel: https://t.me/s/PepeMatter
post_ID: 14327

**Comment by TimofeiStepanov** [comment]
It happens if the channel owner deletes base post . You can use try/exception to skip deleted post. 

```
try:
    async for comment_replies in client.iter_messages(channel, reply_to=post_ID):
        print(vars(message))
exept:
    pass

```
