### ISSUE TITLE
Account blocking

### ISSUE THREAD

**Issue by nsplife2** [LonamiWebs/Telethon#3843]
I use version 1.24 everything worked fine, but about 5 days ago problems started, accounts were banned.
I registered an account from the official application, performed actions as soon as I authorize through Telethon for 3-5 minutes and the account is blocked

**Comment by nuqz** [comment]
The same problem here with v1.24. I've been chatting with Telethon client for a while (no more that 10 messages in both directions) and caught a ban.

**Comment by nsplife2** [comment]
> The same problem here with v1.24. I've been chatting with Telethon client for a while (no more that 10 messages in both directions) and caught a ban.

for me it helped so far by specifying this data similar to real
app_version = '3.7.3'
system_version = 'Windows 10'
device_model = I put a random motherboard from the list

try it might help you too

**Comment by ZE1L** [comment]
> > The same problem here with v1.24. I've been chatting with Telethon client for a while (no more that 10 messages in both directions) and caught a ban.
> 
> for me it helped so far by specifying this data similar to real app_version = '3.7.3' system_version = 'Windows 10' device_model = I put a random motherboard from the list
> 
> try it might help you too

towards what he refers too it would look like this:

without proxy:
client = TelegramClient(phone, api_id, api_hash, device_model="iPhone 13 Pro Max", app_version = '3.7.3', system_version = 'Windows 10')

with proxy:

client = TelegramClient(phone, api_id, api_hash, proxy=('HTTP', 'ip address', port, True, 'username', 'password'), device_model="iPhone 13 Pro Max", app_version = '3.7.3', system_version = 'Windows 10')

this is randomized info, of course you wont put "iphone" with windows 🤣

**Comment by ghost** [comment]
id 64 bit got banned hahahhaha

**Comment by Lonami** [comment]
See #824.

**Comment by askoriy** [comment]
I had banned 3 different accounts almost immediately after login with Telethon. Before these accounts worked for several weeks on my mobile phone with no problems.
Now all these phones numbers fired additionally to my main account that was banned at the end of April after about two years of using with Telethon (subscribed and stored one channel messages).
Tried to contact Telegram support but got only silence.

@Lonami  **Please write an advertisement on the main page that using of Telethon has a risk of banning phone number**

until gathering enough information to understand the reason for bans and mitigate it.
