### ISSUE TITLE
Invite to channel with InviteToChannelRequest

### ISSUE THREAD

**Issue by vmail** [LonamiWebs/Telethon#3845]
Hi, I can invite someone to a group with InviteToChannelRequest but it does not work when I try to invite them to a channel. I'm the admin of the channel

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
