### ISSUE TITLE
`iter_messages()` returns empty message when `offset_date` is `1970-01-01` and `reverse=True` 

### ISSUE THREAD

**Issue by dsharma522** [LonamiWebs/Telethon#3847]
`iter_messages()`, returns **empty messages** when  `offset_date` is `1970-01-01` and `reverse=True`  
but it **returns messages** when `offset_date` is changed to `1970-01-02` and `reverse=True`

Returns No messages or empty list
```python
date_offset=dateutil.parser.parse('1970-01-01').replace(tzinfo=tz.tzoffset('UTC', 0))
for conversation in self._telegram_client.iter_messages(channel, offset_date=date_offset, reverse=True):
     pass
```

Returns messages as expected
```python
date_offset=dateutil.parser.parse('1970-01-02').replace(tzinfo=tz.tzoffset('UTC', 0))
for conversation in self._telegram_client.iter_messages(channel, offset_date=date_offset, reverse=True):
     pass
```

**Comment by ChoiHwaa** [comment]
I have to disagree. This is the equivolent of setting the date to (1970, 1, 1). I got back the first message alright.

``` python
import datetime
from telethon.tl.types import MessageService

async def first_msg(event, params):
    msgs = event.client.iter_messages(event.chat, offset_date=datetime.timedelta(0), limit=1, reverse=True)
    async for msg in msgs:
        # How do I handle unsupported messages?
        if type(msg) == MessageService:
            await event.respond(str(msg))
        else:
            await event.respond(msg)
```
Check your error catching, you might be missing important errors.

**Comment by dsharma522** [comment]
I am not getting any error at all. I do not know, what am i missing ?😩

how does `datetime.timedelta(0)` is equivalent to `(1970, 1, 1)` ? 
I ran the above , it shows me date as `2022-06-13 00:00:00`

**Comment by ChoiHwaa** [comment]
I have done some digging and I have dug up a problem with the datetime class in which it doesn't handle the zero epoch `datetime(1970, 1, 1)` correctly on all platforms. The solution is to not use this date or anything below it. Finally, call `timestamp()` on the datetime object when you pass it to `iter_messages()` or it will return messages slightly off the date you requested. Just don't use the datetime object, use timestamps or ints instead. If you want to return messages from the very beginning you can use `offset_date=0` and it will work.

`timedelta(0)` equals the zero epoch and that's why it works. On its own it doesn't mean anything.

**Comment by dsharma522** [comment]
Thanks @ChoiHwaa 😅😅
I have one more question . 
can we fetch participants/users incrementally. 

```bash
for user in self._telegram_client.iter_participants(channel):
     print(user)
```

This loop will be runnning untill we get all the participants.
My question is this, is there any way to fetch users incrementally similar to message where we can fetch incrementally messages using `date_offset` ? 
Any way to achieve this incremental process? 

The reason is , due to interruption of network, i do not want to fetch all users again and again. Instead i want to fetch next users after i fetched in previous run

**Comment by ChoiHwaa** [comment]
@dsharma522 about your question, unfortunately not.

You can join the telegram group to ask questions https://t.me/TelethonChat and
you can view the official documentation https://docs.telethon.dev.
