### ISSUE TITLE
How to fetch users incrementally 

### ISSUE THREAD

**Issue by dsharma522** [LonamiWebs/Telethon#3849]
I have one more question . 
can we fetch participants/users incrementally. 

```bash
for user in self._telegram_client.iter_participants(channel):
     print(user)
```

This loop will be runnning untill we get all the participants.
My question is this, is there any way to fetch users incrementally similar to message where we can fetch incrementally messages using `date_offset` ? 
Any way to achieve this incremental process? 

The reason is , due to interruption of network, i do not want to fetch all users again and again. Instead i want to fetch next users after i fetched in previous run

_Originally posted by @dsharma522 in https://github.com/LonamiWebs/Telethon/issues/3847#issuecomment-1155266107_

**Comment by Lonami** [comment]
A parameter for the offset is not planned, with the goal to prevent possible future breakage if Telegram ever changes how members are fetched.
