### ISSUE TITLE
Telegram API restricts features provided by telethon?

### ISSUE THREAD

**Issue by teplinsky-maxim** [LonamiWebs/Telethon#3850]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
from telethon.sessions import MemorySession
from telethon.tl.functions.channels import JoinChannelRequest

# initialize your session and client
session = MemorySession(...)

client = TelegramClient(
    session,
    api_id,
    api_hash,
    ...
)

# join entity
entity = await client.get_entity('TelegramTips')
await client(JoinChannelRequest(entity))


```

**Traceback**
```
Traceback (most recent call last):
...
  File "/home/my-fancy-file.py", line 132, in fancy-func
    await client(JoinChannelRequest(entity))
  File "/home/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/venv/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.ChannelsTooMuchError: You have joined too many channels/supergroups (caused by JoinChannelRequest)
```
I ran into a problem, where I try to join a group\channel, but API sends me `telethon.errors.rpcerrorlist.ChannelsTooMuchError`. My first assumption was the real limit, but then I created a brand new account, and API sends me the same error. It was unexpected, so I joined in the new account using official tdesktop app, and I saw no entities in the account. I tried to join some groups and channels, did it successfully. Moreover I was able to leave them using my unofficial client (there are `await client(LeaveChannelRequest(entity))` and `client.delete_dialog(entity)` calls to do so). So the question is, can Telegram API detect telethon somehow? I understand, that it is not related to the library directly, but looks like something exposes calls, which telethon does (order of RPC calls or smth. like that). Are there any recommendation or similar issues? 

Version: 1.24.0

**Comment by Lonami** [comment]
Telegram decides the limits. For new accounts it's probably to prevent spam. There's nothing the library can do about it.
