### ISSUE TITLE
How to find separate member from chat

### ISSUE THREAD

**Issue by ITZ-ZAID** [LonamiWebs/Telethon#3855]
How to find separate user in a chat?

Like get_chat_member(chat, user_id) in PyroGram

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
