### ISSUE TITLE
Unable to turn off notifications in a private channel

### ISSUE THREAD

**Issue by supirdupir** [LonamiWebs/Telethon#3856]
I'm trying to turn off notifications, but an exception occurs:

`TypeError: a TLObject was expected but found something else`

Several solutions I have tried (not working):

1.
` client(functions.account.UpdateNotifySettingsRequest(peer=1726627609, settings=types.InputPeerNotifySettings(show_previews=False, mute_until=datetime(2023, 6, 25), sound='none')))                                
`

2.
`
ent = client.get_input_entity("https://t.me/+miva_ouNLio0MjE8")
client(functions.account.UpdateNotifySettingsRequest(peer=ent, settings=types.InputPeerNotifySettings(show_previews=False, mute_until=datetime(2023, 6, 25), sound='none'))) 
`

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
