### ISSUE TITLE
Add an is_premium parameter

### ISSUE THREAD

**Issue by rscx-r1** [LonamiWebs/Telethon#3859]
Early of this moment Telegram added a premium and in yours library User class doesn't have is_premium parameter

**Comment by Emojigit** [comment]
According to https://t.me/TelethonUpdates/1278,

> This branch has been updated to the latest layer (#3862) (meaning, you can now detect premium users). You can use the same command to update.

**Comment by Lonami** [comment]
Closing. As pointed out, this is possible in the v1.24 branch (and latest PyPi version).
