### ISSUE TITLE
InviteToChannelRequest (ChatWriteForbiddenError)

### ISSUE THREAD

**Issue by windx13** [LonamiWebs/Telethon#386]
Hello, Lonami!
I'm trying to add a user to the supergroup, but there is such an error:

> Traceback (most recent call last):
> File "F:/Python_Code/TeleNew/Inviter.py", line 37, in <module>
>   result = client.invoke(InviteToChannelRequest(input_channel, [input_user, input_user2]))
> File "C:\Python34_32\lib\site-packages\telethon\telegram_bare_client.py", line 461, in __call__
>   sender, call_receive, update_state, *requests
> File "C:\Python34_32\lib\site-packages\telethon\telegram_bare_client.py", line 517, in _invoke
>   raise next(x.rpc_error for x in requests if x.rpc_error)
> telethon.errors.rpc_error_list.ChatWriteForbiddenError: (ChatWriteForbiddenError(...), "You can't write in  this chat")

My code:
```
GROUP = 'public_name_group'
USER = 'nickname_user'

client = TelegramClient('session_name', api_id, api_hash)
client.connect()

result = client(ResolveUsernameRequest(GROUP))
input_channel = InputChannel(result.peer.channel_id, result.chats[0].access_hash)

user = client(ResolveUsernameRequest(USER))
input_user = InputUser(user.users[0].id, user.users[0].access_hash)

result2 = client(InviteToChannelRequest(input_channel, [input_user]))
print(result2)
```

In a supergroup, each participant can add other participants. Everyone has a right to this. What am I doing wrong?

**Comment by Lonami** [comment]
Have you tried adding such user to such group through official clients? Does it actually work?

**Comment by windx13** [comment]
I apologize, apparently, Telegram changed something at home. Earlier it was possible, and now even in the official client there is no such possibility.

**Comment by Lonami** [comment]
So I guess you really don't have the permission anymore. Not much we can do!
