### ISSUE TITLE
Read receipts

### ISSUE THREAD

**Issue by bffrahul** [LonamiWebs/Telethon#3860]
I'm a newbie to Telethon. Seems like read receipts of a group message aren't available or I can't find. Can you help?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by bffrahul** [comment]
Hi Lonami,

Thanks for the link on Github.

*Can you please delete this issue*?
https://github.com/LonamiWebs/Telethon/issues/3860 . It looks so childish
now. 😳

Thanks in advance.

Rob
