### ISSUE TITLE
RPCError 400: GROUPCALL_INVALID (caused by InviteToGroupCallRequest)

### ISSUE THREAD

**Issue by zxllkada** [LonamiWebs/Telethon#3864]
RPCError 400: GROUPCALL_INVALID (caused by InviteToGroupCallRequest)

Am sure I pass cureect vars but I got this error. in single client its working but when I use it with a group of client ( with client ) its not working.. why?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
