### ISSUE TITLE
How to get 10,000+ members from Telegram group

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaavc** [LonamiWebs/Telethon#3866]
I am currently using [GetParticipantsRequest](https://tl.telethon.dev/methods/channels/get_participants.html) to get members from Telegram group I tried on group 20k , 45k 132k members but only got 10k members why?
I tried using `WTelegramClient` library on `C#` and I can get almost 100% group members

Telethon still has a function called `get_participants` but it can only be used with small groups, I try it on a group of more than 5000 members, there will be an error,
When I set `aggressive=False` got the error `'ChannelParticipants' object is not subscriptable`

When I set `aggressive=True` I get an error `FloodWait....`

**Comment by Lonami** [comment]
Telegram does not allow this.

**Comment by jerry199507** [comment]
Did you find a solution?
