### ISSUE TITLE
Send_message didn't work correctly.

### ISSUE THREAD

**Issue by boxxello** [LonamiWebs/Telethon#3868]
Hello guys! I'm currently forwarding messages from a telegram channel to another channel.

The thing is: I'm using send_message from Telethon Client to send messages.
It all went well since this morning a message hasn't been forwarded.
I log basically everything, but the message has arrived correctly (the incoming event) but it hasn't been forwarded. 

Now from the docs:
https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.messages.MessageMethods.send_message

I don't see a way to check if the api request has been sent correctly by getting the return value from the request.

How could I achieve such thing and is it possible?
I don't actually know what really went wrong, it could be a bunch of things, but to prevent this from happening again what could I do?

**Comment by Lonami** [comment]
If you await and it returns, it succeeds. If it raises, it failed (and with logging enabled you should be seeing why).

**Comment by boxxello** [comment]
You're absolutely right, it was my bad, I checked the logs incorrectly, the message got sent straight away and it actually logged.

May I ask another question without opening another issue if possible?
Sometimes it happens that I miss a Deleted event here and there.

(It could also be due to the connection obviously), but what would be the best way to implement a check on it? 
Store the messages and re-send / edit / delete them if the records change? So performing an iter messages on the whole chat and then updating the -forward channel chat-? 
Thank you in advance and sorry about the other one.

**Comment by Lonami** [comment]
Delete events are not reliably sent by the Telegram server in my experience (although the [v1.24 branch](https://t.me/TelethonUpdates/1276) should catch up on missed updates correctly, including deletes).

**Comment by boxxello** [comment]
I'll give that a try! Thank you for the support and the API itself!

Have a nice day!
