### ISSUE TITLE
How to generate a 32KB session file?

### ISSUE THREAD

**Issue by zixingonline** [LonamiWebs/Telethon#3871]
I saw that other people's session file is 32KB, but my own generated session file is only 28KB.

Then I parsed the session file and found that there was an encrypts table in their SQLite.

There are three fields "word, time, key" in the encrypts table. The word and key fields are encrypted by MD5. What is the function? Does anyone know what this watch is for?

![1657622381209](https://user-images.githubusercontent.com/51315718/178472159-b24690ff-82a9-49da-ae0c-abc42c963a8f.jpg)
![1657622408676](https://user-images.githubusercontent.com/51315718/178472165-1276175a-5d43-4f83-991b-ba0c73f97a58.jpg)

**Comment by Lonami** [comment]
Achieving a specific session size is not a goal for Telethon. The "encrypts" table is not something Telethon has ever used as far as I can remember. Make sure you're using trustworthy versions of the library.

**Comment by zixingonline** [comment]
> Achieving a specific session size is not a goal for Telethon. The "encrypts" table is not something Telethon has ever used as far as I can remember. Make sure you're using trustworthy versions of the library.

Do you mean that the extra encrypts table was deliberately added? It doesn't really work, does it?
