### ISSUE TITLE
Broken link on releases page

### ISSUE THREAD

**Issue by lorien** [LonamiWebs/Telethon#3874]
On the page https://github.com/LonamiWebs/Telethon/releases the link to changelog is broken, see screenshot.
![2022-07-16_01-26](https://user-images.githubusercontent.com/35171/179319200-2834b6c9-282d-4f01-b158-b2154570bb15.png)

**Comment by Lonami** [comment]
That's from 2018. I do not retroactively update old posts and do not intend to do so (it would be a lot of work), so I am going to close this issue. Currently change-log can still be accessed in https://docs.telethon.dev/en/stable/misc/changelog.html though.

**Comment by Lonami** [comment]
Ah nevermind the release straight up says to check the changelog which is broken. I've updated it. Thanks.
