### ISSUE TITLE
FloodWait Error: A wait of 3600 seconds is required (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))

### ISSUE THREAD

**Issue by LPeng111** [LonamiWebs/Telethon#3875]
Hello, I have a problem using Telethon v1.24.
I logged into my Telegram account on Android app and tried to get some group messages through Telethon, but I encountered this problem when logging in using Telethon.

```
Traceback (most recent call last):
  File "E:/PycharmProjects/TelethonTest/test_package/test2.py", line 11, in <module>
    with TelegramClient(username, api_id, api_hash, proxy=proxy).start() as client:
  File "D:\python_env\python37\lib\site-packages\telethon\client\auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "D:\python_env\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "D:\python_env\python37\lib\site-packages\telethon\client\auth.py", line 140, in _start
    await self.connect()
  File "D:\python_env\python37\lib\site-packages\telethon\client\telegrambaseclient.py", line 542, in connect
    LAYER, self._init_request
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 3600 seconds is required (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))

Process finished with exit code 1

```
My code is as follows
```python
username = 'xxx'
api_id = 11123
api_hash = 'xxx'
proxy = (socks.SOCKS5, '10.1.130.172', 30199)

with TelegramClient(username, api_id, api_hash, proxy=proxy).start() as client:
    print(client.get_me())

```

I have also tried to sign up my account on Telegram Desktop, and it works very well.
![screenshot](https://user-images.githubusercontent.com/39934458/179455701-be379c3f-c433-459c-8baa-ff3525a9c1a6.png)

So, I want to know what is the cause of this problem, and how should I solve it?

**Comment by Lonami** [comment]
This error comes from Telegram and there is nothing Telethon can do to "bypass it" or "fix it".

**Comment by LPeng111** [comment]
Does that mean I can't sign in this account using Telethon later?

**Comment by LPeng111** [comment]
> This error comes from Telegram and there is nothing Telethon can do to "bypass it" or "fix it".

Does that mean I can't sign in this account using Telethon later?

**Comment by Lonami** [comment]
The error says you have to wait. Waiting should eventually resolve it. This is probably a new Telegram measure to prevent spam.
