### ISSUE TITLE
If there are too many group messages, it will get stuck when use "iter_messages"

### ISSUE THREAD

**Issue by hhxdestiny** [LonamiWebs/Telethon#3882]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
...
dlgs = client.loop.run_until_complete(client.get_dialogs())
for dlg in dlgs:
    log.logger.info(f'name: {dlg.name}, title: {dlg.title}')
    its = client.iter_messages(dlgs[0].id, reverse=True)
    cnt = 0
    for it in its:
        cnt += 1
    log.logger.info(fcount: {cnt}')
```

**Log**
```
[2022-07-22 15:58:24,041 INFO]: Sleeping for 3s (0:00:03) on GetHistoryRequest flood wait
[2022-07-22 16:04:32,009 INFO]: Sleeping for 3s (0:00:03) on GetHistoryRequest flood wait
```
**Question**
Hi, will the traversal group messages get stuck?
Sometimes I get news such as "Sleeping for 3s (0:00:03) on GetHistoryRequest flood wait" or reconnection news, and then there is no news.
If there are a lot of group messages, how can I get all group messages gracefully?

**Comment by Lonami** [comment]
The error comes from Telegram to prevent API abuse. It is not something the library can fix. You should use events if you want to constantly monitor group messages (see the documentation).
