### ISSUE TITLE
Is account.checkUsername#2714d86c username:string = Bool working ?

### ISSUE THREAD

**Issue by nprime496** [LonamiWebs/Telethon#3886]
**Checklist**
* [ X] The error is in the library's code, and not in my own.
I used snippet code from the documentation.

* [X ] I have searched for this issue before posting it and there isn't a duplicate.
I couldn't find something similar.

* [ X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
I tried it but it just broke everything ( `no module found 'markdown_it'` ) so I unistalled and ran `pip install telethon` again.

I am using the code snippet from the documentation of [CheckUsernameRequest](https://tl.telethon.dev/methods/account/check_username.html) and it just doesn't work. I tried it with a lot of usernames and channel names .  It keeps saying that they don't exist but they DO.

Here are a few I tested : 
* https://t.me/lexfridman
* https://t.me/tagliafi

 Am I doing something wrong ? Is it broken ?

PS: I don't understand the result type either, it's supposed to be a **bool** but I find myself dealing with obscure [coroutine](https://docs.python.org/fr/3.7/library/asyncio-task.html) stuffs.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
from telethon import functions, types

with TelegramClient('session_name', api_id, api_hash) as client:
    result = client(functions.account.CheckUsernameRequest(
        username='lexfridman'
    ))
    if result == True:
        print("yAY")
    else:
        print("pOUAH")

```

**Traceback**
pOUAH

**Comment by Lonami** [comment]
You're using raw API, meaning you're at the mercy of whatever the Telegram server says. Telethon is not changing the result or request behind your back (other than resolving to input types, not the case here). This means it's not something we can "fix". This is probably done to prevent abuse (e.g. the request that checked if an account existed had the same treatment, now you must try to login and fail to find out).
