### ISSUE TITLE
iter_messages 4125 limit for channels

### ISSUE THREAD

**Issue by Ori-Pixel** [LonamiWebs/Telethon#3888]
I'm scraping Telegram data with Telethon, and it appears that iter_messages() on a channel maxes out at 4125 requests regardless of sleep timer. When using verbose logging, it completes successfully, no indication of a timeout. I'm thinking the best course of action would be to get the ID of the most recent message in the channel, then passing chunks of 3k requests until it hits that ID.

```
from telethon.sync import TelegramClient
name = 'anon'
api_id = 'xxxxxxxx'
api_hash = "xxxxxxxxxxxxxxxxxxxxxxx"

Minimal example:
async def main():
        async for message in client.iter_messages(channel_name, offset_date=datetime.timedelta(0), limit=None, reverse=True):
            print(message.id, ",", message.date, ":", message.text)
            print("\n")
```

**Comment by Lonami** [comment]
No such limit exists in the library, closing under the assumption it's some sort of limit from Telegram.
