### ISSUE TITLE
account banned after login client

### ISSUE THREAD

**Issue by deFang** [LonamiWebs/Telethon#3889]
I use the api_id and api_hash registered with my account（https://my.telegram.org/auth） to log in to listen for messages on a certain channel, the code is as follows.

```
client = TelegramClient('session_name', TELEGRAM_SETTING['api_id'], TELEGRAM_SETTING['api_hash'])
await client.start()

@client.on(events.NewMessage(chats=TELEGRAM_SETTING['channel_id']))
    async def handler(event):
         handle_message(event)
     return
```

But every time I run the program for 20 hours or so, my account is banned. 
I have tried 4 times, yes, I have registered 4 new accounts and all of them end up the same thing, can you help me what is going on?

**Comment by Lonami** [comment]
See #824.
