### ISSUE TITLE
After using InviteToChannelRequest, but in group that member not listed

### ISSUE THREAD

**Issue by swjung703** [LonamiWebs/Telethon#3897]
**Checklist**
* [O] The error is in the library's code, and not in my own.
* [O] I have searched for this issue before posting it and there isn't a duplicate.
* [O] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

My code is below.

with TelegramClient(name, api_id, api_hash) as client:
    result = client(functions.channels.InviteToChannelRequest(
        channel='test',
        users=['test']
    ))
    print(result.stringify())
    

I invited the main account to the test (megagroup) using my sub-account.

As shown below, an invitation message occurred within the group, but the invited people are not displayed in the group user list.

![image](https://user-images.githubusercontent.com/11012703/183243675-c46244c9-7ef3-4f77-9187-4fd9102c3524.png)

Also, I can't see the invited groups in my main account. This means that there are no invited groups in the chat list on my main account.

**Comment by Lonami** [comment]
You're using raw API, meaning the behavior you are getting is whatever Telegram intends it to be, and Telethon cannot fix it in any way.
