### ISSUE TITLE
Issue in installing Telethon on qpython3

### ISSUE THREAD

**Issue by parazitt** [LonamiWebs/Telethon#390]
Hello Dear, 
I want to install telethon on qpython3(android) with pip, but i got this error:

> python setup.py install
> Failed to import TelegramClient due to No module named rpc_error_list
> Generating TLObjects...
> Traceback (most recent call last):
>   File "setup.py", line 153, in <module>
>     main()
>   File "setup.py", line 98, in main
>     gen_tl()
>   File "setup.py", line 62, in gen_tl
>     generator.generate_tlobjects(SCHEME_TL, import_depth=IMPORT_DEPTH)
>   File "/storage/emulated/legacy/com.hipipal.qpyplus/scripts3/Telethon-master/telethon_generator/tl_generator.py", line 45, in generate_tlobjects
>     os.makedirs(self._get_file('functions'), exist_ok=True)
>   File "/data/data/com.hipipal.qpy3/files/lib/python3.2/python32.zip/os.py", line 152, in makedirs
> OSError: [Errno 17] File exists: 'telethon/tl/functions'
> 1

Where is my problem? can you help me?

**Comment by Lonami** [comment]
> os.makedirs(self._get_file('functions'), exist_ok=True)
File "/data/data/com.hipipal.qpy3/files/lib/python3.2/python32.zip/os.py", line 152, in makedirs
OSError: [Errno 17] File exists: 'telethon/tl/functions'

`makedirs(exist_ok=True)`

This is supposed to ignore the error if the directory already exists. I'm not sure why this happened.

**Comment by andreif** [comment]
@parazitt Try running `setup.py develop`. The problem is that you generate python modules in the repo directory, while you need them in the destination path where you use them.

**Comment by andreif** [comment]
Ah, sorry, this seems not related to #391.

**Comment by Lonami** [comment]
After revisiting this issue I looked up what "QPython" exactly was, and seems like you want [Python on Android](http://www.qpython.com/). While I'm sure the guys over QPython have worked hard to make it work, I would advice you to use something like [Termux](https://termux.com) which you can download from [F-Droid](https://f-droid.org/packages/com.termux/) for free. You can install both Python and Telethon with no issue there:
```
pkg install python
pip install telethon
python
from telethon import TelegramClient
```

**Comment by Lonami** [comment]
I've closed the issue because:
```python
os.makedirs(self._get_file('functions'), exist_ok=True)
```

The `exist_ok=True` part is explicitly there so this error:
> OSError: [Errno 17] File exists: 'telethon/tl/functions'

Is ignored, but it's not.

**Comment by sundarrinsa** [comment]
showing this error.

Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    from telethon import TelegramClient, sync
  File "C:\Python33\lib\site-packages\telethon\__init__.py", line 2, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "C:\Python33\lib\site-packages\telethon\telegram_bare_client.py", line 9, in <module>
    from . import version, utils
ImportError: cannot import name version

**Comment by Lonami** [comment]
@sundarrinsa #937.
