### ISSUE TITLE
messages.getMessageReactionsList support

### ISSUE THREAD

**Issue by tolia77** [LonamiWebs/Telethon#3901]
Can you add https://core.telegram.org/method/messages.getMessageReactionsList in telethon?

**Comment by Lonami** [comment]
It should already exist in v1.24 branch. See the TelethonUpdates Telegram channel.

**Comment by tolia77** [comment]
But it doesn't exist, and i haven't found anything in TelethonUpdates channel. Where can i found it?
![telethon](https://user-images.githubusercontent.com/85370550/185467220-efaf307e-3d6c-4751-af73-516425b3199e.png)

**Comment by Lonami** [comment]
The channel explains how to install the branch which should have the method. The installation may vary depending on your environment.
