### ISSUE TITLE
I can't delete the video after uploading it [WinError 32]

### ISSUE THREAD

**Issue by dustiwe** [LonamiWebs/Telethon#3902]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
client = TelegramClient(...)

file_name = message.file.name
await message.download_media(file=pathlib.Path(__file__).parent.resolve())
await client.send_file(channel,file_name,caption=message.message,allow_cache=False)
os.remove(file_name)
```

**Traceback**
```
Traceback (most recent call last):
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
```

When sending a video, I cannot delete it after sending, and after my tests it turned out only with video, with images and audio there is no such problem

**Comment by Lonami** [comment]
Videos are not treated in any special case, so it is strange that video files in particular wouldn't be closed properly. It might be large files take "longer" to close by Windows. Try sleeping a bit before attempting to remove the file.

**Comment by dustiwe** [comment]
> Videos are not treated in any special case, so it is strange that video files in particular wouldn't be closed properly. It might be large files take "longer" to close by Windows. Try sleeping a bit before attempting to remove the file.

Sleep didn't help.While the script is running, all used videos to send are not available for deletion due to this error

**Comment by Lonami** [comment]
Try using `open(video path file, 'wb')` and passing the file handle to the method. Then you can make 100% sure you close the handle, so deleting should work. If not even that works, then it's probably Windows being weird.

**Comment by Lonami** [comment]
I have tried the following code:

```python
shutil.copy(r'C:\Users\L\Desktop\a.mp4', r'C:\Users\L\Desktop\b.mp4')
await client.send_file('me', r'C:\Users\L\Desktop\b.mp4', caption='caption', allow_cache=False)
os.remove(r'C:\Users\L\Desktop\b.mp4')
```

I have not experienced any issue. Unfortunately this probably means Telethon is properly closing the file, but Windows might be acting up. I do not think there is anything that can be done by Telethon to fix this so I'll close the issue (Telethon opens and closes the file handles correctly for files being used through string paths).
