### ISSUE TITLE
trouble with python , CMD 

### ISSUE THREAD

**Issue by bigsmallninja** [LonamiWebs/Telethon#3910]
when i try and run the program of taking contacts of csv file and adding them to a group it comes up with

 `(i) Distributing CSV files...
Traceback (most recent call last):
  File "C:\Users\HOME\Desktop\telegramscraper-main\tsadder.py", line 153, in <module>
    with open('members\\members.csv', 'w', encoding='UTF-8') as f:
PermissionError: [Errno 13] Permission denied: 'members\\members.csv'

C:\Users\HOME\Desktop\telegramscraper-main>`

anyone got an idea of whats wrong

**Comment by Lonami** [comment]
This is not related to Telethon at all, so I'll close the issue as there's nothing to fix. Please note that mass adding users is considered spam and is likely to get your account banned.
