### ISSUE TITLE
Doesn't upload file

### ISSUE THREAD

**Issue by nikton079** [LonamiWebs/Telethon#3911]
I'm trying add video to message after user clicks on button. But video doesn't upload and there isn't any error

**Code that causes the issue**
```
@bot.on(events.callbackquery.CallbackQuery())
async def callback(event):
    await event.edit(buttons=[[Button.inline("Upload video")]], file="/home/user/python/videos/first.mp4") # I indicate button because I want that it stays 
```

**Comment by Lonami** [comment]
Media cannot be added or removed from existing messages. This is a Telegram limitation.
