### ISSUE TITLE
Can Telethon get tying support

### ISSUE THREAD

**Issue by dnslin** [LonamiWebs/Telethon#3913]
Dear Developer During development, I noticed that many example objects could not be inferred by `pycharm` and therefore could not be code completed. I did a google search and manually added typing to the example objects and pycharm was able to do function completion, so could Telethon please support typing as it is very painful to see how many methods a class has through the doc, if not that is fine, this is just a suggestion, thanks

**Comment by Lonami** [comment]
Unfortunately this is not a priority for me so it's unlikely I'll ever get to it. My intention is for the v1.24 branch (v1 series) to just be kept up-to-date, with little to no new features, and the master branch (v2 series) is on hold for the time being (until I get the motivation to work on it). So I don't think this will happen any time soon.

**Comment by dnslin** [comment]
okay, thank you for your reply
