### ISSUE TITLE
GetParticipantsRequest return same result for every query

### ISSUE THREAD

**Issue by jakbin** [LonamiWebs/Telethon#3915]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
alfa = ['a','b','c','d','e']
i = 0
for al in alfa:
    my_filter = ChannelParticipantsSearch(al)
    print(my_filter)
    offset = 0

    while while_condition:

        participants = client(GetParticipantsRequest(channel=from_group,  offset= offset, filter = my_filter, limit=200, hash=0))

        all_participants.extend(participants.users)
        offset += len(participants.users)

        print(len(participants.users))

        if len(participants.users) < 1 :

            while_condition = False

```
GetParticipantsRequest return same result for every query ?

**Comment by Lonami** [comment]
You are using raw API. This means whatever Telegram returns is intended and Telethon cannot "fix" it.

**Comment by jakbin** [comment]
Is there any solution for this ?
@Lonami

**Comment by jerry199507** [comment]
Did you find a solution?

**Comment by jakbin** [comment]
> Did you find a solution?

No
