### ISSUE TITLE
Can not import contacts by using ImportContactsRequest

### ISSUE THREAD

**Issue by nileshnehate769** [LonamiWebs/Telethon#3918]
can't able to add a phone number to the telegram contact list

I'm tried this code and was not able to add

also tried to add my own number to check if it works or not but can't able to add

from telethon.sync import TelegramClient
from telethon import functions, types
from telethon.tl.functions.contacts import ImportContactsRequest

with TelegramClient(name, api_id, api_hash) as client:
    result = client(functions.contacts.ImportContactsRequest(
        contacts=[types.InputPhoneContact(
            client_id=random.randrange(-2**63, 2**63),
            phone='some string here',
            first_name='some string here',
            last_name='some string here'
        )]
    ))
    print(result.stringify())

**Comment by Lonami** [comment]
You are using raw API. This means whatever results you're getting are intended by Telegram's API, and there is nothing Telethon can do to "fix" it.
