### ISSUE TITLE
Add members to channel

### ISSUE THREAD

**Issue by anon-user-com** [LonamiWebs/Telethon#3927]
I want to add user to my channel because I'm migrating from group to channel but I'm having difficulties I have found this code but it only show me groups not channels 
```

result = client(GetDialogsRequest(
             offset_date=last_date,
             offset_id=0,
             offset_peer=InputPeerEmpty(),
             limit=chunk_size,
             hash = 0
         ))
chats.extend(result.chats)
 
for chat in chats:
    try:
        if chat.megagroup== True:
            groups.append(chat)
    except:
        continue
 
print('Choose a group to add members:')
i=0
for group in groups:
    print(str(i) + '- ' + group.title)
    i+=1
 

```

**Comment by Lonami** [comment]
This is a duplicate. Adding users is considered spam. This is not a bug for Telethon to fix.

**Comment by anon-user-com** [comment]
So it's a Telegram side problem or just Telethon don't want to add it. Because with a script I have found I have add members to telegram but with username not with ID
