### ISSUE TITLE
[FEATURE REQUEST] add media file name attribute

### ISSUE THREAD

**Issue by afterdelight** [LonamiWebs/Telethon#3928]
continuing from this https://github.com/LonamiWebs/Telethon/issues/111

maybe 'message.filename' or 'message.file.name' would be good. like 'message.file.size' which already exist.
im trying to download roundvoice. thank

**Comment by Lonami** [comment]
`message.file.name` exists.

**Comment by afterdelight** [comment]
could you tell me more how to print message.file.name and link the documentation pls

i got error: NameError: name 'message' is not defined

im also trying to print 'roundvoice.file.name' by using constructor InputMessagesFilterRoundVoice
but it results in 'None' value. i can only print 'roundvoice.file.size'

sorry im a newbie in programming

**Comment by Lonami** [comment]
Sorry, but GitHub issues is not the right place to ask questions. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

Note that many questions in StackOverflow has been asked and answered. Search before asking again or your question will be removed if it's a duplicate.
The same is true for the Telethon chat. And questions related to Python and not Telethon are offtopic ("'message' is not defined" is not related to Telethon, it's Python).

Unfortunately you will likely have to learn Python elsewhere.

**Comment by afterdelight** [comment]
So some private channels or forwarded messages or file returned by bots has its file name as `None`. How do I generate filename without executing `client.download_media`?
