### ISSUE TITLE
example quart_login.py doesn't work

### ISSUE THREAD

**Issue by theRedCount** [LonamiWebs/Telethon#3929]
I've installed via pip the latest version 1.25.0
When I try to run the script I obtain this error:

```
Traceback (most recent call last):
  File "quart_login.py", line 8, in <module>
    from telethon.types import Message
ModuleNotFoundError: No module named 'telethon.types'
```

I've tried to comment rows n.8 and n.56 just for test, but it doesn't work  after I inserted API_ID and API_HASH

**Comment by Lonami** [comment]
Yeah I'm not sure what happened. `telethon.tl.types` should work in the meantime.
