### ISSUE TITLE
Add support for voice message transcription (it's in MTProto)

### ISSUE THREAD

**Issue by Hexalyse** [LonamiWebs/Telethon#3934]
Telegram Premium offers a way to transcribe voice messages into text (Speech-To-Text). This is a very useful feature that I've been trying to mimic with external STT services (like Google Speech-To-Text API) but Telegram results are way better than what I get with Google.

I think it would be great to implement into Pyrogram the 2 new updates and 2 new functions added to MTProto regarding this feature : https://corefork.telegram.org/api/transcribe

This way, it would be possible to automate the transcription of the voice messages, which could allow not only the paid premium user but also their contacts with which they are talking to see the transcriptions (which as of now, is not possible, and feels like a really cheap move from Telegram).

**Comment by Lonami** [comment]
These are available through raw API (see https://tl.telethon.dev/?q=transcribe). I have no plans to add new friendly methods to v1, but new Telegram features are always available through raw API.
