### ISSUE TITLE
Telethon doesn't work with multiple accounts

### ISSUE THREAD

**Issue by AyacosiDernOriginal** [LonamiWebs/Telethon#3935]
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 5d99adee. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: b'\xee\xad\x99]k\x00\x00\x02?\xeb0,\x01\x00\x00\x00\xd1J\xe3`n\x17n\xfe\x06seqqxx\x00\x05wttqw\x00\x00\x06\xf7\xd1\x82\x02\x00\x00\x00\xfa\xc01\x1bz\xc4II\x10\x01\x08\x08\xa9\xe5\xfe\xef\xaag9\xce\xe1E\x14P\x07\x00\x00\x00\x02\x00\x00\x00I9\xb9\xedy\x9a,c\x15\xc4\xb5\x1c\x01\x00\x00\x00a\xaca\x82D!\xd4\x01E\x14\x1d`\x00\x00\x00\x00:\xef\x96\x98\xd4\x1b?=\x1bAdopt me | Murder Mystery 2\x18Adoptme_robloxmm2_roblox\x00\x00\x00\x11\x1cn\x1c\x02\x00\x00\x00\xd2\xbc1\x1b\xcb\x98qJ\x10\x01\x08\x08\xd0\xfd\xef\xda\xfa\xfc\x9f\xa5\x14QI\r\x9f\x00\x00\x00\x02\x00\x00\x008\x90,c\x18\x04\x12\x9f\xf8\x04\x02\x00\xff\xff\xff\x7f\xd1\x99,c\x00\x00\x00\x00'

I use telethon with multiple accounts and i have this error
I use v1.25.0 telethon

When i work with 1-5 accounts i don't have problems, when i work with 20 accounts i have this problem

**Comment by AyacosiDernOriginal** [comment]
I noticed one thing that the ID is always the same, maybe it occurs only with one account?

**Comment by AyacosiDernOriginal** [comment]
Perhaps this happened because the session was cleared?

**Comment by Lonami** [comment]
This error should not be related to using multiple accounts. Telegram sometimes send types from the wrong layer and Telethon cannot parse them. Updating should fix this.

**Comment by AyacosiDernOriginal** [comment]
> Эта ошибка не должна быть связана с использованием нескольких учетных записей. Telegram иногда отправляет типы из неправильного слоя, и Telethon не может их разобрать. Обновление должно исправить это.

I using latest version(v1.25.0)

**Comment by Lonami** [comment]
Unfortunately I cannot directly fix this. Telegram is sending incorrect data it should not be sending, Telethon doesn't understand said data and can't do anything about it.

**Comment by AyacosiDernOriginal** [comment]
Thanks, how can i catch this?

**Comment by manojsitapara** [comment]
> Thanks, how can i catch this?

are you able to catch this?
