### ISSUE TITLE
`get_entity()` by phone number is not working 

### ISSUE THREAD

**Issue by dsharma522** [LonamiWebs/Telethon#3937]
**Description**

`get_entity()` is not resolving to a valid username when trying with phone_number . While it works fine if i put user_name to it. 
I provide the exactly same phone number which is got from from response when looking with username.

From library, it seems that [get_entity()](https://github.com/LonamiWebs/Telethon/blob/v1/telethon/client/users.py#L223) supports [Phone](https://github.com/LonamiWebs/Telethon/blob/v1/telethon/hints.py#L13-L21) as entity too.

#### Error is 
```
ValueError: Cannot find any entity corresponding to "<phone_number>"
```

**Steps to reproduce**
-  Get entity by username to confirm that username is valid.
-  Try to get entity by the phone_number now for the same username (can use the phone_number got from the response of lookup by username).

**Code that causes the issue**
```python

# lookup via username , works fine
user = await client.get_entity('username')
print(user)


# lookup via phone for same username , does not work
user = await client.get_entity('+9170......')
print(user)

```

However, following workaround works 
```python
user = await client.get_input_entity('91.......')
print(user)
        
user = await client.get_entity(user)
print(user)
```

**Comment by Lonami** [comment]
It's working fine for me. Current implementation should be using `GetContactsRequest` and then may be reading from cache. You can also do this manually or use the new `ResolvePhoneRequest` (never tried, no idea what that does but from the name it seems like it would do what you need it to do).
