### ISSUE TITLE
`id` property from `File` class is not calculating

### ISSUE THREAD

**Issue by swimmwatch** [LonamiWebs/Telethon#3938]
Hi! I have tried to get file ID from channel post but `id` property from [`File` class](https://github.com/LonamiWebs/Telethon/blob/v1/telethon/tl/custom/file.py) is not calculating.

**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

I run this code with 1.25.2 version.
**Code that causes the issue**
```python
from telethon.sync import TelegramClient

from config import telegram_settings

client = TelegramClient(
    "test", telegram_settings.telegram_api_id, telegram_settings.telegram_api_hash
)

with client:
    channel_name = "https://t.me/kod_podbora"
    explorer = TelethonExplorer(client)
    channel = client.get_entity(channel_name)
    for post in client.iter_messages(channel):
        if post.file:
            print(post.file.id)
```

**Traceback**
```
Traceback (most recent call last):
  File "/home/swimmwatch/Desktop/gitlab/telegram-radar/main.py", line 24, in main
    print(post.file.id)
  File "/home/swimmwatch/.cache/pypoetry/virtualenvs/telegram-radar-vimVJ2w1-py3.8/lib/python3.8/site-packages/telethon/tl/custom/file.py", line 34, in id
    return utils.pack_bot_file_id(self.media)
  File "/home/swimmwatch/.cache/pypoetry/virtualenvs/telegram-radar-vimVJ2w1-py3.8/lib/python3.8/site-packages/telethon/utils.py", line 1268, in pack_bot_file_id
    size = size.location
AttributeError: 'PhotoSize' object has no attribute 'location'
```

**Comment by Lonami** [comment]
File IDs are broken in newer versions and I don't really have plans to maintain them further (they will be entirely removed in v2).

**Comment by swimmwatch** [comment]
Ок, thanks.
