### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'get_running_loop'

### ISSUE THREAD

**Issue by Samjith888** [LonamiWebs/Telethon#3939]
**Checklist**

* [X ] The error is in the library's code, and not in my own.
* [ X] I have searched for this issue before posting it and there isn't a duplicate.
* [X ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

user_app = TelegramClient(self.session_name, self.api_id, self.api_hash).start()
...

```

**Traceback**
```
ERROR:telethon.client.updates:Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/updates.py", line 354, in _update_loop
    deadline = self._message_box.check_deadlines()
  File "/usr/local/lib/python3.6/dist-packages/telethon/_updates/messagebox.py", line 240, in check_deadlines
    now = asyncio.get_running_loop().time()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'


```

**Comment by Lonami** [comment]
You can fix this by upgrading your Python version, but I'll see if I can make it 3.6 compatible again.

**Comment by Samjith888** [comment]
Which is the minimum python version currently you are recommending ?

**Comment by Lonami** [comment]
Telethon should run fine in the latest Python version (if not, that's also a bug). I would recommend using the highest version you can.
