### ISSUE TITLE
number of retries reached 0

### ISSUE THREAD

**Issue by pedram1992** [LonamiWebs/Telethon#394]
self.connect() in my code The following error occurred: 

in telegrambare_client.py line 219
`self(getConfigRequest()).dc_options`
in telegrambare_client.py line 462 in __call__
`number of retries reached 0`

**Comment by Lonami** [comment]
#270.

**Comment by pedram1992** [comment]
i read this but my problem don't solved, my code is worked correctly for some day and this error appears after the some days, the logic of my codes is that i get updates in while loop and do some process

**Comment by Lonami** [comment]
Yeah the problem is not solved and there's an issue open with "help wanted" that wants your (or anyone else's having the issue) help.
