### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by salismazaya** [LonamiWebs/Telethon#3940]
may i add an example of django + telethon? this is for hacktoberfest

**Comment by Lonami** [comment]
Hey, thanks for the interest, I'm not currently doing hacktoberfest. I don't think a Django example is necessary, sorry.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/issues/3939 should be relatively easy to fix if you would like to send a PR for that. I also have other repositories both in this account and the LonamiWebs organization, so feel welcome to take a look and see if anything makes you interested!
