### ISSUE TITLE
Alternative url connection string

### ISSUE THREAD

**Issue by 0v3rd0s3d** [LonamiWebs/Telethon#3947]
Hey guys, i just started to read the docs and i have a simple question.

I have local network which has only one way to access internet via reverse nginx proxy.
The only way to access https://api.telegram.org/bot from my local network is to use local address http://10.10.0.1:4822/t/ behind nginx reverse proxy.
Using your library, how can i change default connection string?

Thank you in advance!

**Comment by Lonami** [comment]
There's no such thing as a "connection string". It connects directly via IP to Telegram's servers. Not the HTTP bot API URL. It's also not possible to configure the IP used.
