### ISSUE TITLE
BrokenPipeError [WinError 10058]

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#395]
This piece of code
```
client = TelegramClient(session, api_id, api_hash, proxy=proxy,
                     device_model = dev, app_version = app,
                                    system_version = ver, update_workers=1, timeout=10)
client.add_update_handler(updater)
client.connect()
client(UpdateStatusRequest(offline=False))
client(UpdateStatusRequest(offline=True))
client.disconnect()
```
sometimes raises following error:

> --- Logging error —-
> Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 844, in _recv_thread_impl
>     self.idle(stop_signals=tuple())
>   File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 822, in idle
>     self._sender.receive(update_state=self.updates)
>   File "C:\Python\lib\site-packages\telethon\network\mtproto_sender.py", line 108, in receive
>     body = self.connection.recv()
>   File "C:\Python\lib\site-packages\telethon\network\connection.py", line 160, in _recv_abridged
>     length = struct.unpack('<B', self.read(1))[0]
>   File "C:\Python\lib\site-packages\telethon\network\connection.py", line 208, in _read_obfuscated
>     self.conn.read(length)
>   File "C:\Python\lib\site-packages\telethon\extensions\tcp_client.py", line 118, in read
>     partial = self._socket.recv(bytes_left)
>   File "C:\Python\lib\site-packages\socks.py", line 438, in recv
>     bytes, _ = self.recvfrom(*pos, **kw)
>   File "C:\Python\lib\site-packages\socks.py", line 419, in recvfrom
>     return super(socksocket, self).recvfrom(bufsize, flags)
> BrokenPipeError: [WinError 10058] A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python\lib\logging\__init__.py", line 992, in emit
>     msg = self.format(record)
>   File "C:\Python\lib\logging\__init__.py", line 838, in format
>     return fmt.format(record)
>   File "C:\Python\lib\logging\__init__.py", line 575, in format
>     record.message = record.getMessage()
>   File "C:\Python\lib\logging\__init__.py", line 338, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "C:\Python\lib\threading.py", line 884, in _bootstrap
>     self._bootstrap_inner()
>   File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Python\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 849, in _recv_thread_impl
>     error
> Message: 'Unknown error on the read thread, please report'
> Arguments: (BrokenPipeError(10058, 'A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call', None, 10058, None),)

What's with this error?

**Comment by Lonami** [comment]
What version?

**Comment by vegeta1k95** [comment]
0.15.3.2

**Comment by Lonami** [comment]
On which line does it fail?

**Comment by vegeta1k95** [comment]
Can't say, error occured only 2-3 times for a long period of use so I didn't log it properly.

**Comment by Lonami** [comment]
```python
>>> issubclass(BrokenPipeError, OSError)
True
```

The [`tcp_client`](https://github.com/LonamiWebs/Telethon/blob/bfff1567aff5889e1069c9be2d116ce7c2dc39eb/telethon/extensions/tcp_client.py) is excepting `OSError`'s all over the place so I'm not sure from where this one can have slipped in. Do reopen if you can reproduce consistently somehow and a better traceback.
