### ISSUE TITLE
Feature request: Saving GIFs / Stickerpacks request

### ISSUE THREAD

**Issue by Arb1trage** [LonamiWebs/Telethon#3952]
Hi Lonami,

sending GIFs/Stickers is hard because for each account the key values differ, and from what I figured, the only way to automate sending GIFs/Stickers is to save them by hand (rightclick -> save GIF), then use client(messages.GetSavedGifsRequest(hash=0)) / client(messages.GetAllStickersRequest(hash=0)) and reference them this way.

It would be great if there was a "Save GIF/Stickerpack" function/request. That way you could scrape GIFs/stickers in your own channel and be able to use them without manual actions.

Or alternatively, I may have missed something and there is an easier way to send and reference GIFs/Stickers with multiple accounts that could be automated. Either way I'd be thankful for your input and appreciate your work!

**Comment by Lonami** [comment]
If you can do it with official clients ("saving GIFs"), you can do it with Telethon. Not sure what request is used though. Media has an access hash, which is unique per account, meaning if you get Media X in Account A, then Account B cannot use that Media X unless it fetches it itself.

**Comment by Lonami** [comment]
Alternatively just upload the GIF from disk, or keep a `(channel id, msg id)` pair and fetch its media to send when needed.
