### ISSUE TITLE
send_code_request not sending code due to disconnecting afterwards

### ISSUE THREAD

**Issue by adbenitez** [LonamiWebs/Telethon#3954]
**Checklist**

* [ ] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

async def main():
    client = TelegramClient("test", api_id, api_hash)
    await client.connect()
    res = await client.send_code_request(phone)
    await client.disconnect()  # <- ISSUE HERE
    print("hash:", res.phone_code_hash)
```

The issue seems to be that because of calling `client.disconnect()` right after requesting the code, Telegram never sends the code, if there is nothing Telethon could do to avoid this, it would be nice to at least documenting in `send_code_request()` that if connection is dropped immediately the code might never arrive, so developers can avoid having this error in their code

**Comment by adbenitez** [comment]
for reference:

https://stackoverflow.com/questions/74093209/telegram-does-not-send-authorization-code-if-the-request-was-sent-from-telethon/74100828#74100828

**Comment by Lonami** [comment]
Feel free to send a PR with the documentation change. However I'm going to close this issue as there is nothing to fix.
