### ISSUE TITLE
My account is banned

### ISSUE THREAD

**Issue by xiaomi2077** [LonamiWebs/Telethon#3955]
In the last week, I have been banned from 4 accounts. They are all new virtual phone numbers, and I started to use the telethon library to develop userbot and bot applications after just registering with telegram. But without exception, within less than a day, the account was automatically kicked off the line, and when I logged in again, it displayed "Is this phone number banned!". 

I promise I'm not using userbots or bots to post ads, I'm just retweeting what I want to post to userbot to help me retweet to my own channel. I wrote a lot of emails to the official, but no official response was received, and the account has been banned.

Is it because new accounts are easily banned for using userbot? Is it easy to block just with bots? In addition to sending an email to the official, is there any way to unblock the account, it seems that the official does not handle the email.

**Comment by Lonami** [comment]
See #824.
