### ISSUE TITLE
Can't login through linux host, and cant send verification code. athKeyUnregisteredError

### ISSUE THREAD

**Issue by ParrotInTheGarden** [LonamiWebs/Telethon#3956]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient, events
client = TelegramClient('name', "xxx", "xxxx")
client.connect()
client.sign_in(phone="+380 99 781 72 98", code=input("Enter code: "))
```

I am trying to host the client on linux host, I tried not using `client.sign_in` but telethon doesn't ask for code nor does telegram send one, and when I try to access client data on linux I get this error `athKeyUnregisteredError: The key is not registered in the system`

I tried searching for a solution but couldn't find any, my guess was that verification code is needed.

On my windows, telethon asked for code on first launch only.

What should I do?
Am I doing something wrong?
Does this not work on linux for some reason?

**Comment by Lonami** [comment]
The current code as-is will ask for Telegram's code before it is actually sent which is wrong. Please see the documentation for how to login.

If the issue persists, Telegram may be simply refusing to send the code (#1448 has more details on a similar case).
