### ISSUE TITLE
track invite_link 

### ISSUE THREAD

**Issue by ghost** [LonamiWebs/Telethon#3957]
hi, i create lots of unique invite link via bot for my group,  i need to how many users joined in for each invite_link,
i read all related method and docs, but found no solutions.
please, is there any way to make it work?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
