### ISSUE TITLE
I have got User, but still show errors "Could not find the input entity for PeerUser"

### ISSUE THREAD

**Issue by bobogavin** [LonamiWebs/Telethon#3958]
I want to find some chat message sender then send content to him, but SendMessageRequest shows "Could not find the input entity for PeerUser", from userTemp I got User info, why show this error ?

getMessageResult = await client(functions.channels.GetMessagesRequest(channel=chatUsername,id=[chatMessageid]))
 userTemp = getMessageResult.users[0]
sendResult = await client(functions.messages.SendMessageRequest(peer=userTemp,message=content))

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
