### ISSUE TITLE
Can't send code because python not reading string

### ISSUE THREAD

**Issue by lynrayy** [LonamiWebs/Telethon#3961]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events, sync

api_id = 12345678
api_hash = '123456123456123456'
session_name = "Ray's userbot"

client = TelegramClient('session_name', api_id, api_hash)
client.start()
```

**Traceback**
```
--

```

Python just not reading line with code and creating new lines in pressing ENTER
https://youtu.be/B5zhr6Qgi8c

**Comment by lynrayy** [comment]
P.s This is PyCharm

**Comment by Lonami** [comment]
If you have 2FA enabled the prompt to enter your password may not show in some terminals but you should still be able to type in the password and press enter to login. Alternatively, provide the password to `start`. Unfortunately this can't really be fixed while keeping the interactive password hidden as far as I know.

**Comment by lynrayy** [comment]
Have you seen video? Enter does nothing

**Comment by Lonami** [comment]
Yes I have seen the video. As I said you can enter the 2FA directly in the code, or use the manual login flow without start (see docs), or, if there's a bug, I would need `logging.DEBUG` to be enabled to tell.
