### ISSUE TITLE
Proxy is not working on windows. 

### ISSUE THREAD

**Issue by niuhuan** [LonamiWebs/Telethon#3962]
Setting the client proxy on Windows does not work. I do not find any logs on the proxy server console.

my desktop is win10 system, and proxy working good on macos

**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
...
        client = TelegramClient(
            'keep',
            api_id,
            api_hash,
            app_version="0.0.1",
            device_model="session_backups(telethon)",
            auto_reconnect=False,
            proxy= {
                'proxy_type': 'SOCKS5',
                'addr': '127.0.0.1',
                'port': 10808,
                'rdns': True
            }
        )
```

**Log**
```
2022-10-26 Wednesday 14:31:18  mtprotosender.py : INFO  Connecting to 149.154.167.51:443/TcpFull...
2022-10-26 Wednesday 14:31:28  mtprotosender.py : WARNING  Attempt 1 at connecting failed: TimeoutError:
2022-10-26 Wednesday 14:31:39  mtprotosender.py : WARNING  Attempt 2 at connecting failed: TimeoutError:

```

**Comment by Lonami** [comment]
I do not have much experience with proxies or interest in them currently, so I am unlikely to look into this any time soon. However, you are welcome to submit a PR fixing this, and I will happily review it.

**Comment by jw-star** [comment]
My windows11 does not work either, the latest version

**Comment by artemki2077** [comment]
I have conducted tests and the proxy disappears only on windows, on linux and on mac os everything works fine

**Comment by jw-star** [comment]
@niuhuan  use this package

```
python-socks[asyncio]
```

**Comment by niuhuan** [comment]
> @niuhuan use this package
> 
> ```
> python-socks[asyncio]
> ```

Good job 👍!

**Comment by jw-star** [comment]
Read more documents, there are instructions in the documents

**Comment by yeyuchen198** [comment]
大佬跟我一样的情况给哈哈哈，手机正常，windows用v2rayN就不行

**Comment by yeyuchen198** [comment]
请问大佬解决了吗？

**Comment by yeyuchen198** [comment]
pip install python-socks[asyncio] -i https://pypi.tuna.tsinghua.edu.cn/simple
只要这样就行了
proxy = (socks.SOCKS5, '127.0.0.1', 10808, True)
TelegramClient(name, api_id, api_hash, proxy=proxy)

**Comment by hyperbolic-c** [comment]
> pip install python-socks[asyncio] -i https://pypi.tuna.tsinghua.edu.cn/simple 只要这样就行了 proxy = (socks.SOCKS5, '127.0.0.1', 10808, True) TelegramClient(name, api_id, api_hash, proxy=proxy)

@yeyuchen198 大佬，请问你用的是哪家的代理，我试了几个都不行，开了代理还是连接不上。

**Comment by wzshuang** [comment]
> pip install python-socks[asyncio] -i https://pypi.tuna.tsinghua.edu.cn/simple 只要这样就行了 proxy = (socks.SOCKS5, '127.0.0.1', 10808, True) TelegramClient(name, api_id, api_hash, proxy=proxy)

worked for me, thanks
