### ISSUE TITLE
finding .session file phone number

### ISSUE THREAD

**Issue by balicali420** [LonamiWebs/Telethon#3963]
Hello !
I have already authorized .session file I forgot his number,
tried adding other account to contact,
tried changing privacy so I can see from other accs,
all with no success..
any suggestions ?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
