### ISSUE TITLE
Not receiving a code

### ISSUE THREAD

**Issue by abduselam1** [LonamiWebs/Telethon#3964]
I tried to authenticate and after I put my phone number I didnt receive a code from telegram I have checked my phone, api id, api hash everything even I have created a new telegram account and an api again its not working
**Checklist**

* [x ] The error is in the library's code, and not in my own.
* [x ] I have searched for this issue before posting it and there isn't a duplicate.
* [ x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

with TelegramClient('anon', api_id, api_hash) as client:
    client.loop.run_until_complete(client.send_message('me', 'Hello, myself!'))

```

**Comment by Lonami** [comment]
Duplicate of #3835.
