### ISSUE TITLE
AttributeError: 'list' object has no attribute 'title'

### ISSUE THREAD

**Issue by slagusev** [LonamiWebs/Telethon#3966]
I used code:
```
async def main():
    links = get_stores()
    for url in links:
        channel = await client.get_entity(url)
        print(channel.title)
```

When print get error: AttributeError: 'list' object has no attribute 'title'. I have been learning Python for a relatively short time.

![image](https://user-images.githubusercontent.com/2290650/198965196-0b6c0649-a63b-4ad6-af00-31631295aae6.png)

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

I have tried the code to check if there was a bug in the library but it seems to work fine, so this really is a question.
