### ISSUE TITLE
Bot can't reply to another bot

### ISSUE THREAD

**Issue by roman2861** [LonamiWebs/Telethon#3969]
My bot can't answer to another despite the fact that I get correct reply_to message ID

My code:

```
arguments = {}
if event.is_reply:
    try:
        arguments['reply_to'] = event.reply_to.reply_to_msg_id
    except Exception as e:
        reply_message = await event.get_reply_message()
        arguments['reply_to'] = reply_message.id
return await bot.send_message(entity=event.chat_id, message=search_query, **arguments)
```
**arguments['reply_to']** get correct data, but if I (bot) reply to myself/user, all works as expected. If I answer to another bot, **bot.send_message** just send standalone message (no reply).

**Comment by Lonami** [comment]
Telegram does not let bot accounts see messages from other bot accounts. There may be other limitations, like the one you're experiencing.
