### ISSUE TITLE
IndexError telethon.client.dialogs in _load_next_chunk

### ISSUE THREAD

**Issue by JustTony97** [LonamiWebs/Telethon#3971]
Hello everyone, I would like to report a bug discovered during the development process, in particular using the method:
``` TelegramClient.iter_dialogs() ```
The problem is in the asynchronous iterator when the user's dialogs are loaded. Loading takes place in chunks of 100 dialogs and there may be a situation (in my case 400 dialogs) that the last chunk will be complete and at the same time load the entire list of dialogs. In this case, at the next iteration, the program receives an empty list, as a result of which an error occurs at the moment of accessing this list by index.
``` self.request.offset_peer = self.buffer[-1].input_entity ```
I think it is necessary to add an additional check **self.buffer** for empty in **telethon.client.dialogs._load_next_chank** method.
For example:
``` 
if len(r.dialogs) < self.request.limit\
      or not isinstance(r, types.messages.DialogsSlice)\
      or not self.buffer:  # this line has been added
   return True
```

**Traceback**
```
IndexError: list index out of range
  ...
  File "telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "telethon/client/dialogs.py", line 112, in _load_next_chunk
    self.request.offset_peer = self.buffer[-1].input_entity
```
The ver. of Telethon that was used is 1.25.4
Thank you for your attention.

**Comment by Lonami** [comment]
Yeah that's the correct solution although the problem is Telegram is returning a non-zero amount even though none of the dialogs would match with the requested offset.
