### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by superarray** [LonamiWebs/Telethon#3973]
[Line:542]-[Func:_handle_auto_reconnect]-[Level:WARNING] : Error executing high-level request after reconnect: <class 'telethon.errors.rpcerrorlist.AuthKeyDuplicatedError'>: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by GetUsersRequest)

keep getting this error
An exception should be thrown when this error occurs

**Comment by Lonami** [comment]
The warning comes from here:

https://github.com/LonamiWebs/Telethon/blob/0c868065c7fd10d806c3e6287095c469c8296b89/telethon/client/updates.py#L556-L564

This is only called once here:

https://github.com/LonamiWebs/Telethon/blob/2ffac2dcdb1919a6486b10deaf28465d564aea7a/telethon/network/mtprotosender.py#L402-L405

While there's a loop, it breaks immediately after creating the task.

`_start_reconnect` is only called whenever there are IO errors or a ping failed.

So it sounds like it might a network issue. You might want to disable autoreconnect.

**Comment by superarray** [comment]
This error is not caused by a network problem. You should add an exception judgment. If you encounter AuthKeyDuplicatedError, you should throw an exception instead of looping

**Comment by Lonami** [comment]
There is no loop where that line is printed, or in its caller. You're welcome to further investigate this issue and report back, but as it stands, I have no way to reproduce this error or look into it further (all I can do is take a look at the code and see what could be wrong but did not find anything obvious).

**Comment by superarray** [comment]
**It may need to be handled like this, here is the code snippet**

```python
from telethon.errors import rpcerrorlist


async def _handle_auto_reconnect(self: 'TelegramClient'):
    # TODO Catch-up 
    # For now we make a high-level request to let Telegram 
    # know we are still interested in receiving more updates. 
    try:
        await self.get_me()
    except Exception as e:
        self._log[__name__].warning('Error executing high-level request '
                                    'after reconnect: %s: %s', type(e), e)
        if isinstance(e, rpcerrorlist.AuthKeyDuplicatedError):  # AuthKeyDuplicatedError should be a problem with the telegram authorization key, an exception needs to be thrown, and the user should handle it by himself
            raise

```

**Comment by Lonami** [comment]
That would be ignored. The task is spawned but never checked to see if it succeeds.

As I said there should not be a loop but you're welcome to investigate *why* such a "loop" is happening (and **where** it is looping). I cannot really investigate this myself without a way to reliably reproduce this.
