### ISSUE TITLE
Can't retrive more than 200 users of channel?

### ISSUE THREAD

**Issue by pxlvoid** [LonamiWebs/Telethon#3976]
Using 
```python
for u in client.iter_participants(channel, aggressive=True):
    print(u.id, u.first_name, sep=';')

```
But can get only 200 members. How can i get other members?

**Comment by Lonami** [comment]
This is a limitation imposed by Telegram. If you can use https://tl.telethon.dev/methods/channels/get_participants.html without changing the filter in a way that makes it possible to fetch more than 200 members let me know how and then I can review if the current implementation is buggy or works fine.
