### ISSUE TITLE
Add support for Topics

### ISSUE THREAD

**Issue by roman2861** [LonamiWebs/Telethon#3977]
After last Telegram update there are some new params such as message_thread_id & is_topic_message

Despite the fact that V2 is under development, I think that it would be great to add Topics support in the current Telethon version, because in some cases Topics are gamechangers for bots. Thank you.

**Comment by Lonami** [comment]
This should be possible with raw API in the v1 branch, as it's using the latest layer with topics I believe. If not, feel free to send a PR with the latest layer.

However I'm unlikely to provide new friendly methods in v1 to work with these as I'd like v1 to be feature frozen.
