### ISSUE TITLE
send_message   = Peer Flood Error 

### ISSUE THREAD

**Issue by spam1712** [LonamiWebs/Telethon#398]
`result = client.invoke(SendMessageRequest(client.get_input_entity(326296648),'hi there'))`

telethon.errors.rpc_error_list.PeerFloodError: (PeerFloodError(...), 'Too many requests')

getting this error for no apparent reason
believe, i use requests very sparingly - once 3-5 minutes so flooderror is not the problem
i have tried every possible combination with invoking the API thingy and other

trashiest bit is that it works with SOME users, which additionaly indicates that there is no problem with flooding

please help!

**Comment by Lonami** [comment]
[You should have used search](https://github.com/LonamiWebs/Telethon/wiki/Deleted,-Limitted-or-Deactivated-Accounts). There are also other closed issues with this error (look for `PEER_FLOOD`).

**Comment by spam1712** [comment]
i am sorry but this is not the case:

it works with SOME users!
and there is no ban!! i checked!

i have explitited this in the issue :(

**Comment by Lonami** [comment]
I actually don't really know when `PeerFloodError` is raised then. But either way move the discussion to #397 since that's an already open issue.

**Comment by spam1712** [comment]
ok thanks 
your work is very good!

**Comment by Lonami** [comment]
@spam1712 thanks!

**Comment by Vaghasiyayash** [comment]
I also got this error. I have grp of 20k members in telegram. But when i run bot, msg send to only 15-20 people and after that it's showing peer flood error. You get any solutions?

**Comment by StarNeit** [comment]
Hello @Vaghasiyayash 
Did you solve your PEER_FLOOD issue?
If yes, would you please let me know how to avoid that?

**Comment by azoulaynoam** [comment]
The real question is what are the differences between FloodWaitError and PeerFloodError.
In that matter, I am having issues while inviting users to a group...
@Lonami I dont know if you still here but maybe you got an answer.

**Comment by Mongo71** [comment]
OUR SCRIPTS DO NOT HAVE 'PEER FLOOD ERRORS' LIKE ALL THE OTHER SCRIPTS YOU CAN GET ONLINE. 
WE FIX THAT ON OUR SCRIPTS..
http://telegram-groups-scraper-adder.com/

**Comment by Talanted-Blockchain-Dev** [comment]
I get this error too
I have 15 users and after send only 400 requests get this error.
Please let me know how to avoid this error
Please help me

**Comment by Lonami** [comment]
Peer flood occurs when the account is likely to be spamming. Telethon cannot fix it.
