### ISSUE TITLE
anonymous=True and add_admins=True doesn't work in edit_admin request

### ISSUE THREAD

**Issue by msukach** [LonamiWebs/Telethon#3980]
**Short description**
In edit_admins everything is set as expected inside of a private group, except `anonymous=True `and `add_admins=True`. Can't figure out why. I've checked and [Telegram Client API](https://core.telegram.org/type/ChatAdminRights) still contains both of these values, and the response from the `edit_admin` request is `True`.

**Checklist**

* [x] The error is in the library's code, not mine.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python

user_id = XXX
session = StringSession("test")
async with TelegramClient(session, settings.API_ID, settings.API_HASH) as client:
    users = ["my_username"]
    response = await client(functions.messages.CreateChatRequest(
            users=users,
            title="Example"
        ))
    chat = response.chats[0]
    
    await client.edit_admin(
          entity=chat,
          user=user_id,
          is_admin=True,
          change_info=True,
          post_messages=True,
          edit_messages=True,
          delete_messages=True,
          ban_users=True,
          invite_users=True,
          pin_messages=True,
          add_admins=True,
          manage_call=True,
          anonymous=True,
      )
    
```

<img width="396" alt="Screenshot 2022-11-22 at 19 10 13" src="https://user-images.githubusercontent.com/79835809/203389705-c21eae65-79b4-4888-9116-acac50c4161d.png">

**Comment by Lonami** [comment]
Those permissions are likely channel (broadcast / megagroup) specific.
