### ISSUE TITLE
parse_mode when copying messages

### ISSUE THREAD

**Issue by User087** [LonamiWebs/Telethon#3983]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

When copying a message, using `client.send_message(chat,Message)`, I would expect the message to be sent as it is with its formatting entities already in place, so any apparent formatting syntax within `Message.message` is actually supposed to be part of the message and remain unparsed. Yet the default markdown-based `parse_mode` remains in place and tries to parse the text of the message, so the result is the copied message either comes out different to the original or fails to send throwing an ENTITY_BOUNDS_INVALID error. Take for example this message: https://t.me/lkljlksu/2. It can be rectified by setting `parse_mode=None` but shouldn't this really be the default when sending Message objects, as it is to be assumed that the text of an already-existing Message hsa already been parsed and is included in the entities of the message?

**Comment by Lonami** [comment]
The function:

https://github.com/LonamiWebs/Telethon/blob/8ae75db86268a7726e16b100a93a2aca7643938d/telethon/client/messages.py#L624

doesn't use `parse_mode` at all if you pass a `Message`:

https://github.com/LonamiWebs/Telethon/blob/8ae75db86268a7726e16b100a93a2aca7643938d/telethon/client/messages.py#L831-L867

Please make sure you're using the latest version, and if the problem persists, please post the code necessary to trigger the issue (preferably less than 100 lines without additional dependencies), so that I can reopen this and take a look then.

**Comment by User087** [comment]
Not sure why setting `parse_mode = None` fixes it then. Here's the code:
```
from telethon import TelegramClient

client = TelegramClient(...)
#client.parse_mode = None
chat = ...

async def main():
    await client.start()
    async for msg in client.iter_messages('lkljlksu',ids=2):
        await client.send_message(chat, msg)
        
client.loop.run_until_complete(main())
```
and compare with uncommenting `client.parse_mode = None`. I installed Telethon with the above command: `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip`.

For some reason, setting the global `client.parse_mode = None` fixes the problem, but setting the property `client.send_message(chat, msg, parse_mode=None)` doesn't.

**Comment by Lonami** [comment]
The problem was specifically when sending a copy of a message with a file where the caption had no formatting entities at all. Which I expect to be rare so I think I'll hold a bit on releasing a new patch version.
