### ISSUE TITLE
sys:1: RuntimeWarning: coroutine 'MessageMethods.get_messages' was never awaited

### ISSUE THREAD

**Issue by byxiaobian** [LonamiWebs/Telethon#3984]
No matter how you tune it, okay?

**Comment by Lonami** [comment]
I cannot "fix" this unless you provide more information, although it seems likely to *not* be a bug in Telethon in any case (rather, how it's being used), so I'm closing this.

**Comment by byxiaobian** [comment]
> 

Thank you. It's all set
