### ISSUE TITLE
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 3540 seconds is required 

### ISSUE THREAD

**Issue by byxiaobian** [LonamiWebs/Telethon#3985]
Traceback (most recent call last):
  File "E:\Download\Telethon-1\tests\telethon\client\__init__.py", line 62, in <module>
    client.loop.run_until_complete(main())
  File "D:\ProgramFiles\python39\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\Download\Telethon-1\tests\telethon\client\__init__.py", line 40, in main
    res = await client(InviteToChannelRequest(
  File "E:\Download\Telethon-1\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "E:\Download\Telethon-1\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 3540 seconds is required (caused by InviteToChannelRequest)

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

**Comment by byxiaobian** [comment]
> 



> API，API，这这着获得的直接来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自来自直接来自直接直接直接直接不不不不不会任何方式更改更改它们（（除了除了需要需要需要时调整输入输入输入它是 Telethon 无法“修复”的东西，而这正是 Telegram API 的工作方式。



> 您使用的是原始 API，这意味着您获得的结果直接来自 Telegram，并且 Telethon 不会以任何方式更改它们（除了在需要时调整一些输入参数，同时尊重预期值）。不幸的是，这意味着它是 Telethon 无法“修复”的东西，而这正是 Telegram API 的工作方式。

Well, thank you. But the inviter did not prompt when entering the group

**Comment by byxiaobian** [comment]
Well, thank you. But the inviter did not prompt when entering the group
