### ISSUE TITLE
How can I log in with Session? Thank you

### ISSUE THREAD

**Issue by byxiaobian** [LonamiWebs/Telethon#3986]
After successful login, record the session. Next time, log in directly using Session or other methods， Thank you！

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
