### ISSUE TITLE
Unable to do an UploadMediaRequest

### ISSUE THREAD

**Issue by Rucadi** [LonamiWebs/Telethon#399]
I'm having problems with the UploadMediaRequest, I'll try to clarify absolutly everything that I'm doing following what I think it's the correct way to do it.

for implement this, I used https://lonamiwebs.github.io/Telethon/methods/messages/upload_media.html
as reference.

first of all I have an InputPeerChannel

`theIPC = InputPeerChannel(int(channel_id), int(access_hash))
`
Second, I have the photo stored in local.

for the size x (the only one I really want to resend) I rebuild the needed structures:

First of all, I start with the FileLocation:
`
 fileLocation = FileLocation(dc_id,volume_id,local_id,secret)`

then I build the photoSize, where type is the letter of the size (x)

`photoSize = PhotoSize(type,fileLocation ,w,h,size)
`
then I build the photo, the id and the access_hash this time are from the photo not the channel:

`thePhoto = Photo(int(id),int(access_hash),datetime.fromtimestamp(int(date)),[photoSize],False)`
and then, I create the photo and invoke the method on the client

`self.client.invoke(UploadMediaRequest(theIPC ,InputMediaPhoto(thePhoto,"test",None)))`

But It ends having a MEDIA_INVALID error. I know that I must be doing it badly.

Also, If I try to do the same procedure but using the media received directly from telegram servers, It still don't work for me:

            self.client.invoke(UploadMediaRequest(theIPC ,retm.messages[0].media))
where the message has media.

Thank you for your help.

**Comment by Lonami** [comment]
I don't think like reading that but to upload media you should use `.upload_file(file)`, then that returns the `InputFile` you need to work with.

**Comment by Rucadi** [comment]
Thanks for your response.
I'm trying to use **previously uploaded media** that I got via GetMessagesRequest for reusing it without reuploading the media myself.
(I'm not trying to forward neither)

**Comment by Rucadi** [comment]
Ok, I still don't get why it was failing or what UploadMediaRequest is supposed to do, but the method that I was looking for was  **SendMediaRequest**
Sorry for the issue, I was too many hours in this error.

**Comment by Lonami** [comment]
No problem, the "low level" API can be really confusing. A good thing to do is to look at how things are done inside the `TelegramClient`, since in the end, this is just a wrapper around some of the most used requests.
