### ISSUE TITLE
telethon.client.updates: Fatal error handling updates

### ISSUE THREAD

**Issue by ggr18** [LonamiWebs/Telethon#3993]
**Checklist**

* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

This week a lot of errors handling errors have been appearing. The last one froze many accounts I own on a code with continuous updates. The error triggers on the last two versions at least, I have not tried another one.

Due to security concerns, I cannot upload the code.

**Comment by Lonami** [comment]
You need to use the latest version. This error is more likely to occur if you are reusing the session from somewhere else. It is recommended that you login with Telethon, and don't reuse the session this creates anywhere else.

**Comment by ggr18** [comment]
The error ocurred on the lastest version as well. I prefered to downgrade because I receive less errors with the previous one than with the updated one.

I will try to create new session files, but they are not reused.

Thanks.
