### ISSUE TITLE
Persistent timestamp empty

### ISSUE THREAD

**Issue by xwr-ron** [LonamiWebs/Telethon#3994]
Hello. I ran into a problem when creating a group.
My task is to create a group through a bot for my managers at work. Since the bot doesn't have access to this, I enlisted a telebot for this.

First I need to create a regular group so that I can add a manager to the group.
As the second step, I need to migrate to a megagroup so that I can set up the group more flexibly.
and at the end i need to create an invite link and send to the user but i get an error

**UPD1: I have found and fixed bugs in my code, but I still get this error**
**UPD2: I noticed a strange phenomenon. If you run the project using the debugger, then the error does not appear. I use VS Code**

**Traceback**
```
Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/telethon/client/updates.py", line 311, in _update_loop
    diff = await self(get_diff)
  File "/env/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/env/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.PersistentTimestampEmptyError: Persistent timestamp empty (caused by GetChannelDifferenceRequest)

```

**Comment by Lonami** [comment]
This should have been fixed by https://github.com/LonamiWebs/Telethon/commit/6d2a5dada5e5f03d67a5aae26727911f613a208c.

**Comment by xwr-ron** [comment]
@Lonami Thanks, looking forward to it!
