### ISSUE TITLE
All sessions crushed

### ISSUE THREAD

**Issue by Stepashka20** [LonamiWebs/Telethon#3999]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events, sync

api_id = 12345
api_hash = '0123456789abcdef0123456789abcdef'

client = TelegramClient('session_name', api_id, api_hash)
client.start()
```
I use this code to authorize as userbot. I entered the code, then everything is fine for the first 10 minutes, but then the telegram delete ALL sessions and I have to receive SMS to my phone. What should I do?

**Comment by Lonami** [comment]
Unfortunately, I don't think this is a bug in Telethon, but rather one of Telegram's anti-spam measures. I do not know how to circumvent this, but I truly believe there's nothing Telethon can do to fix it (other than trying to mimic official clients more closely, which would make it easier on spammers, which I would rather not even try).
