### ISSUE TITLE
Exception: Number of retries reached 0

### ISSUE THREAD

**Issue by pashbelg** [LonamiWebs/Telethon#400]

**Comment by Lonami** [comment]
#270, thank you very much.

**Comment by pashbelg** [comment]
Hello! How can i fix this trouble? I saw last thread and try to edit flood_sleep_threshold, but i can't find this parameter!

**Comment by Lonami** [comment]
`flood_sleep_threshold` and retries reaching 0 are two completely unrelated issues.

**Comment by Lonami** [comment]
```python
TelegramClient(blah, blah, blah, flood_sleep_threshold=N)
# or
client.session.flood_sleep_threshold = N
```

**Comment by pashbelg** [comment]
I saw this thread https://github.com/LonamiWebs/Telethon/issues/270

**Comment by Lonami** [comment]
Why did you open a new issue then?

**Comment by pashbelg** [comment]
Because i cant solve this problem

**Comment by Lonami** [comment]
Then tell us about your experience in the old, already open issue, instead opening a new one which people doesn't know about.

**Comment by pashbelg** [comment]
Ok
