### ISSUE TITLE
Make the path of the session file configurable

### ISSUE THREAD

**Issue by salvodgiuffrida** [LonamiWebs/Telethon#4001]
The session file (named [username].session) is currently stored in the running directory.
I'm developing a software which uses this library, and runs as a serverless function in AWS Lambda. Because the Lambda container is read-only, the session file can't be written to the file system, which is a disaster.

However...inside the Lambda container, the /tmp directory is writeable, but in order to have the session file stored there I need to have its path configurable.

**Comment by Lonami** [comment]
You can already pass full or relative paths as the first parameter to `TelegramClient`, including the `.session` extension if you want to. I'm not entirely sure why people assume this is not possible, but it's definitely not the first time this question has came up. Please feel welcome to send a pull request to make this clearer in the documentation (although it [already is in Signing In](https://docs.telethon.dev/en/stable/basic/signing-in.html#id2)):

> ```python
> # The first parameter is the .session file name (absolute paths allowed)
> ```

**Comment by Lonami** [comment]
In any case what you probably want is a different session storage - also described in the documentation.
