### ISSUE TITLE
When failing to complete login, telegram just refuses to send messages

### ISSUE THREAD

**Issue by shards-7** [LonamiWebs/Telethon#4003]
well i was trying to do a user login through a bot, so sometimes a faced some errors, which led to some issues 

so when this is happening, the telegram (android) suddenly just refuses to send messages from the account i was trying to login, and just keeps "Loading" may i say

mostly this issue get around after the

`client.send_code_request` function

NOTE : i always close the connection at the end no matter what

![THE ISSUE PIC](https://user-images.githubusercontent.com/100168398/208263664-b677a636-de91-4cb8-926d-cc10cb69a949.jpg)

an image from the account i was trying to login from

![yeah](https://user-images.githubusercontent.com/100168398/208263722-74429e64-58e7-4b9b-886a-8557c813a7e4.jpg)

**Comment by Lonami** [comment]
This is most likely a flood wait, an error produced by Telegram itself to reduce abuse / spam. There is not much Telethon can do to "fix" this problem.
