### ISSUE TITLE
Shouldn't be a special exception for sellable usernames?

### ISSUE THREAD

**Issue by shards-7** [LonamiWebs/Telethon#4004]
well hey I'm sorry to bothering again

but you see here i was trying to check some usernames around, then by accident i checked a sellable usernames, so `BadRequestError` popped off

shouldn't be a special exception for that?

**Comment by Lonami** [comment]
[Yes, in the next version](https://github.com/LonamiWebs/Telethon/commit/b2925f82798726585ad73ff9116ca5f4a2894937#diff-50e4f0d708fba7f9870fb3cd19be08e3b7b780dfa9436b6695583847cd2c3e3eR398).
