### ISSUE TITLE
 forward_messages The views count is inaccurate.

### ISSUE THREAD

**Issue by aniwn88480857** [LonamiWebs/Telethon#4007]
Has anyone noticed some issues with views when you use forward_messages?
Assuming a channel message, the current view is 1000. When you forward this message to a new channel through forward_messages, then in the new channel, the message view is 1.
If you forward to a group or someone's account, the view is 1000, which is correct,
Only when the forwarding destination is a channel, the view count is inaccurate.
Is this what is the reason?
(If you don't use telethon forward_messages), use real client forwarding, then the view is also 1000,

**Comment by Lonami** [comment]
Please feel welcome to use https://tl.telethon.dev/methods/messages/forward_messages.html. If the behaviour is the same, then the "problem" is on Telegram's side, and not Telethon.

As you were told in the main help chat, the view of 1000 from official clients might be a cache issue. Perhaps if you restart you would see the real count.

In any case, I'll be closing this, as I doubt it's a bug, but I'll happily reopen if I'm proven wrong when using the raw API `ForwardMessagesRequest`.
