### ISSUE TITLE
i cant received my code in the other app

### ISSUE THREAD

**Issue by cxapython** [LonamiWebs/Telethon#4008]
**Code that causes the issue**
```python
from telethon import TelegramClient, events, sync

# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.
api_id = xxx
api_hash =xxx

client = TelegramClient('session_name', api_id, api_hash)
client.start()
```
Please enter your phone (or bot token): +861881066xxxx

I can receive the code when I use the app to log in, but I can’t receive the code when I use the telethon to send it. I changed two mobile phone numbers and tested it. There is no error message during

**Comment by Lonami** [comment]
This is likely a duplicate of #3835.

**Comment by Lllliubo** [comment]
> 这可能是#3835的副本。

What happened? I tried many times today and couldn't get the code
