### ISSUE TITLE
events.new.message add wait timeout with client.disconnect()

### ISSUE THREAD

**Issue by wangqiang1988** [LonamiWebs/Telethon#4010]
i use event.new.message, i send to a message to a bot , bot give me some message or photo  is freedom ,i want recive  last message or photo more than 5 sec then client.disconnect()

hope the funcation

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

I saw https://stackoverflow.com/q/74941435, so you probably don't need to open a new question, but it's hard to understand at the time of writing, so others might not be able to help.
