### ISSUE TITLE
Coudn`t find Constructor ID

### ISSUE THREAD

**Issue by TopSpammer** [LonamiWebs/Telethon#4011]
I got the following problem. When sending messages, regardless of the account, this error pops up, I tried first at 1.25, then manually updated to 1.26, the error stopped killing the script, but it still occurs

![photo_2023-01-03_12-35-02](https://user-images.githubusercontent.com/67190825/210379733-0c416108-e534-4f76-b88b-4a31f82874d3.jpg)

**Comment by Lonami** [comment]
Make sure you're up to date, and that the session is not being used anywhere else. Login with Telethon, and don't use the session anywhere else.

Other than that there's not much I can do to fix this problem. The error comes from Telegram.
