### ISSUE TITLE
Auto log out from account after run script

### ISSUE THREAD

**Issue by RFG-G** [LonamiWebs/Telethon#4012]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.

**Code that causes the issue**
```python
from telethon import TelegramClient
from config import APP_ID, APP_HASH

client = TelegramClient('changer', APP_ID, APP_HASH)

async def main():
    await client.start()
with client:
    client.loop.run_until_complete(main())
```

**Traceback**
```
No errors

```
Run script, login into the account. Everything is fine. But after 3-5 seconds TG log out account from all devices. And now I cannot to login into my 3 tg accounts.

**Comment by Lonami** [comment]
As far as I'm aware there's not much Telethon can do to "fix" this. The "problem" comes from Telegram.

**Comment by RFG-G** [comment]
> As far as I'm aware there's not much Telethon can do to "fix" this. The "problem" comes from Telegram.

But that's trouble only with telethon.

**Comment by Lonami** [comment]
You're more than welcome to try and investigate why it happens. I have never experienced such a thing myself. My suspicion is Telegram has learnt to detect Telethon to stop those who abuse it to spam.
