### ISSUE TITLE
WARNING:telethon.client.updates: Getting difference for channel updates * caused SessionRevokedError

### ISSUE THREAD

**Issue by simbadmorehod** [LonamiWebs/Telethon#4014]
I'm not an expert programmer, but this bug kind of threw me off, especially the "To-do" in the code, which literally says "TODO investigate why/when this happens and if this is the proper solution".

I'd like to figure out what the problem is, what I should do in this case, similar updates come from one session. 

I would like to be able to handle them properly and exclude them from the log. 

And I also want to thank the author, you are like a tank)

**Comment by Lonami** [comment]
The TODO you refer to:

https://github.com/LonamiWebs/Telethon/blob/508071556579ec1beb51e23b1ccfba13c87ed924/telethon/client/updates.py#L335

is only for `PersistentTimestampInvalidError`, not `SessionRevokedError`. The error you experienced is one of [401 Unauthorized, SESSION_REVOKED](https://core.telegram.org/api/errors#401-unauthorized), which:

> The authorization has been invalidated, because of the user terminating all sessions

So the warning is correct to stay. However, it is true that perhaps the library should disconnect when this happens and raise an error for the user to handle.

Appreciate the kind words!

**Comment by simbadmorehod** [comment]
Thank you, I anticipated something like this, I'll try to look into it and fix it. Have a good evening.

**Comment by simbadmorehod** [comment]
Can you tell me how to handle this exception correctly? I can just hang:

try; ..... exeption SessionRevokedError: ......
   
Something like this?

And how can I turn off the notification of normal chat or channel updates? `INFO:telethon.client.updates:Got difference for channel 1032422089 updates

It's a bit distracting and clogs up the log.

**Comment by Lonami** [comment]
You currently cannot handle this error. You would need to patch the library code if you want it to "exit early". You can make requests every few minutes to see if the session disconnected.

Configuring `logging` is offtopic here. Both the official Python documentation for the module or other forums are a better place to ask how to "turn a log line off".

**Comment by simbadmorehod** [comment]
Here's what I found for future study: https://github.com/LonamiWebs/Telethon/issues/228 https://stackoverflow.com/questions/68165628/unable-to-close-session-using-telethon-due-to-session-too-new

Thanks @Lonami for the answers, I think it's time to close this issue. have a good day or night everyone!

**Comment by Lonami** [comment]
Okay I'll close this but I still want to fix what I said so I opened a new one.

**Comment by msadeqian** [comment]
hi , I faced this issue in my project .
I get save error : Got difference for channel 1257723241 updates
telethon 1.28.5 

please help me to find a solution

**Comment by bb7790cc** [comment]
> 你好，我在项目中遇到了这个问题。我收到保存错误：频道 1257723241 更新 telethon 1.28.5 存在差异
> 
> 请帮我找到解决办法

Brother, you solved it

**Comment by heking1004** [comment]
> 您好，我的项目中遇到了这个问题。 保存时出现错误：通道 1257723241 更新 Telethon 1.28.5时出现差异。
> 
> 请帮我找到解决方案

解决了吗

**Comment by heking1004** [comment]
> > 你好，我在项目中遇到了这个问题。我收到保存错误：频道 1257723241 更新 telethon 1.28.5 存在差异
> > 请帮我找到解决办法
> 
> 兄弟，你解决了。

解决了吗
