### ISSUE TITLE
Disconnect and raise a proper error on session revoked

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#4016]
See #4014 for context. This was also discussed in private chats. The update loop "dies" and the user is logged out but we should actually be able to let the user know by raising a proper error.

**Comment by simbadmorehod** [comment]
```
try:
     ....
except (AuthKeyUnregisteredError, SessionRevokedError):
    ....
```

So far I have done something like this when trying to get data from the telegram servers through an inactive session, then I deactivate it in case of an error and no longer run, thereby notifications do not come out.
