### ISSUE TITLE
Methods returning type messages.messages contains a member chats

### ISSUE THREAD

**Issue by estebanpdl** [LonamiWebs/Telethon#4020]
Hi, there.

I have been utilizing Telethon to develop a command-line tool for collecting data from Telegram channels. I apologize if this is not the appropriate forum for my inquiry, but I was hoping to gain clarification on the meaning of `chats:Vector<Chat>` when it is returned using the GetHistoryRequest constructor. Are the chats represented in this vector ones that are mentioned in the collected messages, or potentially forwarded messages? I have noticed instances where channels are included in the vector, yet I cannot find them present in the messages. Is it possible that the message associated with a chat has been deleted, yet the chat remains in the vector? I appreciate any insight you can provide, as I have been unable to find this information in the Telethon documentation.

Thanks in advance.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
