### ISSUE TITLE
NewMessage method also receives old messages

### ISSUE THREAD

**Issue by efeint01** [LonamiWebs/Telethon#4021]
```
telegram_client = TelegramClient('anon', api_id, api_hash)
@telegram_client.on(events.NewMessage(chats='xxxx'))
async def my_event_handler(event):
    message = event.raw_text
    print(message) 

telegram_client.start()
telegram_client.run_until_disconnected()
```

I am using this code and some times it behaves abnormally. If there is no new message from the channel, it gives me the last message sent. I have no clue why doing this? Any help will be appreciated.

Python version: 3.9.13
Telethon version: 1.26.1

**Comment by Lonami** [comment]
Please follow the issue template.

The library will automatically catch up on missed messages if a few minutes pass with no new messages (as that may mean some are missing). As long as the client didn't terminate abnormally and had a chance to correctly persist the update state, everything should be working as expected.

If you're not receiving duplicate messages, I'm inclined to say is fine and close the issue. If this is a message you received before let me know and I will reopen it. But for me to have a chance at fixing it, I will need a way to reproduce it. With clear and detailed instructions. If not, there is not much I can do. Someone who has the issue would need to investigate it and send a PR with a fix.
