### ISSUE TITLE
Hello, I want to ask

### ISSUE THREAD

**Issue by JohnGoods** [LonamiWebs/Telethon#4026]
def _get_entity_pair(entity_id, entities, cache,
                     get_input_peer=get_input_peer):
    """
    Returns ``(entity, input_entity)`` for the given entity ID.
    """
    entity = entities.get(entity_id)
    try:
        input_entity = cache[entity_id]
    except KeyError:
        try:
            input_entity = get_input_peer(entity)
        except TypeError:
            input_entity = None

    return entity, input_entity

**Comment by JohnGoods** [comment]
I use  
groupUrl = 'xxxxx'
msg = get_messages(groupUrl, ids = 123)

msg.input_sender
This variable is sometimes empty and sometimes not
I use the same url and id every time

Is there any way to make input_ Sender is not empty

Because I want to send messages to the corresponding sender through the group source information, because the latest version of the group can set hidden member information

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
