### ISSUE TITLE
Spoiler media handled as MessageMediaUnsupported

### ISSUE THREAD

**Issue by NicolaMarchioro** [LonamiWebs/Telethon#4029]
Is there a plan to modify the current behavior when receiving media, such as in client.on(events.NewMessage()), where media marked as a spoiler is not included in the event and the event media is of type `MessageMediaUnsupported"? Does this limitation come from the Telegram APIs? Am I missing something?

**Comment by Lonami** [comment]
This should be available in the latest versions. Please make sure you are up to date before reporting issues.
