### ISSUE TITLE
How to fix syntax highlighting in PyCharm?

### ISSUE THREAD

**Issue by PieceOfGood** [LonamiWebs/Telethon#4030]
I'm sorry. I can't judge how wrong this is because the code works as advertised, but I have no idea how to develop an application when the IDE highlights sections of the code as erroneous and, the corresponding attributes and methods look like they are not available.

This is just example [from QuikStart](https://docs.telethon.dev/en/stable/basic/quick-start.html#quick-start):
![image](https://user-images.githubusercontent.com/31653906/217473156-d499bdfa-1de6-4e7f-9441-8165e7f05e52.png)
Here, I've only included the type hint from `telethon.types.Message` that `send_message()` returns to clarify, because without this hint, the following problems exist:
![image](https://user-images.githubusercontent.com/31653906/217473484-55ea046c-7d6e-43f0-aa2e-7046282d60ea.png)
But as you can see, it's only getting worse.
Can you please tell me if there is some way to fix this for PyCharm, or which IDE do you use that handles this problem better and renders the existing attributes and methods correctly?

**Comment by PieceOfGood** [comment]
Sorry. A colleague suggested:
```python
from telethon.tl.custom.message import Message
```
Whereas the `send_message()` method explicitly returns a different type.
![image](https://user-images.githubusercontent.com/31653906/217517398-2a9fbbe0-d9a5-46db-8759-37c87ade581e.png)
I can't judge how reasonable this is, but since this is a known fact, it deserves to be mentioned at the very beginning of acquaintance with this tool, so as not to mislead those who expect obvious behavior.

**Comment by Lonami** [comment]
v1 typing is in a sorry state. `types.Message` is monkey-patched with the `custom.Message` you found, but IDEs can have a hard time with that. I intended to improve that situation in v2 but I don't know when that will happen. I'm not really sure this is worth spending the time into fixing for v1.

But if you can get type hints to work, you're welcome to send a PR for the things you think are missing. Note that for inputs however "anything which looks like a message" works, not just that exact type (and that is, any object with `.id`, for most methods).
