### ISSUE TITLE
Exception handling by the user has a higher priority than by the library

### ISSUE THREAD

**Issue by simbadmorehod** [LonamiWebs/Telethon#4031]
As a code example:
`except (errors.ChannelPrivateError, errors.ChannelInvalidError):
          # Timeout triggered a get difference, but we have been banned in the channel since then.
          # Because we can no longer fetch updates from this channel, we should stop keeping track
          # of it entirely.
          self._log[__name__].info(
              'Account is now banned in %d so we can no longer fetch updates from it',
              get_diff.channel.channel_id
)`

I would like to handle this exception myself and based on that process the application logic, while this exception is caught by the Telethon module for me, tell me how to handle "Manually" similar exceptions that are already handled by the module at a higher level?

**Comment by Lonami** [comment]
What's your use case? What do you need this for? I did not (and currently still don't) have plans to expose this to end-users. But you may be able to convince me otherwise.

**Comment by simbadmorehod** [comment]
In fact, when such an error occurs, I would like to stop the process and notify the user that there is a problem with authorization of the user.

The same problem when a user is excluded from a channel or group, he can no longer receive or send messages from there, I would also like to exclude these tasks from the execution plan and notify the user about the problem.

I would appreciate if you could give me a simple solution on how to intercept such exceptions, thank you.

**Comment by Lonami** [comment]
> the process

Depending on what "the process" means, if you're fetching data, you will also find out that you were banned.

> I would appreciate if you could give me a simple solution on how to intercept such exceptions

This isn't really the place to ask for help, but you can probably read Python's `logging` documentation to set up a custom filter and be able to "hook" into that call (essentially a callback when that line is logged…).

**Comment by simbadmorehod** [comment]
Yes, I have received a similar response in the past.)
