### ISSUE TITLE
"message" function from custom package not working

### ISSUE THREAD

**Issue by wdano3akm** [LonamiWebs/Telethon#4032]
I tried using the message(str) function as found in the documentation

```
message ([str]):
    The string text of the message for [Message] instances, which will be [None] for other types of messages.

```
To create a qrcode maker
```python
from telethon import TelegramClient, events, custom

@client.on(events.NewMessage(outgoing=True, pattern = "\.qrcode"))
async def qrcode(event):
    if event.is_reply:
        replied = await custom.Message.message(event.get_reply_message())
        print(replied)
        img = qrcode.make(replied)
        img.save("qrcode.png")
        await event.reply("Here's your qrcode", client.send_file("path_to_file"))

```

However this issue arose:
```
replied = await custom.Message.message(event.get_reply_message())
AttributeError: type object 'Message' has no attribute 'message'

```

I don't know if it could be helpful but i created a class to fix the issue

```python

class canwefixit(object):
    def yeswecan(self, str):
        if "message" in str:
            index = str.find("message='")
            to_remove = str[:(index + len("message='"))]
            newstr = str.replace(to_remove, "")
            index = newstr.find("'")
            message = newstr[:index]
            return message


```

Based on the knowledge that the raw text of the message is preceded by `message="` and followed by `"`

**Comment by Lonami** [comment]
It's a property of `Message` instances (as in, `print(message.message)` to show its text), not a function you're expected to call. `await event.get_reply_message()` already returns a `Message`, there is no need to use any additional functions.

**Comment by wdano3akm** [comment]
> It's a property of `Message` instances (as in, `print(message.message)` to show its text), not a function you're expected to call. `await event.get_reply_message()` already returns a `Message`, there is no need to use any additional functions.

Thank you, I thought it was a function. Sorry for the inconvenience
