### ISSUE TITLE
I didn't found searchChartNearby API in Telethon. Pls update it to Telethon

### ISSUE THREAD

**Issue by pandawengogo** [LonamiWebs/Telethon#4035]
I need a searchChartsNearby API in my Application. But I don't find it in Telethon. pls add it to Telethon. thank you author.
And I found it in TDLib methods. and also in telegram client.
[search_chats_nearby](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1search_chats_nearby.html)

**Comment by Lonami** [comment]
TDLib builds functions on top of raw API which you can find in https://tl.telethon.dev. There you should find the same function that's being used underneath by `search_chats_nearby`. I don't know the name, but this is not the right place to ask for help, so I will be closing the issue (as it's not an issue).
