### ISSUE TITLE
ValueError: readexactly size can not be less than zero

### ISSUE THREAD

**Issue by DavidKoban** [LonamiWebs/Telethon#4038]
I have this error. When I start my project on server, but on local machine it was okay. Help me please to solve it.

**Comment by DavidKoban** [comment]
![16768187097588864596193318621490](https://user-images.githubusercontent.com/49913976/219956166-10277de1-8e40-4adf-b019-b237dc24f60c.jpg)

**Comment by Lonami** [comment]
Please follow the issue template.
