### ISSUE TITLE
wiki typos

### ISSUE THREAD

**Issue by lacerated** [LonamiWebs/Telethon#404]
Hello!
Trying to figureout updates and been reading https://github.com/LonamiWebs/Telethon/wiki/Working-with-Updates

Noticed misleading info there:
```
from telethon.tl.types import UpdateShortMessage, PeerUser

def replier(update):
    if isinstance(update, UpdateShortMessage) and not update.out:
        client.send_message(PeerUser(update.user_id), update.message[::-1])


client.add_update_handler(callback)
input('Press enter to stop this!')
```
Think it should be `client.add_update_handler(replier)` to make it work

Also how is `input('Press enter to stop this!')` there supposed to stop autoreplies? At least it didn't worked for me.
Think `client.remove_update_handler(replier)` might help here

**Comment by Lonami** [comment]
Anyone can edit so if you would like to do that. After the work is done (in this case after the `input()`) the client should always `.disconnect()`. This also ensures that the background workers are stopped.

> Think `client.remove_update_handler(replier)` might help here

Nah that has no effect, it only prevents such handler to receive more updates. But they will still be processed.
