### ISSUE TITLE
Unexpected exception in the receive loop

### ISSUE THREAD

**Issue by mi01** [LonamiWebs/Telethon#4042]
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**

The code is quite complex, so I can not post it here. But it was working without any problem before and now this error suddenly  appeared before I invoke anything else in the library ...
```python
from telethon.sync import TelegramClient

class TGController:
    client = TelegramClient(label, api_id, api_hash)

    async def foo(self):
        await self.client.start()
        ...

if __name__ == "__main__":
        controller = TGController()
        asyncio.run(controller.foo())
...

```

**Traceback**
```
python3[537]: >- 2023-02-21 05:21:47 Created new MessageBox with map = {}, date = datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), seq = 0
python3[537]: >- 2023-02-21 05:21:49 Connecting to 149.154.167.51:443/TcpFull...
python3[537]: >- 2023-02-21 05:21:49 Connection to 149.154.167.51:443/TcpFull complete!
python3[537]: >- 2023-02-21 05:21:49 Loading MessageBox with session_state = {'user_id': 0, 'dc_id': 0, 'bot': 0, 'pts': 15, 'qts': 0, 'date': 1676953309, 'seq': 6007, 'takeout_id': 0}, channel_states = []
python3[537]: >- 2023-02-21 05:21:50 The server closed the connection while sending
python3[537]: >- 2023-02-21 05:21:50 Connection closed while receiving data
python3[537]: >- 2023-02-21 05:21:50 Closing current connection to begin reconnect...
python3[537]: >- 2023-02-21 05:21:50 <class 'BrokenPipeError'> during disconnect: [Errno 32] Broken pipe
python3[537]: >- 2023-02-21 05:21:50 Connecting to 149.154.167.51:443/TcpFull...
python3[537]: >- 2023-02-21 05:21:50 Connection to 149.154.167.51:443/TcpFull complete!
python3[537]: >- 2023-02-21 05:21:50 Unexpected exception in the receive loop
python3[537]: Traceback (most recent call last):
python3[537]:   File "./venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 329, in _recv_loop
python3[537]:     data = await self._recv()
python3[537]:   File "./venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 372, in _recv
python3[537]:     return await self._codec.read_packet(self._reader)
python3[537]:   File "./venv/lib/python3.9/site-packages/telethon/network/connection/tcpfull.py", line 27, in read_packet
python3[537]:     body = await reader.readexactly(packet_len - 8)
python3[537]:   File "/usr/lib/python3.9/asyncio/streams.py", line 709, in readexactly
python3[537]:     raise ValueError('readexactly size can not be less than zero')
python3[537]: ValueError: readexactly size can not be less than zero
python3[537]: >- 2023-02-21 05:21:50 Connection closed while sending data
python3[537]: >- 2023-02-21 05:21:50 Closing current connection to begin reconnect...
python3[537]: >- 2023-02-21 05:21:50 Connection closed while receiving data
python3[537]: >- 2023-02-21 05:21:50 Connecting to 149.154.167.51:443/TcpFull...
python3[537]: >- 2023-02-21 05:21:50 Connection to 149.154.167.51:443/TcpFull complete!
... the same error again ...
```

**Comment by Lonami** [comment]
This is not the first time I've seen this reported, unfortunately, I have never been able to reproduce it, as far as I'm aware. If you can reliably trigger the issue, I encourage you to try to debug and fix this issue, and send a pull request. Otherwise, I will likely need either all the data sent and transmitted by the script (so that I can attempt to reproduce it locally without network access) or remote access to the machine so I can debug it there, both of which require you to trust me. But even then I can't guarantee that this is fixable.

If more people had this issue, the library would be literally unusable to many. Which doesn't seem to be the case, as not many report it, and those who do, don't report it often. Which likely indicates this may be a problem with the network or device where it's running.

**Comment by mi01** [comment]
Thank you for your reply. I can comprehend that this issue is hard to debug for you, so I tried to dig into the problem on my own, but my knowledge of the telethons codebase and MTProto is limited. But the problem is persistant, so I can repeat the scenario over and over again. I started adding some debug output in `telethon/network/connection/tcpfull.py`:

```
    async def read_packet(self, reader):
        packet_len_seq = await reader.readexactly(8)  # 4 and 4
        logging.info(f">>> packet_len_seq: {packet_len_seq.hex(' ')}")
        packet_len, seq = struct.unpack('<ii', packet_len_seq)
        logging.info(f">>> packet_len: {packet_len} - seq: {seq}")
        if packet_len <= 8:
            data = await reader.read(100)
            logging.warning(f">>> Packet len < 8 bytes - data: {data.hex(' ')}")

        body = await reader.readexactly(packet_len - 8)
        checksum = struct.unpack('<I', body[-4:])[0]
        body = body[:-4]

        valid_checksum = crc32(packet_len_seq + body)
        if checksum != valid_checksum:
            raise InvalidChecksumError(checksum, valid_checksum)

        return body
```

Then I ran the app  again with the following output:

```
>-  >>> packet_len_seq: c4 00 00 00 7d 01 00 00
>-  >>> packet_len: 196 - seq: 381
>-  >>> packet_len_seq: 14 01 00 00 7e 01 00 00
>-  >>> packet_len: 276 - seq: 382
>-  >>> packet_len_seq: c4 00 00 00 7f 01 00 00
>-  >>> packet_len: 196 - seq: 383
>-  >>> packet_len_seq: c4 00 00 00 80 01 00 00
>-  >>> packet_len: 196 - seq: 384
>-  The server closed the connection while sending
>-  Connection closed while receiving data
>-  Closing current connection to begin reconnect...
>-  <class 'BrokenPipeError'> during disconnect: [Errno 32] Broken pipe
>-  <class 'BrokenPipeError'> during disconnect: [Errno 32] Broken pipe
>-  Connecting to 149.154.167.51:443/TcpFull...
>-  Connection to 149.154.167.51:443/TcpFull complete!
>-  >>> packet_len_seq: 53 fe ff ff 53 fe ff ff
>-  >>> packet_len: -429 - seq: -429
>-  >>> Packet len < 8 bytes - data: 53 fe ff ff
>-  Unexpected exception in the receive loop
Traceback (most recent call last):
  File "./venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "./venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 375, in _recv
    return await self._codec.read_packet(self._reader)
  File "./venv/lib/python3.9/site-packages/telethon/network/connection/tcpfull.py", line 35, in read_packet
    body = await reader.readexactly(packet_len - 8)
  File "/usr/lib/python3.9/asyncio/streams.py", line 709, in readexactly
    raise ValueError('readexactly size can not be less than zero')
ValueError: readexactly size can not be less than zero
>-  Connection closed while sending data
>-  Closing current connection to begin reconnect...
>-  Connection closed while receiving data
>-  Connecting to 149.154.167.51:443/TcpFull...
>-  Connection to 149.154.167.51:443/TcpFull complete!
>-  >>> packet_len_seq: 53 fe ff ff 53 fe ff ff
>-  >>> packet_len: -429 - seq: -429
>-  >>> Packet len < 8 bytes - data: 53 fe ff ff
>-  Unexpected exception in the receive loop
... same error again ...
```
As you can see there is always the same byte string in the reader buffer after the reconnect, which is _53 fe ff ff_. Any idea why the server is sending this, or does this make no sense? I can supply you with a package capture from wireshark, if this would be helpful. Or any other idea, how to debug this problem further?

**Comment by Lonami** [comment]
Thanks, that's enough for me to diagnose the issue. HTTP 429 stands for "too many requests". I was aware of the [-404 `InvalidBufferError`](https://github.com/LonamiWebs/Telethon/blob/18da855dd4dc787b7aab08fecf3066bac80790ff/telethon/errors/common.py#L45). But when that happens, [the packet size is 8 bytes or less](https://github.com/LonamiWebs/Telethon/blob/18da855dd4dc787b7aab08fecf3066bac80790ff/telethon/network/mtprotostate.py#L157). I guess all Telethon needs is being taught about this error and properly raising an `InvalidBuffer`. It won't solve your problem per-se, but it won't be unexpectedly crashing anymore.

**Comment by mi01** [comment]
Ah, I did not consider negative numbers to be HTTP response codes. Good to know what is the reason for this problem. Can you predict when there will be a patch in the master? Would be great to get an appropriate exception from telethon as user (InvalidBuffer is ambiguous), so I can throttle load in this case.

**Comment by Lonami** [comment]
No ETA, but you're welcome to send a PR with a fix. The way I would suggest implementing is, check that the length is negative. If it is, and it matches the `seq`, read 4 bytes. If those 4 bytes are again the same, `raise InvalidBuffer` with all that's been read so far.

But naively raising that error inside `tcpfull.py` will likely lead to the same unexpected error. Probably the receive loop of `connection.py` needs to be taught to propagate some errors.

Or maybe we could pretend we only read 4 bytes, and return that -429, which will then be handled correctly.
