### ISSUE TITLE
Missed functions

### ISSUE THREAD

**Issue by M1V4D1M** [LonamiWebs/Telethon#4044]
Hi! Can u add some functions:
- [createChatInviteLink](https://core.telegram.org/bots/api#createchatinvitelink) 
- [editChatInviteLink](https://core.telegram.org/bots/api#editchatinvitelink)
- [revokeChatInviteLink](https://core.telegram.org/bots/api#revokechatinvitelink)

Because a didn't found them in library =(
Or, u can give me some instructions how can I call them directly?

**Comment by nitanmarcel** [comment]
Find them in tl.telethon.dev

**Comment by M1V4D1M** [comment]
<img width="475" alt="Screenshot 2023-02-22 at 10 59 14" src="https://user-images.githubusercontent.com/37630058/220558220-382ba45a-3f63-479d-9527-621baf5d76d7.png">


> Find them in tl.telethon.dev

@nitanmarcel can u provide the link, because I can't find any of them

**Comment by nitanmarcel** [comment]
> <img alt="Screenshot 2023-02-22 at 10 59 14" width="475" src="https://user-images.githubusercontent.com/37630058/220558220-382ba45a-3f63-479d-9527-621baf5d76d7.png">
> 
> > Find them in tl.telethon.dev
> 
> @nitanmarcel can u provide the link, because I can't find any of them

Because those are methods from the bot api. In MtProto they are named differently

https://tl.telethon.dev?q=chatinviterequest
