### ISSUE TITLE
Adding fuzz testing and integrating with Google/OSS-fuzz

### ISSUE THREAD

**Issue by jesslatimer** [LonamiWebs/Telethon#4045]
Hi,

I am wondering if Telethon would be interested in adding fuzz tests and integrating with oss-fuzz to help keep it secure and reliable. 

In case you are not familiar with fuzz testing, briefly, it is an additional layer of testing (working alongside other tests) that is particularly good at finding unexpected bugs, usually nested deep within code, as it doesn't rely on a developer's suspicion to target a piece of code for testing. [Wikipedia ](https://en.wikipedia.org/wiki/Fuzzing)explains it nicely:

>In programming and software development, fuzzing or fuzz testing is an automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program. The program is then monitored for exceptions such as crashes, failing built-in code assertions, or potential memory leaks.

Google offers a free, continuous fuzzing service called OSS-fuzz. If Telethon is integrated into oss-fuzz, the fuzz tests under Telethon will be built and then run once a day, to search for bugs and vulnerabilities in Telethon. This service can be integrated with the CI for Telethon, so that the fuzz tests are run for 10min or so for every pull request, preventing buggy code from being merged.

 If you are keen on adding Telethon to oss-fuzz and utilising fuzz testing I'd be happy to write up a simple fuzzer :)

**Comment by Lonami** [comment]
Thanks for the suggestion, but I'm not really interested. I can definitely see the value. But at the moment I have no energy to work on properly figuring out fuzzing tests for this library. If someone else is interested in sending a PR, I probably wouldn't mind running the fuzzing myself before I release a new minor version. But I also don't want Google running it.
