### ISSUE TITLE
Logout from all devices (client2) when use 2 clients at the same time

### ISSUE THREAD

**Issue by miratania** [LonamiWebs/Telethon#4046]
**Checklist**

* [x] The error is in the library's code, and not in my own. (Not sure about this, but with 1 client everything works fine)
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

v1.27.0 version Telethon

I am trying to use 2 clients at the same time, run them in main.py
Distributed 2 clients into different files (client1,client2)
It takes about 30 seconds and I am logged out from all devices in the client2 account
I found a similar error on StackOverFlow, but the result of solving this problem is not there.
Individually, both clients work perfectly.

**Code that causes the issue**
File client1/client2:
```python
import configparser

from telethon import TelegramClient, sync, events

# Config
config = configparser.ConfigParser()
config.read('config.ini')

api_id = config.getint('Client1', 'api_id')
api_hash = config.get('Client1', 'api_hash')
session_file_name = config.get('Client1', 'client_session_file')

client1 = TelegramClient(session_file_name, api_id, api_hash, sequential_updates = True)

```
File main:
```python
import asyncio

from client1 import client1
from client2 import client2
from logger import logger

async def create_task(client):
    try:
        print(client.session.filename)
        logger.info(f'Starting client (session_file - {client.session.filename})...')
        await client.start()

        logger.info(f'Running client (session_file - {client.session.filename})...')
        task = asyncio.create_task(client.run_until_disconnected())

        logger.info(f'Client (session_file - {client.session.filename}) is up and running.')

        return task
    except Exception as e:
        logger.error(f'Error while starting and running client (session_file - {client.session.filename}): {e}')

async def main():
    task_run_client1 = await asyncio.create_task(create_task(client1))

    task_run_client2 = await asyncio.create_task(create_task(client2))

    await asyncio.gather(task_run_client1, task_run_client2)

if __name__ == '__main__':
    asyncio.run(main())
```

**Traceback**
```
Возникло исключение: SessionRevokedError
The authorization has been invalidated, because of the user terminating all sessions (caused by GetDifferenceRequest)
  File "...\main_test.py", line 27, in main
    await asyncio.gather(client1, clien2)
  File "...main_test.py", line 30, in <module>
    asyncio.run(main())
telethon.errors.rpcerrorlist.SessionRevokedError: The authorization has been invalidated, because of the user terminating all sessions (caused by GetDifferenceRequest)
```

**Comment by Lonami** [comment]
This is very likely something that cannot be fixed from Telethon's side, but rather something Telegram does. We can't know how the Telegram server is implemented. So it is also impossible for me to explain why it happens.

**Comment by cashriver** [comment]
I get it too. And I can't understand why. I described my problem in more detail here:
https://ru.stackoverflow.com/questions/1499616/%d0%bf%d1%80%d0%b8-%d0%b0%d0%b2%d1%82%d0%be%d1%80%d0%b8%d0%b7%d0%b0%d1%86%d0%b8%d0%b8-%d1%81%d0%b5%d1%81%d1%81%d0%b8%d0%b8-%d0%b2-%d1%81%d0%b2%d0%be%d0%b5%d0%bc-api-%d0%bf%d1%80%d0%b8%d0%bb%d0%be%d0%b6%d0%b5%d0%bd%d0%b8%d0%b8-%d0%b8-%d1%81%d1%82%d0%b0%d1%80%d1%82%d0%b5-%d0%bf%d1%80%d0%b8%d0%bb%d0%be%d0%b6%d0%b5%d0%bd%d0%b8%d0%b5-%d0%b7%d0%b0%d0%ba%d1%80%d1%8b%d0%b2%d0%b0%d1%8e%d1%82%d1%81%d1%8f-%d0%b2%d0%be

**Comment by minaton-ru** [comment]
Same situation.
Iv tried to authorizate via StringSession but it did not help - Telegram logout me from my devices.

**Comment by G-Pavel** [comment]
Same situation ((

**Comment by G-Pavel** [comment]
Same situation (( but is even sadder ((
I am running this code:
```
with TelegramClient(StringSession(), API_ID, API_HASH) as client:
    print(client.session.save())
```
I enter the phone number and the code from the application into the terminal and get a session.
And within one minute telegram closes all open sessions on all cell phones (two).
I checked two phone numbers!

**Comment by G-Pavel** [comment]
<details><summary>…</summary><blockquote>

**Checklist**

    * [x]  The error is in the library's code, and not in my own. (Not sure about this, but with 1 client everything works fine)

    * [x]  I have searched for this issue before posting it and there isn't a duplicate.

    * [x]  I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.


v1.27.0 version Telethon

I am trying to use 2 clients at the same time, run them in main.py Distributed 2 clients into different files (client1,client2) It takes about 30 seconds and I am logged out from all devices in the client2 account I found a similar error on StackOverFlow, but the result of solving this problem is not there. Individually, both clients work perfectly.

**Code that causes the issue** File client1/client2:

```python
import configparser

from telethon import TelegramClient, sync, events

# Config
config = configparser.ConfigParser()
config.read('config.ini')

api_id = config.getint('Client1', 'api_id')
api_hash = config.get('Client1', 'api_hash')
session_file_name = config.get('Client1', 'client_session_file')

client1 = TelegramClient(session_file_name, api_id, api_hash, sequential_updates = True)
```

File main:

```python
import asyncio

from client1 import client1
from client2 import client2
from logger import logger

async def create_task(client):
    try:
        print(client.session.filename)
        logger.info(f'Starting client (session_file - {client.session.filename})...')
        await client.start()

        logger.info(f'Running client (session_file - {client.session.filename})...')
        task = asyncio.create_task(client.run_until_disconnected())

        logger.info(f'Client (session_file - {client.session.filename}) is up and running.')

        return task
    except Exception as e:
        logger.error(f'Error while starting and running client (session_file - {client.session.filename}): {e}')

async def main():
    task_run_client1 = await asyncio.create_task(create_task(client1))

    task_run_client2 = await asyncio.create_task(create_task(client2))

    await asyncio.gather(task_run_client1, task_run_client2)

if __name__ == '__main__':
    asyncio.run(main())
```

**Traceback**

```
Возникло исключение: SessionRevokedError
The authorization has been invalidated, because of the user terminating all sessions (caused by GetDifferenceRequest)
  File "...\main_test.py", line 27, in main
    await asyncio.gather(client1, clien2)
  File "...main_test.py", line 30, in <module>
    asyncio.run(main())
telethon.errors.rpcerrorlist.SessionRevokedError: The authorization has been invalidated, because of the user terminating all sessions (caused by GetDifferenceRequest)
```

https://github.com/LonamiWebs/Telethon/issues/4046#issue-1596966985

**Checklist**

    * [x]  The error is in the library's code, and not in my own. (Not sure about this, but with 1 client everything works fine)

    * [x]  I have searched for this issue before posting it and there isn't a duplicate.

    * [x]  I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.


v1.27.0 version Telethon

I am trying to use 2 clients at the same time, run them in main.py Distributed 2 clients into different files (client1,client2) It takes about 30 seconds and I am logged out from all devices in the client2 account I found a similar error on StackOverFlow, but the result of solving this problem is not there. Individually, both clients work perfectly.

**Code that causes the issue** File client1/client2:

```python
import configparser

from telethon import TelegramClient, sync, events

# Config
config = configparser.ConfigParser()
config.read('config.ini')

api_id = config.getint('Client1', 'api_id')
api_hash = config.get('Client1', 'api_hash')
session_file_name = config.get('Client1', 'client_session_file')

client1 = TelegramClient(session_file_name, api_id, api_hash, sequential_updates = True)
```

File main:

```python
import asyncio

from client1 import client1
from client2 import client2
from logger import logger

async def create_task(client):
    try:
        print(client.session.filename)
        logger.info(f'Starting client (session_file - {client.session.filename})...')
        await client.start()

        logger.info(f'Running client (session_file - {client.session.filename})...')
        task = asyncio.create_task(client.run_until_disconnected())

        logger.info(f'Client (session_file - {client.session.filename}) is up and running.')

        return task
    except Exception as e:
        logger.error(f'Error while starting and running client (session_file - {client.session.filename}): {e}')

async def main():
    task_run_client1 = await asyncio.create_task(create_task(client1))

    task_run_client2 = await asyncio.create_task(create_task(client2))

    await asyncio.gather(task_run_client1, task_run_client2)

if __name__ == '__main__':
    asyncio.run(main())
```

**Traceback**

```
Возникло исключение: SessionRevokedError
The authorization has been invalidated, because of the user terminating all sessions (caused by GetDifferenceRequest)
  File "...\main_test.py", line 27, in main
    await asyncio.gather(client1, clien2)
  File "...main_test.py", line 30, in <module>
    asyncio.run(main())
telethon.errors.rpcerrorlist.SessionRevokedError: The authorization has been invalidated, because of the user terminating all sessions (caused by GetDifferenceRequest)
```

</blockquote></details>

Have you solved the problem?

**Comment by LogovoStudio** [comment]
I have same problem
Deleting the .session used to help, now it doesn't work

**Comment by LordGvozd** [comment]
Solved the problem by deleting the .session file every time the client starts up
