### ISSUE TITLE
WebPageEmpty for bot.get_messages instead of WebPage

### ISSUE THREAD

**Issue by OlegBEZb** [LonamiWebs/Telethon#4054]
**Checklist**

* [x] The error is in the library's code, and not in my own (I hope).
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Issue**

I have the following flow:
1. user reads a message from some channel
2. user sends the message to the bot
3. bot reads the message

If the message contains WebPage media, for some reason WebPage from step 1 becomes WebPageEmpty in step 3. In other words, media disappears when the bot read the message with it.

**Code that causes the issue**
```python
from telethon import TelegramClient

user_client = TelegramClient(user_client_path, config.api_id, config.api_hash)

# get one message from any available channel
msg = await client.get_messages(entity=src_ch_id, **get_history_request_kwargs)[0]
# now msg has MessageMediaWebPage with media=WebPage

async with user_client:
    bot_entity = await user_client.get_input_entity(config.bot_id)
    # sends the message to the chat with the bot
    await user_client.forward_messages(entity=bot_entity, messages=msg, from_peer=src_ch_id)

bot_client = TelegramClient(bot_client_path, config.api_id, config.api_hash).start(bot_token=config.bot_token)
async with bot_client:
    bot_last_id = get_last_bot_id() # func that keeps the last ID in the chat
    msg = await bot_client.get_messages(config.my_id, ids=bot_last_id)
# now msg has MessageMediaWebPage with media=WebPageEmpty
```

**Comment by Lonami** [comment]
Bots can't access web previews.

**Comment by OlegBEZb** [comment]
thank you for the answer. I didn't find this in the doc. @Lonami , could you, please, navigate me to the corresponding place in the doc or the code?

**Comment by Lonami** [comment]
I'm not aware of any place explicitly documenting this. The response was based on my and other people's experience.
