### ISSUE TITLE
Every line is trying to send in new message. Too many requests (caused by SendMessageRequest)`

### ISSUE THREAD

**Issue by DiMiTriFrog** [LonamiWebs/Telethon#4056]
*  When i'm trying to send message, the api is splitting in more than one message.: 
* When i remove all break lines is working and sending the message. Why can't add breaklines ? I tried with <br>, <br /> (both didn't work) and with /n (same result than actual message).
* I'm having this issue only with Telethon, with other py telegram bot libraries is working right, but i need to send from real telegram user
* The account is not flagged, when i remove the break lines in the string, is sending the message.
* I think the api is splitting the string in various messages and Telegram thinks is flood. 
* My string has 12 break lines.

**Code that causes the issue**
```python
the_str = f"""Title

Some text

Some more text

Some end"""
await client.send_message(event.chat_id, str(the_str), parse_mode="html")`
...

```

**Traceback**
```
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by SendMessageRequest)

```

**Comment by Lonami** [comment]
Please follow the issue template. Telethon can send messages with newlines just fine. Peer flood means the account is flagged as spam.

**Comment by DiMiTriFrog** [comment]
> Please follow the issue template. Telethon can send messages with newlines just fine. Peer flood means the account is flagged as spam.

Sorry for the template, i thought is simple..
THe account is working, when i change the message or put the same message in one line its working, but if i put break lines i have this error.

i think the api is splitting the string in more than one messages... I want to send in single message.

**Comment by DiMiTriFrog** [comment]
> Please follow the issue template. Telethon can send messages with newlines just fine. Peer flood means the account is flagged as spam.

updated

**Comment by Lonami** [comment]
I and many others can send messages with newlines just fine. Telegram decides how to deal with flood limits based on the account, request, and probably other things. I very much doubt this error is "fixable" from Telethon's side. It's coming from Telegram and Telethon has no control over that.
