### ISSUE TITLE
If I download a file with message.download_media, I get a corrupted file

### ISSUE THREAD

**Issue by jonhef** [LonamiWebs/Telethon#4057]
I use message.download_media to download a file, but if the file is more than 10 megabytes, it gets corrupted, and the next time I send it, it sends not the original file, but a corrupted one, and something strange happens. i don't know what to do, please help. maybe you can tell me how to convert telethon.tl.custom.file into hints.FileLike, or send the file by ID, or how to know the direct link to the file, this would solve the problem

**Comment by Lonami** [comment]
Please follow the issue template.
