### ISSUE TITLE
Adding BotCommandScopeChatMember

### ISSUE THREAD

**Issue by alexbel2404** [LonamiWebs/Telethon#4059]
Please implement the command type BotCommandScopeChatMember. https://core.telegram.org/bots/api#botcommandscopechatmember

**Comment by Lonami** [comment]
I don't know what the equivalent is in raw API, but

https://github.com/LonamiWebs/Telethon/blob/1f79f063a28b40d251cee8821fae0f2771f890bf/telethon_generator/data/api.tl#L1332-L1338

seems very likely to be what you need, which is already available if you install the development version, and will be in the next release.
