### ISSUE TITLE
Attempt 1 at connecting failed: TimeoutError:

### ISSUE THREAD

**Issue by liaoxingquan** [LonamiWebs/Telethon#4060]
from telethon import TelegramClient, events, sync
import socks
# These example values won't work. You must get your own api_id and
# api_hash from https://my.telegram.org, under API Development.

api_id = 0
api_hash = '**'
host = '127.0.0.1'  # a valid host
port = 0000  # a valid port
proxy = (socks.SOCKS4, host, port)

client = TelegramClient('00000',api_id,api_hash,proxy=proxy)
client.start()

and then wrong :  Attempt 1 at connecting failed: TimeoutError:

**Comment by Lonami** [comment]
Please follow the issue template.

It seems like it's a network issue, or issue with the proxy, which is not something Telethon can fix.

**Comment by liaoxingquan** [comment]
But my proxy settings are okay,

Because my local Telegram client can log in

**Comment by wei-z-git** [comment]
I use the http proxy and it works,
client = TelegramClient('haha', api_id, api_hash,proxy=("http", '192.168.0.107', 7890))

**Comment by hyperbolic-c** [comment]
> I use the http proxy and it works, client = TelegramClient('haha', api_id, api_hash,proxy=("http", '192.168.0.107', 7890))

@wei-z-git hi, could you please tell me what proxy you used? I have try many proxy but it does not work, thanks!

**Comment by chenyu1990** [comment]
> > I use the http proxy and it works, client = TelegramClient('haha', api_id, api_hash,proxy=("http", '192.168.0.107', 7890))
> 
> [@wei-z-git](https://github.com/wei-z-git) hi, could you please tell me what proxy you used? I have try many proxy but it does not work, thanks!

It's a telethon problem, I use other libraries normally.

**Comment by wzshuang** [comment]
> > > I use the http proxy and it works, client = TelegramClient('haha', api_id, api_hash,proxy=("http", '192.168.0.107', 7890))
> > 
> > 
> > [@wei-z-git](https://github.com/wei-z-git) hi, could you please tell me what proxy you used? I have try many proxy but it does not work, thanks!
> 
> It's a telethon problem, I use other libraries normally.

hi, could you please tell me what libraries you used
