### ISSUE TITLE
event.Album does not see events sent by another bot to the channel

### ISSUE THREAD

**Issue by Etvanser** [LonamiWebs/Telethon#4061]
**Checklist**

* [ ] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [х ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
@client.on(events.Album(chats=[id_chanel]))
    print('NewMessage', event.grouped_id)
...

If the album is sent to the channel by a bot. For example @FleepBot. Then the events.Album method does not return grouped_id. If you send manually, the grouped_id is returned

**Comment by Lonami** [comment]
If you use `events.NewMessage`, do the messages have `grouped_id`? How many messages are received? Are you sure they actually belong to an album?

**Comment by Etvanser** [comment]
If I use event.New message, then grouped_id is missing. The id of each element is present separately. If the album was not sent by a bot, then event.Album is present. The problem appeared relatively recently. There were no problems before that

**Comment by Lonami** [comment]
> If I use event.New message, then grouped_id is missing

The current Telethon version doesn't remove the `grouped_id` under any circumstance. So it's very likely Telegram is not including the album ID, for whatever reason. And therefore, this is not something Telethon can fix, so I'll close this issue.

(My suspicion is that it's not an album at all. But the API may be behaving in a strange manner.)
