### ISSUE TITLE
View of search type

### ISSUE THREAD

**Issue by jack-manual** [LonamiWebs/Telethon#4062]
Hello
How in telethon view from the search type on the post

So that it can be seen in Telegram statistics

is this possible?

![photo_2023-03-18_14-08-11](https://user-images.githubusercontent.com/92995399/226100453-24c7ad6d-c3d2-4609-9a09-b6b4b7d272c4.jpg)

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
