### ISSUE TITLE
How to check integrity of uploaded file?

### ISSUE THREAD

**Issue by divyam234** [LonamiWebs/Telethon#4065]
I am uploading files through multiple connections  to speed up the process  but  sometimes files are not fully uploaded so  I want to  check if uploaded file has same hash as  original  file.

**Comment by Lonami** [comment]
Data sent to Telegram is encrypted in such a way that I would expect any transmission errors under the wire would be caught. You should just need to make sure all parts corresponding to the file are fully uploaded before you attempt to use it. There is no way to check the hash of an uploaded file as far as I'm aware (but again, you shouldn't need that).

This isn't really something Telethon needs to solve so I'll close the issue.
