### ISSUE TITLE
Move database version check and table creation from __init__ in SQLiteSession

### ISSUE THREAD

**Issue by alozovskoy** [LonamiWebs/Telethon#4066]
Hello!

I want to use postgresql to store sessions data. For this task i consider to subclass from `SQLiteSession`, because it's have all necessery methods, and i should override only database connection and some other stuff like retrive cursors. Now the check of database version and create tables (if not exist) is performed in `__init__`, so when i override `__init__` i should copypaste all of it. I think this can easily moved into separate functions.

**Comment by Lonami** [comment]
I think it's fine for you to copy paste all that code. You can definitely subclass `SQLiteSession` but I did not design it with subclassing in mind, and I don't have plans to change that for the time being, sorry.

Other than that, the database code is unlikely change in v1 of the library.
