### ISSUE TITLE
sendContact shares contact which is greyed out

### ISSUE THREAD

**Issue by Slava1793** [LonamiWebs/Telethon#4068]
When trying to share contact with sendContact(even if user has shared his telephone number via KeyboardButton(request_contact=True)) sometimes the shared contact is greyed out and user has no option to write him directly but only has options to invite to telegram or to add to contacts. I believe that it might be connected with privacy of telegram user and lifetime of request_contact, but unfortunately I haven't found anything in telegram API docs. Could you please clarify this point?

Thanks

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
