### ISSUE TITLE
npcerrorlist.UserBannedInChannelError - 

### ISSUE THREAD

**Issue by mcontetjsp** [LonamiWebs/Telethon#4070]
Hi everyone, recently my app started banning all my accounts, it was working normally until last week, can anyone help me understand why?

**Código - Telethon 1.27**
```python

...
client.connect()

try:
        receiver = client.get_input_entity("username")
        client(InviteToChannelRequest(target_group_entity, receiver))
except:
        traceback.print_exc()
        sys.exit()

client.disconnect()
...

```

**Traceback**
```
Traceback (most recent call last):
telethon.errors.rpcerrorlist.UserBannedInChannelError: You're banned from sending messages in supergroups/channels (caused by InviteToChannelRequest)

```

Any account I try to add causes me this same error, can I use old or new accounts, I will be blocked on any attempt, someone to help me please?

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
