### ISSUE TITLE
The query ID is invalid (caused by SetBotCallbackAnswerRequest)

### ISSUE THREAD

**Issue by PerchunPak** [LonamiWebs/Telethon#4073]
Hello, Sentry caught #4002 a few times, although I don't know what is the reason for the error. All what I have - a report on Sentry, so I don't know what to provide more.

https://perchunpak.sentry.io/share/issue/55deb7db50b74e96803957872c3b5c84/

---

```
Task exception was never retrieved
future: <Task finished name='Task-331' coro=<CallbackQuery.Event.answer() done, defined at /usr/local/lib/python3.11/site-packages/telethon/events/callbackquery.py:218> exception=QueryIdInvalidError('The query ID is invalid (caused by SetBotCallbackAnswerRequest)')>
...
QueryIdInvalidError: The query ID is invalid (caused by SetBotCallbackAnswerRequest)
  File "telethon/events/callbackquery.py", line 244, in answer
    return await self._client(
  File "telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "telethon/client/users.py", line 84, in _call
    result = await future
```

**Comment by Lonami** [comment]
Make sure you're answering queries fast enough, [Telegram's timeout seems to be pretty low](https://t.me/TelethonChat/536961):

> probably this, is just an expired query. I did got a lot of those, that's why I had to send a message and edit it after.
>
> The timeout time is pretty low too

Let me know if you managed to verify that the answers are quick and the issue persists. Note that Telegram may be slow to send the updates, so even if `answer` happens fast and the handler doesn't take too long, it may still be too late.

Until then, I'll close the issue.
