### ISSUE TITLE
GetLocatedRequest returns cached data and does not work in the latest version

### ISSUE THREAD

**Issue by woj-ciech** [LonamiWebs/Telethon#4074]
**Checklist**

* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
client = TelegramClient(StringSession(sessio), "", "")

async def main():
    results = await client(functions.contacts.GetLocatedRequest(
            geo_point=types.InputGeoPoint(
                lat=float(lat),
                long=float(lon),
                accuracy_radius=42,
            ),
    self_expires=1
    )
    )
    for i in results.users:
        user_id = i.id
        print(user_id)


with client:
    lat = 49.8155984164182
    lon = 18.275489226890738
    client.loop.run_until_complete(main(lat,lon))

```

This code should return users based on provided coordinates.
In version 1.24.0 it returns same data for any latitude and longitude provided. I'm not sure if it's not cache related.

In version 1.27.0 it returns 
```
Server sent a very new message with ID 7216007778471571461, ignoring
Server sent a very new message with ID 7216007778514435073, ignoring
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Unhandled error while receiving data
Traceback (most recent call last):
  File "/root/PycharmProjects/telethon_test/telethon_test/venv/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 505, in _recv_loop
    body = await self._connection.recv()
  File "/root/PycharmProjects/telethon_test/telethon_test/venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 301, in recv
    raise err
  File "/root/PycharmProjects/telethon_test/telethon_test/venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/root/PycharmProjects/telethon_test/telethon_test/venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/root/PycharmProjects/telethon_test/telethon_test/venv/lib/python3.9/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
```
and no data is returned

**Comment by Lonami** [comment]
The library doesn't cache responses to requests. The most it caches is entities returned by them, but the result you get from invoking a request is always returned directly by Telegram.

This means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

As for the logs from 1.27.0, it seems to be unrelated to the request itself. Make sure your system time is correct, and that the session you're using is not in use anywhere else. "Server closed the connection" is also something Telethon can't really work around.

It is possible Telethon is sending bad data to Telegram somehow. But this is extremely unlikely. All code is generated in the same way, and `GetLocatedRequest` isn't really special. Other than using doubles, but those are serialized fine:

```python
from telethon.tl import types, functions
from telethon.extensions import BinaryReader

original = functions.contacts.GetLocatedRequest(
    geo_point=types.InputGeoPoint(
        lat=float(12.34),
        long=float(56.78),
        accuracy_radius=42,
    ),
    background=False,
    self_expires=1
)

reencoded = BinaryReader(bytes(original)).tgread_object()

assert reencoded == original
```

**Comment by Sinnerman07** [comment]
@woj-ciech did you solve this problem? because I had same issue with GetLocatedRequest method. It always turn same locations

**Comment by woj-ciech** [comment]
@Sinnerman07  No, I didn't sorry. The only thing that worked for me was to complete delete the session and start it again, however it's not scalable in my case.
