### ISSUE TITLE
 Get a bug, always when i try to run code

### ISSUE THREAD

**Issue by ekondrashov25** [LonamiWebs/Telethon#4076]
**Checklist**

* [ x] The error is in the library's code, and not in my own.
* [ x] I have searched for this issue before posting it and there isn't a duplicate.
* [ x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

### I ran this code a week ago and everything worked perfectly, but now that I’m running it, I keep getting this bug and the same current telegram session on all my devices goes missing and leaves my account

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
import config

client = TelegramClient('anon', api_id, api_hash)
client.start()
chat_id = config.chat_id
chat_id2 = config.chat_id2

@client.on(events.NewMessage(chat_id))
async def main(event):
    await client.forward_messages(chat_id2 , event.message)

client.run_until_disconnected()
```

**Traceback**
```
telethon.errors.rpcerrorlist.SessionRevokedError: The authorization has been invalidated, because of the user terminating all sessions (caused by GetDifferenceRequest)

```

**Comment by Lonami** [comment]
This error comes from Telegram. It's not something Telethon can fix. See #4051.
