### ISSUE TITLE
Session crash

### ISSUE THREAD

**Issue by KindSpidey** [LonamiWebs/Telethon#4077]
Hello guys. I didnt find this issue here, but I think it should be here. Looks like it is a very big bug which ruins using of Telethon. 

A few days ago my code just stopped work. It required mobile phone, code and after successfull authorization and one minute of work (or just immediately) ALL sessions (on my phone, web, PC, all devices) just logged out.

This is described by other people perfectly, I got same situation - https://askto.pro/question/why-does-telethon-script-end-all-sessions

How it can be fixed?

**Comment by Lonami** [comment]
Likely a duplicate of #4051.
