### ISSUE TITLE
Running as Service / in background

### ISSUE THREAD

**Issue by digitaldesaster** [LonamiWebs/Telethon#408]
Hi, thank you very much for your work. 
i like to run the update example in the background  / as a service
https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/print_updates.py

i wonder why the update_handler function is not called if i run it in background, e.g. 
"nohup ./print_updates.py &"
any ideas?

best regards
Alex

**Comment by Lonami** [comment]
What does your code look like right now? It seems like you just want to idle the main thread. The wiki shows how. Glad you like the library!

**Comment by digitaldesaster** [comment]
it is almost your example code https://pastebin.com/BqPFunvN
thanks for looking into it.. br Alex

**Comment by Lonami** [comment]
```python
def main():
    client = TelegramClient(session_name,api_id,api_hash,proxy=None,update_workers=4)
 
    print('INFO: Connecting to Telegram Servers...', end='', flush=True)
    client.connect()
    print('Done!')
 
    if not client.is_user_authorized():
        print('INFO: Unauthorized user')
        client.send_code_request(user_phone)
        code_ok = False
        while not code_ok:
            code = input('Enter the auth code: ')
            try:
                code_ok = client.sign_in(user_phone, code)
            except SessionPasswordNeededError:
                password = getpass('Two step verification enabled. Please enter your password: ')
                code_ok = client.sign_in(password=password)
    print('INFO: Client initialized succesfully!')
 
    client.add_update_handler(update_handler)
    #input('Press Enter to stop this!\n')
 
def update_handler(update):
    print(update)
    print('Press Enter to stop this!')
 
if __name__ == '__main__':
    main()
```

**Comment by Lonami** [comment]
Well your issue is the line you commented…:
> ```python
>     #input('Press Enter to stop this!\n')
> ```

The function ends and the script terminates. [Please do as the wiki describes here](https://github.com/LonamiWebs/Telethon/wiki/Working-with-Updates#using-the-main-thread-instead-the-readthread).

**Comment by digitaldesaster** [comment]
thanks, will take a look into it
