### ISSUE TITLE
How to Download Media from Telegram Channel?

### ISSUE THREAD

**Issue by AboRamy** [LonamiWebs/Telethon#4083]
Hello
I have tried this Code in order to download media from a telegram channel  (for example @xxxxxxxxx)

========================================
api_id = xxxxxxxx
api_hash = 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
name = 'session1'

from telethon.sync import TelegramClient
from telethon import functions, types

with TelegramClient(name, api_id, api_hash) as client:
    result = client(functions.channels.GetFullChannelRequest(
        channel='@xxxxxxxxx'
    ))
    message.download_media()

========================================

I got this error

File "C:\Users\user\AppData\Local\Programs\Python\Python39\telethon-test\get.py", line 12, in <module>
    message.download_media()
NameError: name 'message' is not defined

========================================
Please help! and thanks

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
