### ISSUE TITLE
cannot send requests while disconnected

### ISSUE THREAD

**Issue by ghost** [LonamiWebs/Telethon#4085]
hello everyone, I have successfully connected to the session file, I get the message cannot send requests while disconnected when inviting members to the group, and then my main account is dead, can you give me Do you know why my account is dead?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
