### ISSUE TITLE
Which users increase count views.

### ISSUE THREAD

**Issue by Egor-Kotovsky** [LonamiWebs/Telethon#409]
For example, I get count views from channel message ( 100 ).
Can I get information, which users form count views (100). 
If yes, how will get list of this users?

**Comment by Lonami** [comment]
You haven't looked hard enough.

**Comment by Egor-Kotovsky** [comment]
What method allows do it?

**Comment by Lonami** [comment]
Please look for old issues.

**Comment by Egor-Kotovsky** [comment]
I looked all issues, but I don`t find the same issue.
If you will have enough time, please help me in this question. Sorry for my English.
The problem is next:
1) I have count of views, for example it 5
2) How I can know which users formed this count 5 ?
3) In result I want get list of ID Users, for example ( us1, us2, us3, us4, us5 ) count=5
4) It is necessary to know who illegal increase views in channel messages.
Thank you.

**Comment by Lonami** [comment]
> How I can know which users formed this count 5 ?

Can you from official clients? No. You can't.

> In result I want get list of ID Users

That's impossible.

> It is necessary to know who illegal increase views in channel messages.

"Illegal"? Either way you **can't**.
