### ISSUE TITLE
Reaction event

### ISSUE THREAD

**Issue by prsai** [LonamiWebs/Telethon#4093]
Hola, I'm using Telethon 1.28.5, I'm trying to capture the events for reactions.
I use this code snippet:
```
#!/usr/bin/python3

from telethon import TelegramClient, events

api_id = XXXXXX
api_hash = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

with TelegramClient('sesion', api_id, api_hash) as client:
    @client.on(events.Raw)
    async def handler(event):
        print(event.stringify())

    client.run_until_disconnected()
```

From official Web Z client I add the reaction to a message sent by myself (in "saved messages"):
![test-reactions](https://user-images.githubusercontent.com/10794595/232921050-abc9ab6d-4175-48f0-8673-de06d6de3329.png)

These are the events I receive in Telethon:
```
UpdateUserStatus(
    user_id=XXXXXXX,
    status=UserStatusOnline(
        expires=datetime.datetime(2023, 4, 18, 19, 56, 41, tzinfo=datetime.timezone.utc)
    )
)
UpdateEditMessage(
    message=Message(
        id=XXXXXXX,
        peer_id=PeerUser(
            user_id=XXXXXXX
        ),
        date=datetime.datetime(2023, 4, 18, 19, 51, 9, tzinfo=datetime.timezone.utc),
        message='test',
        out=False,
        mentioned=False,
        media_unread=False,
        silent=False,
        post=False,
        from_scheduled=False,
        legacy=False,
        edit_hide=True,
        pinned=False,
        noforwards=False,
        from_id=None,
        fwd_from=None,
        via_bot_id=None,
        reply_to=None,
        media=None,
        reply_markup=None,
        entities=[
        ],
        views=None,
        forwards=None,
        replies=None,
        edit_date=datetime.datetime(2023, 4, 18, 19, 51, 44, tzinfo=datetime.timezone.utc),
        post_author=None,
        grouped_id=None,
        reactions=MessageReactions(
            results=[
                ReactionCount(
                    reaction=ReactionEmoji(
                        emoticon='ð'
                    ),
                    count=1,
                    chosen_order=0
                ),
            ],
            min=False,
            can_see_list=False,
            recent_reactions=[
                MessagePeerReaction(
                    peer_id=PeerUser(
                        user_id=XXXXXXX
                    ),
                    date=datetime.datetime(2023, 4, 18, 19, 51, 44, tzinfo=datetime.timezone.utc),
                    reaction=ReactionEmoji(
                        emoticon='ð'
                    ),
                    big=False,
                    unread=False
                ),
            ]
        ),
        restriction_reason=[
        ],
        ttl_period=None
    ),
    pts=638180,
    pts_count=1
)
UpdateUserStatus(
    user_id=XXXXXXX,
    status=UserStatusOffline(
        was_online=datetime.datetime(2023, 4, 18, 19, 51, 45, tzinfo=datetime.timezone.utc)
    )
)
```
**My question is:** according to the answer given by @Lonami in [Stackoverflow](https://stackoverflow.com/questions/75843700/how-to-monitor-telegram-message-reactions-using-telethon) I had to have received a `UpdateMessageReactions` event instead of `UpdateEditMessage` I have received currently.
Which is really the expected event? Could be a library bug?
As `UpdateEditMessage` is recevied when a text edition is done it's a bit diffcult to distinguish between it and a reaction, specially when a previous reaction already existed for the message.

I also tried to capture the `UpdateMessageReactions` as suggested in the answer with no event received, using the same code modified:
```
 #!/usr/bin/python3
 
 from telethon import TelegramClient, events
+from telethon.tl.types import UpdateMessageReactions
 
 api_id = XXXXXX
 api_hash = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
 
 with TelegramClient('sesion', api_id, api_hash) as client:
-    @client.on(events.Raw)
+    @client.on(events.Raw(UpdateMessageReactions))
     async def handler(event):
         print(event.stringify())
```
Thanks.

**Comment by Lonami** [comment]
Thanks for the detailed report.

> Which is really the expected event?

That's up to Telegram. They could change it any time. I suppose my answer may not be entirely accurate. I do not know when Telegram decides to send which.

> Could be a library bug?

No. The library does not modify what `events.Raw` you get.

> As `UpdateEditMessage` is recevied when a text edition is done it's a bit diffcult to distinguish between it and a reaction, specially when a previous reaction already existed for the message.

Unfortunately there's really no other way. I guess you could check the edit date in the message to determine whether it was a "real" edit or just new reactions.
