### ISSUE TITLE
When I searched for the channel name, there was no information returned here. I also tested on the app that the channel exists and cannot return any information here.

### ISSUE THREAD

**Issue by misskiki** [LonamiWebs/Telethon#4094]
async def search_channels(channel_name):
    await connect()
    await login()
    channels = []
    dialogs = await client.get_dialogs()  # 等待结果返回
    for dialog in dialogs:
        if dialog.is_channel and channel_name in dialog.name:
            channels.append(dialog)
        print(dialog.name)
    return channels
When I searched for the channel name, there was no information returned here. I also tested on the app that the channel exists and cannot return any information here.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
