### ISSUE TITLE
MsgIdInvalidError: when fetching comments while looping through messages. 

### ISSUE THREAD

**Issue by dipdey1** [LonamiWebs/Telethon#4095]
### MsgIdInvalidError: The message ID used in the peer was invalid (caused by GetRepliesRequest)

```
async def get_comments():
  await client.start()
  channel = await client.get_entity(group_username)
  all_comments = []
  async for message in client.iter_messages(channel, reverse=True):
    async for comment in client.iter_messages(channel, reply_to=message.id):
      comment_dict = {'id': comment.id,
                  'text': comment.text,
                  'date': comment.date.isoformat(),
                  'messageId': message.id}
      all_comments.append(comment_dict)
  
  return all_comments
```

The code runs perfectly well when reply_to paramter has the direct value of the messageid.
for example:

```
async for message in client.iter_messages(channel, reverse=True, limit=2):
 async for comment in client.iter_messages(channel, reply_to=1093):
```
but as soon as I am looping through a list of message ID values and passing it as the parameter value,
the error surfaces. 

Traceback:

```
MsgIdInvalidError                         Traceback (most recent call last)
[<ipython-input-87-9f68a1db1b20>](https://localhost:8080/#) in <cell line: 1>()
----> 1 comments = asyncio.run(get_comments())

11 frames
[/usr/lib/python3.9/asyncio/futures.py](https://localhost:8080/#) in result(self)
    199         self.__log_traceback = False
    200         if self._exception is not None:
--> 201             raise self._exception
    202         return self._result
    203 

MsgIdInvalidError: The message ID used in the peer was invalid (caused by GetRepliesRequest)
```

for testing purposes:
`group_username = 'v_vap'`

**Comment by Lonami** [comment]
Thanks for the detailed report. You probably can't get comments for messages before a channel was linked is my guess. Also, I doubt it's possible to reply to service messages (like "channel created"). You can see in Telegram Desktop that not all messages can be used to leave a comment:

![image](https://user-images.githubusercontent.com/6297805/233673089-42937d0b-6a2b-4ffd-a0f1-14a4d1dda23d.png)

![image](https://user-images.githubusercontent.com/6297805/233673120-987276cd-7e72-4255-83da-ff2c5c30ecfd.png)

So I doubt there's anything that can be "fixed".
