### ISSUE TITLE
Dear developers, please add subscription check function

### ISSUE THREAD

**Issue by 31onMusk** [LonamiWebs/Telethon#4098]
Hello dear developers, I have some problems with my code, I want to check are I subscribed to Channel/Group or not and if not then do stuff, but I don't found any way to do that.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
