### ISSUE TITLE
is there any method for delete messages?

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [LonamiWebs/Telethon#41]
hello, is there any method equivalent to telegram-cli delete-msg command?

**Comment by Lonami** [comment]
Yes, `telethon/tl/functions/messages/delete_messages.py`, you have to `.invoke()` the `DeleteMessagesRequest` method with the right paramteres. If you want to know how to invoke methods, check out the `InteractiveTelegramClient`. If that's not enough, check the `TelegramClient` itself

**Comment by alirezaafzalaghaei** [comment]
Tanks. So how can i get message id? Can you show me an example?
I cant find project documentation. where is it? I have a lot of questions and think its better to read documentation or some examples :smile:
