### ISSUE TITLE
Get User.access_hash, when i know only User.id

### ISSUE THREAD

**Issue by skvoshiz** [LonamiWebs/Telethon#410]
How i can Get User.access_hash, when i know only User.id ?

**Comment by Lonami** [comment]
Yoy haven't tried much have you?

**Comment by skvoshiz** [comment]
@Lonami  if i use https://lonamiwebs.github.io/Telethon/methods/users/get_users.html
i need write access_hash
so i dont know access_hash
know only id

**Comment by Lonami** [comment]
Well there's this thing called wiki that explains certain methods to do what you need.

**Comment by skvoshiz** [comment]
@Lonami sorry, i just not found method where i can get user.access_hash, if i know only user.id
You can show me?

**Comment by Lonami** [comment]
Of course! https://github.com/LonamiWebs/Telethon/wiki.

**Comment by skvoshiz** [comment]
@Lonami can you show me method on https://lonamiwebs.github.io/Telethon/methods/index.html ?

**Comment by Lonami** [comment]
It's not there. I have linked the wiki for a reason.

**Comment by Lonami** [comment]
[It isn't that hard](https://github.com/LonamiWebs/Telethon/wiki/Retrieving-an-entity). Thanks.

**Comment by skvoshiz** [comment]
@Lonami I see, but this example use GetUsersRequest
GetUsersRequest have Parameters 'id' = InputUser
So InputUser have Parameters 'user_id' and 'access_hash'
I know only user_id, and dont know access_hash
