### ISSUE TITLE
telethon.errors.rpcerrorlist.BotInvalidError: This is not a valid bot (caused by GetInlineBotResultsRequest)

### ISSUE THREAD

**Issue by TrueGodOfHyperdeath** [LonamiWebs/Telethon#4100]
Hello. When I try to display a list of inline buttons, BotInvalidError is displayed. I double-checked the bot username and inline support. the error pops up at this point (bot username and text are hidden):

`results = await client.inline_query('usernamebot', 'some text')`.

**Comment by Lonami** [comment]
Telethon doesn't produce `BotInvalidError` by itself. It is Telegram sending the error. Because of this, I don't think Telethon can do anything to "fix" it.

**Comment by TrueGodOfHyperdeath** [comment]
> Telethon doesn't produce `BotInvalidError` by itself. It is Telegram sending the error. Because of this, I don't think Telethon can do anything to "fix" it.

What could possibly be the reason for this error?

**Comment by Lonami** [comment]
I don't know. I have experience with the protocol used by the library and what the library does, but not so much how Telegram's API works, specially more recent features or changes such as this one.

**Comment by TrueGodOfHyperdeath** [comment]
> I don't know. I have experience with the protocol used by the library and what the library does, but not so much how Telegram's API works, specially more recent features or changes such as this one.

I'm understood, thank you. Most likely the reason was that I did not delete the .session file from another account. After deleting this file and re-logging into the account, the error disappeared.
