### ISSUE TITLE
The speed of method GetRepliesRequest

### ISSUE THREAD

**Issue by Fengzdadi** [LonamiWebs/Telethon#4103]
If I just get the history message in group or channel, every 100 message just need few seconds. However, when I add the GetRepliesRequest methon to get the comments of message, It spend few minutes to get 100 messages with their comments. In most cases, the comments is not too much or maybe doesn't exist. So could this speed be accelerated? I also want to know how the method GetRepliesRequest implement? Does it traverse the historical messages first, and then take out the replies that matches the messageid pointed to by replies?

**Comment by Lonami** [comment]
`GetRepliesRequest` is part of what's known as "raw API", which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). This includes the "speed" of the method. Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

As for how it's implemented, we can't know. We would need to know what the Telegram server does. Telethon simply sends the request to Telegram and Telegram does the processing.

**Comment by Fengzdadi** [comment]
Thank you
