### ISSUE TITLE
Server sent a very new message with ID

### ISSUE THREAD

**Issue by Attila888** [LonamiWebs/Telethon#4105]
I have a simple script with on linux works on windows 11 I have this issue 'Server sent a very new message with ID': 
i thing may be a problem with sql lib datetime / localtime / timezone. I try to move the .session file created by win to linux and i works.

**Comment by Lonami** [comment]
That check is a security feature. There is nothing to fix here.

**Comment by Attila888** [comment]
Thanks for the reply, I had read this motivation on the web. But it is not clear to me why the control of the .session file works on linux (I can reuse .session several times) and on win11 it doesn't (same script and as indicated the same .session file produced among other things with windows). Having had problems with sqlite and timezone/localtime/tzdata in the past I wanted to make this suggestion. fortunately at the moment I have to use the script on linux.

**Comment by Lonami** [comment]
The library should detect the correct time offset during the initial connection but probably won't if it changes while running. Some proxies may also affect this.

I haven't experienced it myself so it's hard for me to debug, but if you believe something is wrong or could be done better, feel free to give it a stab.
