### ISSUE TITLE
Add ability to disable some hard-coded output ("Signed in successfully as user" when logging in using `.start()`)

### ISSUE THREAD

**Issue by Andrew15-5** [LonamiWebs/Telethon#4107]
I want to have an option to disable user-friendly messages (quiet/silent mode).  I tried disabling logging, but it didn't work, because some messages are printed using standard `print()` function:

https://github.com/LonamiWebs/Telethon/blob/c4a41adae591154915804eaf23b53c0e6599b941/telethon/client/auth.py#L244

As one can use this Python package in a script, it is always desirable to have a full control of what is printed out in stdout in your own script. When user is logged in, then `.start()` method won't print anything, otherwise it will print something. I don't want that.

The easiest solution would be to add `quiet` positional parameter with the default value of `False`. Or the `file` parameter of the `print()` function can be used to be able to send the output to anywhere (stdout, stderr, devnull or any existing file). And finally, the logging may be involved, but I'm not familiar with that, so I'm not sure about it.

**Comment by Lonami** [comment]
`start()` is meant to be used when you want the interactive login flow (and it's also called when using `with`). Changing any of this would be a breaking change.

You can simply not use either of the two and do the login flow manually (`connect`, `is_user_authorized`, `send_code_request` and `sign_in`).

**Comment by Andrew15-5** [comment]
Oh, and I read (in documentation) that simply using `start()` is enough (when I was exploring `sign_in()` and others). That is why I started using `start()` right away. Thank you, I will rewrite my logic then.

**Comment by Lonami** [comment]
`start()` is enough since it does all the things for you, but it was not my intention to imply in the documentation that it was the *only* way to do it.

**Comment by Andrew15-5** [comment]
I'm not saying that it implies the "only", I'm saying that if `.start()` is the easiest/all-in-one solution, then I probably should use it, but I didn't see in the documentation that it _also implies_ the additional unremovable `print()` statement(s).

In other words, this method is not a one-to-one substitution, but rather a substitution that "gets the job done" all by itself + some deviations in form of a printed user-friendly text.

If it's possible or appropriate, then it would be nice to say about this small detail in the documentation of the `.start()` method.

**Comment by Lonami** [comment]
You're welcome to send a PR improving the documentation, and perhaps even better explain what the equivalent would be without using `start()`.
