### ISSUE TITLE
File download doesn't work completely!

### ISSUE THREAD

**Issue by mohammad2611373** [LonamiWebs/Telethon#411]
I have tried to download a file of size 8MB, but download_file do it's job only for the first 1MB and doesn't download whole file ! I have also tried using download_media but the result is same. I have printed out offset and limits that is returned back by telegram in bare client : 

result = client(GetFileRequest(
    input_location, offset, part_size
))
hashes = result.cdn_file_hashes
for h in hashes:
      print(h.offset, h.limit)
if isinstance(result, FileCdnRedirect):
      cdn_decrypter, result = \
           CdnDecrypter.prepare_decrypter(
                client, self._get_cdn_client(result), result
           )

Result is as follows : 

0           131072
131072 131072
262144 131072
393216 131072
524288 131072
655360 131072
786432 131072
917504 131072

Although my file is 8MB large it only returns the first 1MB and also limits are not dependent of part_size.

**Comment by mohammad2611373** [comment]
I have also tried client.download_media. Same thing happens.

**Comment by mohammad2611373** [comment]
Even if I use InteractiveTelegramClient I get the same issue and file is not downloaded completely.

**Comment by mohammad2611373** [comment]
Problem is from the library or its from telegram?

**Comment by vivekbestpeers** [comment]
Hi @mohammad2611373  can you help me with receiving messages using telethon

**Comment by Lonami** [comment]
I can download a 9.7MB file without trouble so I'm going to need more information. Can't reproduce.

**Comment by mamdosein97** [comment]
hello. thanks for your amazing library. i use the "download_media" method to download the medias from channels. but for some musics, just its first 1MB will be downloaded. these musics are forwarded from one bot to a channel and won't be downloaded completely. what should i do? please help me. is there another method for downloading musics properly?

**Comment by Lonami** [comment]
Enable DEBUG logging and show me the output.

**Comment by Re3ar** [comment]
Thanks for this great lib.
I have this issue too.
file download is limited to 1MB.
the logging output is as bellow:

ERROR:telethon.telegram_bare_client:Authorization key seems broken and was invalid!
WARNING:telethon.telegram_bare_client:Invoking ['GetCdnFileRequest(file_token=b\'\\xb7\\xec\\x90\\xd8Vzr\\x85>c\\x15\\x0f\\x84\\xba\\xdd\\x00kO:$\\xa8\\xfb\\x10\\x91\\xe5\\xeb\\x1b\\xac\\xb2\\x956f\\xddJ\\x11\\xce\\xb8+\\x1c\\xfa\\x82q\\xef$\\xa2Gh\\xb7\\x8f2\\xa0\\xe4V\\xdd\\xca\\xc5\\xb5\\x05\\xf0Zh\\x88U\\xf5b\\xb9\\xe1)\\x00\\x8f\\x8f q\\xa0J\\xb7\\x96<\\x13\\xb8\\xac\\xec3\\xecg\\xb5 \\x81\\xb0g\\xae\\xc6\\xe6\\xe2\\x16yv\\xfd\\x02\\xa8\\xd5\\x9c\\xcf\\xbe\\xa5Z\\x13\\x91\\x8f\\xc7\\xc0[\\n\\x1e\\x0fx\\xa8\\xa8\\x16t\\xc0\\xeb\\xaeY\\xb8\\x16sPG\\xc3\\x80J\\x15;\\xcd\\x9em\\xfc=c9;ax\\xb5\\xfd\\x02b\\xa3\\x99uZ\\xee\\x0bf\\xa6\\xf2?\\xca\\x93\\xd6\\x90RR\\x9d\\xe7\\xba\\x7f\\t\\x96\\xed?H-\\x1c\\xc1BI\\x02\\xd4q#\\x17q\\xcdG\\xa2Z"!\\xaeD/\\xfa\\xe5\\xa0\\xec\\xda*\\xcbE\\x9d%\\xf2\\x13\\xefKnT\\x11\\xf9\\xc1 Co\\x8b\\x07\\xaf\\x9d\\x9d\\xeay0\\xb1\\xbcL\\x15r\\xe1\\xa0\\xf7\\x19V\\x12\\x80\\x152\\x8d\\xf0\\xe1l\\xd7\\xb1U\\xd0`\\xbfH\\xb55\\x94\\x9b\\x14\\x9b:\\xbd\', offset=0, limit=131072)'] failed 1 times, reconnecting and retrying
OK

**Comment by Lonami** [comment]
@Re3ar see #598.
