### ISSUE TITLE
Download speed 

### ISSUE THREAD

**Issue by khainee** [LonamiWebs/Telethon#4110]
Is anyway to get faster download speed downloading is too slow

**Comment by Lonami** [comment]
Communication with Telegram is encrypted, and doing encryption with Python is slow. As the docs recommend, you can install `cryptg`. The library does not download multiple file parts in parallel because that's more likely to lead to flood errors, but you're free to do so (or find someone who has).

**Comment by khainee** [comment]
> Communication with Telegram is encrypted, and doing encryption with Python is slow. As the docs recommend, you can install `cryptg`. The library does not download multiple file parts in parallel because that's more likely to lead to flood errors, but you're free to do so (or find someone who has).

No change after installing ```cryptg``` i got only 300 to 400 KB/s

**Comment by Lonami** [comment]
You're welcome to benchmark where the bottleneck is, if you still think Telethon is doing something wrong. But I'm fairly confident that's as good as it gets unless parallel download is used.

**Comment by ewwink** [comment]
if you use `download_media` try `download_file` with `part_size_kb=512`, it double the speed.
I got 1600 KBps instead of 700KBps, but still it slower than browser (3000 KBps)

```
msg= await client.get_messages(channel, ids=12345)
document = msg.document
inputLoc = types.InputDocumentFileLocation(
    id=document.id,
    access_hash=document.access_hash,
    file_reference=document.file_reference,
    thumb_size=''
)
await client.download_file(inputLoc, file=msg.file.name, part_size_kb=512, file_size=document.size) # progress_callback=self.progress_callback
```
