### ISSUE TITLE
reactions

### ISSUE THREAD

**Issue by SharkLabDev** [LonamiWebs/Telethon#4112]
```
sent_message = await client.send_message(group_id, message, parse_mode='HTML', link_preview=False)
                await client(SendReactionRequest(
                    peer=group_id,
                    msg_id=sent_message.id,
                    reaction=[types.ReactionEmoji(
                        emoticon='\u1F44D'
                    )]
                ))

```

  File "C:\Users\PC\AppData\Roaming\Python\Python311\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Roaming\Python\Python311\site-packages\telethon\client\users.py", line 83, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.ReactionInvalidError: Invalid reaction provided (only emoji are allowed) (caused by SendReactionRequest)

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

**Comment by SharkLabDev** [comment]
sent_message = await client.send_message(group_id, message, parse_mode='HTML', link_preview=False)
                await client(
                    functions.messages.SendReactionRequest(
                        peer=group_id,
                        msg_id=sent_message.id,
                        big=True,
                        add_to_recent=True,
                        reaction=[types.ReactionEmoji(emoticon='👍')]
                    )
                )
                
                
                it is work)) thanks

**Comment by snowman** [comment]
> ```
>             sent_message = await client.send_message(group_id, message, parse_mode='HTML', link_preview=False)
>             await client(
>                 functions.messages.SendReactionRequest(
>                     peer=group_id,
>                     msg_id=sent_message.id,
>                     big=True,
>                     add_to_recent=True,
>                     reaction=[types.ReactionEmoji(emoticon='👍')]
>                 )
>             )
>             
>             
>             it is work)) thanks
> ```

when access `types.ReactionEmoji`, it shows ```*** AttributeError: module 'telethon.tl.types' has no attribute 'ReactionEmoji'```

**Comment by snowman** [comment]
okay, "👍" works but not "🥱"
