### ISSUE TITLE
receive messages from telegram bot

### ISSUE THREAD

**Issue by MHZarei** [LonamiWebs/Telethon#4115]
​
​I login to telethon as a user, but can't receive any message from a bot with username or new message events. And the list of messages is empty.

I using this code in python:

```python
...
messages = await client.get_messages('mybotid_bot')
...
```

In script, receive messages from other users.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
