### ISSUE TITLE
Can't do enumerate on client.iter_messages()

### ISSUE THREAD

**Issue by dossma** [LonamiWebs/Telethon#4116]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events, sync
from telethon.tl.types import InputMessagesFilterRoundVoice  

async def main():
    async for idx, msg in enumerate(client.iter_messages(entity=channel, limit=limit, filter=InputMessagesFilterRoundVoice, ids=filtered_ids)):
        print(idx, msg)
```

**Traceback**
```
Traceback (most recent call last):
  File "C:\Users\Katzi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3547, in run_code
    last_expr = (await self._async_exec(code_obj, self.user_ns))
  File "<ipython-input-35-3d92f55d5e30>", line 4, in async-def-wrapper
  File "C:\Users\Katzi\Anaconda3\lib\site-packages\telethon\requestiter.py", line 101, in __iter__
    'You must use "async for" if the event loop '
RuntimeError: You must use "async for" if the event loop is running (i.e. you are inside an "async def")
```

In any case the error message is inaccurate yet I do not know if this is not working on purpose. With enumerate, I want to have the index of each messsage.

**Comment by Lonami** [comment]
`enumerate` does not work with asynchronous iterators (which `iter_messages` returns). You will need to use an async-alternative to that method or just count manually:

```python
idx = 0
async for msg in ...:
    ...
    idx += 1
```
