### ISSUE TITLE
Unable to get complete participant list: get_participants

### ISSUE THREAD

**Issue by mondyfy** [LonamiWebs/Telethon#4117]
**Checklist**

* [ x] The error is in the library's code, and not in my own.
* [x ] I have searched for this issue before posting it and there isn't a duplicate.
* [ x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that is not working as expected**
```python
        target_group=self.groups[int(g_index)]

        print('Fetching Members...')
        all_participants = []

        all_participants = self.client.get_participants(target_group, aggressive=True)
```

get_participants is only giving a few participants but not the complete group participants. It was working fine a few weeks back but not working as of now. Am I missing anything here?

**Comment by Lonami** [comment]
If you haven't updated Telethon, and you haven't changed your code, then the most likely thing is the Telegram server itself has changed.

Telegram doesn't really want you to fetch all members. Telethon is not going to implement hacky workarounds - spammers could abuse those and they tend to break.

So I'll be closing this, as there's nothing to fix from Telethon side. (Also, `aggressive` has been long deprecated.)
