### ISSUE TITLE
Infinity connection

### ISSUE THREAD

**Issue by reigeneric** [LonamiWebs/Telethon#4119]
Making an attempt to connect it just takes for a long time without any errors. How to detect invalid sessions like this one?

**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import asyncio

from telethon import TelegramClient
from telethon.sessions import StringSession


async def main():
    string_session = '1ApWapzMBuyt9YGjv8dqA1M36XPLPZtLpHZHPbo7jd91qav7ZUe0pU0eF5F-BszNLJeMOycn57lKFFyjGe9_KBgDytZ_szwdEOtzED5We-DCTwG2r4XMjc0xSX9dStFBVkr9Xu5XD5W0mPi9JnebyJx8ClCoGbzBaua4xeifwdO2YgXM_F7DeUMLbyUgexI8l4UxHU0K-p1VW5NC2OP02S3WL3DMkqYVkeqR6fYnPFJ83vazN726hXphpVU5jF9IctFfLcfTD_L-q1WolD5HWC9oKJoZfSQ4xUwCDn6Fi4rii2mfAh3Qk1yAqCGs235odXgCSFGqr587atU00PwLvD0MMLM1lqfA='

    client = TelegramClient(
        session=StringSession(string_session),
        api_id=...,
        api_hash=...,
    )

    await client.connect()

    me = await client.get_me()

    print(me)


if __name__ == '__main__':
    asyncio.run(main())

...

```

**Traceback**
```
No errors
```

**Comment by Lonami** [comment]
You will need to provide some logs (probably at `DEBUG` level at least) for me to tell what's going on or where it gets stuck. As it stands, there's not much I can do about this.

**Comment by NotStatilko** [comment]
You're using `API_ID` and `API_HASH` of official Telegram app. This is prohibited. Probably the infinite connection is because of this. Don't continue or this may result in **account block**. It seems that there is nothing to fix.

I hope you disconnected your StringSession, though :)

**Comment by reigeneric** [comment]
> You will need to provide some logs (probably at `DEBUG` level at least) for me to tell what's going on or where it gets stuck. As it stands, there's not much I can do about this.

```
DEBUG:asyncio:Using selector: KqueueSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51:443/TcpFull complete!
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7239664963344727288 to InvokeWithLayerRequest (102f72dd0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 76 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
```

**Comment by reigeneric** [comment]
> You will need to provide some logs (probably at `DEBUG` level at least) for me to tell what's going on or where it gets stuck. As it stands, there's not much I can do about this.

I provided code above. You can try it by yourself to figure out what's wrong

**Comment by Lonami** [comment]
I tried the code. I get a log similar to yours. It does get stuck.

I've added some additional logging calls and the library is correctly sending the data over the network.

It is Telegram the one who is not responding.

I suspect the session is broken.

I'm not sure if it would make sense to add a timeout. You can also do that yourself with `asyncio.wait_for` if you suspect `client.connect` may be getting stuck. This is even suggested in the documentation for the `TelegramBaseClient.timeout` constructor parameter. So I will be closing the issue.

Please don't post `api_id` and `api_hash` values. They're supposed to remain secret (I don't care if they're available publicly - they should not be).

**Comment by staseek** [comment]
I have this problem too. Did you find solution? Or something helpful with it?
This code 
`await client.connect()`

stuck with this log
`DEBUG:telethon.network.mtprotosender:Receiving items from the network...`

and nothing happened for 5 minutes. Tried with different accounts and from different addresses (I thought about "shadow" ban from telegram servers)

**Comment by aminsalami** [comment]
> I have this problem too. Did you find solution? Or something helpful with it? This code `await client.connect()`
> 
> stuck with this log `DEBUG:telethon.network.mtprotosender:Receiving items from the network...`
> 
> and nothing happened for 5 minutes. Tried with different accounts and from different addresses (I thought about "shadow" ban from telegram servers)

Same issue. It get stuck at `DEBUG:telethon.network.mtprotosender:Receiving items from the network...`

The only solution I found was to remove the session and login again!

**Comment by voronoff2803** [comment]
same issue
