### ISSUE TITLE
Method descriptions on tl.telethon.dev

### ISSUE THREAD

**Issue by tm-a-t** [LonamiWebs/Telethon#4122]
### Describe your suggested feature

Some common-used methods are briefly described on https://core.telegram.org/methods. Can those descriptions be copied to tl.telethon.dev? 

With descriptions, it would be more convenient to search for methods in tl.telethon.dev without referring to the official documentation.  Thank you.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by tm-a-t** [comment]
Oops, I missed that those are the same descriptions as from https://core.telegram.org/schema. So there are not only methods.

I suggest to extract descriptions from the subpages somehow.

**Comment by Lonami** [comment]
I don't have plans to do this any time soon in the near future. If you'd like to work on it let me know and then I will keep the issue open with you assigned. Though note that the code generation code is a big mess so it might not be straightforward to add.

If it's done, I would also like some sort of disclaimer explaining that the documentation is taken from their site.

I'm also not sure if there's some kind of JSON file now with the descriptions, but it might be better than scraping.
