### ISSUE TITLE
Problem with 'limit' in contacts.SearchRequest

### ISSUE THREAD

**Issue by navepno** [LonamiWebs/Telethon#4126]
### Code that causes the issue

``` python
from telethon import TelegramClient, functions
from telethon.sessions import StringSession

client = TelegramClient(StringSession(token), api_id, api_hash)


async def main():
    await client.connect()
    search = 'london'
    result = await client(functions.contacts.SearchRequest(
        q=search,
        limit=7, # here is this problem
    ))
    return result

with client:
    result = client.loop.run_until_complete(main())
    print(len(result.chats))
```

### Expected behavior

I was trying to write a code that will search for chats in telegram with my keywords and noticed that limit parameter doesn't work. No matter what number I enter, I will always get 9-10 chats (if this keyword is popular)

Maybe I'm doing something wrong, maybe not, but I'm asking for help 

### Actual behavior

For example, this is result of my example above
```python
❯ python search_issue.py
9
```

### Telethon version

 1.28.5

### Python version

3.10

### Operating system (including distribution name and version)

macOS 13.3.1

### Checklist

- [x] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
