### ISSUE TITLE
ImportContactsRequest got an unexpected argument <replace>

### ISSUE THREAD

**Issue by Tacenda25** [LonamiWebs/Telethon#413]
Several months ago i wrote a script which added numbers in contacts,

Unfortunately i didn't remember a telethon version which use,
`def telegram_contacts(user_numbers):`
    `    l = []`
    `for num in user_numbers:`
        `contact = InputPhoneContact(123456789, num, '', '')`
        `l.append(contact)`
    `req_contact = client.invoke(ImportContactsRequest(l, replace=True))`
    `# req_contact = client.invoke(ImportContactsRequest(l))`

all worked with `replace=True`, but now i got an error
![2017-11-07_14-10-18](https://user-images.githubusercontent.com/12529036/32493448-8d4c87c6-c3c6-11e7-8922-16dd538171d1.png)

**Comment by Lonami** [comment]
Well how about you read the documentation? Of course types in the API change.
