### ISSUE TITLE
ImportChatInviteRequest - Not functioning

### ISSUE THREAD

**Issue by yarinas5** [LonamiWebs/Telethon#4131]
### Code that causes the issue

from telethon.tl.functions.messages import ImportChatInviteRequest

#Adding sessions to Channels by id
updates = await client(ImportChatInviteRequest('+Vtq5M9RoZuI0MzI0)'))   ### Tried Without plus too

this is the channel i tried to join the seesions to ,PRivate channel, invite link which doesnt need confirmation https://t.me/+Vtq5M9RoZuI0MzI0

### Expected behavior

I have a loop of connection to sessions.
each one loggin in a way of Client (api id, api hash......)
login is succeful
Now I have tried that each session will join a specific Invite link of a private channel,

updates = await client(ImportChatInviteRequest('+Vtq5M9RoZuI0MzI0)'))   ### Tried Without plus too
 this line written after each connection completed, but has the problem of ImportChatInviteRequest  isnt defined as async
 
 In adddion to the several tries, I did also tried  client(JoinChannelRequest(+Vtq5M9RoZuI0MzI0)) but us it needs username it doesnt work anyways

### Actual behavior

Describe the bug
telethon.tl.functions.messages
ImportChatInviteRequest

When writing:
await client(ImportChatInviteRequest('group'))

an error which says : "await" allowed only within async function
which probably means ImportChatInviteRequest isnt async function, fix pls or tell me what to do and ill fix.

Screenshots:

![צילום מסך 2023-06-10 124518](https://github.com/LonamiWebs/Telethon/assets/23079835/e9bc8e87-09b8-4166-85e2-e4ffff785555)

### Telethon version

1.28.5

### Python version

3.10.11

### Operating system (including distribution name and version)

Windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This is not a bug in Telethon. As Python indicates you can only `await` things inside of `async def`.

Assuming the request is sent a response is received, note that you are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
