### ISSUE TITLE
Getting an Invalid Peer Error

### ISSUE THREAD

**Issue by justin-jalandoni** [LonamiWebs/Telethon#4136]
### Code that causes the issue

```python

async with TelegramClient("me", api_id, api_hash) as client:
    for groupName in groups:
        try:
            # entity = await client.get_entity(groupName)
            print(f"\n{datetime.now()}: Sending message to {groupName}")
            # await client.send_message(groupName, message, file=imagePath)
            await client.send_message(groupName, message)
        except Exception as e:
            print(f"\n{datetime.now()}: Error {e}")

```

### Expected behavior

It's supposed to send a message

### Actual behavior

Instead I get the InvalidPeerError

![image](https://github.com/LonamiWebs/Telethon/assets/16448415/9c9001c5-b45f-44e1-8c79-dbc057e27e71)

### Telethon version

1.28.5

### Python version

3.5

### Operating system (including distribution name and version)

Windows 11

### Other details

I would like to know the cause. There seems to be no documentation

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
The code you posted does not show what `message` is. I am assuming that is the issue. It is unlikely that this is a problem in Telethon, but rather something with a particular group.
