### ISSUE TITLE
Search for multiple keywords with search request

### ISSUE THREAD

**Issue by CaledoniaProject** [LonamiWebs/Telethon#4138]
### Describe your suggested feature

The API here supports only one keyword https://tl.telethon.dev/methods/contacts/search.html
Does the API support multiple keywords?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Telethon can't change the behaviour, or add features to, the API Telegram offers. So, no.
