### ISSUE TITLE
Know if a message is a Original message or if a Fowarder Message

### ISSUE THREAD

**Issue by PCDControl** [LonamiWebs/Telethon#4139]
Hi, there is a method to know if a message is an original message or a fowarder message? 
Example:  There is a Group discussion, inside this group there is a original message and a fowarder message of a same client.
If i hear with python telethon  `newMessage = event.message.message
    await client_TG.forward_messages(entity='me', messages=event.message)`

there is a method to know if the new message is an original or a fowarder?
Thank's

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
