### ISSUE TITLE
Is there any way to connect to MTProto test servers for dev. stage??

### ISSUE THREAD

**Issue by sabloger** [LonamiWebs/Telethon#414]

**Comment by Lonami** [comment]
[Yeah](https://github.com/LonamiWebs/Telethon/blob/a6c898f8d12bf60f1298784981060f238b5e0178/telethon_tests/crypto_test.py).

**Comment by Lonami** [comment]
[It's in the wiki, too](https://github.com/LonamiWebs/Telethon/wiki/Test-Servers). Which I assume you didn't bother looking did you?

**Comment by sabloger** [comment]
Thanks, I didn't find that.
