### ISSUE TITLE
Reply to comments below the post

### ISSUE THREAD

**Issue by alexkorolex** [LonamiWebs/Telethon#4140]
### Describe your suggested feature

Good afternoon I encountered such a problem that the send_message method has the ability to write a comment under the post in the telegram channel. But, unfortunately, it is not possible to leave a response to other comments under the same post, although both message_id and post_id are available. Most often, an error occurs that administrator rights are required, although they are not needed for this action. Please help me with this issue!

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
`send_message` already has a `comment_to` which should be enough.

**Comment by alexkorolex** [comment]
> `send_message` already has a `comment_to` which should be enough.

This method is used in the following code

```
async def change_files():
    client = work_with_boys()
    await client.change_data_bot(bot=bot)

async def reply_to_comment(channel_link, post_id, comment_id, text):
    chat = await client.get_entity(channel_link)
    post = await client.get_messages(chat, id=post_id)
    comment = await client.get_messages(chat, id=comment_id)
    await client.send_message(chat, text, comment_to=comment)

with client:
    client.loop.run_until_complete(reply_to_comment("t.me/na moskve reke", 2445, 6462, text="🥰"))
```
    
   And the following error occurs: `Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by SendMessageRequest)`
    
 However, it is not necessary to have admin rights to leave comments and respond to them

**Comment by Lonami** [comment]
I'm not that familiar with comments. If you believe the library is doing something wrong, you're welcome to use raw API. If you can get it to work, a PR would be appreciated.  You can also enable debug mode in some official clients to know what happens behind the scenes, although I don't remember the details on how to do so.

My gut feeling is that the comment is in a different channel and some parameters are wrong.
