### ISSUE TITLE
utils.markdown.parse can't properly parse MessageEntityPre

### ISSUE THREAD

**Issue by merura** [LonamiWebs/Telethon#4143]
### Code that causes the issue

```python
from telethon import utils

MARKDOWN_TEXT = """
``python
print("I love telethon!")
``
"""

if __name__ == "__main__":
    text, entities = utils.markdown.parse(MARKDOWN_TEXT)
    print("Text", text, "Entities", *entities, sep="\n")
```

* Add addition ` to the code. I removed it, as it breaks preview in github

### Expected behavior

It should print something like:
```
Text
print("I love telethon!")
Entities
MessageEntityPre(offset=0, length=26, language='python')
```

### Actual behavior

It prints:
```
Text
python
print("I love telethon!")
Entities
MessageEntityPre(offset=0, length=32, language='')
```

### Telethon version

1.28.5

### Python version

3.10.11

### Operating system (including distribution name and version)

NixOS 23.05

### Other details

It is [documented feature](https://core.telegram.org/api/entities#allowed-entities) in telegram, so I think current implementation of pre is wrong.
I tried to fix the current behavior, but apparently it requires significantly changing the processing and adding a separate if for pre

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Parsing is done client-side. Current Telethon's markdown is not really the markdown we're used to (GFM). Instead, it follows tdesktop more closely (at least it did at some point). Changing this would be a breaking change.

You can set the `client.parse_mode` to custom functions, which you could implement with the help of an actual package implementing proper markdown support. My recommendation is to use HTML for anything but the most trivial of formattings though.

There's still plans in the horizon to switch to commonmark in v2. Some day.
