### ISSUE TITLE
In Sign In method -No documentation regarding how to obfuscate the code telegram sent

### ISSUE THREAD

**Issue by Muditjain13** [LonamiWebs/Telethon#4144]
### Description

In Sign In method -No documentation regarding how to obfuscate the code telegram sent.Telegram code immediately expires

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Such obfuscation is most useful for illegitimate use of the API, and therefore, the library will not make an attempt to document such a thing, as it would make it easier for bad actors to take advantage of it.
