### ISSUE TITLE
InviteToChannelRequest not adding users and causing phone number ban

### ISSUE THREAD

**Issue by bengabp** [LonamiWebs/Telethon#4145]
### Code that causes the issue

```python

def add_members_to_group(self, members: List[InputUser]):
  print(f"Adding {len(members)} to group ...")
  entity = self.clients[0].get_entity(self.add_to_group_id) # I have a list of clients just for adding more members before wait time
  channel = InputChannel(entity.id, entity.access_hash) # Get channel as InputChannel
  
  for input_user in members:
    print(f"Sending request for {len(members)} members")
    add_request = InviteToChanneRequest(channel, [input_user])
    try:
      self.clients[0](add_request)
    except UserPrivacyRestrictedError:
      pass
    print("Success !")
```

### Expected behavior

When i run this method passing in the correct arguments, it runs fine but when i check the group, the members added do not appear in the group. Also if i run the code one more time or 2 more times, telegram bans the phone number. Also the clients are admins of the add_to group and have the right permission to add members, Its also a test group which means i just created the group and I am running the code after some minutes ( would this cause any issues) ?. Let me know if this is a bug in the telethon library or what solution i can take and why is telegram banning my numbers. Note that this also occurs when i test using a test channel which i own 

### Actual behavior

It should add the users to the group

### Telethon version

latest

### Python version

3.9

### Operating system (including distribution name and version)

Ubuntu 22.04

### Checklist

- [ ] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

**Comment by bengabp** [comment]
@Lonami Please what do you mean by using raw API ?
