### ISSUE TITLE
Don't see the argument "phone" in "client.start(phone)" if inside "async with TelegramClient(phone, api_id, api_hash) as client:"

### ISSUE THREAD

**Issue by LL1yt** [LonamiWebs/Telethon#4146]
### Code that causes the issue

async with TelegramClient(phone, api_id, api_hash) as client:
        
        await client.start(phone)

### Expected behavior

Will send the code to the phone number provided 

### Actual behavior

Asks for a phone number

### Telethon version

1.28.5

### Python version

3.9

### Operating system (including distribution name and version)

macOS 13.4

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
`with` already calls `start` inside. You should `async with TelegramClient(...).start(...) as ...` instead.

**Comment by LL1yt** [comment]
Right, thank you very much. It wasn't that simple: You've dealt with it in the past. I'll leave a link, maybe it helps anyone. https://github.com/LonamiWebs/Telethon/issues/1127#issuecomment-475195663 (Another working solution: add `await` to the line `async with await TelegramClient('anon', api_id, api_hash).start(phone) as client:`)
