### ISSUE TITLE
How to kick and ban a user from a channel?

### ISSUE THREAD

**Issue by dsldsl** [LonamiWebs/Telethon#415]
I can't find a command in the `invoke` library for deleting a user from a room.  I have found this:

```client.invoke(EditBannedRequest(scratch_entity, client.get_input_entity(cc), ChannelBannedRights(datetime.datetime(2010, 12, 25))))```

However that seems to be only able to remove specific rights, not actually ban a user from joining a channel. 

Is this doable currently?

BTW - THNAK YOU for this AWESOME tool!

**Comment by Lonami** [comment]
By the way, using `invoke` is kind of old. You xan just do `client(SomeRequest(...))`

**Comment by alihesari** [comment]
@Lonami How can I import SomeRequest into my code? I'm using ```from telethon.tl.functions.channels import SomeRequest``` but it doesn't work.
