### ISSUE TITLE
Auto Ban when using

### ISSUE THREAD

**Issue by twan-hub** [LonamiWebs/Telethon#4150]
### Code that causes the issue

When I signed up for api credential I was automatically banned. My personal and test accounts. 

For context I am making a channel cloner 

### Expected behavior

Go to my.telegram.org

sign up for api and get credentials 

Forward content from source channel to backup or source channel.

### Actual behavior

Go to my.telegram.org

sign up for api and get credentials 

ban after forwarding a message 

### Telethon version

Current

### Python version

Current

### Operating system (including distribution name and version)

Windows 11

### Other details

No help from telegram support 

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by ShayneBermejo** [comment]
Can you provide the code? I doubt it's the error in the library's code. Perhaps Telegram thinks you are spamming.

**Comment by twan-hub** [comment]
Is telethon connected to telegram directly? I’m sure it the anti spammer too, but I want to make them aware and get my accounts back

**Comment by Lonami** [comment]
See discussion in #824 and linked issues.

**Comment by EvgenKasta** [comment]
Hey, everybody. Let's try to solve this problem together. Previous commenter, stop confusing and transferring to other threads where there are no constructive solutions!

**Comment by jacobsnum** [comment]
> Hey, everybody. Let's try to solve this problem together. Previous commenter, stop confusing and transferring to other threads where there are no constructive solutions!

Hello, did you found decision?

**Comment by EvgenKasta** [comment]
Привет. Да, я нашел решение.

Co-founder
*"FeelQueen - онлайн Beauty сервис"**https://feelqueen.by/*
<https://feelqueen.by/>
Кастогрыз Евгений Николаевич
*+375 29 127 54 22* (viber, telegram, WhatsApp)
instagram https://www.instagram.com/evgenkasta/



Пт, 15 марта 2024 г. в 18:58, jacobsnum ***@***.***>:
