### ISSUE TITLE
download_media in memory as a list for albums

### ISSUE THREAD

**Issue by FindMyBug** [LonamiWebs/Telethon#4151]
### Describe your suggested feature

When using download_media for albums with bytes parameters the method seems to return only the last media object. Instead, we can return a list that contains all downloaded byte-like media objects so that the entire album is available from memory. 

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Albums are separate messages so you need to download each of them.
