### ISSUE TITLE
Error : Got difference for channel 1257723241 updates

### ISSUE THREAD

**Issue by msadeqian** [LonamiWebs/Telethon#4155]
### Code that causes the issue

# pylint: disable=missing-function-docstring
import configparser
import os.path
import os
import sys
from getpass import getpass
from telethon import events
from telethon import TelegramClient
from telethon.errors import SessionPasswordNeededError, FloodWaitError
import Configuration
from messages import MessageService
from SignalActions import SignalGroup
from DBContext.Database import session
from DBContext import Models
from sqlalchemy import select, delete
import asyncio

logger = Configuration.ConfigureLogger()
config = Configuration.getappconfig()
path = Configuration.getconfigpath()

api_id = int(config["Telegram"]["api_id"])
api_hash = str(config["Telegram"]["api_hash"])
phone = config["Telegram"]["phone"]
username = config["Telegram"]["username"]
sourcechannelid = int(config["Telegram"]["sourcechannelid"])
targetchannelid = int(config["Telegram"]["targetchannelid"])

telegramsessionfile = f"{path}current-session"
client = TelegramClient(telegramsessionfile, api_id, api_hash)
message_service = MessageService(client)

async def connect():
    print("Connecting...")
    await client.connect()

    print(await client.is_user_authorized())
    if not await client.is_user_authorized():
        try:
            await client.send_code_request(phone)
            logger.info("Sending a code...")
            await client.sign_in(phone, code=input("Enter code: "))
            logger.info("Successfully!")
        except FloodWaitError as FloodError:
            logger.info("Flood wait: {}.".format(FloodError))
            sys.exit()
        except SessionPasswordNeededError:
            await client.sign_in(password=getpass("Enter password: "))
            logger.info("Successfully!")

async def get_messages(source_channel_id, limit=20):
    items = list(
        reversed(
            [m async for m in client.iter_messages(source_channel_id, limit=limit)]
        )
    )
    for m in items:
        msg = {
            "id": m.id,
            "isreply": m.is_reply,
            "replyid": m.reply_to_msg_id,
            "chat_id": m.chat_id,
            "message": m.message
        }
        logger.info(msg)
        await message_service.new_message(m)

@client.on(events.NewMessage())
async def handler(event):
    await message_service.new_message(event.message)

if not os.path.isfile(telegramsessionfile):
    loop = asyncio.get_event_loop()
    loop.run_until_complete(connect())

client.start()
logger.info("running waiting for New Message")

client.run_until_disconnected()

logger.info("disconnected from Telegram Server")

### Expected behavior

I have write a simple program to get update from telegram channel and process ... 
this app work good until 10 day ago ,

### Actual behavior

 I get this error randomly and all process will be stop , after restart app it work for random time and face same error 
 Error : Got difference for channel 1257723241 updates
  I use telethon 1.28.5 and python 3.11.3 on ubuntu

### Telethon version

1.28.5

### Python version

3.11.3

### Operating system (including distribution name and version)

ubuntu 20.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
The log message you mention is not an error. The library is working as expected: if there are no updates in a while or a gap is detected, it will try fetching them.

This issue is not actionable in its current form so I will close it.
