### ISSUE TITLE
Don't get auth code in telegram 

### ISSUE THREAD

**Issue by JackCat1** [LonamiWebs/Telethon#4156]
### Code that causes the issue

tg_ses = TELETHON_DATA_FIELD + str(self.instance.pk)
client = TelegramClient(tg_ses, TELEGRAM_API_ID, TELEGRAM_API_HASH) 
await client.connect()

if await client.is_user_authorized():
     await client.disconnect()            
     return {'status':'is_auth'}
phone_hash = ''
try:
   send_phone = await client.send_code_request(phone)
            
    if send_phone.phone_code_hash:
        phone_hash = send_phone.phone_code_hash                
except errors.RPCError as e:             
     return {'status':'error', 'msg':e.message}
except Exception as e:                    
      return {'status':'error', 'msg':'Авторизация не возможна'} 
await client.disconnect()           
return {'status':'OK', 'phone_code_hash':phone_hash}

### Expected behavior

I'd like auth in TG. I do client.send_code_request(phone) and get auth code

### Actual behavior

I'd like auth in TG. I do client.send_code_request(phone) and get "phone_code_hash" But code in telegram doesn't come. It happens sometimes. Especially, I often get this behavior in the evening. Has anyone experienced this?

### Telethon version

1.24.0

### Python version

3.9.16

### Operating system (including distribution name and version)

Ubuntu 18.04.6 LTS

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This behaviour likely happens from Telegram's side, and not Telethon, and therefore, there's probably nothing to fix in the library itself.

**Comment by JackCat1** [comment]
Do you know why this happens? Have you encountered this behavior before?

**Comment by Lonami** [comment]
#3835 is currently pinned and this is a duplicate of it.
