### ISSUE TITLE
get group and channel info 

### ISSUE THREAD

**Issue by amin1994** [LonamiWebs/Telethon#416]
Hello I want to get group and channel info by telethon functions and apis how can I get ?thanks

**Comment by Lonami** [comment]
You haven't tried anything.

**Comment by amin1994** [comment]
yes I have tried 
updates = client(CheckChatInviteRequest('A7SgeDuzptdo9zhyJV7MVA'))
print(updates)
but it shows me :

**Comment by Lonami** [comment]
You want the `FullChannel`. Have you even bothered looking?

**Comment by amin1994** [comment]
no, as you know telegram has info for every group or channel  like title as you see above I'm looking for info not chats or messages in groups or channels? thank you

**Comment by Lonami** [comment]
> ChatInviteAlready: {chat: {banned_rights: None, title: "Big Data", […]

I don't know about you, but I see a `title` there. Also upgrade, because that `__str__` is old.

**Comment by dmitrdv** [comment]
try this:

`
import telethon
from telethon.tl.functions.channels import GetFullChannelRequest

api_id = 49631
api_hash = 'some_hash'

telegram = telethon.TelegramClient('sessions', api_id, api_hash)
channel = telegram.get_entity('@russica2')
details = telegram.invoke(GetFullChannelRequest(channel))
`
