### ISSUE TITLE
Problem with supports_streaming

### ISSUE THREAD

**Issue by serverworm** [LonamiWebs/Telethon#4162]
### Code that causes the issue

await client.send_file(id_chanel, file=f, caption='some kind of description', attributes=(DocumentAttributeVideo(183, 1280, 720),), supports_streaming=True, part_size_kb=1024)

### Expected behavior

I expect that my video will be uploaded to the channel and when you want to watch it, you don't have to wait for the file to download completely

### Actual behavior

Unfortunately, the video cannot be watched without a full download of the file to the device
![image](https://github.com/LonamiWebs/Telethon/assets/81970442/c992becd-51bd-477d-9d6c-7e7d123459a9)

### Telethon version

1.29.2

### Python version

3.11

### Operating system (including distribution name and version)

Windows 10

### Other details

I download .mp4 videos and don't get any errors. How can this be fixed? I will be very grateful to you!

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by randomuser9912** [comment]
I have the same issue😢

**Comment by Lonami** [comment]
The video must have a specific format and encoding for Telegram to allow streaming. I do not remember the specifics. But you should be able to upload such video from an official Telegram client, to then find out what is needed in the message or uploaded media.
