### ISSUE TITLE
Angola lockout after enabling account with "updatesToLong" error

### ISSUE THREAD

**Issue by IlyaZaigralov** [LonamiWebs/Telethon#4164]
### Code that causes the issue

Просто подключение 

### Expected behavior

I used to run indonesia and it worked fine. When I tried to launch Angola - bans started after connecting to the account.

I have Telegram Expert software that I use and everything works fine, maybe it's the queries?

https://core.telegram.org/api/updates

### Actual behavior

Hi everyone, has anyone worked with telethon or other telegram libraries?

After joining an account an error "UpdatesToLong" occurs and the account is banned

Telegram say:
updatesTooLong

Too many updates, it is necessary to execute updates.getDifference.

Help please understand) maybe someone has faced this situation, account Angola country

### Telethon version

1

### Python version

3

### Operating system (including distribution name and version)

11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This bug report is not actionable as it is. See #824 for more details regarding bans.
