### ISSUE TITLE
Request SendMessageRequest had missing message mapping Updates

### ISSUE THREAD

**Issue by plutonium777** [LonamiWebs/Telethon#4167]
### Code that causes the issue

```python
await tgc.send_message(entity=event.message.peer_id,
                                     message=text,
                                     comment_to=event.message,
                                     schedule=0, parse_mode='md', link_preview=False)
```

### Expected behavior

Send message to my channel comments at newMessage event to be first one commenting it

### Actual behavior

Message isn't sent, following log printed ```Request SendMessageRequest(peer=InputPeerChannel(channel_id=1495342029, access_hash=-311934215877242870), message='////', no_webpage=True, silent=None, background=None, clear_draft=False, noforwards=None, update_stickersets_order=None, reply_to=InputReplyToMessage(reply_to_msg_id=713, top_msg_id=None), random_id=-3165220698344483296, reply_markup=None, entities=[], schedule_date=datetime.timedelta(0), send_as=None) had missing message mapping Updates(updates=[UpdateReadChannelInbox(channel_id=1495342029, max_id=714, still_unread_count=0, pts=1126, folder_id=1), UpdateNewChannelMessage(message=MessageEmpty(id=714, peer_id=PeerChannel(channel_id=1495342029)), pts=1127, pts_count=0)], users=[], chats=[Channel(id=1495342029, title='Channel Chat', photo=ChatPhotoEmpty(), date=datetime.datetime(2023, 7, 21, 16, 47, 22, tzinfo=datetime.timezone.utc), creator=False, left=False, broadcast=False, verified=False, megagroup=True, restricted=False, signatures=False, min=False, scam=False, has_link=True, has_geo=False, slowmode_enabled=False, call_active=False, call_not_empty=False, fake=False, gigagroup=False, noforwards=False, join_to_send=True, join_request=False, forum=False, access_hash=-311934215877242870, username=None, restriction_reason=[], admin_rights=None, banned_rights=None, default_banned_rights=ChatBannedRights(until_date=datetime.datetime(2038, 1, 19, 3, 14, 7, tzinfo=datetime.timezone.utc), view_messages=False, send_messages=False, send_media=False, send_stickers=False, send_gifs=False, send_games=False, send_inline=False, embed_links=False, send_polls=False, change_info=True, invite_users=True, pin_messages=True, manage_topics=False, send_photos=False, send_videos=False, send_roundvideos=False, send_audios=False, send_voices=False, send_docs=False, send_plain=False), participants_count=None, usernames=[])], date=datetime.datetime(2023, 8, 5, 23, 54, 29, tzinfo=datetime.timezone.utc), seq=0)```

### Traceback

no traceback as it's just log

### Telethon version

1.29.2

### Python version

3.11.4

### Operating system (including distribution name and version)

Windows 11

### Other details

Thought it is spam bot limitations, but I can send message to this chat from same account using my phone 

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Was the chat or message somehow deleted at the same time the message was sent? Telegram returning `MessageEmpty` from `sendMessage` is impressive, and not in a good way.

**Comment by plutonium777** [comment]
Thank you for answer, I'm shocked as well :D My program doesn't delete messages. No bots that can delete this message in chat as well as it's my test channel and linked chat. So it wasn't.

**Comment by Lonami** [comment]
You can try manually invoking the `client(SendMessage(...))`. There's a small chance `client.send_message` messes up somewhere, so if you get it to work, then we could compare, see the difference and fix it (but again it's unlikely there's a problem there).

With the error you posted, it means the library did send the request. But if you see nothing happen in Telegram, either a parameter was wrong or the servee messed up (and I believe that's the case, so there'd be nothing for Telethon to "fix").

**Comment by plutonium777** [comment]
Hi, @Lonami . After a long time research figured out where is the problem exactly. The problem is specifically in the link in the bio.   After I removed it, account can send comments to my channel without any problems. I have information that this link was banned by telegram algorithm, because when I created a new one my script works fine with link in bio. I can give that link to you so you can check what's wrong as the problem still at telethon side (I think), because I can write comments from official apps. In any case, thanks in advance!

**Comment by plutonium777** [comment]
Changing send_message to SendMessageRequest did not help.

**Comment by Lonami** [comment]
> Changing send_message to SendMessageRequest did not help.

Please post the code you used for this, and the response from the call or error.

**Comment by plutonium777** [comment]
Here is that small piece of code
```
res = await tgc(GetDiscussionMessageRequest(event.message.peer_id, get_message_id(event.message)))
await tgc(SendMessageRequest(peer=res.chats[0],
                   message=self.text,
                   reply_to=types.InputReplyToMessage(
                       reply_to_msg_id=res.messages[0].id,
                       top_msg_id=res.messages[0].id
)))
```
SendMessageRequest returns a new message but with text = None

**Comment by Lonami** [comment]
I need to see the returned `Updates`. You can censor away data you want to hide, but I'd like to see the structure:

```python
updates = await tgc(SendMessageRequest(...))
print(updates.stringify())
```

**Comment by plutonium777** [comment]
Here it is:

<details>

```
Updates(
	updates=[
		UpdateReadChannelInbox(
			channel_id=1898190608,
			max_id=880,
			still_unread_count=0,
			pts=1934,
			folder_id=None
		),
		UpdateNewChannelMessage(
			message=MessageEmpty(
				id=880,
				peer_id=PeerChannel(
					channel_id=1898190608
				)
			),
			pts=1935,
			pts_count=0
		),
	],
	users=[
	],
	chats=[
		Channel(
			id=1898190608,
			title=-,
			photo=ChatPhotoEmpty(
			),
			date=datetime.datetime(2023, 7, 9, 14, 0, 22, tzinfo=datetime.timezone.utc),
			creator=False,
			left=True,
			broadcast=False,
			verified=False,
			megagroup=True,
			restricted=False,
			signatures=False,
			min=False,
			scam=False,
			has_link=True,
			has_geo=False,
			slowmode_enabled=False,
			call_active=False,
			call_not_empty=False,
			fake=False,
			gigagroup=False,
			noforwards=False,
			join_to_send=False,
			join_request=False,
			forum=False,
			access_hash=-8280747966187315986,
			username=None,
			restriction_reason=[
			],
			admin_rights=None,
			banned_rights=None,
			default_banned_rights=ChatBannedRights(
				until_date=datetime.datetime(2038, 1, 19, 3, 14, 7, tzinfo=datetime.timezone.utc),
				view_messages=False,
				send_messages=False,
				send_media=False,
				send_stickers=False,
				send_gifs=False,
				send_games=False,
				send_inline=False,
				embed_links=False,
				send_polls=False,
				change_info=True,
				invite_users=True,
				pin_messages=True,
				manage_topics=False,
				send_photos=False,
				send_videos=False,
				send_roundvideos=False,
				send_audios=False,
				send_voices=False,
				send_docs=False,
				send_plain=False
			),
			participants_count=None,
			usernames=[
			]
		),
	],
	date=datetime.datetime(2023, 9, 2, 19, 48, 44, tzinfo=datetime.timezone.utc),
	seq=0
)
```

</details>

**Comment by plutonium777** [comment]
By the way without banned link in bio I do have such output:

<details>

```
Updates(
	updates=[
		UpdateMessageID(
			id=882,
			random_id=6573753954819314332
		),
		UpdateReadChannelInbox(
			channel_id=1898190608,
			max_id=882,
			still_unread_count=0,
			pts=1938,
			folder_id=None
		),
		UpdateNewChannelMessage(
			message=Message(
				id=882,
				peer_id=PeerChannel(
					channel_id=1898190608
				),
				date=datetime.datetime(2023, 9, 2, 19, 50, 51, tzinfo=datetime.timezone.utc),
				message='text',
				out=True,
				mentioned=False,
				media_unread=False,
				silent=False,
				post=False,
				from_scheduled=False,
				legacy=False,
				edit_hide=False,
				pinned=False,
				noforwards=False,
				from_id=PeerUser(
					user_id=854523506
				),
				fwd_from=None,
				via_bot_id=None,
				reply_to=MessageReplyHeader(
					reply_to_msg_id=881,
					reply_to_scheduled=False,
					forum_topic=False,
					reply_to_peer_id=None,
					reply_to_top_id=None
				),
				media=None,
				reply_markup=None,
				entities=[
				],
				views=None,
				forwards=None,
				replies=None,
				edit_date=None,
				post_author=None,
				grouped_id=None,
				reactions=None,
				restriction_reason=[
				],
				ttl_period=None
			),
			pts=1938,
			pts_count=1
		),
	],
	users=[
		User(
			id=854523506,
			is_self=True,
			contact=False,
			mutual_contact=False,
			deleted=False,
			bot=False,
			bot_chat_history=False,
			bot_nochats=False,
			verified=False,
			restricted=False,
			min=False,
			bot_inline_geo=False,
			support=False,
			scam=False,
			apply_min_photo=True,
			fake=False,
			bot_attach_menu=False,
			premium=False,
			attach_menu_enabled=False,
			bot_can_edit=False,
			close_friend=False,
			stories_hidden=False,
			stories_unavailable=True,
			access_hash=-7691835549633342691,
			first_name=-,
			last_name=-,
			username=None,
			phone=-,
			photo=UserProfilePhoto(
				photo_id=3670150512389498909,
				dc_id=2,
				has_video=False,
				personal=False,
				stripped_thumb=b'\x01\x08\x08w\xef|\xefY\x8b{\xe4QE\x14\x80'
			),
			status=UserStatusOnline(
				expires=datetime.datetime(2023, 9, 2, 19, 51, 31, tzinfo=datetime.timezone.utc)
			),
			bot_info_version=None,
			restriction_reason=[
			],
			bot_inline_placeholder=None,
			lang_code=None,
			emoji_status=None,
			usernames=[
			],
			stories_max_id=None
		),
	],
	chats=[
		Channel(
			id=1898190608,
			title=-,
			photo=ChatPhotoEmpty(
			),
			date=datetime.datetime(2023, 7, 9, 14, 0, 22, tzinfo=datetime.timezone.utc),
			creator=False,
			left=True,
			broadcast=False,
			verified=False,
			megagroup=True,
			restricted=False,
			signatures=False,
			min=False,
			scam=False,
			has_link=True,
			has_geo=False,
			slowmode_enabled=False,
			call_active=False,
			call_not_empty=False,
			fake=False,
			gigagroup=False,
			noforwards=False,
			join_to_send=False,
			join_request=False,
			forum=False,
			access_hash=-8280747966187315986,
			username=None,
			restriction_reason=[
			],
			admin_rights=None,
			banned_rights=None,
			default_banned_rights=ChatBannedRights(
				until_date=datetime.datetime(2038, 1, 19, 3, 14, 7, tzinfo=datetime.timezone.utc),
				view_messages=False,
				send_messages=False,
				send_media=False,
				send_stickers=False,
				send_gifs=False,
				send_games=False,
				send_inline=False,
				embed_links=False,
				send_polls=False,
				change_info=True,
				invite_users=True,
				pin_messages=True,
				manage_topics=False,
				send_photos=False,
				send_videos=False,
				send_roundvideos=False,
				send_audios=False,
				send_voices=False,
				send_docs=False,
				send_plain=False
			),
			participants_count=None,
			usernames=[
			]
		),
	],
	date=datetime.datetime(2023, 9, 2, 19, 50, 50, tzinfo=datetime.timezone.utc),
	seq=0
)
```

</details>

in this case my message exists

**Comment by Lonami** [comment]
Okay thanks, indeed there's no `UpdateMessageID` in the second case. It would be interesting to know if other users could see this message.

So raw API "works", i.e. it doesn't crash (it doesn't do what you want, but that's on Telegram, not the library). All that needs fixing is the "invalid mapping".

(I've also edited your comments to remove the phone and names, as well as better formatting.)

**Comment by plutonium777** [comment]
Other users can see this message. Hope this information was useful for your library. Also today I became your sponsor at GitHub. Hope you will fix that issue somehow, also would be cool if it will throw some kind of error, so users would know that their messages is invisible / not exist.

**Comment by Lonami** [comment]
> I became your sponsor at GitHub

Much appreciated :)

> also would be cool if it will throw some kind of error

The library logs a warning for other instances of "missing messages", and returns `None` instead of the `Message`.

So when this is fixed, you'll get `None` from `send_message` if it "can't" be sent.

**Comment by Lonami** [comment]
> I need to see the returned `Updates`

Looking back, you had included them in the original post, oops. Actually, there's nothing to fix, as this is already happening:

> The library logs a warning for other instances of "missing messages", and returns `None` instead of the `Message`.

I should've read the description more carefully (often, long one-line pastes make me look away).
