### ISSUE TITLE
Why Telethon requires api_id and api_hash?

### ISSUE THREAD

**Issue by User195** [LonamiWebs/Telethon#417]
First of all I am using this library and it is perfect!

Question is why does Telethon require api_id and api_hash while teltelegram-cli requires a phone number only?

Are there any ways to login only with phone number?

**Comment by Lonami** [comment]
Glad you like the library, and funny question. I don't know what `api_id` and `api_hash` the library uses, but it's likely the author has published the code to use his own ID/hash combination, which you should **not** do, as these values are private. Hence, you should get your own ID/hash combination :)

**Comment by Lonami** [comment]
[Here](https://github.com/vysheng/tgl/blob/ffb04caca71de0cddf28cd33a4575922900a59ed/mtproto-client.h#L40-L41).

**Comment by Lonami** [comment]
Linking this with #361 for future references.
