### ISSUE TITLE
Error with bot API ID of more than 4 bytes

### ISSUE THREAD

**Issue by tskim-cs** [LonamiWebs/Telethon#4171]
### Code that causes the issue

```python
client = TelegramClient(
    'bot', 6410000000, '{hash}', 
    connection=connection.ConnectionTcpMTProxyRandomizedIntermediate,
    proxy=('{address}', '{port}', '{secret}')
).start(bot_token={token})
```

### Expected behavior

My API ID starts with 6 and 10 digits, which exceed 4 byte integer.
I tried to sign in and got error as below:
```
Request caused struct.error: 'i' format requires -2147483648 <= number <= 2147483647: InvokeWithLayerRequest(layer=160, query=InitConnectionRequest(api_id=6410000000, device_model='PC 64bit', system_version='22.5.0', app_version='1.29.2', system_lang_code='en', lang_pack='', lang_code='en', query=GetConfigRequest(), proxy=InputClientProxy(address='xxx.xxx.xxx.xxx', port=xxx), params=None))
```

### Actual behavior

Should be signed in with long API ID.

### Traceback

```
Traceback (most recent call last):
    ...
    struct.pack('<i', self.api_id),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

### Telethon version

1.29.2

### Python version

3.11

### Operating system (including distribution name and version)

macOS 13.4

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by tskim-cs** [comment]
I checked my bot's API ID via below command:
```
curl https://api.telegram.org/bot{bot_token}/getMe
{"ok":true,"result":{"id":6410000000,"is_bot":true,"first_name":"xx","username":"xx_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}}
```

**Comment by tskim-cs** [comment]
If the API ID is different from the bot's API ID, what should I enter for the bot?

**Comment by Lonami** [comment]
What you get from BotFather is not the API ID. It is the bot token (consisting of bot user ID and a hash). The API ID and hash must be obtained from my.telegram.org. The documentation explains this.

**Comment by rafaelribeiroo** [comment]
> ```python
> hash
> ```

You had success on this issue?
