### ISSUE TITLE
Telegram bot crashed, said it was a Telethon bug

### ISSUE THREAD

**Issue by jpzex** [LonamiWebs/Telethon#4172]
### Code that causes the issue

from decouple import config
import logging
import requests
import telebot
from telethon.sync import TelegramClient
from telethon.tl.types import InputPeerUser, InputPeerChannel
from telethon import TelegramClient, sync, events

logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s', level=logging.DEBUG)

print("Starting...")

APP_ID = config("APP_ID", default=None, cast=int)
API_HASH = config("API_HASH", default=None)
FROM_ = config("FROM_CHANNEL")
TO_ = config("TO_CHANNEL")
TOKEN = "<BOT TOKEN REDACTED>"

FROM = [int(i) for i in FROM_.split()]
TO = [int(i) for i in TO_.split()]

try:
    client = TelegramClient('manteguinharedirectbot', APP_ID, API_HASH)
    client.start(bot_token=TOKEN)

except Exception as ap:
    print(f"ERROR - {ap}")
    exit(1)

@client.on(events.NewMessage(incoming=True, chats=FROM))

async def sender_bH(event):
    for i in TO:
        try:
            await client.forward_messages(
                i,
                event.message,
                as_album="true"
            )
        except Exception as e:
            print(e)

print("Bot has started.")
client.run_until_disconnected()

### Expected behavior

The bot redirects messages from one channel to another keeping the forwarded label

### Actual behavior

The bot crashed

### Traceback

DEBUG/2023-08-13 16:08:21,091] telethon.extensions.messagepacker: Assigned msg_id = 7266885812505368808 to GetChannelDifferenceRequest (7fc3e83ef220)
[DEBUG/2023-08-13 16:08:21,091] telethon.network.mtprotosender: Encrypting 1 message(s) in 56 bytes for sending
[DEBUG/2023-08-13 16:08:21,091] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2023-08-13 16:08:21,091] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2023-08-13 16:08:21,091] telethon.extensions.messagepacker: Assigned msg_id = 7266885812507472612 to MsgsAck (7fc3e8543160)
[DEBUG/2023-08-13 16:08:21,091] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2023-08-13 16:08:21,092] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2023-08-13 16:08:21,092] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2023-08-13 16:08:26,215] telethon.network.mtprotosender: Handling RPC result for message 7266885812505368808
[DEBUG/2023-08-13 16:08:26,217] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2023-08-13 16:08:26,217] telethon.extensions.messagepacker: Assigned msg_id = 7266885834487775556 to MsgsAck (7fc3e83eff40)
[DEBUG/2023-08-13 16:08:26,218] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[DEBUG/2023-08-13 16:08:26,218] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2023-08-13 16:08:26,218] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2023-08-13 16:08:26,218] telethon.extensions.messagepacker: Assigned msg_id = 7266885834490308512 to MsgsAck (7fc3e8543190)
[DEBUG/2023-08-13 16:08:26,218] telethon.network.mtprotosender: Encrypting 1 message(s) in 36 bytes for sending
[ERROR/2023-08-13 16:08:26,219] telethon.client.updates: Fatal error handling updates (this is a bug in Telethon v1.29.2, please report it)
Traceback (most recent call last):
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 353, in _update_loop
    diff = await self(get_diff)
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.TimedOutError: RPCError -503: Timedout (caused by GetChannelDifferenceRequest)
[ INFO/2023-08-13 16:08:26,243] telethon.network.mtprotosender: Disconnecting from 149.154.175.60:443/TcpFull...
[DEBUG/2023-08-13 16:08:26,244] telethon.network.mtprotosender: Closing current connection...
[DEBUG/2023-08-13 16:08:26,244] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2023-08-13 16:08:26,244] telethon.network.mtprotosender: Cancelling 0 pending message(s)...
[ INFO/2023-08-13 16:08:26,244] telethon.network.mtprotosender: Disconnection from 149.154.175.60:443/TcpFull complete!
[ INFO/2023-08-13 16:08:26,245] telethon.network.mtprotosender: Not disconnecting (already have no connection)
[ INFO/2023-08-13 16:08:26,251] telethon.network.mtprotosender: Not disconnecting (already have no connection)
Traceback (most recent call last):
  File "/home/jpzex/telefwd/telegram-auto_forwarder/bot.py", line 65, in <module>
    client.run_until_disconnected()
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 96, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 38, in _run_until_disconnected
    raise self._updates_error
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/updates.py", line 353, in _update_loop
    diff = await self(get_diff)
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/jpzex/.local/lib/python3.10/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.TimedOutError: RPCError -503: Timedout (caused by GetChannelDifferenceRequest)

### Telethon version

1.29.2

### Python version

Python 3.10.12

### Operating system (including distribution name and version)

Ubuntu Server 22.04 / Linux LTS 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux

### Other details

It is on my local server, the network has some port forwarding from the router to this specific device but they might not interfere with the bot, since it does not demand any port forwarding.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by CatchingStars** [comment]
I am having this issue on one of the connected accounts: every several days the client will disconnect because of it.

I think it's this issue: https://stackoverflow.com/questions/67608717/telegram-is-having-internal-issues-rpccallfailerror

I guess, the solution should be to await some time and try an update again? I am currently thinking on how to do that correctly in my code, but shouldn't it be implemented in Telethon itself, if it's a common occurrence in Telegram Servers?

**Comment by Lonami** [comment]
It seems Telegram for some reason renamed `Timeout` to <code>Time<strong>d</strong>out</code>, so this code indeed needs to change:

https://github.com/LonamiWebs/Telethon/blob/128b7074881c95fcc748f312ee92d09d650fd2f9/telethon/client/updates.py#L311
