### ISSUE TITLE
connect to proxy

### ISSUE THREAD

**Issue by jack-manual** [LonamiWebs/Telethon#4173]
### Code that causes the issue

I had a question about proxy

This code works correctly and the ip is also changed:

```
import requests

proxy = "username:password@v.site.com:8001"
proxies = {'http': f"http://{proxy}", 'https': f"http://{proxy}"}
response = requests.get(url="https://api.ipify.org/", proxies=proxies)
print(response.text)
```

But it gives an error when connecting to telethon with a proxy:

```
import os
from telethon.sync import TelegramClient
import socks


directory = os.path.dirname(os.path.abspath(__file__))

api_id = '7923474'
api_hash = '76473d5ab42a4307a858808d25cc2be9'

proxy = {
    'proxy_type': socks.PROXY_TYPE_HTTP,
    'addr': 'v.site.com',
    'port': 8001,
    'username': 'username',
    'password': 'password',
    'rdns': True
}

with TelegramClient(f"{directory}/xxx", api_id, api_hash, proxy=proxy) as client:
    print(client.get_me())
```

Error:
```
Attempt 1 at connecting failed: ConnectionError: [Errno 22] Could not connect to proxy v.site.com:8001 [The specified network name is no longer available]
```

### Expected behavior

connect to with proxy

### Actual behavior

It doesn't connect to the proxy

### Telethon version

1.29

### Python version

3.10

### Operating system (including distribution name and version)

windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by phapntm** [comment]
hello.
how did you fix issue?
i use the proxy but it not come through proxy...
i did use your code

**Comment by vpsconfig** [comment]
`pip install python-socks PySocks`, I found that they are indispensable, finally replace '123' in this code with the correct one

```
from telethon import TelegramClient;
import socks # pip install python-socks PySocks

api_id = 123
api_hash = "123"

proxy = {
    'proxy_type': 'socks5', # (mandatory) protocol to use (see above)
    'addr': '127.0.0.1',      # (mandatory) proxy IP address
    'port': 123,           # (mandatory) proxy port number
    'rdns': True            # (optional) whether to use remote or local resolve, default remote
}

# The first parameter is the .session file name (absolute paths allowed)
with TelegramClient("anon", api_id, api_hash, proxy=proxy) as client:
    client.loop.run_until_complete(client.send_message("me", "Hello, World!"))

```
