### ISSUE TITLE
Implement message translation

### ISSUE THREAD

**Issue by Programie** [LonamiWebs/Telethon#4176]
### Describe your suggested feature

The Telegram API supports translating messages using [messages.translateText](https://core.telegram.org/method/messages.translateText).

As of now, there is no way to access that method of the API. Therefore, this is a request for adding the ability to use the translation API into Telethon.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
> there is no way to access that method of the API

There is. See [The Full API](https://docs.telethon.dev/en/stable/concepts/full-api.html) and [`TranslateTextRequest`](https://tl.telethon.dev/methods/messages/translate_text.html).
