### ISSUE TITLE
Attempt 1 at connecting failed: TimeoutError: 

### ISSUE THREAD

**Issue by songqingshududu** [LonamiWebs/Telethon#4179]
### Code that causes the issue

from telethon import TelegramClient
proxy_address = '127.0.0.1'
proxy_port = 7890

client = TelegramClient('session_name', api_id, api_hash, proxy=("http", proxy_address, proxy_port))
client.start()

### Expected behavior

I used the proxy to connect to the client according to the examples provided in your documentation, and it has been unsuccessful

### Actual behavior

error：Attempt 1 at connecting failed: TimeoutError: 
![image](https://github.com/LonamiWebs/Telethon/assets/142251921/d7ce6281-1e09-4121-a32d-c90e1cd72253)

### Telethon version

1.29.3

### Python version

Python 3.8.10

### Operating system (including distribution name and version)

windows10

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This is likely an issue with the proxy. The traceback seems cut, so there's not much for me to work with.
