### ISSUE TITLE
Story support

### ISSUE THREAD

**Issue by emilio-cea** [LonamiWebs/Telethon#4180]
### Describe your suggested feature

Telegram introduced a new feature called "Story" similar to what Instagram has: small videos that show on a user profile.

These videos can also be shared on a chat and the library returns the message with a "MessageMediaUnsupported" type of media.

Will these stories be supported?

![yvUKcoE76d](https://github.com/LonamiWebs/Telethon/assets/23096738/8c8e1cf9-54a5-4e7b-814a-0666d6572486)

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Stories should already be supported via the raw API. Make sure you are using the latest version.

**Comment by emilio-cea** [comment]
Just updated to v1.29! Now they appear just fine.

Although this media shows up like a WebPage with an attribute telethon.tl.types.WebPageAttributeStory. I assume there's no easy way to get the photo/video of the story?

**Comment by Lonami** [comment]
I do not know or care for how stories work (and this isn't the right place to ask). But as the documentation suggests, it's recommended to just `print` the object to figure out what it has where.
