### ISSUE TITLE
TelegramClient.get_entity cannot resolve the user behind a forwarded message.

### ISSUE THREAD

**Issue by nzdev03** [LonamiWebs/Telethon#4181]
### Code that causes the issue

```
async with TelegramClient('test.session', API_ID, API_HASH) as client:
    message = await some_func_to_get_the_fwd_message(client)
    entity = await client.get_entity(message.fwd_from.from_id)
```

### Expected behavior

I was expecting the target `User` to be returned from `TelegramClient.get_entity`.

### Actual behavior

`ValueError` was risen.

### Traceback

```
Traceback (most recent call last):
  File "telegram.py", line 69, in main
    await client.get_entity(message.fwd_from.from_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telethon/client/users.py", line 291, in get_entity
    inputs.append(await self.get_input_entity(x))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telethon/client/users.py", line 467, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for PeerUser(user_id=<REDACTED>) (PeerUser). Please read https://docs.telethon.dev/en/stable/concepts/entities.html to find out more details.
```

### Telethon version

1.29.2

### Python version

python 3.11.3

### Operating system (including distribution name and version)

macOS 13.4

### Other details

It appears it only works on Channels, I tested using the `message.fwd_from.from_id.user_id` also with the same error being rose. Edit: I discovered this occurs only after attempting to get the entity of forwarded messages' sender users multiple times. It appears to be a weird rate-limit via Telegram's server. It may be a good idea to raise a `FloodWaitError` when this occurs or `TimeOutError`.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You don't seem to be using the latest Telethon version.

> I discovered this occurs only after attempting to get the entity of forwarded messages' sender users multiple times. It appears to be a weird rate-limit via Telegram's server

This shouldn't be the case. You're relying on Telethon's cache to get the user.

You may have better like with `message.forward.get_sender()`.
