### ISSUE TITLE
get type of chat id

### ISSUE THREAD

**Issue by Morrigan-Ship** [LonamiWebs/Telethon#4186]
### Description

how can i find chatid type?
for example if a chat id is 1786995317 how can i know this is for user or bot or channel?
i know for group and channels -100 is befor chat id
but sometime -100 is not how can i know the type?

### Checklist

- [ ] This is a documentation problem, not a question or a bug report.
- [ ] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
