### ISSUE TITLE
InitConnectionRequest params

### ISSUE THREAD

**Issue by artemki2077** [LonamiWebs/Telethon#4189]
### Describe your suggested feature

I would like to use params in the InitConnectionRequest, but TelegramBaseClient does not have such an attribute to add it to

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
You can already configure most of what's passed to `InitConnection` when creating the `TelegramClient`:

https://github.com/LonamiWebs/Telethon/blob/9b1d9aa672118fd9984b0b85610a2af105ad9c04/telethon/client/telegrambaseclient.py#L383-L392

Not all fields are intended for third-party applications to use, so those cannot be configured.

**Comment by artemki2077** [comment]
I mean this variable
<img width="610" alt="Снимок экрана 2023-09-01 в 11 47 44" src="https://github.com/LonamiWebs/Telethon/assets/86531080/a91aa1ee-50a6-4992-b809-def1ec91622a">
<img width="1062" alt="Снимок экрана 2023-09-01 в 11 49 00" src="https://github.com/LonamiWebs/Telethon/assets/86531080/038bb7f5-875b-4b2e-a067-1bd59821c0d8">

**Comment by Lonami** [comment]
As I mentioned, Not all fields are intended for third-party applications to use, so those cannot be configured.
