### ISSUE TITLE
Is there a simple way to get entity of a private channel? 

### ISSUE THREAD

**Issue by User195** [LonamiWebs/Telethon#419]
I know that to create a new entity of the channel there is two options
first option is to create the instance via constuctor
and second by get_entity() method, but as far as I know get_entity() method works with public channels only? Is there any helper method to get entity of the secret chat by chat link?

**Comment by Lonami** [comment]
I plan on adding support for private channels known their link soon. Currently you use the part after t.me/, which is the hash. Look for "hash" and "channel".

**Comment by User195** [comment]
The problem is that I need to create InputChannel of the private channel and it requires two parameters `channel_id` and `access_hash`. And if `access_hash` is part of  t.me/ link so where I get `channel_id`?

PS Sorry for my Enlgish, it is not my native language

**Comment by Lonami** [comment]
No, that's not the access hash, it's just a hash. You can get the channel with that "check invite" if I recall correctly (look for it). The library also converts normal channels to input channels foe you.

**Comment by User195** [comment]
Now to create an new secret InputChannel knowing only  t.me/ link I do:
```
chatinvite = client(CheckChatInviteRequest('*************link**********'))
channel_id = chatinvite.chat.id
access_hash_channel = chatinvite.chat.access_hash
input_channel = InputChannel(channel_id, access_hash_channel)
```
I think that there is a better solution to get InputChannel. Or no?

**Comment by Lonami** [comment]
There are functions on `telethon.utils` to do it yes but as I said the library will convert the channel to input channel when it needs.

**Comment by User195** [comment]
Thanks for this quick reply. Where can I get docs for all available helper methods? As far as I understand https://lonamiwebs.github.io/Telethon wiki describe only methods that can be `invoke()` so is there any docs for helper methods?

**Comment by Lonami** [comment]
```python
import telethon.utils
help(telethon.utils)
```
