### ISSUE TITLE
Cannot edit caption of File uploaded by other User in Channel

### ISSUE THREAD

**Issue by NotStatilko** [LonamiWebs/Telethon#4193]
### Code that causes the issue

1. Make a `Channel` (`C`) from user **A**
2. Add user **B** to `C` & grant all Admin privileges
3. Upload any `Document` to `C` from **B**
4. Run code example below from user **A**

```python
from telethon.sync import TelegramClient
from telethon.types import PeerChannel

API_ID = ...
API_HASH = ...
CHANNEL = PeerChannel(...)

client = TelegramClient(...)
client.start()

channel = client.get_entity(CHANNEL)

message = next(client.iter_messages(channel))
print(message.edit('Test caption') is None)
# ^ Message is NOT edited if result is True
```

### Expected behavior

I believe that user **A** (with _Owner_ privileges) should change caption of `Message` of user **B**.  

### Actual behavior

`Document` message is NOT edited (`None` returned).

### Traceback

`No Traceback.`

### Telethon version

1.29.3 (HEAD)

### Python version

3.9.2

### Operating system (including distribution name and version)

Debian 11

### Other details

This can be easily done within Telegram. Moreover, if **B** edit caption of file uploaded by **himself**, then things is OK (`Document` caption is edited).

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by NotStatilko** [comment]
Little debug show me that probably the problem in [this two lines of code](https://github.com/LonamiWebs/Telethon/blob/e928fbdac07b06730c8f6ef109a11126e2583f50/telethon/tl/custom/message.py#L806-L807):
```python3
        if self.fwd_from or not self.out or not self._client:
            return None  # We assume self.out was patched for our chat

```
As far i understand, `self.out` stands for "We are sender of this Message or not?". What is a reason behind using this in such statement? What if we just remove the `or not self.out`? This will resolve the problem described in this issue.

**UPD**: It seems that `client.edit_message` works fine on this Issue.

**Comment by Lonami** [comment]
Thanks for the very detailed report. To be fair, it's probably safe to remove that check entirely.

Trying to emulate server rules locally does not often end well.
