### ISSUE TITLE
Session expires too quickly (AuthKeyDuplicatedError)

### ISSUE THREAD

**Issue by AndriiRomanenko** [LonamiWebs/Telethon#4194]
### Code that causes the issue

client1 = TelegramClient(StringSession(session1), api_id1, api_hash1)
client1.start()

@client1.on(events.NewMessage())
async def normal_handler(event):
   #some code for new messages handling

client1.run_until_disconnected()

### Expected behavior

Expected that the session live more than 1 day

### Actual behavior

I have several accounts. Every account has its own client that uses its own string session. Code run on Heroku. 

After 15-20 hours code fails with an error:
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))

### Traceback

 Sep 08 04:56:50Z  app/worker.1 Traceback (most recent call last):
 Sep 08 04:56:50Z  app/worker.1   File "/app/main.py", line 58, in <module>
 Sep 08 04:56:50Z  app/worker.1     client1.start()
 Sep 08 04:56:50Z  app/worker.1   File "/app/.heroku/python/lib/python3.10/site-packages/telethon/client/auth.py", line 128, in start
 Sep 08 04:56:50Z  app/worker.1     else self.loop.run_until_complete(coro)
 Sep 08 04:56:50Z  app/worker.1   File "/app/.heroku/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
 Sep 08 04:56:50Z  app/worker.1     return future.result()
 Sep 08 04:56:50Z  app/worker.1   File "/app/.heroku/python/lib/python3.10/site-packages/telethon/client/auth.py", line 135, in _start
 Sep 08 04:56:50Z  app/worker.1     await self.connect()
 Sep 08 04:56:50Z  app/worker.1   File "/app/.heroku/python/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 593, in connect
 Sep 08 04:56:50Z  app/worker.1     await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
 Sep 08 04:56:50Z  app/worker.1 telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))

### Telethon version

1.29.3

### Python version

3.10

### Operating system (including distribution name and version)

Heroku-20 Stack (Ubuntu based OS)

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This isn't something Telethon can fix. The error describes what is, to the best of my knowledge, the reason.

So it's probably Heroku, which maybe runs the scripts from different locations.
