### ISSUE TITLE
Multiple Sessions

### ISSUE THREAD

**Issue by addreeh** [LonamiWebs/Telethon#4196]
### Describe your suggested feature

I have a server and a flutter app to log in telegram but i am only able to have one session in the server. I mean if I install the app in one phone and I log in telegram and then I install it in another phone I just entered in my account because is auto login with the session of the server.
I would like to be able to have multiple sessions.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
You can already create as many `TelegramClient` instances as you like, with as many different sessions as you like. The documentation also describes how to use different session storages if the default is not good for you.
