### ISSUE TITLE
on message receive event

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [LonamiWebs/Telethon#42]
Hello, Is there any method for "on messege receive" event? 
I need something like this:

```
def my_func(sender, msg):
    pass 
client = TelegramClient(...)
client.connect()
client.on_msg_receive(my_func)
```

**Comment by Lonami** [comment]
Yes… They're called "update handlers". Once again, see the `InteractiveClientExample`. Please fully read it before asking any other question (these are not **issues**, they are **questions**).

**Comment by alirezaafzalaghaei** [comment]
It not works for super-groups! At least it not worked for me...

**Comment by Lonami** [comment]
> It not works for super-groups!

I would say supergroups work slightly different. At least, on the official client, it happens to me that I don't receive any messages until I enter the application, or unless I'm mentioned. Perhaps you can manually check for those periodically.

**Comment by alirezaafzalaghaei** [comment]
The only reason i use telethon is on_msg_receive event :cry: 
I was very good that,on_msg_rec event works when i am admin...

**Comment by Lonami** [comment]
Once again, @vysheng has done an amazing job on his independant Telegram project. And [this issue](https://github.com/vysheng/tg/issues/1135) is probably related. I'm not sure what to do, I can only provide some insight. Telethon's update handler is simply another thread constantly trying to receive data from Telegram. If they're not sending this data (i.e.,&nbsp;message sent on a supergroup), it will obviously receive nothing.

The only solution I can think of is that you periodically check for these messages. Maybe on 10s intervals. I'm not sure. Or perhaps there's another way to subscribe to these events which I'm not aware of. The official [Telegram documentation](https://core.telegram.org/api/updates) on updates doesn't provide much insight, either.

**Comment by alirezaafzalaghaei** [comment]
Did you see telegram desktop or telegram for android/winphone source code? What did they do for this event on super groups?
I wanna to make an  ads remover client on a super with more than 4k member. sometimes members send more than 2-3 messages per second and sometimes 2-3 message per hour! on one hand use a short period(like 0.1 sec) cause more cpu usage, on the other hand use long time period(2-3sec) cause loosing some messages..

**Comment by Lonami** [comment]
> Did you see telegram desktop or telegram for android/winphone source code?

Not really no, I based Telethon on TLSharp. Occasionally took a look to their code, but it's *big*, like really big. I'm not willing to put the effort into studying it.

> I wanna to make an ads remover client on a super with more than 4k member.

Normal bots can also be used for this. You can make them administrators, and they can manage people who spam a lot.

**Comment by alirezaafzalaghaei** [comment]
> Not really no, I based Telethon on TLSharp. Occasionally took a look to their code, but it's big, like really big. I'm not willing to put the effort into studying it.

Can u ask from TLSharp author about that?

> Normal bots can also be used for this. You can make them administrators, and they can manage people who spam a lot.

bots cant remove members(spammers)...

maybe i should integrate your cli (to Delete messages) and another python bot manager module that supports webhooks. but its not best solution...

**Comment by Lonami** [comment]
> Can u ask from TLSharp author about that?

Not really no, this actually has got nothing to do with him. You can try using his library and find out why Telethon doesn't work (just my advice). I'd appreciate if you shared your knowledge back ;) — but again, your problem is not "an issue" with Telethon itself, but rather with how to use it. I mean, there's no bug. The way you're trying to do it must just not be the right way to do it. And I'm afraid I don't know either how this works, so I can't help much. Sorry Telegram doesn't have a good official documentation.

> Bots cant remove members(spammers)...

I would say the actually can. They just need admin priviledges. Maybe they can't if they're also trying to remove another person with priviledges, but in this case, only the owner can remove him. Am I wrong?

**Comment by alirezaafzalaghaei** [comment]
> I would say the actually can. They just need admin priviledges. Maybe they can't if they're also trying to remove another person with priviledges, but in this case, only the owner can remove him. Am I wrong?

Sorry bots can remove spammers, but they cant remove their spam messeges..

**Comment by Lonami** [comment]
> but they cant remove their spam messeges.

You're right, a bot cannot delete its own message. Which I don't understand why…
