### ISSUE TITLE
How to change version

### ISSUE THREAD

**Issue by cnekTep** [LonamiWebs/Telethon#420]
I create new client:
`client = TelegramClient(username, api_id, api_hash, connection_mode=connection.ConnectionMode.TCP_FULL, proxy=None, update_workers=None, timeout=timedelta(seconds=5), spawn_read_thread=True, device_model="mobileTel", app_version='1.0.1', system_version='123')`

then I try to view sessions:
`client(GetAuthorizationsRequest())`

and Telegram returns:
`Authorizations(authorizations=[Authorization(hash=0, flags=1, device_model='Windows', platform='Desktop', system_version='10', app_version='0.15.3.2', date_created=1510303321, date_active=1510305444 ...)`

what am I doing wrong? why not change device_model, app_version and system_version?

**Comment by Lonami** [comment]
Have you logged in before with a different version? It's only set on login, then not used.

**Comment by Lonami** [comment]
Actually, it's set when initializing the connection, not necessarily when logging in:
https://github.com/LonamiWebs/Telethon/blob/cad1e883a6baa989661a5643cf88a2cb86e3a3bf/telethon/telegram_bare_client.py#L218-L229

This is only called when:
* You have upgraded the library and the layer changes or
* It's the first time invoking something so it needs to initialize the connection.

Easiest thing, log out and try again setting the `app_version` from the beginning. Or, force a call yourself like so:
```
client(client._wrap_init_connection(GetAuthorizationsRequest()))
```

**Comment by cnekTep** [comment]
yes, I logged before, but if I terminate session in official Telegram app, and connect again (with new login code). After log_out everything works, thank you very much.

**Comment by Lonami** [comment]
Yeah, that was it, the library had an `auth_key` for the server but you can or not be logged in.
