### ISSUE TITLE
Bug: view once secret media is not implemented.

### ISSUE THREAD

**Issue by YaCodesDevelopment** [LonamiWebs/Telethon#4202]
### Describe your suggested feature

In Telegram there is a feature to send a secret media with ttl = view once, but there is no such thing implemented in Telethon. Please fix it, cause I can't normally work with the media.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
There are no plans to implement this in the near future. In the meantime, you can use https://tl.telethon.dev/methods/messages/send_media.html.

**Comment by YaCodesDevelopment** [comment]
But I mean also receiving such messages. That just spawns generic MessageMediaUnsupported(), which I can't handle

**Comment by Lonami** [comment]
Make sure you are up to date. I am not aware of any recent additions of new media types. Perhaps Telegram is blocking third-party applications from seeing them, in which case there is nothing to be done either.

**Comment by YaCodesDevelopment** [comment]
I am up to date, I'll send here the screenshots of what I mean now

**Comment by YaCodesDevelopment** [comment]
![IMG_20230916_161505_761.jpg](https://github.com/LonamiWebs/Telethon/assets/57478599/87a3148d-208c-4988-b41c-fa9ec2301803)

![IMG_20230916_161505_778.jpg](https://github.com/LonamiWebs/Telethon/assets/57478599/05b6ff45-7d61-4094-a87a-34f2796bc395)

![IMG_20230916_161505_435.jpg](https://github.com/LonamiWebs/Telethon/assets/57478599/42d0a801-7f0f-4bc1-a110-95ddf4435330)

Here is how it looks in app, and below is what it looks like in code:

![image](https://github.com/LonamiWebs/Telethon/assets/57478599/658e2d90-c079-4c10-8a42-35c40f620de8)

**Comment by Lonami** [comment]
Telegram distributes new features via layers.

Telethon is currently on layer 162:

https://github.com/LonamiWebs/Telethon/blob/ad19987cd6375cbcd7b7de6c6f3ce7d35180e913/telethon_generator/data/api.tl#L2126

The latest, to my knowledge, is 163:

https://github.com/telegramdesktop/tdesktop/blob/76ac6c3be76665eb17e86f1d91943f3dc7bb534b/Telegram/SourceFiles/mtproto/scheme/layer.tl#L1C12-L1C12

[There are, to my knowledge, no new media types](https://diff.telethon.dev/?from=162&to=163).

Therefore, this is not something I can "fix".

> I am not aware of any recent additions of new media types. Perhaps Telegram is blocking third-party applications from seeing them, in which case there is nothing to be done either.

**Comment by YaCodesDevelopment** [comment]
Alright, but is there maybe a way to catch this message as it arrives and get the structure out of it?
Cause I mean sure thing this was updated no matter what they say

**Comment by YaCodesDevelopment** [comment]
I guess I've found this:
```
        if (messageOwner.ttl == 0x7FFFFFFF) {
            if (secretOnceSpan == null) {
                secretOnceSpan = new SpannableString("v");
                ColoredImageSpan span = new ColoredImageSpan(R.drawable.mini_viewonce);
                span.setTranslateX(-AndroidUtilities.dp(3));
                span.setWidth(AndroidUtilities.dp(13));
                ((Spannable) secretOnceSpan).setSpan(span, 0, secretOnceSpan.length(), Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
            }
            return TextUtils.concat(secretOnceSpan, "1");
        }
```
        
Another reference:
`downloadObject.secret = MessageObject.isVideoDocument(messageMedia.document) && (messageMedia.ttl_seconds > 0 && messageMedia.ttl_seconds <= 60 || messageMedia.ttl_seconds == 0x7FFFFFFF);`

**Comment by YaCodesDevelopment** [comment]
Seems like max integer means view once, if so this should be an easyfix

**Comment by YaCodesDevelopment** [comment]
Exactly, just setting layer to 163 resolves the problem, but it returns ttl of 2147483647

**Comment by Lonami** [comment]
Layer 163 was released shortly after 162 with not that many additions it seems so it probably will be a while before I bump the number in Telethon.

2147483647 (0x7fffffff, or `i32::MAX_VALUE`) is probably just special cased to mean secret. Or maybe it sets the highest duration because "view once" is elsewhere.

**Comment by YaCodesDevelopment** [comment]
> Layer 163 was released shortly after 162 with not that many additions it seems so it probably will be a while before I bump the number in Telethon.
> 
> 2147483647 (0x7fffffff, or `i32::MAX_VALUE`) is probably just special cased to mean secret. Or maybe it sets the highest duration because "view once" is elsewhere.

Exactly, max int value is assigned to mark that this is one-time viewable media, that was silently implemented in 163 Layer. Just tested it to work fine with a few simple modifications and LAYER bumped. I guess this info will help implementing L163 here)

**Comment by drizzo0** [comment]
Hi, 
if you managed to add the view-once media type and for you works, can you create a PR?

**Comment by YaCodesDevelopment** [comment]
Well, it kinda works, but it's just a workaround, not a sufficient implementation. Nevertheless if you want, I may publish it.

UPD:
I mean I didn't fully implement layer 163, but I did make it pretend to fully support it, which might cause instabilities in some cases (for me works just fine since then, but your experiences may vary).

**Comment by drizzo0** [comment]
Yeah, if you can it would be appreciated, it could be a starting point to take off some wight from Lonami.
I'm heavly stressing the library in this period, so if a bug happens I'm pretty sure I would catch it

**Comment by Lonami** [comment]
Updating the layer is a matter if copying https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/mtproto/scheme/api.tl over to https://github.com/LonamiWebs/Telethon/blob/v1/telethon_generator/data/api.tl while keeping the `// LAYER` comment.

This will be done eventually. But Telegram often reuses the same layer with multiple changes, which is why I will wait to do it.

**Comment by drizzo0** [comment]
Yeah I guessed that.. but as YaCodes said there are also some small fixes, for this reason I just asked for the PR
