### ISSUE TITLE
Login without session

### ISSUE THREAD

**Issue by addreeh** [LonamiWebs/Telethon#4203]
### Description

Hi, I have I question, If I log in telegram from one pc for example, a session is saved, alright. But if other one try to log in with the same account he enters directly in the account because of the session. How can I solve that? I was searching in the documentation and stackoverflow but I did not find anything. 
So my problem is a security problem, because someone with my mobile phone can enter in my account if I already logged in the program.

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

Session file means access to the account. If a user has access to your PC and you have Telegram Desktop, the same happens - Telethon is not special in that reward.

Don't allow others to access your session file if you don't want them using it.
