### ISSUE TITLE
Issue when try to download fowarded messages.

### ISSUE THREAD

**Issue by JoaoZaokk** [LonamiWebs/Telethon#4206]
### Code that causes the issue

if message.media:
        # Especificando o caminho onde o arquivo será salvo (usando uma extensão genérica)
        caminho_arquivo = path + f"/{message.id}.file"
        caminho_arquivo = await message.download_media(file=caminho_arquivo)
        print('File saved to', caminho_arquivo)  # printed after download is done

### Expected behavior

Should download the media fowarded.

### Actual behavior

Actually nothing happens. Even the text fowarded messages isnt read by the bot.

### Telethon version

1.28.5

### Python version

3.10

### Operating system (including distribution name and version)

Windows 11

### Other details

What i did to get the videos is fowarding the message with send_file and send_nessage. This way it downloads to my drive (thats what i want) and send it to another group that ive created. The files is being downloaded with .file extension, whats weird, bc its clearly a video, and when i open that file with some player it runs well. Am i doing something wrong with the download_media?

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You're using an out-of-date version:
https://github.com/LonamiWebs/Telethon/blob/bd11564579c57c10757a9d841923d7f6968af204/telethon/version.py#L3

You're also passing `.file` to the filename. This is what's causing that to be the extension. Remove the extension if you want to let Telethon infer one or pass a different extension.

**Comment by JoaoZaokk** [comment]
Ill update, but the .file is a workaround that ive founded. When i was using media, for some reason the program doesnt find the messages.
