### ISSUE TITLE
Telethon || events.NewMessage do not detect message pattern if contains \n

### ISSUE THREAD

**Issue by KernelPanicNT** [LonamiWebs/Telethon#4208]
## Account # Telegram-Channel listener
@client.on(events.NewMessage(chats=intTGChannelId,pattern='.*Hello mates.*'))
async def handler(event):
    ## To Do stuff here

### Expected behavior

The expected behavior is detect text despite having a carriage return

### Actual behavior

Telethon library doesnt detect message (im using regex)

## Message with media attached
Message(id=306, peer_id=PeerChannel(channel_id=XXXXXX), date=datetime.datetime(2023, 9, 21, 2, 50, 52, tzinfo=datetime.timezone.utc), message='Good morning\nHello mates', out=True, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, from_id=None, fwd_from=MessageFwdHeader(date=datetime.datetime(2023, 9, 21, 2, 48, 55, tzinfo=datetime.timezone.utc), imported=False, from_id=PeerChannel(channel_id=XXXXXX), from_name=None, channel_post=302, post_author=None, saved_from_peer=None, saved_from_msg_id=None, psa_type=None), via_bot_id=None, reply_to=None, media=MessageMediaPhoto(photo=Photo(id=5789649519288369598, file_reference=b'\x04s\xd3\xdf\xe2\x00\x00\x012e\x0b\xaf\x8c\xdd\xe2\x99\x12\xf1`&\xc3\x86\xc8\xf9\x99%\x9a\xadf', date=datetime.datetime(2023, 9, 21, 2, 48, 55, tzinfo=datetime.timezone.utc), sizes=[PhotoStrippedSize(type='i', bytes=b'\x01\x1c(\xb0\xa2c)\xdd#\x80;f\x96E\x92X\xcf\x97$\xab\xee\x18\xd2\xcc\xc43*\xf5$\xd3\xe0\xda\x07\xdf\xce8\xe3\xb5=\xc5\xb2#EuA\x89\xa4n:\xee<\xd0\xdep\x04\xf9\xad\x81\xefAuR\xeb\xd8r?\x1f\xf2i\xad('), PhotoSize(type='m', w=320, h=229, size=18432), PhotoSizeProgressive(type='x', w=480, h=344, sizes=[3885, 9461, 14315, 19022, 27766])], dc_id=4, has_stickers=False, video_sizes=[]), ttl_seconds=None), reply_markup=None, entities=[], views=1, forwards=0, replies=MessageReplies(replies=0, replies_pts=0, comments=True, recent_repliers=[], channel_id=XXXXXX, max_id=None, read_max_id=None), edit_date=None, post_author=None, grouped_id=None, restriction_reason=[], ttl_period=None)

## Message without media attached
Message(id=307, peer_id=PeerChannel(channel_id=XXXXXX), date=datetime.datetime(2023, 9, 21, 2, 57, 46, tzinfo=datetime.timezone.utc), message='Good morning\nHello mates', out=True, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to=None, media=None, reply_markup=None, entities=[], views=1, forwards=0, replies=MessageReplies(replies=0, replies_pts=0, comments=True, recent_repliers=[], channel_id=XXXXXX, max_id=None, read_max_id=None), edit_date=None, post_author=None, grouped_id=None, restriction_reason=[], ttl_period=None)

### Telethon version

latest

### Python version

3.8.10

### Operating system (including distribution name and version)

Ubuntu Server

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This is not a problem with Telethon but the way [`re`](https://docs.python.org/3/library/re.html) works.

> (Dot.) In the default mode, this matches any character except a newline. If the [DOTALL](https://docs.python.org/3/library/re.html#re.DOTALL) flag has been specified, this matches any character including a newline.
