### ISSUE TITLE
Spoiler formatting is not available

### ISSUE THREAD

**Issue by MrVolot** [LonamiWebs/Telethon#4209]
### Describe your suggested feature

Why not to move to the newer version of telegram API and allow users to parse Spoiler formatting? Is this work planned?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Spoilers are supported and currently explained in https://github.com/LonamiWebs/Telethon/wiki/Sending-more-than-just-messages.

Changing the current markdown parser can't be done because it could break certain valid inputs today.

**Comment by MrVolot** [comment]
But what about the html formatting?

**Comment by Lonami** [comment]
No new features are planned for v1 at the moment. You can pass your own format functions as the `parse_mode` though.

**Comment by MrVolot** [comment]
> No new features are planned for v1 at the moment. You can pass your own format functions as the `parse_mode` though.

Got it, thanks
