### ISSUE TITLE
Telethon always asks for phone number and code, not using saved session

### ISSUE THREAD

**Issue by avk0** [LonamiWebs/Telethon#4210]
### Code that causes the issue

from telethon import TelegramClient

api_id = api_id 
api_hash = "api_hash"
session_name = 'New pools'
channel_username = "channel_username"

client = TelegramClient(session_name, api_id, api_hash)

async def main():
    # You can print the message history of any chat:
    async for message in client.iter_messages(channel_username, limit=10):
        print(message.id, message.text)

with client:
    client.loop.run_until_complete(main())

### Expected behavior

According to Telethon docs
_The session file contains enough information for you to login without re-sending the code, so if you have to enter the code more than once, maybe you’re changing the working directory, renaming or removing the file, or using random names._

This code is expected not to ask for phone number on a repeated code run without changing any file names or file locations. 

### Actual behavior

It asks for phone number even New pools.session file exists and was not changed.

Please enter your phone (or bot token):

### Telethon version

1.30.3

### Python version

3.10.11

### Operating system (including distribution name and version)

Windows 10 Home 22H2

### Other details

Run on a local laptop from Thailand. Physical phone with a number used is located in a different country.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Cannot reproduce.

Make sure the session file is being saved. You can confirm this with an SQLite Viewer program or similar.

If you don't want to use SQLite, [the documentation explains how to use other storage formats](https://docs.telethon.dev/en/stable/concepts/sessions.html#different-session-storage).

**Comment by avk0** [comment]
I looked inside SQLite with DBeaver, there is data in one line of the sessions table. Suggest that this is a security measure due to different locations of my computer and phone.

Thank you!
