### ISSUE TITLE
Add option to enable Telegram privacy mode for Groups/Channels on create

### ISSUE THREAD

**Issue by KernelPanicNT** [LonamiWebs/Telethon#4211]
### Describe your suggested feature

It will be helpfull (i didnt find it on docs) to make a boolean to enable/disable group/channel privacy mode or at least send this bool when CreateChannelRequest was done

Thanks in advance :)

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Raw API types and functions cannot be changed. Telegram decides those. This means you need to find a separate request in https://tl.telethon.dev to do what you need.
