### ISSUE TITLE
Send messages to chats with a channel as the sender

### ISSUE THREAD

**Issue by BotheorY** [LonamiWebs/Telethon#4215]
### Describe your suggested feature

As a Premium user of Telegram, with their official app, I can send **messages to chats** by setting **one of the channels I administer as the sender**. It would be nice if Telethon allowed doing the same thing.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
You can already do this in v1 using https://tl.telethon.dev/methods/messages/send_message.html directly, with `send_as`.
