### ISSUE TITLE
Get group by name

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [LonamiWebs/Telethon#4216]
### Code that causes the issue

```python
await client.get_entity("<group_name>")
```

### Expected behavior

I should be able to get the group entity by name

### Actual behavior

error saying, cannot find the entity - tried to look [here](https://arabic-telethon.readthedocs.io/en/stable/extra/basic/entities.html#getting-entities) but no luck

### Telethon version

1.30.3

### Python version

3.9

### Operating system (including distribution name and version)

macOS

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You can only reliably get groups by username, not name.

**Comment by FrancescoSaverioZuppichini** [comment]
> You can only reliably get groups by username, not name.

Thanks a lot for the reply, could you give ma an example?
