### ISSUE TITLE
Sending message containing link to boost channel turns message content to empty string and media to MessageMediaUnsupported()

### ISSUE THREAD

**Issue by redooo98** [LonamiWebs/Telethon#4217]
### Code that causes the issue

```py
@client.on(events.NewMessage(chats="testchat"))
async def my_event_handler(event):
      print(event.message)
```

### Expected behavior

i am using an echo bot that monitors a telegram channel and reposts messages from that channel to a discord channel. So the Expected behavior is that the message gets reposted to discord as it is.

### Actual behavior

the problem is whenever a link to boost the channel(https://t.me/<chatname>?boost) is sent anywhere inside the message, the message content turns into an empty string and media to MessageMediaUnsupported(). it only happens if the aformentioned link is inserted in a message, otherwise everything works fine.

### Telethon version

1.30.3

### Python version

3.10.5

### Operating system (including distribution name and version)

Windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
> I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

Did you actually do this? Are you sure the script used the development version?

**Comment by redooo98** [comment]
> > I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.
> 
> Did you actually do this? Are you sure the script used the development version?

Yes i did, and the development version is the only version i have installed so i am using it.

**Comment by Lonami** [comment]
[Current layer is 165](https://github.com/telegramdesktop/tdesktop/blob/9ad38b963835d3747168583cc3bc197df2febcad/Telegram/SourceFiles/mtproto/scheme/layer.tl#L1) and so is Telethon's:

https://github.com/LonamiWebs/Telethon/blob/7d7dbdf47f9ce57ebfafdd2fc3dde38840eb2f96/telethon_generator/data/api.tl#L2144

So I don't think this is something that can be fixed on Telethon's side, but rather Telegram doing its thing.
