### ISSUE TITLE
channels.getAdminedPublicChannels support

### ISSUE THREAD

**Issue by jurakontor** [LonamiWebs/Telethon#4218]
### Describe your suggested feature

hello
are you planning to add support for channels.getAdminedPublicChannels? do you have any idea how to get even private channels where you are an admin?
thanks

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
This is already supported https://tl.telethon.dev/methods/channels/get_admined_public_channels.html.
