### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by zakkanijia** [LonamiWebs/Telethon#4220]
### Code that causes the issue

from telethon.sync import TelegramClient, events
import python_socks
import os

api_id =
api_hash = ''

client = TelegramClient('mybot', api_id, api_hash, proxy=(python_socks.ProxyType.HTTP, '127.0.0.1', 10809))

client.start()

### Expected behavior

I was doing the example in the document. I live in a country that block telegrame so I have to use a proxy and it is v2Rayn.

### Actual behavior

I keep getting this error "Request caused struct.error: argument out of range: InvokeWithLayerRequest(layer=162, query=InitConnectionRequest(api_id=6680856537, device_model='PC 64bit', system_version='10', app_version='1.30.3', system_lang_code='en', lang_pack='', lang_code='en', query=GetConfigRequest(), proxy=None, params=None))"

### Traceback

Traceback (most recent call last):
  File "C:\Users\zakka_nijia\Desktop\telebot\main.py", line 11, in <module>
    client.start()
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\client\auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\client\auth.py", line 135, in _start
    await self.connect()
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\client\telegrambaseclient.py", line 593, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\network\mtprotosender.py", line 183, in send
    state = RequestState(request)
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\network\requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\tl\tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\tl\functions\__init__.py", line 253, in _bytes
    self.query._bytes(),
  File "C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\tl\functions\__init__.py", line 127, in _bytes
    struct.pack('<i', self.api_id),
struct.error: argument out of range
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<MTProtoSender._send_loop() running at C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\network\mtprotosender.py:464> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000018F78001940>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._recv_loop() running at C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\network\mtprotosender.py:507> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000018F780019A0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Connection._send_loop() running at C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\network\connection\connection.py:316> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000018F77FE0F40>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._recv_loop() running at C:\Users\zakka_nijia\anaconda3\envs\pytorch\lib\site-packages\telethon\network\connection\connection.py:335> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000018F780015B0>()]>>
Exception ignored in: <coroutine object Connection._recv_loop at 0x0000018F77FBBF40>
RuntimeError: coroutine ignored GeneratorExit

### Telethon version

1.30.3

### Python version

3.9.7

### Operating system (including distribution name and version)

Windows 10

### Other details

Thank you for your work. But really I have no idea what to do with this problem. Please help me. And i tried the proxy with other scripts and they work fine. I guess it is not proxy's fault. Please help me.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
I appreciate the kind words.

Unfortunately HTTP proxies probably require the HTTP connection mode which hasn't been maintained in a long while. There's no plans to revive them. I have no motivation to do so either.

**Comment by zakkanijia** [comment]
I tried with sock5 and get the same issue ...

**Comment by Lonami** [comment]
Right. Your API ID is probably wrong. This is not the number in your bot token. The documentation explains where to get this value from.
