### ISSUE TITLE
How to get stories with all data and download

### ISSUE THREAD

**Issue by iyamk** [LonamiWebs/Telethon#4221]
### Describe your suggested feature

I am executing a method to load a list of channel messages
```result = await client(GetMessagesRequest('https://t.me/+EFH53IOJSADif1', [2]))```
I get: media=MessageMediaStory(user_id=6468649006, id=1, via_mention=False, story=None)
I don’t understand where the raw data is and how I can download it

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
