### ISSUE TITLE
Remote String Session

### ISSUE THREAD

**Issue by AbdelrahmanAbounida** [LonamiWebs/Telethon#4223]
### Description

I wanna create an app such that any user can login with his telegram phone number and he can access his telegram data
so it is 2steps :
(1)  send a request to user telegram (route1)
(2)  get the code and send it to signin (route2)

but the problem is both routes will have differnet **TelegramClient** how to solve that 

Thanks 

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
