### ISSUE TITLE
Can't install v2 to test it

### ISSUE THREAD

**Issue by elky** [LonamiWebs/Telethon#4224]
### Code that causes the issue

Trying to test v2 according to the [Installation guide](https://docs.telethon.dev/en/v2/basic/installation.html):

```
> pip install --upgrade https://github.com/LonamiWebs/Telethon/archive/v2.zip
```

### Expected behavior

v2 installation with pip expected

### Actual behavior

```
Collecting https://github.com/LonamiWebs/Telethon/archive/v2.zip
  Using cached https://github.com/LonamiWebs/Telethon/archive/v2.zip
ERROR: https://github.com/LonamiWebs/Telethon/archive/v2.zip does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

### Telethon version

2

### Python version

3.11.6

### Operating system (including distribution name and version)

Ubuntu 23.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Thanks, I'll update the docs.

You can clone the repository, `git checkout v2`, and run `pip install client/` from the root of the repository.

I don't know if there's a way to specify a folder of a Git repository or ZIP install.

**Comment by Lonami** [comment]
Using subdirectories is documented in https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support.
