### ISSUE TITLE
bug at client while trying to connect to TelegramClient, will sleep until i break the program

### ISSUE THREAD

**Issue by carrot303** [LonamiWebs/Telethon#4225]
### Code that causes the issue

```python
import asyncio
import socks
from telethon import TelegramClient

TELEGRAM_CONNECTION_RETRIES = 2
TELEGRAM_REQUEST_RETRIES = 2
TELEGRAM_TIMEOUT = 5
proxy = {
    'proxy_type': socks.SOCKS5,
    'addr': "<addresss>",
    'port': <port>,
    'username': "<username>",
    'password': "<password>",
    'rdns': True
}

def return_teleclient(api_id, api_hash, session_path):
    return TelegramClient(
        session_path,
        api_id,
        api_hash,
        connection_retries=TELEGRAM_CONNECTION_RETRIES,
        request_retries=TELEGRAM_REQUEST_RETRIES,
        timeout=TELEGRAM_TIMEOUT,
        proxy=proxy,
        system_lang_code="en",
        lang_code="en"
    )

async def main():
    client = return_teleclient("<api_id>","<api_hash>", "<session_path>")
    print("before connecting")
    await client.connect()
    print("client connected"
    ## some stuff things here (like join to channel)
    await client.disconnect()

```

### Expected behavior

when i run the program, in **some cases** client does not connect to telegram and it will wait until the connection successfully becomes to done (actually this will never happened, i wait a lot to see what will happen)

and only the line `before connecting` will print in console, i also set **timeout**, **request_retries**, **connection_retries** , at least i expected the  *connection failed* or *timeout error* error, but it does not appear

what's wrong here?

### Actual behavior

actually sometimes this program runs very well but in some cases it does not run completely and will set my program in Sleep mode

### Traceback

after some minute i tried to break the program with `Ctrl+C`
and this Traceback appear there

```
(venv) $ python3 worker.py            
^CTraceback (most recent call last):                                                
  File "<file_path>", line 105, in <module>        
    asyncio.run(worker())                                                           
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run                    
    return loop.run_until_complete(main)                                            
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()                                                              
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever       
    self._run_once()                                                                
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once        
    event_list = self._selector.select(timeout)                                     
  File "/usr/lib/python3.10/selectors.py", line 469, in select                      
    fd_event_list = self._selector.poll(timeout, max_ev)                            
KeyboardInterrupt                                                                   
```

### Telethon version

1.31.1

### Python version

3.10.12

### Operating system (including distribution name and version)

Ubuntu 22.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by khoben** [comment]
You may try to connect like [this](https://github.com/LonamiWebs/Telethon/issues/1536#issuecomment-1739029968)

**Comment by carrot303** [comment]
Thanks I'll try that

**Comment by carrot303** [comment]
@khoben 
hi, this approach did not works on my code, i think it because  of `pysocks`, i think this library is sync not async, so can i use something like `aiosocks`?

**Comment by khoben** [comment]
> @khoben 
> hi, this approach did not works on my code, i think it because  of `pysocks`, i think this library is sync not async, so can i use something like `aiosocks`?

I don't know exactly, I've never used telethon with proxy, maybe the library itself doesn't work well with proxies. But with this approach it shouldn't hang forever while connecting, seems like a network/proxy problem.

**Comment by Lonami** [comment]
This is unlikely to be a problem in Telethon but rather the proxy. Direct proxy support will be removed in v2 but you will be able to use your own "open connection" (including using proxies). So I'll be closing the issue.
