### ISSUE TITLE
OperationalError('attempt to write a readonly database')

### ISSUE THREAD

**Issue by twelc** [LonamiWebs/Telethon#4227]
### Code that causes the issue

elif not users.get(message.chat.id) == None and users.get(message.chat.id) == [11]:
            try:
                dat = message.raw_text.split("\n")
                _id, _hash, _num = dat[0], dat[1], dat[2]
            except:
                await bot.send_message(message.chat.id, "Incorrect")
            try:
                if os.path.exists(f"anon{_id}.session"):
                    os.remove(f"anon{_id}.session")
            except:
                await bot.send_message(message.chat.id, str(sys.exc_info()[1]) + str(sys.exc_info()[2].tb_lineno))
            try:
                _cl = TelegramClient(f'anon{_id}', _id, _hash, system_version="4.16.30-vxCUSTOM", device_model="ASUS Laptop", app_version="4.10", loop=loop)
                await _cl.connect()
                accounts.append(_cl)
                if not await _cl.is_user_authorized():
                    phone_hash = await _cl.send_code_request(_num)
                    phone_code_hash = phone_hash.phone_code_hash
                    users[message.chat.id] = [12, _cl.api_id, _num, phone_code_hash]
                    await bot.send_message(message.chat.id, "Enter code")
                else:
                    await bot.send_message(message.chat.id, "Saved", buttons=[Button.inline("Home", data="home_Page")])
            except:
                await bot.send_message(message.chat.id, str(sys.exc_info()[1]) + str(sys.exc_info()[2].tb_lineno))
        
        elif not users.get(message.chat.id) == None and users.get(message.chat.id)[0] == 12:
            print(f"num: {users.get(message.chat.id)[2]}, code: {message.raw_text}")
            try:
                for a in accounts:
                    if a.api_id == users.get(message.chat.id)[1]:
                        acc = a
                        break
                
              
                await acc.sign_in(users.get(message.chat.id)[2], message.raw_text, phone_code_hash=users.get(message.chat.id)[3])
                await bot.send_message(message.chat.id, "Сохранено", buttons=[Button.inline("Home", data="home_Page")])
            except:
                
                await bot.send_message(message.chat.id, "Error " + str(sys.exc_info()))

### Expected behavior

I need to log into user accounts using the bot account as the interface. There is no problem with adding some accounts, but with some others I get this error.

### Actual behavior

When logging some accounts I get this error

### Traceback

<class 'sqlite3.OperationalError'> OperationalError('attempt to write a readonly database')

### Telethon version

1.30.3

### Python version

3.10

### Operating system (including distribution name and version)

Hosting like docker container

### Other details

I'm running my application on cloud.amvera.ru

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This is not something Telethon can fix. If SQLite says the database is readonly, you need to figure that out or use a different session to SQLite as documented.
