### ISSUE TITLE
Unhandled exception on normal_handler

### ISSUE THREAD

**Issue by alexisaeff** [LonamiWebs/Telethon#4228]
### Code that causes the issue

message = event.message.to_dict()['message']

### Expected behavior

I send message like "#TEB buy setup" and get error

### Actual behavior

Get error "File "/home/../.local/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update"

### Traceback

Traceback (most recent call last):
  File "/home/...../.local/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)

### Telethon version

1.30.3

### Python version

Python 3.10.12

### Operating system (including distribution name and version)

Ubuntu 20

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You're not using the latest version and the issue does not contain enough information to be actionable.
