### ISSUE TITLE
Problem in downloading media documents

### ISSUE THREAD

**Issue by abahramali** [LonamiWebs/Telethon#423]
Hi,
Thanks for your library. I have a issue; when I am trying to download media documents such as videos or tracks "download_media" function keep downloading the file several times and I don't know why but it is fine for photos.
I really appreciate if anyone can help me.
Thanks

**Comment by Lonami** [comment]
#411, likely #338.

**Comment by abahramali** [comment]
Thanks but they are not answered!

**Comment by Lonami** [comment]
No they're not and opening a new issue won't make a solution pop up faster. It will rather delay me by making me answer this and having to keep track of two issues instead you providing more information in the existing ones.
