### ISSUE TITLE
Missed update during automatic connection recovery

### ISSUE THREAD

**Issue by azhuchkov** [LonamiWebs/Telethon#4235]
### Code that causes the issue

```python
from telethon import TelegramClient, events

...

client = TelegramClient(SESSION, API_ID, API_HASH, system_version='4.16.30-vxCUSTOM')
logger = logging.getLogger('SCRIPT')

@client.on(events.NewMessage(chats=[CHAT_ID], incoming=True))
async def message_handler(event):
    msg_text = event.message.message

    logger.info("Incoming message: %s", msg_text)
    ...
   

client.start()
client.run_until_disconnected()
```

### Expected behavior

The client machine goes to sleep and then awakes after some time resulting in TCP connection reset. The connection should be automatically recovered and all pending updates should be delivered to handler methods. Or: if the automatic recovery has unavoidable restrictions and pitfalls, they should be documented.

Note: sometimes it works, but often does not. Local firewall didn't help to reproduce. 

### Actual behavior

There is a pending unread message that is not handled till the next message arrival. After that **both** of the messages are passed to the handler method.

### Traceback

```
...
[ INFO/2023-11-02 23:19:53,216] telethon.client.updates: Got difference for channel xxxxxx3621 updates
[ INFO/2023-11-02 23:19:53,352] telethon.client.updates: Got difference for channel xxxxxx1723 updates
[WARNING/2023-11-02 23:52:06,738] telethon.network.connection.connection: Server closed the connection: [Errno 54] Connection reset by peer
[ INFO/2023-11-02 23:52:06,738] telethon.network.mtprotosender: Connection closed while receiving data: [Errno 54] Connection reset by peer
[ INFO/2023-11-02 23:52:06,738] telethon.network.mtprotosender: Closing current connection to begin reconnect...
[ INFO/2023-11-02 23:52:06,739] telethon.network.connection.connection: <class 'ConnectionResetError'> during disconnect: [Errno 54] Connection reset by peer
[ INFO/2023-11-02 23:52:06,739] telethon.network.mtprotosender: Connecting to 149.154.167.xx:443/TcpFull...
[ INFO/2023-11-02 23:52:06,835] telethon.network.mtprotosender: Connection to 149.154.167.xx:443/TcpFull complete!
[ INFO/2023-11-02 23:52:09,120] telethon.client.updates: Got difference for channel xxxxxx2515 updates
[ INFO/2023-11-02 23:52:09,244] telethon.client.updates: Got difference for channel xxxxxx1723 updates
[ INFO/2023-11-02 23:52:39,412] telethon.client.updates: Got difference for account updates
[ INFO/2023-11-02 23:52:39,413] SCRIPT: Incoming message: <MESSAGE>
[ INFO/2023-11-02 23:52:39,414] SCRIPT: Incoming message: <MESSAGE>
...
```

### Telethon version

1.32.0

### Python version

3.12.0

### Operating system (including distribution name and version)

macOS 12.7.1

### Other details

The missed message arrives concurrently to connection recovery process, so there is a race condition that makes the problem harder to reproduce.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
> There is a pending unread message that is not handled till the next message arrival. After that both of the messages are passed to the handler method.

This sounds like it's working as intended, then. The library can only know updates are missing if it either:

* hasn't received updates in a while, or
* has detected a gap in the updates.

As long as you're getting all updates in the correct order at some point then it's working fine.

I don't think `asyncio.open_connection` really offers a way to know when the network is "back online".

**Comment by azhuchkov** [comment]
> As long as you're getting all updates in the correct order at some point then it's working fine.

There are cases where incoming messages are time-critical and must be handled in seconds. 
Is there some configuration property to decrease interval to detect missed updates?

**Comment by Lonami** [comment]
You can call `.catch_up()` to pretend there was a gap and cause a fetch. This is documented.

In the general case Telegram can delay the updates much longer and I don't know what the effects of calling the above constantly are. So you're probably out of luck.

**Comment by azhuchkov** [comment]
Thanks a lot for the lead. I tried to set `catch_up=True` for `TelegramClient`, that apparently addressing a similar issue, but unfortunately still no luck.

I should also say, that even when connection is not closed (i.e. period of sleep is quite short), there is a significant delay in message processing which includes lots of warnings like `Server sent a very old message` and `Security error while unpacking a received message: Too many messages had to be ignored consecutively`.

According to the FAQ such messages may appear in case of problems with machine system time. Does it mean that `telethon` assumes that system time always gradually increasing and fails in case of discrete time change (by NTP, SA or sleep mode). Can it hypothetically cause the issue I'm discovering?

I still believe that the problem can be solved, since _official_ Telegram client for `macOS` uses the same protocol and perfectly works in exactly the same environment and conditions that I use for `telethon`.

**Comment by azhuchkov** [comment]
Follow-up: I tried to set system time several minutes ahead and then return it back to normal. As a result I got a bunch of errors, connection was closed and re-established, but most importantly the message that was sent after system time change  was kept unprocessed even after the correct time was set and despite of messages `Got difference for channel`.

**Comment by Lonami** [comment]
> I still believe that the problem can be solved, since _official_ Telegram client for `macOS` uses the same protocol and perfectly works in exactly the same environment and conditions that I use for `telethon`.

I've heard before of Telethon receiving updates on-time and other libraries being delayed. And vice-versa. This is Telegram's own doing. Telegram decides when to deliver the updates to which sessions. You cannot control this. Even official clients may sometimes be delayed.
