### ISSUE TITLE
web app button

### ISSUE THREAD

**Issue by crazyministr** [LonamiWebs/Telethon#4236]
### Describe your suggested feature

Is there a way to make a button with web_app param ? https://core.telegram.org/bots/api#inlinekeyboardbutton

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

But yes, they can be used https://t.me/TelethonChat/532349.
