### ISSUE TITLE
error for parsing message from channel

### ISSUE THREAD

**Issue by dmitrdv** [LonamiWebs/Telethon#424]
Hello!

I am trying to find channel by name and then get messages from it. My code is following:
` import telethon`
`telegram = telethon.TelegramClient('myssesion', 49631, 'fb050b8f6771e15bfda5df2409931569')`
`telegram.connect()`

`channel = telegram.get_entity('russica2') # find channel by name, channel is found successfully`
`messages = telegram.get_message_history(entity=channel) # exception is thrown here`

Channel is found successfully. But during getting messages I got error:
> Traceback (most recent call last):
  File "sandbox.py", line 8, in <module>
    messages = telegram.get_message_history(entity=channel)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telethon/telegram_client.py", line 561, in get_message_history
    add_mark=True
KeyError: 1118393225

Could you please help me?

**Comment by Lonami** [comment]
I'm not sure I understand the error.

**Comment by dmitrdv** [comment]
I don't understand it too. I got just this number 1118393225 in error message.
Maybe it is some new telegram feature? I have not this channel in contact list for that telegram channel. just find it by name and search

**Comment by Lonami** [comment]
Just format the issue clearer and try to explain what happened better. `KeyError` makes no sense with what you posted.

**Comment by dmitrdv** [comment]
In general:
I try to find channel by name 'russica2'. Channel is found successfully
Then I try to get message from found channel. And during it exception is thrown. On console output I see that error.

**Comment by Lonami** [comment]
Okay that's weird the message https://t.me/russica2/3224 has no `.from_id` and no `.fwd_from.from_id` either (while it was forwarded).

**Comment by dmitrdv** [comment]
and what can be done to get messages from this channel?
also if I set limit=1 it still failed despite I get only last one message which is correct

**Comment by Lonami** [comment]
@dmitrdv I've fixed the issue, I'll push to PyPi in a sec.

**Comment by dmitrdv** [comment]
ok great thank you!!
