### ISSUE TITLE
Telegram telethon messages forwarding bot stopped working

### ISSUE THREAD

**Issue by dottantgal** [LonamiWebs/Telethon#4259]
### Code that causes the issue

@client.on(events.NewMessage())
async def handler(event):
    print(event)

### Expected behavior

Catch messages and print the event if something is posted on chat, group or channels

### Actual behavior

It prints just from chat, group and channel where I am admin, not from channels that I follow

### Telethon version

1.24.0

### Python version

Python 3.8.10

### Operating system (including distribution name and version)

Ubuntu 20.04

### Other details

starting from yesterday' afternoon my messages forwarding bot stopped to work from grabbing messages from channels, but it seems to work with channels where I am admin. In a few words these code lines (I'm omitting all the previous standard code lines where the client starts) are not catching messages if new messages are posted in channels that I follow. Anyone got the same issue?
Do you know if something changed and the channels now can block this kind of events?
Thank you

EDIT
It works just with one channel where I am admin, I really don't understand the issue.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by dottantgal** [comment]
Probably I discovered what happened: the massage forwarding is blocked trying to grab messages from channel with more than a certain number of followers. In facts my bot works for channel that I follow with less than 1000 followers, otherwise it doesn't grab anything. This is my theory

**Comment by kittyandrew** [comment]
My userbot was reposting (receiving and sending as new) messages from 15k people channel (I'm admin) and it just stopped working completely yesterday. Very much fun

**Comment by dottantgal** [comment]
So it's a common issue right now. What can be the source? Telegram itself blocked it? Basically is not the forwarding, but the catching of messages from medium/big channels that doesn't work anymore

**Comment by kittyandrew** [comment]
Fixed by upgrading to latest version of telethon!
I don't remember why my version was pinned at 1.24.0, but considering we both had the same version, there probably was a good reason at a time.
Works fine now for me (**so far**).

**Comment by dottantgal** [comment]
Thank you, it works now
