### ISSUE TITLE
not store all session entities in memory

### ISSUE THREAD

**Issue by dmitrdv** [LonamiWebs/Telethon#426]
Hi!

Tell me please. You wrote that it is possible to store session in database instead of file. But in any cases all entities upload in memory from DB or from file. I think that after some times count of entities will increase significantly and it will not suitable to store all of them in memory simultaneously. 

So is it possible somehow to not store keys in memory at all but find specific one in database when it is needed?

Thank you

**Comment by Lonami** [comment]
`self.session.entities.enabled_full = False`.
