### ISSUE TITLE
Async context manager is not properly typed

### ISSUE THREAD

**Issue by Aplietexe** [LonamiWebs/Telethon#4260]
### Code that causes the issue

```python
async with TelegramClient("telegram_session",api_id,api_hash) as client:
    # client is typed as Unknown
```

### Expected behavior

The return type of the async context manager should be TelegramClient

### Actual behavior

The return type of the async context manager is Unknown

### Telethon version

1.32.1

### Python version

3.11.6

### Operating system (including distribution name and version)

Ubuntu 22.04.3 LTS under WSL2 on Windows 11

### Other details

Seems like a simple fix, I'd be happy to make a PR. 

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Unlikely to be fixed in v1 due to the .sync hack but should work in v2.
