### ISSUE TITLE
Encountering an OSError while attempting to download a file.

### ISSUE THREAD

**Issue by meirkremer** [LonamiWebs/Telethon#4266]
### Code that causes the issue

file_path = await client.download_media(telegram_message)

### Expected behavior

The file should be downloaded, and the file path should be returned.

### Actual behavior

I encountered an OSError: [Errno 22] Invalid argument due to an invalid character in the file name.

### Traceback

Traceback (most recent call last):
  File "C:\Users\marwo\Desktop\WORK\media_service\send_new_songs\app.py", line 67, in <module>
    loop.run_until_complete(main())
  File "C:\Users\marwo\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\marwo\Desktop\WORK\media_service\send_new_songs\app.py", line 51, in main
    file_link, file_name = await telegram_to_drive(song_message, folder_id)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwo\Desktop\WORK\media_service\send_new_songs\from_telegram_to_gdrive.py", line 104, in telegram_to_drive
    file_path = await download_song(telegram_message)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwo\Desktop\WORK\media_service\send_new_songs\from_telegram_to_gdrive.py", line 15, in download_song
    file_path = await client.download_media(telegram_message)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwo\PycharmProjects\send_new_songs\venv\Lib\site-packages\telethon\client\downloads.py", line 422, in download_media
    return await self._download_document(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwo\PycharmProjects\send_new_songs\venv\Lib\site-packages\telethon\client\downloads.py", line 889, in _download_document
    result = await self._download_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marwo\PycharmProjects\send_new_songs\venv\Lib\site-packages\telethon\client\downloads.py", line 540, in _download_file
    f = open(file, 'wb')
        ^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'נפתלי קמפה - תפילת חנה | לייב.mp3'

### Telethon version

1.28.5

### Python version

3.11.7

### Operating system (including distribution name and version)

windows 11 Home 22H2

### Other details

The error occurs because there is no mechanism in place to check and handle invalid characters in the file name.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by meirkremer** [comment]
It seems that the issue lies in the method `_get_proper_filename` within `telethon.client.downloads.DownloadMethods`. To address this problem, it is necessary to incorporate additional business logic within the method to ensure that the file name does not contain any invalid characters for any operating system.

**Comment by Lonami** [comment]
This is unlikely to change in v1. You can provide your own file name instead.

**Comment by meirkremer** [comment]
> This is unlikely to change in v1. You can provide your own file name instead.

I added this function to _get_proper_filename:
```python
def remove_unvalid_chars(name):
    unvalid_chars = ['*', '?', ':', '|', '/', '\\', '<', '>', '"']
    pattern = '[' + re.escape(''.join(unvalid_chars)) + ']'
    result = re.sub(pattern, '', name)
    return result
```
and it's solved the issue

**Comment by Lonami** [comment]
It's not just those characters that are invalid. Other combinations or different systems may have different rules.

**Comment by meirkremer** [comment]
> It's not just those characters that are invalid. Other combinations or different systems may have different rules.

Yeah, this was only a local-temporary solution. For a complete solution, you can use the 'pathvalidate' library, but it adds another dependency to the project.
