### ISSUE TITLE
Subscribe to group messages user is not a member of

### ISSUE THREAD

**Issue by allserialtv** [LonamiWebs/Telethon#4267]
### Describe your suggested feature

Hello

Now i use another php lib and there is a cool feature to subscribe to a new messages of the chat in which user is not participant(Not a member of this public chat) This method called subscribeToUpdates in php madeline proto.

Do you plan to implement such function in Telethon?

Thanks

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
There are no plans to implement this as a built-in, but you're free to use [GetChannelDifferenceRequest](https://tl.telethon.dev/methods/updates/get_channel_difference.html) to your heart's content. How to do so is offtopic for the issues section - the documentation explains how to use raw API.
