### ISSUE TITLE
Unable to get the total number of messages in the public channel

### ISSUE THREAD

**Issue by agoukuaile** [LonamiWebs/Telethon#4270]
### Code that causes the issue

        chat_entity = client.get_input_entity('Durov')
        result = client(GetSearchCountersRequest(
            peer=chat_entity,
            filters=[
                # Photo
                types.InputMessagesFilterPhotos(),
                # Video
                types.InputMessagesFilterVideo(),
                # Voice
                types.InputMessagesFilterVoice(),
                # All
                types.InputMessagesFilterEmpty(),
            ],
        ))
        for x in result:
            if x.filter == types.InputMessagesFilterPhotos():
                print('Photo Count:',x.count)
            if x.filter == types.InputMessagesFilterVideo():
                print('Video Count:',x.count)
            if x.filter == types.InputMessagesFilterVoice():
                print('Voice Count:',x.count)
            if x.filter == types.InputMessagesFilterEmpty():
                print('All msg count:',x.count)

### Expected behavior

Return the total number of messages

### Actual behavior

Photo Count: 32
Video Count: 4
Voice Count: 0
All msg count: 0

### Telethon version

1.28.5

### Python version

3.9.13

### Operating system (including distribution name and version)

Windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

You're also using an outdated Telethon version.
