### ISSUE TITLE
Code expired despite not sending it via the app

### ISSUE THREAD

**Issue by paweldzia** [LonamiWebs/Telethon#4271]
### Code that causes the issue

Running with Quart:

```
@auth_blueprint.route('/verifyCode', methods=['POST'])
async def verify_telegram_code():
    data = await request.get_json()
    phone_number = data['phone_number']
    code = data['code']
    requester_uid = data['requester_uid']

    if not requester_uid:
        return jsonify({"status": "error", "message": "No requester_uid provided"})

    # Retrieve phone_code_hash from Firestore, that has been saved during send_code_request
    doc_ref = db.collection('telegram_sessions').document(requester_uid)
    doc = doc_ref.get()
    
    if not doc.exists:
        return jsonify({"status": "error", "message": "Session in Firestore not found"})

    phone_code_hash = doc.to_dict()['phone_code_hash']
    session_string = doc.to_dict().get('session', "")

    client = TelegramClient(StringSession(session_string), TELEGRAM_API_ID, TELEGRAM_API_HASH)
    if not client.is_connected():
        await client.connect()

    try:
        await client.sign_in(phone=phone_number, code=code, phone_code_hash=phone_code_hash)

        # Update Firestore with the new session data
        new_session_string = client.session.save()
        doc_ref.update({'session': new_session_string})

        return jsonify({"status": "success", "message": "Logged in successfully"})
    except errors.SessionPasswordNeededError:
        return jsonify({"status": "error", "message": "Two-step verification is enabled"})
    except errors.PhoneCodeInvalidError:
        return jsonify({"status": "error", "message": "Invalid code"})
    except errors.PhoneCodeExpiredError:
        return jsonify({"status": "error", "message": "Expired code"})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)})
    finally:
        await client.disconnect()
```

### Expected behavior

I want to sign in into my Telegram account in my own custom app. Both, the official Telegram app as well as my custom app, are on the same device.

1. I request the code via `client.send_code_request(phone_number)`
2. I get the code automatically via official Telegram app (from the user "Telegram")
4. I see the code in the new message notification from the Telegram app
5. I type in the code in my custom app (on the same phone) within 10-15 seconds after receiving it
6. I get logged in, the session string is being saved

### Actual behavior

Instead of being signed in upon providing phone hash + code, I get the error that the code has expired.

1. I request the code via `client.send_code_request(phone_number)`
2. I get the code automatically via official Telegram app (from the user "Telegram")
4. I see the code in the new message notification from the Telegram app
5. I type in the code in my custom app (on the same phone) within 10-15 seconds after receiving it
6. Error: PhoneCodeExpiredError

This applies to both, the test phone number provided in the Telegram API docs (eg +99966XYYYY - X being the test DC and YYYY being random numbers) as well as with my real phone number.

Providing an invalid code during signup results in the same error message: code expired (instead of invalid).

I assume that the time synchronisation between services should be correct. I use Firebase for backend & database, my custom app runs on the Apple app store. Tested it with both, actual backend as well as my backend script running locally (MacBook, date & time is set to automatically, should also be correct therefore).

A week ago this code has worked.

### Telethon version

1.33.1

### Python version

3.11.5

### Operating system (including distribution name and version)

macOS 14.0

### Other details

In the documentation, I read the part about codes automatically expiring if being sent through the app.
In my understanding, this means that when I receive the code from Telegram and then send it through the Telegram app to someone else, then it does expire. 
As I do not send it to anyone via Telegram (just receiving it there from the Telegram user / bot), I assume that this does not apply to me.

Potentially related issue: 
https://github.com/LonamiWebs/Telethon/issues/97

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
I appreciate the detailed report, but it's unlikely to be something that can be fixed in the library, so I'll be closing the issue.

Usual recommendation remains, try to simplify your workflow and see how much little code is needed to reproduce the problem. If you haven't updated, then it might be on Telegram's side. If you have, you can downgrade. If all fails, you can use https://tl.telethon.dev/ directly instead of relying on the (perhaps buggy) `client` methods.
