### ISSUE TITLE
Asynchronous TelegramClient.start() method

### ISSUE THREAD

**Issue by IlmirSharifullin** [LonamiWebs/Telethon#4272]
### Code that causes the issue

await self.client.start()

### Expected behavior

ok

### Actual behavior

Hint: Class 'TelegramClient' does not define '__await__', so the 'await' operator cannot be used on its instances. Works ok, just wrong hint
but when i remove 'await' from call it causes: RuntimeWarning: coroutine 'AuthMethods._start' was never awaited
  self.client.start()

### Telethon version

1.32.1

### Python version

3.10

### Operating system (including distribution name and version)

Ubuntu 22.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
There are no plans to fix this in v1. `start` is special-cased so that `await` is only needed while a loop is already running.
