### ISSUE TITLE
i have i problem i need to help 

### ISSUE THREAD

**Issue by rajred2** [LonamiWebs/Telethon#4274]
### Code that causes the issue

from telethon import TelegramClient
client = TelegramClient("session1", api_id='myid',
                        api_hash='myhash')

async def main():
    user = await client.get_me()

with client:
    client.loop.run_until_complete(main())

### Expected behavior

Server sent a very new message with ID 7312861028164375553, ignoring (see FAQ for details)
Server sent a very new message with ID 7312861028205957121, ignoring (see FAQ for details)

### Actual behavior

when i run my code i got this Result
 Server sent a very new message with ID 7312861028164375553, ignoring (see FAQ for details)
Server sent a very new message with ID 7312861028205957121, ignoring (see FAQ for details)

### Traceback

Server sent a very new message with ID 7312861028164375553, ignoring (see FAQ for details)
Server sent a very new message with ID 7312861028205957121, ignoring (see FAQ for details)

### Telethon version

1.33.1

### Python version

Python 3.9.2 

### Operating system (including distribution name and version)

Ubuntu

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This is not something that can be fixed. The FAQ explains why the error occurs.

**Comment by rajred2** [comment]
what is solve now ?

**Comment by rajred2** [comment]
> This is not something that can be fixed. The FAQ explains why the error occurs.


what is solve now ?
