### ISSUE TITLE
No event on user start/end typing

### ISSUE THREAD

**Issue by Rudzyansky** [LonamiWebs/Telethon#4280]
### Code that causes the issue

```python
import asyncio
import logging

from telethon import TelegramClient, events

import config

logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.INFO)
client = TelegramClient(session=config.SESSION_FILE, api_id=config.TG_API_ID, api_hash=config.TG_API_HASH)


@client.on(events.UserUpdate)
async def handler(event):
    logging.info(event)


async def main():
    await client.connect()
    await client.run_until_disconnected()


if __name__ == '__main__':
    asyncio.run(main())

```

### Expected behavior

Some event on user start and end typing and uploading logging

### Actual behavior

No event on user start and end typing and uploading
Only two events handles, with status UserStatusOnline and UserStatusOffline

### Telethon version

1.33.1

### Python version

3.10

### Operating system (including distribution name and version)

Windows 10

### Other details

https://docs.telethon.dev/en/stable/modules/events.html#telethon.events.userupdate.UserUpdate
> Occurs whenever a user goes online, starts typing, etc.

```python
@client.on(events.UserUpdate)
async def handler(event):
    # If someone is uploading, say something
    if event.uploading:
        await client.send_message(event.user_id, 'What are you sending?')
```

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Only events relating to messages are reliable. Anything else, Telegram is free to not bother sending, which is probably what is happening here, and therefore is not something that can be solvedin Telethon's side.

Perhaps being "active" in the chat (like sending messages) will let Telegram know you're looking at the chat and send them. I don't know. I haven't tested this.
