### ISSUE TITLE
Link preview is interpreted as photo

### ISSUE THREAD

**Issue by MrVolot** [LonamiWebs/Telethon#4283]
### Describe your suggested feature

It would be nice to have a functionality to distinguish between media attached and links preview. Currently, if there is a link in the text, the client will have a photo object in the message. So, the question is:

Is there a way to distinguish whether the photo is really attached or the photo just came from a link preview? If not, is there a plan to help to handle it within the client?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by MrVolot** [comment]
Just one notice, I can use event.message.media.webpage to verify if it is a preview or not. However, I am not sure if that is a good solution.

**Comment by Lonami** [comment]
This is intended and will stay this way in v1 as changing it would be a breaking change.
