### ISSUE TITLE
Facing Issues while adding members in Groups

### ISSUE THREAD

**Issue by DeepakDhaka201** [LonamiWebs/Telethon#4284]
### Describe your suggested feature

I am not able to add members to any group. It started giving Flood errors on the first time when adding 10 people at at time. 

Steps to reproduce :

1. Take any group which has more than 200 members.
2. Add 10 people using the InviteToChannelRequest method.

Error: 

A wait of 61 seconds is required (caused by InviteToChannelRequest)

Can someone help or tell me why suddenly it stopped working?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
