### ISSUE TITLE
WARNING:telethon.network.mtprotostate:Server sent a very old message with ID xxx, ignoring (see FAQ for details) 

### ISSUE THREAD

**Issue by vnvdev** [LonamiWebs/Telethon#4286]
### Describe your suggested feature

I created a bot that listens for new messages from any channel but I have a problem when there is a warning WARNING: telethon.network.mtprotostate:Server sent a very old message with ID 7319115934080661505, ignoring (see FAQ for details) WARNING:telethon.network.mtprotostate:Server sent a very old message with ID xxx, ignoring (see FAQ for details) WARNING:telethon.network.connection.connection:Server closed the connection: 0 bytes read on a total of 8 expected bytes . Then my program stops until I press Enter from the keyboard

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Unlikely to be solvable. FAQ contains our best understanding so far of the problem, as the error message mentions.
