### ISSUE TITLE
How telethon works with SafetyNet API

### ISSUE THREAD

**Issue by robertpustota** [LonamiWebs/Telethon#4287]
### Describe your suggested feature

i know that telegram require to use safetynet checks? How it implemented in the Telethon?
Is it a reason why sign up functionality was removed from telethon?
### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
No idea what SafetyNet, but it is definitely not implemented in Telethon.

Third party applications, such as those built using Telethon, are not allowed to sign up.
