### ISSUE TITLE
CHAT_MEMBER_ADD_FAILED

### ISSUE THREAD

**Issue by luigirovani** [LonamiWebs/Telethon#4288]
### Code that causes the issue

        try:
            client(channels.InviteToChannelRequest(channel, [user]))
        except errors.RPCError as e:
            print(e)
            
            
        

### Expected behavior

This method worked well last year and only produced the errors described in https://tl.telethon.dev/methods/channels/invite_to_channel.html, which I handled in my code.

### Actual behavior

 However, in the past week, it started raising "BadRequest" with the message "CHAT_MEMBER_ADD_FAILED" when calling the above method.

I couldn't find any error description in the telethon documentation or even in the Telethon API documentation. Therefore, I couldn't understand the cause of the problem. I suspected it might be server-side issues, but the code is 400. I also checked the issue on other machines.

### Traceback

  Stack para 5567991004200: RPCError 400: CHAT_MEMBER_ADD_FAILED (caused by InviteToChannelRequest)
Traceback (most recent call last):
  File "C:\Users\luigi\source\repos\Mathwtag\add.py", line 213, in add_user_to_channel
    client(channels.InviteToChannelRequest(channel, [user]))
  File "C:\Users\luigi\source\repos\Mathwtag\env\Lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\luigi\source\repos\Mathwtag\env\Lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luigi\source\repos\Mathwtag\env\Lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
             

### Telethon version

1.31.1

### Python version

3.11.7

### Operating system (including distribution name and version)

Windows 11 pro

### Other details

    I add this code in rpc_message_to_error for print result of request.
    
    def rpc_message_to_error(rpc_error, request):

    with open ('out.txt', 'a+', encoding='utf-8') as file:
        file.write('\n\n RPC_ERROR')
        print(rpc_error, file=file)
        file.write('\REQUEST')
        print(request, file=file)
        file.write('\n\n')

Result:

RPC_ERRORRpcError(error_code=400, error_message='CHAT_MEMBER_ADD_FAILED')
\REQUESTInviteToChannelRequest(channel=InputChannel(channel_id=1796819815, access_hash=2869353619099934389), users=[InputUser(user_id=1648929995, access_hash=3475610849918243816)])

 RPC_ERRORRpcError(error_code=400, error_message='CHAT_MEMBER_ADD_FAILED')
\REQUESTInviteToChannelRequest(channel=InputChannel(channel_id=1796819815, access_hash=2710632244450952695), users=[InputUser(user_id=5229365459, access_hash=-7234061377607831868)])

 RPC_ERRORRpcError(error_code=400, error_message='CHAT_MEMBER_ADD_FAILED')
\REQUESTInviteToChannelRequest(channel=InputChannel(channel_id=1796819815, access_hash=-7111540046512097518), users=[InputUser(user_id=1726943438, access_hash=-2176131795908830544)])

 RPC_ERRORRpcError(error_code=400, error_message='CHAT_MEMBER_ADD_FAILED')
\REQUESTInviteToChannelRequest(channel=InputChannel(channel_id=1796819815, access_hash=-419547088632870197), users=[InputUser(user_id=856015899, access_hash=-6822038612237579520)])

I couldn't find any error description in the telethon documentation or even in the Telethon API documentation

https://tl.telethon.dev/methods/channels/invite_to_channel.html
https://core.telegram.org/method/channels.inviteToChannel

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

**Comment by guivalerioS** [comment]
Hi guys, I'm also having this error, any idea what it could be?
or where can I find the description of this in the telegram api

**Comment by Saddys42** [comment]
Hey guys im also having the same problem, what could be the reason? It happens just with one group, with other groups works fine. Im not understanding this error. 
RPCError 400: CHAT_MEMBER_ADD_FAILED (caused by InviteToChannelRequest)

**Comment by valera123v** [comment]
hi guys, I also have this error when adding new users to the telegram chat. Any idea why this is happening and how to fix it?

**Comment by EightShift** [comment]
As far as I understand, this error is caused by telegram's restriction on inviting to a group/channel, due to abuse of this function. Restrictions are imposed specifically on the group/channel.

**Comment by EightShift** [comment]
As I understand it, this error is caused by telegram's restriction on inviting to a group/channel, due to abuse of this function. Restrictions are imposed specifically on the group/channel.
