### ISSUE TITLE
wrong pattern for channel name

### ISSUE THREAD

**Issue by dmitrdv** [LonamiWebs/Telethon#429]
Hi!

I have error "Unacceptable username. Must match r"[a-zA-Z][\\w\\d]{3,30}[a-zA-Z\\d]"" for following channels:
@muhammadjazira
@ummahnewsrus
@transurf
@UsuduSham
@kitabyahdi
@voyska_shama1
@trebuy_znaniya
@muhammad_takoy
@novostiIslamskoyummi
@Muhadjirin_val_ansar
@vdagestan
@fuckhumor

But that channels are exists in telegram. Could you please fix it?

Thank you

**Comment by Lonami** [comment]
Could you show your code?

**Comment by dmitrdv** [comment]
import telethon

telegram = telethon.TelegramClient('mysessionfile', 49631, 'fb050b8f6771e15bfda5df2409931569')
channel = telegram.get_entity('@muhammadjazira')

**Comment by Lonami** [comment]
The API should be returning `USERNAME_NOT_OCCUPIED` instead `USERNAME_INVALID`. The username is indeed valid, I don't know why this error is being raised.

Either way, neither of these usernames are in use, so the call will obviously not return anything.
