### ISSUE TITLE
Similar Channels

### ISSUE THREAD

**Issue by ali-moroukian** [LonamiWebs/Telethon#4290]
### Describe your suggested feature

Hi!

Please add an endpoint to get similar channels.

Thanks.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
There won't be a friendly method for this, but you can use raw API, as documented, to use any current and future method Telegram adds.

**Comment by ali-moroukian** [comment]
How could I find the raw API for this?

**Comment by Lonami** [comment]
This is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
