### ISSUE TITLE
Add new message receive finished parameter

### ISSUE THREAD

**Issue by yalunren** [LonamiWebs/Telethon#4291]
### Describe your suggested feature

I got new message from bot get cut off since the bot reply message in stream. The new message returns immediatly when the event is triggered and the message isn't show in full. Maybe can add a message finished receving tag, so I can know whether the message is finished.

current code

@client.on(events.NewMessage(from_users=bot_username))
async def handler(event):
       print("Received message:", event.message.text)

await client.run_until_disconnected()

for example:
the bot replies "It's been a good day. The weather is good and sunny. "

actual message get is
"It's been"

The rest message is still sending from bot and it is not receving.

maybe can add a parameter 

@client.on(events.NewMessage(from_users=bot_username, finish_tag=True))

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
There is no such thing as "message finished receving tag". A message is received entirely or not at all. If the bot is sending partial messages and then editing them, or sending continued messages, that's up to you to handle. Telethon cannot possibly know how arbitrary bots behave. But you know how bots you interact with behave.
