### ISSUE TITLE
Get/Set folders for dialogs

### ISSUE THREAD

**Issue by aryashivakumar** [LonamiWebs/Telethon#4292]
### Describe your suggested feature

this has still not been built out, need feature for getting and setting dialogfilters using telethon

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
v1 is feature frozen and v2 will be intentionally smaller in scope. v2 doesn't have a planned release date yet. So I will be closing this, because it's not something that's in my plans.

#1630 contains some code using the raw API.
