### ISSUE TITLE
sqlite3.OperationalError: duplicate column name: takeout_id

### ISSUE THREAD

**Issue by Tsyretorov** [LonamiWebs/Telethon#4293]
### Code that causes the issue

from telethon.sync import TelegramClient
from telethon import functions, types

import datetime
import time
import config

client = TelegramClient(config.phone, config.api_id, config.api_hash)
client.start()

usernames = set()
names_canals = ["@pbondareva"]
client.connect()

for i in names_canals:
    count = 0
    posts = client.get_messages(i, limit=2000)
    post_ids = [post.id for post in posts]

    for idd in post_ids:
        try:
            for message in client.iter_messages(i, reply_to=idd, reverse=True):
                if isinstance(message.sender, types.User):
                    print(message.sender)
                    if user.username not in usernames:
                        usernames.add(user.username)
                        print(user.username)

                        with open(f"test_{i}.txt", "a", encoding="utf-8") as f:
                            f.write(f"{count} - @{user.username}\n")

                        count += 1
                        # time.sleep(1)
                else:
                    print(f"Сообщение от канала или бота")

        except telethon.errors.rpcerrorlist.MsgIdInvalidError:
            print(f"ID сообщения {idd} недействителен, пропускаем...")
            continue

client.disconnect()

### Expected behavior

Hello, first of all, I want to say thank you very much for such a library, thanks to it I was able to place an order. But the customer asked me to parse the bio in the telegram and I came across this code https://github.com/ypankovych/telegram-bio-parser/blob/master/
I downloaded the libraries from it, but nothing worked, I decided to try asking myself, I deleted these libraries and returned to the working code, but this problem appeared, I reinstalled the libraries, but nothing worked

### Actual behavior

з

### Traceback

Traceback (most recent call last):
  File "/home/oem/Python/test/test.py", line 8, in <module>
    client = TelegramClient(config.phone, config.api_id, config.api_hash)
  File "/home/oem/.local/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 289, in __init__
    session = SQLiteSession(session)
  File "/home/oem/.local/lib/python3.10/site-packages/telethon/sessions/sqlite.py", line 55, in __init__
    self._upgrade_database(old=version)
  File "/home/oem/.local/lib/python3.10/site-packages/telethon/sessions/sqlite.py", line 147, in _upgrade_database
    c.execute("alter table sessions add column takeout_id integer")
sqlite3.OperationalError: duplicate column name: takeout_id

### Telethon version

1.33.1

### Python version

3.10

### Operating system (including distribution name and version)

Ubuntu 23.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You cannot use the session files created by recent Telethon versions in older Telethon versions. In other words, sessions are only forwards-compatible.

**Comment by Tsyretorov** [comment]
Name: Telethon
Version: 1.33.1
Summary: Full-featured Telegram client library for Python 3
Home-page: https://github.com/LonamiWebs/Telethon
Author: Lonami Exo
Author-email: totufals@hotmail.com
License: MIT
Location: /home/oem/.local/lib/python3.10/site-packages
Requires: pyaes, rsa
Required-by: 
oem@Poni:~/Python/test$ python3 test.py 
Traceback (most recent call last):
  File "/home/oem/Python/test/test.py", line 8, in <module>
    client = TelegramClient(config.phone, config.api_id, config.api_hash)
  File "/home/oem/.local/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 289, in __init__
    session = SQLiteSession(session)
  File "/home/oem/.local/lib/python3.10/site-packages/telethon/sessions/sqlite.py", line 55, in __init__
    self._upgrade_database(old=version)
  File "/home/oem/.local/lib/python3.10/site-packages/telethon/sessions/sqlite.py", line 147, in _upgrade_database
    c.execute("alter table sessions add column takeout_id integer")
sqlite3.OperationalError: duplicate column name: takeout_id

Thanks for the answer, I'm using the latest version.
I deleted the old version and re-downloaded the new library, but the problem remained.

**Comment by Lonami** [comment]
Make a new session. That one is broken.

**Comment by Tsyretorov** [comment]
ahaha that's exactly what I'm supposed to do, sorry for bothering you and thank you :)
