### ISSUE TITLE
Way to get access hashes for many channels (over 200)

### ISSUE THREAD

**Issue by i-s-m-mipt** [LonamiWebs/Telethon#4294]
### Describe your suggested feature

Are there any ways to obtain access hashes for many channels (approximately 10000), by using one account without FloodWaitError? I tried many ways, have found smth about official api for Telegram, but it seems unworkable. For me the next way is to use different account to resolve usernames from each, so I can resolve 1000 instead of 200 every day by using 5 accounts.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
No.
