### ISSUE TITLE
Support for one-time audio and video messages

### ISSUE THREAD

**Issue by ShnurD6** [LonamiWebs/Telethon#4297]
### Describe your suggested feature

Now when you try to receive the one-time audio or video message – you get MessageMediaUnsupported in media:
```
Message(id=1234, peer_id=PeerUser(user_id=12345), date=datetime.datetime(2024, 1, 16, 21, 39, 41, tzinfo=datetime.timezone.utc), message='', out=False, mentioned=False, media_unread=True, silent=False, post=False, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, noforwards=False, invert_media=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to=None, media=MessageMediaUnsupported(), reply_markup=None, entities=[], views=None, forwards=None, replies=None, edit_date=None, post_author=None, grouped_id=None, reactions=None, restriction_reason=[], ttl_period=None)
```
Please add support for these message types.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
This shouldn't be unsupported media in the latest versions.

**Comment by ShnurD6** [comment]
@Lonami 

Maybe I did something wrong, but I deleted the version from my pip and installed the latest version from github:
`pip3 uninstall Telethon; pip3 install git+https://github.com/LonamiWebs/Telethon`

Now one-time audio messages are recognized correctly (as MessageMediaDocument with voice=True and ttl_seconds), but one-time video messages are still recognized as MessageMediaUnsupported:

`Message(id=1234, peer_id=PeerUser(user_id=12345), date=datetime.datetime(2024, 1, 17, 15, 20, 27, tzinfo=datetime.timezone.utc), message='', out=False, mentioned=False, media_unread=True, silent=False, post=False, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, noforwards=False, invert_media=False, from_id=None, saved_peer_id=None, fwd_from=None, via_bot_id=None, reply_to=None, media=MessageMediaUnsupported(), reply_markup=None, entities=[], views=None, forwards=None, replies=None, edit_date=None, post_author=None, grouped_id=None, reactions=None, restriction_reason=[], ttl_period=None)`

**Comment by Lonami** [comment]
Not aware of Telegram restricting certain clients for certain media. As far as I'm aware the layer is what dictates what's available. That media may belong to an unreleased layer.

If the problem doesn't fix itself in newer layers, then maybe Telegram is restricting media types to third party clients after all.

**Comment by ShnurD6** [comment]
Today I updated Telethon to this commit - https://github.com/LonamiWebs/Telethon/commit/32a4cb82ce86117800f7e39f4525a785a00e8d21, and now it works! 
I also re-tested the previous commit that didn't work, and it really doesn't work until your update.
Thanks, everything is fine now)

**Comment by emilio-cea** [comment]
Is there a reason why installing telethon via a regular `pip install` still shows MessageMediaUnsupported but installing the git version does not?

I see both methods install Telethon version 1.33.1

**Comment by Lonami** [comment]
A new version with the latest layer hasn't been pushed to PyPi. I don't update the version from Git until I have to make a new release.
