### ISSUE TITLE
Hi, Can you tell me how to build telethon_generator/data/api.tl 

### ISSUE THREAD

**Issue by xspeed1989** [LonamiWebs/Telethon#4298]
### Describe your suggested feature

Hi, Can you tell me how to build telethon_generator/data/api.tl , I means make layer xxx => layer170

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
The types are built when you install the library when `pip` and the `setup.py` file runs. Make your changes and install the local source (or use `python setup.py gen` for development).

**Comment by xspeed1989** [comment]
> The types are built when you install the library when `pip` and the `setup.py` file runs. Make your changes and install the local source (or use `python setup.py gen` for development).

There is something wrong with my word. What I mean is how to get the latest scheme  and write it into a tl file.

**Comment by Lonami** [comment]
You have to find the `.tl` file in a different project that is up to date, such as tdesktop, and copy it over to Telethon's `api.tl` file.

**Comment by xspeed1989** [comment]
thanks

Lonami ***@***.***> 于2024年1月19日周五 09:36写道：
