### ISSUE TITLE
[Q] How to add user to supergroup with userid

### ISSUE THREAD

**Issue by Fogia4** [LonamiWebs/Telethon#43]
Hello,

I want to add user(s) to existing supergroup that I created(have admin privileges).
How can I add user with resolved userid into supergroup?

First I tried AddChatUserRequest but failed. According to #38, supergroup was treated as channel. So I did not try AddChatUserRequest API, will be 400 CHAT_ID_INVALID.

Next I tried InviteToChannelRequest but does not work for supergroup.
(Case1) add user to supergroup by InviteToChannelRequest API(fail, server returns 400 PEER_FLOOD)
(Case2) add user to channel by InviteToChannelRequest API(Succeeded)

Is it right way to use InviteToChannelRequest to add user to supergroup? Or any invalid parameter?
Added code to client "telegram_client.py":

`
    def add_user(self,
        user_id, # by SearchRequest, int ex. 230000000
        user_access_hash, # by SearchRequest, long ex. 2000000000000000000
        entity): # by get_dialogs

    if 'telethon.tl.types.chat.Chat' in str(type(entity)):
        print("chat")
        return
    print(entity)
    print()

    chat_id = entity.id  # ex. id=1113800000
    #inuser = InputPeerUser(user_id, user_access_hash)
    inuser = InputUser(user_id, user_access_hash)
    chan = InputChannel(chat_id, entity.access_hash)

    if hasattr(entity, "megagroup") and entity.megagroup: # debug code
        # (Case1) not work(400 PEER_FLOOD)
        print("Here is supporsed to be supergroup!")
    try:
        print("InviteToChannelRequest:")
        result = self.invoke(InviteToChannelRequest(chan, [inuser]))
        print(result)
    except RPCError as err:
        print("telethon.errors.RPCError Detected: {0}".format(err))`

**Comment by Fogia4** [comment]
`def add_user(self,
user_id, # by SearchRequest, int ex. 230000000
user_access_hash, # by SearchRequest, long ex. 2000000000000000000
entity): # by get_dialogs

    if 'telethon.tl.types.chat.Chat' in str(type(entity)):
        print("chat")
        return
    print(entity)
    print()

    chat_id = entity.id  # ex. id=1113800000
    #inuser = InputPeerUser(user_id, user_access_hash)
    inuser = InputUser(user_id, user_access_hash)
    chan = InputChannel(chat_id, entity.access_hash)

    if hasattr(entity, "megagroup") and entity.megagroup: # debug code
        # (Case1) not work(400 PEER_FLOOD)
        print("Here is supporsed to be supergroup!")
    try:
        print("InviteToChannelRequest:")
        result = self.invoke(InviteToChannelRequest(chan, [inuser]))
        print(result)
    except RPCError as err:
        print("telethon.errors.RPCError Detected: {0}".format(err))`

**Comment by Lonami** [comment]
Have you checked #29 out? I would say supergroups are treated as channels.

**Comment by Fogia4** [comment]
Hi @Lonami , thanks for your quick reply.
I checked #29 but I've already joined to the supergroup and want to invite the other user to the supergroup by API.

**Comment by Lonami** [comment]
You mentioned you had a `PEER_FLOOD` error. I wonder if this is similar to [vysheng's tg, issue 886](https://github.com/vysheng/tg/issues/886). Have you been spamming with that API key?

**Comment by Lonami** [comment]
Please check this link: https://www.telegram.org/faq_spam. Quote:
> Limited accounts can send messages to people who have their number saved as a **contact**. You can also always **reply** to anyone who messages you first.

Can you add people manually, without using Telethon (e.g. official clients)? Or does this only happen with Telethon?

**Comment by Fogia4** [comment]
> You mentioned you had a PEER_FLOOD error. I wonder if this is similar to vysheng's tg, issue 886. Have you been spamming with that API key?
I understood. @SpamBot told me that I was limited.
Thanks!
