### ISSUE TITLE
html parse_mode ruins formatting with code snippets

### ISSUE THREAD

**Issue by MrVolot** [LonamiWebs/Telethon#4302]
### Code that causes the issue

Any simple application with parse_mode set to html

### Expected behavior

I have a simple message which contains a bit of text and code. When you take a look on `text` property with parse_mode="HTML", you get:

```
"Hello:\n<pre>\n    <code class='language-javascript'>\n        var result = (function() {\n  return 5 + 3;\n})();{}\n    </code>\n</pre>"
```

I do not get where does those extra characters, tabs, empty spaces are coming from. Here is the example message to reproduce:

Hello:
```
var result = (function() {
  return 5 + 3;
})();
```

### Actual behavior

Here is what you get as a result, shown in telegram:

Hello:
```
    
        var result = (function() {
  return 5 + 3;
})();{}
```

### Telethon version

1.33.1

### Python version

3.11.7

### Operating system (including distribution name and version)

Windows11, Ubuntu 20.04.6

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Changing this in v1 would be a breaking change. You need to trim the whitespace after the `<pre>` tag yourself, as Telethon is simply keeping whatever characters are there.
