### ISSUE TITLE
Message history can't fetch message text when it contains newly added Quote Formatting feature

### ISSUE THREAD

**Issue by knwlim** [LonamiWebs/Telethon#4303]
### Code that causes the issue

GetHistoryRequest() can't get the whole message when the message uses the new feature "Quote Foramtting"

https://9to5google.com/2023/10/30/telegram-quote-update/

### Expected behavior

the message in text format inside the Message object

### Actual behavior

it's empty like message=''

### Telethon version

1.33.1

### Python version

3.10

### Operating system (including distribution name and version)

macOS 14.3

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This will work in future versions with a higher layer number.
