### ISSUE TITLE
InviteToChannelRequest: The method you tried to invoke cannot be executed as a bot

### ISSUE THREAD

**Issue by nikky78** [LonamiWebs/Telethon#4307]
### Description

As per the documentation, I am using the InviteToChannelRequest method as follow:
response = await client(InviteToChannelRequest(channel=channel, users=[user])) # For channels
I always get the error: BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot 

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
The documentation correctly says:

> Only users can use this request
