### ISSUE TITLE
Unable to register absolutely new account

### ISSUE THREAD

**Issue by User195** [LonamiWebs/Telethon#431]
Previously, I used the telethon library with my own api_id, api_hash (I got it, as stated in the official manual https://core.telegram.org/api/obtaining_api_id). And everything works fine. But now I want to create a absolutely new telegram account. I have a simple phone (not a smartphone) and I wanted to create a new account with a new phone number and api_id, api_hash from the previous account. But when I run my script, the sms code does not come. Is there a restriction on the side of the telegram?

```
api_id = id from another account
api_hash = 'hash from another account'
my_phone_number = '+phone number of my simple device'
client = TelegramClient('sasahah_h', api_id, api_hash)
print("Connect status: " + str(client.connect()))
client.sign_in(phone=my_phone_number)
```

**Comment by Lonami** [comment]
You don't want to `.sign_in`, you want to `.sign_up`.

**Comment by Lonami** [comment]
As a matter of style, this:
```python
print("Connect status: " + str(client.connect()))
```

Is equivalent to:
```python
print("Connect status:", client.connect())
```
