### ISSUE TITLE
Add a function to serialise and deserialise a message object

### ISSUE THREAD

**Issue by FreeM1ne** [LonamiWebs/Telethon#4312]
### Describe your suggested feature

Add a function to serialise and deserialise a message object
Pickle and dill not work

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Messages and any other raw type can already be serialized with `bytes(message)` and read with:
```python
from telethon.extensions import BinaryReader
BinaryReader(serialized_bytes).tgread_object()
```
However, this often won't work across layer updates of the library (but neither would `pickle`).
