### ISSUE TITLE
Add the ability to use list chat_ids in iter_messages

### ISSUE THREAD

**Issue by FreeM1ne** [LonamiWebs/Telethon#4313]
### Describe your suggested feature

Add the ability to use list chat_ids in iter_messages
`client.iter_messages(entity=[-123, -505, 777000])`

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
The code is messy as it is and the API doesn't support it. Furthermore, I'd prefer to keep new features to v1 to a minimum, preferably zero. And v2 will intentionally be smaller in scope.

**Comment by FreeM1ne** [comment]
Is this the documentation for the second version? https://tl.telethon.dev

**Comment by Lonami** [comment]
No, that's the raw API reference for all raw methods available in v1.

**Comment by FreeM1ne** [comment]
When approximately will the second version be out?

**Comment by Lonami** [comment]
I don't know. I don't have much free time left, and the time I have, I don't have much motivation to continue. So it could be weeks. Months. Or years.
