### ISSUE TITLE
File/Media/Document download speed is capped at 1MB/s even in my premium account

### ISSUE THREAD

**Issue by SSM-04** [LonamiWebs/Telethon#4315]
### Describe your suggested feature

i wrote a very simple programme to download files from a chat(channel/group/user) and it works fine but the speed it is downloading the files with is capped at 1 MB/s or 8 mbps; i have cryptg installed as said in the documentation.
It would be very helpful if someone replied on how to solve this.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by FreeM1ne** [comment]
Absolutely the same problem, wanted to create a topic too
0.5MB/s

**Comment by Lonami** [comment]
Telethon downloads file parts sequentially, not concurrently, and I don't plan to change this in the near future.

**Comment by FreeM1ne** [comment]
solution
pip install cryptg

**Comment by FreeM1ne** [comment]
> Telethon downloads file parts sequentially, not concurrently, and I don't plan to change this in the near future.

Add somewhere the information about cryptg the difference in speed 7 times gets

**Comment by GodFatherClover** [comment]
> solution pip install cryptg

my windows 11 had install cryptg , but download speed is max 250kb/s
