### ISSUE TITLE
Getting an empty message text on NewMessage

### ISSUE THREAD

**Issue by AlexShnap** [LonamiWebs/Telethon#4316]
### Code that causes the issue

```@client.on(events.NewMessage(chats=([-1002054145525])))
async def post_handler(event):
    print("a", event.raw_text)
```

### Expected behavior

a hello

### Actual behavior

a

### Telethon version

1.34.0

### Python version

3.10.10

### Operating system (including distribution name and version)

Windows 10

### Other details

Everything worked fine, but two days ago it broke

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by FreeM1ne** [comment]
try message.message
