### ISSUE TITLE
Fetching a Boost message returns an unsupported kind of media

### ISSUE THREAD

**Issue by emilio-cea** [LonamiWebs/Telethon#4317]
### Code that causes the issue

```py
client.get_messages(
        entity,
        ids=[12345]
    )
```

### Expected behavior

request a message that contains a boost link and have a Media type.

### Actual behavior

The message contains text but no media.

### Telethon version

1.34.0

### Python version

3.7.3

### Operating system (including distribution name and version)

Debian 4.19.260-1

### Other details

I tried installing Telethon using pip and form git as well as using the `v1.zip` package and the result was the same in every case.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This will be fixed when a new layer is released and Telethon switches to it. I can't "add" it until then.
