### ISSUE TITLE
All sessions gets deauthenticated when using system_lang_code = "ru"

### ISSUE THREAD

**Issue by loggedou** [LonamiWebs/Telethon#4320]
### Code that causes the issue

```python
client = TelegramClient(
            StringSession(),
            api_id,
            api_hash,
            lang_code="ru",
            system_lang_code="ru",
            proxy={
                "proxy_type": "socks5",
                "addr": proxy_addr,
                "port": proxy_port,
                "username": proxy_username,
                "password": proxy_password,
                "rdns": True,
            },
        )
```

### Expected behavior

Sessions should not be deauthenticated

### Actual behavior

Account immediately gets deauthenticated after using logging using custom system_lang_code parameter

### Telethon version

1.33.1

### Python version

3.11.4

### Operating system (including distribution name and version)

macOS / Windows 10

### Other details

Everything works as expected when using default system_lang_code parameter

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Nothing Telethon can do about this, except silently changing it to 'en' or throwing an error itself.
