### ISSUE TITLE
We need to fix the download speed

### ISSUE THREAD

**Issue by FreeM1ne** [LonamiWebs/Telethon#4323]
### Code that causes the issue

With telegram premium download speed 1-2 megabytes per second, look at the code in pyrogram everything is downloaded there without problems

### Expected behavior

With telegram premium download speed 1-2 megabytes per second, look at the code in pyrogram everything is downloaded there without problems

### Actual behavior

With telegram premium download speed 1-2 megabytes per second, look at the code in pyrogram everything is downloaded there without problems

### Telethon version

last

### Python version

3.11.5

### Operating system (including distribution name and version)

Windows11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by FreeM1ne** [comment]
cryptg installed

**Comment by FreeM1ne** [comment]
try tgcrypto lib

**Comment by FreeM1ne** [comment]
![image](https://github.com/LonamiWebs/Telethon/assets/83845767/9534e9d9-312d-446b-aed8-e8deae261f94)

**Comment by Lonami** [comment]
I don't have any interest in further complicating the code to download files. So I will be closing this issue.

Increasing the download speed will lead to flood waits if one attempts to download many files, which is the actual limiting factor anyway.

You're free to improve the way Telethon makes requests to download file parts or [use alternatives](https://gist.github.com/painor/7e74de80ae0c819d3e9abcf9989a8dd6).

**Comment by FreeM1ne** [comment]
I want to download one file in one thread, multi download in telegram is a fake, even in the main client files are downloaded one by one

**Comment by FreeM1ne** [comment]
Fast telethon broke your library and it's not clear how it did it.

**Comment by FreeM1ne** [comment]
I decided to check your parallel downloading of multiple files yesterday, since that's your excuse. The download speed of three files just divided by three if I was downloading a single file

**Comment by FreeM1ne** [comment]
And I don't understand why you don't want to address this issue if downloading and uploading files is one of the most important things in telegram

**Comment by Lonami** [comment]
> I don't understand why you don't want to address this issue

I've answered this before. I personally don't have any interest in further complicating the code to download files.

Code in the library is code I feel obliged to maintain. And I do not want to maintain v1 anymore. Doing so is not fun.

> downloading and uploading files is one of the most important things in telegram

This is an absolute statement that I don't agree applies to everyone. It definitely doesn't apply to me.

Since you can download 3 files at once, you should also be able to read the source code and do the same with 3 file *parts* of a single file instead, to get the speed increase you want.

**Comment by FreeM1ne** [comment]
Version 2 doesn't have this problem?

The problem is that the download speed does not increase with the division into parts

**Comment by FreeM1ne** [comment]
?

**Comment by FreeM1ne** [comment]
You changed something, my downloads are even slower than before?

**Comment by Lonami** [comment]
I haven't changed anything related to downloads. The commit history is public and you can verify it yourself.

Given that the conversation does not seem to be going anywhere and I've already explained my stance I will be locking the issue.
