### ISSUE TITLE
The teleram client asks for a phone number although we pass it in a variable

### ISSUE THREAD

**Issue by Meirzhan06** [LonamiWebs/Telethon#4325]
### Code that causes the issue

from telethon import TelegramClient
import asyncio

async def main():
    api_id = xxxxxxxx
    api_hash = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    phone_number = '+7778xxxxxxx'  # Замените на свой номер телефона

    client = TelegramClient(phone_number, api_id, api_hash)

    await client.start()
    if not await client.is_user_authorized():
        await client.send_code_request(phone_number)
        # Введите код, который вы получили по SMS
        await client.sign_in(phone_number, input('Введите код: '))

# Запуск основной функции
asyncio.run(main())

### Expected behavior

I expected that we would be able to pass the phone number in a variable and use it in the telegram client

### Actual behavior

We expected her to use the phone number from the variable and insert

### Telethon version

1.34.0

### Python version

3.12

### Operating system (including distribution name and version)

windows 10

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
`start` has always asked for phone number if not logged in. `connect` is the one that just connects.

**Comment by Meirzhan06** [comment]
The documentation says that this can be done
