### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by vvs001** [LonamiWebs/Telethon#4330]
### Code that causes the issue

Request SendMediaRequest(peer=InputPeerChannel(channel_id=1631823122, access_hash=-4947882237054159141), media=InputMediaUploadedPhoto(file=InputFile(id=1807271934250501861, parts=1, name='1.jpg', md5_checksum='5d39160af57ae46f1cf01cbfb8c12869'), stickers=[], ttl_seconds=None), message=
silent=None, background=None, clear_draft=False, reply_to_msg_id=None, random_id=6142636474183281450, reply_markup=None, entities=[], schedule_date=None) had missing message mapping Updates(updates=[UpdateReadChannelInbox(channel_id=1631823122, max_id=4742020, still_unread_count=0, pts=8501666, folder_id=1), UpdateNewChannelMessage(message=MessageEmpty(id=4742020, peer_id=PeerChannel(channel_id=1631823122)), pts=8501666, pts_count=0)], users=[], chats=[Channel(id=1631823122, title='천상계 [天上界] 구인구직 홍보방', photo=ChatPhoto(photo_id=5998997624138612976, dc_id=4, has_video=False, stripped_thumb=b"\x01\x08\x08\xbd\xbf\xe5'\x03w\xb7Z(\xa2\x95\xc0"), date=datetime.datetime(2024, 3, 16, 14, 34, 26, tzinfo=datetime.timezone.utc), creator=False, left=False, broadcast=False, verified=False, megagroup=True, restricted=False, signatures=False, min=False, scam=False, has_link=True, has_geo=False, slowmode_enabled=False, call_active=True, call_not_empty=False, fake=False, gigagroup=False, access_hash=-4947882237054159141, username='CSGGIGJHBB', restriction_reason=[], admin_rights=None, banned_rights=None, default_banned_rights=ChatBannedRights(until_date=datetime.datetime(2038, 1, 19, 3, 14, 7, tzinfo=datetime.timezone.utc), view_messages=False, send_messages=False, send_media=False, send_stickers=False, send_gifs=False, send_games=False, send_inline=False, embed_links=False, send_polls=True, change_info=True, invite_users=False, pin_messages=True), participants_count=None)], date=datetime.datetime(2024, 3, 18, 6, 46, 35, tzinfo=datetime.timezone.utc), seq=0)

### Expected behavior

1

### Actual behavior

1

### Telethon version

1

### Python version

1

### Operating system (including distribution name and version)

1

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This issue is not actionable.
