### ISSUE TITLE
Can't install v2 through documentation command

### ISSUE THREAD

**Issue by Drebedenb** [LonamiWebs/Telethon#4333]
### Description

Hello, I wanted to update to version 2.0, but I get an error that this version is not in pip. Code from docs:

`python -m pip install --upgrade "telethon~=2.0"`

The error:

`ERROR: Could not find a version that satisfies the requirement telethon~=2.0 (from versions: ...`

I updated pip and Python, but the error persisted.

`Python 3.12.2`
`pip 24.0`

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
v2 has not been released to PyPi. Both the library and documentation are still a work-in-progress.

After it has been released, the command will work.
