### ISSUE TITLE
Convert Telegram web auth keys to sssion file

### ISSUE THREAD

**Issue by vhdm** [LonamiWebs/Telethon#4334]
### Describe your suggested feature

Hi @Lonami , is it possible to convert logged in web telegram auth keys (local storage) to session file and use it in teleton?

<img width="995" alt="Screenshot 2024-03-26 at 11 57 20 PM" src="https://github.com/LonamiWebs/Telethon/assets/14149777/75e0963c-372f-4d01-97ca-309a96729719">

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
You can certainly do it, as the code is open source and freely available. I have no plans to make this feature built-in though. There is enough spam as is.

My suggestion is to just login again, which one should be able to do in legitimate cases.
