### ISSUE TITLE
How can I know if an event is protected?

### ISSUE THREAD

**Issue by development-soft** [LonamiWebs/Telethon#4337]
### Description

How can I know in advance that a message is protected? What methods or properties are there for this?

```
@client.on(events.NewMessage)
async def my_event_handler(event):
    if event.is_protected: # ????
        print("ok") 
```

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
I do not know what that is. But you can `print(event.message.stringify())` to see everything in the message, and find the difference between protected media and not.
