### ISSUE TITLE
Telethon cannot handle message sent by itself

### ISSUE THREAD

**Issue by Ivanlon30000** [LonamiWebs/Telethon#4340]
### Code that causes the issue

There are two Message Handlers, `download` and `search`. The former listens to messages with Media sent to Saved Message; and when I send 'search xxx' to Saved Message, the latter listens to the message, performs a global search, and then forwards messages with media to Saved Message.

When I manually send the file to Saved Message, the download works fine. But I found that the message forwarded to Saved Message in `search` does not trigger `download`. 
I don't know if this is a bug or a feature, or there's something wrong with my code.

```python
@client.on(
    telethon.events.NewMessage(
        func=lambda event: isinstance(event.media, MessageMediaDocument), chats=my_id
    )
)
async def download(event):
    """This handler download any Media in the Message sent to 'Saved Message'"""
    print(f"[Download] New message with media: {get_media_name(event.media)}")
    await event.reply(f"Start downloading")

    # download or do something else ...


@client.on(telethon.events.NewMessage(pattern=r"search (\w+)", chats=my_id))
async def search(event):
    """When I send 'search xxx', do a global search; then send/forward
    message with Media to 'Saved Message'"""
    keyword = event.pattern_match.group(1)
    async for message in client.iter_messages(
        None, limit=3, search=keyword, filter=InputMessagesFilterDocument
    ):
        print(
            f"[Search] Send message {message.id} with media {get_media_name(message.media)}"
        )
        await client.send_message(my_id, message)


if __name__ == "__main__":
    client.run_until_disconnected()
```

### Expected behavior

Assume that a global search using keyword 'sample' can search for 3 messages with Media named 'sampleA.zip', 'sampleB.zip' and 'sampleC.zip'.
After I send command 'search sample' to Saved Message, I expect the following output from the console:
```
[Search] Send message 280 with media sampleA.zip
[Download] New message with media: sampleA.zip
[Search] Send message 299 with media sampleB.zip
[Download] New message with media: sampleB.zip
[Search] Send message 301 with media sampleC.zip
[Download] New message with media: sampleC.zip
```

### Actual behavior

... but I got:
```
[Search] Send message 280 with media sampleA.zip
[Search] Send message 299 with media sampleB.zip
[Search] Send message 301 with media sampleC.zip
```
It means that messages sent by `search` handler are not handled by `download`.

### Telethon version

1.34.0

### Python version

3.11.7

### Operating system (including distribution name and version)

Windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Changing this in v1 would be a breaking change.

This should already work in v2, but when that will be published I don't know.

**Comment by Ivanlon30000** [comment]
> Changing this in v1 would be a breaking change.
> 
> This should already work in v2, but when that will be published I don't know.

Well. I wonder if there is any temporary solution

**Comment by Lonami** [comment]
Handlers are normal functions. You can call them directly. Or you can extract common logic elsewhere and reuse that.
