### ISSUE TITLE
Files are so slow to download that File_Reference is running out of time

### ISSUE THREAD

**Issue by FreeM1ne** [LonamiWebs/Telethon#4341]
### Code that causes the issue

telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest

### Expected behavior

telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest

### Actual behavior

telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest

### Traceback

telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest

### Telethon version

last

### Python version

3.11.5

### Operating system (including distribution name and version)

Windows 10

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by FreeM1ne** [comment]
download speed does not exceed 0.3mb

**Comment by FreeM1ne** [comment]
I think we should add a "workers" parameter to specify the number of workers to download the file.

**Comment by Lonami** [comment]
I don't have plans to complicate the download code further. Not in v1.

However, the above should refetch the message, if you're using `message.download_media` to download the file.

**Comment by FreeM1ne** [comment]
Yeah, I'm using message.download_media
but the error still appears

**Comment by Lonami** [comment]
The above commit has not been released yet, though you could try `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and see if it helped at all.

**Comment by FreeM1ne** [comment]
Either way it's very slow, also, on importance I rate it 8/10
Telegram wouldn't be telegram if it didn't have files, it's not just chatting.
