### ISSUE TITLE
List of channels and groups?

### ISSUE THREAD

**Issue by matrix6inc** [LonamiWebs/Telethon#4343]
### Describe your suggested feature

I'm trying to build a comprehensive list of all public channels and groups. Does Telethon support this?

Any suggestions on how to implement such a thing?

Thanks!

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
