### ISSUE TITLE
[v2] Pyproject.toml minimum Python version is too low

### ISSUE THREAD

**Issue by nemec** [LonamiWebs/Telethon#4348]
### Describe your suggested feature

So it looks like `typing.Self` ([used here](https://github.com/LonamiWebs/Telethon/blob/v2/generator/src/telethon_generator/_impl/tl_parser/tl/definition.py#L2)) is added in Python 3.11 but your [current pyproject.toml](https://github.com/LonamiWebs/Telethon/blob/v2/client/pyproject.toml) in the V2 branch specifies Python 3.8 as the minimum version. I was able to successfully install after installing Python 3.11 in a venv. Not a huge issue, but before you release 2.0 you'll probably want to bump this version in pyproject.toml

https://docs.python.org/3/library/typing.html#typing.Self

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Jahongir-Qurbonov** [comment]
This issue is resolved in #4481

**Comment by nemec** [comment]
Thank you!
