### ISSUE TITLE
 Could not find the input entity

### ISSUE THREAD

**Issue by miguel-hub1** [LonamiWebs/Telethon#4349]
### Description

Sometimes I will not be able to use the function:
clienteTelegram.get_entity(idChat)
I get the following error, I always use the same group ID but sometimes it works and sometimes it doesn't is it a bug or what  can I do?
ValueError: Could not find the input entity for <specific entity>. Please read https://telethon.readthedocs.io/en/latest/extra/basic/entities.html to find out more details.

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
The problem is documented in the link from the error. There is nothing in the documentation to fix.

**Comment by miguel-hub1** [comment]
The documentation link gives the following error:
404 Not Found

You are browsing the documentation of telethon. The documentation page you are looking for was not found.

**Comment by miguel-hub1** [comment]
Also the problem happens to be in MacOS, because the same code I have implemented works windows but it doesn't work on Mac.

**Comment by Lonami** [comment]
My bad, I hadn't clicked the link.

In any case, the current URL is correct:
https://github.com/LonamiWebs/Telethon/blob/d3a201a277fd98bcea47f92269b907ba9607b2d1/telethon/client/users.py#L470

so you're most likely using a (very) old version of Telethon.

As the page explains, if the entity is not in cache, it won't work.
