### ISSUE TITLE
I am here to report to using alfem/telegram-download-daemon with api_id 611335 then my account got banned.

### ISSUE THREAD

**Issue by ghost** [LonamiWebs/Telethon#4358]
### Code that causes the issue

None.

### Expected behavior

Not banned.

### Actual behavior

Got banned.

### Traceback

None.

### Telethon version

1.34.0

### Python version

3.11.6

### Operating system (including distribution name and version)

Arch Linux

### Other details

Anybody beware, don't use api_id 611335 again.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
#824.
