### ISSUE TITLE
Telethon have any support for private channels?

### ISSUE THREAD

**Issue by sabloger** [LonamiWebs/Telethon#436]
I want to create a private channel and add member (admin) in runtime, But `InviteToChannelRequest` or `JoinChannelRequest` or `AddChatUserRequest` doesn't work and raises exceptions like these:

```
telethon.errors.rpc_error_list.ChannelInvalidError:
(ChannelInvalidError(...), 'Invalid channel object. Make sure to pass the right types,
for instance making sure that the request is designed for channels
or otherwise look for a different one more suited')
```
and
```
telethon.errors.rpc_error_list.UserIdInvalidError:
(UserIdInvalidError(...), 'Invalid object ID for an user. Make sure to pass the right types,
for instance making sure that the request is designed for users
or otherwise look for a different one more suited')
```
or
```
telethon.errors.rpc_error_list.ChatIdInvalidError:
(ChatIdInvalidError(...), 'Invalid object ID for a chat. Make sure to pass the right types,
for instance making sure that the request is designed for chats (not channels/megagroups)
or otherwise look for a different one more suited\nAn example working with a megagroup and AddChatUserRequest, it will fail because megagroups are channels. Use InviteToChannelRequest instead')
```

What should i do?

I was searched and tried so far but didn't find any way to do what i want.

**Comment by Lonami** [comment]
Show your code.

**Comment by sabloger** [comment]
`owner_channel = owner_client.get_entity(PeerChannel(channel_id))
 inv = owner_client(InviteToChannelRequest(channel=owner_channel, users=[client.get_me()]))

client(JoinChannelRequest(channel=InputChannel(channel_id=channel_id, access_hash=inv.chats[0].access_hash)))`
or
`            owner_channel = owner_client.get_entity(PeerChannel(channel_id))
            inv = owner_client(InviteToChannelRequest(channel=owner_channel, users=[client.get_me()]))
            j = client(JoinChannelRequest(channel=owner_channel))`

**Comment by Lonami** [comment]
I don't feel like reading that right now but yes, the library does support private channels. The library supports *everything* official clients do (I've said this many times). As the error say look for more suited requests.

**Comment by sabloger** [comment]
Sorry the styling was corrupted on that comment.
Please tell me a simple example for this flow, Only add a member to a private channel.
Thanks.

**Comment by Lonami** [comment]
The issues section is not for support though, it's for actual issues about the library itself and not wrong usage.

**Comment by Lonami** [comment]
Anyway procedure is the same as #103.
