### ISSUE TITLE
Introduce placeholder text support for Button.text alongside buttons

### ISSUE THREAD

**Issue by chaosrun** [LonamiWebs/Telethon#4360]
### Describe your suggested feature

In the current implementation of Telethon, the `force_reply` supports setting a placeholder text, but it cannot be used simultaneously with buttons.

The Telegram Bot API and the TL-schema do support `replyKeyboardMarkup` with a custom placeholder text that can coexist with buttons in a single message, as documented here: https://core.telegram.org/constructor/replyKeyboardMarkup

An example of this functionality is showcased in the screenshot below where both the buttons and a custom placeholder are present in the same message layout:

![example](https://github.com/LonamiWebs/Telethon/assets/34976476/52419620-9057-4710-91ae-b9f36c11c4f8)

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
As with https://github.com/LonamiWebs/Telethon/issues/4359#issuecomment-2072562948, no new features are planned for v1.

It should be possible with raw API though.
