### ISSUE TITLE
Request for forward_messages function update, specifying chat_id and message_thread_id

### ISSUE THREAD

**Issue by BookMat** [LonamiWebs/Telethon#4364]
### Describe your suggested feature

HI,
the "forward_messages" function does not support native forwarding to a chat_id and message_thread_id, as normally happens for the "send_message" function, perhaps at the time the function was written it was not accepted by the Telegram API, but here it seems to be https:// core.telegram.org/bots/api#forwardmessage.

Is it possible to add native forwarding capability to a message_thread_id?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Supporting topics here is not planned for v1 but you can use https://tl.telethon.dev/methods/messages/forward_messages.html directly.
