### ISSUE TITLE
Wrong Message type in MessageMethods.send_message()

### ISSUE THREAD

**Issue by pirog-x** [LonamiWebs/Telethon#4365]
### Description

I'm slightly confused by reading the docs and the source code. In `telethon.client.messages.py` in class `MessageMethods` in method: `send_message` you provide the `message` parameter of  type: `hints.MessageLike`, which is:
```python
# file: telethon.hints.py
from .tl import types, custom
...
MessageLike = typing.Union[str, types.Message]
```

```python
# file: telethon.client.messages.py
    async def send_message(
            self: 'TelegramClient',
            entity: 'hints.EntityLike',
            message: 'hints.MessageLike' = '',
            ...
    ) -> 'types. Message':

```

But in the documentation, you've set another type of message: `telethon.tl.custom.message.Message`
[docs link](https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.messages.MessageMethods.send_message)

```python
"""
...
            message (`str` | `Message <telethon.tl.custom.message.Message>`):
                The message to be sent, or another message object to resend.

                The maximum length for a message is 35,000 bytes or 4,096
                characters. Longer messages will not be sliced automatically,
                and you should slice them manually if the text to send is
                longer than said length.
...
"""
```

Maybe I missed something? Or do I understand something differently?

### Checklist

- [x] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
There's some weird monkey patching of the `types.Message`. It's a mess and I'm not all that interested in fixing it in v1.

https://github.com/LonamiWebs/Telethon/blob/47673680f4f615aac15d7e8c1886abea2fe40d9e/telethon/tl/patched/__init__.py#L1-L20

**Comment by pirog-x** [comment]
Do you want to fix it in the V2? Or already fixed in V2?

PS: I just want to know, which version of the library I should use.

**Comment by Lonami** [comment]
v2 won't have this hack so you could say it's fixed, yes.

v2 is not ready for use yet and I don't know when it will be. So v1 is the only supported stable version at the moment.
