### ISSUE TITLE
Сan I change the documentation theme to furo?

### ISSUE THREAD

**Issue by chirizxc** [LonamiWebs/Telethon#4367]
### Description

Furo theme looks more fresh and has both dark and white theme?
![image](https://github.com/LonamiWebs/Telethon/assets/109767616/25189820-e478-4178-b331-65cac0ae7255)
![image](https://github.com/LonamiWebs/Telethon/assets/109767616/2d03c14f-95f3-4e24-917c-d2f16cdba562)

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
I like the current one and don't have plans to change it at the moment.
