### ISSUE TITLE
Problem with server fingerprint

### ISSUE THREAD

**Issue by krow89** [LonamiWebs/Telethon#437]
Hi... My proble is on next code:

```
api_id   = 0000 # my real api_id here
api_hash = 'this_is_not_real_apy_hash' #my real api_hash here
phone    = '+3911111111' # my real number here
server_test= { "host":"149.154.167.40", "port":443}

client = TelegramBareClient('Krow', api_id, api_hash, timeout=timedelta(seconds=8), connection_mode=ConnectionMode.TCP_ABRIDGED)
client.session.server_address= server_test["host"]
ret= client.connect()
if not client.is_user_authorized():
    client.send_code_request(phone)
    client.sign_in(phone, input('Enter the code: '))

dialogs, entities = client.get_dialogs(10)
entity = entities[0]
result = client(GetHistoryRequest(
    entity,
    limit=20,
    offset_date=None,
    offset_id=0,
    max_id=0,
    min_id=0,
    add_offset=0
))
messages = result.messages
```

I hava problem on auth... The Res_q request is all right but at server response  ( that send me valid fingerprint 0xc3b42b026ce86b21) the rsa module cannot get valid public key from fingerprint that serve give me (in practice, the line key = _server_keys.get(fingerprint, None) in telethon.crypto.rsa.encrypt() return None)....  What is my problem??
P.S. Sorry for bad english

**Comment by Lonami** [comment]
Well, to begin with, the `TelegramBareClient` doesn't have `.send_code_request` nor `.sign_in`. Why aren't you just using the `TelegramClient`? Of course, either will work, but I see no reason behind why avoid the `TelegramClient`. In the same way, it doesn't have `.get_dialogs`.

> but at server response

I don't get any response. I can't even connect to `'149.154.167.40'`.

> the rsa module cannot get valid public key from fingerprint that serve give me

I need more data. Stack traces and used values would be useful too.

**Comment by krow89** [comment]
You are right, this code dont work arrivated at methods not avaible in TelegramBareClient but for me dont worked before.... I have reinstalled the library and now work right (i dont know that happening)... Anyway, it' s possible implement this library for using with python 2.x? Another similar library that work on python 2.x (without cli, pure python)? I want use this library on my android in QPython and it dont support (very well) python 3.x

**Comment by Lonami** [comment]
@krow89 I don't know of any other pure Python library for Telegram that works under Python 2. Anyway, just use Termux and install Python 3.6.3 on it. The library works just fine there.
