### ISSUE TITLE
incorrect operation of the event.MessageEdited

### ISSUE THREAD

**Issue by Andrew501-cmd** [LonamiWebs/Telethon#4373]
### Description

Hello everyone, sorry for the bad English. I recently ran into a problem in an event.The message has been edited. I analyzed one channel and found that the event is triggered when reactions are put on messages. But in my understanding (and how it should work in my program), the event should only work on changing the message text. Is there a way to solve this by standard means? And if not, how can I find a workaround to make it work the way I want it to?

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
You're using an old version.

**Comment by khoben** [comment]
> the event is triggered when reactions are put on messages.

Try checking the flag `event.message.edit_hide` that is set to True for stealth updates for bots and reactions.

**Comment by Platon2612** [comment]
I am faced with the problem of not being able to distinguish the editing event of a message by its author from the setting of a reaction to this message by another user. I got acquainted with this problem of how to distinguish such events by event.message.edit_hide.

This works in some cases, but not all.

If the message was first edited by its author, and then when someone puts a reaction on it, an event with the parameter event.message.edit_hide = False is received. (it should come with the event.message.edit_hide = True parameter).

The behavior was tested on Telethon 1.40.0. (On the old version 1.34.0, the behavior was similar).
