### ISSUE TITLE
Is there a way to get accont's login email and 2fa email?

### ISSUE THREAD

**Issue by AnselChopin** [LonamiWebs/Telethon#4374]
### Describe your suggested feature

I can not find a api to get account's login email and 2fa emal, is there a way to get accont's login email and 2fa email?
Thanks!

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself.

**Comment by AnselChopin** [comment]
> Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself.

Ok, understood! I am tring to find a way to get account's email, do you have any idea about it ? Thanks a lot!
