### ISSUE TITLE
How to get user info by ID

### ISSUE THREAD

**Issue by theasder** [LonamiWebs/Telethon#438]
Hey there,

I tried several functions but haven't found any that could return username of the user.

**Comment by Lonami** [comment]
No function will return the *username* known an ID, but rather the whole user.

**Comment by theasder** [comment]
We can get the whole user, but how can we extract the username from it?

**Comment by Lonami** [comment]
Not sure how much you've worked with Python or programming languages in general. But if you have an instance of some object, and said object has an `username` attribute, well, you can do `user.username` to access the username.

**Comment by theasder** [comment]
Oh, I didn't notice that attribute in class. Thanks.

**Comment by Lonami** [comment]
Always use lonamiwebs.github.io/Telethon. It has a nice search. You can even `print` the user, `dir(user)` it, `help(user)` or `print(user.stringify())`. Endless options.

**Comment by fastikprog** [comment]
> Get and updates all dialog, then you can find a dialog.

```python
async def get_username(user_id):
    try:
        await client.get_dialogs()

        user_entity = await client.get_entity(int(user_id))
        
        if user_entity.username:
            return user_entity.username
        else:
            return False
    except Exception as e:
        print(f"Error: {e}")
        return False```

**Comment by fukemy** [comment]
> > Get and updates all dialog, then you can find a dialog.
> 
> ```python
> async def get_username(user_id):
>     try:
>         await client.get_dialogs()
> 
>         user_entity = await client.get_entity(int(user_id))
>         
>         if user_entity.username:
>             return user_entity.username
>         else:
>             return False
>     except Exception as e:
>         print(f"Error: {e}")
>         return False```
> ```

it's work only for friend list
