### ISSUE TITLE
get_participants only return part of members in megagroup

### ISSUE THREAD

**Issue by Kootain** [LonamiWebs/Telethon#4385]
### Code that causes the issue

``` python
@client.on(events.NewMessage())
async def handler2(event):
    message: Message = event.message
    chat: Chat = await message.get_chat()
    sender: Optional[User] = await message.get_sender()
    if sender is None:
        print(event)
        return
    if isinstance(sender, User):
        username = sender.username
        if username is None:
            try:
                user: UserFull = await client(GetFullUserRequest(sender))
            except Exception as e:
                print(e)
                p = await client.get_participants(chat)
                print(chat.stringify())
                print(f'{message.sender_id} [{chat.title}#{chat.id}] @{username}: {text}')
            else:
                username = user.users[0].username
                print(f'[{chat.title}#{chat.id}] @{username}: {text}')
    else:
        print(type(sender))
        raise Exception()
```

### Expected behavior

I am listening to messages from a megagroup. When I cannot retrieve the user entity, I will try to 'encounter' this user using `client.get_participants()` as described in the documentation. However, it only returns 12 users (there are 78K users in this group). Is this a limitation of the Telegram API? If so, how can I 'encounter' users who send messages in a megagroup?

i tried add limit, filter, aggressive input params, still the same.

### Actual behavior

`client.get_participants()` only return part of members

### Telethon version

1.35.1

### Python version

Python 3.11.6

### Operating system (including distribution name and version)

macOS 14.3

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Kootain** [comment]
i have to get those kind of user's username from android app client, and query `GetFullUserRequest` by username once, after that i can get the user entity by message.get_sender() properly. but there seems no way to get the username from message event

**Comment by Lonami** [comment]
> Is this a limitation of the Telegram API?

Yes, which means Telethon cannot "fix" this, so I will close the issue.

> If so, how can I 'encounter' users who send messages in a megagroup?

Same way an official client would. Either through events or fetching the message history. Usage questions are offtopic here though.

**Comment by syabro** [comment]
@Lonami why? there is an "offset" parameter
https://core.telegram.org/method/channels.getParticipants

Also:
https://core.telegram.org/api/offsets
<img width="576" alt="image" src="https://github.com/user-attachments/assets/6d50db47-e32a-43f0-ade0-24db900aa19f">

**Comment by Lonami** [comment]
> @Lonami why? there is an "offset" parameter
> https://core.telegram.org/method/channels.getParticipants

The library uses it. It used to work fine. Not anymore though. Nothing the library can do.

If you find a way to "fix" offset not "working", PRs are welcome - but I strongly believe this remains a restriction on Telegram's side.
