### ISSUE TITLE
how to resolve an add emoji link

### ISSUE THREAD

**Issue by mokeLiu** [LonamiWebs/Telethon#4388]
### Describe your suggested feature

how to resolve an add emoji link like:
https://t.me/addemoji/{sticker_set_name}_by_{bot_username}
this is a link that refer to an emoji created from a robot.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
