### ISSUE TITLE
Trying to get client's channels

### ISSUE THREAD

**Issue by klaiderman** [LonamiWebs/Telethon#4389]
### Description

Hi, I went through all the documentations but couldn't find the client's channels as an object. 
I guess there is such a thing but I was just wondering the name.

I would appreciate an answer. Thanks (:

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
