### ISSUE TITLE
ValueError: Cannot cast InputPeerEmpty to any kind of int.

### ISSUE THREAD

**Issue by misamplus** [LonamiWebs/Telethon#439]
I saw this exception from get_message_history[line 535]->get_peer_id->_raise_cast_fail...

**Comment by Lonami** [comment]
Could you show your code? Or the relevant parts of it, such as how you got that user.

**Comment by misamplus** [comment]
I was want to get last messages of this username: konkour1234

**Comment by Lonami** [comment]
I have asked for your **code**, not what you want to do.

**Comment by misamplus** [comment]
Keep calm, I wrote my code process!
Any way you can test the bug with this code:
src = client.get_entity('konkour1234')
res = client.get_message_history(src, limit=100, offset_id=0)

**Comment by Lonami** [comment]
What version are you using? The code works just fine.

**Comment by misamplus** [comment]
I don't know way but it solved! :|

**Comment by Lonami** [comment]
What solved it?
