### ISSUE TITLE
Get audio or video-only stream from videos in downloader

### ISSUE THREAD

**Issue by dossma** [LonamiWebs/Telethon#4392]
I'd appreciate a feature that if a video is tageted to be downloaded, to get the audio or video-only (mute) stream.
While I do not know if that is possible with Telegram, it is possible with YouTube which has been realized by the yt-dlp project, see exemplary the option `bestaudio` under
[https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#post-processing-options](url)

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
> While I do not know if that is possible with Telegram

It is not. You will have to download everything and split the file yourself.
