### ISSUE TITLE
RPCError 400: CALL_PROTOCOL_LAYER_INVALID 

### ISSUE THREAD

**Issue by georgerabus** [LonamiWebs/Telethon#4398]
### Code that causes the issue

```
with TelegramClient(name, api_id, api_hash) as client:
    result = client(functions.phone.RequestCallRequest(
        user_id='<phone number>',
        g_a_hash=b'\xa3\x90W\xcb?\x17\xe8\xac\x14\xa1\xc6,\x98\xf6\xc8d\xbe\xe10\xa4k?\xb1<\xff\xc3\x16k,\xf3o\xe7',
        protocol=types.PhoneCallProtocol(
            min_layer=42,
            max_layer=42,
            library_versions = ['1.36.0'],
            udp_p2p=True,
            udp_reflector=True
        ),
        video=True
    ))
    print(result.stringify())
```

I have no idea what is wrong with the thing, any hints?

### Expected behavior

to work

### Actual behavior

```
 File "/home/user/project/env/lib/python3.12/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: CALL_PROTOCOL_LAYER_INVALID (caused by RequestCallRequest)
```

### Telethon version

1.36.0

### Python version

3.12.3

### Operating system (including distribution name and version)

Arch Linux 

### Other details

I used the sample provided in the documentation, I don't see any other information regarding those layers

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

**Comment by georgerabus** [comment]
i'm sorry but is there a chance you will implement voip call request in telethon api?
![image](https://github.com/LonamiWebs/Telethon/assets/144466896/ea1d2d44-bd05-426c-9f57-d0d1745a6ecc)

also a side question, is the g_a_hash actually important for telegram or any random bit value is ok? And where can I learn about my specific error (CALL_PROTOCOL_LAYER_INVALID)

**Comment by Lonami** [comment]
That README seems to be at least 4 years old. I have no personal interest in learning how calls work, so I've never studied them either.
