### ISSUE TITLE
 RPCError 400: TOPIC_ID_INVALID

### ISSUE THREAD

**Issue by GNAIXOAH** [LonamiWebs/Telethon#4405]
### Code that causes the issue

from datetime import datetime, timezone
import time
import openpyxl
import asyncio
from telethon import TelegramClient

# Setup Google Sheets with OpenPyXL
workbook = openpyxl.Workbook()
worksheet_name = 'Oyster'  # This line isn't necessary since it isn't used afterward
sheet = workbook.active

# Define titles
titles = ['Scraping ID', 'Group', 'Author ID', 'Content', 'Date', 'Message ID', 'Author', 'Views', 'Reactions', 'Shares', 'Media', 'Comments']
sheet.append(titles)  # This will add titles as the first row in the worksheet

# Setup Telegram client
username = ''  # your Telegram username
api_id = ''  # your api_id
api_hash = ''  # your api_hash

# Scraping settings
channel = 'https://t.me/'  # channel or group to scrape
start_date = datetime(2024, 4, 1, tzinfo=timezone.utc)
end_date = datetime(2024, 7, 1, tzinfo=timezone.utc)
key_search = ''  # keyword to search (optional)

# Function to scrape Telegram messages
async def scrape_telegram():
    index = 2  # Start from the second row since the first row contains titles

    async with TelegramClient(username, api_id, api_hash) as client:
        await client.start()
        async for message in client.iter_messages(channel, search=key_search):
            if start_date < message.date < end_date:
                url = f'https://t.me/{channel}/{message.id}'.replace('@', '') if message.media else 'no media'
                emoji_string = " ".join(f"{reaction_count.reaction.emoticon} {reaction_count.count}" for reaction_count in (message.reactions.results if message.reactions else []))
                comments = []
                async for comment in client.iter_messages(channel, reply_to=message.id):
                    comments.append(comment.text)
                comment_str = '; '.join(comments)

                # Append row to sheet
                content = [f'#ID{index-1:05}', channel, message.sender_id, message.text, message.date.strftime('%Y-%m-%d %H:%M:%S'), message.id, message.post_author, message.views, emoji_string, message.forwards, url, comment_str]
                sheet.append(content)

                print(f'Item {index-1:05} completed!')
                index += 1
                time.sleep(1)

        print(f'----------------------------------------\n#Concluded! #{index-2:05} posts were scraped!\n----------------------------------------')

# Run the scraping function
asyncio.run(scrape_telegram())

# Save the workbook
workbook.save('Scraped_Telegram_Data.xlsx')

### Expected behavior

I was trying to scrap chats from a telegram channel.

### Actual behavior

telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: TOPIC_ID_INVALID (caused by GetRepliesRequest)

### Traceback

 File "d:\Downloads\web-scraping-telegram-main\web-scraping-telegram-main\web-scraping-telegram.py", line 53, in <module>
    asyncio.run(scrape_telegram())
  File "C:\Users\Legion_Slim-7i\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Legion_Slim-7i\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\Downloads\web-scraping-telegram-main\web-scraping-telegram-main\web-scraping-telegram.py", line 38, in scrape_telegram
    async for comment in client.iter_messages(channel, reply_to=message.id):
  File "C:\Users\Legion_Slim-7i\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\Legion_Slim-7i\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\messages.py", line 184, in _load_next_chunk
    r = await self.client(self.request)
  File "C:\Users\Legion_Slim-7i\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Legion_Slim-7i\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: TOPIC_ID_INVALID (caused by GetRepliesRequest)

### Telethon version

1.36.0

### Python version

Python 3.10.11

### Operating system (including distribution name and version)

Windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Issue is unreadable and error doesn't seem to match the code.
