### ISSUE TITLE
updateapptologin error

### ISSUE THREAD

**Issue by mmudasir1** [LonamiWebs/Telethon#4407]
### Code that causes the issue

i am getting telethon.errors.rpcerrorlist.updateAppToLoginError (caused by SendCodeRequest)

### Expected behavior

![photo_2024-07-10_03-10-32 2](https://github.com/LonamiWebs/Telethon/assets/128186349/fc9180bc-34f0-4f13-9e41-8f1cd4db774a)

### Actual behavior

when i entered my phone number it gives me that error and i am not receiving code for login

### Traceback

i attached screenshot

### Telethon version

1.36.0

### Python version

3.12

### Operating system (including distribution name and version)

windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Double check the version used is correct.

**Comment by olehdutko** [comment]
I have the same issue( 
My code was working for a long time and now I have this error

**Comment by Erjona1** [comment]
Did you manage to fix this? What was it?
