### ISSUE TITLE
client.download_media(event.message,bytes) - not load bypes

### ISSUE THREAD

**Issue by pbadun** [LonamiWebs/Telethon#4408]
### Describe your suggested feature

.venv/lib/python3.11/site-packages/telethon/client/updates.py:-1: RuntimeWarning: coroutine 'DownloadMethods.download_media' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by pbadun** [comment]
psycopg2.ProgrammingError: can't adapt type 'coroutine'

**Comment by Lonami** [comment]
This is not a bug in the Telethon library.
