### ISSUE TITLE
Constant access_hash=3107249229418738550 in  media=MessageMediaGeo(geo=GeoPoint( access_hash=3107249229418738550))

### ISSUE THREAD

**Issue by riphet** [LonamiWebs/Telethon#4409]
### Code that causes the issue

```
class MiBot:
 def __init__(self, bot_name, api_id, api_hash, token):
 self. Token = token
 self.client = TelegramClient(bot_name, api_id, api_hash)

 async def begin(self):
 await self.customer.start(bot_token=self. Token)

async def manejar_ubicacion(event):
 if event.is_private and event.message.media and event.message.media.geo:
 print(f'access_hash: {event.message.media.access_hash}')
...
self.cliente.add_event_handler(manejar_ubicacion, events.NewMessage(incoming=True, func=lambda e: e.message.media and e.message.media.geo))
```

### Expected behavior

understanding that it must be the same value.
access_hash of users.
access_hash corresponding to the user who sends location.
Related information is welcome

### Actual behavior

access_hash: 3107249229418738550
access_hash: 3107249229418738550
access_hash: 3107249229418738550
access_hash: 3107249229418738550
access_hash: 3107249229418738550
access_hash: 3107249229418738550

### Telethon version

1.36.0

### Python version

3.11

### Operating system (including distribution name and version)

Windows 11

### Other details

:)

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
The results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
