### ISSUE TITLE
Hash in GetParticipantsRequest

### ISSUE THREAD

**Issue by FlashAJ** [LonamiWebs/Telethon#441]
Hi.
In the new version (after 0.15.3.2) of Telethon, in the function GetParticipantsRequest appeared option the Hash. Where to get his?

**Comment by Lonami** [comment]
Why did you open a second issue

**Comment by FlashAJ** [comment]
I did not understand how to write

**Comment by Lonami** [comment]
How to write what?

**Comment by FlashAJ** [comment]
Question
