### ISSUE TITLE
Invert media on send

### ISSUE THREAD

**Issue by julius425** [LonamiWebs/Telethon#4410]
Hello !
I noticed that the invert_media flag is available on the Message object in recent versions, which allows us to check if text and pictures are switched upside down. I can get its value when fetching messages from the channel, but I can't use it on send_file. Will you update this feature, or should I make a PR? I have already implemented this in my local project.

**Comment by Lonami** [comment]
I would prefer to not add any more features to v1. I don't know when v2 will be ready.

A local modified copy or fork with your needs is fine, or monkey patching as needed.
