### ISSUE TITLE
Connot connect with the WEB API key

### ISSUE THREAD

**Issue by tayp1n** [LonamiWebs/Telethon#4412]
### Code that causes the issue

I am trying to connect by using the web api key prior generated. It seems to not working. The code freezes here -> await client.connect(). 

```python
from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.crypto import AuthKey
import binascii
import asyncio

# Your parameters
api_id = ""
api_hash = ""
auth_key_hex = ""
session = StringSession()
session.auth_key = AuthKey(data=bytearray.fromhex(auth_key_hex))
client = TelegramClient(session, api_id, api_hash)

async def main():
    await client.connect()
asyncio.run(main())
```

### Expected behavior

connect the client with success

### Actual behavior

doesn't connect and freezes

### Telethon version

1.36.0

### Python version

3.11

### Operating system (including distribution name and version)

macOS

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by tayp1n** [comment]
#795 #742 #316 these the same i did

**Comment by Lonami** [comment]
Telethon only officially supports sessions created by the client itself, not external ones.
