### ISSUE TITLE
[v2] Type hint support to @client.on

### ISSUE THREAD

**Issue by xplus2g4** [LonamiWebs/Telethon#4414]
### Describe your suggested feature

Hi,

May I request a small enhancement on the typing of `@client.on`?
```Python
@client.on(events.NewMessage, filters.Command("/hi"))
async def handler(event: events.NewMessage): # type err: Event is incompatible with NewMessage
    await event.reply("Hello!")
```
Currently, the type of a handler is: `Callable[[Event], Awaitable[Any]]`, but `Callable` is contravariant, which means it can only takes in Event or Superclass of Event. 

Proposal 1 - Type Parameter Lists (Python 3.12+)
```Python
def on[T: Superclass](
    self,
    event_cls: Type[T],
    ........ # more params here
) -> Callable[[Callable[[T], Awaitable[Any]]], Callable[[T], Awaitable[Any]]]:
    # method body
    pass
```
Proposal 2 - TypeVar
```Python
AnyEvent = TypeVar("AnyEvent", bound=Event, covariant=True)
def on(
    self,
    event_cls: Type[AnyEvent],
    ........ # more params here
) -> Callable[[Callable[[AnyEvent], Awaitable[Any]]], Callable[[AnyEvent], Awaitable[Any]]]:
    # method body
    pass
```

Thanks for looking through!

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
I tried a few things but couldn't get it to work. Seems like you've done some digging, so feel free to send a PR.
