### ISSUE TITLE
Can I send my contact in chat?

### ISSUE THREAD

**Issue by Sataff** [LonamiWebs/Telethon#4416]
### Description

Good afternoon, I haven’t found anywhere how I can share my contact. Please tell me how can I do this?

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
