### ISSUE TITLE
Add Support for Hashtag Search (between all public channels)

### ISSUE THREAD

**Issue by scripter76** [LonamiWebs/Telethon#4418]
### Describe your suggested feature

Telegram added a new feature about searching in all public channels for a #hashtag but i cant find a function for it on Telethon.
Could you please add support for this feature?
https://telegram.org/blog/message-effects-and-more#hashtag-search

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
No new features are planned in v1, though if it exists in the API, you can invoke the method from tl.telethon.dev directly.
