### ISSUE TITLE
Multi session

### ISSUE THREAD

**Issue by tkiew** [LonamiWebs/Telethon#4421]
### Description

I don't know how to create a main.py source in my server for several sessions that are inside a folder

### Checklist

- [ ] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
I don't believe this is something that should be explicitly called out in the documentation. The first parameter to the `TelegramClient` already allows one to create as many clients as they like, each with one session.
