### ISSUE TITLE
Can't get User id...

### ISSUE THREAD

**Issue by ultimakaz** [LonamiWebs/Telethon#4422]
### Code that causes the issue

async def get_user_entity(user_id):
    try:
        return await client.get_input_entity(user_id)
    except Exception as e:
        print(f"Error retrieving user entity for ID {user_id}: {e}")
        return None

### Expected behavior

This code worked well last week, but now i can't get user's id, what;s wrong? What can i do? 

### Actual behavior

It's just gives an error

### Telethon version

Version: 1.34.0

### Python version

3.12.0

### Operating system (including distribution name and version)

windows server 2018

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Entity must be in cache. If it's not, Telethon can't fetch it.
