### ISSUE TITLE
hyperlink in the message not correct

### ISSUE THREAD

**Issue by konglquan** [LonamiWebs/Telethon#4423]
### Code that causes the issue

    message = "[超链接文字[这是多余文字]](https://github.com/)"
    message = process_brackets(message)
    send_result = await client.send_message(
        entity=target_chat_id,
        message=message,
        file=None,
        link_preview=True
    )
    print(send_result)

### Expected behavior

![image](https://github.com/user-attachments/assets/9048735c-9634-4d95-b1f3-522d3d3fa819)

### Actual behavior

![image](https://github.com/user-attachments/assets/f4a3fc7b-1844-4049-8c17-432dc4552ca8)

### Telethon version

1.36.0

### Python version

3.12

### Operating system (including distribution name and version)

winwows11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
v1's markdown doesn't support anything beyond the simplests strings. Use the 'html' parse_mode.
