### ISSUE TITLE
Support async in telethon sessions management

### ISSUE THREAD

**Issue by NikitaVoitov** [LonamiWebs/Telethon#4427]
### Describe your suggested feature

According to Telethon's doc (https://docs.telethon.dev/en/stable/concepts/sessions.html#creating-your-own-storage) it's possible to write own implementation of sessions management by utilizing MemorySession and custom backend for storing session. The problem is that Telethon expects the custom session management to be sync by nature. It does not support, e.g. async approach with sessions management by design, although Telethon supports asyncio at some degree. I rewrote telemongo using motor and beanie (used in my project for any kind of interaction with the MongoDB), but stuck on Telethon's internal methods (auth, baseclient, something from helpers, etc.) that are expecting sync code. So it's impossible to achieve stable and predictable async session management with Telethon unfortunately, because some parts of the library still expecting a sync code.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Unfortunately not planned for v1. Though the fork https://github.com/tulir/Telethon/ should support them.

**Comment by NikitaVoitov** [comment]
What's the difference between this fork and the main Telethon project? I don't wanna switch just for the sake of async session management, I want to understand the overall impact.

**Comment by Lonami** [comment]
I don't know. All I remember is this fork exists and has async sessions. The author is trustworthy, and there's not a lot of additional commits, so it's easy to see what's changed.
