### ISSUE TITLE
How to share folder by telethon

### ISSUE THREAD

**Issue by y-super-y** [LonamiWebs/Telethon#4429]
### Describe your suggested feature

Telegram support share chat folder with others ,but seems telethon does not support it 

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

Everything supported by Telegram's API is supported by Telethon, but most methods don't exist in the `TelegramClient`; only in https://tl.telethon.dev.
