### ISSUE TITLE
Joinchat hash and public or private property

### ISSUE THREAD

**Issue by epelaez1** [LonamiWebs/Telethon#443]
Hi,
is there any way to obtain the hash of a private channel that you have already joined via api?
```
https://telegram.me/joinchat/<hash>
```
In the [telegram web](https://web.telegram.org) you can obtain it clicking at the name of the channel.

And one more question:
Is there any way to know if a channel that you have already joined is public or private?
Maybe the username parameter of the channel is reserved for public channels only, but please confirm me if public channels always have a username and a private channels never have it. 

Thank you for all

**Comment by Lonami** [comment]
`client.get_entity(chat_link)`. Not sure if I had pushed this before but it's not on the wiki. Once you have the channel entity you should use that to join.

> Is there any way to know if a channel that you have already joined is public or private?

It should be in your dialogs if you belong to it.

**Comment by epelaez1** [comment]
A la vista de que eres español voy a aprovechar a expresarme algo mejor. 
El tema es cuando no tienes el "chat_link" y estás ya dentro del canal. ¿Como puedo obtener ese hash?
El programa se mete en el telegram del usuario y en los canales que este metido tiene que poder mostrar el link entero con el hash. 

Y en cuanto a los canales privados o publicos en el dialog asociado solo se muestra la siguiente información:
```
Dialog(
	pinned=False,
	peer=PeerChannel(
		channel_id=
	),
	top_message=2563,
	read_inbox_max_id=2563,
	read_outbox_max_id=0,
	unread_count=0,
	unread_mentions_count=0,
	notify_settings=PeerNotifySettings(
		show_previews=True,
		silent=False,
		mute_until=0,
		sound='default'
	),
	pts=5682,
	draft=None
)
```

Por favor, si puedes dame un ejemplo de código partiendo de que tengo el PeerChannel, el Channel, o el Dialog.
Gracias de antemano

**Comment by Lonami** [comment]
Although I'm Spanish and I do understand that, other people reading these GitHub issues likely won't. Anyway, [search is your friend](https://lonamiwebs.github.io/Telethon/index.html?q=invite).

**Comment by epelaez1** [comment]
I'll do my best to explain myself in english
I have been trying all the methods related with this problem.
Methods: 
**ImportChatInviteReques** -> Requires the hash. The hash is what i want.
**CheckChatInviteRequest** -> Requires the hash. The hash is what i want.
**ExportChatInviteRequest** -> Doesn't work with Channels or megagroups
```
*** telethon.errors.rpc_error_list.ChatIdInvalidError: (ChatIdInvalidError(...), 'Invalid object ID for a chat. Make sure to pass the right types, for instance making sure that the request is designed for chats (not channels/megagroups) or otherwise look for a different one more suited\\nAn example working with a megagroup and AddChatUserRequest, it will fail because megagroups are channels. Use InviteToChannelRequest instead')
```
**ExportInviteRequest** -> Doesn't work without admin privileges
```
*** telethon.errors.rpc_error_list.ChatIdInvalidError: (ChatIdInvalidError(...), 'Invalid object ID for a chat. Make sure to pass the right types, for instance making sure that the request is designed for chats (not channels/megagroups) or otherwise look for a different one more suited\\nAn example working with a megagroup and AddChatUserRequest, it will fail because megagroups are channels. Use InviteToChannelRequest instead')
```
**SendInvitesRequest** -> I don't want to send any message

The hash is not private for a user that has already joined the channel, if you use the telegram web you can obtain it by clicking in the title of the channel.

If there is any way to obtain the link or the hash I'll apreciate if you post the code here as an example.

**Comment by Lonami** [comment]
> The hash is what i want.

The hash is nothing but the part after `joinchat/`. So, the hashes for:
```python
url1 = 't.me/joinchat/AAAAAEkk2WdoDrB4-Q8-gg'
url2 = 't.me/joinchat/AAAAAExTYt4PTTEtJ3_ylA'
```

Are just:
```python
hash1 = 'AAAAAEkk2WdoDrB4-Q8-gg'
hash2 = 'AAAAAExTYt4PTTEtJ3_ylA'
```

Note that:
> if you use the telegram web you can obtain it by clicking in the title of the channel.

Won't always work. You may not have the permission to get an invite link. Given than the search doesn't allow looking for parameters, <kbd>Ctrl+F</kbd> in this file instead: https://github.com/LonamiWebs/Telethon/blob/master/telethon_generator/scheme.tl until you find what you need. I don't really know what's the right way to get the hash/invite link.
