### ISSUE TITLE
A lot of events for one reaction (after starting bot)

### ISSUE THREAD

**Issue by riphet** [LonamiWebs/Telethon#4432]
### Code that causes the issue

```
from telethon.tl.types import UpdateBotMessageReaction
from datetime import datetime
```

```
async def handle_event(event,bot):
    print(f"Evento recibido: {event}")

    # Verificar si se han agregado reacciones en un mensaje del bot
    if isinstance(event, UpdateBotMessageReaction ) :
        if (datetime.now(timezone.utc)-event.date).total_seconds() < 5 :   # Evitar historial de eventos de reacciones anteriores.
            # Obtener la reacción anterior de old_reactions
            if event.old_reactions:
                previous_reaction = event.old_reactions[-1].emoticon
                # previous_reaction = event.old_reactions[0].emoticon
                print(f"Reacción eliminada: {previous_reaction}")
                # await bot.cliente.send_message(event.peer, f"Reacción eliminada: {previous_reaction}")

            # Obtener la última reacción de new_reactions
            if event.new_reactions:
                latest_reaction = event.new_reactions[-1].emoticon
                # latest_reaction = event.new_reactions[0].emoticon
                print(f"Reacción añadida: {latest_reaction}")
                # await bot.cliente.send_message(event.peer, f"Recibí la reacción: {latest_reaction}")
```

`        self.cliente.add_event_handler(lambda event: partial(handle_event, bot=self)(event), events.Raw)`

### Expected behavior

1.- Start bot ✅
2.- When some  user places first reaction, I hope to receive only one event. but this does not happen.
3.-  I also expect to receive a correct value of qts. But this is not so necessary for me.

### Actual behavior

1.- Start bot ✅
2.- When some user places first reaction, many events are received (one event for each old reaction). ❌
3.- When a user posts their first reaction, All previous reaction events have a value qts=0, including the last reaction event received with value qts = 0 ❌

### Traceback

Forced to filter with the only option:

`        if (datetime.now(timezone.utc)-event.date).total_seconds() < 5 :   # Evitar historial de eventos de reacciones anteriores.`

### Telethon version

1.36.0

### Python version

3.11 (64-bit)

### Operating system (including distribution name and version)

Windows 11 Home Single Language

### Other details

I would love to know how to fix my ban on local groups. 
Telegram won't let me create a local group (group with location).
but this is other detail with telegram😀

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Are you using `catch_up=True`?

**Comment by riphet** [comment]
> Are you using `catch_up=True`?
I appreciate your interest, I don't use catch_up, this is the code:
`        self.cliente = TelegramClient(bot_name, api_id, api_hash)`

**Comment by riphet** [comment]
After trying with `catch_up=True`, now get an event for each reaction. This works much better for me.
The correction was in:
`self.cliente = TelegramClient(session=bot_name, api_id=api_id, api_hash=api_hash, catch_up=True, lang_code='es', system_lang_code='es')`

And the following code is no longer needed:
`if (datetime.now(timezone.utc)-event.date).total_seconds() < 5 :`

Now the issue is being closed, thanks a lot to Lonami 🤩

**Comment by riphet** [comment]
thanks a lot to Lonami 🤩
