### ISSUE TITLE
Issue with changing username

### ISSUE THREAD

**Issue by NoTUsR** [LonamiWebs/Telethon#4439]
### Code that causes the issue

        async with TelegramClient(k[1], k[3], k[4]) as client:
            result = await client(functions.account.CheckUsernameRequest(username=k[0]))
            if result == True:
                print("The telegram", k[0], "is available")
                await client(functions.account.UpdateUsernameRequest(k[0]))
                free_nicks.append([k[0], k[1], k[5]])
            else:
                print("The telegram", k[0], "is not available")

### Expected behavior

Change username

### Actual behavior

telethon.errors.rpcerrorlist.UsernameOccupiedError: The username is already taken (caused by UpdateUsernameRequest)

### Traceback

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\nicks\venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Admin\Desktop\nicks_telethon\main.py", line 449, in check_nicks
    await client(functions.account.UpdateUsernameRequest(k[0]))
  File "C:\Users\Admin\Desktop\nicks\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Admin\Desktop\nicks\venv\lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.UsernameOccupiedError: The username is already taken (caused by UpdateUsernameRequest)

### Telethon version

1.36

### Python version

3.10.4

### Operating system (including distribution name and version)

Windows 11

### Other details

I try to change username to the recently released one, I get the following error: telethon.errors.rpcerrorlist.UsernameOccupiedError: The username is already taken (caused by UpdateUsernameRequest).

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
