### ISSUE TITLE
sign_up

### ISSUE THREAD

**Issue by FlashAJ** [LonamiWebs/Telethon#444]
How use function sign_up for register new user if for this is necessary api_id and api_hash, since without these parameters the request is not possible?

**Comment by Lonami** [comment]
What?

**Comment by FlashAJ** [comment]
To register a new user, you need to send an SMS code, which in turn needs an api_id and api_hash?

ps. sorry for my English

**Comment by Lonami** [comment]
Well, yeah, you need to get your own `api_id/api_hash` to do *anything* with the library, not just sign up. If you really refuse to get your own, you can find the ID/hash combinations for other projects like tg-cli or tdesktop online. Use at your own risk.

**Comment by FlashAJ** [comment]
Thank you. I thought so.
