### ISSUE TITLE
Can i cancel send_file method?

### ISSUE THREAD

**Issue by MohammadArak** [LonamiWebs/Telethon#4441]
### Describe your suggested feature

lets say i have called a new send_file method and now i want to cancel uploading process, is there any way to do that?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

`asyncio`-created tasks do have a `.cancel()` method. But this is something the Python's stdlib provides, and is not specific in any way to Telethon.
