### ISSUE TITLE
return voice total count error

### ISSUE THREAD

**Issue by amone-bit** [LonamiWebs/Telethon#4445]
### Code that causes the issue

```python
async def get_voice_total_count(entity: 'hints.EntityLike') -> int:
    voices = await client.get_messages(entity, limit=0, filter=InputMessagesFilterRoundVoice)
    return voices.total
```

### Expected behavior

I want to return voice messages total count that in the desktop client's right side. First I try to use InputMessagesFilterVoice, but the return's count is video's count, and than I try to use InputMessagesFilterRoundVoice, than return's count is correct.Is that a bug, or am I using it incorrectly?

### Actual behavior

error count

### Telethon version

1.36.0

### Python version

3.11.7

### Operating system (including distribution name and version)

windows 10

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Filters are passed to Telegram as-is:
https://github.com/LonamiWebs/Telethon/blob/aec957d62da03d511b7a656a76490e882f740024/telethon/client/messages.py#L75

If that doesn't work, it's Telegram's fault.

You might want to use https://tl.telethon.dev/methods/messages/get_search_counters.html though.
