### ISSUE TITLE
Adding mypyc compilation

### ISSUE THREAD

**Issue by Jahongir-Qurbonov** [LonamiWebs/Telethon#4450]
### Describe your suggested feature

Advantages: https://mypyc.readthedocs.io/en/latest/introduction.html#why-mypyc

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Not planned. Definitely not in v1. I'll close this for now, but if you were planning to work on this for v2, I can reopen and assign it to you.

**Comment by Jahongir-Qurbonov** [comment]
I need to experiment with mypy, not sure when, but I think I'll send a pr in the near future. Let the issue remain closed for now
