### ISSUE TITLE
Update to layer 185

### ISSUE THREAD

**Issue by flexagoon** [LonamiWebs/Telethon#4452]
### Describe your suggested feature

Please add support for API Layer 185

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
The git repository is already at layer 186 https://github.com/LonamiWebs/Telethon/commit/90f1e5b0733239ed18a0feb369dfd80d99b65088.

**Comment by flexagoon** [comment]
@Lonami why are the objects and methods from layer 185 not available then?

**Comment by Lonami** [comment]
No clue. The layer was taken from tdesktop's repository. Perhaps it's changed again?

**Comment by flexagoon** [comment]
@Lonami no, the methods are there in the tl file, but there's no generated python code for eg `messageMediaPaidMedia` which was added in layer 183, while older types like `messageMediaPoll` do have a dedicated python type.

**Comment by Lonami** [comment]
The code is generated when the library is installed. There's just no PyPi version yet. But pip allows installing from git repositories.
