### ISSUE TITLE
In rare cases iter_messages with reverse=True aborts its work

### ISSUE THREAD

**Issue by kristal374** [LonamiWebs/Telethon#4453]
### Code that causes the issue

```python
import asyncio
from telethon import TelegramClient

api_id: int = "api_id"
api_hash = "api_hash"


async def main():
    client = TelegramClient('name', api_id, api_hash)
    await client.connect()

    CHANNEL = "channel_id"
    channel_entity = await client.get_entity(CHANNEL)

    messages_list = []
    async for message in client.iter_messages(channel_entity, reverse=True):
        messages_list.append(message)

    print(f"Messages processed: {len(messages_list)}")

    messages_count = await client.get_messages(channel_entity, limit=0)
    print(f"Total messages: {messages_count.total}")

    # >>> Messages processed: 100
    # >>> Total messages: 9575

if __name__ == "__main__":
    asyncio.run(main())

```

### Expected behavior

It is expected that client.iter_messages(channel, reverse=True) will be iterated through all messages from old to new.

### Actual behavior

client.iter_messages(channel, reverse=True) returns only the 100 oldest messages.

### Telethon version

1.36.0

### Python version

3.7.9 & 3.10.10

### Operating system (including distribution name and version)

Windows 10

### Other details

After analyzing the script's operation with the debugger, I concluded that the cause of the error is this [fix](https://github.com/LonamiWebs/Telethon/commit/b6d8311a5565a84986a3bd07d9539c55d9b7ca4e). In rare cases, the last message in the group will have an id of 100, which also equals `request.limit=100` since this is the maximum batch size. This issue is also discussed in the related [issue](https://github.com/LonamiWebs/Telethon/issues/3949#issuecomment-1742159943).

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Please feel free to send a PR, since you've already done some digging. I probably won't look into this in the near future myself.
