### ISSUE TITLE
Issue in pack_bot_file_id method 

### ISSUE THREAD

**Issue by chandan22140** [LonamiWebs/Telethon#4458]
### Code that causes the issue

This is the code of the method having the issue.

```
def pack_bot_file_id(file):
    """
    Inverse operation for `resolve_bot_file_id`.

    The only parameters this method will accept are :tl:`Document` and
    :tl:`Photo`, and it will return a variable-length ``file_id`` string.

    If an invalid parameter is given, it will ``return None``.
    """
    if isinstance(file, types.MessageMediaDocument):
        file = file.document
    elif isinstance(file, types.MessageMediaPhoto):
        file = file.photo

    if isinstance(file, types.Document):
        file_type = 5
        for attribute in file.attributes:
            if isinstance(attribute, types.DocumentAttributeAudio):
                file_type = 3 if attribute.voice else 9
            elif isinstance(attribute, types.DocumentAttributeVideo):
                file_type = 13 if attribute.round_message else 4
            elif isinstance(attribute, types.DocumentAttributeSticker):
                file_type = 8
            elif isinstance(attribute, types.DocumentAttributeAnimated):
                file_type = 10
            else:
                continue
            break
        ret = _encode_telegram_base64(_rle_encode(struct.pack('<iiqqb', file_type, file.dc_id, file.id, file.access_hash, 2)))
        print("_encode_telegram_base64", ret)
        return ret
    ```

### Expected behavior

On using this method, an year ago, I used to get a string of 71 characters as file_id as output of the method , which is expected
"BQACAgUAAxkBAAIkeWbcpPid1R5UHBbQxaYFD5Siu8zOAAJlEgAC1xHoVq0YxoxvBTCiNgQ"

### Actual behavior

On using this method right now, I get a string of 31 characters as file_id as the output of the method, which is not expected

"BQADBQADXRIAAtcR6Fass92SitfR7QI"

### Telethon version

v1

### Python version

3.12.5

### Operating system (including distribution name and version)

Windows 11 64 bit

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
This method is unfortunately broken and no longer maintained. It will be gone entirely from v2.

**Comment by chandan22140** [comment]
Can you suggest any Alternative to this method which can provide the
file-id given that telethon message.media is provided
