### ISSUE TITLE
Multiple Download with one client open

### ISSUE THREAD

**Issue by cat0rgi0** [LonamiWebs/Telethon#446]
Hi ,
i've tried to download multiple file one for each workers that have global connection but it seems they share also the same TCP connection.
```
def downloadMediaFile(message):
        fileName=message.media.document.attributes[0].file_name
        client.download_media(message, '/Download/')
        client.send_message(123456,'Download %s completato' % fileName)
....
def testThread(update):
        logging.info('Thread Test %d'%threading.get_ident())
        if isinstance(update,UpdateNewMessage) and update.message.media is not None:
                downloadMediaFile(update.message)
....
client = TelegramClient(XXXX, api_id, api_hash,update_workers=4)
client.add_update_handler(testThread)
....
```

Until i dont' start download all seems to work fine

>  1995714560 -  2017-11-17 18:07:05,945 - root - Read Thread
>  1979004000 -  2017-11-17 18:07:13,862 - root - Thread Test 
>  1950348384 -  2017-11-17 18:07:47,078 - root - Thread Test 
>  1969222752 -  2017-11-17 18:07:47,126 - root - Thread Test 
>  1958736992 -  2017-11-17 18:07:55,457 - root - Thread Test

 

but when an update handler start

> 1958736992 -  2017-11-17 18:07:55,460 - root - Download File 

any other workers seem to be locked. Especially if i send a new file any free workers don't wake up.
It's a normal behavior of a telethon? I have to open a new connection every download event in handler?

....Great library...

**Comment by Lonami** [comment]
While a worker is downloading things, other workers should not be affected, no. And currently the way media is downloaded through any thread that's not the main thread is far from optimal. Each part of the file creates a new connection. So maybe you would be better off using only the main thread to listen for updates and download media.

**Comment by cat0rgi0** [comment]
For this reason I ve opened an issue cos it seems a strange bahavior. I want to download more files in the same time so I don't think I can use only the main thread in a parallel multiple download if I don't manage a multiple threading. 
In the case I written bottom it seems some message during download coming rarely.

**Comment by cat0rgi0** [comment]
For this reason I ve opened an issue cos it seems a strange bahavior. I want to download more files in the same time so I don't think I can use only the main thread in a parallel multiple download if I don't manage a multiple threading. 
In the case I written bottom it seems some message during download coming rarely.

**Comment by Lonami** [comment]
Alright but why two comments?

**Comment by cat0rgi0** [comment]
I m on mobile phone...after i will delete one ...sorry

**Comment by Lonami** [comment]
@cat0rgi0 you can delete comments from mobile.

**Comment by cat0rgi0** [comment]
It shoul be a problem by thread manage of unix system cos telethon start with high priority all parts of downlaod thread?

**Comment by Lonami** [comment]
You're probably running CPython which has a Global Interpreter Lock, or GIL, so the thread manager of unix doesn't really come into play here I guess. I don't know much though so I may be wrong.

**Comment by Lonami** [comment]
I'm going to close this issue since opening multiple connections requires more work when it comes down to handling updates, and it may be tricky. Since you have a very specific use case for this, maybe you want to open a new connection yourself (you can connect to Telegram servers several times, and execute requests on each of them). Then again, CPython's GIL may not help, and updates may be dropped, but it's possible. I would suggest creating a clone of the `TelegramClient` and replacing the `.sender` with a new `MtProtoSender` on a new connection.
