### ISSUE TITLE
RequestWebViewRequest's start_param parameter not working 

### ISSUE THREAD

**Issue by phongpt156** [LonamiWebs/Telethon#4469]
### Code that causes the issue

```
result = await client(RequestWebViewRequest(
            peer=peer,
            bot=bot,
            platform='android',
            from_bot_menu=True,
            url='url',
            start_param='my start param',
            theme_params=DataJSON(
                data='{"bg_color":"#212121","text_color":"#ffffff","hint_color":"#aaaaaa","link_color":"#8774e1","button_color":"#8774e1","button_text_color":"#ffffff","secondary_bg_color":"#0f0f0f","header_bg_color":"#212121","accent_text_color":"#8774e1","section_bg_color":"#212121","section_header_text_color":"#aaaaaa","subtitle_text_color":"#aaaaaa","destructive_text_color":"#e53935"}'
            )
        ))
```

### Expected behavior

The url returned from request must include start_param in url query string

### Actual behavior

The url returned from request not include start_param in url query string

### Telethon version

1.36.0

### Python version

3.10

### Operating system (including distribution name and version)

macOS

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

**Comment by braveltd** [comment]
Is there a way to fix that?

**Comment by Lonami** [comment]
This is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat). The chat contains questions and answers on how to use it.

**Comment by braveltd** [comment]
> Is there a way to fix that?

Use RequestWebAppViewRequest instead of RequestWebViewRequest!!
