### ISSUE TITLE
ReadHistoryRequest marks message as read but doesn't increase view counter

### ISSUE THREAD

**Issue by Lerbytech** [LonamiWebs/Telethon#447]
This issue is continuation of previous  #344  where  I've asked how to mark messages as read. 

Experimental layout is: two tg accounts. I have access two both of them from official telegram client app.
Account A is creator of _onetimechannel_
Account B is subscribed to this channel. 
I have python script which is connected to B - i can easily read messages.

If I send private message from A to B, I can easily read it and mark as read.
If A sends message to channel user B still can read it (get text) and mark as read.
Problem is that view counter doesn't increase in this case.

I can see this message in official app was not read before my script and after running it i see that there is no unread messages left. But number of views in channel is not increased. 
However, if I enter after this to channel from B's official app, number of views is increasing.
This means that something is missing in my workflow. But I don't know what.

To read private message I do this:
```
entity1 = clientP.get_entity('accountB') # entity of my channel for tests
messages = clientP.get_message_history(entity1, 100, None, 0, 0, 0, 0)
result = clientP(ReadHistoryRequest(entity1, messages[0]))
clientP.send_read_acknowledge(entity1, messages[1])
```

To read message from channel I do this:
```
entity1 = clientP.get_entity('onetimeshit') # entity of my channel for tests
messages = clientP.get_message_history(entity1, 100, None, 0, 0, 0, 0)
result = clientP(ReadHistoryRequest(entity1, messages[0]))
```
ReadHistoryRequest from _tl.functions.channels_ is capable to remove unread indicator of messages in channel. 
Perhaps to fullfill procedure and increase view counter i have to use 
`clientP.send_read_acknowledge(entity1, messages[1])`

But it throws exception)

> Traceback is:
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "C:/Users/Little-Dany/PycharmProjects/TG_ForTests/main.py", line 327, in <module>
>     test()
>   File "C:/Users/Little-Dany/PycharmProjects/TG_ForTests/main.py", line 288, in test
>     clientP.send_read_acknowledge(entity1, messages[1])
>   File "C:\Users\Little-Dany\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 597, in send_read_acknowledge
>     max_id=max_id
>   File "C:\Users\Little-Dany\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 439, in __call__
>     sender, call_receive, update_state, *requests
>   File "C:\Users\Little-Dany\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 530, in _invoke
>     raise next(x.rpc_error for x in requests if x.rpc_error)
> telethon.errors.rpc_error_list.PeerIdInvalidError: (PeerIdInvalidError(...), 'An invalid Peer was used. Make sure to pass the right peer type')
> 

I've tried to cast get_input_entity and create InputPeerChannel manually passing correct id and hash. Exceptions were the same. 

What are other types of Peer that I need to use?

**Comment by Lonami** [comment]
This has been asked so many times I opened a wiki page [just for that](https://github.com/LonamiWebs/Telethon/wiki/Increasing-View-Count) not long ago.
