### ISSUE TITLE
Update Handler for Chat Preview

### ISSUE THREAD

**Issue by shotnothing** [LonamiWebs/Telethon#4472]
### Describe your suggested feature

On telegram, for certain groups and channels you can view the messages without joining. The messages are updated in real time, as if you were in the group. In Telethon, `events.NewMessage` does not detect updates to said groups, and there is no way to listen for messages in a group you are previewing.

I don't know if this is an MTProto limitation, but I have not found a way to do this.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by shotnothing** [comment]
Relevant:

> The API will automatically send passive updates (i.e. as standalone [Updates](https://core.telegram.org/type/Updates) constructors in the socket) for channels/supergroups the user/bot is a member of.
> 
> However, clients (user accounts only) should also additionally invoke [updates.getChannelDifference](https://core.telegram.org/method/updates.getChannelDifference) periodically for channels and supergroups the user is currently viewing (i.e. explicitly opened channels/supergroups in one or more tabs/windows).

from https://core.telegram.org/api/updates#subscribing-to-updates-of-channels-supergroups

**Comment by Lonami** [comment]
Not planned for v1. In the meantime, you will need to call that request yourself, and probably inject or manually call the handlers-
