### ISSUE TITLE
Unable to send the buttons in the channel message. 

### ISSUE THREAD

**Issue by invinciible** [LonamiWebs/Telethon#4479]
### Code that causes the issue

```
@client.on(events.NewMessage(chats=CHANNELS["ds_new_pairs_solana"]))
async def handle_solana_message(event):
    try:
        message = event.message

        logger.info(f"Received new message from {CHANNELS['ds_new_pairs_solana']}")
        logger.debug(f"Message content: {message.text}")

        is_valid, contract_address = verify_solana_message(message.message)

        if is_valid:
            logger.info(
                f"Found valid Solana pair announcement from Raydium. Address: {contract_address}"
            )

            markup = ReplyInlineMarkup(
                rows=[
                    KeyboardButtonRow(
                        buttons=[
                            KeyboardButtonUrl(
                                text="🦅 Show chart & trades on DEX Screener",
                                url="https://dexscreener.com/solana/fxoodvswrs318ujcz6dxfrhqc9b3drqfh3z6nknpeu8f?utm_source=telegram&utm_medium=new-pairs",
                            )
                        ]
                    ),
                    KeyboardButtonRow(
                        buttons=[
                            KeyboardButtonUrl(
                                text="🐦 Twitter Search",
                                url="https://twitter.com/search?q=%24CmqHRVNNWXSVA83nCdMQ6quWd1MbHnXUcqAWV9KJpump",
                            )
                        ]
                    ),
                ]
            )

            # Send a new message with the same content and updated buttons
            await client.send_message(
                CHANNELS["target_channel"],
                "Pick one from this grid",
                parse_mode="md",
                buttons=markup,
            )

            logger.info(
                f"Sent new message to target channel {CHANNELS['target_channel']}"
            )
        else:
            logger.info("Message does not meet forwarding criteria")

    except Exception as e:
        logger.error(
            f"Error processing message from channel {CHANNELS['ds_new_pairs_solana']}: {str(e)}",
            exc_info=True,
        )

```

### Expected behavior

I'm trying to send the message recieved from one channel to another channel by doing some analysis. However, the buttons attached in the message aren't visible in the channel, only the message is sent. 

### Actual behavior

The messsage should be sent along with the buttons. 

### Telethon version

1.37.0

### Python version

3.12.5

### Operating system (including distribution name and version)

macOS 14.7

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by invinciible** [comment]
While the issue isn't in the SDK, can someone point out what's wrong. Tried asking GPT, claude and whatever code they shared tried it out yet no luck. 
`client = TelegramClient(SESSION_NAME, API_ID, API_HASH)
await client.start(phone=PHONE_NUMBER) 
#await client.start(bot_token=BOT_TOKEN)` Tried with both bot token and phone number.

**Comment by Lonami** [comment]
> While the issue isn't in the SDK,

I'll close the issue then. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
