### ISSUE TITLE
How to get type of channel message?

### ISSUE THREAD

**Issue by MasterGroosha** [LonamiWebs/Telethon#449]
Hello. Sorry for a stupid question, but I don't seem to find a solution anywhere.
Here is my code:
```python
username = 'telegram'
dp = client.get_entity(username)
messages = client.get_message_history(dp, limit=1)
msg = messages[1][0]
```

So `msg` is of type [Message](https://lonamiwebs.github.io/Telethon/constructors/message.html). Unfortunately it doesn't have any `type` field, so that I might detect whether it is a text post, photo, video, geolocation and so on (just like in Bot API).
I tried searching for "type message" issues and looking for "type" in [Telethon API](https://lonamiwebs.github.io/Telethon/index.html), however I see nothing useful.

Is it possible somehow (maybe invoking extra API request) to get type of message?

**Comment by Lonami** [comment]
Messages don't have a type. They can, however, have a [`media`](https://lonamiwebs.github.io/Telethon/types/message_media.html) of numerous types. Is that what you need?

**Comment by MasterGroosha** [comment]
They do have `media`, but even a text post can have them (f.ex. a YouTube video with in-app player).
So are you suggesting checking for media array and then "guessing" the type of message? Am I right, that [MessageMediaWebPage](https://lonamiwebs.github.io/Telethon/constructors/message_media_web_page.html), for example, can be only in "text" message?

**Comment by Lonami** [comment]
YouTube video with in-app player. That sounds to one of the [`entities`](https://lonamiwebs.github.io/Telethon/types/message_entity.html).

**Comment by Lonami** [comment]
And yes, [`MessageMediaWebPage`](https://lonamiwebs.github.io/Telethon/constructors/message_media_web_page.html) is used when Telegram shows a preview.

**Comment by MasterGroosha** [comment]
Just checked with YouTube link: an object `telethon.tl.types.MessageMediaWebPage` appears as a member of `media` (just for your information).

Also thank you very much for the answer (I honestly didn't know that Telegram Core API doesn't have any "type" field).

**Comment by Lonami** [comment]
A <kbd>Ctrl+F</kbd> on the [`scheme.tl`](https://github.com/LonamiWebs/Telethon/blob/HEAD/telethon_generator/scheme.tl) may sometimes be a better option than using the other search, which is only useful for type/function names, not searching for parameters.
