### ISSUE TITLE
Should wait error !

### ISSUE THREAD

**Issue by unkn19wn** [LonamiWebs/Telethon#45]
![image](https://cloud.githubusercontent.com/assets/12671628/24694650/fc51400e-19f7-11e7-9ef7-be75a5ecd2f2.png)

is there any idea how to fix this ?

**Comment by Lonami** [comment]
Yes, be careful when using Telegram's API and don't abuse it, i.e., don't make so many requests in such a short period of time.

Quoting from [API/Errors](https://core.telegram.org/api/errors#420-flood):
> `FLOOD_WAIT_X`: A wait of `X` seconds is required (where `X` is a number)
