### ISSUE TITLE
Problem using get_entity

### ISSUE THREAD

**Issue by farodrig** [LonamiWebs/Telethon#450]
Hi, I was trying to get an entity by the phone number but the library always throw:
`ValueError: Could not find user with username PHONE_NUMBER`

It always throw that because `client.session.entities._phone_id` is always empty (client is an instance of TelegramClient). Also, in `client.session.entities._username_id` are the phone numbers (besides usernames) that I need.

I don't know if I have to do something before to use get_entity to be able to get the entity by the phone number.

I must say that using the username I don't have any issues, it's just with the phone number. Besides, I previously check that the client is connected and the user is authorized.

I expect someone can help me.

(sorry for my english, I'm not a native speaker)

**Comment by Lonami** [comment]
Nobody is called [@PHONE_NUMBER](https://t.me/PHONE_NUMBER), so of course the library won't find it. Unless I'm taking you literally and `PHONE_NUMBER` is actually a phone number.

> in client.session.entities._username_id are the phone numbers (besides usernames) that I need.

That was a bug. What version are you using?

**Comment by farodrig** [comment]
PHONE_NUMBER was a representation of a phone number, because I'll not write the actual number.
Using your phone's representation would be:
`ValueError: Could not find user with username 34xxxxxxxxx`

The version I'm using is 0.15.4.

**Comment by Lonami** [comment]
See bug fixes https://github.com/LonamiWebs/Telethon/releases/tag/v0.15.5.
