### ISSUE TITLE
Server closed the connection: 0 bytes read on a total of 8 expected bytes

### ISSUE THREAD

**Issue by irhamdz** [LonamiWebs/Telethon#4501]
### Code that causes the issue

```
proxy = Proxy.from_str(proxy_str)

proxy_dict = dict(
    proxy_type=proxy.protocol,
    addr=proxy.host,
    port=proxy.port,
    username=proxy.login,
    password=proxy.password,
)

client = TelegramClient(
    session_path,
    API_ID,
    API_HASH,
    proxy=proxy_dict,
)
```

### Expected behavior

hide error log so its clean

### Actual behavior

Hi recently i got this error while using telethon with proxy
`Server closed the connection: 0 bytes read on a total of 8 expected bytes`

it doesn't affect the program but its makes the log dirty, 
how do I hide that message anyway?
ThanksI

### Telethon version

1.37.0

### Python version

3.10.14

### Operating system (including distribution name and version)

Ubuntu 20.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
I have no plans on changing the severity of this log. The `logging` module offers the ability to filter log messages though, and it's explained in the official Python documentation.
