### ISSUE TITLE
TypeError: 'type' object is not subscriptable while importing TelegramClient

### ISSUE THREAD

**Issue by DemonXpy** [LonamiWebs/Telethon#4507]
### Code that causes the issue

```from telethon import TelegramClient```

### Expected behavior

Importing TelegramClient from telethon

### Actual behavior

Literally raises TypeError when trying to import TelegramClient.

### Traceback

  File "../telegram.py", line 2, in <module>
    from telethon import TelegramClient
  File ".../.local/lib/python3.8/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File ".../.local/lib/python3.8/site-packages/telethon/client/__init__.py", line 15, in <module>
    from .uploads import UploadMethods  # Required for messages to send files
  File ".../.local/lib/python3.8/site-packages/telethon/client/uploads.py", line 103, in <module>
    class UploadMethods:
  File ".../.local/lib/python3.8/site-packages/telethon/client/uploads.py", line 137, in UploadMethods
    **kwargs) -> list[typing.Any] | typing.Any:
TypeError: 'type' object is not subscriptable

### Telethon version

1.3.8

### Python version

3.8.10

### Operating system (including distribution name and version)

Ubuntu 22.04

### Other details

Seems like line 137 in telethon/client/uploads.py must be 
`**kwargs) -> typing.List[typing.Any] | typing.Any:`
instead of 
`**kwargs) -> list[typing.Any] | typing.Any:`

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by DemonXpy** [comment]
My bad. Must be:
`**kwargs) -> typing.Union[typing.List[typing.Any], typing.Any]:`

**Comment by Lonami** [comment]
Fixed in https://github.com/LonamiWebs/Telethon/commit/9ca3b599fc28668ae25fd1674a63739ca8534f8f.
