### ISSUE TITLE
Where does a p2p message have its read/opened status?

### ISSUE THREAD

**Issue by menovikov** [LonamiWebs/Telethon#451]
Message appears to have no read_status related fields and doesn't show whether it was opened and read or not. Telegram api docs show that it should have a field "unread" https://core.telegram.org/constructor/message.
```

{'date': datetime.datetime(2017, 11, 21, 12, 46, 6),
 'edit_date': None,
 'entities': [],
 'from_id': 267118***,
 'fwd_from': None,
 'id': 86179,
 'media': None,
 'media_unread': False,
 'mentioned': False,
 'message': 'еще одно тестовое сообщение',
 'out': True,
 'post': False,
 'post_author': None,
 'reply_markup': None,
 'reply_to_msg_id': None,
 'silent': False,
 'to_id': {'user_id': 309401***},
 'via_bot_id': None,
 'views': None}
```

**Comment by Lonami** [comment]
I think it's a combination between **dialogs** and updates. Look for "read" in the [`scheme.tl`](https://github.com/LonamiWebs/Telethon/blob/master/telethon_generator/scheme.tl) just like I did until you find something useful. I don't actually know how this works.

**Comment by Lonami** [comment]
Yes I was right. It's a combination of dialogs and their `read_inbox_max_id` (and `read_outbox_max_id`) and handling updates properly. The official documentation which you linked is incredibly out of date so you shouldn't rely on it to see "what fields are available".
