### ISSUE TITLE
Need set or update Login email

### ISSUE THREAD

**Issue by Who-X1** [LonamiWebs/Telethon#4510]
### Describe your suggested feature

this very helpfull for secure our session file

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Who-X1** [comment]
@Lonami

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
