### ISSUE TITLE
Is it possible to update the login email in a Telethon session?

### ISSUE THREAD

**Issue by Who-X1** [LonamiWebs/Telethon#4511]
### Describe your suggested feature

Hello everyone,

I’m working with Telethon and I want to know if there’s a way to update or change the login email for an existing session. Has anyone encountered this situation, or is it possible to achieve this? If so, could you please share how to do it? Any help would be greatly appreciated!

Thank you in advance!

### Checklist

@Lonami 

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
