### ISSUE TITLE
Join Live of a Channel

### ISSUE THREAD

**Issue by johndoely** [LonamiWebs/Telethon#4512]
### Describe your suggested feature

Is there any possibility of adding a new function where we can get the user to join a channel Live stream?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
To the `TelegramClient`, no, I'm not adding new methods.

To the raw API, if it doesn't exist in https://tl.telethon.dev, it will exist once Telegram adds it and Telethon updates.
