### ISSUE TITLE
ValueError: Cannot find any entity corresponding to "name channel"

### ISSUE THREAD

**Issue by makc228383** [LonamiWebs/Telethon#4514]
### Code that causes the issue

case 5:
            reaction = "👍"
            userInput = "Путник из Будущего ANTI"
            reaction_count = {}
            total_reactions = 0  # Общий счетчик реакций
            session_counter = 1  # Счетчик для отслеживания текущей сессии (аккаунта)

            for account in accounts:
                session_index = accounts.index(account) + 1  # Индекс текущей сессии
                account_id = account.get_me().id
                nickname = account.get_me().first_name  # Получение никнейма аккаунта               
                for dialog in account.iter_dialogs():
                    if dialog.name == userInput:
                        for message in account.get_messages(dialog, limit=1):
                            account.send_read_acknowledge(dialog, message)
                        for message in account.get_messages(dialog, limit=1):
                            account(SendReactionRequest(peer=dialog.name, msg_id=message.id, reaction=[types.ReactionCustomEmoji(document_id=5224627162086136219)]))
                            print(f"Реакция '{reaction}' добавлена к сообщению в канале {dialog.title} с аккаунта {nickname} (сессия {session_index}/{len(accounts)}).")
                            delay_ms = random.randint(1000, 2000)
                            print(f"Ожидание {delay_ms/2000:.1f} секунд перед следующей реакцией")
                            time.sleep(delay_ms / 2000)
                session_counter += 1  # Переходим к следующей сессии

### Expected behavior

я хотел поставить реакции на приватный телеграмм канал, 

### Actual behavior

но у меня выдаёт данную ошибку. На других каналах бот спокойно работает.

### Telethon version

1.8

### Python version

3.12

### Operating system (including distribution name and version)

windows 10

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
