### ISSUE TITLE
Add `reply_from` field in MessageReplyHeader

### ISSUE THREAD

**Issue by dic1911** [LonamiWebs/Telethon#4517]
### Describe your suggested feature

As title, from the [doc](https://tl.telethon.dev/constructors/message_reply_header.html) it seems that I should be able to access `reply_from` in `reply_to`, but it seems that it's not there anymore.

```
Traceback (most recent call last): 
  File "/data/telethon/venv/lib/python3.12/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "/data/telethon/cleaner.py", line 470, in auto_admin
    if event.message.reply_to and event.message.reply_to.reply_from and event.message.reply_to.reply_from.from_id != 0:
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MessageReplyHeader' object has no attribute 'reply_from'
```

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
The TL reference you linked to always refers to the most-recent version of the library published to PyPi. Make sure to update.

**Comment by dic1911** [comment]
@Lonami I'm on 1.38.1, isn't that latest shown on PyPI?

**Comment by Lonami** [comment]
Please double check you're not accidentally using a different Telethon version from another environment:

```ts
import telethon
print(telethon.__version__)
```

I am confident that the field is there https://github.com/LonamiWebs/Telethon/blob/225ea9c3ab405db0e8665297a64b5c907627c933/telethon_generator/data/api.tl#L1325.

**Comment by dic1911** [comment]
Yeah I did search the source code and feel confused, huge thank for the tip of printing version in runtime as even `pip list` is showing 1.38.1, turns out it's indeed using 1.27.0 from elsewhere.
