### ISSUE TITLE
An error rising when i try to put a reaction with Telethon Python

### ISSUE THREAD

**Issue by qqiwi92** [LonamiWebs/Telethon#4518]
## Into
I was testing around with telethon, trying to make chatgpt analyse posts of a channel to place a reaction. I've got errors so i simplified it first (without ai stuff). So just place emojis on first 3 posts.

## Code
I've got something like this:
```python
from telethon import TelegramClient
from telethon.tl.types import ReactionEmoji
from telethon.tl.functions.messages import SendReactionRequest
import asyncio

api_id = "123"
api_hash = "some_hash"

channel_id = 123 

reaction_emoji = "🔥"

client = TelegramClient('anon', api_id, api_hash)

async def react_to_posts():
    try:
        async for message in client.iter_messages(channel_id, reverse=True, limit=3):
            # Skip messages that don't allow reactions or are service messages. The code works only with this condition
            # if not message.reactions:  # Skip service messages
            #     print(f"Skipping message ID: {message.id} - Not eligible for reactions")
            #     continue

            print(f"Reacting to message ID: {message.id}")
            try:
                await client(SendReactionRequest(
                    peer=channel_id, 
                    msg_id=message.id,  
                    reaction=[ReactionEmoji(emoticon=reaction_emoji)]
                ))
                await asyncio.sleep(1)
            except Exception as inner_error:
                print(f"Failed to react to message ID {message.id}: {inner_error}")

    except Exception as e:
        print(f"An error occurred: {e}")

with client:
    client.loop.run_until_complete(react_to_posts())

```

So it only works when i don't put an emoji on a post with no emojis and just skip them. Otherwise this error is being raised:

```bash
Failed to react to message ID 1: The specified message ID is invalid or you can't do that operation on such message (caused by SendReactionRequest)
```

How can i fix this? I am new to telethon, so I can be wrong. I would be glad get any response.

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

You are also using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

I personally don't know how reactions work, but I'll suggest fetching the message and printing the existing reactions. Perhaps the encoded emoji bytes are different.
