### ISSUE TITLE
MTProto proxy method not updated

### ISSUE THREAD

**Issue by ghost** [LonamiWebs/Telethon#4519]
### Describe your suggested feature

As far as i know, the current way that telethon handles mtproto proxies is using the old version of mtproro, therefore it only accepts proxies that have their secret value starting with "dd", for example:
```
client = TelegramClient(
    'session', api_id, api_hash,
    connection=connection.ConnectionTcpMTProxyAbridged,
    proxy=('cloudflare.com.nokia.com.co.uk.do_yo.want_to.clash_with.this.www.microsoft.com.there_is_no.place_like.localhost.www.bing.com.count_with_me.cyou.net.digikala.com.www.enamad.ir.www.google.com.again_to_fight.everyone.i_am.the_internet.voriaz-boriaz.info.',4550, 'DDBighLLvXrFGRMCBVJdFQRueWVrdGFuZXQuY29tZmFyYTrhdi5jb212YZ6ubmFqXeEuY29tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'))
```

the version above works because its using an old proxy, but the version below dosent work because its has a new mtproto proxy

```
client = TelegramClient(
    'session', api_id, api_hash,
    connection=connection.ConnectionTcpMTProxyAbridged,
    proxy=('82.153.35.247',85, '7gD_AA___wD_9VVf______VmLmtvLS0='))
```
with the code above, you get a valueerror on the secret part
im not a profesional but if you run both codes the issue is clear.

for testing:
channel with modern proxies: @iproxy
channel with old proxies(some posts contain them): @myporoxy

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
Support for "new" proxies is not planned.
