### ISSUE TITLE
Help forwarding a message from one group to another

### ISSUE THREAD

**Issue by dsldsl** [LonamiWebs/Telethon#452]
First off - THANK YOU for this amazing tool.  Do you accept donations?  Pls share Ether wallet address if so.

I am attempting to forward a chat message from one group to another.  I found some code that seems relevant from the wiki, however haven't been able to get it to work.  I'm using `ForwardMessagesRequest` 

I'm still using v 0.14 because of the issue with the null access hashes.

THANK YOU!

```from telethon.tl.types import InputPeerChat, InputPeerUser

data = client.get_message_history(entity, limit=100)
message = [1][0]
user = data[2][0]
client.invoke(ForwardMessagesRequest(
     from_peer=InputPeerUser(user.id, user.access_hash),  # who sent these messages?
     id=[message.id,],  # which are the messages?
     to_peer=InputPeerChat(bot_entity.id)  # who are we forwarding them to?
))
```

The error I'm getting is a MessageIdInvalidError ('The specified message ID is invalid):

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/dan/py3/lib/python3.6/site-packages/telethon/telegram_client.py", line 265, in invoke
    retries=kwargs.get('retries', 5)
  File "/Users/dan/py3/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 343, in invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_errors_400.MessageIdInvalidError: (MessageIdInvalidError(...), 'The specified message ID is invalid.')
```

So it says the message ID is invalid, yet when I look at the message object it has an ID and a message and all that.  

```
>>> message
<telethon.tl.types.Message object at 0x107293a20>
>>> message.__dict__
{'request_msg_id': 0, 'confirm_received': <threading.Event object at 0x107293320>, 'rpc_error': None, 'constructor_id': 0, 'content_related': False, 'out': None, 'mentioned': None, 'media_unread': None, 'silent': None, 'post': None, 'id': 180260, 'from_id': 470463409, 'to_id': <telethon.tl.types.PeerChannel object at 0x1072936a0>, 'fwd_from': None, 'via_bot_id': None, 'reply_to_msg_id': None, 'date': datetime.datetime(2017, 11, 22, 15, 31, 54), 'message': 'blahblah blah.', 'media': None, 'reply_markup': None, 'entities': None, 'views': None, 'edit_date': None, 'post_author': None}
```

**Comment by Lonami** [comment]
Can you format the code more nicely, and pay attention to the error see if you can fix it yourself. Also you're calling get history twice, when doing once works.

**Comment by dsldsl** [comment]
@Lonami updated code style.  I have been working at debugging and will continue to work at it.

**Comment by dsldsl** [comment]
@Lonami i did figure it out in the end.  Issue was that the first from_peer needs to be the channel it's from not the user it's from.  Will add wiki comment
