### ISSUE TITLE
UnboundLocalError: cannot access local variable 'entry' where it is not associated with a value

### ISSUE THREAD

**Issue by borkasm** [LonamiWebs/Telethon#4520]
### Code that causes the issue

A local variable `entry` is not defined in `messagebox.py`

```python
# Reset the deadline for the periods without updates for the given entries.
#
# It also updates the next deadline time to reflect the new closest deadline.
def reset_deadlines(self, entries, deadline):
    for entry in entries:
        if entry not in self.map:
            raise RuntimeError('Called reset_deadline on an entry for which we do not have state')
        self.map[entry].deadline = deadline

    if self.next_deadline in entries:
        # If the updated deadline was the closest one, recalculate the new minimum.
        self.next_deadline = min(self.map.items(), key=lambda entry_state: entry_state[1].deadline)[0]
    elif self.next_deadline in self.map and deadline < self.map[self.next_deadline].deadline:
        # If the updated deadline is smaller than the next deadline, change the next deadline to be the new one.
        # Any entry will do, so the one from the last iteration is fine.
        self.next_deadline = entry
    # else an unrelated deadline was updated, so the closest one remains unchanged.
```

### Expected behavior

Iterate through dialogs

### Actual behavior

An exception that causes disconnect

### Traceback

telethon.client.updates - ERROR - Fatal error handling updates (this is a bug in Telethon v1.37.0, please report it)
Traceback (most recent call last):
  File "/home/borkasm/.venv/athunt/lib/python3.11/site-packages/telethon/client/updates.py", line 461, in _update_loop
    users, chats = self._message_box.process_updates(updates, self._mb_entity_cache, processed)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borkasm/.venv/athunt/lib/python3.11/site-packages/telethon/_updates/messagebox.py", line 485, in process_updates
    self.reset_deadlines(reset_deadlines, next_updates_deadline())
  File "/home/borkasm/.venv/athunt/lib/python3.11/site-packages/telethon/_updates/messagebox.py", line 309, in reset_deadlines
    self.next_deadline = entry
                         ^^^^^
UnboundLocalError: cannot access local variable 'entry' where it is not associated with a value

### Telethon version

1.38.1

### Python version

3.11.2

### Operating system (including distribution name and version)

Debian 12.7

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
> this is a bug in Telethon v1.37.0, please report it

> **Telethon version** 1.38.1

Which one is correct?

**Comment by borkasm** [comment]
@Lonami if you look at the source code there’s a possibly undefined variable in the latest version (same problem on 1.37 and 1.38.1).
