### ISSUE TITLE
endless connection with a stable network

### ISSUE THREAD

**Issue by wowtelethonfew** [LonamiWebs/Telethon#4522]
### Code that causes the issue

import asyncio
import logging

from telethon import TelegramClient

logging.basicConfig(level=logging.DEBUG)

async def main():
    client = TelegramClient(
        session='session_name',
        api_id=2040,
        api_hash='b18441a1ff607e10a989891a5462e627',
    )
    await client.connect()
    print(await client.get_me())
    await client.disconnect()

asyncio.run(main())

### Expected behavior

telegram should return a reply

### Actual behavior

Telegram is not responding

### Traceback

DEBUG:asyncio:Using proactor: IocpProactor
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.40:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.40:443/TcpFull complete!
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7418190276776993808 to InvokeWithLayerRequest (2393d0fe840)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 92 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...

### Telethon version

1.38.1

### Python version

3.11.9

### Operating system (including distribution name and version)

Windows 10

### Other details

I know that the session is dead, presumably the problem is with the authkey. but I don't understand why a telegram can't give me an answer. Instead, I wait endlessly.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by wowtelethonfew** [comment]
о я нашел решение а вы ниче не получите

**Comment by erc20lzt** [comment]
помоги
