### ISSUE TITLE
How to search all messages by emoji?

### ISSUE THREAD

**Issue by qoakzmxncb** [LonamiWebs/Telethon#4523]
### Describe your suggested feature

I am trying to use the following function to search all messages:

``` python
async for message in client.search_all_messages(query='👇👇'):
```
However, it always raises the following error:
``` go
telethon._impl.client.errors.SearchQueryEmpty: rpc error 400: SEARCH_QUERY_EMPTY
```
Could you please help me understand why this happens and how to fix it?

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
The results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.
