### ISSUE TITLE
In documentation there is no method to findout channel username by its id

### ISSUE THREAD

**Issue by mohammad2611373** [LonamiWebs/Telethon#458]

**Comment by Lonami** [comment]
[There is](https://github.com/LonamiWebs/Telethon/wiki/Retrieving-an-entity).

**Comment by Lonami** [comment]
#457.

**Comment by mohammad2611373** [comment]
ValueError: Could not find the input entity corresponding to "PeerUser(user_id=1007801221)".Make sure you have encountered this peer before.

**Comment by mohammad2611373** [comment]
Channel is new I have seen it for the first time !

**Comment by Lonami** [comment]
If you want a **Channel** why are you using Peer**User**‽

**Comment by mohammad2611373** [comment]
same error
ValueError: Could not find the input entity corresponding to "PeerChannel(channel_id=1007801221)".Make sure you have encountered this peer before.

**Comment by Lonami** [comment]
The library won't magically get you any channel by their ID. You need to get dialogs first so the library can see the channel once.
