### ISSUE TITLE
How to authorize after sign up

### ISSUE THREAD

**Issue by cnekTep** [LonamiWebs/Telethon#466]
I sign up to  #Telegram
```
client = TelegramClient(username, api_id, api_hash)
client.connect()
client.send_code_request(phone)
client.sign_up(code, "name", "name")
```
Then I try to sign in and print information about me
```
client.sign_in(phone)
print(client.get_me())
```
But I get error
`telethon.errors.rpc_error_list.AuthKeyUnregisteredError: (AuthKeyUnregisteredError(...), 'The key is not registered in the system')`
How can I sign in without sending sms again?

**Comment by Deependrasg** [comment]
`client.sign_in(phone=phone)`

> Get OTP and use sign_up method
`client.sign_up(code='57724',first_name='abc',last_name='abc')`

**Comment by Lonami** [comment]
No @Deependrasg, calling `.sign_up()`:
https://github.com/LonamiWebs/Telethon/blob/6662f49bcbf7b7a1f0db855fe8c6a2fd883ac0b7/telethon/telegram_client.py#L225

Will return the new user on success:
https://github.com/LonamiWebs/Telethon/blob/6662f49bcbf7b7a1f0db855fe8c6a2fd883ac0b7/telethon/telegram_client.py#L244

So you're doing it right. You send the code, then you sign up. Now you're signed in. If then you call `.sign_in` again you need to re-enter the code. Just don't do that. `.sign_up` first time, `.sign_in` next.

**Comment by EgorXor** [comment]
got the same problem. i am  trying  to make auto-registrator
1)sign_up:

```
api_id ='id from another account'
api_hash = 'api_hash from another account'
client = TelegramClient('test', api_id, api_hash)
client.connect()
number='***'
client.send_code_request(number)
code=input('Enter code: ')
client.sign_up(code, 'name', 'surname')
```
here  i am using selenium to get new api_id and api_hash fot this account:
```
driver.get("https://my.telegram.org/auth")
driver.find_element_by_id("my_login_phone").send_keys(number)
driver.find_element_by_tag_name("button").click()
sleep(2)
chat = InputPeerUser(777000, access_hash=0)
messages = client.get_messages(chat)
print('message with code',messages)
print(messages[0])
password = messages[0].message.split(":")[1].split("\n")[1].split("\n")[0]
```
here i get : `chat = InputPeerUser(777000, access_hash=0)`  the following error :  
i```
nvoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.AuthKeyUnregisteredError: The key is not registered in the system
```
do i need to sign_in first ? 
i am using sms -registrators  so i have  only one sms code
