### ISSUE TITLE
get_entity by phone number

### ISSUE THREAD

**Issue by FlashAJ** [LonamiWebs/Telethon#467]
Why when using the code:
`user=client.get_entity('+xxxxxxxxxxx')` (instead of "x" digits)

an error is issued:
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 159, in _parse_key
>     return self._phone_id[phone]
> KeyError: 'xxxxxxxxxxx'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 182, in __getitem__
>     return self._entities[self._parse_key(key)]
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 164, in _parse_key
>     raise ValueError() from e
> ValueError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\telethon\telegram_client.py", line 1071, in _get_entity_from_string
>     return self.session.entities[entity]
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 184, in __getitem__
>     raise KeyError(key) from e
> KeyError: 'xxxxxxxxxxx'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\****.py", line 62, in <module>
>     user=client.get_entity('+xxxxxxxxxxx')
>   File "C:\Python34\lib\site-packages\telethon\telegram_client.py", line 1042, in get_entity
>     return self._get_entity_from_string(entity)
>   File "C:\Python34\lib\site-packages\telethon\telegram_client.py", line 1074, in _get_entity_from_string
>     'Could not find user with username {}'.format(entity)
> ValueError: Could not find user with username xxxxxxxxxxx

If use username them all normal

**Comment by Lonami** [comment]
What version?

**Comment by FlashAJ** [comment]
0.15.4.3

**Comment by FlashAJ** [comment]
So what?

**Comment by Lonami** [comment]
So upgrade.

**Comment by FlashAJ** [comment]
After upgrade nothing changed

**Comment by Lonami** [comment]
Are you sure of that? What version is it now? And what's the error now?

**Comment by FlashAJ** [comment]
0.15.5.7

**Comment by Lonami** [comment]
Okay but the error?

**Comment by FlashAJ** [comment]
Exactly the same

**Comment by Lonami** [comment]
Well it works on my machine.

**Comment by FlashAJ** [comment]
Ok. Now I will recheck. I'll try to restart Eclipse...

**Comment by FlashAJ** [comment]
Not work. All my code (maybe I missed something):
`from telethon import TelegramClient

api_id = xxxxxx
api_hash = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
phonenum = '+xxxxxxxxxxx'
client = TelegramClient('session_name', api_id, api_hash)
client.connect()
user=client.get_entity(phonenum)    # or '+xxxxxxxxxxx'
`
Trace error:

> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 159, in _parse_key
>     return self._phone_id[phone]
> KeyError: 'xxxxxxxxxxx'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 182, in __getitem__
>     return self._entities[self._parse_key(key)]
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 164, in _parse_key
>     raise ValueError() from e
> ValueError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Python34\lib\site-packages\telethon\telegram_client.py", line 1081, in _get_entity_from_string
>     return self.session.entities[entity]
>   File "C:\Python34\lib\site-packages\telethon\tl\entity_database.py", line 184, in __getitem__
>     raise KeyError(key) from e
> KeyError: 'xxxxxxxxxxx'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\***\workspace\telegram_copy\telegram_copy.py", line 54, in <module>
>     user=client.get_entity(phonenum)
>   File "C:\Python34\lib\site-packages\telethon\telegram_client.py", line 1052, in get_entity
>     return self._get_entity_from_string(entity)
>   File "C:\Python34\lib\site-packages\telethon\telegram_client.py", line 1084, in _get_entity_from_string
>     'Could not find user with username {}'.format(entity)
> ValueError: Could not find user with username xxxxxxxxxxx

**Comment by Lonami** [comment]
Are you 100% sure you don't have conflicting Python versions? Because this issue has been fixed.

**Comment by FlashAJ** [comment]
[https://image.prntscr.com/image/Q0Xk5H_sRyyxnqqf7QbgsA.jpeg](url)
[https://image.prntscr.com/image/tb7-A3itQTGAUO1ArrGBbQ.jpeg](url)
[https://image.prntscr.com/image/SgHe0YxtRw6DfQD8jFqhHg.jpeg](url)

**Comment by Lonami** [comment]
Still do:
```python
import telethon.version
print(telethon.version.__version__)
```

**Comment by FlashAJ** [comment]
0.15.5.7
https://image.prntscr.com/image/xHZCkGmyQLSOU9VwwDh-EA.jpeg

**Comment by Lonami** [comment]
Okay… are you sure that phone belongs to your contacts? How many contacts do you have?

**Comment by FlashAJ** [comment]
I try to take my number. Also one of the contact numbers.
The result is the same. The numbers are exactly the same as those indicated in user.phone (if parse by username), but with "+".

**Comment by Lonami** [comment]
Have you by any chance disabled the entity database? Could you add a few prints to the function to make sure get contacts is called or why it fails? I'm clueless.

**Comment by FlashAJ** [comment]
Where disabled/enabled the entity database?

**Comment by Lonami** [comment]
If you haven't done that then it should be enabled.

**Comment by FlashAJ** [comment]
I did not touch anything.) I installed the library as is

**Comment by FlashAJ** [comment]
Can you somehow transfer the numbers in PM so as not to swig in public? You would check them out. Maybe it's in them?

**Comment by Lonami** [comment]
I asked you to check other stuff first. But I would rather we not share mumbers at all. The code is indeed looking it up in the right dictionary after reading it more carefully so do what I said.

**Comment by FlashAJ** [comment]
I did not understand what and where to add? Sorry.

**Comment by Lonami** [comment]
> Could you add a few prints to the function to make sure get contacts is called or why it fails?

`telegram_client.py`, on `def get_entity`, check what the `EntityDatabase` of the `.session` contains before and after `GetContactsRequest` is called (and whether it's called at all).

**Comment by FlashAJ** [comment]
How to do it? What to insert? `EntityDatabase` there is no, like a `GetContactsRequest`...

**Comment by Lonami** [comment]
No, that's on `TelegramClient`. Best option is to use a debugger.

**Comment by FlashAJ** [comment]
I'm not so much an advanced coder, sorry. Can you tell me the actions ...?

**Comment by FlashAJ** [comment]
However, while I do not have time to understand this. I found another way out of the situation. To take information not by phone, but by ID
Thanx for help!

**Comment by Lonami** [comment]
Reopen if after merging `sqlite-session` branch this hasn't been fixed.

**Comment by tuxzz** [comment]
Problem still exists in version 0.18.0.3.

**Comment by Lonami** [comment]
What about 0.18.2.2?

**Comment by mrfinm** [comment]
hey guys i know its too late but i leave a message=)

you must add number to your telegram contacts and then try it ...
if that number did not exist in your contacts u cant get info

**Comment by y02DSS** [comment]
Hi guys! 
I find problem with creating contacts.
https://tl.telethon.dev/methods/contacts/import_contacts.html#examples
This document is not working...
