### ISSUE TITLE
UserFull object

### ISSUE THREAD

**Issue by maxim-smirnov** [LonamiWebs/Telethon#470]
According to this [page](https://core.telegram.org/constructor/userFull) `UserFull` class must have parameters like `real_first_name` and `real_last_name` but it doesn't, is it normal?

**Comment by Lonami** [comment]
Official docs are really outdated, we're on layer 73 and they're on 20-ish.

**Comment by maxim-smirnov** [comment]
Do you know, is it possible to get the real first name and last name which are set by user?

**Comment by Lonami** [comment]
@maxim-smirnov isn't first/last name enough?

**Comment by maxim-smirnov** [comment]
@Lonami telegram return names from contacts, can I get names which are set by user?

**Comment by Lonami** [comment]
@maxim-smirnov no. You need to remove them from your contacts or use an auxiliary bot.

**Comment by maxim-smirnov** [comment]
@Lonami thank you very much!
