### ISSUE TITLE
ImportError: No module named 'telethon.errors.rpc_error_list'

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [LonamiWebs/Telethon#472]
on first line when I try to 

import telethon

Thanks

**Comment by JohnPlayerSpecial** [comment]
can you please help me?
why closed without answer?

**Comment by JohnPlayerSpecial** [comment]
can you please give me an insight on how to use the library?
why do I get the import error?
thanks

Il 03 Dic 2017 13:47, "Lonami" <notifications@github.com> ha scritto:

**Comment by Lonami** [comment]
I don't know. You have provided nearly zero information and I'm not willing to help like this.

**Comment by ingria** [comment]
@JohnPlayerSpecial Seems like you've simply cloned this repo without running the code generator. Try installing this library with `pip3` instead.

**Comment by Lonami** [comment]
@ingria likely, thanks for helping out. Then again, I wish people provided more information. Or read the wiki as I strongly advice.
