### ISSUE TITLE
bug in telethon.telegram_client.TelegramClient download_media

### ISSUE THREAD

**Issue by dmitrdv** [LonamiWebs/Telethon#473]
Hi!

Telethon version: 0.15.4.3
channel = @abuddha
message id = 1170

when I try to call download_media for this message I get error:
'PhotoEmpty' object has no attribute 'sizes'

possible error here:
line 847, _download_photo

possible way to fix:
line 829, download_media change to "if isinstance(media, MessageMediaPhoto) and isinstance(media.photo, Photo):"

I checked last version and think that problem is still exists

Thank you

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/blob/152856dfbc9e3f8b4b29b171bad306236d7fc754/telethon/telegram_client.py#L831

Should instead be:
```python
if isinstance(media, (MessageMediaPhoto, Photo)):
```

https://github.com/LonamiWebs/Telethon/blob/152856dfbc9e3f8b4b29b171bad306236d7fc754/telethon/telegram_client.py#L844-L848

Should instead be:
```python
 def _download_photo(self, photo, file, date, progress_callback): 
     """Specialized version of .download_media() for photos""" 
  
    # Determine the photo and its largest size 
    if isinstance(photo, MessageMediaPhoto):
        photo = photo.photo
    if not isinstance(photo, Photo):
        return
```

Do you want to make a pull request?

**Comment by Lonami** [comment]
I'm guessing not.

**Comment by dmitrdv** [comment]
Hi!
Sorry. I am going to do it in NY holidays

**Comment by Lonami** [comment]
I just fixed it.

**Comment by dmitrdv** [comment]
ok thank you
