### ISSUE TITLE
How to show (print) all updated message automatically in my chat widow (In html page) .

### ISSUE THREAD

**Issue by Deependrasg** [LonamiWebs/Telethon#474]
> I  received all update to call add_update_handler method,
I want to show updated message on Html page but how i don't know,
```
`client.add_update_handler(update_handler)
    while True:
        try:
            update = client.updates.poll()
            if isinstance(update,UpdateShortMessage) == True:
                print('message',update.message) `
```
Here "print" show all updated message on terminal'
How to show (print) all updated message automatically in my chat widow (In html page) .

**Comment by Lonami** [comment]
That's not a problem with the library.

**Comment by Deependrasg** [comment]
I'ts right that's not a problem in library,I'm new in python and django can you give me idea to show updated output on window chat

**Comment by Lonami** [comment]
@Deependrasg not really, this isn't a help desk and you're not my client.

**Comment by Deependrasg** [comment]
i'm happy with your instant response and  thanks for telethon.
