### ISSUE TITLE
"hash" argument in GetParticipantsRequest

### ISSUE THREAD

**Issue by caleb0** [LonamiWebs/Telethon#475]
<img width="687" alt="m1mhxsn" src="https://user-images.githubusercontent.com/18242998/33584711-96606b1c-d99b-11e7-9efa-ba601580bb50.png">

I've looked a the documentation and the code, but still can't figure out  what this argument is supposed to be.All of the code examples I've looked at don't even have this as an argument

Help would be much appriciated. 
Thanks.

**Comment by Lonami** [comment]
0. It's in the wiki.
