### ISSUE TITLE
Session file is cleaned (The session file size is 0 KB)

### ISSUE THREAD

**Issue by chahooki** [LonamiWebs/Telethon#476]
In my application, after some days,  suddenly session file becomes 0 KB. I dont understand its problem. So, It should be deleted and the session file recreated again.

**Comment by Lonami** [comment]
> I dont understand its problem.

I don't either. No exception is caught:
https://github.com/LonamiWebs/Telethon/blob/1d19bb22a5a7cf4aafa768d4f535ecb7f245a57a/telethon/tl/session.py#L75-L94

**Comment by Lonami** [comment]
Closing hoping #506 fixed this.

**Comment by gambitov** [comment]
Dear @Lonami , I deleted session file, but now I cannot send messeges because my bot do not find entity. May you help me?
