### ISSUE TITLE
Handle CHANNELS_TOO_MUCH error

### ISSUE THREAD

**Issue by ingria** [LonamiWebs/Telethon#479]
It may be returned by the `channels.joinChannel` method, but  `ChannelInvalidError` is thrown instead of the `ChannelsTooMuchError`.

__UPD:__
Hmm, it seems like RPC returns `400: CHANNEL_INVALID` instead of the `400: CHANNELS_TOO_MUCH`.
Official Telegram apps throw the correct error (tested in Telegram Web)

![ssd](https://user-images.githubusercontent.com/2178368/33640264-9f2b3ae2-da40-11e7-951b-0ef684a79980.png)

**Comment by Lonami** [comment]
`CHANNELS_TOO_MUCH` is in the list of errors generated, <kbd>Ctrl+F</kbd> https://raw.githubusercontent.com/LonamiWebs/Telethon/master/telethon_generator/errors.json. So it's just the API being weird. See https://github.com/LonamiWebs/Telethon/wiki/API-Status.
