### ISSUE TITLE
Send Message type directly to entity

### ISSUE THREAD

**Issue by lopezm94** [LonamiWebs/Telethon#480]
I want to forward messages but without using the forward function of the API. The problem with forward messages is that replies dissapear. I have been looking into the source to hopefully find an internal function where you put a Message type and send it to an entity, but couldn't find such a thing.

I noticed that there 8 ways to make a send request (SendMediaRequest, SendMessageRequest, etc), and inside you need a type with several subtypes (InputMediaContact, InputMediaGame, etc). That would make for a lot of logic. Is there a simpler way?

**Comment by Lonami** [comment]
> but without using the forward function of the API.

Well that's impossible.

> The problem with forward messages is that replies dissapear.

Nothing you can do unless you forward the replies too.

> internal function where you put a Message type and send it to an entity

What?

> SendMediaRequest

https://github.com/LonamiWebs/Telethon/blob/1d19bb22a5a7cf4aafa768d4f535ecb7f245a57a/telethon/telegram_client.py#L620-L624

> SendMessageRequest

https://github.com/LonamiWebs/Telethon/blob/1d19bb22a5a7cf4aafa768d4f535ecb7f245a57a/telethon/telegram_client.py#L367-L372

> That would make for a lot of logic. Is there a simpler way?

Not really. `help(TelegramClient)` and have a nice day. PRs are welcome.
