### ISSUE TITLE
Any plans to upgrade to MTProto 2.0

### ISSUE THREAD

**Issue by matiniamirhossein** [LonamiWebs/Telethon#484]
Hello,
Thanks for your awesome library.

Is there any plan to upgrade to MTProto v2.0 ?

**Comment by Lonami** [comment]
@matiniamirhossein eventually.

**Comment by matiniamirhossein** [comment]
@lonami I don`t know how to thank you for this library; Implementing MTProto myself takes a lot of time and effort and also MadelineProto is a mess.

I didn't see much changed from MTProto v1.0 to 2.0 version.

I hope you update soon. Thanks <3

**Comment by Lonami** [comment]
I think we can keep this open until it's implemented, because it has to be done.

**Comment by danog** [comment]
Just a quick question, why do you think my client is a mess?
I am honestly interested, I am always open to constructive criticism.

**Comment by matiniamirhossein** [comment]
@danog The library which needs a lot of dependencies and needs whole php compilation and uses lot's of memory. 
Actually my friends are using your library and I'm thankful of you but I prefer this one because it's not heavy.

Madeline proto memory usage snapshot:
![image](https://user-images.githubusercontent.com/27870951/33811079-e1d45ee2-de22-11e7-8cbc-4434eb8c3bdd.png)

Code:
`<?php
ini_set('memory_limit', '-1');
declare(ticks=1);
$servername = "localhost";
$username = "<hidden>";
$pass = "<hidden>";
$dbname = "<hidden>";
$conn = mysqli_connect($servername, $username, $pass, $dbname);
mysqli_query($conn, "SET NAMES 'utf8'");
mysqli_query($conn, "SET CHARACTER SET 'utf8'");
mysqli_query($conn, "SET character_set_connection = 'utf8'");
require '/home/<hidden>/public_html/MadelineProtoBot/MadelineProto/vendor/autoload.php';
$arr = [
    'MTPROTO_SETTINGS' => ['app_info' => ['api_id' => '146424', 'api_hash' => '1d6aed4703fca6f41c52a2a415f5a473']]

];
if (file_exists("/home/<hidden>/public_html/session.madeline")) {
    echo "Exists";
    $MadelineProto = \danog\MadelineProto\Serialization::deserialize('/home/<hidden>/public_html/session.madeline');
} else {
    $MadelineProto = new \danog\MadelineProto\API($arr['MTPROTO_SETTINGS']);
    $MadelineProto->phone_login('<hidden>');
    sleep(70);
    $myfile = fopen("/home/<hidden>/public_html/update.txt", "r") or die("Unable to open file!");
    $authorization = $MadelineProto->complete_phone_login(fread($myfile, filesize("/home/<hidden>/public_html/update.txt")));
    if ($authorization['_'] === 'account.noPassword') {
        logger('a');
        throw new \danog\MadelineProto\Exception('2FA is enabled but no password is set!');
    }
    if ($authorization['_'] === 'account.password') {
        logger('b');
        $authorization = $MadelineProto->complete_2fa_login(readline('Please enter your password (hint ' . $authorization['hint'] . '): '));
    }
    if ($authorization['_'] === 'account.needSignup') {
        logger('c');
        $authorization = $MadelineProto->complete_signup(readline('Please enter your first name: '), readline('Please enter your last name (can be empty): '));
    }
    $MadelineProto->session = 'session.madeline';
    $MadelineProto->serialize('/home/<hidden>/public_html/session.madeline');
}

global $runningLoop;
$runningLoop = true;
pcntl_signal(SIGTERM, function ($signal)
{
    global $runningLoop;
    $runningLoop = FALSE;
});
while ($runningLoop) {
    $a = mysqli_query($conn, "SELECT * FROM channel");
    while ($row = mysqli_fetch_array($a)) {
        try {
            $me = null;
            $id = $row['id'];
            $last = $row['last'];
            $last = $last + 1;
            $last = $last - 1;
            $star = $row['star'];
            $dasteh = $row['dasteh'];
            $lang = $row['lang'];
            $messages_PeerDialogs = $MadelineProto->messages->getPeerDialogs(['peers' => ["$id"],]);
            $top = $messages_PeerDialogs['dialogs'][0]['top_message'];
            if ( $top-$last >= 100) {
                $last = $top - 100;
                mysqli_query($conn, "update channel set last=$last WHERE id='$id'");
            }
            while ($last < $top) {
                if ($top > $last) {
                    if ($top - $last >= 150) {
                        $top = $last + 150;
                    }
                    $ids=null;
                    for ($i = $last; $i < $top; $i++) {
                        $ids[] = $i;
                    }
                    $messages_Messages = $MadelineProto->channels->getMessages(['channel' => "$id", 'id' => $ids,]);
                    for ($i = 0; $i < count($ids); $i++) {
                        if ($messages_Messages['messages'][$i]['_'] == "message") {
                            if (array_key_exists("media", $messages_Messages['messages'][$i])) {
                                $me[] = $messages_Messages['messages'][$i]['id'];
                                $Updates = $MadelineProto->messages->forwardMessages(['from_peer' => "$id", 'id' => $me, 'to_peer' => "@<hidden>bot",]);
                                $me = null;

                            } else {
                                $date = $messages_Messages['messages'][$i]['date'];
                                $d = date("Y-m-d", $date);
                                mysqli_query($conn, "insert into posts VALUE ('$id','" . $messages_Messages['messages'][$i]['message'] . "',Null,'text',$star,$dasteh,'$d',true,$lang)");
                            }
                        }
                        mysqli_query($conn, "update channel set last=last+1 where id='$id'");
                        $last = $last + 1;
                    }
                    sleep(30);
                }
            }
        } catch (Exception $e) {
            $c = $e->getMessage();
            if (strstr($c, "Flood_wait")) {
                $id = preg_replace("/[^0-9]/", '', $c);
                sleep($id);
            }
        }
    }
}
`

**Comment by danog** [comment]
LMFAO I have never seen such high memory usage values on any instance of my client, probably you didn't use the getUpdates offset properly, not deleting old updates.
About the dependencies, any MTProto client (including this one) requires dependecies to handle big numbers, cryptography and VoIP, and compilation of native extensions is actually not needed, since native fallbacks are always used, where possible.

**Comment by Lonami** [comment]
>  dependecies to handle big numbers

Built into the language.

> cryptography

Mostly AES, RSA could be easily get cut away.

> VoIP

Not supported! But indeed would use libtgvoip.

**Comment by ingria** [comment]
Sorry for the offtop, but:

> I have never seen such high memory usage values 

I've experienced such memory issues too, before I switched to Telethon 🤷‍♂️ .

That happens because your library is serializing literally everything, even what's not really need to be serialized. As the PHP script is (usually) not intended to run as a daemon, one have to perform that resource-consuming _ioread-parsing-serialization-iowrite_ cycle very often.

**Comment by matiniamirhossein** [comment]
@ingria @danog @Lonami  I think madeline should definitely switch to mysql instead of serializing. Telethon does a good job in saving entities and you can disable saving entities but I think We should all use a mysql or sqlite3 database for telethon. That way the process is done on mysql. No more memory usage by php or python. and simply instead of parsing whole file and keep it into memory each time (Consider 500 groups with 5-13k members) we query database each time to only get the needed result.

**Comment by Lonami** [comment]
I thought of that too (using Python's `sqlite`). We could have a single database for *all* sessions, maybe in the home directory. But would this work out with several instances running at the same time accessing the database? Another option is a database per session, with just two tables, `session` (with the required information) and `entities`.

**Comment by matiniamirhossein** [comment]
@Lonami Definitely the way to go is database per session. I tried using a database file with multiple instances (with threading and multiprocess library) even with mysql which is thread safe pretty much you must create one connection per instance/thread.

**Comment by ingria** [comment]
I'd personally vote against that. Caching should be your app's responsibility, not the underlying lib's.

Maybe in something called `telethon-cli` that would be appropriate, along with convenient readline input, json output, sockets, etc.

**Comment by Lonami** [comment]
> Caching should be your app's responsibility, not the underlying lib's.

Okay, but there are a lot of people that would love to run `.get_entity('username')` without having to worry about `FloodWaitError` for a whole day. It's a *lot* more convenient to remember the `username` rather than the user ID (which I need to save anyway if you want to be able to get users by ID). So, I don't think letting *every* application reimplement this is a good idea, more when I can easily hook-up saving them in a straightforward way on the library. And yet, yes. You can disable this and re-implement it in your own application.

**Comment by ingria** [comment]
Yeah, of course it's convenient, yet not correct. Because username is not permanent and tend to change sometimes. Sometimes people even switch usernames between different entities – e. g. between the channel and the user. 

That's why there's no permanent caching in official telegram apps. Just saying.

**Comment by Lonami** [comment]
There isn't? The Android application can show all dialogs, people names, usernames and phones, even when you're connected to the network. I know they can change and it won't be 100% reliable but it's still convenient, while allowing of course a feature to force a re-fetch. And if all the updates are caught, the values will be updated to be correct. Just like I presume official clients do.

**Comment by Lonami** [comment]
MtProto 2.0 is actually trivial. Thanks again @delivrance, I was too lazy to understand the [official documentation](https://core.telegram.org/mtproto/description) which actually had nice pseudocode anyway.

**Comment by delivrance** [comment]
Python code ain't pseudocode :^)
