### ISSUE TITLE
Add a link to RTD and API docs

### ISSUE THREAD

**Issue by svenstaro** [LonamiWebs/Telethon#485]
You should add a link to http://telethon.readthedocs.io/en/latest/ and https://lonamiwebs.github.io/Telethon somewhere in your README as currently these resources are harder to discover than they need to be.

**Comment by Lonami** [comment]
I need to work some more on RTD before I link there.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/f2fbdc64164fcadd758032ec44ca149dcd5ceeeb
https://github.com/LonamiWebs/Telethon/commit/c039ba3e16bedfe7eaea87a8cac7c87dac3fc5d0
https://github.com/LonamiWebs/Telethon/commit/60594920bd0e1d56822f2474bfb56894c62a40e1
https://github.com/LonamiWebs/Telethon/commit/a489b4b18b76c0dccf22b85880505fd5ea54838e
https://github.com/LonamiWebs/Telethon/commit/9635a57683e418f6401a7366732bf65eaa1f9faf
https://github.com/LonamiWebs/Telethon/commit/cb45e8fca991b13e7e81cbef524ef0b34e5a4ed8

**Comment by svenstaro** [comment]
Cool stuff!
