### ISSUE TITLE
ChatAdminRequiredError when calling GetParticipantsRequest

### ISSUE THREAD

**Issue by petresdaniel** [LonamiWebs/Telethon#486]
I'm trying to fetch channel participants for a channel that I'm in although I'm not an admin in it. Is there a way to fetch these participants or I must be an admin to get the results?

`⁣``python

		offset = 0
		limit = 100
		channel = InputChannel(chat_id, chat_hash)
		all_participants = []

		while True:
			participants = client.invoke(GetParticipantsRequest(
				channel, ChannelParticipantsSearch(''), offset, limit
			))
			if not participants.users:
				break
			all_participants.extend(participants.users)
			offset += len(participants.users)

`⁣``

**Comment by Lonami** [comment]
Upgrade, it should work. If it doesn't you need indeed admin, or use other filters.

**Comment by petresdaniel** [comment]
I've upgraded it. Now it says:
`__init__()` missing 1 required positional argument: 'hash'
The channels access hash is not a valid format for it, and if I use the channel's access id it still says: ChatAdminRequiredError.

**Comment by Lonami** [comment]
@petresdaniel Use 0. It's in the wiki. You clearly don't have lonamiwebs.github.io/Telethon open.

**Comment by agorunucu** [comment]
Hey, did you solve the problem and how?

I got same problem with using ChannelParticipantsSearch('') method.

**Comment by khapota** [comment]
I got the same problem when calling this function. I think telegram removed it because I still cannot view channel members in native application.
