### ISSUE TITLE
Delete a Contact Using Telethon

### ISSUE THREAD

**Issue by mhrn007** [LonamiWebs/Telethon#488]
Hi , I'm wondering how can i delete a contact using telethon?
i already passed a user to Delete Contact request but i guess i should pass an id and i don't know how to retrive it.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/wiki/Retrieving-an-entity. You were half way there (getting to the right request), you just missed this. I guess.

**Comment by itJunky** [comment]
Can't find anything about deletion of contact from my buddy list.
Wiki on github is clear, and here https://telethon.readthedocs.io/en/stable/extra/basic/entities.html#getting-entities i'm don't see anything about deletion.

**Comment by Lonami** [comment]
@itJunky ask in the right place.

**Comment by itJunky** [comment]
Where the right place?

**Comment by Lonami** [comment]
StackOverflow or the [official group](t.me/telethonchat).
