### ISSUE TITLE
can not  encode to utf-8

### ISSUE THREAD

**Issue by parazitt** [LonamiWebs/Telethon#49]
hi when i call the "get_dialogs" return an error:

> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 394, in updates_thread_method
>     reader)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 225, in process_msg
>     return self.handle_gzip_packed(msg_id, sequence, reader, request)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 356, in handle_gzip_packed
>     request)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 243, in process_msg
>     return self.handle_update(msg_id, sequence, reader)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/network/mtproto_sender.py", line 253, in handle_update
>     tlobject = reader.tgread_object()
>   File "/usr/local/lib/python3.5/dist-packages/telethon/utils/binary_reader.py", line 128, in tgread_object
>     result.on_response(self)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/tl/types/updates_tg.py", line 64, in on_response
>     users_item = reader.tgread_object()
>   File "/usr/local/lib/python3.5/dist-packages/telethon/utils/binary_reader.py", line 128, in tgread_object
>     result.on_response(self)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/tl/types/user.py", line 168, in on_response
>     self.last_name = reader.tgread_string()
>   File "/usr/local/lib/python3.5/dist-packages/telethon/utils/binary_reader.py", line 92, in tgread_string
>     return str(self.tgread_bytes(), encoding='utf-8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 6: invalid start byte
> 

i check this problem and i found the "®" character in a user name.
i'll trying to resolve this problem and commit it

**Comment by Lonami** [comment]
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 6: invalid start byte
> i check this problem and i found the "®" character in a user name.

Using a Python shell:
```python
>>> '®'.encode('utf-8')
b'\xc2\xae'
```

So yes, that's the issue :P, But it's definitely strange because [I read all the bytes](https://github.com/LonamiWebs/Telethon/blob/master/telethon/utils/binary_reader.py#L90-L92) before actually converting it to a string. And I've never had issues sending or receiving any kind of strings?

> i'll trying to resolve this problem and commit it

Awesome then, I'll leave it to you. Keep me updated :)

**Comment by parazitt** [comment]
tnx a lot i replace line 92 in utils/binary_reader.py with:

>         try:
>             return str(self.tgread_bytes(), encoding='utf-8')
>         except:
>             pass

it worked fine :)

**Comment by Lonami** [comment]
I can't do that though. You should never simply ignore exceptions like that, and definitely not in a vital method like that. There has to be a better way to fix this.

**Comment by parazitt** [comment]
i know that, but for my target ignore is a best and shortest way. but for the others its may be Unpleasant,

**Comment by Lonami** [comment]
I tried adding `®` to the name of one of my contacts, and I don't have such issue. Not sure how I could test this.

**Comment by Lonami** [comment]
Trying with the example given by #67, I tried copying the text of the offending message, for then pasting it back (on Telegram itself, for instance). I noticed that, instead of crashing, it shows a � character. So maybe I could remove the offending part and replace it?

**Comment by Lonami** [comment]
Every day I'm more surprised with Telegram :^)

**Comment by gtavasoli** [comment]
I found a solution. Simply add `errors` parameter to `str` object in method `tgread_string`. 😎
The default value for this parameter is 'strict' that cause the exception.

```
def tgread_string(self):
    """Reads a Telegram-encoded string"""
    return str(self.tgread_bytes(), encoding='utf-8', errors='replace')
```
For more information ([Unicode Python 3](https://docs.python.org/3.3/howto/unicode.html))

![image](https://cloud.githubusercontent.com/assets/1962630/25635453/6cfda42c-2f93-11e7-8d59-5169c9621fa1.png)

**\ufffd** is equivalent to **�**

**Comment by Lonami** [comment]
Absolutely, I came accross that but the code confused me so I ignored it. Would you like to make a pull request yourself @gtavasoli?

**Comment by ykaner** [comment]
Is this issue solved?
I am using the newest 1.0.3 version and still get a similar error. It's caused by the name of a channel that includes an emoji, in the `stringify` method. 

> Traceback (most recent call last):
>   File "Telethon1.py", line 12, in <module>
>     print(contact.stringify())
>   File "C:\Users\ykane\AppData\Local\Programs\Python\Python35\lib\encodings\cp437.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_map)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f30d' in position 597: character maps to <undefined>
>

**Comment by Lonami** [comment]
That's an issue with your terminal, not the library.
