### ISSUE TITLE
Help wanted / Authentication questions

### ISSUE THREAD

**Issue by jcity** [LonamiWebs/Telethon#492]
I'm trying to build a script that will run every minute and check for new messages in a channel.

I tried the following last night but it appears that I have been banned or rate limited. I think I may be misunderstanding how the session/authentication system works.

```python
import os
import sys
import time

from telethon import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import InputPeerEmpty

TELEGRAM_API_ID = '<redacated>'
TELEGRAM_API_HASH = '<redacated>'
TELEGRAM_API_PHONE = '<redacated>'
TELEGRAM_API_CODE = <redacated>
TELEGRAM_API_PHONE_CODE_HASH = '<redacated>'
TELEGRAM_CLIENT_NAME = 'test_client'

telegramClient = TelegramClient(TELEGRAM_CLIENT_NAME, TELEGRAM_API_ID, TELEGRAM_API_HASH)
telegramClient.connect()
me = telegramClient.sign_in(phone=TELEGRAM_API_PHONE, code=TELEGRAM_API_CODE, phone_code_hash=TELEGRAM_API_PHONE_CODE_HASH)

last_date = None
chunk_size = 20
dialogs = []
users = []
chats = []
while True:
     result = telegramClient(GetDialogsRequest(offset_date=last_date, offset_id=0, offset_peer=InputPeerEmpty(), limit=chunk_size))

     print (result)
     time.sleep(2)
```

I ended up getting the following exception
```
telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 82529 seconds is required')
```

It was working the first few times I ran it. I received an authentication code to my existing client that I then used to login in. That makes me think that I was rate limited or something.

Is what I'm trying to do possible specifically:
* Login once, then re-use that session information so a login is not required for subsequent runs?

If so, is there any sample code I could look at?

Thanks in advance!

**Comment by Kyle2142** [comment]
This is gonna be flagged as RTFM
I suggest you check how .session files work, and perhaps use the login example...

**Comment by jcity** [comment]
@Kyle2142 where can I read how .session works?

**Comment by Lonami** [comment]
I'm not going to rewrite what I've already written in the wiki. If you don't have the time to read it, I don't have the time to help you.

**Comment by jcity** [comment]
A simple link to the wiki page you are referring to would be a lot more productive and helpful to other people that search these issues than a snarky response.

**Comment by Lonami** [comment]
Or you know you can do that yourself. I have better things to do than to give away my time for free.

**Comment by Lonami** [comment]
Fine you win. https://github.com/LonamiWebs/Telethon/wiki/RPC-errors. I admit `FloodWaitError` could be described better.

**Comment by jcity** [comment]
Actually, I think that's described just fine.

What I was looking for was the docs on how the sessions are persisted across script runs (if that is possible)

Thank you for your help.
