### ISSUE TITLE
Q: Update not handled on some mega groups

### ISSUE THREAD

**Issue by matiniamirhossein** [LonamiWebs/Telethon#493]
Hi,
I have a problem receiving updates from channels (megagroups).
When there is lot's of members any probably lot's of them are fake, we don't receive any updates!

I must open telegram desktop and sync state and after receivingUpdateReadChannelInbox(channel_id=1327242278, max_id=26565) it will work.

This also happens in telegram-cli.

Can you help me?

Update: somehow when I insert this code before while loop everything works!
`differences = client(GetChannelDifferenceRequest(
    channel=client.get_input_entity(PeerChannel(peer_id)),
    filter=ChannelMessagesFilterEmpty(),
    pts=53742, limit=1000
)) # type: ChannelDifference`

**Comment by davidmckenzie** [comment]
I'm likewise missing updates on large megagroups... curious where you inserted that code - guessing you're using a while loop for the messages instead of the client.idle() method?

**Comment by matiniamirhossein** [comment]
@davidmckenzie try loggin out all other sessions and only the telethon client logged in.
Tell me if it works

**Comment by davidmckenzie** [comment]
Unfortunately can't really test that at the moment, but looking into a workaround at the moment anyway.

Planning on recording the last message id received, then periodically doing a `GetHistoryRequest` with min_id as the last id received. Need to look into it a bit more first as I'm not too familiar with threaded python, and don't want to block the idle() loop. :)

**Comment by Lonami** [comment]
You could try to call `GetDifference` manually.

**Comment by Lonami** [comment]
Closing in favour of #237.
