### ISSUE TITLE
search channel 

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#497]
hi.
1- This channel (@behtarin_iran) is available in the telegram, but why not available in result search?
 ```python
result_search = client(SearchRequest('behtarin_iran', 10))
```

2- is there a way or API, I can find the entity of this channel?

**Comment by Lonami** [comment]
Uh sure `.get_entity('channel')`.

**Comment by printercu** [comment]
@Lonami does it work in `0.15.5.7`? I've copied group name from TelegramDesktop and `get_entity` throws `UsernameInvalidError`. Neither `telethon.tl.functions.contacts.SearchRequest` works. The only way for now is `get_dialogs(limit=None)`, but it does not return all dialogs on windows.
ps. Can not update to 0.16 because of breaking changes.

**Comment by Lonami** [comment]
Group name ≠ username. If you want to search by title, get all dialogs and look for it yourself. The search you mention probably works for contacts (and not dialogs).

**Comment by printercu** [comment]
Can you please help with `get_dialogs`. I'm new to python and I'm confused by getting different results in windows and linux. This code

```python
len(client.get_dialogs(limit=None)[0])
```

running the same time returns 433 in windows and 466 linux. So I can not find some chats by name :(

Linux has python 3.4.3, and in windows I've tried both 3.4.3 and 3.6.4.

**Comment by Lonami** [comment]
That's really strange. You should probably upgrade to `v0.16.1.x` though (your code would become `len(client.get_dialogs(limit=None))`). Please upgrade and test:

```python
dialogs = client.get_dialogs(limit=None)
print('total:', dialogs.total, '; have:', len(dialogs))
```

**Comment by Proteus86** [comment]
dialogs = client.get_dialogs(**limit=1**)
print('total:', dialogs.total, '; have:', len(dialogs))
total: 97 ; **have: 8**

dialogs = client.get_dialogs(**limit=10**)
print('total:', dialogs.total, '; have:', len(dialogs))

total: 97 ; **have: 13**
Telethon 0.18.0.2
That's really strange.

**Comment by Lonami** [comment]
It might be returning pinned dialogs always, I'll check.

**Comment by kingzez** [comment]
the same problem 
total: 375 ; have: 160

**Comment by Lonami** [comment]
You guys are posting this in a completely unrelated issue.

**Comment by vineetv2821993** [comment]
Hi, @Lonami How to find all channels by a keyword. As per this solution .get_entity('channel') I am getting a channel with a username='channel'

**Comment by vineetv2821993** [comment]
Following code also not providing the result.
client(SearchGlobalRequest(
        q='my_search_string',
        offset_date=None,
        offset_peer=InputPeerEmpty(),
        offset_id=0,
        limit=100
    ))

**Comment by Lonami** [comment]
The documentation showcases the right way to do it. If you can't find it there ask in StackOverflow.
