### ISSUE TITLE
Telegramm banned phone

### ISSUE THREAD

**Issue by Egor-Kotovsky** [LonamiWebs/Telethon#498]
I use method 
client = TelegramClient(phone_number, api_id, api_hash)
client.session.report_errors = False
client.raise_flood=False
client.connect()

client.sign_up(kod, name1, name2), but phone number blocked by telegramm. Why?
I used proxy, result was the same.

**Comment by Lonami** [comment]
Not an issue with the library.

**Comment by Afonichev** [comment]
Banned my number

`
import socks
import telethon
import datetime

from telethon import errors


def build_proxy(type, host, port, username, password, rdns=False):
    return type, host, port, rdns, username, password

phone = 7938*********
proxy = build_proxy(type=socks.SOCKS5,
                    host='37.*.*.165',
                    port=10000,
                    username='login',
                    password='password')

client = telethon.TelegramClient(session=str(phone),
                                 api_id=app_id,
                                 api_hash='app_hash',
                                 proxy=proxy)

if not client.is_connected():
    client.connect()

if not client.is_user_authorized():
    try:
        client.sign_in(phone=phone)
        try:
            client.sign_in(code=input('Enter code: '))
        except errors.SessionPasswordNeededError:
            client.sign_in(password='2fa_password')
    except errors.rpc_error_list.FloodWaitError as e:
        date = datetime.datetime.now() + datetime.timedelta(seconds=e.seconds)
        print('Работа аккаунта {0} приостановлена до {1}'.format(phone, date.strftime('%d/%m/%Y %H:%M:%S')))

if client.is_user_authorized():
    messages = client.get_messages('user_name_in_my_contact_list')
    for message in messages:
        print(message)
`

**Comment by mike-johnson-jr** [comment]
Did you ever get unbanned?
