### ISSUE TITLE
send_read_acknowledge for supergroup locks the update thread

### ISSUE THREAD

**Issue by LarsFox** [LonamiWebs/Telethon#501]
So I have a class that implements `TelegramClient` and a method with this code. I know that supergroups are not regular chats, but then there is this strange behavior.

```
print("Gets printed")
self.send_read_acknowledge(self.chats[self.supergroup], [update.message])
print("Never gets printed")
```

`self.chats` is a dictionary of entities based on their id. The third line actually never gets printed if I send the request this way. I have tried sending `ReadHistoryRequest`, `ReadMessageContentsRequest` and something else: the line gets printed then, but the unread messages counter never sets to zero.

The only successful way of removing the counter is to send a message to the supergroup (which is a thing of Telegram, I guess). Checked only with the web version of the client launched in a separate window.

I am really sorry if this has already been brought up, but so far I only found the issues for channels, not supergroups.

Thanks!

**Comment by Lonami** [comment]
Do you want to remove counter or mark messages as read (double check)? If the former, I have no idea, never tried doing that. I'll test whether this "blocks" my thread too, thanks for providing so much info.
