### ISSUE TITLE
disabled save in memory

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#502]
> The library will by default too save all the entities (users with their name, username, chats and so on) in memory, not to disk, so that you can quickly access them by username or phone number. 

I have a problem that after the Telethon runs, the amount of RAM consumed by the server increases.
I think the problem is this part.
How can I disable this?

**Comment by Lonami** [comment]
`save_entities=False` on the constructor. I think.

**Comment by alihossein** [comment]
i useing this code but I think this code only prevents being stored in the `Session` and not in memory
``` python
client = TelegramClient(...)
client.connect()
client.session.save_entities = False

**Comment by Lonami** [comment]
I said through the constructor not accessing the parameter. See https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/session.py and https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/entity_database.py.

**Comment by alihossein** [comment]
@Lonami 
i write this : 
``` python
client = TelegramClient(save_entities=False,session=session_path, api_id=api_id, api_hash=api_hash)
client.connect()
```
But I could not disable (enabled,enabled_full) through the constructor.
please help me.

**Comment by Lonami** [comment]
Wait for `sqlite-session` to be merged. I don't think entities are the problem though.

**Comment by alihossein** [comment]
@Lonami 
when useing 
``` python
client.session.entities.enabled = False

client.session.entities.enabled_full = False
```
the‍ ‍`get_entity` method return this exception :
``` python

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 915, in _get_entity_from_string
    return self.session.entities[entity]
  File "/usr/local/lib/python3.5/dist-packages/telethon/tl/entity_database.py", line 144, in __getitem__
    return self._entities[self._username_id[key]]
KeyError: 'tery_chnl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "schedules.py", line 124, in worker
    entity_channel = client.get_entity(channel.get('username').lower())
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 896, in get_entity
    return self._get_entity_from_string(entity)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 918, in _get_entity_from_string
    'Could not find user with username {}'.format(entity)
ValueError: Could not find user with username tery_chnl
```
my code :
``` python
client = TelegramClient(session=session_path, api_id=xxx, api_hash='xxx',)

client.session.entities.enabled = False
client.session.entities.enabled_full = False
client.connect()
entity = client.get_entity('tery_chnl')
```

**Comment by Lonami** [comment]
@alihossein you're using an old version anyway.

**Comment by alihossein** [comment]
yes my app work with `Telethon==0.15.5.7
`

**Comment by Lonami** [comment]
@alihossein I don't support old versions though.
