### ISSUE TITLE
error return without exception set

### ISSUE THREAD

**Issue by hamid07ss** [LonamiWebs/Telethon#503]
### Reproducing code example:
```
client(ForwardMessagesRequest(
                from_peer=fwd_from,
                id=[int(msg_id)],
                to_peer=peer_fwd))
```

### Error message:
```
Exception ignored in: <generator object TelegramBareClient._invoke.<locals>.<genexpr> at 0x0724FD80>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 505, in <genexpr>
    while not all(x.confirm_received.is_set() for x in requests):
SystemError: error return without exception set
```

error occurred on upgrade to last Telethon version

**Comment by Lonami** [comment]
This error seems related to writing C code (see https://bugs.python.org/issue1195984). But the library doesn't use any C besides `libssl` if available, and the code where this errors is nowhere near that.

**Comment by delivrance** [comment]
What Python interpreter are you using? Because this is an internal Python error: https://docs.python.org/3/library/exceptions.html#SystemError

**Comment by hamid07ss** [comment]
` What Python interpreter are you using?  ` Python 3.6.3

I was working on the old version and this problem was not there.
but today I remove Telethon source and install with:

> pip install Telethon

after this update that error occurred.

**Comment by Lonami** [comment]
Can you reproduce consistently? What was the working version?

**Comment by hamid07ss** [comment]
My prev version is: `0.13.6`

**Comment by Lonami** [comment]
> Can you reproduce consistently?

**Comment by Lonami** [comment]
It has been a while, please reopen if it still happens in the latest version. If it does, also provide a `DEBUG` log like so:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
...
```
