### ISSUE TITLE
Forwaring messages from user chat to my boy chat

### ISSUE THREAD

**Issue by etnic90** [LonamiWebs/Telethon#507]
In this code I just try to retrieve last messages from an user chat and forward them to my bot:

    source_chat_id = "here i put the user id"
    source_hash = "here i put his access_hash"

    source_chat = InputPeerUser(source_chat_id, source_hash)
    total_count, messages, senders = client.get_message_history(
                source_chat, limit=10)

    for msg in reversed(messages):
    print ("msg:", msg.id, msg)

    msg = messages[0]    
    print ("msg id:", msg.id)

    dest_chat = "here i tried to put  my bot ID"   

    result = client.invoke(ForwardMessagesRequest(from_peer=source_chat, id=[msg.id], random_id=[generate_random_long()], to_peer=dest_chat))

The print was correct but i didn't receive anything to my bot chat. I know that there will be a lot of errors so please be patient and sorry.

**Comment by Lonami** [comment]
Can't see anything wrong. Ask in [@TelethonChat](https://t.me/TelethonChat) maybe.

**Comment by etnic90** [comment]
On dest_chat variable is it right to put directly my bot ID?

Or maybe I have to put this string: 

    dest_chat = get_input_peer("my bot ID")
