### ISSUE TITLE
invite user to channel

### ISSUE THREAD

**Issue by justxor** [LonamiWebs/Telethon#508]
i am trying to invite user to  my channel (i am admin).
 from telethon.tl.functions.channels import InviteToChannelRequest
 cl=client.get_entity('username') 
 channel=client.get_entity('channelname') 
 z=[]
 z.append(cl)
 client(InviteToChannelRequest(channel=channel,users=z)) 

The error that I get when I run this is:

[    client(InviteToChannelRequest(channel=channel,users=z))
  File "/home/lav/.local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 439, in __call__
    sender, call_receive, update_state, *requests
  File "/home/lav/.local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 530, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.ChatWriteForbiddenError: (ChatWriteForbiddenError(...), "You can't write in this chat")](url)

How to fix it ?

**Comment by Lonami** [comment]
What you should fix is the formatting of your issue.

**Comment by justxor** [comment]
@Lonami  formatted it

**Comment by Lonami** [comment]
> How to fix it ?

I have no idea. You seem to be doing it right, but the API is for some reason refusing to do it because you "don't have permission". Ask in [@TelethonChat](https://t.me/telethonchat), I don't know the answer.

**Comment by justxor** [comment]
@Lonami thanks for response . This one worked :
```
 from telethon.helpers import get_input_peer

client.invoke(InviteToChannelRequest(
    get_input_peer(client.get_entity(chan),
    [get_input_peer(client.get_entity(user))]
))

```

**Comment by Lonami** [comment]
`get_input_peer(client.get_entity(...))` is redundant. Just do `client.get_input_peer(...)`.

**Comment by justxor** [comment]
@Lonami 

now i am trying to add 200 users to my channel
```
chann=client.get_entity('bitfut')
for i in range (0,200):
  try:
  

      client.invoke(InviteToChannelRequest((chann),[(client.get_entity(w))]))
      print(w)
      time.sleep(1*90)
  except Exception as e :
      print(e)
 
      time.sleep(3*30)
   
```
after  added 20 or 25  i am got the following error:
```
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 77439 seconds is required')
```
what should i do to avoid this error? i tried assigned time.sleep more but  it wont helped .

**Comment by Lonami** [comment]
> what should i do to avoid this error?

Not abusing the API.
