### ISSUE TITLE
Increase get_dialogs limit

### ISSUE THREAD

**Issue by parazitt** [LonamiWebs/Telethon#51]
Hello agian,
i tried to get_dialogs(200) but it limit on 99 and not show more, how i can get more?
tank you

**Comment by Lonami** [comment]
[Telebackup shows how](https://github.com/LonamiWebs/Telebackup/blob/master/gui/windows/select_dialog_window.py#L88-L111).

**Comment by parazitt** [comment]
helpful
tank you again
