### ISSUE TITLE
Debugging sign_in failure

### ISSUE THREAD

**Issue by LeeHJones** [LonamiWebs/Telethon#516]
First, thank you for the library. It's invaluable and I wouldn't be able to do this project without it. 

Now, my problem: 

I have written an uber-light client for the purposes of forwarding messages from one channel to another. When I run it on my account and a test account I have, it works fine. But when I try to run it pointing to colleagues' accounts, the sign_in() call fails. I can't tell why it's failing - just the return is coming back "None". 

When I run it using a colleague's account, it sends her a code via Telegram, she copies and pastes it to me, and I enter it into the client below. That works perfectly for my accounts, but fails for hers.

The relevant code is below. I have two questions:

- Can anybody quickly think why it might work with a couple of accounts but fail with others? One thing: the two accounts that work are both US-based (+1...), the two that are failing are UK-based (+44...). I can't imagine it should matter - the phone numbers are just a way of identifying people.
- How can I modify my code to better spot the problem? Are there exceptions I'm not catching?

Thanks in advance,
Lee

```
if (not client.is_user_authorized()): # need to sign in
    print('First run. Sending code request...')
    client.sign_in(phone=tgramPhone)
    myself = None
    tries = 0
    while ((myself is None) and (tries < maxTries)):
      tries += 1
      pinCode = input('Enter the code you just received: ')
      try:
        myself = client.sign_in(phone=tgramPhone,code=pinCode)

        # Two-step verification may be enabled, and .sign_in will
        # raise this error. If that's the case ask for the password.
      except SessionPasswordNeededError:
        pw = input('Two step verification is enabled. Please enter your password: ')

    if (myself == None):
      print("!ERROR: Unable to sign into userid " + userName + " on phone # " + tgramPhone)
      sys.exit(1)
    else:
      print("SUCCESS - logged into " + userName + " using phone number " + tgramPhone)

```

**Comment by Lonami** [comment]
You could try [enabling logging](https://github.com/LonamiWebs/Telethon/wiki/Enabling-logging). You say it fails only for certain phone numbers? That's quite strange.

**Comment by LeeHJones** [comment]
Well. Logging has helped a lot, but I'm really confused. Here are the messages:
```
Enter the code you just received: 57006
DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Read RPC error: (PhoneCodeExpiredError(...), 'The confirmation code has expired')
```
I promise it was a matter of 30 seconds or less (probably 15 seconds or less) before I got the code from my colleague and put it in. Does telethon set the timeout time, or is that set at a lower layer?

Thanks, Lee

**Comment by Lonami** [comment]
> I promise it was a matter of 30 seconds or less (probably 15 seconds or less)

Yeah, I can believe that, I think I saw this before but I can't remember where sorry. Maybe the system time is different? You said it's an UK phone so perhaps…

**Comment by LeeHJones** [comment]
Sure - system time is different, but I don't see how that affects it. They're sending a 5-digit confirmation code to a Telegram user somewhere. I suppose it's possible that they freak out if the system time for the machine running the client is different than that for the client that is receiving the code. 

Anyway, this gives me a lot more to go on - thank you so much.

**Comment by LeeHJones** [comment]
_I think I saw this before but I can't remember where sorry. Maybe the system time is different? You said it's an UK phone so perhaps…_

Looks like [this](https://github.com/LonamiWebs/Telethon/issues/172) might be similar. I need to try a random user who's in the same time zone with me, and apparently even a time drift of a few seconds may be enough. 

I'll let you know if that resolves the problem.
