### ISSUE TITLE
Get message history - To many values to unpack

### ISSUE THREAD

**Issue by 4k4zh** [LonamiWebs/Telethon#518]
I am getting
`too many values to unpack (expected 3)`

when calling

`total, messages, senders = client.get_message_history(from_peer, limit=20)`

The same code is working fine with another telegram account, but in one specific number I am getting the above error. I am sure my from_peer is correct and the error is in no other part of the code.
What could be the issue?

**Comment by Lonami** [comment]
The issue is you don't read the changelog. https://github.com/LonamiWebs/Telethon/releases/tag/v0.16.
