### ISSUE TITLE
Script not working properly on background.

### ISSUE THREAD

**Issue by underscrew** [LonamiWebs/Telethon#522]
Hi!

My script is running smoothly, It does works flawlessly receiving and interacting, but when I try to run it on background using `python3 myscript.py &`, I can see it connects successfully but it doesn't receive any message.

What could it be?
  
I am using the function `def update_handler(update):` to get the updates.

**Comment by Lonami** [comment]
I have no idea.

**Comment by matiniamirhossein** [comment]
Try this:
'nohup python3 app.py > /dev/null 2>&1 &'

I think you have some input/output which closes and causes termination.

**Comment by underscrew** [comment]
@matiniamirhossein No success. 👎

**Comment by underscrew** [comment]
@matiniamirhossein and @Lonami: the problem was using the input waiting to end the script.
I used a while True with a sleep instead and it is ok now.
Is there any other better method I can use there, such as a threading.join()? Or is this sleep OK?

Thanks for the help, guys.

**Comment by Lonami** [comment]
Joining a thread will wait until it finishes (at which point it will join). Not sure what your use case is exactly, sleep is okay, but you might want to use `.idle()` instead so the thread is doing something useful.

**Comment by renanfilipe** [comment]
@underscrew I'm trying to run my script on the background of an amazon web service and I'm having the same issue that you had. Can you show me the code that you used on your while true?
