### ISSUE TITLE
reach private channels 

### ISSUE THREAD

**Issue by aydinsenih** [LonamiWebs/Telethon#529]
hi,
I`m using #client.get_message_history# for get messages from channel or chats but 
if I want to reach private channel`s messages which is I`m in the member of the channel
I can`t get any messages because private channels don`t have ID
I read documentation but I didn`t find any other way to get messages 
Does your lib have any support for this

thanks

**Comment by Lonami** [comment]
>  Does your lib have any support for this

[Yes](http://telethon.readthedocs.io/en/latest/extra/basic/entities.html#getting-entities).
