### ISSUE TITLE
Channel message lost (not appearing in update)

### ISSUE THREAD

**Issue by underscrew** [LonamiWebs/Telethon#531]
Hi!
I am monitoring the updates of a private channel (1k subscribers).
Sometimes I get the updates from this channel and sometimes i do not.

I know the channel id may change, but I am monitoring by its title using `client.get_entity(PeerChannel(update.message.to_id.channel_id)).title`

Is it already reported or it is only with me?

Oh, I had this same problem with pytg.

**Comment by Lonami** [comment]
> I know the channel id may change, but I am monitoring by its title using `client.get_entity(PeerChannel(update.message.to_id.channel_id)).title`

Actually, the ID won't change. What may change is `.get_title()`. Also, if you're calling `.get_entity()` every time an update occurs, that's a killer. Save the ID somewhere, and compare the ID instead.

If after doing this the error still happens please discuss it on #237 as more people is having the issue.
