### ISSUE TITLE
Joining a private chat or channel

### ISSUE THREAD

**Issue by xates** [LonamiWebs/Telethon#536]
I have read the docs, however, the information about [Joining a private chat or channel](http://telethon.readthedocs.io/en/latest/extra/examples/chats-and-channels.html#joining-a-private-chat-or-channel) is incomplete.
After the phrase _"Now you can use ImportChatInviteRequest as follows:"_ there is no example and a new paragraph starts.

I tried with the same method as for public channels
```python
channel = 'https://t.me/joinchat/AAAAAFH0lxxxJ-VTxxxj6w'
client(JoinChannelRequest(client.get_input_entity(channel)))
```
but I expectedly get an error
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    client(JoinChannelRequest(client.get_input_entity(channel)))
  File "/home/me/ve/lib/python3.5/site-packages/telethon/telegram_client.py", line 1359, in get_input_entity
    return utils.get_input_peer(self._get_entity_from_string(peer))
  File "/home/me/ve/lib/python3.5/site-packages/telethon/utils.py", line 85, in get_input_peer
    _raise_cast_fail(entity, 'InputPeer')
  File "/home/me/ve/lib/python3.5/site-packages/telethon/utils.py", line 78, in _raise_cast_fail
    type(entity).__name__, target))
TypeError: Cannot cast bool to any kind of InputPeer.
```

So, what should be the correct way to join a private channel?

**Comment by Lonami** [comment]
Like it says you need to use [`ImportChatInviteRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/import_chat_invite.html). The `hash` is the part after `/joinchat/`, that is, `'AAAAAFH0lxxxJ-VTxxxj6w'`. So… `client(ImportChatInviteRequest('AAAAAFH0lxxxJ-VTxxxj6w'))`. I'll update the docs.

**Comment by Lonami** [comment]
Actually that's weird. The example is there but RST is *so* picky…:
https://raw.githubusercontent.com/LonamiWebs/Telethon/c12af5e41296ae84349f6b2c1df3b2feb5ee762f/readthedocs/extra/examples/chats-and-channels.rst

**Comment by xates** [comment]
Wow! You've been super fast! And it was that easy...
However, it still doesn't seem to work...

It seems the problem is in the `get_input_entity` method because this doesn't work either:

```python
invite = 'https://t.me/joinchat/AAAAAFH0lyGeJ-VTaTaj6w'
channel = client.get_input_entity(invite)
```
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    channel = client.get_input_entity(invite)
  File "/home/me/ve/lib/python3.5/site-packages/telethon/telegram_client.py", line 1359, in get_input_entity
    return utils.get_input_peer(self._get_entity_from_string(peer))
  File "/home/me/ve/lib/python3.5/site-packages/telethon/utils.py", line 85, in get_input_peer
    _raise_cast_fail(entity, 'InputPeer')
  File "/home/me/ve/lib/python3.5/site-packages/telethon/utils.py", line 78, in _raise_cast_fail
    type(entity).__name__, target))
TypeError: Cannot cast bool to any kind of InputPeer.
```
Otherwise I guess I'm missing something here...

**Comment by xates** [comment]
> Actually that's weird. The example is there but RST is so picky…

Hmm, that's odd...
