### ISSUE TITLE
Supporting secret chats in Telethon

### ISSUE THREAD

**Issue by ehsanonline** [LonamiWebs/Telethon#537]
BountySource: https://www.bountysource.com/issues/53732854

**Comment by Lonami** [comment]
Nope, not yet. Note that even if it were possible, your existing secret chats would not show (they are **per device**), and you would need to create new ones.

**Comment by ehsanskyboy** [comment]
thanks for your fast answer! it's ok that they are per device. i'm trying to make a gui python telegram client.

**Comment by a000a** [comment]
Just found this:
https://github.com/painor/telethon-secret-chat
maybe it's a start

**Comment by Lonami** [comment]
Yes, that's what solves this issue, just haven't had the time to test it.

**Comment by Lonami** [comment]
@painor's [telethon-secret-chat](https://github.com/painor/telethon-secret-chat) repository is the solution to this issue 🎉. Use it if you need secret chats in Telethon. It won't be a builtin because I believe it's bloat for most people, and can be separatedly installed if needed.

**Comment by Lonami** [comment]
(Trying to work out BountySource…)

**Comment by rnyPlanet** [comment]
> @painor's [telethon-secret-chat](https://github.com/painor/telethon-secret-chat) repository is the solution to this issue 🎉. Use it if you need secret chats in Telethon. It won't be a builtin because I believe it's bloat for most people, and can be separatedly installed if needed.

is there an example when? I am trying to send SMS to a secret chat but it does not send (

**Comment by FaazAbidi** [comment]
Is there a simple example code for creating a secret chat and sending a secret message? I'm following the given example but it's not working for me. @Lonami

**Comment by FaazAbidi** [comment]
The code below creates a chat but it's not sending a message. It says that chat not found. Anyone? @Lonami

![prob](https://user-images.githubusercontent.com/57310134/120793009-c863bd00-c54f-11eb-994b-4855116a0fc4.JPG)

**Comment by simplPart** [comment]
> The code below creates a chat but it's not sending a message. It says that chat not found.

same

**Comment by painor** [comment]
that code starts a secret chat. the chat is not created until the other party accepts it. so you can't send a message until they accept and the start method does not return a chat but a simple temporary id used to then accept the chat. you need to use events for this.

**Comment by FaazAbidi** [comment]
> that code starts a secret chat. the chat is not created until the other party accepts it. so you can't send a message until they accept and the start method does not return a chat but a simple temporary id used to then accept the chat. you need to use events for this. 

Thank you @painor! Is there a chance you can show me with a simple example? I'm lost.

**Comment by painor** [comment]
as you can see in the example in https://github.com/painor/telethon-secret-chat there is an event for when a chat is accepted/created 
```python
async def new_chat(chat, created_by_me):
    if created_by_me:
        print("User {} has accepted our secret chat request".format(chat))
    else:
        print("We have accepted the secret chat request of {}".format(chat))
```
when the user accepts a chat that you started the first if will work and you can use that chat variable to send messages to them.

**Comment by FaazAbidi** [comment]
Got it! Thank you

**Comment by notplayer777** [comment]
> as you can see in the example in https://github.com/painor/telethon-secret-chat there is an event for when a chat is accepted/created
> 
> ```python
> async def new_chat(chat, created_by_me):
>     if created_by_me:
>         print("User {} has accepted our secret chat request".format(chat))
>     else:
>         print("We have accepted the secret chat request of {}".format(chat))
> ```
> 
> when the user accepts a chat that you started the first if will work and you can use that chat variable to send messages to them.



I am trying to send a message in the created chat, but I get a message that the chat has been canceled



Task exception was never retrieved
future: <Task finished name='Task-12' coro=<new_chat() done, defined at E:/Programirovanie/Python_project/Sender/secret.py:58> exception=EncryptionDeclinedError('The secret chat was declined (caused by SendEncryptedRequest)')>
Traceback (most recent call last):
  File "E:/Programirovanie/Python_project/Sender/secret.py", line 60, in new_chat
    await manager.send_secret_message(chat, "I am Bob")
  File "E:\Programirovanie\Python_project\Sender\venv\lib\site-packages\telethon_secret_chat\secret_methods.py", line 419, in send_secret_message
    res = await self.client(
  File "E:\Programirovanie\Python_project\Sender\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "E:\Programirovanie\Python_project\Sender\venv\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.EncryptionDeclinedError: The secret chat was declined (caused by SendEncryptedRequest)

**Comment by SMotlaq** [comment]
> as you can see in the example in https://github.com/painor/telethon-secret-chat there is an event for when a chat is accepted/created
> 
> ```python
> async def new_chat(chat, created_by_me):
>     if created_by_me:
>         print("User {} has accepted our secret chat request".format(chat))
>     else:
>         print("We have accepted the secret chat request of {}".format(chat))
> ```
> 
> when the user accepts a chat that you started the first if will work and you can use that chat variable to send messages to them.

Hi, I can't realize how can I create a "new message" event in secret chats. Would you mind helping me? Thanks
