### ISSUE TITLE
Odd msg_seqno expected (relevant message), but even received.

### ISSUE THREAD

**Issue by Iriskin0** [LonamiWebs/Telethon#54]
I receive telethon.errors.BadMessageError: (BadMessageError(...), 'Odd msg_seqno expected (relevant message), but even received.') when trying to invoke telethon.tl.types.InputChannelEmpty:

`result = client.invoke(`
`        InputChannelEmpty()`
`    )`
`    return result`

**Comment by Lonami** [comment]
From the [docs](https://lonamiwebs.github.io/Telethon/#methods):
> Methods, also known as requests, are used to interact with the Telegram API itself and are invoked with a call to `.invoke()`. **Only these** can be passed to `.invoke()`! You cannot `.invoke()` types or constructors, only requests. After this, Telegram will return a `result`, which may be, for instance, a bunch of messages, some dialogs, users, etc.
