### ISSUE TITLE
File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 419

### ISSUE THREAD

**Issue by scubamarc** [LonamiWebs/Telethon#540]
I just installed telegram on debian (stretch), when i open the python shell and run "**from telethon import TelegramClient**" and also through a basic script. I get the following error.  I thought I installed everything correctly.  Can anyone help?  (Seems simple to me, not sure how I can screw this up)

hass@debian:~$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> **from telethon import TelegramClient**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/telethon/__init__.py", line 2, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 419
    def __call__(self, *requests, retries=5):
                                        ^
SyntaxError: invalid syntax
>>>

my install:
hass@debian:~$ sudo pip3 show telethon
Name: Telethon
Version: 0.16.1.1
Summary: Full-featured Telegram client library for Python 3
Home-page: https://github.com/LonamiWebs/Telethon
Author: Lonami Exo
Author-email: totufals@hotmail.com
License: MIT
Location: /usr/local/lib/python3.5/dist-packages
Requires: rsa, pyaes

**Comment by Lonami** [comment]
> $ python
> Python 2.7.13

**Comment by scubamarc** [comment]
thanks!!
