### ISSUE TITLE
Support SQLite <= 3.7.x

### ISSUE THREAD

**Issue by GiovanniCardamone** [LonamiWebs/Telethon#541]
we discussed this on https://t.me/TelethonChat, seems the new session storage method is broken for "dated" SQlite version, trying to create a `TelegramClient` with this SQLite version ends in Exception.

My test:
- SQLite version 3.7.9 2011-11-01 00:52:41
- telethon 0.16.1.1

exception:
```
File "/app/.heroku/python/lib/python3.6/site-packages/telethon/tl/session.py", line 88, in __init__
    c.execute("select name from sqlite_master "
sqlite3.DatabaseError: malformed database schema (sent_files) - near "without": syntax error
```

**Comment by Lonami** [comment]
Oh, you're the same person as #532. You could have reopened the old issue.

**Comment by GiovanniCardamone** [comment]
But is not the same issue, neither the same version

**Comment by Lonami** [comment]
Sorry, I meant to mention #523 (probably mistyped the last digit).

**Comment by Lonami** [comment]
> SQLite version 3.7.9

The table is created like this:
https://github.com/LonamiWebs/Telethon/blob/045f7f5643539b21f6f46ee1ce2daee76f74a954/telethon/tl/session.py#L191-L195

So it's really weird it's using the `without rowid` syntax when there's an explicit check. What do you get if you run this?:
```python
import sqlite3
sqlite_v = tuple(int(x) for x in sqlite3.sqlite_version.split('.')) 
print(sqlite_v, 'supports rowid?', sqlite_v >= (3, 8, 2))
```

**Comment by GiovanniCardamone** [comment]
```
~ $ python3
Python 3.6.3 (default, Nov 14 2017, 17:29:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite_v = tuple(int(x) for x in sqlite3.sqlite_version.split('.')) 
>>> print(sqlite_v, 'supports rowid?', sqlite_v >= (3, 8, 2))
(3, 7, 9) supports rowid? False
```

i run it from cli interpreter

**Comment by Lonami** [comment]
It says it doesn't support rowid. So I have no idea why it's using it because like I showed you, it's doing `extra = ' without rowid' if sqlite_v >= required else ''`. Did you copy the session file from your computer/whatever to Heroku? Maybe it's using a session with `without rowid` which won't work? I'm not too sure on how SQLite works.

**Comment by GiovanniCardamone** [comment]
ohhh XDXDXD!

that's why, im using shared session for both (development and production) environment, i have to do it again. :P

okok i have to discard all session and create it again in the new environment, but is very frustrating, there should be better solution :confused:

**Comment by Lonami** [comment]
I could just completely disable `without rowid`, but seems silly as it works just fine on recent versions :/

Sure there's likely no performance benefit on using my own primary key instead that field SQLite always adds (unless we use those keywords), but I don't know.

**Comment by tsujp** [comment]
So how do we get this working for those of us who generated a session file on 3.8.2 or higher (after without rowid support)?

**Comment by Lonami** [comment]
Generate the file with a lower version or somehow upgrade SQLite. I mean I can remove `without rowid` at all (I'm being a bit stubborn) but it just sucks we can't use newer features because of this.

**Comment by mike-johnson-jr** [comment]
@Lonami what would a heroku-compatible implementation look like (for those of us who want to fork the repo and edit the code)

**Comment by Lonami** [comment]
[This was changed](https://github.com/LonamiWebs/Telethon/commit/208adc93a6ca09524e8326bb715fb9b0f51d03bd).

**Comment by mike-johnson-jr** [comment]
I get banned using layer75 and any version over 0.18.3. Can you send me the last commit of 0.18.3 so I can fork the repo and reset changes to that commit, and copy the changes of https://github.com/LonamiWebs/Telethon/commit/208adc93a6ca09524e8326bb715fb9b0f51d03bd until you get the packages sorted out?

**Comment by Lonami** [comment]
@mike-johnson-jr you can install specific versions with `pip`, and you don't need the "last commit", `v0.18.3` is a valid identifier.

**Comment by mike-johnson-jr** [comment]
I know, but I need to edit the repo to include the changes of https://github.com/LonamiWebs/Telethon/commit/208adc93a6ca09524e8326bb715fb9b0f51d03bd. Can't do that without a fork.

**Comment by Lonami** [comment]
@mike-johnson-jr oh, right indeed, you would need to fork and cherry pick that change.

**Comment by mike-johnson-jr** [comment]
Yes. Do you know 0.18.3's last commit?

**Comment by Lonami** [comment]
@mike-johnson-jr go to "releases", tags, select 0.18.3. It should show the commit.

**Comment by mike-johnson-jr** [comment]
thanks,
