### ISSUE TITLE
anyway to use account in a new machine

### ISSUE THREAD

**Issue by hadihoda** [LonamiWebs/Telethon#542]
hello
I'm using the latest telethon version with sqlite session, and need to copy account to a new machine
i've just copied the session file and created a ```TelegramClient``` with that in the new machine, 
but client is not authorized (at least telethon says so!), while the client in old machine is working fine.
is there another thing to copy? or the session is binded to machine info someway

**Comment by Lonami** [comment]
Make sure you're accessing that same session file and not creating/accessing a new one. Anyway, not a bug.
