### ISSUE TITLE
Get chat entity by telegram chat invite

### ISSUE THREAD

**Issue by ksanderer** [LonamiWebs/Telethon#543]
Hi there! Can't find any info on how to get chat entity by chat invite link (for example: https://t.me/joinchat/DxoSakHOdk5mqsE-LelfVg)

Is it possible?

**Comment by Lonami** [comment]
Did you try `client.get_entity('link')`? Will work if you're in.

**Comment by IamYVJ** [comment]
What if I am not on the group?

**Comment by Lonami** [comment]
That is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
