### ISSUE TITLE
FloodWaitError - When Creating Client (client.send_code_request(phone_number))

### ISSUE THREAD

**Issue by guybader** [LonamiWebs/Telethon#544]
Hey, 
 I recived error when Im trying to recived Code to my telegram account
The problem line: client.send_code_request(phone_number)
Any Ideas how to solve it without waiting 21 hours? :/

Code:
```
from telethon import TelegramClient
import getpass
from telethon.errors import SessionPasswordNeededError

# Use your own values here
api_id = XXXXXX
api_hash = 'XXXXXXXXXXXXXXXXXXX'
phone_number = '+XXXXXXX'
client = TelegramClient('TelegrmClient2', api_id, api_hash)

assert client.connect()
if not client.is_user_authorized():
    try:
        client.send_code_request(phone_number)
        client.sign_in(code=input('Enter code: '))
    except SessionPasswordNeededError:
        client.sign_in(password=getpass.getpass())

print('Done')

```
Error: 
> Traceback (most recent call last):
>   File "C:/Users/Guy/PycharmProjects/TelegramTestV2/main.py", line 11, in <module>
>     client.send_code_request(phone_number)
>   File "C:\Users\Guy\PycharmProjects\TelegramTestV2\venv\lib\site-packages\telethon\telegram_client.py", line 175, in send_code_request
>     result = self(SendCodeRequest(phone, self.api_id, self.api_hash))
>   File "C:\Users\Guy\PycharmProjects\TelegramTestV2\venv\lib\site-packages\telethon\telegram_bare_client.py", line 446, in __call__
>     result = self._invoke(call_receive, *requests)
>   File "C:\Users\Guy\PycharmProjects\TelegramTestV2\venv\lib\site-packages\telethon\telegram_bare_client.py", line 546, in _invoke
>     return self._invoke(call_receive, *requests)
>   File "C:\Users\Guy\PycharmProjects\TelegramTestV2\venv\lib\site-packages\telethon\telegram_bare_client.py", line 526, in _invoke
>     raise next(x.rpc_error for x in requests if x.rpc_error)
> telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 76608 seconds is required')

**Comment by Lonami** [comment]
> Any Ideas how to solve it without waiting 21 hours? :/

I'm afraid you have to wait. If you try to login too many times Telegram will flood wait you for said 21 hours. Next time try to be more careful and don't sign in every time.

**Comment by guybader** [comment]
Im trying to sign with '2FA'. Is this the reason I reciving this error?
Thank you such a fast replay

**Comment by Lonami** [comment]
No 2FA doesn't have anything to do with this. It doesn't matter if you have 2FA or not. If you try to sign in too many times you'll be flood waited for obvious security reasons.

**Comment by guybader** [comment]
I tried 4 times. its strange.. Is it bug or its Telegram rules?

**Comment by Lonami** [comment]
Telegram rules, however you want to call it.

**Comment by guybader** [comment]
Ok thank you!
