### ISSUE TITLE
My account's banned

### ISSUE THREAD

**Issue by masoudcom** [LonamiWebs/Telethon#545]
Hi.
When use telethon and create account after multi day all my accounts banned and deleted from telegram.
please help me

**Comment by Lonami** [comment]
#397

**Comment by masoudcom** [comment]
I am iranian and used proxy(SOCKS) for each account but tg banned my accounts. you have not solution for me?

**Comment by Lonami** [comment]
No, I have no solution for you.

**Comment by masoudcom** [comment]
tnx
