### ISSUE TITLE
get_message_history returning error message

### ISSUE THREAD

**Issue by LeeHJones** [LonamiWebs/Telethon#546]
Hi folks -
This code is working just fine on Anaconda Python3, but is failing on Python.framework...

`totalCount, messages, senders = client.get_message_history(targetEntity, limit=howMany)`

The error message I'm getting (on Python.framework python3) is:

```
Traceback (most recent call last):
  File "msgfwd-00-04.py", line 200, in <module>
    readSomeMessages(blistGroup,20)
  File "msgfwd-00-04.py", line 39, in readSomeMessages
    totalCount, messages, senders = client.get_message_history(targetEntity, limit=howMany)
ValueError: too many values to unpack (expected 3)

```

I've pip3 uninstalled telethon and reinstalled to be sure I have the most recent code. Again, this works great on one machine, fails on another.

Thanks, Lee

**Comment by Lonami** [comment]
The method returns a single list now, not a tuple.

**Comment by LeeHJones** [comment]
Plenty cool - you might want to update the examples.

Thanks, Lee

**Comment by Lonami** [comment]
What example? I thought I updated everything.

**Comment by LeeHJones** [comment]
https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/interactive_telegram_client.py

**Comment by Lonami** [comment]
Had forgotten that file existed, thanks.
