### ISSUE TITLE
How to add new contacts?

### ISSUE THREAD

**Issue by blinterrr** [LonamiWebs/Telethon#55]
Hi. New in telegram api, i've researched webogram(js web version), so simple question

My goal is to add a bulk list of contacts from file, like .vcf file or phone per line
i've tried InputPhoneContact and ImportContactsRequest but got no expected result. either i send something wrong in these functions

What api calls should i use for this, can you help me please with code snippet?

**Comment by Lonami** [comment]
What have you actually tried (besides using those functions)? Did you pass the right parameteres?

**Comment by Lonami** [comment]
Please reopen after answering the above if you still have this problem :), closing not to have noise on the issues section.

Also, if you're still lost, make sure you've read the full [`README.rst`](https://github.com/LonamiWebs/Telethon/blob/master/README.rst).
