### ISSUE TITLE
Getting FileMigrateError when trying to download photo

### ISSUE THREAD

**Issue by ars1303** [LonamiWebs/Telethon#551]
For some reason when I am trying to download a photo and only when it is stored in DC 4, I get FileMigrateError. Any ideas on how to solve this issue?

```python
Traceback (most recent call last):
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 749, in download_file
    input_location, offset, part_size
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 474, in __call__
    sender, call_receive, update_state, *requests
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 560, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FileMigrateError: (FileMigrateError(...), 'The file to be accessed is currently stored in DC 4')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Users\abhis\Documents\TelegramClient V2\TelegramRelayer.py", line 59, in <module>
    output = client.download_media(message.media, r"media\picture")
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_client.py", line 851, in download_media
    media, file, date, progress_callback
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_client.py", line 886, in _download_photo
    progress_callback=progress_callback
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 761, in download_file
    client = self._get_exported_client(e.new_dc)
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 387, in _get_exported_client
    id=export_auth.id, bytes=export_auth.bytes
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 474, in __call__
    sender, call_receive, update_state, *requests
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 538, in _invoke
    sender.receive(update_state=update_state)
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 147, in receive
    self._process_msg(remote_msg_id, remote_seq, reader, update_state)
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 226, in _process_msg
    return self._handle_rpc_result(msg_id, sequence, reader)
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\network\mtproto_sender.py", line 523, in _handle_rpc_result
    request.on_response(reader)
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\tl\functions\auth.py", line 323, in on_response
    self.result = reader.tgread_object()
  File "C:\Users\Abhishek Sane\AppData\Local\Programs\Python\Python36\lib\site-packages\telethon\extensions\binary_reader.py", line 136, in tgread_object
    raise TypeNotFoundError(constructor_id)
telethon.errors.common.TypeNotFoundError: (TypeNotFoundError(...), 'Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 0xf6b673a4. Most likely, a TLObject was trying to be read when it should not be read.')
```

Here is the code specifically for getting photos. This code works perfectly fine for any file stored in DC 1.

```python
for message in reversed(messages):
    if hasattr(message, "id") and (message.id > currentMessage[name]):
        updateCurrentMessage(name, message.id)
        print (name)
        if getattr(message, 'media', None):
            client.found_media[message.id] = message
            try:
                messageMedia = client.found_media[message.id]
            except (ValueError, KeyError):
                print ("Invalid media ID given or message not found!")
                continue
```

**Comment by Lonami** [comment]
Pretty much like #355. I have no idea why it fails. It works for me.

**Comment by keepitsane** [comment]
So the library is supposed to do this automatically. Is there a way to manual change which DC it is accessing?

**Comment by Lonami** [comment]
I just noticed something, perhaps it's reconnecting but not specifying the layer to use… Because it says `TypeNotFoundError` after exporting a client.

**Comment by Lonami** [comment]
Maybe not, it's strange it works for me:
<details><summary>(log)</summary>
<pre>INFO:telethon.telegram_bare_client:Connecting to 149.154.167.91:443...
INFO:telethon.telegram_bare_client:Connection success!
DEBUG:telethon.telegram_bare_client:Invoking GetStateRequest
INFO:telethon.telegram_bare_client:Initializing a new connection while invoking
DEBUG:telethon.network.mtproto_sender:Processing BadServerSalt result
DEBUG:telethon.network.mtproto_sender:Processing container result
DEBUG:telethon.network.mtproto_sender:Processing NewSessionCreated result
DEBUG:telethon.network.mtproto_sender:Processing MsgsAck result
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.update_state:Saved new updates state
INFO:telethon.telegram_bare_client:Starting to wait for items from the network
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking GetHistoryRequest
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
INFO:telethon.telegram_client:Downloading file in chunks of 131072 bytes
DEBUG:telethon.telegram_bare_client:Invoking GetFileRequest
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
INFO:telethon.telegram_client:File lives in another DC
DEBUG:telethon.telegram_bare_client:Invoking GetConfigRequest
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
INFO:telethon.telegram_bare_client:Exporting authorization for data center DcOption(port=443, static=False, media_only=False, id=2, cdn=False, ip_address='149.154.167.51', tcpo_only=False, ipv6=False)
DEBUG:telethon.telegram_bare_client:Invoking ExportAuthorizationRequest
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
INFO:telethon.telegram_bare_client:Creating exported new client
INFO:telethon.telegram_bare_client:Connecting to 149.154.167.51:443...
INFO:telethon.telegram_bare_client:Connection success!
DEBUG:telethon.telegram_bare_client:Invoking ImportAuthorizationRequest
INFO:telethon.telegram_bare_client:Initializing a new connection while invoking
ERROR:telethon.telegram_bare_client:Authorization key seems broken and was invalid!
WARNING:telethon.telegram_bare_client:Invoking ["ImportAuthorizationRequest(id=10885151, bytes=b'...censored..."] failed 1 times, reconnecting and retrying
INFO:telethon.telegram_bare_client:Reconnection aborted: already connected
INFO:telethon.telegram_bare_client:Need to generate new auth key before invoking
INFO:telethon.telegram_bare_client:Initializing a new connection while invoking
DEBUG:telethon.network.mtproto_sender:Processing BadServerSalt result
DEBUG:telethon.network.mtproto_sender:Processing container result
DEBUG:telethon.network.mtproto_sender:Processing NewSessionCreated result
DEBUG:telethon.network.mtproto_sender:Processing MsgsAck result
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.telegram_bare_client:Invoking GetFileRequest
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.telegram_client:Saved 93593 more bytes
DEBUG:telethon.telegram_bare_client:Invoking GetFileRequest
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
INFO:telethon.telegram_bare_client:Disconnecting...
DEBUG:telethon.telegram_bare_client:Stopping all workers...
DEBUG:telethon.telegram_bare_client:Disconnecting the socket...
INFO:telethon.telegram_bare_client:Disconnecting...
DEBUG:telethon.telegram_bare_client:Stopping all workers...
DEBUG:telethon.telegram_bare_client:Disconnecting the socket...
INFO:telethon.telegram_bare_client:Disconnecting...
DEBUG:telethon.telegram_bare_client:Stopping all workers...
DEBUG:telethon.telegram_bare_client:Disconnecting the socket...</pre>
</details>

**Comment by keepitsane** [comment]
Yes that is very odd. I was not able to reproduce the same error in my test environment, the error only happens on certain images. Even the channel that it is pulling the photos from doesn't matter some work and some don't. Like I said if you would like to see my code I would be happy to share, but not sure how much that would help to fix the problem. If there is anything you would like to me to test let me know and I can try. (As a side note would it be possible to add more examples on using updates with chats and channels in the documentation. Thanks!)

**Comment by Lonami** [comment]
What DC do you use, and what's the DC on which the media lives? Could I have a link to the faulty media so that I can try to download it myself? As a side note, you can check the examples on the repository which should work.

**Comment by keepitsane** [comment]
Am I supposed to explicitly state which DC I use? So far the issue has been mainly when the file is stored on DC 4. Sorry I don't have an example on hand. But I was doing some testing, and for some reason when I change the code to only download a picture if it has the photo attribute, this issue go away I think I am still testing but not entirely sure.

```python
                        if getattr(message, 'media', None):
                            client.found_media[message.id] = message
                            try:
                                messageMedia = client.found_media[message.id]
                            except (ValueError, KeyError):
                                print ("Invalid media ID given or message not found!")
                                continue
                            if hasattr(message.media, 'webpage'):
                                fullMessage = "%s\n**[%s UTC]** \n%s" % \
                                (everyone, str(message.date), str(message.media.webpage.url))
                            elif hasattr(message.media, 'photo'):
                                output = client.download_media(message.media, r"media\picture")
                                imageLink = uploadImage(output)
                                fullMessage = "%s\n**[%s UTC]** \n%s" % \
                                (everyone, str(message.date), message.media.caption)
```

**Comment by ingria** [comment]
Yeah, the problem is in different API layers. For some reason Telegram thinks that your app uses one of the obsolete API layer.

The error says:
```
Could not find a matching Constructor ID for the TLObject that was supposed
to be read with ID 0xf6b673a4.
```

`0xf6b673a4` is [an ancient version](https://core.telegram.org/constructor/auth.authorization) of `auth.authorization` constructor. Now it has [different hash](https://github.com/LonamiWebs/Telethon/blob/7286f77008af13d959a7a553a45d202a0ac305f2/telethon_generator/scheme.tl#L290).

**Comment by Lonami** [comment]
Oh, I missed that part (I assumed the error was the same and pretty much skipped the log…). So what fails is getting a exported client and calling `invokeWithLayer` correctly, thanks for pointing it out.

**Comment by Lonami** [comment]
…but anyway it should be calling `invokeWithLayer` (and not only because it works for me but because of the current flow). A new bare client is created, it has `_first_request = True`, this means the first `ImportAuthorizationRequest` will be called with it. So no idea why Telegram is replying with such ancient object. And anyway there's even another `except TypeNotFoundError` that resets the first request flag and then it will retry. If you could enable logging it should say `Initializing a new connection while invoking`.

**Comment by Lonami** [comment]
Not sure if anything changed but I never could reproduce this bug. If it still happenas as of the latest version (currently `v0.18.3`) reopen and let me know.
