### ISSUE TITLE
FloodWaitError, A wait of 9800 seconds is required

### ISSUE THREAD

**Issue by rezakeramati** [LonamiWebs/Telethon#552]
Dear,
I have written a script using telethon to send a file and text to people on telegram.
I am totally not spamming and after sending 2 or 3 messages I get the error "FloodWaitError, A wait of 9800 seconds is required"
This is the snippet for sending message
I am adding the person to my contacts and sending a file and a text message.
I've put lots of sleeps to make sure my rate would not be high, but I still have the problem.
Any Ideas of what is the cause of the problem? I have access from Telegram Desktop to this account and I still can send messages from that, but no luck in telethon

```
def send(mobile,file,caption,message=""):
	try:
		sleep(random.randint(1,10))
		contact = InputPhoneContact(client_id = 0, phone = mobile, first_name=mobile,last_name="")
		result = client.invoke(ImportContactsRequest([contact]))
		sleep(1)
		if message:
			client.send_message(mobile,message)
		sleep(1)
		client.send_file(mobile, file,caption)
		print ("SENT TO "+mobile)
	except Exception as ex:
		print(ex)
		pass
```

**Comment by Lonami** [comment]
Maybe the problem is import contacts and not send message. You can use the phone string on send message.

**Comment by rezakeramati** [comment]
@Lonami I've tried that before but it seems that for some people the message is not being sent that way (maybe because of privacy settings)

**Comment by Lonami** [comment]
Just a few things but you can and probably should import many contacts at once instead one by one. Several requests accepting a list with a single item is stupid. Nothing I can do about privacy settings or flood waits.
