### ISSUE TITLE
Send_file doesn't work

### ISSUE THREAD

**Issue by Pantic14** [LonamiWebs/Telethon#555]
send_file doesn't work and 3 days ago if it worked.
I don't touch my code.
Only happen with images over 100kb. 
Images less than 100kb ok and files over and less 100kb ok.

**Comment by Pantic14** [comment]
I don't touch anything and now run... :S

**Comment by Lonami** [comment]
What doesn't work exactly? Throws error? Doesn't send but method returns the message? What?

**Comment by Pantic14** [comment]
The method don't return anything message.
And if send other file or message, the program run.

**Comment by Lonami** [comment]
Well I just sent myself a 1MB file and it worked. So you either provide more information (`logging` maybe) or I close this issue because I can't reproduce.
```python
import os
import itertools
with open('test', 'wb') as f:
    kb = bytes(range(256)) * 4
    f.write(1024 * kb)

print(client.send_file('me', 'test'))
os.remove('test')
```

**Comment by Pantic14** [comment]
Ok. wait a moment

**Comment by Lonami** [comment]
I can send a 227KB `.jpg` file without issues…

**Comment by Pantic14** [comment]
is in .png files, .jpg files run ok

**Comment by Lonami** [comment]
That makes no sense. All files are treated equally.

**Comment by Pantic14** [comment]
I don't know but happen this

**Comment by Pantic14** [comment]
@Lonami 
This code don't return anything only for images PNG over 120Kb.

> where = client.download_media(update.message, '----')
> print(client.send_file(channel_prueba, where))

**Comment by Lonami** [comment]
It would be nice to have the media so I could test it…

**Comment by Pantic14** [comment]
You have telegram or anything? And talk about this. My telegram is @pantic14

**Comment by Lonami** [comment]
No you [talk to me first](https://t.me/Lonami). And of course I have Telegram. It's the whole point of the library.

**Comment by Lonami** [comment]
Conclusion: no clue what's going on but there's no need to download/upload file, can just use `SendMediaRequest` to "forward" media without the forward header.
