### ISSUE TITLE
PhoneMigrateError

### ISSUE THREAD

**Issue by javinsnc** [LonamiWebs/Telethon#558]
Hi,

I have trying to test interactive_example and I get and error when I try to register my number. The stack trace is:

telethon.errors.rpc_error_list.PhoneMigrateError: (PhoneMigrateError(...), 'The phone number a user is trying to use for authorization is associated with DC 4')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoDawElite.py", line 162, in <module>
    itc = InteractiveTelegramClient('',"0034644404166",148615,"bc488da1147db423a6c5277cc303eaca");
  File "cryptoDawElite.py", line 95, in __init__
    self.sign_in(user_phone)
  File "/usr/lib/python3.4/site-packages/telethon/telegram_client.py", line 343, in sign_in
    return self.send_code_request(phone)
  File "/usr/lib/python3.4/site-packages/telethon/telegram_client.py", line 191, in send_code_request
    result = self(SendCodeRequest(phone, self.api_id, self.api_hash))
  File "/usr/lib/python3.4/site-packages/telethon/telegram_bare_client.py", line 440, in __call__
    result = self._invoke(call_receive, *requests)
  File "/usr/lib/python3.4/site-packages/telethon/telegram_bare_client.py", line 540, in _invoke
    return self._invoke(call_receive, *requests)
  File "/usr/lib/python3.4/site-packages/telethon/telegram_bare_client.py", line 520, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 62335 seconds is required')

**Comment by Lonami** [comment]
You've tried signing in too many times and for security reasons you've been flood waitted with 62335 seconds. Just wait those 17:18:55.

**Comment by javinsnc** [comment]
Hi again Lonami.

As I do when I sign in in Gmail, I'll sign in once and I can use the api (the email) every time.

The thing is I need to execute my script in order to debug it, so I was executing the TelegramApi(session,...) many times. Is there any chance to use the same session instead of trying to sign in every time in order to debug my script.

In other words, which is the proper way to sign once and stay connected for next script executions? I have noticed that only the first time I execute your API, a code was requested, but the other times doesnt.

Thanks in advance!

**Comment by Lonami** [comment]
If you `.log_out()` you'll need to sign in later. Otherwise `.is_user_authorized() is True` and you don't need to sign in.

**Comment by javinsnc** [comment]
But I did not .log_out(). This is the code i have used (extracted from your interactive example):

# If the user hasn't called .sign_in() or .sign_up() yet, they won't
        # be authorized. The first thing you must do is authorize. Calling
        # .sign_in() should only be done once as the information is saved on
        # the *.session file so you don't need to enter the code every time.
        if not self.is_user_authorized():
            print('First run. Sending code request...')
            self.sign_in(user_phone)

            self_user = None
            while self_user is None:
                code = input('Enter the code you just received: ')
                try:
                    self_user = self.sign_in(code=code)

                # Two-step verification may be enabled, and .sign_in will
                # raise this error. If that's the case ask for the password.
                # Note that getpass() may not work on PyCharm due to a bug,
                # if that's the case simply change it for input().
                except SessionPasswordNeededError:
                    pw = getpass('Two step verification is enabled. '
                                 'Please enter your password: ')

                    self_user = self.sign_in(password=pw)

itc = InteractiveTelegramClient('session_name',PHONE,API_ID, API_HASH);

With that, the code was requested once (except if I change session_name). The thing is that I just sign_in once but at the end i've been flood :(

**Comment by Lonami** [comment]
Well of course different session name you need to sign again.
