### ISSUE TITLE
self in update_handler? (i need send_message, delete_messages etc, from update_handler).

### ISSUE THREAD

**Issue by alecreator** [LonamiWebs/Telethon#56]
Hi all, sorry for my bad english and lame code))) Can you help me, show example code, for automate answer message or do some...

i edit `interactive_telegram_client.py` in `def update_handler(update_object)` add new types check 

```
elif type(update_object) is UpdatesTg:
    for update in update_object.updates:
        if type(update) is UpdateNewChannelMessage:
            if update.message.message:
                print('[SuperGroup: {}]'.format(update.message.message))
```
it work fine. But how i can use example, some like this:
```
elif type(update_object) is UpdatesTg:
    for update in update_object.updates:
        if type(update) is UpdateNewChannelMessage:
            if update.message.message:
                self.send_message(1062677923, " MESSAGES TEST ")
```
how send "self" in `def update_handler(update_object):` or any another way for this do?

**Comment by Lonami** [comment]
Since you're using the `InteractiveTelegramClient` as example, and this subclasses the `TelegramClient` which, I assume, is the one you want to pass as `self`, you can simply change:
```python
    @staticmethod
    def update_handler(update_object):
```

with

```python
    def update_handler(self, update_object):
```

For it not to be a `@staticmethod` and for you to have access to the `self` object))

**Comment by alecreator** [comment]
ok, thank you very much! it's work. 

Can you help me again? pls )
```
elif type(update_object) is UpdatesTg:
	for update in update_object.updates:
		if type(update) is UpdateNewChannelMessage:
			if update.message.message:
				print('[SuperGroup: {}]'.format(update.message.message))
				self.send_message(update.message.to_id.channel_id, " TEST: " + update.message.message, markdown=True, no_web_page=True)
```
How i need sendMessage from handle? What arguments in `self.send_message`. I think need create Channel object??? Or some??? Show please example code, if it is not difficult. Thank you!

**Comment by Lonami** [comment]
> I think need create Channel object

The common way is to use `.get_dialogs()`, although there are more ways to retrieve a specific channel, perhaps by username.

**Comment by alecreator** [comment]
Thank you for answer. Litle i understand how it work (`InteractiveTelegramClient`), but low understand OOP programming... (Soon i get read about this). `get_dialogs` it's method usable for user-interface (console) and (GUI), but i need for automatic system send or del msg, from handler where already have dialogs id's and more... If precise my question about use `send_message` with use know `channel_id`. 

It possible, manualy create `Channel` object_type with `channel_id` for use them in argument for `send_message`? Or best way use `invoke`, or some???

**Comment by Lonami** [comment]
> where already have dialogs id's

Then you can build the [https://lonamiwebs.github.io/Telethon/types/input_channel.html](InputChannel) yourself.

**Comment by alecreator** [comment]
Can you show example? please. Thanks!

**Comment by Lonami** [comment]
> Can you show example?

The `InteractiveTelegramClient` should really be enough example If not, check the `TelegramClient` itself to see how it works. And if you want to know how Python itself works, I encourage you to read [Dive Into Python 3](http://www.diveintopython3.net/).

**Comment by alecreator** [comment]
> Then you can create an instance of an InputChannel yourself.

Type `InputChannel`, no enter in `peer`. I get error:
`AttributeError: 'NoneType' object has no attribute 'on_send'`

 I think need use `InputPeerChannel`, because in `get_input_peer` check's

```
def get_input_peer(entity):
    """Gets the input peer for the given "entity" (user, chat or channel).
       Returns None if it was not found"""
    if (isinstance(entity, InputPeerUser) or
        isinstance(entity, InputPeerChat) or
            isinstance(entity, InputPeerChannel)):
        return entity

    if isinstance(entity, User):
        return InputPeerUser(entity.id, entity.access_hash)
    if isinstance(entity, Chat):
        return InputPeerChat(entity.id)
    if isinstance(entity, Channel):
        return InputPeerChannel(entity.id, entity.access_hash)
```
and `send_message` use `get_input_peer`
```
	def send_message(self,
					 entity,
					 message,
					 markdown=False,
					 no_web_page=False):
		"""Sends a message to the given entity (or input peer) and returns the sent message ID"""
		if markdown:
			msg, entities = parse_message_entities(message)
		else:
			msg, entities = message, []

		msg_id = utils.generate_random_long()
		self.invoke(
			SendMessageRequest(
				peer=get_input_peer(entity),
				message=msg,
				random_id=msg_id,
				entities=entities,
				no_webpage=no_web_page))
		return msg_id
```

Anyway thank you much! 

And i have new question, about acces_hash. Where i can get them best way? And what is it? Presonal acces_hash for each channel or global, for all channels???

**Comment by Lonami** [comment]
> Where i can get them best way?

You can either `.get_dialogs` to retrieve it or search for it using [ResolveUsernameRequest](https://lonamiwebs.github.io/Telethon/methods/contacts/resolve_username.html), which returns a [ResolvedPeer](https://lonamiwebs.github.io/Telethon/constructors/contacts/resolved_peer.html), which has a `.chats` parameter, which can be [any of these](https://lonamiwebs.github.io/Telethon/types/chat.html) (I've just used the search for "username", and found all that))).

Once you find it, if it's always going to be the same channel, I recommend you to save its ID and hash and just create the `InputPeerChannel` yourself. This will save you from the searching process.
