### ISSUE TITLE
account.registerDevice method not found. Schema changed?

### ISSUE THREAD

**Issue by georgsh** [LonamiWebs/Telethon#562]
I tried to subscribe to push notifications:
```python
from telethon import TelegramClient
from telethon import utils
from telethon.tl.functions.account import RegisterDeviceRequest

api_id = 1234
api_hash = '1234567890abcdef'
client = TelegramClient('session_name', api_id, api_hash)
client.start()

device_request = RegisterDeviceRequest(token_type=4, token='1234', other_uids=[])
push_settings = client(device_request)
```

resulting

```
Traceback (most recent call last):
  File "user.py", line 11, in <module>
    push_settings = client(device_request)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 441, in __call__
    result = self._invoke(call_receive, *requests)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 530, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.InputMethodInvalidError: (InputMethodInvalidError(...), 'The invoked method does not exist anymore or has never existed')
```

I think reason is [official schema](https://core.telegram.org/schema)
`account.registerDevice#446c712c token_type:int token:string device_model:string system_version:string app_version:string app_sandbox:Bool lang_code:string = Bool;`
is different from schema in project
`account.registerDevice#f75874d1 token_type:int token:string other_uids:Vector<int> = Bool;`

According to [commit in pyrogram](https://github.com/pyrogram/pyrogram/commit/ea35fa24801e6767c6fd37e4221abb5abafdbbc9) telegram changed schema again recently. But I cannot find it in official docs.

**Comment by Lonami** [comment]
Official documentation is incredibly out of date, we're using layer 74, while docs are in 23. Use https://lonamiwebs.github.io/Telethon.
