### ISSUE TITLE
How many TelegramClients i can run from one server (one IP adress)

### ISSUE THREAD

**Issue by petrucci89** [LonamiWebs/Telethon#564]
Hi!

I want to ask advanced Telethon users, how many  TelegramClients i can run from one server (one IP adress).

It will not be spam bots or flood bot, only simple bots who answer questions to those who write them the first.

Is it any limits from Telegram fir such tasks, and what your ideas to solve them.

Thx!

**Comment by Lonami** [comment]
Infinite.

**Comment by petrucci89** [comment]
Its great!

Very grateful for the answer
