### ISSUE TITLE
sqlite3.InterfaceError

### ISSUE THREAD

**Issue by LarsFox** [LonamiWebs/Telethon#567]
My bot sends a lot of messages and today I got an error:
```
  File "/home/user/py3env/lib/python3.5/site-packages/telethon/telegram_client.py", line 578, in send_message
    entity = self.get_input_entity(entity)
  File "/home/user/py3env/lib/python3.5/site-packages/telethon/telegram_client.py", line 1706, in get_input_entity
    return self.session.get_input_entity(peer)
  File "/home/user/py3env/lib/python3.5/site-packages/telethon/session.py", line 425, in get_input_entity
    (username,))
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

It is only one failed message out of a thousand sent today, and as long I implement the Telegram Client, I believe it is something with SQLLite, not my code.

Nice updates handler, by the way!

**Comment by Lonami** [comment]
Could you tell me what the type of that `username` is? Maybe add a `print()`. And thank you.

**Comment by LarsFox** [comment]
I call `self.send_message(entity, text, parse_mode='markdown')` where `entity` is `"TelegramRPGBot"`, a nickname of a bot I send message to.

**Comment by Lonami** [comment]
@LarsFox okay but if it's a string it shouldn't fail so it's probably a different type that managed to get there.

**Comment by LarsFox** [comment]
```
File "/home/user/bot/bot/client.py", line 624, in send_locations
    sent = self.send(GAME, emoji)
```
It is a constant and I do not redefine it anywhere else. So, I guess, I will have to put several prints here and there to see what may get there. Will tell you if something goes wrong on your side then.

**Comment by Lonami** [comment]
Note the `isinstance` check against `str`:
https://github.com/LonamiWebs/Telethon/blob/3b8365f8716add070490e7aca46b728eb8cbc43b/telethon/session.py#L433-L441

In the same way, `parse_username` can only return `str`:
https://github.com/LonamiWebs/Telethon/blob/3b8365f8716add070490e7aca46b728eb8cbc43b/telethon/utils.py#L339-L352

Not sure what's going on.
