### ISSUE TITLE
How get users (list) from Supergroup?

### ISSUE THREAD

**Issue by alecreator** [LonamiWebs/Telethon#57]
How i can get all users from supergroup channel??? GetChannelsRequest, GetAllChatsRequest and GetChatsRequest take Error:
`Unknown error message with code 400: CHANNEL_INVALID`

**Comment by Lonami** [comment]
[This person](https://github.com/sochix/TLSharp/issues/313) also got the `CHANNEL_INVALID` (although they were trying to retrieve the message history).

So in conclusion, do you have the **right ID and hash combination**? The Telethon equivalent would be creating a [`InputPeerChannel`](https://lonamiwebs.github.io/Telethon/constructors/input_peer_channel.html) or using `get_input_peer` from the helpers, then [`GetFullChannelRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/get_full_channel.html) should work.

**Comment by alecreator** [comment]
I just modify `telegram_client.py`
```
def get_full_channel(self, channel):
	return self.invoke( GetFullChannelRequest( channel ) )
```
and `interactive_telegram_client.py`
```
# Retrieve the selected user (or chat, or channel)
entity = entities[i]
var_dump(self.get_full_channel(entity))
```
then i choose need channel (supergroup). 

> or using get_input_peer from the helpers
Thank's it work! I use:
`var_dump(self.get_full_channel(get_input_peer(entity)))`
But object users it's only bots. How i can get all users from supergroup? :(

**Comment by Lonami** [comment]
> But object users it's only bots.

[`GetParticipantsRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/get_participants.html) instead?

**Comment by alecreator** [comment]
> GetParticipantsRequest instead?

Yeah, it work's! Thank you!!!
