### ISSUE TITLE
Forward multiple messages to multiple chats

### ISSUE THREAD

**Issue by ehsanskyboy** [LonamiWebs/Telethon#571]
hi. could you improve the library by passing a list of peers in `to_peer` arg at `ForwardMessage(s)Request` function?
is it available in Telegram API?
it could be a huge help to stop getting flood errors when using loops.

**Comment by Lonami** [comment]
> is it available in Telegram API?

No. When you forward something from a channel to many people the official clients actually make many calls (with, I presume, a loop).
