### ISSUE TITLE
Fetching full user list from large supergroup always yields 10k users

### ISSUE THREAD

**Issue by faustow** [LonamiWebs/Telethon#573]
I'm trying to fetch the full user list from a supergroup that has well over 10k users, but I always get 10k users back. Here's an example to illustrate that:
```
>>> def get_channel_participants(channel, offset, batch_size):
...     api_id = 1234567
...     api_hash = '7dfs7sdf7sdf7sdf7sdfsdf7sd7f'
...     client = TelegramClient('session_name', api_id, api_hash)
...     client.start()
...     all_participants = []
...
...     while True:
...         participants = client(GetParticipantsRequest(
...             channel, ChannelParticipantsSearch(''), offset, batch_size,
...             hash=0
...         ))
...         if not participants.users:
...             break
...         all_participants.extend(participants.users)
...         offset += len(participants.users)
...         sleep(5)
...     return all_participants
...
>>> users = get_channel_participants('mysupergroup', 0, 100)                                   
>>> len(users)
10000
>>> users = get_channel_participants('mysupergroup', 0, 500)                                   
>>> len(users)
10000
>>> users = get_channel_participants('mysupergroup', 0, 20000)                                   
>>> len(users)
10000
```
Is there a hard cap somewhere in the telethon code/telegram api that I've missed? If so, is there a way to somehow get the **full** user list and not just 10000 users?

**Comment by stek29** [comment]
Yup, there's a server side limit and Telethon can do nothing with it.

**Comment by Lonami** [comment]
Thanks @stek29, I'm closing this then. As a guess, if someone searched by "A", "B", "C"… "Z", would that help get all members?

**Comment by ali-kamali** [comment]
Does using hash have any effect?

**Comment by Lonami** [comment]
Hash is just so Telegram can reply with "nothing changed", so you don't need to refetch everything, and is calculated from what you know.

**Comment by ali-kamali** [comment]
I mean first get 10k users, then calculate the hash of the first part and ask for second 10k users.

**Comment by Lonami** [comment]
Like I said probably not but you can of course try.

**Comment by stek29** [comment]
No, hash has nothing to do with this.

**Comment by faustow** [comment]
Tried different combinations of hash, batch_size and offset but with no luck. Also tried `ChannelParticipantsRecent` instead of `ChannelParticipantsSearch` to see if they were ordered differently and that would yield a different set but it didn't help much. There must be a way of retrieve all users from a supergroup... @ali-kamali any luck?
Also, @stek29 where is this hard cap documented? Thanks.

**Comment by Lonami** [comment]
I doubt it's documented anywhere. Probably found by trial and error or talking with official developers.

**Comment by faustow** [comment]
If you have contact with official developers @Lonami or @stek29 would you please check with them if there's any way of circumventing this hard cap? That'd be super useful now that supergroups are becoming bigger and bigger.

**Comment by Lonami** [comment]
You must remember the API is only there to serve official applications, and official applications for a normal usage don't need to show *all* members…

**Comment by stek29** [comment]
@faustow That limit is put intentionally, and there's no "official" way to overcome it. Play with search queries :P

**Comment by faustow** [comment]
Tried that but the limit seems to be set per `client` and not per request nor search.

**Comment by stek29** [comment]
@faustow *shrug*

Telegram doesn't want us to do it, and people who figured out a way to overcome this won't share it :P

**Comment by saksham2410** [comment]
channel_index = input("Please select number of super group you want to scrape> ")
    channel = client.get_entity(PeerChannel(avail_channels[channel_index][1]))



    offset = 0
    limit = 200
    all_participants = []
    users = []


    while True:
        try:
            participants = client.invoke(GetParticipantsRequest(channel, ChannelParticipantsSearch(''), offset, limit))
            if not participants.users:
                break
            all_participants.extend(participants.users)
            offset += len(participants.users)

        except Exception as e:
            print(e)
            sys.exit()


The data is capped at 10K. All the supergroups return only usernames with 10K entries only. I see there is a workaround by using client.get_participant(..,aggressive = true) . How do I do this?
