### ISSUE TITLE
Phone number gets banned

### ISSUE THREAD

**Issue by ehsanskyboy** [LonamiWebs/Telethon#577]
it's the second time that my phones get banned when i use this library. it doesn't matter what i do, after couple days the phone gets banned. please check what's going on.
this is a conversion that i googled and it might help:
https://github.com/sochix/TLSharp/issues/439

**Comment by Lonami** [comment]
I can't do anything about this. I don't know what you're using (or abusing) the library for.

> please check what's going on.

That's a bit demanding, and this has never happened to me before (or any other of the people using the library).
