### ISSUE TITLE
Maximum length of all_participants stops at 10000

### ISSUE THREAD

**Issue by wyehuongyan** [LonamiWebs/Telethon#578]
Firstly, awesome library. 

Looked at the code for GetParticipantsRequest and it worked for me. However, the length of all_participants stops at 10000. The channel (megagroup) I am querying has more than 10000 users. 

Would like to understand if this is some limitation on Telegram's API or am I doing something incorrectly. 

Thank you.

**Comment by Lonami** [comment]
#573 3 days ago (or 5 issues ago).
