### ISSUE TITLE
Get Pinned Message and Number of Members from Link of Group(not Channel!!)

### ISSUE THREAD

**Issue by hd-dev** [LonamiWebs/Telethon#579]
Hi, how can i get Pinned Message in Group or Super Group , and Members Of Group From invite link?
 i use "CheckChatInviteRequest" to catch some data from group , can i use extracted "id" and "access hash" to solve my problem?
Please Help me

**Comment by Lonami** [comment]
[`GetFullChannelRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/get_full_channel.html) and eventually [`ChannelFull`](https://lonamiwebs.github.io/Telethon/constructors/channel_full.html) which has message ID. There are methods to get a message by ID.

**Comment by hd-dev** [comment]
Thanks Lonami
now, i can start from invite link and go to pinned message and in the end  get message by id from "client(GetMessagesRequest(peers,[pinnedMsgId]))"

but this return : 
-----------
ChannelMessages(pts=41065, count=0, messages=[Message(out=False, mentioned=False, media_unread=False, silent=False, post=False, id=20465, from_id=111104071, to_id=PeerChannel(channel_id=1111111111), fwd_from=None, via_bot_id=None, reply_to_msg_id=None, date=datetime.utcfromtimestamp(1517325331), message=' test message test', media=None, reply_markup=None, entities=[], views=None, edit_date=None, post_author=None, grouped_id=None)], chats=[Channel(creator=..............
-----------
i only need test of message ------>  test message test
how can catch that alone?

thanks
