### ISSUE TITLE
[Q] How to forward a message?

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [LonamiWebs/Telethon#58]
Hello, I wanna forward a message from a channel to a group. I found `ForwardMessageRequest` class. My question is:
How pass id parameter to this class? I mean how can i get id of a message in group?

I tested this:
```
for msg in messages:
    try:
        msg.message
        msg_id = utils.generate_random_long()
        client.invoke(ForwardMessageRequest(peer=get_input_peer(Entity), id=msg.id, random_id=msg_id))
    except:
        pass
```
But when i run script it says:
`Could not stabilise initial connection: (RPCError(...), 'Unknown error message with code 400: MESSAGE_ID_INVALID')`

**Comment by Lonami** [comment]
Check #23, I know that issues title isn't the most descriptive, but it contains what you're looking for.
