### ISSUE TITLE
GetParticipantsRequest  gets only 10000 Members and not more.

### ISSUE THREAD

**Issue by CodeDem** [LonamiWebs/Telethon#580]
Python 3.6

I am working on a project to get a list of members of a group or channel:

I followed the code sample given in the doc to retrieve all the members:

[Click Here](http://telethon.readthedocs.io/en/latest/extra/examples/chats-and-channels.html#retrieving-all-chat-members-channels-too)

http://telethon.readthedocs.io/en/latest/extra/examples/chats-and-channels.html#retrieving-all-chat-members-channels-too

```
offset = 0
limit = 100
all_participants = []
channel = 'thecoinfarm'
while True:
    participants = client(GetParticipantsRequest(
        channel, ChannelParticipantsRecent(), offset, limit,
        hash=0
    ))
    if not participants.users:
        break
    all_participants.extend(participants.users)
    offset += len(participants.users)
    print(offset)
```

I saw that it can only retrieve 10000  members and not more. The given test channel has approx 27 thousand members and I was able to extract only 10000 of them, so my question is, is that the limitation from telegram?

I went through the telegram API doc and was not able to find this limitation, I also tried with a negative offset in an attempt to traverse from the back but it didn't work.

Just wanted to know if it is possible to get all of the member lists.
Thanks for creating this project though.

**Comment by Lonami** [comment]
[Use](https://github.com/LonamiWebs/Telethon/issues/578) [search](https://github.com/LonamiWebs/Telethon/issues/573). Glad you like this project though!

**Comment by CodeDem** [comment]
@Lonami  Thanks for the quick response to my query it helped :).

I came up with this naive solution as a workaround.

```
queryKey = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
all_participants = []
channel = 'someGroupName'

for key in queryKey:
    offset = 0
    limit = 100
    while True:
        participants = client(GetParticipantsRequest(
            channel, ChannelParticipantsSearch(key), offset, limit,
            hash=0
        ))
        if not participants.users:
            break
        for user in participants.users:
            try:
                if re.findall(r"\b[a-zA-Z]", user.first_name)[0].lower() == key:
                    all_participants.append(user)
    
            except:
                pass

        offset += len(participants.users)
        print(offset)
```

**Comment by ericchenmelt** [comment]
^Does that actually work? Searching dosent return all of the participants.

**Comment by Lonami** [comment]
How many members is that 70-85%?

**Comment by CodeDem** [comment]
I tested it on 2 groups of 24K and 20K members and was able to get 70-80% of em.
 https://www.telegram.me/whalepoolbtc , I tested for this group and was able to extract 21,163 members out of 24,754. Members.

**Comment by Lonami** [comment]
Nice, fairly surprising it works might I add ;) Did you add sleeps or ran all the queries without any flood wait?

**Comment by CodeDem** [comment]
No, i didn't use sleep.  I think telegram does not restrict calls to the search queries. I ran it again just to test on the same group and it took 6 minutes to extract members and this time I was able to get 24,015 members.

**Comment by Lonami** [comment]
We could support this by default in the method introduced by #639. Do you know of any nice name for the argument? `aggressive=True` maybe?

**Comment by CodeDem** [comment]
@Lonami  can we user any random name? Like from any native language? :sweat_smile: 
I have a good one in mind.

**Comment by Lonami** [comment]
Sure, say it, I'll translate it and think of a good name in English.

**Comment by CodeDem** [comment]
We can use jugaad=True 

Jugaad (alternatively Juggaar) is a colloquial Hindi-Urdu word that can mean an innovative fix or a simple workaround, used for solutions that bend rules, or a resource that can be used as such, or a person who can solve a complicated issue. It is used as much to describe enterprising street mechanics as for political fixers. This meaning is often used to signify creativity to make existing things work or to create new things with meagre resources.

Since this, fix of getting maximum possible users using api is workaround, I think this should be it. haha

**Comment by Lonami** [comment]
Not sure what I expected 😅 I didn't know that word even existed and I doubt other people know either. It's not too intuitive either because the end user should be able to know as little as possible about this "limitation" to just work with it.

**Comment by CodeDem** [comment]
Hahaha, I know. Nvm  aggressive=True sounds good.

**Comment by Lonami** [comment]
I managed to get 24,444 members from `@whalepoolbtc` which has 24,760 members :)

**Comment by JosXa** [comment]
@Lonami Not bad ^^

**Comment by CodeDem** [comment]
Great, I'm happy that it is useful :)

**Comment by Lonami** [comment]
93,296 people from a group with 100,000 people. Not bad. Not bad at all.

**Comment by Lonami** [comment]
Loving it.

**Comment by ericchenmelt** [comment]
Figured out a way to get 99% on a 15k group (less so if it gets bigger):
get one list of participants from alphabet searching (dosen't include special character names: chinese/korean) and the other one from normal search (10k one)
and just add unique entries from the 10k list. we'll achieve 99%

**Comment by JosXa** [comment]
@ericchenmelt How long does it take?

**Comment by ericchenmelt** [comment]
+ time takes to fetch 10k on top of the search by alphabet.

**Comment by CodeDem** [comment]
It should not take more than 5-7 minutes.

**Comment by CodeDem** [comment]
@ericchenmelt,  yes  normal search returns 10k random. Keen to know if you have implemented any mechanism to not to add members which have been already extracted.

**Comment by CodeDem** [comment]
Ahha  that's fantastic.

**Comment by kaxap** [comment]
Searching by key other than an empty string does not return anything for me. 

```python
    from string import ascii_lowercase, digits, punctuation

    offset = 0
    limit = 100
    all_participants = []
    ids = set()

    channel='some_large_group'
    query_key = ['', ' '] + list(ascii_lowercase + digits + punctuation)

    for key in query_key:
        print('using key ' + key)
        while True:
            participants = client(GetParticipantsRequest(
                 channel, ChannelParticipantsSearch(key), offset, limit,
                 hash=0
            ))

            if not participants.users:
                break

            for user in participants.users:
                if user.id in ids:
                    continue
                ids.add(user.id)
                all_participants.append(user)

            offset += len(participants.users)
            print(len(ids))
```

**Comment by ZombieTheBest** [comment]
is this workaround still working?

**Comment by Lonami** [comment]
Sure, but just read the documentation for `TelegramClient.iter_participants`.

**Comment by ZombieTheBest** [comment]
@Lonami Thanks a lot!

**Comment by lybimiy86** [comment]
Friends, in which part of the code insert: aggressive=True ? 
` participants = client.invoke(GetParticipantsRequest(
            channel, ChannelParticipantsSearch(''), offset, limit,
            hash=0
        ))`
Where I put it, it gives an error: TypeError: __call__() got an unexpected keyword argument 'aggressive'
Version: 0.18.2.3

**Comment by lybimiy86** [comment]
@Lonami please help.  in which part of the code insert: aggressive=True ?
`participants = client.invoke(GetParticipantsRequest( channel, ChannelParticipantsSearch(''), offset, limit, hash=0 ))`
Where I put it, it gives an error: TypeError: call() got an unexpected keyword argument 'aggressive'
Version: 0.18.2.3

**Comment by Lonami** [comment]
No, read the manual.

**Comment by lybimiy86** [comment]
Thanks, angry people.

**Comment by stronghandsdeeppockets** [comment]
@Lonami 
I am actually encountering the same problem as the person above me. The documentation for get_participants (http://telethon.readthedocs.io/en/latest/telethon.html#telethon.telegram_client.TelegramClient.get_participants) states that it is similar to iter_participants (http://telethon.readthedocs.io/en/latest/telethon.html#telethon.telegram_client.TelegramClient.iter_participants).
However, aggressive appears in Args in iter_participants, but does not quite work as it gives the error stated above, unexpected keyword argument.
`users = get_channel_participants('asdfasdf1234123', 0, 100, aggressive=True)`

**Comment by Lonami** [comment]
Are you sure you're using an up-to-date version?

**Comment by stronghandsdeeppockets** [comment]
using .2 instead of .3. I know updating would be a smart idea anyway, but will that help me with my issue?

**Comment by Lonami** [comment]
I mean, probably?

**Comment by stronghandsdeeppockets** [comment]
Despite updating, I still receive the error. I've seen the fix above, would implementing that work? The thing is, I need as much accuracy as possible.
