### ISSUE TITLE
Workers aren't picking up newChannelMessages that contain an emoticon

### ISSUE THREAD

**Issue by BreakfastToGo** [LonamiWebs/Telethon#582]
The update workers aren't picking up newChannelMessages if the message contains an emoticon. 
Is there a way to get the workers to "find" the updates with emoticons in them that I'm missing?

**Comment by Lonami** [comment]
It works perfectly fine. If you have logging enabled or print the message your terminal might not support it so it crashes and "you don't receive it" (but you do).

**Comment by BreakfastToGo** [comment]
You're right, I was writing them off to a file with seems to have been the culprit. Thanks!
