### ISSUE TITLE
Downloading session file and using it with TelegramClient()

### ISSUE THREAD

**Issue by tsujp** [LonamiWebs/Telethon#585]
I'm new to Python and I'm trying to download a session file stored somewhere, and without writing to disk, use this file with the TelegramClient constructor. Things aren't working since if I use this file on disk and give the path all is okay, but trying to parse it as a bytestream, or binary object yields no result and a mixture of errors all related to an invalid session.

I've read the documentation about the session file being an sqlite3 file with session information, but I have no idea how to properly parse it and correctly assign a "file-like object" to TelegramClient().

Here is my code thus far:

```
r = requests.get(session_url, stream = True)
f = tempfile.SpooledTemporaryFile()
f.write(r.content)
mm = mmap.mmap(f.fileno(), 0)

client = TelegramClient(mm, int(api_id), api_hash, update_workers = 1, spawn_read_thread = False)
```

**Comment by Lonami** [comment]
Not the place to ask this. You should use a temporary file though or something because I doubt you can load a SQLite file from a memory stream.
