### ISSUE TITLE
Getting access_hash with user ID

### ISSUE THREAD

**Issue by Keln54** [LonamiWebs/Telethon#590]
Hello!

I have a problem with resolve user access_hash by user id.
Trying with a simple code: 

```

client = TelegramClient('teleth', api_id, api_hash)
client.connect()


s = client(functions.users.GetFullUserRequest(1119115518))
print(s)
```

I have an error:
TypeError: Could not find the input entity corresponding to "PeerUser(user_id=1119115518)".Make sure you have encountered this peer before.

But i can resolve access_hash with pyrogram with the same telegram account. Only with username. Can you help me, how can i do it with telethon? 

Thanks a lot!

**Comment by Lonami** [comment]
`client.get_entity(id)`.

**Comment by Lonami** [comment]
Oh, wait, that's what the library is doing behind the scenes. The library you mention has "seen" the user before. Telethon needs to do so too. So once you "see" the user you mention (e.g. `client.get_entity('username')`, it will work.

**Comment by Keln54** [comment]
Yes, it's work great with usernames. But if user does't have username, but i have messege from him? Or i consist in private channel? 

Can telethon do it?

**Comment by Lonami** [comment]
Well you can `client.get_dialogs(limit=None)` and the library will see everything in your dialogs (if you have a conversation open with him, it will work). This should only be done once (you can except the `ValueError` from `.get_entity()`, and `.get_dialogs(...)` if it happens before retrying) since you may have many conversations open. If it's a participant you need to get participants of that group, __or__ get the history in that group where he talks.

**Comment by Keln54** [comment]
I will show you:
```
client = TelegramClient('teleth', api_id, api_hash)
client.connect()

dialogs = client.get_dialogs(limit=None)
for i in dialogs:
    print(i.dialog)
entity = client.get_entity(1139159476)
print(entity)
```

Print show me:
![image](https://user-images.githubusercontent.com/26634447/35908808-c0f8c51a-0c02-11e8-8357-208e9e523693.png)

So, i have dialogs with that group. And i still have same error:
TypeError: Could not find the input entity corresponding to "PeerUser(user_id=1139159476)".Make sure you have encountered this peer before.

Where i have a mistake?

**Comment by Lonami** [comment]
Because it's a **group**, not an user! Users, chats and channels **may** have the same ID and the library will not try to guess which one is correct. You want `PeerChannel(id)`.

**Comment by Keln54** [comment]
So, it must works?
`entity = client(functions.channels.GetFullChannelRequest(1139159476))`

**Comment by Lonami** [comment]
`entity = client(functions.channels.GetFullChannelRequest(-1001139159476))`
or
`entity = client(functions.channels.GetFullChannelRequest(PeerChannel(1139159476)))`

**Comment by Keln54** [comment]
Oh, thats amazing! Works!
Thanks a lot!!

**Comment by Lonami** [comment]
Yeah, libraries work a bit differently. You can't assume things work in the same way. Personally I think it's a bug that the library you mentioned "guesses" the right type only from the ID, instead needing it to be explicit.

**Comment by Jasur09** [comment]
import csv
from telegram import Bot

TOKEN = "YOUR_BOT_TOKEN"

def add_telegram_contacts():
    bot = Bot(TOKEN)
    
    with open('your_csv_file.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            username = row['username']
            user_id = row['user_id']
            access_hash = row['access_hash']
            name = row['name']
            
            # Используйте методы Telegram API для добавления контакта
            # bot.contacts_addContact(user_id=user_id, access_hash=access_hash, first_name=name, username=username)
            
add_telegram_contacts()
