### ISSUE TITLE
Receive Messages and Get phone book names

### ISSUE THREAD

**Issue by chri1389** [LonamiWebs/Telethon#599]
Hello!
I have used this library and works very well!

I have two questions:

----------------------------------------------------
 
1) how can obtain the list of phone number book of a user (the address book)?

-----------------------------------------------------

2) I can get the live message received. I receive this information in the "update" object:
> UpdateShortMessage(out=False, mentioned=False, media_unread=False, silent=False, id=****, 
> user_id=*******, message='******', pts=******, pts_count=1, date=datetime.utcfromtimestamp(*******), 
> fwd_from=None, via_bot_id=None, reply_to_msg_id=None, entities=[])

In "update.message" I obtain the text message. My question is: How can obtain the telephone number of the sender?

Can you help me?

Thank you very much!

Best regards!

**Comment by Lonami** [comment]
> how can obtain the list of phone number book of a user (the address book)?

https://lonamiwebs.github.io/Telethon/?q=getcontacts

> How can obtain the telephone number of the sender?

`client.get_entity(update.user_id)`. If and only if they're in your contacts you will know their phone. There's no way to find their phone unless they're your contacts.

**Comment by chri1389** [comment]
Thank you very much!
I have a problem...
> client.get_entity(update.user_id). If and only if they're in your contacts you will know their phone. 
> There's no way to find their phone unless they're your contacts.

I have this code to get updates:

def update_handler(update):   
..    print('There is an update')
..    print('Message received: ', update.message)
etc....


It works very well, but if I add the line `client.get_entity(update.user_id)` it blocks here and skip all successive code rows. Why?

*** Ps.  To test this, I receive a message from a user that is in my contacts!

Thank you very much!

**Comment by Lonami** [comment]
> Why?

I don't know I don't have any log information or stacktrace…

**Comment by chri1389** [comment]
For example I have this code:

def update_handler(update):
..    print('Message received: ', update.message)
..    print('Id User: ', update.user_id)
..    print('Telephone number sender: ',client.get_entity(update.user_id))
..    print('End update_handler function!')
etc...

Every time I receive a message from a user (in my contacts), it prints only the first two "print":
Message received:  "Text Message"
Id User:  1234....


Is there some error in my code?


Thank you very much!

**Comment by Lonami** [comment]
@chri1389 okay but I want full traceback and/or log.

**Comment by chri1389** [comment]
I am sorry.. How can obtain a full traceback or log?

**Comment by Lonami** [comment]
[You can try reading](http://telethon.readthedocs.io/en/latest/extra/troubleshooting/enable-logging.html).

**Comment by chri1389** [comment]
I am sorry, I solved the problem. My distraction error! :)

The "client" variable was declared in a function and so update_handler function did not see it!

**Comment by chri1389** [comment]
I am sorry! I do not understand how to get the list of the contacts of the user (the command to use     GetContactsRequest)...
