### ISSUE TITLE
Timeout for invoke

### ISSUE THREAD

**Issue by MuallimCh** [LonamiWebs/Telethon#6]
We have to implement a timeout in invoke. For example, we lost internet connection just before sending a message; we will trapped in infinite loop in reading receive.

**Comment by XyLoNaMiyX** [comment]
I guess we could add more ways to cancel the receive. Perhaps both "timeout" and the normal `.cancel()` could live together. I think it is a great idea, because sometimes we receive nothing! What about the `send()` one though? Does it need timeout?

**Comment by MuallimCh** [comment]
I think implementing timeout should in socket layer, and commonly about 90 - 120 seconds. I face this problem when using mobile connection with poor signal.

**Comment by XyLoNaMiyX** [comment]
The timeout [is in the "_socket layer_"](https://github.com/LonamiWebs/Telethon/blob/7399bfacd17e2fd5010e16c92a469bfbec133f7f/telethon/network/tcp_client.py#L41-L84), but it had to [backpropagate](https://github.com/LonamiWebs/Telethon/blob/7399bfacd17e2fd5010e16c92a469bfbec133f7f/telethon/network/tcp_transport.py#L34-L60) [a](https://github.com/LonamiWebs/Telethon/blob/7399bfacd17e2fd5010e16c92a469bfbec133f7f/telethon/network/mtproto_sender.py#L108-L124) [bit](https://github.com/LonamiWebs/Telethon/blob/7399bfacd17e2fd5010e16c92a469bfbec133f7f/telethon/telegram_client.py#L129-L139) or it would be useless! I thought 5 seconds was a reasonable amount, but we can perfectly do 90-120 seconds as default. What do you think then? You can of course `invoke` your requests with any `timeout`.

**Comment by MuallimCh** [comment]
How about socket.setTimeout() or time.time(). Anyway thank you. Its perfect.
May be next version using asyncio rather than thread. Just my two cent.

**Comment by XyLoNaMiyX** [comment]
> How about socket.setTimeout()

How would you call `socket.setTimeout()`, if the call is blocked there? With another thread? You could also `.cancel_read()`! I think it's a better solution to call it with a given timeout.

> `time.time()`

What do you mean? Basically it already uses `datetime.now()`, and compares it to the `start_time` with the resulting delta times.

> May be next version using asyncio rather than thread

It would be great, but I have no idea on how to do that :-) You're free to implement it, it'll be thanked.

> Just my two cent

This is also appreciated 😋
