### ISSUE TITLE
help handling updates and corrupt sessions

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#60]
Updates are sometimes received with a delay of 2/6 sec. is it normal? if not how can i fix it?

Another problem is that after a few times i start the script and then i do "ctrl+c" (the script) do not work anymore maybe corrupted session? I also saw that by doing a client.connect the script does not turn off even if I do not call any method or I insert the handle updates

**Comment by Lonami** [comment]
> Updates are sometimes received with a delay of 2/6 sec. is it normal?

6 seconds maybe is not so normal, but, given that Telethon only has one connection shared accross two threads, definitely is not as fast as it could be otherwise.

> maybe corrupted session?

Perhaps though it shouldn't happen? Make sure you do `client.disconnect()`.

> I also saw that by doing a client.connect the script does not turn off even if I do not call any method or I insert the handle updates

It's strange, because I cancel all the pending reads and supposedly stop the updates thread. Maybe I could run it as `daemon=True` instead…

**Comment by seby2000** [comment]
Thanks for your answer! For the first problem, is there a way to increase
the threads?
For the second i forgot "client.disconnect()". Sorry my bad xd.

Il 29/Apr/2017 01:32, "Lonami" <notifications@github.com> ha scritto:

**Comment by Lonami** [comment]
> For the first problem, is there a way to increase the threads?

No, and that would probably just make it worse.

**Comment by seby2000** [comment]
Ok thank you

Il 29/Apr/2017 10:28, "Lonami" <notifications@github.com> ha scritto:

**Comment by Lonami** [comment]
I've tried to stop it twice with <kbd>Ctrl+C</kbd> and it successfully stopped (the updates thread closed itself and all), so I'll consider this as fixed. I'd appreciate if you could test the new version and report back how well it goes :)
