### ISSUE TITLE
Noob Error: No module named telethon

### ISSUE THREAD

**Issue by rRexee** [LonamiWebs/Telethon#600]
_I used python modules before, and I thought I knew how to install them. But I'm stuck._

I'm trying to create a Python script that uses Telegram and Instagram to do some automated tasks.

So, I've installed telethon using pip `pip3 install telethon`. And also `libssl`
I've created a test file named `AntidoteBot_Telegram_v1.py ` in my Projects Folder. My code is:

```
from telethon import TelegramClient

api_id = xxxxx
api_hash = 'xxxxxxxxxxxxxxxxxxxxxxxx'

client = TelegramClient('antidotebot', api_id, api_hash)
client.start()

for dialog in client.get_dialogs(limit=15):
    print(utils.get_display_name(dialog.entity), dialog.draft.message)

client.disconnect()
```

But I'm unable to start it. Error:
```
pi@raspberrypi_alex:~/Projects/InstaPy $ python AntidoteBot_Telegram_v1.py 
Traceback (most recent call last):
  File "AntidoteBot_Telegram_v1.py", line 1, in <module>
    from telethon import TelegramClient
ImportError: No module named telethon
```

What am I doing wrong?

**Comment by Lonami** [comment]
`python` might be `python2`, and you used (the right) `pip3` to install it. So run `python3` maybe.

**Comment by rRexee** [comment]
I've (re)installed all the modules with `pip3` then run my code with `python3` and it worked. Thanks!

**Comment by Lonami** [comment]
Nice, no problem. Enjoy the library!

**Comment by Subibhu** [comment]
> I've (re)installed all the modules with `pip3` then run my code with `python3` and it worked. Thanks!

can u send the code please i am having the same problem

**Comment by Subibhu** [comment]
the command lines i meant
