### ISSUE TITLE
Send Big video

### ISSUE THREAD

**Issue by JackCloudman** [LonamiWebs/Telethon#601]
How can i send a Big vídeo as vídeo?, no file
My Code:
client.send_file("myuser","myfile.mp4")

**Comment by Lonami** [comment]
Try:
```python
from telethon.tl.types import DocumentAttributeVideo
client.send_file(..., attributes=(DocumentAttributeVideo(0, 0, 0),))
```

**Comment by JackCloudman** [comment]
Thanks :D

**Comment by Lonami** [comment]
Does the video get sent with the correct duration, width and height? In theory you should probably specify it yourself but I just left it to zero assuming Telegram would get it right for you. Did it?

**Comment by mohamnag** [comment]
First thanks for this excellent work.

I'm also having this problem. While uploading lots of videos, whatever is less than 10MB gets sent correctly as video and whatever is larger just as file. 

Adding `attributes=(DocumentAttributeVideo(0, 0, 0)` fixes the issue (at least it seems so) but isn't it something that should probably be fixed in the client? 

I'm using v0.17

**Comment by mohamnag** [comment]
well that was a fast reply ;) thanks

**Comment by mohamnag** [comment]
well, now they are being uploaded as videos, but with wrong size (it was also the same with attribute). shall I report that in a separate ticket?

**Comment by Lonami** [comment]
I leave the dimensions set to zero, I'd assume Telegram would put the right the values. How are the values though? Is the ratio kept or they're completely random? If there's a way to determine the video dimensions from Python (as well as artist and song title while we're at it?), that would be nice.

**Comment by mohamnag** [comment]
If your setting it to 0,0 for all video files (under and over 10MB) then telegram is only fixing it for the files less than 10MB. For the rest (>10MB) it just uses the 0,0 values (my assumption as it looks the smallest size a video file is shown in different clients) and it also does not generate thumbnails for them.

unfortunately I'm not very experienced in python, but it seems there are at least some libs for it: https://stackoverflow.com/questions/7348505/get-dimensions-of-a-video-file

**Comment by Lonami** [comment]
It does something similar with gifs now that I think about it. Send a gif below 10MB and Telegram will turn it into mp4. Any bigger and it won't.

**Comment by mohamnag** [comment]
yes and also the video duration is not set. so they just skip processing whatever > 10MB

**Comment by mohamnag** [comment]
Oh I just experimented with some libs, and this one, even though it says its audio only, works really well and is python only. You can extract not only the video size, but also the meta data you asked before: https://mutagen.readthedocs.io/en/

**Comment by mohamnag** [comment]
ignore last comment, they were itunes attributes, so nothing generic...

**Comment by mohamnag** [comment]
I ended up using this one: http://hachoir3.readthedocs.io/developer.html

the code sample goes as:
```
from hachoir.metadata import extractMetadata
from hachoir.parser import createParser

metadata = extractMetadata(createParser(file_name))

tc.send_file(..., attributes=(
                                  DocumentAttributeVideo(
                                      (metadata.get('duration').seconds, 0)[metadata.has('duration')],
                                      (metadata.get('width'), 0)[metadata.has('width')],
                                      (metadata.get('height'), 0)[metadata.get('height')]
                                  )))
```

**Comment by Lonami** [comment]
Cool, thanks. We can have that as an optional dependency.

**Comment by mohamnag** [comment]
its also pure python, so no external dependencies
