### ISSUE TITLE
Send message with invisible

### ISSUE THREAD

**Issue by Ghetreek** [LonamiWebs/Telethon#602]
How send a message and don't switch account status to 'online'?

**Comment by Lonami** [comment]
You "can't".

**Comment by Ghetreek** [comment]
Why? Exist many customers with this function. Or is it on the level of telegram?

**Comment by Lonami** [comment]
> Exist many customers with this function

What…?

> Or is it on the level of telegram?

Yes… Telegram updates the last seen when you send a message and there's nothing you can do about it.

**Comment by Ghetreek** [comment]
Thx a lot
