### ISSUE TITLE
help |How to Export all contact list to a csv file

### ISSUE THREAD

**Issue by kolet** [LonamiWebs/Telethon#603]
hey ya all,

i am trying to export all of my contact list , first name,last name,@username, phone number, nickname , picture , into a csv file .

i have tried to use tg cli with no success and https://github.com/salarcode/ExportTelegramContacts
which did not export more than 9.9k contacts and it does not export all the info i mention.
it does export it to a vcf file but no info that i am looking for in that vcf file. 

help will be apriciated thanks 
thanks

**Comment by Lonami** [comment]
Not the place to ask, but look for `getContacts`.

**Comment by kolet** [comment]
i do want to update that it worked.
but i still have an issue, 
when printing the result it give me the ids,  but the firstname and lastname is the name that i gave when saved in contacts and not the name that everyone see it.
for example if u search a person by his username u will see his name eg,
@amirv u will see amirmohamad !
but sine i have added him to my contact list amirmohamad! wont be seen.

so the question is , how do i extract the name that every one sees ?
(hope this is a valid question) :)


> import json
> import os
> import sys
> import time
> import random
> from random import randint
> from telethon import TelegramClient
> from telethon.tl.types import InputPhoneContact
> from telethon.tl.functions.contacts import ImportContactsRequest
> from telethon.tl.functions.contacts import GetContactsRequest

> api_id = 111111
> api_auth = 'pepepepepepepepepe'
> session_number = '+123456789'
> 
> client = TelegramClient(session_number, api_id, api_auth)
> client.start()
> 
> result = client.invoke(GetContactsRequest(hash=api_id))
> print(result)

**Comment by Lonami** [comment]
You can use an auxiliar bot for that. I don't know if there's a way from within the same user.

**Comment by kolet** [comment]
@Lonami  
i searched online for auxiliar bot, no result .
whats auxiliar bot ?


even if it wasnt in the same user, telegram will probably red flag the other user.
i have over 10k contacts...
i know that when adding a user to my contact list telegram do send back a result with the name before it being add to the contact list. but ones its being added to ur contact the original is gone. which is so bad.

**Comment by Lonami** [comment]
…I didn't mean an "auxiliar bot" literally. I meant you could make a bot that can see the real name and last name, like [@JsonDumpBot](https://t.me/jsondumpbot).

**Comment by kolet** [comment]
cool.
thanks alot.

i have extracted most of my contacts , but only 9k out of 15k~ got extract
any idea why or how can i solve this ?

**Comment by Lonami** [comment]
Uh, maybe #293.

**Comment by kolet** [comment]
@Lonami  
what u suggesting to do is changing the (GetContactsRequest(hash=api_id)) api_id with 0 ?
the result stay the same (even less result and isntead of having a nice report (name,firname,lastname...) on each id i am getting only Contact(mutual=False, user_id=1234567) )

if u reffering to errors or exception the other person receive well its not my case, im not getting any of these errors.

do u think telegram block such thing?

i will try to another approach
is that possible to exclude the 9k found for the next run ? so it will spit only the one that im not requesting? if so, how?

thanks again for all ur hard working and support :)

**Comment by Lonami** [comment]
N-no… I don't even know why you were passing the API ID for the hash parameter, it has nothing to do, it had to be zero all the time. I don't know how to get such an insane amount of contacts, no.
