### ISSUE TITLE
GetParticipantsRequest() pegging at 10k users

### ISSUE THREAD

**Issue by LeeHJones** [LonamiWebs/Telethon#604]
I'm using the code as directly stolen from section 1.11.6 in:

https://media.readthedocs.org/pdf/telethon/latest/telethon.pdf

All I need is the number of users in the channel:

```
def getParticipantCount(client,entity):
  offset = 0
  limit = 100
  allParticipants = []
  while True:
    participants = client(GetParticipantsRequest(entity, ChannelParticipantsSearch(''), offset, limit,
     hash=0))

    if not participants.users:
     break

    allParticipants.extend(participants.users)
    offset += len(participants.users)

  participantCount = len(allParticipants)

  return(participantCount)

```

Works beautifully except if the channel has more than 10k members, it always returns 10k. If the channel has 8072, I get 8072. If it has 19,723 I get 10,000. Where is the number getting clipped and can I fix that?

Thanks, Lee

**Comment by Lonami** [comment]
#573.
