### ISSUE TITLE
Getting Specific Input Entity

### ISSUE THREAD

**Issue by chhudson** [LonamiWebs/Telethon#605]
Python 3.6.4
Issue Type: Question

I am attempting to grab the most recent messages from a channel and put them into an array or Dataframe for later usage.

Currently, I am having issues with `get_input_entity`. I iterated over all the entities to get the `input_peer` to then use in the `offset_peer` arg for `get_input_entity`. The entity itself is a channel without a username.

Any help is appreciated and thanks in advance.

Code:
```
client = TelegramClient('hodloo_query', api_id, api_hash)
client.start(password=password)

# Listing all the dialogs (conversations you have open)
input_entity = client.get_input_entity(1158021569)
print(input_entity)

for dialog in client.get_dialogs(offset_peer=input_entity):
    entity = dialog.entity
    input_peer = get_input_peer(entity)
    #print(entity, input_peer)
    for message in client.get_message_history(entity, limit=10):
        print(message.message)
```

Traceback:
```
Traceback (most recent call last):
  File "hodloo.py", line 15, in <module>
    input_entity = client.get_input_entity(1158021569)
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 1863, in get_input_entity
    'Make sure you have encountered this peer before.'.format(peer)
TypeError: Could not find the input entity corresponding to "PeerUser(user_id=1158021569)".Make sure you have encountered this peer before.
```

**Comment by Lonami** [comment]
I'll assume you've figured out that the error means you need to "find" that entity somehow before being able to fetch it by ID. Probably swapping the order (get dialogs limit none) and then input entity works.

**Comment by MaskRay** [comment]
@Lonami Can you elaborate how to retrieve the user information properly?

I have a similar user scenario in my telegram->IRC gateway (normal account, not bot).

I subscribe to UpdateNewChannelMessage and use get_entity(user_id) to resolve the information of the message sender.
In some cases get_entity(user_id) throws TypeError (Could not find the input entity corresponding to "350756331". Make sure you have e>)
I understand this is definitely the problem of the handling of telegramircd (the application in question that calls telethon)
but would like to know how I should properly resolve the sender information. Thanks in advance!


 File "/usr/lib/python3.6/site-packages/telethon/update_state.py", line 106, in _worker_loop
    self.handler(update)
  File "/usr/lib/python3.6/site-packages/telethon/telegram_client.py", line 2203, in _on_hand>
    progress_callback(f.tell(), file_size)
  File "/usr/bin/telegramircd", line 2036, in on_telegram_update
    getattr(TelegramUpdate, name)(self, update)
  File "/usr/bin/telegramircd", line 1674, in UpdateNewChannelMessage
    server.on_telegram_update_message(update, update.message)
  File "/usr/bin/telegramircd", line 2042, in on_telegram_update_message
    sender, to = self.resolve_from_to(msg)
  File "/usr/bin/telegramircd", line 2019, in resolve_from_to
    from_ = server.ensure_special_user(msg.from_id, None)
  File "/usr/bin/telegramircd", line 1980, in ensure_special_user
    tg_user = web.proc.get_entity(user_id)
  File "/usr/lib/python3.6/site-packages/telethon/telegram_client.py", line 2332, in get_enti>
    return self.remove_event_handler(handler)
  File "/usr/lib/python3.6/site-packages/telethon/telegram_client.py", line 2332, in <listcom>
    return self.remove_event_handler(handler)
  File "/usr/lib/python3.6/site-packages/telethon/telegram_client.py", line 2476, in get_inpu>
    entity (`str` | `int` | :tl:`Peer` | :tl:`InputPeer`):
TypeError: Could not find the input entity corresponding to "350756331". Make sure you have e>

**Comment by Lonami** [comment]
You know better than the library where that user might be. If the user sent a message in a megagroup and you can't find the user by their ID, get all the participants of the group upon excepting the error. `client.get_entity` is the way to go, although if you use `events` instead the old updates, they should do this magic for you when possible. It's all in the documentation.

**Comment by MaskRay** [comment]
Thanks. I have made some blind changes and hope it works. (I use telegram out of frustration and had to build this IRC gateway to make me feel better)

```
    def run_telethon(self):
-       self.proc.add_update_handler(server.on_telegram_update)
+       self.proc.add_event_handler(server.on_telegram_update)
```

```python
    def resolve_from_to(self, msg):
........
        try:
            from_ = server.ensure_special_user(msg.from_id, None) #  which invokes get_entity(msg.from_id)
        except:
            # Haven't seen the peer before. Retry.
            web.channel_members(to_id)
            from_ = server.ensure_special_user(msg.from_id, None)  #  which invokes get_entity(msg.from_id) again
        return from_, to
```
