### ISSUE TITLE
Strange behavior of get_message_history with max_id

### ISSUE THREAD

**Issue by DrJackilD** [LonamiWebs/Telethon#607]
Hi

I'm using Telethon to get message history from one large channel. Code looks like this:

```pyton
def download(entity: InputPeerChannel) -> Generator[List[types.Message], None, None]:
    limit = 3000
    messages = client.get_message_history(entity, limit=1)
    if not messages:
        return
    start_id = messages[0].id
    while True:
        messages = client.get_message_history(entity, limit=limit, max_id=start_id, wait_time=2)
        if not messages:
            break
        start_id = messages[-1].id
        yield messages
    return
```

The problem is that after first batch (3k messages), when start id changed to oldest message (like from 64323 to 58956) I've got empty list of messages. In the same way, if I'm using `offset_id` instead of `max_id` - all working good. Is there something which I'm missing, or that's a possible bug?

Thank you in advance!

**Comment by DrJackilD** [comment]
Btw, I'm not sure I understand the difference between `max_id` and `offset_id`, can someone explain it? Thanks :)

**Comment by Lonami** [comment]
To be honest, I haven't quite used `max_id`, `min_id` and friends. I rely on a different set of offsets:
https://github.com/LonamiWebs/Telethon/blob/e9dd93f09cc2232c388479fb1fa366adef51af51/telethon/telegram_client.py#L767-L795

If all offsets worked properly (I don't know if they do…), you should note that the higher the ID, the more recent the message is, and the lower, the older. So it might be tricky to get an intuition on whether to use `max_id` or `min_id`.

For instance if we look at [`tdesktop`'s source](https://github.com/telegramdesktop/tdesktop/search?utf8=%E2%9C%93&q=MTPmessages_GetHistory&type=) we can see that he leaves all the `max_id` and `min_id` to `None` always!
