### ISSUE TITLE
Can I add contacts that aren't in my contact list using this lib ?

### ISSUE THREAD

**Issue by dharmagetic** [LonamiWebs/Telethon#608]
The functionality I need is creating a group chat and inviting users there. This works fine when I add somebody who is in my contact list:

import telethon
from telethon.tl.functions.messages import CreateChatRequest
client = telethon.TelegramClient('some_session', 'key', '6284f5acf91b03somehash441ac9eef319')
client.start()
client(CreateChatRequest(['+79297226653'], 'Test Group')) # number from my contact list
However, this breaks if the number I pass is not in my contact list (an I am certain this phone number is registered with Telegram)

  File "/Users/1111/.virtualenvs/inviter-WB5rPISo/lib/python3.6/site-packages/telethon/telegram_client.py", line 1680, in _get_entity_from_string
    'Cannot turn "{}" into any entity (user or chat)'.format(string)
TypeError: Cannot turn "+79291101517" into any entity (user or chat)
My suspicion is that CreateChatRequest only works for my PeerUsers, i.e. using non-peer phones is prohibited in this method.

So the question is, how do I add somebody to a group chat if he is not one of my contacts?

**Comment by Lonami** [comment]
It will work as long as whatever phone is in your contacts. [`ImportContactsRequest`](https://lonamiwebs.github.io/Telethon/methods/contacts/import_contacts.html).

**Comment by dharmagetic** [comment]
Thank you!

**Comment by 2704jakob** [comment]
> It will work as long as whatever phone is in your contacts. [`ImportContactsRequest`](https://lonamiwebs.github.io/Telethon/methods/contacts/import_contacts.html).

What about using the users id? Do I need to add the users to my contacts or can I add them just using the user id?
