### ISSUE TITLE
auth.checkPhone

### ISSUE THREAD

**Issue by GoldenEagle66** [LonamiWebs/Telethon#612]
Hello, how to make a method
https://core.telegram.org/method/auth.checkPhone

**Comment by Lonami** [comment]
In case you missed it: http://telethon.rtfd.io/. Or you give more details.

**Comment by GoldenEagle66** [comment]
I register new accounts, and in his f-tion saw the processing of a similar error PhoneNumberOccupiedError. But it processes it when sending sms for registration, I would like to directly call this function, https://core.telegram.org/method/auth .checkPhone

**Comment by Lonami** [comment]
http://telethon.readthedocs.io/en/latest/extra/advanced-usage/accessing-the-full-api.html, https://lonamiwebs.github.io/Telethon/methods/auth/check_phone.html.

**Comment by Lonami** [comment]
Or you can `except` the error.

**Comment by GoldenEagle66** [comment]
thank you very much for the quick response
