### ISSUE TITLE
Opening dialogs with bots using url

### ISSUE THREAD

**Issue by saharokk** [LonamiWebs/Telethon#615]
Hi! 
Have a question about opening dialogs with bots if I have a link such like: "https://telegram.me/BTC_CHANGE_BOT?start=KU73I4FG8CSB2ECBYR5Y8JssCheque"
Is that just a get request? If yes, how I could use it?
I know about  ImportChatInviteRequest() method, but url must include "joinchat" part.

Thanks for any thoughts!

**Comment by Lonami** [comment]
Would be nice if you told us how you solved the issue?

**Comment by saharokk** [comment]
Oh sorry, it was so easy, so I've got embarrassed=)

According to: https://core.telegram.org/bots,
Queries like "https://telegram.me/triviabot?start=test" it's like a message to the bot with username @triviabot, containing a command "/start" with payload "test", or just "/start test"

So, in my case, I resolved that this way
client.send_message('BTC_CHANGE_BOT', '/start 8SG2FEDPCKDQYUET5P1M9CssCheque')

Hope this will help somebody! ;)

**Comment by Lonami** [comment]
Alright nice.
