### ISSUE TITLE
get chat or chanel id before joining by join hash

### ISSUE THREAD

**Issue by ehsankhorasani** [LonamiWebs/Telethon#617]
I have a lot of join hash links
but before join, need to know about channel or chat id
i use `CheckChatInviteRequest` but It does not return this id
Is there any way?

**Comment by Lonami** [comment]
No.

**Comment by delivrance** [comment]
@ehsankhorasani Actually, *there is* a way. For public channels/groups you can get some basic info without joining. Here you can find some explanation: https://github.com/pyrogram/pyrogram/issues/6

**Comment by sogand145** [comment]
> > Hi there! Nope, is not possible to get the id/hash pair for **private** chats or channels via the joinchat link without joining first, all you can do is using messages.CheckChatInvite to get a brief description. You have to pass only the link hash as argument, which is GG4BlQwm19czcBGOewv40Q in your example.
> 
> > However, if the chat/channel is **public** (i.e., you have its public username), you can get the id/hash pair by using contacts.ResolveUsername.
> 
> > Edit: If the channel/group is **public** and all you have is just an invite link, you can use messages.CheckChatInvite to get the id/hash pair. The returned type will be types.ChatInviteAlready in this case, instead of types.ChatInvite

Thanks for your reply, do you know how can find that which group is public or private by new join link?
on the other hand I didn't understand when we get types.ChatInviteAlready or types.ChatInvit after calling messages.CheckChatInvite ??

**Comment by sogand145** [comment]
> > > Hi there! Nope, is not possible to get the id/hash pair for **private** chats or channels via the joinchat link without joining first, all you can do is using messages.CheckChatInvite to get a brief description. You have to pass only the link hash as argument, which is GG4BlQwm19czcBGOewv40Q in your example.
> > 
> > 
> > > However, if the chat/channel is **public** (i.e., you have its public username), you can get the id/hash pair by using contacts.ResolveUsername.
> > 
> > 
> > > Edit: If the channel/group is **public** and all you have is just an invite link, you can use messages.CheckChatInvite to get the id/hash pair. The returned type will be types.ChatInviteAlready in this case, instead of types.ChatInvite
> 
> Thanks for your reply, do you know how can find that which group is public or private by new join link?
> on the other hand I didn't understand when we get types.ChatInviteAlready or types.ChatInvit after calling messages.CheckChatInvite ??

for example with this new link: 
https://t.me/joinchat/AzIy4T300lkg29ARvDqK1g
sometimes I get ChatInviteAlready and sometimes ChatInvit

**Comment by delivrance** [comment]
> > > > Hi there! Nope, is not possible to get the id/hash pair for **private** chats or channels via the joinchat link without joining first, all you can do is using messages.CheckChatInvite to get a brief description. You have to pass only the link hash as argument, which is GG4BlQwm19czcBGOewv40Q in your example.
> > > 
> > > 
> > > > However, if the chat/channel is **public** (i.e., you have its public username), you can get the id/hash pair by using contacts.ResolveUsername.
> > > 
> > > 
> > > > Edit: If the channel/group is **public** and all you have is just an invite link, you can use messages.CheckChatInvite to get the id/hash pair. The returned type will be types.ChatInviteAlready in this case, instead of types.ChatInvite
> > 
> > 
> > Thanks for your reply, do you know how can find that which group is public or private by new join link?
> > on the other hand I didn't understand when we get types.ChatInviteAlready or types.ChatInvit after calling messages.CheckChatInvite ??
> 
> for example with this new link:
> https://t.me/joinchat/AzIy4T300lkg29ARvDqK1g
> sometimes I get ChatInviteAlready and sometimes ChatInvit

Hi, the comment is quite old and for some reason lonami deleted my actual content. I'm not sure how to respond given I'm out of context of my own comment.

**Comment by sogand145** [comment]
> > > > > Hi there! Nope, is not possible to get the id/hash pair for **private** chats or channels via the joinchat link without joining first, all you can do is using messages.CheckChatInvite to get a brief description. You have to pass only the link hash as argument, which is GG4BlQwm19czcBGOewv40Q in your example.
> > > > 
> > > > 
> > > > > However, if the chat/channel is **public** (i.e., you have its public username), you can get the id/hash pair by using contacts.ResolveUsername.
> > > > 
> > > > 
> > > > > Edit: If the channel/group is **public** and all you have is just an invite link, you can use messages.CheckChatInvite to get the id/hash pair. The returned type will be types.ChatInviteAlready in this case, instead of types.ChatInvite
> > > 
> > > 
> > > Thanks for your reply, do you know how can find that which group is public or private by new join link?
> > > on the other hand I didn't understand when we get types.ChatInviteAlready or types.ChatInvit after calling messages.CheckChatInvite ??
> > 
> > 
> > for example with this new link:
> > https://t.me/joinchat/AzIy4T300lkg29ARvDqK1g
> > sometimes I get ChatInviteAlready and sometimes ChatInvit
> 
> Hi, the comment is quite old and for some reason lonami deleted my actual content. I'm not sure how to respond given I'm out of context of my own comment.

Ok, thanks

**Comment by Lonami** [comment]
Not sure what I removed but most likely a mention or link to your library because I acted like that back then, but indeed this is extremely old. 

In any case, the issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
