### ISSUE TITLE
Date member of Channel type is not the creation date?

### ISSUE THREAD

**Issue by StigP1337** [LonamiWebs/Telethon#624]
I do a **ResolveUsernameRequest** and get among other things a **Channel** object in return. The **Channel** object has a member called **date**. I guessed from the limited Telegram API documentation where Chat.date is described as "_Date created_" that **date** is the creation date of the Channel. But the date is newer than some of the messages in the channel. In one example the returned timestamp is from July 25th 2017 but messages reach back until January 2016. 

Do you know the meaning of this date?

I would like to get the real creation date of the channel without crawling through the whole message history. I noticed in the type **MessageService** the action **MessageActionChannelCreate** but I haven't found a way to just search for this specific message type in a channel.

Do you know a way to get the creation date?

**Comment by Lonami** [comment]
Set some low `offset_date` like `offset_date=datetime(2010, 1, 1)`, then `add_offset=-1` and a `limit=1`. For some reason that works and will give you the first available message (with a date). No clue what the date on the channel object is.

**Comment by snowman** [comment]
Maybe the date is the join time
