### ISSUE TITLE
Authorization key seems broken and was invalid

### ISSUE THREAD

**Issue by TheUnravelGhoul** [LonamiWebs/Telethon#625]
Hi. 
I've got some strange trouble. 
Few hours ago everything was ok, but now I'm getting the error "Authorization key seems broken and was invalid!". I've tried to remove the session and re-login. No effect. 
I've also tried switching to the another Telegram account.

The most strange is the following:
1. APIClient after login seems fine. is_user_authorized reutrns True. No errors.
2. I'm recreating the client instance in the another method, and is_user_authorized is false and error occures (message is Authorization key seems broken and was invalid!).

**Comment by Lonami** [comment]
I hope you're using the same name for the client (the session file name) or, at least, renamimg the file if you change it.

**Comment by Lonami** [comment]
Could you show some small code example that reproduces the issue consistently?

**Comment by TheUnravelGhoul** [comment]
I've just swithed branch to "master", it has been working fine, for a week on the prod server, and now there's the same trouble. 

I have wrapper for the client, I'm using it in the different places.

Wrapper's init method:
```Python
self.client = TelegramClient('session', self.api_id, self.api_hash, timeout=10, spawn_read_thread=False)
self.client.connect()
self.client.session.flood_sleep_threshold = 300
```

When the client is created once, everything is OK. 
When I'm creating a new instance, an error occures (it has begun a few hours ago without any changes from my side).

**Comment by Lonami** [comment]
Are you creating two clients with the aame session name at once? You shouldn't.

**Comment by TheUnravelGhoul** [comment]
I'm using Telethon 0.17.3.

**Comment by TheUnravelGhoul** [comment]
Oh... But it worked...

**Comment by TheUnravelGhoul** [comment]
I've just changed my wrapper. Now it's a singleton. 
The same error.

**Comment by TheUnravelGhoul** [comment]
Oh my...
It's session issue. When I'm initializing client the first time, session file is being created in the my ~/home. 
But when I'm creating the client next time, the session file is being taken from the project dir.

**Comment by Lonami** [comment]
Closing then.

**Comment by TheUnravelGhoul** [comment]
...still don't understand why the session was created in the home dir.

**Comment by Lonami** [comment]
If you open a new terminal, the working directory often defaults to home. Entering an interactive shell won't change it.

**Comment by TheUnravelGhoul** [comment]
All the actions are being performed from the one application. The working dir is always the same.

**Comment by Lonami** [comment]
Then I've no idea but it's good you figured out a solution.

**Comment by TheUnravelGhoul** [comment]
Found the problem. 
I'm using PyCharm and I have two running configurations.
One is for applicaition, and one is for Celery debugging.
PyCharm just ignored my explicit "working dir" parameter.
