### ISSUE TITLE
Cannot get entity from a channel (or group) that you are not part of

### ISSUE THREAD

**Issue by GoldenEagle66** [LonamiWebs/Telethon#626]
I get an error "Can not get an entity from a channel (or group) that you are not part of"
at
username = client.get_entity ("https://t.me/joinchat/HJHDWFKvPgQGwv_m2VxSdQ")
but how do I join a chat / channel if I can not get information about it?

**Comment by Lonami** [comment]
Well you use "join chat" or similar with the hash (part after joinchat/). I think RTD details this.

**Comment by GoldenEagle66** [comment]
@Lonami 
thank you half-hearted, but tell me again what this error is and how to solve it,
userchat = client.get_entity (PeerUser (500905609))
Could not find the input entity corresponding to "PeerUser (user_id = 500905609)". Make sure you have encountered this peer before.

**Comment by Lonami** [comment]
The error is exactly telling you the issue, the library hasn't "seen" that user. Please read the documentation on this since typing it all again is pointless. You can and should favour using usernames when possible.
