### ISSUE TITLE
Not receiving updates for megagroups and channels when using a new .sessions file

### ISSUE THREAD

**Issue by hcv57** [LonamiWebs/Telethon#627]
Hi, thanks for the great library. 

I am using v. 0.17.2.1 in a docker container that comes bundled with a session file, so that one does not need to go through the sing-in process. 

The client, however, does not receive `UpdateNewChannelMessage` updates for groups or channels that were added after the bundled session snapshot was taken.

I've tried `client.get_dialogs(limit=9999)` in the hope that that would make the session aware of all the channels I subscribed to but to no avail.

I am stuck.

**Comment by Lonami** [comment]
Did you try enabling logging and printing all incoming `events.Raw`?

**Comment by hcv57** [comment]
Thanks for the quick repsonse.

I am printing the update object in the update handler as per the example in the docs:

```
def callback(update):
    print('I received', update)
```
I've also enabled logging in my main code as shown below - I am still not sure how to do that properly in Python.

import logging
...

if __name__ == '__main__':
    # FIXME remove logging
    logger = logging.getLogger('telethon')
    logger.addHandler(logging.StreamHandler())
    logger.setLevel(logging.DEBUG)
    main()
```

If I run the code with a fresh session file the `callback` handler is never invoked and this is all I see:

```
Idling to receive items from the network
Receiving items from the network...
Receiving items from the network timed out
Receiving items from the network...
Receiving items from the network timed out
Receiving items from the network...
```

With the old session file I used during development it has lines such as:
`UpdateNewChannelMessage(message=Message(out=False, mentioned=...)`

**Comment by Lonami** [comment]
Please format your comment better.

**Comment by hcv57** [comment]
Done

**Comment by Lonami** [comment]
Are you sure you called connect/start and authorized the session file and that you can invoke methods and such?

**Comment by hcv57** [comment]
I've got this  `connection.py` module below and do a `from connection import client` in the code I want to use the `client`. I've tried to join chats with, for example, `client(JoinChannelRequest(entity))` and that works. 

```
from getpass import getpass
from telethon import TelegramClient
from telethon.errors import SessionPasswordNeededError, PhoneCodeInvalidError

...

def _setup_client():
    client = TelegramClient(
        config.TELEGRAM_SESSION,
        config.TELEGRAM_API_ID,
        config.TELEGRAM_API_HASH,
        update_workers = 4,
        spawn_read_thread=False)

    assert client.connect()

    if not client.is_user_authorized():
        client.send_code_request(config.TELEGRAM_PHONE)
        code_ok = False
        while not code_ok:
            code = input('Enter the auth code: ') or 'NOCODE'
            try:
                code_ok = client.sign_in(config.TELEGRAM_PHONE, code)
            except PhoneCodeInvalidError:
                print('Invalid code')
            except SessionPasswordNeededError:
                password = getpass('Two step verification enabled. Please enter your password: ')
                code_ok = client.sign_in(password=password)
    print('INFO: Client initialized succesfully!')
    return client

client = _setup_client()
```

**Comment by Lonami** [comment]
You must call `client.idle()` if you don't spawn a read thread.

**Comment by hcv57** [comment]
I am calling `idle()` in the main code that uses the `client` above howeve rit seems like it just took time for telegram to share updates with the client (perhaps some throttling on the Telegram side?). After a while I started to see updates trickling in. Thanks for your help.

**Comment by Lonami** [comment]
I'm not sure why Telegram sometimes stops delivering updates. As of `v0.17.3` I call `getState` every hour which should tell Telegram "hey, we're still here, don't stop sending us updates". It seemed to work when I tested it. Not sure what else we can do (pings alone are definitely not enough).
