### ISSUE TITLE
Group types limitations for GetParticipantsRequest

### ISSUE THREAD

**Issue by zxwild** [LonamiWebs/Telethon#628]
Are there any limitations to retrieve group members?

```python
# 1. this doesn't work, but I see this group (just simple group) 
# and its name is definetely 'c1admin'
client(GetParticipantsRequest('c1admin', ChannelParticipantsSearch(''), 0, 20, hash=0))

# Error:
# telethon.errors.rpc_error_list.UsernameNotOccupiedError: 
# The username is not in use by anyone else yet

# 2. just another group, but error is different (both these groups I'm joined)
client(GetParticipantsRequest('psy', ChannelParticipantsSearch(''), 0, 20, hash=0))

# Error:
# telethon.errors.rpc_error_list.UsernameInvalidError: 
# Nobody is using this username, or the username is unacceptable. 
# If the latter, it must match r"[a-zA-Z][\w\d]{3,30}[a-zA-Z\d]"


# 3. this works, I don't know why, it's just first group name which I could imagine
client(GetParticipantsRequest('mygroup', ChannelParticipantsSearch(''), 0, 20, hash=0))

# Response:
# <telethon.tl.types.channels.ChannelParticipants object at 0x7f9126fdac18>
```

Also I tried to play with `.get_dialogs` but `GetParticipantsRequest` doesn't take any of `entity`, `input_entity` attributes as the first parameter.

# 4.
```python
client(
    GetParticipantsRequest(
        dialog.input_entity, ChannelParticipantsSearch(''), 0, 20, hash=0)
)

# Error:
# TypeError: Cannot cast InputPeerChat to any kind of InputChannel.
```

I think I tried all variant which I could imagine.

**Comment by Lonami** [comment]
> and its name is definetely 'c1admin'

Unless you're using `master` (not the version from PyPi), getting an entity by name or title will *not* work that way. Get the peer through e.g. dialogs or username.

`'psy'` isn't a valid username, you should read the error.

`'mygroup'` works because it exists.

READ the error. Get participants wants a CHANNEL or megagroup, not a normal chat.

**Comment by Lonami** [comment]
It's not even read the manual. You need to read and understand the error messages. They are there for a reason.

**Comment by zxwild** [comment]
Are there ways to retrieve members from a `group`?

**Comment by Lonami** [comment]
"Get full chat".
