### ISSUE TITLE
Getting entity from bot with parameter 'start' does not work

### ISSUE THREAD

**Issue by danielleontiev** [LonamiWebs/Telethon#629]
When I call `get_entity('t.me/my_bot_name')` it works as expected, but `get_entity('t.me/my_bot_name?start=ABC')` crashes with exception `telethon.errors.rpc_error_list.UsernameInvalidError`

**Comment by Lonami** [comment]
Well exactly that. `'my_bot_name?start=ABC'` is not a valid username.

**Comment by danielleontiev** [comment]
It is possible to send parameters when interact with bots

**Comment by Lonami** [comment]
Yes.

**Comment by danielleontiev** [comment]
So, this client does not support such behavior, so, I assumed it is issue

**Comment by Lonami** [comment]
It does support such behaviour. It's simply not used that way. That method is used to retrieve an entity, like a bot in your case. It makes no sense to retrieve a bot with a parameter. Like I said, that username is invalid, and the error tells you so.

**Comment by Lonami** [comment]
You want #615.

**Comment by danielleontiev** [comment]
Yes, thank you, it solves my problem
