### ISSUE TITLE
parse_username don't correctly parse URL with "www" and "/" at the end

### ISSUE THREAD

**Issue by DrJackilD** [LonamiWebs/Telethon#630]
Hi. I noticed, that parse_username return incorrect username in two cases:
1. When meet urls like `http://www.t.me/ccointoken`
2. When got urls like `http://t.me/ReadyBusinessKe/`

Current regex for this is

```python
USERNAME_RE = re.compile(
    r'@|(?:https?://)?(?:telegram\.(?:me|dog)|t\.me)/(joinchat/)?'
)
```

I think problem with point 1 is `?` between protocol and `telegram|t.me` pattern. If we change it to `.+` - it works. Second I think may be fixed with `str.rstrip('/')`. I didn't make PR for this because regex is not my strong side and I'm not sure that my solution is correct.

Thank you!

**Comment by Lonami** [comment]
Not sure why in the world you would add `www.` to any URL nowadays though.

**Comment by DrJackilD** [comment]
@Lonami I'm not, but I found this bug, when work with list of 3500 telegram urls and found those two bugs.

**Comment by Lonami** [comment]
Sorry, you or anyone :P I still find it so strange when some websites *require* you to type in `www.` or they won't load at all…
