### ISSUE TITLE
Type of Update

### ISSUE THREAD

**Issue by chri1389** [LonamiWebs/Telethon#631]
Hello!
in the `def update_handler(update)...` when I receive an update, How can see the type of update?

for example, I would:
if isinstance(update, UpdateShortChatMessage):
         #do anything
      elif isinstance(update, UpdateShortMessage): 
         #do anything
      etc....

Thank you very much!

**Comment by Lonami** [comment]
Yep like that. Or read the documentation and use `events` instead.

**Comment by chri1389** [comment]
OK thanks...
Because the log return an error:
if isinstance(update, UpdateShortChatMessage):
NameError: name 'UpdateShortChatMessage' is not defined

**Comment by Lonami** [comment]
Well of course you need to import it like anything else in Python. Not related to the library.
