### ISSUE TITLE
Editing messages in the saved chat via Event doesn't work

### ISSUE THREAD

**Issue by Poolitzer** [LonamiWebs/Telethon#632]
Hey. I just used a simple code. Will drop it here so you dont have to write it for yourself. Simply doesn't work :D 

```
from telethon import TelegramClient, events
client.start()

@client.on(events.NewMessage(chats='me'))
def just_another_handler(event):
    if 'bevore' in event.raw_text:
        event.edit(str(event.raw_text.replace('bevore', 'before')))
        event.reply(str('Test'))
client.idle()
```

It works when the script edits a message in a channel.

**Comment by Lonami** [comment]
Oh I see, messages in your chat are for some reason incoming instead outgoing. There's a check to avoid editing unless they're outgoing (i.e. you sent them) so that's what's not working.

**Comment by Poolitzer** [comment]
A, great. So just disable the check for the me chat? :D

**Comment by Lonami** [comment]
Yeah that's the tricky part. I don't save the ID of the user who logged in anywhere.

**Comment by Poolitzer** [comment]
Hm. How are you able to use me instead of having to use the your number etc. then?

**Comment by Lonami** [comment]
There's a special `InputUserSelf()` type.

**Comment by Poolitzer** [comment]
Hm. Well, you are the dev, and I'm very glad that my little bot runs. So, have fun with this bug, but I won't be a big help at all :(

**Comment by Lonami** [comment]
Nothing too hard I just got distracted. Thanks for the star/bug report by the way.

**Comment by Poolitzer** [comment]
Whoa. You are good. That was a nice workaround :D

No problem, I love it so far. I just think that some working code examples would be great for some modules etc.

**Comment by Lonami** [comment]
There's read the docs with an examples sections and more examples in the `telethon_examples/`, though.

**Comment by Poolitzer** [comment]
I saw them in the docs I think. Let me finish my work here and then check.

**Comment by Poolitzer** [comment]
So, I found https://lonamiwebs.github.io/Telethon/#example. A bit... clean.

But yeah, otherwise I'm blind :D Was just overseeing this part.

**Comment by cscortes** [comment]
Could this be related to a change my own message text getting an error?
