### ISSUE TITLE
Last seen of an Entity

### ISSUE THREAD

**Issue by mmsamiei** [LonamiWebs/Telethon#635]
hello
Thank you very much for Telethon :+1:  :)
I have a question, how can i access to **last seen of an Entity**?

**Comment by Lonami** [comment]
@mmsamiei what have you tried?

**Comment by mmsamiei** [comment]
@Lonami I read your docs, yet I couldn't find anything useful

**Comment by Lonami** [comment]
Are you sure? The [`User`](https://lonamiwebs.github.io/Telethon/constructors/user.html) entity has a `.status` of type [`UserStatus`](https://lonamiwebs.github.io/Telethon/types/user_status.html)…

**Comment by andy1337** [comment]
> Are you sure? The [`User`](https://lonamiwebs.github.io/Telethon/constructors/user.html) entity has a `.status` of type [`UserStatus`](https://lonamiwebs.github.io/Telethon/types/user_status.html)…

I'm sorry I'm new in python can you explain me how I can get online status of user by @username (last seen # hours ago and etc).
