### ISSUE TITLE
Can't add user to supergroup

### ISSUE THREAD

**Issue by Jinqad** [LonamiWebs/Telethon#640]
Hey,
I am trying to add my other account to a super group but it doesn't seem to work
right now im using
`client(AddChatUserRequest(-100chat_id,"USERNAME",fwd_limit=10))
`
but when i run this 
it gives a struct.error: 'i' format requires -2147483648 <= number <= 2147483647
and ive searched online if anyone else has had the same issue but it doesnt seem like so i thought id let you know and if you could help me please.

**Comment by JosXa** [comment]
@Jinqad Remove the "100" from your chat_id

**Comment by Lonami** [comment]
1. That request is for normal groups. You want [`InviteToChannelRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/invite_to_channel.html).
2. The error message makes me think you're using an old version. The -100 should be okay, but prefer doing `PeerChannel(id)`.
