### ISSUE TITLE
Voice notes appear as 'unnamed' in the telegram app.

### ISSUE THREAD

**Issue by devxpy** [LonamiWebs/Telethon#641]
[here](https://uploadfiles.io/9ihp5) is that file.
Its wav, recorded using `arecord -d 5 test.wav`

here is the code i use.
`client.send_voice_note('@inf0geek', 'test.wav')`

P.S. i have tried sending that file from the app and it seems to play fine.

**Comment by Lonami** [comment]
Do you have `hachoir` installed?

**Comment by devxpy** [comment]
No, i see multiple python packages with that name, can you please point me to the correct one?

**Comment by Lonami** [comment]
No, it's okay. I was going to ask you to remove it.

**Comment by devxpy** [comment]
Could this be because its a wav file?

**Comment by Lonami** [comment]
Not sure, it's weird… With this code:
```python
client.send_voice_note('me', '/home/lonami/test.wav'
```

I get this on Telegram Desktop:
![image](https://user-images.githubusercontent.com/6297805/36645541-bb3cbc5a-1a6a-11e8-838a-ca11d628cfab.png)

Seems to work.

**Comment by devxpy** [comment]
![image](https://user-images.githubusercontent.com/19492893/36645547-8e72da26-1a90-11e8-8fbe-3c124124190d.png)
I get this, telegram desktop, Linux

**Comment by Lonami** [comment]
`unnamed` is the default name if you `open(filename, 'rb')` and pass the stream instead. But you're not doing that, you're passing the filename, right?

**Comment by devxpy** [comment]
![image](https://user-images.githubusercontent.com/19492893/36645566-eb217764-1a90-11e8-8227-5b76ec3ea76e.png)

This is what it appears like when i send directly using app

**Comment by devxpy** [comment]
Yes. directly passing filename. I also tried the absolute path, but that doesnt help.

**Comment by devxpy** [comment]
I tried using ogg file and it worked..Guess its some issue with telegram only

**Comment by Lonami** [comment]
Well, very strange because I get the filename from the path…:
https://github.com/LonamiWebs/Telethon/blob/e5aecca79ce77c6643cd87857918cf77ac6fb781/telethon/telegram_client.py#L1193-L1200

I just pushed https://github.com/LonamiWebs/Telethon/commit/3b0ab7794b7399f126a0088d8d3ad9e3b5ec1118 in case anyone passes `open()`.

> I tried using ogg file and it worked

Oh okay, no idea then ¯\\\_(ツ)\_/¯

**Comment by devxpy** [comment]
Even more wierd, that ogg file appears as audio file on iOS but generic file on web. 

It's definitely a telegram issue. I am going to submit an issue there
