### ISSUE TITLE
Can't run other functions while having telethon running

### ISSUE THREAD

**Issue by Jinqad** [LonamiWebs/Telethon#642]
Well when using the lib
```python
import json
from telethon import TelegramClient, events
import logging
import time

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s', datefmt='%m-%d %H:%M')
logger = logging.getLogger('bot')
logger.setLevel("DEBUG")
tclient = TelegramClient(phone, api_id, api_hash, update_workers=4, spawn_read_thread=False)
tclient.start()
eDict = None
b_prices = None 
def b_price_update():
	global b_prices
	b_prices = ...
	time.sleep(30)
	b_price_update()
def step_size_update():
	global eDict
	eDict = ...
	time.sleep(1000)
	step_size_update()

@tclient.on(events.NewMessage(chats=channel_id, incoming=True))
def handler(event):
	print(event.raw_text)
step_size_update()
b_price_update()
tclient.idle()
tclient.disconnect()
```
So when i run this it doesn't work at all i mean it just doesn't go into the idle bit and doesn't run the functions or i think it doesn't is there something in this lib which i can create a background task?
Like
```python
tclient.create_loop(step_size_update())
```

**Comment by Lonami** [comment]
`.idle()` is blocking. Don't set `spawn_read_thread=False` and then you don't have to call it.

**Comment by Lonami** [comment]
Although those sleeps are really high. The functions will only be called 4 times (number of update threads) and then all will sleep…

**Comment by Jinqad** [comment]
Oh you're saying i should remove `spawn_read_thread=False` and remove `tclient.idle()` and i need to update the variables every x seconds to update them from a API i didnt show there. Thanks

**Comment by Lonami** [comment]
I read your code really fast so my first assumption is you had code after the idle, but it's not the case. You have very large sleeps. Those are blocking. You should design it differently.

**Comment by Jinqad** [comment]
hmm i should use asyncio? instead of `time`

**Comment by Lonami** [comment]
Well if you know how to use it… There's a branch for that. Anyway there are way to schedule callbacks that don't block the code…

**Comment by Lonami** [comment]
Look online. This is not an issue with the library.
