### ISSUE TITLE
ForwardMessagesRequest with wrong params locks the update thread

### ISSUE THREAD

**Issue by LarsFox** [LonamiWebs/Telethon#643]
Hi!

If I send a ForwardMessagesRequest with the wrong `message_id`, I never manage to get to the end of the thread.

```
def callback(update):
    print('Gets printed')

    # Forwarding any received message to a certain ENTITY
    client(
        ForwardMessagesRequest(
            ENTITY,
            [update.id],  # if it is update.message.id it works perfectly fine
            ENTITY
        )
    )
    print('Never gets printed')
```

Not sure if it the problem with the library or with the response from Telegram.

Thanks!

**Comment by Lonami** [comment]
Well of course, just like in any other program if an exception is raised and you never except it, the program flow doesn't continue in the line after. You can enable logging and handle that case.

**Comment by LarsFox** [comment]
So basically there is an error deep inside which I cannot catch? How to then? The app never crashes and keeps receiving updates

**Comment by Lonami** [comment]
I never said you can't catch it.

**Comment by LarsFox** [comment]
Oh, man, that was really lame of me :(
