### ISSUE TITLE
How can I create client because  when I am creating using Python through Telethon it's not working please help me

### ISSUE THREAD

**Issue by rex101** [LonamiWebs/Telethon#644]

**Comment by Lonami** [comment]
If you *really* are having trouble you should have given more information. But honestly, I don't know what may be so hard to understand.

**Comment by rex101** [comment]
I am using Telethon and want to create client , I am using this code but not working : from telethon import TelegramClient

# (1) Use your own values here
api_id = 1234
api_hash = 'asdad465a464ad4a6d46a4d6a54d6a4'

phone = '+123457'
username = 'xyz_bot'

client = TelegramClient('session_name', api_id, api_hash)
client.start()

print(client)

and the error is : 

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from telethon import TelegramClient
  File "/home/xyz/Desktop/Telet/Telethon-0.15.5/telethon/__init__.py", line 2, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/home/xyz/Desktop/Telet/Telethon-0.15.5/telethon/telegram_bare_client.py", line 13, in <module>
    from .crypto import rsa, CdnDecrypter
  File "/home/xyz/Desktop/Telet/Telethon-0.15.5/telethon/crypto/__init__.py", line 1, in <module>
    from .aes import AES
  File "/home/xyz/Desktop/Telet/Telethon-0.15.5/telethon/crypto/aes.py", line 2, in <module>
    import pyaes
ImportError: No module named 'pyaes'
 ------------------------------------------------------------------------------------------------------------------------------
I am totally tired of this , tried many ways but not working

**Comment by Lonami** [comment]
> tried many ways but not working

Doubtful. Did you look online? You just had to `pip install pyaes`.

**Comment by Lonami** [comment]
Needless to say, the Telethon version you're using is pretty old.
