### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by facadev** [LonamiWebs/Telethon#648]
client.connect() failed constantly:

```
INFO:telethon.telegram_bare_client:Connecting to 149.154.167.51:443...
INFO:telethon.extensions.tcp_client:OSError "[Errno 61] Connection refused" raised while connecting
INFO:telethon.extensions.tcp_client:OSError "[Errno 61] Connection refused" raised while connecting
INFO:telethon.extensions.tcp_client:OSError "[Errno 61] Connection refused" raised while connecting
INFO:telethon.extensions.tcp_client:OSError "[Errno 61] Connection refused" raised while connecting
```

I'd like to change the default server ip, so I did as the documentation told me:
`client.session.server_address = '149.154.167.40'`
That resulted in an exception immediately:
`AttributeError: can't set attribute`

After some trials and errors, I found the set_dc() method did the work. Yet still, the connection was refused.

Any clue on what is going on? Do I need to configure anything before using the client? I was shown a public key after I created an app. Is that useful somehow?

**Comment by Lonami** [comment]
No, you shouldn't worry about that public key and either way, it doesn't kick into play well after estabilishing the initial connection (which you can't do).

No, I don't really know why the socket is unable to connect to Telegram servers at all. I would do a online search to reason about possible causes.

**Comment by Lonami** [comment]
- From https://www.reddit.com/r/Python/comments/2etkih/socketerror_errno_61_connection_refused/ I ask, is there anything on your computer using port 443? Just to make sure… this probably doesn't make a difference but I guess it's worth a try.
- From https://stackoverflow.com/a/29093630/4759433, do you have a firewall blocking the connection maybe?
- From https://github.com/DamnWidget/anaconda/issues/3, are you using OS X maybe? Seems like a 
super hack but if it works it works.
- From https://github.com/SAP/PyHDB/issues/58, it might be that you just can't connect to Telegram from there.

**Comment by facadev** [comment]
@Lonami Thank you so much for the detailed steps.

- I checked all the used ports locally and found no process was using 443.
- As for firewall, I can ping the IP address without any problem.
- I do use macOS, but no Anaconda.
- I can use the official Telegram without any connection issue.

**Comment by Lonami** [comment]
That's really strange then 😕. I'm out of ideas. It's failing on the lowest level (directly connecting through a socket), and if that fails I'm not sure what other options we have. Try port 80 instead 443.

**Comment by facadev** [comment]
The server is running on 443, which cannot be changed.
I tried connecting from somewhere else and everything went fine. I guess it is a geographical problem anyway. :)

**Comment by Lonami** [comment]
I'd still would like you to try connecting to Telegram on port 80. I think it should work too (even without HTTP mode implemented).
