### ISSUE TITLE
Get All Dialogs Problem

### ISSUE THREAD

**Issue by unkn19wn** [LonamiWebs/Telethon#649]
I Have Problem For Retrive All Dialogs From My Profile.

My Code Is This :
    dialogs = []
    users = []
    chats = []
    last_date = None
    chunk_size = 100
    offID=0
    while True:
        result = client.invoke(GetDialogsRequest(
            offset_date=last_date,
            offset_id=0,
            offset_peer=InputPeerEmpty(),
            limit=chunk_size,
        ))
        dialogs.extend(result.dialogs)
        users.extend(result.users)
        chats.extend(result.chats)
        print(dialogs[-1].peer)
        print(len(chats), len(users), len(dialogs))
        last_date = min(msg.date for msg in result.messages)
        print(last_date)
        sleep(1)
        if not result.dialogs:
            break

And The Answer i`ve Got is :

Client loaded and authorized.
PeerUser(user_id=423365606)
12 164 101
2017-06-17 15:36:06
PeerChat(chat_id=224532642)
16 195 132
2017-05-15 04:16:58
PeerChat(chat_id=224532642)
18 196 133
2017-05-15 04:16:58
PeerChat(chat_id=224532642)
20 197 134
2017-05-15 04:16:58
PeerChat(chat_id=224532642)
22 198 135
2017-05-15 04:16:58

i have more than 400 dialogs but i only get the first 100 
Thanks

**Comment by Lonami** [comment]
`client.get_dialogs(limit=None)`.

**Comment by unkn19wn** [comment]
result = client.get_dialogs(None)
    print(result)

took 20 min and nothing happend
same thing happening

**Comment by Lonami** [comment]
Well then you should enable logging maybe.

**Comment by unkn19wn** [comment]
INFO:telethon.telegram_bare_client:Connecting to 149.154.167.51:443...
INFO:telethon.telegram_bare_client:Connection success!
DEBUG:telethon.telegram_bare_client:Invoking GetStateRequest
INFO:telethon.telegram_bare_client:Initializing a new connection while invoking
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: InvokeWithLayerRequest: 6527321245918101632
DEBUG:telethon.network.mtproto_sender:Processing BadServerSalt result
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: InvokeWithLayerRequest: 6527321246524729096
DEBUG:telethon.network.mtproto_sender:Processing container result
DEBUG:telethon.network.mtproto_sender:Processing NewSessionCreated result
DEBUG:telethon.network.mtproto_sender:Processing MsgsAck result
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6527321246524729096
INFO:telethon.telegram_bare_client:Starting to wait for items from the network
Client loaded and authorized.
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking GetUsersRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: GetUsersRequest: 6527321247116297092
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6527321247116297092
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking ResolveUsernameRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: ResolveUsernameRequest: 6527321247722413388
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6527321247722413388
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking ResolveUsernameRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: ResolveUsernameRequest: 6527321252274752584
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6527321252274752584
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking GetDialogsRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: GetDialogsRequest: 6527321253827644316
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6527321253827644316
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking GetDialogsRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: GetDialogsRequest: 6527321261453731748
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6527321261453731748
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking GetDialogsRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: GetDialogsRequest: 6527321271184925532
DEBUG:telethon.network.mtproto_sender:Processing UpdateShort result
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6527321271184925532
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.telegram_bare_client:Invoking GetDialogsRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: GetDialogsRequest: 6527321275261029340
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result

**Comment by Lonami** [comment]
Well if it's "going on" maybe you do have a lot of dialogs cause that's just normal behaviour. 20 minutes is stupidly long though.
