### ISSUE TITLE
Is there any function or class that returns "media" downloadable link? 

### ISSUE THREAD

**Issue by mowhamadrexa** [LonamiWebs/Telethon#651]
As I understand, Telegram's server create a temporary link and we can download the medias through the link, how can I know what is the link? I tried FileLocation, and InputFileLocation but they wouldn't help.

**Comment by Lonami** [comment]
No, there's no such thing. However, if you have a `FileLocation` or its `Input` version you can download the files with those (method `client.download_file`).

**Comment by jimist** [comment]
I need this method too.

I've traced the download until InputDocumentFileLocation but can't get how it is getting the file from CDN!

Is it not possible to get the link from telegram at all? @Lonami

**Comment by Lonami** [comment]
> I need this method too.

> No, there's no such thing.

> but can't get how it is getting the file from CDN!

Should be handled by the library. If it's, you know the file is in a CDN (hint: enable logging), you can help out over #598.

> Is it not possible to get the link from telegram at all?

**There's no such thing as a link if you sign in as an user.**
