### ISSUE TITLE
problem with GetAdminLogRequest method

### ISSUE THREAD

**Issue by zohre70** [LonamiWebs/Telethon#656]
hello. I recently installed telethon. It works perfect in other methods but I have problem in running GetAdminLogRequest method.
This is my code: 

`from telethon import TelegramClient
api_id = xxxx
api_hash = 'xxxx'
client = TelegramClient('anon', api_id, api_hash)
assert client.connect()

from telethon.tl.functions.channels import GetAdminLogRequest

participants = client(GetAdminLogRequest(
    'https://t.me/rssfeedtest', q='string',max_id=1073741829,min_id=1073741824,limit=10
))
print(participants.stringify())`

It prints:
`AdminLogResults(
          chats=[
          ],
          users=[
          ],
          events=[
          ]
)`
and its empty!
I get min_id & max_id from recent action messages ids in my telegram. and I don't know what I exactly must write for q parameter.
Thanks in advanced for your help.

**Comment by Lonami** [comment]
`q` is query (search). Try leaving both `max_id` and `min_id` empty (`0`). To iterate over the entire log pick up the `min()` ID and set that to `max_id`.
