### ISSUE TITLE
Invite to channel methon error , not able to add member in group

### ISSUE THREAD

**Issue by rex101** [LonamiWebs/Telethon#659]
I have written all codes to add my friend in my group and I am admin also, but when I am executing it shows error 

Traceback (most recent call last):
  File "test.py", line 86, in <module>
    r = client(InviteToChannelRequest(channel, users))
  File "C:\Users\xyz\Desktop\tel\Telethon-master\telethon\telegram_bare_client.py", line 443, in __call__
    result = self._invoke(call_receive, *requests)
  File "C:\Users\xyz\Desktop\tel\Telethon-master\telethon\telegram_bare_client.py", line 532, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.ChatWriteForbiddenError: You can't write in this chat

----------------------------------------------------------------------------------------------------

MY CODE IS : 

resultc = client.invoke(ResolveUsernameRequest('abc'))
channel = InputChannel(resultc.peer.channel_id, resultc.chats[0].access_hash)
resultu = client.invoke(ResolveUsernameRequest('xxx'))
user1 = InputUser(resultu.peer.user_id, resultu.users[0].access_hash)

users = [user1]

r = client(InviteToChannelRequest(channel, users))

**Comment by Lonami** [comment]
It's exactly that. **You don't have permission to add members and the error is telling you**.

**Comment by Lonami** [comment]
I don't know. The error is being returned by the API. There's nothing I can do about it.

**Comment by rex101** [comment]
ok let me find myself :(

**Comment by MaxKUlish1** [comment]
Guys, this is a really weird bug, but to fix it we need to create a channel from a second account and make ourselves an admin in it. We definitely need to report this to Telegram.
