### ISSUE TITLE
How to publish @vote poll?

### ISSUE THREAD

**Issue by pazis** [LonamiWebs/Telethon#66]
Imagine I have made a poll using `@vote` bot. How can I publish it to a list of `chatID`s I have in Telethon? 😵

**Comment by Lonami** [comment]
Try searching for "[bot](https://lonamiwebs.github.io/Telethon/)" on the documentation. I found these results:
- [`GetInlineBotResultsRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_inline_bot_results.html)
- [`SendInlineBotResultRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/send_inline_bot_result.html)

I would say those work. If they do please close the issue and you may want to post the solution here so other people can find it too :)

**Comment by pazis** [comment]
Actually, I had read both pages, but couldn't figure out the arguments. `random_id`!? `offset`!? No idea what to pass to the function!

**Comment by Lonami** [comment]
`random_id` is clearly a random ID [(!)](https://github.com/LonamiWebs/Telethon/blob/af9fbbb4635515efb76c4a01deacbf7280c9dff3/telethon/helpers.py#L7), and offset is probably the offset of the results. So, try passing `offset=0`, since you don't want to skip any.

**Comment by pazis** [comment]
Thanks @Lonami. Yeah `random_id` seems to be self-explaining, but why the hell do we have to pass a random number!? Couldn't they make a random number server-side, which looks to be a better approach!?

**Comment by Lonami** [comment]
> why the hell do we have to pass a random number!?

¯\_(ツ)_/¯

> Couldn't they make a random number server-side, which looks to be a better approach!?

I don't know why they did it the way the did. Perhaps it's so people can't spam by resending certain packets without modifying the random ID (which would first involve decoding the packet).
