### ISSUE TITLE
How to remove admin rigths from all Chat participants ?

### ISSUE THREAD

**Issue by dharmagetic** [LonamiWebs/Telethon#660]
Good day!
I'm have an issue in removing admin rights from all Chat participants. After creating a chat, I make a query EditChatAdminRequest(chat_id, input_user, False) for every chat participant, but result differs than I suspect. Invitable user still can add participants and change chat avatar i.e. invitable user still have admin rights.

**Comment by Lonami** [comment]
Maybe you have to disable "everyone is admin" first (I think that's a default on normal group chats?) For channels (and megagroups) there is a different request.

**Comment by dharmagetic** [comment]
Yeah, I create a default on normal group chats. And yes, I have to disable "everyone is admin" settings for these chats. But how should I disable this programmatically ? In CreateChatRequest I haven't saw this setting in constructor or other place. Can you please guide me ?

**Comment by Lonami** [comment]
I've never done this. I would use the search over https://lonamiwebs.github.io/Telethon until I found what I needed. That's how I solve most issues here anyway and that's something you can do too. The API is a mess. I don't know every bit :/

**Comment by Lonami** [comment]
Oh, was simple. [`ToggleChatAdminsRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/toggle_chat_admins.html).

**Comment by dharmagetic** [comment]
Thank you!
Damned! I thought to use this request before, but it has strange name so I wan't
Thank you very much! You are awesome!
