### ISSUE TITLE
Error in disabling "everyone is admin" by invoking ToggleChatAdminsRequest

### ISSUE THREAD

**Issue by dharmagetic** [LonamiWebs/Telethon#661]
When I try to disable "everyone is admin" in Chat settings, by invoking ToggleChatAdminsRequest I got ChatNotModifiedError(...), "The pinned message wasn't modified"
It's strange, but how admin settings relate to pins ?

**Comment by Lonami** [comment]
I grab error descriptions from @danog's API (https://rpc.pwrtelegram.xyz/?description_for=CHAT_NOT_MODIFIED in this case). The description is "The pinned message wasn't modified". I guess it's not always the case. Maybe it was already disabled/enabled so it didn't modify the state.
