### ISSUE TITLE
Phone code always expires

### ISSUE THREAD

**Issue by facadev** [LonamiWebs/Telethon#663]
This is a weird problem I've recently encountered.

```
# Cell 1
client = TelegramClient(session_name, api_id, api_hash)
client.connect()

# Ensure you're authorized
if not client.is_user_authorized():
    client.send_code_request(phone)

# Cell 2
# Wait for the code, and run the next statement once it's received.
client.sign_in(phone, 'xxxxx')
```
In Jupyter, this works fine. However, when I run it in Python3 Interactive Shell, weird things happen.

When I call sign_in(), it throws an exception, telling me that I have to pass in phone_code_hash. No problem. I can get it via `phone_code_hash = client.send_code_request(phone).phone_code_hash`. OK then. How about calling sign_in() again? This time, it keeps telling me that my code has expired, no matter how many times I try, and the issue persists even when I switch to another phone number of mine.

Is there anything I've missed?

**Comment by Lonami** [comment]
You can use:
```python
client.start()
```

Instead:
```python
client.connect()
if not client.is_user_authorized():
    client.send_code_request(phone)

client.sign_in(phone, 'xxxxx')
```

This should ease your workflow significantly as well as making sure you're not doing any silly mistake.

Also, make sure you are *not* sending the code over Telegram. It expires inmediatly if you do so.
