### ISSUE TITLE
Send message to Group

### ISSUE THREAD

**Issue by caarl21** [LonamiWebs/Telethon#664]
Hello!
If "client" is authorized and if I have the "id" of a specific group of the client, How can I send a message to this specific group?

I am sorry, but I have read the documentation and I did not succeed!

**Comment by Lonami** [comment]
Did you read http://telethon.readthedocs.io/en/latest/extra/basic/entities.html?

**Comment by Lonami** [comment]
Hm, perhaps I should update that page to reflect "recent" changes.

**Comment by caarl21** [comment]
Thank you very much!

Yes, I have read the page but unfortunately I did not understand how it works..sorry

**Comment by Lonami** [comment]
Right. You can use `PeerChat(id)` as the "entity" to which you want to send the message or whatever.

**Comment by caarl21** [comment]
Ok thank you very much, you are very kind!
I write the code, so it could be useful to other users:

from telethon.tl import types
..
group = client.get_entity(type.PeerChat(...idGroup as integer...))
client.send_message(group, "text to send...")
