### ISSUE TITLE
thumbnail of images

### ISSUE THREAD

**Issue by mamdosein97** [LonamiWebs/Telethon#669]
Hello again. thanks for your amazing library and your very quick answering!!
how i can download images thumbnail? i didn't find anything after many search and reading docs.
 is there any way to download them?

**Comment by Lonami** [comment]
[`Photo`](https://lonamiwebs.github.io/Telethon/constructors/photo.html)'s have many [`PhotoSize`](https://lonamiwebs.github.io/Telethon/types/photo_size.html). Pick the smallest and `.download_media()` that. If it doesn't work, say it here because I might be missing a case for it.

**Comment by mamdosein97** [comment]
thanks. i will go company in day after tomorrow and will do your both suggests and will report results here.
thanks

**Comment by Lonami** [comment]
There was no need to create a clone… Nevermind.

**Comment by Lonami** [comment]
Like I expected, `client.download_media()` wouldn't accept a `PhotoSize`. Now it does.

**Comment by snowman** [comment]
```python
client.download_media(message, thumb=-1)
```
