### ISSUE TITLE
Blob does not exist in Postgres

### ISSUE THREAD

**Issue by alper** [LonamiWebs/Telethon#670]
I've got the `AlchemySessionContainer` setup with my Postgres connection on heroku, but if I then try to use it I get this error:
```
(psycopg2.ProgrammingError) type "blob" does not exist
LINE 7:  auth_key BLOB, 
                  ^
 [SQL: '\nCREATE TABLE telethonsessions (\n\tsession_id VARCHAR NOT NULL, \n\tdc_id INTEGER NOT NULL, \n\tserver_address VARCHAR, \n\tport INTEGER, \n\tauth_key BLOB, \n\tPRIMARY KEY (session_id, dc_id)\n)\n\n']
```

It seems to be the case that the BLOB type does not exist in Postgres (there they call it a BYTEA). The solution would seem to be to replace that with the [LargeBinary](http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.LargeBinary) type which should resolve to the correct type per database.

**Comment by Lonami** [comment]
Would you like to make a pull request?
