### ISSUE TITLE
Filter user chats out of Gui Dialog Window 

### ISSUE THREAD

**Issue by TriptonPt** [LonamiWebs/Telethon#672]
Any way to edit the dialogs window code to filter out the user chats and only list groups ?

 while True:
            # Retrieve the top dialogs. You can set the limit to None to
            # retrieve all of them if you wish, but beware that may take
            # a long time if you have hundreds of them.
            dialog_count = 15

            # Entities represent the user, chat or channel
            # corresponding to the dialog on the same index.
            dialogs = self.get_dialogs(limit=dialog_count)

            i = None
            while i is None:
                print_title('Dialogs window')

                # Display them so the user can choose
                for i, dialog in enumerate(dialogs, start=1):
                    sprint('{}. {}'.format(i, get_display_name(dialog.entity)))

**Comment by Lonami** [comment]
Well, sure, nothing stops you from doing `isinstance(dialog.entity, types.User)` or whatever you need but this is not a problem with the library.
