### ISSUE TITLE
Draft needs .send() method

### ISSUE THREAD

**Issue by JosXa** [LonamiWebs/Telethon#673]
The custom `Draft` tl object should get a method to actually execute the pending draft, i.e. sending it to the peer.

**Comment by Lonami** [comment]
I would swear they had one and you also had an optional `clear`. Maybe I've dreamt that.

**Comment by JosXa** [comment]
https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/custom/draft.py

I remember the `clear` hmm..

**Comment by Lonami** [comment]
Should probably modify it to have `.text` and `.raw_text`, just like `events.NewMessage.Event`.

**Comment by JosXa** [comment]
For sure
