### ISSUE TITLE
cannot get the channel_id for some deleted messages in groups

### ISSUE THREAD

**Issue by dales** [LonamiWebs/Telethon#675]
Python 3.6.3
Since latest version in pypy 0.18.0.1 I cannot get the channel_id for some deleted messages in groups

```python
event._chat_peer.to_id.channel_id 
```
results in  

```
'NoneType' object has no attribute 'channel_id'
```

Is there another way to know what group a message was deleted from. The message ID is not enough

**Comment by Lonami** [comment]
Could you be more specific?

**Comment by dales** [comment]
I have a group with myself and another user (for test purposes). When i add messages in the group i can create a unique ID by joining the channel id with the message ID. When I delete a message, the event object has no way to identify what group it was removed from. This does not happen with a channel (and i suspect supergroup)

```python
@client.on(events.MessageDeleted())
def normal_handler(event):
   try:
       print("{}_{}".format(event._chat_peer.to_id.channel_id, event.deleted_id))
   except Exception as e:
       pass
```

**Comment by Lonami** [comment]
Okay probably related to #674. Can you install the library from git?

**Comment by dales** [comment]
yes I can try that. Are there a lot more fixes there?

this is what my _chat_peer looks like (excluding the confirm_received object)

```python
{  
  "rpc_error":null,
  "result":null,
  "content_related":false,
  "out":null,
  "mentioned":null,
  "media_unread":null,
  "silent":null,
  "post":null,
  "id":150,
  "from_id":null,
  "to_id":null,
  "fwd_from":null,
  "via_bot_id":null,
  "reply_to_msg_id":null,
  "date":null,
  "message":"",
  "media":null,
  "reply_markup":null,
  "entities":null,
  "views":null,
  "edit_date":null,
  "post_author":null,
  "grouped_id":null
}
```

**Comment by Lonami** [comment]
Well it fixes a bug building deleted events so…

**Comment by dales** [comment]
Can i install it directly into my virtual environment?

**Comment by dales** [comment]
i should build from master?

**Comment by Lonami** [comment]
Probably. I don't work with virtual environments. I'll definitely push to PyPi when I get a chance.

**Comment by dales** [comment]
Things seem to be a lot worse now. When deleting messages in a channel the DeletedMessage handler gets fired several times, and its not firing at all when deleting messages from a group

**Comment by Lonami** [comment]
Well that's for sure not something introduced now, I had reports before. Strange though since I did a quick test and it didn't happen.

**Comment by dales** [comment]
before i installed from master:

- Didnt get duplicated events being called
- Was able to get event on group delete (but no ID)

**Comment by Lonami** [comment]
It would be awesome if you could `git bisect` to find where it started failing with duplicated events.

**Comment by dales** [comment]
never done a git bisect before. seems pretty straight forward. will give it a try

**Comment by dales** [comment]
I went all the way back to fe627d197003ca3774cfaf76b85ca1a4866cb630

Each time i did
python setup.py build
python setup.py install

And still reproduced.

Will try go bath further later when i have some time

**Comment by Lonami** [comment]
@dales thanks, so we know v0.18.0.1 didn't introduce this.

**Comment by dales** [comment]
@Lonami I think commit c40a3ca77ca8e844203a45d9a51cd21cc6e12a5d messed things up a bit.

I checked out 854c42b7ef25763bb5f14290e32c714164d0ace4 and I was able to get the event when deleting messages from the group using the MessageChanged function but still there is no value in _chat_peer so I cant get the ID of the group it was deleted from, only the deleted_ids (which isnt enough)

**Comment by Lonami** [comment]
Neat thanks, silly call that was needed for the older class but not the common base which I forgot to update. `git bisect` was supposed to help out spot that "double event bug", not this, but still helpful.

**Comment by mamdosein97** [comment]
Hello
sometimes on deleting a group of messages, no update event (events.MessageDeleted()) will occur and nothing will be generated. i see logging in logging.DEBUG level and nothing is printed. What should i do?

**Comment by Lonami** [comment]
There's nothing I can do if Telegram doesn't deliver the update at all.

**Comment by mamdosein97** [comment]
so how it is deleted from all my official clients?
have you ever faced with my problem?

**Comment by Lonami** [comment]
No.

**Comment by mamdosein97** [comment]
these logs means that telegram didn't deliver the update at all??

DEBUG:telethon.extensions.tcp_client:socket.timeout "timed out" while reading data
DEBUG:telethon.telegram_bare_client:Receiving items from the network timed out
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.extensions.tcp_client:socket.timeout "timed out" while reading data
DEBUG:telethon.telegram_bare_client:Receiving items from the network timed out
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.extensions.tcp_client:socket.timeout "timed out" while reading data
DEBUG:telethon.telegram_bare_client:Receiving items from the network timed out
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.extensions.tcp_client:socket.timeout "timed out" while reading data
DEBUG:telethon.telegram_bare_client:Receiving items from the network timed out
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.extensions.tcp_client:socket.timeout "timed out" while reading data
DEBUG:telethon.telegram_bare_client:Receiving items from the network timed out
DEBUG:telethon.telegram_bare_client:Receiving items from the network...

**Comment by Lonami** [comment]
That's correct, it means Telegram didn't send anything. Does it work before a long time passes while running the script?

**Comment by mamdosein97** [comment]
it doesn't matter to the time of running the script.
it's strange and doesn't have any pattern that i can understand when it works and when it doesn't.
for some deletes the updates come and for some doesn't!
