### ISSUE TITLE
Question: Is it possible to receive the content of GetHistoryRequest as JSON?

### ISSUE THREAD

**Issue by mohsenkhanpour** [LonamiWebs/Telethon#677]
Hi, first of all thanks for this great repository. When I use the GetHistoryRequest the content comes in this format. 
`ChannelMessages(
	pts=5299,
	count=5064,
	messages=[
		Message(
			out=False,
			mentioned=False,
			media_unread=False,
			silent=False,
			post=True,
                        ....`
It is not a proper JSON. 
1.What kind of array is that?
2.How can I convert it to JSON so I can explore them more easily?

**Comment by Lonami** [comment]
> Is it possible to receive the content of GetHistoryRequest as JSON?

Yes.

**Comment by Lonami** [comment]
More seriously though you can use `.to_dict()` on any item to turn it into a dictionary and then [look online](https://ddg.gg/python%20json) to turn that into a JSON. It's not an array. It's just a representation that lets you build the exact same object back while also showing its members.

**Comment by Lonami** [comment]
Also `print(x.stringify())` if you want something friendly. It's all in the docs...

**Comment by mohsenkhanpour** [comment]
Thanks for your fast response, I have read the docs and I am already using `print(x.stringify())` .
I have also read about Python JSON and my research got me through to this point:

``` 
result = client(GetHistoryRequest(
    peer=#############,    # On which chat/conversation
    offset_date=None,       # Maximum date
    offset_id=0,            # ID of the message to use as offset
    add_offset=0,           # Additional offset
    limit=5,                # How many results
    max_id=0,               # Maximum message ID
    min_id=0,               # Minimum message ID
    hash=0                  # Who must have sent the message (peer)
))
print(result)

stringdata = result.stringify()
with open('data.json', 'w', encoding='utf-8') as f:
  json.dump(stringdata, f, ensure_ascii=False,sort_keys=True, indent=4, separators=(',', ': '))
```
This picture is the content of my data.json in which the messages are not separated properly.
![image](https://user-images.githubusercontent.com/28626829/37221979-e39cf79e-23e0-11e8-9319-11c99aca1c44.png)

As I told you I am using `print(x.stringify())` but the reason I am want the content in JSON is that I want to use Telethon to write a bot to remove duplicate messages from my channel (as it's being updated by RSS sometimes there are duplicates)
I want to be able to modify the content using some code like this: https://stackoverflow.com/questions/17076345/remove-duplicates-from-json-data

Thanks again.

**Comment by mohsenkhanpour** [comment]
Should I use `stringdata.to_dict()` before using `json.dump`?

**Comment by tulir** [comment]
> Should I use `stringdata.to_dict()` before using `json.dump`?

Yes, obviously.

> I want the content in JSON is that I want to use Telethon to write a bot to remove duplicate messages from my channel (as it's being updated by RSS sometimes there are duplicates)

Why do you want it as JSON for that...? Converting to JSON does not help with finding duplicates in any way.

**Comment by mohsenkhanpour** [comment]
> Why do you want it as JSON for that...? Converting to JSON does not help with finding duplicates in any way.
Coming from Node I thought it would be more familiar. And during my research I came through this: https://stackoverflow.com/questions/17076345/remove-duplicates-from-json-data

So I thought that way I can get the list of all messages of the channel, convert to json, and list the messages by their `message` entity, and if they are more than one, I keep one and remove the duplicates using: `DeleteMessagesRequest`

So far it has been confusing for me, if you know any better way I would be more than glad to hear about it.

**Comment by mohsenkhanpour** [comment]
> Yes, obviously.

`stringdata.to_dict()` brings about an `AttributeError: 'str' object has no attribute 'to_dict'`

**Comment by tulir** [comment]
> Coming from Node I thought it would be more familiar

No. You need to use whatever works in the language. JSON is not native to Python, so don't use it unless you have to.

> And during my research I came through this: https://stackoverflow.com/questions/17076345/remove-duplicates-from-json-data

Nothing there is really JSON-specific. Also, there all the examples are *reading* JSON and processing the dict rather than converting anything to JSON.

> So I thought that way I can get the list of all messages of the channel, convert to json, and list the messages by their `message` entity, and if they are more than one, I keep one and remove the duplicates using: `DeleteMessagesRequest`

Yes, that's the way to do it, except converting to JSON is completely unnecessary and will just make things harder.

You can do something like this:
```python
found_messages = []
for message in messages:
    if message.message in found_messages:
        # Handle duplicate here
    else:
        found_messages.append(message.message)
```

> `stringdata.to_dict()` brings about an `AttributeError: 'str' object has no attribute 'to_dict'`

Ah, I didn't read your message closely enough. `stringify()` will convert the message into a string and `to_dict()` will convert it to a dict, they're completely different things and you need to use `message.to_dict()` and not `stringify().to_dict()`

**Comment by mohsenkhanpour** [comment]
Thanks for helping out @tulir.  I read about Python dicts online and I was able to extract the `messages` section of `ChannelMessages`
In the snippet you have shared we have `found_messages` and `messages` : how are they different?

In writing my code when I use the snippet you shared, I get an error regarding `messages` not being defined. Then I assigned `result.messages` to `messages` which makes the earlier `found_messages` redundant

This is my code:
```
found_messages = result.to_dict()['messages']
messages = result.messages


for message in messages:
    if message.message in found_messages:
        print(message.id)
    else:
        found_messages.append(message.message)
```

**Comment by tulir** [comment]
> In the snippet you have shared we have `found_messages` and `messages` : how are they different?

`found_messages` is the list of messages the code has already seen. If the code encounters the content in `found_messages` again, they're duplicates and should be removed.

> Then I assigned `result.messages` to `messages`

Yes, that was the intention (though you could've just replaced `messages` with `result.messages`)

> which makes the earlier `found_messages` redundant

No, it doesn't.

<blockquote>This is my code:
<pre>
found_messages = result.to_dict()['messages']
messages = result.messages
</pre>
</blockquote>

First of all, forget `to_dict()`. You don't need it.

Secondly, `found_messages` is supposed to be empty. The point is that you loop through messages and add the content to `found_messages`, except if the content is already there in which case you know that message is a duplicate and can be removed.

**Comment by mohsenkhanpour** [comment]
Thanks @tulir. You have been a great help to me. This way that I learned from you is much simpler.
And also thanks for giving comprehensive answers.

I was able to get the duplicates using this code:
```
found_messages = []
for message in messages:
    if message.media.caption in found_messages:
        print(message.id)
    else:
        found_messages.append(message.media.caption)
    
print(found_messages)
```
Now I am able to import `DeleteMessagesRequest` and replace `print(message.id)` in my loop with `channels.deleteMessages#84c1fd4e channel:InputChannel id:Vector<int> = messages.AffectedMessages`

Practically I am now able to do what I intended. But two more technical questions which I am asking just to improve my knowledge and learn:

1. If I put `channels.deleteMessages` in my loop it will do it for each duplicate. How can I collect all of the `id`s and just run the `channels.deleteMessages` once. 
That way I can use the Vector feature of the request too.

2. In my `GetHistoryRequest`, I have:
```
result = client(GetHistoryRequest(
    peer=############,    # On which chat/conversation
    offset_date=None,       # Maximum date
    offset_id=0,            # ID of the message to use as offset
    add_offset=0,           # Additional offset
    limit=10000,                # How many results
    max_id=0,               # Maximum message ID
    min_id=0,               # Minimum message ID
    hash=0                  # Who must have sent the message (peer)
))
```
How can I reconfigure it to get the all of the messages of my channel? (I tried setting `limit` to `0` and `none` and it didn't work)
