### ISSUE TITLE
GetAdminLogRequest method skips some actions

### ISSUE THREAD

**Issue by zohre70** [LonamiWebs/Telethon#679]
hello, I use GetAdminLogRequest method to get recent actions from my channel that has 82k members. my problem is that the method skips some actions and does not show all of them. this is my code:
`actions = client(GetAdminLogRequest(
    "https://t.me/majale_javanan", q=" ",max_id=0,min_id=0,limit=10,events_filter=ChannelAdminLogEventsFilter(join="true",leave="true",invite="true",ban="true",kick="true")
))`

**Comment by mohsenkhanpour** [comment]
Telegram only holds Recent Actions for 48 hours.
Also you have set the limit to 10. So that may be your problem.

**Comment by Lonami** [comment]
Thanks for the answer @mohsenkhanpour. It's exactly that.

**Comment by zohre70** [comment]
no, I also set limit in 100 and checked users and actions one by one and compare with recent action list in telegram app. but it shows two action skips three actions, again show 4 and skip 2 ... and so on.
I searched a lot and can't find the problem

**Comment by mohsenkhanpour** [comment]
@zohre70 when specifying your filter, you have set it to return data related to `(join="true",leave="true",invite="true",ban="true",kick="true")` so the result will filter out only the ones you have asked for. 
This constructor has more options, if you want a complete list of the log you should set more of them to `true` .

Please read this link for more information.
https://lonamiwebs.github.io/Telethon/constructors/channel_admin_log_events_filter.html

I hope this has helped you.

**Comment by mohsenkhanpour** [comment]
@zohre your snippet will return `join` and`leave` log for example as you have set them to `true`, but will not return `settings` or `pinned` as you have not asked for it in your request.

**Comment by zohre70** [comment]
thanks @mohsenkhanpour, but I just need these filters. however It has the same behavior when I'm not setting filters at all. I need only these filters and some of leaves and joins has been skipped and are not shown.

**Comment by mohsenkhanpour** [comment]
In that case upload the log from your Telethon request, and the log from your Telegram application, and infrom @Lonami for a more comprehensive answer or workaround.
