### ISSUE TITLE
event.delete() not work in "Working with Updates event.ChatAction "

### ISSUE THREAD

**Issue by m3r3lin** [LonamiWebs/Telethon#680]
event.delete() not work in working with updates for ChatAction

please help me

**Comment by Lonami** [comment]
@m3r3lin you should give more information.

**Comment by m3r3lin** [comment]
my code:
@client.on(events.ChatAction)
def add_to_group(event):
    print(event.build)
    if event.user_added:
        event.respond('wellcome')
        event.delete()

i need remove "add message" in group

but event.delete() not work

**Comment by Lonami** [comment]
@m3r3lin you should enable logging. I'm not sure what you're trying to achieve with event.build.

**Comment by m3r3lin** [comment]
@Lonami  How to enable logging?

**Comment by Lonami** [comment]
@m3r3lin look online.

**Comment by m3r3lin** [comment]
but added message don't deleted with event.delete() in @client.on(events.ChatAction)
i'm sure :(

**Comment by Lonami** [comment]
I'm fairly sure `events.build` doesn't exist. The documentation (section on using events) advices you to use `logging` too. You could have asked how to enable it in a search engine instead here. Just remove that `print`.

**Comment by Lonami** [comment]
Also that event doesn't have a `.respond()` so of course it will fail.

**Comment by Lonami** [comment]
#681.
