### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'MessageService'

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#681]
int() argument must be a string, a bytes-like object or a number, not 'MessageService'
It happened when event.delete()

**Comment by m3r3lin** [comment]
i have same problem with @client.on(events.ChatAction)

**Comment by Lonami** [comment]
@m3r3lin you didn't tell me that though.

**Comment by realiza** [comment]
what's the solution? please help me

**Comment by m3r3lin** [comment]
@Lonami  Sorry You are right
