### ISSUE TITLE
Peer always set to None on UpdateDeletedMessages

### ISSUE THREAD

**Issue by dales** [LonamiWebs/Telethon#682]
Peer is always sent to None on UpdateDeletedMessages

```python
 def build(self, update):
        if isinstance(update, types.UpdateDeleteMessages):
            event = MessageDeleted.Event(
                deleted_ids=update.messages,
                peer=None
            )
        elif isinstance(update, types.UpdateDeleteChannelMessages):
            event = MessageDeleted.Event(
                deleted_ids=update.messages,
                peer=types.PeerChannel(update.channel_id)
            )
        else:
            return
```

the code before this included the peer

```python
    def build(self, update):
        if isinstance(update, (types.UpdateEditMessage,
                               types.UpdateEditChannelMessage)):
            event = MessageChanged.Event(edit_msg=update.message)
        elif isinstance(update, (types.UpdateDeleteMessages,
                                 types.UpdateDeleteChannelMessages)):
            event = MessageChanged.Event(
                deleted_ids=update.messages,
                peer=types.PeerChannel(update.channel_id)
            )
        else:
            return

        return self._filter_event(event)
```

**Comment by Lonami** [comment]
We fixed this on #675, I just didn't push to PyPi yet.

**Comment by Lonami** [comment]
It is not, as `v0.18.0.3`.

**Comment by dales** [comment]
:+1:

**Comment by Lonami** [comment]
Well, that object doesn't have a peer at all. This doesn't affect megagroups.

**Comment by dales** [comment]
So how can I found out which group a message was deleted from? (This was my initial problem). Channels works fine, but there is no information about group when a message is deleted from it

**Comment by Lonami** [comment]
There should be a "getmessages" request that needs only the ID.

**Comment by dales** [comment]
If i have a handler 

```python
@client.on(events.MessageDeleted)
def message_deleted_handler(event):
    deleted_id = event.deleted_ids
    ....
```

Is there no way I can know what group that message that intercepted was deleted from?

I can see what channel it was deleted from by accessing `event._chat_peer.channel_id`, is there no equivalent for a group message?

**Comment by Lonami** [comment]
No there is no way to do this, you would have had to save that message in a database or somewhere so you could then delete it (which is what this update is thought for…). Even if you `functions.messages.GetMessagesRequest` it, it will just return `MessageEmpty(id=xyz)` with no further information.
