### ISSUE TITLE
How to reduce the delay on Working with Updates?

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#683]
when use event.NewMessage in group with 10k member 
delay is high for repond and delete event
 
How to reduce the delay on Working with Updates event?
what is better way for big group?

**Comment by Lonami** [comment]
#652.

**Comment by realiza** [comment]
i read issue 652 but i have delay :-(

what is best way for big group?

Another question:
i use get_entity(PeerUser(user_id)) for get information for example First_Name
but for some id_user it work and for some id_user i get error for this code 
i change this code to : 
sender_info = client.get_input_entity(sender_id)
sender_info=client.get_entity(sender_info)
but i get same error for some

**Comment by Lonami** [comment]
If you've already read it and saw there was an open issue why did you open another one?

**Comment by realiza** [comment]
sorry i read it ,after you say  :-)

please help me for another question :

i use get_entity(PeerUser(user_id)) for get information for example First_Name
but for some id_user it work and for some id_user i get error for this code
i change this code to :
sender_info = client.get_input_entity(sender_id)
sender_info=client.get_entity(sender_info)
but i get same error for some
