### ISSUE TITLE
Error with 'found_media'

### ISSUE THREAD

**Issue by olivier-nexmo** [LonamiWebs/Telethon#684]
Sorry, not sure how to check if the problem is with my code or the library.

I'm getting this error: 'TelegramClient' object has no attribute 'found_media', followed (after a while) by Number of retries reached 0.

Any idea why I'm getting this?

I think the post I'm getting to retrieve contains a URL. And it stops from getting other messages from the room.

Thank you

**Comment by Lonami** [comment]
Reopen if you have more information.

**Comment by Lonami** [comment]
Yeah no that appears inside the `InteractiveTelegramClient` **not** the `TelegramClient`.

**Comment by olivier-nexmo** [comment]
Ok. Thank you
