### ISSUE TITLE
You have not setup any workers, so you won't receive updates

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#686]
my code:
client = TelegramClient('session_name', api_id, api_hash, update_workers=2 ,spawn_read_thread=False)

i use updates events

UserWarning: You have not setup any workers, so you won't receive updates. Pass update_workers=1 when creating the TelegramClient, or set client.self.updates.workers = 1
  "You have not setup any workers, so you won't receive updates."

What should I do?

**Comment by GiovanniCardamone** [comment]
maybe try with 3
`
client = TelegramClient('session_name', api_id, api_hash, update_workers=3, spawn_read_thread=False)
`

**Comment by Lonami** [comment]
You should read.

**Comment by tulir** [comment]
Here's the code you need to run (in your brain), stolen from https://github.com/LonamiWebs/Telethon/issues/213#issuecomment-325403179:
```python
while self.hasQuestion():
    try:
        self.parseEnglish(telethon.fetchREADME())
    except NotUnderstoodError:
        try:
            self.parseEnglish(telethon.fetchREADME())
        except NotUnderstoodError:
            try:
                self.parseEnglish(python.fetchDocs())
            except NotUnderstoodError:
                raise KMSError()
```

**Comment by Lonami** [comment]
Nevermind, I'm sorry, I didn't read your issue correctly. So it fails with 2 but works with 1. I'll check this out, thank you.

**Comment by realiza** [comment]
i using 0.18.0.3

**Comment by Lonami** [comment]
Can you post the entire code that causes this? Or a small version that still triggers it.

**Comment by realiza** [comment]
@Lonami 
my code:

api_id = #api id
api_hash = #api hash

client = TelegramClient('session_name', api_id, api_hash, update_workers=2 ,spawn_read_thread=False)
client.start()  # second password password
print(client.get_me())

after login and enter code of telegram show this text: "You have not setup any workers, so you won't receive updates."

@client.on(events.NewMessage(incoming=True))
def my_event_handler(event):
    if event.is_group:{ ... }


@client.on(events.ChatAction)
def join_and_add_to_group(event):
        if event.user_added:{....}

client.idle()

**Comment by realiza** [comment]
Can this problem delay the receipt of the message on work with updates events? 
#652 ?

**Comment by Lonami** [comment]
No, the delay is unrelated.
