### ISSUE TITLE
How to search members in a channel?

### ISSUE THREAD

**Issue by pazis** [LonamiWebs/Telethon#688]
In Telegram official client there is search functionality for group and channel members. It is more useful for channels as only 200 members are shown.

I looked through all methods in https://lonamiwebs.github.io/Telethon/index.html and couldn't find anything resembling such kind of search.

How is it possible to search channel members using Telethon?

Thanks

**Comment by pazis** [comment]
I found the solution! In order to search members I should use ChannelParticipantsSearch filter with GetParticipantsRequest method. like this: (to find baboons)

    response = client.invoke(GetParticipantsRequest(
                    channel=InputChannel(peerID, access_hash),
                    filter=ChannelParticipantsSearch('baboon'), offset=offset, limit=200))

**Comment by speedyworldclub** [comment]
> I found the solution! In order to search members I should use ChannelParticipantsSearch filter with GetParticipantsRequest method. like this: (to find baboons)
> 
> ```
> response = client.invoke(GetParticipantsRequest(
>                 channel=InputChannel(peer_id, access_hash),
>                 filter=ChannelParticipantsSearch('baboon'), offset=0, limit=200))
> ```

Couldnt get ut to work with the latest version of Telethon, please help.

**Comment by fukemy** [comment]
hi, any solution now? Thanks
