### ISSUE TITLE
KeyError while event handling

### ISSUE THREAD

**Issue by ivanklimuk** [LonamiWebs/Telethon#689]
I'm using the event handler wrapper from the [example](https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/extra/basic/working-with-updates.rst).

It behaves really strange in defferent situations:

1) When I run it from a jupyter notebook everything works pretty fine

2) When I run it from pycharm (on Ubuntu) I get a `KeyError` every time I try to print `event.sender.id` for example (actually, any field of `event.sender` rises an exception)

3) When I started it in a docker container it throws the `KeyError` every time I try to access any field of the `event` object

The most interesting is that in all these cases when I print `dir(event)` I get the same result:
`['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_chat', '_chat_peer', '_client', '_get_input_entity', '_input_chat', '_input_sender', '_message_id', '_reply_message', '_sender', '_text', 'chat', 'client', 'delete', 'document', 'edit', 'forward', 'forward_to', 'input_chat', 'input_sender', 'is_channel', 'is_group', 'is_private', 'is_reply', 'media', 'message', 'out', 'pattern_match', 'photo', 'raw_text', 'reply', 'reply_message', 'respond', **'sender'**, 'text']`

But it acts different in all these environments. What could be the problem?

P.S. In all cases I use the same account and different authorized session files.

**Comment by Lonami** [comment]
Thanks, still missing some bits of information. The examples you linked don't access the `.sender`, only mention it, so I'm not sure what your code may be doing wrong. You're also only telling me the type of error, not its message or even traceback. Please provide this information.

**Comment by ivanklimuk** [comment]
1) I see they don't call event.sender, but I did it from my own code in the jupyter notebook. It's something simple like:
`print(event.sender.id)`

2) That's the message I see when the code is being started from pycharm or in a docker:
`KeyError: 129843194
  File "telegram_listener.py", line 66, in my_event_handler
    print(dir(event.sender))
  File "telethon/events/__init__.py", line 403, in sender
    self._sender = self._client.get_entity(self._input_sender)
  File "telethon/telegram_client.py", line 2174, in get_entity
    for x in inputs
  File "telethon/telegram_client.py", line 2174, in <listcomp>
    for x in inputs`

**Comment by Lonami** [comment]
It's strange it works on one place but not the other. What version are you using exactly? Also if you just want the ID, you should access `.input_sender`.

**Comment by ivanklimuk** [comment]
All stuff I use has the latest version. Telethon, docker, etc. Actually, it used to work properly till last week. Any other field, like `.text`, `.raw_text`, etc. raise the same exception

**Comment by ivanklimuk** [comment]
Actually I figured out that the version 0.18.1 works both on ubuntu and windows, still does not work in a docker-ubuntu container
And it's still not clear why the old version (0.17.4) stopped working properly at one moment

**Comment by JackD111** [comment]
I'm running the latest version in an alpine docker (python:3.6.4-alpine3.7) container without issues. Haven't tried running it in ubuntu

**Comment by Lonami** [comment]
Please let me know if this is an issue in the latest `asyncio` version @ivanklimuk. Closing until then.
