### ISSUE TITLE
get_entity for some id_user it work and for some id_user i get error 

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#690]
i use get_entity(PeerUser(user_id)) for get information for example First_Name
but for some id_user it work and for some id_user i get error for this code
i change this code to :
sender_info = client.get_input_entity(sender_id)
sender_info=client.get_entity(sender_info)
but i get same error for some id_user

what is the best way for get First_Name from id_user ?
i can not get First_Name from get_input_entity

**Comment by Lonami** [comment]
`.get_entity` is what you need to do and you're not telling me what fails.

**Comment by realiza** [comment]
Error is  : Make sure you have encountered this peer before.

**Comment by Lonami** [comment]
Well, you need to encounter the peer before because you can fetch it by ID.

**Comment by realiza** [comment]
@Lonami 
I need to identify the bot from the normal user , when member add another
or get First_name of member that send message on group
i use get_entity but get this error

how can i encounter the peer ?

**Comment by Lonami** [comment]
You should know where that peer is.

**Comment by realiza** [comment]
i'm from iran 
i don't speak english very well

when member of my group send message , i write this code:

sender_info = client.get_input_entity(sender_id)
sender_info=client.get_entity(sender_info)

or

get_entity(PeerUser(sender_id))

can you send me example code for soloution this error?

**Comment by Lonami** [comment]
You can `client.get_participants` in a group to "see" its members.

**Comment by realiza** [comment]
@Lonami thanks very much! :+1:
