### ISSUE TITLE
GetMessagesViewsReques doesn't increase my view count 

### ISSUE THREAD

**Issue by keyvanvafaee** [LonamiWebs/Telethon#692]
hi , it is my code 

    #total, messages, senders = client.get_message_history('test_piko') # test_piko is my channel name
    messages = (client.get_message_history('test_piko'))[0]
    print (str(messages))
    entity = client.get_entity('test_piko')
    #print(entity)
    #peer = utils.get_input_user(entity)
    #print(peer)

    client(GetMessagesViewsRequest(
    peer="xcdx", # my username
    id=[1299601672], # i give this id from parsing 'str(messsages))'
    increment=True
    ))
but this not increase my view why?

**Comment by Lonami** [comment]
Why did you open #691 without any information just to later open a new issue?

**Comment by Lonami** [comment]
Only reason why it might not work is because the views have already been increased. You can only do it once or twice per day.

**Comment by keyvanvafaee** [comment]
sorry i am new in github this is my first post

**Comment by keyvanvafaee** [comment]
but the count doesn't changed ! it count is 1

**Comment by Lonami** [comment]
Nothing I can do, that's the request you must use and its usage is correct.

**Comment by keyvanvafaee** [comment]
it's correct that i set my channel id in client.get_entity(' my_channel_id'  ) ?

**Comment by Lonami** [comment]
What?

**Comment by keyvanvafaee** [comment]
in argument of clinet.get_entity('  ') should i write my channel name ? or channel id ? or channel admin id ?
and is this correct that i wrote my Id in peer? 
    client(GetMessagesViewsRequest(
    peer="This is my Id",
    id=[1299601672,8],
    increment=True
    ))

**Comment by Lonami** [comment]
Read in https://github.com/Telethon/ what you need to put.

**Comment by Lonami** [comment]
The documentation also explains what everything is under examples.

**Comment by NabiKAZ** [comment]
### Attention:
Seems that if the `messages.getMessagesViews` are used successive in a large number for a few hours, the viewer will not increase further for current client for any posts, and also don't return any error message, and just return current view of post.
A silent flood !!!
But, after a few hours, everything will return to its original state.

**Comment by Lonami** [comment]
That's indeed mentioned in the documentation 😅

**Comment by NabiKAZ** [comment]
So where is this tip written?
