### ISSUE TITLE
TypeError: object of type 'int' has no len() when forwardmessagesrequest

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#695]
when i use forwardMessagesRequest get this error:
TypeError: object of type 'int' has no len()

**my code:**
long_random=helpers.generate_random_long()
print(long_random)
client.invoke(ForwardMessagesRequest(from_chat,message_id,mychannel,long_random))

**text of error:**

client.invoke(ForwardMessagesRequest(from_chat,message_id,mychannel,long_random))

self.random_id = random_id if random_id is not None else [int.from_bytes(os.urandom(8), 'big', signed=True) for _ in range(len(id))]

TypeError: object of type 'int' has no len()

**Comment by Lonami** [comment]
That's because it wants a list and you're passing just an int. Use `client.forward_messages` instead and please [RTFM](https://telethon.rtfd.io), you're using arcane syntax.

**Comment by realiza** [comment]
thanks :)
