### ISSUE TITLE
SendMediaRequest error

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#699]
my code:
message=update_data['message']
message_text = message['message']
media = update_data['message']['media']
mychannel= client.get_input_entity(PeerChannel(id))
client.invoke(SendMediaRequest(mychannel,InputMediaPhoto(media),message_text))

get this error on SendMediaRequest:
'str' object cannot be interpreted as an integer

**Comment by Lonami** [comment]
You probably passed a string where an integer is required.

**Comment by Lonami** [comment]
Why are you using this arcane syntax? Where are you getting this code from? There are much better ways to do this.

**Comment by realiza** [comment]
Sorry , what is input of InputMediaPhoto()? 
InputMediaPhoto(media['photo']['id']) not work

please send example of SendMediaRequest for photo :-(

**Comment by Lonami** [comment]
I'm not rewriting the docs here for you again. I spent a considerable amount of time writing them and you should spend that time reading instead asking.

**Comment by realiza** [comment]
Sorry @Lonami 

My code was wrong! I need to be more careful!

SendMediaRequest  work very  good :+1:
