### ISSUE TITLE
Issues running Telethon for the first time

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#7]
If it's the first time running Telethon, these are some issues that some people (including me) have had:
- An exception happens after handling the `InvalidDcError`, "data is trying to be read outside the bounds".
- After a "corrupted `.session`" is created, the same packet is always received: `b'l\xfe\xff\xff'`.

Both however are solved by deleting the `.session` file. I don't know what could be causing this. Is `b'l\xfe\xff\xff'` some Telegram code? What does it mean:
- `b'l\xfe\xff\xff'` (little endian) 4294966892 or 0xfffffe6c
- `b'l\xfe\xff\xff'` (big endian) 1828651007 or 0x6cfeffff

**Comment by cher-nov** [comment]
@Lonami, `0x6CFEFFFF` is also a `-404` if treated as signed little-endian.
Same is for `0xFFFFFE6C` if treated as signed big-endian.
As you know, 404 is HTTP error code.

Maybe this will help.

**Comment by Lonami** [comment]
Thanks for giving some more insight into what it could be, but a 404 error is as strange. When an `InvalidDCError` is thrown, and handled in a "strange" way to reconnect to corrupt the session, all it does is set the IP address and port *told* by the error (this is, to what address we should connect). The only other places in which the session file is modified, is on sign in/sign up. So I have no clue on how the session even gets corrupt!

Perhaps it would be good to dump the session file in a readable way before and after the error happens, and see its differences. But… it's not a bug easy to reproduce.

**Comment by Lonami** [comment]
So the only difference I could find between the corrupt one an the non-corrupt one is that `user=None` in the corrupt one. Maybe that's why it shows a "404", because the user is not found. But it [is](https://github.com/LonamiWebs/Telethon/blob/master/telethon/interactive_telegram_client.py#L47) still [strange](https://github.com/LonamiWebs/Telethon/blob/fbc7aabf1396abfb2fca4092063b2c3a9c14e501/telethon/telegram_client.py#L188-L191) because that's exactly what I check…

Also, I noticed, `.send()` is done, `.receive()` fails.

**Comment by Lonami** [comment]
Update: connecting for the first time now works a lot better thanks to [`bbd3eb7`](https://github.com/LonamiWebs/Telethon/commit/bbd3eb7c28d9c21e0d486ab9983335cb72d44124) by @cher-nov and [`6550d83`](https://github.com/LonamiWebs/Telethon/commit/6550d83d429487ec8f2899659eb1a76a5121ef03). Though I haven't yet tested the "-404" error.

**Comment by Lonami** [comment]
Quoting #65:

> Once downloading media from a different DC works, the b'l\xfe\xff\xff' packet won't be received anymore (it's caused by a corrupt authorization). Closing this issue to clean up the issues section.
