### ISSUE TITLE
why i get this

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#70]
Traceback (most recent call last):
  File "try_telethon.py", line 30, in <module>
    api_hash=settings['api_hash'])
  File "/home/telethon/Telethon/telethon/interactive_telegram_client.py", line 33, in __init__
    print_title('Initialization')
  File "/home/telethon/Telethon/telethon/interactive_telegram_client.py", line 15, in print_title
    print('\u250c{}\u2510'.format('\u2500' * available_cols))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-79: ordinal not in range(128)

**Comment by seby2000** [comment]
When i comment this lines `    #print(' ^ ^ {} ^ ^ '.format(' ^ ^ ' * available_cols))
    #print(' ^ ^ {} ^ ^ '.format(title.center(available_cols)))
    #print(' ^ ^ {} ^ ^ '.format(' ^ ^ ' * available_cols))
`  it dont crash but next i get al loop of this `1. Telegram


1. Telegram


1. Telegram


1. Telegram


1. Telegram


1. Telegram


1. Telegram
`

**Comment by Lonami** [comment]
On what platform are you (Windows/Linux based/…)?

**Comment by seby2000** [comment]
linux ubuntu 16.04

**Comment by seby2000** [comment]
NOTE that if install it from pip all will work correctly

**Comment by Lonami** [comment]
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-79: ordinal not in range(128)

That's… really strange. I just tested on both Python **3** *and* Python 2, and it both worked (though, on Python 2, it didn't show the characters correctly). Maybe your terminal doesn't support these characters? For some strange reason (because I used to have xUbuntu 16.04, and it was working).

> When i comment this lines

Also I don't know how commenting a few `print()`'s turns it into an infinite loop.

> i installed it from git

I assume that you followed the `README.rst` and generated the TLObjects and all.

> i need to restart the script another time for the code request.

[I'm aware](https://github.com/LonamiWebs/Telethon/issues/7).

**Comment by chiva** [comment]
I've just tested the same script and same result:

```
~/python/Telethon$ python3 try_telethon.py

Traceback (most recent call last):
  File "try_telethon.py", line 30, in <module>
    api_hash=settings['api_hash'])
  File "/home/joshua/python/Telethon/telethon/interactive_telegram_client.py", line 34, in __init__
    print_title('Initialization')
  File "/home/joshua/python/Telethon/telethon/interactive_telegram_client.py", line 16, in print_title
    print('\u250c{}\u2510'.format('\u2500' * available_cols))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-148: ordinal not in range(128)
Exception ignored in: <bound method TelegramClient.__del__ of <telethon.interactive_telegram_client.InteractiveTelegramClient object at 0x7f21d7dd1860>>
Traceback (most recent call last):
  File "/home/joshua/python/Telethon/telethon/telegram_client.py", line 87, in __del__
    self.disconnect()
  File "/home/joshua/python/Telethon/telethon/telegram_client.py", line 153, in disconnect
    if self.sender:
AttributeError: 'InteractiveTelegramClient' object has no attribute 'sender'
```

Also seeems to have another exception when destroying the `TelegramClient` class. Probably something to do with the last commits.

**Comment by Lonami** [comment]
> ```
>  File "/home/joshua/python/Telethon/telethon/telegram_client.py", line 87, in __del__
>```

I blame @cher-nov! ;) I should have tested his commits.

**Comment by Lonami** [comment]
Could you please test the changes @chiva? Or @seby2000, since this error doesn't happen to me.

**Comment by chiva** [comment]
First run, as expected and as you stated in issue #7, it failed to login

```==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
First run. Sending code request...
[13:13:26.762/MainThread] WARNING: Read RPC error: (RPCError(...), 'The phone number a user is trying to use for authorization is associated with a different data center (#4).')
```

Second run sent and asked correctly the login code, but as @seby2000 said, it started an infinite loop listing the 3 first dialogs
```==================
= Dialogs window =
==================
1. Dialog 1
2. Dialog 2
3. Dialog 3


==================
= Dialogs window =
==================
1. Dialog 1
2. Dialog 2
3. Dialog 3


==================
= Dialogs window =
==================
1. Dialog 1
2. Dialog 2
3. Dialog 3


==================
= Dialogs window =
==================
1. Dialog 1
2. Dialog 2
3. Dialog 3
```

Dialog 1, 2 and 3 where correctly displayed with its real names

**Comment by Lonami** [comment]
Does any of your dialogs also contain strange character on their names? Perhaps it causes a `ValueError`, which is considered to be from a wrong `input()` (never reached), and so it loops over and over again.

**Comment by chiva** [comment]
It seems I have reached a login rate limitation as it is stuck on _Connecting to Telegram servers..._
(If it is true, could this be logged so we can be aware of this? And know the remaining time)

Anyways, they did have some strange characters indeed.

**Comment by Lonami** [comment]
> It seems I have reached a login rate limitation as it is stuck on Connecting to Telegram servers

Try in a few minutes, this is not the same as the flood error, I would say.

**Comment by cher-nov** [comment]
> I blame @cher-nov! ;) I should have tested his commits.

but it's not my fault

![](http://cs8.pikabu.ru/images/previews_comm/2016-11_3/1478987370118544741.jpg)

**Comment by seby2000** [comment]
@Lonami now it work almost correctly but i have to run try_telethon.py 3 times for get the dialogs. 
First run i receive this without any response from telegram server.
```==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
```
second run i receive this 
```
==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
First run. Sending code request...
[08:10:54.077/MainThread] WARNING: Read RPC error: (RPCError(...), 'The phone number a user is trying to use for authorization is associated with a different data center (#4).')
```
only in the third run it work correctly 
```==================
= Initialization =
==================
Initializing interactive example...
Connecting to Telegram servers...
First run. Sending code request...
Enter the code you just received: ```

**Comment by Lonami** [comment]
> but i have to run try_telethon.py 3 times for get the dialogs

That's a different issue though. If it doesn't crash, we can consider this one to be resolved.
