### ISSUE TITLE
 INVALID_CHAT_ID for InviteToChannelRequest 

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#704]
when i used InviteToChannelRequest and got an INVALID_CHAT_ID.
my code:

from telethon.tl.functions.channels import InviteToChannelRequest
from telethon.helpers import get_input_peer

client.invoke(InviteToChannelRequest(
    get_input_peer(channel),
    [get_input_peer(user)]
))
What should I do?

**Comment by Lonami** [comment]
I'll ask again. Where are you taking this arcane syntax from…? `.invoke()` (while available) shouldn't be used anymore. `.get_input_peer()` is unnecessary. `channel` might not be a `Channel` so it fails.

**Comment by realiza** [comment]
:) sorry but
you writed this code in #103, i just copied its in old version

i change this code to : 
channel_entity = client.get_input_entity(PeerChannel(channel_id)) # my channel id
user_entity = client.get_input_entity(username)  # for example @realiza without @
client(InviteToChannelRequest(channel_entity,list_user_entity))

the channel_id and username of user is true 
but i get this error:
INVALID_CHAT_ID

**Comment by realiza** [comment]
get username with GetParticipantsRequest from group and save to file then add username with InviteToChannelRequest (with one session ) (this work)
different with
read username from file ( Already written , without GetParticipantsRequest from group) then add username with InviteToChannelRequest (with two session , session one get username then save and session two add username)
when session two use InviteToChannelRequest get this error : INVALID_CHAT_ID
