### ISSUE TITLE
`events.ChatAction` doesn't works with pinned messages as should be.

### ISSUE THREAD

**Issue by JrooTJunior** [LonamiWebs/Telethon#706]
Handling of pinned messages is documented but doesn't works.
This trouble is desribed in the chat:

1. https://t.me/TelethonChat/25317
2. https://t.me/TelethonChat/25318
3. https://t.me/TelethonChat/25322

**Comment by JrooTJunior** [comment]
I think need to add:
```python
elif isinstance(action, types.MessageActionPinMessage):
    event = ChatAction.Event(msg, users=msg.from_id, new_pin=msg.reply_to_msg_id)
```
in this block: https://github.com/LonamiWebs/Telethon/blob/7825994393aab11101f85bc37904eee266d2991e/telethon/events/__init__.py#L632-L665

**Comment by Lonami** [comment]
The thing is I think I tested this and came up with this result:
https://github.com/LonamiWebs/Telethon/blob/d379b2633909860e965eaa8d02eaa154f7a2cd8a/telethon/events/__init__.py#L611-L615

**Comment by Lonami** [comment]
Indeed I tried pinning some message and got:
```
UpdateChannelPinnedMessage(channel_id=1135354474, id=29846)
UpdateReadChannelInbox(channel_id=1135354474, max_id=29847)
UpdateNewChannelMessage(message=MessageService(out=True, mentioned=False, media_unread=False, silent=True, post=False, id=29847, from_id=10885151, to_id=PeerChannel(channel_id=1135354474), reply_to_msg_id=29846, date=datetime.utcfromtimestamp(1521386376), action=MessageActionPinMessage()), pts=50596, pts_count=1)
```

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/pull/715
