### ISSUE TITLE
Multiple clients with same credentials

### ISSUE THREAD

**Issue by Senpos** [LonamiWebs/Telethon#707]
Hello.

First of all, **thanks** for such a nice library.

I have a **question** about creating multiple instances of `client` with the **same** credentials.

### The story
Let's say, i have a `main.py`, i do all the required stuff to make it work and then start `idle`.

But one day, i wanted to send a message asynchronously using `Celery`. Since i **can't** pass `client` as an argument to the task, i have to **create** a **new** **instance** of `client` and send a message. And it **worked**! Message from the _Celery task_ was successfully sent. **But...** 

Remember `main.py` and its client that is in `idle` "mode"? It **does not see** any new updates. It is still `is_connected==True` and `is_user_authorized==True`, even more, it is still trying hard to work: 
```
DEBUG:telethon.telegram_bare_client:Receiving items from the network timed out
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
DEBUG:telethon.extensions.tcp_client:socket.timeout "timed out" while reading data
DEBUG:telethon.telegram_bare_client:Receiving items from the network timed out
...
and so on
```

### Trying to fight
I was investigating this problem for awhile. 

**What i have tried**:
- to set `update_workers` to `1` in the`main.py`, in the `task` and in both
- to play with `spawn_read_thread`
- to manually disconnect client inside the `task` after the job was done

Nothing of listed above helped. :( 

### THE WIN!
But apparently, i have found something interesting in the _docs_ - `.sync_updates()`. Well, i decided to run this every time task was done. But how should i do this? `idle` locked my `main.py`, so i had to get rid of it. So, i wrote my own simple
```python
while True:
    sleep(1)
    client.sync_updates()
```

And it **worked**!

It seems like, when i called `connect` in another `client` "entity", it acquired update handling, so my `main.py` `client` couldn't  receive anything.

### Questions
 - Is this a proper way of handling this kind of problem or you can suggest me anything else?
 - Is `.sync_updates()` cheap or expensive? I am a little worried how calling this every 1 second will effect performance? 
- If it is a good way of handling such problems and it is not expensive, is it possible to add this thing to `idle`? :-)

Regards,
@Senpos

**Comment by Lonami** [comment]
`.idle()` is blocking. If you don't set `spawn_read_thread=False`, it will be `True` by default. That thread will call `.idle()` for you so you can do different things in your main thread. `.sync_updates()` is I guess not expensive but you don't need to call it either. Sleeping alone should be enough.

So you can have:
```python
client = TelegramClient(name, api_id, api_hash).start()
# spawn_read_thread is True by default, you can add event handlers

@client.on(events.NewMessage)
def _(e):
    pass

# You can use the client as you like here
...

# When you're done
client.disconnect()
```

**Comment by Lonami** [comment]
The issue is nicely formatted and explained but there's a lot of information so let me go through it again…

**Comment by Lonami** [comment]
Okay so you can create as many `TelegramClient`'s as you want but they should have a different session `name`. If you call `.idle()` that will block so it won't do anything else. That was addressed already on my previous comment and I think you didn't have more problems?

**Comment by Senpos** [comment]
> you can create as many TelegramClient's as you want but they should have a different session name
That's probably what i need.

But anyway, i will show example what i did, what went wrong and how i fixed it.

**main.py**
```python
def update_handler(update):
    doing_cool_things = True

client = TelegramClient(
        session=settings.TELEGRAM_MOBILE_NUMBER,
        api_id=settings.TELEGRAM_API_ID,
        api_hash=settings.TELEGRAM_API_HASH,
        proxy=None,
        update_workers=4
    )

if SOME_STUFF_HAPPENED == True:
    my_task.delay()

client.add_update_handler(update_handler)

client.idle()
# or 
# client.start()
# while True:
#     sleep(1)
```

**tasks.py**
```python
@task
def my_task():
    client = TelegramClient(
        settings.TELEGRAM_MOBILE_NUMBER,
        api_id=settings.TELEGRAM_API_ID,
        api_hash=settings.TELEGRAM_API_HASH,
        proxy=None,
        update_workers=1
    )
   
    client.start()

    client.send_message(1234, 'You totally want to read this message!')

    client.disconnect()
```

**Before** the task started - client from `main.py` could read messages.
**After** the task done - client from `main.py` no longer can read messages.

To fix this, i have to put `client.sync_updates()` inside the `main.py` loop:
```python
while True:
    sleep(1)
    client.sync_updates()
```

And after that, client from `main.py` **can** read updates again.

That was fun time playing with this. :)

I will try to create a client with difference `session` and report how it's going here. 

Thanks for help!

**Comment by Senpos** [comment]
> you can create as many TelegramClient's as you want but they should have a different session name

I tried this out.

Unfortunately, it does not fit my needs. :(

The first problem is **authorization**, which i have to do on a new session, but it is not easy, because i do not have access to **stdin** using **Celery**. Task runs in the another independent process. 

The second problem is that the **first** session **catches** **updates** from the **second** session. :smile_cat: 

So i have to stick with my kind of _hacky_ solution, using `sync_updates`, so i can re-use the same session in different places.

**Comment by Lonami** [comment]
I really don't think you need to call `client.sync_updates()` though. Just sleep. But that's the same thing as `.idle()` does. Maybe see http://telethon.readthedocs.io/en/latest/extra/advanced-usage/update-modes.html.

**Comment by Senpos** [comment]
@Lonami I actually do. If you are interested in real app example, i can record a short video tomorrow.

**Comment by Lonami** [comment]
No it's alright.

**Comment by kuchaow** [comment]
I think sync_updates was deprecated or something, visual studio code doesn't identify it as a Telegram Client function and I have the same problem now on 2022 ;(

**Comment by li894882182** [comment]
> I think sync_updates was deprecated or something, visual studio code doesn't identify it as a Telegram Client function and I have the same problem now on 2022 ;(

I have same question , and this method "sync_updates" is not exists already , maybe its because version upgrade . so do you resolved this problem?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
