### ISSUE TITLE
Telethon - Detect admins in a channel among users

### ISSUE THREAD

**Issue by AbouMehdi** [LonamiWebs/Telethon#708]

**Comment by AbouMehdi** [comment]
@Lonami I updated my description, sorry

**Comment by Lonami** [comment]
`client.get_participants` returns `User` with an extra `.participant` field that tells you what you need.

**Comment by AbouMehdi** [comment]
Thanks @Lonami, I do have a list of Users using `client.get_participants('telegram.me/'XXX')` , but no extra .participant on Users. Did I miss something ? 

I've tried too :  `client.get_participants(InputPeerChannel(id, access_hash))` same results.

Thanks for your help

**Comment by Lonami** [comment]
1. Make sure you're using some recent version.
2. It won't show if you `print()` it but it should be there.

**Comment by AbouMehdi** [comment]
@Lonami Awesome, thank you, I did it !

**For those who are beginneers in Python (like me) 👍  Here the solution**  I hope it will help.
- `Pip install freeze` -> `pip freeze ` :  Check if Telethon is the latest : http://telethon.readthedocs.io/en/latest/extra/changelog.html
- If not, Pip install telethon --upgrade 
- Once you have the latest version, you won't see the extra .participant if you don't call it.
Add your .participant on each User Object, you need !

Cheers
