### ISSUE TITLE
Kick users from Channel(megagroup)

### ISSUE THREAD

**Issue by dharmagetic** [LonamiWebs/Telethon#709]
Hi!
I've faced with issue - I can't find any relevance method to kick/delete user from Channel(megagroup) I tried to search on https://lonamiwebs.github.io/Telethon/methods/channels/index.html but I have no found anything relevance. Can you please guide me ?

**Comment by Lonami** [comment]
Telegram doesn't have a method to "kick". Instead you need to "ban" the users to kick them. Then you can unban them if you wish.

**Comment by shikhov** [comment]
There is channels.kickFromChannel

**Comment by Lonami** [comment]
No, that doesn't exist.
