### ISSUE TITLE
TelegramClient.getDialogs() - 'count' argument

### ISSUE THREAD

**Issue by cher-nov** [LonamiWebs/Telethon#71]
Current name is confusing, because we can pass 0 in this parameter to return all of the dialogs.
Even in the Telegram API itself it's named as `limit`.

**Comment by Lonami** [comment]
> Current name is confusing, because we can pass 0 in this parameter to return all of the dialogs.

I wasn't aware of such feature. Would you like to make a pull request?

**Comment by cher-nov** [comment]
@Lonami, done: #72.

**Comment by cher-nov** [comment]
Closed with ff469ac.
