### ISSUE TITLE
Strange work of send.message(parse_mode)

### ISSUE THREAD

**Issue by ted24** [LonamiWebs/Telethon#712]
Hi!

I try to send message as 
`client.send_message(entity=ch, message=txt, reply_to=None, parse_mode="html", link_preview=False, file=message.media, force_document=False)`
It works fine if message.media is empty, links in the txt parse well, but if message.media is not empty, links stop parsing (just notclickable text appears). The same situation is with Markdown. Parsing does not work if this message received on telegram iOS client,  if message received on desktop client it parsed well with enabled links.

**Comment by Lonami** [comment]
Mind explaining why you closed this? Although I hadn't time to read this throughly my first impression was that official clients just haven't been updated yet and don't support markdown in the captions.
