### ISSUE TITLE
"send_file(force_document=True)" doesn't work

### ISSUE THREAD

**Issue by Senpos** [LonamiWebs/Telethon#713]
Hello!

I am using `client.send_file(...)` to send **images**.

One day, i realized, that i need to send them as files, because there might me some text data which is important to be read clearly, so i don't need Telegram's compression.

I found `force_document` argument for `send_file` in documentation, which says:

> If left to `False` and the file is a path that **ends** with
                the **extension** of an **image** file or a video file, it will be
                sent as such. **Otherwise** always as a **document**.

**My code**
```python
client.send_file(
    user.chat_id,
    force_document=True, # <- i want my images to be sent as files!
    file=some_list_of_paths,
    caption='My cool caption'
)
```
I **expect** images  to be sent as **documents**, **not** as **images** as it is right now.

To be more clear, here what `some_list_of_paths` is:
```
[
    '/home/myuser/Projects/myapp_project/myapp/media/uploads/2018/03/16/ff9bdc10-d36b-44c9-84d4-be9dd2baee26.jpg', 
    '/home/myuser/Projects/myapp_project/myapp/media/uploads/2018/03/20/66b500c9-adaa-47d9-91fb-8e1264aff66a.jpg'
]
```
### Environment
**OS**: `Ubuntu 16.04`
**Interpreter**: `Python 3.6.3`
**Lib**: `Telethon==0.18.1`

If you need more details on what am i doing - feel free to ask.

**Comment by Senpos** [comment]
### Note 1
I tried to send files as literally **file objects**. In this case - they are sent as documents even without `force_document` option.

**Comment by Lonami** [comment]
Strange, I just sent a `.png` with `force_document=True` and it indeed was sent as a document.

**Comment by Lonami** [comment]
Same with `.jpg`. Having or not a caption seems to make no difference. Also yes if you pass a file object it won't determine it's an image and will always sent as a document.

**Comment by Lonami** [comment]
Ah I see you're sending a list, that always get sent as an album and the parameter is ignored. I'll look into that, for now call `.send_file()` with only one path repeatedly.

**Comment by Senpos** [comment]
@Lonami 
Cool, thanks for answer.
