### ISSUE TITLE
asyncio AttributeError: 'UpdateNewChannelMessage' object has no attribute 'entities'

### ISSUE THREAD

**Issue by elmcrest** [LonamiWebs/Telethon#714]
__this maybe only affects the `asyncio` branch.__

I get this error while the bot runs in the background, didn't check it yet but this is the place to keep it, so I can refer to this later or someone else might, too.

full Exception:

```
Task exception was never retrieved
future: <Task finished coro=<TelegramClient._on_handler() done, defined at /usr/local/lib/python3.6/site-packages/telethon/telegram_client.py:2191> exception=AttributeError("'UpdateNewChannelMessage' object has no attribute 'entities'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telethon/telegram_client.py", line 2193, in _on_handler
    event = builder.build(update)
  File "/usr/local/lib/python3.6/site-packages/telethon/events/__init__.py", line 286, in build
    event._entities = update.entities
AttributeError: 'UpdateNewChannelMessage' object has no attribute 'entities'
```

how I use it:
```Python
async def process_new_message(message):
    if 'ping' in message.raw_text.lower():
        await message.reply("pong!")

async def main():
    await client.start()
    await client.add_event_handler(process_new_message, events.NewMessage)

loop.create_task(main())
loop.run_forever()
```

**Comment by Lonami** [comment]
Likely missed to merge https://github.com/LonamiWebs/Telethon/commit/7e9d19d727663336534d5d1e1ffe71ecf2a66bf9 or similar.

**Comment by elmcrest** [comment]
so, rebase master to `asyncio` branch would be the right thing to do?

**Comment by elmcrest** [comment]
... trying now ;)

**Comment by Lonami** [comment]
Rebase is not going to work. You need to merge.

**Comment by elmcrest** [comment]
Ok trying again later

**Comment by Lonami** [comment]
You don't have to, in theory I already merged. Not sure why the change isn't there. I'll check myself when I have time.

**Comment by Lonami** [comment]
Not sure what version you were using but the entities were already there after this recent merge https://github.com/LonamiWebs/Telethon/compare/d4e1f13e4177...8b0580901a07#diff-a1ad268b4dc8daf64b9443221885f69bR78.
