### ISSUE TITLE
Better test coverage

### ISSUE THREAD

**Issue by elmcrest** [LonamiWebs/Telethon#716]
Any reasons the test files are named as they are?

If I rename them to standards like `test_filename.py` Test runners can find the tests. 

I‘m currently working on fixing the broken tests, we‘ll see if I can make them work again.

**Comment by Lonami** [comment]
Not sure if any test passes at all, they were only useful in the beginning of the library. Otherwise it's heavily untested.

**Comment by elmcrest** [comment]
ok I will try to improve test coverage

it's huuugely important if you ask me :)

**Comment by Lonami** [comment]
#385 is probably relevant.

**Comment by elmcrest** [comment]
maybe it would help if you add some starting help here, like what modules should be tests first or what makes sense to test and what not...
f.e. I was thinking it's not easy to get integration tests since this involves telegram

maybe a test bot would be nice to have? :) 
so some bot running on a different instance which just replies to tests in an expected manner?

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/blob/master/telethon_tests/higher_level_test.py shows how to login to the tests servers (read the docs [is somewhat more updated](http://telethon.readthedocs.io/en/latest/extra/developing/test-servers.html) for that too). I guess testing that the friendly methods work would be a nice thing to have.

I'm not sure what needs testing and what doesn't, really. I'm not very experienced with tests as you can probably tell. The most active part is often the `TelegramClient` and I don't know how we would test that the responses are okay from the server since that's a somewhat big process that just happens. No clue sorry.

**Comment by elmcrest** [comment]
I'd consider https://github.com/LonamiWebs/Telethon/pull/717 as a start

**Comment by Lonami** [comment]
Here's a few from easier to harder (in my opinion), and where to look, if anyone is interested:
* [Markdown parsing (and unparsing) methods][1].
* [HTML parsing (and unparsing) methods][2].
* [Connection modes][3] (against the [test servers][4]).
* [Generation of the authorization key][5].
* [`.tl` file parsing][6].
* [Code generation][7].
* [Serialization and deserialization of objects][7].

[1]: https://github.com/LonamiWebs/Telethon/blob/master/telethon/extensions/markdown.py
[2]: https://github.com/LonamiWebs/Telethon/blob/master/telethon/extensions/html.py
[3]: https://github.com/LonamiWebs/Telethon/tree/master/telethon/network/connection
[4]: https://telethon.readthedocs.io/en/latest/extra/developing/test-servers.html
[5]: https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/authenticator.py
[6]: https://github.com/LonamiWebs/Telethon/tree/master/telethon_generator/parsers
[7]: https://github.com/LonamiWebs/Telethon/tree/master/telethon_generator/generators

**Comment by Lonami** [comment]
Idea for easily testing the high-level interface: as opposed to using the test servers, we should mock Telegram responses (perhaps this was obvious to others, but not me). Maybe a `TelegramClient` subclass which, at creation time, lets us specify what responses we expect to arrive (and their order). Such as `MockedClient([expected_response]); assert mocked(request) == expected`.

**Comment by Lonami** [comment]
Not gonna happen (at least not any time soon by me), so closing.
