### ISSUE TITLE
Eventhandler on events.NewMessage returns MessageEdited.Event

### ISSUE THREAD

**Issue by elmcrest** [LonamiWebs/Telethon#718]
```
>>>type(event)
<class 'telethon.events.NewMessage.Event'>
>>>print(event)
MessageEdited.Event(pattern_match=None, is_private=False, is_group=True, is_channel=False, message=Message(out=True, mentioned=False, media_unread=False, silent=False, post=None, id=123, from_id=124, to_id=PeerChat(chat_id=125), fwd_from=None, via_bot_id=None, reply_to_msg_id=None, date=datetime.utcfromtimestamp(126), message='alla hopp', media=None, reply_markup=None, entities=[], views=None, edit_date=None, post_author=None, grouped_id=None), is_reply=False)
```

is this expected behaviour?

(*cough* this library really needs some tests)

**Comment by Lonami** [comment]
Did you try https://github.com/LonamiWebs/Telethon/commit/3550974b71087c3e66e8166b4ed623d2c160379c?

**Comment by elmcrest** [comment]
ok, if I manually change this, it looks better to me :) 

```
>>>type(event)
<class 'telethon.events.NewMessage.Event'>
>>>print(event)
NewMessage.Event(pattern_match=None, is_private=False, is_group=True, is_channel=False, message=Message(out=True, mentioned=False, m....
```

need to check now how to merge this into the `asyncio` branch

did I mention the tests situation? what's holding you back from setting up travis?

I could as well but I don't have the privileges to the repo, so you have to do it...

**Comment by Lonami** [comment]
I haven't updated the `asyncio` branch. I work on `master` and eventually merge to `asyncio`. There's nothing holding me back from using Travis, I simply haven't gotten around this and the lack of tests don't bother me much (I know people like you think differently).
