### ISSUE TITLE
Send video with stream

### ISSUE THREAD

**Issue by JackCloudman** [LonamiWebs/Telethon#721]
I send a video by:
`from telethon.tl.types import DocumentAttributeVideo
client.send_file("username",path,allow_cache=False,attributes=(DocumentAttributeVideo(1457, 848, 480),))`
But file dont uploaded with stream option o.o <3

**Comment by Lonami** [comment]
> But file dont uploaded with stream option

What?

**Comment by JackCloudman** [comment]
When i send a video, it isn't available to see in stream mode o.o

**Comment by Lonami** [comment]
I think this is done client-side. It might depend on the file type.

**Comment by Lonami** [comment]
Actually it was Telegram being silly (see #731). Pass your own `DocumentAttributeVideo` to the `attributes` of `.send_file` with `supports_streaming=True`.

**Comment by JackCloudman** [comment]
Thanks <3

**Comment by aminhyper** [comment]
Hello
It is my problem too,
`
from telethon.tl.types import DocumentAttributeVideo 
client.send_file('username','path',allow_cache=False,supports_streaming=True,attributes=(DocumentAttributeVideo(1727,1280,720),))`

When I upload the file, it will not be streamed. The file is `mp4`

**Comment by Mr3rf1** [comment]
actually i have this problem too, supports_streaming=True didn't work

![image](https://github.com/LonamiWebs/Telethon/assets/69768793/3431cd05-ee1e-4f21-bd7f-ed5ef9f71b32)

the video can't be streamed yet.

**Comment by hackerstech** [comment]
Set thumbanil idiot

**Comment by randomuser9912** [comment]
supports_streaming=True didn't work
Add thumbnail but not work

**Comment by Lonami** [comment]
Use an official client to send media the way you want. Then fetch the message with Telethon to learn what must be done to correctly have the media.

Telegram can change the requirements for this at any time. Old solutions may not work. The above is the only way to reliably find out how to do so in the latest version.

**Comment by AshenIndeewara** [comment]
this works 

`await client.send_file(chat_id, file=output_video_file, thumb="thumb/123.jpg", caption=movie_file_name1, attributes=(DocumentAttributeVideo(duration, 1280, 720, supports_streaming=True),))` ❤️
