### ISSUE TITLE
get id from supergorups that i joined it

### ISSUE THREAD

**Issue by realiza** [LonamiWebs/Telethon#723]
how to get list of supergroup's id that i joined it?

**Comment by Lonami** [comment]
Some questions really just belong to StackOverflow or any other QA site. **This is not a problem with the library.**

**Comment by m3r3lin** [comment]
sorry sir but I don't find any solution for this problem in stackoverflow
I join in 30 supergroups 
Now i need to get list of group's id for send message

**Comment by m3r3lin** [comment]
i ask this question in stackoverflow in this link :

https://stackoverflow.com/questions/49464235/telethon-gets-id-from-supergorups-that-i-joined-it

**Comment by m3r3lin** [comment]
please answer me or please give me title for search in stackoverflow
