### ISSUE TITLE
`else` without obvious `if` in tl_generator.py#L216

### ISSUE THREAD

**Issue by elmcrest** [LonamiWebs/Telethon#724]
https://github.com/LonamiWebs/Telethon/blob/1c9dc8dc63f59a6e7b385e5c9ebbd54eb67be73c/telethon_generator/tl_generator.py#L216

hey again,

I don't really get why there is an else case without any `if` before - only a, I think "closed" `if not` in L145

Besides this, is there some documentation or other issue that discusses, why do you generate all the types in first place?
does the telegram api change this often or what's the reason behind?

thx, 
elmcrest

**Comment by Lonami** [comment]
That `else` is probably a leftover from some other code which I forgot to remove. It does indeed do nothing.

> why do you generate all the types in first place?

It's possible to parse the `scheme.tl` on runtime. You could just use dictionaries. But I like being able to generate classes so type hinting works and there's no need to ship the generator/tl definition this way.

> does the telegram api change this often or what's the reason behind?

Well, every time they add a new layer.

**Comment by Lonami** [comment]
I think that was there so that if the `for` was empty, it would write `pass`. But that's not how the `else` in `for`'s must be used. Ping #678 (@tulir) for https://github.com/LonamiWebs/Telethon/commit/935de0afbb480b366d650f59217507824b5b2cd4#diff-6582cad19615e60699c8cd8891c1aadbR216.

**Comment by tulir** [comment]
Oh, I assumed it's ran if the array is empty, but apparently it's ran if the loop isn't broken. The `else` can just be removed (or replaced with `if not imports` if you want to be fancy)
