### ISSUE TITLE
Cannot cast CdnFileHash to any kind of InputPeer

### ISSUE THREAD

**Issue by mamdosein97** [LonamiWebs/Telethon#727]
sometimes after a while of running script occurs an exception with TypeError: "Cannot cast CdnFileHash to any kind of InputPeer."
I want to know what is the problem and why this exception is occured?
and if i want to handle it, is it of type of **telethon.errors.common.CdnFileTamperedError**? if answer is no what kind of error it is?

**Comment by Lonami** [comment]
>  I want to know what is the problem and why this exception is occured?

I want to know more information the issue. I haven't seen what code may be triggering it and you've only provided a line, not a traceback. So not too helpful.

No, it's not of type `telethon.errors.common.CdnFileTamperedError`.

**Comment by mamdosein97** [comment]
this is an image of the logger of script:

![logger](https://user-images.githubusercontent.com/18369388/37959028-4ba18c80-31c7-11e8-828a-64aebcfd67f8.jpg)

 
I think maybe this is because of some kind of images (or any kind of files) that are on CDNs (and maybe because of my country Iran)

**Comment by Lonami** [comment]
I'm closing this since I think https://github.com/LonamiWebs/Telethon/commit/898e550335b9979a131dd956c8aa26a01d341b4c fixed it. I will push a new version later (currently `v0.18.1`).

**Comment by Lonami** [comment]
You can upgrade to `v0.18.2` now.
