### ISSUE TITLE
Anyway to read a Reply message as well as the updated reply to the message? 

### ISSUE THREAD

**Issue by danveersaini** [LonamiWebs/Telethon#728]
client = TelegramClient('', api_id, api_hash)
client.start()
messages = client.get_message_history('', limit=1)
for msg in reversed(messages):
	content = msg.message
	print(content)

Anyway to print the reply to the message as well as the current message at once?

**Comment by Lonami** [comment]
http://telethon.readthedocs.io/en/latest/telethon.html#telethon.telegram_client.TelegramClient.send_read_acknowledge
