### ISSUE TITLE
Call .disconnect() in the destructor of TelegramClient

### ISSUE THREAD

**Issue by cher-nov** [LonamiWebs/Telethon#73]
Consider next code:

```python
import telethon

# NOTE: DON'T SHARE THESE VALUES!
TGAPP_API_ID =  #some id
TGAPP_API_HASH =  #some hash

tg_client = telethon.TelegramClient("test", TGAPP_API_ID, TGAPP_API_HASH)
tg_client.connect()

raise ValueError("let's die lol")
```

Currently everything hangs if an exception happens, because TelegramClient uses threads.
But if we add `tg_client.disconnect()` before `raise` in the example above, everything will work nicely.

I can propose a corresponding PR if you want.

**Comment by Lonami** [comment]
> I can propose a corresponding PR if you want.

Sure, I like it when people contribute code :)

**Comment by cher-nov** [comment]
> Sure, I like it when people contribute code :)

I just didn't sure that it's the right way to fix the problem.
But okay, #74 is already here.

**Comment by Lonami** [comment]
> I just didn't sure that it's the right way to fix the problem.

Well at least it will cause less trouble.
