### ISSUE TITLE
Slow download speed for media

### ISSUE THREAD

**Issue by dante96** [LonamiWebs/Telethon#730]
I'm writing a little script in Python 3, using thelethon, that allows to collect media files from a specific group/channel/chat.
I've noticed that the download speed is very very low, about 60kbps to download a single file.

Are there some solutions?

**Comment by Lonami** [comment]
`pip install cryptg`. It's mentioned in the documentation.

**Comment by dante96** [comment]
Collecting cryptg
  Using cached cryptg-0.1.0.7.tar.gz
Installing collected packages: cryptg
  Running setup.py install for cryptg ... error
Exception:
Traceback (most recent call last):
  File "c:\users\alex\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 103: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\alex\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\alex\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\alex\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\alex\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\alex\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\alex\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 103: invalid start byte

**Comment by Lonami** [comment]
@dante96 pip3

**Comment by Lonami** [comment]
Oh, it's using `python36-32`. That's weird…

**Comment by dante96** [comment]
Same problem with pip3. My version of python: 3.6.4 (windows)
The terminal supports utf8...
Which version should I use?

**Comment by Lonami** [comment]
Python 3.4 or higher is fine, so that should be fine. The problem doesn't seem to be with the library though but rather some encoding weirdness. Try looking online, as I'm not sure what the error is.

**Comment by dante96** [comment]
Just tried with 'manual' installation:
C:\Users\Alex\Desktop\cryptg-master>python setup.py install
running install
running bdist_egg
running egg_info
writing cryptg.egg-info\PKG-INFO
writing dependency_links to cryptg.egg-info\dependency_links.txt
writing top-level names to cryptg.egg-info\top_level.txt
reading manifest file 'cryptg.egg-info\SOURCES.txt'
writing manifest file 'cryptg.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_ext
building 'cryptg' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Alex\AppData\Local\Programs\Python\Python36-32\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\include" /Tccryptgmodule.c /Fobuild\temp.win32-3.6\Release\cryptgmodule.obj
cryptgmodule.c
c:\users\alex\appdata\local\programs\python\python36-32\include\pyconfig.h(59): fatal error C1083: Non è possibile aprire il file inclusione: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

Do I need to install VS2017?

**Comment by Lonami** [comment]
@dante96 it's a C extension, so probably. That's why it will be faster if you install it :P

**Comment by dante96** [comment]
Ops... I've installed it time ago... so it's already on my system but I get that error

**Comment by dante96** [comment]
@Lonami please look [here](https://github.com/teemupitkanen/mrpt/issues/7), it's my problem

**Comment by dante96** [comment]
Solved, needed to download Visual Studio Build Tools 2017 (Visual C++ build tools + Windows Universal CRT SDK). After needed to include them by typing in terminal:
`SET INCLUDE="C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt"
SET LIB="C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64"`

**Comment by Lonami** [comment]
Nice, is the speed better now?

**Comment by dante96** [comment]
Much better!

**Comment by dante96** [comment]
Another question... If I define a progress_callback function and pass it to download_media function, the code breaks (nothing works anymore, won't downloads and if it does the downloaded media is corrupted).

This is my progress_callback:
`def progress_callback(current, total):
    print(current+' '+total)`

**Comment by Lonami** [comment]
You're gonna need to give more information and that should probably be a different issue. Enable `logging` before opening it if you do.

**Comment by dante96** [comment]
`DEBUG:telethon.telegram_bare_client:Invoking GetHistoryRequest
DEBUG:telethon.network.mtproto_sender:Sending requests with IDs: GetHistoryRequest: 6537983920786190464
DEBUG:telethon.network.mtproto_sender:Processing Remote Procedure Call result
DEBUG:telethon.network.mtproto_sender:Received response for request with ID 6537983920786190464
DEBUG:telethon.network.mtproto_sender:Confirmed GetHistoryRequest through normal result ChannelMessages
DEBUG:telethon.telegram_bare_client:Receiving items from the network...
INFO:telethon.telegram_bare_client:Disconnecting...
DEBUG:telethon.telegram_bare_client:Stopping all workers...
DEBUG:telethon.telegram_bare_client:Disconnecting the socket...
INFO:telethon.network.mtproto_sender:Disconnecting MtProtoSender...
INFO:telethon.extensions.tcp_client:OSError "[WinError 10038] Tentativo di operazione su un elemento diverso dal socket" while reading data
INFO:telethon.telegram_bare_client:Connection closed by the user, not reading anymore
`
I hope logging is enabled correctly

**Comment by Lonami** [comment]
> `INFO:telethon.extensions.tcp_client:OSError "[WinError 10038] Tentativo di operazione su un elemento diverso dal socket" while reading data`

What?

**Comment by dante96** [comment]
Just run my script and that is what comes out. My OS is in italian

**Comment by Lonami** [comment]
"Attempt to operation on something other than the socket". I have no idea why Windows is so stupid (most problems with the socket are from Windows…).

**Comment by Lonami** [comment]
Wait, did you call `disconnect()` or something?

**Comment by m3r3lin** [comment]
Hi
What is need to install for error :c++ build tools 14 for  pip install cryptg 
I install some c++ build tools but not work 
Please send me link for download c++ buid tools for this error

**Comment by Lonami** [comment]
v1.2 will use libssl if available, enable DEBUG logging before importing the library to find out.

**Comment by m3r3lin** [comment]
C:\Windows\system32>pip install cryptg --upgrade
Collecting cryptg
  Using cached https://files.pythonhosted.org/packages/4f/21/9d242c1ed5dbf4a26bedf14355db62e2fed1dcc433099e79de5de4fa788c/cryptg-0.1.0.7.tar.gz
Building wheels for collected packages: cryptg
  Running setup.py bdist_wheel for cryptg ... error
  Complete output from command "c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ali\\AppData\\Local\\Temp\\pip-install-xy47k0ra\\cryptg\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Ali\AppData\Local\Temp\pip-wheel-6kvfsjlt --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'cryptg' extension
  b'\\\x00W\x00i\x00n\x00d\x00o\x00w\x00s\x00 \x00w\x00a\x00s\x00 \x00u\x00n\x00e\x00x\x00p\x00e\x00c\x00t\x00e\x00d\x00 \x00a\x00t\x00 \x00t\x00h\x00i\x00s\x00 \x00t\x00i\x00m\x00e\x00.\x00\r\x00\n\x00'
  creating build
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\cryptg
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-Ic:\program files (x86)\python37-32\include" "-Ic:\program files (x86)\python37-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tccryptg/cryptgmodule.c /Fobuild\temp.win32-3.7\Release\cryptg/cryptgmodule.obj
  cryptgmodule.c
  c:\program files (x86)\python37-32\include\pyconfig.h(215): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for cryptg
  Running setup.py clean for cryptg
Failed to build cryptg
Installing collected packages: cryptg
  Running setup.py install for cryptg ... error
    Complete output from command "c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ali\\AppData\\Local\\Temp\\pip-install-xy47k0ra\\cryptg\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ali\AppData\Local\Temp\pip-record-_v74et8r\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'cryptg' extension
    b'\\\x00W\x00i\x00n\x00d\x00o\x00w\x00s\x00 \x00w\x00a\x00s\x00 \x00u\x00n\x00e\x00x\x00p\x00e\x00c\x00t\x00e\x00d\x00 \x00a\x00t\x00 \x00t\x00h\x00i\x00s\x00 \x00t\x00i\x00m\x00e\x00.\x00\r\x00\n\x00'
    creating build
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\cryptg
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-Ic:\program files (x86)\python37-32\include" "-Ic:\program files (x86)\python37-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tccryptg/cryptgmodule.c /Fobuild\temp.win32-3.7\Release\cryptg/cryptgmodule.obj
    cryptgmodule.c
    c:\program files (x86)\python37-32\include\pyconfig.h(215): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

    ----------------------------------------
Command ""c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ali\\AppData\\Local\\Temp\\pip-install-xy47k0ra\\cryptg\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ali\AppData\Local\Temp\pip-record-_v74et8r\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Ali\AppData\Local\Temp\pip-install-xy47k0ra\cryptg\

**Comment by m3r3lin** [comment]
i installl c++ build tools 14 and it work :+1:
