### ISSUE TITLE
Missing supports_streaming support in DocumentAttributeVideo

### ISSUE THREAD

**Issue by Nekmo** [LonamiWebs/Telethon#731]
It is necessary to add support for this flag available recently. Examples:

https://docs.madelineproto.xyz/API_docs/constructors/documentAttributeVideo.html

Current class:
```python
class DocumentAttributeVideo(TLObject):
    CONSTRUCTOR_ID = 0xef02ce6
    SUBCLASS_OF_ID = 0xf729eb9b

    def __init__(self, duration, w, h, round_message=None):
        pass
```

**Comment by Lonami** [comment]
Great. Telegram decided to change the `scheme.tl` *without incrementing the layer number*… **Again.**

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/7bc021bba45528137bd25b3bb67678f8fddd0b5e

**Comment by Nekmo** [comment]
Thanks :)
