### ISSUE TITLE
Calling client.get_input_entity(marked_peer_id) fails if the relevant peer is not in the most recent 100 peers.

### ISSUE THREAD

**Issue by expectocode** [LonamiWebs/Telethon#735]
[This line](https://github.com/LonamiWebs/Telethon/blob/898e550335b9979a131dd956c8aa26a01d341b4c/telethon/telegram_client.py#L2460) causes this issue.

Potential fixes: 
- (async only) Change the iter_dialogs(100) to iter_dialogs(limit=None) so that all the dialogs are tried rather than only the first 100, without losing efficiency for the first 100 thanks to async iterators.
- Change the TypeError on this failure path to a ValueError or something else, so that users can try-catch this code without also catching the **real** TypeErrors elsewhere in this function.

**Comment by Lonami** [comment]
Would you like to make a pull request? Ideally "has ran get dialogs" would be saved to the session file so that it's only done once *ever* for convenience and when required, and on not found, only search until some old dialog has already been retrieved. It's tricky. I've changed that so many times.

**Comment by expectocode** [comment]
Yeah, tricky indeed. Incremental improvements though :)

**Comment by expectocode** [comment]
The thing about saving 'has run get dialogs' to the session (apart from needing to change all the sessions) is that new dialogs may be created that our session doesn't know about, and we wouldn't know that we don't know about these new dialogs. It's a cache invalidation problem :/

**Comment by Lonami** [comment]
Oh, right, old dialogs might talk… It could be somewhat sophisticated. Maybe if you find one you had but it's either the last you got or after that there's a new one, you keep getting more. Not worth the effort right?

**Comment by expectocode** [comment]
I meant new dialogs being created, which would then not be found in get_input_peer because we would think we knew about every dialog.
