### ISSUE TITLE
how to ban user ?

### ISSUE THREAD

**Issue by Mohammadwh** [LonamiWebs/Telethon#739]
hi lonami
i try many code for restrict user but return is False
bot(EditBannedRequest(msg.message.to_id.channel_id,msg.message.to_id,ChannelBannedRights(send_messages=False,send_media=False,send_stickers=False,send_gifs=False,send_games=False,send_inline=True,embed_links=False,until_date=False,view_messages=True)))
or
bot(EditBannedRequest(msg.message.to_id.channel_id,msg.message.to_id,ChannelBannedRights(send_messages=False,send_media=False,send_stickers=False,send_gifs=False,send_games=False,send_inline=True,embed_links=False,until_date=None,view_messages=True)))
return is math domain error
plz help me :(

**Comment by Lonami** [comment]
Well first you should edit your issue to make it look better.

**Comment by Mohammadwh** [comment]
![image](https://user-images.githubusercontent.com/18552903/38246850-586bcf02-3758-11e8-82fa-66361ce1648f.png)

**Comment by Mohammadwh** [comment]
plz help me😭😭

**Comment by Lonami** [comment]
> return is math domain error

Make sure you're using the latest version before trying again, and post the entire traceback if you want any meaningful reply instead just the error message.
