### ISSUE TITLE
How to interpret "SearchRequestrequest" result?

### ISSUE THREAD

**Issue by Etignis** [LonamiWebs/Telethon#740]
I need to get access to some telegram channel to find important (for me) messages.

I use code from example:

```
from telethon.tl.functions.messages import SearchRequest
from telethon.tl.types import InputMessagesFilterEmpty

filter = InputMessagesFilterEmpty()
result = client(SearchRequest(
    peer=client.get_input_entity("channel_name"),      # On which chat/conversation
    q='me',      # What to search for /// serch "t.me/" links
    filter=filter,  # Filter to use (maybe filter for media)
    min_date=None,  # Minimum date
    max_date=None,  # Maximum date
    offset_id=0,    # ID of the message to use as offset
    add_offset=0,   # Additional offset
    limit=10,       # How many results
    max_id=0,       # Maximum message ID
    min_id=0,       # Minimum message ID
    from_id=None    # Who must have sent the message (peer)
))
```

But I don't uderstand what to do with "result":

`print(result)` shows:
```
Traceback (most recent call last):
  File "telegram.py", line 57, in <module>
    print(result)
  File "D:\Progs\Puthon3\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1011-1013: character maps to <undefined>
```

`pprint(result)` shows:
`telethon.tl.types.messages.ChannelMessages object at 0x05E287F0`

I see it's spetial type for messages. But I can't "read" it. I haven't fount examples of working with request result in docs: http://telethon.readthedocs.io/en/latest/extra/examples/working-with-messages.html

**Comment by Lonami** [comment]
> ```
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 1011-1013: character maps to <undefined>
> ```

There's probably some strange characters in the result and it's failing. Perhaps see [Python, Unicode, and the Windows console](https://stackoverflow.com/q/5419/4759433) or [UnicodeEncodeError: 'charmap' codec can't encode - character maps to <undefined>, print function](https://stackoverflow.com/q/14630288/4759433)… No idea.

Either way, the types are described on https://lonamiwebs.github.io/Telethon/ (namely [`ChannelMessages`](https://lonamiwebs.github.io/Telethon/constructors/messages/channel_messages.html)). There you have a list of members and what their value type is. No need to `print()` it (though it helps a lot).

**Comment by Etignis** [comment]
Thank you!
