### ISSUE TITLE
How to convert Web session into Telethon session?

### ISSUE THREAD

**Issue by ChairmanMeow** [LonamiWebs/Telethon#742]
I am having trouble loading a session created in the web telegram client.
The session format from webogram is a JSON file 
```
{
    "dc2_auth_key": "b8ff0cb033408d951490161e7fbe6d2.....",
    "dc2_server_salt": "8838c378338699ee",
    "dc": 2,
    "dc4_auth_key": "141dd51313c8ef8ca974fecf9ddcf........",
    "dc4_server_salt": "da533535cd0708aa"
}
```
I believe the only important parts are the auth key and the dc_id

I have tried replacing the authkey, but seems like the session file has more things i need to do.
```
from telethon.crypto import AuthKey
new_key= AuthKey(data=bytearray.fromhex(obtained_string))
```
How can I create a new .session file that can work with the Telethon client?
I am attempting to modify an existing one, but that is not quite working... it seems that the default sqlite session, i need to modify variables.

I am referencing this issue: `https://github.com/LonamiWebs/Telethon/issues/316`
#316

**Comment by Lonami** [comment]
#316 indeed contains all information you need for that. What problem are you exactly facing?

**Comment by ChairmanMeow** [comment]
OK I resolved this issue. I was attempting to create a new session file via SQLite which turned out quite complex. However the simpler solution is to get an existing one and the just modify the auth_key.

My solution using previously created session file - 'modify.session'

`client = TelegramClient('modify.session',api_id, api_hash)
client.session.set_dc(2,'149.154.167.51',443)
client.session.auth_key= AuthKey(data=bytearray.fromhex(obtained_string))
client.start()`

**Comment by GoldenEagle66** [comment]
@ChairmanMeow in the end it turned out to download the session to the web version? you can provide an example

**Comment by ChairmanMeow** [comment]
@GoldenEagle66 
I used a previous session file that was generated by telethon. 
First I ran:
`client = TelegramClient('first.session',api_id, api_hash)`
Then I renamed **first.session** to **modify.session**  and ran the code snippet I had above

**Comment by GoldenEagle66** [comment]
@ChairmanMeow 
Can you give an example of the code for translating a session on the web?

**Comment by ghost** [comment]
please give an example how to change auth_key

**Comment by vhdm** [comment]
@ChairmanMeow 

please give an example how to change auth_key
