### ISSUE TITLE
Projects using Telethon

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#744]
# [See Projects using Telethon on the Wiki](https://github.com/LonamiWebs/Telethon/wiki/Projects-using-Telethon)

If you have or know any useful project that uses the library, please [update the wiki](https://github.com/LonamiWebs/Telethon/wiki/Projects-using-Telethon) with it so other people can find it more easily.

The library has been around for a while and some people have already made cool things with it. This issue was originally meant to have people comment about these useful projects, but has since then moved to the wiki.

As an example of some projects using Telethon itself to make cool things:

### [telegram-export](https://github.com/expectocode/telegram-export)

A tool to download Telegram data (users, chats, messages, and media) into a database (and display the saved data).

### [mautrix-telegram](https://github.com/tulir/mautrix-telegram)

A Matrix-Telegram hybrid puppeting/relaybot bridge.

### [TelegramTUI](https://github.com/bad-day/TelegramTUI)

A Telegram client on your terminal.

**Comment by Poolitzer** [comment]
https://github.com/Poolitzer/spotify_telegram_bio_updater

pretty proud of it, works good. May want to rename it on the way, will keep it here updated (or if it's in the doc then there)

**Comment by baalajimaestro** [comment]
https://github.com/raphielgang/telegram-userbot

Pretty much a modular userbot, similar to marie in its base, written fully on telethon, with abilities to block personal messages from random people and much more. 

Check out the wiki on the repo for more/use the help command with the bot.

(( I dont wanna advertise too much xD ))

**Comment by peaktogoo** [comment]
https://gitlab.com/blankX/gban-helper

Does exactly what it said, Help you gbanning peopple

https://github.com/mojurasu/kantek/

Does like the bot above but pretty much better!

**Comment by SpEcHiDe** [comment]
Hi. Please check out https://telegram.dog/CheckRestrictionsBot which can allow you to check restriction_reason of public bots and channels. It also works with private channels. 😉

**Comment by Ak4zh** [comment]
Please consider adding ConfluxBot to the list of projects using telethon.

ConfluxBot allows you to connect multiple social Media accounts including **Telegram** (used telethon as the back end), **Discord** and **Twitter** at one place.

_Users can create cross posts between accounts by creating connections._

**Telegram Bot Link:** https://telegram.me/ConfluxBot
**Website:** https://confluxbot.com
**Web Dashboard:** https://app.confluxbot.com

**Video Tutorial:** https://www.youtube.com/watch?v=gMmBFmCJSVA
**Documentation:** https://confluxbot.readthedocs.io/en/latest/

**Comment by Lonami** [comment]
I plan to move the [documentation page of "Projects using Telethon"](https://github.com/LonamiWebs/Telethon/blob/c904b7ccd8a1dbc185bb614df51ebb124de109bd/readthedocs/examples/projects-using-telethon.rst) to the [wiki - Projects using Telethon](https://github.com/LonamiWebs/Telethon/wiki/Projects-using-Telethon). This way people can add any project they want  with more ease, and I'm also lowering the quality bar with this so any project can be welcome.

If you're interested in having your project there, please add it yourself.
