### ISSUE TITLE
Bug in iter_participants() while using filters ChannelParticipantsBanned/ChannelParticipantsKicked 

### ISSUE THREAD

**Issue by pitzlabs** [LonamiWebs/Telethon#745]
TypeError: __init__() missing 1 required positional argument: 'q'

The issue is that that both ChannelParticipantsBanned and ChannelParticipantsKicked has "q" member in it but the object is constructed as filter = filter()

Fix - have a q parameter for ChannelParticipantsBanned & ChannelParticipantsKicked filters

**Comment by Lonami** [comment]
Hmm, seems more like your issue who passed a type instead of an instance. That line is there for convenienve (because *a lot* of people pass a type instead an instance), but I thought they would at least pass the right instance if it *needed* some parameter.

**Comment by Lonami** [comment]
Meh, who cares.

**Comment by pitzlabs** [comment]
That works !
Also thanks for the great work.

**Comment by Lonami** [comment]
Thanks :)
