### ISSUE TITLE
Can I find the contents of a message with message id and chat_id?

### ISSUE THREAD

**Issue by cho060303** [LonamiWebs/Telethon#757]
Can I find the contents of a message with message id and chat_id?

**Comment by Lonami** [comment]
Yes, you can.

**Comment by cho060303** [comment]
What is the name of the function?

**Comment by Lonami** [comment]
@cho060303 have you tried searching?

**Comment by cho060303** [comment]
I could not find it in the document.

**Comment by Lonami** [comment]
[Try again](https://lonamiwebs.github.io).

**Comment by cho060303** [comment]
Thank you. I'll try searching again.

**Comment by ngodanghuuha** [comment]
client(AddChatUserRequest(
        chat_id,
        user_id,
        fwd_limit=10
))
i also have an issue like you, where can i find chat_id

**Comment by bmwant** [comment]
@bf-dev here is an example (using bot, mostly the same for client version of the code)

```
bot = TelegramClient('bot', API_ID, API_HASH).start(bot_token=BOT_TOKEN)
result = await bot(functions.messages.GetMessagesRequest(id=[message_id]))
message = result.messages[0]
print(message.text)
```
[Check documentation](https://tl.telethon.dev/methods/messages/get_messages.html) for more

@ngodanghuuha if you want to get current chat id use `get_chat`

```
@bot.on(events.NewMessage)
async def any_message_arrived_handler(event):
    chat = await event.get_chat()
    full_chat = await bot(functions.messages.GetFullChatRequest(
        chat_id=chat.id
    ))
```

example above shows how to get full chat too which contains a lot of extra information

**Comment by DaltonG3** [comment]
async def main():
    message = await client.get_messages(chatid, ids=a)
    print(message.text)
with client:
    client.loop.run_until_complete(main())

**Comment by soroushfathi** [comment]
totally work❤🔥 thanks a lot🙌🏻

**Comment by soroushfathi** [comment]
> totally work❤🔥 thanks a lot🙌🏻

**Comment by soroushfathi** [comment]
> @bf-dev here is an example (using bot, mostly the same for client version of the code)
> 
> ```
> bot = TelegramClient('bot', API_ID, API_HASH).start(bot_token=BOT_TOKEN)
> result = await bot(functions.messages.GetMessagesRequest(id=[message_id]))
> message = result.messages[0]
> print(message.text)
> ```
> 
> [Check documentation](https://tl.telethon.dev/methods/messages/get_messages.html) for more
> 
> @ngodanghuuha if you want to get current chat id use `get_chat`
> 
> ```
> @bot.on(events.NewMessage)
> async def any_message_arrived_handler(event):
>     chat = await event.get_chat()
>     full_chat = await bot(functions.messages.GetFullChatRequest(
>         chat_id=chat.id
>     ))
> ```
> 
> example above shows how to get full chat too which contains a lot of extra information

totally work❤🔥 thanks a lot🙌🏻

**Comment by soroushfathi** [comment]
the above solution has some  bug, but there is another function that return the message with client.[get_message()](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.messages.MessageMethods.get_messages)
even you can use [iter_message()](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.messages.MessageMethods.iter_messages) to iterate in your all chat

good luck
