### ISSUE TITLE
mt_proto_sender logs huge byte arrays

### ISSUE THREAD

**Issue by christosR** [LonamiWebs/Telethon#759]
W 180411 17:53:17 mtproto_sender:542] Lost request (ID 6543234913852079008) with code 0x96a18d5 will be skipped, contents: File(type=FilePartial(), mtime=1518737356, bytes=b'OggS\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x88%"l\x00\x00\x00\x00\x0f\xf6\x9b"\x01\x13OpusHead\x01\x018\x01\x80>\x00\x00\x00\x00\x00OggS\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x88%"l\x01\x00\x00\x00\x98\x91\xdf\x8d\x03\xff\xff\xfeOpusTags\x15\x00\x00\x00libopus unknown-fixed\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x .... ......

Not sure why but my logs are full of these. 
Why is this happening? 
is it necessary for the `mt_proto_sender` to log the whole byte array?
 
I am on python 3.5 and telethon version is: 0.18.2.3

**Comment by Lonami** [comment]
> is it necessary for the `mt_proto_sender` to log the whole byte array?

Well yes. What you're seeing is #658. Can you reproduce consistently? Provide `DEBUG` logs?

**Comment by christosR** [comment]
[D 180411 18:08:06 telegram_bare_client:454] Invoking GetChannelsRequest
[D 180411 18:08:06 mtproto_sender:94] Sending requests with IDs: GetChannelsRequest: 6543238737083887060
[D 180411 18:08:06 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:06 mtproto_sender:481] Received response for request with ID 6543238737083887060
[D 180411 18:08:06 mtproto_sender:520] Confirmed GetChannelsRequest through normal result Chats
[D 180411 18:08:06 telegram_bare_client:666] Receiving items from the network...
[I 180411 18:08:06 telegram_client:2121] Downloading file in chunks of 131072 bytes
[D 180411 18:08:06 telegram_bare_client:454] Invoking GetFileRequest
[D 180411 18:08:06 mtproto_sender:94] Sending requests with IDs: GetFileRequest: 6543238737654512368
[D 180411 18:08:07 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:07 mtproto_sender:481] Received response for request with ID 6543238737654512368
[D 180411 18:08:07 mtproto_sender:504] Confirmed GetFileRequest through error The file to be accessed is currently stored in DC 1
[D 180411 18:08:07 telegram_bare_client:666] Receiving items from the network...
[I 180411 18:08:07 telegram_client:2142] File lives in another DC
[I 180411 18:08:07 telegram_bare_client:384] Creating exported new client
[I 180411 18:08:07 telegram_bare_client:199] Connecting to 149.154.175.50:443...
[I 180411 18:08:07 telegram_bare_client:205] Connection success!
[D 180411 18:08:07 telegram_bare_client:454] Invoking GetFileRequest
[I 180411 18:08:07 telegram_bare_client:496] Initializing a new connection while invoking
[D 180411 18:08:07 mtproto_sender:94] Sending requests with IDs: InvokeWithLayerRequest: 6543238739419612492
[D 180411 18:08:07 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:07 mtproto_sender:481] Received response for request with ID 6543238735904243432
[D 180411 18:08:07 mtproto_sender:520] Confirmed GetFileRequest through normal result File
[D 180411 18:08:07 telegram_client:2155] Saved 131072 more bytes
[D 180411 18:08:07 telegram_bare_client:454] Invoking GetFileRequest
[D 180411 18:08:07 mtproto_sender:94] Sending requests with IDs: GetFileRequest: 6543238739526097856
[D 180411 18:08:07 mtproto_sender:206] Processing container result
[D 180411 18:08:07 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:07 mtproto_sender:481] Received response for request with ID 6543238735833166084
[W 180411 18:08:07 mtproto_sender:542] Lost request (ID 6543238735833166084) with code 0x96a18d5 will be skipped, contents: File(type=FileUnknown(), bytes=b'', mtime=0)
[D 180411 18:08:07 mtproto_sender:221] Processing MsgDetailedInfo result
[D 180411 18:08:07 mtproto_sender:221] Processing MsgsAck result
[D 180411 18:08:08 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:08 mtproto_sender:481] Received response for request with ID 6543238739526097856
[D 180411 18:08:08 mtproto_sender:520] Confirmed GetFileRequest through normal result File
[D 180411 18:08:08 telegram_client:2155] Saved 131072 more bytes
[D 180411 18:08:08 telegram_bare_client:454] Invoking GetFileRequest
[D 180411 18:08:08 mtproto_sender:94] Sending requests with IDs: GetFileRequest: 6543238743521974768
[D 180411 18:08:08 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:08 mtproto_sender:481] Received response for request with ID 6543238739419612492
[W 180411 18:08:08 mtproto_sender:542] Lost request (ID 6543238739419612492) with code 0x96a18d5 will be skipped, contents: File(type=FilePartial(), bytes=b'OggS\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\xde\x90$}\x00\x00\x00\x00_X\xb4V\x01\x13OpusHead\x01\x018\x01\x80>\x00\x00\x00\x00\x00OggS\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xde\x90$}\x01\x00\x00\x00\x10\xce^\xf1\x03\xff\xff\xfeOpusTags\x15\x00\x00\x00libopus unknown-fixed\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00OggS\x00\x00@\x0b\x00\x00\x00\x00\x00\x00\xde\x90$}\x02\x00\x00\x00\xc1\xa8\xc9(\x01eX\x80\x0c<\xac\xf6vr/\xa7\x04\xa3\x8eP\xfe0f\x18\x131{ik\x87\xcc\r\xf1\xae\x17\xb2\xb3wp\xe2\xfe\xca\xf4\x96\x0fYBy\xcdA\xb3\xfa\xa3\x88\xe9$\x9d\xb8\xb9M8\xcb\xdf\xbb\xb5\xae#\xcbZ\x12h\xb5\xa6.\x95\xed0}zM8\x1d-\xf2\x02\x15\xe6\xd7\x9c\t\xad\x19\x8f\xe2z_K|j\xe0e_&s\xc4\x1a\xe0OggS\x00\x00\x80\x16\x00\x00\x00\x00\x00\x00\xde\x90$}\x03\x00\x00\x00\x0b\xbae\x05\x01~X\xe2O\xdb*,\xb1\x17WL/\xed(\xd9\x0c\x96Wa\xa2\xc1>\x0b"\xc7Y\xcc\xe2M\x0f\xb76:\xed\x05\xe1\xd3R\x18$\xb0\x9d\x8d\x7f\xff\x94\xb6!\x91{\x8c\xbft\xe5\xdc\x0f\x01\\64\x1a\x1c\x0b|=\x8a\xfdb\xc0\x9c\xb2"Y\x84\x7f\xa0\xdcwL1w\xd7-b\xc0p\xb2\xe9t\xbf\x11f\xe7\x98\x16R&\x95\xf3\x1e\x81\x16\x7fqG\x1b\xcf\xfc\xe9^\xff\x0e\xaf)\xd9\xd0\xfay\x8b\xd4\xb1\x01\x1bQ\xfa\xe4\xb0OggS\x00\x00\xc0!\x00\x00\x00\x00\x00\x00\xde\x90$}\x04\x00\x00\x00\xb2\x01j\xfb\x01zX\xe2\xb7\x15q\xbe\x06\xe2<\x1d\xdd\xa6W_\xa8._m\x1d\x05Y\xb2z\xfd4T\xfa\xe2\xe1w\xe9\xeaT\x07\xd0\x06\xbb\xee\xe2\xc5B\xe3\xc5\xe7\x97i\xee:@\x1e\x99\xe3\x91\xb3F\x1bJTT~\xcb\xa8_sAO\xedZ\xdb\x02\te\xadC\xe3i\x83\x81\x84d\x9cm`\xf51j\xfd\xdfO\xfeT\x05.6\xd7\xc8Z\xb7\x87\x9c\xb4\xaaQ\xea\xa4\xaa\xfd&L\xc8fQ\xa8f\x03\xe8\xc2\xb8\xd6\xbd$\x10OggS\x00\x00\x00-\x00\x00\x00\x00\x00\x00\xde\x90$}\x05\x00\x00\x00\xf2\x08x \x01mX-\x8e\xd1\xa73\xbd\xb7$\xcc\x02L\xe9\xb1\xf8\x05\n\xa91\xb7\xe1\x80R\xfb_\x0f\x01*\x1e\xbf\x1a\xdd\xc2\xe4\x10\xfej\xe7\x1b\xe5\xf9J\xc9\xa0\xec\xcf\xe2\xc1|>\xd4qus#\xa9\xf4\x1f+n\x0b\to\xd6\x8c\nl|\x0e~\xed\x92hsy\xcfQ\x08\xb1z\xb5tNG\xaf\xf9\xa4\x03LO\xb5\x1b\xef\tb\x8f\xbe\xd4i\xfb\xbf\x94\xef\x9fa\xda\xcc<\xb8OggS\x00\x00@8\x00\x00\x00\x00\x00\x00\xde\x90$}\x06\x00\x00\x00\x80\xdc\x08K\x01xX\xe3A\xfbc\xce\xbf\xe3e \xa6\x8e\xe2g\xf7\x89\x9a\xec\xbd\xda\x8d"\xa2\xc81\xb9W\x9f\x9b\x0e\xfc\xe55HM\x08\xb5\x1c\\\x14\x8f\xd0T\xce\xcc\xbd\xd6\xc4\xcd\xc5\xf1hP\x99\xaf\xc1\xe9v\xfe"\xf5v\xccz;\xc4\xb8\'j\xa3A\x92\x8d\xf2\xc6\xa5\xfd\xa1pW\xa6@_\xe1\xb4\xc2\xb1p\xd8\x93\xe2H\x1b\x825\xb5m\xea\xd5U\x95\xf8\xd9\xd7\x1c\xe93\xc3\xa3aa\x96\xe6\x14\xa2\xder\xe2v0OggS\x00\x00\x80C\x00\x00\x00\x00\x00\x00\xde\x90$}\x07\x00\x00\x00\xa4\xf5\x12\x92\x01~X\xe0\x91\xf0\xa7y\x87\xc0\xc7\xb1\x95u\xd9Q.\x15\x0f\xe2#&0\x0fZ\x0e\xe2\xad\x1bQ3\xe4c:\x18\xe7\xa3\xca\xaf\x07\xf4p`\xb8\xa0e\x1c\x9f\x91\xbe\xc7\x92:C!\xee\xdb\xbe\xf2_OJ\xea\xe8\xc6=]\xa2Kf<a\xff\xe3LU\x90G\xbe\x18\xa2\xf0A\xd3$\xd0\xc7\x11\xf3\xcf\xaf#\xaa\x8a2j\x1e\xe5hD\xcc\x07\x88mr\x83\xf6%EU\x87\xf6\x96\xcf\xf2\x81\x8cI\xee\xda\xe1(\xe19\xb7FS@OggS\x00\x00\xc0N\x00\x00\x00\x00\x00\x00\xde\x90$}\x08\x00\x00\x00\x0b\xbe\x97\xd8\x01xX\xe3A\xe8\xa6+ \xffTi,@\xdd\r\x9c\x96m#\x8dI\xbb\xd44\x1f\x94B\x8b\x0b\xf6\xa3q@\x9e\xdc\xa7C\x92\xdb\x87\xb2\xeap\x1a\xecd}\xaa\xd0\xe0\xa0`\xa5\x0c%\xbf\x92\x01\x90g[wED\x0c\x84\x98\xf3\x12\xcf\x1f\xc2\xfa C6\'\x01y$\xc6\x18\x88\nX\xa7\xeeN\xb6Z!JUM\xe1\xc8>\xca\x83\xb7I\xb7\xec\x14\xb1\xe3\x87\xd8{NS\xb6J\x9b\x9e\x9eC<\xd0\x9c+OggS\x00\x00\x00Z\x00\x00\x00\x00\x00\x00\xde\x90$}\t\x00\x00\x008\xc6v\xd0\x01~X\xe3G\xf4\xd8\xd7\xac\xa3\x0e\xc4W\xa8JN\xafZ\x9a\xd7i9#$8\xc1is\xc6\xde\x92\xa2\x92\xc9\xf5\x8f(\x13\xa2\x0em\xfdR\xad&\xdd\x98\x81v\xa8\xfccw\xb2\x0f\xc4e\x1c\x89\xa2\xde\xb00t@-\xcc\x03\x05\xb80\xd7\xdf"\xa6\xe90\x03=\xd8\x8f\x0b\x82\x98\xbe1\x06\x1a\xfa\x94]\xd3;\xe8I#\x08\x12R\xd7<\xce\x10\x95S\xb0\xa9\xa9\xc0\x8d\xc4\xb1\x1d9s\x19\x85\xa7\x06\x03\xa1B\xf2\x81\xab=\xde2OggS\x00\x00@e\x00\x00\x00\x00\x00\x00\xde\x90$}\n\x00\x00\x00\xaa)\xcc\x86\x01qX\xe0\xa8#\x8drI2\xacU&\xf1W\x08\x9d\xb1\xcb(\xd1\xf2\xae)N!\xd1\x08\x9ewK\xe4\xbd]tu\x8dG\xfbx?\xad\xdb3\xd8\x9a\xe4F\x13J\'\xa4\xc1#\x89PJfp\x01\xd1\xc6\x11\x02\xcb\xd3a\xe9\xa6D\xb3\xcc\r\xfe9\xb2\x1f\x86\xa0\xf74\x0f\xa4\xca\x96=b\xb5M\xea?C\x83\x0ew;\x13\xe7J\xb4\xf2\xd1\xed\xfe\xb8x\xb6\x08\x7f\xb8\xe9\x95\xef\xcbLOggS\x00\x00\x80p\x00\x00\x00\x00\x00\x00\xde\x90$}\x0b\x00\x00\x000\xeeD<\x01wX\xe3\x87]8SW\xa4\xdf_\x80a\x00\x91\x14\x05\r\xb8\x9b\x9e\xb3\xb1YA\xcc\xa1\x1a\xd6f2\xbf\xec\xe8A\xc0\xad\xea\xd4F\x1a\x02\xe6Y\x07\x06;\'\xe1\xede;s \n\r\xab\xe0?b\xf8\x18\xe7C\xe3R\xba]\x1c\xa2\x96\xef\x90\x8d\x01\xd2\xdd\x8d\xf2+\\\x1b\n\xcc\x05\x1b\xf3v\x82 X\xc3\x86\x86\xcc@\xbfI\xe6\xd8=\x05i\t1\xf8\xd3\x0f\x9a4\x198\x9a\x08\xa6?\x02\x85\xd7\xc0OggS\x00\x00\xc0{\x00\x00\x00\x00\x00\x00\xde\x90$}\x0c\x00\x00\x00\x92A\xdd\xfa\x01\x83X\xe3\x92\x19+\xaf\xac\xb1\xb6\xc2u\x94_\xc6aA\xbc\x03j\x9bT#\xcfN\xda\xc5i\xdd\xfb\xf7\xd2\x93\xb5\x0b\x06h\xd1`\x81\x15Q\xa1|\xca\x07\x99s\xd2\x9d\xdeT\x98\x11WF\xda!\r\x8c\xcf\xc5\xbd\x9b\xca\xa7\xf7\x11,\x81wc\x8d\xcdG\xff\xbc<\x98c\xe5\xc7\xd1d\xf9}jt\x1c}\x7f\xbc\xa7\xbf/d\x0c#\x1f\x04\xf1\xdf\x12\xb3b\xbd\x7fRxU\xbb,\x1a\x91O\x03|vJ/\x1b\xdf\xac\xb5\xfc\xc9l\xf4\n1\xd9\xf0OggS\x00\x00\x00\x87\x00\x00\x00\x00\x00\x00\xde\x90$}\r\x00\x00\x00S\xaf\x18#\x01yX\xe3\xee\x018\x00\xe6\xf9M>\xcd\x06;\xd3>\x87\xf9\x1e\x98\xd2w\x8e\xf5\x8c\x7f)R1t\xd5QK}[*s\x8as=/j\xaaV&+\xa0\x82tQ\xf6\xb8\xfcu\xeb\xef\xcdr<\x94\x051!\xd3y"\xc4\xf3\xca&\xf3\x1f\xdd\xeb\x16\xae\xf7\xe8 \xdb\x0c+\x05\x04\xda\xd2{\x08\xd5\x83N\x9aD\x1d\x19\x0e\x88\x08\nmVS\x92vP\xfe%\x1f~\xe5\xcf\xfbzZ^&w\x0c\xa5\x97\xb4\xe0OggS\x00\x00@\x92\x00\x00\x00\x00\x00\x00\xde\x90$}\x0e\x00\x00\x00G\x95Pn\x01oXA\x83\xc9A$\xb7)\xf0oZ\xf5;\x04\x13hv\x99f\xa6\x1f\xf0\x7f\x1d\x87\x81&\xcf!,\x01\x97G\xb2\x13P\x88\xc1-\x05\x9d\x14tDZ\x92\tK\x1c\x81\xd5\x16[\xa2M\x7fg\x92\x81\xb8\xdc}y]2\xfef\xc2\x11\xa6\xc4\xe9\x9d\xaf\x8c\x89\xcc:\x0e\xeeY\xef\x8ai\xff&[\xf6\xaa\xe6\xdf\xa6\xa9\x9bVy"f\xe5S|\x01\xd2\x13\xc4}\x15H4\x1e\x8bOggS\x00\x00\x80\x9d\x00\x00\x00\x00\x00\x00\xde\x90$}\x0f\x00\x00\x00\x8c\xa12S\x01nX\x80\xad\x0b\xba\x0f\xe4\xbb\'u\t\x07#\xdac\xb7\xb6\xae\xc7\x92\xd5\xfa\xa4y\x8c\x96nV\xab\xf6\x87f=\'-\xe8\x03^\xac\xd08\x95\x9do\x80\xb3\x02r\x0f\xb0\x16\xd3\x81\xdb\x8e\x7f\x00Z\x06\xa6\xec\x17q\xd5d\x19\x05\x9b\x14\x13\xb4\x1ay\x0b$\xa7ol*f.W\x00\x18\xe3\x99w\x92"\xced\x1e\xcf\xef\xda&\xa4q\x93\xdei-
\xd0m\x0b\x8f\xb9\xb1\xd0\xc0OggS\x00\x00\xc0\xa8\x00\x00\x00\x00\x00\x00\xde\x90$}\x10\x00\x00\x00t\xef~u\x01fX\x83\x87_\

the rest of the byte array is ommited

[D 180411 18:08:09 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:09 mtproto_sender:481] Received response for request with ID 6543238743521974768
[D 180411 18:08:09 mtproto_sender:520] Confirmed GetFileRequest through normal result File
[D 180411 18:08:09 telegram_client:2155] Saved 131072 more bytes
[D 180411 18:08:09 telegram_bare_client:454] Invoking GetFileRequest
[D 180411 18:08:09 mtproto_sender:94] Sending requests with IDs: GetFileRequest: 6543238747739168968
[D 180411 18:08:10 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:10 mtproto_sender:481] Received response for request with ID 6543238747739168968
[D 180411 18:08:10 mtproto_sender:520] Confirmed GetFileRequest through normal result File
[D 180411 18:08:10 telegram_client:2155] Saved 131072 more bytes
[D 180411 18:08:10 telegram_bare_client:454] Invoking GetFileRequest
[D 180411 18:08:10 mtproto_sender:94] Sending requests with IDs: GetFileRequest: 6543238751907839268
[D 180411 18:08:10 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:10 mtproto_sender:481] Received response for request with ID 6543238751907839268
[D 180411 18:08:10 mtproto_sender:520] Confirmed GetFileRequest through normal result File
[D 180411 18:08:10 telegram_client:2155] Saved 74104 more bytes
[D 180411 18:08:10 telegram_bare_client:454] Invoking GetFileRequest
[D 180411 18:08:10 mtproto_sender:94] Sending requests with IDs: GetFileRequest: 6543238754252165288
[D 180411 18:08:10 mtproto_sender:202] Processing Remote Procedure Call result
[D 180411 18:08:10 mtproto_sender:481] Received response for request with ID 6543238754252165288
[D 180411 18:08:10 mtproto_sender:520] Confirmed GetFileRequest through normal result File
[I 180411 18:08:10 telegram_bare_client:264] Disconnecting...
[D 180411 18:08:10 telegram_bare_client:267] Stopping all workers...
[D 180411 18:08:10 telegram_bare_client:272] Disconnecting the socket...
[I 180411 18:08:10 mtproto_sender:74] Disconnecting MtProtoSender...


does this help? on my local machine doesn't happen as often as when I run it in docker

**Comment by Lonami** [comment]
Is the file downloaded correctly after all this?

**Comment by christosR** [comment]
I added some more logging in order to see which file is this. Will update soon

**Comment by christosR** [comment]
yup, the files are getting downloaded at the end

**Comment by Lonami** [comment]
So the files get downloaded correctly but Telegram sends information that… doesn't has any effect apparently? Originally I set it as a warning because it's an odd thing, but if it's normal… No clue why it happens, I'd love to know why.

**Comment by christosR** [comment]
I am not familiar with that class or the mtproto protocol, will have to dig more. However, looks like that happens for large files that live on different datacentres and the client tries to reconnect when is already connected... this is more of an assumption and not conclusion

**Comment by Lonami** [comment]
Yes I think it happens on DC migrations indeed, as mentioned in the issue linked above.
