### ISSUE TITLE
is_user_authorized() fails after log_out()

### ISSUE THREAD

**Issue by cher-nov** [LonamiWebs/Telethon#76]
Code to reproduce:
```python
#!/usr/bin/env python3

import sys

import telethon

# NOTE: DON'T SHARE THESE VALUES!
TGAPP_API_ID = *
TGAPP_API_HASH = *

phone = sys.argv[1]

cli = telethon.TelegramClient(phone, TGAPP_API_ID, TGAPP_API_HASH)
cli.connect()
if not cli.is_user_authorized():
    cli.send_code_request(phone)
    code = input("Enter authorization code: ")
    cli.sign_in(phone, code)

cli.log_out()
print(cli.is_user_authorized())
```

This will fail with the next error:
```
Traceback (most recent call last):
  File "./tglogin.py", line 16, in <module>
    print(cli.is_user_authorized())
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 195, in is_user_authorized
    return self.session.user is not None
AttributeError: 'NoneType' object has no attribute 'user'
```

I could try to fix this issue by myself (it happens because `.session` is set to `None` in `log_out()`), but I'm unsure for now in my current knowledge of library code.

**Comment by Lonami** [comment]
> I could try to fix this issue by myself (it happens because `.session` is set to `None` in `log_out()`)

So replace with:
```python
if self.session and self.session.user:
    return True
return False
```

**Comment by evandrix** [comment]
> > I could try to fix this issue by myself (it happens because `.session` is set to `None` in `log_out()`)
> 
> So replace with:
> 
> ```python
> if self.session and self.session.user:
>     return True
> return False
> ```

i.e. `return self.session and self.session.user`
