### ISSUE TITLE
whether a user is member of channel or not?

### ISSUE THREAD

**Issue by dara1400** [LonamiWebs/Telethon#760]
Hi

I want to just check whether a special user is member of a channel or not?
I want to do this by user_id.
ChannelParticipantsSearch dose not accept user_id as input.

any suggestions?

what is the fastest method to check ?

**Comment by Lonami** [comment]
There's no way to search by ID, this makes no sense in a legit application (why would the end user even need to know about *IDs*?) and the API is modeled with these applications in mind, not random scripts. So you're out of luck. Get all participants and check if the ID is between them.
