### ISSUE TITLE
how to use an auth.sendCall api 

### ISSUE THREAD

**Issue by henrymark92** [LonamiWebs/Telethon#761]
Link API SendCall:
https://core.telegram.org/method/auth.sendCall

Thanks

**Comment by Lonami** [comment]
That method is from layer 23. We're on layer 75, and it's gone. Look for it [here](https://lonamiwebs.github.io/Telethon/) instead.

**Comment by henrymark92** [comment]
@Lonami 
which telethon version build on layer 23. I want use send call method plz.
Thanks

**Comment by Lonami** [comment]
You need to replace the `telethon_generator/scheme.tl` file with layer 23, run `python setup.py gen_tl`, and then make a lot of modifications to the `TelegramClient` for it to work.

**Comment by henrymark92** [comment]
@Lonami 
Have a lot of change modifications. I cannot do it. Can you support a version using layer 23.
Thanks

**Comment by Lonami** [comment]
@henrymark92 no.

**Comment by henrymark92** [comment]
@Lonami  Can you make a version support python 2.7?

Thanks

**Comment by Lonami** [comment]
@henrymark92 no.

**Comment by henrymark92** [comment]
I will help u
