### ISSUE TITLE
how i can  get a list of supergroups and groups in telethon?

### ISSUE THREAD

**Issue by Mohammadwh** [LonamiWebs/Telethon#762]
hello 
how i can  get a list of supergroups and groups in telethon?
in tg vysheng one method do this work
this method is in telethon?

**Comment by Lonami** [comment]
No there's no method to do *directly* that but there are other methods to achieve the similar thing.

**Comment by Mohammadwh** [comment]
If possible, introduce a way to do this

**Comment by Lonami** [comment]
No, you probably can figure that out yourself with enough knowledge, or maybe ask in [@TelethonChat](https://t.me/telethonchat).

**Comment by dreammaker0717** [comment]
I would like to get the list of all groups for mega group using telethon.
Please help me!
