### ISSUE TITLE
The phone code entered was invalid... but it should be valid

### ISSUE THREAD

**Issue by ZombieTheBest** [LonamiWebs/Telethon#763]
Hello,
I'm trying to implement an automatic account-creation system using smspva API to generate Phone Numbers and get SMS.
I've coded everything, and smspva seems to work:

I get the phone number and then:
```
client = TelegramClient(phone_number, api_id, api_hash) //create a session with the phone number as name (in the form +7123456789...)
assert client.connect()
client.send_code_request(phone_number) //phone number (in the form +7123456789...)
```

Then i place the listener to receive SMS, and I get it:
`code = check_sms(number_id)`

I've printed out the code to see it was correct:
`Got Code: 90156`

Then i just pass the code into sign_up function with this: 
`myself = client.sign_up(phone_number, code)`

And it fails:
```
Traceback (most recent call last):
  File "account_creator.py", line 35, in <module>
    myself = client.sign_up(number[1], code)
  File "venv/lib/python3.6/site-packages/telethon/telegram_client.py", line 468, in sign_up
    last_name=last_name
  File "venv/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 459, in __call__
    result = self._invoke(call_receive, *requests)
  File "venv/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 551, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneCodeInvalidError: The phone code entered was invalid 
```
It fails also if i replace the sign_up part with this:
`myself = client.sign_up(phone_number, input('Enter code:'))`

If I type the code manually it still fails, but the code should be correct... as you can see:
```
{"response":"1","number":"123456789","id":2222260,"text":"16782","extra":"0","karma":33.975,"pass":"","sms":"16782","balanceOnPhone":0}
Got Code: 16782
Enter the Code: 16782
Traceback (most recent call last):
  File "account_creator.py", line 35, in <module>
    myself = client.sign_up(number[1], input('Enter the Code: '))
  File "venv/lib/python3.6/site-packages/telethon/telegram_client.py", line 468, in sign_up
    last_name=last_name
  File "venv/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 459, in __call__
    result = self._invoke(call_receive, *requests)
  File "venv/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 551, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PhoneCodeInvalidError: The phone code entered was invalid
```

I have no idea what else I could try. I'm pretty new to Python. Also I'm just using all my smspva balance for testing ahahah

Thanks a lot :)

**Comment by Lonami** [comment]
If you send the code over Telegram itself, it will expire inmediatly. If you're going to send it over Telegram, obfuscate it somehow first.

**Comment by Lonami** [comment]
[Quote](http://telethon.readthedocs.io/en/latest/telethon.html#telethon.telegram_client.TelegramClient.sign_in):

> *The code that Telegram sent. Note that if you have sent this code through the application itself it will immediately expire. If you want to send the code, obfuscate it somehow. If you’re not doing any of this you can ignore this note.*

**Comment by ZombieTheBest** [comment]
@Lonami Thanks for the ultra-rapid answer! I've read that part, but thought it was only meant for codes received over Telegram App and not over SMS. Why it still does not work if I put it manually?

**Comment by ZombieTheBest** [comment]
@Lonami Thanks again.

```
number = get_number()
if number[0] != -1:
    print("ID: {}  |  Number: {}".format(number[0], number[1]))
    try:
        client = TelegramClient(number[1], api_id, api_hash)
        assert client.connect()
        client.send_code_request(number[1])
    except Exception as e:
        print(e)
        ban_number(number[0])
        sys,exit(1)

time.sleep(5)
code = check_sms(number[0])
if code != -1:
    print("Got Code: {}".format(code))
    myself = client.sign_up(number[1], input('Enter the Code: '))
else:
    print("Error getting confirmation code.")
```

This is my code, where number[1] contains the phone number and number[0] contains a smspva ID.

The code is returned in the check_sms function, with this return        
```
 if j['response'] == '1':
            return j['sms']
```

How should i obfuscate the code? I'm asking because every number I use i'm paying about 0.10$... and done many tests ahahah
Open a issue here was my last resort

**Comment by Lonami** [comment]
> How should i obfuscate the code?

`1.2.3.4.5`, maybe `12345+137 -> 12482`. There are several ways.

> Does this work with legit phone numbers that you actually own physically instead `smspva`'s?

**Comment by ZombieTheBest** [comment]
@Lonami Oh well... just tried with my phone.

I kept sign_up and got the "code invalid". Tried with sign_in and worked (of course i already had a telegram account). Maybe I have to try with sign_in first and then if it fails sign_up?

**Comment by Lonami** [comment]
Sign in works if you have an account. Sign up works if you don't. Normally, you would know when you do and when you don't have an account. `.start()` handles that for you.

**Comment by ZombieTheBest** [comment]
@Lonami 
```
Got Code: 30565

Process finished with exit code 0
```

Thanks, thanks, thanks! I finally got it. I thought that smspva was selling unused phone numbers, but apparently they are selling already-activated telegram account. Thats why sign_up was not working. 

Changed my code with this:

```
code = check_sms(number[0])
if code != -1:
    print("Got Code: {}".format(code))
    try:
        myself = client.sign_in(number[1], code)
    except Exception as e:
        myself = client.sign_up(number[1], code)
else:
    print("Error getting confirmation code.")

```

Thanks again for your help!

**Comment by Lonami** [comment]
You might not be the first one to use `smspva` for this, so yeah. Try to avoid global `except`'s when possible, too.

**Comment by ZombieTheBest** [comment]
@Lonami As I told you, pretty new to python. How should i write a good exception handler? Thanks for your time

**Comment by Lonami** [comment]
```python
from telethon.errors import PhoneCodeInvalidError
...
    except PhoneCodeInvalidError:
```

**Comment by ZombieTheBest** [comment]
@Lonami Thanks!

**Comment by fakkoweb** [comment]
Might be a VERY stupid question, but reading through Telethon guide I could not understand this: even obfuscating it, how can you get in the python script the confirmation code sent through telegram if you have not yet completed the authentication process you are trying to finalize?
It is truly not clear to me from the docs

**Comment by SmartManoj** [comment]
> How should i obfuscate the code?

Tested code+0 Passed

**Comment by admin0406** [comment]
> @Lonami Thanks again.
> 
> ```
> number = get_number()
> if number[0] != -1:
>     print("ID: {}  |  Number: {}".format(number[0], number[1]))
>     try:
>         client = TelegramClient(number[1], api_id, api_hash)
>         assert client.connect()
>         client.send_code_request(number[1])
>     except Exception as e:
>         print(e)
>         ban_number(number[0])
>         sys,exit(1)
> 
> time.sleep(5)
> code = check_sms(number[0])
> if code != -1:
>     print("Got Code: {}".format(code))
>     myself = client.sign_up(number[1], input('Enter the Code: '))
> else:
>     print("Error getting confirmation code.")
> ```
> 
> This is my code, where number[1] contains the phone number and number[0] contains a smspva ID.
> 
> The code is returned in the check_sms function, with this return
> 
> ```
>  if j['response'] == '1':
>             return j['sms']
> ```
> 
> How should i obfuscate the code? I'm asking because every number I use i'm paying about 0.10$... and done many tests ahahah
> Open a issue here was my last resort
> 
> EDIT: Yes i've used this library with other phone numbers and was working great

hi  
I have encountered the same problem as you, but I don't know how to solve it. Where is your check_sms() imported?

**Comment by SmartManoj** [comment]
> Might be a VERY stupid question, but reading through Telethon guide I could not understand this: even obfuscating it, how can you get in the python script the confirmation code sent through telegram if you have not yet completed the authentication process you are trying to finalize?
> It is truly not clear to me from the docs

You only to obfuscate when you send the code over Telegram.

**Comment by ubuygold** [comment]
If you are still there.
I ve got a similar problem. I dont input the code got from online sms manually, but use client.sign_up(code). When I do this, it turns out"invalid code". But when I use client.start(), and get a code from the same online sms site, it turns out ok. Could you tell me what happens if you are still there. Thank you.

**Comment by SmartManoj** [comment]
> I thought that smspva was selling unused phone numbers, but apparently they are selling already-activated telegram account. Thats why sign_up was not working.

**Comment by ubuygold** [comment]
> > I thought that smspva was selling unused phone numbers, but apparently they are selling already-activated telegram account. Thats why sign_up was not working.

Not really, I tried the numbers via start() method and it works and signed up a totally new account, it just didnt work when I use sign_up method.

**Comment by captainluzik** [comment]
So maybe a respected developer @Lonami  will give an example of code that eliminates this error?

**Comment by captainluzik** [comment]
Because the start () method works, but does not fit tasks for the bot

**Comment by Lonami** [comment]
`start` already supports enough callbacks to fit virtually any scenario. Furthermore you can copy its source code and adapt it to your needs and it will work exactly the same.

**Comment by captainluzik** [comment]
why can't the sign_up () method be fixed so that the telegram perceives the code as correct?

**Comment by Lonami** [comment]
If you think the friendly methods are working incorrectly, I encourage you to use the raw API calls yourself. If it doesn't work, then you will see there is nothing to fix because that's how Telegram works.

**Comment by VarunChilukuri** [comment]
Hi @Lonami, 

I hope you don't think this is too much of a bother, but I was wondering if you could clarify how I would obfuscate the code, as I'm still unable to understand what you mean by reading this thread. Here's a rough idea of what I'm trying to achieve: User enters phone -> I store their email -> they input the code they received -> I use the code to log in. I'm trying to do this _without_ having to enter anything into the terminal, since I want it to be all automatic and require no intervention from me.

Thanks!
