### ISSUE TITLE
InputFetchFailError when sending a message

### ISSUE THREAD

**Issue by Mohammadwh** [LonamiWebs/Telethon#767]
hello
i use get message method and return this error:
Failed deserializing TL payload

**Comment by Lonami** [comment]
1. Post the code that caused this issue.
2. Post `logging.DEBUG`'s output.

**Comment by Mohammadwh** [comment]
if text == 'setsudo' and msg.message.reply_to_msg_id and is_ownerbot(msg):
					id = [int(msg.message.reply_to_msg_id)]
					p = bot(GetMessagesRequest(msg.message.to_id.channel_id,id))
					if db.sismember('bot{}:sudos:'.format(botnumber),p.users[0].id):
						bot.send_message(msg.message.to_id.channel_id,'• کاربر <a href="tg://user?id={}">{}</a> در لیست سودو ها وجود دارد!'.format(p.users[0].id,p.users[0].id), reply_to=msg.message.id, link_preview=True,clear_draft=False, parse_mode='html')
					else:
						db.sadd('bot{}:sudos:'.format(botnumber),p.users[0].id)
						bot.send_message(msg.message.to_id.channel_id,'• کاربر <a href="tg://user?id={}">{}</a> به لیست سودو ها اضافه گردید!'.format(p.users[0].id,p.users[0].id), reply_to=msg.message.id, link_preview=True,clear_draft=False, parse_mode='html')

**Comment by Mohammadwh** [comment]
here you are

**Comment by Lonami** [comment]
Now can you post the full error message too like I said?

**Comment by Mohammadwh** [comment]
"Failed deserializing TL payload" its full error :(

**Comment by Lonami** [comment]
I asked more people and apparently it might happen when the request is invalid. Are you sure you passed the right parameter types everywhere?
