### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by maxim-smirnov** [LonamiWebs/Telethon#772]
I'm trying to disable telethon logger with:
`logging.getLogger('telethon').setLevel(level=logging.CRITICAL)`

But with no luck, telethon is sending ERROR level messages, like:
`ERROR: Number of retries reached 0 for ['GetStateRequest'].`

**Comment by Lonami** [comment]
I ran the following:
```python
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('telethon').setLevel(logging.CRITICAL)
```

And it works just fine. Make sure you didn't misspell the name. [More projects](https://github.com/expectocode/telegram-export/blob/33fc2191ee37218d9c07a394eea8e2eb0c530db3/telegram_export/__main__.py#L87) do that and it works just fine.

**Comment by maxim-smirnov** [comment]
I am running with (`info` by default): 
```python
if arguments['logging'] == 'debug':
    logging.basicConfig(level=logging.DEBUG, format=LOGGING_FORMAT)
elif arguments['logging'] == 'warning':
    logging.basicConfig(level=logging.WARNING, format=LOGGING_FORMAT)
elif arguments['logging'] == 'error':
    logging.basicConfig(level=logging.ERROR, format=LOGGING_FORMAT)
else:
    logging.basicConfig(level=logging.INFO, format=LOGGING_FORMAT)

logging.getLogger('telethon').setLevel(level=logging.CRITICAL)
```
With such setup telethon's logger is printing errors, but I don't want to get any error from telethon, what should I do?
