### ISSUE TITLE
Insert: aggressive=True

### ISSUE THREAD

**Issue by lybimiy86** [LonamiWebs/Telethon#773]
Friends, in which part of the code insert: aggressive=True ?
`participants = client.invoke(GetParticipantsRequest( channel, ChannelParticipantsSearch(''), offset, limit, hash=0 ))`
Where I put it, it gives an error: TypeError: call() got an unexpected keyword argument 'aggressive'
Version: 0.18.2.3

**Comment by AnvarKhan** [comment]
why client.get_participants(target_group, aggressive=True) not working?

**Comment by daveusa31** [comment]
> why client.get_participants(target_group, aggressive=True) not working?

https://github.com/LonamiWebs/Telethon/issues/3709#issuecomment-1032615229

**Comment by Creampanda** [comment]
I have solved this problem guys
/lib/python3.8/site-packages/telethon/client/chats.py 
```
    async def _load_next_chunk(self):
        import time
        time.sleep(32)
```
add sleep method between loading chunks
and change max chunk size in same file (i make 2000 and it worked for me)
`_MAX_PARTICIPANTS_CHUNK_SIZE = 2000`

**Comment by daveusa31** [comment]
> I have solved this problem guys /lib/python3.8/site-packages/telethon/client/chats.py
> 
> ```
>     async def _load_next_chunk(self):
>         import time
>         time.sleep(32)
> ```
> 
> add sleep method between loading chunks and change max chunk size in same file (i make 2000 and it worked for me) `_MAX_PARTICIPANTS_CHUNK_SIZE = 2000`

Yes. It worked for me, thanks.
I did it with a stop in 29 seconds. I tried to reduce it - errors flew out

And yes, it's better to use ```await asyncio.sleep```, so as not to block the entire stream

**Comment by iliman99** [comment]
Could you please share the entire code
