### ISSUE TITLE
How to forward message with reply?

### ISSUE THREAD

**Issue by overjoy** [LonamiWebs/Telethon#774]
Hello. Is it possible to forward a reply? Right now if I forward message with reply between channels the citation is lost. How to retain it? I tried client.send_message(reply_to=...) and MessageEvent.forward() with no luck.

Alternatively, is there any way to mirror channel content without forwarding?

**Comment by Lonami** [comment]
Just `send_message` with the `Message` itself, not the text.

**Comment by Lonami** [comment]
Wait, I read now. Preserving replies is harder. The IDs of the messages are probably different, so of course it won't just work. You need to save the ID of the original message and the ID of the saved one. Then when you forward a reply figure out which to reply on your "local" channel.

**Comment by overjoy** [comment]
Do you mean "reply_to" argument in client.send_message() ? I tried to pass it integers and message object from MessageEvent.reply_message but can't get the citation. Only the message body is sent.

**Comment by Lonami** [comment]
Like I said you'd need to save original + new IDs and when forwarding something with a reply go from original reply -> saved ID. Maybe ask in [@TelethonChat](https://t.me/telethonchat).

**Comment by overjoy** [comment]
I get the citation when I send raw text, but not when send message object from update event. What could cause that?
```
client.send_message(target, 'some message', reply_to=51506) # citation is present
client.send_message(target, msg_object, reply_to=51506) # no citation
```
I tried to change `reply_to_msg_id` property but no result.

**Comment by yikes101** [comment]
Hi there, I was wondering could you get it to work?

**Comment by NilanjPatel** [comment]
hello @overjoy have you succeeded with replay_to_id?

**Comment by Roobahist** [comment]
> Wait, I read now. Preserving replies is harder. The IDs of the messages are probably different, so of course it won't just work. You need to save the ID of the original message and the ID of the saved one. Then when you forward a reply figure out which to reply on your "local" channel.

isn't there any better ways to do that? how can i get message id after forwarding in my local channel?

**Comment by maerco** [comment]
Why this has been closed? 
the forward with replay to is also the only way to forward into a specific topic of a group, isn't it?

**Comment by Lonami** [comment]
Topics were not a thing when this was closed. Raw API can be used for that functionality until it's added to the friendly method.
