### ISSUE TITLE
BIG QUESTION

### ISSUE THREAD

**Issue by luv-huynq2** [LonamiWebs/Telethon#776]
How can i send message in to the channel ? i can't use method inputchannel

**Comment by Lonami** [comment]
Or ask in StackOverflow, this is not the place for these questions. This is for *issues* with the library (although I'm okay with questions about "complicated" API queries). Sending a message is literally in the `README`.

**Comment by luv-huynq2** [comment]
Ok . thanks

**Comment by xypnox** [comment]
Pretty damn big question indeed. :clap:
