### ISSUE TITLE
Revert handling AUTH_KEY_DUPLICATED

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#777]
Relevant commit: https://github.com/LonamiWebs/Telethon/commit/500792975e3a3e42192d544da7ac67c452d78b17

Original submitter: @christosR.

I'd like to discuss this further so we can come with a good solution for everyone. Reverting the commit would be really straightforward but perhaps together we can come up with a better solution.

**Comment by christosR** [comment]
I noticed that after upgrading to 18.2 my clients were getting logged out very often and seeing in the logs this `DUP_AUTH_KEY` error.  I downgraded to 18.0 and my clients now are logged in for days. The comment in the commit was mostly for me to understand what was the reason about it? I probably won't be able today to test again with the 18.2 version will try to squeeze it in at the end of the day

**Comment by Lonami** [comment]
Before this commit it would `raise RPCError` instead the (now existing) `AuthKeyError`, which I can more easily catch. So if it raised that I'm not sure how your program could keep running? Or even be logged in? It's an error with the auth_key… I'm just not sure what the right code flow should be.

**Comment by christosR** [comment]
yes but before that you didn't nullify the auth key right? `self.session.auth_key = None`

**Comment by Lonami** [comment]
Right. But if the auth key is duplicated isn't the best behaviour to clear it so it's a new clean one that's not duplicated? I thought the error meant that the auth key wouldn't work and a new one would be needed. Probably not the right guess. So retrying should work you say?

**Comment by christosR** [comment]
retry was working ok for me, didn't had issues before.

**Comment by Lonami** [comment]
Alright, so the fix should just be to remove the line that sets it to `None` and just retry. If you could test that out first would you like to make a pull request?

**Comment by christosR** [comment]
ok I will try and do that and leave it running for the weekend and see what happens

**Comment by Lonami** [comment]
Bump.

**Comment by Lonami** [comment]
See https://github.com/zhukov/webogram/issues/1674 and https://waffle.io/zhukov/webogram/cards/5ad45a3ec89ef5001bc3a504. Ping @stek29 and @delivrance for providing the respective links.

**Comment by vegeta1k95** [comment]
SInce some recent update I've started to recieve some strange error behavior:
Somehow AUTH_KEY_DUPLICATED error becomes RECURSIVE and raises itself until Python tells me that it has reached maximum level of recursion and then ij just shuts down.

Something like this:
``` python
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 217, in connect
    self.sync_updates()
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 636, in sync_updates
    self.updates.process(self(GetStateRequest()))
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 486, in __call__
    result = self._invoke(call_receive, request, ordered=ordered)
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 583, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_base_errors.AuthKeyError: AUTH_KEY_DUPLICATED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 217, in connect
    self.sync_updates()
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 636, in sync_updates
    self.updates.process(self(GetStateRequest()))
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 486, in __call__
    result = self._invoke(call_receive, request, ordered=ordered)
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 583, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_base_errors.AuthKeyError: AUTH_KEY_DUPLICATED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 217, in connect
    self.sync_updates()
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 636, in sync_updates
    self.updates.process(self(GetStateRequest()))
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 486, in __call__
    result = self._invoke(call_receive, request, ordered=ordered)
  File "C:\Python\lib\site-packages\telethon\telegram_bare_client.py", line 583, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_base_errors.AuthKeyError: AUTH_KEY_DUPLICATED

During handling of the above exception, another exception occurred:
...
```
and so on.  The worst thing is that I can't catch this error properly or stop the recursion from outisde of the client code.

**Comment by Lonami** [comment]
We can revisit this issue after [`core-rewrite`](https://github.com/LonamiWebs/Telethon/tree/core-rewrite) gets merged, which should be soon.

**Comment by vegeta1k95** [comment]
@Lonami 
Is there any hotfix that I can apply right now to stop recursion / ignore this error?

**Comment by Lonami** [comment]
Well the line is this one:
https://github.com/LonamiWebs/Telethon/blob/0418f7e37553b167786b40d6554eda4e2cfe9152/telethon/telegram_bare_client.py#L583

I guess you could fork, modify somewhere there, and install your fork for now.

**Comment by Lonami** [comment]
@vegeta1k95 you could also use an older, working version.

**Comment by mike-johnson-jr** [comment]
I'm getting this error as well, `AUTH_KEY_DUPLICATED`, client used to work fine, now I can't login (`client.start`)

**Comment by Lonami** [comment]
Closing, not handled in master anymore. The update hasn't been pushed to PyPi yet.
