### ISSUE TITLE
CheckPhoneRequest() always phone_registered=True

### ISSUE THREAD

**Issue by maxim-smirnov** [LonamiWebs/Telethon#778]
It doesn't matter what value I pass to the `CheckPhoneRequest()`, it always returns `phone_registered=True`.

May be it's an API error, can someone check it?

**Comment by Lonami** [comment]
Maybe the phones really are registered and their accounts exist?

**Comment by maxim-smirnov** [comment]
I just passed `phone_number='0'`.
It doesn't seem like this phone is registered...

**Comment by Lonami** [comment]
Throw garbage at a program, it will throw garbage back. Perhaps try with *legit* phone numbers. Or perhaps `'0'` is really registered for internal tests. Or perhaps they return `true` for invalid ones.

**Comment by maxim-smirnov** [comment]
With invalid was it must raise `PhoneNumberInvalidError`. I've tried with phones which doesn't registered. No luck, `CheckPhoneRequest()` returns `True`.

**Comment by maxim-smirnov** [comment]
Here is the result for `'0'`:

```python
client.invoke(CheckPhoneRequest(phone_number='0'))
```
`CheckedPhone(phone_registered=True)`

```python
client.send_code_request(phone='0')
```
`telethon.errors.rpc_error_list.PhoneNumberInvalidError: The phone number is invalid`

**Comment by Lonami** [comment]
Closing since this is not something I can do anything about. It's just Telegram's response.
