### ISSUE TITLE
How do you check if user has group invite from friends only from the User object.

### ISSUE THREAD

**Issue by Jinqad** [LonamiWebs/Telethon#779]
Couldn't find this documented so maybe you'd know.
When adding a member how do you know they don't have the friends only option enabled here - 
https://i.imgur.com/0tjvDRV.png

So how do i know about that?
```
User(id=, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=False, bot_chat_history=False, bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False, access_hash=, first_name='', last_name='', username='', phone=None, photo=UserProfilePhoto(photo_id=, photo_small=FileLocation(dc_id=, volume_id=, local_id=, secret=-), photo_big=FileLocation(dc_id=, volume_id=, local_id=, secret=)), status=UserStatusOnline(expires=datetime.utcfromtimestamp()), bot_info_version=None, restriction_reason=None, bot_inline_placeholder=None, lang_code=None)
```

**Comment by Lonami** [comment]
Maybe https://lonamiwebs.github.io/Telethon/constructors/user_full.html. Maybe https://lonamiwebs.github.io/Telethon/methods/account/get_notify_settings.html. Try looking there for relevant keywords until you find it as I don't really know.
