### ISSUE TITLE
Send a message using an inline bot

### ISSUE THREAD

**Issue by hamid07ss** [LonamiWebs/Telethon#780]
@Lonami 

can i send a message using an inline bot?
like: `@Linksazibot test`

i use:
```
        t = self.client(GetInlineBotResultsRequest('@Linksazibot', '@hamid_sarani', '', '0'))
        self.client(SendInlineBotResultRequest(
            '@hamid_sarani',
            t.query_id,
            t.results[0].id
        ))
```

bot i get: `The inline query expired`

**Comment by Lonami** [comment]
It would be nice if you told us how you solved the issue.

**Comment by Jerry981028** [comment]
@Lonami I'm getting same error.
`mybot = client.get_entity('mybot')
mychat = client.get_entity('whatever')
def inline_query():
    bot_results = client(GetInlineBotResultsRequest(
        mybot, mychat, '', ''
    ))
    if bot_results.results:
        query_id = bot_results.query_id
        # choose a result from the list
        result_id = getResultId(bot_results.results)
        client(SendInlineBotResultRequest(
            mychat,
            query_id,
            result_id
        ))
        return True

    else:
        print(bot_results)
    return None`
However, I'm always getting telethon.errors.rpc_error_list.InlineResultExpiredError : The inline query expired

**Comment by Jerry981028** [comment]
I've tried using the Telegram App, which had no problem sending the inline query.

**Comment by Lonami** [comment]
@Jerry981028 the library is raising an `RPCError` which means Telegram responded but *you* are doing something wrong.

**Comment by Lonami** [comment]
Good there's nothing to fix from my side.
