### ISSUE TITLE
How to add users to Channel?

### ISSUE THREAD

**Issue by mowshon** [LonamiWebs/Telethon#781]
Hello!

I have a list of usernames `@user_one, @user_two` and my personal public channel.
How can I add automaticaly users to channel with telethon-api ?

**Comment by Lonami** [comment]
@mowshon what have you tried?

**Comment by mowshon** [comment]
@Lonami 

```python
from telethon import TelegramClient

api_id = 000000
api_hash = 'c111111111111111111111b'

client = TelegramClient('session_name', api_id, api_hash)
client.start()

user = client.get_entity('user_one')
channel = client.get_entity('my_channel')

# Profit ???
```

I didn't find some examples of adding users to channel.

**Comment by Lonami** [comment]
You might want to read http://telethon.readthedocs.io/en/latest/extra/advanced-usage/accessing-the-full-api.html.

**Comment by mowshon** [comment]
@Lonami sorry for silly question)) 
This is working code for me.

```python
from telethon import TelegramClient
from telethon.tl.functions.channels import InviteToChannelRequest

api_id = 00000
api_hash = 'c11111111111111111111111b'

client = TelegramClient('session_name', api_id, api_hash)
client.start()

user = client.get_entity('user_login')
channel = client.get_entity('your_channel')

# Add users.
result = client(InviteToChannelRequest(
    channel,
    [user]
))
```

**Comment by ImTheDeveloper** [comment]
Sorry to comment on a closed issue. 

Does anyone know the limit on the number of users that can be added? I'm migrating 6000 users from my current channel to merge with another I own. I've tried batching as well as the full amount but I'm currently sat blocked by Telegram because of such efforts. I can't see anywhere mentioning a limit nor sensible wait time between batches

**Comment by mowshon** [comment]
@ImTheDeveloper you need to test. But I think if you will add all users from one account, telegram will block you for some period of time and each time will increase this period.

**Comment by ozdav** [comment]
@mowshon 
I tried same as you did `InviteToChannelRequest`
But I am getting response 
updates = []
users = []
Can you please help me?

**Comment by amir1379** [comment]
i have that problem too
