### ISSUE TITLE
No module named 'telethon.tl.types.input_peer_chat'

### ISSUE THREAD

**Issue by tomillo** [LonamiWebs/Telethon#785]
Hello! How can i fix this?

`$ python3 telegram_scrypt.py
Traceback (most recent call last):
  File "telegram_exporter.py", line 6, in <module>
    from telethon.tl.types.input_peer_chat import InputPeerChat
ModuleNotFoundError: No module named 'telethon.tl.types.input_peer_chat'`

**Comment by Lonami** [comment]
You don't. That never existed.

**Comment by Lonami** [comment]
Actually, it did, but long ago.

**Comment by tomillo** [comment]
I know, i take the script from https://stackoverflow.com/questions/44467293/how-can-i-download-the-chat-history-of-a-group-in-telegram

**Comment by Lonami** [comment]
The correct code is now `from telethon.tl.types import InputPeerChat`.

**Comment by tomillo** [comment]
Thank you Lonami. Last error:
`Traceback (most recent call last):
  File "telegram_exporter.py", line 12, in <module>
    total_count, messages, senders = client.get_message(chat, limit=10)
AttributeError: 'TelegramClient' object has no attribute 'get_message'`
