### ISSUE TITLE
Download Video or Photos ONLY?

### ISSUE THREAD

**Issue by chriskwanmy** [LonamiWebs/Telethon#786]
Is there any method I can apply for the get_messages() api to download the specific type of media(vdo/photo)?

thanks

**Comment by Lonami** [comment]
You can do the `isinstance(msg.media, ...)` yourself.

**Comment by chriskwanmy** [comment]
`from telethon import TelegramClient
    
api_id=270754
api_hash='b81af5ee42b3fa1c7759711c0c394dab'
client = TelegramClient('test_session', api_id, api_hash)
client.start()
for message in client.get_messages('https://t.me/joinchat/CS4FMEC5fhsz2RcDOt7M_w', limit=500):
    if isinstance(message.media, DocumentAttributeVideo):
        client.download_media(message)`

I tried this but fail.
Am i wrong?

**Comment by dnslin** [comment]
After trying isinstance() I found that some image files are also considered MessageMediaDocument in telethon, so I can't download just one type of file e.g. mkv? avi? mp4? Looking forward to your reply

**Comment by Lonami** [comment]
Photos sent uncompressed will be documents. You can check the `message.file.mime_type` instead.
