### ISSUE TITLE
How to get all messages from result (now get only 100 messages)

### ISSUE THREAD

**Issue by aakorzhenko** [LonamiWebs/Telethon#787]
Hello! 
I use method `SearchRequest` for get history from the channel. 
I use exampe from http://telethon.readthedocs.io/en/latest/extra/examples/working-with-messages.html?highlight=SearchRequest 
And I change limit for 1000.
`filter = InputMessagesFilterEmpty()
result = client(SearchRequest(
    peer='@***',      # On which chat/conversation
    q='***',      # What to search for
    filter=filter,  # Filter to use (maybe filter for media)
    min_date=datetime(2017, 6, 1, 0, 0, 1 ),  # Minimum date
    max_date=datetime(2018, 3, 31, 23, 59, 59),  # Maximum date
    offset_id=0,    # ID of the message to use as offset
    add_offset=0,   # Additional offset
    limit=1000,       # How many results 
    max_id=0,       # Maximum message ID
    min_id=0,       # Minimum message ID
    from_id=None    # Who must have sent the message (peer)
))`

I get `result.count = 313` but when I check `len(result.messages) = 100` only 100! :(
There is a strict limit?

And another question.
Where can I get description of metadata? I have not found in wiwki https://lonamiwebs.github.io/Telethon/index.html 

I use `result.__dict__.keys()` for understanding attributes. I did not find the description of result. Can you please tell me where I can to find it?

THANKS!

**Comment by Lonami** [comment]
Telegram has a hard limit of 100. No matter how big the limit you put there is, it will just return 100. The `master` branch has updated `.get_messages` with support for a `from_peer` parameter. You can install the library from `git` to get these changes by using `pip install --upgrade git+https://github.com/LonamiWebs/Telethon@master`.

**Comment by Lonami** [comment]
https://lonamiwebs.github.io/Telethon/index.html is not a wiki, you should read http://telethon.readthedocs.io/en/latest/extra/advanced-usage/accessing-the-full-api.html. Using `result.__dict__.keys()` is rather weird as you can print the result to achieve the same effect (or read the `Members` section).

**Comment by anneta01** [comment]
Ok, thanks a lot!)
Where can i read the `Members` section?

**Comment by Lonami** [comment]
![image](https://user-images.githubusercontent.com/6297805/39302366-affc1fcc-4952-11e8-8117-058f0cc8b6b4.png)

**Comment by anneta01** [comment]
Ok, thank you!
