### ISSUE TITLE
ImportContactsRequest does not work anymore

### ISSUE THREAD

**Issue by kaxap** [LonamiWebs/Telethon#788]
Hi, I am using telethon-0.18.3

`ImportContactsRequest` worked well a week ago, but now it seems like it doesn't work properly anymore.

```python3
contacts = [InputPhoneContact(client_id=random_id, phone=phone_number_with_telegram_account, first_name="John", last_name="Doe")]

response: ImportedContacts = client.invoke(ImportContactsRequest(contacts))
print(len(response.imported)) # prints 0
```

I've tried importing different contacts, logging in from different accounts, as well as with different api_id and api_hash. Absolutely new accounts with empty contact list can import 5 contacts at best.

Tbh, it seems like more of a Telegram issue than a Telethon issue. But I am not sure.

**Comment by Lonami** [comment]
> Tbh, it seems like more of a Telegram issue than a Telethon issue

That seems to be the case, sadly. You're invoking a raw request and the library does no modification to those (besides casting everything to the required types so that the request works), so what you see is what Telegram is doing. Does adding a contact work through official applications?

**Comment by kaxap** [comment]
Used official android app and successfully added 8 contacts one by one.
Also I have imported couple of thousands contacts to an android emulator and installed Telegram APK. None of them were imported into Official Telegram App. 

![image](https://user-images.githubusercontent.com/2851970/39359072-404f68b2-4a3a-11e8-900f-f34f488209c5.png)

Looks like they disabled mass contact import. 

Btw, does API have a singular import method?

**Comment by Lonami** [comment]
Nope, only multiple at once. Guess it's commonly used when you add a new phone and want to import all the contacts in it.

**Comment by Lonami** [comment]
`contacts.importContacts` is [as old as the first layer](https://github.com/stek29/tl-schema/blob/2862b4e08dc6d523f12b082260fcd5d2d78bb5bc/l001/schema.tl#L210).

**Comment by Lonami** [comment]
Nothing much we can do about it sorry. Closing.

**Comment by kirushkomanowar** [comment]
Hello! please help? I have a problem with result = client.invoke
something like 

AttributeError: 'TelegramClient' object has no attribute 'invoke'

**Comment by kirushkomanowar** [comment]
> Hello! please help, I have a problem with result = client.invoke
> something like
> 
> AttributeError: 'TelegramClient' object has no attribute 'invoke'

reason- old telethon, thank to all

 *facepalm*
