### ISSUE TITLE
How to use specific/latest scheme.tl

### ISSUE THREAD

**Issue by mbande** [LonamiWebs/Telethon#789]
hello
I want this to stay up to date with telegram latest app API as they publish.
I checked android/web telegram repositories and can not find any "scheme.tl" in them
is there any official place that publishes them? how official apps use them?

**Comment by Lonami** [comment]
* [tdesktop](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl)
* [webogram](https://github.com/zhukov/webogram/blob/master/app/js/lib/schema.tl)
* [tdlib](https://github.com/tdlib/td/tree/master/td/generate/scheme)

I can't find DrKLO Android's, although they hardly publish the source code anyway. Telegram Desktop and Webogram also might lag behind mobile clients, so the schema is often *older* than what the library uses.

You can also refer to @stek29's [great archive](https://github.com/stek29/tl-schema).

As an user, you shouldn't worry about this. I update the layer as soon as someone lets me know about a more recent, published version. [Unigram](https://github.com/UnigramDev/Unigram) used to have it before they switched to [tdlib](https://github.com/tdlib/td)

**Comment by Lonami** [comment]
Guess we can use `tdlib` from now on. See https://github.com/LonamiWebs/Telethon/commit/08dbc42718215de131b1f01a6996cfb68679fd0e.
