### ISSUE TITLE
How to get all media/files count for an entity?

### ISSUE THREAD

**Issue by ReS4** [LonamiWebs/Telethon#793]
Is There any api/method to get all media count in chats or channels or any entity?
One simple (or bad) way is iterate over messages, but is there any way to retreive all at once?
i mean these:
![entity](https://user-images.githubusercontent.com/6023799/39545427-ba6425de-4e40-11e8-9abd-bd66c53d901f.PNG)

**Comment by Lonami** [comment]
[Questions don't belong here.](https://raw.githubusercontent.com/LonamiWebs/Telethon/master/.github/ISSUE_TEMPLATE.md)

**Comment by snowman** [comment]
```python
messages = client.get_messages(name, 0, filter=types.InputMessagesFilterPhotos)
print(messages.total)
```
