### ISSUE TITLE
TelegramClient get_dialogs(limit=None) problem

### ISSUE THREAD

**Issue by Kosat** [LonamiWebs/Telethon#794]
Hello,
In my code I'm using Telethon v0.17

The below call to `get_dialogs` works perfectly well on my two machines.
```
dialogs = self.get_dialogs(limit=None)
```

However, the other person complained that on his machine (Windows OS) it doesn't. 
Below is the log from his machine:
![error_img](https://user-images.githubusercontent.com/18563504/39625789-79e5b1d6-4f75-11e8-8903-852898b08af6.PNG)

This is not a network connectivity issue. It happens all the times he runs it, on any channel/dialogue.

Please advise.

**Comment by Lonami** [comment]
Looks like they have an insane amount of dialogs and it needs a lot of calls. Depending on their physical location or phone number I feel like the flood waits are more severe (but the library didn't crash and succeeded, by sleeping automatically as much as needed). They can use `print(client.get_dialogs(0).total)` to see how many they have. They will need `(total + 99) // 100` requests.

**Comment by Lonami** [comment]
Consider upgrading. We're on `0.18.3`.
