### ISSUE TITLE
how to bring the session into a format for the web

### ISSUE THREAD

**Issue by GoldenEagle66** [LonamiWebs/Telethon#795]
how to bring the session into a format for a web view:
`{
    "dc2_auth_key": "b8ff0cb033408d951490161e7fbe6d2.....",
    "dc2_server_salt": "8838c378338699ee",
    "dc": 2,
    "dc4_auth_key": "141dd51313c8ef8ca974fecf9ddcf........",
    "dc4_server_salt": "da533535cd0708aa"
}`

**Comment by Lonami** [comment]
#742, #316.

**Comment by GoldenEagle66** [comment]
@Lonami in these topics, the task per revolution
