### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by PanderMusubi** [LonamiWebs/Telethon#796]
Please, add the following to the documentation. Before running

    sudo pip3 install telethon

on Ubuntu 18.04, one can run

    sudo apt-get install python3-pyasn1 python3-rsa

This takes care of the dependencies in a more global approach.

**Comment by Lonami** [comment]
`pip3` should by itself install the dependencies. Not sure what you mean by "more global approach". With `sudo` it already installs for everyone.

**Comment by PanderMusubi** [comment]
To avoid having double installation of these libs. Not that it causes functional errors, but if one has installed these libs already via your OS, pip doesn't need to install them.
