### ISSUE TITLE
Getting dialog by channel id

### ISSUE THREAD

**Issue by Kosat** [LonamiWebs/Telethon#797]
Hi,

Is it possible to **get the Dialog object knowing _only_ its channelId** (with or without access_hash) ???

For example, given that I have 10 dialogues, I'd like to fetch only the 5'th Dialogue object knowing only its ChannelID=-1001088908272.

I've tried to do something like that but it doesn't work for me
```
peer = self.get_entity(PeerChannel(-1001088908272))
self.get_dialogs(limit=1, offset_peer=peer)
```

NOTE1: I don't need the whole Dialog object actually, the InputPeer corresponding to that dialog would be enough.
NOTE2: By __get the Dialog object__ I actually mean fetching it from server, not just finding it in a local cache.

Thanks.

**Comment by Lonami** [comment]
No, you need the hash.
