### ISSUE TITLE
The key is not registered in the system

### ISSUE THREAD

**Issue by masoudcom** [LonamiWebs/Telethon#798]
Hi.
I have 2 session, one telegram desktop and other telethon. after 1 day telethon get error `The key is not registered in the system`. i must re login :(.
Can I help me?

**Comment by Lonami** [comment]
You need to give more information.

**Comment by masoudcom** [comment]
File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 459, in __call__
    result = self._invoke(call_receive, *requests)
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_bare_client.py", line 551, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.AuthKeyUnregisteredError: The key is not registered in the system

**Comment by Lonami** [comment]
Alright well. Maybe you haven't logged in? I haven't seen the code.

**Comment by masoudcom** [comment]
Already registered but after 1 or 2 days throw error.

**Comment by Lonami** [comment]
Well unless I see the code I can't do much.
