### ISSUE TITLE
client.idle() and set_update_state

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#807]
I think there is a little incompatibility with client.idle() and set_update_state... because usually when someone use client.idle(), when she want to exit, she will terminate it and on termination there is no way to disconnect from server in regular way. So the state remains unchanged.

**Comment by Lonami** [comment]
Sending a <kbd>Ctrl+C</kbd> signal will gracefully stop the loop and call `disconnect`, which calls `set_update_state`.

**Comment by hnikaein** [comment]
Correct, but in case of SIGKILL, there is no chance for it...

**Comment by Lonami** [comment]
I wouldn't like to make a commit to sqlite for *every* incoming update. That feels slow. Any ideas?

**Comment by hnikaein** [comment]
1) I think it would not be that slow. Anyway you can put a flag for it, so user can decide for it (for example in client.idle method)
2) Write a method that correct state after a kill. user should call this method by herself.

**Comment by Lonami** [comment]
1. Calling `.commit()` is *really* slow using builtin's sqlite. I've had this issue in [telegram-export](https://github.com/expectocode/telegram-export/) where calling `.commit()` for 100 messages downloaded as fast as possible would make it take like 2-3 seconds, whereas it takes somewhere close to 0.1s if you just make the insert query.
2. You can pass any termination signals to `.idle()` just like in [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot), including `SIGKILL`. Also, if you handle the `SIGKILL` yourself, you can also gracefully `.disconnect()`.

**Comment by hnikaein** [comment]
2. In some situation you can't handle it. For example I think in windows there is no way to handle it. With this way I meant writing a method which user call it after running the client after the KILL.

**Comment by Lonami** [comment]
How would you call it after killing it if the problem to begin with is that the information hasn't been saved? ^^

**Comment by hnikaein** [comment]
Ok, what about log file and recovering from it?

**Comment by Lonami** [comment]
I really would rather just keep the `.session` file. We could insert on every update but commit every minute or so. Not sure what the best way to do this is, really.

**Comment by hnikaein** [comment]
That would make inconsistency.

**Comment by Lonami** [comment]
So do you suggest a minimal companion file `session_name.state` that gets saved every time and doesn't have to go through sqlite? But then I need to worry about its format and upgrades too.

**Comment by hnikaein** [comment]
Yes... And you are right... We will have a lot of trouble about its format...
Anyway, we don't need anything special for saving files. We should just flush it.

**Comment by Lonami** [comment]
Things have changed quite a bit, update state is currently not persisted. After some discussion it should only be kept in memory to detect holes, not to fetch updates after long disconnected periods.
