### ISSUE TITLE
AuthKeyUnregisteredError: The key is not registered in the system

### ISSUE THREAD

**Issue by EgorXor** [LonamiWebs/Telethon#814]
how to use client after sign_up?
 i am trying to make auto-registrator
1)sign_up:

```
api_id ='id from another account'
api_hash = 'api_hash from another account'
client = TelegramClient('test', api_id, api_hash)
client.connect()
number='***'
client.send_code_request(number)
code=input('Enter code: ')
client.sign_up(code, 'name', 'surname')
```
here i am using selenium to get new api_id and api_hash fot this account:

```
driver.get("https://my.telegram.org/auth")
driver.find_element_by_id("my_login_phone").send_keys(number)
driver.find_element_by_tag_name("button").click()
sleep(2)
chat = InputPeerUser(777000, access_hash=0)
messages = client.get_messages(chat)
print('message with code',messages)
print(messages[0])
password = messages[0].message.split(":")[1].split("\n")[1].split("\n")[0]
```
here i get : `messages = client.get_messages(chat) `the following error :

```
invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)

telethon.errors.rpc_error_list.AuthKeyUnregisteredError: The key is not registered in the system
```
do i need to sign_in first ?
i am using sms -registrators so i have only one sms code

**Comment by Lonami** [comment]
1. make sure the session name is the same.
2. make sure you connect and sign in (or just start) the "second" client.

**Comment by EgorXor** [comment]
@Lonami  , thanks reply .
make sure you connect and sign in (or just start) the "second" client. - 
if i want to sign_in  or start second client   i need new api_id and  api_hash for this client right ?
its look like dead end. i can not get api_id and  api_hash  without code from telegram and cant 
get code witout api_id and  api_hash

**Comment by Lonami** [comment]
No, you can reuse the API ID and Hash. I'm just not sure what your code looks like or what you're trying to do but from what you've posted I think it's not Telethon's fault.

**Comment by EgorXor** [comment]
@Lonami , 
```
api_id ='id from another account'
api_hash = 'api_hash from another account'
client = TelegramClient('test', api_id, api_hash)
client.connect()
number='number of new account'
client.send_code_request(number)
code=input('Enter code: ')
client.sign_up(code, 'name', 'surname')
```
after this i want to read message from telegram 
`chat = InputPeerUser(777000, access_hash=0) `
and get: 
`telethon.errors.rpc_error_list.AuthKeyUnregisteredError: The key is not registered in the system`

**Comment by Lonami** [comment]
> after this i want to read message from telegram

I don't know what you mean by "after". You're posting pieces of the code, not all of it.

**Comment by EgorXor** [comment]
@Lonami ,full code
```
api_id =2***
api_hash = '***'

client = TelegramClient('new_workses', api_id, api_hash,update_workers=4,spawn_read_thread=False)

client.connect()

number='7****'

client.send_code_request(number)
code=input('Enter code: ')
print(code)
client.sign_up(code, 'name', 'surname')
print(client)
driver.get("https://my.telegram.org/auth")

driver.find_element_by_id("my_login_phone").send_keys(number)
driver.find_element_by_tag_name("button").click()
sleep(2)
chat = InputPeerUser(777000, access_hash=0)
messages = client.get_messages(chat)

telethon.errors.rpc_error_list.AuthKeyUnregisteredError: The key is not registered in the system
```

**Comment by SmartManoj** [comment]
```
def r(k=0):
	client2 = TelegramClient(sn, api_id, api_hash)
	if k:
		client2.start()
	else:
		client2.connect()
		client2.send_code_request(num)
		try:
			pass
			client2.sign_in(num, input('Enter code'))
		except Exception as e:
			print(e)
		client2.sign_in(password=pwd)

```

**Comment by sinarezaei** [comment]
I have the same issue,
I am using a DjangoSession to store the session from [django_telethon_session](https://github.com/sinarezaei/django-telethon-session) library. This piece of code is being called from a celery task.


This is the code:
**Code that causes the issue**
```python
from telethon.sync import TelegramClient
from django_telethon_session.sessions import DjangoSession
import asyncio

class TelethonHelper():
    def __init__(loop: asyncio.AbstractEventLoop)
        self.loop = loop

    async def get_client(self):
        self.client = TelegramClient(session=DjangoSession(), api_id=self.api_id, api_hash=self.api_hash, loop=self.loop)
        self.client.parse_mode = 'html'
        await self.client.connect()
        await self.client.start()
        dialogs = await self.client.get_dialogs()

...

```

**Traceback**
```
The key is not registered in the system (caused by GetDialogsRequest)
Trace: Traceback (most recent call last):
...
File "/src/telethon_helper.py", line 14, in get_client
File "/usr/local/lib/python3.7/site-packages/telethon/client/dialogs.py", line 250, in get_dialogs
   return await self.iter_dialogs(*args, **kwargs).collect()
 File "/usr/local/lib/python3.7/site-packages/telethon/requestiter.py", line 114, in collect
   async for message in self:
 File "/usr/local/lib/python3.7/site-packages/telethon/requestiter.py", line 75, in __anext__
   if await self._load_next_chunk():
 File "/usr/local/lib/python3.7/site-packages/telethon/client/dialogs.py", line 53, in _load_next_chunk
   r = await self.client(self.request)
 File "/usr/local/lib/python3.7/site-packages/telethon/client/users.py", line 74, in __call__
   result = await future
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system (caused by GetDialogsRequest)

```

**Comment by Lonami** [comment]
@sinarezaei I hadn't seen that session storage before. Does it also happen without it?

**Comment by sinarezaei** [comment]
I will test it with SQL session and let you know.

**Comment by quick-wq** [comment]
> I will test it with SQL session and let you know.

what's then?

**Comment by sinarezaei** [comment]
> > I will test it with SQL session and let you know.
> 
> what's then?

The issue was from django-telethon-session library. No it's fixed

**Comment by schattencheg** [comment]
Have the same issue!
But this code works fine on one PC (win) but does not on another!
```
from telethon import TelegramClient
import logging
logging.basicConfig(level=logging.DEBUG)

class TestClient(TelegramClient):
    def __init__(self):
        self.api_id = 'id'
        self.api_hash = 'hash'
        self.client = TelegramClient('session_name', self.api_id, self.api_hash)
        self.client.connect()
        dialogs = self.client.iter_dialogs()
        groups = [x for x in dialogs if x.is_group]
        channels = [x for x in dialogs if x.is_channel]
        print("Total groups {}, total channels {}".format(len(groups), len(channels)))

start_time = datetime.now()
client = TestClient()
```

I have two different errors in two different projects:
1. The key is not registered in the system (caused by GetDialogsRequest)
2. RuntimeWarning: coroutine 'TelegramBaseClient.connect' was never awaited self.client.connect()

I have no idea what to do next, **please help**.

**Comment by Metalymph** [comment]
Hi @schattencheg,
the answer is far late but, I'm new to this community: 
1. You have to sign in the user with the  `client.start()` method if you want to write at hand your credentials  from the console, or, call the `client.send_code_request(phone_number)` and then use the code received calling the `client.sign_in(phone_number, code)`.  Of course the `connect()` will guarantee the connection to the session data every time you start the app (unless the validation expires).
2. You need to call `connect()` with await since returns a coroutine. Everything here is an awaitable object.
