### ISSUE TITLE
get_messages cannot return a range

### ISSUE THREAD

**Issue by umaxfun** [LonamiWebs/Telethon#816]
When I use min_id and max_id to get a range of messages in the channel, nothing is returned.

```
telegram_client.get_messages(1315078272, min_id=1, max_id=100) # get range from 1 to 100
Out[2]: []
```

However, there is a message with the id of 100 and 99 and so on:
```
telegram_client.get_messages(1315078272, limit=1, offset_id=101)[0].id
Out[3]: 100

telegram_client.get_messages(1315078272, limit=1, offset_id=100)[0].id
Out[4]: 99
```

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/a076688fdc983714e584dfacf4432af32e5aab81

> ```python
> # Telegram doesn't like min_id/max_id. If these IDs are low enough
> # (starting from last_id - 100), the request will return nothing.
> #
> # We can emulate their behaviour locally by setting offset = max_id
> # and simply stopping once we hit a message with ID <= min_id.
> ```
