### ISSUE TITLE
how to use ipv6

### ISSUE THREAD

**Issue by GoldenEagle66** [LonamiWebs/Telethon#818]
how to use ipv6?
` if app.getOptionBox("proxytype") == "ipv6":
                        ipv6 = True
                        pr.connect((('[2001:67c:4e8:f002::a]', 443, 0, 0)))
                    else:
                        ipv6 = False
                    if app.getOptionBox("proxy") != "noproxy":
                        client = TelegramClient(dir + "/" + number, api_id, api_hash, proxy=pr,use_ipv6=ipv6)`
I try so, but does not work
is there a ready-made example?

**Comment by Lonami** [comment]
> but does not work

Not enough information and horrible issue formatting.

**Comment by GoldenEagle66** [comment]
@Lonami 
how to use ipv6?
I try so, but does not work 
```
 if app.getOptionBox("proxytype") == "ipv6":
                        ipv6 = True
                        pr.connect((('[2001:67c:4e8:f002::a]', 443, 0, 0)))
                    else:
                        ipv6 = False
                    if app.getOptionBox("proxy") != "noproxy":
                        client = TelegramClient(dir + "/" + number, api_id, api_hash, proxy=pr,use_ipv6=ipv6)
                    else:
                        client = TelegramClient(dir + "/" + number, api_id, api_hash)
                    client.connect()
```
returns response

> PySocks doesn't support IPv6: ('[2001:67c:4e8:f002::a]', 443, 0, 0)

is there a ready-made example?

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/issues/322.

**Comment by GoldenEagle66** [comment]
@Lonami 
when executed in the debug mode on
```
 pr = socks.socksocket()
                                    pr.set_proxy(socks.HTTP, currproxy[0], int(currproxy[1]), True, currproxy[2], currproxy[3])
                                    pr.connect(('2001:67c:4e8:f002::a', 443))
```
answer
`Socket error: 502: Bad Gateway`
