### ISSUE TITLE
how to use ipv6?

### ISSUE THREAD

**Issue by GoldenEagle66** [LonamiWebs/Telethon#819]
how to use ipv6?
I try so, but does not work 
 if app.getOptionBox("proxytype") == "ipv6":
                        ipv6 = True
                        pr.connect((('[2001:67c:4e8:f002::a]', 443, 0, 0)))
                    else:
                        ipv6 = False
                    if app.getOptionBox("proxy") != "noproxy":
                        client = TelegramClient(dir + "/" + number, api_id, api_hash, proxy=pr,use_ipv6=ipv6)

                    else:
                        client = TelegramClient(dir + "/" + number, api_id, api_hash)
                    client.connect()
returns response
PySocks doesn't support IPv6: ('[2001:67c:4e8:f002::a]', 443, 0, 0)
is there a ready-made example?

**Comment by Lonami** [comment]
#818.
