### ISSUE TITLE
Create a friendlier Message class

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#820]
It would be really convenient to have a custom `Message` class. Considering the usage of Telegram's `Message` is widespread, its attributes should be preserved (so we shouldn't have a `.message` attribute to access the original message as it is often used to access the text). Subclassing it seems like the way to go. In addition:
* `text` property to access the markdown version.
* `reply` (and `respond`?) methods, of course returning the sent message.
* `download_media` method.
* `reply_to` property to access the reply.
* Methods to ease interacting with inline buttons.
* `from_user`/`chat` and its input variants (via bot too?).
* A way to easily access the entities' text.

**Comment by mistyhands** [comment]
Suggestion:

`respond` sends a message in the same chat

`reply` does the same but uses Telegram's reply formatting to reply to the specific message

**Comment by Lonami** [comment]
@mistyhands please see #830, it also mentions to unify the `events.NewMessage` with `custom.Message` since they are nearly identical.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/12812ea542638d587328821329e6f836ff9875da
