### ISSUE TITLE
MTProto proxy support in Telethon

### ISSUE THREAD

**Issue by saeedesfandi** [LonamiWebs/Telethon#823]
Hi,
Do you have any plans to add mtproto proxy support?

---

BountySource: https://www.bountysource.com/issues/58957769

**Comment by Lonami** [comment]
@saeedesfandi sure, it could be done, when I have time or when someone else decides to help.

**Comment by drinksober** [comment]
Hi, any idea to finish the mtproto proxy support, I want help to finish this feature, but I cant find any article to talk about mtproto proxy client. what I can do is setup a mtproto proxy server...

**Comment by Lonami** [comment]
@drinksober you should create a [new connection class](https://github.com/LonamiWebs/Telethon/tree/master/telethon/network/connection) in that directory that uses the proxy. Somehow.
