### ISSUE TITLE
Two client.connect

### ISSUE THREAD

**Issue by JonahSabri** [LonamiWebs/Telethon#826]
Hello
I want to use the profile in two sources, but when I enter client.connect in the second source, the first source does not read the update.
I get an update on client.idle in the first source

**Comment by Lonami** [comment]
I have no idea what your code looks like but you should use different session files for different clients.

**Comment by JonahSabri** [comment]
i need to connect a session file with two file

but if i run second source , first source dont get any update

my first source:

client = TelegramClient("./Sessions/{}.session".format(text), config.apis[str(text)]["api_id"], config.apis[str(text)]["api_hash"], update_workers=2, spawn_read_thread=False)
client.start()

@client.on(events.NewMessage)
def my_event_handler(event):
    print(event)
client.idle()

second source:

client = TelegramClient("./Sessions/{}.session".format(text), config.apis[str(text)]["api_id"], config.apis[str(text)]["api_hash"], update_workers=2, spawn_read_thread=False)
client.connect

**Comment by JonahSabri** [comment]
please answer me :(

**Comment by Lonami** [comment]
[I already did](https://github.com/LonamiWebs/Telethon/issues/826#issuecomment-393127639):
> but you should use different session files for different clients.
