### ISSUE TITLE
Could not find the input entity

### ISSUE THREAD

**Issue by JonahSabri** [LonamiWebs/Telethon#828]
Hello
I want to get messages from a group using:
client.get_messages

While the account is in the group, telethon gives this message:
Could not find the input entity for "-1001160591810"

how can i fix this?

thanks

**Comment by Lonami** [comment]
You read the documentation, and if you still have issues  you ask them in [@TelethonChat](https://t.me/TelethonChat).

**Comment by JonahSabri** [comment]
I have read documentation but I have not found anything about this
I can not subscribe to global groups because iranians has blocked access to global groups.

If you can respond here so I can solve my problem

**Comment by Lonami** [comment]
[You need to learn to read documentations](http://telethon.readthedocs.io/en/latest/extra/basic/entities.html):

> "To “encounter” an ID, you would have to “find it” like you would in the normal app. If the peer is in your dialogs, you would need to client.get_dialogs(). If the peer is someone in a group, you would similarly client.get_participants(group)."

> you would need to client.get_dialogs().

> **client.get_dialogs()**
