### ISSUE TITLE
Instabanned after logging in with Telethon?

### ISSUE THREAD

**Issue by mike-johnson-jr** [LonamiWebs/Telethon#829]
I just got banned right after I logged in with Telethon. Is anyone else experiencing this problem?

**Comment by Lonami** [comment]
Yes, #824 and recently a comment in #498. I have no idea why this happens. I have *never* had my account banned, or deleted, and I have been using this library for the longest time since I need to test what I write… I've heard of more reports from other developers. The cause is unknown.
