### ISSUE TITLE
Help forwarding a message

### ISSUE THREAD

**Issue by ThiPereira** [LonamiWebs/Telethon#831]
Hi!

I'm creating a Bot to redirect messages from one channel to another. My script is already working if the message is just text but if it is a photo I can not do it... Could anyone help me with it?

```python
@client.on(events.NewMessage)
def my_event_handler(event):
    sender = event.chat_id
    if sender == -XXXXXXXXX:
        if event.raw_text != "":
            print("text")
            client.send_message(-xxxx, event.raw_text)
        if event.photo:
            print("photo")
            client.send_message(-xxxx, event.photo)
```

**Comment by Lonami** [comment]
1. Enable logging.
2. [Ask in the group](https://t.me/TelethonChat).
