### ISSUE TITLE
Create events.CallbackQuery

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#835]
The library already offers signing in as a bot, so it's only natural that we should further facilitate its usage as one. This includes events specific to bots like `events.CallbackQuery` (and maybe exposing `reply_markup` on `send_message` and `edit_message` methods).

Some clear must-haves:
* `.answer()` method (name may change).
* `.message` property to get the message.

**Comment by Kyle2142** [comment]
Some convenience functions:
- `event.edit_markup(...)`
- `event.edit_message(...)`

**Comment by Lonami** [comment]
I feel like it should be `event.edit(markup=...)`. Maybe `.edit_message` still. For `events.NewMessage`, it makes sense to `.edit()` the message, but for a "callback", it makes sense to `.edit_message()`.

**Comment by Kyle2142** [comment]
if `event.edit_message` allows `markup=` on its own, then that is fine and can unify the suggestions I made

**Comment by Lonami** [comment]
Creation https://github.com/LonamiWebs/Telethon/commit/05e8e60291cd6f11c7c4f892dabb4ab4dd631235.
Filtering https://github.com/LonamiWebs/Telethon/commit/f6c45dcc639abc677fb47c8b54e067605343bad8.
