### ISSUE TITLE
Didn't understand how to use 2FA

### ISSUE THREAD

**Issue by kyle250** [LonamiWebs/Telethon#837]
I use try to login and set password at first time like this code:

```python
client = TelegramClient(phone,api_id,api_hash)
assert client.connect()
if not client.is_user_authorized():  
    client.send_code_request(phone)
    code = input('Enter Code:') 
try:
    client.sign_in(phone, code)
    client.edit_2fa(new_password='mypassword') #set password first time
except SessionPasswordNeededError:
    client.sign_in(phone, code, password='mypassword')
```

after this, session file will be generated as "phone.session" file, then next time i want to use my client like:

```python
client = TelegramClient(phone,api_id,api_hash)
assert client.connect()
entity = client.get_entity('https://t.me/DMChain')
print(entity)
```

if now 2FA password ,this code would be perfect . and i don't need to input code every time.

but if i set 2FA password , this will trigger error like:
SessionPasswordNeededError: Two-steps verification is enabled and a password is required

i don't want to use client.sign_in(phone, code, password='mypassword') to login my session every time. and i don't know how to pass my password while simply use client.connect().

i think some way to use password would like:
client = TelegramClient(phone,api_id,api_hash,password='mypassword')
or
client.connect(password='mypassword')

but just dont know how to use it.

hope someone can help me .

**Comment by Lonami** [comment]
This belongs in [@TelethonChat](https://t.me/TelethonChat), not here.
