### ISSUE TITLE
low speed bot in large supergroups

### ISSUE THREAD

**Issue by Mohammadwh** [LonamiWebs/Telethon#838]
![rec 0040](https://user-images.githubusercontent.com/18552903/41064748-bcc77c50-69f1-11e8-936c-f3969751c019.gif)

Hi, How can I increase the speed of the bot inside large SuperGroups?

**Comment by Lonami** [comment]
I have never noticed such delays. It's probably Telegram not sending the updates fast enough.

**Comment by Mohammadwh** [comment]
Why does not (Tdbot)[https://github.com/vysheng/tdbot] have this problem?

**Comment by Lonami** [comment]
Well, I'd really like to know! I have never been able to spot these huge delays some people have complained about. I joined the groups they mentioned and it worked just fine.

It might be Telegram not sending the updates as soon as with that library, for some reason. I don't know. Maybe it's hitting Python's slowness as a bottleneck, where it can't decode things fast enough… What group is slow for you?

**Comment by Mohammadwh** [comment]
Groups whose members are over 10,000.

**Comment by Lonami** [comment]
Okay, what groups?

**Comment by Mohammadwh** [comment]
https://t.me/joinchat/EKgUTkPuK_ROCmfhJ5fSQQ

**Comment by Mohammadwh** [comment]
can you send message to my account in telegram?
@KingOFDevelopers

**Comment by Lonami** [comment]
Would you mind trying the current `asyncio` version of the library and telling me if the issue persists? Thanks.
