### ISSUE TITLE
'ascii' codec can't encode characters in position 89-91: ordinal not in range(128)

### ISSUE THREAD

**Issue by Shonminh** [LonamiWebs/Telethon#839]
![image](https://user-images.githubusercontent.com/7269690/41139148-61994390-6b18-11e8-91b6-1af87be6bdf4.png)
Hi, when invoke `CreateChatRequest`, it occurs exception like this: `'ascii' codec can't encode characters in position 89-91: ordinal not in range(128)`. 
I can't find reason about this, can any help?

**Comment by Shonminh** [comment]
I sovled the problem, It's a reason about server's `locale`, python file contains some strings that server don't support. :(

**Comment by Lonami** [comment]
It would probably be enough as long as you don't print anything, or configure your terminal to support UTF-8. Maybe.
