### ISSUE TITLE
problem with client.download_media(message)

### ISSUE THREAD

**Issue by mecko** [LonamiWebs/Telethon#841]
keep having a problems when I try to run my code, When I use my username without @ sign it shows an ValueError: No user has "anon1gazr" as username. When i try my number it shows: get_message_history is deprecated, use get_messages instead

```python
from telethon import TelegramClient
api_id=myIDnum
api_hash='myHash'
client = TelegramClient('test_session', api_id, api_hash)
client.start()
for message in client.get_message_history('myUsername', limit=25):
    client.download_media(message)
```

**Comment by Lonami** [comment]
Both errors are self-explanatory.

**Comment by mecko** [comment]
It is easy to say that the error is self-explanatory but it is not, I tried get_message it returns (No user has "username" as username) but it is exist and working.
maybe you should update your return error  a bit to be more specific?

**Comment by Lonami** [comment]
It is. No username has "username" *as username*. Username like @Lonami it's different from an *user's name*. Subtle, but that's the way it's called in the API. You have first name, last name and username.
