### ISSUE TITLE
Doesn't get the entity of private channel by id

### ISSUE THREAD

**Issue by bixnel** [LonamiWebs/Telethon#842]
I don't think, that this is my mistake, but...
When I get entity of secret channel by joinchat-URL, I get it's id.
After that, I'm trying to get entity of this channel by id, but nothing found.
 ```python
client.get_entity('https://t.me/joinchat/AAAAAEXsaN7j7E_vXTHPAw')
>>> Channel(id=1173121246, ...)

client.get_entity(PeerChannel(1173121246))
>>> ValueError: Could not find the input entity for "PeerChannel(channel_id=1173121246)".
```

Is it OK, that in first usage it uses **id** and in the second it uses **channel_id**?
If it's my mistake, please correct me and write the correct way of getting entity of private channel **by id**.

**Comment by Lonami** [comment]
This belongs to [@TelethonChat](https://t.me/telethonchat).
