### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by Goalthy** [LonamiWebs/Telethon#849]
Hello,

I need some help to configure Telethon.. I've been on it all the afternoon but now I just stuck. I never used linux and python before and I learned all today.

I'm stuck at this step here: https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/extra/basic/creating-a-client.rst

`Once that's ready, the next step is to create a TelegramClient. This class will be your main interface with Telegram's API, and creating one is very simple:
from telethon import TelegramClient

(#) Use your own values here
api_id = 12345
api_hash = '0123456789abcdef0123456789abcdef'

client = TelegramClient('some_name', api_id, api_hash)`

I've been searching for hours but I don't know what to do with that !? Where do I need to modify this ? What is it ? Is this a comand to do on phython or something to modify in a file ? Where do I need to set my api and my hash ?

I don't know how to create this TelegramClient, what I need to do and trust me for me this is now "very simple" as it's said ^^.

(I modified id and hash in the API folder in settings_example)

And I also get this error when I do python try_telethon.py:
![screenshot_13](https://user-images.githubusercontent.com/40277697/41435655-dcd657c6-701f-11e8-8bca-1d12bc1aab46.png)

And also this one when I try client = TelegramClient('some_name', api_id, api_hash)
![screenshot_14](https://user-images.githubusercontent.com/40277697/41436811-138959fa-7023-11e8-8602-547517760485.png)

Sorry, I'm a noob. Thank you for your help if someone reply!

**Comment by Lonami** [comment]
You need to learn Python. [There are a lot of guides online](https://ddg.gg/learn%20python). The page you linked goes very slowly explaining how it works and I think it's easy to understand. The issue section is for problems *in the library*, not running your own code.

**Comment by Lonami** [comment]
By the way `python try_telethon.py` is currently broken, sorry for that. You can `git checkout v0.19.1` and try again.

**Comment by Goalthy** [comment]
Thank you for you answer.

What do you mean by broken ? Is it possible to run it ?

**Comment by Lonami** [comment]
By "broken" I mean the library is being rewritten into using `asyncio` at its core and the [`sync`](https://github.com/LonamiWebs/Telethon/tree/sync) branch will be usable just like you've been using the `telethon` package all the time. I haven't updated the examples or documentation yet.
