### ISSUE TITLE
Secret Chat Support?

### ISSUE THREAD

**Issue by Foleosy** [LonamiWebs/Telethon#85]
Hi, sorry for opening this as an issue; I couldn't find a better way to ask for questions.

My current dialog window in the Interactive Telegram Client has four chats - Me with myself, me with a bot, me with Telegram and me with another phone/account. However, I do have a secret chat (on my phone) running with my other phone as well, and this chat does not show on the client.

I was wondering if it was some configuration issue, or that it is not current possible for secret chats in the client? If so, would it be (theoretically) possible to add support for secret chats in the client (via Telegram API invokes or otherwise), between the client and the phone (but not accessible if I login to the same account on the phone, of course)? I understand that even the official web/desktop telegrams do not support this (?), so I'm just... wondering?

Thanks.

P.S. I had a real issue of some duplicate printing of message retrieval real-time, but when I check the !h the last 10 lines print fine (no duplicates).

**Comment by Lonami** [comment]
I've never worked with those, but building on top of Telethon itself, it shouldn't be *that* complex to implement secret chats. Here's the official documentation: https://core.telegram.org/api/end-to-end.

Web and desktop official clients don't implement those for different reasons, it still should be possible.

**Comment by Foleosy** [comment]
I greatly appreciate your quick response!

Thank you very much. Will be looking to see if there's any other alternatives before trying to implement (I suck at the Telegram TL stuffs), though Telethon seems to be amongst the best out there. :1st_place_medal:
