### ISSUE TITLE
ImportError: cannot import name 'ConnectionMode'

### ISSUE THREAD

**Issue by V5647** [LonamiWebs/Telethon#850]
Hi , I have some issues with telethon. First i've see DraftMessageEmpty error, then I try to update telethon at last version (0.19.1.6) and the problem now is another. Now I have an ImportError: cannot import name 'ConnectionMode'. Can you solve this? Thanks.

**Comment by Lonami** [comment]
No, I'm not solving that. It was a breaking change. Update your code. See http://telethon.readthedocs.io/en/latest/extra/changelog.html#breaking-changes.

**Comment by V5647** [comment]
How can I update my code? How I have to update "from telethon import ConnectionMode"?

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/blob/24d2074e0c47b61631dc1cc29b2bab264ddf1285/telethon_examples/interactive_telegram_client.py#L7

https://github.com/LonamiWebs/Telethon/blob/24d2074e0c47b61631dc1cc29b2bab264ddf1285/telethon_examples/interactive_telegram_client.py#L70-L78
