### ISSUE TITLE
Syntax error in telegrambaseclient.py on line 106

### ISSUE THREAD

**Issue by RickyFisher98** [LonamiWebs/Telethon#851]
Hi,

I'm trying to use this client and I'm getting a syntax error before I even start, on the '*' here:

```python
def __init__(self, session, api_id, api_hash,
                 *,
                 connection=ConnectionTcpFull,
                 use_ipv6=False,
                 proxy=None,
                 timeout=timedelta(seconds=5),
                 report_errors=True,
                 device_model=None,
                 system_version=None,
                 app_version=None,
                 lang_code='en',
                 system_lang_code='en',
                 loop=None):
```

Within the Telethon folder, I have start.py which contains:

```python
from telethon import TelegramClient

api_id = xxx
api_hash = 'xxx'

client = TelegramClient('some_name', api_id, api_hash)
```

That's all, I've done nothing more to it. I installed it using 
```
git clone https://github.com/LonamiWebs/Telethon.git
```

**Comment by Lonami** [comment]
> That's all, I've done nothing more to it. I installed it using 
> ```
> git clone https://github.com/LonamiWebs/Telethon.git
> ```

Master branch is currently going through a lot of changes and should not be used. You should install it from PyPi if possible or `git checkout v0.19.1`. What Python version are you using? The `*` is perfectly valid syntax in Python.

**Comment by RickyFisher98** [comment]
Everything I've done relating to this is:

1 .apt-get install python3-pip
2. git clone https://github.com/LonamiWebs/Telethon.git as suggested on the docs, shouldn't be there if it's not reliable.

**Comment by Lonami** [comment]
> as suggested on the docs, shouldn't be there if it's not reliable.

Well yeah. Things take their time, and it will be fixed eventually unless you want to help speed it up (you don't) :)

You didn't answer your Python version. 3.5? 3.6? Just run `python --version`.

**Comment by RickyFisher98** [comment]
3.5.

If I use:

```pip3 install telethon``` it installs:
```telethon/
Telethon-0.19.1.6.dist-info/
telethon_generator/
```

in ```/usr/local/lin/python3.5/dist-packages/```. Can I just ```mv telethon``` and ```telethon_generator``` to my working directory and ```rm -f Telethon-0.19.1.6.dist-info/```?

**Comment by Lonami** [comment]
You should be able to yes. You just need `telethon`. `telethon_generator` should not be installed at all:
https://github.com/LonamiWebs/Telethon/blob/cbd5594dba6e71c82833ed64ae0eee502f537944/setup.py#L222-L223

But I have no idea why it's ignoring my `excludes`. And the `dist-info` is metadata.
