### ISSUE TITLE
Spams the message once event triggered

### ISSUE THREAD

**Issue by Jinqad** [LonamiWebs/Telethon#856]
```python
import asyncio
from telethon import TelegramClient, events

loop = asyncio.get_event_loop()
phone = '...' 
phone_2 = '...'                                                                                                    

api_id =                                                                                                              
api_hash = '' 
client = TelegramClient(phone, api_id, api_hash)
client_2 = TelegramClient(phone_2, api_id, api_hash)                                                                    
loop.create_task(client.start())
loop.create_task(client_2.start())

@client.on(events.NewMessage(chats=[1236282300]))
async def my_event_handler(event):
    await client_2.send_message(1236282300,"Hello [Test]")

loop.run_forever()
```
Well i'm not sure but when i send a message to that channel; on the other account it doens't send the "Hello [Test]" once but it spams it honestly not sure why its doing that... maybe you know  more and how to fix this.

**Comment by Lonami** [comment]
> but it spams it honestly not sure why its doing that

Well, `client2` sends a message, and `client` receives it, so `client2` sends a message and `client` receives it… I think you know where this is going.

**Comment by Jinqad** [comment]
Oh holy fuck I'm so sorry just makes me so dumb ://////

**Comment by Lonami** [comment]
No problem :sweat_smile: you provided a Minimal Working Example, which is good and not everyone does.
