### ISSUE TITLE
Click button error

### ISSUE THREAD

**Issue by proroot** [LonamiWebs/Telethon#867]
`Message(id=111, to_id=PeerChannel(channel_id=111111), date=datetime.utcfromtimestamp(1529926407), message='11111', out=False, mentioned=False, media_unread=False, silent=False, post=True, from_id=None, fwd_from=None, via_bot_id=111111, r_msg_id=None, media=None, reply_markup=ReplyInlineMarkup(rows=[KeyboardButtonRow(buttons=[KeyboardButtonCallback(text='Reopen poll', data=b'{"id":"19bead1","a":"open","in":1}')])]), entities=[MessageEntityBold(offset=0, length=87), MessageEntityItalic(offset=88, length=14), MessageEntityHashtag(offset=107, length=8), MessageEntityHashtag(offset=145, length=7), MessageEntityHashtag(offset=171, length=5), MessageEntityItalic(offset=218, length=12)], views=3458, edit_date=datetime.utcfromtimestamp(1530025072), post_author='1111', grouped_id=None)`

`history.messages[0].click(1)`

AttributeError: 'Message' object has no attribute 'click'

**Comment by Lonami** [comment]
Old version.

**Comment by proroot** [comment]
__version__ = '1.0-rc1'

**Comment by proroot** [comment]
```
test = o_telegram_api.api()(GetHistoryRequest(
            peer=username,
            offset_id=offset_id,
            offset_date=offset_date,
            add_offset=add_offset,
            limit=limit,
            max_id=max_id,
            min_id=min_id,
            hash=hash
        ))

test.messages[0].click(1)
```

**Comment by Lonami** [comment]
You're calling a raw method, hence you get a raw message, not `custom.Message`. Is there *any* reason at all why you wouldn't use `client.get_messages`?
