### ISSUE TITLE
get all dialogs 

### ISSUE THREAD

**Issue by AbolfazlDalily** [LonamiWebs/Telethon#871]
hello 
i use this code to get all dialogs 
'''
from telethon.tl.functions.messages import GetDialogsRequest
        from telethon.tl.types import InputPeerEmpty
        get_dialogs = GetDialogsRequest(
            offset_date=None,
            offset_id=0,
            offset_peer=InputPeerEmpty(),
            limit=1000,
        )
        dialogs = client(get_dialogs)
        
        contacts = ''
        users = {}
        chats = {}
        for u in dialogs.users:
            users[u.id] = u

        for c in dialogs.chats:
            chats[c.id] = c

        for d in dialogs.dialogs:
            peer = d.peer
            if isinstance(peer, PeerChannel):
                id = peer.channel_id
                channels = chats[id]
                access_hash = channels.access_hash
                name = str(channels.title)
                chusername = str(channels.username)
                contacts = contacts+"{0:20s}{1:40s}{2:20s}{3:20s}".format("Channel",str(id),chusername,name)+"\n"
                print("{0:20s}{1:40s}{2:20s}{3:20s}".format("Channel",str(id),chusername,name))
                input_peer = InputPeerChannel(id, access_hash)

            elif isinstance(peer, PeerChat):
                id = peer.chat_id
                group = chats[id]
                name = str(group.title)
                input_peer = InputPeerChat(id)

                contacts = contacts + "{0:20s}{1:40s}{2:20s}{3:20s}".format("Group",str(id),'-------',name)+"\n"
                print("{0:20s}{1:40s}{2:20s}{3:20s}".format("Group",str(id) ,"-------",name))

            elif isinstance(peer, PeerUser):
                id = peer.user_id
                user = users[id]
                access_hash = user.access_hash
                username = str(user.username)
                name = str(user.first_name)
                input_peer = InputPeerUser(id, access_hash)

                contacts = contacts + "{0:20s}{1:40s}{2:20s}{3:20}".format("User",str(id),username,name) + "\n"
                print("{0:20s}{1:40s}{2:20s}{3:20}".format("User",str(id),username,name))
            else:
                continue
'''
to get all dialogs 
but this cod return only 104 dialogs while i  have much more ?

**Comment by Lonami** [comment]
Why are you not using `client.get_dialogs`.

**Comment by Lonami** [comment]
Old version.
