### ISSUE TITLE
Finding user by id sents Could not find the input entity for "379231835".

### ISSUE THREAD

**Issue by Katerou22** [LonamiWebs/Telethon#873]
Im trying to find user by client.get_entity(id)
but it arise Could not find the input entity for "379231835". !

Why this happends?! how i can get user by id i never chat before?

**Comment by Katerou22** [comment]
Event using PeerUser it arise again : 
Could not find the input entity for "PeerUser(user_id=379231835)".

**Comment by Lonami** [comment]
Did you consider reading the documentation? I'm pretty sure that error has a link.

**Comment by Lonami** [comment]
(And if it doesn't, you're using an old version).

**Comment by Katerou22** [comment]
Im using the latest version and yes it mentioned  a link
but in link i couldn't find anything to solve this f problem!!!!

**Comment by Lonami** [comment]
Next time you open an issue please put enough information first ("I have read this link...") instead making me ask that question. The link basically means that you probably just need to `client.get_dialogs()`. But the issue should be "unclear error" instead of just complaining about it.

**Comment by Katerou22** [comment]
Sry bout that, 
What actually client.get_dialogs() do?!

**Comment by Lonami** [comment]
Read the documentation for it.

**Comment by Katerou22** [comment]
I used get dialogs and again that error , i cant found the problem here!!!! i just want to get entity by some id i never chat before , it turns error!!

**Comment by Lonami** [comment]
It's impossible to message someone by their ID unless you see the ID somewhere first.

**Comment by Katerou22** [comment]
I have received a forwarded message from him i get id by this format: event.message.fwd_from.from_id

**Comment by Lonami** [comment]
You should upgrade and use `event.forward.from_user`.

**Comment by Katerou22** [comment]
:|

AttributeError: '_CustomMessage' object has no attribute 'forward'

**Comment by Lonami** [comment]
Did you upgrade…

**Comment by Katerou22** [comment]
Whats instead of update_workers? im getting erro from this after upgrading

**Comment by Lonami** [comment]
Just remove it.

**Comment by Katerou22** [comment]
When u update?! I just install it 2days ago!

**Comment by Katerou22** [comment]
Whats instead of idle?

**Comment by Lonami** [comment]
`run_until_disconnected`.

**Comment by Katerou22** [comment]
Thank you for ur responses, but still i have error: AttributeError: 'Forward' object has no attribute 'from_user'

**Comment by Lonami** [comment]
It's `sender`, not `from_user`.

**Comment by Katerou22** [comment]
What is this then? TypeError: object NoneType can't be used in 'await' expression

**Comment by Katerou22** [comment]
@client.on(events.NewMessage)
def my_event_handler(event):
    print(event.forward.sender) my code

**Comment by Lonami** [comment]
```
pip uninstall telethon
pip install telethon-sync
```

**Comment by Katerou22** [comment]
All methods same as telethon default ?

**Comment by Katerou22** [comment]
Im sure im forwarding message to the client but print return None
