### ISSUE TITLE
get all dialogsa

### ISSUE THREAD

**Issue by AbolfazlDalily** [LonamiWebs/Telethon#874]
hello 
I updated the telethon package and use this code to get all dialogs 
```
class ShowDialogsExecutor(Executor):
    def __init__(self):
        pass

    def execute(self):
        print("Hello")
        try:
            
            dialogs = client.get_dialogs()
            print(len(dialogs))
        except Exception as e :
            print(e)
```
but I do not receive any response . 
There are about a thousand contacts in my current account.
When I try this code for my other account, which has 49 contacts, I will answer

Thanks !

**Comment by Lonami** [comment]
Do you even run the code…? Does it show anything? Enabled logging?

**Comment by AbolfazlDalily** [comment]
I tested this code with two accounts. One of the accounts that has a little audience has the correct answer, but the account that has nearly 1000 contacts does not answer.

**Comment by Lonami** [comment]
What does this show?:
```python
i = 0
for d in client.iter_dialogs():
    i += 1
    print(i)
```

**Comment by AbolfazlDalily** [comment]
```
from telethon import TelegramClient
api_id = ******
api_hash = '**********************'
session = 'session'
global client

client = TelegramClient(session,api_id,api_hash,update_workers=3)
```
I create my client with this code

**Comment by Lonami** [comment]
If that code works, you're not using the latest version.

**Comment by AbolfazlDalily** [comment]
I tried your code but when I run the dialogs command (this command executes your code) I will not get any results.
![screenshot 12](https://user-images.githubusercontent.com/39518484/42079335-4bd219f2-7b34-11e8-9580-eaf6110d46a0.png)

**Comment by Lonami** [comment]
Very strange. Not sure what you're doing wrong.

**Comment by Lonami** [comment]
What does this show?:
```python
i = 0
print('Before')
for d in client.iter_dialogs():
    i += 1
    print('Dialog', i)
print('After')
```

**Comment by AbolfazlDalily** [comment]
I tried this code. Code execution is taking too long and not finished yet?
![screenshot 13](https://user-images.githubusercontent.com/39518484/42080248-e524b64e-7b36-11e8-8140-acf956a5a93b.png)

**Comment by Lonami** [comment]
What does this show?:
```python
from datetime import datetime

i = 0
print(datetime.now(), 'Before')
for d in client.iter_dialogs():
    i += 1
    print(datetime.now(), 'Dialog', i)
print(datetime.now(), 'After')
```

**Comment by AbolfazlDalily** [comment]
![screenshot 15](https://user-images.githubusercontent.com/39518484/42080578-07a69b5a-7b38-11e8-9a74-038f3bafcf0b.png)
Again the same result

**Comment by Lonami** [comment]
Do you have to run your code inside a `ShowDialogsExecutor`?

**Comment by AbolfazlDalily** [comment]
![screenshot 20](https://user-images.githubusercontent.com/39518484/42081413-3a3db3ee-7b3a-11e8-9afc-961b67d82bbf.png)
![screenshot 21](https://user-images.githubusercontent.com/39518484/42081425-40b2a25c-7b3a-11e8-80e5-d932b7b21b0b.png)


I run this code to test it, but I got the same result

**Comment by AbolfazlDalily** [comment]
![screenshot 22](https://user-images.githubusercontent.com/39518484/42081453-52082a7c-7b3a-11e8-846b-0d52194de648.png)

**Comment by AbolfazlDalily** [comment]
?

**Comment by Lonami** [comment]
Are you using the latest version of the library? If you're not remember:
> If you're upgrading from Telethon pre-1.0 to 1.0, please make sure to read this section of the documentation, or pip install telethon-sync which is compatible with synchronous code. Don't forget to remove the asynchronous version (pip uninstall telethon) if you do install sync.
