### ISSUE TITLE
automatic fill confirm code

### ISSUE THREAD

**Issue by vhdm** [LonamiWebs/Telethon#876]
hi @Lonami 
how to automatic fill confirm code in:
Please enter the code you received:
and two step verification password?

**Comment by Lonami** [comment]
When I answered you on https://github.com/expectocode/telegram-export/issues/58#issuecomment-401535504 I pointed you to [@TelethonChat](https://t.me/telethonchat), not here. Anyway that's in [the docs](http://telethon.readthedocs.io/en/stable/telethon.client.html#telethon.client.auth.AuthMethods.send_code_request), of course.
