### ISSUE TITLE
Implement calls in Telethon

### ISSUE THREAD

**Issue by Lonami** [LonamiWebs/Telethon#877]
A good start: https://github.com/LonamiWebs/Telethon-calls
BountySource: https://www.bountysource.com/issues/60374650

**Comment by cher-nov** [comment]
Note that this should support proxying through PySocks and MTProxy.

**Comment by MurzNN** [comment]
I have found https://github.com/bakatrouble/pytgvoip project, can it help with implementing call feature in Telethon?

**Comment by Lonami** [comment]
@MurzNN there's a nearly-ready to use implementation for Telethon in https://github.com/cher-nov/pytgcalls.

**Comment by Lonami** [comment]
Closing since this won't be implemented in this library (support will be added by someone else on a third party library if at all, but not by me any time soon).
