### ISSUE TITLE
use new version ! 

### ISSUE THREAD

**Issue by AbolfazlDalily** [LonamiWebs/Telethon#880]
Hello ..
I installed version 1.0.3 of the telethon package
In the old version, I created a client with update-worker = 3 then
When the client managed events in the background, I could send instructions to the program via the 
console, but in this version, I do not know what to do.

I have read the two links below :
[http://telethon.readthedocs.io/en/latest/extra/basic/asyncio-magic.html](url)
[http://telethon.readthedocs.io/en/latest/extra/basic/working-with-updates.html](url)

Thanks :

**Comment by Lonami** [comment]
First you should remove the "update workers" and "read thread" link. Second, you should consider uninstalling `telethon` and installing `telethon-sync` instead. Third, rename idle to run_until_disconnected.

**Comment by AbolfazlDalily** [comment]
I did the above. And I run the code to test it, but the code does not work properly.
`‍‍``
from telethon import TelegramClient,events
import logging
client = TelegramClient('session',*****,'***********************************')
logging.basicConfig(level=logging.ERROR)

@client.on(events.NewMessage)
async def handler(event):
    print(event)

if __name__ == '__main__':
    client.start()
    client.run_until_disconnected()
    print(client.get_me())
    while True:
        cli = input(">>>")
        if cli == 'exit':
            break
        else:
            print(cli)

```
‍‍‍‍‍
![screenshot 30](https://user-images.githubusercontent.com/39518484/42323224-41773c78-8014-11e8-82bc-18b5ee4d90d7.png)

**Comment by Lonami** [comment]
You don't use async def if you install sync.

**Comment by AbolfazlDalily** [comment]
Thank you for your help
But in this code, I can not use the console

```
from telethon import TelegramClient,events
import logging
client = TelegramClient('session',291079,'252799d8e65a1bfca0c8cf10291ce7c4')
logging.basicConfig(level=logging.ERROR)

@client.on(events.NewMessage)
def handler(event):
    print(event)

if __name__ == '__main__':
    client.start()
    client.run_until_disconnected()
    print(client.get_me())
    while True:
        cli = input(">>>")
        if cli == 'exit':
            break
        else:
            print(cli)
‍```
![screenshot 31](https://user-images.githubusercontent.com/39518484/42323610-98a1e8bc-8015-11e8-9728-a05bf7a9abfa.png)

‍‍

**Comment by Lonami** [comment]
run_until_disconnected obviously blocks.

**Comment by AbolfazlDalily** [comment]
I din't notice .
How do i solve it

**Comment by Lonami** [comment]
@AbolfazlDalily just remove the line and stop asking.
