### ISSUE TITLE
There is no current event lo op in thread 'ThreadPoolExecutor-0_0'.

### ISSUE THREAD

**Issue by greyyoung** [LonamiWebs/Telethon#884]
Hi，I update to 1.03 version and run but get 'There is no current event loop in thread 'ThreadPoolExecutor-0_0'.' It's works well in 1.02. Should I change some code to adapt with v1.03? Thanks.

**Comment by Lonami** [comment]
You're mixing threads and `asyncio`, right? I'm not even sure how such thing was working in 1.0.2. You have three options:
1. Create and use said loop under that thread.
2. Don't ise threads.
3. Use the `telethon-sync` package.

**Comment by greyyoung** [comment]
Yes，you are right. I use telethon-sync and all works well now. Thanks.
