### ISSUE TITLE
Attribute error in sync branch

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#885]
Sometimes I get this error.
![image](https://user-images.githubusercontent.com/32207817/42444653-4a91c086-8379-11e8-8add-0b17adca193a.png)

**Comment by Lonami** [comment]
You mean `telethon-sync`, because this was fixed in the `sync` branch.

**Comment by vegeta1k95** [comment]
@Lonami 
Are the `telethon-sync` and `sync` branch different?

**Comment by Lonami** [comment]
The `telethon-sync` package doesn't get updated automatically, it's updated on a version-by-version basis.
