### ISSUE TITLE
Get history with limit=None gives out error when sync module is used

### ISSUE THREAD

**Issue by vsananthu** [LonamiWebs/Telethon#890]
```
from telethon import sync

client(GetHistoryRequest(
			entity,
			limit=None,
			offset_date=None,
			offset_id=0,
			max_id=0,
			min_id=self.last_read_message,
			add_offset=0,
			hash=0,
		))
```
This error happens when I used the sync module

```
  File "/home/ubuntu/Env/alpha3/lib/python3.5/site-packages/telethon/tl/functions/messages.py", line 1442, in __bytes__
    struct.pack('<i', self.limit),
struct.error: required argument is not an integer
```
It goes away when I keep a larger value or any integer as the limit.

Also, I don't seem to get more than 100 messages even when the limit is more, using the sync module? Is this intentional?

**Comment by Lonami** [comment]
You're confusing [`GetHistoryRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_history.html) with [`client.get_messages`](https://telethon.readthedocs.io/en/stable/telethon.client.html#telethon.client.messages.MessageMethods.get_messages). What you're showing probably never worked.
