### ISSUE TITLE
Client in idle, Issue with Flask running!

### ISSUE THREAD

**Issue by Katerou22** [LonamiWebs/Telethon#891]
**Hey lonami,**

I Run flask and include telethon in it,

After all functions i call: `client.run_until_disconnected()`

Issue is, Flask wont serve before i disconnect the client!

What i must do?!

**Comment by Lonami** [comment]
I bet Flask also has its own `idle()` variant. So use that instead.

**Comment by Katerou22** [comment]
I couldn't find that thing u said!

**Comment by Lonami** [comment]
I don't know how Flask works but how to use the library with Flask doesn't belong in these issues.
