### ISSUE TITLE
RuntimeWarning: coroutine 'MessageMethods.send_message' was never awaited

### ISSUE THREAD

**Issue by Katerou22** [LonamiWebs/Telethon#892]
Hey again!

Why im getting this error?!

my code:

 `@client.on(events.NewMessage(incoming=True, pattern='b'))
def blocking(event):
    text = 'b u said'
    client.send_message(entity=event.chat_id, message=text, parse_mode='markdown')`

Error: RuntimeWarning: coroutine 'MessageMethods.send_message' was never awaited

**Comment by Katerou22** [comment]
And how can use reply and defining parse mode in it?! something like this: `event.reply('b u said','markdown')`

**Comment by Lonami** [comment]
You should re-read the documentation.

**Comment by Lonami** [comment]
Or use an older version. Or use `telethon-sync`.

**Comment by Katerou22** [comment]
Changing code to this: 

`@client.on(events.NewMessage(incoming=True, pattern='b')) async def blocking(event): text = 'b u said' await client.send_message(entity=event.chat_id, message=text, parse_mode='markdown')`


Not working at all

**Comment by Lonami** [comment]
You should enable logging.
