### ISSUE TITLE
LOL, Sending message to who received from entity not found

### ISSUE THREAD

**Issue by Katerou22** [LonamiWebs/Telethon#893]
LOL, Look at here 1min please,

Replying to who sent message errors: 

>  Could not find the input entity for "64872989". Please read https://telethon.readthedocs.io/en/latest/extra/basic/entities.html to find out more details.

And code : 

`await client.send_message(entity=event.chat_id, message=text, parse_mode='markdown')`

**Comment by Lonami** [comment]
You probably are never calling `disconnect()`.

**Comment by Lonami** [comment]
If you don't call disconnect the library can't save entities. I'm pretty sure if you `client.get_entity('username')` and then use `client.get_entity(id_of_that_user)` it will work.

**Comment by Lonami** [comment]
Eh, I apologize for that, you're opening a lot of issues and it's starting to bother me. So please test what I just said and comment. I read your issue too fast.

**Comment by Katerou22** [comment]
Look, Any function i call in client it errors 

> RuntimeWarning: coroutine 'TelegramBaseClient.disconnect' was never awaited

Every function like send_message or disconnect

my code is: 

> def send_message(id, text, sender, receiver=None):
    .........
    client.send_message(entity=id, message=text, parse_mode='markdown')

- i use async define and no difference





but in another file i have this and its working perfectly i cant understand why!! : 


> @client.on(events.NewMessage(incoming=True, pattern='b'))
async def blocking(event):
    text = 'b u said'
    await client.send_message(entity=event.chat_id, message=text, parse_mode='markdown')
   client.run_until_disconnected()

**Comment by Katerou22** [comment]
All my problems fixed, but 1 is still annoying!

`importing = client(ImportContactsRequest(contacts))`

I have this, i want get `importing.imported` but it errors: 

`Error: 'coroutine' object has no attribute 'imported'`
