### ISSUE TITLE
InputPhoneContact doesn`t work

### ISSUE THREAD

**Issue by mitya2back** [LonamiWebs/Telethon#895]
I want to add new contact but see that:

Traceback (most recent call last):
    contact = InputPhoneContact(client_id=0, phone='+123456789', first_name='<First Name its required field>', last_name='<Last Name its optional field>')
NameError: name 'InputPhoneContact' is not defined

I use this method:
contact = InputPhoneContact(client_id=0, phone='+123456789', first_name='<First Name its required field>', last_name='<Last Name its optional field>')

client.invoke(ImportContactsRequest[contact],replace=True )

**Comment by Lonami** [comment]
You should either learn Python or read "accessing the full API".
