### ISSUE TITLE
client.get_dialogs skips channels from 100 to 120

### ISSUE THREAD

**Issue by ingria** [LonamiWebs/Telethon#896]
**More detailed explanation**
1. There's a list of 200+ channels (**500** in my case);
2. I'm calling `client.get_dialogs()`;
3. I'm getting the list of 480 channels instead of 500.

```
   Telethon:                 TDLib:

[0]   channel#0        [0]   channel#0
[1]   channel#1        [1]   channel#1
       ...                   ...
[99]  channel#99       [99]  channel#99
                       [100] channel#100
                       [101] channel#101
                       [102] channel#102
                             ...
[100] channel#119      [119] channel#119
[101] channel#120      [120] channel#120
```

Tested on several clients. Telethon is latest version, sync mode. Seems like there's something wrong with offsets.

**Comment by Lonami** [comment]
Does `tdlib` by any chance return duplicates? The library uses all offsets, not sure how that can even be wrong. See it by yourself:
https://github.com/LonamiWebs/Telethon/blob/7f78d7ed2f356da48461eb88b1cc569582297eac/telethon/client/dialogs.py#L69-L119

**Comment by ingria** [comment]
Yep, I've checked the source code — everything seems fine. Maybe it's Telegram API acting weird, not your code.

BTW, `messages.getAllChats` works as expected, returning the correct number of chats.

**Comment by Lonami** [comment]
Bump. Reopen when you can answer or if you figure(d) something else out.
