### ISSUE TITLE
can`t invite user to channel by userid

### ISSUE THREAD

**Issue by ChangMM** [LonamiWebs/Telethon#897]
```python
# temp.append(InputUser(int(id), int(access_hash)))
temp.append(PeerUser(int(id)))
    try:
        self.client(InviteToChannelRequest(channel_entity, temp))
    except Exception as e:
         print(e)                 
```
both `temp.append(InputUser(int(id), int(access_hash)))` and `temp.append(PeerUser(int(id)))`  do not work

**Comment by Lonami** [comment]
The request works completely fine. If you see no error Telegram simply is not letting you invite them. You could print the result and check by yourself.

**Comment by ChangMM** [comment]
@Lonami I find the reason. Because save the `id` to a file ,i delete session file  and relogin. Be the way, can i invite user to channel by userid if `client.session.save_entities = False`? And can I change the path of session file?
