### ISSUE TITLE
Adding people to a supergroup

### ISSUE THREAD

**Issue by Shreevenkr99** [LonamiWebs/Telethon#899]
When I try to add people to a group, it works for 50 people then it stops asking me to wait 17ish hours. I am using the code as is from the documentation. But at least this is working. When I try to add people using the supergroup or a channel it takes the first letter of a persons name and says no entity can be found of "f" or something similar. How do I fix this

**Comment by Lonami** [comment]
How is this a Telegram issue?

**Comment by Lonami** [comment]
That's Telegram limits you're seeing there not Telethon. Nothing I can do.

**Comment by Shreevenkr99** [comment]
Fine but at least in the adding users to a channel with
client(InviteToChannelRequest(
    channel,
    [users_to_add]
))
Am I supposed to put the channel ID or channel name neither seem to be working and I get an error saying no entity can be found of "f"  or similar. How do I deal with this

**Comment by Lonami** [comment]
You could try reading the documentation. Maybe. Honestly it's not hard and if you don't have time to read that I don't have time to explain it to you.
