### ISSUE TITLE
Disable auto-reconnect in Telethon

### ISSUE THREAD

**Issue by bybaga** [LonamiWebs/Telethon#903]
Hello. I'm from Russia and our goverment decided to block Telegram, so we must to use proxy to access Telegram. But proxy isn't enduring.

When proxy went down Telethon begin auto-reconnect. In ReadTheDocs wrote that you can use

client = TelegramClient(... , auto-reconnect=False, ...)

But there isn't any **kwargs for it in TelegramClient

**Comment by Lonami** [comment]
`auto-reconnect` definitely will not work but `auto_reconnect` should.

**Comment by bybaga** [comment]
```python
from telethon import TelegramClient
import socks

api_id = xxxxxx
api_hash = 'xxx'

client = TelegramClient('test',
                        api_id,
                        api_hash,
                        auto_reconnect=False,
                        proxy=(socks.SOCKS5,
                               'xxx',
                               1080,
                               True,
                               'xxx',
                               'xxx')).start()
```

and I got this

Traceback (most recent call last):
  File "C:/Users/Администратор.WIN-H2O5EF29JET/Desktop/11.py", line 16, in <module>
    'telegram')).start()
  File "C:\Program Files\python3.6.5\lib\site-packages\telethon\telegram_client.py", line 199, in __init__
    **kwargs
TypeError: __init__() got an unexpected keyword argument 'auto_reconnect'

telethon==0.19.1.6

**Comment by Lonami** [comment]
@bybaga I don't support old versions.
