### ISSUE TITLE
Collecting users from channel

### ISSUE THREAD

**Issue by cnekTep** [LonamiWebs/Telethon#904]
Thanks for great lib.

I try to collect all channel members like this:
http://telethon.readthedocs.io/en/stable/extra/examples/chats-and-channels.html#retrieving-all-chat-members-channels-too

`from telethon.tl.functions.channels import GetParticipantsRequest
from telethon.tl.types import ChannelParticipantsSearch
from time import sleep

offset = 0
limit = 100
all_participants = []

while True:
    participants = client(GetParticipantsRequest(
        channel, ChannelParticipantsSearch(''), offset, limit, hash=0
    ))
    if not participants.users:
        break
    all_participants.extend(participants.users)
    offset += len(participants.users)`

but collecting only about 200 users, what do I wrong?

**Comment by Lonami** [comment]
Thanks, you're not doing anything wrong. Telegram changed some limits server-side, so you can only retrieve 200 members per search. This probably helps reduce spam.

**Comment by cnekTep** [comment]
so, if i need all channel members, a should do many searches with offset?

**Comment by cnekTep** [comment]
maybe there is some way to get all the channel users?

**Comment by Lonami** [comment]
Recent server-side change (since 20 July); only 200 members may be retrieved. Use `iter_participants` with `aggressive=True`.

**Comment by blazeis** [comment]
client.get_participants(group) with agressive=True does not retrieve users without telegram nickname

**Comment by Lonami** [comment]
Aggressive is a hack that I want to remove in Telethon 2.0. I would not recommend its use anymore.

**Comment by blazeis** [comment]
Wich method do you recommend to use, if i need to get all members in channel?

**Comment by Lonami** [comment]
The API clearly does not want you to fetch all members, and I don't use this myself, so I cannot recommend anything. With the new channel statistics, getting the members is less relevant than ever.

**Comment by blazeis** [comment]
Thank you for explanation.
I'll try to find another method for my case..
