### ISSUE TITLE
I can't authorize my telegram account

### ISSUE THREAD

**Issue by Jihante** [LonamiWebs/Telethon#905]
I can't authorize my telegram account. When my program prompts you to enter an SMS, it comes in the application. Then insert it into the program and immediately exit the phone. Somewhere I saw something about obfuscation, so I tried to do this: the code 12884 changed so: 13000-116. But it didn't work out. I'm desperate!

**Comment by Lonami** [comment]
Not an issue with the library.

**Comment by Jihante** [comment]
I did the right thing? Thank you very much for your quick response!

**Comment by Lonami** [comment]
@Jihante nah you probably hardcoded "13000-116" which is not a valid code.

**Comment by Jihante** [comment]
Can you please then give an example of how to do it right?

**Comment by Jihante** [comment]
If you of course not difficult)

**Comment by Jihante** [comment]
Please
