### ISSUE TITLE
auth.checkPhone CheckPhoneRequest missing?

### ISSUE THREAD

**Issue by arrix** [LonamiWebs/Telethon#909]
Telethon 1.1.1. 
I was trying `from telethon.tl.functions.auth import CheckPhoneRequest` but it turns out that
CheckPhoneRequest is missing.
https://core.telegram.org/method/auth.checkphone

The return value is present, however. https://lonamiwebs.github.io/Telethon/types/auth/checked_phone.html

I remember we used to have it in an older version but I'm not sure.

I'm happy to help adding telethon.tl.functions.auth.CheckPhoneRequest.

Where do I find the correct value for CONSTRUCTOR_ID and values in __bytes__()?

**Comment by Lonami** [comment]
Official documentation [has layer 23](https://core.telegram.org/schema). We have [layer 82](https://github.com/LonamiWebs/Telethon/blob/v1.1/telethon_generator/data/telegram_api.tl#L1185). So, uh, it got removed. You can downgrade if you want.

**Comment by arrix** [comment]
Thanks for clarifying this!
I was confused by the official "current TL-schema".
checkPhone was removed in layer 80. https://github.com/LonamiWebs/Telethon/commit/e93b8f2b13c450ce413f850672a3afee67691fce#diff-3c7839b37c4df7649756dbada43daf60L854

**Comment by arrix** [comment]
They removed the method `auth.checkPhone` but not its return type `auth.CheckedPhone`.

So I decided to try my luck
```
class CheckPhoneRequest(telethon.tl.TLRequest):
    CONSTRUCTOR_ID = 0x6fe51dfb
    SUBCLASS_OF_ID = 0x99a3d765

    def __init__(self, phone_number):
        """
        :param str phone_number:

        :returns auth.CheckedPhone: Instance of CheckedPhone.
        """
        self.phone_number = phone_number  # type: str

    def to_dict(self):
        return {
            '_': 'CheckPhoneRequest',
            'phone_number': self.phone_number
        }

    def __bytes__(self):
        return b''.join((
            b'\xfb\x1d\xe5o',
            self.serialize_bytes(self.phone_number),
        ))

    @classmethod
    def from_reader(cls, reader):
        _phone_number = reader.tgread_string()
        return cls(phone_number=_phone_number)
```

It runs without any error. However, no matter what the input phone_number is, the server always returns `CheckedPhone(phone_registered=True)`

Anyway, I learned something about the schema.

**Comment by Lonami** [comment]
@arrix nice try ;) I think it started returning always true before removing it.
