### ISSUE TITLE
Get client current DC

### ISSUE THREAD

**Issue by alexvelickiy** [LonamiWebs/Telethon#911]
Is there a way to get current client DC?

I need this to load clients for other DCs to be able to load media fast.

**Comment by Lonami** [comment]
> Is there a way to get current client DC?

Yes.

> I need this to load clients for other DCs to be able to load media fast.

You should let the library do its job, which should be quite good if you're on `v1.1`.

**Comment by Lonami** [comment]
If you're *utterly* concerned about speed, you might as well re-write the code to use raw requests yourself everywhere to get extreme control.
