### ISSUE TITLE
Authenticator has broken in new layer

### ISSUE THREAD

**Issue by andr-04** [LonamiWebs/Telethon#916]
https://github.com/LonamiWebs/Telethon/blob/19900a373afa37da785ebab7ed342253e172fed8/telethon/network/authenticator.py#L179 raises `TypeError: cannot convert 'str' object to bytes`

**Comment by Lonami** [comment]
Master is using `bytes` for `pq`:
https://github.com/LonamiWebs/Telethon/blob/26f121060d114add6083e48d0ba0b90e293d6d0a/telethon_generator/data/mtproto_api.tl#L13
