### ISSUE TITLE
Problem with using multi accounts to invite user to group inside a for loop ?

### ISSUE THREAD

**Issue by louka2** [LonamiWebs/Telethon#917]
I am getting a problem when i try to use like 2 accounts (for not getting banned , every account add 40 members )
the problem is the first account work perfectly and add correctly users but second one is not adding any user
did i miss something? a code should be added to change session correctly or something?
this is part of code (adding user part)
`

        user_chunks = list(chunks(input_users, 5))
        for item in user_chunks:
            try:
                print(await self.client(
                    InviteToChannelRequest(InputChannel(target_group_data[1], target_group_data[2]), item)))
                print('Adding chunk of ' + str(len(item)) + ' users...')
                time.sleep(10)
            except Exception as e:
                print(str(e) + '\nsome error occurred, skipping to next chunk.')
                time.sleep(2)

        print('There was attempt to add ' + str(len(input_users)) + ' users in total added')
        await self.client.disconnect()`
there's like list where it contains multi account information it read from it using for loop , and inside the loop there : connect the account , add users by using jsonfile(contains some ids and hash_access), then disconnect

**Comment by Lonami** [comment]
If you don't see any errors then the library is working correctly and there is nothing for me to fix.
