### ISSUE TITLE
RPCError: No workers running

### ISSUE THREAD

**Issue by arrix** [LonamiWebs/Telethon#919]
```Traceback (most recent call last):
  ....
    return await client(InviteToChannelRequest(test_channel, test_users))
  File "/home/aaa/venvs/myenv/lib/python3.6/site-packages/telethon/client/users.py", line 48, in __call__
    result = await future
telethon.errors.rpcbaseerrors.RPCError: No workers running
```

Telethon 1.1.1 master. Account status is good (free as a bird), network condition is good. No other suspicious log precedes.

This is a very rare error. Found it it log. No further information available.
Please close the issue if it doesn't ring any bells.

**Comment by Lonami** [comment]
That's a new one. It's not raised by the library but rather Telegram used it as a result for one of your requests. No idea what it means.

**Comment by Lonami** [comment]
There's not much more I can do with this little information. The best is to install the latest version with `pip install --upgrade git+https://github.com/LonamiWebs/Telethon@master` and wait for it to happen again. Then we can create a specific error for it. Reopen if such thing happens.
