### ISSUE TITLE
download media via telethon

### ISSUE THREAD

**Issue by mar02500** [LonamiWebs/Telethon#92]
hi, I have used telethon to download telegram posts, but I can not downlaod media from the post. I have tried using download_msg_media but no result. how can I download media using telethon??

this is the code i have used for downloading function:

```
def download_media(self, media_id):
    try:
        msg_media_id = int(media_id)
        output = str('usermedia/{}'.format(msg_media_id))
        print('Downloading media wit   h name {}...'.format(output))
        output = self.client.download_msg_media(
            msg_media_id,
            file_path=output,
            progress_callback=self.client2.download_progress_callback)
        print('Media downloaded to {}!'.format(output))

    except ValueError:
        print('Invalid media ID given!')
```

the document says that the input of this function should be a MessageMedia, which has 10 constructors:

https://lonamiwebs.github.io/Telethon/types/message_media.html

how can I pass a telegram post to this function and get a MessageMedia and then pass that MessageMedia to Download function?

**Comment by Lonami** [comment]
As I always suggest, it's nice looking at the `InteractiveTelegramClient` example. More precisely, [these lines](https://github.com/LonamiWebs/Telethon/blob/master/telethon/interactive_telegram_client.py#L229-L247). What the example does is "store all the messages which have any sort of media". Then the user enters the message ID, fetches that message, and accesses its `msg.media`.

Notice that you can retrieve the media [from a message](https://lonamiwebs.github.io/Telethon/constructors/message.html), as noted by the `media:flags.9?MessageMedia` argument. That `media` is one of the 10 constructors available, which you can just pass to the client.

**Comment by mar02500** [comment]
I have checked InteractiveTelegramClient, and I have used that code in my program. when I give the function a specific telegram post id, it just says:
Downloading media with name usermedia/1426...
Media downloaded to None!
"store all the messages which have any sort of media": it does this for a specific channel (with a given id) or? could you explain this more? how does the user have access to the message id? @Lonami

**Comment by mar02500** [comment]
I could retrieve media from media attribute. but I can not save the media locally. this is what I am getting for photo attribute:

`(photo (ID: 0x9288dd29) = (has_stickers=None, id=5845865598901398016, access_hash=-297749042833952597, date=2017-05-23 09:01:28, sizes=['(photoCachedSize (ID: 0xe9a734fa) = (type=s, location=(fileLocation (ID: 0x53d69076) = (dc_id=4, volume_id=430531531, local_id=111833, secret=1132264834260955610)), w=90, h=68, bytes=b\'\\xff\\xd8\\xff\\xe0\\x00\\x10JFIF\\x00\\x01\\x01\\x01\\x00H\\x00H\\x00\\x00\\xff\\xdb\\x00C\\x00\\x0e\\n\\x0b\\r\\x0b\\t\\x0e\\r\\x0c\\r\\x10\\x0f\\x0e\\x11\\x16$\\x17\\x16\\x14\\x14\\x16, !\\x1a$4.763.22:ASF:=N>22HbINVX]^]8EfmeZlS[]Y\\xff\\xdb\\x00C\\x01\\x0f\\x10\\x10\\x16\\x13\\x16*\\x17\\x17*Y;2;YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\\xff\\xc0\\x00\\x11\\x08\\x00D\\x00Z\\x03\\x01"\\x00\\x02\\x11\\x01\\x03\\x11\\x01\\xff\\xc4\\x00\\x1b\\x00\\x00\\x01\\x05\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x06\\x00\\x02\\x03\\x04\\x05\\x01\\x07\\xff\\xc4\\x00;\\x10\\x00\\x02\\x01\\x03\\x01\\x04\\x05\\t\\x06\\x06\\x03\\x00\\x00\\x00\\x00\\x00\\x01\\x02\\x03\\x00\\x04\\x11\\x12\\x05\\x13!1\\x06"Aa\\x81\\x14#2Qq\\x91\\x92\\x93\\xd13CRS\\x94\\xa1\\x15Tr\\x83\\xb1\\xc1b\\x84\\xe1\\xff\\xc4\\x00\\x19\\x01\\x00\\x03\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x03\\x01\\x04\\x05\\xff\\xc4\\x00\\x1d\\x11\\x00\\x02\\x02\\x03\\x01\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\\x02\\x11\\x12\\x13!\\x031A\\xff\\xda\\x00\\x0c\\x03\\x01\\x00\\x02\\x11\\x03\\x11\\x00?\\x00\\xd9\\xb7T\\xd1\\xc7\\xc9\\xf3\\xff\\x00(\\x1c\\xff\\x00\\x8a\\x92=!\\xcf\\x18>S\\x8a\\x8e\\xdaV\\t\\xc1\\x8f\\xea\\xb1\\xfe\\xaaX\\xe5m\\xe1\\xeb?\\x85\\xc8\\xaf9\\x96\\x14\\xef\\x12)v1\\x05Q\\x92@q\\xc2\\x86d\\xdbWwSn\\xac\\xe3US\\x9d=\\xc3\\xbf4A\\xb6\\x19\\x8e\\xcb\\xba\\xc9\\x97\\xec\\x9b\\x9c\\xc1\\x87*\\x10\\xd9\\xf6\\xce.\\xa3\\x907\\x98#P \\xe0\\x13\\xd9O\\x14\\xaa\\xd8Sn\\x82\\x9d\\x94o\\x83\\x15\\xbe\\x89\\n\\x11\\x90\\xfa\\xb1\\x83V\\xae7z\\xf8\\x04\\xf0rj\\x9d\\x85\\xc6\\xd03\\x08\\xe4\\x92\\xdfO\\x02\\x02\\x1e\\xb6\\x9e\\xdcq\\xe7\\xca\\xaf\\\\k\\xd7\\xce\\xe3\\xc5\\x96\\x97\\xf4i,_\\x05n\\x13\\xb4G\\xe2\\xe6\\xac.\\xebQ\\xfb/{\\x1a\\xc6\\x96{\\xa9.\\xa4\\x8a+\\xe4\\xb2\\x86\\x10\\x03\\xb4\\x8c\\x0b1 \\x1e\\x1d\\xdcEC\\x16\\xd4\\xba\\xb2\\xdb)esr\\xd71\\xc9\\xa4+\\xa1\\xc1\\xebr\\xc7\\x8dn"\\xbb]7\\xdbN\\x96\\xc6\\xefN\\xa1\\xd8qO\\xeai\\xe7o\\xf2\\\\\\xd3\\x1b9$\\x99s\\x91\\xcd\\x86}\\xf56\\xb6\\x03\\xef~p\\xa44da=p|\\x96\\xa7\\xf9\\xbf\\xc5\\x17\\xc8jj\\xc8\\xdcx\\xb7\\xea1Kx\\xde\\xb3\\xfa\\xaa\\x00\\xcd\\xb6i4\\xfd\\x9c\\xc7\\xbfr\\x86\\xab\\xcd\\xb5mmee\\x9aR\\xae9\\xae\\xe5I\\xac\\xad\\xb1\\xb5\\x16\\xce\\xcc\\xc7\\x18A4\\x83\\x00\\x8d@\\xa8\\xf5\\xf1\\xa1\\x16\\xb8c2\\x92\\xc4\\xe4\\xe0\\xd7D|\\xf2\\xeb%)\\xd7\\x10E\\xb6zXt\\xb46\\xb0.X`\\xbc\\x88\\xa0\\x80{\\x87\\xd6\\xaa\\xdbL\\xb0\\xd9[\\xaa\\x1e\\xa8\\x1d\\xa7\\xb7<hzu&PY\\xb3\\x93\\x8a\\x96\\x1b\\xb7X^68LesT~j\\xb8\\x10\\xf4i\\xf4:\\xd8\\xf6\\xa2K\\x91;1tU\\xd4\\x80\\xc7\\xac\\x02xvV\\xa4\\xfaup\\xd2?\\xb0G\\xfa\\xaf4\\xb2\\xbd\\xb8\\xb6}\\xe42\\xc8\\x87\\xd6\\x1b\\x14[e\\xb6\\xd6\\xe6\\xc8\\xcf;"\\xb4|\\x1b.r{\\xc0\\xef\\xa9\\xcb\\xcd\\xa3v)1^\\xdc\\xc3g\\xb4g\\x12C\\x13$\\xea5o\\x10\\xe5\\xb9pQ\\xe0>\\xb5\\xa3p\\x96\\x97W\\x9b8\\x94h\\xd9OQ\\x15I\\x19\\xf4\\xb1\\xc3\\xd8\\x7fz\\x19\\xba\\xe9(k\\xf8\\xe4Xt\\xa4k\\x81\\x96\\xc9\\\'=\\xbe\\xaa\\x92\\xebn\\x19V!m)I\\xd32\\x17^\\x188\\xc6\\x07\\xae\\x8dr\\xb4Wdq\\x0e\\xb0\\xba\\\\p\\xce\\xa1\\xf7d~\\xd50\\x1d^\\xdf\\x93B;7\\xa4\\xfb\\xd4Xn\\xd0\\x07b<\\xe6\\xa2\\x06{\\xc5\\x12\\t2\\xbe\\x94\\x1f4\\xd4\\xa5\\x07\\x17\\xd1\\x13O\\xe1i3\\x8eM\\xe1\\rw\\xad\\xea\\x7f\\x92*\\xa2I\\xcf\\x8c?\\x19\\xae\\xef\\x07\\xae\\x1f\\x8d\\xa9hc\\xcb\\xb6\\x9e\\xd17wO.\\x97\\xd2N\\x14\\xb7\\xab\\xb0U\\x03/X\\x11\\xc3\\x07\\x95N\\xb03\\x8e\\xa8\\xf1\\x15Q\\x94\\xa4\\x85X`\\x83]\\xe9Q\\xcb\\xf4\\x9es\\x96\\xd4=\\xb4\\xc6\\xc1\\x07\\x87:p\\xeb\\x0f\\nk\\x8cb\\x99\\x18M\\x9c&s\\xc0vT\\x91\\xb8\\x00\\xaey\\xf2\\x15]\\xcfT*\\xd3W*\\x03\\x8fH\\x1eT&\\x14>U,Kg\\x95v1\\xe7\\x15\\x81\\xc6k\\xa2@_R\\x9e\\x04\\xd78g\\x99\\x03\\x14\\xdc\\x02\\xc6\\xf0\\xc7(\\xc0\\xcf\\x1a:\\xe8\\xe5\\xd3\\xdcX\\x18\\xf2\\xee\\xf0\\xf0\\xe6=\\x1e\\xce~>\\xea\\xf3\\xb9\\x8e\\xa7^$p\\xf6Q\\x17D\\xf7\\xa2\\xf9\\xd5\\xd8:n\\x89\\xc1]]\\xa3\\x15/Uq\\x1e\\x1ca\\xd2\\x89\\\\z\\x12\\x1f\\x15\\x14\\xb4M\\xf9r|B\\xab(O\\xcbC\\xfd\\xa3\\xf5\\xa5\\xd4\\xfc\\xb8\\xfeI\\xfa\\xd7\\x11\\xd2\\x0b\\xdb\\xf4[io\\xc2\\x91\\x10\\x8bV\\x0b\\xef\\x178\\xf5\\xe3>\\xaa%^\\x88l\\x9b\\xbb3\\x1d\\xd24R\\x02<\\xe4L5\\x9f\\x1c\\x1c\\xf2\\xff\\x00\\xca\\xab\\x1e\\xd0\\xd9\\xa5@\\xfe#v\\x879$:\\x81\\xfb\\xa9\\xff\\x005r\\xcf\\xa4{2\\xceF\\x02y\\xe6N\\xc6r\\xa5\\xb9xWKl\\x95$\\xa9"\\x9d\\xef@\\xf6tvR\\xbd\\x95\\xd5\\xd6\\xfdW\\xa8\\\'e\\x0b\\x9e\\xfe\\xa8\\xa1{\\x9e\\x88\\xedX\\xe2\\xde\\x95\\x81\\x94\\x0c\\xe0J2h\\xee\\xf7\\xa5\\x1b:\\xfe\\xceXa\\x9d\\xa0\\x90\\xe3\\x0c\\xe5Go\\xf5VB\\xce\\x85\\x1d_i+\\xc6\\xdd\\x82T\\xfa\\x8f\\xf3FrA\\xad?\\xa0\\x84\\x1b2X\\xcbo\\xd0\\x07\\xcf\\x05,8U[\\xabi\\x92\\xe5\\x90F\\xe0p\\xe0\\x06E\\x15\\\\E\\x10q\\xba\\x93X\\xc6\\x0e\\x93\\x91\\xfbUi"\\x8fI.H\\x1d\\xe7\\x15\\x9bZc\\xe9\\x8dY\\x87\\x06\\xcfGRCJs\\xf8q\\x8a\\xbdo\\xb2\\x8a\\xb1\\xd1\\x06\\xf8\\x11\\xc4H\\xb9\\xc7\\xb3\\x15\\xb5o}c\\x15\\xb0\\x84l\\xfbf\\xc3j\\xd7\\xbc\\xc3r\\xc70yc\\x15\\xdf\\xe2\\x16?\\xc8\\xc6?\\xed\\xb7\\xd6\\x9b6OX\\x1d=\\x8d\\xc4R\\x9dQ\\x1d\\x00\\xe0\\x1cp\\xad\\xbe\\x89\\xcd\\xb9\\xdaRC#\\x0c\\xbcd)$\\xaf#\\xca\\xb5\\xbc\\xbe\\xc4+\\x05\\xb1\\x83,0\\x19\\xaeY\\xb1\\xde2i\\x9b.\\xdd#\\xbd\\xb8\\xbaOE\\xb1\\xbb*\\xc0\\xe3#\\xad\\xfb\\xd1)\\xdah\\x14\\x1a\\x08\\x12@\\x07\\xda/\\xcd"\\xbb\\xbc\\x1f\\x98>y\\xa8\\x16w\\x03\\xd3\\x7frS\\x8c\\xaf\\x9fNO\\x85+\\x9a\\x8b\\x01^S1\\xfb\\xc7\\xf8\\x8dunf\\xce7\\xaf\\xf1\\x1aT\\xabYq\\xc2\\xea|c}&?\\xa8\\xd7|\\xae|\\x9f:\\xfc\\xbf\\x11\\xa5J\\xb0\\x07\\x9b\\xab\\x8cg\\x7f/\\xc6i-\\xed\\xd7/)\\x9b\\xe34\\xa9V\\x00\\xe1\\xb4/\\x07+\\xb9\\xc7\\xb2C]]\\xa5zNM\\xcc\\xa7\\xda\\xd9\\xa5J\\xb4\\xda\\x1c6\\x85\\xcbqi2{\\xc0\\xab\\xf672M\\x01y4\\xb3j#\\xd1\\x14\\xa9V!\\\'\\xf0\\xb5\\xbc\\xe1\\xe8\\\'\\xba\\xb8g\\xe3\\xf6Q\\xfb\\xa9R\\xa6"\\x7f\\xff\\xd9\'))', '(photoSize (ID: 0x77bfb61b) = (type=m, location=(fileLocation (ID: 0x53d69076) = (dc_id=4, volume_id=430531531, local_id=111834, secret=-840546536578932866)), w=320, h=242, size=21695))', '(photoSize (ID: 0x77bfb61b) = (type=x, location=(fileLocation (ID: 0x53d69076) = (dc_id=4, volume_id=430531531, local_id=111832, secret=-2943408949814512901)), w=429, h=325, size=28828))']))`

how can I download the media? what is the url?

**Comment by Lonami** [comment]
There is no url. If you have the `photo` you should be able to use `download_photo` on the `TelegramClient.py`.

**Comment by mar02500** [comment]
thanks @Lonami  
I have another question, is this part of code true?

` if not msg.media == None:

                self.client.download_msg_media(msg.media, "home/negin/media/")`

if the message media attribute is not null, it should download that media. but the folder is still empty after running this

**Comment by Lonami** [comment]
> but the folder is still empty after running this

Do you get `InvalidDCError`'s? That's being worked on another branch, but currently I don't have the time for it so please be patient. Also thanks for spotting that comparison to `None`, it should be `if msg.media is not None`.

**Comment by mar02500** [comment]
ok thanks @Lonami

**Comment by Lonami** [comment]
> Also thanks for spotting that comparison to `None`, it should be if `msg.media is not None`.

I thought that was part from Telethon but it's not. You should replace:
```python
if not msg.media == None:
```

with:

```python
if msg.media is not None:
```

Not only because it reads better, but because it's the right way to do it.

**Comment by mar02500** [comment]
it works now! thanks

**Comment by dmitrdv** [comment]
for me webpage preview photo could be download in following way:

messages = telegram.get_message_history(channel)
location = messages[1][0].media.webpage.photo.sizes[0].location
inputFileLocation = InputFileLocation(
                volume_id=location.volume_id,
                local_id=location.local_id,
                secret=location.secret
            )

file = telegram.download_file(inputFileLocation, 'aaa.jpg')

**Comment by orkenstein** [comment]
@Lonami what might be wrong in this snippet?
```python
from telethon import TelegramClient
import getpass
from telethon.errors import SessionPasswordNeededError
from telethon.tl.types import UpdateNewChannelMessage, Message, InputPeerChat, InputPeerChannel
from telethon.tl.functions.messages import ForwardMessagesRequest

def replier(update):
            media = update.message.media
            if media is not None:
                print("Will download image")
                print(media)                                // The last output I get
                download_res = client.download_msg_media(
                    media, '/Users/<user>/Development/TelegramFun')
                print("Download done: {}".format(download_res))

// create client and add updater here
```
No sign of download...

**Comment by orkenstein** [comment]
@mar02500 were you able to download media?

**Comment by msnannaware** [comment]
how did you download messages telegram messages. can you send the code to download txt messages?

**Comment by idontknowanything1** [comment]
hi,i dont know anything about coding . but i want to download media from a particular channel . 

my status is , i have installed telethon and created a client succesfully with help of tutorials

i request some one to kindly give me a ready to deploy command so that i only need to change the n=channel name.

**Comment by Kyle2142** [comment]
@idontknowanything1 I am sure you could pay someone to write code for you. This is not an issue with telethon so please don't hijack this issue

**Comment by snowman** [comment]
how to download photos when media has multiple photos

**Comment by SarvarRaxmonov** [comment]
@snowman, to download multiple images from a post, you can use this method. 

<img width="759" alt="Image" src="https://github.com/user-attachments/assets/ba2323c9-9cbd-4bca-8373-eba8fed62685" />

**But remember: do not filter by message type, because every photo is also a message in Telegram. If you filter for text, you will only get the first image from multiple attached photos in the post.**
