### ISSUE TITLE
error in async_generator

### ISSUE THREAD

**Issue by ahmadsl** [LonamiWebs/Telethon#925]
when i get an iterator on messages, after reading some message from a chat, i get below error:

`RuntimeError: partially-exhausted async_generator 'iter_messages' garbage collected`

why? how can solve this?

**Comment by ahmadsl** [comment]
anyone doesn't have idea?

**Comment by Lonami** [comment]
https://github.com/python-trio/async_generator/issues/13

**Comment by ahmadsl** [comment]
i saw that link before. but i cant understand how can solve this problem!
can you say how solve in this case.

i know when reading a history of a chat, after read first message sent to that chat and reading history completed that error occur.

do you have any idea for this?

**Comment by Lonami** [comment]
If you don't `break` the error should not occur.

**Comment by ahmadsl** [comment]
after remove `break` the error not occur. but some time i want read messages in a period of time. for this goal i check time of message sent and if sent exit of time period i break the loop. how can do this without error!!?

**Comment by Lonami** [comment]
How to use `async_generator` is not an issue with the library and it does not belong here. Ask somewhere else.
