### ISSUE TITLE
when use  telegram  AddChatUserRequest  method  Error: '  Too many requests'

### ISSUE THREAD

**Issue by Huochengyan** [LonamiWebs/Telethon#929]
when use  telethon API  AddChatUserRequest  method   return   error: '  Too many requests'  
i do it once in 30~40 seconds
what should i do?

**Comment by Lonami** [comment]
You stop spamming and abusing Telegram's API.

**Comment by Huochengyan** [comment]
No, I didn't send spam. I just wanted to copy a group of people to my new group.

**Comment by Lonami** [comment]
Sorry, but most people use it to spam. Consider asking them to join instead. Limits are not public.
