### ISSUE TITLE
Sending back an auto-reply upon receiving messages

### ISSUE THREAD

**Issue by Foleosy** [LonamiWebs/Telethon#93]
Hi, sorry for asking another question here.

I am currently looking to send back an auto-reply upon receiving a message from another user, is it possible?

I have tried using "self.invoke(SendMessageRequest(peer=get_input_peer(entity),message=msg,random_id=msg_id,entities=entities,no_webpage=False))" in the update_handler, method in the interactive_telegram_client class, such that whenever it receives a message and prints it to screen, it also sends back the auto-reply.

However, since it is a static function, I do not have access to the client to use "self". Could you provide me any suggestions to work around this?

I have tried instantiating an entire new client (a bad choice), making the methods all non-static (bad choice again), and implementing an observer pattern (too complicated for my lousy python skills).

Just an update for the previous one, but I'm probably going to just my own encryption on the messaging since it's easier than working with Telegram secret chat..

Edit: Have added a [question on SO ](https://stackoverflow.com/questions/44125272/calling-non-static-methods-from-static-methods-with-use-of-self)about this

**Comment by Lonami** [comment]
As I answered on your SO question, since the `InteractiveClientExample` already uses `self.` to refer to the static update handler method, simply replace:

```python
@staticmethod
def update_handler(update_object):
```

with:

```python
def update_handler(self, update_object):
```

And it should work.

**Comment by Foleosy** [comment]
I'd reply on SO comments, but SO comments sucks so hard, so...

I changed the method definition to the non-static one, and added in 
```
entity = update_object.user_id
message = update_object.message
msg, entities = message, []
msg_id = utils.generate_random_long()
self.invoke(SendMessageRequest(peer=get_input_peer(entity),
       message=msg,random_id=msg_id,entities=entities,no_webpage=False))`
```
to obtain the various arguments for the request, and I get 

> 
 > Exception in thread UpdatesThread:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/ming/Documents/LiClipse Workspace/Telethon/telethon/network/mtproto_sender.py", line 447, in updates_thread_method
>     reader)
>   File "/home/ming/Documents/LiClipse Workspace/Telethon/telethon/network/mtproto_sender.py", line 259, in process_msg
>     return self.handle_update(msg_id, sequence, reader)
>   File "/home/ming/Documents/LiClipse Workspace/Telethon/telethon/network/mtproto_sender.py", line 272, in handle_update
>     handler(tlobject)
>   File "/home/ming/Documents/LiClipse Workspace/Telethon/telethon/interactive_telegram_client.py", line 282, in update_handler
>     message=msg,random_id=msg_id,entities=entities,no_webpage=False))
>   File "/home/ming/Documents/LiClipse Workspace/Telethon/telethon/telegram_client.py", line 169, in invoke
>     self.sender.send(request)
>   File "/home/ming/Documents/LiClipse Workspace/Telethon/telethon/network/mtproto_sender.py", line 127, in send
>     request.on_send(writer)
>   File "/home/ming/Documents/LiClipse Workspace/Telethon/telethon/tl/functions/messages/send_message.py", line 52, in on_send
>     self.peer.on_send(writer)
> AttributeError: 'NoneType' object has no attribute 'on_send'

**Comment by Foleosy** [comment]
Oh dear, apologies, I had forgotten to search this time. =/

**Comment by Lonami** [comment]
> ```python
> entity = update_object.user_id
> # …
> peer=get_input_peer(entity)
> ```

You cannot do that. `get_input_peer` can't work with integer values (`user_id`) because it needs more information (namely, `access_hash`), so it returns `None`. It should probably raise a better error.

So first retrieve the user per se, or store or somewhere to then look it up by its ID, or any other approach should work. But you need to pass an `User` to get the `InputUser` from that function.

**Comment by Foleosy** [comment]
Thanks, got it.

`dialogs, entities = self.get_dialogs(10)
 message = 'Received: ' + update_object.message #The reply message
 msg_id = utils.generate_random_long()
 self.invoke(SendMessageRequest(peer=get_input_peer(entities[0]),
        message=message,random_id=msg_id,entities=entities,no_webpage=False))`

Probably should check if the entities[0] is the one I'm looking for instead of just assuming it's the first aha

Thanks @Lonami ~

**Comment by Lonami** [comment]
> Probably should check if the entities[0] is the one I'm looking for instead of just assuming it's the first aha

Yes :)
