### ISSUE TITLE
Use InviteToChannelRequest and get banned

### ISSUE THREAD

**Issue by yangfangdev** [LonamiWebs/Telethon#933]
Hi, I just created a get my new phone number and register for a new account. Then I try to add my friend F (just F, not tons of people) to a supergroup G which I am not in. When calling the function for the first time, it shows 
ChatWriteForbiddenError: You can't write in this chat
I just ran the program again and I get banned and deleted:
UserDeactivatedError: The user has been deleted/deactivated
And I can no longer login to telegram. And it shows the phone number get banned. Any ideas?

**Comment by Lonami** [comment]
Don't use virtual phone numbers? Don't use that request? Ask your friend to join by themselves? Not an issue with the library.

**Comment by yangfangdev** [comment]
It's not a virtual phone number lol. I get the number with SIM card. I was testing the library tho. So basically you are saying people can't use that request to add people?

**Comment by Lonami** [comment]
I assumed you used a VoIP number because that's what most reports are about. See #824 for more discussion on this if you're interested. I have never had my phone banned, you should be able to write to the email addresses there to get it back.

**Comment by yangfangdev** [comment]
Thanks for the reply. Nah I know people use VoIP number sometime but not in my case. That's kinda weird cuz I just start using it and testing with some function for fun and get ban instantly. Kinda feeling sad about it hhh. Yep I will go ahead and check out the #824 to see it that helps. Just a quick question. I was trying to see how the InviteToChannelRequest is implemented in the library to see why I get banned. And I couldn't found it in the library. However, in the library it says: 
from telethon.tl.functions.messages import AddChatUserRequest
But I don't see the functions or messages folder in the library. Would you mind explain how that works for me. I really appreciate it.

**Comment by Lonami** [comment]
That code is not in the repository because it is generated from the `.tl` files under `telethon_generator/`, so you can clone and run `python3 setup.py gen` if you want to see it. It just makes the request to Telegram with no other fancy additions. Sorry you got banned, but that's just how Telegram handles limits and bans and whatnot, which is out of my control.

**Comment by yangfangdev** [comment]
I am fully understand. Thank you for your reply.

**Comment by SnaggerNetwork** [comment]
Hi Lonami,
Is it unsafe to use this api method InviteToChannelRequest if I am the channel owner?

Thanks.

**Comment by Lonami** [comment]
It is not unsafe, however, it poses a risk, as adding users is considered spam, and when people report the channel, Telegram can take action (even deleting the channel or the account).
