### ISSUE TITLE
Can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by lugiank** [LonamiWebs/Telethon#934]
After upgrading to latest version after a "gone offline" user Status Update this exception is raised:
can't subtract offset-naive and offset-aware datetimes

In version 1.0.4 (the version i used before upgrading) this problem was not present because it was used datetime.fromtimestamp(timestamp)

**Comment by Lonami** [comment]
Pretty sure https://github.com/LonamiWebs/Telethon/commit/7b22c72c3ebd386caa6ce4e71e27a061082a46f9 fixed it.
