### ISSUE TITLE
showing error on  from telethon import TelegramClient, sync

### ISSUE THREAD

**Issue by sundarrinsa** [LonamiWebs/Telethon#937]
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    from telethon import TelegramClient, sync
  File "C:\Python33\lib\site-packages\telethon\__init__.py", line 2, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "C:\Python33\lib\site-packages\telethon\telegram_bare_client.py", line 9, in <module>
    from . import version, utils
ImportError: cannot import name version

**Comment by sundarrinsa** [comment]
showing above erorr

**Comment by Lonami** [comment]
Python 3.3 is not supported. Use 3.4 or above for `telethon-sync`, and 3.5 or above for `telethon`.

**Comment by Lonami** [comment]
For people coming here again, `telethon-sync` was a mistake and **is no longer officially supported**. `telethon` is the only available, asynchronous package for Python 3.5.2.

**Comment by anonymous1894** [comment]
ImportError: cannot import name 'InteractiveTelegramClient' from 'telethon' (/data/data/com.termux/files/home/Telethon/telethon/__init__.py)

Getting this error
