### ISSUE TITLE
event.chat is None

### ISSUE THREAD

**Issue by Badiboy** [LonamiWebs/Telethon#938]
Python 3.5.3
Telethon 1.1.1 (async version)
Windows10 / Raspbian

After upgrading from 0.19 to 1.x in some cases (~10% of all incoming messages **in every chat**) has **event.chat == None**. At the same time **event.chat_id** has a correct value.

What's the reason of having chat == None and is it a correct behavior?

**Comment by Lonami** [comment]
It is correct behaviour. Use `get_chat()`. Properties no longer access the network. Read the changelog.
