### ISSUE TITLE
cant able to get channel participant list

### ISSUE THREAD

**Issue by sundarrinsa** [LonamiWebs/Telethon#940]
My code is below
from telethon import TelegramClient,sync
from telethon.tl.functions.contacts import ResolveUsernameRequest
from telethon.tl.functions.channels import GetAdminLogRequest
from telethon.tl.functions.channels import GetParticipantsRequest
from telethon.tl.types import ChannelParticipantsSearch
from telethon.tl.types import InputChannel
from telethon.tl.types import ChannelAdminLogEventsFilter
from telethon.tl.types import InputUserSelf
from telethon.tl.types import InputUser
from time import sleep
def get_channel_participants(channel, offset, batch_size):
    api_id = 12345
    api_hash = 'jvvjhvhcyucduyctuxxyu'
    client = TelegramClient('session_name', api_id, api_hash)
    client.start()
    all_participants = []
    while True:
        participants = client(GetParticipantsRequest(channel, ChannelParticipantsSearch(''), offset, batch_size,hash=0))
        if not participants.users:
            break
        all_participants.extend(participants.users)
        offset += len(participants.users)
        sleep(5)
    return all_participants

users = get_channel_participants('mysupergroup', 0, 100)
print(users)

**Comment by sundarrinsa** [comment]
showing [<telethon.tl.types.User object at 0x0000026034768710>, <telethon.tl.types.User object at 0x0000026034768828>]

**Comment by Lonami** [comment]
Hey, look, this place is not for me or anyone to answer your questions on how to use Python or the library. There's, in my opinion, good documentation on how to use the library, and there are plenty of resources online to learn Python. There are far better ways to do what you're doing, again in the documentation.
