### ISSUE TITLE
`file` with path string is not handled correctly

### ISSUE THREAD

**Issue by vzts** [LonamiWebs/Telethon#941]
From: https://github.com/LonamiWebs/Telethon/blob/master/telethon/client/uploads.py#L396

```python
if not isinstance(file, str):
            file_handle = await self.upload_file(
                file, progress_callback=progress_callback,
                use_cache=use_cache if allow_cache else None
            )
```
Currently the conditional branch in `_file_to_media()` has no way to resolve file specified with path string. Maybe the original intention was `if isinstance(file, str):`, but that seems to impair the code following.

**Comment by Lonami** [comment]
No, I'm pretty sure I intended `not isinstance` for the bot API file ID to be handled. Maybe that broke other things, though.
