### ISSUE TITLE
Start my app with Supervisor failed!

### ISSUE THREAD

**Issue by DreamerLeon** [LonamiWebs/Telethon#944]
Traceback (most recent call last):
  File "/mnt/telegram/app.py", line 25, in <module>
    client = TelegramClient(phone_number, api_id, api_hash, proxy=(socks.SOCKS5, '192.168.137.1', 1080))
  File "/mnt/telegram/venv/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 174, in __init__
    session = SQLiteSession(session)
  File "/mnt/telegram/venv/lib/python3.6/site-packages/telethon/sessions/sqlite.py", line 44, in __init__
    c = self._cursor()
  File "/mnt/telegram/venv/lib/python3.6/site-packages/telethon/sessions/sqlite.py", line 233, in _cursor
    check_same_thread=False)
sqlite3.OperationalError: unable to open database file

Use command is succeed!
why?

**Comment by Lonami** [comment]
No clue. Does the supervisor have access to such file? Use another session storage (this is in the docs)? Either way not an issue with the library.

**Comment by markolofsen** [comment]
@Lonami the same error

**Comment by Lonami** [comment]
@markolofsen the same answer

> not an issue with the library.

Everything works as intended. There is nothing the library can do if sqlite can't open the file, but you can not use sqlite.

**Comment by akash-rajput** [comment]
FYI this can happen if you deleted the sessions directory accidentally. Just create it again & it should work.
Actually the library can do something: **Check for the sqlite db directory exists**

**Comment by danydanay** [comment]
> FYI this can happen if you deleted the sessions directory accidentally. Just create it again & it should work.
> Actually the library can do something: **Check for the sqlite db directory exists**

Where?
