### ISSUE TITLE
Timout GetBotCallbackAnswerRequest

### ISSUE THREAD

**Issue by rezals00** [LonamiWebs/Telethon#945]
```python
client(GetBotCallbackAnswerRequest(client.get_entity('username'),message.id,data='data'))
```
`    return future.result()
  File "C:\Users\rezab\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\client\users.py", line 48, in __call__
    result = await future
telethon.errors.rpcbaseerrors.BotTimeout: Timeout`

Version : Latest ( i think) 
Telegram Sync

**Comment by Lonami** [comment]
Nothing I can do if the bot doesn't respond fast enough.

**Comment by rezals00** [comment]
in previous version i use client(GetBotCallbackAnswerRequest(),retries=1) 

in latest version how i can limit retry ?

**Comment by Lonami** [comment]
The meaning of retry is different so you could say it only "retries" once already.

**Comment by rezals00** [comment]
so....... 


by the way how can  you are answering so fast , it's not AI Right ?

**Comment by Lonami** [comment]
No, I'm not an AI (yet).
