### ISSUE TITLE
There is no current event loop in thread

### ISSUE THREAD

**Issue by rezals00** [LonamiWebs/Telethon#946]
i want to use threading to multi account use 
```python
from autoload import *

def Do(i):
	print("OK");
	client = TelegramClient(str(session),api_id,api_hash)
	client.connect()
	print("Telegram ID : "+str(client.get_me().id))
	print("Telegram Username : "+client.get_me().username)
	client.disconnect()
threads = []
for x in range(0,len(list)):
		now = data[x];
		if(x >  -1 and x < 5):
			a = threading.Thread(target=Do, args=(x,))
			threads.append(a)
for t in threads:
	t.start()
for t in threads:
	t.join()
print("Success")
``` 

if i run i got error like this 
`RuntimeError: There is no current event loop in thread 'Thread-1'
.....` 

but if Do Function like this 

```python
def Do(i):
	print("OK");
```

it's work  

Telethon : Latest  ( sync )

**Comment by Lonami** [comment]
> Latest ( sync )

No, that's not true. If you are using the `telethon-sync` package that error definitely won't occur.

**Comment by Lonami** [comment]
Either way, you probably should:
1. Create an asyncio loop in that thread and pass it to the client.
2. Create tasks instead creating threads (best option).
3. Install `telethon-sync` and uninstall `telethon`.

**Comment by rezals00** [comment]
ah sry i forgot install 'telethon-sync' after upgrading python

**Comment by rezals00** [comment]
thanks
