### ISSUE TITLE
handle msg too low and msg too high

### ISSUE THREAD

**Issue by light-rain** [LonamiWebs/Telethon#95]
Hi
Is there some way to handle msg too low and msg too high error?

I face these errors some times

**Comment by Lonami** [comment]
So I've been a while looking and although we already use [time offset](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/session.py#L56) when generating a new message ID, the synchronization is probably lost after a (possibly long) time. I've took a look to [all](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl) the available requests and there isn't a single one which mentions `time_offset` (and those who mention `offset` or `time` are not relevant).

Not sure how we could get the right offset again on login, or similar.

**Comment by Lonami** [comment]
Give it a go and let me know how well it works out?

**Comment by light-rain** [comment]
thank you
It should work but to help you I found this file might be useful
https://github.com/badoualy/kotlogram/blob/master/mtproto/src/main/kotlin/com/github/badoualy/telegram/mtproto/time/TimeOverlord.kt

I'll test it and let you know If I see error again

**Comment by Lonami** [comment]
Thanks for the link, I will take it into account before closing this issue.

**Comment by Lonami** [comment]
Actually I just realized I already take into account since I update the used `.session` which is unique per `MtProtoSender` so it already has the right time offset. Feel free to reopen if the workaround didn't work. I may have messed up with the time conversion from `id -> time`.
