### ISSUE TITLE
get channel that message forwarded from that

### ISSUE THREAD

**Issue by ahmadsl** [LonamiWebs/Telethon#954]
hi,
i want get info (title ,about, participant_count) and some recent messages from channels that a message forwarded from that to me.
how can do this?

**Comment by ahmadsl** [comment]
how can i do this?

**Comment by Lonami** [comment]
You can read the documentation.

**Comment by ahmadsl** [comment]
i'm confusing with documentation! with fwd_from  i get only channel_id. but for getting channel need access hash too!

**Comment by ahmadsl** [comment]
this link is empty.
https://github.com/LonamiWebs/Telethon/wiki/Retrieving-an-entity
maybe answer to my question was here!

**Comment by Lonami** [comment]
Documentation ≠ wiki. There is a link to the *documentation* in the `README`.
