### ISSUE TITLE
USERNAME_NOT_OCCUPIED

### ISSUE THREAD

**Issue by unkn19wn** [LonamiWebs/Telethon#96]
Hello 
i want to start a bot and i need InputUser	 or InputPeer for that bot
i tryed :
bot=client.invoke(ResolveUsernameRequest('n1_Robot'))
but i keep getting :
USERNAME_NOT_OCCUPIED

username exist

**Comment by Lonami** [comment]
I just tried this code and it works:
```python
from telethon import TelegramClient
from telethon.tl.functions.contacts import ResolveUsernameRequest

api_id, api_hash, phone   = 'values', 'omitted', 'for privacy'
client = TelegramClient('lonami', api_id, api_hash)
client.connect()

if not client.is_user_authorized():
    client.send_code_request(phone)
    client.sign_in(phone, input('Enter the code: '))

result = client.invoke(ResolveUsernameRequest('n1_Robot'))
client.disconnect()
```
What version are you using? Could you provide more code than only that alone?

**Comment by unkn19wn** [comment]
Fixed After Upgrade to version 0.9
i was using 0.6
Tnx
looking forward for donate page

**Comment by Lonami** [comment]
Okay, awesome.

> looking forward for donate page

I will set it up shortly. Thank you!

**Comment by Lonami** [comment]
@unkn19wn feel free to check https://lonamiwebs.github.io/donate or hit me up for more options ^_^
