### ISSUE TITLE
generate direct url link for each  media

### ISSUE THREAD

**Issue by alihossein** [LonamiWebs/Telethon#960]
Hi . is there any way to generate `direct URL` for each media (Video, Photo,...) by `Telethon`? 
for example [this link](https://cdn4.telesco.pe/file/k8bar65__N9CidSdIHILp-swvxCkIyq9snzoRYPE99n1XFslrchk2Gk8gGmKV1xM9xzDPGYbLPP6pgeMIT8bpNwQrYoQsjXo1xyp2yxVIjZv9yo4RWwy4caZUxqkFW120H3N3_5aktjl_OjX8xNs29zJnyTMMdE2rYh44lmG7ZvhGIzdR2Vh-ujsUQant7Ks12x0tQBMX6b6kGMndGTyPk-DTPNlRI1eMmHPxGMukTyZv-huUsk_1apu9-KWJQZMgzNPw7EoXaMP6SJGfDQ2n3BsQ0QdTIVjQER-fhRIzMS__73HvGAa4YbAp5MUg1AHuKrWCX_K07ROIbMRlwSpnA.mp4)

**Comment by Lonami** [comment]
Telegram API has no such thing.
