### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'users'

### ISSUE THREAD

**Issue by JasonStatham1** [LonamiWebs/Telethon#963]
```python

from telethon import TelegramClient
from telethon.tl.functions.channels import GetParticipantsRequest
from telethon.tl.types import ChannelParticipantsSearch

api_id = 
api_hash = 

offset = 0
limit = 10
all_participants = []
phone_number = 


client = TelegramClient('my_session2', api_id=api_id, api_hash=api_hash)

client.start()

channel = input("Name of group/channel")

while True:
    participants = client(GetParticipantsRequest(
        channel, ChannelParticipantsSearch(''), offset, limit, hash=0
    ))
    if not participants.users:
        break
    all_participants.extend(participants.users)
    offset += len(participants.users)
    print(offset)

thefile = open('users.txt', 'w')

for participant in all_participants:
    if str(participant.username) != 'None':
        thefile.write("%s\n" % participant.username)
```

I made the script that gets usersnames from a group, it works fine on my PC, however, when I try to run it on another PC, the error occurs:
if not participants.users:

> AttributeError: 'coroutine' object has no attribute 'users'
> sys:1: RuntimeWarning: coroutine 'UserMethods.__call__' was never awaited

UPD: I updated telethon (pip3 install --upgrade telethon) and now it doesn't work on my PC either. 
Is there something important I'm missing?

**Comment by JasonStatham1** [comment]
okay, the issue is closed

> from telethon import TelegramClient, sync

**Comment by Lonami** [comment]
I like self-solving issues. I had the `rtfm` label ready already ;)
