### ISSUE TITLE
How Do I Get List Of All Banned Users In Telegram Channel ? Pls Help 

### ISSUE THREAD

**Issue by cryptomagus** [LonamiWebs/Telethon#964]
Hi I Would Like To Ask For A Small Help :) 
How Do I Get List Of All Banned Users In A Telegram Channel And Then Automatically Unban Them Using API .

**Comment by Lonami** [comment]
Not the right place to ask, and you don't seem to have read the docs.

**Comment by cryptomagus** [comment]
pls help sir :-)
