### ISSUE TITLE
'GetFullUserRequest' object has no attribute 'about'

### ISSUE THREAD

**Issue by m3r3lin** [LonamiWebs/Telethon#968]
Retrieving full information
If you need to retrieve the bio, biography or about information for an user you should use GetFullUser:

from telethon.tl.functions.users import GetFullUserRequest

full = client(GetFullUserRequest(user))

 or even

full = client(GetFullUserRequest('username'))

bio = full.about

but i get this error:

'GetFullUserRequest' object has no attribute 'about'

**Comment by Lonami** [comment]
Not possible.

**Comment by m3r3lin** [comment]
What is not possible?
my code:
app=TelegramClient(session_name,api_id,api_hash)
app.connect()
my_user =app.get_me()
full_info=GetFullUserRequest(my_user)
print(full_info) //work
print(full_info.about) //'GetFullUserRequest' object has no attribute 'about'
