### ISSUE TITLE
Request code

### ISSUE THREAD

**Issue by Mfr12** [LonamiWebs/Telethon#969]
hi 
when telethon ask my phone number and i insert it it show me this error(before i insert the code):
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 60407 seconds is required

this is my code:

'''from telethon import TelegramClient

api_id = 123
api_hash = '123'

client = TelegramClient('Test', api_id, api_hash)
client.start()

client.send_message("@Something","How Are You?")'''

i use python 3.6.2 and latest version of Telethon.

**Comment by Lonami** [comment]
Not the place to ask.
