### ISSUE TITLE
Check if a channel is deleted

### ISSUE THREAD

**Issue by codhank** [LonamiWebs/Telethon#970]
Hi, this is not really an issue but I would to know if there is a way to "check" if a channel is active or suspended/deleted with Telethon ?

Input : channel id
output : deleted true or false

Thank you very much

**Comment by Lonami** [comment]
If it's not really an issue it doesn't belong here.

**Comment by codhank** [comment]
Ok, where ?

**Comment by Lonami** [comment]
[TelethonChat](t.me/telethonchat). Maybe if you had read the issue template…
