### ISSUE TITLE
Problem with sending messages by phone number

### ISSUE THREAD

**Issue by Mfr12** [LonamiWebs/Telethon#971]
I want to send a message for a contact that i had his phone number but it give an error that phone number format is incorrect.this is my code:

`from telethon import TelegramClient
from telethon.tl.types import PeerUser

api_id = 123456
api_hash = 'Something'

client = TelegramClient('Telethon', api_id, api_hash)
client.start()

contact = client.get_entity("+98XXXXXXXXXX")`

what should i do?
Note: Python version 3.6 and latest version of Telethon.

**Comment by Lonami** [comment]
You should have shown the error message.
