### ISSUE TITLE
Problem with sending messages by phone number

### ISSUE THREAD

**Issue by Mfr12** [LonamiWebs/Telethon#972]
I want to send a message for a contact that i had his phone number but it give an error that phone number format is incorrect.this is my code:

`from telethon import TelegramClient
from telethon.tl.types import PeerUser

api_id = 123456
api_hash = 'Something'

client = TelegramClient('Telethon', api_id, api_hash)
client.start()

contact = client.get_entity("+98XXXXXXXXXX")`

what should i do?
Note: Python version 3.6 and latest version of Telethon.

and this is the error:
Traceback (most recent call last):
  File "/Users/Mfr/Downloads/Theleton.py", line 11, in <module>
    contact = client._get_entity_from_string("+989121570992")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/client/users.py", line 360, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "+98XXXXXXX"

**Comment by Lonami** [comment]
Next time post an update to previous issues like #971. If it says that, +98xxx is probably not in your contacts.

**Comment by Lonami** [comment]
For what it's worth, I can't reproduce the issue.
