### ISSUE TITLE
Channel subscribers gets banned if added using Telethon API, How to Unban it?

### ISSUE THREAD

**Issue by adeelnoor** [LonamiWebs/Telethon#982]
I am using Telethon API for adding members to my channel from a group, But the users who have been added to my channel gets ban immediately after adding, So they are not added but gets banned.

How to unban them? using telethon API

Inviting them with: 

            client(EditBannedRequest(
                    channel, user, ChannelBannedRights(
                        until_date=datetime.datetime.now() + datetime.timedelta(minutes=1),
                        view_messages=True
                    )

              client(InviteToChannelRequest(
                    channel,
                    [ user ]
                ))

With some exceptions like:

            except UserNotMutualContactError as e:
            except UserPrivacyRestrictedError as e:
            except PeerFloodError as e:
            except FloodWaitError as e:

I am giving the rights:
            
             rights = ChannelAdminRights(
                                             change_info=False,
                                             post_messages=False,
                                             edit_messages=None,
                                             delete_messages=True,
                                             invite_users=True,
                                             pin_messages=True,
                                             ban_users=None,
                                             add_admins=True )
                               client(EditAdminRequest(channel, user, rights))
My channel recent action shows "Banned *username*"

The help would be really appreciated.
Thank you

**Comment by Lonami** [comment]
> How to unban them?

What part of "DON'T ASK QUESTIONS HERE." didn't you understand?

**Comment by adeelnoor** [comment]
Is it possible or not?

**Comment by Lonami** [comment]
**This place is not where you ask questions like that.**

**Comment by adeelnoor** [comment]
Then what is the place for asking question for Telethon API?

**Comment by Lonami** [comment]
Maybe read the [issue template](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE.md).
