### ISSUE TITLE
AttributeError: 'TelegramClient' object has no attribute 'invoke'

### ISSUE THREAD

**Issue by vhdm** [LonamiWebs/Telethon#984]
@Lonami 
hi, my code is
contact = InputPhoneContact(client_id=0, phone="+12345678", first_name="0000ABC", last_name="abc")
result =  client.invoke(ImportContactsRequest([contact], replace=True))

and  error is:

AttributeError: 'TelegramClient' object has no attribute 'invoke'

**Comment by Lonami** [comment]
Not a bug. Re-read the documentation.

**Comment by Lonami** [comment]
I made a edit to https://stackoverflow.com/a/49952974/4759433 assuming you got the code from there.
