### ISSUE TITLE
Can't detect new update if message has Russian or Polish special symbols.

### ISSUE THREAD

**Issue by kifukt** [LonamiWebs/Telethon#986]
Hello dear @Lonami,
Can't detect new update if message has Russian(like "абвг" ) or Polish special symbols (like ęąóżź).

My code is simple:
```
from telethon import TelegramClient, events
import asyncio

Client = TelegramClient('session_name', api_id, api_hash)

@client.on(events.Raw)
async def handler(event):
    print(event)

if __name__ == '__main__':
    client.start()
    client.run_until_disconnected()
```
When I send messages to this session in English, the output is:

> UpdateShortMessage(id=87, user_id=, message='eng text', pts=162, pts_count=1, date=datetime.datetime(2018, 9, 5, 11, 29, 49, tzinfo=datetime.timezone.utc), out=False, mentioned=False, media_unread=False, silent=False, fwd_from=None, via_bot_id=None, reply_to_msg_id=None, entities=[])

But if I send any message from any account in Russian or Polish nothing happens.

**Comment by Lonami** [comment]
Problem with your terminal. Enable logging, figure out the problem, or don't print the text.
