### ISSUE TITLE
endless repeat to telethon.network.mtprotosender:Receiving items from the network... help wanted

### ISSUE THREAD

**Issue by SPITIRU** [LonamiWebs/Telethon#988]
I'm trying AddChatUserRequest, and my app is freeze, logging write this:

`telegrambot_dc | DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) PingRequest...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Outgoing messages 6598374061266128636 sent!
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) PingRequest...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Sending 88 bytes...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Outgoing messages 6598374318988562336 sent!
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
telegrambot_dc | DEBUG:telethon.network.mtprotosender:Receiving items from the network...
`

function to invite user:
```
def invite_chennel_function(user_id, chat, chat_num, message):
    if not client.is_connected():
        client.client.connect()
    client(AddChatUserRequest(chat, user_id, 20))
    client.send_message(chat, "Приветствую в чате №" + chat_num + " Нового пользователя: " + message.chat.first_name)
```

main function:
```
try:
    invite_chennel_function(user_id, chat, chat_num, message)
    bot.send_message(message.chat.id, 'Вы были приглашены в чат № ' + chat_num)
# except StopIteration:
#     invite_chennel_function(user_id, chat, chat_num, message)
except UserAlreadyParticipantError:
    bot.send_message(message.chat.id, 'Вы уже зарегистрированы в чате № ' + chat_num)
except UserNotMutualContactError:
    link = client(ExportChatInviteRequest(chat)).link
    bot.send_message(message.chat.id, 'К сожалению мы не можем автоматически добавить Вас в чат\n'
                                      'Но вы можете воспользоваться ссылкой: ' + link)
except Exception as e:
    logging.error('Ошибка входа в чат: ' + str(e))
    logging.debug('Ошибка входа в чат: ' + str(e))
    link = client(ExportChatInviteRequest(chat)).link
    bot.send_message(message.chat.id, 'К сожалению мы не можем автоматически добавить Вас в чат\n'
                                      'Но вы можете попробовать воспользоваться ссылкой: ' + link)
```

**Comment by steeldimon** [comment]
after 9999 seconds it says in log:

`
INFO:telethon.client.updates:Got new state! State(pts=334, qts=0, date=datetime.datetime(2018, 9, 7, 7, 13, 59, tzinfo=datetime.timezone.utc), seq=1373, unread_count=49)
`

**Comment by singgi11** [comment]
Is there any solution for this problem? I also had the same problem

**Comment by Lonami** [comment]
@singgi11 there is no problem here. "Receiving items from the network" is the correct behaviour (that's why it's `DEBUG` and not `ERROR`).
