### ISSUE TITLE
Change the value of the "chats="

### ISSUE THREAD

**Issue by JakeBV** [LonamiWebs/Telethon#994]
Hi, I have a script:
`my_chat = '@xxx'

@client.on(events.NewMessage(chats=my_account, pattern='@', forwards=False))
async def handler(event):
    global my_chat
    my_chat = event.raw_text`

Here I send the meaning of another chat so that the bot responds to new messages from it.
The other part of the code.
`@client.on(events.NewMessage(chats=my_chat))
async def normal_handler(event):`

But the bot continues to respond to messages from the old chat and does not respond to messages from the new chat. Tell me, please, why?

**Comment by Lonami** [comment]
You cannot update the `chats` value once set. You should do the check inside the handler yourself and stop using `chats`.

**Comment by JakeBV** [comment]
Can you please tell me how to do the check inside the handler?
