### ISSUE TITLE
I can not get all channel members

### ISSUE THREAD

**Issue by Maxirus2** [LonamiWebs/Telethon#997]
**Here is my code:**
`from telethon import TelegramClient, sync
import xlwt

api_id = xxxxxx
api_hash = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
client = TelegramClient('+37529xxxxxxx', api_id, api_hash)
client.start()

print("Enter a name for the channel:");	
answer = input()
channel = client.get_entity(answer)
c = client.get_participants(channel, aggressive=True)
x = 0
wb = xlwt.Workbook()
ws = wb.add_sheet('A Test Sheet')
ws.write(0, 0, 'name')
ws.write(0, 1, 'surname')
ws.write(0, 2, 'nickname')

while x<len(c):
      ws.write(x+1, 0, c[x].first_name)
      ws.write(x+1, 1, c[x].last_name)
      ws.write(x+1, 2, "@"+str(c[x].username)) 
      x += 1

print(len(c));		
wb.save('example.xls') `

**The problem is that this code draws only 1424 users. When on channel 1505 users. What am I doing wrong?**

**Comment by Maxirus2** [comment]
![image](https://user-images.githubusercontent.com/26022218/45454569-0f009180-b6ed-11e8-8ffd-c95f3bd98657.png)
![image](https://user-images.githubusercontent.com/26022218/45454580-19bb2680-b6ed-11e8-9a5a-7081db1cc0bf.png)

**Comment by Maxirus2** [comment]
and such a problem with all channels!

**Comment by Lonami** [comment]
Telegram's server-side limit.
