### ISSUE TITLE
How to get session id of other active sessions?

### ISSUE THREAD

**Issue by EmadHelmi** [LonamiWebs/Telethon#999]
What is a session id? I Get a list of my sessions with GetAuthorizationsRequest() and get an answer like this:
```
{
                     '_': 'Authorization',
                     'api_id': ...,
                     'app_name': '...',
                     'app_version': '4.1.4',
                     'country': 'Unknown',
                     'date_active': ...,
                     'date_created': ...,
                     'device_model': 'SamsungSM-G920F',
                     'flags': 0,
                     'hash': ...,
                     'ip': '...',
                     'platform': 'Android',
                     'region': '',
                     'system_version': 'SDK 23'
}
```
which of these keys is the session id?
I tried to send a req with `client(DestroySessionRequest(hash))` or `client(DestroySessionRequest(apid_id))` but no response after about 15 or 20s even an error or exception. I want to destroy all other sessions except the session with which I am connect now.

**Comment by Lonami** [comment]
Questions dooooon't belong here.

**Comment by EmadHelmi** [comment]
@Lonami where should I ask my question and where can I found my answer? I checked [here](https://lonamiwebs.github.io/Telethon/methods/destroy_session.html) before create my issue but no answer found.

**Comment by Lonami** [comment]
There's a template when you create an issue that **you should read** with that information.

**Comment by EmadHelmi** [comment]
@Lonami I wnated to join your group which you mentioned in the issue template but there is no such group and when I check [the link](https://t.me/TelethonChat) I get user name @TelethonChat not found. Is there any new group ?

**Comment by Lonami** [comment]
No, but your account is probably restricted in some way (see [@SpamBot](https://t.me/spambot)).
